### ISSUE TITLE
--no-check introducing SyntaxError: Rest element must be last element

### ISSUE THREAD

**Issue by danopia** [denoland/deno#10167]
A trailing comma present inside a structure signature can get lifted out when stripping types under `--no-check`, which causes problems around rest params.

```
$ echo 'function myFunc({...data}: {field: string,}) {}' | deno run -
Check file:///private/var/folders/km/5sblvl2s717_5d42_5g1nk3h0000gp/T/tmp.Y4im4uBc/$deno$stdin.ts

$ echo 'function myFunc({...data}: {field: string,}) {}' | deno run --no-check -
error: Uncaught SyntaxError: Rest element must be last element
function myFunc({...data}: {field: string,}) {}
~~~~
    at <anonymous> (file:///private/var/folders/km/5sblvl2s717_5d42_5g1nk3h0000gp/T/tmp.Y4im4uBc/$deno$stdin.ts:1:1)

$ deno --version
deno 1.8.3 (release, x86_64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2
```

I've reported upstream here: https://github.com/swc-project/swc/issues/1573

This explains the error message itself, why the trailing comma is bad: https://stackoverflow.com/questions/58631487/syntax-error-rest-element-must-be-last-element

**Comment by danopia** [comment]
Looks like this also can crop up with `deno bundle`:

```
$ cat main.ts
export function myFunc({...data}: {
  field: string,
}) {}

$ deno bundle main.ts | tee main.js
Bundle file:///private/var/folders/km/5sblvl2s717_5d42_5g1nk3h0000gp/T/tmp.Y4im4uBc/main.ts
Check file:///private/var/folders/km/5sblvl2s717_5d42_5g1nk3h0000gp/T/tmp.Y4im4uBc/main.ts
function myFunc1({ ...data,  }) {
}
export { myFunc1 as myFunc };

$ deno run main.js
error: Uncaught SyntaxError: Rest element must be last element
function myFunc1({ ...data,  }) {
                      ~~~~
    at <anonymous> (file:///private/var/folders/km/5sblvl2s717_5d42_5g1nk3h0000gp/T/tmp.Y4im4uBc/main.js:1:23)
```

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by kdy1** [comment]
Fixed on upstream.
