### ISSUE TITLE
Deno 1.9.0, Uncaught InvalidData: invalid url scheme

### ISSUE THREAD

**Issue by FSou1** [denoland/deno#10170]
I have recently published a library: https://deno.land/x/fsquery/mod.ts

Now I'm trying to test it:

```
import { fsselect } from 'https://deno.land/x/fsquery/mod.ts';

await fsselect("select * from .");
```

Unfortunately, I receive the error:
```
error: Uncaught InvalidData: invalid url scheme
    throw new Deno.errors.InvalidData("invalid url scheme");
          ^
    at fileURLToPath (https://deno.land/std@0.92.0/node/url.ts:53:11)
    at createRequire (https://deno.land/std@0.92.0/node/module.ts:535:18)
    at https://deno.land/x/fsquery@deno-module-0.1/parser.ts:3:17
```

**Comment by lucacasonato** [comment]
`createRequire` can only be used from `file` modules. We should improve the error message here.
