### ISSUE TITLE
Multipart Reader fails when compiled with error: ReferenceError: matchAfterPrefix is not defined

### ISSUE THREAD

**Issue by vinc3m1** [denoland/deno#10187]
from: https://github.com/denoland/deno/issues/9620#issuecomment-809747601

While #9620 was fixed for the `--no-check` case, the `compile --unstable` case is still broken using the test script linked to in https://github.com/denoland/deno/issues/9620#issuecomment-787210444:
```
$ deno compile --unstable test.ts
[...]
Emit test
$ ./test
error: ReferenceError: matchAfterPrefix is not defined
    at scanUntilBoundary (file://$deno$/bundle.js:1702:9)
    at PartReader.read (file://$deno$/bundle.js:1737:22)
    at async copyN (file://$deno$/bundle.js:107:24)
    at async MultipartReader.readForm (file://$deno$/bundle.js:1825:27)
    at async file://$deno$/bundle.js:2095:18
```

But running with --no-check passes now so that's good:
```
$ deno run --no-check test.ts
entry [ "payload", "CONTENT" ]
formdata {
  file: [Function: file],
  value: [Function: value],
  entries: [GeneratorFunction: entries],
  removeAll: [AsyncFunction: removeAll],
  [Symbol(Symbol.iterator)]: [Function: [Symbol.iterator]]
}
```

`test.ts`:
```typescript
import { MultipartReader } from "https://deno.land/std@0.93.0/mime/multipart.ts";
import { StringReader } from "https://deno.land/std@0.93.0/io/readers.ts";

// carriage returns added for running on POSIX, not needed if on windows
const content = `--------------------------366796e1c748a2fb\r
Content-Disposition: form-data; name="payload"\r
Content-Type: text/plain\r
\r
CONTENT\r
--------------------------366796e1c748a2fb--`

const boundary = "------------------------366796e1c748a2fb";

const stringReader = new StringReader(content);

const multipartReader = new MultipartReader(stringReader, boundary);
const formData = await multipartReader.readForm()
for (const entry of formData.entries()) {
  console.log("entry", entry);
}
console.log("formdata", formData);
```

**Comment by nayeemrmn** [comment]
What happens when you run on Deno 1.9.0 and std 0.93.0?

**Comment by vinc3m1** [comment]
> What happens when you run on Deno 1.9.0 and std 0.93.0?

Just tested on `deno 1.9.0 (release, aarch64-apple-darwin)`, still the same error output when `compile`d, just different line numbers.

**Comment by nayeemrmn** [comment]
cc @kdy1. Looks like the `matchAfterPrefix()` function is wrongly removed from https://deno.land/std@0.93.0/mime/multipart.ts during DCE when bundling the above code.

**Comment by kdy1** [comment]
I fixed it and published a new version :)

**Comment by satyarohith** [comment]
This issue no longer exists with `1.9.2`.
