### ISSUE TITLE
ReferenceError: KubectlRawRestClient is not defined

### ISSUE THREAD

**Issue by kodeninja** [denoland/deno#10218]
This is a simple script that deletes Kubernetes jobs older than a certain no of days/hours. It runs fine via `deno run`, but fails with the below error when run via the binary generated with `deno compile`.

I'm leveraging https://deno.land/x/kubernetes_client@v0.2.1/mod.ts for kubernetes support.

```bash
$ exa --tree
.
├── delete_jobs
│  ├── deps.ts
│  ├── mod.ts
├── deps.ts
├── mod.ts
└── README.md
```

```bash
$ deno --version 
deno 1.9.0 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2

$ deno compile --output deno-k8s-scripts-macos --target x86_64-apple-darwin --unstable --allow-all --no-check mod.ts

Bundle file:///~/deno-k8s-scripts/mod.ts
Compile file:///~/deno-k8s-scripts/mod.ts
Archive:  /var/folders/rd/qfcjlzzj7_bd27tvc1cdwv9w0000gp/T/.tmptTSBH8/deno..zip
  inflating: deno                    
Emit deno-k8s-scripts-macos
```

```bash
$ ./deno-k8s-scripts-macos --action=deleteJobsOlderThanHours --namespace=<namespace> --olderThan=18 --dryRun --verbose

Detecting kubernetes client...
error: ReferenceError: KubectlRawRestClient is not defined
    at deleteJobsOlderThanHours (file://$deno$/bundle.js:4531:24)
    at main (file://$deno$/bundle.js:4610:19)
    at file://$deno$/bundle.js:4627:1
```

Running the same as a script works:

```bash
$ deno run --allow-all --unstable --no-check mod.ts --action=deleteJobsOlderThanHours --namespace=test --olderThan=18 --dryRun --verbose

Detecting kubernetes client...
Finding jobs older than 18 hours...
GET /apis/batch/v1/namespaces/test/jobs 
$ kubectl get --raw /apis/batch/v1/namespaces/test/jobs 
Jobs to be deleted: 0
Dry run mode is on. Exiting.
```

It seems `deno compile` is not bundling the deps in `delete_jobs/deps.ts`?

```bash
$ cat delete_jobs/deps.ts 
export * from 'https://deno.land/x/kubernetes_client@v0.2.1/mod.ts';

$ cat delete_jobs/mod.ts
import { KubectlRawRestClient } from './deps.ts';

export async function deleteJobsOlderThanDays(namespace: string, olderThanDays: number, options: any) {
...

$ cat mod.ts
import { parse } from './deps.ts';
import {deleteJobsOlderThanHours, deleteJobsOlderThanDays} from './delete_jobs/mod.ts';

const validActions = ["deleteJobsOlderThanHours", "deleteJobsOlderThanDays"];
...
```

Maybe my project structure is not correct, or perhaps there's a way to specify the top-level `mod.ts` _and_ `delete_jobs/*` in the `deno compile ...` step?

**Comment by nktpro** [comment]
It's likely that you ran into this issue https://github.com/denoland/deno/issues/10174

We'll have to wait until the next release after deno upgrades `swc`.
