### ISSUE TITLE
Panic on uncaught error with invalid utf8 string

### ISSUE THREAD

**Issue by janispritzkau** [denoland/deno#10217]
This will cause rust to panic in Deno 1.9.0 if run as a script:

```js
JSON.parse(new TextDecoder().decode(new Uint8Array([13, 137])))
```

The crash log with backtrace:

```
$ RUST_BACKTRACE=1 deno run crash.js 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExpectedUtf8', core/error.rs:190:52
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: deno_core::error::JsError::from_v8_exception
   4: deno_core::runtime::exception_to_err_result
   5: deno_core::runtime::JsRuntime::poll_event_loop
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

My guess is that a bug in the TextDecoder creates an invalid string, which then triggers a v8 exception on JSON.parse.

**Comment by janispritzkau** [comment]
What I find weird is that this doesn't happen in the repl.

**Comment by bwac2517** [comment]
Same happens here

**Comment by janispritzkau** [comment]
Actually, the error has nothing to do with `JSON.parse`. Here is a simpler panic reproduction:

```
throw new Error(new TextDecoder().decode(new Uint8Array([255])))
```

Also, the panic only happens if you don't catch the error in javascript. If you simply log the error, nothing happens. That must also be why the repl didn't panic.
