### ISSUE TITLE
TypeError: Cannot read property 'rid' of undefined

### ISSUE THREAD

**Issue by nikolalukovic** [denoland/deno#10234]
```
const { writeSync } = Deno.stdout;

const { encode } = new TextEncoder();

Deno.test("writeSync closure test", () => {
    writeSync(encode("bla bla bla"));
});
```

When running above-mentioned code with:
```
deno 1.9.0 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```
I get this error:

```
Check file:///Users/nikola/Projects/deno_test/$deno$test.ts
running 1 tests
test stdout closure test ... FAILED (3ms)

failures:

stdout closure test
TypeError: Cannot read property 'rid' of undefined
    at writeSync (deno:runtime/js/40_files.js:162:29)
    at file:///Users/nikola/Projects/deno_test/test.ts:6:5
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:37:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:73:13)
    at Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:100:15)
    at TestRunner.[Symbol.asyncIterator] (deno:runtime/js/40_testing.js:272:24)
    at AsyncGenerator.next (<anonymous>)
    at Object.runTests (deno:runtime/js/40_testing.js:347:22)
    at async file:///Users/nikola/Projects/deno_test/$deno$test.ts:3:1

failures:

        stdout closure test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (3ms)
```

Now considering I yoink `writeSync` from `stdout` and place it in a test closure to be ran later I'm not even sure if this is a bug or some low level shenanigans I know nothing about and this works as it should.

**Comment by nayeemrmn** [comment]
You can't destructure `writeSync` out of `Deno.stdout`, this is more or less expected.

**Comment by kitsonk** [comment]
This is standard behaviour of JavaScript methods, they are bound to the context of their instance.

**Comment by nikolalukovic** [comment]
OK cool, thanks for a quick response.
