### ISSUE TITLE
Support for Named Pipes in Deno.connect

### ISSUE THREAD

**Issue by DjDeveloperr** [denoland/deno#10244]
Currently, `Deno.connect` only supports IPC for unix (using unstable `transport: "unix"`). There should be named pipes support too, which would allow IPC on Windows (as NodeJS' `net` mode does).

**Comment by DjDeveloperr** [comment]
I wasn't aware Windows supports AF_UNIX, but `transport: "unix"` doesn't seem to work at all in Windows (I'm on Windows 10). I tried it with both existent named pipe, file, and a non-existent path, all I got is:
```
Uncaught TypeError: Error parsing args: data did not match any variant of untagged enum ArgsEnum
    at unwrapOpResult (deno:core/core.js:100:13)
    at Object.opAsync (deno:core/core.js:109:28)
    at Object.opConnect (deno:runtime/js/30_net.js:22:17)
    at Object.connect (deno:runtime/js/40_net_unstable.js:37:29)
    at <anonymous>:2:23
```
but it shows correct error on WSL when I try to connect:
```
Uncaught NotFound: No such file or directory (os error 2)
    at unwrapOpResult (deno:core/core.js:100:13)
    at async Object.connect (deno:runtime/js/40_net_unstable.js:37:19)
    at async <anonymous>:2:12
```

**Comment by jimboyeah** [comment]
fallback to TCPIP

**Comment by DjDeveloperr** [comment]
> 
> 
> fallback to TCPIP

The application I'm trying to interact through named pipes does not support that.

**Comment by lucacasonato** [comment]
Tokio supports named pipes now, so this should be unblocked: https://github.com/tokio-rs/tokio/releases/tag/tokio-1.7.0

**Comment by DjDeveloperr** [comment]
> Tokio supports named pipes now, so this should be unblocked: https://github.com/tokio-rs/tokio/releases/tag/tokio-1.7.0

Would a PR be welcome to add new transport for named pipes? I'm going to give this a try

**Comment by fushihara** [comment]
What do I have to wait for to get this problem resolved?

I'm not sure if the term “named pipe” is correct, but anyway, there should have always been an equivalent to named pipes in windows.
If you are a windows user, you can use googleChrome's address field file://. //pipe// in the address field of googleChrome to see a list of existing pipes.

**Comment by cyans-nya** [comment]
I am working on a PR https://github.com/denoland/deno/pull/29308 that supports Named Pipe via `Deno.pipe`.

I am asking for any Windows user to test if the the named pipe actually works. If you are interested in, and have necessary dev environment, you can found me on Deno Discord (same id) to help me test the pr on Windows. Thanks

EDIT: It's unlikely to introduce a new API like `Deno.pipe` in Deno
