### ISSUE TITLE
respond to http request from onmessage

### ISSUE THREAD

**Issue by alexanderGalushka** [denoland/deno#10251]
deno: 1.9.0

responding to http request from onmessage (response from worker) in the main thread

getting this error:

```
error: Uncaught (in promise) BadResource: Bad resource ID
          numBytesWritten = await this.writer.write(data);
                            ^
    at unwrapOpResult (deno:core/core.js:100:13)
    at async write (deno:runtime/js/12_io.js:107:12)
    at async BufWriter.write (https://deno.land/std@0.93.0/io/bufio.ts:501:29)
    at async writeResponse (https://deno.land/std@0.93.0/http/_io.ts:275:15)
    at async ServerRequest.respond (https://deno.land/std@0.93.0/http/server.ts:87:7)
```

**Comment by kitsonk** [comment]
Could you please provide a more complete replication.

Did this same code work in previous versions of Deno?

**Comment by alexanderGalushka** [comment]
nvm, I had a race condition, closing issue
