### ISSUE TITLE
Deno.serveHttp yields invalid Request.url values

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#10271]
I was trying out the new http server and discovered a bug today:

For each [`Deno.RequestEvent`](https://doc.deno.land/builtin/unstable#Deno.RequestEvent) yielded by [`Deno.serveHttp`](https://doc.deno.land/builtin/unstable#Deno.serveHttp), the value of `requestEvent.request.url` is not a valid URL. It is only a pathname. See the reproduction case below:

### Reproduce:

`example.ts`:
```ts
async function handleConnection(conn: Deno.Conn<Deno.NetAddr>) {
  for await (const { request, respondWith } of Deno.serveHttp(conn)) {
    console.log("URL provided by Deno.serveHttp:", request.url);
    try {
      request.clone(); // ⚠️ Throws
      respondWith(new Response("Response successfully cloned"));
    } catch (ex) {
      respondWith(new Response(ex.toString(), { status: 500 }));
      throw ex;
    }
  }
}

async function main() {
  const url = new URL("http://localhost:8000/");
  console.log(
    "URL of manually constructed request:",
    new Request(url.href).url,
  );
  await Deno.permissions.request({ name: "net", host: url.host });

  const server = Deno.listen({
    hostname: url.hostname,
    port: parseInt(url.port, 10),
  });

  console.log(`Listening at ${url.href}\nUse ctrl+c to stop`);
  for await (const conn of server) handleConnection(conn);
}

if (import.meta.main) main();
```

1. Start server:
```
% deno --unstable run main.ts
URL of manually constructed request: http://localhost:8000/
⚠️  ️Deno requests network access to "localhost:8000". Grant? [g/d (g = grant, d = deny)] g
Listening at http://localhost:8000/
Use ctrl+c to stop
```

2. Navigate to http://localhost:8000/ in a browser. Switch back to terminal.
3. An exception was thrown. More in `stdout` and `stderr`:
```
URL provided by Deno.serveHttp: /
error: Uncaught (in promise) TypeError: Invalid URL
      request.clone(); // ⚠️ Throws
              ^
    at unwrapOpResult (deno:core/core.js:100:13)
    at Object.opSync (deno:core/core.js:114:12)
    at new URL (deno:op_crates/url/00_url.js:209:30)
    at new Request (deno:op_crates/fetch/26_fetch.js:1049:15)
    at Request.clone (deno:op_crates/fetch/26_fetch.js:1080:14)
    at handleConnection (file:///Users/jesse/example/example.ts:5:15)
```

### Version

```
% deno --version
deno 1.9.0 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```

**Comment by nayeemrmn** [comment]
Already fixed by #10256.
