### ISSUE TITLE
Request.[Deno.customInspect] throws TypeError: this.url is not a function

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#10334]
See example and link to source below.

`example.ts`:
```ts
const r = new Request('https://example.com');
console.log(r);
```

```
% deno run example.ts
error: Uncaught TypeError: this.url is not a function
console.log(r);
        ^
    at Request.[Deno.customInspect] (deno:op_crates/fetch/23_request.js:395:19)
    at inspectObject (deno:op_crates/console/02_console.js:925:50)
    at inspectValue (deno:op_crates/console/02_console.js:481:16)
    at inspectArgs (deno:op_crates/console/02_console.js:1454:19)
    at console.log (deno:op_crates/console/02_console.js:1504:9)
    at file:///Users/jesse/example/example.ts:2:9

% deno --version
deno 1.9.2 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```

https://github.com/denoland/deno/blob/2400ecbe16775b54ccd9782119b09b00e3b0e786/op_crates/fetch/23_request.js#L389-L398

**Comment by AaronO** [comment]
Thought I had searched for that pattern in #10295 🤦‍♂️

**Comment by helloworldless** [comment]
For what it's worth, this seems to have broken from 1.9.0 to 1.9.1. I downgraded to 1.9.0 for now.
