### ISSUE TITLE
Cloning a request with an additional property throws an unrelated error in 1.9.2 – 1.10.2

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno#10355]
Note this only happens when the source request is in the `RequestInit` position (see below).

I found #10286, but this situation really has nothing to do with `request.cache`, the clone should succeed, and later throw if and only if cache is accessed.

This did not throw in 1.9.0.

```
deno 1.9.2 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```

```typescript
// tmp.ts
const port = parseInt(Deno.args[0]);
const listener = Deno.listen({ port: port });

fetch(`http://localhost:${port}`).then(r => console.log(r)).catch(e => console.error(e));

for await (const conn of listener) {
    (async () => {
        for await (const { request, respondWith } of Deno.serveHttp(conn)) {
            (request as any).foo = true;
            // const reqCopy = new Request(request); // this succeeds
            const reqCopy = new Request(request.url, request); // this throws
            respondWith(new Response(`${reqCopy.url}`));
        }
    })();
}
```

`deno run --unstable --allow-net tmp.ts 3333`

```
error: Uncaught (in promise) TypeError: This property is not implemented.
            const reqCopy = new Request(request.url, request); // this throws
                            ^
    at Request.get cache (deno:op_crates/fetch/23_request.js:343:13)
    at Array.RequestInit (deno:op_crates/webidl/00_webidl.js:661:33)
    at new Request (deno:op_crates/fetch/23_request.js:198:46)
    at tmp.ts:11:29
```

**Comment by johnspurlock** [comment]
Still broken in 1.10.2 - different line in `23_request.js`, but same basic issue. 

```
deno 1.10.2 (release, x86_64-apple-darwin)
v8 9.1.269.27
typescript 4.2.2
```

```
error: Uncaught (in promise) TypeError: This property is not implemented.
            const reqCopy = new Request(request.url, request); // this throws
                            ^
    at Request.get cache (deno:extensions/fetch/23_request.js:346:13)
    at Array.RequestInit (deno:extensions/webidl/00_webidl.js:661:33)
    at new Request (deno:extensions/fetch/23_request.js:198:46)
    at tmp.ts:12:29
```

**Comment by kitsonk** [comment]
There is a reason why the issue is still open, because it isn't fixed.
