### ISSUE TITLE
Logging native server request events throws error

### ISSUE THREAD

**Issue by cmorten** [denoland/deno#10533]
Attempting to log the `Request` object from a native server http request event results in an error thrown from the request / console op_crates.

Taken from `v1.9` blog example with minor adjustment to expose and attempt to log the `request`:

```ts
const body = new TextEncoder().encode("Hello World");
for await (const conn of Deno.listen({ port: 4500 })) {
  (async () => {
    for await (const { request, respondWith } of Deno.serveHttp(conn)) {
      console.log(request); // 💥
      await respondWith(new Response(body));
    }
  })();
}
```

```console
$ deno run --unstable -A ./repro.ts
error: Uncaught (in promise) TypeError: this.url is not a function
      console.log(request);
              ^
    at Request.[Deno.customInspect] (deno:op_crates/fetch/23_request.js:395:19)
    at inspectObject (deno:op_crates/console/02_console.js:925:50)
    at inspectValue (deno:op_crates/console/02_console.js:481:16)
    at inspectArgs (deno:op_crates/console/02_console.js:1454:19)
    at console.log (deno:op_crates/console/02_console.js:1504:9)
    at ...
```

Expected behaviour is that consumers should be able to log the request, or parts therein without an exception being thrown.

**Comment by crowlKats** [comment]
Duplicate of #10334

**Comment by cmorten** [comment]
Ah apologies, my issue searching clearly failed - closing as duplicate.
