### ISSUE TITLE
Improve the error message from `stat/statSync`

### ISSUE THREAD

**Issue by canonic-epicure** [denoland/deno#10553]
Currently the error message of the exception, thrown from the `Deno.stat/statSync`, when the file is missing, does not include the file name:
```
nickolay@frontier:~/workspace/Bryntum/siesta-monorepo/siesta$ deno
Deno 1.9.2
exit using ctrl+d or close()
> Deno.statSync('/home/nickolay/not_existing_file')
Uncaught NotFound: No such file or directory (os error 2)
    at unwrapOpResult (deno:core/core.js:99:13)
    at Object.opSync (deno:core/core.js:113:12)
    at Object.statSync (deno:runtime/js/30_fs.js:224:22)
    at <anonymous>:2:6
> 
```
Is this intentional with some rationale behind, or just an oversight? From usability perspective the filename should be included in the message of course.

**Comment by bnoordhuis** [comment]
Pull request welcome!

The error message is bubbled up straight from the Rust runtime. The relevant code is here:

https://github.com/denoland/deno/blob/1cd1419e18386d512ab98849d132117182545b89/runtime/ops/fs.rs#L846-L850

It's possible to remap the error message to include the filename but it should be done in a principled manner, i.e., for more than just stat.

With ops that operate on more than one path (like link) you don't know which path is the problematic one. I'd include both in the error message, that's what Node does.

**Comment by CGQAQ** [comment]
![image](https://user-images.githubusercontent.com/15936231/118353751-46105a80-b59a-11eb-8bbb-9c3a149d8f69.png)

here's how the node prints out the error message, I should print it just like that?

**Comment by CGQAQ** [comment]
![image](https://user-images.githubusercontent.com/15936231/118354196-7822bc00-b59c-11eb-8ccb-1b67676f0c54.png)

Is this ok or not? @bnoordhuis

**Comment by abakfja** [comment]
@CGQAQ if you are not working on this, can I take this up?

**Comment by CGQAQ** [comment]
Sure

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Kannav Mehta ***@***.***>
发送时间: Wednesday, June 30, 2021 1:18:07 AM
收件人: denoland/deno ***@***.***>
抄送: CGQAQ ***@***.***>; Mention ***@***.***>
主题: Re: [denoland/deno] Improve the error message from `stat/statSync` (#10553)


@CGQAQ<https://github.com/CGQAQ> if you are not working on this, can I take this up?

―

**Comment by bartlomieju** [comment]
> @CGQAQ if you are not working on this, can I take this up?

Please do, there's already an open PR https://github.com/denoland/deno/pull/10642, but ideally we'd want to unify error messages for all ops in `ops/fs.rs` and provide the paths in those messages.

**Comment by ntedgi** [comment]
Is this PR still available?
I would be happy to give it a try

**Comment by abakfja** [comment]
Sure.

**Comment by SRNV** [comment]
@ntedgi are you still on it ?
I want to take this one
