### ISSUE TITLE
Uncaught NotFound: No such file or directory (os error 2) on Ubuntu when use filesystem with absolute path

### ISSUE THREAD

**Issue by scriptfulness** [denoland/deno#10624]
I use Ubuntu Ubuntu 20.04.2 and Deno 1.9.2

The file structure is 
```
- usecase.ts
- testfile.txt
```
inside the directory "usecase".

Content of the "usecase.ts" is
```
const testtext = Deno.readTextFileSync("./testfile.txt");
console.log(testtext)
```

When I run it from the current directory
` deno run -A usecase.ts`

it reads the file fine:
```
root@cb:/home/usecase# deno run -A usecase.ts
Check file:///home/usecase/usecase.ts
This is a test file
```

But when I run from the root directory, I get an error: "No such file or directory"
```
root@cb:~# deno run -A /home/usecase/usecase.ts
error: Uncaught NotFound: No such file or directory (os error 2)
const rates = Deno.readTextFileSync("./testfile.txt");
                   ^
    at unwrapOpResult (deno:core/core.js:99:13)
    at Object.opSync (deno:core/core.js:113:12)
    at openSync (deno:runtime/js/40_files.js:32:22)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:29:18)
    at file:///home/usecase/usecase.ts:1:20
```

Here are more logs:
```
root@cb:~# deno -L debug run -A /home/usecase/usecase.ts
DEBUG RS - deno_runtime::js:9 - Deno isolate init with snapshots.
DEBUG JS - args []
DEBUG RS - deno:870 - main_module file:///home/usecase/usecase.ts
DEBUG RS - deno::file_fetcher:605 - FileFetcher::fetch() - specifier: file:///home/usecase/usecase.ts
DEBUG RS - deno_runtime::permissions:40 - ⚠️️  Granted read access to "/home/usecase/usecase.ts"
DEBUG RS - deno::module_graph:836 - graph does not need to be checked or emitted.
DEBUG RS - deno::program_state:192 - Compilation statistics:

DEBUG RS - deno_runtime::permissions:40 - ⚠️️  Granted read access to "./testfile.txt"
error: Uncaught NotFound: No such file or directory (os error 2)
const rates = Deno.readTextFileSync("./testfile.txt");
                   ^
    at unwrapOpResult (deno:core/core.js:99:13)
    at Object.opSync (deno:core/core.js:113:12)
    at openSync (deno:runtime/js/40_files.js:32:22)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:29:18)
    at file:///home/usecase/usecase.ts:1:20
```

**Comment by caspervonb** [comment]
Working as intended.
Paths are relative to the working directory, not the executing module.

**Comment by brainless** [comment]
@scriptfulness what you might want to do is change your working directory before you (if the path is different). As I understand from the code [here](https://github.com/denoland/deno/blob/main/core/module_specifier.rs#L141) there is no way to set a base path.

**Comment by caspervonb** [comment]
You can use `import.meta.url` as a base to resolve from, similar to `__dirname` in node.
