### ISSUE TITLE
localStorage API errors for compiled deno binaries

### ISSUE THREAD

**Issue by grempe** [denoland/deno#10693]
I was excited to try out the new `localStorage` API (which seems like a great and natural fit for CLI's) and I found that it throws an error for any compiled output. This was run with Deno `1.10.2` on macOS.

welcome.ts
```
console.log("Welcome to Deno!")

localStorage.setItem("foo", "bar")
console.log(localStorage.getItem("foo"))
console.log(localStorage.length)
```

output : uncompiled

```
❯ deno run --location=https://127.0.0.1 welcome.ts
Welcome to Deno!
bar
1
```

output : compiled

```
❯ deno compile --unstable --location=https://127.0.0.1 welcome.ts
Check file:///private/tmp/cli/welcome.ts
Bundle file:///private/tmp/cli/welcome.ts
Compile file:///private/tmp/cli/welcome.ts
Emit welcome

❯ ./welcome
Welcome to Deno!
error: NotSupported: LocalStorage is not supported in this context.
    at DOMExceptionNotSupportedError (deno:runtime/js/99_main.js:199:16)
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at createStorage (deno:extensions/webstorage/01_webstorage.js:93:22)
    at localStorage (deno:extensions/webstorage/01_webstorage.js:178:24)
    at file://$deno$/bundle.js:2:1
```

The error message seems to originate from here:

https://github.com/denoland/deno/blob/dfe528198d363ebc883da84dc816bce112ecd24b/extensions/webstorage/lib.rs#L70

**Comment by crowlKats** [comment]
The problem is that we currently lack `DENO_DIR` in `compile`d context, which is required to store the SQLite file backing `localStorage`. This is definitively something wanted, but was omitted for the first iteration

**Comment by ihack2712** [comment]
It makes sense that it does not work for compiled binaries because there is no way for the compiled binary to know where the sqlite file should be stored, because it doesn't have the `$DENO_DIR` variable.

**Comment by ihack2712** [comment]
@ry Wasn't this the intended behaviour, making it not a bug?

**Comment by kitsonk** [comment]
bug/feature, minor distinction, but I changed the label

**Comment by grempe** [comment]
Thanks. I would suggest that the docs page reflect this (current) limitation.

Does it have to write to DENO_DIR? What about using arch specific default locations?

e.g.

https://deno.land/x/config_dir@v0.1.1/mod.ts

**Comment by wiremoons** [comment]
Out of interest - I don't understand the logic of this issue being labelled as a **feature** and not a **bug**?  

The reason for thinking it is in fact a **bug** is that Deno is '*broken*' functionality wise for any script that uses *LocalStorage* and wants to use the `compile` option. Both are great existing capabilities in Deno, so the fact they don't work together correctly is not intended behaviour - or is it? 

I don't think any developer would (or should) purposefully break a program capability, and then label the outcome a **feature**?

But whichever is fine - I guess my real interest is when it might be fixed or the feature added :)

Don't take my questions the wrong way please - I know there is lots of other higher priority issues, so I am not complaining, just checking out of interest. Also it is quite an amusing label switch from a user perspective for the reason outlined above :)

**Comment by crowlKats** [comment]
The reason this is a `feature` is because this requires adding some sort of caching capability to `compile`d as localStorage requires to store a sqlite file on the disk. its not a bug as this was fairly intentional when localStorage was merged, and as such isnt unexpected behaviour

**Comment by pitkes22** [comment]
Please mention this in the documentation page of [Compiling Executables](https://deno.land/manual/tools/compiler).

**Comment by maekoos** [comment]
I'm interested in getting this to work. Would it be a bad idea to require the user to supply the `origin_data_folder_path` manually during compilation? Maybe by using a flag like `--origin-data=./data`?

**Comment by enriquecaballero** [comment]
Does anyone have a workaround for this? Even if temporary? I can compile my app but I get this error when I try to run the binary. If I build and compile using Bun, everything works fine. 😕

**Comment by enriquecaballero-agx** [comment]
> Out of interest - I don't understand the logic of this issue being labelled as a **feature** and not a **bug**?
> 
> The reason for thinking it is in fact a **bug** is that Deno is '_broken_' functionality wise for any script that uses _LocalStorage_ and wants to use the `compile` option. Both are great existing capabilities in Deno, so the fact they don't work together correctly is not intended behaviour - or is it?
> 
> I don't think any developer would (or should) purposefully break a program capability, and then label the outcome a **feature**?
> 
> But whichever is fine - I guess my real interest is when it might be fixed or the feature added :)
> 
> Don't take my questions the wrong way please - I know there are lots of other higher priority issues, so I am not complaining, just checking out of interest. Also it is quite an amusing label switch from a user perspective for the reason outlined above :)

I agree with this: `deno compile` is completely unusable for me because the error prevents the app from running in compiled form. Might be a feature, but it’s very much also a **bug**.

**Comment by johnstonphilip** [comment]
I am attempting to do server side rendering and getting this error in compiled mode. Is there a way of overriding localStorage so this error doesn't prevent further execution?

**Comment by jespertheend** [comment]
It seems like you can use [Object.defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) to implement your own localStorage like so:

```js
Object.defineProperty(globalThis, "localStorage", {
	get: () => {
		const newLocalStorage = {}
		return newLocalStorage;
	}
})
```

Though I didn't try this in compiled mode so not sure if it still works then.

**Comment by ToshY** [comment]
Show stopper.

---

I'll leave [this article](https://phuoc.ng/collection/javascript-proxy/create-a-local-storage-polyfill-for-non-browser-environments/#creating-a-polyfill-for-the-localstorage-api) here to polyfill the localstorage with `Map`.

**Comment by johnstonphilip** [comment]
@jespertheend Thanks, this seems to have worked for me:

```
globalThis.localStorage = {
			getItem: (keyName) => {
				return keyName;
			},
			setItem: () => {
				const newLocalStorage = {}
				return newLocalStorage;
			},
			removeItem: () => {},
			clear: () => {},
			key: (key) => {return ''},
			length: 0,
};
Object.defineProperty(globalThis, "localStorage", globalThis.localStorage );
```

**Comment by sigmaSd** [comment]
I created a polyfill for this https://jsr.io/@sigma/deno-compile-extra

**Comment by Ivanov-Anton** [comment]
The same problem and fixed with https://jsr.io/@sigma/deno-compile-extra as temporary workaround
