### ISSUE TITLE
bug: `localStorage` methods give leaking resource errors in `Deno.test`

### ISSUE THREAD

**Issue by sno2** [denoland/deno#10691]
Basically, if you use `localStorage.getItem` or `localStorage.setItem` within a `Deno.test` callback (async or not), you will get errors for leaking resources.

## Example

```ts
Deno.test("Getting Keys", () => {
  localStorage.getItem("hello");
});

Deno.test("Setting Keys", () => {
  localStorage.setItem("hello", "foo");
});
```

```sh
$ deno test --location "http://deno.test"
```

## What Happens

It gives this error:

```
Check file:///C:/Projects/Deno/safe/mod_test.ts
running 2 tests from file:///C:/Projects/Deno/safe/mod_test.ts
test Getting Keys ... FAILED (9ms)
test Setting Keys ... ok (28ms)

failures:

Getting Keys
AssertionError: Test case is leaking resources.
Before: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr"
}
After: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr",
  "3": "webStorage"
}

Make sure to close all open resource handles returned from Deno APIs before
finishing test case.
    at assert (deno:runtime/js/06_util.js:33:13)
    at resourceSanitizer (deno:runtime/js/40_testing.js:69:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:85:9)
    at async runTest (deno:runtime/js/40_testing.js:199:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:244:7)
    at async file:///C:/projects/deno/safe/$deno$test.js:1:1

failures:

        Getting Keys

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (88ms)
```

## Expect behavior

It should not be throwing errors.

## Notes

If you actually look closely at the stdout, then you can see that it says that the "Setting Keys" test passes.  It seems that you will only get the resource leak error for the first `localStorage` call.  You can see this by changing the code to the following:

```ts
Deno.test("Getting Keys", () => { // FAIL
  localStorage.getItem("hello");
});

Deno.test("Setting Keys #1", () => { // PASS
  localStorage.setItem("hello", "foo");
});

Deno.test("Setting Keys #2", () => { // PASS
  localStorage.setItem("hello", "foo3");
});

Deno.test("foo", () => { // FAIL
  throw Error("foo");
});
```

**Comment by kitsonk** [comment]
cc/ @crowlKats
