### ISSUE TITLE
cli: panics when the output is piped to a non-existent executable

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno#10764]
Steps to reproduce:
```
➜  cat log.ts 
console.log("hello");
➜  deno  run log.ts | 404
zsh: command not found: 404
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:940:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    52032 abort      deno run log.ts | 
       52033 exit 127   404
```

**Comment by aaronhuggins** [comment]
@satyarohith Isn't this expected behavior on command line?

```shell
echo 'hello' | 404
echo "Exit code:" $?
deno eval "console.log('hello')" | 404
echo "Exit code:" $?

# Expected output:
#
# bash: 404: command not found
# Exit code: 127
# bash: 404: command not found
# thread 'main' panicked at 'failed printing to stdout: The pipe is being closed. (os error 232)', library\std\src\io\stdio.rs:940:9
# note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
# Exit code: 127
```

**Comment by satyarohith** [comment]
It shouldn't panic. For comparison, the behavior of node:
```
➜  ~ cat script.js
console.log("hello");
➜  ~ node script.js | 404
zsh: command not found: 404
```
