### ISSUE TITLE
assertion failed @ cli/program_state.rs

### ISSUE THREAD

**Issue by mustakimur** [denoland/deno#10831]
The following input will fail the assertion check at cli/program_state.rs:396:9.

Command: `./target/debug/deno run --allow-all input`
input:
```js
function g() {}
dEbugger;f() {
}.apply(nula, ['']);
f()
```
Failed assertion check:
```rust
  fn get_source_line(
    &self,
    file_name: &str,
    line_number: usize,
  ) -> Option<String> {
    if let Ok(specifier) = resolve_url(file_name) {
      self.file_fetcher.get_source(&specifier).map(|out| {
        // Do NOT use .lines(): it skips the terminating empty line.
        // (due to internally using .split_terminator() instead of .split())
        let lines: Vec<&str> = out.source.split('\n').collect();
        assert!(lines.len() > line_number);  // this is failed
        lines[line_number].to_string()
      })
    } else {
      None
    }
  }
```

The backtrace is following:
```
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
   3: <deno::program_state::ProgramState as deno::source_maps::SourceMapGetter>::get_source_line
   4: deno::source_maps::get_orig_position
   5: deno::ops::errors::op_apply_source_map
   6: deno_core::ops_json::op_sync::{{closure}}
   7: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
```

**Comment by mustakimur** [comment]
In case, the input files can be found here: https://github.com/mustakimur/crash_report/tree/main/deno/10831

**Comment by satyarohith** [comment]
I could reproduce for the second input file.
```
➜  ~ cat panic.ts
function g() {}
dEbugger;f() {
}.apply(nula, ['']);
f()
➜  ~ deno run -A panic.ts
error: Expected ';', '}' or <eof> at file:///Users/sr/panic.ts:2:13


➜  ~ cat -e invalid.js
^M^M^M^M^M^M^M^M^M^M^M^M^M^M^M^M-^M^M^M^M^M$
➜  ~ deno run -A invalid.js
thread 'main' panicked at 'assertion failed: lines.len() > line_number', cli/program_state.rs:396:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

➜  ~ deno --version
deno 1.11.0 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

**Comment by mustakimur** [comment]
@satyarohith please, use the file (that we have provided) itself instead of copy/paste input.

**Comment by crowlKats** [comment]
This has been fixed at some point, so will close.
