### ISSUE TITLE
panic on unwrap() of 'None' value@ cli/fmt_errors.rs

### ISSUE THREAD

**Issue by dianestephens** [denoland/deno#10886]
The following input  panic on unwrap() of a `None` value' @ cli/fmt_errors.rs:168:45

Command: ./target/debug/deno run --allow-all input
input:
```javascript
function a() {}
function b() {}
b
prototype = a;
new b();
```
Panic on unwrap:
```rust
fn format_maybe_source_line(
   ...

  for _i in 0..start_column {
    if source_line.chars().nth(_i as usize).unwrap() == '\t' {
      s.push('\t');
    } else {
      s.push(' ');
    }
  }
  
 ...
```
Backtrace is:
```
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:386:21
   4: deno::fmt_errors::format_maybe_source_line
             at ./cli/fmt_errors.rs:168:8
   5: deno::fmt_errors::format_stack
             at ./cli/fmt_errors.rs:115:15
   6: <deno::fmt_errors::PrettyJsError as core::fmt::Display>::fmt
             at ./cli/fmt_errors.rs:230:8
   7: <&T as core::fmt::Display>::fmt
```

**Comment by wperron** [comment]
I can't reproduce issue with 1.10.3, 1.11.0 or building from source @e779ea9 on Ubuntu 20.04 -- are you running on a different OS or Deno version?

**Comment by satyarohith** [comment]
I couldn't reproduce on macOS with deno `1.11.0` and canary (`deno 1.11.0+e75ffab`) as well.

**Comment by dianestephens** [comment]
I am running deno 1.10.3 on Ubuntu 20.04.2 but input should be this:
```rust
function a() {}
function b() {}
prototype = a;
new b();
```
 to get the panic on unwrap() of a None.

**Comment by kitsonk** [comment]
```
$ deno --version
deno 1.11.0 (debug, x86_64-apple-darwin)
v8 9.1.269.27
typescript 4.3.2

$ cat test.ts
function a() {}
function b() {}
prototype = a;
new b();

$ deno fmt test.ts
Checked 1 file
```

😕

**Comment by kitsonk** [comment]
Based on the command, it looks like you are building from source.  What commit are you building from and what is the output of `cargo --version`?

**Comment by kitsonk** [comment]
Actually repeating exactly what was provided initially, with the updated code:

```
$ deno run --allow-all input
error: Uncaught ReferenceError: prototype is not defined
prototype = a;
          ^
    at file:///[snip]/input:3:11

```

Again, working as expected.

**Comment by kitsonk** [comment]
One thing that could have happened is that there is something strange going where the cache has gotten into a funky state...  You might want to try to clear it for example:

```
$ deno info
DENO_DIR location: "/Users/kitsonk/Library/Caches/deno"
Remote modules cache: "/Users/kitsonk/Library/Caches/deno/deps"
Emitted modules cache: "/Users/kitsonk/Library/Caches/deno/gen"
Language server registries cache: "/Users/kitsonk/Library/Caches/deno/registries"
Origin storage: "/Users/kitsonk/Library/Caches/deno/location_data"

$ rm -rf /Users/kitsonk/Library/Caches/deno/gen
```

**Comment by mustakimur** [comment]
Actually, multiple inputs went down to the same panic! error. Here are three [inputs](https://gist.github.com/mustakimur/09e13afbb63912ae3d1f566caf28667b).

Executed as: `./target/debug/deno run --allow-all input`
Error Message: 
```
error: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/fmt_errors.rs:168:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Cargo: `cargo 1.52.0 (69767412a 2021-04-21)`
OS: `Linux 5.8.0-53-generic #60~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Fountainn** [comment]
Hello, I'm having the same issue on the latest version (deno 1.14.2)
Clearing the cache only temporarily solves the problem.

Cargo: `cargo 1.55.0 (32da73ab1 2021-08-23)`
Rustc: `rustc 1.55.0 (c8dfcfe04 2021-09-06)`
OS: `Manjaro Linux 21.0.7`

**Comment by nayeemrmn** [comment]
> So somewhere between isolate returning error and pretty-print the source line is switched - I suspect this is done by the source mapping functionality, which is completely unaware that the code was wrapped for execution. What I'm unsure of is why the code gets source mapped if it's already a JavaScript file.

- On runtime exceptions we get a source line directly from V8: https://github.com/denoland/deno/blob/v1.15.1/core/error.rs#L240.
- For TS sources we have to discard that source line and get one by **querying the URL to the file fetcher**: https://github.com/denoland/deno/blob/v1.15.1/cli/source_maps.rs#L168.
- As of #9604, the above will usually happen with JS sources as well since the source line gotten from V8 needs to be overridden anyway: https://github.com/denoland/deno/blob/v1.15.1/cli/source_maps.rs#L75.
- Meaning if there is a code transformation between what is at that resource and what is executed, the fetched source line can fall out of alignment with the line and column numbers. This is what's happening at https://deno.land/std@0.111.0/node/module.ts#L1077 `Deno.core.evalContext(transformedCode, untransformedUrl)`.

Not sure what the correct solution is, but I think whenever we execute synthetic or transformed code which is different than the content at the URL it was allocated (e.g. `Deno.core.evalContext()`) there should be a record of that so we at least doesn't try to fetch a source line from that URL.

More importantly, instead of panicking on source line formatting errors we should print `<error formatting source line>` in its place. There are other ways of reproducing this panic, like clearing a source file between module load and error throw.
