### ISSUE TITLE
Language Server crashes when using Japanese

### ISSUE THREAD

**Issue by numb86** [denoland/deno#10891]
### test

The language server crashes when using Japanese is performed as a comment.  
It also occurs when inputting Japanese in a markdown file with the following configuration.  
However, it does not always occur, and we have not found a reliable way to reproduce it.

```
.
├── README.md
└── main.ts
```

**To Reproduce**

1. create `main.ts`.
2. write comments in `main.ts` in Japanese
3. A notification will appear in the lower right corner. `A request has failed`
4. check the notification, the language server is down.

```
Starting Deno language server...
  version: 1.10.3 (release, x86_64-apple-darwin)
Connected to "Visual Studio Code" 1.56.2
language server initialized
Server ready.
thread '<unnamed>' panicked at 'slice index starts at 8573 but ends at 8570', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/dissimilar-1.0.2/src/range.rs:94:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

[Info  - 18:14:19] Connection to server got closed. Server will restart.
[Error - 18:14:19] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.

    at Object.dispose (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at LanguageClient.handleConnectionClosed (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at closeHandler (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at CallbackList.invoke (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at CallbackList.invoke (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at StreamMessageWriter.fireClose (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
    at Socket.<anonymous> (/Users/user/.vscode/extensions/denoland.vscode-deno-3.5.1/client/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
Starting Deno language server...
  version: 1.10.3 (release, x86_64-apple-darwin)
Connected to "Visual Studio Code" 1.56.2
language server initialized
Server ready.
```

**Screenshots**

![スクリーンショット 2021-06-08 19 21 44](https://user-images.githubusercontent.com/16703337/121176693-7b595100-c897-11eb-8019-2eba1b529af1.png)

**Versions**

vscode: 1.56.2 deno: 1.10.3 extension: 3.6.1

This has been happening since before `3.6.1`, and I was hoping that `3.6.1` would fix it, but no luck.

**Comment by kitsonk** [comment]
@numb86 it occurs randomly when typing Japanese characters?

There are some known issues with the text comparison library we are using, and the library hasn't published in a year and an issue I raised has gone unaddressed.  The problem was that the alternative crate was 10x slower than this one. Grrr...

**Comment by numb86** [comment]
Yes. Since it occurs randomly, it is difficult to reproduce.

I found this by accident, but it also happened when I pasted the code (which does not contain Japanese).
It happened when I copied and pasted the `case` of the `switch` statement.
As usual, this occurrence is also random.

https://user-images.githubusercontent.com/16703337/121192163-9cc23900-c8a7-11eb-86ab-4b9e84a3f788.mp4

The error content is as follows.
Some of them are in Japanese, these are the contents of `README.md` in the same directory.

```
thread '<unnamed>' panicked at 'begin <= end (9823 <= 9820) when slicing `# Cloudflare の挙動を理解する

## https://support.cloudflare.com/hc/ja/articles/200172516

基本的に、オリジンによる HTTP ヘッダを尊重する。  
だが「Edge Cache TTL」で上書きされていれば、それが採用される`[...]', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/dissimilar-1.0.2/src/range.rs:90:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[Info  - 10:05:09 PM] Connection to server got closed. Server will restart.
[Error - 10:05:09 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at LanguageClient.handleConnectionClosed (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at closeHandler (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at CallbackList.invoke (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at CallbackList.invoke (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at StreamMessageReader.fireClose (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 10:05:09 PM] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
    at Object.dispose (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at LanguageClient.handleConnectionClosed (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at closeHandler (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at CallbackList.invoke (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at CallbackList.invoke (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at StreamMessageReader.fireClose (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/Users/user/.vscode/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
Starting Deno language server...
  version: 1.10.3 (release, x86_64-apple-darwin)
Connected to "Visual Studio Code" 1.56.2
language server initialized
Server ready.
```

**Comment by magurotuna** [comment]
I tried to see if this occurs locally but was never able to reproduce it even though I tried to put several kinds of Japanese characters. Super weird...

Also the error message is weird, it refers to https://github.com/dtolnay/dissimilar/blob/1.0.2/src/range.rs#L90 but how could this line result in `begin <= end`? 🤔

**Comment by kitsonk** [comment]
Yeah, I think it happens in certain situations when there are MBC in the document and we are changing the document in certain ways.  There is an issue open where I have found that it doesn't parse unicode combinators properly.

**Comment by lucacasonato** [comment]
We have not gotten reports of this in a while. I think this is fixed. Please re-open if it is not.
