### ISSUE TITLE
lsp: panic "parse_lit should no be called"

### ISSUE THREAD

**Issue by RickStanley** [denoland/deno#10902]
# Steps to reproduce
1. Create a file "a.ts";
2. Start typing: `const a = {}`;
3. Add import operator to import a type: `const a: typeof import() = {}`;
4. See LSP panic and shutdown.

It happens as soon as `import()` is done, regardless of `typeof`.

# Expected behavior
It should allow import type file from file, for example, a JSON file, like so:
![image](https://user-images.githubusercontent.com/23178554/121256475-99fd1f00-c87a-11eb-8a12-11f420248423.png)
*Deno is disabled for this workspace

If missing `typeof` it should suggest adding it, like TS does:
![image](https://user-images.githubusercontent.com/23178554/121255954-09264380-c87a-11eb-8874-508df6baaf7e.png)

Stack:
```
Starting Deno language server...
  version: 1.10.3 (release, x86_64-unknown-linux-gnu)
Connected to "Visual Studio Code" 1.56.2
language server initialized
Server ready.
thread 'main' panicked at 'internal error: entered unreachable code: parse_lit should not be called', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.54.4/src/parser/expr.rs:1569:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 16:52:11] Connection to server got closed. Server will restart.
[Error - 16:52:11] Request textDocument/signatureHelp failed.
Error: Connection got disposed.
	at Object.dispose (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireClose (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at Socket.<anonymous> (/home/stanley/.vscode-server/extensions/denoland.vscode-deno-3.6.1/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
```

Not sure if I should report this here, or if I've provided enough information. Please let me now.

deno 1.10.3 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.27
typescript 4.2.2

**Comment by kitsonk** [comment]
Thanks. The info you supplied should be sufficient to troubleshoot.

**Comment by RickStanley** [comment]
@kitsonk Am I correct to assume that, even if this issue gets corrected, I wouldn't be able to import just the typings from a JSON file, since Deno currently doesn't support JSON files import by default (`resolveJsonModule`)?

**Comment by kitsonk** [comment]
Correct.  It should just treat it as an `any` though.

**Comment by dsherret** [comment]
This doesn't seem to panic anymore. Must have been fixed in swc so I'm going to close this one.
