### ISSUE TITLE
Cannot find name 'WeakRef' / Property 'deref' does not exist on type 'object'

### ISSUE THREAD

**Issue by maxxturing** [denoland/deno#10910]
1. Backend code has not changed since 2 Jun 2021 - everything has been fine

2. Ran command to run backend locally today (9 Jun 2021)
```
deno run --allow-net --allow-env --allow-read --allow-write --unstable --reload app.ts
```

3. Runs successfully
![image](https://user-images.githubusercontent.com/36308251/121387248-72718980-c942-11eb-901f-c29e4e053f2b.png)

4. After a few seconds it breaks and multiple errors are outputted 
```
Cannot find name 'WeakRef'
Property 'deref' does not exist on type 'object'
```
![image](https://user-images.githubusercontent.com/36308251/121386299-c9c32a00-c941-11eb-8128-7e9450387ccb.png)

Possibly linked to:
8 Jun 2021 Update - https://github.com/denoland/deno/releases/tag/v1.11.0
https://github.com/denoland/deno_std/issues/949
https://github.com/denoland/deno_std/pull/951
https://github.com/denoland/deno_std/blame/e2360e70bfc0d69725e2975e4c2c2352305f83e5/testing/asserts.ts#L177
https://github.com/denoland/deno_std/blame/e2360e70bfc0d69725e2975e4c2c2352305f83e5/testing/asserts.ts#L178
https://github.com/denoland/deno_std/blame/e2360e70bfc0d69725e2975e4c2c2352305f83e5/testing/asserts.ts#L179

deno 1.3.3
v8 8.6.334
typescript 4.0.2
superoak 3.1.0

📣  **_Friendly deno users - Any ideas as to what the issue is here? 🤔_**

**Comment by kt3k** [comment]
@maxxturing The type declaration of WeakRef was added at deno v1.5.0 ref: https://github.com/denoland/deno/blob/main/Releases.md#150--20201027 You need to upgrade at least to v1.5.0 to type check WeakRefs. Is that possible for your case?

**Comment by MierenManz** [comment]
if possible, try to upgrade to the latest version. It has loads and loads of improvements

**Comment by kt3k** [comment]
If upgrade is difficult, the options might be:
- use `--no-check` option to avoid type error (WeakRef exists in runtime even in v1.3.x, only typing is missing)
- provides type declaration manually (copy the contents of cli/dts/lib.esnext.weakref.d.ts and include it by `/// <reference />` directive
- pin `std/testing` version to <= 0.97.0 (you need to detect which dependency uses `std/testing` in your tree to do this)

**Comment by maxxturing** [comment]
Using `--no-check` still threw an error so I upgraded to `deno 1.11.0 (release, x86_64-apple-darwin)`

I'm now getting 16 errors:

```
error: TS2729 [ERROR]: Property 'boundary' is used before its initialization.
  readonly newLineDashBoundary = encoder.encode(`\r\n--${this.boundary}`);
                                                              ~~~~~~~~
    at https://deno.land/std@0.61.0/mime/multipart.ts:264:63

    'boundary' is declared here.
      constructor(reader: Deno.Reader, private boundary: string) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/std@0.61.0/mime/multipart.ts:269:36

TS2729 [ERROR]: Property 'boundary' is used before its initialization.
  readonly dashBoundaryDash = encoder.encode(`--${this.boundary}--`);
                                                       ~~~~~~~~
    at https://deno.land/std@0.61.0/mime/multipart.ts:265:56

    'boundary' is declared here.
      constructor(reader: Deno.Reader, private boundary: string) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/std@0.61.0/mime/multipart.ts:269:36

TS2729 [ERROR]: Property 'boundary' is used before its initialization.
  readonly dashBoundary = encoder.encode(`--${this.boundary}`);
                                                   ~~~~~~~~
    at https://deno.land/std@0.61.0/mime/multipart.ts:266:52

    'boundary' is declared here.
      constructor(reader: Deno.Reader, private boundary: string) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/std@0.61.0/mime/multipart.ts:269:36

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  FormFile,
  ~~~~~~~~
    at https://deno.land/x/multiparser@v2.0.1/deps.ts:5:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Form as FormV2,
  ~~~~~~~~~~~~~~
    at https://deno.land/x/multiparser@v2.0.1/mod.ts:4:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  FormFile as FormFileV2,
  ~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/multiparser@v2.0.1/mod.ts:5:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { FormFile } from "https://deno.land/std@0.61.0/mime/multipart.ts";
         ~~~~~~~~
    at https://deno.land/x/multiparser@v2.0.1/mod.ts:9:10

TS2612 [ERROR]: Property 'resolve' will overwrite the base property in 'Deferred<undefined>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    public readonly resolve!: () => void;
                    ~~~~~~~
    at https://deno.land/x/evt@v1.9.12/tools/Deferred.ts:57:21

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ServerRequest,
  ~~~~~~~~~~~~~
    at file:///Users/maxxwell/GitHub/the-tribe-backend/deps.ts:2:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  RouterContext,
  ~~~~~~~~~~~~~
    at file:///Users/maxxwell/GitHub/the-tribe-backend/deps.ts:3:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Middleware,
  ~~~~~~~~~~
    at file:///Users/maxxwell/GitHub/the-tribe-backend/deps.ts:7:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  TableRecord,
  ~~~~~~~~~~~
    at file:///Users/maxxwell/GitHub/the-tribe-backend/deps.ts:13:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  FieldSet,
  ~~~~~~~~
    at file:///Users/maxxwell/GitHub/the-tribe-backend/deps.ts:14:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  SelectResult,
  ~~~~~~~~~~~~
    at file:///Users/maxxwell/GitHub/the-tribe-backend/deps.ts:15:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  IRequestBody,
  ~~~~~~~~~~~~
    at file:///Users/maxxwell/GitHub/the-tribe-backend/deps.ts:30:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ISimpleRequestBody,
  ~~~~~~~~~~~~~~~~~~
    at file:///Users/maxxwell/GitHub/the-tribe-backend/deps.ts:31:3

Found 16 errors.
```

Any idea how to solve these?

**Comment by lucacasonato** [comment]
Type re exports require that you use `export type {} from "...";`.
