### ISSUE TITLE
'attempt to multiply with overflow' in swc_ecma_parser crate

### ISSUE THREAD

**Issue by dianestephens** [denoland/deno#10927]
Input that causes the overflow:
```
\u{cccccccccsccccccQcXt[uc(~).const[uctor().const[uctor())tbr())
```
The error reported:
```
thread 'main' panicked at 'attempt to multiply with overflow', /home/diane/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.57.3/src/lexer/number.rs:277:29
```
Backtrace:
```
thread 'main' panicked at 'attempt to multiply with overflow', /home/diane/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.57.3/src/lexer/number.rs:277:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
   3: swc_ecma_parser::lexer::number::<impl swc_ecma_parser::lexer::Lexer<I>>::read_int_u32::{{closure}}
             at /home/diane/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.57.3/src/lexer/number.rs:277:29

```
The swc code with the overflow:
```rust
    pub(super) fn read_int_u32(
        &mut self,
        radix: u8,
        len: u8,
        raw: &mut Raw,
    ) -> LexResult<Option<u32>> {
        let mut count = 0;
        let v = self.read_digits(
            radix,
            |opt: Option<u32>, radix, val| {
                count += 1;
                let total = opt.unwrap_or_default() * radix as u32 + val as u32;  // line causing the overflow
                (Some(total), count != len)
            },
            raw,
            true,
        )?;
        if len != 0 && count != len {
            Ok(None)
        } else {
            Ok(v)
        }
    }

```

**Comment by dianestephens** [comment]
Input file(s) can be found here: https://github.com/mustakimur/crash_report/tree/main/deno/10927
