### ISSUE TITLE
runTests API to run tests: expected type `rusty_v8::data::Integer`, got `rusty_v8::data::Value

### ISSUE THREAD

**Issue by linux-china** [denoland/deno#10941]
I want to use API to run tests, not command line  style(`deno test xxx.test.ts`) , and code as following: 

```typescript
Deno.test('hello', () => {
    console.log("hello")
})

await Deno[Deno.internal].runTests();
```

And I get the following exception: 

```
error: Uncaught TypeError: invalid op id: expected type `rusty_v8::data::Integer`, got `rusty_v8::data::Value`
await Deno[Deno.internal].runTests();
                          ^
    at dispatch (deno:core/core.js:82:12)
    at Object.opSync (deno:core/core.js:120:27)
    at postTestMessage (deno:runtime/js/40_testing.js:146:17)
    at Object.runTests (deno:runtime/js/40_testing.js:237:5)
```

Does Deno supply API to run tests?   Thanks

**Comment by caspervonb** [comment]
It's internal and the test harness is only available in `deno test`.

**Comment by kitsonk** [comment]
See #10771 for discussion around a user API for testing.
