### ISSUE TITLE
lsp: index out of bounds panic in adjust_folding_end_line

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#11182]
Not sure what I did, but this occurred:

```
Starting Deno language server...
  version: 1.11.3 (release, x86_64-pc-windows-msvc)
Connected to "Visual Studio Code" 1.57.1
language server initialized
Server ready.
thread 'main' panicked at 'index out of bounds: the len is 3253 but the index is 3286', cli\lsp\tsc.rs:1666:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to send notification
failed to send notification
[Info  - 4:27:02 p.m.] Connection to server got closed. Server will restart.
[Error - 4:27:02 p.m.] Request textDocument/foldingRange failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
    at Object.dispose (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-languageclient\lib\common\client.js:73:35)
    at LanguageClient.handleConnectionClosed (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
    at LanguageClient.handleConnectionClosed (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-languageclient\lib\node\main.js:155:15)
    at closeHandler (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
    at CallbackList.invoke (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at closeHandler (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
    at CallbackList.invoke (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at StreamMessageReader.fireClose (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
    at Socket.<anonymous> (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\messageReader.js:125:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 4:27:02 p.m.] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
    at Object.dispose (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-languageclient\lib\common\client.js:73:35)
    at LanguageClient.handleConnectionClosed (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
    at LanguageClient.handleConnectionClosed (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-languageclient\lib\node\main.js:155:15)
    at closeHandler (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
    at CallbackList.invoke (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at closeHandler (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
    at CallbackList.invoke (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at StreamMessageReader.fireClose (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
    at Socket.<anonymous> (c:\Users\david\.vscode\extensions\denoland.vscode-deno-3.6.1\client\node_modules\vscode-jsonrpc\lib\common\messageReader.js:125:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
Starting Deno language server...
```

https://github.com/denoland/deno/blob/f4bed1081456089559c82441a13c4fb700840cac/cli/lsp/tsc.rs#L1666

**Comment by kitsonk** [comment]
Were you copy pasting something?  I suspect it occurred during an edit where tsc was out of sync with the state of the document in the lsp.

We obviously need to guard against this situation, as it will randomly occur.  Two options I can think of, is that when we get the content to "adjust" we check the version that was sent to tsc and short circuit if the version is now different.  The other option is we range guard against it.  We could log an `error!()` if the range check fails to try to narrow it down further, but I think it is just the "life" of a multi-threaded language server calling into tsc that is single threaded.

I am pretty sure I know what needs to be done, so I can fix it, but I wouldn't want to discourage someone else from attempting.

**Comment by bartlomieju** [comment]
@dsherret is this issue still relevant?

**Comment by dsherret** [comment]
I haven't seen it in a long time and there's been a lot of improvements in the lsp. We can close it.
