### ISSUE TITLE
Printing `Request.prototype` in REPL results in panic

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#11257]
On commit 7ef0f43d87e3e45e8084bb7ae0dee2053968c010

```
~/p/g/d/deno ❯❯❯ cargo run
   Compiling deno v1.11.3 (/mnt/starship/Projects/github.com/denoland/deno/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 30.00s
     Running `target/debug/deno`
Deno 1.11.3
exit using ctrl+d or close()
> Request.prototype
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/repl.rs:575:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: deno::tools::repl::ReplSession::get_eval_value::{{closure}}
             at ./cli/tools/repl.rs:575:17
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   6: deno::tools::repl::ReplSession::evaluate_line_and_get_output::{{closure}}
             at ./cli/tools/repl.rs:469:21
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   8: deno::tools::repl::run::{{closure}}
             at ./cli/tools/repl.rs:687:22
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  10: deno::run_repl::{{closure}}
             at ./cli/main.rs:776:3
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  13: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:634:65
  14: tokio::coop::with_budget::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:106:9
  15: std::thread::local::LocalKey<T>::try_with
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
  16: std::thread::local::LocalKey<T>::with
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:352:9
  17: tokio::coop::with_budget
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:99:5
  18: tokio::coop::budget
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:76:5
  19: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:634:42
  20: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/macros/scoped_tls.rs:61:9
  21: tokio::task::local::LocalSet::with
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:548:9
  22: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:624:9
  23: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:498:9
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  25: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  26: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:213:62
  27: tokio::coop::with_budget::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:106:9
  28: std::thread::local::LocalKey<T>::try_with
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
  29: std::thread::local::LocalKey<T>::with
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:352:9
  30: tokio::coop::with_budget
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:99:5
  31: tokio::coop::budget
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:76:5
  32: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:213:39
  33: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:323:29
  34: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/macros/scoped_tls.rs:61:9
  35: tokio::runtime::basic_scheduler::enter
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:323:5
  36: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:202:9
  37: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:516:9
  38: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:162:24
  39: tokio::runtime::Runtime::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/mod.rs:450:46
  40: tokio::task::local::LocalSet::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:459:9
  41: deno::tokio_util::run_basic
             at ./cli/tokio_util.rs:24:3
  42: deno::main
             at ./cli/main.rs:1405:18
  43: core::ops::function::FnOnce::call_once
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by SimonRask** [comment]
`console.log(Request.prototype)` seems weird too

<pre><font color="#C01C28"><b>error</b></font>: Uncaught TypeError: Illegal invocation
console.log(Request.prototype);
<font color="#C01C28">        ^</font>
    at <i><b>Object.assertBranded</b></i> (<font color="#2AA1B3">deno:extensions/webidl/00_webidl.js</font>:<font color="#A2734C">841</font>:<font color="#A2734C">13</font>)
    at <i><b>Object.get [as bodyUsed]</b></i> (<font color="#2AA1B3">deno:extensions/fetch/22_body.js</font>:<font color="#A2734C">191</font>:<font color="#A2734C">18</font>)
    at <i><b>Object.[Deno.customInspect]</b></i> (<font color="#2AA1B3">deno:extensions/fetch/23_request.js</font>:<font color="#A2734C">376</font>:<font color="#A2734C">24</font>)
    at <i><b>inspectObject</b></i> (<font color="#2AA1B3">deno:extensions/console/02_console.js</font>:<font color="#A2734C">919</font>:<font color="#A2734C">50</font>)
    at <i><b>_inspectValue</b></i> (<font color="#2AA1B3">deno:extensions/console/02_console.js</font>:<font color="#A2734C">473</font>:<font color="#A2734C">16</font>)
    at <i><b>inspectValue</b></i> (<font color="#2AA1B3">deno:extensions/console/02_console.js</font>:<font color="#A2734C">488</font>:<font color="#A2734C">11</font>)
    at <i><b>inspectArgs</b></i> (<font color="#2AA1B3">deno:extensions/console/02_console.js</font>:<font color="#A2734C">1446</font>:<font color="#A2734C">19</font>)
    at <i><b>console.log</b></i> (<font color="#2AA1B3">deno:extensions/console/02_console.js</font>:<font color="#A2734C">1496</font>:<font color="#A2734C">9</font>)
    at <font color="#2AA1B3">file:///home/simon/dev/test2/test.js</font>:<font color="#A2734C">1</font>:<font color="#A2734C">9</font>
</pre>

**Comment by caspervonb** [comment]
This is coming from inspect.

```
Deno[Deno.internal].inspectArgs(['%o', Request.prototype])
Uncaught TypeError: Illegal invocation
    at Object.assertBranded (deno:extensions/webidl/00_webidl.js:845:13)
    at Object.get [as bodyUsed] (deno:extensions/fetch/22_body.js:191:18)
    at Object.[Deno.customInspect] (deno:extensions/fetch/23_request.js:376:24)
    at inspectObject (deno:extensions/console/02_console.js:904:41)
    at _inspectValue (deno:extensions/console/02_console.js:473:16)
    at inspectValue (deno:extensions/console/02_console.js:488:11)
    at Object.inspectArgs (deno:extensions/console/02_console.js:1402:30)
    at <anonymous>:2:21
    ```
