### ISSUE TITLE
After upgrading to 1.12.0, deno still access to old version of deno/std and errors occur.

### ISSUE THREAD

**Issue by WhiteF326** [denoland/deno#11399]
It happens while using Deno with PowerShell 7.1.3 inside VSCode on Windows 11 Home x64 21H2 build 22000.65 .
```
> deno --version

deno 1.12.0+1ad6575 (canary, x86_64-pc-windows-msvc)
v8 9.2.230.14
typescript 4.3.2
```

Today, I executed "deno upgrade" in PowerShell inside VSCode. The version I used before was deno 1.7.5, with TypeScript 4.1.4, that worked well with deno/std.
But at the time I run my script with Deno, which uses deno/std, it accesses to deno/std@0.85.0, and errors written below occur.
```
error: TS2729 [ERROR]: Property 'boundary' is used before its initialization.
  readonly newLineDashBoundary = encoder.encode(`\r\n--${this.boundary}`);
                                                              ~~~~~~~~
    at https://deno.land/std@0.85.0/mime/multipart.ts:263:63

    'boundary' is declared here.
      constructor(reader: Deno.Reader, private boundary: string) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/std@0.85.0/mime/multipart.ts:268:36

TS2729 [ERROR]: Property 'boundary' is used before its initialization.
  readonly dashBoundaryDash = encoder.encode(`--${this.boundary}--`);
                                                       ~~~~~~~~
    at https://deno.land/std@0.85.0/mime/multipart.ts:264:56

    'boundary' is declared here.
      constructor(reader: Deno.Reader, private boundary: string) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/std@0.85.0/mime/multipart.ts:268:36

TS2729 [ERROR]: Property 'boundary' is used before its initialization.
  readonly dashBoundary = encoder.encode(`--${this.boundary}`);
                                                   ~~~~~~~~
    at https://deno.land/std@0.85.0/mime/multipart.ts:265:52

    'boundary' is declared here.
      constructor(reader: Deno.Reader, private boundary: string) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/std@0.85.0/mime/multipart.ts:268:36

Found 3 errors.
```
What is my wrong? Or some bugs with deno, or windows?

Sorry for my bad English.

P.S.
This is the command I executes when I got errors written above : 
```
deno run -A --unstable server.js
```

**Comment by WhiteF326** [comment]
This problem was solved by destroying all files in "c:\users\(username)\AppData\Local\deno".
Sorry for making a meaningless issue.
