### ISSUE TITLE
Worker panics if terminated incorrectly 'No worker handle found', runtime\ops\worker_host.rs:522:6

### ISSUE THREAD

**Issue by Ciantic** [denoland/deno#11416]
I guess my termination code is incorrect, but Deno still should not panic:

```typescript
import { assertEquals } from "https://deno.land/std@0.100.0/testing/asserts.ts";

const fauxself = self as Worker & typeof self;
fauxself.onmessage = function (e) {
    fauxself.postMessage("foo");
    fauxself.close();
};


function runWorkerOnce(worker: Worker, initMessage: any) {
    return new Promise((resolve, _reject) => {
        worker.onmessage = (m) => {
            // Following causes a panic:
            // thread '<unnamed>' panicked at 'No worker handle found', runtime\ops\worker_host.rs:522:6
            worker.terminate();
            resolve(m);
        };
        worker.postMessage(initMessage);
    });
}

if (typeof Deno !== "undefined") {
    Deno.test({
        name: "test something",
        async fn() {
            const w = new Worker(import.meta.url, {
                type: "module",
            });

            const res: any = await runWorkerOnce(w, "");
            assertEquals(res.data, "foo");
        },
    });
}
```

Try runnin the `Deno.test` case, it gives me `thread '<unnamed>' panicked at 'No worker handle found', runtime\ops\worker_host.rs:522:6`

## Workaround

```
       setTimeout(() => {
                worker.terminate();
            }, 0);
```

**Comment by andreubotella** [comment]
This panic seems to happen when the message and the close event are both received in the same run of `poll_pending_ops`, since the close event will be processed in Rust, and the worker removed from the workers table, before the message's JS promise reactions get to run.
