### ISSUE TITLE
should Deno.rename handle moving across mounts/devices?

### ISSUE THREAD

**Issue by kinghat** [denoland/deno#11541]
**Is your feature request related to a problem? Please describe.** 

currently you cannot use `Deno.rename` to `move` a file or directory across mounts/devices:
> error: Uncaught (in promise) Error: Invalid cross-device link (os error 18)
  await Deno.rename(src, dest);
  ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.rename (deno:runtime/js/30_fs.js:172:5)
    at async move (https://deno.land/std@0.102.0/fs/move.ts:33:3)

 this is not the case with the `mv` command: `mv uses cp(1) and rm(1)`

**Describe the solution you'd like**

make Deno.rename match `mv`.

**Comment by ry** [comment]
`Deno.rename` maps onto a posix system call. We want to maintain the ability to make this low-level call.

I think we should have the functionality you describe but it belongs in `std/fs/move.ts`

I will transfer this issue back to deno_std and retitle it.
