### ISSUE TITLE
`deno compile` produce `ReferenceError` for wildcard export

### ISSUE THREAD

**Issue by ratson** [denoland/deno#11575]
**Test Case**

```sh-session
deno compile https://raw.githubusercontent.com/ratson/bug-report/deno/compile-import-export/mod.ts
./compile-import-export
```

Source: https://github.com/ratson/bug-report/tree/deno/compile-import-export

**Expect**
```
/tmp/deps
/tmp/path
```

**Got**
```
/tmp/deps
error: ReferenceError: path is not defined
    at file://$deno$/bundle.js:1088:13
```

**Version**
```sh-session
❯ deno --version
deno 1.12.2 (release, x86_64-apple-darwin)
v8 9.2.230.14
typescript 4.3.5
```

**Comment by F3n67u** [comment]
Can also reproduce when use `deno bundle` and `deno run`, It's likely bug from upstream `swc`;
```
 % deno bundle https://raw.githubusercontent.com/ratson/bug-report/deno/compile-import-export/mod.ts bundle.js
Check https://raw.githubusercontent.com/ratson/bug-report/deno/compile-import-export/mod.ts
Bundle https://raw.githubusercontent.com/ratson/bug-report/deno/compile-import-export/mod.ts
Emit "bundle.js" (35.42KB)
 % deno run bundle.js 
/tmp/deps
error: Uncaught ReferenceError: path is not defined
console.log(path.join("/tmp", "path"));
            ^
    at file:///Users/feng/test/bug-report/bundle.js:1088:13
```

Version
```
% deno --version
deno 1.12.2 (release, x86_64-apple-darwin)
v8 9.2.230.14
typescript 4.3.5
```

**Comment by ratson** [comment]
Is there any blocker to merge the upstream fix?
The error is still presented in the latest release.

```
❯ deno --version
deno 1.16.3 (release, x86_64-apple-darwin)
v8 9.7.106.5
typescript 4.4.2
```
