### ISSUE TITLE
`integration::test::doc` and `integration::test::doc_markdown` tests are flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#11593]
```
---- integration::test::doc_markdown stdout ----
root path /Users/runner/work/deno/deno
deno_exe path /Users/runner/work/deno/deno/target/release/deno
deno_exe args test --doc --allow-all test/doc_markdown
deno_exe tests path "/Users/runner/work/deno/deno/cli/tests"
output path /Users/runner/work/deno/deno/cli/tests/test/doc_markdown.out
[test_util/src/lib.rs:1382] part = "/test/doc_markdown/doc.md$11-14.js\nCheck "
[test_util/src/lib.rs:1382] i = 1
[test_util/src/lib.rs:1388] "found " = "found "
[test_util/src/lib.rs:1388] found = 45
[test_util/src/lib.rs:1382] part = "/test/doc_markdown/doc.md$17-20.ts\nCheck "
[test_util/src/lib.rs:1382] i = 2
[test_util/src/lib.rs:1388] "found " = "found "
[test_util/src/lib.rs:1388] found = 45
Error: til/src/lib.rs:1382] part = "/test/doc_markdown/doc.md$23-26.ts\nerror: TS2322 [ERROR]: Type 'number' is not assignable to type 'string'.\nconst a: string = 42;\n      ^\n    at "
[test_util/src/lib.rs:1382] i = 3
[test_util/src/lib.rs:1391] "exit false " = "exit false "
[test_util/src/lib.rs:1391] i = 3
OUTPUT
Check file:///Users/runner/work/deno/deno/cli/tests/test/doc_markdown/doc.md$11-14.js
Check file:///Users/runner/work/deno/deno/cli/tests/test/doc_markdown/doc.md$17-20.ts
Check file:///Users/runner/work/deno/deno/cli/tests/test/doc_markdown/doc.md$23-26.ts
error: Error: Error converting the result for "op_respond".
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at exec (deno:cli/tsc/99_main_compiler.js:533:10)
    at [deno:cli/tsc.rs:567:27]:1:12

OUTPUT
EXPECTED
Check [WILDCARD]/test/doc_markdown/doc.md$11-14.js
Check [WILDCARD]/test/doc_markdown/doc.md$17-20.ts
Check [WILDCARD]/test/doc_markdown/doc.md$23-26.ts
Error: TS2322 [ERROR]: Type 'number' is not assignable to type 'string'.
const a: string = 42;
      ^
    at [WILDCARD]/test/doc_markdown/doc.md$23-26.ts:1:7

EXPECTED
Error: thread 'integration::test::doc_markdown' panicked at 'pattern match failed', test_util/src/lib.rs:1342:7
stack backtrace:
   0:        0x10d5524d3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6a8908fa3ed6f9e8
   1:        0x10d400dfc - core::fmt::write::h4be00f71c5582919
   2:        0x10d551d0a - std::io::Write::write_fmt::h93cbb8c6ac53b1a6
   3:        0x10d55160f - std::panicking::default_hook::{{closure}}::h1577f0656e419c0e
   4:        0x10d5507b6 - std::panicking::rust_panic_with_hook::h10bc487d002f6c42
   5:        0x10d5c3b07 - std::panicking::begin_panic::{{closure}}::h206873fcb4e1e1c0
   6:        0x10d5c3ad8 - std::sys_common::backtrace::__rust_end_short_backtrace::h2b7a7bc34e5a596d
   7:        0x10d7a58d8 - std::panicking::begin_panic::h6767762d09347c4a
   8:        0x10d5c2372 - test_util::CheckOutputIntegrationTest::run::ha304ca1e71674017
   9:        0x10d3421b2 - core::ops::function::FnOnce::call_once::h2b72dc751f116574
  10:        0x10d5a811a - test::__rust_begin_short_backtrace::h8537766c178d3dff
  11:        0x10d5a83e1 - test::run_test::run_test_inner::{{closure}}::hef20bc7b3073ef89
  12:        0x10d5a9e41 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbedd640dcb83f549
  13:        0x10d5a9c92 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbeed65ddf37019e1
  14:        0x10d584b4a - std::sys::unix::thread::Thread::new::thread_start::h63f8b299c7b9d50c
  15:     0x7fff6e339109 - __pthread_start
Error: thread 'integration::test::doc' panicked at 'pattern match failed', test_util/src/lib.rs:1342:7
stack backtrace:
   0:        0x10d5524d3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6a8908fa3ed6f9e8
   1:        0x10d400dfc - core::fmt::write::h4be00f71c5582919
   2:        0x10d551d0a - std::io::Write::write_fmt::h93cbb8c6ac53b1a6
   3:        0x10d55160f - std::panicking::default_hook::{{closure}}::h1577f0656e419c0e
   4:        0x10d5507b6 - std::panicking::rust_panic_with_hook::h10bc487d002f6c42
   5:        0x10d5c3b07 - std::panicking::begin_panic::{{closure}}::h206873fcb4e1e1c0
   6:        0x10d5c3ad8 - std::sys_common::backtrace::__rust_end_short_backtrace::h2b7a7bc34e5a596d
   7:        0x10d7a58d8 - std::panicking::begin_panic::h6767762d09347c4a
   8:        0x10d5c2372 - test_util::CheckOutputIntegrationTest::run::ha304ca1e71674017
   9:        0x10d342203 - core::ops::function::FnOnce::call_once::h17cdf11597635b42
  10:        0x10d5a811a - test::__rust_begin_short_backtrace::h8537766c178d3dff
  11:        0x10d5a83e1 - test::run_test::run_test_inner::{{closure}}::hef20bc7b3073ef89
  12:        0x10d5a9e41 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbedd640dcb83f549
  13:        0x10d5a9c92 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbeed65ddf37019e1
  14:        0x10d584b4a - std::sys::unix::thread::Thread::new::thread_start::h63f8b299c7b9d50c
  15:     0x7fff6e339109 - __pthread_start


failures:
    integration::test::doc
    integration::test::doc_markdown

test result: FAILED. 484 passed; 2 failed; 14 ignored; 0 measured; 0 filtered out; finished in 206.17s
```

https://github.com/denoland/deno/pull/11590/checks?check_run_id=3255508350

**Comment by caspervonb** [comment]
Ugh, these tests aren't racy in any way so this is likely a real failure.

**Comment by dsherret** [comment]
I'm just going to close this one. Haven't seen it in a while.
