### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', extensions/http/lib.rs:204:12

### ISSUE THREAD

**Issue by mitranim** [denoland/deno#11651]
Previously with Deno `1.11.5`, our server kinda worked. Now with Deno `1.13.0` or `1.12.2`, our server crashes with the following:

```
stack backtrace:
   0:     0x55b27dfe2450 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55b27dfe2450 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b27dfe2450 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b27dfe2450 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b27e00daaf - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55b27dfd9fa5 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55b27dfe4bbb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b27dfe4bbb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b27dfe4bbb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55b27dfe468d - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55b27dfe533d - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x55b27dfe4e77 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:495:13
  12:     0x55b27dfe28ec - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55b27dfe4e09 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x55b27e00b141 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x55b27e00b08d - core::panicking::panic::h60569d8a39169222
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
  16:     0x55b27eb4e81b - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::haeff1a7a4bb18c84
  17:     0x55b27e5c38bf - <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll::h726dabe479f9f9ef
  18:     0x55b27eee71f9 - futures_util::stream::stream::StreamExt::poll_next_unpin::hb6be4eaee9072b61
  19:     0x55b27ef1ad33 - deno_core::runtime::JsRuntime::poll_event_loop::h99bc884fd7f8345b
  20:     0x55b27e1e63bc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h018c7c4d27bc194f
  21:     0x55b27e209785 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h67f282694380cc0c
  22:     0x55b27e2088e4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h61485ad0a4680096
  23:     0x55b27e3258fb - deno::main::h64940669c574a9ef
  24:     0x55b27e097447 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4da3430ff95f780c
  25:     0x55b27e09ce54 - std::rt::lang_start::{{closure}}::hf5eccd5e7dfa5024
  26:     0x55b27dfe583a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  27:     0x55b27dfe583a - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  28:     0x55b27dfe583a - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  29:     0x55b27dfe583a - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  30:     0x55b27dfe583a - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  31:     0x55b27e33961e - main
  32:     0x7f91c9787b46 - __libc_start_main
  33:     0x55b27d203bea - _start
  34:                0x0 - <unknown>
```

**Comment by bartlomieju** [comment]
@mitranim can you add examples of the helper functions you're using in the above code? (`maybeLogErr`, `errRes`, `respondErr`)

**Comment by mitranim** [comment]
Like Dr. Frankenstein putting the homunculus together, I've ripped apart the server code and put it together in a smaller, oversimplified form. This should contain everything meaningfully related to HTTP handling, without unnecessary business-specific details. This lacks actual HTML page generation, but that's probably not essential.

https://gist.github.com/mitranim/6807b69277add79e49b7fb0fd32cf003

**Comment by mitranim** [comment]
Sadly I can't guarantee that the above can actually reproduce the issue. Trying to downscale the example, but might accidentally omit the actual cause.

**Comment by mitranim** [comment]
Updated to `1.13.1` today, no crashes yet.
