### ISSUE TITLE
Array accesses need primordials

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#11677]
```js
Object.defineProperty(Array.prototype, "0", {
  set: (v) => {
    throw new Error("WTF");
  },
});
console.log("Test");
```

```
Test
error: Uncaught Error: WTF
    throw new Error("WTF");
          ^
    at <anonymous> (file:///home/abotella/test.js:3:11)
```

**Comment by andreubotella** [comment]
I thought the array access in question in the above sample was in the console code, but it seems to happen when dealing with the `load` event:

```js
Object.defineProperty(Array.prototype, "0", {
  get: () => "c",
});
```

```
error: Uncaught TypeError: Cannot set property 0 of [object Array] which has only a getter
    at <anonymous> (deno:extensions/web/02_event.js:507:5)
```

**Comment by nayeemrmn** [comment]
Rather than primordials, this is related to naive property dereferencing vs using `Object.hasOwnProperty()`/ `Object.getOwnProperty()`. But even e.g. `Array.prototype.join()` is susceptible to `Array.prototype[0]` modification:
![image](https://user-images.githubusercontent.com/29990554/160206185-9824b1c7-e34c-4270-a6a5-905f62dc86e3.png)
The problem is entangled parts of our internal JS responding to that in less predictable ways. But it's hard to determine what is or isn't worth making more fault-tolerant if any of it.

**Comment by Hajime-san** [comment]
It doesn't seem to be happening right now. Is this resolved?

```bash
% deno --version  
deno 1.40.4 (release, aarch64-apple-darwin)
v8 12.1.285.6
typescript 5.3.3
```

**Comment by bartlomieju** [comment]
Both repros from this thread (setter and getter on `Array.prototype[0]`) no longer reproduce on Deno 2.9.1, the load event fires and user code runs fine. Internal JS has since migrated to primordials with lint enforcement. The general hazard mentioned above (prototype-chain lookups for array holes in user-visible builtins like `join`) is inherent to JS and covered by the primordials discipline in ext/ code rather than fixable as a single bug. Closing as completed.
