### ISSUE TITLE
Bad resource ID when closing listener connection in tests

### ISSUE THREAD

**Issue by alisabzevari** [denoland/deno#11687]
I am using Deno v1.13.0 and the following test throws `Bad resource ID` error:

``` ts
Deno.test({
  name: "closing server resources", fn: async () => {
    const listener = Deno.listen({ port: 8080 });
    const conn = listener.accept();

    (async () => {
      const requests = Deno.serveHttp(await conn);
      const req = await requests.nextRequest();
      req?.respondWith(new Response("Hi"));
    })();

    const resp = await fetch("http://localhost:8080");
    resp.body?.cancel();
    (await conn).close(); // Error throws here
    listener.close();
  }
});
```

The thrown error is as follows:
```
BadResource: Bad resource ID
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at opSync (deno:core/01_core.js:140:12)
    at Object.close (deno:core/01_core.js:148:5)
    at Conn.close (deno:extensions/net/01_net.js:92:12)
    at fn (file:///home/asabzevari/projects/ts/http4ts/src/deno/__tests__/server.test.ts:25:18)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
```

I have also tried `Deno.close(rid)` and got the same result.
Am I missing something?

**Comment by bartlomieju** [comment]
`const requests = Deno.serveHttp(await conn);` <-- this line consumes the tcp connection and instead creates a new resource "http connection". So you don't need to close `conn` manually. You want to to call `requests.close()`

**Comment by michaelwybraniec** [comment]
0

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
