### ISSUE TITLE
lsp: language server errorred when typing with type `Generator`

### ISSUE THREAD

**Issue by g-plane** [denoland/deno#11758]
I have a TypeScript snippet below:

```ts
declare let g: Generator<string, string>

g.next
```

When I typed parens (which will be `g.next()`), language server crashed.

Output:

```
Starting Deno language server...
  version: 1.13.0 (release, x86_64-unknown-linux-gnu)
  executable: /usr/bin/deno
Connected to "Visual Studio Code" 1.59.0
language server initialized
Server ready.
Failed to request to tsserver: TypeError: Cannot read properties of undefined (reading 'checkFlags')
    at deno:cli/tsc/00_typescript.js:134532:113
    at Array.map (<anonymous>)
    at itemInfoForParameters (deno:cli/tsc/00_typescript.js:134530:26)
    at getSignatureHelpItem (deno:cli/tsc/00_typescript.js:134484:98)
    at deno:cli/tsc/00_typescript.js:134424:83
    at Object.map (deno:cli/tsc/00_typescript.js:645:29)
    at createSignatureHelpItems (deno:cli/tsc/00_typescript.js:134424:28)
    at deno:cli/tsc/00_typescript.js:134012:23
    at Object.runWithCancellationToken (deno:cli/tsc/00_typescript.js:45451:28)
    at Object.getSignatureHelpItems (deno:cli/tsc/00_typescript.js:134010:32)
[Error - 下午10:54:15] Request textDocument/signatureHelp failed.
  Message: Invalid request
  Code: -32600 
Failed to request to tsserver: TypeError: Cannot read properties of undefined (reading 'checkFlags')
    at deno:cli/tsc/00_typescript.js:134532:113
    at Array.map (<anonymous>)
    at itemInfoForParameters (deno:cli/tsc/00_typescript.js:134530:26)
    at getSignatureHelpItem (deno:cli/tsc/00_typescript.js:134484:98)
    at deno:cli/tsc/00_typescript.js:134424:83
    at Object.map (deno:cli/tsc/00_typescript.js:645:29)
    at createSignatureHelpItems (deno:cli/tsc/00_typescript.js:134424:28)
    at deno:cli/tsc/00_typescript.js:134012:23
    at Object.runWithCancellationToken (deno:cli/tsc/00_typescript.js:45451:28)
    at Object.getSignatureHelpItems (deno:cli/tsc/00_typescript.js:134010:32)
[Error - 下午10:54:27] Request textDocument/signatureHelp failed.
  Message: Invalid request
  Code: -32600 
```

This can be only reproduced with Deno LSP. For a normal TypeScript project on Node.js, everything works well.

**Comment by dsherret** [comment]
Investigated and the fix for this will be available in TS 4.4: https://github.com/microsoft/TypeScript/pull/44083

**Comment by kitsonk** [comment]
Also, note, it doesn't "crash" it errors. The built in TypeScript language server swallows these type of errors, where as we notify the user.

**Comment by g-plane** [comment]
This has been fixed. Closing.
