### ISSUE TITLE
Deno.startTls 

### ISSUE THREAD

**Issue by aricart** [denoland/deno#11759]
`Deno.startTls` seems to have gone away from the docs for some reason (not in unstable or stable docs). Hopefully, this is an omission, not a removal, as TLS was originally designed to be an upgrade process rather than a straight connect process.

Previously, if there was a bad certificate (as in the CA was not specified etc), the connection would fail on the `Deno.startTls` API call, resolving to error `InvalidData` which was not very informative, but at least could be associated with the process of upgrading to the TLS connection.

On newer versions (1.13.1) it fails on a socket flush. Definitely not expecting it to fail after the call to startTls has returned indicating that the socket is ready for work. The message `Sending fatal alert BadCertificate` is logged on the console, but this is not useful. Instead, I would expect some reasonable error to be raised on Deno.startTls, and that I can handle/propagate properly.

```
error: Uncaught (in promise) UnexpectedEof: tls handshake eof
    nwritten += await w.write(arr.subarray(nwritten));
                ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async write (deno:ext/net/01_net.js:26:12)
    at async writeAll (https://deno.land/std@0.95.0/io/util.ts:79:17)
    at async BufWriter.flush (https://deno.land/std@0.95.0/io/bufio.ts:470:7)
    at async write (file:///Users/synadia/Dropbox/code/src/github.com/nats-io/nats.deno/src/deno_transport.ts:45:3)
```

**Comment by bartlomieju** [comment]
This behavior was changed on purpose, see https://github.com/denoland/deno/issues/9123

**Comment by aricart** [comment]
@bartlomieju thanks for the quick turnaround. How am I supposed to handle the condition - IE, if the transport (whatever kind of connection it is) according to the API `connected` but really it didn't. It will fail sometime in the future on a write... Any way of testing the Conn returned to check if it is closed?

**Comment by bartlomieju** [comment]
@aricart I'm afraid we don't have an API that would check if connection is closed. I know that this change was done on purpose but I don't have full context. CCing @piscisaureus and @lucacasonato

**Comment by lucacasonato** [comment]
@aricart It fails on `read` or `write` or flush (as part of write). You might be able to detect it with a 0 byte read. The problem is that if you detect it as connected, and only if it is connected to something, there is racyness. The connection might close between checking if it is connected, and reading / writing to it. You should just try to read/write and handle errors accordingly.

**Comment by aricart** [comment]
@lucacasonato will try the trick of 0 byte read - with an empty write or flush nothing happens.

The complexity on my side is that the handling of the connection is not aware of any Deno specifics (reused in node, browser, etc). The connect is expected to succeed or fail with that sort of error there, rather than on the read/write which of course can happen but indicates a different issue.

**Comment by aricart** [comment]
@lucacasonato tried a zero byte read, which unfortunately succeeds :(

**Comment by aricart** [comment]
IMHO, I know there is a good reason to think that the error could be raised during the stream processing, but it sort of defeats the well-defined step of the connection upgrade. Any failure in the processing of the stream usually requires a re-dial (on long-running processes). An error on the connect/upgrade usually will attempt so many times, and in the case, where the cert may not be valid/trusted, may require stopping the process.

**Comment by aricart** [comment]
Eagerly awaiting this fix - thanks!

**Comment by aricart** [comment]
@bartlomieju I saw that - very happy that is going to land - I have not modified my side yet, so this is awesome!
