### ISSUE TITLE
`httpServerIncompleteMessage` and `integration::lsp::lsp_diagnostics_refresh_dependents` tests flaky

### ISSUE THREAD

**Issue by F3n67u** [denoland/deno#11798]
After https://github.com/denoland/deno/pull/11793 merged into `main` ci fail. Seems the following two test case is flaky.

1. `httpServerIncompleteMessage`: https://github.com/denoland/deno/runs/3389189999

```
error: Test failed

failures:

httpServerIncompleteMessage
AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   1
+   2

    at assertEquals (file:///Users/runner/work/***/***/test_util/std/testing/asserts.ts:259:9)
    at httpServerIncompleteMessage (file:///Users/runner/work/***/***/cli/tests/unit/http_test.ts:808:5)
    at async asyncOpSanitizer (***:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (***:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (***:runtime/js/40_testing.js:99:9)
    at async applyPermissions (***:runtime/js/40_testing.js:124:9)
    at async runTest (***:runtime/js/40_testing.js:215:7)
    at async Object.runTests (***:runtime/js/40_testing.js:283:22)
    at async file:///Users/runner/work/***/***/bc549e32-de8a-448e-b563-1a49d06f69d0$***$test.js:4:1

failures:

	httpServerIncompleteMessage

test result: FAILED. 833 passed; 1 failed; 19 ignored; 0 measured; 0 filtered out (48927ms)
```

2. `integration::lsp::lsp_diagnostics_refresh_dependents`: https://github.com/denoland/deno/runs/3389190031
```
---- integration::lsp::lsp_diagnostics_refresh_dependents stdout ----
Error: thread 'integration::lsp::lsp_diagnostics_refresh_dependents' panicked at 'assertion failed: params.diagnostics.is_empty()', cli/tests/integration/lsp_tests.rs:2938:7

failures:
    integration::lsp::lsp_diagnostics_refresh_dependents

test result: FAILED. 509 passed; 1 failed; 8 ignored; 0 measured; 0 filtered out; finished in 279.19s
```

**Comment by dsherret** [comment]
The log was improved for `lsp_diagnostics_refresh_dependents`:

```
thread 'integration::lsp::lsp_diagnostics_refresh_dependents' panicked at 'assertion failed: `(left == right)`
  left: `[Diagnostic { range: Range { start: Position { line: 0, character: 12 }, end: Position { line: 0, character: 13 } }, severity: Some(Error), code: Some(Number(2305)), code_description: None, source: Some("deno-ts"), message: "Module '\"./file_01.ts\"' has no exported member 'b'.", related_information: None, tags: None, data: None }]`,
 right: `[]`', cli/tests/integration/lsp_tests.rs:2938:7
```

**Comment by bartlomieju** [comment]
Another failure in `lsp_diagnostics_refresh_dependents` https://github.com/denoland/deno/runs/3540658003

**Comment by kitsonk** [comment]
Ok, it is some sort of race condition in the `refresh_dependents`... grrr...

**Comment by kitsonk** [comment]
I don't know why it has gone flaky recently though, it was really stable before...

**Comment by kitsonk** [comment]
I think this race condition was eliminated during the refactor of documents/sources.
