### ISSUE TITLE
esnext unit test fail when running outside ci

### ISSUE THREAD

**Issue by F3n67u** [denoland/deno#11795]
```
% cargo test js_unit_tests
...

failures:

objectHasOwn
TypeError: Object.hasOwn is not a function
    at objectHasOwn (file:///Users/feng/Projects/deno/cli/tests/unit/esnext_test.ts:16:17)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:35:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:72:13)
    at exitSanitizer (deno:runtime/js/40_testing.js:99:15)
    at applyPermissions (deno:runtime/js/40_testing.js:124:15)
    at runTest (deno:runtime/js/40_testing.js:215:13)
    at Object.runTests (deno:runtime/js/40_testing.js:283:28)
    at async file:///Users/feng/Projects/deno/9d0b291e-5bb6-476c-bf34-04c5424461a4$deno$test.js:4:1

errorCause
AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   undefined
+   "something"

    at assertEquals (file:///Users/feng/Projects/deno/test_util/std/testing/asserts.ts:259:9)
    at errorCause (file:///Users/feng/Projects/deno/cli/tests/unit/esnext_test.ts:22:3)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:35:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:72:13)
    at exitSanitizer (deno:runtime/js/40_testing.js:99:15)
    at applyPermissions (deno:runtime/js/40_testing.js:124:15)
    at runTest (deno:runtime/js/40_testing.js:215:13)
    at Object.runTests (deno:runtime/js/40_testing.js:283:28)
    at async file:///Users/feng/Projects/deno/9d0b291e-5bb6-476c-bf34-04c5424461a4$deno$test.js:4:1

failures:

        objectHasOwn
        errorCause

test result: FAILED. 835 passed; 2 failed; 16 ignored; 0 measured; 0 filtered out (78648ms)

error: Test failed
test integration::js_unit_tests ... FAILED

failures:

---- integration::js_unit_tests stdout ----
test_server starting...
thread 'integration::js_unit_tests' panicked at 'assertion failed: `(left == right)`
  left: `Some(0)`,
 right: `Some(1)`', cli/tests/integration/mod.rs:1076:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    integration::js_unit_tests

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 516 filtered out; finished in 120.69s

error: test failed, to rerun pass '-p deno --test integration_tests'
```

```
% ./target/debug/deno --version
deno 1.13.1 (debug, x86_64-apple-darwin)
v8 9.2.230.14
typescript 4.3.5
```

**Comment by kitsonk** [comment]
Your version of v8 is wrong for the build somehow. I would do a `cargo clean` and rebuild. These features were added in v8 9.3.

**Comment by F3n67u** [comment]
Test passed after a clean build: `cargo clean && cargo build`. Thanks @kitsonk
