### ISSUE TITLE
Need complete stack trace for unhandled promise rejections.

### ISSUE THREAD

**Issue by TradeIdeasPhilip** [denoland/deno#11859]
If you have un unhandled exception in a promise, that causes Deno to shut down.  Before shutting down it prints an error message like this:

```
error: Uncaught (in promise) Error: No such host is known. (os error 11001)
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.connect (deno:extensions/net/01_net.js:219:13)
```

The problem is that the stack trace doesn't point to any of _my_ code.  Normally when I see a stack trace it goes all the way back to my code.

I have also tried asking VS code to break on all exceptions.  Then I could see the stack trace live.  But VS Code / Deno ignored that request.

I would like something to help me find the source of this problem.  I can reproduce this problem at will, but I can't find the source of it.

[More details.](https://stackoverflow.com/questions/68811003/uncaught-in-promise-how-to-find-the-source-of-the-problem-in-a-deno-program?noredirect=1#comment121650904_68811003)

Thank you.

**Comment by TradeIdeasPhilip** [comment]
If I may beat a dead horse...  I ran into a similar problem in my browser just now.  
![image](https://user-images.githubusercontent.com/18409827/141170040-9389bff7-94f0-48e2-a9b4-1df3d8eb2fd9.png)
I'm missing a `.catch()` so chrome printed a stack trace.  It's a complete stack trace all the way from the `await` that received the `Error` to the main program.  It even uses the source maps to show me my TypeScript code.

It's helpful.  Chrome has figured out how to do it.  Thanks for taking a look.

**Comment by bartlomieju** [comment]
Let's revisit this issue

**Comment by jespertheend** [comment]
I'm running into a similar issue with a failing `fetch()`. If you save the following to a file and run it:
```js
fn1();

function fn1() {
  fn2();
}

async function fn2() {
  const response = await fetch("file:///does/not/exist/");
  console.log(await response.text());
}
```
it only prints:
```
error: Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
    at async mainFetch (deno:ext/fetch/26_fetch.js:280:14)
```
which is rather unhelpful. When running this in the console of Chrome on the other hand, you get a full stack trace and the failing url is logged:
![image](https://user-images.githubusercontent.com/2737650/157643139-e5d50a7c-a6b3-4f13-b9c4-191e1533095d.png)

**Comment by jeff-hykin** [comment]
A CLI flag such as `--traceAllPromises` that causes all promises to keep track of where they were constructed (and report it later) would be an interface I'd be more than happy to use.

Most of the time its not my code that's failing to await a promise, its some deeply nested library in the dependency tree I have no real way of searching for.

**Comment by jeff-hykin** [comment]
> Most of the time its not my code that's failing

[*cough cough*](https://github.com/lino-levan/astral/pull/142) @lino-levan

**Comment by bartlomieju** [comment]
Fixed on current `main`. Unhandled promise rejections now show the complete stack trace through user code:

```
error: Uncaught (in promise) Error: failed to lookup address information: ...
    at async Object.connect (ext:deno_net/01_net.js:712:11)
    at async innerConnect (file:///tmp/test.ts:2:3)
    at async outerFunction (file:///tmp/test.ts:6:3)
```

The full async call chain is visible, pointing to the user's code.
