### ISSUE TITLE
Using Promise.allSettled to stress test JSON API. Why do rejections increase on subsequent requests?

### ISSUE THREAD

**Issue by webdev3301** [denoland/deno#11893]
Good morning. I came up with the following code to stress test a simple JSON API.

I'm using Deno's `serve` as the server and in a separate script, as the client.
I'm using Windows 10 Pro with Deno 1.13.2

```ts
/*
  ACME HTTP Stress Tester 5000
*/
let promises: Promise<any>[] = [];
let fulfilled: number = 0;
let rejected: number = 0;

for (let i = 0; i < 3000; ++i) {
  // push fetch into array of promises
  promises.push(fetch('http://localhost:80/api/v1/index.json'));
}

// Execute test in Parallel
await Promise.allSettled(promises).then((results) => {

  results.forEach((result) => {
    if(result.status == 'fulfilled') fulfilled++;
    if(result.status == 'rejected') rejected++;
  });

  console.log(`
Total Requests:  ${results.length}
Total Fulfilled: ${fulfilled}
Total Rejected:  ${rejected}`);

});
```
Looking at the output you can see it starts great then begins to degrade in subsequent requests. Am I hitting some sort of network connection pool limit or am I doing it wrong?

```
C:\Users\nexlevel\.deno\bin>deno run --allow-all stress.ts

Total Requests:  3000
Total Fulfilled: 3000
Total Rejected:  0

C:\Users\nexlevel\.deno\bin>deno run --allow-all stress.ts

Total Requests:  3000
Total Fulfilled: 3000
Total Rejected:  0

C:\Users\nexlevel\.deno\bin>deno run --allow-all stress.ts

Total Requests:  3000
Total Fulfilled: 3000
Total Rejected:  0

C:\Users\nexlevel\.deno\bin>deno run --allow-all stress.ts

Total Requests:  3000
Total Fulfilled: 2012
Total Rejected:  988

C:\Users\nexlevel\.deno\bin>deno run --allow-all stress.ts

Total Requests:  3000
Total Fulfilled: 1662
Total Rejected:  1338

C:\Users\nexlevel\.deno\bin>deno run --allow-all stress.ts

Total Requests:  3000
Total Fulfilled: 794
Total Rejected:  2206

C:\Users\nexlevel\.deno\bin>deno run --allow-all stress.ts

Total Requests:  3000
Total Fulfilled: 367
Total Rejected:  2633

C:\Users\nexlevel\.deno\bin>deno run --allow-all stress.ts

Total Requests:  3000
Total Fulfilled: 242
Total Rejected:  2758
```
Ironically, if I just wait 10 seconds and run it again, it will once again fulfill all 3000 parallel requests.

The `Promise.allSettled` error:

    TypeError: error sending request for url (http://localhost/api/v1/index.json): error trying to connect: tcp connect error: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
        at deno:core/01_core.js:106:46
        at unwrapOpResult (deno:core/01_core.js:126:13)
        at async mainFetch (deno:ext/fetch/26_fetch.js:265:14)

**Comment by lucacasonato** [comment]
cc @piscisaureus as this is Windows related. Is it possible that this is related to port exhaustion?

**Comment by webdev3301** [comment]
Some more research. The following updated script has a 100% fulfillment rate.

```ts
/***
 *  ACME HTTP Stress Tester 5000
 * 
 */
let requests: Promise<any>[] = [];

const requestCount: number = 100;
const parallelCount: number = 3000;

let fulfilled: number = 0;
let rejected: number = 0;

for (let x = 0; x < requestCount; ++x) {

  for (let y = 0; y < parallelCount; ++y) {
    // Push fetch calls into Promise array of requests
    requests.push(fetch('http://localhost:80/api/v1/index.json'));
  }

  // Execute fetch calls in Parallel
  await Promise.allSettled(requests).then((results) => {

    results.forEach((result) => {
      if(result.status == 'fulfilled') fulfilled++;
      if(result.status == 'rejected') rejected++;
    });

    console.log('Total Requests:', results.length);
    console.log('Total Fulfilled:', fulfilled);
    console.log('Total Rejected:', rejected);
    console.log('— — — — — — — — — — — — — — — — — — — — ')

    /***
     *  Reset these global vars on every new request 
     *  containing 3000 parallel fetch calls
     * 
     */
    requests = [];
    fulfilled = 0;
    rejected = 0;

  });

}
```

**Comment by lucacasonato** [comment]
@piscisaureus We have a default agent that is used for connection pooling, but I think it doesn't have a max concurrency cap. In browsers there is a max HTTP/1.1 connection cap per origin of 6.

**Comment by piscisaureus** [comment]
> @piscisaureus We have a default agent that is used for connection pooling, but I think it doesn't have a max concurrency cap. In browsers there is a max HTTP/1.1 connection cap per origin of 6.

I see. Using HTTP2 would solve the issue, since it allows multiple *concurrent* fetches to run over the same TCP stream, right?

**Comment by lucacasonato** [comment]
Yes.

**Comment by webdev3301** [comment]
Perhaps a load balancer similar to NGINX?

```sh
upstream backend {

  # PHP-CGI GATEWAY LOAD BALANCER

  # Here we distribute requests using the round-robin method.
  # All weights are currently set to 3, 2, 1.

  # PHP-CGI GATEWAY 1 - listening on IPv4 & Port...
  server                127.0.0.1:9000 weight=3 max_fails=9 fail_timeout=1s;
  # PHP-CGI GATEWAY 2 - listening on IPv4 & Port...
  server                127.0.0.1:9001 weight=2 max_fails=6 fail_timeout=2s;
  # PHP-CGI GATEWAY 3 - listening on IPv4 & Port...
  server                127.0.0.1:9002 weight=1 max_fails=3 fail_timeout=3s;

} # END upstream backend
```
