### ISSUE TITLE
deno cache crashes on deno bundle output

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#11960]
## Repro

Create a file called `dog.ts` with this content:

```ts
const nameSymbol = Symbol('pet name')
export class Dog {
  private readonly [nameSymbol]: string
  constructor(name: string) {
    this[nameSymbol] = name
  }
}
```

Run

```sh
deno bundle dog.ts > dog.js
```

Create a file called `script.ts` with this content:

```
imoprt { Dog } from './dog.js'

console.log(typeof Dog)
```

Run

```sh
deno cache script.ts
```

## Expected behaviour

Deno caches the code successfully.

## Actual behaviour

```sh
error: Error: Debug Failure. False expression.
    at getConstructorDefinedThisAssignmentTypes (deno:cli/tsc/00_typescript.js:52650:22)
    at getWidenedTypeForAssignmentDeclaration (deno:cli/tsc/00_typescript.js:52485:90)
    at getTypeOfVariableOrParameterOrPropertyWorker (deno:cli/tsc/00_typescript.js:52871:24)
    at getTypeOfVariableOrParameterOrProperty (deno:cli/tsc/00_typescript.js:52802:28)
    at getTypeOfSymbol (deno:cli/tsc/00_typescript.js:53173:24)
    at checkVariableLikeDeclaration (deno:cli/tsc/00_typescript.js:77288:41)
    at checkPropertyDeclaration (deno:cli/tsc/00_typescript.js:75345:13)
    at checkSourceElementWorker (deno:cli/tsc/00_typescript.js:80061:28)
    at checkSourceElement (deno:cli/tsc/00_typescript.js:80029:17)
    at Object.forEach (deno:cli/tsc/00_typescript.js:384:30)
```

If I had to guess I would think that is a problem of `deno cache` which cannot parse the symbol declaration.

## System info

```sh
$ deno --version 
deno 1.13.2 (release, x86_64-unknown-linux-gnu)
v8 9.3.345.11
typescript 4.3.5
```

**Comment by kitsonk** [comment]
I can't reproduce this with Deno Canary (which has TypeScript 4.4 and where the error is originating from).

Could you try the following and see if the issue is resolved for you?

```
> deno upgrade --canary
```

**Comment by kitsonk** [comment]
(a workaround to get past the error if you don't want to upgrade would be to use the `--no-check` flag)

**Comment by KnorpelSenf** [comment]
I can confirm that upgrading to canary fixes the problem.

In the future, I would expect Deno to provide a more helpful error message about _which_ expression is false. Is it possible to log that along with the error? The crash occurred in a bundled source file containing several thousand lines of code.

**Comment by kitsonk** [comment]
@KnorpelSenf this isn't, sadly, something Deno can do... this is a defect with the TypeScript compiler itself that is embedded in Deno, and when it decides to fail its internal debug, we have no choice but to surface what is provided.

**Comment by KnorpelSenf** [comment]
That's understandable. Thanks for the clarification!
