### ISSUE TITLE
Panic when unhandled error in worker in worker

### ISSUE THREAD

**Issue by kuuote** [denoland/deno#12068]
# Repro step

1. Place following files

a.js:

```
new Worker(new URL("./b.js", import.meta.url).href, {type: "module"});
```

b.js:

```
new Worker(new URL("./c.js", import.meta.url).href, {type: "module"});
```

c.js:
```
throw Error();
```

2. Run `deno run --allow-read a.js`

# Problem

Panic with this error.

```
error: Uncaught (in worker "") Error
throw Error();
      ^
    at file:///home/arch/c.js:1:7
thread 'worker-0' panicked at 'coding error: either js is polling or the worker is terminated', runtime/web_worker.rs:531:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Uncaught (in promise) Error: Unhandled error event reached main worker.
    at Worker.#pollControl (deno:runtime/js/11_workers.js:261:23)
```

# Expected

I want to occurs JS Error similar to case of only one worker.

```
error: Uncaught (in worker "") Error
throw Error();
      ^
    at file:///home/arch/b.js:1:7
error: Uncaught (in promise) Error: Unhandled error event reached main worker.
    at Worker.#pollControl (deno:runtime/js/11_workers.js:261:23)
```

# Environment

```
deno 1.13.2 (release, x86_64-unknown-linux-gnu)
v8 9.3.345.11
typescript 4.3.5
```

**Comment by bartlomieju** [comment]
CC @andreubotella

**Comment by andreubotella** [comment]
This is the same panic as in #11342, and probably related to the nested worker case in https://github.com/denoland/deno/issues/11342#issuecomment-918327693

**Comment by bartlomieju** [comment]
Thanks, closing in favor of #11342
