### ISSUE TITLE
Is there a command like `npm explain` or `yarn why`?

### ISSUE THREAD

**Issue by disjukr** [denoland/deno#12082]
As the deno version is upgraded to 1.14.0, an error occurs in the following module, I wonder why this module was installed.

```sh
❯ deno run ...blabla
Check file:///...blabla
error: TS2801 [ERROR]: This condition will always return true since this 'Promise<Deno.PermissionStatus>' is always defined.
  if (Deno.permissions.query({ name: "env" })) {
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/tty@0.1.2/is_interactive.ts:2:7

TS2773 [ERROR]:     Did you forget to use 'await'?
      if (Deno.permissions.query({ name: "env" })) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/tty@0.1.2/is_interactive.ts:2:7
```

The `deno info` command didn't give me the info I needed.
```sh
❯ deno info https://deno.land/x/tty@0.1.2/is_interactive.ts
local: /Users/me/Library/Caches/deno/deps/https/deno.land/26e835f96821d84b7a10ed84ee8bf125c1bf7bbdbf8f1cfc5cd8b03d96a83ae0
type: TypeScript
emit: /Users/me/Library/Caches/deno/gen/https/deno.land/26e835f96821d84b7a10ed84ee8bf125c1bf7bbdbf8f1cfc5cd8b03d96a83ae0.js
dependencies: 0 unique (total 275B)

https://deno.land/x/tty@0.1.2/is_interactive.ts (275B)
```

**Comment by bartlomieju** [comment]
There's not. If you specify your entry point to `deno info` it will print the whole dependency graph and you'll be able to see what imports this file.
