### ISSUE TITLE
Bug macOS: Panic when trying to upgrade a websocket with std/http

### ISSUE THREAD

**Issue by lucsoft** [denoland/deno#12098]
This panic only works with std/http over native http it doesn't panic

**Info**
deno 1.14.0+868f38d (canary, x86_64-apple-darwin)
macOS 11.6 (20G165)

**Code**
```ts
import { listenAndServe } from "https://deno.land/std@0.107.0/http/server.ts";
listenAndServe(":1000", (event) => {
    const { response } = Deno.upgradeWebSocket(event);
    return response;
})
const ws = new WebSocket("ws://localhost:1000")
ws.onopen = console.log
```

**Error**
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.12/src/server/conn.rs:1226:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lucacasonato** [comment]
@bartlomieju This looks like a double poll, or poll after close situation. Probably in `op_http_next_request`.

**Comment by bartlomieju** [comment]
> @bartlomieju This looks like a double poll, or poll after close situation. Probably in `op_http_next_request`.

Indeed, it looks like poll after close, relevant code that panics:

https://github.com/hyperium/hyper/blob/f46b175bf71b202fbb907c4970b5743881b891e1/src/server/conn.rs#L1226

**Comment by sant123** [comment]
@lucacasonato Do you know how to reproduce it without `std/http`? I'm taking a look at the code but looks pretty related. 

I'm curious 🤔

**Comment by ayame113** [comment]
Additional information

1. This is also happening on windows.
2. Error message when running with `RUST_BACKTRACE=full`

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.12\src\server\conn.rs:1226:64
stack backtrace:
   0:     0x7ff681b47224 - <unknown>
   1:     0x7ff68130b9ba - <unknown>
   2:     0x7ff681b454a8 - <unknown>
   3:     0x7ff681b462f2 - <unknown>
   4:     0x7ff681b45922 - <unknown>
   5:     0x7ff6812c2c0a - <unknown>
   6:     0x7ff681b452df - <unknown>
   7:     0x7ff681b4db1b - <unknown>
   8:     0x7ff681b4da9f - <unknown>
   9:     0x7ff681b4da3f - <unknown>
  10:     0x7ff682bf2020 - CrashForExceptionInNonABICompliantCodeRange
  11:     0x7ff682bf217c - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff6815d5717 - <unknown>
  13:     0x7ff681420ac8 - <unknown>
  14:     0x7ff68142c983 - <unknown>
  15:     0x7ff681572b59 - <unknown>
  16:     0x7ff6813b894c - <unknown>
  17:     0x7ff6813b1de8 - <unknown>
  18:     0x7ff680f04afc - <unknown>
  19:     0x7ff680ef83cd - <unknown>
  20:     0x7ff681023541 - <unknown>
  21:     0x7ff6810224c5 - <unknown>
  22:     0x7ff680ecdfb2 - <unknown>
  23:     0x7ff680eb7942 - <unknown>
  24:     0x7ff680eb35f1 - <unknown>
  25:     0x7ff680eb3693 - <unknown>
  26:     0x7ff682ba77fc - CrashForExceptionInNonABICompliantCodeRange
  27:     0x7ffb3a507034 - BaseThreadInitThunk
  28:     0x7ffb3b5a2651 - RtlUserThreadStart
```
3. Code to reproduce without using `std/http`

    If I delete the `await` line (★) here, it works correctly.

```ts
const server = Deno.listen({ port: 8080 });

const ws = new WebSocket("ws://localhost:8080");
ws.onopen = console.log;

for await (const conn of server) {
  handle(conn);
}

async function handle(conn: Deno.Conn) {
  const httpConn = Deno.serveHttp(conn);
  for await (const requestEvent of httpConn) {
    (async () => {
      const response = handleReq(requestEvent.request);
      await Promise.resolve(); // (★) Without this line, no panic will occur
      requestEvent.respondWith(response);
    })();
  }
}

function handleReq(req: Request): Response {
  if (req.headers.get("upgrade") != "websocket") {
    return new Response("request isn't trying to upgrade to websocket.");
  }
  const { socket, response } = Deno.upgradeWebSocket(req);
  socket.onmessage = (e) => {
    console.log("socket message:", e.data);
    socket.send(new Date().toString());
  };
  return response;
}
```

On `std/http`, I think the line `await this.#handler` in `async #respond()` is causing the panic.
https://github.com/denoland/deno_std/blob/7a1db16dba9cc4fb1f01f0731ef35d80230ae256/http/server.ts#L343-351

**Comment by retog** [comment]
> @lucacasonato Do you know how to reproduce it without `std/http`? I'm taking a look at the code but they are more or less the same.
> 

This code gives the error without using std/http (note that the error only occurs when "flattening" the async iterator of async iterators, not when using nested for-awaits):

```typescript
const never = function <T>() {
  return new Promise<T>(
    () => {},
  );
};

function getNext<T>(asyncIterator: AsyncIterator<T>, index: number) {
  return asyncIterator.next().then((result) => ({
    index,
    result,
  }));
}

function flatten<T>(
  outer: AsyncIterator<AsyncIterator<T>>,
): AsyncIterator<T> {
  const innerIterators: AsyncIterator<T>[] = [];
  const innerIteratorsNexts: Promise<
    { index: number; result: IteratorResult<T> }
  >[] = innerIterators.map(getNext);
  let outerNext: Promise<IteratorResult<AsyncIterator<T>>> = outer.next();
  let finishedIterators = 0;
  return {
    next: () => {
      const iteration: () => Promise<IteratorResult<T>> = async () => {
        if (finishedIterators < (innerIterators.length + 1)) {
          const nextEvent = await Promise.race([
            outerNext,
            ...innerIteratorsNexts,
          ]);
          if ("index" in nextEvent) {
            //an actual result
            if (nextEvent.result.done) {
              innerIteratorsNexts[nextEvent.index] = never();
              finishedIterators++;
              return iteration();
            } else {
              innerIteratorsNexts[nextEvent.index] = getNext(
                innerIterators[nextEvent.index],
                nextEvent.index,
              );
              return nextEvent.result;
            }
          } else {
            //a new inner iterator
            if (nextEvent.done) {
              finishedIterators++;
              outerNext = never<IteratorResult<AsyncIterator<T>>>();
            } else {
              innerIterators.push(nextEvent.value);
              innerIteratorsNexts.push(getNext(
                nextEvent.value,
                innerIteratorsNexts.length,
              ));
              outerNext = outer.next();
            }
            return iteration();
          }
        } else {
          return { done: true, value: undefined };
        }
      };
      return iteration();
    },
  };
}

const getHttpConnections = async function* () {
  const server = Deno.listen({ port: 8888 });
  for await (const conn of server) {
    yield Deno.serveHttp(conn)[Symbol.asyncIterator]();
  }
};
const httpRequests = flatten(getHttpConnections()[Symbol.asyncIterator]());

function handleReq(req: Request): Response {
  if (req.headers.get("upgrade") != "websocket") {
    return new Response("request isn't trying to upgrade to websocket.");
  }
  const { socket, response } = Deno.upgradeWebSocket(req);
  socket.onopen = () => console.log("socket opened");
  socket.onmessage = (e) => {
    console.log("socket message:", e.data);
    socket.send(new Date().toString());
  };
  socket.onerror = (e) => console.log("socket errored:", e);
  socket.onclose = () => console.log("socket closed");
  return response;
}

for await (
  const requestEvent of { [Symbol.asyncIterator]: () => httpRequests }
) {
  await requestEvent.respondWith(handleReq(requestEvent.request));
}
```

**Comment by sant123** [comment]
😮

**Comment by kt3k** [comment]
Seems like this is now fixed in main (might be related to #12385)

```shellsession
$ deno1.15.1.6337918 -V       
deno 1.15.1+6337918
$ cat test.js                    
import { listenAndServe } from "https://deno.land/std@0.107.0/http/server.ts";
listenAndServe(":1000", (event) => {
    const { response } = Deno.upgradeWebSocket(event);
    return response;
})
const ws = new WebSocket("ws://localhost:1000")
ws.onopen = console.log
$ deno1.15.1.6337918 run -A test.js
Check file:///Users/kt3k/denoland/deno_std/test.js
Event {
  bubbles: false,
  cancelable: false,
  composed: false,
  currentTarget: WebSocket {
```
