### ISSUE TITLE
flock tests are flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#12094]
Based on how the test is written, probably flockFileSync is flaky too.

```
error: Test failed
failures:

flockFileAsync
AssertionError: shared does not block shared
    at assertEquals (file:///D:/a/deno/deno/test_util/std/testing/asserts.ts:271:9)
    at flockFileAsync (file:///D:/a/deno/deno/cli/tests/unit/flock_test.ts:96:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async applyPermissions (deno:runtime/js/40_testing.js:124:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:299:22)

failures:

	flockFileAsync
```

**Comment by dsherret** [comment]
Still not good on the CI 😅

```
error: Test failed

failures:

flockFileAsync
AssertionError: shared does not block shared
    at assertEquals (file:///D:/a/***/***/test_util/std/testing/asserts.ts:271:9)
    at runFlockTests (file:///D:/a/***/***/cli/tests/unit/flock_test.ts:47:3)
    at async flockFileAsync (file:///D:/a/***/***/cli/tests/unit/flock_test.ts:15:5)
    at async asyncOpSanitizer (***:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (***:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (***:runtime/js/40_testing.js:99:9)
    at async applyPermissions (***:runtime/js/40_testing.js:124:9)
    at async runTest (***:runtime/js/40_testing.js:215:7)
    at async Object.runTests (***:runtime/js/40_testing.js:299:22)

failures:

	flockFileAsync
```

**Comment by ry** [comment]
This is still happening
```
2021-09-28T10:40:15.9309637Z [0m[1m[31merror[0m: Test failed
2021-09-28T10:40:15.9311573Z failures:
2021-09-28T10:40:15.9313045Z 
2021-09-28T10:40:15.9397182Z flockFileAsync
2021-09-28T10:40:15.9407236Z AssertionError: shared does not block shared
2021-09-28T10:40:15.9409877Z     at assertEquals (file:///D:/a/***/***/test_util/std/testing/asserts.ts:271:9)
2021-09-28T10:40:15.9417974Z     at runFlockTests (file:///D:/a/***/***/cli/tests/unit/flock_test.ts:47:3)
2021-09-28T10:40:15.9671307Z     at async flockFileAsync (file:///D:/a/***/***/cli/tests/unit/flock_test.ts:15:5)
2021-09-28T10:40:15.9682459Z     at async asyncOpSanitizer (***:runtime/js/40_testing.js:35:9)
2021-09-28T10:40:15.9684571Z     at async resourceSanitizer (***:runtime/js/40_testing.js:72:7)
2021-09-28T10:40:15.9685935Z     at async exitSanitizer (***:runtime/js/40_testing.js:99:9)
2021-09-28T10:40:15.9687224Z     at async applyPermissions (***:runtime/js/40_testing.js:124:9)
2021-09-28T10:40:15.9688456Z     at async runTest (***:runtime/js/40_testing.js:215:7)
2021-09-28T10:40:15.9689700Z     at async Object.runTests (***:runtime/js/40_testing.js:299:22)
2021-09-28T10:40:15.9690563Z 
2021-09-28T10:40:15.9691312Z failures:
2021-09-28T10:40:15.9691835Z 
2021-09-28T10:40:15.9692564Z 	flockFileAsync
2021-09-28T10:40:15.9693114Z 
2021-09-28T10:40:15.9694448Z test result: [0m[31mFAILED[0m. 829 passed; 1 failed; 51 ignored; 0 measured; 0 filtered out [0m[38;5;8m(100989ms)[0m
2021-09-28T10:40:15.9695290Z 
2021-09-28T10:40:16.1008088Z test integration::run::_042_dyn_import_evalcontext ... ok
2021-09-28T10:40:16.1793028Z test integration::js_unit_tests ... FAILED
```
https://github.com/denoland/deno/runs/3731206016
