### ISSUE TITLE
tools: permission denies accessing cargo

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12174]
The `03_bump_cli_version.ts` has the following:

```
#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run="cargo,git"
```

But when run from the command line, you still get a permission error saying accessing `cargo` is not allowed.

**Comment by dsherret** [comment]
Works on Windows 😅

**Comment by kitsonk** [comment]
Looks like on *NIX you need to not quote. The following works... I will raise a PR.

```
#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run=cargo,git
```

**Comment by dsherret** [comment]
Hmmm... a bug in my binary version manager tool (it's requiring quotes). Sorry for the bother!

```ts
> deno run --allow-read --allow-write --allow-run="cargo,git" ./tools/release/03_bump_cli_version.ts
Check file:///V:/deno/tools/release/03_bump_cli_version.ts
Increment patch? [y/N]
> deno run --allow-read --allow-write --allow-run=cargo,git ./tools/release/03_bump_cli_version.ts
error: Uncaught PermissionDenied: Requires run access to "cargo", run again with the --allow-run flag
  const p = Deno.run({
                 ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at opRun (deno:runtime/js/40_process.js:27:17)
    at Object.run (deno:runtime/js/40_process.js:114:17)
    at runCommand (file:///V:/deno/tools/release/helpers/helpers.ts:44:18)
    at Module.getMetadata (file:///V:/deno/tools/release/helpers/cargo.ts:29:24)
    at Function.load (file:///V:/deno/tools/release/helpers/deno_workspace.ts:20:19)
    at file:///V:/deno/tools/release/03_bump_cli_version.ts:9:39
> V:\deno\target\debug\deno.exe run --allow-read --allow-write --allow-run=cargo,git ./tools/release/03_bump_cli_version.ts
Increment patch? [y/N]
```
