### ISSUE TITLE
`/websockets/stream/tentative/abort.any.html?wpt_flags=h2` is flaky

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#12208]
In #12206 I was enabling WPT tests that were disabled, and `/websockets/stream/tentative/abort.any.html?wpt_flags=h2` seems to be flaky.

On my machine the test as a whole fails with an uncaught rejection:
```
error: Uncaught (in promise) NetworkError: failed to connect to WebSocket: WebSocket protocol error: httparse error: invalid HTTP version
    at DOMExceptionNetworkError (deno:runtime/js/99_main.js:273:16)
    at unwrapOpResult (deno:core/01_core.js:126:13)
```

On CI the test file as a whole succeeds, but on some run all tests fail, and on others only "abort after connect should do nothing" succeeds. For the "abort after connect should do nothing" failure (but probably also for the other two tests), [the error is still the same, except this time it's not unhandled:](https://github.com/denoland/deno/runs/3698588514#step:40:18954)
```
promise_test: Unhandled rejection with value: object "NetworkError: failed to connect to WebSocket: WebSocket protocol error: httparse error: invalid HTTP version"
Error
    at get_stack (http://web-platform.test:8000/resources/testharness.js:3811:21)
    at new AssertionError (http://web-platform.test:8000/resources/testharness.js:3804:22)
    at assert (http://web-platform.test:8000/resources/testharness.js:3794:19)
    at Test.<anonymous> (http://web-platform.test:8000/resources/testharness.js:694:29)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:2117:25)
    at http://web-platform.test:8000/resources/testharness.js:2144:35
```

**Comment by lucacasonato** [comment]
https://github.com/denoland/deno/pull/12260/checks?check_run_id=3737837878 <- another one here
