### ISSUE TITLE
ext/http error: Uncaught (in promise) BadResource: Bad resource ID

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#12251]
### `boom2.js`

```js
// deno run -A --unstable recverror.js

import { assert } from "https://deno.land/std@0.108.0/testing/asserts.ts";

await Promise.all([serve(), curl()]);

async function serve() {
  const listener = Deno.listen({ port: 8000 });
  const conn = await listener.accept();
  const http = Deno.serveHttp(conn);

  let i = 0;
  for (;;) {
    const req = await http.nextRequest();
    if (req == null) break;

    req.respondWith((async () => {
      await delay(10);
      const res = new Response(`Response #${++i}`);
      await delay(10);
      return res;
    })());
  }
}

async function curl() {
  const proc = Deno.run({
    cmd: ["curl", "--http2-prior-knowledge", "http://localhost:8000/?[0-999]"],
  });
  await delay(200);
  proc.kill("SIGKILL");
  const status = await proc.status();
  assert(!status.success);
}

async function delay(ms) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}
```

### Output

```
piscisaureus@dumbo:~/d/deno 🦕 ./target/debug/deno run -A --unstable boom2.js

[1/1000]: http://localhost:8000/?0 --> <stdout>
--_curl_--http://localhost:8000/?0
Response #1
[2/1000]: http://localhost:8000/?1 --> <stdout>
--_curl_--http://localhost:8000/?1
Response #2
[3/1000]: http://localhost:8000/?2 --> <stdout>
--_curl_--http://localhost:8000/?2
Response #3
[4/1000]: http://localhost:8000/?3 --> <stdout>
--_curl_--http://localhost:8000/?3
Response #4
[5/1000]: http://localhost:8000/?4 --> <stdout>
--_curl_--http://localhost:8000/?4
Response #5
[6/1000]: http://localhost:8000/?5 --> <stdout>
--_curl_--http://localhost:8000/?5
Response #6
[7/1000]: http://localhost:8000/?6 --> <stdout>
--_curl_--http://localhost:8000/?6
error: Uncaught (in promise) BadResource: Bad resource ID
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:ext/http/01_http.js:199:27)
```

**Comment by leizongmin** [comment]
I try to simplify the above codes:

```ts
// deno run -A --unstable demo.js

await Promise.all([serve(), curl()]);

async function serve() {
  const listener = Deno.listen({port: 8000});
  const conn = await listener.accept();
  const http = Deno.serveHttp(conn);
  for (; ;) {
    const req = await http.nextRequest();
    if (req == null) break;

    req.respondWith((async () => {
      await delay(20);
      return new Response(`Hello`);
    })());
  }
}

async function curl() {
  const proc = Deno.run({
    cmd: ["curl", "--http2-prior-knowledge", "http://localhost:8000/?[1-1000]"],
  });
  await delay(10);
  proc.kill("SIGKILL");
}

async function delay(ms) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}
```

The process will outputs `error: Uncaught (in promise) BadResource: Bad resource ID`. 
Because `curl` command was killed _(delay 10ms)_ before `req.respondWith()`_(delay 20ms)_.

If add an `await` to the `req.responseWith()`, the process will exit normally without any errors:

```ts
await req.respondWith((async () => {
  await delay(20);
  return new Response(`Hello`);
})());
```

**Comment by leizongmin** [comment]
And there is a very stranger problem:  `try ... catch` statement cannot catch the error:

```ts
try {
  await http.nextRequest();
} catch (err) {
  console.log("catch error", err);
}
```

will still outputs (with exit code 1):

```
error: Uncaught (in promise) BadResource: Bad resource ID
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:ext/http/01_http.js:199:27)
```

**Comment by F3n67u** [comment]
This also can be fixed by changing

```
    req.respondWith((async () => {
      await delay(10);
      const res = new Response(`Response #${++i}`);
      await delay(10);
      return res;
    })());
```
to
```
      await delay(10);
      const res = new Response(`Response #${++i}`);
      await delay(10);
      req.respondWith(res);
```

**Comment by qballer** [comment]
it seems like I'm encountering this bug as well while trying to benchmark Deno here. I could've missed something. https://github.com/TechEmpower/FrameworkBenchmarks/pull/6892

When running 
```./tfb --test deno-mongodb-raw --mode debug```

I will get 
```
deno-mongodb-raw: error: Uncaught (in promise) BadResource: Bad resource ID
deno-mongodb-raw:     at Object.respondWith (deno:ext/http/01_http.js:217:19)
```

**Comment by bartlomieju** [comment]
@qballer which Deno version are you using?

**Comment by qballer** [comment]
1.16.0

**Comment by qballer** [comment]
Just validated with 1.16.0 
<img width="1559" alt="Screen Shot 2021-11-10 at 21 40 27" src="https://user-images.githubusercontent.com/1002622/141181999-fc3dc5ab-d732-4da7-8506-8b42d7df6b35.png">

**Comment by bartlomieju** [comment]
This issue will be fixed by https://github.com/denoland/deno/pull/12732#pullrequestreview-803201492 which we hope to release in 1.16.1 tomorrow.

**Comment by qballer** [comment]
as soon as the docker container for Deno is released I will test my use case to see if the issue is gone. Thanks!

**Comment by qballer** [comment]
<img width="1588" alt="Screen Shot 2021-11-11 at 17 04 05" src="https://user-images.githubusercontent.com/1002622/141320714-cb2f45af-8213-402b-bd4f-4031efbd898a.png">

**Comment by piscisaureus** [comment]
> Could this be unrelated to this issue? it's still happening.

I think it is unrelated, indeed.
