### ISSUE TITLE
httpServerIncompleteMessage is flaky

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12388]
httpServerIncompleteMessage
AssertionError: Values are not equal:
error: Test failed

    [Diff] Actual / Expected

-   connection error:Connectionresetbypeer(oserror54)
+   connection closedbeforemessagecompleted

    at assertEquals (file:///Users/runner/work/***/***/test_util/std/testing/asserts.ts:271:9)
    at httpServerIncompleteMessage (file:///Users/runner/work/***/***/cli/tests/unit/http_test.ts:866:7)
    at async asyncOpSanitizer (***:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (***:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (***:runtime/js/40_testing.js:99:9)
    at async applyPermissions (***:runtime/js/40_testing.js:124:9)
    at async runTest (***:runtime/js/40_testing.js:232:7)
    at async Object.runTests (***:runtime/js/40_testing.js:317:22)

failures:

	httpServerIncompleteMessage

test result: FAILED. 868 passed; 1 failed; 21 ignored; 0 measured; 0 filtered out (118626ms)

**Comment by lucacasonato** [comment]
https://github.com/denoland/deno/runs/5209954629?check_suite_focus=true
