### ISSUE TITLE
webgpuComputePass test is flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#12431]
```
webgpuComputePass
AssertionError: Test case is leaking resources.
Before: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr"
}
After: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr",
  "3": "webGPUAdapter"
}

Make sure to close all open resource handles returned from Deno APIs before
finishing test case.
    at assert (deno:runtime/js/06_util.js:41:13)
    at resourceSanitizer (deno:runtime/js/40_testing.js:128:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:144:9)
    at async Object.applyPermissions [as fn] (deno:runtime/js/40_testing.js:245:9)
    at async runTest (deno:runtime/js/40_testing.js:349:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:460:22)

failures:

	webgpuComputePass
```

Failed on Windows. Maybe this does not close the right resource sometimes?

https://github.com/denoland/deno/blob/43a63530acb16e57cbb190eacedbd097c536a775/cli/tests/unit/webgpu_test.ts#L98

**Comment by lucacasonato** [comment]
This test has been re-enabled.
