### ISSUE TITLE
Deno.emit crashes with `BorrowMutError`

### ISSUE THREAD

**Issue by bebraw** [denoland/deno#12453]
I've been developing a small static site generator on top of Deno and I ran into a mysterious little issue. In my work, I'm leveraging `Deno.emit` to bundle client side JavaScript. Interestingly enough doing this results in a `BorrowMutError` during my build on Netlify Ubuntu but not on MacOS.

Here are instructions on how to reproduce the issue on your machine:

1. Clone https://github.com/survivejs/gustwind . I know at least using commit cf226922b80 can reproduce the issue and most likely even current `master` will do.
2. Clone https://github.com/netlify/build-image
3. `cd build-image`
4. `./test-tools/start-image.sh ../gustwind` (assuming you cloned the first repo to a sibling directory)
5. After running the image, run `/opt/build-bin/build "curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.15.1 && RUST_BACKTRACE=1 /opt/buildhome/.deno/bin/deno run --unstable --no-check --import-map=import_map.json -A ./src/build.ts"`
6. You should see the trace below:

```
thread 'main' panicked at 'already borrowed: BorrowMutError', core/bindings.rs:423:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
   4: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
             at ./../../../../v8/src/api/api-arguments-inl.h:152:3
   5: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
             at ./../../../../v8/src/builtins/builtins-api.cc:112:36
   6: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
             at ./../../../../v8/src/builtins/builtins-api.cc:142:5
   7: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
```

Note that you'll need a recent version of Docker to run the image.

If you remove `pages/playground.ts`, the issue should vanish as then it's not triggering `Deno.emit` anymore. That led me to believe there's some problem with the command. I'm aware the API will likely vanish so I'm happy if you can point me to an alternative way of bundling TS in a Deno environment and then this issue might become a `wontfix`.

Let me know if you need any further information.

**Comment by irbull** [comment]
The snippet I posted above no longer exhibits the problem, but it does still need to happen in my program with 1.15.3. Here is the full trace I'm getting. I'll see if I can put together another minimal snippet that demonstrates this:

```
thread 'main' panicked at 'already borrowed: BorrowMutError', /Users/runner/work/deno/deno/core/ops_json.rs:62:43
stack backtrace:
   0:        0x108076a43 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d168763f08a78b9
   1:        0x1079386bc - core::fmt::write::h0fa46d4891ed63f1
   2:        0x10807493a - std::io::Write::write_fmt::hacbf9e10e17149ce
   3:        0x108075b7f - std::panicking::default_hook::{{closure}}::hee7cf38dedfa76fc
   4:        0x108074d4d - std::panicking::default_hook::hd12252412832a45f
   5:        0x1078f3651 - deno::setup_exit_process_panic_hook::{{closure}}::h080aa49274f758ea
   6:        0x1080747e9 - std::panicking::rust_panic_with_hook::h521fd09e07057893
   7:        0x108092eea - std::panicking::begin_panic_handler::{{closure}}::h3588a5a9cca9e8e5
   8:        0x108092e58 - std::sys_common::backtrace::__rust_end_short_backtrace::h86522c151a195ff9
   9:        0x108092e00 - _rust_begin_unwind
  10:        0x1091d7c3f - core::panicking::panic_fmt::h8ab5bf5f27d0a26a
  11:        0x1091d7f25 - core::result::unwrap_failed::ha249df8fad19d4e8
  12:        0x107bb1891 - deno_core::ops_json::op_sync::{{closure}}::hc6c3193a288613a1
  13:        0x1079bedaf - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb8218fc046e4c2b8
  14:        0x1079b448f - deno_core::ops::OpTable::route_op::hcaf0d19e6698686f
  15:        0x1079c4427 - <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn::h54d721405ef7f580
  16:        0x1084672f5 - __ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  17:        0x1084668e1 - __ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  18:        0x108465e4e - __ZN2v8
```

**Comment by irbull** [comment]
Looks like it's a combination of `Deno.emit` with a clean cache and a webserver. Here is a little snippet that demonstrates the problem. You need to run this with a clean cache (`-r`).

```
RUST_BACKTRACE=full deno run --unstable -A -r src/emit-issue.ts
```

```
// src/emit-issue.ts
import { listenAndServe } from 'https://deno.land/std@0.113.0/http/server.ts';

console.log('🦖 Deno Version:', Deno.version);
listenAndServe(':8000', () => {
  Deno.emit('https://deno.land/std/datetime/mod.ts');
  return new Response('ok');
});
```

And this is the log:
```
Download https://deno.land/std@0.113.0/http/server.ts
Download https://deno.land/std@0.113.0/async/mod.ts
Download https://deno.land/std@0.113.0/async/deadline.ts
Download https://deno.land/std@0.113.0/async/debounce.ts
Download https://deno.land/std@0.113.0/async/deferred.ts
Download https://deno.land/std@0.113.0/async/delay.ts
Download https://deno.land/std@0.113.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.113.0/async/pool.ts
Download https://deno.land/std@0.113.0/async/tee.ts
Check file:///Users/irbull/git/low-code/mediform/tenant-controller/src/emit-issue.ts
🦖 Deno Version: { deno: "1.15.3", v8: "9.5.172.19", typescript: "4.4.2" }
Download https://deno.land/std/datetime/mod.ts
thread 'main' panicked at 'already borrowed: BorrowMutError', ext/http/lib.rs:408:6
stack backtrace:
   0:        0x102317a43 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d168763f08a78b9
   1:        0x101bd96bc - core::fmt::write::h0fa46d4891ed63f1
   2:        0x10231593a - std::io::Write::write_fmt::hacbf9e10e17149ce
   3:        0x102316b7f - std::panicking::default_hook::{{closure}}::hee7cf38dedfa76fc
   4:        0x102315d4d - std::panicking::default_hook::hd12252412832a45f
   5:        0x101b94651 - deno::setup_exit_process_panic_hook::{{closure}}::h080aa49274f758ea
   6:        0x1023157e9 - std::panicking::rust_panic_with_hook::h521fd09e07057893
   7:        0x102333eea - std::panicking::begin_panic_handler::{{closure}}::h3588a5a9cca9e8e5
   8:        0x102333e58 - std::sys_common::backtrace::__rust_end_short_backtrace::h86522c151a195ff9
   9:        0x102333e00 - _rust_begin_unwind
  10:        0x103478c3f - core::panicking::panic_fmt::h8ab5bf5f27d0a26a
  11:        0x103478f25 - core::result::unwrap_failed::ha249df8fad19d4e8
  12:        0x101cee195 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h22dea0523f82d3b6
  13:        0x101ceaba5 - deno_core::ops_json::op_async::{{closure}}::h31d4f6dbd31b1dd2
  14:        0x101c5fdaf - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb8218fc046e4c2b8
  15:        0x101c5548f - deno_core::ops::OpTable::route_op::hcaf0d19e6698686f
  16:        0x101c66580 - <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn::hfbef0cfc7148e96d
  17:        0x1027082f5 - __ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  18:        0x1027078e1 - __ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  19:        0x102706e4e - __ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
```

**Comment by irbull** [comment]
This certainly isn't urgent for me. I've removed our use of `Deno.emit`, but it likely shows there is some condition with a Borowed Mutex leading to a system panic. Should I file a new issue for this, or do you think it's related and the snippet can stay here?

**Comment by AaronO** [comment]
> This certainly isn't urgent for me. I've removed our use of `Deno.emit`, but it likely shows there is some condition with a Borowed Mutex leading to a system panic. Should I file a new issue for this, or do you think it's related and the snippet can stay here?

I mentioned this in #12525:
> We'll probably want to rethink OpState, since variants of Deno.emit crashes with BorrowMutError #12453 could happen if OpState is mutably borrowed across an await (took a quick look and didn't see any instances of it in the codebase)

I'll submit a PR changing how we pass OpState around to fix this.

**Comment by dgreensp** [comment]
In case it's useful data, I just encountered this crash.

I was able to work around it by repopulating the cache from VS Code (`> Deno: Cache Dependencies` after opening all the files that import remote modules).

I'm glad it's already fixed!  Nice!
