### ISSUE TITLE
md file causing extension to crash

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#12465]
I had some difficulty with getting a minimum reproduction path but here is a video of the issue happening whenever I scroll or click anywhere in the typescript file. In the video, you can see the extension has no issue with the mod.ts until the README.txt file's extension is changed to md. Then they start happening whenever I click or type anything in the mod.ts file.

https://user-images.githubusercontent.com/3241653/137607071-1db7f9f3-24fb-4201-bfa1-3018fbcc5b85.mp4

I'm not exactly sure what about the text in the README.md file causes it. If I delete line 2 the errors goes away.

## Files

README.md

```md

If a Node.js package has the type "module" specified in its package.json file,
the JavaScript bundle can be imported as a `.js` file.

```

mod.ts

```ts
export const x = 5;
```

.vscode/settings.json

```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": false,
  "deno.suggest.imports.hosts": {
    "https://deno.land": true
  }
}
```

### Deno Language Server output

Here is the start of the output. 

```
Starting Deno language server...
  version: 1.15.1 (release, x86_64-unknown-linux-gnu)
  executable: /home/kyle/.deno/bin/deno
Connected to "Visual Studio Code" 1.61.1
Enabling import suggestions for: https://deno.land
language server initialized
Server ready.
Failed to request to tsserver Error: Debug Failure.
    at deno:cli/tsc/00_typescript.js:19487:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (deno:cli/tsc/00_typescript.js:19487:21)
    at Object.createDetachedDiagnostic (deno:cli/tsc/00_typescript.js:19503:20)
    at parseErrorAtPosition (deno:cli/tsc/00_typescript.js:30898:42)
    at parseErrorAt (deno:cli/tsc/00_typescript.js:30905:13)
    at parseErrorAtCurrentToken (deno:cli/tsc/00_typescript.js:30892:13)
    at parseErrorForInvalidName (deno:cli/tsc/00_typescript.js:31130:17)
    at parseErrorForMissingSemicolonAfter (deno:cli/tsc/00_typescript.js:31102:21)
    at parseExpressionOrLabeledStatement (deno:cli/tsc/00_typescript.js:34992:21)
[Error - 8:45:27 PM] Request textDocument/codeAction failed.
  Message: Invalid request
  Code: -32600 
Failed to request to tsserver Error: Debug Failure.
    at deno:cli/tsc/00_typescript.js:19487:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (deno:cli/tsc/00_typescript.js:19487:21)
    at Object.createDetachedDiagnostic (deno:cli/tsc/00_typescript.js:19503:20)
    at parseErrorAtPosition (deno:cli/tsc/00_typescript.js:30898:42)
    at parseErrorAt (deno:cli/tsc/00_typescript.js:30905:13)
    at parseErrorAtCurrentToken (deno:cli/tsc/00_typescript.js:30892:13)
    at parseErrorForInvalidName (deno:cli/tsc/00_typescript.js:31130:17)
    at parseErrorForMissingSemicolonAfter (deno:cli/tsc/00_typescript.js:31102:21)
    at parseExpressionOrLabeledStatement (deno:cli/tsc/00_typescript.js:34992:21)
[Error - 8:45:34 PM] Request textDocument/semanticTokens/full failed.
  Message: Invalid request
  Code: -32600 
Failed to request to tsserver Error: Debug Failure.
    at deno:cli/tsc/00_typescript.js:19487:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (deno:cli/tsc/00_typescript.js:19487:21)
    at Object.createDetachedDiagnostic (deno:cli/tsc/00_typescript.js:19503:20)
    at parseErrorAtPosition (deno:cli/tsc/00_typescript.js:30898:42)
    at parseErrorAt (deno:cli/tsc/00_typescript.js:30905:13)
    at parseErrorAtCurrentToken (deno:cli/tsc/00_typescript.js:30892:13)
    at parseErrorForInvalidName (deno:cli/tsc/00_typescript.js:31130:17)
    at parseErrorForMissingSemicolonAfter (deno:cli/tsc/00_typescript.js:31102:21)
    at parseExpressionOrLabeledStatement (deno:cli/tsc/00_typescript.js:34992:21)
[Error - 8:45:35 PM] Request textDocument/semanticTokens/full failed.
  Message: Invalid request
  Code: -32600 
ERROR TSLS = Error: Debug Failure.
    at deno:cli/tsc/00_typescript.js:19487:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (deno:cli/tsc/00_typescript.js:19487:21)
    at Object.createDetachedDiagnostic (deno:cli/tsc/00_typescript.js:19503:20)
    at parseErrorAtPosition (deno:cli/tsc/00_typescript.js:30898:42)
    at parseErrorAt (deno:cli/tsc/00_typescript.js:30905:13)
    at parseErrorAtCurrentToken (deno:cli/tsc/00_typescript.js:30892:13)
    at parseErrorForInvalidName (deno:cli/tsc/00_typescript.js:31130:17)
    at parseErrorForMissingSemicolonAfter (deno:cli/tsc/00_typescript.js:31102:21)
    at parseExpressionOrLabeledStatement (deno:cli/tsc/00_typescript.js:34992:21)
Failed to request to tsserver Error: Debug Failure.
    at deno:cli/tsc/00_typescript.js:19487:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (deno:cli/tsc/00_typescript.js:19487:21)
    at Object.createDetachedDiagnostic (deno:cli/tsc/00_typescript.js:19503:20)
    at parseErrorAtPosition (deno:cli/tsc/00_typescript.js:30898:42)
    at parseErrorAt (deno:cli/tsc/00_typescript.js:30905:13)
    at parseErrorAtCurrentToken (deno:cli/tsc/00_typescript.js:30892:13)
    at parseErrorForInvalidName (deno:cli/tsc/00_typescript.js:31130:17)
    at parseErrorForMissingSemicolonAfter (deno:cli/tsc/00_typescript.js:31102:21)
    at parseExpressionOrLabeledStatement (deno:cli/tsc/00_typescript.js:34992:21)
[Error - 8:45:35 PM] Request textDocument/semanticTokens/full failed.
  Message: Invalid request
  Code: -32600 
```

**Comment by igorsaux** [comment]
@kitsonk the issue was fixed by https://github.com/denoland/deno/pull/12535
