### ISSUE TITLE
watchFsReturn is flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#12476]
```
error: Test failed

failures:

watchFsReturn
AssertionError: Values are not equal:


    [Diff] Actual / Expected


    [
-     {
-       kind: "create",
-       paths: [
-         "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/67531d9f",
-       ],
-     },
+     ,
    ]

    at assertEquals (file:///Users/runner/work/deno/deno/test_util/std/testing/asserts.ts:271:9)
    at watchFsReturn (file:///Users/runner/work/deno/deno/cli/tests/unit/fs_events_test.ts:80:5)
    at async testStepSanitizer (deno:runtime/js/40_testing.js:161:7)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:42:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:112:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:144:9)
    at async Object.applyPermissions [as fn] (deno:runtime/js/40_testing.js:245:9)
    at async runTest (deno:runtime/js/40_testing.js:349:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:460:22)

failures:

	watchFsReturn

test result: FAILED. 888 passed; 1 failed; 19 ignored; 0 measured; 0 filtered out (105645ms)
```

https://github.com/denoland/deno/pull/12475/checks?check_run_id=3927316181

**Comment by ry** [comment]
Hit this again in https://github.com/denoland/deno/pull/12488/checks?check_run_id=3933998308
```
2021-10-19T02:11:22.4327780Z failures:
2021-10-19T02:11:22.4429180Z 
2021-10-19T02:11:22.4430250Z watchFsReturn
2021-10-19T02:11:22.4452170Z AssertionError: Values are not equal:
2021-10-19T02:11:22.4530290Z 
2021-10-19T02:11:22.4561010Z 
2021-10-19T02:11:22.4605270Z     [90m[1m[Diff][22m[39m [31m[1mActual[22m[39m / [32m[1mExpected[22m[39m
2021-10-19T02:11:22.4612930Z 
2021-10-19T02:11:22.4613800Z 
2021-10-19T02:11:22.4615530Z [37m    [[39m
2021-10-19T02:11:22.4617100Z [31m[1m-     ***[22m[39m
2021-10-19T02:11:22.4618690Z [31m[1m-       kind: "create",[22m[39m
2021-10-19T02:11:22.4620240Z [31m[1m-       paths: [[22m[39m
2021-10-19T02:11:22.4626990Z [31m[1m-         "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/f9dfef2b",[22m[39m
2021-10-19T02:11:22.4628750Z [31m[1m-       ],[22m[39m
2021-10-19T02:11:22.4630270Z [31m[1m-     ***,[22m[39m
2021-10-19T02:11:22.4631680Z [32m[1m+     ,[22m[39m
2021-10-19T02:11:22.4633410Z [37m    ][39m
2021-10-19T02:11:22.4637900Z 
2021-10-19T02:11:22.4639440Z     at assertEquals (file:///Users/runner/work/***/***/test_util/std/testing/asserts.ts:271:9)
2021-10-19T02:11:22.4641190Z     at watchFsReturn (file:///Users/runner/work/***/***/cli/tests/unit/fs_events_test.ts:80:5)
2021-10-19T02:11:22.4642770Z     at async testStepSanitizer (***:runtime/js/40_testing.js:161:7)
2021-10-19T02:11:22.4644320Z     at async asyncOpSanitizer (***:runtime/js/40_testing.js:42:9)
2021-10-19T02:11:22.4645840Z     at async resourceSanitizer (***:runtime/js/40_testing.js:112:7)
2021-10-19T02:11:22.4647300Z     at async exitSanitizer (***:runtime/js/40_testing.js:144:9)
2021-10-19T02:11:22.4648510Z     at async Object.applyPermissions [as fn] (***:runtime/js/40_testing.js:245:9)
2021-10-19T02:11:22.4650580Z     at async runTest (***:runtime/js/40_testing.js:349:7)
2021-10-19T02:11:22.4653840Z     at async Object.runTests (***:runtime/js/40_testing.js:460:22)
2021-10-19T02:11:22.4753140Z 
2021-10-19T02:11:22.4756210Z failures:
2021-10-19T02:11:22.4757000Z 
2021-10-19T02:11:22.4758110Z 	watchFsReturn
2021-10-19T02:11:22.4758860Z 
2021-10-19T02:11:22.4761310Z test result: [0m[31mFAILED[0m. 888 passed; 1 failed; 19 ignored; 0 measured; 0 filtered out [0m[38;5;8m(101791ms)[0m
2021-10-19T02:11:22.4764420Z 
2021-10-19T02:11:22.5292590Z test integration::js_unit_tests ... FAILED
```
