### ISSUE TITLE
Test behavior changes between runs

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#12471]
I don't have a short reproduction path but it can be reproduced from my http_error repository at [this commit](https://github.com/udibo/http_error/tree/bb1f1e786c15e82d5532583b31872c5f0ce481c6). The first run will fail but runs after that will pass. If you change the file again afterward, it will fail again for 1 run then pass all runs after it. It appears to be related to the check happening only when there is a change.

https://user-images.githubusercontent.com/3241653/137639910-957c054e-2149-4ab7-944d-7d57bf1a2352.mp4

```
$ deno --version
deno 1.15.1 (release, x86_64-unknown-linux-gnu)
v8 9.5.172.19
typescript 4.4.2
```

**Comment by bradenmacdonald** [comment]
I believe I have encountered the same issue, and I have a short script to reproduce it:

Put this into `test.ts`:
```typescript
import {
    S3Client,
} from "https://deno.land/x/aws_sdk@v3.23.0-1/client-s3/mod.ts";

new S3Client({
    endpoint: "https://objStoreEndpointURL.com",
    region: "objStoreRegion",
    credentials: {
        accessKeyId: "objStoreAccessKey",
        secretAccessKey: "objStoreSecretKey",
    },
});
```

then run `deno run --allow-read --allow-env --unstable test.ts`

The first time it runs, it will fail with various type errors. Oddly, including an error that `--unstable` is required.

```
error: TS2551 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag, or did you mean 'signal'?
  signals: Deno.Signal,
                ~~~~~~
    at https://deno.land/std@0.101.0/node/os.ts:246:17

    'signal' is declared here.
      export function signal(sig: Signal): SignalStream;
                      ~~~~~~
        at asset:///lib.deno.unstable.d.ts:618:19

TS2345 [ERROR]: Argument of type '{ runtime: string; base64Decoder: Decoder; base64Encoder: Encoder; bodyLengthChecker: (body: any) => number | undefined; defaultUserAgentProvider: Provider<UserAgent>; ... 18 more ...; customUserAgent?: string | ... 1 more ... | undefined; } & ... 4 more ... & UserAgentResolvedConfig' is not assignable to parameter of type 'SSOClientResolvedConfig'.
  Type '{ runtime: string; base64Decoder: Decoder; base64Encoder: Encoder; bodyLengthChecker: (body: any) => number | undefined; defaultUserAgentProvider: Provider<UserAgent>; ... 18 more ...; customUserAgent?: string | ... 1 more ... | undefined; } & ... 4 more ... & UserAgentResolvedConfig' is not assignable to type 'Required<ClientDefaults>'.
    Types of property 'sha256' are incompatible.
      Type 'HashConstructor | ((secret?: any) => void)' is not assignable to type 'HashConstructor'.
        Type '(secret?: any) => void' is not assignable to type 'HashConstructor'.
          Type '(secret?: any) => void' provides no match for the signature 'new (secret?: SourceData | undefined): Hash'.
    super(_config_5);
          ~~~~~~~~~
    at https://deno.land/x/aws_sdk@v3.23.0-1/client-sso/SSOClient.ts:229:11

TS2322 [ERROR]: Type '{ runtime: string; base64Decoder: Decoder; base64Encoder: Encoder; bodyLengthChecker: (body: any) => number | undefined; defaultUserAgentProvider: Provider<UserAgent>; ... 18 more ...; customUserAgent?: string | ... 1 more ... | undefined; } & ... 4 more ... & UserAgentResolvedConfig' is not assignable to type 'SSOClientResolvedConfig'.
    this.config = _config_5;
    ~~~~~~~~~~~
    at https://deno.land/x/aws_sdk@v3.23.0-1/client-sso/SSOClient.ts:230:5
... 
```

But the second time it will run, it works fine. Until I make any change to the file, and then it will give an error again on the next run.

```
deno 1.15.2 (release, x86_64-apple-darwin)
v8 9.5.172.19
typescript 4.4.2
```

**Comment by tpiros** [comment]
Which Deno version is this fix going to be part of? I'm current only 1.15.3 and still experience this issue.

**Comment by kitsonk** [comment]
v1.16 on the 9th November.

**Comment by tpiros** [comment]
awesome @kitsonk thank you!
