### ISSUE TITLE
integration::lsp::lsp_cache_location is flaky

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12486]
```
---- integration::lsp::lsp_cache_location stdout ----
thread 'integration::lsp::lsp_cache_location' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<6
>12

', cli\tests\integration\lsp_tests.rs:2678:3
stack backtrace:
   0:     0x7ff621f110cf - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff621f110cf - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff621f110cf - std::sys_common::backtrace::_print_fmt
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff621f110cf - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff621f2e69a - core::fmt::write
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\core\src\fmt\mod.rs:1115
   5:     0x7ff621f087d8 - std::io::Write::write_fmt<alloc::vec::Vec<u8,alloc::alloc::Global> >
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\std\src\io\mod.rs:1665
   6:     0x7ff621f14696 - std::sys_common::backtrace::_print
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\std\src\sy
```

https://github.com/denoland/deno/pull/12479/checks?check_run_id=3931937701

**Comment by bnoordhuis** [comment]
Probably no longer relevant, the affected code has been refactored. Please reopen if it still happens.
