### ISSUE TITLE
`leaking async ops` error with combination of HTTP server and substep test

### ISSUE THREAD

**Issue by ayame113** [denoland/deno#12492]
The code below works as expected.

```ts
import { assertEquals } from "https://deno.land/std@0.111.0/testing/asserts.ts";
import { listenAndServe } from "https://deno.land/std@0.111.0/http/server.ts";

Deno.test({
  name: "server test",
  async fn() {
    const controller = new AbortController();
    const server = listenAndServe(
      ":8080",
      () => new Response("Hello World"),
      controller,
    );

    const response = await fetch("http://localhost:8080/");
    assertEquals(await response.text(), "Hello World");

    controller.abort();
    await server;
  },
});
```

However, when I rewrite it with the subtest API, I get a `leaking async ops` error.

```ts
import { assertEquals } from "https://deno.land/std@0.111.0/testing/asserts.ts";
import { listenAndServe } from "https://deno.land/std@0.111.0/http/server.ts";

Deno.test({
  name: "server test with step",
  async fn(t) {
    const controller = new AbortController();
    const server = listenAndServe(
      ":8080",
      () => new Response("Hello World"),
      controller,
    );
    // Using the test step API
    await t.step({
      name: "hello-world",
      async fn() {
        const response = await fetch("http://localhost:8080/");
        assertEquals(await response.text(), "Hello World");
      },
    });
    controller.abort();
    await server;
  },
});
/*
test server test with step ...
  test hello-world ... FAILED (357ms)
    AssertionError: Test case is leaking async ops.
    Before:
      - dispatched: 11
      - completed: 10
    After:
      - dispatched: 19
      - completed: 17
    Ops:
      op_http_request_next:
        Before:
          - dispatched: 2
          - completed: 2
        After:
          - dispatched: 4
          - completed: 3

    Make sure to await all promises returned from Deno APIs before
    finishing test case.
        at assert (deno:runtime/js/06_util.js:41:13)
        at asyncOpSanitizer (deno:runtime/js/40_testing.js:96:7)
        at async resourceSanitizer (deno:runtime/js/40_testing.js:112:7)
        at async exitSanitizer (deno:runtime/js/40_testing.js:144:9)
        at async TestContext.step (deno:runtime/js/40_testing.js:719:13)
        at async fn (file:///C:/Users/azusa/work/deno/test/test_test.ts:28:5)
        at async testStepSanitizer (deno:runtime/js/40_testing.js:161:7)
        at async asyncOpSanitizer (deno:runtime/js/40_testing.js:42:9)
        at async resourceSanitizer (deno:runtime/js/40_testing.js:112:7)
        at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:144:9)
FAILED (400ms)
*/
```

Is this a bug, or am I missing something?

(version: deno 1.15.1)

**Comment by jjarv-tuni** [comment]
I was puzzled by this feature as using arrow operator with test function will not give you the information about leaked resources even if you use --trace-ops option. 
So instead of
```
Deno.test("Async test", async () => {
  const result = <insert your truefully await test here>
assert(result);
}); 
```
one should use
```
Deno.test({
name: "Async Test",
async fn() {
 const result = <insert your truefully await test here>
assert(result);

},
  sanitizeOps: false,
  sanitizeResources: false,
});
```
