### ISSUE TITLE
Deno emit panics on bad import with classic bundle

### ISSUE THREAD

**Issue by derekwheel** [denoland/deno#12516]
Hello! I have run into an issue in Deno 1.15 with `Deno.emit` in  where using the bundle option will cause a panic rather than throw an exception if the code to be built contain errors. This happens with both `classic` and `module` bundles.
Example:
```ts
/*
main.ts 
run with `deno run --allow-read --unstable main.ts`
*/
import * as path from "https://deno.land/std@0.110.0/path/mod.ts"

const dir = path.fromFileUrl(path.dirname(import.meta.url));
const indexPath = path.join(dir, 'index.ts');

const result = await Deno.emit(indexPath, { bundle: 'classic' });

console.log(result);


/*
index.ts -- notice the intentional syntax error
*/
console.log("index!"
```
In Deno 1.14.3 I get the following error, which can be caught and handled:
```
error: Uncaught (in promise) TypeError: Unable to handle the given specifier: file:///Users/me/code/deno_bug_repro/index.ts
const result = await Deno.emit(indexPath, { bundle: 'classic' });
               ^
    at deno:core/01_core.js:101:46
    at unwrapOpResult (deno:core/01_core.js:121:13)
    at async file:///Users/me/code/deno_bug_repro/main.ts:6:16
```

In Deno 1.15.2 a panic happens instead:
```
thread 'main' panicked at 'Error 'Unable to output during bundling.' contains boxed error of unknown type:
  Error { context: "Unable to output during bundling.", source: load_transformed failed

Caused by:
    0: Bundler.load() failed
    1: Bundler.loader.load(file:///Users/me/code/deno_bug_repro/index.ts) failed
    2: Module "file:///Users/me/code/deno_bug_repro/index.ts" unexpectedly missing when bundling. }
  Error { context: "load_transformed failed", source: Bundler.load() failed

Caused by:
    0: Bundler.loader.load(file:///Users/me/code/deno_bug_repro/index.ts) failed
    1: Module "file:///Users/me/code/deno_bug_repro/index.ts" unexpectedly missing when bundling. }
  Error { context: "Bundler.load() failed", source: Bundler.loader.load(file:///Users/me/code/deno_bug_repro/index.ts) failed

Caused by:
    Module "file:///Users/me/code/deno_bug_repro/index.ts" unexpectedly missing when bundling. }
  Error { context: "Bundler.loader.load(file:///Users/me/code/deno_bug_repro/index.ts) failed", source: Module "file:///Users/me/code/deno_bug_repro/index.ts" unexpectedly missing when bundling. }
  "Module \"file:///Users/me/code/deno_bug_repro/index.ts\" unexpectedly missing when bundling."', cli/errors.rs:73:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I believe the rejected promise is more desirable behavior, as a program can catch that and handle it gracefully, where as the panic is unrecoverable.

Interestingly, if I remove the `bundle` parameter from `Deno.emit`, no error occurs:
```
{
  diagnostics: [
    {
      category: 1,
      code: 900001,
      start: null,
      end: null,
      messageText: "The module's source code could not be parsed: Unexpected eof at file:///Users/me/code/deno_bug_repr...",
      messageChain: null,
      source: null,
      sourceLine: null,
      fileName: "file:///Users/me/code/deno_bug_repro/index.ts",
      relatedInformation: null
    }
  ],
  files: {},
  ignoredOptions: null,
  stats: []
}
```

**Comment by dsherret** [comment]
`Deno.emit` doesn't exist anymore so closing.
