### ISSUE TITLE
bug(signal): Registering SIGKILL causes panic

### ISSUE THREAD

**Issue by MierenManz** [denoland/deno#12515]
the following code will cause a panic in deno 1.15.2
```ts
for await (const sig of Deno.signal("SIGKILL")) {
  console.log(sig);
}
```
Ran with `deno run --unstable mod.ts`

Error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Refusing to register signal 9" }', runtime/ops/signal.rs:185:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

stacktrace
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Refusing to register signal 9" }', runtime/ops/signal.rs:185:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: deno_core::ops_json::op_sync::{{closure}}
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
   5: deno_core::ops::OpTable::route_op
   6: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
   7: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
             at ./../../../../v8/src/api/api-arguments-inl.h:152:3
   8: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
             at ./../../../../v8/src/builtins/builtins-api.cc:112:36
   9: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
             at ./../../../../v8/src/builtins/builtins-api.cc:142:5
  10: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by crowlKats** [comment]
`SIGKILL`, `SIGSTOP`, `SIGILL`, `SIGFPE`, and `SIGSEGV` cannot be registered, as per https://docs.rs/signal-hook-registry/1.4.0/signal_hook_registry/constant.FORBIDDEN.html

> Some signals are impossible to replace according to POSIX and some are so special that this library refuses to handle them (eg. SIGSEGV). The routines panic in case registering one of these signals is attempted.

we shouldn't be unwrapping there, so either we `?`, or we should check for passed signal and error if it is one of the ones that cant be registered

**Comment by MierenManz** [comment]
Wouldn't it also be a good idea to remove these signals? Because they cannot be used anyway?

**Comment by MierenManz** [comment]
Yeah from typings. Maybe then adjust them so that they represent values than can actually be used?
Like habe a base and extended version of the signal types. Base supports both api's and extended only the `kill()` api

**Comment by lucacasonato** [comment]
The ops here should prevent registration of these signals, and gracefully return an error instead.
