### ISSUE TITLE
http_util::tests::test_fetch_with_empty_certificate_store is flaky

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12561]
```
 http_util::tests::test_fetch_with_empty_certificate_store stdout ----
Error: thread 'http_util::tests::test_fetch_with_empty_certificate_store' panicked at 'explicit panic', cli/http_util.rs:426:7
stack backtrace:
   0:        0x10f6c4e71 - std::backtrace_rs::backtrace::libunwind::trace::h027800441f1fc8f7
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10f6c4e71 - std::backtrace_rs::backtrace::trace_unsynchronized::h4d1dc087eb89c650
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10f6c4e71 - std::sys_common::backtrace::_print_fmt::hf2537bbfc4d64c25
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10f6c4e71 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf1ee81583766da09
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10f6e5ccb - core::fmt::write::h8dc218a6eb2426a8
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/fmt/mod.rs:1150:17
   5:        0x10f6bcdea - std::io::Write::write_fmt::h098c2b0a8bc0b3aa
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/io/mod.rs:1667:15
   6:        0x10f6c6be5 - std::sys_common::backtrace::_print::h194fd71b011e1888
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10f6c6be5 - std::sys_common::backtrace::print::h4eec350e8a08a661
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10f6c6be5 - std::panicking::default_hook::{{closure}}::h4b7de73863cf8582
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:210:50
   9:        0x10f6c67ff - std::panicking::default_hook::h778da672ce56a579
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:224:9
  10:        0x10f6c72d0 - std::panicking::rust_panic_with_hook::ha5146542f697c8af
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:624:17
  11:        0x10f629c07 - std::panicking::begin_panic::{{closure}}::h588b2e16b887ab95
  12:        0x10f629b68 - std::sys_common::backtrace::__rust_end_short_backtrace::hfaac658bb0dca4a0
  13:        0x10f70ee83 - std::panicking::begin_panic::hd51565b62cb893c7
  14:        0x10d17663c - deno::http_util::tests::test_fetch_with_empty_certificate_store::{{closure}}::h8e948a31ee6be04c
                               at /Users/runner/work/deno/deno/cli/http_util.rs:426:7
  15:        0x10d1ccb90 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5765fdce385d3ab1
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  16:        0x10d111442 - <core::pin::Pin<P> as core::future::future::Future>::poll::h6ce200ebe9e02530
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/future.rs:119:9
  17:        0x10d1a264a - tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}::hbc6d256eb3290d20
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:230:62
  18:        0x10cdea579 - tokio::coop::with_budget::{{closure}}::h096025bf23e611a0
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:106:9
  19:        0x10cbeefc0 - std::thread::local::LocalKey<T>::try_with::ha2aced9594411d25
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:399:16
  20:        0x10cbe04cc - std::thread::local::LocalKey<T>::with::hb75340e919d362c3
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:375:9
  21:        0x10d1901f7 - tokio::coop::with_budget::hd8651674427abbd6
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:99:5
  22:        0x10d1901f7 - tokio::coop::budget::ha845134efd6b2e54
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:76:5
  23:        0x10d1901f7 - tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::haa4284ac7f95aa60
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:230:39
  24:        0x10d1bdea1 - tokio::runtime::basic_scheduler::enter::{{closure}}::hf19bf1b4b6ec266b
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:339:29
  25:        0x10cf24dcc - tokio::macros::scoped_tls::ScopedKey<T>::set::h1c06a52609f07030
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/macros/scoped_tls.rs:61:9
  26:        0x10d1b5f9c - tokio::runtime::basic_scheduler::enter::h61cd15d4ac78e424
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:339:5
  27:        0x10d17b7cd - tokio::runtime::basic_scheduler::Inner<P>::block_on::h7a417d39aa8bf449
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:218:9
  28:        0x10d1a3c04 - tokio::runtime::basic_scheduler::InnerGuard<P>::block_on::h2fcf319f58343f2e
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:489:9
  29:        0x10d1ac26d - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hb10dfde61b923223
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:178:24
  30:        0x10cdd0c97 - tokio::runtime::Runtime::block_on::h908f308a5d3f7c75
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/mod.rs:461:46
  31:        0x10ce93945 - deno::http_util::tests::test_fetch_with_empty_certificate_store::h3f2d26089ca684af
                               at /Users/runner/work/deno/deno/cli/http_util.rs:424:5
  32:        0x10d1760d1 - deno::http_util::tests::test_fetch_with_empty_certificate_store::{{closure}}::hf766c801bd384616
                               at /Users/runner/work/deno/deno/cli/http_util.rs:402:9
  33:        0x10cfb0531 - core::ops::function::FnOnce::call_once::h8163625fae85614e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  34:        0x10d2598e6 - core::ops::function::FnOnce::call_once::h5f6efdda8e60de7d
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  35:        0x10d2598e6 - test::__rust_begin_short_backtrace::h4f48cf3815abf46e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/test/src/lib.rs:578:5
  36:        0x10d2585c9 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4e5ccab5d32f65ce
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
  37:        0x10d2585c9 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc8c71f4287566577
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panic/unwind_safe.rs:271:9
  38:        0x10d2585c9 - std::panicking::try::do_call::hd21c8475a8becd9f
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  39:        0x10d2585c9 - std::panicking::try::hf0ca7be660a58626
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  40:        0x10d2585c9 - std::panic::catch_unwind::h63ec7adeb6c308f7
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  41:        0x10d2585c9 - test::run_test_in_process::he7521911c8c40eae
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/test/src/lib.rs:601:18
  42:        0x10d2585c9 - test::run_test::run_test_inner::{{closure}}::haeac80836581e38d
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/test/src/lib.rs:493:39
  43:        0x10d22624b - test::run_test::run_test_inner::{{closure}}::ha757ea0fb17b81e0
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/test/src/lib.rs:520:37
  44:        0x10d22624b - std::sys_common::backtrace::__rust_begin_short_backtrace::head63326a9c5636e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:125:18
  45:        0x10d22ac14 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hab4ce7a81612cd78
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/mod.rs:481:17
  46:        0x10d22ac14 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h36a12267cf1cd3d4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panic/unwind_safe.rs:271:9
  47:        0x10d22ac14 - std::panicking::try::do_call::he03c597849bf99b8
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  48:        0x10d22ac14 - std::panicking::try::hb55047ea91a796ac
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  49:        0x10d22ac14 - std::panic::catch_unwind::h0709839d0aafd6ab
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  50:        0x10d22ac14 - std::thread::Builder::spawn_unchecked::{{closure}}::h962b030aca0822a3
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/mod.rs:480:30
  51:        0x10d22ac14 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd2917b4fb82233de
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  52:        0x10f6cd7b7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb0100d59ddd2d43a
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
  53:        0x10f6cd7b7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h39d9f89d6919ae6b
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
  54:        0x10f6cd7b7 - std::sys::unix::thread::Thread::new::thread_start::heea623387f71e830
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys/unix/thread.rs:106:17
  55:     0x7fff6e2b6109 - __pthread_start


failures:
    http_util::tests::test_fetch_with_empty_certificate_store
```

https://github.com/denoland/deno/runs/4022041962?check_suite_focus=true

**Comment by lucacasonato** [comment]
This test has been re-enabled.
