### ISSUE TITLE
Failed ./tools/unit_tests.py

### ISSUE THREAD

**Issue by Tnarita0000** [denoland/deno#1268]
An error occurred when I run ./tools/unit_tests.py.
```
test result: ok. 37 passed; 0 failed; 0 ignored; 0 measured; 182 filtered out

running 8 tests
test getTravisDataSuccess_permW0N1E0R0
HttpOther: an error occurred trying to connect: Connection refused (os error 61)
    at maybeError (deno/js/errors.ts:38:12)
    at handleAsyncMsgFromRust (deno/js/dispatch.ts:27:17)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 211 filtered out

Error: There were 1 test failures.
    at setTimeout (file:///Users/Tnarita0000/git/deno/js/testing/testing.ts:110:13)
    at fire (deno/js/timers.ts:131:3)```

**Comment by kt3k** [comment]
I think you need to run `./tools/http_server.py` before running `./tools/unit_tests.py`

**Comment by ry** [comment]
As @kt3k said. 

Usually we don't run the `tools/unit_tests.py` by itself. We run `tools/test.py`.
