### ISSUE TITLE
Bug: export default Typescript namespaces cause errors in bundled code

### ISSUE THREAD

**Issue by fizx** [denoland/deno#12731]
Reduced reproduction attached 

```
kyle@Kyles-MBP denobug % deno --version                                        
deno 1.16.0 (release, aarch64-apple-darwin)
v8 9.7.106.2
typescript 4.4.2
```

a.ts
```
import B from "./b.ts";

console.log(JSON.stringify(B.b));
```

b.ts
```
namespace B {
  export var b = {};
}

export default B;
```

```
kyle@Kyles-MBP denobug % deno run a.ts
Check file:///Users/kyle/denobug/a.ts
{}
kyle@Kyles-MBP denobug % deno bundle a.ts
Check file:///Users/kyle/denobug/a.ts
Bundle file:///Users/kyle/denobug/a.ts
var B;
(function(B1) {
    B1.b = {
    };
})(B || (B = {
}));
console.log(JSON.stringify(__default.b));

kyle@Kyles-MBP denobug % deno bundle a.ts > c.js
Check file:///Users/kyle/denobug/a.ts
Bundle file:///Users/kyle/denobug/a.ts
kyle@Kyles-MBP denobug % deno run c.js 
error: Uncaught ReferenceError: __default is not defined
console.log(JSON.stringify(__default.b));
                           ^
    at file:///Users/kyle/denobug/c.js:7:28
```

**Comment by watiko** [comment]
I am also affected by this issue.

environment
```
$ deno --version
deno 1.17.0 (release, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

bug.ts
```ts
// original code: https://deno.land/x/rimbu@0.7.3/stream/fast-iterator.ts
namespace FastIterator {
  export const fixedDone = {
    done: true,
  };

  export const emptyFastIterator = {
    next() {
      return fixedDone;
    },
  };
}

console.log(FastIterator.emptyFastIterator.next())
```

bundled-bug.js
```js
var FastIterator;
(function(FastIterator1) {
    FastIterator1.fixedDone = {
        done: true
    };
    FastIterator1.emptyFastIterator = {
        next () {
            return fixedDone; // should be FastIterator1.fixedDone
        }
    };
})(FastIterator || (FastIterator = {
}));
console.log(FastIterator.emptyFastIterator.next());
```

steps to reproduce
```console
$ deno run bug.ts
{ done: true }

$ deno bundle bug.ts > bundled-bug.js
$ deno run bundled-bug.js
error: Uncaught ReferenceError: fixedDone is not defined
            return fixedDone;
            ^
    at Object.next (file:///Users/watiko/tmp/deno-reg/bundled-bug.js:8:13)
    at file:///Users/watiko/tmp/deno-reg/bundled-bug.js:13:44
```

**Comment by watiko** [comment]
It seems to have been corrected some time ago. I believe this issue can be closed.

## environment

```
$ deno --version
deno 1.28.1 (release, x86_64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
```

## bundled contents

```js
// c.js
// deno-fmt-ignore-file
// deno-lint-ignore-file
// This code was bundled using `deno bundle` and it's not recommended to edit it manually

var B;
(function(B) {
    B.b = {};
})(B || (B = {}));
console.log(JSON.stringify(B.b));


```

```js
// bundled-bug.js
// deno-fmt-ignore-file
// deno-lint-ignore-file
// This code was bundled using `deno bundle` and it's not recommended to edit it manually

var FastIterator;
(function(FastIterator) {
    var fixedDone = FastIterator.fixedDone = {
        done: true
    };
    FastIterator.emptyFastIterator = {
        next () {
            return fixedDone;
        }
    };
})(FastIterator || (FastIterator = {}));
console.log(FastIterator.emptyFastIterator.next());
```

## outputs

```console
$ deno run c.js
{}

$ deno run bundled-bug.js
{ done: true }

```

**Comment by lucacasonato** [comment]
`deno bundle` has been deprecated and will be removed in Deno 2.0
