### ISSUE TITLE
Proposal: add permissions to config file

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12763]
## Context

Currently Deno supports a `deno.jsonc` configuration file which allow users to provide a [configuration file](https://deno.land/manual@v1.16.1/getting_started/configuration_file) that can provide TypeScript compiler options, lint options and format options.

It does not currently support other information that can only be expressed on the command line, while this proposal is what

## Semantics

- When a configuration file is applied and the `"permissions"` section is parsed and the permissions are applied from the `"permissions"` section. Any other flags on the command line are ignored.
- If there are flags on the command line and a config file is being applied, and the config file contains `"permissions"` a warning should be issued to stderr that permissions from the config file are being applied.
- Remote configuration files are supported, but a summary of the permissions is prompted before hand and requires user configuration to continue.
- Keys names match the flags on the command line, and values accept a `true` or `false`. If the key supports a value, these can be either a string delimited the same way on the command line, or an array of strings.
- In situations where a base path is needed for relative paths (for `--allow-read` and `--allow-write`) the config file is used as a base, versus the cwd.

## Examples

An example of a configuration file using permissions:

```jsonc
{
  "permissions": {
    "allow-all": true,
    "allow-env": true,
    "allow-hrtime": false,
    "allow-read": [ ".", "/tmp" ],
    "allow-write": ".",
    "allow-net": "deno.land,nest.land"
  }
}
```

## Considerations / Open Questions

- Having explicit a _section_ of `"permissions"` makes it easier to understand explicitly that these effect the runtime permissions.  It also allows the definition of the semantics of `"permissions"` to evolve independently of the rest of the configuration file, as well as opens an easy opportunity to be able to set permissions on other things in the future, like _tasks_/_scripts_ independent of the top level permissions.
- Having an explicit `allow` in the keys provides a mechanism to introduce `block` in the future (for example `"block-net": "deno.land"`) giving more granular permissions.
- If a remote configuration file is used, and there is no TTY or `--no-prompt`/`--quit` is supplied on the configuration is set, should the process just terminate or just allow the program to run with the supplied permissions?
- For remote config files, using the remote URL as a relative base for `--allow-read` `--allow-write` is not possible.  Does this mean that relative paths just error, or that it defaults to the cwd in those situations?

cc/ @bartlomieju @ry

**Comment by crowlKats** [comment]
In my opinion `allow-all` should just be
 ```json
{
  "permissions": true,
}
```

>     * Having an explicit `allow` in the keys provides a mechanism to introduce `block` in the future (for example `"block-net": "deno.land"`) giving more granular permissions.

not a fan of this. it would mean you'd be able to do something with the config file that is impossible to do with just flags

**Comment by bartlomieju** [comment]
I'm in favor of the proposal in general (especially combined with _tasks_/_scripts_), but I'm not in favor of top-level `permissions` key. IMO there's not much benefit of having a single top-level definition if most projects contain several entrypoint, each of them requiring different permissions. With this proposal it becomes non-obvious how permissions would be applied to different entry-points. 

As for the signature of `permissions` object I believe we should follow definition used in `TestDefinition` and `WorkerOptions` as closely as possible:

https://github.com/denoland/deno/blob/dd91ecef502456ba39495d8e178f8101a87c0e34/cli/dts/lib.deno.ns.d.ts#L144-L275

**Comment by kitsonk** [comment]
> IMO there's not much benefit of having a single top-level definition if most projects contain several entrypoint, each of them requiring different permissions.

But there are currently no semantics in the config file for entry points, so it becomes a chicken and egg.

And specifically the example of the "test" permissions seems to apply a top level `"permissions"` key that would be the default set of permissions to be applied.  Given the current lack of a way to express entry points in the config file, it only seems logical to describe the _default_ set of permissions, and then allow addition/different sets of permissions to be described on individual entry points when they become available.

My key point was that we shouldn't flatten permissions to be different top level keys.

**Comment by kitsonk** [comment]
> not a fan of this. it would mean you'd be able to do something with the config file that is impossible to do with just flags.

That is already the case with TypeScript compiler options.

**Comment by kitsonk** [comment]
> As for the signature of `permissions` object I believe we should follow definition used in `TestDefinition` and `WorkerOptions` as closely as possible:

I am agreeable with that, and it makes sense in the context of "top level" permissions and allowing overriding for different tasks/entry points.

**Comment by bartlomieju** [comment]
> > IMO there's not much benefit of having a single top-level definition if most projects contain several entrypoint, each of them requiring different permissions.
> 
> But there are currently no semantics in the config file for entry points, so it becomes a chicken and egg.
> 
> And specifically the example of the "test" permissions seems to apply a top level `"permissions"` key that would be the default set of permissions to be applied. Given the current lack of a way to express entry points in the config file, it only seems logical to describe the _default_ set of permissions, and then allow addition/different sets of permissions to be described on individual entry points when they become available.
> 
> My key point was that we shouldn't flatten permissions to be different top level keys.

Okay, this is a valid point. You're also right about chicken and egg problem. I guess this is a good way to start iterating on these features. Let's do it 👍

**Comment by crowlKats** [comment]
> > not a fan of this. it would mean you'd be able to do something with the config file that is impossible to do with just flags.
> 
> That is already the case with TypeScript compiler options.

yes, but those are "external", as in, they arent something made by/for deno exclusively. the only other option for thsoe would implement all options as flags, which would be unrealistic.
Also this would mean we have some permission related features as flags, but other features only in config file, making things just more confusing imo by having things "all over the place" (i am aware it isnt as bad as i just made it sound, but my point stands).

**Comment by Soremwar** [comment]
> I'm in favor of the proposal in general (especially combined with tasks/scripts), but I'm not in favor of top-level permissions key. IMO there's not much benefit of having a single top-level definition if most projects contain several entrypoint, each of them requiring different permissions. With this proposal it becomes non-obvious how permissions would be applied to different entry-points.

This could be tackled by allowing composition of config file, an `extends` of sorts

**Comment by crowlKats** [comment]
> ```json
> {
>   "permissions": {
>     "allow-all": true,
>     "allow-env": true,
>     "allow-hrtime": false,
>     "allow-read": [ ".", "/tmp" ],
>     "allow-write": ".",
>     "allow-net": "deno.land,nest.land"
>   }
> }
> ```

Thought about the blocklist thing again: how about instead 
```json
{
  "permissions": {
    "env": {
      "block": ["PATH"],
      "allow": ["HOME"]
    },
    "hrtime": false,
    "read": [".", "/tmp"],
    "write": ["."],
    "net": ["deno.land", "nest.land"],
    "prompt": true
  }
}
```
so to specify the blocklist, its an object instead of a proper value for the perm directly. this would all us to add blocklist support at some later point as it would be an extension from what it would be without. also this would allow for allowing specifying `--prompt` on a permission level instead of just a global level

**Comment by lilnasy** [comment]
I really like this proposal. It encourages fine-grained control over what directories can be read and written to, for example. At the moment, it's inconvenient to get this precise with command line options.

**Comment by jsejcksn** [comment]
> I really like this proposal. It encourages fine-grained control over what directories can be read and written to, for example. At the moment, it's inconvenient to get this precise with command line options.

@crowlKats When you said

> the only other option for thsoe would implement all options as flags, which would be unrealistic

by "unrealistic" did you mean "inconvenient"? My impression is that most software which executes with more than a few flags either builds them using a script or hardcodes them into a script.

Adding additional CLI flags from options actually sounds useful (as no extra filesystem i/o in the form of reading/writing a config would need to happen in dynamic execution).

**Comment by jrylan** [comment]
I like the proposal a lot as well, I do think however that there should be at least the option of strict security of the configuration file. It opens up a security risk to read permissions from a configuration file that could be modified by a third-party source.

Say you rely on a third-party module from `deno.land`, the module gets hacked, a new release is published and you update to it without checking... you run deno with `--allow-write=.`, so the hacked third-party module updates your config to give itself more permissions, and then it can do whatever it needs to do on it's next run.

The solution here would be that if there is to be an automatic loading of a Deno config file, then editing said file must be blocked at runtime or at least behind a prompt. Personally, I think a developer should have to manually edit the file.

I've switched over to Deno because of the increasing frustrations with hacked npm packages, so I'm approaching this from the perspective of rightful security paranoia, the key differentiator with Deno is the great security is offers. I want to see that reputation remain intact.

**Comment by jsejcksn** [comment]
> For the strictest security, I would want to be able to explicitly opt-out of reading permissions from the config and instead require all the permissions be provided via flags... that's what I would always want to run in production

Related: https://github.com/denoland/deno/issues/13452 will become even more important if this feature is implemented

**Comment by sno2** [comment]
Now that we have permissions scoped to tests, it would probably be best to just unify a `deno.jsonc` config property `permissions` with [`Deno.test`'s permission object type](https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.ns.d.ts#L119-L250).  Also, when it is `string | URL` we can just only accept `string`.  I think it would be a bad idea to have two different type of objects for specifying permissions and this would give us a chance to have a uniform behavior.

**Comment by ry** [comment]
I'm in favor too. Added to 1.22 milestone.

**Comment by bartlomieju** [comment]
Yes

**Comment by GuillaumeAmat** [comment]
:eyes:

**Comment by happy-little-one** [comment]
there is a short way to achieve this, run this in window terminal:

```
alias d="deno run --allow-net --allow-env --allow-read --unstable" $*
```
and then `d foo.ts`

**Comment by pkoch** [comment]
On #14520, @bartlomieju said:

> There's no consensus about this feature in the core team. Closing for now.

Is now maybe an ok time to retry corralling consensus?

**Comment by cawa-93** [comment]
I would like to be able to set default permissions for each command individually. Example:
```js
{
    // Global permissions
    permissions: {
        'allow-read': ['./config.json']
    },
    // Additional permissions for any `deno test` command
    test: {
        permissions: {
            'allow-read': ['.'],
            'allow-write': ['tests/fixtures'],
            'allow-env':true,
        }
    }
}
```

**Comment by jsejcksn** [comment]
Isn't this kind of functionality practically already in place, provided by the [task runner](https://deno.land/manual@v1.28.3/tools/task_runner#task-runner) (`deno task`) and configurable through task definitions? IIRC, the task runner was not yet implemented at the time this issue was created.

**Comment by lilnasy** [comment]
Isn't that just as much of a concern right now with the task runner? Task aliases are also vulnerable to being edited by a rogue dependency.

**Comment by sigmaSd** [comment]
Here is another proposal https://github.com/denoland/deno/issues/17177

It has in my opinion some advantages:
- It allows specifying complex dependencies, dependencies that requires internal app information, and it allows expressing them in a crossplatfrom way easily
- Unlike deno.json that needs to live besides the app entry point, permissions.ts can live anywhere , so malicious actors can *not* rewrite it if its in remote place for example, or somewhere with no write permission

**Comment by pkoch** [comment]
Maybe the maintainers can define a starting point for the threat model? I feel we're going back-and-forth in a piecemeal fashion. I'd love to have full lay of the land to be able to propose something that's able to be well received.

**Comment by oscarotero** [comment]
My 2 cents:

- I think permissions should live inside the deno.json
- Maybe there should be a special writing permission applied to the config file used currently. Something like `Deno requests write access to the config file "deno.json"`. It would be independent of the `--allow-write` flag and be configured with `--allow-write-config` flag or no flag at all and only using the prompt.
- For cross platform paths, I think it could be managed by Deno in the same way of Deno task have cross platform commands like `cp`, `mkdir`, etc. Maybe using an `$` or somethink like that. For example: `--allow-write=$HOME` for the user's home directory.

**Comment by sigmaSd** [comment]
My main problem with json config is that you cant express very useful permissions, like --allow-read=cache-dir() or even --allow-cache-dir=cache-dir().join(myapp) in a cross platform way

In my opinion these happens all the time, and neither the current system or this proposal improve on thar, which is why ppl just give up and use --allow-read=all

**Comment by jsejcksn** [comment]
> My main problem with json config is that you cant express very useful permissions, like --allow-read=cache-dir() or even --allow-cache-dir=cache-dir().join(myapp) in a cross platform way

@sigmaSd I'm not sure that I understand this exactly, but it seems like a suggestion of some kind of dynamic value resolution. The ability to audit fully-resolved, static values prior to runtime is foundational to the security of permission configuration.

**Comment by sigmaSd** [comment]
That's a valid point

It's a dynamic system, it can be improved by putting the permission file in a immutable registery like deno.land but it still dynamic

**Comment by dsherret** [comment]
> Isn't that just as much of a concern right now with the task runner? Task aliases are also vulnerable to being edited by a rogue dependency.

@lilnasy it's not as much of a concern because it doesn't apply to every `deno run/test/etc` invocation and with `deno task` you probably have some idea about what task in what config file you are running. With `deno run` if you don't have a config file and the script has write permissions, then the malicious script could write one in an ancestor directory which would then be auto-discovered on the next run.

**Comment by DerZade** [comment]
How about another flag to use the permissions from the config file? Something like `--allow-from-config` or `--permissions-from-config` 🤔 Then you would have to explicitly specify that you want to use the permissions from the config. 
Admittedly that doesn't fix the problem all together, but imo brings it down the a similar threat level we currently have with `deno task`

**Comment by dsherret** [comment]
@DerZade yeah, that’s been discussed internally for certain commands like `deno test` and `bench`. Basically if you run without the flag it would prompt and show you the permissions to confirm, or you could provide a flag to use the permissions from the config file and override the prompt. This would help prevent people from accidentally running their tests without permissions granted and have it fail halfway through.

For `deno run`, I’m not sure how useful it is to have permissions in the config file because someone could define a `deno task`. Anyway, this is just all my personal opinion.

**Comment by DerZade** [comment]
I agree that `deno task` helped with this a lot. My personal setup usually includes three tasks, which all execute `deno run`. One with just the permissions, another one with the permissions and `--watch` and a third one with the permissions and `--inspect-brk`. 
Now I have basically the same task with just minor differences and each of them includes the same (very long) permissions options.
So every time I need change permissions, I have to do it three times. That is still bothering me a bit 😅 and why I personally would welcome defining the permissions in the Deno config (or even a external config).

**Comment by theforager** [comment]
+1 for this proposal. The command line flags are fine for running a foreign script or heavy production projects, but this is the worst CX aspect of Deno for quick prototyping, small projects, etc.

**Comment by oscarotero** [comment]
Maybe the permissions in the config file could be assigned only to tasks (instead of globally) because there can be different modules that you want to run with different permissions.

I remember an idea I suggested some time ago to include descriptions in the tasks (https://github.com/denoland/deno/issues/14949). Although it was rejected, it had the ability to configure a task using an object with different properties, not only a plain string. This would allow to configure the permissions in a more ergonomic way:

```json
{
  "tasks": {
    "serve": {
      "run": "deno run ./server.ts",
      "allow": {
        "net": "localhost:3000",
        "read": ["./img", "./styles"],
      },
    },
  }
}
```

It would be equivalent to:

```json
{
  "tasks": {
    "serve": "deno run --allow-net=localhost:3000 --allow-read=./img,./styles ./server.ts"
  }
}
```

**Comment by wojpawlik** [comment]
Shebang is aleeady a nice place for permissions, it just doesn't work on Windows: https://github.com/denoland/deno_task_shell/issues/23.

**Comment by domenic** [comment]
I think I'm running into this problem. I want `deno test` to come with some permissions. But as far as I can tell, I have to either:

- Specify the permissions on the command line every time; or
- Give up on using `deno test` and instead define a custom task and remember to use `deno task test`.

**Comment by jsejcksn** [comment]
> I want `deno test` to come with some permissions. But as far as I can tell, I have to either:
> 
> * Specify the permissions on the command line every time; or
> * Give up on using `deno test` and instead define a custom task and remember to use `deno task test`.

Deno can't know which permissions you want to grant to executable code (whether it's code that's executed by `deno run`, `deno test`, etc.) without your specifying them… _somewhere_.

This is my view of the current state of things: if you plan to locally execute code (more than once using the same options) by interactively typing a command into your terminal, and you don't want to type very much each time to execute that code (who does? 😅), then specifying a task using the [task runner](https://docs.deno.com/runtime/manual/tools/task_runner/) is the simplest way to granularly open up the security sandbox — then, like you said, it's as simple as `deno task test` to run your tests — or `deno task start` to start your program — with only the minimally necessary permissions defined in those tasks.

However, if you want to grant _all_ permissions (disable the security sandbox) for all test modules [whose filenames pattern match by default](https://docs.deno.com/runtime/manual/basics/testing/#running-tests) when running `deno test` (and all of those modules' dependencies)… then you can always use [`deno test -A`](https://docs.deno.com/runtime/manual/basics/permissions/#permissions-list).

<details>
<summary>Example:</summary>

`fs_read_test.ts`:
```ts
// Requires permission --allow-read

import { assertStrictEquals } from "jsr:@std/assert@^1.0.2";

Deno.test("can read the local filesystem", async () => {
  const fileInfo = await Deno.lstat(new URL(import.meta.url));
  assertStrictEquals(fileInfo.size, 298); // This test module is 298 bytes
});

```

Running without any granted permissions:

```txt
% deno test
running 1 test from ./fs_read_test.ts
can read the local filesystem ... FAILED (0ms)

 ERRORS 

can read the local filesystem => ./fs_read_test.ts:5:6
error: PermissionDenied: Requires read access to "/Users/deno/fs_read_test.ts", run again with the --allow-read flag
  const fileInfo = await Deno.lstat(new URL(import.meta.url));
                              ^
    at Object.lstat (ext:deno_fs/30_fs.js:410:21)
    at file:///Users/deno/fs_read_test.ts:6:31

 FAILURES 

can read the local filesystem => ./fs_read_test.ts:5:6

FAILED | 0 passed | 1 failed (1ms)

error: Test failed
```

Running with all permissions:
```
% deno test -A
running 1 test from ./fs_read_test.ts
can read the local filesystem ... ok (0ms)

ok | 1 passed | 0 failed (1ms)
```

```txt
% deno --version
deno 1.45.5 (release, aarch64-apple-darwin)
v8 12.7.224.13
typescript 5.5.2
```

</details>

**Comment by domenic** [comment]
Yes, perhaps I was not clear. I want to specify in my config file what permissions `deno test` should run in, so that people coming to my project can use the standard `deno test` command. Right now I have to instead include special instructions in my readme for a nonstandard testing command.

**Comment by jsejcksn** [comment]
> I want to specify in my config file what permissions `deno test` should run in, so that people coming to my project can use the standard `deno test` command.

This would violate the security concept of sandbox-by-default and explicit granting of permissions: it would be implicit granting of permissions (because configuration files are implicitly resolved).

> Right now I have to instead include special instructions in my readme for a nonstandard testing command.

Can you instruct users to type `deno task test` instead of `deno test`?

**Comment by domenic** [comment]
> Can you instruct users to type `deno task test` instead of `deno test`?

Yes, I can. And then this makes Deno an inferior ecosystem to npm, where to learn how to run a project's tests, I don't need to look it up in the project's readme. I just always use `npm test`.

**Comment by dandv** [comment]
As `deno run` interactively asks for the most granular permissions the code requires, and the user answers, it would be really handy to have an option to save these permissions somehow, in a configuration file, as a `tasks` entry, or even as a CLI command.

**Comment by omarcresp** [comment]
following @oscarotero idea, here is a real app example of why having it declare as an object improves the readability of allowing permissions in the deno config
![2024-10-18T06-20-25_code](https://github.com/user-attachments/assets/cf28884e-ed1c-4c02-9535-f09ef1b1ffae)

**Comment by brianpeiris** [comment]
Please consider my proposal #26372 as well. This proposal seems fine, but in my issue I suggest a simpler solution, but one that also supports multiple "profiles" that can be applied appropriately in different contexts. If my proposal is less appealing, I'd suggest adding the idea of multiple "profiles" to this proposal, so that you aren't globally applying the same set of permissions to all context. For example, my proposal would allow you to use one profile for `deno run` and a different profile for `deno serve`.

**Comment by Xiphe** [comment]
I really like this direction and I think it would really help everyone using granular permissions instead of `--allow-all`.
Before I was pointed here I've written a similar proposal with using permission-config-files: https://github.com/denoland/deno/discussions/27190 - maybe that's inspiring somehow. 

Thank you all for moving towards a simplification of this.

**Comment by Reububble** [comment]
## `deno test` permissions workarounds

> > Can you instruct users to type `deno task test` instead of `deno test`?
> 
> Yes, I can. And then this makes Deno an inferior ecosystem to npm, where to learn how to run a project's tests, I don't need to look it up in the project's readme. I just always use `npm test`.

Assuming the solution is not to implicitly give permissions to `deno test`, the permissions must be granted by the user in some form. A user is likely to try `deno test` without permissions first, so at this point it would be nice to somehow prompt the user for the permissions, and think that should be (part of) the solution to this proposal.

Right now of course, that's not possible exactly, but perhaps a workaround for this specific issue you have is to use the `Deno.permissions` object to query the permissions pre-test, and show a custom error message to the user, then `Deno.exit(1)`.

## Extending the workaround to `deno run`

Similar is true for any other problem case that this proposal wants to solve: If you were to run without permissions, deno might pause the program while it waits for the user to explicitly grant a permission. The `--no-prompt` flag can help with this by terminating the program instead, which is in many cases more ideal than pausing the program. The difference between running `deno test` and `deno run` in this case is that you can **request** permissions at runtime. So similar to how we can query the permissions pre-test, we can request the permissions at program startup. Nothing stops us from doing this today. No matter what your permissions logic is, you can program it into your source code. If there would be many permissions requests, you can suggest the user uses your custom `deno task` which has the permissions written into it. We can't make everyone use the `Deno.permissions` approach, but we can assume that good authors will write appropriate tasks for their programs.

## Redundant permissions objects

The only practical problem at this stage then, is that permissions objects can be duplicated across multiple instances, which is a redundancy waiting for real issues. If we're going to solve that, there needs to be some way for permissions objects should be able to be referenced. This thread has seen a few examples of this already. I would like to be able to reference these permissions objects from `deno run` but there are command line tools that would simplify reusing permissions objects from the command line. `deno task` on the other hand wouldn't have access to the same tools and that's where I think the solution to this proposal should focus.

## Security

This thread has seen proposals where the permissions are implicitly granted based on the config file, which presents a security concern because the config file itself can be written to, invalidating any approval the user might have implied. Above, others have agreed that there is a security issue with trusting the config file permissions implicitly. This is already an issue, and I think it's a severe one, where the tasks have the same implied approval. I think explicit approval should be needed when invoking a task, in a similar way to how permissions work right now: either provide a flag `deno task --allow-task-permissions` or prompt the user to grant the list of permissions that the task requests, retaining the option to specify permissions granularly, pending discussion.

## Solution

So we want a way to write permissions objects that we can reference from tasks and we should have a way to easily grant those permissions. We also want to suggest a permissions object for tests. It would be nice if we could specify the permissions object that `deno test` runs with, similar to how a task does it. Somewhere in the config, there should be an entry along the lines of `"testPermissions": "myPermissions"`, pending discussion. Since each task can have multiple `deno run` commands in it, and we want to prompt for permissions as soon as the task begins, we either need some way to preemptively read the task string and extract the permissions flags required, or we can provide permissions references separately to the command. It could be something along the lines of
```
"myTask": {
  "command": "deno run a.ts",
  "permissions": "myPermissions"
}
```
or
```
"myTask": "sleep 10 && deno run --permissions=myPermissions a.ts"
```
pending discussion.

## Summary

We have suitable workarounds for most of the issues this proposal would want to fix. Permissions in config files should be defined using "permissions object"s which can be referenced from tasks. I think tasks aren't secure enough right now and should require explicit permissions in some form from the command line. I was only expecting to write one paragraph when I started this but here we are.
