### ISSUE TITLE
[test] Log failing tests in final summary when using nested tests

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#12796]
When tests fail inside nested tests, if possible id love to see those specific tests mentioned at the bottom summary of failures. At the moment, it just lists the main initial test which makes it a bit difficult to spot the failure until i scroll and go through hundreds of tests to figure out the failing one. 

**Current:**

```
failures:

[Bot] - Starting Tests
Error: 2 test steps failed.
    at runTest (deno:runtime/js/40_testing.js:353:11)
    at async Object.runTests (deno:runtime/js/40_testing.js:460:22)

failures:

        [Bot] - Starting Tests
```

**Ideally**

```
failures:

[Bot] - Starting Tests
Error: 2 test steps failed.
    at runTest (deno:runtime/js/40_testing.js:353:11)
    at async Object.runTests (deno:runtime/js/40_testing.js:460:22)

failures:

        [Bot] - Starting Tests
            test [channel] delete a channel with a reason ... FAILED (11s)
            test [channel] delete a channel without a reason ... FAILED (11s)
```

**Comment by bartlomieju** [comment]
@dsherret is this something we could do easily?

**Comment by lucacasonato** [comment]
We do this now:

```ts
// test_test.ts
Deno.test("test", async (t) => {
  await t.step("step 1", () => {
    throw new Error("step 1 error");
  });

  await t.step("step 2", () => {
    console.log("hello");
  });
});
```

```
/t/test ❯❯❯ deno test
Check file:///tmp/test/test_test.ts
running 1 test from ./test_test.ts
test ...
  step 1 ... FAILED (1ms)
  step 2 ...
------- output -------
hello
----- output end -----
  step 2 ... ok (0ms)
test ... FAILED (due to 1 failed step) (1ms)

 ERRORS 

test ... step 1 => ./test_test.ts:2:11
error: Error: step 1 error
    throw new Error("step 1 error");
          ^
    at file:///tmp/test/test_test.ts:3:11
    at innerWrapped (ext:cli/40_test.js:191:11)
    at exitSanitizer (ext:cli/40_test.js:107:33)
    at Object.outerWrapped [as fn] (ext:cli/40_test.js:134:20)
    at TestContext.step (ext:cli/40_test.js:492:37)
    at file:///tmp/test/test_test.ts:2:11

 FAILURES 

test ... step 1 => ./test_test.ts:2:11

FAILED | 0 passed (1 step) | 1 failed (1 step) (2ms)

error: Test failed
```
