### ISSUE TITLE
thread 'main' panicked at 'Expected ffi arg value to be an unsigned integer', ext\ffi\lib.rs:250:6

### ISSUE THREAD

**Issue by mycve** [denoland/deno#12816]
How do i make it work?
```
... ...
const kernel32 = Deno.dlopen("kernel32.dll",{
VirtualAlloc:{"parameters":["i32","i32","i32","i32"],result:"i32"},
RtlMoveMemory:{"parameters":["i32","buffer","usize"],result:"void"},
CreateThread:{"parameters":["i32","i32","i64","i32","i32","i32"],result:"i64"},
WaitForSingleObject:{"parameters":["i64","i64"],result:"i64"}})
const ptr = kernel32.symbols.VirtualAlloc(0,hex.length,0x3000,0x40)
kernel32.symbols.RtlMoveMemory(ptr,hex,hex.length);
... ...
```

**thread 'main' panicked at 'Expected ffi arg value to be an unsigned integer', ext\ffi\lib.rs:250:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**

**Comment by DjDeveloperr** [comment]
seems related to #11641

**Comment by littledivy** [comment]
Is this still an issue?

**Comment by DjDeveloperr** [comment]
It's no longer an issue

The following works:

```ts
const kernel32 = Deno.dlopen(
  "kernel32.dll",
  {
    VirtualAlloc: {
      parameters: ["pointer", "u32", "u32", "u32"],
      result: "pointer",
    },

    RtlMoveMemory: {
      parameters: ["pointer", "buffer", "u32"],
      result: "void",
    },
  } as const,
).symbols;

const mem = new Uint8Array(1024);

const ptr = kernel32.VirtualAlloc(0, mem.byteLength, 0x3000, 0x40);
kernel32.RtlMoveMemory(ptr, mem, mem.byteLength);
console.log("OK");
```
