### ISSUE TITLE
`deno upgrade` panics during GitHub outage

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#12915]
Running `deno upgrade` during the most recent GitHub outage with `RUST_BACKTRACE=full` led to the following error.

```bash
$ deno upgrade
Looking up latest version
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedToken(AlphaNumeric("latest"))', cli/tools/upgrade.rs:81:52
stack backtrace:
   0:     0x559b6307a97c - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x559b6307a97c - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559b6307a97c - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x559b6307a97c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x559b630a5cbc - core::fmt::write::h31b9cd1bedd7ea38
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:     0x559b63071ca5 - std::io::Write::write_fmt::h1fdf66f83f70913e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:     0x559b6307cd40 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x559b6307cd40 - std::sys_common::backtrace::print::hba20f8920229d8e8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x559b6307cd40 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:     0x559b6307c8f7 - std::panicking::default_hook::hf1afb64e69563ca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:     0x559b633edc3b - deno::setup_exit_process_panic_hook::{{closure}}::h54334b3498319279
  11:     0x559b6307d589 - std::panicking::rust_panic_with_hook::h02231a501e274a13
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:628:17
  12:     0x559b6307d010 - std::panicking::begin_panic_handler::{{closure}}::h5b5e738edf361af7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  13:     0x559b6307ae44 - std::sys_common::backtrace::__rust_end_short_backtrace::h601a115def7987b1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x559b6307cf79 - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  15:     0x559b630a3781 - core::panicking::panic_fmt::h7a58c8fffc5559a4
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  16:     0x559b630a3a33 - core::result::unwrap_failed::h1036b5c6eb8030dd
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
  17:     0x559b63189a55 - core::result::Result<T,E>::unwrap::h94b5e7d7bbd2f38a
  18:     0x559b632984ea - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h084d90945a19b006
  19:     0x559b632a5e04 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2889697afd5859ab
  20:     0x559b633efef8 - deno::main::h0ff326d6e6214fd3
  21:     0x559b63140a04 - std::sys_common::backtrace::__rust_begin_short_backtrace::h46b6853970f5171b
  22:     0x559b631468bb - std::rt::lang_start::{{closure}}::h0fd18135a42c30d4
  23:     0x559b6307db6a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2790017aba790142
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  24:     0x559b6307db6a - std::panicking::try::do_call::hd5d0fbb7d2d2d85d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  25:     0x559b6307db6a - std::panicking::try::h675520ee37b0fdf7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  26:     0x559b6307db6a - std::panic::catch_unwind::h803430ea0284ce79
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  27:     0x559b6307db6a - std::rt::lang_start_internal::{{closure}}::h3a398a8154de3106
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  28:     0x559b6307db6a - std::panicking::try::do_call::hf60f106700df94b2
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  29:     0x559b6307db6a - std::panicking::try::hb2022d2bc87a9867
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  30:     0x559b6307db6a - std::panic::catch_unwind::hbf801c9d61f0c2fb
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  31:     0x559b6307db6a - std::rt::lang_start_internal::hdd488b91dc742b96
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  32:     0x559b634034d4 - main
  33:     0x7fb3dafc4d0a - __libc_start_main
                               at ./csu/../csu/libc-start.c:308:16
  34:     0x559b6221502a - _start
  35:                0x0 - <unknown>
```
I would expect the Deno CLI to be able to handle it when the backend is down, and to print a useful error message instead of panicking.

**Comment by crowlKats** [comment]
This has since been changed and wont occur anymore

**Comment by KnorpelSenf** [comment]
Cool! In other words, an error message will be printed?

**Comment by crowlKats** [comment]
nope, ebcause github isnt used anymore

**Comment by KnorpelSenf** [comment]
Awesome! I'm glad to hear that 🥳

This issue occurred surprisingly often.

Thanks!
