### ISSUE TITLE
--compat fails for zeromq

### ISSUE THREAD

**Issue by apowers313** [denoland/deno#12939]
Running the nine lines of example [zeromq's producer.js example code](https://zeromq.org/languages/nodejs/) produces the cryptic error message:

> error: Uncaught (in promise) SyntaxError: Invalid or unexpected token
    at wrapSafe (https://deno.land/std@0.116.0/node/module.ts:1257:39)
    at Module._compile (https://deno.land/std@0.116.0/node/module.ts:242:29)
    at Object.Module._extensions..js (https://deno.land/std@0.116.0/node/module.ts:1276:10)
    at Module.load (https://deno.land/std@0.116.0/node/module.ts:230:34)
    at Function._load (https://deno.land/std@0.116.0/node/module.ts:539:14)
    at Module.require (https://deno.land/std@0.116.0/node/module.ts:216:21)
    at require (https://deno.land/std@0.116.0/node/module.ts:1331:16)
    at load (file:///Users/ampower/Projects/proto/node-zeromq-test/node_modules/node-gyp-build/index.js:21:10)
    at Object.<anonymous> (file:///Users/ampower/Projects/proto/node-zeromq-test/node_modules/zeromq/binding.js:1:105)
    at Module._compile (https://deno.land/std@0.116.0/node/module.ts:251:36)

Error is produced inside `Deno.core.evalContext`, presumably as it is loading the `zeromq` module, but the error message doesn't give any information on what line of code or why. My best guess is that `zeromq` is using `node-gyp` which isn't supported by Deno?

**Comment by bartlomieju** [comment]
@apowers313 there are two frames in the trace pointing to the problematic place:
```
at load (file:///Users/ampower/Projects/proto/node-zeromq-test/node_modules/node-gyp-build/index.js:21:10)
at Object. (file:///Users/ampower/Projects/proto/node-zeromq-test/node_modules/zeromq/binding.js:1:105)
```
And it is indeed related to accessing `node-gyp-build` package. 

Unfortunately this is not something we'll be able to address in foreseeable future, so I'm going to close the issue.

**Comment by littledivy** [comment]
NAPI support might land soon #13633. Re-opening since zeromq is also using NAPI.

**Comment by kt3k** [comment]
@milahu compat mode can't run typescript as an entrypoint. `src/pnpm.ts` is executed as javascript in your example. That causes the SyntaxError.

If you want to run pnpm in compat mode, what you need to do is:
```sh
npm install -g pnpm
which pnpm # in my case this returns /Users/kt3k/.nvm/versions/node/v16.9.1/bin/pnpm
deno run --compat --unstable -A /path/to/bin/pnpm
```

**Comment by milahu** [comment]
> compat mode can't run typescript as an entrypoint

damn. im using deno is to run typescript

i added `--compat` to fix

```
$ deno run src/pnpm.ts 
error: Uncaught ReferenceError: process is not defined
process.setMaxListeners(0)
^
    at file:///tmp/pnpm/packages/pnpm/src/pnpm.ts:4:1
```

... and `--compat` needs `--unstable` and `-A`

> `npm install -g pnpm`

will install the compiled javascript version, which is trivial to run

**Comment by bartlomieju** [comment]
This issue is no longer relevant since --compat mode was removed. Prefer to use `npm:` specifiers instead.
