### ISSUE TITLE
compat: type-detect breaks on access to window.location

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12969]
[`type-detect`](https://www.npmjs.com/package/type-detect) is a very popular Node package (over 14m weekly downloads). However it cannot run in `--compat` without `--location` flag:

```
deno run --compat --unstable -A --no-check ./dist/bin/nps.js -c ./package-scripts.js
error: Uncaught (in promise) ReferenceError: Access to "location", run again with --location <href>.
    if (typeof window.location === 'object' && obj === window.location) {
                      ^
    at get (deno:ext/web/12_location.js:381:17)
    at typeDetect (file:///Users/biwanczuk/dev/nps/node_modules/type-detect/type-detect.js:118:23)
    at loadConfig (file:///Users/biwanczuk/dev/nps/dist/bin-utils/index.js:107:78)
    at getPSConfig (file:///Users/biwanczuk/dev/nps/dist/bin-utils/parser.js:274:35)
    at parse (file:///Users/biwanczuk/dev/nps/dist/bin-utils/parser.js:124:18)
    at Object.<anonymous> (file:///Users/biwanczuk/dev/nps/dist/bin/nps.js:21:33)
    at Module._compile (file:///Users/biwanczuk/dev/deno_std/node/module.ts:251:36)
    at Object.Module._extensions..js (file:///Users/biwanczuk/dev/deno_std/node/module.ts:1276:10)
    at Module.load (file:///Users/biwanczuk/dev/deno_std/node/module.ts:230:33)
    at Function._load (file:///Users/biwanczuk/dev/deno_std/node/module.ts:539:14)

```

I found this problem when trying to run [`nps`](https://www.npmjs.com/package/nps).

I believe this severely hinders DX, and we should consider how to solve it. An obvious solution is make `window.location` be `undefined` if no `--location` flag is passed: https://github.com/denoland/deno/pull/10828

CC @kt3k

**Comment by kt3k** [comment]
I keep avoiding that error by supplying `--location` option when I try `nps` locally.

> An obvious solution is make window.location be undefined if no --location flag is passed: #10828

That might be a solution, but because we now supply opaque origin when `--location` is not specified, it feels more natural to me to provide `window.location` object always even when `--location` isn't specified

**Comment by lucacasonato** [comment]
> but because we now supply opaque origin when --location is not specified, it feels more natural to me to provide window.location object always even when --location isn't specified

That opaque origin is for storage only (it isn't really an origin, rather just an opaque storage key). It does not make sense to use for `--location`, because that location's origin does not match the origin of the storage.

Let's just go with `window.location` returning `undefined` when `--location` is not set.

**Comment by bartlomieju** [comment]
I agree with Luca, let's reopen rebased version of #10828

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno/issues/10825
