### ISSUE TITLE
watcher: disable terminal raw mode at each restart

### ISSUE THREAD

**Issue by Im-Beast** [denoland/deno#12995]
After each restart watcher should also disable terminal raw mode (`Deno.setRaw`), as it makes it impossible to kill running command using `Ctrl+C`. It's especially annoying when we haven't specified correct permissions as we have to reopen the terminal.

**Comment by bartlomieju** [comment]
@Im-Beast do you have a program that would replicate the current buggy behavior? FYI I have no trouble existing process with `Ctrl+C` so I presume this only happens if a program actually sets raw mode for terminal.

**Comment by Im-Beast** [comment]
Yes, this only happens if program sets raw mode for terminal.

**Comment by bartlomieju** [comment]
I think this is sensible. If anyone wants to work on this then please do, otherwise I'll put it in my backlog.

**Comment by bartlomieju** [comment]
Actually I think this is not something that should happen automatically - if your application uses raw mode, then it should disable it on `unload` event. That event is already dispatched when the watcher restarts the process.

```js
window.addEventListener("unload", () => {
   Deno.setRawMode(Deno.stdin.rid, false);
});
```

**Comment by Im-Beast** [comment]
I think it'd be better just like you say, especially when It'd be noted in docs

**Comment by Im-Beast** [comment]
Problem doing it like that is that doing actions on readers/writers are asynchronous and when they're already used somewhere else they throw error and don't disable raw mode.

**Comment by bartlomieju** [comment]
> Problem doing it like that is that doing asynchronous actions on readers/writers when they're already used somewhere else they throw.

I'm not sure what you mean here, can you provide a reproduction?

> Edit: Also when file gets changed and `Deno.setRaw` throws on `unload` event it causes watcher to panic

This is interesting, I'll try to replicate it; that said it's perfectly fine for `Deno.setRaw` to throw so you should call it in `try/catch` anyway.

**Comment by Im-Beast** [comment]
Reproduction:
```ts
const reader = Deno.stdin;

async function* readKeys() {
  Deno.setRaw(reader.rid, true, {
    cbreak: true,
  });

  addEventListener("unload", () => {
    Deno.setRaw(reader.rid, false);
  });

  while (true) {
    const buffer = new Uint8Array(1024);

    const byteLength = await reader.read(buffer);
    if (typeof byteLength !== "number") continue;

    yield buffer.subarray(0, byteLength);
  }
}

Deno.addSignalListener("SIGINT", () => {
  Deno.exit(0);
});

for await (const _ of readKeys()) {
  //
}
```

I can't reproduce panicing with a simple example, however it happens on my larger project.

**Comment by bartlomieju** [comment]
@Im-Beast thank you I will check it. If you could trigger the panic with `env RUST_BACKTRACE=full` and paste the output that would still be very useful.

**Comment by Im-Beast** [comment]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Uncaught Busy: Resource is unavailable because it is in use by a promise
    Deno.setRaw(reader.rid, false);
         ^
    at Object.opSync (deno:core/01_core.js:142:12)
    at Object.setRaw (deno:runtime/js/40_tty.js:21:10)
    at file:///home/mateusz/Documents/Projects/deno_tui/src/key_reader.ts:194:10
    at innerInvokeEventListeners (deno:ext/web/02_event.js:749:9)
    at invokeEventListeners (deno:ext/web/02_event.js:788:5)
    at dispatch (deno:ext/web/02_event.js:658:11)
    at dispatchEvent (deno:ext/web/02_event.js:989:14)
    at [deno:cli/main.rs:1130:14]:1:8', cli/main.rs:1133:12
stack backtrace:
   0:     0x556f1b112ec2 - <unknown>
   1:     0x556f1a9a7bdc - <unknown>
   2:     0x556f1b111274 - <unknown>
   3:     0x556f1b112080 - <unknown>
   4:     0x556f1b1117b5 - <unknown>
   5:     0x556f1a9616d1 - <unknown>
   6:     0x556f1b11112f - <unknown>
   7:     0x556f1b130948 - <unknown>
   8:     0x556f1b1308c6 - <unknown>
   9:     0x556f1b130882 - <unknown>
  10:     0x556f1a583a30 - <unknown>
  11:     0x556f1a583d12 - <unknown>
  12:     0x556f1a62d0ec - <unknown>
  13:     0x556f1a62cf52 - <unknown>
  14:     0x556f1a75a83e - <unknown>
  15:     0x556f1a757d49 - <unknown>
  16:     0x556f1a621ce5 - <unknown>
  17:     0x556f1a6124dc - <unknown>
  18:     0x556f1a60de3b - <unknown>
  19:     0x556f1a60e0fd - <unknown>
  20:     0x7f9ef12b7b25 - __libc_start_main
  21:     0x556f1a5bfafe - <unknown>
  22:                0x0 - <unknown>
```
I hope It'll help, thank you for spending time on this wonderful project!
