### ISSUE TITLE
Deno Installation Error (v1.16.4) using Cargo on Ubuntu 21.10 (x86_64)

### ISSUE THREAD

**Issue by ImranQ8546** [denoland/deno#13067]
As a root user in the ZSH shell, I attempt to install DENO using the following command at the prompt:

cargo install deno

Towards the end of the installation, the install crashes with the following output:

**error: failed to run custom build command for `deno_runtime v0.36.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install9AwAn6/release/build/deno_runtime-9e0f6933c22daa4f/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=TARGET=x86_64-unknown-linux-gnu
  cargo:rustc-env=PROFILE=release
  cargo:rerun-if-changed=/home/xxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.110.0/00_primordials.js

  ......<many more similar messages as above>

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unable to build http client: builder error: Unknown TLS backend passed to `use_preconfigured_tls`', /home/xxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_fetch-0.51.0/lib.rs:120:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.16.4`, intermediate artifacts can be found at `/tmp/cargo-install9AwAn6`

Caused by:
  build failed**

**Comment by lucacasonato** [comment]
Use `cargo install deno --locked` as the instructions say: https://deno.land#installation.

**Comment by ImranQ8546** [comment]
Unfortunately, that results in the exact same error.

I have also tried the command:

cargo install-update -a

But both commands fail to install or upgrade deno.

The only thing that seems to work is:

deno upgrade

**Comment by garypen** [comment]
I've got a strange problem with 00_primordials.js as well. I don't think it's quite the same problem as yours, but if I try to create and run a `JsRuntime()` in my server process, then it works fine on my build machine. However, if I copy the binary elsewhere (say into a container), then it crashes with errors similar to (sanitized):
```
cargo:rerun-if-changed=/Users/HOME_DIR/.asdf/installs/rust/1.57.0/registry/src/github.com-1ecc6299db9ec823/deno_core-0.110.0/00_primordials.js
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /Users/HOME_DIR/.asdf/installs/rust/1.57.0/registry/src/github.com-1ecc6299db9ec823/deno_core-0.110.0/runtime.rs:402:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'NaiveIntrospection instantiation panicked: JoinError::Panic(...)', apollo-router/src/apollo_router.rs:45:18
2021-12-13T16:31:40.037003Z ERROR router: Failed to start server.
Error: Failed to start server.
```
It looks like the runtime (runtime.rs:402) is trying to load some javascript files at runtime as a consequence of not being a snapshot VM. Why it's doing this, I don't know... They are present on my build machine, but clearly not present when the process executes in a container.

Maybe this extra information will help narrow down the problem?

**Comment by garypen** [comment]
> @garypen Your problem is different. You are just not snapshotting the isolate, and instead doing loading of builtins at runtime. This is not something that is really supported by `deno_core`. You should use a snapshot.

Ok. Thanks for the info. It looks like this used to work in older versions of deno-core (e.g.: 0.86) because we didn't trip over that problem before we upgraded our dependency to 0.110. Does that make sense?

**Comment by lucacasonato** [comment]
Yes, this was introduced recently.

**Comment by spaghetus** [comment]
I'm trying to use the deno_runtime crate and my crate is failing to compile with the same error as @ImranQ8546. I'm using Fedora Silverblue 35 and the latest nightly rustc.

**Comment by gufoe** [comment]
I am having the same issue, I will add some logs hoping they can help somebody.
The problem only appears when I try to run the executable inside a docker container on `debian:bullseye-slim`. I tried installing `libv8-dev` and `nodejs` on the container, hoping they could provide some dependencies, but nothing changed. 


The lines causing the issue:
```rust
let opts = RuntimeOptions::default();
let mut runtime = JsRuntime::new(opts); # this gives the error
```

Full backtrace (problem is point 4-5):
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.107.0/runtime.rs:399:38
stack backtrace:
cargo:rerun-if-changed=/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.107.0/00_primordials.js
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1299:23
   4: deno_core::runtime::JsRuntime::new
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.107.0/runtime.rs:399:7
   5: js_engine::engine_deno::exec_code
             at /app/src/engine_deno.rs:9:23
   6: js_engine::deno_executor::{{closure}}
             at /app/src/main.rs:44:14
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
   8: <F as futures_core::future::TryFuture>::try_poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.17/src/future.rs:82:9
   9: <warp::filter::and_then::State<T,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.1/src/filter/and_then.rs:99:44
  10: <warp::filter::and_then::AndThenFuture<T,F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.1/src/filter/and_then.rs:74:9
  11: <F as futures_core::future::TryFuture>::try_poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.17/src/future.rs:82:9
  12: <warp::filters::cors::internal::WrappedFuture<F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.1/src/filters/cors.rs:577:26
  13: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.17/src/future/either.rs:90:33
  14: <F as futures_core::future::TryFuture>::try_poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.17/src/future.rs:82:9
  15: <warp::filter::service::FilteredFuture<F> as core::future::future::Future>::poll::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.1/src/filter/service.rs:128:41
  16: scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  17: warp::route::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.1/src/route.rs:17:5
  18: <warp::filter::service::FilteredFuture<F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.1/src/filter/service.rs:128:15
  19: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.14/src/proto/h1/dispatch.rs:491:35
  20: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.14/src/proto/h1/dispatch.rs:297:43
  21: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.14/src/proto/h1/dispatch.rs:161:21
  22: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.14/src/proto/h1/dispatch.rs:137:16
  23: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.14/src/proto/h1/dispatch.rs:120:28
  24: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.14/src/proto/h1/dispatch.rs:424:9
  25: <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.14/src/server/conn.rs:1061:47
  26: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.14/src/server/conn.rs:1265:30
  27: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.14/src/server/conn.rs:1202:36
  28: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/core.rs:161:17
  29: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/loom/std/unsafe_cell.rs:14:9
  30: tokio::runtime::task::core::CoreStage<T>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/core.rs:151:13
  31: tokio::runtime::task::harness::poll_future::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/harness.rs:461:19
  32: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panic/unwind_safe.rs:271:9
  33: std::panicking::try::do_call
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  34: __rust_try
  35: std::panicking::try
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  36: std::panic::catch_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  37: tokio::runtime::task::harness::poll_future
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/harness.rs:449:18
  38: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/harness.rs:98:27
  39: tokio::runtime::task::harness::Harness<T,S>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/harness.rs:53:15
  40: tokio::runtime::task::raw::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/raw.rs:113:5
  41: tokio::runtime::task::raw::RawTask::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/raw.rs:70:18
  42: tokio::runtime::task::LocalNotified<S>::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/mod.rs:343:9
  43: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/thread_pool/worker.rs:420:13
  44: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:106:9
  45: std::thread::local::LocalKey<T>::try_with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:399:16
  46: std::thread::local::LocalKey<T>::with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:375:9
  47: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:99:5
  48: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:76:5
  49: tokio::runtime::thread_pool::worker::Context::run_task
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/thread_pool/worker.rs:419:9
  50: tokio::runtime::thread_pool::worker::Context::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/thread_pool/worker.rs:386:24
  51: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/thread_pool/worker.rs:371:17
  52: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/macros/scoped_tls.rs:61:9
  53: tokio::runtime::thread_pool::worker::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/thread_pool/worker.rs:368:5
  54: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/thread_pool/worker.rs:347:45
  55: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/blocking/task.rs:42:21
  56: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/core.rs:161:17
  57: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/loom/std/unsafe_cell.rs:14:9
  58: tokio::runtime::task::core::CoreStage<T>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/core.rs:151:13
  59: tokio::runtime::task::harness::poll_future::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/harness.rs:461:19
  60: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panic/unwind_safe.rs:271:9
  61: std::panicking::try::do_call
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  62: __rust_try
  63: std::panicking::try
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  64: std::panic::catch_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  65: tokio::runtime::task::harness::poll_future
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/harness.rs:449:18
  66: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/harness.rs:98:27
  67: tokio::runtime::task::harness::Harness<T,S>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/harness.rs:53:15
  68: tokio::runtime::task::raw::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/raw.rs:113:5
  69: tokio::runtime::task::raw::RawTask::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/raw.rs:70:18
  70: tokio::runtime::task::UnownedTask<S>::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/mod.rs:379:9
  71: tokio::runtime::blocking::pool::Inner::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/blocking/pool.rs:265:17
  72: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/blocking/pool.rs:245:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
