### ISSUE TITLE
WS Server Shows Client as NOT OPEN, Even When It Is

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#13143]
```ts
import { Server } from "./src/server.ts"
import { deferred } from "./tests/deps.ts"
const s  = new Server({
    hostname: "localhost",
    port: 1447,
    protocol: "ws"
})
s.run()
const c = new WebSocket(s.address)
const p = deferred()
c.onopen = () => p.resolve()
await p
console.log(c.readyState)
s.to("channel", {

})
```
```
PS D:\Development\drashland\wocket> deno run -A .\a.ts
Check file:///D:/Development/drashland/wocket/a.ts
1
error: Uncaught (in promise) InvalidStateError: readyState not OPEN
    client!.socket.send(JSON.stringify({
                   ^
    at WebSocket.send (deno:ext/websocket/01_websocket.js:278:15)
    at Server.#send (file:///D:/Development/drashland/wocket/src/server.ts:255:20)
    at Server.to (file:///D:/Development/drashland/wocket/src/server.ts:119:17)
    at file:///D:/Development/drashland/wocket/a.ts:27:3
```

Server shouldn't really matter here right? the client is open by the time the server tries to do `client.send(...)`, so no clue why it'd say the client isnt open in the server?

**Comment by ebebbington** [comment]
not an issue with deno
