### ISSUE TITLE
Deno.addSignalListener is leaking async ops

### ISSUE THREAD

**Issue by Im-Beast** [denoland/deno#13265]
`Deno.addSignalListener` is leaking async ops

### Reproduction:
```ts
Deno.test("leaking", () => {
  Deno.addSignalListener("SIGINT", () => {});
});
```

### Error output:
```
test leaking ... FAILED (13ms)

failures:

leaking
AssertionError: Test case is leaking async ops.
Before:
  - dispatched: 0
  - completed: 0
After:
  - dispatched: 2
  - completed: 1
Ops:
  op_signal_poll:
    Before:
      - dispatched: 0
      - completed: 0
    After:
      - dispatched: 1
      - completed: 0

Make sure to await all promises returned from Deno APIs before
finishing test case.
    at assert (deno:runtime/js/06_util.js:41:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:122:7)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:138:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:170:9)
    at async runTest (deno:runtime/js/40_testing.js:428:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:541:22)

failures:

        leaking

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (43ms)
```

**Comment by kt3k** [comment]
You need to call `removeSignalListener` API to prevent op leak:

```ts
Deno.test("remove signal listener", () => {
  const handler = () => {}; 
  Deno.addSignalListener("SIGINT", handler);
  Deno.removeSignalListener("SIGINT", handler);
});
```
