### ISSUE TITLE
Unable to open file even with `--allow-all`

### ISSUE THREAD

**Issue by akalsi87** [denoland/deno#13379]
I'm trying out `deno`, and trying to serve a static file:

import_map.json
```json
{
  "imports": {
    "/": "./",
    "./": "./",
    "deno/": "https://deno.land/std@0.121.0/"
  }
}
```
code:
```javascript
import { serveFile } from 'deno/http/file_server.ts';

Deno.test('static router can serve', async () => {
  console.log(await serveFile(new Request(`http://foo/`), import.meta.url));
});
```

shell:
```sh
$ deno --version
deno 1.17.3 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2

$ deno test --allow-all --import-map import_map.json
Check file://<snip>/router.test.ts
running 1 test from file://<snip>/router.test.ts
test static router can serve ... FAILED (6ms)

failures:

static router can serve
NotFound: No such file or directory (os error 2), open 'file://<snip>/router.test.ts'
    at async Object.open (deno:runtime/js/40_files.js:51:17)
    at async Promise.all (index 0)
    at async serveFile (https://deno.land/std@0.121.0/http/file_server.ts:241:28)
    at async file://<snip>/router.test.ts:13:15
    at async testStepSanitizer (deno:runtime/js/40_testing.js:187:7)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:68:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:138:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:170:9)
    at async runTest (deno:runtime/js/40_testing.js:428:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:541:22)

failures:

        static router can serve

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (22ms)

error: Test failed
```

This may be a noob mistake.

**Comment by akalsi87** [comment]
Figured it out: cannot pass URLs to `Deno.open`

**Comment by lucacasonato** [comment]
@akalsi87 You can pass URLs, but only as URL objects, not as strings.
