### ISSUE TITLE
REPL exits on certain errors

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1343]
For example, this crashes the REPL
```
$ deno
> setTimeout(1)
1
> TypeError: callback is not a function
    at fire (deno/js/timers.ts:131:3)
```

**Comment by kitsonk** [comment]
I don't think that is unique to the REPL:

```
$ cat test.js
// @ts-nocheck
setTimeout(1)

$ deno test.js
Compiling /Users/kkelly/github/deno_example/test.js
TypeError: callback is not a function
    at fire (deno/js/timers.ts:131:3)

```

We have a `setTimeout` that doesn't exhibit the same (nonsensical) runtime behaviour as other runtimes do.

While this is technically valid, what is occurring is likely unintentional and arguable if we would actually want to support it.  The timeout is optional, but the [first argument is allowed to be a function or a string which gets eval'ed](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout).  Because the first argument isn't a function, the argument is implicitly coerced into a string, (`1` becomes `"1"`) and then is eval'ed.  We don't support that interface in our declaration:

```ts
export function setTimeout(
    cb: (...args: Args) => void,
    delay: number,
    ...args: Args
  ): number;
```

And clearly we don't support it at runtime.  This is why I had to turn off TypeScript checking in order to get (bad) code to actually run.  I think it is perfectly acceptable to align our runtime behaviour to our type definitions and not go to extra lengths if people ignore it, and I don't think supporting the ability to allow implicitly coerced strings be eval'ed is really desirable behaviour.  That would never be added to browsers today and is clearly there for backwards compatibility.

**Comment by bartlomieju** [comment]
Tested with Deno v0.5.0 and no longer happening. Can we close this issue now? CC @ry
