### ISSUE TITLE
WebGPU: Deno Panic when several `device.queue.submit` are called

### ISSUE THREAD

**Issue by Jimdooz** [denoland/deno#13571]
I'm currently trying to use the WebGPU Api, and I got this error when I call the `device.queue.submit` function multiple times.

Here my code :
```ts
const adapter = await navigator.gpu.requestAdapter();
if (!adapter) throw "No adapter found";
const device = await adapter.requestDevice();

const numbers = [1, 2, 3, 4, 5, 6, 7];
const size = new Uint32Array(numbers).byteLength;

//Create buffers
const stagingBuffer = device.createBuffer({
    size: size,
    usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST
});

const storageBuffer = device.createBuffer({
    size: size,
    usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC,
    mappedAtCreation: true
});
new Uint32Array(storageBuffer.getMappedRange()).set(numbers);
storageBuffer.unmap();

//Create command
const copyEncoder = device.createCommandEncoder();
copyEncoder.copyBufferToBuffer(storageBuffer, 0, stagingBuffer, 0, size);
const copyCommands = copyEncoder.finish();

//Submit command
device.queue.submit([copyCommands]);
device.queue.submit([copyCommands]); // <--- Deno panic
```

The panic error :
```
$deno run -A --unstable ./gpu_error.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.18.1
Args: ["deno", "run", "-A", "--unstable", "./gpu_error.ts"]

thread 'main' panicked at 'Cannot remove a vacant resource', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.12.2\src\hub.rs:185:32
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Jimdooz** [comment]
I have updated Deno (1.8.2) and It seems that the problem persist, but the error has changed a little bit.

Same code has before.

Here the error :
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.18.2
Args: ["C:\\Users\\romai\\.deno\\bin\\deno.exe", "run", "-A", "--unstable", "./gpu_error.ts"]

thread 'main' panicked at 'Cannot remove a vacant resource', C:\Users\david\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.12.2\src\hub.rs:185:32
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by crowlKats** [comment]
This has since been fixed
