### ISSUE TITLE
Property 'getUid' does not exist on type 'typeof Deno'

### ISSUE THREAD

**Issue by tisonkun** [denoland/deno#13592]
I'm trying to create a demo working with PG and Deno:

```typescript
import pg from 'https://cdn.skypack.dev/pg';

const { Client } = pg.Client;
const client = new Client()
await client.connect()
const res = await client.query('SELECT $1::text as message', ['Hello world!'])
console.log(res.rows[0].message) // Hello world!
await client.end()
```

but I get this error message which seems an internal error of Deno:

```
$ deno run --allow-all app.ts             
Check file:///path/to/app.ts
error: TS2339 [ERROR]: Property 'getUid' does not exist on type 'typeof Deno'.
    if (Deno.build.os !== "windows" && info.uid === Deno.getUid()) {
                                                         ~~~~~~
    at https://deno.land/std@0.125.0/node/_fs/_fs_access.ts:24:58
```

How can I run the code or I just write a bug :)

**Comment by ry** [comment]
I believe this a bug introduced in the latest version. Try to upgrade to 1.18.1 and use the —unstable flag.

cc @kt3k

**Comment by tisonkun** [comment]
@ry I try to run with `--unstable` but the error keeps:

```
$ deno run --unstable --allow-all app.ts
Check file:///path/to/app.ts
error: TS2339 [ERROR]: Property 'getUid' does not exist on type 'typeof Deno'.
    if (Deno.build.os !== "windows" && info.uid === Deno.getUid()) {
                                                         ~~~~~~
    at https://deno.land/std@0.125.0/node/_fs/_fs_access.ts:24:58
$ deno --version                        
deno 1.18.1 (release, x86_64-apple-darwin)
v8 9.8.177.6
typescript 4.5.2
```

**Comment by crowlKats** [comment]
update deno to 1.18.2

**Comment by crowlKats** [comment]
you also should run with unstable

**Comment by tisonkun** [comment]
```
error: Uncaught Error: [Package Error] "node:crypto" does not exist. (Imported by "pg").
throw new Error("[Package Error] \"node:crypto\" does not exist. (Imported by \"pg\").");
      ^
    at https://cdn.skypack.dev/error/node:node:crypto?from=pg:14:7
```

Looks like that we're not very compatible with node now.

**Comment by tisonkun** [comment]
Resolve the original requirement by using `https://deno.land/x/postgres`.

Closed as the title issue fixed in nightly with unstable. The compatibility is another issue which I'm not interested now.
