### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli\lsp\language_server.rs:341:47

### ISSUE THREAD

**Issue by lts20050703** [denoland/deno#13601]
Platform: Windows 11
Deno Version: 1.18.2
Visual Studio Code: 1.65.0 Insider
Extension Version: 3.10.1
```
Starting Deno language server...
  version: 1.18.2 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\lts20050703\.deno\bin\deno.EXE
Connected to "Visual Studio Code - Insiders" 1.65.0-insider

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.18.2
Args: ["C:\\Users\\lts20050703\\.deno\\bin\\deno.EXE", "lsp"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli\lsp\language_server.rs:341:47
stack backtrace:
   0:     0x7ff6b868d104 - <unknown>
   1:     0x7ff6b7d0a6ea - <unknown>
   2:     0x7ff6b868b008 - <unknown>
   3:     0x7ff6b868c1b2 - <unknown>
   4:     0x7ff6b868b63e - <unknown>
   5:     0x7ff6b8cf8c46 - <unknown>
   6:     0x7ff6b868ae37 - <unknown>
   7:     0x7ff6b86aebb5 - <unknown>
   8:     0x7ff6b86aeb29 - <unknown>
   9:     0x7ff6b86aeae4 - <unknown>
  10:     0x7ff6b9b88b60 - CrashForExceptionInNonABICompliantCodeRange
  11:     0x7ff6b9b88e63 - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff6b8983431 - <unknown>
  13:     0x7ff6b8abc3f6 - <unknown>
  14:     0x7ff6b8ab304c - <unknown>
  15:     0x7ff6b8aafdb6 - <unknown>
  16:     0x7ff6b8496b18 - <unknown>
  17:     0x7ff6b8b12861 - <unknown>
  18:     0x7ff6b8b0e40f - <unknown>
  19:     0x7ff6b8b0c99a - <unknown>
  20:     0x7ff6b894da76 - <unknown>
  21:     0x7ff6b8937d16 - <unknown>
  22:     0x7ff6b8931870 - <unknown>
  23:     0x7ff6b8931916 - <unknown>
  24:     0x7ff6b9b4af2c - CrashForExceptionInNonABICompliantCodeRange
  25:     0x7ffed36054e0 - BaseThreadInitThunk
  26:     0x7ffed484485b - RtlUserThreadStart
```

**Comment by dsherret** [comment]
I'm not sure why that's happening.

Not so great, but the code path with that bug can be bypassed by creating a dummy `deno.json` file and then specifying a `"deno.config": "..."` setting in vscode's settings.json.
