### ISSUE TITLE
Assertion Error on Timer 

### ISSUE THREAD

**Issue by BayoKwendo** [denoland/deno#13635]
I am getting this error at intervals. the error seem to come from clearInterval Function on driver.
`Any lead in resolving it permanently? Thanks

    at assert (deno:ext/timers/01_timers.js:40:13)
    at setGlobalTimeout (deno:ext/timers/01_timers.js:349:5)
    at setOrClearGlobalTimeout (deno:ext/timers/01_timers.js:393:7)
    at unschedule (deno:ext/timers/01_timers.js:442:9)
    at clearTimer (deno:ext/timers/01_timers.js:564:5)
    at clearInterval (deno:ext/timers/01_timers.js:581:5)
    at https://deno.land/x/deno_cron@v1.0.0/cron.ts:118:13
    at fire (deno:ext/timers/01_timers.js:477:7)
    at handleTimerMacrotask (deno:ext/timers/01_timers.js:338:7)
Watcher Process finished. Restarting on file change...```

**Comment by kitsonk** [comment]
What version of Deno are you using? (The output of `deno --version`) Can you provide a more complete reproduction?

**Comment by BayoKwendo** [comment]
Am using deno 1.17.1 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2.

This issue usually happens at intervals

**Comment by andreubotella** [comment]
That's odd, because some of those line numbers are past the end of the file in 1.17.1. There was a significant refactor of the timers infrastructure for Deno 1.17, and those line numbers do make sense for 1.16.

Please make sure that you don't have two separate Deno instances with different versions on your system.
