### ISSUE TITLE
TextDecoder().decode() panics while decoding huge data

### ISSUE THREAD

**Issue by fserb** [denoland/deno#13648]
deno 1.17.3 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExpectedString', core/bindings.rs:516:34
stack backtrace:
   0:     0x5608468cb30c - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5608468cb30c - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5608468cb30c - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5608468cb30c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5608468f5ffc - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x5608468c1c05 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x5608468cd6e0 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5608468cd6e0 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5608468cd6e0 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x5608468cd295 - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x560846c4c521 - deno::setup_panic_hook::{{closure}}::hff9d5c6ac54cc9c4
  11:     0x5608468cdf29 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
  12:     0x5608468cd9b0 - std::panicking::begin_panic_handler::{{closure}}::h9371c0fbb1e8465a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
  13:     0x5608468cb7b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b3efa22a5768c0f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x5608468cd919 - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  15:     0x5608468f3ac1 - core::panicking::panic_fmt::h23b9203e89cc61cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  16:     0x5608468f3d73 - core::result::unwrap_failed::h32ef6b3156e8fc57
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
  17:     0x560847563f44 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h1d963f82da8df75f
  18:     0x560845b27dad - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
                               at ./../../../../v8/src/api/api-arguments-inl.h:152:3
  19:     0x560845b272eb - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
                               at ./../../../../v8/src/builtins/builtins-api.cc:112:36
  20:     0x560845b2686e - _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
                               at ./../../../../v8/src/builtins/builtins-api.cc:142:5
  21:     0x5608467ce038 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
```

**Comment by fserb** [comment]
Same on 1.18.2.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExpectedString', core/bindings.rs:516:34
stack backtrace:
   0:     0x56411c59879c - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56411c59879c - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56411c59879c - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56411c59879c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56411c5c3d2c - core::fmt::write::h513b07ca38f4fb1b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:     0x56411c58f145 - std::io::Write::write_fmt::haf8c932b52111354
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:     0x56411c59a750 - std::sys_common::backtrace::_print::h195c38364780a303
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56411c59a750 - std::sys_common::backtrace::print::hc09dfdea923b6730
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56411c59a750 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:     0x56411c59a305 - std::panicking::default_hook::h60284635b0ad54a8
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:     0x56411c8c2737 - deno::setup_panic_hook::{{closure}}::h691f06998f1c655d
  11:     0x56411c59af59 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:610:17
  12:     0x56411c59a9e0 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
  13:     0x56411c598c44 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x56411c59a949 - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  15:     0x56411c5c1551 - core::panicking::panic_fmt::h35f3a62252ba0fd2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  16:     0x56411c5c1803 - core::result::unwrap_failed::hb53671404b9e33c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
  17:     0x56411d545004 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h8784d47d0d6cc695
  18:     0x56411b7e2d0d - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
                               at ./../../../../v8/src/api/api-arguments-inl.h:152:3
  19:     0x56411b7e2230 - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
                               at ./../../../../v8/src/builtins/builtins-api.cc:112:36
  20:     0x56411b7e179e - _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
                               at ./../../../../v8/src/builtins/builtins-api.cc:142:5
  21:     0x56411c499778 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
  ```

**Comment by crowlKats** [comment]
what code are you running to trigger this?

**Comment by fserb** [comment]
This was due to me trying to load a big `.log.gz` file with something like:

```js
import {gunzip} from "https://deno.land/x/compress@v0.4.1/mod.ts";

const dec = gunzip(Deno.readFileSync(f.path));
text = new TextDecoder().decode(dec);
```

Once I split the file in two, it worked fine.

**Comment by kt3k** [comment]
@fserb Sorry we couldn't reproduce this error. Also we couldn't identified which part is actually causing this from the given information.

Can you provide us more specific reproducible example?

> Once I split the file in two, it worked fine.

How large was the original size?

**Comment by ritec03** [comment]
@kt3k I encountered the same (or similar) issue when processing a file that is about 1.13 Gb unzipped. The following is the message:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', serde_v8/magic/u16string.rs:54:10
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <serde_v8::ser::StructSerializers as serde::ser::SerializeStruct>::end
   4: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
   5: __ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
   6: __ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
   7: __ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Here is the script that reproduces the error.
```ts
import { gunzip } from "https://deno.land/x/compress@v0.4.1/mod.ts";

const this_path = "0013_part_00.gz";
const curr_obj = await Deno.readFile(this_path);
const curr_file = gunzip(curr_obj);
const curr_string = new TextDecoder().decode(curr_file);
```

Here is the link to the file: https://s3.amazonaws.com/openalex/data/authors/updated_date=2022-02-08/0013_part_00.gz

Also, I tried prunning the file to various sizes and found that the error starts occurring for this particular file at more than 221104 lines, or about 512 megabytes.

CC @bradenmacdonald

**Comment by GJZwiers** [comment]
Looks like the buffer needed to create the String is larger that the maximum buffer length. As @ritec03 mentioned the max length that works is 512MB. This is also the length in bytes for the (internal) value `v8::String::max_length()`. It is causing a panic! in Rust but without much info on what went wrong. It might be good to make the error message a bit more descriptive.

The limit in Node is also 512MB and given by `buffer.constants.MAX_STRING_LENGTH` ([link](https://nodejs.org/api/buffer.html#buffer_buffer_constants_max_length)). Maybe it would be useful to add something to Deno to retrieve this limit as well?

**Comment by lino-levan** [comment]
#14588 was closed a while ago, I believe this issue should be resolved.
