### ISSUE TITLE
Panic while getting error `WouldBlock` in alpine latest

### ISSUE THREAD

**Issue by firstdorsal** [denoland/deno#13677]
Running on kubernetes/minikube

panic when starting

*Panic! At the Deno* - <3 max

backtrace=1
```sh

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.18.2
Args: ["deno", "run", "--allow-net", "--allow-run", "--allow-write=./work/,./watch/", "--allow-read=./evaluator/Worker.js,./work/,./watch/", "main.ts"]

thread 'main' panicked at 'internal error: entered unreachable code', runtime/errors.rs:61:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: deno_runtime::errors::get_io_error_class
   4: deno_runtime::errors::get_error_class_name
   5: deno::errors::get_error_class_name
   6: deno_core::ops_json::op_sync::{{closure}}
   7: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
   8: deno_core::ops::OpTable::route_op
   9: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
  10: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
             at ./../../../../v8/src/api/api-arguments-inl.h:152:3
  11: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
             at ./../../../../v8/src/builtins/builtins-api.cc:112:36
  12: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
             at ./../../../../v8/src/builtins/builtins-api.cc:142:5
  13: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
backtrace=full
```sh


============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.18.2
Args: ["deno", "run", "--allow-net", "--allow-run", "--allow-write=./work/,./watch/", "--allow-read=./evaluator/Worker.js,./work/,./watch/", "main.ts"]

thread 'main' panicked at 'internal error: entered unreachable code', runtime/errors.rs:61:19
stack backtrace:
   0:     0x556b8d1d179c - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x556b8d1d179c - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556b8d1d179c - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x556b8d1d179c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x556b8d1fcd2c - core::fmt::write::h513b07ca38f4fb1b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:     0x556b8d1c8145 - std::io::Write::write_fmt::haf8c932b52111354
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:     0x556b8d1d3750 - std::sys_common::backtrace::_print::h195c38364780a303
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x556b8d1d3750 - std::sys_common::backtrace::print::hc09dfdea923b6730
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x556b8d1d3750 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:     0x556b8d1d3305 - std::panicking::default_hook::h60284635b0ad54a8
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:     0x556b8d4fb737 - deno::setup_panic_hook::{{closure}}::h691f06998f1c655d
  11:     0x556b8d1d3f59 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:610:17
  12:     0x556b8d1d39b2 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:500:13
  13:     0x556b8d1d1c44 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x556b8d1d3949 - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  15:     0x556b8d1fa551 - core::panicking::panic_fmt::h35f3a62252ba0fd2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  16:     0x556b8d1fa43d - core::panicking::panic::h86fc01e270142a61
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
  17:     0x556b8d915e4e - deno_runtime::errors::get_io_error_class::h9874ed89a1bfaa4f
  18:     0x556b8d915f72 - deno_runtime::errors::get_error_class_name::h8e89d41da4e8b275
  19:     0x556b8d465c10 - deno::errors::get_error_class_name::h9a0e894e582e1a81
  20:     0x556b8d8f2683 - deno_core::ops_json::op_sync::{{closure}}::hea2b8a6f914b15d0
  21:     0x556b8e19c3ec - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h3a6c3185237c3f0d
  22:     0x556b8e1be006 - deno_core::ops::OpTable::route_op::hc01d7669296b0190
  23:     0x556b8e17d23b - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h8784d47d0d6cc695
  24:     0x556b8c41bd0d - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
                               at ./../../../../v8/src/api/api-arguments-inl.h:152:3
  25:     0x556b8c41b230 - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
                               at ./../../../../v8/src/builtins/builtins-api.cc:112:36
  26:     0x556b8c41a79e - _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
                               at ./../../../../v8/src/builtins/builtins-api.cc:142:5
  27:     0x556b8d0d2778 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
```

**Comment by kitsonk** [comment]
Have you run this code previously on earlier versions of Deno?  Can you provide the contents of `main.ts`.

That code hasn't been touched in a long long time where the panic is occurring (well over 14 months and probably longer) and there were no recent changes that I am aware of that would have caused a change in behaviour.

Basically there is an IO operation that is erroring, but in a state that shouldn't exist, therefore the panic is occurring when the error type cannot be determined to be surfaced back to the code.

**Comment by firstdorsal** [comment]
You can check out the project here:
https://github.com/pektin-dns/ribston

The docker Image ist pektin/ribston

**Comment by kitsonk** [comment]
Again, to clarify, this isn't something that previously worked that is now broken, as far as you know, this project on alpine may have never worked?

**Comment by firstdorsal** [comment]
Like said, it worked before on Alpine and still works. But not/never before in the minikube/k8s environment. Everything else is the same.
