### ISSUE TITLE
`DecompressionStream` type error in 1.19 example

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#13716]
I'm trying to run the DecompressionStream example from the 1.19 release notes:

```ts
// mod.ts
const input = await Deno.open("./file.txt.gz");
const output = await Deno.create("./file.txt");
await input.readable
  .pipeTo(new DecompressionStream("gzip"))
  .pipeTo(output.writable);
```

but my editor is showing a typeError at `.pipeTo(new DecompressionStream("gzip"))`:

```
Argument of type 'DecompressionStream' is not assignable to parameter of type 'WritableStream<Uint8Array>'.
  Type 'DecompressionStream' is missing the following properties from type 'WritableStream<Uint8Array>': locked, abort, getWriter deno-ts(2345)
```

Also the next line `.pipeTo(output.writable);` shows the following error:

```
Property 'pipeTo' does not exist on type 'Promise<void>'.deno-ts(2339)
```

Because `pipeTo` takes a WritableStream I thought maybe I could use this instead:

```ts
await input.readable.pipeTo(new DecompressionStream("gzip").writable);
```

This fixes the TypeError in my editor IntelliSense (VS Code) but when running the code I get this error:

```
error: Uncaught (in promise) Error: deflate decompression error
    at Object.opSync (deno:core/01_core.js:168:12)
    at Object.flush (deno:ext/web/14_compression.js:99:31)
    at Object.invokeCallbackFunction (deno:ext/webidl/00_webidl.js:848:18)
    at TransformStreamDefaultController.flushAlgorithm (deno:ext/web/06_streams.js:3108:16)
    at transformStreamDefaultSinkCloseAlgorithm (deno:ext/web/06_streams.js:3405:53)
    at WritableStreamDefaultController.closeAlgorithm (deno:ext/web/06_streams.js:545:14)
    at writableStreamDefaultControllerProcessClose (deno:ext/web/06_streams.js:3711:57)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (deno:ext/web/06_streams.js:3629:7)
    at writableStreamDefaultControllerClose (deno:ext/web/06_streams.js:3645:5)
    at writableStreamClose (deno:ext/web/06_streams.js:3574:5)
```

```
deno --version

deno 1.19.0 (release, x86_64-pc-windows-msvc)
v8 9.9.115.7
typescript 4.5.2
```

**Comment by GJZwiers** [comment]
Using `pipeThrough` also fixes the type error, but I still get the `deflate decompression error`
```ts
const input = await Deno.open("./file.txt.gz");
const output = await Deno.create("./file.txt");
await input.readable
  .pipeThrough(new DecompressionStream("gzip"))
  .pipeTo(output.writable);
```

**Comment by GJZwiers** [comment]
Okay so this error happened because i forgot to actually create a compressed `file.txt.gz`  with gzip. After doing that it works fine. Feel free to close this

**Comment by kt3k** [comment]
@GJZwiers Thanks for your report! We're going to fix the blog post.

**Comment by kt3k** [comment]
Fixed https://deno.com/blog/v1.19
