### ISSUE TITLE
Incorrect line position when exception throw.   Deno 1.16.4 work.

### ISSUE THREAD

**Issue by xnsua** [denoland/deno#13812]
D:\GitRepo\stock-site2\a_my_tools>**deno2.exe**  run --allow-all --no-check --unstable D:\GitRepo\stock-site2\a_my_tools\jqs.js
error: Uncaught ReferenceError: a is not defined
    a.b = 1
    ^
    **at file:///D:/GitRepo/stock-site2/a_my_tools/jqs.js:4:5**

D:\GitRepo\stock-site2\a_my_tools>**deno.exe**  run --allow-all --no-check --unstable D:\GitRepo\stock-site2\a_my_tools\jqs.js
error: Uncaught ReferenceError: a is not defined
Warning Couldn't format source line: Column 22 is out of bounds (source may have changed at runtime)
    **at file:///D:/GitRepo/stock-site2/a_my_tools/jqs.js:7:22**

D:\GitRepo\stock-site2\a_my_tools>deno2.exe --version
**deno 1.16.4 (release, x86_64-pc-windows-msvc)**
v8 9.7.106.15
typescript 4.4.2

D:\GitRepo\stock-site2\a_my_tools>deno.exe --version
**deno 1.19.1 (release, x86_64-pc-windows-msvc)**
v8 9.9.115.7
typescript 4.5.2

**Comment by xnsua** [comment]
jqz.js

`export let testExport = 1`

jqs.js

```
import {testExport} from "./jqz.js";

async function fetchItemInPage(i) {
    a.b = 1
}

fetchItemInPage(1)

```

**Comment by xnsua** [comment]
> @xnsua can you repeat the problem on latest version of Deno (v1.21)?

Not any more for now

**Comment by xnsua** [comment]
> @xnsua can you repeat the problem on latest version of Deno (v1.21)?

**Comment by xnsua** [comment]
> > @xnsua can you repeat the problem on latest version of Deno (v1.21)?

C:\Users\cqhme>deno -V
deno 1.21.1

Yes, it repeats.

I use Webstorm，but problem exists when I run it in cmd window.
In  Deno (v1.21),   
Change file name fixed it. Change it back problem still existed.
