### ISSUE TITLE
integration::worker::workers is flaky

### ISSUE THREAD

**Issue by ry** [denoland/deno#13956]
https://github.com/denoland/deno/runs/5545610971?check_suite_focus=true
```
---- integration::worker::workers stdout ----
deno_exe path D:\a\deno\deno\target\release\deno.exe
test_server starting...
deno_exe args test --reload --location http://127.0.0.1:4545/ -A --unstable workers/test.ts
deno_exe testdata path "D:\\a\\deno\\deno\\cli\\tests\\testdata"
OUTPUT
Check file:///D:/a/deno/deno/cli/tests/testdata/workers/test.ts
running 31 tests from file:///D:/a/deno/deno/cli/tests/testdata/workers/test.ts
test worker terminate ...Check file:///D:/a/deno/deno/cli/tests/testdata/workers/test_worker.ts
 ok (772ms)
test worker from data url ...
OUTPUT
thread 'integration::worker::workers' panicked at 'bad exit code, expected: 0, actual: -1073741819', test_util\src\lib.rs:1771:9
stack backtrace:
   0:     0x7ff753f5861f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff753f5861f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff753f5861f - std::sys_common::backtrace::_print_fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff753f5861f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff753db24aa - core::fmt::write
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\fmt\mod.rs:1168
   5:     0x7ff753f5c8f7 - std::io::Write::write_fmt<alloc::vec::Vec<u8,alloc::alloc::Global> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\io\mod.rs:1660
   6:     0x7ff753f5c34b - std::sys_common::backtrace::_print
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff753f5c34b - std::sys_common::backtrace::print
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff753f5c34b - std::panicking::default_hook::closure$1
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:211
   9:     0x7ff753f5d1d9 - std::panicking::default_hook
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:225
  10:     0x7ff753f5d1d9 - std::panicking::rust_panic_with_hook
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:606
  11:     0x7ff753f5cbc5 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:502
  12:     0x7ff753f5cb39 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:139
  13:     0x7ff753f5caf4 - std::panicking::begin_panic_handler
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:498
  14:     0x7ff7541e1450 - core::panicking::panic_fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\panicking.rs:116
  15:     0x7ff753fae73b - core::fmt::impl$0::write_fmt<std::io::Write::write_fmt::Adapter<enum$<test::console::OutputLocation<std::io::stdio::Stdout> > > >
  16:     0x7ff753c57f53 - main
  17:     0x7ff753f7ed36 - core::ops::function::FnOnce::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\ops\function.rs:227
  18:     0x7ff753f7ed36 - test::__rust_begin_short_backtrace<void (*)()>
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\test\src\lib.rs:574
  19:     0x7ff753f7f00f - alloc::boxed::impl$44::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\alloc\src\boxed.rs:1854
  20:     0x7ff753f7f00f - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\panic\unwind_safe.rs:271
  21:     0x7ff753f7f00f - std::panicking::try::do_call
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panicking.rs:406
  22:     0x7ff753f7f00f - std::panicking::try
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panicking.rs:370
  23:     0x7ff753f7f00f - std::panic::catch_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panic.rs:133
  24:     0x7ff753f7f00f - test::run_test_in_process
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\test\src\lib.rs:597
  25:     0x7ff753f7f00f - test::run_test::run_test_inner::closure$0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\test\src\lib.rs:491
  26:     0x7ff753f80ce4 - test::run_test::run_test_inner::closure$1
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\test\src\lib.rs:518
  27:     0x7ff753f80ce4 - std::sys_common::backtrace::__rust_begin_short_backtrace<test::run_test::run_test_inner::closure$1,tuple$<> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\sys_common\backtrace.rs:123
  28:     0x7ff753f809fa - std::thread::impl$0::spawn_unchecked::closure$1::closure$0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\thread\mod.rs:477
  29:     0x7ff753f809fa - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\panic\unwind_safe.rs:271
  30:     0x7ff753f809fa - std::panicking::try::do_call
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panicking.rs:406
  31:     0x7ff753f809fa - std::panicking::try
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panicking.rs:370
  32:     0x7ff753f809fa - std::panic::catch_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panic.rs:133
  33:     0x7ff753f809fa - std::thread::impl$0::spawn_unchecked::closure$1
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\thread\mod.rs:476
  34:     0x7ff753f809fa - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked::closure$1,tuple$<> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\ops\function.rs:227
  35:     0x7ff753f5f45b - alloc::boxed::impl$44::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\alloc\src\boxed.rs:1854
  36:     0x7ff753f5f45b - alloc::boxed::impl$44::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\alloc\src\boxed.rs:1854
  37:     0x7ff753f5f45b - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys\windows\thread.rs:58
  38:     0x7ffbf0087974 - BaseThreadInitThunk
  39:     0x7ffbf0c5a2f1 - RtlUserThreadStart


failures:
    integration::worker::workers

test result: FAILED. 716 passed; 1 failed; 9 ignored; 0 measured; 0 filtered out; finished in 600.56s
```

**Comment by littledivy** [comment]
Fixed in https://github.com/denoland/deno/pull/13970
