### ISSUE TITLE
flaky WPT: /fetch/api/basic/response-null-body.any.html - Response.body is null for responses with status=204 (method=POST)

### ISSUE THREAD

**Issue by ry** [denoland/deno#13957]
https://github.com/denoland/deno/runs/5543231621?check_suite_focus=true

```

/fetch/api/basic/response-null-body.any.html

test Response.body is null for responses with status=204 (method=POST) ... failed

failures:

Response.body is null for responses with status=204 (method=POST)
promise_test: Unhandled rejection with value: object "TypeError: error sending request for url (http://web-platform.test:8000/fetch/api/resources/status.py?code=204&content=hello-world): invalid HTTP version parsed"
Error
    at get_stack (http://web-platform.test:8000/resources/testharness.js:4418:21)
    at new AssertionError (http://web-platform.test:8000/resources/testharness.js:4411:22)
    at assert (http://web-platform.test:8000/resources/testharness.js:4395:19)
    at Test.<anonymous> (http://web-platform.test:8000/resources/testharness.js:703:29)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:2534:25)
    at http://web-platform.test:8000/resources/testharness.js:2581:35

failures:

        "Response.body is null for responses with status=204 (method=POST)"

file result: failed. 9 passed; 1 failed; 0 expected failure; total 10
```

**Comment by littledivy** [comment]
@lucacasonato added this test in WPT - https://github.com/web-platform-tests/wpt/pull/32813. Chromium has reported it flaky too https://bugs.chromium.org/p/chromium/issues/detail?id=1298836

**Comment by dsherret** [comment]
Also:

failures:

        "/fetch/api/basic/response-null-body.any.worker.html - Response.body is null for responses with method=HEAD"

final result: failed. 1455 passed; 1 failed; 20 expected failure; total 1456

https://github.com/denoland/deno/runs/5761253795?check_suite_focus=true

**Comment by andreubotella** [comment]
I noticed that the test makes a `POST` call without a body. If I'm reading the spec right, this would mean not sending a body at all – no `Content-Length`, `Content-Type` or `Transfer-Encoding` headers, and no body. This seems to be allowed by the HTTP specs, but I'm assuming the `wptserve` server doesn't support those very well. Unfortunately, I've been trying to reproduce and I can't seem to, so I don't know if that's what's going on.

The HEAD case is not explained by this hypothesis, though.
