### ISSUE TITLE
flaky test: integration::run::worker_close_race

### ISSUE THREAD

**Issue by ry** [denoland/deno#13959]
https://github.com/denoland/deno/runs/5544764352?check_suite_focus=true

```
---- integration::run::worker_close_race stdout ----
deno_exe path D:\a\deno\deno\target\release\deno.exe
deno_exe args run --quiet --reload --allow-read worker_close_race.js
deno_exe testdata path "D:\\a\\deno\\deno\\cli\\tests\\testdata"
OUTPUT

OUTPUT
thread 'integration::run::worker_close_race' panicked at 'bad exit code, expected: 0, actual: -1073741819', test_util\src\lib.rs:1771:9
stack backtrace:
   0:     0x7ff644bc861f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff644bc861f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff644bc861f - std::sys_common::backtrace::_print_fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff644bc861f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff644a224aa - core::fmt::write
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\fmt\mod.rs:1168
   5:     0x7ff644bcc8f7 - std::io::Write::write_fmt<alloc::vec::Vec<u8,alloc::alloc::Global> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\io\mod.rs:1660
   6:     0x7ff644bcc34b - std::sys_common::backtrace::_print
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff644bcc34b - std::sys_common::backtrace::print
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff644bcc34b - std::panicking::default_hook::closure$1
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:211
   9:     0x7ff644bcd1d9 - std::panicking::default_hook
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:225
  10:     0x7ff644bcd1d9 - std::panicking::rust_panic_with_hook
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:606
  11:     0x7ff644bccbc5 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:502
  12:     0x7ff644bccb39 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:139
  13:     0x7ff644bccaf4 - std::panicking::begin_panic_handler
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:498
  14:     0x7ff644e51450 - core::panicking::panic_fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\panicking.rs:116
  15:     0x7ff644c1e73b - core::fmt::impl$0::write_fmt<std::io::Write::write_fmt::Adapter<enum$<test::console::OutputLocation<std::io::stdio::Stdout> > > >
  16:     0x7ff6448e8fb6 - main
  17:     0x7ff644beed36 - core::ops::function::FnOnce::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\ops\function.rs:227
  18:     0x7ff644beed36 - test::__rust_begin_short_backtrace<void (*)()>
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\test\src\lib.rs:574
  19:     0x7ff644bef00f - alloc::boxed::impl$44::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\alloc\src\boxed.rs:1854
  20:     0x7ff644bef00f - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\panic\unwind_safe.rs:271
  21:     0x7ff644bef00f - std::panicking::try::do_call
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panicking.rs:406
  22:     0x7ff644bef00f - std::panicking::try
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panicking.rs:370
  23:     0x7ff644bef00f - std::panic::catch_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panic.rs:133
  24:     0x7ff644bef00f - test::run_test_in_process
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\test\src\lib.rs:597
  25:     0x7ff644bef00f - test::run_test::run_test_inner::closure$0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\test\src\lib.rs:491
  26:     0x7ff644bf0ce4 - test::run_test::run_test_inner::closure$1
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\test\src\lib.rs:518
  27:     0x7ff644bf0ce4 - std::sys_common::backtrace::__rust_begin_short_backtrace<test::run_test::run_test_inner::closure$1,tuple$<> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\sys_common\backtrace.rs:123
  28:     0x7ff644bf09fa - std::thread::impl$0::spawn_unchecked::closure$1::closure$0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\thread\mod.rs:477
  29:     0x7ff644bf09fa - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\panic\unwind_safe.rs:271
  30:     0x7ff644bf09fa - std::panicking::try::do_call
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panicking.rs:406
  31:     0x7ff644bf09fa - std::panicking::try
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panicking.rs:370
  32:     0x7ff644bf09fa - std::panic::catch_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\panic.rs:133
  33:     0x7ff644bf09fa - std::thread::impl$0::spawn_unchecked::closure$1
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\thread\mod.rs:476
  34:     0x7ff644bf09fa - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked::closure$1,tuple$<> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\ops\function.rs:227
  35:     0x7ff644bcf45b - alloc::boxed::impl$44::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\alloc\src\boxed.rs:1854
  36:     0x7ff644bcf45b - alloc::boxed::impl$44::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\alloc\src\boxed.rs:1854
  37:     0x7ff644bcf45b - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys\windows\thread.rs:58
  38:     0x7ff9300[2797](https://github.com/denoland/deno/runs/5544764352?check_suite_focus=true#step:35:2797)4 - BaseThreadInitThunk
  39:     0x7ff93090a2f1 - RtlUserThreadStart


failures:
    integration::run::worker_close_race
```

**Comment by littledivy** [comment]
Fixed in https://github.com/denoland/deno/pull/13970
