### ISSUE TITLE
op panic when attempting to use an unsafe pointer

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#14128]
meta:
```
deno 1.20.3 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```
code
```ts
const mem = Deno.makeTempFileSync();

const ankor = new TextEncoder().encode(
  "",
);
const ankorAddr = Deno.UnsafePointer.of(ankor);

Deno.seekSync(mem.rid, ankorAddr, Deno.SeekMode.Start); // to fix the panic replace ankorAddr with Number(ankorAddr)
```
panic:
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.20.3
Args: ["deno", "run", "-A", "--unstable", "b.js"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/work/deno/deno/serde_v8/de.rs:154:3
stack backtrace:
   0:     0x5606f5d4126c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5606f5d4126c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5606f5d4126c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5606f5d4126c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5606f5d6f4cc - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x5606f5d36a43 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x5606f5d44082 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5606f5d44082 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5606f5d44082 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x5606f5d43c65 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x5606f5fd825e - deno::setup_panic_hook::{{closure}}::h27904fd79cbabeea
  11:     0x5606f5d447f5 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
  12:     0x5606f5d444c2 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:500:13
  13:     0x5606f5d41714 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x5606f5d44229 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  15:     0x5606f5d6ccf1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  16:     0x5606f5d6cbbd - core::panicking::panic::h97167cd315d19cd4
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
  17:     0x5606f6332254 - serde_v8::de::from_v8::h1b0b06ab6b687dc3
  18:     0x5606f6476e19 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h0f8e1a710646184d
  19:     0x5606f4f88156 - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
                               at ./../../../../v8/src/api/api-arguments-inl.h:152:3
  20:     0x5606f4f87b8a - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
                               at ./../../../../v8/src/builtins/builtins-api.cc:112:36
  21:     0x5606f4f870cb - _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
                               at ./../../../../v8/src/builtins/builtins-api.cc:130:1
  22:     0x5606f5c42e78 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit

```

**Comment by andreubotella** [comment]
The panic is a bug indeed, but if you were trying to achieve something by passing a pointer to `Deno.seekSync()`, it probably won't do what you expect. As you noticed, that second parameter takes a number of bytes into the file to advance. Passing it a pointer into an `ArrayBuffer` (or the address of such a pointer, as with `Number(anchorAddr)`) will not seek by the length of the buffer, or do anything else that's reasonable.

The reason behind this panic is that `Deno.UnsafePointer` has a `valueOf` method, which returns a bigint. In `serde_v8`, the `deserialize_*` methods (implemented using the `deserialize_signed` and `deserialize_unsigned` macros) will first try to detect if the value to deserialize is a bigint (i.e. `typeof value === "bigint"`), and if it isn't, it takes its (non-bigint) number value, converted to an integer. But in this case, `typeof value === "object"`, but it doesn't have a non-bigint number value, because its primitive value is a bigint.

Looking at the documentation for `v8::Value::integer_value`, I also noticed that objects whose `valueOf` method returns `Number.POSITIVE_INFINITY` also trigger the same panic.

cc @AaronO
