### ISSUE TITLE
error: RangeError: Maximum call stack size exceeded as of deno 1.20.1

### ISSUE THREAD

**Issue by jeiea** [denoland/deno#14132]
### Steps to reproduce
1. Save the following as `mod.ts`.
```typescript
export { cac } from "https://cdn.esm.sh/v66/cac@6.7.12/mod.ts";
```
2. Run `deno cache mod.ts`.

### Expected behavior
```
➜ Downloads  .\deno --version
deno 1.19.3 (release, x86_64-pc-windows-msvc)
v8 9.9.115.8
typescript 4.5.2
➜ Downloads  .\deno cache deps.ts
Check file:///D:/Downloads/deps.ts
```

### Actual behavior
```
➜ Downloads  .\deno --version
deno 1.20.1 (release, x86_64-pc-windows-msvc)
v8 10.0.139.6
typescript 4.6.2
➜ Downloads  .\deno cache deps.ts
Check file:///D:/Downloads/deps.ts

thread 'main' has overflowed its stack
```

```
➜ Downloads  deno --version
deno 1.20.3 (release, x86_64-pc-windows-msvc)
v8 10.0.139.6
typescript 4.6.2
➜ Downloads  deno cache deps.ts
Check file:///D:/Downloads/deps.ts
error: RangeError: Maximum call stack size exceeded
    at recursiveTypeRelatedTo (deno:cli/tsc/00_typescript.js:1:1)
    at isRelatedTo (deno:cli/tsc/00_typescript.js:1:1)
    at checkTypeRelatedTo (deno:cli/tsc/00_typescript.js:1:1)
    at isTypeRelatedTo (deno:cli/tsc/00_typescript.js:1:1)
    at isTypeAssignableTo (deno:cli/tsc/00_typescript.js:1:1)
    at isTypeAssignableToKind (deno:cli/tsc/00_typescript.js:1:1)
    at allTypesAssignableToKind (deno:cli/tsc/00_typescript.js:1:1)
    at checkInstanceOfExpression (deno:cli/tsc/00_typescript.js:1:1)
    at checkBinaryLikeExpressionWorker (deno:cli/tsc/00_typescript.js:1:1)
    at BinaryExpressionStateMachine.onExit (deno:cli/tsc/00_typescript.js:1:1)
```

### Additional context

Caching `https://cdn.esm.sh/v66/cac@6.7.12/mod.ts` directly doesn't make an error.

**Comment by kitsonk** [comment]
It seems that that specific module has some recursive values on importing types that break things in TypeScript 4.6 (which first shipped with Deno 1.20).

Both the following imports should be functionally the same and resolve the issue:

```
import { cac } from "https://cdn.esm.sh/cac@6.7.12/mod.ts";

import { cac } from "https://cdn.esm.sh/v74/cac@6.7.12/";
```

If either of these isn't "acceptable" fixes, I think you will need to report it to [cac](https://github.com/cacjs/cac/) as an issue.  While the issue _may_ not manifest itself under standalone `tsc` because of Deno resolution behaving a bit differently, at its root it is a recursive type in cac that is causing the issue.
