### ISSUE TITLE
`op_close` missing from test sanitizer messages

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#14144]
I ran into an error while running a test:
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:201:26)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:370:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:9)
    at async runTest (deno:runtime/js/40_testing.js:788:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:986:22)
```

I haven't been able to create a reduced test case yet but when debugging it seems it tries to get the message for `op_close`, which doesn't exist:
https://github.com/denoland/deno/blob/89dd5dac6219f9a4c04ada4b5a9c812a88c1c2d4/runtime/js/40_testing.js#L61-L64

**Comment by bartlomieju** [comment]
@jespertheend what is your Deno version?
