### ISSUE TITLE
Logging a proxied date throws an error

### ISSUE THREAD

**Issue by fabiancook** [denoland/deno#14164]
```typescript
console.log(new Date().getTime())

const handler = {
    get(target: Date, p: keyof Date) {
        const value = target[p];
        if (typeof value === "function") {
            return value.bind(target);
        }
        return value;
    },

}

console.log(new Proxy(new Date(), handler).getTime())
console.log(new Proxy(new Date(), handler))
```

The above code will error on the last line. 

With deno this logs:

```shell
1648719239211
1648719239211
error: Uncaught TypeError: this is not a Date object.
console.log(new Proxy(new Date(), handler))
        ^
    at Proxy.getTime (<anonymous>)
    at isInvalidDate (deno:ext/console/02_console.js:104:18)
    at inspectDate (deno:ext/console/02_console.js:877:7)
    at inspectObject (deno:ext/console/02_console.js:1182:14)
    at _inspectValue (deno:ext/console/02_console.js:630:16)
    at inspectValue (deno:ext/console/02_console.js:645:11)
    at inspectArgs (deno:ext/console/02_console.js:1739:19)
    at console.log (deno:ext/console/02_console.js:1793:9)
    at file:///Users/fabiancook/src/virtualstate/fringe/test-deno.ts:14:9
```

With node this logs:

```shell
1648719429883
1648719429885
2022-03-31T09:37:09.886Z
```

It makes sense as to why this is happening, since the log uses `DatePrototypeGetTime` instead of the defined `getTime` function which the handler does a bind with.

https://github.com/denoland/deno/blob/f7ab41583e2bb4425ce7ac89b123089d0f07836a/ext/console/02_console.js#L115

If I drop the prototype using the proxy (meaning the `if (ObjectPrototypeIsPrototypeOf(DatePrototype, value))` check doesn't pass)

```typescript
const handler = {
    get(target: Date, p: keyof Date) {
        const value = target[p];
        if (typeof value === "function") {
            return value.bind(target);
        }
        return value;
    },
    getPrototypeOf() {
        return {}
    }
}
```

I get with deno 

```shell
1648719623874
1648719623875
bound Date {}
```

But with node still 

```shell
1648719686871
1648719686874
2022-03-31T09:41:26.874Z
```

**Comment by fabiancook** [comment]
I believe this should be addressed, it is a normal thing to use dates in JavaScript, and a normal thing to use proxies, and a normal thing to log them, so deno should throw exceptions when all mixed together. 

If not addressed I can maybe try put together a PR for it myself. 

This had caused issues for my cross runtime projects, I had to exclude usage of this pattern in examples to have compatibility with deno
