### ISSUE TITLE
Rust thread panicked

### ISSUE THREAD

**Issue by berryempire** [denoland/deno#14194]
New version of oak (v10.5.1) is crashing deno (v1.20.3) unlike the old version (v7.7.0)

Command:
```
sudo RUST_BACKTRACE=1 /home/user/.deno/bin/deno run --allow-net --allow-read --allow-write --allow-run --unstable app.js 
```

Output:
```
thread 'main' panicked at 'called expect on Ident(Ident { span: Span { lo: BytePos(1558), hi: BytePos(1562), ctxt: #0 }, sym: Atom('type' type=static), optional: false })', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_ast-0.55.0/src/prop.rs:93:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
   2: swc_ecma_dep_graph::parse_import_assertions
   3: swc_ecma_visit::visit_module_decl
   4: swc_ecma_visit::visit_module_items
   5: swc_ecma_dep_graph::analyze_dependencies
   6: deno_graph::ast::analyze_dependencies
   7: deno_graph::graph::parse_module_from_ast
   8: deno_graph::graph::Builder::visit
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: deno::run_command::{{closure}}
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Full backtrace:
```
thread 'main' panicked at 'called expect on Ident(Ident { span: Span { lo: BytePos(1558), hi: BytePos(1562), ctxt: #0 }, sym: Atom('type' type=static), optional: false })', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_ast-0.55.0/src/prop.rs:93:20
stack backtrace:
   0:     0x5641d9a864d0 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5641d9a864d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5641d9a864d0 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5641d9a864d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5641d9ab133c - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x5641d9a7da95 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x5641d9a88f0b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5641d9a88f0b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5641d9a88f0b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x5641d9a889e1 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x5641d9df4c52 - deno::setup_exit_process_panic_hook::{{closure}}::h42a5141e5d7d5324
  11:     0x5641d9a89769 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
  12:     0x5641d9a891f7 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  13:     0x5641d9a869cc - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x5641d9a89159 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  15:     0x5641d9a8910b - std::panicking::begin_panic_fmt::h7ab3d84aa4ae32a2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
  16:     0x5641da91048a - swc_ecma_dep_graph::parse_import_assertions::h48fe0fecac83a06f
  17:     0x5641da902108 - swc_ecma_visit::visit_module_decl::h6cf1ece9f89c629c
  18:     0x5641da9022f8 - swc_ecma_visit::visit_module_items::h5a06881924cb6e97
  19:     0x5641da90ff7f - swc_ecma_dep_graph::analyze_dependencies::h634c5374a273e3ac
  20:     0x5641da6eb4b5 - deno_graph::ast::analyze_dependencies::h9974db33d45f3893
  21:     0x5641da6ef1a1 - deno_graph::graph::parse_module_from_ast::h3ca4cf7f2d232074
  22:     0x5641da6f0827 - deno_graph::graph::Builder::visit::hdcedf1ae5a321e78
  23:     0x5641d9cdfd49 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9e3fa15d0c4ccf2a
  24:     0x5641d9cf73ba - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc763549789923a84
  25:     0x5641d9ca35cc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h06d1bd1a1c15e900
  26:     0x5641d9d07d2a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfdc18c82df175e2d
  27:     0x5641d9cbeca8 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h473a9412d3610209
  28:     0x5641d9ca36da - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0beb53c8b8cc693a
  29:     0x5641d9deefce - deno::run_command::{{closure}}::h19d5ed7f3d0bd557
  30:     0x5641d9d07230 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf19d7919aaab4b77
  31:     0x5641d9ca5777 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0ec679c324bc5ae7
  32:     0x5641d9df68b1 - deno::main::h7974ca8e5faeae9d
  33:     0x5641d9b4bc57 - std::sys_common::backtrace::__rust_begin_short_backtrace::h248c169c771cc7a7
  34:     0x5641d9b522a6 - std::rt::lang_start::{{closure}}::h7681897906f70329
  35:     0x5641d9a89d4a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha9408abe89f69dc4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
  36:     0x5641d9a89d4a - std::panicking::try::do_call::h5b0cc9e9102acb65
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  37:     0x5641d9a89d4a - std::panicking::try::hddc7f8229138b3ba
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  38:     0x5641d9a89d4a - std::panic::catch_unwind::hfa401ff8bab2986e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  39:     0x5641d9a89d4a - std::rt::lang_start_internal::{{closure}}::h8163422320d11405
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
  40:     0x5641d9a89d4a - std::panicking::try::do_call::hc742cc7bb4f0fb20
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  41:     0x5641d9a89d4a - std::panicking::try::ha37d8d2dd1acf7d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  42:     0x5641d9a89d4a - std::panic::catch_unwind::h8a5381d5ecf437bc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  43:     0x5641d9a89d4a - std::rt::lang_start_internal::h7e2cee8c90d4a4d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  44:     0x5641d9e0d724 - main
  45:     0x7f204ab9b0b3 - __libc_start_main
  46:     0x5641d8c8902a - _start
  47:                0x0 - <unknown>
```

**Comment by kitsonk** [comment]
Can you provide the output of `deno --version`?

You aren't using Deno 1.20.3 in the above output, as recent versions of Deno have different panic output and the lib that is panicking is current v0.71 not v0.55 as indicated.

**Comment by tomveich** [comment]
```
deno 1.20.4 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```
```
thread 'main' panicked at 'called expect on Ident(Ident { span: Span { lo: BytePos(1558), hi: BytePos(1562), ctxt: #0 }, sym: Atom('type' type=static), optional: false })', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_ast-0.55.0/src/prop.rs:93:20
stack backtrace:
   0:     0x55834fb134d0 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55834fb134d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55834fb134d0 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55834fb134d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55834fb3e33c - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x55834fb0aa95 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x55834fb15f0b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55834fb15f0b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55834fb15f0b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x55834fb159e1 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x55834fe81c52 - deno::setup_exit_process_panic_hook::{{closure}}::h42a5141e5d7d5324
  11:     0x55834fb16769 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
  12:     0x55834fb161f7 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  13:     0x55834fb139cc - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x55834fb16159 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  15:     0x55834fb1610b - std::panicking::begin_panic_fmt::h7ab3d84aa4ae32a2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
  16:     0x55835099d48a - swc_ecma_dep_graph::parse_import_assertions::h48fe0fecac83a06f
  17:     0x55835098f108 - swc_ecma_visit::visit_module_decl::h6cf1ece9f89c629c
  18:     0x55835098f2f8 - swc_ecma_visit::visit_module_items::h5a06881924cb6e97
  19:     0x55835099cf7f - swc_ecma_dep_graph::analyze_dependencies::h634c5374a273e3ac
  20:     0x5583507784b5 - deno_graph::ast::analyze_dependencies::h9974db33d45f3893
  21:     0x55835077c1a1 - deno_graph::graph::parse_module_from_ast::h3ca4cf7f2d232074
  22:     0x55835077d827 - deno_graph::graph::Builder::visit::hdcedf1ae5a321e78
  23:     0x55834fd6cd49 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9e3fa15d0c4ccf2a
  24:     0x55834fd843ba - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc763549789923a84
  25:     0x55834fd305cc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h06d1bd1a1c15e900
  26:     0x55834fd94d2a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfdc18c82df175e2d
  27:     0x55834fd4bca8 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h473a9412d3610209
  28:     0x55834fd306da - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0beb53c8b8cc693a
  29:     0x55834fe7bfce - deno::run_command::{{closure}}::h19d5ed7f3d0bd557
  30:     0x55834fd94230 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf19d7919aaab4b77
  31:     0x55834fd32777 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0ec679c324bc5ae7
  32:     0x55834fe838b1 - deno::main::h7974ca8e5faeae9d
  33:     0x55834fbd8c57 - std::sys_common::backtrace::__rust_begin_short_backtrace::h248c169c771cc7a7
  34:     0x55834fbdf2a6 - std::rt::lang_start::{{closure}}::h7681897906f70329
  35:     0x55834fb16d4a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha9408abe89f69dc4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
  36:     0x55834fb16d4a - std::panicking::try::do_call::h5b0cc9e9102acb65
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  37:     0x55834fb16d4a - std::panicking::try::hddc7f8229138b3ba
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  38:     0x55834fb16d4a - std::panic::catch_unwind::hfa401ff8bab2986e
                               at /rustc/c8dfcfe
                               046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  39:     0x55834fb16d4a - std::rt::lang_start_internal::{{closure}}::h8163422320d11405
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
  40:     0x55834fb16d4a - std::panicking::try::do_call::hc742cc7bb4f0fb20
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  41:     0x55834fb16d4a - std::panicking::try::ha37d8d2dd1acf7d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  42:     0x55834fb16d4a - std::panic::catch_unwind::h8a5381d5ecf437bc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  43:     0x55834fb16d4a - std::rt::lang_start_internal::h7e2cee8c90d4a4d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  44:     0x55834fe9a724 - main
  45:     0x7f52e14380b3 - __libc_start_main
  46:     0x55834ed1602a - _start
  47:                0x0 - <unknown>
```

**Comment by berryempire** [comment]
```
deno 1.20.4 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```
```
thread 'main' panicked at 'called expect on Ident(Ident { span: Span { lo: BytePos(1558), hi: BytePos(1562), ctxt: #0 }, sym: Atom('type' type=static), optional: false })', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_ast-0.55.0/src/prop.rs:93:20
stack backtrace:
   0:     0x55834fb134d0 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55834fb134d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55834fb134d0 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55834fb134d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55834fb3e33c - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x55834fb0aa95 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x55834fb15f0b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55834fb15f0b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55834fb15f0b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x55834fb159e1 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x55834fe81c52 - deno::setup_exit_process_panic_hook::{{closure}}::h42a5141e5d7d5324
  11:     0x55834fb16769 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
  12:     0x55834fb161f7 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  13:     0x55834fb139cc - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x55834fb16159 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  15:     0x55834fb1610b - std::panicking::begin_panic_fmt::h7ab3d84aa4ae32a2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
  16:     0x55835099d48a - swc_ecma_dep_graph::parse_import_assertions::h48fe0fecac83a06f
  17:     0x55835098f108 - swc_ecma_visit::visit_module_decl::h6cf1ece9f89c629c
  18:     0x55835098f2f8 - swc_ecma_visit::visit_module_items::h5a06881924cb6e97
  19:     0x55835099cf7f - swc_ecma_dep_graph::analyze_dependencies::h634c5374a273e3ac
  20:     0x5583507784b5 - deno_graph::ast::analyze_dependencies::h9974db33d45f3893
  21:     0x55835077c1a1 - deno_graph::graph::parse_module_from_ast::h3ca4cf7f2d232074
  22:     0x55835077d827 - deno_graph::graph::Builder::visit::hdcedf1ae5a321e78
  23:     0x55834fd6cd49 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9e3fa15d0c4ccf2a
  24:     0x55834fd843ba - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc763549789923a84
  25:     0x55834fd305cc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h06d1bd1a1c15e900
  26:     0x55834fd94d2a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfdc18c82df175e2d
  27:     0x55834fd4bca8 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h473a9412d3610209
  28:     0x55834fd306da - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0beb53c8b8cc693a
  29:     0x55834fe7bfce - deno::run_command::{{closure}}::h19d5ed7f3d0bd557
  30:     0x55834fd94230 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf19d7919aaab4b77
  31:     0x55834fd32777 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0ec679c324bc5ae7
  32:     0x55834fe838b1 - deno::main::h7974ca8e5faeae9d
  33:     0x55834fbd8c57 - std::sys_common::backtrace::__rust_begin_short_backtrace::h248c169c771cc7a7
  34:     0x55834fbdf2a6 - std::rt::lang_start::{{closure}}::h7681897906f70329
  35:     0x55834fb16d4a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha9408abe89f69dc4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
  36:     0x55834fb16d4a - std::panicking::try::do_call::h5b0cc9e9102acb65
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  37:     0x55834fb16d4a - std::panicking::try::hddc7f8229138b3ba
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  38:     0x55834fb16d4a - std::panic::catch_unwind::hfa401ff8bab2986e
                               at /rustc/c8dfcfe
                               046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  39:     0x55834fb16d4a - std::rt::lang_start_internal::{{closure}}::h8163422320d11405
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
  40:     0x55834fb16d4a - std::panicking::try::do_call::hc742cc7bb4f0fb20
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  41:     0x55834fb16d4a - std::panicking::try::ha37d8d2dd1acf7d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  42:     0x55834fb16d4a - std::panic::catch_unwind::h8a5381d5ecf437bc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  43:     0x55834fb16d4a - std::rt::lang_start_internal::h7e2cee8c90d4a4d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  44:     0x55834fe9a724 - main
  45:     0x7f52e14380b3 - __libc_start_main
  46:     0x55834ed1602a - _start
  47:                0x0 - <unknown>
```

**Comment by kitsonk** [comment]
There is still a disconnect.  The version information you are providing does not match the panic stack trace, and the version of the library that is panicing does not match the version of the library that is included in Deno 1.20.4.  Panics in recent versions of Deno also provide information like what was provided on the command line as arguments.

The panic is coming from the the use of `import { type Interface } from "module"` syntax which recent versions of oak use.  Older version of Deno did not properly handle that syntax and would panic, which strongly indicates you might think you are running the workload under 1.20.4 but in fact are not.

**Comment by berryempire** [comment]
This issue has not been fixed yet, please consider reopening it.
Or should I repost the issue to the Oak GitHub? Not sure whether the problem lays in the Deno core or Oak.

**Comment by kitsonk** [comment]
You need to provide a reproduction with a current version of Deno.

The 1.20.4 did not generate stack traces in the way you mention and did not use the version of swc that was in the stack trace.  Specifically the version of swc was from a version that did not properly handle imports of JSON modules, which modern versions of oak use.
