### ISSUE TITLE
Panic: Unexpected missing emit: https://deno.land/x/sift@0.4.4/mod.ts', cli/proc_state.rs:521:25

### ISSUE THREAD

**Issue by emdienn** [denoland/deno#14218]
Hi all. Got a panic, reporting it as requested by the CLI

I'm aware sift is up to v0.5.0 now, but I rolled back to resolve some other issue and got hit in the face with this. I did also clear my mod cache and re-test, still panics.

---

### Code to reproduce
```ts
import { serve, json } from 'https://deno.land/x/sift@0.4.4/mod.ts'
serve({
  '/foo': () => json({ foo: 'bar' })
})
```

---

Platform: `linux x86_64`
Version: `1.19.3`
Args: `["deno", "run", "--allow-env", "--allow-net", "--allow-read", "index.ts"]`

```
============================================================

thread 'main' panicked at 'internal error: entered unreachable code: Unexpected missing emit: https://deno.land/x/sift@0.4.4/mod.ts', cli/proc_state.rs:521:25
stack backtrace:
   0:     0x56400186bd7c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56400186bd7c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56400186bd7c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56400186bd7c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x564001899f7c - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x5640018615c3 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x56400186eb92 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56400186eb92 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56400186eb92 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x56400186e775 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x564001b0c4d1 - deno::setup_panic_hook::{{closure}}::hbe02deeb04e70eab
  11:     0x56400186f305 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
  12:     0x56400186f000 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  13:     0x56400186c224 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x56400186ed39 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  15:     0x5640018977a1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  16:     0x564001ab9f8a - deno::proc_state::ProcState::load::h1386f9cb1644670c
  17:     0x564001b77f4d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8be2f9f0ed127cfd
  18:     0x56400289b693 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd10327cf10291376
  19:     0x56400286c05b - <deno_core::modules::RecursiveModuleLoad as futures_core::stream::Stream>::poll_next::hb8c0d981a52b4322
  20:     0x564001a66270 - <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll::h26f9cdfd99b3be4c
  21:     0x564001b57c76 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2991968cb3c78cb8
  22:     0x564001b95149 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbc19329c853cad9a
  23:     0x564001b85732 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha6e671015ccfc2ff
  24:     0x564001b0681a - deno::run_command::{{closure}}::hdd58e5758f21d526
  25:     0x564001b0ed73 - deno::main::{{closure}}::hc9a2aafdcfc66e2a
  26:     0x564001ba1c5f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdb86e6b49ddaf6fd
  27:     0x564001a1d156 - deno_runtime::tokio_util::run_basic::h93b5cc6d1886d10d
  28:     0x564001b0c6c9 - deno::main::ha5142a6ece767a4b
  29:     0x564001b328ce - std::sys_common::backtrace::__rust_begin_short_backtrace::hc3a648ccf4dbf121
  30:     0x564001b310e8 - std::rt::lang_start::{{closure}}::h8f1eef768f1c89db
  31:     0x56400186b430 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  32:     0x56400186b430 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  33:     0x56400186b430 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  34:     0x56400186b430 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  35:     0x56400186b430 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  36:     0x56400186b430 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  37:     0x56400186b430 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  38:     0x56400186b430 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  39:     0x56400186b430 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  40:     0x564001bce70b - main
  41:     0x7f3409db20b3 - __libc_start_main
  42:     0x5640009d7029 - _start
  43:                0x0 - <unknown>
```

**Comment by emdienn** [comment]
Realised I was behind a Deno version, updated to `1.20.4` and tried again: same effect.

New stacktrace:
```
thread 'main' panicked at 'internal error: entered unreachable code: Unexpected missing emit: https://deno.land/x/sift@0.4.4/mod.ts', cli/proc_state.rs:590:25
stack backtrace:
   0:     0x560b5ed0626c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x560b5ed0626c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560b5ed0626c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560b5ed0626c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x560b5ed344cc - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x560b5ecfba43 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x560b5ed09082 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x560b5ed09082 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x560b5ed09082 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x560b5ed08c65 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x560b5efa2ac9 - deno::setup_panic_hook::{{closure}}::haa3a1c77db7da252
  11:     0x560b5ed097f5 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
  12:     0x560b5ed094f0 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  13:     0x560b5ed06714 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x560b5ed09229 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  15:     0x560b5ed31cf1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  16:     0x560b5ef47c0e - deno::proc_state::ProcState::load::h84fe1250b5606168
  17:     0x560b5eff0e02 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1778afb8e7ce0ba9
  18:     0x560b5fe743b3 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8a3bc6093a487843
  19:     0x560b5fe42c5b - <deno_core::modules::RecursiveModuleLoad as futures_core::stream::Stream>::poll_next::he35e94f76e5448b2
  20:     0x560b5eeed785 - <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll::h11b9a2650581973d
  21:     0x560b5f0147d2 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5b8f40073c2eaf02
  22:     0x560b5f003639 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h46523b0e3f3e7084
  23:     0x560b5eff3508 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h19f7a0fba22f37be
  24:     0x560b5ef9d0a4 - deno::run_command::{{closure}}::h3fb7d960947e14d3
  25:     0x560b5efa54ae - deno::main::{{closure}}::h34982cb712ede293
  26:     0x560b5f01f72f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h72b0b3b87e0559c3
  27:     0x560b5ee947da - deno_runtime::tokio_util::run_basic::h78eded18671f3384
  28:     0x560b5efa2cc1 - deno::main::h1dfd4901a6a618c7
  29:     0x560b5efd04f2 - std::sys_common::backtrace::__rust_begin_short_backtrace::h98b30d9a78bf64b4
  30:     0x560b5efcdfce - std::rt::lang_start::{{closure}}::h970d799b9118cb6b
  31:     0x560b5ed05920 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  32:     0x560b5ed05920 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  33:     0x560b5ed05920 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  34:     0x560b5ed05920 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  35:     0x560b5ed05920 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  36:     0x560b5ed05920 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  37:     0x560b5ed05920 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  38:     0x560b5ed05920 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  39:     0x560b5ed05920 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  40:     0x560b5f07ac12 - main
  41:     0x7f489d9090b3 - __libc_start_main
  42:     0x560b5de95029 - _start
  43:                0x0 - <unknown>
```

**Comment by dsherret** [comment]
Looks like #14093?

**Comment by emdienn** [comment]
Sorry, yep. I did search for an existing issue but clearly didn't look hard enough, mybad.

**Comment by dsherret** [comment]
@emdienn that's ok. This is a TypeScript compiler bug and there is a fix available in the TypeScript compiler, so it should be fixed next time we upgrade.
