### ISSUE TITLE
Aborting a CompressionStream/DecompressionStream leaks a resource

### ISSUE THREAD

**Issue by Macil** [denoland/deno#14212]
If inside of a test you call abort() on the writable end of a CompressionStream or DecompressionStream instead of close(), then you get a Deno error about a resource being leaked.

```ts
Deno.test(
  "CompressionStream may be aborted",
  // { sanitizeResources: false },
  async () => {
    const compressionStream = new CompressionStream("gzip");

    async function write() {
      const writer = compressionStream.writable.getWriter();
      await writer.ready;
      await writer.write(new Uint8Array([1, 2, 3]));
      try {
        await writer.abort(new Error("aborting"));
      } catch {
        // abort rejects with the error we give it so ignore that
      }
    }

    async function read() {
      try {
        const reader = compressionStream.readable.getReader();
        console.log("bytes received:", (await reader.read()).value?.byteLength);
        console.log("bytes received:", (await reader.read()).value?.byteLength);
      } catch (err) {
        console.log(
          "got error in read() because of abort call in write()",
          err,
        );
      }
    }

    await Promise.all([
      write(),
      read(),
    ]);
  },
);
```

If `sanitizeResources: false` is set, then this gives the expected output:

```
$ deno test fail_test.ts
Check file:///Users/macil/Coding/streaming-zip/fail_test.ts
running 1 test from file:///Users/macil/Coding/streaming-zip/fail_test.ts
test CompressionStream may be aborted ...bytes received: 19

got error in read() because of abort call in write() Error: aborting
    at write (file:///Users/macil/Coding/streaming-zip/fail_test.ts:12:28)
    at async Promise.all (index 0)
    at async file:///Users/macil/Coding/streaming-zip/fail_test.ts:31:5
    at async testStepSanitizer (deno:runtime/js/40_testing.js:444:7)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:145:9)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:9)
    at async runTest (deno:runtime/js/40_testing.js:788:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:986:22)

 ok (4ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (10ms)
```

But when run normally, this output happens instead:

```
$ deno test fail_test.ts
Check file:///Users/macil/Coding/streaming-zip/fail_test.ts
running 1 test from file:///Users/macil/Coding/streaming-zip/fail_test.ts
test CompressionStream may be aborted ...bytes received: 19

got error in read() because of abort call in write() Error: aborting
    at write (file:///Users/macil/Coding/streaming-zip/fail_test.ts:12:28)
    at async Promise.all (index 0)
    at async file:///Users/macil/Coding/streaming-zip/fail_test.ts:31:5
    at async testStepSanitizer (deno:runtime/js/40_testing.js:444:7)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:145:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:370:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:9)
    at async runTest (deno:runtime/js/40_testing.js:788:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:986:22)

 FAILED (5ms)

failures:

CompressionStream may be aborted
AssertionError: Test case is leaking 1 resource:

 - A CompressionStream (rid 3) was created during the test, but not closed during the test. Close the compression stream by calling `await stream.writable.close()`.

    at assert (deno:ext/web/00_infra.js:293:13)
    at resourceSanitizer (deno:runtime/js/40_testing.js:409:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:9)
    at async runTest (deno:runtime/js/40_testing.js:788:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:986:22)

failures:

	CompressionStream may be aborted

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (11ms)

error: Test failed
```

The same issue exists with DecompressionStream too.

The same issue also exists if the CompressionStream's readable end is canceled (instead of the writable end being aborted):

<details>
  <summary>Details about error in canceling</summary>

```ts
Deno.test(
  "CompressionStream may be aborted",
  // { sanitizeResources: false },
  async () => {
    const compressionStream = new CompressionStream("gzip");

    async function write() {
      const writer = compressionStream.writable.getWriter();
      await writer.ready;
      try {
        await writer.write(new Uint8Array([1, 2, 3]));
      } catch (err) {
        console.log(
          "got error in write() because of cancel call in read()",
          err,
        );
      }
    }

    async function read() {
      try {
        const reader = compressionStream.readable.getReader();
        await reader.cancel(new Error("canceling"));
      } catch {
        // ignore error rethrown by cancel call
      }
    }

    await Promise.all([
      write(),
      read(),
    ]);
  },
);
```

Expected output:

```
$ deno test fail_test.ts
Check file:///Users/macil/Coding/streaming-zip/fail_test.ts
running 1 test from file:///Users/macil/Coding/streaming-zip/fail_test.ts
test CompressionStream may be aborted ...got error in write() because of cancel call in read() Error: canceling
    at read (file:///Users/macil/Coding/streaming-zip/fail_test.ts:23:29)
    at file:///Users/macil/Coding/streaming-zip/fail_test.ts:31:7
    at testStepSanitizer (deno:runtime/js/40_testing.js:444:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:145:15)
    at Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:15)
    at runTest (deno:runtime/js/40_testing.js:788:18)
    at Object.runTests (deno:runtime/js/40_testing.js:986:28)
    at [deno:cli/tools/test.rs:512:6]:1:21

 ok (4ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (10ms)
```

Actual output:

```
$ deno test fail_test.ts
Check file:///Users/macil/Coding/streaming-zip/fail_test.ts
running 1 test from file:///Users/macil/Coding/streaming-zip/fail_test.ts
test CompressionStream may be aborted ...got error in write() because of cancel call in read() Error: canceling
    at read (file:///Users/macil/Coding/streaming-zip/fail_test.ts:23:29)
    at file:///Users/macil/Coding/streaming-zip/fail_test.ts:31:7
    at testStepSanitizer (deno:runtime/js/40_testing.js:444:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:145:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:370:13)
    at Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:15)
    at runTest (deno:runtime/js/40_testing.js:788:18)
    at Object.runTests (deno:runtime/js/40_testing.js:986:28)
    at [deno:cli/tools/test.rs:512:6]:1:21

 FAILED (5ms)

failures:

CompressionStream may be aborted
AssertionError: Test case is leaking 1 resource:

 - A CompressionStream (rid 3) was created during the test, but not closed during the test. Close the compression stream by calling `await stream.writable.close()`.

    at assert (deno:ext/web/00_infra.js:293:13)
    at resourceSanitizer (deno:runtime/js/40_testing.js:409:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:9)
    at async runTest (deno:runtime/js/40_testing.js:788:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:986:22)

failures:

	CompressionStream may be aborted

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (10ms)

error: Test failed
```

</details>

**Comment by Macil** [comment]
This issue still exists in Deno v1.23.0.

**Comment by j50n** [comment]
I believe this is still a problem. Would it help to give another reproduction scenario?
