### ISSUE TITLE
tools/setup.py is not working in mac

### ISSUE THREAD

**Issue by avinashdvv** [denoland/deno#1425]
```
Traceback (most recent call last):
  File "setup.py", line 169, in <module>
    sys.exit(main())
  File "setup.py", line 18, in main
    third_party.fix_symlinks()
  File "/Users/d.v.v.avinash/Desktop/personal/deno/tools/third_party.py", line 107,
in fix_symlinks
    remove_and_symlink("../../build", tp("v8/build"), True)
  File "/Users/d.v.v.avinash/Desktop/personal/deno/tools/util.py", line 105, in remo
ve_and_symlink
    symlink(target, name, target_is_dir)
  File "/Users/d.v.v.avinash/Desktop/personal/deno/tools/util.py", line 143, in syml
ink
    os.symlink(target, name)
OSError: [Errno 2] No such file or directory
```
i am getting this error while running `tool/setup.py` on mac

```
   Compiling want v0.0.6
   Compiling lock_api v0.1.5
   Compiling tokio-current-thread v0.1.4
   Compiling tokio-timer v0.2.8
   Compiling flatbuffers v0.5.0
   Compiling rand_chacha v0.1.0
   Compiling rand_pcg v0.1.1
   Compiling parking_lot_core v0.3.1
   Compiling rand v0.6.1
   Compiling crossbeam-epoch v0.7.0
   Compiling rand v0.5.5
   Compiling iovec v0.1.2
   Compiling net2 v0.2.33
   Compiling num_cpus v1.9.0
   Compiling signal-hook v0.1.6
   Compiling time v0.1.41
   Compiling rand v0.4.3
   Compiling dirs v1.0.4
   Compiling atty v0.2.11
error: failed to run custom build command for `deno v0.2.4 (/Users/d.v.v.avinash/Desktop/personal/deno)`
process didn't exit successfully: `/Users/d.v.v.avinash/Desktop/personal/deno/target/debug/build/deno-c34bd244d9f1b2d0/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=DENO_BUILD_PATH
cargo:rerun-if-env-changed=APPVEYOR_REPO_COMMIT
cargo:rustc-env=GN_OUT_DIR=/Users/d.v.v.avinash/Desktop/personal/deno/target/debug
cargo:rustc-link-search=native=/Users/d.v.v.avinash/Desktop/personal/deno/target/debug/obj/libdeno
cargo:rustc-link-lib=static=deno
cargo:rustc-link-lib=dylib=c++

--- stderr
Traceback (most recent call last):
  File "./tools/setup.py", line 169, in <module>
    sys.exit(main())
  File "./tools/setup.py", line 18, in main
    third_party.fix_symlinks()
  File "/Users/d.v.v.avinash/Desktop/personal/deno/tools/third_party.py", line 107,in fix_symlinks
    remove_and_symlink("../../build", tp("v8/build"), True)
  File "/Users/d.v.v.avinash/Desktop/personal/deno/tools/util.py", line 105, in remove_and_symlink
    symlink(target, name, target_is_dir)
  File "/Users/d.v.v.avinash/Desktop/personal/deno/tools/util.py", line 143, in symlink
    os.symlink(target, name)
OSError: [Errno 2] No such file or directory
thread 'main' panicked at 'assertion failed: status.success()', build.rs:86:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
and i am getting this error  while running `cargo build`

**Comment by avinashdvv** [comment]
for the above issues, this line is failing in third_party.py
`remove_and_symlink("../../build", tp("v8/build"), True)`

**Comment by avinashdvv** [comment]
`git submodule update --init` is not working properly, after that i re-cloned the repo with `
git clone --recurse-submodules https://github.com/denoland/deno.git`.  

after this, i run `python tools/setup.py`. But now i am getting below error

```
CMP-210:tools d.v.v.avinash$ python setup.py
python /Users/d.v.v.avinash/Desktop/personal/deno/third_party/depot_tools/download_from_google_storage.py --platform=darwin --no_auth --bucket=chromium-gn --sha1_file /Users/d.v.v.avinash/Desktop/personal/deno/third_party/v8/buildtools/mac/gn.sha1
python /Users/d.v.v.avinash/Desktop/personal/deno/third_party/depot_tools/download_from_google_storage.py --platform=darwin --no_auth --bucket=chromium-clang-format --sha1_file /Users/d.v.v.avinash/Desktop/personal/deno/third_party/v8/buildtools/mac/clang-format.sha1
python /Users/d.v.v.avinash/Desktop/personal/deno/third_party/v8/tools/clang/scripts/update.py --if-needed
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-346388-5.tgz .......... Done.
release: Writing gn options to '/Users/d.v.v.avinash/Desktop/personal/deno/target/release/args.gn'.
python /Users/d.v.v.avinash/Desktop/personal/deno/third_party/depot_tools/download_from_google_storage.py --platform=darwin --no_auth --bucket=denoland --sha1_file prebuilt/mac/sccache.sha1
0> Downloading prebuilt/mac/sccache...
Downloading 1 files took 69.853673 second(s)
  is_official_build=true
  cc_wrapper="/Users/d.v.v.avinash/Desktop/personal/deno/prebuilt/mac/sccache"
  rustc_wrapper="/Users/d.v.v.avinash/Desktop/personal/deno/prebuilt/mac/sccache"
/Users/d.v.v.avinash/Desktop/personal/deno/third_party/depot_tools/gn gen/Users/d.v.v.avinash/Desktop/personal/deno/target/release
ERROR at //build/config/mac/mac_sdk.gni:68:5: Script returned non-zero exit code.
    exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
    ^----------
Current dir: /Users/d.v.v.avinash/Desktop/personal/deno/target/release/
Command: python /Users/d.v.v.avinash/Desktop/personal/deno/build/mac/find_sdk.py --print_sdk_path 10.12
Returned 1.
stderr:

Traceback (most recent call last):
  File "/Users/d.v.v.avinash/Desktop/personal/deno/build/mac/find_sdk.py", line 104, in <module>
    print main()
  File "/Users/d.v.v.avinash/Desktop/personal/deno/build/mac/find_sdk.py", line 71, in main
    'to continue.')
__main__.SdkError: 'Install Xcode, launch it, accept the license agreement, and run `sudo xcode-select -s /path/to/Xcode.app` to continue.'

See //build/toolchain/mac/BUILD.gn:14:1: whence it was imported.
import("//build/config/mac/mac_sdk.gni")
^--------------------------------------
See //BUILD.gn:10:1: which caused the file to be included.
group("default") {
```

**Comment by avinashdvv** [comment]
Install Xcode, launch it, accept the license agreement, and run sudo xcode-select -s /path/to/Xcode.app to continue.`
