### ISSUE TITLE
fetch redirect issue with utf8 locations

### ISSUE THREAD

**Issue by erfanium** [denoland/deno#14322]
fetch should convert location header encoding from `latin1` to `utf8` in order to correctly support all utf8 characters.

Look at this example from got:
https://github.com/sindresorhus/got/blob/53513ce3ca09258b575496a3f9899c7d0f6ab6ea/source/core/index.ts#L772

I think function `resolve_url_from_location` should be modified

**Comment by erfanium** [comment]
I'll create a repro code as soon as possible

**Comment by andreubotella** [comment]
URLs as sent over HTTP are made up of bytes, interpreted with the Latin-1 encoding; and so is the `Location` header. HTTP clients (browsers, for example) can take the bytes in the `Location` header and directly pass them as the URL for the next request (assuming the URL is absolute and has no hash component). If a server returns a UTF-8 `Location` header but will not accept a URL with those same bytes, that server's logic is wrong. `new URL(headers.get("Location"), baseUrl).href` should get you the right URL for the next request (at least with the `fetch` API; dunno about Node's HTTP API).

**Comment by erfanium** [comment]
To repro this issue, simply run this code in Deno and chorome:
```js
const url = "https://nobat.ir/doctor/%D8%AF%DA%A9%D8%AA%D8%B1-%D8%B3%DB%8C%D8%AF-%D9%85%D8%AD%D9%85%D8%AF-%D9%82%D8%B1%DB%8C%D8%B4%DB%8C-%D8%AA%D9%87%D8%B1%D8%A7%D9%86/dr-14917/";
await fetch(url);
```


#### Deno output
```
Uncaught TypeError: Fetch failed: Maximum number of redirects (20) reached
    at deno:ext/fetch/26_fetch.js:469:27
    at async fetch (deno:ext/fetch/26_fetch.js:490:9)
    at async <anonymous>:2:1
```

#### Chrome output
```
Response {type: 'cors', url: 'xxxx', redirected: true, status: 200, ok: true, …}
```
