### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli\fs_util.rs:273:52

### ISSUE THREAD

**Issue by masx200** [denoland/deno#14375]
```
 deno test "file://C:/Documents/gitee/leetcode-test/deps.ts"




============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.21.0
Args: ["C:\\Users\\Administrator\\.deno\\bin\\deno.exe", "test", "file://C:/Documents/gitee/leetcode-test/deps.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli\fs_util.rs:273:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
deno bench "file:///C:/Documents/gitee/leetcode-test/deps.ts"

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env

Platform: windows x86_64
Version: 1.21.0
Args: ["C:\\Users\\Administrator\\.deno\\bin\\deno.exe", "bench", "file:///C:/Documents/gitee/leetcode-test/deps.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli\fs_util.rs:273:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

```ts
export {
    assert,
    assertAlmostEquals,
    assertEquals,
    assertStrictEquals,
    equal,
} from "https://deno.land/std@0.136.0/testing/asserts.ts";
export { default as random } from "https://cdn.skypack.dev/lodash@4.17.21/random?dts";

export { default as uniqBy } from "https://cdn.skypack.dev/lodash@4.17.21/uniqBy?dts";

```

**Comment by masx200** [comment]
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.21.0
Args: ["deno", "test", "file://C:/Documents/gitee/leetcode-test/deps.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli\fs_util.rs:273:52
stack backtrace:
   0:     0x7ff7e22ccb84 - <unknown>
   1:     0x7ff7e18660ca - <unknown>
   2:     0x7ff7e22c04e7 - <unknown>
   3:     0x7ff7e22d0a6b - <unknown>
   4:     0x7ff7e22d0621 - <unknown>
   5:     0x7ff7e169cd59 - <unknown>
   6:     0x7ff7e22d14bd - <unknown>
   7:     0x7ff7e22d12e5 - <unknown>
   8:     0x7ff7e22d1259 - <unknown>
   9:     0x7ff7e22d1214 - <unknown>
  10:     0x7ff7e33a5b80 - CrashForExceptionInNonABICompliantCodeRange
  11:     0x7ff7e33a5e73 - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff7e16a5633 - <unknown>
  13:     0x7ff7e154a82e - <unknown>
  14:     0x7ff7e173fa6f - <unknown>
  15:     0x7ff7e1697a9c - <unknown>
  16:     0x7ff7e16a1c12 - <unknown>
  17:     0x7ff7e171a797 - <unknown>
  18:     0x7ff7e155cd52 - <unknown>
  19:     0x7ff7e169d003 - <unknown>
  20:     0x7ff7e16765bc - <unknown>
  21:     0x7ff7e17eeff7 - <unknown>
  22:     0x7ff7e335b9fc - CrashForExceptionInNonABICompliantCodeRange
  23:     0x7ffa1a147034 - BaseThreadInitThunk
  24:     0x7ffa1a622651 - RtlUserThreadStart
```

**Comment by sirgallifrey** [comment]
Looking at the code on fs_utils, it seems `test` and `bench` don't support file url, they only http://, https:// and relative paths or absolute paths.

A simple fix, in case the given file is using file:// protocol, could be to make fs_util::collect_specifiers to not change it at all, or transform it into a path, traverse the dir, if any, and then back into Urls
Plus add a descriptive error to all unwraps in that function.

If it's ok I would like to work on this for my first contribution to Deno, but it would be nice to have some comments from a contributor to know if my idea is valid

**Comment by bartlomieju** [comment]
> Looking at the code on fs_utils, it seems `test` and `bench` don't support file url, they only http://, https:// and relative paths or absolute paths.
> 
> A simple fix, in case the given file is using file:// protocol, could be to make fs_util::collect_specifiers to not change it at all, or transform it into a path, traverse the dir, if any, and then back into Urls Plus add a descriptive error to all unwraps in that function.
> 
> If it's ok I would like to work on this for my first contribution to Deno, but it would be nice to have some comments from a contributor to know if my idea is valid

@sirgallifrey good investigation. What you described is reasonable and should work for the described problem. Looking forward to a PR!

**Comment by sirgallifrey** [comment]
Great I'll work on that, should have PR this week.
