### ISSUE TITLE
[unstable] DatagramConn "missing field `transport`"

### ISSUE THREAD

**Issue by skybldev** [denoland/deno#14399]
[originally posted in Deno Discord server]

I'm studying and fixing some code where I'm having a huge issue with the DatagramConn API. [Source](https://github.com/harmonyland/harmony_voice/blob/main/src/udp.ts)

A `DatagramConn` is initialized through `listenDatagram().` [Source](https://github.com/harmonyland/harmony_voice/blob/c088e694ac3342c9aaa25b07d6040b14428295a1/src/udp.ts#L44)
```ts
this.socket = Deno.listenDatagram({
  hostname: "0.0.0.0",
  port: 0,
  transport: "udp",
});
```

Later, `socket.send()` is called, with all the right arguments again. [Source](https://github.com/harmonyland/harmony_voice/blob/c088e694ac3342c9aaa25b07d6040b14428295a1/src/udp.ts#L201)
```ts
return this.socket!.send(
  buffer,
  this.conn.ws?.addr!,
);
```

This should all work, I've checked it by the [documentation](https://doc.deno.land/deno/unstable/~/Deno.DatagramConn) and it looks fine. However, it spits this out:

```
TypeError: Error parsing args at position 1: missing field `transport`
    at Object.opAsync (deno:core/01_core.js:152:35)
    at opSend (deno:ext/net/01_net.js:61:17)
    at Datagram.send (deno:ext/net/01_net.js:321:14)
    at VoiceUDP.sendVoice (file:///home/skybl/code/js/harmony_voice/src/udp.ts:201:25)
    at frame1 (file:///home/skybl/code/js/harmony_voice/src/player.ts:79:38)
```

I'm pretty confused as to why this is happening and I have no idea how to work around this. 

It is also worth knowing that this library was most likely only tested on Windows, judging by the DOS line-ending on all the files. I'm using Linux. Might this be a compatibility or platform support issue?

**Comment by skybldev** [comment]
Okay, after some digging I found that `transport` is in fact not being passed to `op_dgram_send`:

https://github.com/denoland/deno/blob/ad8e2383487e8ef4f15e7b86df80f6dc98fdcc79/ext/net/01_net.js#L281-L284

...which leads to...

https://github.com/denoland/deno/blob/ad8e2383487e8ef4f15e7b86df80f6dc98fdcc79/ext/net/01_net.js#L56-L58

...which calls `op_dgram_send` where it takes this argument set...

https://github.com/denoland/deno/blob/bb53135ed87ec063c9238e1b7de8cf3b44535685/ext/net/ops.rs#L246-L251

This is even more confusing, since I looked back in blames and found that `transport` has never been passed to `op_dgram_send`. At this point I'll try to make a local build that passes it, and see how it goes...

**Comment by skybldev** [comment]
Turns out this was just me being dumb and stuck-up lol. I forgot that the `Addr` type has the values needed, including `transport`. It wasn't available because of a race condition, for some reason.
