### ISSUE TITLE
`integration::run::worker_event_handler_test` breaks for long paths to the Deno checkout

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#14401]
If the Deno checkout is at `/some/particular/way/too/overly/long/path/to/deno`, the test's output is:
```
Target from self.onmessage: [object DedicatedWorkerGlobalScope]
Target from message event listener: [object DedicatedWorkerGlobalScope]
Arguments from self.onerror: [
  "Uncaught Error: Some error message",
  "file:///some/particular/way/too/overly/long/path/to/deno/cli/tests/testdata/workers/worker_event_han...",
  9,
  9,
  Error: Some error message
    at file:///some/particular/way/too/overly/long/path/to/deno/cli/tests/testdata/workers/worker_event_handlers.js:9:9
    at innerInvokeEventListeners (deno:ext/web/02_event.js:754:9)
    at invokeEventListeners (deno:ext/web/02_event.js:794:7)
    at dispatch (deno:ext/web/02_event.js:663:11)
    at dispatchEvent (deno:ext/web/02_event.js:1006:14)
    at pollForMessages (deno:runtime/js/99_main.js:153:9)
]
Is event canceled?: true
```

but the expectation is:
```
Target from self.onmessage: [object DedicatedWorkerGlobalScope]
Target from message event listener: [object DedicatedWorkerGlobalScope]
Arguments from self.onerror: [
  "Uncaught Error: Some error message",
  "[WILDCARD]/worker_event_handlers.js",
  9,
  9,
  Error: Some error message
    at [WILDCARD]
]
Is event canceled?: true
```

The console formatting cuts off the end of the path, breaking the expectation.

**Comment by bartlomieju** [comment]
Could possibly be fixed by https://github.com/denoland/deno/pull/14378 CC @nayeemrmn
