### ISSUE TITLE
Errors within blob urls don't have the correct file names in stack traces

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#14443]
When using dynamic imports on a blob url, the stack traces of potential errors do not show the correct file names.

```js
const blob = new Blob([`
  const x = "foo";
  x.doesNotExist();
  export {x};
`], {type: "application/javascript"});
const url = URL.createObjectURL(blob);

console.log("url:", url);
await import(url);
```

When running the above using `deno run` you get:
```
url: blob:null/df5cf37c-77e1-4ddd-b189-6ef8b3a68836
Check blob:null/df5cf37c-77e1-4ddd-b189-6ef8b3a68836
error: Uncaught (in promise) TypeError: TS2339 [ERROR]: Property 'doesNotExist' does not exist on type '"foo"'.
  x.doesNotExist();
    ~~~~~~~~~~~~
    at blob:///b0d651e4773176cd774272934e7beb31bd7e4ffff6a867671df3f98aed540ecf.js:3:5
await import(url);
^
    at async file:///Users/Jesper/repositories/fake-imports/bloburltest.ts:9:1
```
The logged blob url is `blob:null/df5cf37c-77e1-4ddd-b189-6ef8b3a68836`, but the one reported in the stack trace is `blob:///b0d651e4773176cd774272934e7beb31bd7e4ffff6a867671df3f98aed540ecf.js`.

When running with `deno run --no-check`, the stack traces are fine.

### Some background
As part of https://github.com/jespertheend/fake-imports/issues/9 I'm trying to map error messages from blob urls back to their original paths. This is pretty easy to do with type checking disabled, since you can just find and replace all occurrences of blob urls. But when type checking is enabled, this is not possible. Because in that case the shown blob urls have no reference to the original call to `URL.createObjectURL()` whatsoever.

**Comment by jespertheend** [comment]
I can't reproduce this in `1.23.1`, seems like this is no longer an issue.

**Comment by jespertheend** [comment]
Seems like I wasn't able to reproduce it because type checking is now disabled by default.
But when you run it with `--check` you can still reproduce the issue.

**Comment by bartlomieju** [comment]
No longer reproduces on current Deno — closing as fixed.

The original bug was that under `--check`, the stack-trace URL was a content-hashed `blob:///<hash>.js` form unrelated to the `blob:null/<uuid>` URL returned by `URL.createObjectURL()`. That no longer happens — the URL in the stack trace now matches the one from `createObjectURL()` exactly, in both `--check` and `--no-check`:

```
url: blob:null/14e44d7b-77df-4adb-a807-a7eba070eb25
    at blob:null/14e44d7b-77df-4adb-a807-a7eba070eb25:3:5
```

So mapping errors in blob modules back to their original source (the fake-imports use case) works now, since the reported URL is the same one handed out by `createObjectURL()`.

If you still see a mismatched blob URL in stack traces on a current version, please reopen with a repro.
