### ISSUE TITLE
thread 'main' panicked at 'assertion failed: self.wr_state >= State::TlsClosed', ext\net\ops_tls.rs:426:5

### ISSUE THREAD

**Issue by masx200** [denoland/deno#14494]
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.21.1
Args: ["deno", "run", "-A", "--unstable", "./deno/index.ts"]

thread 'main' panicked at 'assertion failed: self.wr_state >= State::TlsClosed', ext\net\ops_tls.rs:426:5
stack backtrace:
   0:     0x7ff7b29bbf44 - <unknown>
   1:     0x7ff7b1f365aa - <unknown>
   2:     0x7ff7b29af8a7 - <unknown>
   3:     0x7ff7b29bfe2b - <unknown>
   4:     0x7ff7b29bf9e1 - <unknown>
   5:     0x7ff7b1ebf9ea - <unknown>
   6:     0x7ff7b29c087d - <unknown>
   7:     0x7ff7b29c0683 - <unknown>
   8:     0x7ff7b29c0619 - <unknown>
   9:     0x7ff7b29c05d4 - <unknown>
  10:     0x7ff7b3a8da40 - CrashForExceptionInNonABICompliantCodeRange
  11:     0x7ff7b3a8db9c - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff7b2261c5c - <unknown>
  13:     0x7ff7b226219f - <unknown>
  14:     0x7ff7b2b824b6 - <unknown>
  15:     0x7ff7b1a96628 - <unknown>
  16:     0x7ff7b1a9230b - <unknown>
  17:     0x7ff7b1a91508 - <unknown>
  18:     0x7ff7b1a91041 - <unknown>
  19:     0x7ff7b1a91154 - <unknown>
  20:     0x7ff7b3a402bc - CrashForExceptionInNonABICompliantCodeRange
  21:     0x7ff82a037034 - BaseThreadInitThunk
  22:     0x7ff82a4c2651 - RtlUserThreadStart

```

Running this will throw an error.
```ts

const c=await Deno.connectTls({port:443,hostname:'www.baidu.com'});c.close()

```

Running this will not throw an error.

```ts
const c=await Deno.connectTls({port:443,hostname:'ipv6.test-ipv6.com'});c.close()
```

**Comment by lucacasonato** [comment]
@piscisaureus Could you take a look?

**Comment by masx200** [comment]
```
 await fetch('https://www.baidu.com')
Received a ServerHelloDone handshake message while expecting [CertificateRequest]
Response {
  body: ReadableStream { locked: false },
  bodyUsed: false,
  headers: Headers {
  "accept-ranges": "bytes",
  "cache-control": "no-cache",
  connection: "keep-alive",
  "content-length": "227",
  "content-type": "text/html",
  date: "Sat, 07 May 2022 01:14:14 GMT",
  p3p: 'CP=" OTI DSP COR IVA OUR IND COM ", CP=" OTI DSP COR IVA OUR IND COM "',
  pragma: "no-cache",
  server: "BWS/1.1",
  "set-cookie": "BAIDUID=AA1C044B1B81A8119F41F5D8D1FEDFB6:FG=1; max-age=31536000; expires=Sun, 07-May-23 01:14:14 GMT...",
  "strict-transport-security": "max-age=0",
  traceid: "1651886054062447207412560344695640423972",
  "x-frame-options": "sameorigin",
  "x-ua-compatible": "IE=Edge,chrome=1"
},
  ok: true,
  redirected: false,
  status: 200,
  statusText: "OK",
  url: "https://www.baidu.com/"
}
```

**Comment by cjihrig** [comment]
`Received a ServerHelloDone handshake message while expecting [CertificateRequest]` seems to be a [bug in rustls](https://github.com/rustls/rustls/issues/1012). It looks like the bug is fixed but not released yet.

**Comment by cjihrig** [comment]
@masx200 I believe we have a fix for the issue you originally reported - just trying to create a unit test for the change. In the interim, to unblock you, adding an `await c.handshake()` after the `Deno.connectTls()` call prevented the panic on my local machine.
