### ISSUE TITLE
deno fmt panic due to unstable formatting on minified file

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#14527]
```

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.21.2
Args: ["deno", "fmt", "worker.min.js"]

thread 'tokio-runtime-worker' panicked at 'Formatting not stable. Bailed after 5 tries. This indicates a bug in the
 formatter where it formats the file differently each time. As a temporary workaround you can ignore this file.', c
li/tools/fmt.rs:458:11
stack backtrace:
   0:     0x55d67483d37c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/s
rc/backtrace/libunwind.rs:93:5
   1:     0x55d67483d37c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/s
rc/backtrace/mod.rs:66:5
   2:     0x55d67483d37c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtr
ace.rs:67:5
   3:     0x55d67483d37c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b
509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtr
ace.rs:46:22
   4:     0x55d67486b24c - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:
17
   5:     0x55d674832ba3 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x55d674840142 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtr
ace.rs:49:5
   7:     0x55d674840142 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtr
ace.rs:36:9
   8:     0x55d674840142 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:
50
   9:     0x55d67483fd25 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:
9
  10:     0x55d674ad3ef1 - deno::setup_panic_hook::{{closure}}::hd94fa7456793168a
  11:     0x55d6748408b5 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:
17
  12:     0x55d6748405b0 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:
13
  13:     0x55d67483d824 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtr
ace.rs:139:18
  14:     0x55d6748402e9 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:
5
  15:     0x55d674868a71 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116
:14
  16:     0x55d674ab2ef9 - tokio::runtime::task::raw::poll::h520670894482f419
  17:     0x55d67569565d - std::sys_common::backtrace::__rust_begin_short_backtrace::hc331b3cbe7f28f40
  18:     0x55d6756724f6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h5cb81874cd790571
  19:     0x55d674849383 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49b6c7c5155a2
296
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
  20:     0x55d674849383 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha8b5234bfeb15
105
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
  21:     0x55d674849383 - std::sys::unix::thread::Thread::new::thread_start::h6f207dd842d64859
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys/unix/thread.r
s:108:17
  22:     0x7fba8f6755c2 - start_thread
  23:     0x7fba8f6fa584 - __clone
  24:                0x0 - <unknown>
```

To reproduce:
- `wget https://unpkg.com/tesseract.js@2.1.5/dist/worker.min.js`
- `deno fmt worker.min.js`

**Comment by kitsonk** [comment]
You will need to provide a more complete reproduction, like making `worker.min.js` available.

Ideally though you don't want to format minified code, because it will add a lot of extra spacing to the file which undermines the purpose of minified code.

**Comment by sigmaSd** [comment]
I wrote the steps to repreduce(with the link to the file) in the above comment.

**Comment by sigmaSd** [comment]
I'm using deno fmt to deminify and to format json files among other things, I personally find it very useful.

**Comment by cmorten** [comment]
Added another example to the mix...

Formatting <https://github.com/cmorten/opine/blob/main/docs/assets/js/main.js> (accidentally so...) resulted in a panic from the `deno fmt` CLI.

**Output**

```console
$ deno fmt ./docs/assets/js/main.js

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.25.0
Args: ["deno", "fmt", "./docs/assets/js/main.js"]

thread 'tokio-runtime-worker' panicked at 'Formatting not stable. Bailed after 5 tries. This indicates a bug in the formatter where it formats the file differently each time. As a temporary workaround you can ignore this file.', cli/tools/fmt.rs:465:11
stack backtrace:
   0:        0x10e16b6e9 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h85521558a183f368
   1:        0x10d7129ab - core::fmt::write::h01631fae0d2b98bc
   2:        0x10e13c508 - std::io::Write::write_fmt::h675dde99a2999169
   3:        0x10e1704dd - std::panicking::default_hook::{{closure}}::h5e5df492d229fd65
   4:        0x10e1701c4 - std::panicking::default_hook::h18647b59f1a84ee2
   5:        0x10d685427 - deno::setup_panic_hook::{{closure}}::hfd35b9ff5c3158d5
   6:        0x10e17102b - std::panicking::rust_panic_with_hook::hd9ead35a68ccc55e
   7:        0x10e170ea4 - std::panicking::begin_panic_handler::{{closure}}::h6fca91c5e1dc2f30
   8:        0x10e170e19 - std::sys_common::backtrace::__rust_end_short_backtrace::h4ff3025d9a0a0490
   9:        0x10e170dd5 - _rust_begin_unwind
  10:        0x10f567f93 - core::panicking::panic_fmt::h3d9f795ee387ef8d
  11:        0x10d429283 - tokio::runtime::task::raw::poll::hc40159f7214e797c
  12:        0x10e2d9542 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha36d954dbe24e8b1
  13:        0x10e2d92f2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbc5b29601d029abc
  14:        0x10e173a29 - std::sys::unix::thread::Thread::new::thread_start::hf7c5ae502e9a7ed8
  15:     0x7ff8134bd514 - __pthread_start
```

**Similar Issues**

Maybe related to <https://github.com/denoland/deno/issues/14728>

**Comment by ry** [comment]
This has been fixed at some point.

**Comment by bartlomieju** [comment]
Verified resolved on current Deno. Both repro inputs from this issue now format successfully and **stably** on `deno 2.8.2`, with no "Formatting not stable. Bailed after 5 tries" panic:

- `https://unpkg.com/tesseract.js@2.1.5/dist/worker.min.js` (the original repro; the URL pins `@2.1.5` so it's the byte-identical file) — formats cleanly in both stdin and `deno fmt --check` file mode.
- `opine/docs/assets/js/main.js` (the second repro from @cmorten) — formats cleanly.

The instability was fixed by intervening `dprint-plugin-typescript` updates. Closing as resolved; please reopen if a current release still panics for you.
