### ISSUE TITLE
`deno test --jobs` panic on `deno::tools::test::TestOutputPipe::flush`

### ISSUE THREAD

**Issue by curtislarson** [denoland/deno#14537]
I can reproduce this reliably in any large repo locally and in Github Actions and tends to happen more frequently the larger the worker jobs specified. For instance in `deno_std` changing the default `deno task test` command to use `--jobs=8` (max for my laptop):

```sh
Deno has panicked. This is a bug in Deno. Please report this
------- output -------
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.21.2
Args: ["deno", "test", "--jobs=8", "--doc", "--unstable", "--allow-all", "--coverage=./cov", "--ignore=node/"]

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', cli/tools/test.rs:1536:21
stack backtrace:
​[async] abortable (Promise) ...----- output end -----
ok (105ms)
running 2 tests from ./async/pool_test.ts
[async] deadline: return fulfilled promise ... ok (106ms)
running 0 tests from ./async/tee.ts
   0:        0x104f74400 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h58c637f9e30d1b8a
   1:        0x104842bf0 - core::fmt::write::hc16ca97d9f5e0acd
   2:        0x104f6ee68 - std::io::Write::write_fmt::hd53dc7153ccce04d
   3:        0x104f790f8 - std::panicking::default_hook::{{closure}}::ha41f2cf175ca93cf
   4:        0x104f78d70 - std::panicking::default_hook::h838498b157804a1a
   5:        0x1046dbb74 - deno::setup_panic_hook::{{closure}}::h2a1ed8dd0d1b9c5f
   6:        0x104f79c30 - std::panicking::rust_panic_with_hook::h7722806c30430655
   7:        0x104f79994 - std::panicking::begin_panic_handler::{{closure}}::h265229fa7cad6de7
   8:        0x104f79914 - std::sys_common::backtrace::__rust_end_short_backtrace::hfa83d61d0ed14557
   9:        0x104f798e0 - _rust_begin_unwind
  10:        0x1048415d4 - core::panicking::panic_fmt::hd3f68d55261c2af0
  11:        0x1048466a8 - core::result::unwrap_failed::hc1b85f369312af72
  12:        0x1046af5f0 - deno::tools::test::TestOutputPipe::flush::he615e287304bb2e2
  13:        0x1046efac8 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::hcf7f82101afc1b7e
```

Is `--jobs` considered unstable? Or if this isn't an issue with Deno is there something I can do for my local and CI environment to ensure this works? Running with max threads really speeds up my test run time.

<details>

<summary><h1>Full Output</h1></summary>

```sh
❯ RUST_BACKTRACE=full deno test --jobs=8 --doc --unstable --allow-all --coverage=./cov --ignore=node/
running 0 tests from ./_tools/check_circular_deps.ts
running 0 tests from ./README.md
running 0 tests from ./.github/ISSUE_TEMPLATE/bug_report.md
running 0 tests from ./Releases.md
running 1 test from ./_deno_unstable_test.ts
running 0 tests from ./_deno_unstable.ts
running 0 tests from ./_deno_unstable_checked.ts
running 0 tests from ./.github/ISSUE_TEMPLATE/feature_request.md
running 0 tests from ./_tools/release/01_bump_version.ts
running 0 tests from ./_tools/release/repo.ts
running 0 tests from ./_tools/release/deps.ts
running 0 tests from ./_tools/release/03_release.ts
running 0 tests from ./_tools/release/02_create_pr.ts
running 0 tests from ./_util/assert.ts
running 0 tests from ./_util/deep_assign.ts
running 3 tests from ./_util/assert_test.ts
running 0 tests from ./_util/download_file.ts
_deno_unstable.ts complies with --unstable if type checked ... ok (49ms)
running 1 test from ./_util/deep_assign_test.ts
assert valid scenario ... ok (3ms)
deepAssignTest ... ok (3ms)
running 0 tests from ./_util/os.ts
assert invalid scenario, no message ... ok (5ms)
running 0 tests from ./_wasm_crypto/README.md
assert invalid scenario, with message ... ok (4ms)
running 1 test from ./_util/download_file_test.ts
running 0 tests from ./_wasm_crypto/_build.ts
running 0 tests from ./_wasm_crypto/crypto.mjs
running 0 tests from ./_wasm_crypto/crypto.wasm.mjs
running 0 tests from ./_wasm_crypto/mod.ts
running 0 tests from ./archive/tar.ts
running 0 tests from ./archive/README.md
running 0 tests from ./async/README.md
running 0 tests from ./async/abortable.ts
running 6 tests from ./async/abortable_test.ts
running 2 tests from ./_wasm_crypto/test.ts
test ... ok (5ms)
running 0 tests from ./async/deadline.ts
Inlined WASM file's metadata should match its content ... ok (4ms)
running 3 tests from ./async/deadline_test.ts
running 0 tests from ./async/debounce.ts
running 10 tests from ./archive/tar_test.ts
running 5 tests from ./async/debounce_test.ts
createTarArchive ... ok (6ms)
deflateTarArchive ... ok (1ms)
appendFileWithLongNameToTarArchive ... ok (2ms)
running 0 tests from ./async/deferred.ts
running 4 tests from ./async/deferred_test.ts
[node/_tools/setup] downloadFile ... ok (78ms)
[async] deferred: resolve ... ok (3ms)
untarAsyncIterator ... ok (19ms)
[async] deferred: reject ... ok (3ms)
untarAsyncIteratorWithoutReadingBody ... ok (2ms)
[async] deferred: state with promised value ... ok (2ms)
[async] deferred: state is readonly ... ok (2ms)
untarAsyncIteratorWithoutReadingBodyFromFileReader ... ok (4ms)
running 0 tests from ./async/delay.ts
untarAsyncIteratorFromFileReader ... ok (3ms)
running 5 tests from ./async/delay_test.ts
running 0 tests from ./async/mod.ts
running 0 tests from ./async/mux_async_iterator.ts
untarAsyncIteratorReadingLessThanRecordSize ... ok (31ms)
untarLinuxGeneratedTar ... ok (3ms)
directoryEntryType ... ok (3ms)
running 3 tests from ./async/mux_async_iterator_test.ts
running 0 tests from ./async/pool.ts

============================================================

Deno has panicked. This is a bug in Deno. Please report this
------- output -------
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.21.2
Args: ["deno", "test", "--jobs=8", "--doc", "--unstable", "--allow-all", "--coverage=./cov", "--ignore=node/"]

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', cli/tools/test.rs:1536:21
stack backtrace:
​[async] abortable (Promise) ...----- output end -----
ok (105ms)
running 2 tests from ./async/pool_test.ts
[async] deadline: return fulfilled promise ... ok (106ms)
running 0 tests from ./async/tee.ts
   0:        0x104f74400 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h58c637f9e30d1b8a
   1:        0x104842bf0 - core::fmt::write::hc16ca97d9f5e0acd
   2:        0x104f6ee68 - std::io::Write::write_fmt::hd53dc7153ccce04d
   3:        0x104f790f8 - std::panicking::default_hook::{{closure}}::ha41f2cf175ca93cf
   4:        0x104f78d70 - std::panicking::default_hook::h838498b157804a1a
   5:        0x1046dbb74 - deno::setup_panic_hook::{{closure}}::h2a1ed8dd0d1b9c5f
   6:        0x104f79c30 - std::panicking::rust_panic_with_hook::h7722806c30430655
   7:        0x104f79994 - std::panicking::begin_panic_handler::{{closure}}::h265229fa7cad6de7
   8:        0x104f79914 - std::sys_common::backtrace::__rust_end_short_backtrace::hfa83d61d0ed14557
   9:        0x104f798e0 - _rust_begin_unwind
  10:        0x1048415d4 - core::panicking::panic_fmt::hd3f68d55261c2af0
  11:        0x1048466a8 - core::result::unwrap_failed::hc1b85f369312af72
  12:        0x1046af5f0 - deno::tools::test::TestOutputPipe::flush::he615e287304bb2e2
  13:        0x1046efac8 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::hcf7f82101afc1b7e
```

</details>

**Comment by c4spar** [comment]
I have the same issue in two of my projects since deno `1.21.2`. It works if i remove the `--jobs` flag.
With `1.21.1` the --jobs flag is working for me.

```
Platform: macos x86_64
Version: 1.21.2

Args: ["deno", "test", "--unstable", "-A", "--jobs", "8"]

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', cli/tools/test.rs:1536:21
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: deno::tools::test::TestOutputPipe::flush
   4: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
   5: __ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
   6: __ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
   7: __ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

- https://github.com/c4spar/deno-cliffy/runs/6369066748?check_suite_focus=true
- https://github.com/c4spar/deno-dzx/runs/6361820633?check_suite_focus=true
