### ISSUE TITLE
deno fmt issue with minified JS file

### ISSUE THREAD

**Issue by al20ov** [denoland/deno#14728]
Hi,

I got an error trying to format a js file that is seemingly valid (generated by babel and webpack, loads in the browser fine). Is there a way to fix this and format my code properly?
I am very concerned about the line that says "_Formatting not stable. Bailed after 5 tries. This indicates a bug in the formatter where **it formats the file differently each time**_".

Does that mean the formatter is not deterministic?

## Backtrace

`RUST_BACKTRACE=1 deno fmt main.js`
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.22.0
Args: ["deno", "fmt", "main.js"]

thread 'tokio-runtime-worker' panicked at 'Formatting not stable. Bailed after 5 tries. This indicates a bug in the formatter where it formats the file differently each time. As a temporary workaround you can ignore this file.', cli/tools/fmt.rs:458:11
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
<hr>

I really like the deno formatter and I use it for all my JS projects, deno or not because it uses sane settings (two spaces, splits a line if it's too long, etc...). It's literally the first time it's failed me.

Thanks for your help.

**Comment by dsherret** [comment]
@al20ov would you be able to provide the contents of main.js?

Yes, it’s a bug where the formatting keeps flipping back and forth on something.

**Comment by al20ov** [comment]
Here is the file:
[main.js](https://github.com/denoland/deno/files/8775848/main.js.txt)

Had to append .txt to it because github wouldn't let me upload a js file.

it's very long and minified so you probably won't be able to read it unless you prettify it with another tool or a previous version of deno fmt that works.

**Comment by dsherret** [comment]
Ok thanks! Yeah, the formatter has some trouble with some minified files. I will take a look at it sometime soon.

**Comment by al20ov** [comment]
Thanks,
I will also add that it happens in `1.21.2` as well so it's most likely not a regression.

**Comment by milotheirself** [comment]
I just got the same formatting error in two files after updating to Deno version 2.3.1.

```
Error formatting: <path>
   Formatting not stable. Bailed after 5 tries. This indicates a bug in the formatter where it formats the file differently each time. As a temporary workaround you can ignore this file.
```

What triggered the error seems to be HTML comments with line breaks inside template literals with a `html` tag. This is already enough to reproduce it by running a `deno fmt` on a file with only this:

```ts 
function html(..._: unknown[]) {
  return '';
}

const foo = html`
  <!--
  -->
`;
```

**Comment by bartlomieju** [comment]
Verified resolved on current Deno. I ran the exact `main.js.txt` attached to this issue through `deno fmt` on `deno 2.8.2` and it formats successfully and **stably** — no panic and no "Formatting not stable. Bailed after 5 tries". The oscillation was fixed by intervening `dprint-plugin-typescript` updates.

Closing as resolved.

@milotheirself — you mentioned hitting the same error on 2.3.1 with different files. If you can still reproduce on a current Deno release, please open a fresh issue and attach the offending file so we can verify it directly.

**Comment by al20ov** [comment]
I completely forgot about this issue but I'm glad that it's fixed 👍  Just for fun I ran `deno fmt` on it with deno 2.5.7 (LTS) and it worked just fine so it's probably been fixed for a long time now.
