### ISSUE TITLE
version_bump should run the format command to format the Releases.md

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#14739]
I had a version_bump generated PR fail CI because the Releases.md needed to be formatted because of rather long commit messages.  The process should run formatting as part of generating the PR.

**Comment by dsherret** [comment]
Looks to be recent because of updates in the format script. I'll add an unstable flag:

```
error: Uncaught TypeError: Deno.spawn is not a function
  const { status } = await Deno.spawn(execPath, {
                                ^
    at dprint (file:///home/runner/work/deno/deno/tools/format.js:8:33)
    at main (file:///home/runner/work/deno/deno/tools/format.js:20:9)
    at async file:///home/runner/work/deno/deno/tools/format.js:41:1
Error: Error executing deno. Code: 1
    at runCommandWithOutput (https://raw.githubusercontent.com/denoland/automation/0.11.0/helpers.ts:47:11)
    at async updateReleasesMd (file:///home/runner/work/deno/deno/tools/release/01_bump_crate_versions.ts:55:3)
    at async file:///home/runner/work/deno/deno/tools/release/01_bump_crate_versions.ts:37:3
```
