### ISSUE TITLE
Deno vendor AssertionError: "data" is unexpectedly null for an index.d.ts file

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#14798]
https://github.com/esm-dev/esm.sh/issues/341#issue-1260766631

After running `deno vendor` and running a script using the import map it produced, I started getting an error related to a types file. @ije asked me to open an issue for this. A full reproduction path can be found in the esm.sh issue linked above.

```ts
error: AssertionError: "data" is unexpectedly null for "https://esm.sh/v85/@types/react@18.0.11/X-ZC9yZWFjdC1kb21AMTguMS4wLHJlYWN0QDE4LjEuMA/index.d.ts".
    at assert (deno:cli/tsc/99_main_compiler.js:71:13)
    at Object.getSourceFile (deno:cli/tsc/99_main_compiler.js:310:7)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:116391:29)
    at findSourceFile (deno:cli/tsc/00_typescript.js:116300:26)
    at deno:cli/tsc/00_typescript.js:116252:85
    at getSourceFileFromReferenceWorker (deno:cli/tsc/00_typescript.js:116218:34)
    at processSourceFile (deno:cli/tsc/00_typescript.js:116252:13)
    at deno:cli/tsc/00_typescript.js:116543:17
    at Object.forEach (deno:cli/tsc/00_typescript.js:377:30)
    at processReferencedFiles (deno:cli/tsc/00_typescript.js:116542:16)
 ```

**Comment by KyleJune** [comment]
I think that issue might also cause the other issue mentioned in that PR. I don't get either of these type errors when I'm not using the vendor/import_map.json file. The rest of my imports are fine with vendoring except for that Assertion error this issue was created for.

```
$ deno run --import-map=vendor/import_map.json example.ts
Check file:///home/kyle/Projects/deno/udibo/example.ts
error: TS2614 [ERROR]: Module '"file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/react-dom@18.1.0/client.js"' has no exported member 'hydrateRoot'. Did you mean to use 'import hydrateRoot from "file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/react-dom@18.1.0/client.js"' instead?
export { hydrateRoot } from "https://esm.sh/react-dom@18.1.0/client?target=deno&pin=v85&deps=react@18.1.0";
         ~~~~~~~~~~~
    at file:///home/kyle/Projects/deno/udibo/example.ts:2:10

TS2614 [ERROR]: Module '"file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/react-dom@18.1.0/server.js"' has no exported member 'renderToReadableStream'. Did you mean to use 'import renderToReadableStream from "file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/react-dom@18.1.0/server.js"' instead?
export { renderToReadableStream } from "https://esm.sh/react-dom@18.1.0/server?target=deno&pin=v85&deps=react@18.1.0";
         ~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/kyle/Projects/deno/udibo/example.ts:3:10

Found 2 errors.
```

**Comment by dsherret** [comment]
@KyleJune would you be able to provide a full step by step reproduction of the first issue in here? I'm unable to reproduce it. The second type checking issue I am though.

**Comment by KyleJune** [comment]
Sorry about that. I was missing reproduction path for the error in the original post. The original reproduction path was just for those 2 type errors happening only with vendor import map. I figured out minimal reproduction path for the assertion error. In this example, I just added one new import than the original reproduction path I had for the two typescript errors.

Here is example.ts:

```ts
export { default as React } from "https://esm.sh/react@18.1.0?target=deno&pin=v85";
export { hydrateRoot } from "https://esm.sh/react-dom@18.1.0/client?target=deno&pin=v85&deps=react@18.1.0";
export { renderToReadableStream } from "https://esm.sh/react-dom@18.1.0/server?target=deno&pin=v85&deps=react@18.1.0";

export { Link } from "https://esm.sh/react-router-dom@6.3.0?target=deno&pin=v85&deps=react@18.1.0,react-dom@18.1.0";
```

Here is my deno.json file:

```json
{
  "compilerOptions": {
    "lib": ["esnext", "dom", "dom.iterable", "dom.asynciterable", "deno.ns"]
  }
}
```

If I run the script without vendoring, there are no errors.

If I try running deno vendor --force example.ts I get the following error.

```
$ deno vendor --force example.ts
error: Relative import path "react" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v85/@types/react-dom@18.0.5/client~.d.ts"
```

That error is an issue with esm.sh, for some reason it is using "react" as an import map. I workaround that issue by creating and using the following import_map.json file.

```json
{
  "imports": {
    "react": "https://esm.sh/react@18.1.0?target=deno&pin=v85"
  }
}
```

When I run vendor with that import map there are no errors.

```
$ deno vendor --force --import-map=import_map.json example.ts
Vendored 34 modules into vendor/ directory.

To use vendored modules, specify the `--import-map` flag when invoking deno subcommands:
  deno run -A --import-map vendor/import_map.json example.ts
```

If I then try to run the code with that import map I get the error. It happens every time I run it.

```
$ deno run -A --import-map vendor/import_map.json example.ts
Check file:///home/kyle/Projects/deno/udibo/example.ts
error: Uncaught AssertionError: "data" is unexpectedly null for "https://esm.sh/v85/@types/react@18.0.11/X-ZC9yZWFjdC1kb21AMTguMS4wLHJlYWN0QDE4LjEuMA/index.d.ts".
    at <anonymous> (deno:cli/tsc/99_main_compiler.js:71:13)
```

I just found out the error will stop happening though if I run the file without the import map. Then if I run the above command again with the vendor import map, it doesn't log the check message or an error, it just runs successfully. This makes me think the issue is related to checking when using vendored dependencies.

If I edit the file in any way, like adding new lines and try running with the vendor/import_map.json, it does a check and the error returns.

**Comment by cscheid** [comment]
Sorry for reviving this, I'm seeing the same thing on deno 1.28.2, and the following is a step-by-step repro:

```
$ cat main.ts
import puppeteer from "https://deno.land/x/puppeteer@16.2.0/mod.ts";
$ deno --version
deno 1.28.2 (release, aarch64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
$  deno vendor main.ts
Vendored 325 modules into vendor/ directory.

To use vendored modules, specify the `--import-map vendor/import_map.json` flag when invoking Deno subcommands or add an `"importMap": "<path_to_vendored_import_map>"` entry to a deno.json file.
$ deno bundle --unstable --import-map vendor/import_map.json main.ts
Check file:///Users/cscheid/Desktop/daily-log/2022/11/28/main.ts
error: Uncaught AssertionError: "data" is unexpectedly null for "https://esm.sh/v99/node.ns.d.ts".
    at <anonymous> (deno:cli/tsc/99_main_compiler.js:92:13)
$
```

**Comment by lucacasonato** [comment]
`deno vendor` has was deprecated and has been removed in Deno 2.
