### ISSUE TITLE
Ambiguous error with `Deno.bench`

### ISSUE THREAD

**Issue by danteissaias** [denoland/deno#14862]
Steps to reproduce:
```ts
// file.ts
Deno.bench("console.log", () => {
    console.log("Hello, World!")
})
```

```
anon@mini:~/repos/fast$ deno run file.ts 
error: Uncaught TypeError: ops[opName] is not a function
Deno.bench({
     ^
    at Object.opSync (deno:core/01_core.js:172:38)
    at Object.bench (deno:runtime/js/40_testing.js:657:10)
    at file:///Users/anon/repos/fast/benchmarks.ts:11:6
```

**Comment by jmj0502** [comment]
I would like to work on this issue. How can I get more details about it?

**Comment by danteissaias** [comment]
Relevant discussion on discord: https://discord.com/channels/684898665143206084/684911491035430919/986936454225727519
