### ISSUE TITLE
Deno.test: even shorter stack traces

### ISSUE THREAD

**Issue by Skalman** [denoland/deno#14921]
Follow-up to #13586.

`Deno.test` still prints a large stack trace when using steps. Since this is very noisy, I'd like to get rid of all stack info from `deno:runtime` in the case below, or at the very least combine them into a single entry.

Example:

```ts
import { fail } from "https://deno.land/std@0.144.0/testing/asserts.ts";

Deno.test("test", async (t) => {
  await t.step("step", () => fail());
});
```

Current output:

```
> deno --version
deno 1.23.0 (release, x86_64-unknown-linux-gnu)
v8 10.4.132.5
typescript 4.7.2

> deno test test.ts
Check file:///path/to/test.ts
running 1 test from ./test.ts
test ...
  step ... FAILED (6ms)
    error: AssertionError: Failed assertion.
        throw new AssertionError(msg);
              ^
        at assert (https://deno.land/std@0.144.0/testing/asserts.ts:132:11)
        at fail (https://deno.land/std@0.144.0/testing/asserts.ts:561:3)
        at file:///path/to/test.ts:4:30
        at testStepSanitizer (deno:runtime/js/40_testing.js:449:13)
        at asyncOpSanitizer (deno:runtime/js/40_testing.js:147:15)
        at resourceSanitizer (deno:runtime/js/40_testing.js:375:13)
        at exitSanitizer (deno:runtime/js/40_testing.js:432:15)
        at TestContext.step (deno:runtime/js/40_testing.js:1415:19)
        at file:///path/to/test.ts:4:11
FAILED (17ms)

 ERRORS 

test => ./test.ts:3:6
error: Error: 1 test step failed.
    at runTest (deno:runtime/js/40_testing.js:817:11)
    at async Object.runTests (deno:runtime/js/40_testing.js:1095:22)

 FAILURES 

test => ./test.ts:3:6

FAILED | 0 passed | 1 failed (1 step) (38ms)

error: Test failed
```

**Comment by dandv** [comment]
I've created a related feature request to emphasize user code in stack traces, #27553.
