### ISSUE TITLE
Deno crash on a stream unzip

### ISSUE THREAD

**Issue by youurayy** [denoland/deno#14989]
test-case.js:
-----
```js
// RUST_BACKTRACE=1 deno run -A test-case.js

import { existsSync } from 'https://deno.land/std/fs/mod.ts'
import { read as ZipRead } from "https://deno.land/x/streaming_zip@v1.0.1/read.ts";
import { Buffer } from "https://deno.land/std@0.145.0/streams/buffer.ts"

const symbol = 'BNBDOWNUSDT' // will crash
//const symbol = 'DASHUSDT' // will succeed
const zip = `${symbol}-trades-2021-04-08`
const url = `https://data.binance.vision/data/spot/daily/trades/${symbol}/${zip}.zip`
const csv = `${zip}.csv`

if(existsSync(csv))
  Deno.removeSync(csv)

let req = await fetch(url)
for await (let entry of ZipRead(req.body)) {
  req = null
  if (entry.type === "file") {
    if (entry.name.endsWith(".csv")) {
      let buffer = new Buffer()
      console.log('unzipping 1')
      await entry.body.stream().pipeTo(buffer.writable)
      entry = null
      console.log('unzipping 2')
      // CRASHES HERE:
      let contents = new TextDecoder().decode(buffer.bytes())
      buffer = null
      console.log('writing 3')
      Deno.writeTextFileSync(csv, contents)
      contents = null
    } else {
      entry.body.autodrain()
      entry = null
    }
  }
}
```

crash message:
----
<img width="863" alt="image" src="https://user-images.githubusercontent.com/588573/176162283-96e5d247-23b9-46df-93e1-e8139cf9a4a4.png">

**Comment by littledivy** [comment]
Cannot reproduce the panic in Deno 1.23.1. Run `deno upgrade`

```
unzipping 1
unzipping 2
error: Uncaught (in promise) TypeError: Error serializing return: Cannot allocate String from UTF-16: buffer exceeds maximum length.
      let contents = new TextDecoder().decode(buffer.bytes())
                                       ^
    at Object.opSync (deno:core/01_core.js:170:38)
    at TextDecoder.decode (deno:ext/web/08_text_encoding.js:127:23)
    at file:///Users/divy/gh/14989.js:27:40
```

**Comment by youurayy** [comment]
I can confirm the above on Deno 1.23.1.

Thanks!
