### ISSUE TITLE
ffi: Panic when passing empty array by value (index out of bounds)

### ISSUE THREAD

**Issue by glebbash** [denoland/deno#14993]
Passing empty array "by value" to foreign function panics, while passing it using `Deno.UnsafePointer.of` works fine.

Passing non-empty arrays of pointers works fine though.

Reproduction:
```ts
const lib = Deno.dlopen(
  "/usr/lib/llvm-13/lib/libLLVM.so",
  {
    LLVMContextCreate: { result: "pointer", parameters: [] },
    LLVMInt32TypeInContext: { result: "pointer", parameters: ["pointer"] },
    /* signature:
    LLVMTypeRef LLVMFunctionType
      LLVMTypeRef ReturnType, LLVMTypeRef *ParamTypes,
      unsigned ParamCount, LLVMBool IsVarArg
    ) */
    LLVMFunctionType: {
      result: "pointer",
      parameters: [
        "pointer",
        "pointer", // type array
        "i32",
        "i8", // boolean
      ],
    },
  } as const,
);

const i32Type = lib.symbols.LLVMInt32TypeInContext(
  lib.symbols.LLVMContextCreate(),
);

const args1 = BigUint64Array.from([i32Type]);
lib.symbols.LLVMFunctionType(i32Type, args1, args1.length, 0);

const args2 = BigUint64Array.from([]);
const args2Pointer = Deno.UnsafePointer.of(args2);

lib.symbols.LLVMFunctionType(i32Type, args2Pointer, args2.length, 0);

// panics:
lib.symbols.LLVMFunctionType(i32Type, args2, args2.length, 0);
```

Output:
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.23.1
Args: ["deno", "run", "--allow-all", "--unstable", "src/repro.ts"]

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', ext/ffi/lib.rs:706:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:84:5
   3: deno_ffi::ffi_parse_args
   4: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
   5: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
             at ./../../../../v8/src/api/api-arguments-inl.h:147:3
   6: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
             at ./../../../../v8/src/builtins/builtins-api.cc:114:36
   7: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
             at ./../../../../v8/src/builtins/builtins-api.cc:132:1
   8: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by aapoalas** [comment]
Huh. Seems like there is yet another way to create a null pointer. I have a fix for this soon to be published as a PR.
