### ISSUE TITLE
Deno.run fails to resolve .cmd executable on Windows even though .cmd is in PATHEXT

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#15034]
This is weird:

```shellsession
> deno
Deno 1.23.2
exit using ctrl+d or close()
> Deno.run({ cmd: ["npm"] })
Uncaught NotFound: program not found
    at Object.opSync (deno:core/01_core.js:170:12)
    at opRun (deno:runtime/js/40_process.js:28:17)
    at Object.run (deno:runtime/js/40_process.js:111:17)
    at <anonymous>:2:6
> console.log(Deno.env.get("PATHEXT"))
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.CPL
undefined
> Deno.run({ cmd: ["npm.cmd"] })
Process { rid: 3, pid: 21176 }
```

**Comment by dsherret** [comment]
It seems Rust does not take into account PATHEXT...

https://github.com/rust-lang/rust/blob/5018181c79a6fe37913fd931005ad2a63c85be7b/library/std/src/sys/windows/process.rs#L425

**Comment by dsherret** [comment]
Actually, maybe this is not a bug because the CreateProcessW docs seems to only suggest appending .exe and for stuff like .com it needs to be appended https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw

Additionally, the same behaviour occurs in node.js. I'm going to close this one.
