### ISSUE TITLE
Panic caused by missing h in @jsxFrag pragma

### ISSUE THREAD

**Issue by bcheidemann** [denoland/deno#15051]
**Reproduction Steps**

1. Create a new Fresh project
2. Add the below code at `routes/posts/[id].tsx`
3. Run

```tsx
/** @jsx h */
/** @jsxFrag */
import { h } from "preact";
import { Handlers, PageProps } from "$fresh/server.ts";
import { Marked, Parsed } from "markdown";

type Data = { markup: Parsed };

export const handler: Handlers<Data> = {
  async GET(req, ctx) {
    const markdown = await Deno.readTextFile(`posts/${ctx.params.id}.md`)
    const markup = Marked.parse(markdown);
    const resp = await ctx.render({ markup });
    return resp;
  },
};

export default function Greet(props: PageProps<Data>) {
  return (
    <>
      <div
        dangerouslySetInnerHTML={{
          __html: props.data.markup.content,
        }}
      />
    </>
  );
}

```

Note that `/** @jsxFrag */` should be `/** @jsxFrag h */` and this typo causes a panic.

**Output**

```
Warning deno task is unstable and may drastically change in the future
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 4 routes and 1 islands.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.23.2
Args: ["/home/ben/.deno/bin/deno", "run", "-A", "--watch=static/,routes/", "dev.ts"]

thread 'main' panicked at 'not yet implemented: proper error reporting for wrong `@jsxFrag`', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_react-0.120.0/src/jsx/mod.rs:338:34
stack backtrace:
   0:     0x55d31e1aa18d - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d31e1aa18d - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d31e1aa18d - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55d31e1aa18d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55d31e1d3e0c - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x55d31e1a1931 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:     0x55d31e1ac2a5 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55d31e1ac2a5 - std::sys_common::backtrace::print::h426700d6240cdcc2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55d31e1ac2a5 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:     0x55d31e1abf59 - std::panicking::default_hook::h2e88d02087fae196
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:     0x55d31e4e9bad - deno::setup_panic_hook::{{closure}}::h6a421b61f713e8b6
  11:     0x55d31e1ac9b0 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
  12:     0x55d31e1ac7e7 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
  13:     0x55d31e1aa644 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x55d31e1ac519 - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  15:     0x55d31e1d1603 - core::panicking::panic_fmt::h366d3a309ae17c94
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  16:     0x55d31e8248e6 - swc_ecma_transforms_react::jsx::JsxDirectives::from_comments::h5e1fc5f0a1c7945b
  17:     0x55d31e7da06d - swc_ecma_transforms_typescript::strip::Strip<C>::parse_jsx_directives::{{closure}}::hc4976d6feae7d0eb
  18:     0x55d31e7d9e4e - swc_ecma_transforms_typescript::strip::Strip<C>::parse_jsx_directives::hbd6de38ce619a384
  19:     0x55d31e80e6e0 - deno_ast::transpiling::fold_program::h521c13fa4a0d2a43
  20:     0x55d31e809915 - deno_ast::transpiling::<impl deno_ast::parsed_source::ParsedSource>::transpile::h7fb1d9c9d5d75379
  21:     0x55d31e4a79fb - deno::proc_state::ProcState::prepare_module_load::{{closure}}::h770d018673077212
  22:     0x55d31e3b2183 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc53a3547e4d062ce
  23:     0x55d31e39826c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9e550c131ee795f5
  24:     0x55d31f2c46c2 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8d137dc33dfb1ba3
  25:     0x55d31f2eba9f - deno_core::runtime::JsRuntime::poll_event_loop::h1dc2276de2b5c564
  26:     0x55d31e3bdf9d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdc7afd5561fee312
  27:     0x55d31e3c30d3 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdf960def353d80e3
  28:     0x55d31e395539 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h986c628713ccd12c
  29:     0x55d31e3c555a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::heae0dc1172ad5be1
  30:     0x55d31e4e8358 - deno::run_command::{{closure}}::ha8069cabbb45929d
  31:     0x55d31e3c99fa - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf6f1f2ac059a88a8
  32:     0x55d31e4eca73 - deno::main::{{closure}}::h5643fae1aeead7a7
  33:     0x55d31e3b23fc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc7736959919d44db
  34:     0x55d31e1fed66 - deno_runtime::tokio_util::run_basic::h250e312ebe566934
  35:     0x55d31e4e9dcd - deno::main::hd4a930ada2d10825
  36:     0x55d31e231ced - std::sys_common::backtrace::__rust_begin_short_backtrace::hde12cd3b4ac4f0db
  37:     0x55d31e2373e7 - std::rt::lang_start::{{closure}}::h14a2c42803fff497
  38:     0x55d31e197a5e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
  39:     0x55d31e197a5e - std::panicking::try::do_call::hf2ad5355fcafe775
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  40:     0x55d31e197a5e - std::panicking::try::h0a63ac363423e61e
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  41:     0x55d31e197a5e - std::panic::catch_unwind::h18088edcecb8693a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  42:     0x55d31e197a5e - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
  43:     0x55d31e197a5e - std::panicking::try::do_call::hda0c61bf3a57d6e6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  44:     0x55d31e197a5e - std::panicking::try::hbc940e68560040a9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  45:     0x55d31e197a5e - std::panic::catch_unwind::haed0df2aeb3fa368
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  46:     0x55d31e197a5e - std::rt::lang_start_internal::h9c06694362b5b80c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  47:     0x55d31e501792 - main
  48:     0x7f8b523e6fd0 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  49:     0x7f8b523e707d - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:409:3
  50:     0x55d31d2a2029 - _start
  51:                0x0 - <unknown>
```

**Comment by bcheidemann** [comment]
This is caused by an issue with `swc_ecma_transforms_react`. See https://github.com/swc-project/swc/blob/162671ce32765df00e4d7ad8f8c69a8608404360/crates/swc_ecma_transforms_react/src/jsx/mod.rs#L338
Not sure if Deno should panic under these circumstances? 🤔

**Comment by bartlomieju** [comment]
Opened https://github.com/swc-project/swc/issues/5099

**Comment by crowlKats** [comment]
This has been fixed.
