### ISSUE TITLE
esm.sh error: Remote modules are not allowed to import local modules. Consider using a dynamic import instead.

### ISSUE THREAD

**Issue by NekoMaru76** [denoland/deno#15065]
```sh
$ deno cache https://esm.sh/assemblyscript?bundle
Download https://esm.sh/assemblyscript?bundle
Download https://esm.sh/assemblyscript@0.20.13?bundle
Download https://esm.sh/v86/assemblyscript@0.20.13/deno/assemblyscript.bundle.js
Download https://deno.land/std@0.146.0/node/buffer.ts
Download https://deno.land/std@0.146.0/node/process.ts
Download https://deno.land/std@0.146.0/node/_buffer.mjs
Download https://deno.land/std@0.146.0/node/_buffer.d.ts
Download https://deno.land/std@0.146.0/_deno_unstable.ts
Download https://deno.land/std@0.146.0/path/mod.ts
Download https://deno.land/std@0.146.0/node/_process/exiting.ts
Download https://deno.land/std@0.146.0/node/_process/process.ts
Download https://deno.land/std@0.146.0/node/_process/streams.mjs
Download https://deno.land/std@0.146.0/node/_utils.ts
Download https://deno.land/std@0.146.0/node/events.ts
Download https://deno.land/std@0.146.0/node/internal/errors.ts
Download https://deno.land/std@0.146.0/node/internal/options.ts
Download https://deno.land/std@0.146.0/node/internal/process/per_thread.mjs
Download https://deno.land/std@0.146.0/node/internal/validators.mjs
Download https://deno.land/std@0.146.0/node/internal_binding/mod.ts
Download https://deno.land/std@0.146.0/encoding/base64.ts
Download https://deno.land/std@0.146.0/encoding/base64url.ts
Download https://deno.land/std@0.146.0/node/internal/buffer.mjs
Download https://deno.land/std@0.146.0/node/internal/error_codes.ts
Download https://deno.land/std@0.146.0/node/internal/util.mjs
Download https://deno.land/std@0.146.0/node/internal/util/types.ts
Download https://deno.land/std@0.146.0/node/internal_binding/_utils.ts
Download https://deno.land/std@0.146.0/node/internal_binding/buffer.ts
Download https://deno.land/std@0.146.0/node/_next_tick.ts
Download https://deno.land/std@0.146.0/node/internal_binding/async_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/cares_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/config.ts
Download https://deno.land/std@0.146.0/node/internal_binding/constants.ts
Download https://deno.land/std@0.146.0/node/internal_binding/contextify.ts
Download https://deno.land/std@0.146.0/node/internal_binding/credentials.ts
Download https://deno.land/std@0.146.0/node/internal_binding/crypto.ts
Download https://deno.land/std@0.146.0/node/internal_binding/errors.ts
Download https://deno.land/std@0.146.0/node/internal_binding/fs.ts
Download https://deno.land/std@0.146.0/node/internal_binding/fs_dir.ts
Download https://deno.land/std@0.146.0/node/internal_binding/fs_event_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/heap_utils.ts
Download https://deno.land/std@0.146.0/node/internal_binding/http_parser.ts
Download https://deno.land/std@0.146.0/node/internal_binding/icu.ts
Download https://deno.land/std@0.146.0/node/internal_binding/inspector.ts
Download https://deno.land/std@0.146.0/node/internal_binding/js_stream.ts
Download https://deno.land/std@0.146.0/node/internal_binding/messaging.ts
Download https://deno.land/std@0.146.0/node/internal_binding/module_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/native_module.ts
Download https://deno.land/std@0.146.0/node/internal_binding/natives.ts
Download https://deno.land/std@0.146.0/node/internal_binding/options.ts
Download https://deno.land/std@0.146.0/node/internal_binding/os.ts
Download https://deno.land/std@0.146.0/node/internal_binding/performance.ts
Download https://deno.land/std@0.146.0/node/internal_binding/pipe_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/process_methods.ts
Download https://deno.land/std@0.146.0/node/internal_binding/report.ts
Download https://deno.land/std@0.146.0/node/internal_binding/serdes.ts
Download https://deno.land/std@0.146.0/node/internal_binding/signal_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/spawn_sync.ts
Download https://deno.land/std@0.146.0/node/internal_binding/stream_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/string_decoder.ts
Download https://deno.land/std@0.146.0/node/internal_binding/symbols.ts
Download https://deno.land/std@0.146.0/node/internal_binding/task_queue.ts
Download https://deno.land/std@0.146.0/node/internal_binding/tcp_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/timers.ts
Download https://deno.land/std@0.146.0/node/internal_binding/tls_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/trace_events.ts
Download https://deno.land/std@0.146.0/node/internal_binding/tty_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/types.ts
Download https://deno.land/std@0.146.0/node/internal_binding/udp_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/url.ts
Download https://deno.land/std@0.146.0/node/internal_binding/util.ts
Download https://deno.land/std@0.146.0/node/internal_binding/uv.ts
Download https://deno.land/std@0.146.0/node/internal_binding/v8.ts
Download https://deno.land/std@0.146.0/node/internal_binding/worker.ts
Download https://deno.land/std@0.146.0/node/internal_binding/zlib.ts
Download https://deno.land/std@0.146.0/node/_events.mjs
Download https://deno.land/std@0.146.0/node/_events.d.ts
Download https://deno.land/std@0.146.0/node/internal/readline/callbacks.mjs
Download https://deno.land/std@0.146.0/node/stream.ts
Download https://deno.land/std@0.146.0/node/_process/stdio.mjs
Download https://deno.land/std@0.146.0/node/internal_binding/node_options.ts
Download https://deno.land/std@0.146.0/node/internal/hide_stack_frames.ts
Download https://deno.land/std@0.146.0/node/internal/normalize_encoding.mjs
Download https://deno.land/std@0.146.0/async/mod.ts
Download https://deno.land/std@0.146.0/streams/conversion.ts
Download https://deno.land/std@0.146.0/testing/asserts.ts
Download https://deno.land/std@0.146.0/node/internal/crypto/_keys.ts
Download https://deno.land/std@0.146.0/bytes/mod.ts
Download https://deno.land/std@0.146.0/node/internal_binding/_node.ts
Download https://deno.land/std@0.146.0/node/_core.ts
Download https://deno.land/std@0.146.0/node/internal/fixed_queue.ts
Download https://deno.land/std@0.146.0/node/internal/util/inspect.mjs
Download https://deno.land/std@0.146.0/node/util.ts
Download https://deno.land/std@0.146.0/node/internal/net.ts
Download https://deno.land/std@0.146.0/node/internal_binding/ares.ts
Download https://deno.land/std@0.146.0/node/internal_binding/_timingSafeEqual.ts
Download https://deno.land/std@0.146.0/node/internal_binding/_listen.ts
Download https://deno.land/std@0.146.0/node/internal_binding/connection_wrap.ts
Download https://deno.land/std@0.146.0/node/internal_binding/handle_wrap.ts
Download https://deno.land/std@0.146.0/node/internal/crypto/constants.ts
Download https://deno.land/std@0.146.0/flags/mod.ts
Download https://deno.land/std@0.146.0/node/internal/readline/utils.mjs
Download https://deno.land/std@0.146.0/async/abortable.ts
Download https://deno.land/std@0.146.0/async/deadline.ts
Download https://deno.land/std@0.146.0/async/debounce.ts
Download https://deno.land/std@0.146.0/async/deferred.ts
Download https://deno.land/std@0.146.0/async/delay.ts
Download https://deno.land/std@0.146.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.146.0/async/pool.ts
Download https://deno.land/std@0.146.0/async/tee.ts
Download https://deno.land/std@0.146.0/node/_stream.mjs
Download https://deno.land/std@0.146.0/node/_stream.d.ts
Download https://deno.land/std@0.146.0/bytes/equals.ts
Download https://deno.land/std@0.146.0/node/_util/_util_callbackify.ts
Download https://deno.land/std@0.146.0/node/internal/util/comparisons.ts
Download https://deno.land/std@0.146.0/node/internal/util/debuglog.ts
Download https://deno.land/std@0.146.0/node/util/types.ts
Download https://deno.land/std@0.146.0/node/internal_binding/node_file.ts
Download https://deno.land/std@0.146.0/node/internal_binding/_libuv_winerror.ts
Download https://deno.land/std@0.146.0/io/buffer.ts
Download https://deno.land/std@0.146.0/node/internal/streams/_utils.ts
Download https://deno.land/std@0.146.0/node/internal/streams/add-abort-signal.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/compose.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/destroy.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/duplex.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/end-of-stream.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/legacy.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/passthrough.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/pipeline.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/readable.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/transform.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/utils.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/writable.mjs
Download https://deno.land/std@0.146.0/node/stream/promises.mjs
Download https://deno.land/std@0.146.0/fmt/printf.ts
Download https://deno.land/std@0.146.0/node/internal_binding/_winerror.ts
Download https://deno.land/std@0.146.0/node/_global.d.ts
Download https://deno.land/std@0.146.0/bytes/bytes_list.ts
Download https://deno.land/std@0.146.0/io/types.d.ts
Download https://deno.land/std@0.146.0/node/internal/blob.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/from.mjs
Download https://deno.land/std@0.146.0/node/string_decoder.ts
Download https://deno.land/std@0.146.0/node/internal/streams/buffer_list.mjs
Download https://deno.land/std@0.146.0/node/internal/streams/state.mjs
error: Remote modules are not allowed to import local modules. Consider using a dynamic import instead.
  Importing: types:assemblyscript/src/ast
    at https://esm.sh/assemblyscript@0.20.13/dist/assemblyscript.generated.d.ts:7600:19
```

**Comment by NekoMaru76** [comment]
I am using the lastest deno version. Should I open this issue in esm.sh repo instead?

**Comment by NekoMaru76** [comment]
Fixed after reinstalling deno.

**Comment by NekoMaru76** [comment]
Deno cache acts strange, I tried to cache `https://esm.sh/@assemblyscript/loader` after I successfully cached `https://esm.sh/assemblyscript`, and it gives the old error.
```sh
$ deno cache https://esm.sh/@assemblyscript/loader@0.20.13
Download https://esm.sh/@assemblyscript/loader@0.20.13
Download https://esm.sh/v86/@assemblyscript/loader@0.20.13/deno/loader.js
Download https://esm.sh/v86/@assemblyscript/loader@0.20.13/index.d.ts
error: Remote modules are not allowed to import local modules. Consider using a dynamic import instead.
  Importing: types:assemblyscript/src/ast
    at https://esm.sh/assemblyscript@0.20.13/dist/assemblyscript.generated.d.ts:7600:19
```
And it also gives same error if I tried to cache other mod.
```sh
$ deno cache https://esm.sh/chevrotain@10.1.2
error: Remote modules are not allowed to import local modules. Consider using a dynamic import instead.
  Importing: types:assemblyscript/src/ast
    at https://esm.sh/assemblyscript@0.20.13/dist/assemblyscript.generated.d.ts:7600:19
[gaia@Tsu Methemetics]$ deno cache https://esm.sh/chevrotain@10.1.2 --reload
Download https://esm.sh/chevrotain@10.1.2
Download https://esm.sh/assemblyscript@0.20.13/dist/assemblyscript.generated.d.ts
Download https://esm.sh/v86/chevrotain@10.1.2/deno/chevrotain.js
Download https://esm.sh/v86/chevrotain@10.1.2/chevrotain.d.ts
Download https://esm.sh/v86/@chevrotain/types@10.1.2/api.d.ts
Download https://esm.sh/v86/@chevrotain/cst-dts-gen@10.1.2/deno/cst-dts-gen.js
Download https://esm.sh/v86/@chevrotain/gast@10.1.2/deno/gast.js
Download https://esm.sh/v86/@chevrotain/utils@10.1.2/deno/utils.js
Download https://esm.sh/v86/lodash@4.17.21/deno/assign.js
Download https://esm.sh/v86/lodash@4.17.21/deno/clone.js
Download https://esm.sh/v86/lodash@4.17.21/deno/compact.js
Download https://esm.sh/v86/lodash@4.17.21/deno/defaults.js
Download https://esm.sh/v86/lodash@4.17.21/deno/difference.js
Download https://esm.sh/v86/lodash@4.17.21/deno/drop.js
Download https://esm.sh/v86/lodash@4.17.21/deno/dropRight.js
Download https://esm.sh/v86/lodash@4.17.21/deno/every.js
Download https://esm.sh/v86/lodash@4.17.21/deno/filter.js
Download https://esm.sh/v86/lodash@4.17.21/deno/find.js
Download https://esm.sh/v86/lodash@4.17.21/deno/first.js
Download https://esm.sh/v86/lodash@4.17.21/deno/flatMap.js
Download https://esm.sh/v86/lodash@4.17.21/deno/flatten.js
Download https://esm.sh/v86/lodash@4.17.21/deno/forEach.js
Download https://esm.sh/v86/lodash@4.17.21/deno/groupBy.js
Download https://esm.sh/v86/lodash@4.17.21/deno/has.js
Download https://esm.sh/v86/lodash@4.17.21/deno/identity.js
Download https://esm.sh/v86/lodash@4.17.21/deno/includes.js
Download https://esm.sh/v86/lodash@4.17.21/deno/indexOf.js
Download https://esm.sh/v86/lodash@4.17.21/deno/isArray.js
Download https://esm.sh/v86/lodash@4.17.21/deno/isEmpty.js
Download https://esm.sh/v86/lodash@4.17.21/deno/isFunction.js
Download https://esm.sh/v86/lodash@4.17.21/deno/isObject.js
Download https://esm.sh/v86/lodash@4.17.21/deno/isRegExp.js
Download https://esm.sh/v86/lodash@4.17.21/deno/isString.js
Download https://esm.sh/v86/lodash@4.17.21/deno/isUndefined.js
Download https://esm.sh/v86/lodash@4.17.21/deno/keys.js
Download https://esm.sh/v86/lodash@4.17.21/deno/last.js
Download https://esm.sh/v86/lodash@4.17.21/deno/map.js
Download https://esm.sh/v86/lodash@4.17.21/deno/noop.js
Download https://esm.sh/v86/lodash@4.17.21/deno/pickBy.js
Download https://esm.sh/v86/lodash@4.17.21/deno/reduce.js
Download https://esm.sh/v86/lodash@4.17.21/deno/reject.js
Download https://esm.sh/v86/lodash@4.17.21/deno/some.js
Download https://esm.sh/v86/lodash@4.17.21/deno/uniq.js
Download https://esm.sh/v86/lodash@4.17.21/deno/values.js
Download https://esm.sh/v86/regexp-to-ast@0.5.0/deno/regexp-to-ast.js
Download https://esm.sh/v86/lodash@4.17.21/deno/upperFirst.js
error: Remote modules are not allowed to import local modules. Consider using a dynamic import instead.
  Importing: types:assemblyscript/src/ast
    at https://esm.sh/assemblyscript@0.20.13/dist/assemblyscript.generated.d.ts:7600:19
```
