### ISSUE TITLE
Deno has panicked - ext/http/lib.rs

### ISSUE THREAD

**Issue by sant123** [denoland/deno#15107]
``` 
============================================================                                                                                                                           
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.23.3                              
Args: ["/home/sant821/.deno/bin/deno", "run", "--allow-net", "--allow-write", "server.ts"]

thread 'main' panicked at 'internal error: entered unreachable code', ext/http/lib.rs:561:10
stack backtrace:                             
   0:     0x559a18f12f1d - std::backtrace_rs::backtrace::libunwind::trace::hb729d9642bb971eb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x559a18f12f1d - std::backtrace_rs::backtrace::trace_unsynchronized::h373bb774579df5c7
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559a18f12f1d - std::sys_common::backtrace::_print_fmt::hfbd4e92d240c89bb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x559a18f12f1d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f618991fbf64972
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x559a18f3d91c - core::fmt::write::hc69b5b640d88cce8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:     0x559a18f0a681 - std::io::Write::write_fmt::h3403cef06a24a303
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:     0x559a18f14c85 - std::sys_common::backtrace::_print::h368f27cdedea0e52
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x559a18f14c85 - std::sys_common::backtrace::print::ha105c9cf5a64cd17
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x559a18f14c85 - std::panicking::default_hook::{{closure}}::h48ed2c3707d5e20e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:     0x559a18f148f9 - std::panicking::default_hook::h8744fc5cea5e3110
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:     0x559a1926173a - deno::setup_panic_hook::{{closure}}::hd56719706f0c976e
  11:     0x559a18f15416 - std::panicking::rust_panic_with_hook::hc82286af2030e925
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:702:17
  12:     0x559a18f151d9 - std::panicking::begin_panic_handler::{{closure}}::h1c15057c2f09081f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:586:13
  13:     0x559a18f133d4 - std::sys_common::backtrace::__rust_end_short_backtrace::h65de906a5330f8da
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x559a18f14f49 - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  15:     0x559a18f3b003 - core::panicking::panic_fmt::h741cfbfc95bc6112
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  16:     0x559a18f3ae4d - core::panicking::panic::hab046c3856b52f65
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:48:5
  17:     0x559a19c947e8 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h02dee94591c62860
  18:     0x559a180a2e25 - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
                               at ./../../../../v8/src/api/api-arguments-inl.h:147:3
  19:     0x559a180a290a - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20Function
TemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE                                           
                               at ./../../../../v8/src/builtins/builtins-api.cc:114:36
  20:     0x559a180a1d66 - _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
                               at ./../../../../v8/src/builtins/builtins-api.cc:132:1
  21:     0x559a18e0d7f8 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
```

**Comment by sant123** [comment]
This is my file in case you need it:

``` ts
import { serve } from "https://deno.land/std@0.147.0/http/server.ts";

serve(async (request) => {
  if (request.method !== 'POST') {
    return new Response(`Error: POST method expected, ${request.method} recieved`, { status: 400 });
  }

  try {
    const form = await request.formData();
    const SAMLResponse = form.get('SAMLResponse')?.toString();

    if (!SAMLResponse) {
      console.log('SAMLResponse field is empty or not exists');
      return new Response('', { status: 400 });
    }

    Deno.writeTextFile('saml-response.txt', encodeURIComponent(SAMLResponse), { mode: 0o600 });
    console.log('Got SAMLResponse field and saved it to the saml-response.txt file');
    return new Response('Got SAMLResponse field, it is now safe to close this window\n');
  } catch (error) {
    return new Response(`ParseForm() err: ${error}`, { status: 400 });
  }
}, {
  onListen({ port }) {
    console.log('Starting HTTP server at http://127.0.0.1:%d', port);
  },
  port: 35001,
});
```

Thank you so much!

**Comment by cjihrig** [comment]
I can reproduce this on macOS with v1.23.3 using the following command:

```sh
curl -d "SAMLResponse=foo" -X POST http://127.0.0.1:35001
```

However, I cannot reproduce this with the current `main` branch.

**Comment by hwcwy** [comment]
The following code will also cause the same situation in Deno v1.23.3:
```typescript
const listener: Deno.Listener = Deno.listen({ port: 2333 });
console.log("running");

for await (const conn of listener) router(conn);

async function router(conn) {
  const httpConn = Deno.serveHttp(conn);
  for await (const requestEvent of httpConn) {
    const { request } = requestEvent;
    request.json();
    console.log(request);
  }
}

```

**Comment by brendantang** [comment]
Getting the same error playing with a Fresh project:

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.23.3
Args: ["/opt/homebrew/bin/deno", "run", "-A", "--watch=static/,routes/", "dev.ts"]

thread 'main' panicked at 'internal error: entered unreachable code', ext/http/lib.rs:561:10
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Here is the endpoint causing the panic:

```
/** @jsx h */
import { h } from "preact";
import { Handlers } from "$fresh/server.ts";

export const handler: Handlers = {
  async POST(req: Request, ctx) {
    const formData = await req.formData(); // This is the problematic line
    return new Response(formData);
  },
};
```

Only seems to happen with the call to Request.formData(). If I change that line to `req.text()` or `req.json()` it doesn't panic.

Hope this helps, and thanks for all your hard work.

**Comment by maruichilab** [comment]
I face to the same problem too.
I fixed it as follows and it worked.

```ts
export const handler: Handlers = {
  async POST(req: Request, ctx) {
    const headers = req.headers; // here!
    const formData = await req.formData();
    return new Response(formData);
  },
};
```

I am posting this thread in the hope that it will be helpful to you as you make your corrections.

**Comment by dbushell** [comment]
Similar to the above comment though `req.text()` was panicking for me.
```js
const headers = req.headers; // "fixed" the panic
const text = await req.text();
```
