### ISSUE TITLE
[BUG] thread 'main' panicked at 'internal error: entered unreachable code', ext/http/lib.rs:561:10

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#15150]
```ts
import { serve } from "https://deno.land/std@0.147.0/http/server.ts";

async function handler(req: Request): Response {
  // OK
  // console.log(req, await req.clone().text());
  
  // OK
  // console.log(req);
  // console.log(await req.text());

  // thread 'main' panicked at 'internal error: entered unreachable code', ext/http/lib.rs:561:10
  console.log(req, await req.text());
  return new Response("Hello, World!");
}

serve(handler);
```

**Comment by bartlomieju** [comment]
CC @littledivy please take a look

**Comment by cjihrig** [comment]
This looks very similar to https://github.com/denoland/deno/issues/15107. Possible duplicate.

**Comment by hironichu** [comment]
Yep seems to be the same issue !

**Comment by cjihrig** [comment]
I'll close this as a dupe then so we can track everything in #15107. Thanks!
