### ISSUE TITLE
TypeError: The stream controller cannot close or enqueue.

### ISSUE THREAD

**Issue by harshmangalam** [denoland/deno#15203]
```ts

return new ReadableStream({
  async pull(controller) {
    const chunk = new Uint8Array(blockSize);
    try {
      const read = await video.read(chunk);
      if (read) {
        controller.enqueue(chunk.subarray(0, read));
      }

      readBlocks--;
      if (readBlocks === 0) {
        video.close();
        controller.close();
      }
    } catch (e) {
      console.log(e);
      controller.error(e);
      video.close();
    }
  },
});



```

TypeError: The stream controller cannot close or enqueue.
    at ReadableStreamDefaultController.enqueue (deno:ext/web/06_streams.js:5107:15)

**Comment by lucacasonato** [comment]
This is not a reproducible example. Your readable stream may be closed when you are trying to enqueue.

Please submit an example that I can run _as is_. Also, what Deno version is this?

**Comment by iacore** [comment]
Encountered the same error when running `express` (http server) in Deno. When the browser refreshes while loading a page, the server breaks.

```
error: Uncaught TypeError: The stream controller cannot close or enqueue.
    at ReadableStreamDefaultController.enqueue (ext:deno_web/06_streams.js:5606:13)
    at Function.#enqueue (ext:deno_node/http.ts:987:24)
    at ServerResponse.write [as _write] (ext:deno_node/http.ts:1016:40)
    at writeOrBuffer (ext:deno_node/_stream.mjs:3948:16)
    at _write (ext:deno_node/_stream.mjs:3893:14)
    at ServerResponse.Writable.write (ext:deno_node/_stream.mjs:3896:14)
    at ReadStream.ondata (ext:deno_node/_stream.mjs:3180:26)
    at ReadStream.emit (ext:deno_node/_stream.mjs:1852:9)
    at addChunk (ext:deno_node/_stream.mjs:2874:16)
    at readableAddChunk (ext:deno_node/_stream.mjs:2853:13)
```

**Comment by bartlomieju** [comment]
@crowlKats please take a look

**Comment by crowlKats** [comment]
seems overall an architectural issue of the setup. can't really see what the issue is, however this shouldnt be using web streams at all. ServerResponse should be rewritten.

**Comment by iacore** [comment]
I can't recreate the setup. It has something to do with `express` and Node.js.

**Comment by crowlKats** [comment]
sorry, bad wording on my end: I meant with our setup/logic for the node http server

**Comment by iacore** [comment]
Maybe this issue can be closed? So far we have no reproducible example.

**Comment by firecakes** [comment]
I have a reproducible example that can be run in both Deno and Node.js, see attached.

What I am doing is different. I'm trying to have the client request a large file as a blob to the server, which then returns a readable stream using the "node:fs" package to a zip file that then can be downloaded by the client. If the client refreshes the page before it receives the file, the server crashes on Deno (it is easier to hit refresh if the zip file is larger, I had to shorten it so it could be sent as an attachment):

```
error: Uncaught (in promise) TypeError: The stream controller cannot close or enqueue.
    at ReadableStreamDefaultController.enqueue (ext:deno_web/06_streams.js:6055:13)
    at Function.#enqueue (node:http:1038:18)
    at ServerResponse.write [as _write] (node:http:1067:32)
    at writeOrBuffer (ext:deno_node/_stream.mjs:3950:16)
    at _write (ext:deno_node/_stream.mjs:3895:14)
    at ServerResponse.Writable.write (ext:deno_node/_stream.mjs:3898:14)
    at ReadStream.ondata (ext:deno_node/_stream.mjs:3182:26)
    at ReadStream.emit (ext:deno_node/_stream.mjs:1854:9)
    at addChunk (ext:deno_node/_stream.mjs:2876:16)
    at readableAddChunk (ext:deno_node/_stream.mjs:2855:13)

```

In contrast, when running as a Node program, it errors one of two messages but does not crash the server:

```
  Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

```
  Error: write ECONNRESET
      at afterWriteDispatched (node:internal/stream_base_commons:160:15)
      at writevGeneric (node:internal/stream_base_commons:143:3)
      at Socket._writeGeneric (node:net:815:11)
      at Socket._writev (node:net:824:8)
      at doWrite (node:internal/streams/writable:406:12)
      at clearBuffer (node:internal/streams/writable:561:5)
      at Socket.Writable.uncork (node:internal/streams/writable:348:7)
      at connectionCorkNT (node:_http_outgoing:797:8)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Instructions in `server.js`, but after running as Deno or Node program you go to `http://localhost:8000/testing.html` to click on the export button on the page that starts the read stream on the server.

[deno-test.zip](https://github.com/denoland/deno/files/14074398/deno-test.zip)

**Comment by jiv-e** [comment]
I'm not sure if this is exactly the same problem, but here's another reproduction example.

[deno-stream-not-closing.zip](https://github.com/denoland/deno/files/14857860/deno-stream-not-closing.zip)

## Instructions
1. Extract the .zip file to a folder.
2. Open a terminal in the folder.

### Node.js
Ensure you have Node.js installed. Tested on: Node version 18.16.0.

3. Run: npm install
4. Run: node server.mjs
5. Check that the serve is starting normally.
6. Open another terminal window and run: curl localhost:8080/stream
7. Check that the stream is working. It should print out multiple data:{"chunk": <number>} lines.
8. Close the connection by pressing CTRL+C.
9. Check that the first terminal displays: Stream closed.

### Deno
Ensure you have Deno installed. Tested on: deno 1.42.1 (release, x86_64-apple-darwin)

10. In the same terminal, run: demo run server.ts
11. Check that the serve is starting normally.
12. Open another terminal window and run: curl localhost:8080/stream
13. Check that the stream is working. It should print out multiple data:{"chunk": <number>} lines.
14. Close the connection by pressing CTRL+C.

## What should happen?
I should see "Stream closed." on the first terminal and server should still be running.

## What actually happens?
I see an error and the server process is terminated:
```
error: Uncaught TypeError: The stream controller cannot close or enqueue.
    at ReadableStreamDefaultController.enqueue (ext:deno_web/06_streams.js:6053:13)
    at Function.#enqueue (node:http:1039:18)
    at ServerResponse.write [as _write] (node:http:1072:32)
    at writeOrBuffer (ext:deno_node/_stream.mjs:3950:16)
    at _write (ext:deno_node/_stream.mjs:3895:14)
    at ServerResponse.Writable.write (ext:deno_node/_stream.mjs:3898:14)
    at file:///Users/jiv/Projects/raksatuote/proto/repro/server.ts:16:9
    at eventLoopTick (ext:core/01_core.js:203:13)
```

**Comment by lucacasonato** [comment]
For the node compat issue, closing as duplicate of #22820.

For the original issue, the code provided is correct. If the user closes the HTTP request, the response stream will be closed.
