### ISSUE TITLE
`promise` and `reason` missing in `unhandledrejection` event type

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#15270]
If the unhandledrejection example from the blog post is run in TypeScript, there are some type errors:

```ts
globalThis.addEventListener("unhandledrejection", (e) => {
    console.log("unhandled rejection at:", e.promise, "reason:", e.reason);
    e.preventDefault();
  });
```

```
deno check .\unhandledrejection.ts
Check file:///C:/Users/GJZwiers/repos/deno_deno/unhandledrejection.ts
error: TS2339 [ERROR]: Property 'promise' does not exist on type 'Event'.
    console.log("unhandled rejection at:", e.promise, "reason:", e.reason);
                                             ~~~~~~~
    at file:///C:/Users/GJZwiers/repos/deno_deno/unhandledrejection.ts:3:46

TS2339 [ERROR]: Property 'reason' does not exist on type 'Event'.
    console.log("unhandled rejection at:", e.promise, "reason:", e.reason);
                                                                   ~~~~~~
    at file:///C:/Users/GJZwiers/repos/deno_deno/unhandledrejection.ts:3:68

Found 2 errors.
```

Deno v1.24.0

**Comment by bartlomieju** [comment]
Really strange, I explicitly added these typings in https://github.com/denoland/deno/commit/d53936eb7d3fe4cda8e06f7310e4c8f12702b413#diff-3a1d49a3c5b727a871162db69f39667764ea922b92906677961b6ea43a5ee42aR408

**Comment by GJZwiers** [comment]
Looks likes the types exist on `PromiseRejectionEvent` but not on `Event` itself, which is the type of `e` in the handler.

**Comment by bartlomieju** [comment]
You're right, I did miss typing, this should be fixed by https://github.com/denoland/deno/pull/15271
