### ISSUE TITLE
`Deno.spawn` cannot find 'Write-Output' program

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#15308]
```ts
Deno.spawnSync("Write-Output", {
    args: [ "hello" ],
    stdout: "inherit"
});
```

```pwsh
deno run --unstable spawn.ts

⚠️  ️Deno requests run access to "Write-Output". Run again with --allow-run to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
error: Uncaught NotFound: program not found
Deno.spawnSync("Write-Output", {
     ^
    at Object.opSync (deno:core/01_core.js:170:12)
    at Object.spawnSync (deno:runtime/js/40_spawn.js:244:25)
    at file:///C:/Users/GJZwiers/repos/deno-init/spawn.ts:1:6
```

The same goes for `echo` which is an alias for Write-Output on Windows. 

``` 
deno --version

deno 1.24.0+4e71a94 (canary, x86_64-pc-windows-msvc)
v8 10.4.132.20
typescript 4.7.4
```

**Comment by AnInternetTroll** [comment]
Both `echo` and `Write-Output` are a part of the shell, in your case powershell. As such you need the following I think

```js
Deno.spawnSync("pwsh", {
    args: [ "/c", "echo", "hello" ],
    stdout: "inherit"
});
```

**Comment by GJZwiers** [comment]
Thanks, that works! I was a bit confused on having to invoke the shell because with e.g. a `git` command it is not needed to do that.
