### ISSUE TITLE
(WebSocketStream) Error: IO error: unexpected end of file

### ISSUE THREAD

**Issue by tavindev** [denoland/deno#15302]
Getting this error with WebSocketStream after a while.

The error:
```
error: Uncaught (in promise) Error: IO error: unexpected end of file
    at pull (deno:ext/websocket/02_websocketstream.js:264:33)
    at async pull (deno:ext/websocket/02_websocketstream.js:254:21)
    at async Object.pull (deno:ext/websocket/02_websocketstream.js:254:21)
```

The code: 
```typescript
let writer: WritableStreamDefaultWriter<string | Uint8Array>;
let reader: ReadableStreamDefaultReader<string | Uint8Array>;

async function handleData(
    writer: WritableStreamDefaultWriter<string | Uint8Array>,
    reader: ReadableStreamDefaultReader<string | Uint8Array>
) {
    writer.ready.then(() => {
        console.log("connection established!");
        writer.write(
            JSON.stringify({
                type: "connection_init",
            })
        );
    });
    while (true) {
        const { value, done } = await reader.read();

        if (done) {
            console.log("reader is done");
            break;
        }
        console.log(`Received message: ${value}`);
    }
}

const connectWs = async () => {
        const rollWebsocket = new WebSocketStream(
            "wss://api.csgoroll.com/graphql",
            {
                protocols: ["graphql-transport-ws"],
                headers: {
                    "User-Agent":
                        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "en-US,en;q=0.5",
                    Pragma: "no-cache",
                    "Cache-Control": "no-cache",
                    origin: "https://www.csgoroll.com",
                    cookie: `session=${config.session}`,
                },
            }
        );

        const { writable, readable } = (await rollWebsocket.connection) as {
            writable: WritableStream<string | Uint8Array>;
            readable: ReadableStream<string | Uint8Array>;
        };

        reader = readable.getReader();
        writer = writable.getWriter();

        await handleData(writer, reader);

        rollWebsocket.closed.then((err) => {
            console.log("reconnecting...");
            connectWs();
        });
};

setInterval(() => {
    console.log("pinging");
    writer.write(
        JSON.stringify({
            type: "ping",
        })
    );
}, 30_000);
```

**Comment by kitsonk** [comment]
This can often happen when the other side drops the connection uncleanly. What leads you to believe it is an issue?

**Comment by tavindev** [comment]
You are right! The server closes the connection after some time. I was a little too hasty on this one 😆. Closing!

**Comment by Chznrl** [comment]
i see u set a session cookie. where did u get it from

**Comment by ClydexGG** [comment]
i'm struggling to connect via python, i need some guidance, i also get 403 forbidden... contact my twitter @ClydexLT if you can help
