### ISSUE TITLE
deno can not be built under node_modules folder.

### ISSUE THREAD

**Issue by caijw** [denoland/deno#1536]
when using `tools/build.py` to build `deno`, if `deno` is under a `node_modules` folder, it can not work.
```
/Users/jingweicai/Documents/code/node_modules/deno/tools/ts_library_builder/main.ts:1
(function (exports, require, module, __filename, __dirname) { import * as path from "path";
                                                                     ^

SyntaxError: Unexpected token *
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/jingweicai/Documents/code/node_modules/deno/third_party/node_modules/ts-node/src/index.ts:431:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
[322/540] ACTION //build_extra/rust:unicode_segmentation_rustc(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
```
And i figure out it is because:
`ts-node`  won't compile code under `node_modules` folder.
see the `ts-node` issue: https://github.com/TypeStrong/ts-node/issues/505#issuecomment-356774721
When generating the compiled code `gen/lib/lib.deno_runtime.d.ts`, this error hanppens.
I open  this issue to remind others not to put `deno` under any `node_modules` folder.

**Comment by caijw** [comment]
https://github.com/denoland/deno/pull/1555

Adding a ts-node cli option can fix this.
