### ISSUE TITLE
Running an install script fails on deno run with compat, unstable and -A

### ISSUE THREAD

**Issue by renhiyama** [denoland/deno#15395]
```
$ RUST_BACKTRACE=1 deno run -A --compat --unstable https://raw.githubusercontent.com/rovelstars/reejs/master/install.js

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.23.3
Args: ["deno", "run", "-A", "--compat", "--unstable", "https://raw.githubusercontent.com/rovelstars/reejs/master/install.js"]

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"https"`,
 right: `"file"`', cli/main.rs:1062:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: deno::run_command::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: deno::main::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: deno_runtime::tokio_util::run_basic
   9: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by renhiyama** [comment]
How should it be running properly?
```sh
curl -s https://raw.githubusercontent.com/rovelstars/reejs/master/install.js | node
```

(was testing this install script on deno)

**Comment by bartlomieju** [comment]
I'm going to close this issue as --compat mode was removed. Please use `npm:` specifiers in your code instead.
