### ISSUE TITLE
`deno run --watch` panics when handling error

### ISSUE THREAD

**Issue by kidonng** [denoland/deno#15428]
Pardon me for not able to provide a reproduce without dependencies, but I believe this is a Deno bug as it should be able to handle errors gracefully.

Given the following Telegram bot program:

```js
// test.ts
import {Bot} from 'https://deno.land/x/grammy@v1.8.3/mod.ts'
import {Octokit} from 'https://esm.sh/@octokit/rest@19.0.3'

new Octokit() // Without this there's no error, can't comprehend

const bot = new Bot(Deno.env.get('BOT_TOKEN'))

bot.command('test', (ctx) => {
	ctx.reply(does_not_exist) // This triggers an error
})

bot.start()
```

Run it, send a `/test` command to the bot, the program errored out:

```shellsession
$ deno run -A ./test.ts
Error in middleware while handling update 148195597 ReferenceError: does_not_exist is not defined
    at file:///workspaces/qvrelease-bot/test.ts:9:12
    at https://deno.land/x/grammy@v1.8.3/composer.ts:125:41
    at https://deno.land/x/grammy@v1.8.3/composer.ts:125:41
    at https://deno.land/x/grammy@v1.8.3/composer.ts:677:48
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:136:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:133:9
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:677:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:136:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:133:9
    at async run (https://deno.land/x/grammy@v1.8.3/composer.ts:155:5)
No error handler was set!
Set your own error handler with `bot.catch = ...`
Stopping bot
error: Uncaught BotError: ReferenceError in middleware: does_not_exist is not defined
```

But when running it with `--watch`, Deno will panic when the error is triggerd:

```shellsession
$ deno run --watch -A ./test.ts
Watcher Process started.
Error in middleware while handling update 148195598 ReferenceError: does_not_exist is not defined
    at file:///workspaces/qvrelease-bot/test.ts:9:12
    at https://deno.land/x/grammy@v1.8.3/composer.ts:125:41
    at https://deno.land/x/grammy@v1.8.3/composer.ts:125:41
    at https://deno.land/x/grammy@v1.8.3/composer.ts:677:48
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:136:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:133:9
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:677:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:136:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:133:9
    at async run (https://deno.land/x/grammy@v1.8.3/composer.ts:155:5)
No error handler was set!
Set your own error handler with `bot.catch = ...`
Stopping bot

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.24.2
Args: ["deno", "run", "--watch", "-A", "./test.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Uncaught Error: execution terminated', cli/main.rs:983:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bartlomieju** [comment]
@nayeemrmn feels like this problem is similar to https://github.com/denoland/deno/commit/a74b2ecf379ddb1ff03c61d4e876153d7b4c45d2, any ideas how to tackle that?

**Comment by nayeemrmn** [comment]
We should just remove the unwrap at https://github.com/denoland/deno/blob/50fc5d169aec43b4cc0c4ff08a8073bca99c18f4/cli/worker.rs#L153-L163 It's not tolerant of user errors.
