### ISSUE TITLE
`Deno.stdin.close()` should end `Deno.stdin.read()` promises

### ISSUE THREAD

**Issue by andykais** [denoland/deno#15479]
The following snippet illustrates what I am referring to:
```ts
const buffer = new Uint8Array(1024)
const promise = Deno.stdin.read(buffer)

setTimeout(() => { Deno.stdin.close() })
await promise
```

this snippet will hang indefinitely even though the stdin resource has been closed. For the most part, this does not matter, but when used along with `setRaw`, then it becomes an issue:
```ts
const buffer = new Uint8Array(1024)
Deno.setRaw(Deno.stdin.rid, true)
const promise = Deno.stdin.read(buffer)

setTimeout(() => {
  Deno.setRaw(Deno.stdin.rid, false)
  Deno.stdin.close()
})
await promise
```
this will give the following error:
```
error: Uncaught (in promise) Busy: Resource is unavailable because it is in use by a promise
  Deno.setRaw(reader.rid, false);
       ^
    at Object.opSync (deno:core/01_core.js:170:12)
    at Object.setRaw (deno:runtime/js/40_tty.js:21:10)
```

and attempting to setRaw after closing stdin gives the following error:
```
error: Uncaught (in promise) BadResource: Bad resource ID
  Deno.setRaw(reader.rid, false);
       ^
    at Object.opSync (deno:core/01_core.js:170:12)
    at Object.setRaw (deno:runtime/js/40_tty.js:21:10)
```

so effectively there isnt a great way to close stdin here besides waiting for user input and _then_ closing the reader

**Comment by andykais** [comment]
related: https://github.com/dmitriytat/keypress/issues/6

**Comment by rottenpen** [comment]
in this case, settimeout's callback will run before promise resolve，this is a race condition.

**Comment by bartlomieju** [comment]
Seems like a bug, all reads on a resource should throw an error when the underlying resource is closed.

**Comment by rottenpen** [comment]
> Seems like a bug, all reads on a resource should throw an error when the underlying resource is closed.

you means in this case , run `Deno.setRaw` after closed will throw `resource is closed `？

**Comment by bartlomieju** [comment]
> > Seems like a bug, all reads on a resource should throw an error when the underlying resource is closed.
> 
> you means in this case , run `Deno.setRaw` after closed will throw `resource is closed ` instead of `Bad resource ID`？

No, the error will always be `Bad resource ID`

**Comment by sigmaSd** [comment]
The problem is deno uses sync reads https://github.com/denoland/deno/blob/main/runtime/ops/io.rs#L687 which is just a wrapper over rust std read, std read have no guarantees on blocking

Maye its possible to try to detect that here:
```ts
tokio::select
_ => read
_ => check_if_we_closed
```
But don't know how can that be implemented, and what the performance impact if possible

**Comment by gtarsia** [comment]
I really want to use deno, but things like this or the lack of control of sockets makes it really difficult for lower level cases.
I'm very grateful for the work the deno team did, but I can't use it for a simple term editor.

**Comment by bartlomieju** [comment]
Verified this is fixed on the latest canary (2.8.2+2655d44), so closing.

Close while a read is pending (pipe stdin): the read promise no longer hangs, it rejects promptly with `Interrupted: operation canceled` as soon as `Deno.stdin.close()` runs, which is the behavior discussed above (reads error out when the underlying resource is closed).

Raw mode variant under a real PTY (tested with the modern `Deno.stdin.setRaw()` API, since `Deno.setRaw(rid)` was removed in Deno 2.0):

```
isTerminal: true
setRaw(false) ok        <- was: Busy: Resource is unavailable because it is in use by a promise
close ok
read rejected: Interrupted - operation canceled   <- was: hang
```

`setRaw(false)` no longer throws `Busy` while a read is pending, `close()` works, and the pending read settles with a catchable error. The `BadResource` complaint (calling `setRaw` after close) is moot since the natural order, `setRaw(false)` then `close()`, now works. The original use case of a terminal app canceling a pending stdin read is unblocked.
