### ISSUE TITLE
Panic when `chdir`ing to a non-existent parent directory

### ISSUE THREAD

**Issue by TheLastZombie** [denoland/deno#15501]
Example code to reproduce:

```JS
const directory = Deno.cwd();

await Deno.mkdir("parent/child", { recursive: true });
Deno.chdir("parent/child");

await Deno.remove(directory + "/parent", { recursive: true });
Deno.chdir("..");
```

<details>

<summary>Output of <code>RUST_BACKTRACE=1 deno run --allow-read --allow-write mod.ts</code></summary>

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.24.3
Args: ["/home/eric/.asdf/installs/deno/1.24.3/bin/deno", "run", "--allow-read", "--allow-write", "mod.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to get current working directory

Caused by:
    No such file or directory (os error 2)', runtime/permissions.rs:1448:46
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: deno_runtime::permissions::resolved_and_display_path
   4: deno_runtime::permissions::UnaryPermission<deno_runtime::permissions::ReadDescriptor>::check
   5: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
   6: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
             at ./../../../../v8/src/api/api-arguments-inl.h:147:3
   7: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
             at ./../../../../v8/src/builtins/builtins-api.cc:114:36
   8: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
             at ./../../../../v8/src/builtins/builtins-api.cc:132:1
   9: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

<details>

<summary>Output of <code>RUST_BACKTRACE=full deno run --allow-read --allow-write mod.ts</code></summary>

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.24.3
Args: ["/home/eric/.asdf/installs/deno/1.24.3/bin/deno", "run", "--allow-read", "--allow-write", "mod.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to get current working directory

Caused by:
    No such file or directory (os error 2)', runtime/permissions.rs:1448:46
stack backtrace:
   0:     0x557fbfd83fed - std::backtrace_rs::backtrace::libunwind::trace::h8e036432725b1c57
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557fbfd83fed - std::backtrace_rs::backtrace::trace_unsynchronized::h4f83092254c85869
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557fbfd83fed - std::sys_common::backtrace::_print_fmt::h9728b5e056a3ece3
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x557fbfd83fed - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h48bb4bd2928827d2
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x557fbfdaf03c - core::fmt::write::h909e69a2c24f44cc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/fmt/mod.rs:1196:17
   5:     0x557fbfd7b7a1 - std::io::Write::write_fmt::h7f4b8ab8af89e9ef
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/io/mod.rs:1654:15
   6:     0x557fbfd85d35 - std::sys_common::backtrace::_print::hff4838ebf14a2171
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x557fbfd85d35 - std::sys_common::backtrace::print::h2499280374189ad9
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x557fbfd85d35 - std::panicking::default_hook::{{closure}}::h8b270fc55eeb284e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:295:22
   9:     0x557fbfd859a9 - std::panicking::default_hook::h3217e229d6e9d13c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:314:9
  10:     0x557fc00ccdb2 - deno::setup_panic_hook::{{closure}}::h144eead8301ce14a
  11:     0x557fbfd864c6 - std::panicking::rust_panic_with_hook::h9acb8048b738d2e0
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:702:17
  12:     0x557fbfd862c7 - std::panicking::begin_panic_handler::{{closure}}::h70f3b839526af6dc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:588:13
  13:     0x557fbfd844a4 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ecf2cee857fbe0a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x557fbfd85ff9 - rust_begin_unwind
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
  15:     0x557fbfdac483 - core::panicking::panic_fmt::h9f8393e7fd56d655
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
  16:     0x557fbfdac733 - core::result::unwrap_failed::h8b88eb424b1f8daa
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
  17:     0x557fc078ab60 - deno_runtime::permissions::resolved_and_display_path::hebb61ca199e92bf4
  18:     0x557fc07837ec - deno_runtime::permissions::UnaryPermission<deno_runtime::permissions::ReadDescriptor>::check::h371bb7ad56afb4f5
  19:     0x557fc05a8933 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h4f26a4837ed52d94
  20:     0x557fbef13175 - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
                               at ./../../../../v8/src/api/api-arguments-inl.h:147:3
  21:     0x557fbef12c5a - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
                               at ./../../../../v8/src/builtins/builtins-api.cc:114:36
  22:     0x557fbef120b6 - _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
                               at ./../../../../v8/src/builtins/builtins-api.cc:132:1
  23:     0x557fbfc7e7f8 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
```

</details>

**Comment by liruifengv** [comment]
This bug seems to have been fixed.

**Comment by TheLastZombie** [comment]
Ah, you're right. 1.25.4 (or v8 10.7) fixed it.
