### ISSUE TITLE
`httpServerGetChunkedResponseWithKa` is flaky

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#15540]
```
httpServerGetChunkedResponseWithKa ... FAILED (29ms)

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.24.3
Args: ["/Users/runner/work/deno/deno/target/debug/deno", "test", "--unstable", "--location=http://js-unit-tests/foo/bar", "--no-prompt", "-A", "/Users/runner/work/deno/deno/cli/tests/unit"]

thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', ext/flash/lib.rs:1293:42
stack backtrace:
   0:        0x10f18a2f4 - std::backtrace_rs::backtrace::libunwind::trace::hc513dadde6954c86
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10f18a2f4 - std::backtrace_rs::backtrace::trace_unsynchronized::hef5b528e06275835
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10f18a2f4 - std::sys_common::backtrace::_print_fmt::hd90f3854346e0ebc
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x10f18a2f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h85521558a183f368
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x10f1ade0b - core::fmt::write::h01631fae0d2b98bc
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:        0x10f181c58 - std::io::Write::write_fmt::h675dde99a2999169
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:        0x10f18c19d - std::sys_common::backtrace::_print::h9f1d91ee7cd2be55
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x10f18c19d - std::sys_common::backtrace::print::h4ad640f11cc29383
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x10f18c19d - std::panicking::default_hook::{{closure}}::h5e5df492d229fd65
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:        0x10f18bef4 - std::panicking::default_hook::h18647b59f1a84ee2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:        0x10a6fe060 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h373f10a573861aeb
  11:        0x109ec633e - deno::setup_panic_hook::{{closure}}::h01a70c74bcf2196c
  12:        0x10f18c79b - std::panicking::rust_panic_with_hook::hd9ead35a68ccc55e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
  13:        0x10f18c5da - std::panicking::begin_panic_handler::{{closure}}::h6fca91c5e1dc2f30
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:586:13
  14:        0x10f18a777 - std::sys_common::backtrace::__rust_end_short_backtrace::h4ff3025d9a0a0490
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  15:        0x10f18c2ea - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  16:        0x10f24bbe3 - core::panicking::panic_fmt::h3d9f795ee387ef8d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  17:        0x10f24bac7 - core::panicking::panic::h02eb82771823ab30
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
  18:        0x10e0fc10e - core::option::Option<T>::unwrap::he5e41fdb420fdaa6
  19:        0x10c4b6b64 - deno_flash::op_flash_wait_for_listening::call::{{closure}}::h2474dfb19459500b
  20:        0x10c4c00cb - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8f1d353fe9661f9d
  21:        0x10c4b7923 - deno_flash::op_flash_wait_for_listening::v8_func::{{closure}}::h5ef97f80e5589f26
  22:        0x10c4bfbfb - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4883db71c2dd8267
  23:        0x10dde4d4f - <core::pin::Pin<P> as core::future::future::Future>::poll::ha60a51dda3415815
  24:        0x10de8ef54 - <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll::h05851d2623ec0a3f
  25:        0x10c4d061a - deno_core::ops::OpCall<T>::eager::hf264f68fee04e200
  26:        0x10c4e2ad2 - deno_core::runtime::queue_async_op::hbe7c675b6932f31f
  27:        0x10c4b751c - deno_flash::op_flash_wait_for_listening::v8_func::h6e60362ae65d96b7
  28:        0x10c4dd70d - core::ops::function::Fn::call::h3641c5d9cf45f927
  29:        0x10c4c3e3e - v8::function::<impl v8::support::MapFnFrom<F> for extern "C" fn(*const v8::function::FunctionCallbackInfo)>::mapping::{{closure}}::h79cbfb6bc99db4a1
  30:        0x10c4c176a - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h3e9b06797214e0e4
  31:        0x10e244aff - HandleApiCallHelper<false>
                               at ./../../../../v8/src/builtins/builtins-api.cc:112:36
  32:        0x10e243fd6 - Builtin_HandleApiCall
                               at ./../../../../v8/src/builtins/builtins-api.cc:130:1
httpServerPostWithContentLengthBody ...test integration::js_unit_tests ... FAILED
```

This happened in test fastci macos-12: https://github.com/denoland/deno/runs/7958493678?check_suite_focus=true

**Comment by littledivy** [comment]
Resolved with #15591
