### ISSUE TITLE
spawnChildUnref is flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#15589]
```
spawnChildUnref => ./cli/tests/unit/spawn_test.ts:716:6
error: AssertionError: Expected error to be instance of "NotFound", but was "PermissionDenied".
    throw new AssertionError(msg);
          ^
    at assertIsError (file:///C:/actions-runner/work/deno/deno/test_util/std/testing/asserts.ts:584:11)
    at assertThrows (file:///C:/actions-runner/work/deno/deno/test_util/std/testing/asserts.ts:661:7)
    at spawnChildUnref (file:///C:/actions-runner/work/deno/deno/cli/tests/unit/spawn_test.ts:780:5)

 FAILURES 

spawnChildUnref => ./cli/tests/unit/spawn_test.ts:716:6

FAILED | 1092 passed (6 steps) | 1 failed | 58 ignored (2m8s)
```

https://github.com/denoland/deno/runs/7999331454?check_suite_focus=true

**Comment by lucacasonato** [comment]
This test does not exist anymore.
