### ISSUE TITLE
Deno 1.25 breaks sqlite3 ffi

### ISSUE THREAD

**Issue by wangbinyq** [denoland/deno#15588]
```sqlite-ffi.ts
import { Database } from "https://deno.land/x/sqlite3@0.4.4/mod.ts";

const db = new Database("test.db");

console.log("ok");
```

run with Deno 1.25.0 `deno run -A --unstable sqlite-ffi.ts`

```
error: Uncaught TypeError: Invalid FFI pointer type, expected null, integer or BigInt
  const result = lib.sqlite3_open_v2(
                     ^
    at sqlite3_open_v2 (https://deno.land/x/sqlite3@0.4.4/src/ffi.ts:486:22)
    at new Database (https://deno.land/x/sqlite3@0.4.4/src/database.ts:154:20)
    at file:///C:/Users/wangb/git/ts-project/deno-test/sqlite-ffi.ts:3:12
(base) 
```

run with Deno 1.24.3, 'ok' is printed.

**Comment by littledivy** [comment]
There was a breaking change in the FFI API. `pointer` types were split into a `buffer` type. Will be fixed when x/sqlite3 is updated. See https://github.com/denodrivers/sqlite3/pull/44
