### ISSUE TITLE
Failed to `import XR from "npm:xregexp@5.1.0";`

### ISSUE THREAD

**Issue by wojpawlik** [denoland/deno#15593]
```
error: Uncaught NotFound: No such file or directory (os error 2)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:729:25)
    at Module.load (deno:ext/node/02_require.js:630:34)
    at Function.Module._load (deno:ext/node/02_require.js:487:14)
    at Module.require (deno:ext/node/02_require.js:652:21)
    at require (deno:ext/node/02_require.js:777:18)
    at Object.<anonymous> (file:///home/wojpawlik/.cache/deno/npm/registry.npmjs.org/@babel/runtime-corejs3/7.18.9/helpers/arrayWithHoles.js:1:278)
    at Object.<anonymous> (file:///home/wojpawlik/.cache/deno/npm/registry.npmjs.org/@babel/runtime-corejs3/7.18.9/helpers/arrayWithHoles.js:8:4)
    at Module._compile (deno:ext/node/02_require.js:713:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:740:12)
    at Module.load (deno:ext/node/02_require.js:630:34)
```

**Comment by GJZwiers** [comment]
I get a panic! instead of an error:
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.25.0
Args: ["C:\\Users\\GJZwiers\\.cargo\\bin\\deno.exe", "run", "--unstable", "-A", "main.js"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', ext\node\lib.rs:488:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
