### ISSUE TITLE
`deno repl` throws `ArrayPrototypeFilter is not defined` when referencing `Deno`.

### ISSUE THREAD

**Issue by curtislarson** [denoland/deno#15594]
```sh
❯ deno repl
Deno 1.25.0
exit using ctrl+d or close()
> Deno
ReferenceError: ArrayPrototypeFilter is not defined
    at Object.ownKeys (deno:ext/node/01_node.js:54:7)
    at keys (<anonymous>)
    at inspectRawObject (deno:ext/console/02_console.js:1100:24)
    at inspectObject (deno:ext/console/02_console.js:1306:30)
    at _inspectValue (deno:ext/console/02_console.js:677:16)
    at inspectValue (deno:ext/console/02_console.js:691:11)
    at inspectValueWithQuotes (deno:ext/console/02_console.js:799:16)
    at inspectRawObject (deno:ext/console/02_console.js:1147:15)
    at inspectObject (deno:ext/console/02_console.js:1306:30)
    at _inspectValue (deno:ext/console/02_console.js:677:16)
> globalThis.Deno
ReferenceError: ArrayPrototypeFilter is not defined
    at Object.ownKeys (deno:ext/node/01_node.js:54:7)
    at keys (<anonymous>)
    at inspectRawObject (deno:ext/console/02_console.js:1100:24)
    at inspectObject (deno:ext/console/02_console.js:1306:30)
    at _inspectValue (deno:ext/console/02_console.js:677:16)
    at inspectValue (deno:ext/console/02_console.js:691:11)
    at inspectValueWithQuotes (deno:ext/console/02_console.js:799:16)
    at inspectRawObject (deno:ext/console/02_console.js:1147:15)
    at inspectObject (deno:ext/console/02_console.js:1306:30)
    at _inspectValue (deno:ext/console/02_console.js:677:16)
```

```sh
❯ deno --version
deno 1.25.0 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
```

You can access the functions/properties on the `Deno` namespace just fine.

Occurs with and without `--unstable`. Also occurs on `aarch64-apple-darwin`

**Comment by bartlomieju** [comment]
Thanks for the report, we'll fix it right away.
