### ISSUE TITLE
Incomplete error cause for long cause chains

### ISSUE THREAD

**Issue by Cre3per** [denoland/deno#15602]
```text
deno 1.25.0 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
```

If the `Error.cause` chain exceeds 2 `Error`s and the last `Error` is caused by a previous `Error`, deno doesn't output the cause of the last `Error`.

`deno run` this code

```typescript
const foo = new Error("foo");
const bar = new Error("bar", { cause: foo });
const baz = new Error("baz", { cause: bar });
foo.cause = bar;
throw baz;
```

Output

```
error: Uncaught Error: baz
const baz = new Error("baz", { cause: bar });
            ^
    at file:///home/lukas/projects/deno/cli/tests/testdata/error_cause_recursive_non_topmost.ts:3:13
Caused by: Error: bar
    at file:///home/lukas/projects/deno/cli/tests/testdata/error_cause_recursive_non_topmost.ts:2:13
Caused by: Error: foo
    at file:///home/lukas/projects/deno/cli/tests/testdata/error_cause_recursive_non_topmost.ts:1:13
```

Note that deno doesn't tell us the cause of `foo`

Expected (Added 2 lines to the end)

```text
error: Uncaught Error: baz
const baz = new Error("baz", { cause: bar });
            ^
    at file:///home/lukas/projects/deno/cli/tests/testdata/error_cause_recursive_non_topmost.ts:3:13
Caused by: Error: bar
    at file:///home/lukas/projects/deno/cli/tests/testdata/error_cause_recursive_non_topmost.ts:2:13
Caused by: Error: foo
    at file:///home/lukas/projects/deno/cli/tests/testdata/error_cause_recursive_non_topmost.ts:1:13
Caused by: Error: bar
    at file:///home/lukas/projects/deno/cli/tests/testdata/error_cause_recursive_non_topmost.ts:2:13
```

Same issue if there are 4 `Error`s. But not if there are 2 `Error`s.

For comparison, if there are 2 `Error`s

```typescript
const foo = new Error("foo");
const bar = new Error("bar", { cause: foo });
foo.cause = bar;
throw bar;
```

Output matches expectation

```text
error: Uncaught Error: bar
const bar = new Error("bar", { cause: foo });
            ^
    at file:///home/lukas/projects/deno/cli/tests/testdata/error_cause_recursive_non_topmost.ts:2:13
Caused by: Error: foo
    at file:///home/lukas/projects/deno/cli/tests/testdata/error_cause_recursive_non_topmost.ts:1:13
Caused by: Error: bar
    at file:///home/lukas/projects/deno/cli/tests/testdata/error_cause_recursive_non_topmost.ts:2:13
```

Found while working on #13413  
In the broken example: `JsError::cause` of `foo` is `None` in `format_js_error_inner()`.
In the working example: `JsError::cause` of `foo` is `bar` in `format_js_error_inner()`. `bar`'s cause is `None`.

Node handles the example as expected (And with `<ref>` and `[Circular]`)

**Comment by Cre3per** [comment]
`inner_from_v8_exception()` tracks causes it has already seen. Quoting the original example for context

```typescript
const foo = new Error("foo");
const bar = new Error("bar", { cause: foo });
const baz = new Error("baz", { cause: bar });
foo.cause = bar;
throw baz;
```

This is how `seen` is checked and tracked

```js
      //                      seen=[]
baz   // !seen.contains(bar) -> seen=[bar]
->bar // !seen.contains(foo) -> seen=[bar,foo]
->foo // seen.contains(bar) -> don't add a cause
->bar // dropped, because already seen
```

This bug always appears if an `Error` was caused by a previously seen `Error` that was not the first `Error`.

To fix it, instead of tracking seen `cause`s, we can track seen `exception`s.

```js
      //                      seen=[]
baz   // !seen.contains(baz) -> seen=[baz]
->bar // !seen.contains(bar) -> seen=[baz,bar]
->foo // !seen.contains(foo) -> seen=[baz,bar,foo]
->bar // seen.contains(bar) -> don't add a cause
->foo // dropped, because already seen
```

This way, we include the cause of every exception seen for the first time.

@crowlKats I'd like to take over if you haven't start yet, is that ok?  
Sorry for not asking sooner, I had low hopes for me finding the... _cause_.
