### ISSUE TITLE
`npm:ytdl-core` throws `Uncaught SyntaxError: Identifier 'setTimeout' has already been declared`

### ISSUE THREAD

**Issue by JasperVanEsveld** [denoland/deno#15635]
It also needs access to the `NODE_DEBUG` environment variable though I am not sure why.

```
import "npm:ytdl-core";
```
```
⚠️  ️Deno requests env access to "NODE_DEBUG". Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
error: Uncaught SyntaxError: Identifier 'setTimeout' has already been declared
    at Object.evalContext (deno:core/01_core.js:297:14)
    at wrapSafe (deno:ext/node/02_require.js:692:27)
    at Module._compile (deno:ext/node/02_require.js:703:29)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:740:12)
    at Module.load (deno:ext/node/02_require.js:630:34)
    at Function.Module._load (deno:ext/node/02_require.js:487:14)
    at Module.require (deno:ext/node/02_require.js:652:21)
    at require (deno:ext/node/02_require.js:777:18)
    at Object.<anonymous> (file:///C:/Users/jaspe/AppData/Local/deno/npm/registry.npmjs.org/ytdl-core/4.11.1/lib/index.js:2:17)
    at Object.<anonymous> (file:///C:/Users/jaspe/AppData/Local/deno/npm/registry.npmjs.org/ytdl-core/4.11.1/lib/index.js:216:4)
```

**Comment by dsherret** [comment]
Already fixed by #15608
