### ISSUE TITLE
npm URL throws: `Cannot read properties of undefined (reading 'filename')`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#15642]
Happens with `g-i-s`:

```js
import gis from 'npm:g-i-s';
```

```
deno run -A --unstable .\main.js

error: Uncaught TypeError: Cannot read properties of undefined (reading 'filename')
    at Object.Module._extensions..js (deno:ext/node/02_require.js:734:64)
    at Module.load (deno:ext/node/02_require.js:630:34)
    at Function.Module._load (deno:ext/node/02_require.js:487:14)
    at Module.require (deno:ext/node/02_require.js:652:21)
    at require (deno:ext/node/02_require.js:776:18)
    at Object.<anonymous> (file:///C:/Users/GJZwiers/AppData/Local/deno/npm/registry.npmjs.org/cheerio/1.0.0-rc.12/lib/parsers/parse5-adapter.js:14:16)
    at Object.<anonymous> (file:///C:/Users/GJZwiers/AppData/Local/deno/npm/registry.npmjs.org/cheerio/1.0.0-rc.12/lib/parsers/parse5-adapter.js:68:4)
    at Module._compile (deno:ext/node/02_require.js:712:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:739:12)
    at Module.load (deno:ext/node/02_require.js:630:34)
```

**Comment by bartlomieju** [comment]
The problem arises from trying to `require()` `/Users/ib/Library/Caches/deno/npm/registry.npmjs.org/parse5/7.0.0/dist/cjs/index.js` with following metadata:

```json
{
  exists: true,
  exports: { ".": { import: "./dist/index.js", require: "./dist/cjs/index.js" } },
  imports: null,
  bin: null,
  main: "dist/cjs/index.js",
  name: "parse5",
  path: "/Users/ib/Library/Caches/deno/npm/registry.npmjs.org/parse5/7.0.0/./package.json",
  typ: "module",
  types: "dist/index.d.ts"
}
```

which doesn't match content of `package.json` for this module:

```json
{
    "name": "parse5",
    "type": "module",
    "description": "HTML parser and serializer.",
    "version": "7.0.0",
    "author": "Ivan Nikulin <ifaaan@gmail.com> (https://github.com/inikulin)",
    "contributors": "https://github.com/inikulin/parse5/graphs/contributors",
    "homepage": "https://github.com/inikulin/parse5",
    "funding": "https://github.com/inikulin/parse5?sponsor=1",
    "dependencies": {
        "entities": "^4.3.0"
    },
    "keywords": [
        "html",
        "parser",
        "html5",
        "WHATWG",
        "specification",
        "fast",
        "html parser",
        "html5 parser",
        "htmlparser",
        "parse5",
        "serializer",
        "html serializer",
        "htmlserializer",
        "parse",
        "serialize"
    ],
    "license": "MIT",
    "main": "dist/cjs/index.js",
    "module": "dist/index.js",
    "types": "dist/index.d.ts",
    "exports": {
        "import": "./dist/index.js",
        "require": "./dist/cjs/index.js"
    },
    "scripts": {
        "build:cjs": "tsc --module CommonJS --target ES6 --outDir dist/cjs && echo '{\"type\":\"commonjs\"}' > dist/cjs/package.json"
    },
    "repository": {
        "type": "git",
        "url": "git://github.com/inikulin/parse5.git"
    },
    "files": [
        "dist",
        "!*.map"
    ]
}
```

(notice that `package.json` doesn't specify `"type": "module"`)
