### ISSUE TITLE
Some modules cannot be found when importing from npm.

### ISSUE THREAD

**Issue by waptik** [denoland/deno#15645]
Hi. I want to say great work on the experimental npm support.

So i was giving it a try on a new fresh backed project and i came across some errors like `error: Uncaught (in promise) Error: Cannot find module 'fs'` and the most common are about `fs` and `fs/promises`.

Many npm packages that i know of use `fs` directly or indirectly(3rd party).

I made mention of the issue on [discord](https://discord.com/channels/684898665143206084/684898665151594506/1013030972989648958) and i [was told](https://discord.com/channels/684898665143206084/684898665151594506/1013089008974299287) to create an issue so here i am doing it.

I made a reproduction repo of it at https://github.com/waptik/using-epub-gen-in-deno.git

Clone it, run `deno task start` and go to http://localhost:8000/api/epub .
The server might even crash right after the first cache

**Comment by dsherret** [comment]
At the moment, since npm specifiers are so experimental they don't work with fresh. Just importing that package seems to work outside a fresh project, so maybe try without fresh?

**Comment by waptik** [comment]
> At the moment, since npm specifiers are so experimental they don't work with fresh. Just importing that package seems to work outside a fresh project, so maybe try without fresh?

I see. I moved the core functionalities of the projects and but them in both an `oak` and `serve`(a serve.ts file inside the same oak project root directory) projects.
For oak, the same issues from fresh came up. But for the `serve` project, the images are failing to download.

Here are the logs for `serve`:
```sh
Listening on http://localhost:8000/
Generating Template Files...
Downloading fonts...
No fonts to download
Downloading images...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book2.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book3.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book4.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book5.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book6.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book7.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book2.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book3.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book4.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book5.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book6.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book7.jpg` 2 times. Retrying...
Error: native promise missing, set fetch.Promise to your favorite alternative
    at fetch (file:///home/waptik/.cache/deno/npm/registry.npmjs.org/node-fetch/2.6.7/lib/index.js:1431:9)
    at file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib/util/fetchable.js:79:63
    at step (file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib/util/fetchable.js:52:23)
    at Object.next (file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib/util/fetchable.js:33:53)
    at file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib/util/fetchable.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib/util/fetchable.js:23:12)
    at fetchable (file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib/util/fetchable.js:67:50)
    at file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib/util/other.js:84:59
    at step (file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib/util/other.js:43:23)
Generating Template Files...
Downloading fonts...
No fonts to download
Downloading images...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book2.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book3.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book4.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book5.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book6.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book7.jpg` 1 time. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book1.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book2.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book3.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book4.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book5.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book6.jpg` 2 times. Retrying...
Failed to fetch `http://www.alice-in-wonderland.net/wp-content/uploads/1book7.jpg` 2 times. Retrying...
Error: native promise missing, set fetch.Promise to your favorite alternative
    at fetch (file:///home/waptik/.cache/deno/npm/registry.npmjs.org/node-fetch/2.6.7/lib/index.js:1431:9)
    at file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib/util/fetchable.js:79:63
    at step (file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib/util/fetchable.js:52:23)
    at Object.next (file:///home/waptik/.cache/deno/npm/registry.npmjs.org/epub-gen-memory/1.0.9/dist/lib
```

**Comment by bartlomieju** [comment]
@waptik both of the errors above should now be addressed. Could you try again and let us know if there are any more problems?

**Comment by waptik** [comment]
> @waptik both of the errors above should now be addressed. Could you try again and let us know if there are any more problems?

I can confirm that the errors have gone away and the package works as it should.
My Deno version is `deno 1.25.1`

Is it because i upgraded my version?
