### ISSUE TITLE
`ReferenceError: ArrayPrototypeFilter is not defined` occurs when `Deno` called

### ISSUE THREAD

**Issue by hyp3rflow** [denoland/deno#15659]
## repro
```javascript
console.log(Deno);
```
or type `Deno` in REPL,
you can get `ReferenceError`.
```
error: Uncaught ReferenceError: ArrayPrototypeFilter is not defined
    at Object.ownKeys (deno:ext/node/01_node.js:54:7)
    at keys (<anonymous>)
    at inspectRawObject (deno:ext/console/02_console.js:1100:24)
    at inspectObject (deno:ext/console/02_console.js:1306:30)
    at _inspectValue (deno:ext/console/02_console.js:677:16)
    at inspectValue (deno:ext/console/02_console.js:691:11)
    at inspectValueWithQuotes (deno:ext/console/02_console.js:799:16)
    at inspectRawObject (deno:ext/console/02_console.js:1147:15)
    at inspectObject (deno:ext/console/02_console.js:1306:30)
    at _inspectValue (deno:ext/console/02_console.js:677:16)
```

**Comment by hyp3rflow** [comment]
oops #15594. already resolved. sry :q
