### ISSUE TITLE
Feature Request:  loading .node files

### ISSUE THREAD

**Issue by codebenderhq** [denoland/deno#15686]
Hi currently not able to import @parcel/core with deno npm new feature was hoping to find out if implementing loading .node files is in the works 

or can a work around be suggested

Eg Error below

```
error: Uncaught Error: not implemented loading .node files
    at Object.Module._extensions..node (deno:ext/node/02_require.js:764:11)
    at Module.load (deno:ext/node/02_require.js:630:34)
    at Function.Module._load (deno:ext/node/02_require.js:487:14)
    at Module.require (deno:ext/node/02_require.js:652:21)
    at require (deno:ext/node/02_require.js:777:18)
    at Object.<anonymous> (file:/// Library/Caches/deno/npm/registry.npmjs.org/@parcel/source-map/2.1.0/parcel_sourcemap_node/index.js:15:18)
    at Object.<anonymous> (file:///Caches/deno/npm/registry.npmjs.org/@parcel/source-map/2.1.0/parcel_sourcemap_node/index.js:17:4)
    at Module._compile (deno:ext/node/02_require.js:713:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:740:12)
    at Module.load (deno:ext/node/02_require.js:630:34)
```

**Comment by bartlomieju** [comment]
Node API support landed in v1.27
