### ISSUE TITLE
Tagged versions in npm specifiers cause a panic

### ISSUE THREAD

**Issue by Liamolucko** [denoland/deno#15753]
Attempting to run an npm package with a tagged version causes Deno to panic:

```
❯ RUST_BACKTRACE=1 deno run --unstable npm:rome@next

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.25.1
Args: ["deno", "run", "--unstable", "npm:rome@next"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid version requirement.

Caused by:
    0: Invalid npm specifier version requirement 'next'.
    1: Unexpected character.
         next
         ~', cli/graph_util.rs:86:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: deno::graph_util::GraphData::add_graph
   4: deno::proc_state::ProcState::prepare_module_load::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: deno::run_command::{{closure}}
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: deno::main::{{closure}}
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: deno_runtime::tokio_util::run_local
  16: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Tagged versions should probably be supported, but at the very least they should gracefully fail instead of panicking.

**Comment by bartlomieju** [comment]
This was fixed in https://github.com/denoland/deno/pull/15746 and will be released in V1.25.2 next week

**Comment by Liamolucko** [comment]
My bad, forgot to look at closed issues 🤦‍♂️

**Comment by niedzielski** [comment]
I believe this is still an issue in v1.26.0:

```
$ deno --version
deno 1.26.0 (release, x86_64-unknown-linux-gnu)
v8 10.7.193.3
typescript 4.8.3

~ ──────────────────────────────────────────────────────────────────────────────────────────────
$ deno run -A --unstable --node-modules-dir npm:live-server@1.2.2
error: npm package: live-server@1.2.2

Caused by:
    0: error parsing version requirement for dependency: opn@latest
    1: Invalid npm version requirement 'latest'.
    2: Unexpected character.
         latest
         ~
```

**Comment by dsherret** [comment]
Documentation on valid tag names: https://git-scm.com/docs/git-check-ref-format#_description

**Comment by dsherret** [comment]
@niedzielski thanks for that! I opened #16321 for it because the error occurs when an npm package specifies a tagged version.
