### ISSUE TITLE
Error on sync_third_party.py

### ISSUE THREAD

**Issue by daynin** [denoland/deno#1577]
Got this error when try to sync third party deps:

OS: OS X 10.14.2
python: 2.7.15_2
rust: 1.32.0

```
Installing collected packages: pypiwin32
Exception:
Traceback (most recent call last):
  File "/var/folders/9k/zcgn3n8d5k73n0r9w34g7rs40000gn/T/tmpN4npgM/lib/python/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/var/folders/9k/zcgn3n8d5k73n0r9w34g7rs40000gn/T/tmpN4npgM/lib/python/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/var/folders/9k/zcgn3n8d5k73n0r9w34g7rs40000gn/T/tmpN4npgM/lib/python/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/var/folders/9k/zcgn3n8d5k73n0r9w34g7rs40000gn/T/tmpN4npgM/lib/python/site-packages/pip/_internal/req/req_install.py", line 919, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/var/folders/9k/zcgn3n8d5k73n0r9w34g7rs40000gn/T/tmpN4npgM/lib/python/site-packages/pip/_internal/req/req_install.py", line 445, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/var/folders/9k/zcgn3n8d5k73n0r9w34g7rs40000gn/T/tmpN4npgM/lib/python/site-packages/pip/_internal/wheel.py", line 280, in move_wheel_files
    prefix=prefix,
  File "/var/folders/9k/zcgn3n8d5k73n0r9w34g7rs40000gn/T/tmpN4npgM/lib/python/site-packages/pip/_internal/locations.py", line 180, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
```

**Comment by bartlomieju** [comment]
CC @ry this is stale, can we close it?
