### ISSUE TITLE
[Bug 1.25.1] (Deno has panicked) - Bad url provided to the deno test --reload flag

### ISSUE THREAD

**Issue by sagea** [denoland/deno#15770]
### Description
Deno panics when the deno test command is run with a bad url in the `--reload` flag

### Failure Cases
**IMPORTANT:** 

> Each of these test cases provides a slightly different output at this location...
> thread 'main' panicked at 'Bad Url: foo', cli/args/flags.rs:3106:7
> &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;⬆️

**Cases:**
1. A bad URL 
`deno test --reload=badurl`
2. Nothing after equal sign 
`deno test --reload=`
3. Single comma after equal sign 
`deno test --reload=,`
4. Trailing comma 
`deno test --reload=http://0.0.0.0:4500/,` 
5. leading comma 
`deno test --reload=,http://0.0.0.0:4500/`
6. Bad URL after good URL 
`deno test --reload=http://0.0.0.0:4500/,badUrl`

### Trace
```
RUST_BACKTRACE=full deno test --reload=foo

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.25.1
Args: ["deno", "test", "--reload=foo"]

thread 'main' panicked at 'Bad Url: foo', cli/args/flags.rs:3106:7
stack backtrace:
   0:        0x109f73149 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h85521558a183f368
   1:        0x10951ad8b - core::fmt::write::h01631fae0d2b98bc
   2:        0x109f43f68 - std::io::Write::write_fmt::h675dde99a2999169
   3:        0x109f77f3d - std::panicking::default_hook::{{closure}}::h5e5df492d229fd65
   4:        0x109f77c24 - std::panicking::default_hook::h18647b59f1a84ee2
   5:        0x10948d26b - deno::setup_panic_hook::{{closure}}::h92c4da2c5f40e0fc
   6:        0x109f78a8b - std::panicking::rust_panic_with_hook::hd9ead35a68ccc55e
   7:        0x109f78904 - std::panicking::begin_panic_handler::{{closure}}::h6fca91c5e1dc2f30
   8:        0x109f78879 - std::sys_common::backtrace::__rust_end_short_backtrace::h4ff3025d9a0a0490
   9:        0x109f78835 - _rust_begin_unwind
  10:        0x10b371893 - core::panicking::panic_fmt::h3d9f795ee387ef8d
  11:        0x1093ac838 - deno::args::flags::reload_arg_parse::hb14e0ff60cbfc8ee
  12:        0x1093ab7da - deno::args::flags::compile_args_parse::hf9db57b5cdb4f802
  13:        0x1093ab8e8 - deno::args::flags::runtime_args_parse::h214e9384c04b492f
  14:        0x1093a0ed1 - deno::args::flags::flags_from_vec::h1d4465ae54c87f45
  15:        0x10948f4ce - deno::main::{{closure}}::hb24a3c359ee9dc72
  16:        0x109316e2c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha7d9a17c30cb5fb2
  17:        0x1091534e4 - deno_runtime::tokio_util::run_local::h3080e139a5e54647
  18:        0x10948d498 - deno::main::h275bcd1c00097713
  19:        0x10918a387 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha506a7419e7b243b
  20:        0x1094aa225 - _main
```

**Comment by kitsonk** [comment]
Obviously it shouldn't work, but it also shouldn't panic.

**Comment by sagea** [comment]
I was thinking the same thing. I will try to take a stab at it.

**Comment by sagea** [comment]
@kitsonk I think I have a good solution. I will create a PR shortly.

**Comment by lino-levan** [comment]
This issue should be closed? It looks like Deno errors instead of panicking in 1.25.2 thanks to #15784 being merged.

<img width="684" alt="Screen Shot 2022-09-11 at 3 38 52 PM" src="https://user-images.githubusercontent.com/11367844/189551849-5e26fc13-8db6-4cf8-9e14-d7cb0767ddbf.png">

**Comment by sagea** [comment]
@lino-levan Thanks for the notification. The ticket is now closed.
