### ISSUE TITLE
Unable to discover some of npm dependencies

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#15823]
Best seen in an example here: https://github.com/denoland/deno/issues/15427#issuecomment-1227199177

Concretely:
```js
// vite.config.js
import { defineConfig } from 'npm:vite'
import vue from 'npm:@vitejs/plugin-vue'
import "npm:vue@3.2.37/compiler-sfc" // <--- this step is not required when running in Node

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()]
})
```

In the above example `vue` is a peer dependency of `@vitejs/plugin-vue`. However, if we try to run to run a project without that import we get following error:
```
Download https://registry.npmjs.org/@vitejs/plugin-vue/-/plugin-vue-3.1.0.tgz
error when starting dev server:
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
    at resolveCompiler (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/@vitejs/plugin-vue/3.1.0/dist/index.mjs:12:11)
    at Context.buildStart (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/@vitejs/plugin-vue/3.1.0/dist/index.mjs:2587:46)
```

Due to how Deno currently discovers and handles npm dependencies, we are not installing `vue` package that is required to run this program.

**Comment by bartlomieju** [comment]
One solution to this problem might be that all `npm:<specifier>` references present in the import map could be downloaded upfront. This could play nicely with set up scripts that various tools provide that scaffold a project for the user.
