### ISSUE TITLE
node: `deno run` has issues when npm module self-invokes

### ISSUE THREAD

**Issue by cmoog** [denoland/deno#15836]
Raw error:

```console
$ deno run --unstable -A npm:wrangler
error: Uncaught NotFound: No such file or directory (os error 2)
      this.#process = Deno.spawnChild(cmd, {
                           ^
    at Object.spawnChild (deno:runtime/js/40_spawn.js:36:23)
    at new ChildProcess (https://deno.land/std@0.155.0/node/internal/child_process.ts:135:28)
    at spawn (https://deno.land/std@0.155.0/node/child_process.ts:140:10)
    at runWrangler (file:///home/charlie/.cache/deno/npm/registry.npmjs.org/wrangler/2.0.29/bin/wrangler.js:55:9)
    at main (file:///home/charlie/.cache/deno/npm/registry.npmjs.org/wrangler/2.0.29/bin/wrangler.js:126:64)
    at Object.<anonymous> (file:///home/charlie/.cache/deno/npm/registry.npmjs.org/wrangler/2.0.29/bin/wrangler.js:168:6)
    at Object.<anonymous> (file:///home/charlie/.cache/deno/npm/registry.npmjs.org/wrangler/2.0.29/bin/wrangler.js:170:4)
    at Module._compile (deno:ext/node/02_require.js:712:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:745:12)
    at Module.load (deno:ext/node/02_require.js:630:34)
```

`wrangler.js` is invoking `spawn` with `process.execPath`.

**Comment by cmoog** [comment]
New error on latest version:
```console
$ deno --version
deno 1.25.3 (release, aarch64-apple-darwin)
v8 10.6.194.5
typescript 4.7.4

$ deno run --unstable -A npm:wrangler
error: Found argument '--no-warnings' which wasn't expected, or isn't valid in this context

	If you tried to supply `--no-warnings` as a value rather than a flag, use `-- --no-warnings`

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
```

The node module is creating a subprocess with `process.execPath` under the assumption that it will resolve to a node binary. Then, the newly invoked Deno child process fails to parse the node flags and throws the error as shown above.

I think this could be solved with something like the following: https://github.com/cmoog/deno_std/commit/638f59db57fec73ce49125ea58305e7cfd1567eb

**Comment by bartlomieju** [comment]
@kt3k @cjihrig I believe this is related to your work on subprocess API in `std/node`. Could you please take a look?

**Comment by cjihrig** [comment]
It looks like Deno 1.25.3 is being used, so I think it might be unrelated to our changes in std/node (which are newer). Either way, I'll take a look.

**Comment by cjihrig** [comment]
@cmoog your proposal is close to something we recently implemented. I don't think we would want to use `filter()` to just drop arguments though, as that could lead to unexpected behavior. For example, in the case of `wrangler` here, I would expect to see no warning messages, but if we ignore `--no-warnings` then that would not be the case.

We **could** filter out all of the arguments that are allowed in the [`NODE_OPTIONS`](https://nodejs.org/api/cli.html#node_optionsoptions) environment variable, and then spawn the child process with that environment variable. It wouldn't handle all Node.js flags, and we'd have to be careful not to overwrite any existing `NODE_OPTIONS`, and it would change `process.execArgv` which some code could be depending on.

Longer term, to properly support this, I think we need to be able to start the Deno CLI in Node mode. npm module support is getting us closer, but there are still some missing edge cases I think.
