### ISSUE TITLE
[Bug]PermissionDenied: Reading package.json is not allowed when using npm:mocha@10.0.0

### ISSUE THREAD

**Issue by char8x** [denoland/deno#15845]
# Problem
Output `PermissionDenied` when running
```sh
deno run --unstable --allow-env --allow-read npm:mocha@10.0.0 test.js
```

# Simplest Reproduction
Project files like [this](https://stackblitz.com/edit/node-qvb6qn?file=test.js)

### test.js
```js
import assert from "assert";
describe("Array", function () {
  describe("#indexOf()", function () {
    it("should return -1 when the value is not present", function () {
      assert.equal([1, 2, 3].indexOf(4), -1);
    });
  });
});

```
### package.json
```json
{
  "type": "module"
}
```
### file permission
```sh
drwxr-xr-x   .
drwxr-xr-x   ..
-rw-r--r--   package.json
-rw-r--r--   test.js
```

# Error Output
```sh
PermissionDenied: Reading .../mocha-example/package.json is not allowed
    at Object.Module._extensions..js (deno:ext/node/02_require.js:731:28)
    at Module.load (deno:ext/node/02_require.js:630:34)
    at Function.Module._load (deno:ext/node/02_require.js:487:14)
    at Module.require (deno:ext/node/02_require.js:652:21)
    at require (deno:ext/node/02_require.js:782:18)
    ...
```

# Extra Info
Deno: v1.25.2
macOS: 11.6.8

**Comment by brenelz** [comment]
It appears it only allows reading if it's in the deno_dir node modules. I'm not sure exactly how this should work

**Comment by traceypooh** [comment]
i have similar issue with trying to get `eslint` to work FWIW 
("cant" read `package.json` or `.eslintrc.js`)

**Comment by dsherret** [comment]
Can still reproduce in the latest canary. The npm code needs to take user permissions into account instead of being restricted to the cache or node_modules directory.

**Comment by bartlomieju** [comment]
https://github.com/denoland/deno/pull/17134 will be a stepping stone to fix this problem.

**Comment by arjunyel** [comment]
Does anyone have a work around?
