### ISSUE TITLE
compat: Deno panic when doing odd things with npm support

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#15844]
steps:

- cd ~/.cache/deno/npm
- deno run registry.npmjs.org/z

panic:

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.25.2
Args: ["/home/mrcool/.deno/bin/deno", "run", "registry.npmjs.org/z"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid npm version 'z'.

Caused by:
    Unexpected character.
      z
      ~', cli/npm/cache.rs:162:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mrcool@mrcool~/.c/d/npm> env RUST_BACKTRACE=1 deno run registry.npmjs.org/ze

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.25.2
Args: ["deno", "run", "registry.npmjs.org/ze"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid npm version 'ze'.

Caused by:
    Unexpected character.
      ze
      ~', cli/npm/cache.rs:162:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: deno::npm::cache::NpmCache::resolve_package_id_from_specifier
   4: <deno::npm::GlobalNpmPackageResolver as deno::npm::NpmPackageResolver>::resolve_package_from_specifier
   5: deno::npm::NpmPackageResolver::in_npm_package
   6: <deno::module_loader::CliModuleLoader as deno_core::modules::ModuleLoader>::prepare_load
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: deno::run_command::{{closure}}
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: deno::main::{{closure}}
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: deno_runtime::tokio_util::run_local
  16: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
version: `deno 1.25.2`

**Comment by sigmaSd** [comment]
Odd things = debugging npm packages that aren't currently working with deno

**Comment by dsherret** [comment]
Yeah, don't run stuff in the npm cache directly. It won't work and is not a supported scenario. I'm going to mark this one as won't fix for now.

**Comment by kitsonk** [comment]
> Odd things = debugging npm packages that aren't currently working with deno

The npm cache in Deno is not like `node_modules` and is not designed that way.
