### ISSUE TITLE
Unhandled error inside a WebSocket callback with `--watch` panics

### ISSUE THREAD

**Issue by Emonadeo** [denoland/deno#15866]
```ts
// main.ts
import { serve } from "https://deno.land/std@0.155.0/http/server.ts";

function handler(req: Request): Response {
  try {
    const { response, socket } = Deno.upgradeWebSocket(req);
    socket.onopen = () => {
      throw new Error(); // <- panic
    };
    return response;
  } catch {
    return new Response(null, { status: 400 });
  }
}

serve(handler, { port: 3000 });
```
Running `deno run --allow-net --watch main.ts` and sending a websocket request panics.

Running `deno run --allow-net main.ts` (without `--watch`) does not panic.

### Log (`RUST_BACKTRACE=1`)
```
Platform: windows x86_64
Version: 1.25.1
Args: ["C:\\Users\\Emonadeo\\.deno\\bin\\deno.EXE", "run", "--allow-net", "--watch", "main.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Uncaught Error: execution terminated', cli\worker.rs:210:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Log (`RUST_BACKTRACT=full`)
```
Platform: windows x86_64
Version: 1.25.1
Args: ["C:\\Users\\Emonadeo\\.deno\\bin\\deno.EXE", "run", "--allow-net", "--watch", "main.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Uncaught Error: execution terminated', cli\worker.rs:210:14
stack backtrace:
   0:     0x7ff76552f31f - <unknown>
   1:     0x7ff7649536ea - <unknown>
   2:     0x7ff76550b4d9 - <unknown>
   3:     0x7ff765532f1b - <unknown>
   4:     0x7ff765532b44 - <unknown>
   5:     0x7ff7648b2c05 - <unknown>
   6:     0x7ff7655339b2 - <unknown>
   7:     0x7ff765533753 - <unknown>
   8:     0x7ff7655336b9 - <unknown>
   9:     0x7ff765533674 - <unknown>
  10:     0x7ff76676d4e5 - CrashForExceptionInNonABICompliantCodeRange
  11:     0x7ff76676d7a3 - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff764541498 - <unknown>
  13:     0x7ff7645030e0 - <unknown>
  14:     0x7ff7648a9b8a - <unknown>
  15:     0x7ff76469a662 - <unknown>
  16:     0x7ff7648b6f40 - <unknown>
  17:     0x7ff76465abb8 - <unknown>
  18:     0x7ff7644a0c01 - <unknown>
  19:     0x7ff7648b2ea5 - <unknown>
  20:     0x7ff7644e366a - <unknown>
  21:     0x7ff7648d8703 - <unknown>
  22:     0x7ff76671eb8c - CrashForExceptionInNonABICompliantCodeRange
  23:     0x7fffaf2d7034 - BaseThreadInitThunk
  24:     0x7fffb0202651 - RtlUserThreadStart
```

**Comment by Emonadeo** [comment]
While opening this issue I noticed that 1.25.2 just released two days ago.
Just updated and it seems to have fixed it.
Closing.
