### ISSUE TITLE
Deno.stat does not work with `file:///path/to/my/file.txt` file urls

### ISSUE THREAD

**Issue by jonasfrey** [denoland/deno#15984]
i dont know it this is intended, but :
/home/myuser/denotest/test_deno_stat_with_file_url.js
```javascript
var o_stat = await Deno.stat("file:///home/myuser/denotest/test_deno_stat_with_file_url.js");
console.log(o_stat)
```
output 
```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2), stat 'file:///home/myuser/denotest/test_deno_stat_with_file_url.js'
var o_stat = await Deno.stat("file:///home/myuser/denotest/test_deno_stat_with_file_url.js");
             ^
    at async Object.stat (deno:runtime/js/30_fs.js:231:17)
    at async file:///home/myuser/denotest/test_deno_stat_with_file_url.js:1:14
```
my deno version is :
```
deno --version
deno 1.25.3 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
```

**Comment by brenelz** [comment]
I believe that is to be expected. If you do the following it would probably work:

```typescript
var o_stat = await Deno.stat("/home/myuser/denotest/test_deno_stat_with_file_url.js");
console.log(o_stat)
```
