### ISSUE TITLE
run compiled file error

### ISSUE THREAD

**Issue by sunkainj** [denoland/deno#15990]
I'm trying to compile a  project here https://github.com/vicky-gonsalves/deno_rest.git by running the following command:
`deno compile --allow-all app.ts`
show:
```
Compile file:///home/xxx/Documents/deno_rest/app.ts
Emit app
```
run file
```
./app
mongodb://127.0.0.1:7010/dfx
2022-09-22T08:12:29.929Z [20] Database connecting...
2022-09-22T08:12:29.935Z [20] Database connected!
2022-09-22T08:12:29.937Z [20] Current Environment: development
2022-09-22T08:12:29.937Z [20] Server listening at http://localhost:7000

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.25.3
Args: ["./app"]

thread 'worker-0' panicked at 'not yet implemented: Workers are currently not supported in standalone binaries', cli/standalone.rs:241:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: deno::standalone::run::{{closure}}::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

os: deepin 20

**Comment by dsherret** [comment]
> thread 'worker-0' panicked at 'not yet implemented: Workers are currently not supported in standalone binaries', cli/standalone.rs:241:5

See #8654
