### ISSUE TITLE
Error fetching Wasm file

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#16002]
Source: https://discord.com/channels/684898665143206084/684898665151594506/1022408024725405698

The following code throws an error in Deno versions 1.17 and upwards:

```ts
const { instance, module } = await WebAssembly.instantiateStreaming(
  fetch("https://wpt.live/wasm/incrementer.wasm"),
);

const increment = instance.exports.increment as (input: number) => number;
console.log(increment(41));
```

```
deno run -A wasm.ts
```

Deno 1.16:
```
42
```

Deno 1.17:

```
error: Uncaught (in promise) Error: request or response body error: error reading a body from connection: unexpected end of file
    at async Object.pull (deno:ext/fetch/26_fetch.js:104:24)
```

Deno 1.25:
```
error: Uncaught (in promise) Error: request or response body error: error reading a body from connection: unexpected end of file
    at async Object.pull (deno:ext/fetch/26_fetch.js:119:24)
```

**Comment by ar37-rs** [comment]
```ts
const { instance, module } = await WebAssembly.instantiateStreaming(
  fetch("http://wpt.live/wasm/incrementer.wasm"),
);
```

change `https://` to `http://` working as expected, not sure why. i'm new to deno. @dsherret any idea?

**Comment by eryue0220** [comment]
Maybe the problem is caused by the rustls, discussed in [13058](https://github.com/denoland/deno/issues/13058). And is there any plan to fixed?
