### ISSUE TITLE
worker_terminate_tla_crash is flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16041]
```
---- integration::worker::worker_terminate_tla_crash stdout ----
deno_exe path C:\actions-runner\work\deno\deno\target\release\deno.exe
deno_exe args run --quiet --reload workers/terminate_tla_crash.js
deno_exe cwd "C:\\actions-runner\\work\\deno\\deno\\cli\\tests\\testdata"
output path C:\actions-runner\work\deno\deno\cli\tests\testdata\workers/terminate_tla_crash.js.out
thread 'integration::worker::worker_terminate_tla_crash' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<error: Uncaught (in worker "") Access is denied. (os error 5)
<error: Uncaught (in worker "") Access is denied. (os error 5)
<error: Uncaught (in worker "") Access is denied. (os error 5)
<error: Uncaught (in worker "") Access is denied. (os error 5)
<error: Uncaught (in worker "") Access is denied. (os error 5)
<error: Uncaught (in worker "") Access is denied. (os error 5)
<error: Uncaught (in worker "") Access is denied. (os error 5)
<error: Uncaught (in worker "") Access is denied. (os error 5)
<error: Uncaught (in worker "") Access is denied. (os error 5)
<error: Uncaught (in worker "") Access is denied. (os error 5)
<

', test_util\src\lib.rs:1977:7
stack backtrace:
   0:     0x7ff6ac89ac7f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff6ac89ac7f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff6ac89ac7f - std::sys_common::backtrace::_print_fmt
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff6ac89ac7f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff6ac63c0ea - core::fmt::write
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\fmt\mod.rs:1197
   5:     0x7ff6ac89ecb9 - std::io::Write::write_fmt<alloc::vec::Vec<u8,alloc::alloc::Global> >
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\io\mod.rs:1672
   6:     0x7ff6ac89e6eb - std::sys_common::backtrace::_print
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff6ac89e6eb - std::sys_common::backtrace::print
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff6ac89e6eb - std::panicking::default_hook::closure$1
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:295
   9:     0x7ff6ac89f405 - std::panicking::default_hook
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:311
  10:     0x7ff6ac89f405 - std::panicking::rust_panic_with_hook
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:698
  11:     0x7ff6ac89ef33 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:588
  12:     0x7ff6ac89ee99 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff6ac89ee54 - std::panicking::begin_panic_handler
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
  14:     0x7ff6acb7b605 - core::panicking::panic_fmt
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
  15:     0x7ff6ac8ff26b - core::fmt::impl$0::write_fmt<std::io::Write::write_fmt::Adapter<enum$<test::console::OutputLocation<std::io::stdio::Stdout> > > >
  16:     0x7ff6ac342d93 - _d_inf
  17:     0x7ff6ac2865d6 - _d_inf
  18:     0x7ff6ac8c4e9f - alloc::boxed::impl$44::call_once
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\alloc\src\boxed.rs:1951
  19:     0x7ff6ac8c4e9f - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panic\unwind_safe.rs:271
  20:     0x7ff6ac8c4e9f - std::panicking::try::do_call
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:492
  21:     0x7ff6ac8c4e9f - std::panicking::try
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:456
  22:     0x7ff6ac8c4e9f - std::panic::catch_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panic.rs:137
  23:     0x7ff6ac8c4e9f - test::run_test_in_process
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\test\src\lib.rs:595
  24:     0x7ff6ac8c4e9f - test::run_test::run_test_inner::closure$0
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\test\src\lib.rs:489
  25:     0x7ff6ac8c6ca4 - test::run_test::run_test_inner::closure$1
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\test\src\lib.rs:516
  26:     0x7ff6ac8c6ca4 - std::sys_common::backtrace::__rust_begin_short_backtrace<test::run_test::run_test_inner::closure_env$1,tuple$<> >
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys_common\backtrace.rs:122
  27:     0x7ff6ac8c6945 - std::thread::impl$0::spawn_unchecked_::closure$1::closure$0
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\thread\mod.rs:505
  28:     0x7ff6ac8c6945 - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panic\unwind_safe.rs:271
  29:     0x7ff6ac8c6945 - std::panicking::try::do_call
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:492
  30:     0x7ff6ac8c6945 - std::panicking::try
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:456
  31:     0x7ff6ac8c6945 - std::panic::catch_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panic.rs:137
  32:     0x7ff6ac8c6945 - std::thread::impl$0::spawn_unchecked_::closure$1
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\thread\mod.rs:504
  33:     0x7ff6ac8c6945 - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<test::run_test::run_test_inner::closure_env$1,tuple$<> >,tuple$<> >
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\ops\function.rs:248
  34:     0x7ff6ac895f0b - alloc::boxed::impl$44::call_once
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\alloc\src\boxed.rs:1951
  35:     0x7ff6ac895f0b - alloc::boxed::impl$44::call_once
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\alloc\src\boxed.rs:1951
  36:     0x7ff6ac895f0b - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\sys\windows\thread.rs:56
  37:     0x7ff88fef7974 - BaseThreadInitThunk
  38:     0x7ff89027a2f1 - RtlUserThreadStart


failures:
    integration::worker::worker_terminate_tla_crash
```

**Comment by dsherret** [comment]
Still flaky https://github.com/denoland/deno/actions/runs/3193418551/jobs/5211947955

**Comment by magurotuna** [comment]
Still flaky https://github.com/denoland/deno/actions/runs/3718668155/jobs/6307020794#step:33:3648 (in https://github.com/denoland/deno/pull/17078)

**Comment by dsherret** [comment]
Still flaky https://github.com/denoland/deno/actions/runs/3897639058/jobs/6655515686
