### ISSUE TITLE
fix_exotic_specifiers is flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16042]
Why is this test requesting a remote url?

```
---- integration::run::fix_exotic_specifiers stdout ----
deno_exe path /home/runner/work/deno/deno/target/release/deno
deno_exe args run --quiet --reload run/fix_exotic_specifiers.ts
deno_exe cwd "/home/runner/work/deno/deno/cli/tests/testdata"
OUTPUT
TLS alert received: AlertMessagePayload ***
    level: Fatal,
    description: HandshakeFailure,
***
error: error sending request for url (https://jspm.dev/lodash@4/clone): error trying to connect: received fatal alert: HandshakeFailure
    at file:///home/runner/work/deno/deno/cli/tests/testdata/run/fix_exotic_specifiers.ts:1:19

OUTPUT
thread 'integration::run::fix_exotic_specifiers' panicked at 'bad exit code, expected: 0, actual: 1', test_util/src/lib.rs:1934:9
stack backtrace:
   0:     0x561cd93f818d - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x561cd93f818d - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561cd93f818d - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x561cd93f818d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x561cd942022c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x561cd93f0a21 - std::io::Write::write_fmt::h1da442c9e1df41d6
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x561cd93fa315 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x561cd93fa315 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x561cd93fa315 - std::panicking::default_hook::***closure***::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x561cd93f9fb4 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:311:9
  10:     0x561cd93fa906 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
  11:     0x561cd93fa7f7 - std::panicking::begin_panic_handler::***closure***::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
  12:     0x561cd93f8684 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x561cd93fa529 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  14:     0x561cd941e243 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  15:     0x561cd970b634 - test_util::CheckOutputIntegrationTest::run::h66759d5609a039ab
  16:     0x561cd94942a1 - core::ops::function::FnOnce::call_once::h45a5672db7cde7e5
  17:     0x561cd9387c83 - core::ops::function::FnOnce::call_once::h2da14387562cd1a6
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  18:     0x561cd9387c83 - test::__rust_begin_short_backtrace::h307c198d88e9e51a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/test/src/lib.rs:572:5
  19:     0x561cd9386a8a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h42564b04a6d1df41
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/boxed.rs:1935:9
  20:     0x561cd9386a8a - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h286b0e8427b9af31
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
  21:     0x561cd9386a8a - std::panicking::try::do_call::h0b094c8aa8626e3b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  22:     0x561cd9386a8a - std::panicking::try::h253dd43de0385d2d
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  23:     0x561cd9386a8a - std::panic::catch_unwind::h8a89f69958871bf1
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  24:     0x561cd9386a8a - test::run_test_in_process::h79875496f9bc15c6
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/test/src/lib.rs:595:18
  25:     0x561cd9386a8a - test::run_test::run_test_inner::***closure***::hf979093fbdf02646
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/test/src/lib.rs:489:39
  26:     0x561cd93513ad - test::run_test::run_test_inner::***closure***::he01c2dd4903b57d1
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/test/src/lib.rs:516:37
  27:     0x561cd93513ad - std::sys_common::backtrace::__rust_begin_short_backtrace::hece2f1c514466a0a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:122:18
  28:     0x561cd9356d18 - std::thread::Builder::spawn_unchecked_::***closure***::***closure***::h658be5979f99b3a5
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/mod.rs:505:17
  29:     0x561cd9356d18 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9dbd94372ee944af
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
  30:     0x561cd9356d18 - std::panicking::try::do_call::hff71896f3757c3b2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  31:     0x561cd9356d18 - std::panicking::try::hbb4c2c2616b6a189
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  32:     0x561cd9356d18 - std::panic::catch_unwind::h72f47810ab7e379e
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  33:     0x561cd9356d18 - std::thread::Builder::spawn_unchecked_::***closure***::h6331fb85a785812c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/mod.rs:504:30
  34:     0x561cd9356d18 - core::ops::function::FnOnce::call_once***vtable.shim***::h467656fda03180e5
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  35:     0x561cd9400bd3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h56d5fc072706762b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/boxed.rs:1935:9
  36:     0x561cd9400bd3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h41deef8e33b824bb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/boxed.rs:1935:9
  37:     0x561cd9400bd3 - std::sys::unix::thread::Thread::new::thread_start::ha6436304a1170bba
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys/unix/thread.rs:108:17
  38:     0x7fcda6be8609 - start_thread
  39:     0x7fcda69be133 - clone
  40:                0x0 - <unknown>


failures:
    integration::run::fix_exotic_specifiers
```

https://github.com/denoland/deno/actions/runs/3130627490/jobs/5081078268

**Comment by bartlomieju** [comment]
It seems we don't have this test anymore. Closing.
