### ISSUE TITLE
npm: Not implemented: crypto.Hmac

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno#16107]
I know npm support is still experimental/unstable but I'm guessing issue reports are still helpful. If not I can close.

```ts
import AWS from "npm:aws-sdk";

const lambda = new AWS.Lambda();

await lambda.listFunctions().promise();
```

```output
error: Uncaught Error: Not implemented: crypto.Hmac
  throw new Error(message);
        ^
    at notImplemented (https://deno.land/std@0.158.0/node/_utils.ts:25:9)
    at new Hmac (https://deno.land/std@0.158.0/node/internal/crypto/hash.ts:136:5)
    at Object.createHmac (https://deno.land/std@0.158.0/node/crypto.ts:264:10)
    at Object.hmac (file:///Users/$USER/Library/Caches/deno/npm/registry.npmjs.org/aws-sdk/2.1226.0/lib/util.js:436:30)
    at Object.getSigningKey (file:///Users/$USER/Library/Caches/deno/npm/registry.npmjs.org/aws-sdk/2.1226.0/lib/signers/v4_credentials.js:62:8)
    at V4.signature (file:///Users/$USER/Library/Caches/deno/npm/registry.npmjs.org/aws-sdk/2.1226.0/lib/signers/v4.js:98:36)
    at V4.authorization (file:///Users/$USER/Library/Caches/deno/npm/registry.npmjs.org/aws-sdk/2.1226.0/lib/signers/v4.js:93:36)
    at V4.addAuthorization (file:///Users/$USER/Library/Caches/deno/npm/registry.npmjs.org/aws-sdk/2.1226.0/lib/signers/v4.js:35:12)
    at file:///Users/$USER/Library/Caches/deno/npm/registry.npmjs.org/aws-sdk/2.1226.0/lib/event_listeners.js:299:20
    at finish (file:///Users/$USER/Library/Caches/deno/npm/registry.npmjs.org/aws-sdk/2.1226.0/lib/config.js:396:7)
```

**Comment by cjihrig** [comment]
This is being tracked in https://github.com/denoland/deno_std/issues/2557, so I'll close this out. Thanks for reporting though!
