### ISSUE TITLE
npm compat fs.ReadStream.

### ISSUE THREAD

**Issue by Octo8080X** [denoland/deno#16113]
Hello.

I tried use json-server on Deno.
But,  fs.ReadStream will be not work.
How should we respond?

```sh 
$ deno run -A --unstable npm:json-server --host 0.0.0.0 --port 8000 db.json

  \{^_^}/ hi!

  Loading db.json
  Done

  Resources
  http://0.0.0.0:8000/posts
  http://0.0.0.0:8000/comments
  http://0.0.0.0:8000/profile

  Home
  http://0.0.0.0:8000

  Type s + enter at any time to create a snapshot of the database
Some error occurred Error: Not implemented: fs.ReadStream.prototype.constructor with unsupported options ({"maxage":0,"root":"/deno-dir/npm/registry.npmjs.org/json-server/0.17.0/public","start":0,"end":2056})
    at notImplemented (https://deno.land/std@0.153.0/node/_utils.ts:23:9)
    at new ReadStream (https://deno.land/std@0.153.0/node/_fs/_fs_streams.ts:18:7)
    at Object.createReadStream (https://deno.land/std@0.153.0/node/_fs/_fs_streams.ts:54:10)
    at SendStream.stream (file:///deno-dir/npm/registry.npmjs.org/send/0.18.0/index.js:790:19)
    at SendStream.send (file:///deno-dir/npm/registry.npmjs.org/send/0.18.0/index.js:703:8)
    at file:///deno-dir/npm/registry.npmjs.org/send/0.18.0/index.js:770:12
    at Deno.stat.then.denoErrorToNodeError.syscall (https://deno.land/std@0.153.0/node/_fs/_fs_stat.ts:274:15)
```

Best regards.

**Comment by cjihrig** [comment]
Can you try upgrading to a newer version. I see `std@0.153.0` in your stack trace. We are up to 0.158.0 now, with a number of improvements to the Node `fs` streams particularly. I just tried your example with the latest version of Deno, and it worked for me.
