### ISSUE TITLE
ffmpeg import via npm: specifiers fails with 'Invalid URL'

### ISSUE THREAD

**Issue by andykais** [denoland/deno#16139]
simple repro script:
`deno run --unstable --allow-read mod.ts`
```ts
import ffmpegCore from 'npm:@ffmpeg/core'
import { createFFmpeg, fetchFile } from 'npm:@ffmpeg/ffmpeg'

const ffmpeg = createFFmpeg({ log: true })
await ffmpeg.load();
```

```
[info] use ffmpeg.wasm v0.11.5
[info] load ffmpeg-core
[info] loading ffmpeg-core
✅ Granted read access to <main_module>.
[fferr] TypeError: Invalid URL
error: Uncaught RuntimeError: abort(TypeError: Invalid URL). Build with -s ASSERTIONS=1 for more info.
    at process.u (file:///Users/andrew.kaiser/Library/Caches/deno/npm/registry.npmjs.org/@ffmpeg/core/0.11.0/dist/ffmpeg-core.js:25:109)
    at process.emit (https://deno.land/std@0.158.0/node/_events.mjs:379:28)
    at process.emit (https://deno.land/std@0.158.0/node/process.ts:435:20)
    at https://deno.land/std@0.158.0/node/process.ts:301:15
    at innerInvokeEventListeners (deno:ext/web/02_event.js:755:9)
    at invokeEventListeners (deno:ext/web/02_event.js:795:7)
    at dispatch (deno:ext/web/02_event.js:664:11)
    at dispatchEvent (deno:ext/web/02_event.js:1043:14)
    at promiseRejectMacrotaskCallback (deno:runtime/js/99_main.js:633:18)
```

`deno --version` output:
```
deno 1.26.0 (release, aarch64-apple-darwin)
v8 10.7.193.3
typescript 4.8.3
```

(tangentially related, we have been working through some of the runtime issues with ffmpeg-wasm running in deno here https://github.com/ffmpegwasm/ffmpeg.wasm/issues/110)

**Comment by FuriouZz** [comment]
I actually fixed the URL issue by giving `corePath` and rewrite ffmpeg.wasm to support `wasmPath` in node environment.

But now the program crash on `ffmpeg.run` with this error

```zsh
error: Uncaught RuntimeError: abort(RangeError: Maximum call stack size exceeded). Build with -s ASSERTIONS=1 for more info.
    at process.u (file:///Users/username/path/node_modules/.deno/@ffmpeg+core@0.11.0/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:25:109)
    at process.emit (https://deno.land/std@0.166.0/node/_events.mjs:379:28)
    at process.emit (https://deno.land/std@0.166.0/node/process.ts:496:20)
    at https://deno.land/std@0.166.0/node/process.ts:362:15
    at innerInvokeEventListeners (deno:ext/web/02_event.js:755:9)
    at invokeEventListeners (deno:ext/web/02_event.js:795:7)
    at dispatch (deno:ext/web/02_event.js:664:11)
    at dispatchEvent (deno:ext/web/02_event.js:1043:14)
    at promiseRejectMacrotaskCallback (deno:runtime/js/99_main.js:377:18)
```

```ts
import "npm:@ffmpeg/core";
import { createFFmpeg, fetchFile } from "npm:@ffmpeg/ffmpeg";

const FFmpegCoreLocation = join(
  dirname(import.meta.url),
  "./node_modules/@ffmpeg/core/dist/ffmpeg-core.js"
).replace("file:", "");

const FFmpegWasmLocation = join(
  dirname(import.meta.url),
  "./node_modules/@ffmpeg/core/dist/ffmpeg-core.wasm"
);

const ffmpeg = createFFmpeg({
  corePath: FFmpegCoreLocation,
  wasmPath: FFmpegWasmLocation,
});

await ffmpeg.load();

const uint8 = Deno.readFileSync("./static/video.mp4");

ffmpeg.FS("writeFile", "input.mp4", uint8);

// Convert video to image sequence
await ffmpeg.run(
  "-i",
  "input.mp4",
  "-vf",
  "fps=1",
  "out%d.png"
);

const dir = ffmpeg.FS("readdir", "/");
console.log(dir);
```

**Comment by bartlomieju** [comment]
This is no longer a Deno-specific issue and can be closed.

Re-tested on current canary (Deno 2.8.1). The `TypeError: Invalid URL` still
reproduces, but **stock Node.js 24 now fails identically**:

```
# Deno
[fferr] TypeError: Invalid URL: '.../@ffmpeg/core/dist/ffmpeg-core.wasm'
# Node 24
Error: Failed to parse URL from .../@ffmpeg/core/dist/ffmpeg-core.wasm
```

**Root cause** is in `@ffmpeg/core@0.11`'s (old) emscripten loader, which picks
its wasm-loading strategy roughly like this:

```js
return wasmBinary
  || typeof WebAssembly.instantiateStreaming !== "function"
  || isDataURL() || startsWith("file://")
  || typeof fetch !== "function"
  ? syncFsRead()              // safe: fs.readFileSync
  : fetch(barePath, {...})    // fetch('/abs/path/ffmpeg-core.wasm')
```

The wasm path is a bare absolute filesystem path (not a `file://` URL). When the
runtime exposes both global `fetch` and `WebAssembly.instantiateStreaming`, every
guard is false, so the loader calls `fetch('/abs/path')`, which throws because
`fetch` requires a valid URL.

When this issue was filed (2022), Node 16 was current and had **no** global
`fetch`, so Node took the safe `fs.readFileSync` branch while Deno (which already
had global `fetch`) took the broken one. Node 18+ now also ships global `fetch`,
so both runtimes hit the same path. This is not something Deno can fix in the
runtime: making `fetch` accept bare filesystem paths would violate the spec, and
Node doesn't do it either.

Resolution is on the user side: upgrade to `@ffmpeg/ffmpeg@0.12+`, which was
rewritten and no longer uses this loader pattern (`@ffmpeg/core@0.11` is simply
old emscripten output).

Closing as obsolete.
