### ISSUE TITLE
Deno compile panicked with octokit query parameter import

### ISSUE THREAD

**Issue by ideadapt** [denoland/deno#16155]
Stacktrace:

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.26.0
Args: ["deno", "compile", "--allow-read", "--allow-net", "--allow-env", "./main.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Missing(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("cdn.skypack.dev")), port: None, path: "/-/aws-lambda@v1.0.7-1Ur26iuIfIR0rJkZpPTF/dist=es2019,mode=types/trigger/cognito-user-pool-trigger/.d.ts", query: None, fragment: None })', cli/main.rs:256:17
stack backtrace:
Download ⠧ https://cdn.skypack.dev/-/aws-lambda@v1.0.7-1Ur26iuIfIR0rJkZpPTF/dist=es2019,mode=types/trigger/cognito-user-pool-trigger/.d.ts  0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: deno::compile_command::{{closure}}
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: deno::main::{{closure}}
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: deno_runtime::tokio_util::run_local
   8: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

At first sight, the file name in the URL looks suspicious (.d.ts)

If I remove the ?dts query parameter from my octokit import, everything works fine. This is my import statement: `import { Octokit } from "https://cdn.skypack.dev/octokit?dts";`

**Comment by dsherret** [comment]
This looks like #16132. It seems skypack is returning that one of the dependency urls can't be found:

https://cdn.skypack.dev/-/aws-lambda@v1.0.7-1Ur26iuIfIR0rJkZpPTF/dist=es2019,mode=types/trigger/cognito-user-pool-trigger/.d.ts
