### ISSUE TITLE
How to import a node module that depends on a module with a path of ".."?

### ISSUE THREAD

**Issue by wallace-eduardo** [denoland/deno#16245]
Hi I am new to deno, I am trying to import a node module to use snowflake, I am using deno 1.26.1.

I tried using esm.sh:
```
import { Snowflake } from 'https://esm.sh/snowflake-promise'//;
```
I get the following error after a deno run:
```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at https://esm.sh/v96/readable-stream@3.6.0/deno/lib/_stream_duplex.js:2:1360
    at https://esm.sh/v96/readable-stream@3.6.0/deno/lib/_stream_duplex.js:2:810
    at https://esm.sh/v96/readable-stream@3.6.0/deno/lib/_stream_duplex.js:2:2549
```
I tried skypack:
```
import snowflakePromise from 'https://cdn.skypack.dev/snowflake-promise@4.5.0';
```
I get the following error after a deno run:
```
error: Relative import path ".." not prefixed with / or ./ or ../
    at https://cdn.skypack.dev/-/winston-transport@v4.4.0-BtLGcov7GHKlyCf57AV4/dist=es2019,mode=imports/unoptimized/legacy.js:3:29
```
`deno vendor` did not change the error.
I looked at the file skypack is complaining about and It looks like it does not like this line:
```
import TransportStream from "..";
```
Is there anything I can do about it? Can I create an import map to tell deno the correct path? Thanks in advance.

**Comment by wallace-eduardo** [comment]
Still no luck, my command line
```
 deno run --allow-read --allow-env --allow-net --unstable --allow-write --allow-sys main.ts
```
my code, everything else is commented out
```typescript
import { Snowflake } from 'npm:snowflake-promise'

const snowflake = new Snowflake({
    account: Deno.env.get('SNOWFLAKE_ACCOUNT')!,
    username: Deno.env.get('SNOWFLAKE_USERNAME')!,
    password: Deno.env.get('SNOWFLAKE_PASSWORD'),
    database: Deno.env.get('SNOWFLAKE_DATABASE'),
    schema: Deno.env.get('SNOWFLAKE_SCHEMA'),
    warehouse: Deno.env.get('SNOWFLAKE_WAREHOUSE')
})

    await snowflake.connect()
```
this code works fine in typescript + node, but here I get the error
```
error: Uncaught TypeError: Class constructor Agent cannot be invoked without 'new'
    at Object.HttpsOcspAgent [as agentClass] (file:///C:/Users/Wallace/AppData/Local/deno/npm/registry.npmjs.org/snowflake-sdk/1.6.14/lib/agent/https_ocsp_agent.js:19:26)
    at NodeHttpClient.sendRequest (file:///C:/Users/Wallace/AppData/Local/deno/npm/registry.npmjs.org/snowflake-sdk/1.6.14/lib/http/base.js:94:54)
    at file:///C:/Users/Wallace/AppData/Local/deno/npm/registry.npmjs.org/snowflake-sdk/1.6.14/lib/http/base.js:141:7
    at Gzip.onEnd (https://deno.land/std@0.159.0/node/_zlib.mjs:191:5)
    at Gzip.emit (https://deno.land/std@0.159.0/node/_events.mjs:391:35)
    at of (https://deno.land/std@0.159.0/node/_stream.mjs:10:43074)
    at processTicksAndRejections (https://deno.land/std@0.159.0/node/_next_tick.ts:41:15)
```
right after I uncomment the line
```typescript
    await snowflake.connect()
```

**Comment by wallace-eduardo** [comment]
Since this issue is very specific to the lib and not to deno itself I am going to close the issue, on a personal not for my small project I reverted back to not because that lib is crucial and the http api was too cumbersome to use.
