### ISSUE TITLE
npm: Prisma Studio does not work / does not load pages

### ISSUE THREAD

**Issue by janpio** [denoland/deno#16282]
When in a working Prisma project that can run Prisma Studio via `npx prisma studio`, calling the equivalent command via deno CLI `deno run -A --unstable npm:prisma@4.4.0-integration-feat-deno-deploy.1 studio` does not succeed:

(This is with `DEBUG=*` for all the log output)

```
PS C:\Users\Jan\Documents\throwaway\denoTest> deno run -A --unstable npm:prisma@4.4.0-integration-feat-deno-deploy.1 studio            
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\denoTest\package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\denoTest\.env +0ms
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\@prisma\engines\4.4.0-integration-feat-deno-deploy.1\query_engine-windows.dll.node +0ms
napi_add_env_cleanup_hook is currently not supported
  prisma:getConfig  Loaded Node-API Library +8ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +2ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\denoTest\package.json +18ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\denoTest\.env +16ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\denoTest\package.json +17ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\denoTest\.env +19ms
  prisma:studio-pcw [constructor] {
  resolve: {
    '@prisma/client': 'C:\\Users\\Jan\\AppData\\Local\\deno\\npm\\registry.npmjs.org\\prisma\\4.4.0-integration-feat-deno-deploy.1\\prisma-client\\index.js'
  }
} +0ms
  prisma:studio-server Starting Studio server +0ms
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +1ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +1ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +1ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +1ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to 'C:\\Users\\Jan\\Documents\\throwaway\\denoTest\\views' +1ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +2ms
  express:router:layer new '/' +1ms
  express:router use '/' expressInit +0ms
  express:router:layer new '/' +1ms
  express:router use '/' textParser +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +1ms
  express:router use '/' serveStatic +1ms
  express:router:layer new '/' +1ms
  express:router:route new '/api' +0ms
  express:router:layer new '/api' +1ms
  express:router:route post '/api' +1ms
  express:router:layer new '/' +0ms
  prisma:cli  AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
    at Object.runMicrotasks (deno:core/01_core.js:336:30)
    at processTicksAndRejections (https://deno.land/std@0.159.0/node/_next_tick.ts:62:10) {
  code: 'EADDRINUSE'
} +0ms
Prisma Studio is up on http://localhost:5555
```

For the default port `5555` it reports that it already is in use, which it definitely is not. (Our success message should probably only be shown when it actually started successfully... ahem.)

Any other port it can start, but I either still get an instant error in the browser or it seems to load the HTML page but then none of its content. The browser just keeps spinning forever and the log indicate no further activity:
```
PS C:\Users\Jan\Documents\throwaway\denoTest> deno run -A --unstable npm:prisma@4.4.0-integration-feat-deno-deploy.1 studio --port 5678
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\denoTest\package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\denoTest\.env +0ms
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\@prisma\engines\4.4.0-integration-feat-deno-deploy.1\query_engine-windows.dll.node +0ms
napi_add_env_cleanup_hook is currently not supported
  prisma:getConfig  Loaded Node-API Library +3ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +1ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\denoTest\package.json +12ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\denoTest\.env +11ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\denoTest\package.json +4ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\denoTest\.env +4ms
  prisma:studio-pcw [constructor] {
  resolve: {
    '@prisma/client': 'C:\\Users\\Jan\\AppData\\Local\\deno\\npm\\registry.npmjs.org\\prisma\\4.4.0-integration-feat-deno-deploy.1\\prisma-client\\index.js'
  }
} +0ms
  prisma:studio-server Starting Studio server +0ms
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +0ms
  express:application set "etag fn" to [Function: generateETag] +1ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +1ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +1ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to 'C:\\Users\\Jan\\Documents\\throwaway\\denoTest\\views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +1ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +0ms
  express:router use '/' textParser +1ms
  express:router:layer new '/' +2ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +1ms
  express:router use '/' serveStatic +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/api' +0ms
  express:router:layer new '/api' +0ms
  express:router:route post '/api' +1ms
  express:router:layer new '/' +0ms
  prisma:studio-server Studio server is up at http://0.0.0.0:5678/ +16ms
Prisma Studio is up on http://localhost:5678
  prisma:cli  TypeError: child.disconnect is not a function
    at check (file:///C:/Users/Jan/AppData/Local/deno/npm/registry.npmjs.org/prisma/4.4.0-integration-feat-deno-deploy.1/build/index.js:84951:15) +0ms
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\@prisma\engines\4.4.0-integration-feat-deno-deploy.1\query_engine-windows.dll.node +2s
  prisma:getConfig  Loaded Node-API Library +3ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +6ms
  express:router dispatching GET / +3s
  express:router query  : / +5ms
  express:router expressInit  : / +2ms
  express:router textParser  : / +1ms
  body-parser:text skip empty body +4ms
  express:router <anonymous>  : / +0ms
  express:router serveStatic  : / +1ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\pages\http\databrowser.html" +3ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\pages\http\databrowser.html" +4ms
  send accept ranges +2ms
  send content-type text/html +1ms
  express:router dispatching GET /http/databrowser.js +154ms
  express:router query  : /http/databrowser.js +0ms
  express:router expressInit  : /http/databrowser.js +1ms
  express:router textParser  : /http/databrowser.js +0ms
  body-parser:text skip empty body +1ms
  express:router <anonymous>  : /http/databrowser.js +0ms
  express:router serveStatic  : /http/databrowser.js +1ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\http\databrowser.js" +0ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\http\databrowser.js" +3ms
  send accept ranges +2ms
  send content-type application/javascript +2ms
  express:router dispatching GET /index.css +73ms
  express:router query  : /index.css +1ms
  express:router expressInit  : /index.css +0ms
  express:router textParser  : /index.css +1ms
  body-parser:text skip empty body +0ms
  express:router <anonymous>  : /index.css +1ms
  express:router serveStatic  : /index.css +0ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\index.css" +1ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\index.css" +1ms
  send accept ranges +0ms
  send content-type text/css +0ms
  express:router dispatching GET /assets/index.js +228ms
  express:router query  : /assets/index.js +0ms
  express:router expressInit  : /assets/index.js +1ms
  express:router textParser  : /assets/index.js +0ms
  body-parser:text skip empty body +0ms
  express:router <anonymous>  : /assets/index.js +1ms
  express:router serveStatic  : /assets/index.js +0ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\assets\index.js" +0ms
  express:router dispatching GET /assets/vendor.js +1ms
  express:router query  : /assets/vendor.js +0ms
  express:router expressInit  : /assets/vendor.js +1ms
  express:router textParser  : /assets/vendor.js +0ms
  body-parser:text skip empty body +1ms
  express:router <anonymous>  : /assets/vendor.js +0ms
  express:router serveStatic  : /assets/vendor.js +0ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\assets\vendor.js" +1ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\assets\index.js" +1ms
  send accept ranges +0ms
  send content-type application/javascript +1ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\assets\vendor.js" +1ms
  send accept ranges +0ms
  send content-type application/javascript +1ms
  express:router dispatching GET / +3m
  express:router query  : / +2ms
  express:router expressInit  : / +1ms
  express:router textParser  : / +1ms
  body-parser:text skip empty body +6ms
  express:router <anonymous>  : / +2ms
  express:router serveStatic  : / +3ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\pages\http\databrowser.html" +11ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\pages\http\databrowser.html" +7ms
  send accept ranges +1ms
  send content-type text/html +2ms
  express:router dispatching GET / +7s
  express:router query  : / +1ms
  express:router expressInit  : / +0ms
  express:router textParser  : / +1ms
  body-parser:text skip empty body +0ms
  express:router <anonymous>  : / +1ms
  express:router serveStatic  : / +0ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\pages\http\databrowser.html" +0ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\pages\http\databrowser.html" +1ms
  send accept ranges +1ms
  send content-type text/html +0ms
  express:router dispatching GET /http/databrowser.js +75ms
  express:router query  : /http/databrowser.js +2ms
  express:router expressInit  : /http/databrowser.js +1ms
  express:router textParser  : /http/databrowser.js +1ms
  body-parser:text skip empty body +2ms
  express:router <anonymous>  : /http/databrowser.js +1ms
  express:router serveStatic  : /http/databrowser.js +2ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\http\databrowser.js" +0ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\http\databrowser.js" +3ms
  send accept ranges +2ms
  send content-type application/javascript +4ms
  express:router dispatching GET /index.css +162ms
  express:router query  : /index.css +0ms
  express:router expressInit  : /index.css +0ms
  express:router textParser  : /index.css +1ms
  body-parser:text skip empty body +0ms
  express:router <anonymous>  : /index.css +1ms
  express:router serveStatic  : /index.css +0ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\index.css" +0ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\index.css" +2ms
  send accept ranges +0ms
  send content-type text/css +0ms
  express:router dispatching GET /assets/index.js +138ms
  express:router query  : /assets/index.js +1ms
  express:router expressInit  : /assets/index.js +0ms
  express:router textParser  : /assets/index.js +0ms
  body-parser:text skip empty body +1ms
  express:router <anonymous>  : /assets/index.js +0ms
  express:router serveStatic  : /assets/index.js +0ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\assets\index.js" +1ms
  express:router dispatching GET /assets/vendor.js +0ms
  express:router query  : /assets/vendor.js +0ms
  express:router expressInit  : /assets/vendor.js +1ms
  express:router textParser  : /assets/vendor.js +0ms
  body-parser:text skip empty body +0ms
  express:router <anonymous>  : /assets/vendor.js +0ms
  express:router serveStatic  : /assets/vendor.js +1ms
  send stat "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\assets\vendor.js" +0ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\assets\index.js" +1ms
  send accept ranges +0ms
  send content-type application/javascript +0ms
  send pipe "C:\Users\Jan\AppData\Local\deno\npm\registry.npmjs.org\prisma\4.4.0-integration-feat-deno-deploy.1\build\public\assets\vendor.js" +1ms
  send accept ranges +1ms
  send content-type application/javascript +0ms
```

Something is amiss here.

---

```
> deno --version
deno 1.26.1 (release, x86_64-pc-windows-msvc)
v8 10.7.193.3
typescript 4.8.3
```

**Comment by kt3k** [comment]
prisma studio should work with the following command with Deno v1.28.

```
deno run -A --node-modules-dir --unstable npm:prisma@4.6.1 studio
```
