### ISSUE TITLE
panic: `Custom error class must have a builder registered`

### ISSUE THREAD

**Issue by mxcl** [denoland/deno#16418]
We're getting the following crashes for compiled and interpreted code.

If I revert to deno 1.22 they stop.

It happens while executing other processes with `Deno.run`. It consistently happens only when running in a docker instance of `debian:buster-slim`

We probably can get a test case if required, but not until next week probs.

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.26.2
Args: ["deno", "run", "--allow-read", "--allow-write", "--allow-net", "--allow-run", "--allow-env", "--unstable", "--import-map=/__w/cli/cli/import-map.json", "/__w/cli/cli/src/app.ts", "+curl.se", "curl", "-L", "tea.xyz/white-paper/"]

thread 'main' panicked at 'Custom error class must have a builder registered', core/error.rs:116:6
stack backtrace:

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.26.2
Args: ["deno", "run", "--allow-read", "--allow-write", "--allow-net", "--allow-run", "--allow-env", "--unstable", "--import-map=/__w/cli/cli/import-map.json", "/__w/cli/cli/src/app.ts", "+charm.sh/glow", "glow", "-"]

thread 'main' panicked at 'Custom error class must have a builder registered', core/error.rs:116:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:1874:5
   5: deno_core::error::to_v8_error
   6: deno_runtime::ops::fs::op_stat_sync::v8_func
   7: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
   8: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
             at ./../../../../v8/src/builtins/builtins-api.cc:112:36
   9: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
             at ./../../../../v8/src/builtins/builtins-api.cc:130:1
  10: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:1874:5
   5: deno_core::error::to_v8_error
   6: deno_runtime::ops::fs::op_stat_sync::v8_func
   7: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
   8: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
             at ./../../../../v8/src/builtins/builtins-api.cc:112:36
   9: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
             at ./../../../../v8/src/builtins/builtins-api.cc:130:1
  10: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mxcl** [comment]
You added the needs info label, but what specifically did I not provide?

**Comment by mxcl** [comment]
Probs fixed or our workarounds are enough.
