### ISSUE TITLE
napi_register_module_v1 not found

### ISSUE THREAD

**Issue by blackmius** [denoland/deno#16459]
I tried to run [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js) which is bindings to c++ uws on napi and got this traceback

```
Platform: linux x86_64
Version: 1.27.0
Args: ["deno", "run", "--unstable", "-A", "index.ts"]

thread 'main' panicked at 'napi_register_module_v1 not found: DlSym { desc: "/home/blackmius/projects/denouws/uws_linux_x64_108.node: undefined symbol: napi_register_module_v1" }', /home/runner/work/deno/deno/ext/napi/lib.rs:596:14
stack backtrace:
   0:     0x564087e2bf6d - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x564087e2bf6d - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564087e2bf6d - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x564087e2bf6d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x564087e57ecc - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x564087e23721 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x564087e2dcc5 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x564087e2dcc5 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x564087e2dcc5 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x564087e2d9e1 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x5640881e6f4a - deno::setup_panic_hook::{{closure}}::haa5e598db939d339
  11:     0x564087e2e36a - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:702:17
  12:     0x564087e2e1a7 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
  13:     0x564087e2c464 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x564087e2ded9 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  15:     0x564087e552b3 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  16:     0x564087e555c3 - core::result::unwrap_failed::h42ad8e915aa0a906
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
  17:     0x5640886fb0d7 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h6fb436c8c9b8bb7b
  18:     0x564086e6e935 - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
                               at ./../../../../v8/src/builtins/builtins-api.cc:112:36
  19:     0x564086e6dd26 - _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
                               at ./../../../../v8/src/builtins/builtins-api.cc:130:1
  20:     0x564087d1c3b8 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
  ```
  
  How to reproduce
``` shell
yarn add uWebSockets.js@uNetworking/uWebSockets.js#v20.10.0
```
``` ts
// index.ts
import { createRequire } from "https://deno.land/std@0.161.0/node/module.ts";
const require = createRequire(import.meta.url);
const uws = require('./node_modules/uWebSockets.js/uws_linux_x64_108.node')
```

**Comment by bartlomieju** [comment]
CC @littledivy

**Comment by littledivy** [comment]
uWebSocket.js does not use Node-API. It's using V8 & Node internal symbols directly which we cannot support https://github.com/uNetworking/uWebSockets.js/blob/master/src/addon.cpp#L26-L27
