### ISSUE TITLE
Sass Support

### ISSUE THREAD

**Issue by vikaskaliramna** [denoland/deno#16480]
[Sass Lang](https://sass-lang.com/)

Currently there is a Uri.base error which occurs due to window.location. I tried to fix it and that error was fixed with 4-5 lines of code but Deno panicked.

Support Sass CLI and Sass JavaScript API would be great. Importing StyleSheet within frameworks like Fresh or Aleph.
It would also allow processing sass content with PostCSS after sass support

**Comment by crowlKats** [comment]
> but Deno panicked

What is the panic?

**Comment by vikaskaliramna** [comment]
Sorry for delay. I am not sure the code I wrote was correct or not but the previous error was not showing so I guess it was doing the right job.


The Panic I got
```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.27.0
Args: ["deno", "run", "-A", "--unstable", "compile.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\a\deno\deno\serde_v8\de.rs:573:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```



The Code I wrote

```ts

import SassLang from 'npm:sass@latest';


window.location = {
	href : Deno.cwd()
};


const Content = await SassLang.compile('Package/Common.scss');
console.log(Content);

```

**Comment by jrson83** [comment]
The [denosass](https://deno.land/x/denosass@1.0.4) module is not maintained well and lacks many features, but binyamin created [deno-sass](https://github.com/binyamin/deno-sass), a wrapper for [dart-sass](https://github.com/sass/dart-sass), which works flawless (also with @use & @forward).

**Comment by vikaskaliramna** [comment]
I used the deno-sass wrapper created by binyamin.

And I am still facing Uri.base error.

**Comment by jrson83** [comment]
> I used the deno-sass wrapper created by binyamin.
> 
> And I am still facing Uri.base error.

Did you use the synchronous API?

**Comment by oscarotero** [comment]
I'm trying to use the official NPM Sass package and have the same issue:

```ts
// main.js

import sass from "npm:sass";

const code = sass.compile("styles.scss", {
  includePaths: [import.meta.resolve("./_includes")]
});

console.log(code);
```

```scss
// styles.scss

@import "vars.sass";

body {
  font: 100% $font-stack;
  color: $primary-color;
}
```

```scss
// _includes/vars.sass

$font-stack: Helvetica, sans-serif;
$primary-color: #333;
```

It seems that sass depends on a value in `window.location`, so I need to run with `--location`:

```
deno run -A --location="https://deno.land" main.js

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.28.2
Args: ["deno", "run", "-A", "--location=https://deno.land", "main.js"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/work/deno/deno/serde_v8/de.rs:573:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jiawei397** [comment]
I also have this problem now. Does Deno have a plan to repair it?

**Comment by oscarotero** [comment]
@jiawei397 The problem is SASS detects Deno as if it was in a browser environment instead of Node, because only check if the `window` object exists (and Deno has `window`).

You can use [@lumeland/sass](https://www.npmjs.com/package/@lumeland/sass), that contains the same code as the official sass package but including a fix in this detection, so it works on Deno.

**Comment by jiawei397** [comment]
> @jiawei397 The problem is SASS detects Deno as if it was in a browser environment instead of Node, because only check if the `window` object exists (and Deno has `window`).
> 
> You can use [@lumeland/sass](https://www.npmjs.com/package/@lumeland/sass), that contains the same code as the official sass package but including a fix in this detection, so it works on Deno.

Thank you very much. This has helped me a lot.
