### ISSUE TITLE
Cannot import knex via npm specifier

### ISSUE THREAD

**Issue by akatechis** [denoland/deno#16495]
Specifically, I'm attempting to import `knex` via "npm:knex@2.3.0", and I **suspect** the issue is native modules. Not sure if there's an existing issue for that, or if it's even planned to support such packages that depend on native modules, but here goes.

In the output below, it breaks trying to install `sqlite3` which according to its README, is a C++ addon for node (https://github.com/TryGhost/node-sqlite3/blob/master/README.md#features)

# Repro Example

```typescript
// knexample.ts
import { knex } from "npm:knex@2.3.0";

const q = knex("postgres").queryBuilder()
  .select("*")
  .table("users")
  .where({ name: "alex" })
  .toQuery();

console.log(q);
```

```sh
$ deno run --unstable -A knexample.ts
```

# Output

```
Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack:
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\dialects\sqlite3\index.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\dialects\index.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\knex-builder\internal\config-resolver.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\knex-builder\Knex.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\index.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\knex.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\knex.js
Error: Cannot find module 'sqlite3'
Require stack:
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\dialects\sqlite3\index.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\dialects\index.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\knex-builder\internal\config-resolver.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\knex-builder\Knex.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\index.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\knex.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\knex.js
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:613:17)
    at Function.Module._load (deno:ext/node/02_require.js:445:29)
    at Module.require (deno:ext/node/02_require.js:656:21)
    at require (deno:ext/node/02_require.js:790:18)
    at Client_SQLite3._driver (file:///C:/Users/Alexandros/AppData/Local/deno/npm/registry.npmjs.org/knex/2.3.0/lib/dialects/sqlite3/index.js:42:12)
    at Client_SQLite3.initializeDriver (file:///C:/Users/Alexandros/AppData/Local/deno/npm/registry.npmjs.org/knex/2.3.0/lib/client.js:190:26)
    at new Client (file:///C:/Users/Alexandros/AppData/Local/deno/npm/registry.npmjs.org/knex/2.3.0/lib/client.js:75:12)
    at new Client_SQLite3 (file:///C:/Users/Alexandros/AppData/Local/deno/npm/registry.npmjs.org/knex/2.3.0/lib/dialects/sqlite3/index.js:22:5)
    at Function.knex (file:///C:/Users/Alexandros/AppData/Local/deno/npm/registry.npmjs.org/knex/2.3.0/lib/knex-builder/Knex.js:16:28)
    at file:///C:/Users/Alexandros/workspace/boxesandlines/knexample.ts:3:16
error: Uncaught Error: Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack:
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\dialects\sqlite3\index.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\dialects\index.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\knex-builder\internal\config-resolver.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\knex-builder\Knex.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\lib\index.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\knex.js
- C:\Users\Alexandros\AppData\Local\deno\npm\registry.npmjs.org\knex\2.3.0\knex.js
    at Client_SQLite3.initializeDriver (file:///C:/Users/Alexandros/AppData/Local/deno/npm/registry.npmjs.org/knex/2.3.0/lib/client.js:194:13)
    at new Client (file:///C:/Users/Alexandros/AppData/Local/deno/npm/registry.npmjs.org/knex/2.3.0/lib/client.js:75:12)
    at new Client_SQLite3 (file:///C:/Users/Alexandros/AppData/Local/deno/npm/registry.npmjs.org/knex/2.3.0/lib/dialects/sqlite3/index.js:22:5)
    at Function.knex (file:///C:/Users/Alexandros/AppData/Local/deno/npm/registry.npmjs.org/knex/2.3.0/lib/knex-builder/Knex.js:16:28)
    at file:///C:/Users/Alexandros/workspace/boxesandlines/knexample.ts:3:16
```

**Comment by bartlomieju** [comment]
Does `sqlite3` require a "postinstall" script?

**Comment by akatechis** [comment]
It doesn't seem so:

```json
  "scripts": {
    "build": "node-pre-gyp build",
    "build:debug": "node-pre-gyp build --debug",
    "install": "node-pre-gyp install --fallback-to-build",
    "pretest": "node test/support/createdb.js",
    "test": "mocha -R spec --timeout 480000",
    "pack": "node-pre-gyp package"
  }
```

**Comment by dsherret** [comment]
This is peer dependencies not being supported yet. I'm working on it this week.

**Comment by dsherret** [comment]
Actually, looking at the source here, it seems these peer dependencies are marked as optional, so Deno would never warn about them not being set. Also, I'm not sure why knex is trying to import sqlite when specifying postgres. I'm able to get further by adding an import for sqlite3 (`import "npm:sqlite3@5";`) and using a node_modules directory (`--node-modules-dir`), but then it errors because of #15611.

**Comment by bombillazo** [comment]
Any update on being able to run knex with deno?

**Comment by marvinhagemeister** [comment]
Knex can be used with Deno today. The error shown here happens in Node to. Knex requires a database driver to be installed manually, regardless of the runtime you're using, see their installation instructions https://knexjs.org/guide/#node-js

> ```sh
> $ npm install knex --save
> ```
>
> Then add one of the following (adding a --save) flag:
> ```sh
> $ npm install pg
> $ npm install pg-native
> $ npm install sqlite3
> $ npm install better-sqlite3
> $ npm install mysql
> $ npm install mysql2
> $ npm install oracledb
> $ npm install tedious
> ```

Swap the `npm install <package>` with `deno install npm:<package>` if you want to use Deno to install the dependencies. If you want to use `sqlite3` that would be:

```sh
deno install npm:knex npm:sqlite3
```

Then to be able to use `knex` with ESM in either Node or Deno, the import statement needs to be changed because the `knex` module doesn't have any named exports.

```diff
- import { knex } from "npm:knex@2.3.0";
+ import knex from "knex";
```

Marking the issue as resolved as it works in Deno now.
