### ISSUE TITLE
Svelte support via Vite

### ISSUE THREAD

**Issue by lambtron** [denoland/deno#16513]
Running into a `TypeError` when trying to add an import statement in `vite.config.mjs`. I'm on MacOS Intel i5.

Reproduce:

1. Run `deno run -A --unstable npm:create-vite-extra` and selecting `deno-svelte`
2. Update `vite.config.mjs` to 

```
import { defineConfig } from 'npm:vite'
import { svelte } from 'npm:@sveltejs/vite-plugin-svelte'

import "npm:svelte";
import "npm:svelte-routing";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte()]
})
```

3. Run `dev deno run -A --unstable --node-modules-dir npm:vite`

Error message:

```
failed to load config from /Users/andyjiang/Developer/deno/blog/how-to-series/svelte/vite.config.mjs
error when starting dev server:
TypeError: 'import', and 'export' cannot be used outside of module code at file:///Users/andyjiang/Developer/deno/blog/how-to-series/svelte/node_modules/.deno/svelte-routing@1.6.0/node_modules/svelte-routing/src/index.js:1:1
    at async loadConfigFromBundledFile (file:///Users/andyjiang/Developer/deno/blog/how-to-series/svelte/node_modules/.deno/vite@3.2.2/node_modules/vite/dist/node/chunks/dep-c842e491.js:64010:21)
    at async loadConfigFromFile (file:///Users/andyjiang/Developer/deno/blog/how-to-series/svelte/node_modules/.deno/vite@3.2.2/node_modules/vite/dist/node/chunks/dep-c842e491.js:63895:28)
    at async resolveConfig (file:///Users/andyjiang/Developer/deno/blog/how-to-series/svelte/node_modules/.deno/vite@3.2.2/node_modules/vite/dist/node/chunks/dep-c842e491.js:63519:28)
    at async createServer (file:///Users/andyjiang/Developer/deno/blog/how-to-series/svelte/node_modules/.deno/vite@3.2.2/node_modules/vite/dist/node/chunks/dep-c842e491.js:62819:20)
    at async CAC.<anonymous> (file:///Users/andyjiang/Developer/deno/blog/how-to-series/svelte/node_modules/.deno/vite@3.2.2/node_modules/vite/dist/node/cli.js:707:24)
```

**Comment by birkskyum** [comment]
This is only breaking for me because of the "npm:svelte-routing" now. It's running if I don't alter the vite.config
