### ISSUE TITLE
thread 'main' panicked at 'Only a single use of this resource should happen: FullDuplexResource

### ISSUE THREAD

**Issue by simonstead** [denoland/deno#16528]
Rebooted my (Retina, 15-inch, Mid 2015) mac today and since then every time i try to build my docker container containing my deno api i see this

```
api_1  | Deno has panicked. This is a bug in Deno. Please report this
api_1  | at https://github.com/denoland/deno/issues/new.
api_1  | If you can reliably reproduce this panic, include the
api_1  | reproduction steps and re-run with the RUST_BACKTRACE=1 env
api_1  | var set and include the backtrace in your report.
api_1  | 
api_1  | Platform: linux x86_64
api_1  | Version: 1.24.3
api_1  | Args: ["deno", "run", "--allow-net", "--allow-env", "--allow-write", "--allow-read", "--watch", "server.ts"]
api_1  | 
api_1  | thread 'main' panicked at 'Only a single use of this resource should happen: FullDuplexResource { rd: AsyncRefCell<tokio::net::tcp::split_owned::OwnedReadHalf>, wr: AsyncRefCell<tokio::net::tcp::split_owned::OwnedWriteHalf>, cancel_handle: CancelHandle { node: Node { inner: UnsafeCell { .. }, _pin: PhantomPinned } } }', /home/runner/work/deno/deno/ext/net/ops_tls.rs:832:6
api_1  | stack backtrace:
api_1  |    0:     0x55f728025fed - std::backtrace_rs::backtrace::libunwind::trace::h8e036432725b1c57
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
api_1  |    1:     0x55f728025fed - std::backtrace_rs::backtrace::trace_unsynchronized::h4f83092254c85869
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
api_1  |    2:     0x55f728025fed - std::sys_common::backtrace::_print_fmt::h9728b5e056a3ece3
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
api_1  |    3:     0x55f728025fed - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h48bb4bd2928827d2
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22
api_1  |    4:     0x55f72805103c - core::fmt::write::h909e69a2c24f44cc
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/fmt/mod.rs:1196:17
api_1  |    5:     0x55f72801d7a1 - std::io::Write::write_fmt::h7f4b8ab8af89e9ef
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/io/mod.rs:1654:15
api_1  |    6:     0x55f728027d35 - std::sys_common::backtrace::_print::hff4838ebf14a2171
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:48:5
api_1  |    7:     0x55f728027d35 - std::sys_common::backtrace::print::h2499280374189ad9
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:35:9
api_1  |    8:     0x55f728027d35 - std::panicking::default_hook::{{closure}}::h8b270fc55eeb284e
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:295:22
api_1  |    9:     0x55f7280279a9 - std::panicking::default_hook::h3217e229d6e9d13c
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:314:9
api_1  |   10:     0x55f72836edb2 - deno::setup_panic_hook::{{closure}}::h144eead8301ce14a
api_1  |   11:     0x55f7280284c6 - std::panicking::rust_panic_with_hook::h9acb8048b738d2e0
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:702:17
api_1  |   12:     0x55f7280282c7 - std::panicking::begin_panic_handler::{{closure}}::h70f3b839526af6dc
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:588:13
api_1  |   13:     0x55f7280264a4 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ecf2cee857fbe0a
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
api_1  |   14:     0x55f728027ff9 - rust_begin_unwind
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
api_1  |   15:     0x55f72804e483 - core::panicking::panic_fmt::h9f8393e7fd56d655
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
api_1  |   16:     0x55f72804e733 - core::result::unwrap_failed::h8b88eb424b1f8daa
api_1  |                                at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
api_1  |   17:     0x55f728a0532f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf50ae9be826c6dcf
api_1  |   18:     0x55f728857ada - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h731df565207913d5
api_1  |   19:     0x55f7271b5175 - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
api_1  |                                at ./../../../../v8/src/api/api-arguments-inl.h:147:3
api_1  |   20:     0x55f7271b4c5a - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
api_1  |                                at ./../../../../v8/src/builtins/builtins-api.cc:114:36
api_1  |   21:     0x55f7271b40b6 - _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
api_1  |                                at ./../../../../v8/src/builtins/builtins-api.cc:132:1
api_1  |   22:     0x55f727f207f8 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
```

**Comment by crowlKats** [comment]
This has since been fixed
