### ISSUE TITLE
Cross-compiling (x86_64 -> aarch64) on Linux fails with "Cross compiling with snapshot is not supported"

### ISSUE THREAD

**Issue by user13571113** [denoland/deno#16552]
I wish to cross-compile deno on an x86_64 Linux machine so as to run on an aarch64 Linux machine. The compilation fails with the error
```
error: failed to run custom build command for `deno v1.27.1 (/home/[retracted]/tmp/deno/cli)`

Caused by:
  process didn't exit successfully: `/home/[retracted]/tmp/deno/target/debug/build/deno-2c98b6fe55143aa0/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Cross compiling with snapshot is not supported.', cli/build.rs:338:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Judging from the error message, this failure is intended. Is there any suggest way to circumvent it? I would prefer to build the deno executable with `cargo build --target=aarch64-unknown-linux-gnu` rather than using distcc or a container.

I use the following setup:
```
$ uname -a
Linux [retraced] 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64 GNU/Linux\
```
```
$ cargo -V
cargo 1.65.0 (4bc8f24d3 2022-10-20)
```
```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/[retracted]/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.64.0-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.65.0 (897e37553 2022-11-02)
```
I have added the following two lines to .cargo/config.toml:
```
[target.aarch64-unknown-linux-gnu]
linker="aarch64-linux-gnu-gcc"
```

Appendum: This is the complete compilation log:
```
$ cargo build --target=aarch64-unknown-linux-gnu                    
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.14.0
   Compiling smallvec v1.9.0
   Compiling scopeguard v1.1.0
   Compiling spin v0.5.2
   Compiling bitflags v1.3.2
   Compiling pin-project-lite v0.2.9
   Compiling itoa v1.0.3
   Compiling tinyvec_macros v0.1.0
   Compiling percent-encoding v2.2.0
   Compiling unicode-bidi v0.3.8
   Compiling ryu v1.0.11
   Compiling base64 v0.13.1
   Compiling regex-syntax v0.6.27
   Compiling if_chain v1.0.2
   Compiling bytes v1.2.1
   Compiling futures-sink v0.3.24
   Compiling futures-io v0.3.24
   Compiling pin-utils v0.1.0
   Compiling subtle v2.4.1
   Compiling either v1.8.0
   Compiling unicode-width v0.1.10
   Compiling rustc-hash v1.1.0
   Compiling siphasher v0.3.10
   Compiling stable_deref_trait v1.2.0
   Compiling precomputed-hash v0.1.1
   Compiling void v1.0.2
   Compiling new_debug_unreachable v1.0.4
   Compiling scoped-tls v1.0.0
   Compiling untrusted v0.7.1
   Compiling static_assertions v1.1.0
   Compiling unicode-id v0.3.3
   Compiling byteorder v1.4.3
   Compiling ppv-lite86 v0.2.16
   Compiling typed-arena v2.0.1
   Compiling fnv v1.0.7
   Compiling termcolor v1.1.3
   Compiling base64ct v1.5.2
   Compiling opaque-debug v0.3.0
   Compiling fixedbitset v0.4.2
   Compiling tower-service v0.3.2
   Compiling const-oid v0.9.0
   Compiling adler v1.0.2
   Compiling try-lock v0.2.3
   Compiling bumpalo v3.11.1
   Compiling alloc-no-stdlib v2.0.4
   Compiling httpdate v1.0.2
   Compiling crc-catalog v1.1.1
   Compiling pathdiff v0.2.1
   Compiling data-url v0.2.0
   Compiling relative-path v1.7.2
   Compiling retain_mut v0.1.9
   Compiling utf-8 v0.7.6
   Compiling ipnet v2.5.0
   Compiling radix_fmt v1.0.0
   Compiling openssl-probe v0.1.5
   Compiling base16ct v0.1.1
   Compiling bit-vec v0.6.3
   Compiling mime v0.3.16
   Compiling outref v0.1.0
   Compiling cty v0.2.2
   Compiling os_str_bytes v6.3.0
   Compiling hexf-parse v0.2.1
   Compiling unicode-xid v0.2.4
   Compiling matches v0.1.9
   Compiling match_cfg v0.1.0
   Compiling unic-common v0.9.0
   Compiling unic-char-range v0.9.0
   Compiling fallible-streaming-iterator v0.1.9
   Compiling fallible-iterator v0.2.0
   Compiling quick-error v1.2.3
   Compiling strsim v0.10.0
   Compiling renderdoc-sys v0.7.1
   Compiling profiling v1.0.6
   Compiling inplace_it v0.3.5
   Compiling data-encoding v2.3.2
   Compiling glow v0.11.2
   Compiling textwrap v0.15.1
   Compiling linked-hash-map v0.5.6
   Compiling copyless v0.1.5
   Compiling linux-raw-sys v0.0.46
   Compiling same-file v1.0.6
   Compiling endian-type v0.1.2
   Compiling tower-layer v0.3.1
   Compiling block-modes v0.9.1
   Compiling cache_control v0.2.0
   Compiling dyn-clone v1.0.9
   Compiling diff v0.1.13
   Compiling path-clean v0.1.0
   Compiling yansi v0.5.1
   Compiling number_prefix v0.4.0
   Compiling monch v0.2.1
   Compiling utf8parse v0.2.0
   Compiling humantime v2.1.0
   Compiling remove_dir_all v0.5.3
   Compiling iana-time-zone v0.1.48
   Compiling fastrand v1.8.0
   Compiling unicode-segmentation v1.10.0
   Compiling dissimilar v1.0.4
   Compiling text-size v1.1.0
   Compiling shell-escape v0.1.5
   Compiling napi-sys v2.2.2
   Compiling bencher v0.1.5
   Compiling test_ffi v0.1.0 (/home/[retracted]/tmp/deno/test_ffi)
   Compiling num-bigint v0.4.3
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling num-iter v0.1.43
   Compiling num-integer v0.1.45
   Compiling memoffset v0.6.5
   Compiling unicase v2.6.0
   Compiling serde v1.0.144
   Compiling memchr v2.5.0
   Compiling parking_lot_core v0.9.3
   Compiling typenum v1.15.0
   Compiling futures-core v0.3.24
   Compiling libloading v0.7.3
   Compiling serde_json v1.0.85
   Compiling futures-task v0.3.24
   Compiling futures-channel v0.3.24
   Compiling tracing-core v0.1.29
   Compiling lazy_static v1.4.0
   Compiling thiserror v1.0.35
   Compiling futures-util v0.3.24
   Compiling instant v0.1.12
   Compiling gpu-alloc-types v0.2.0
   Compiling gpu-descriptor-types v0.1.1
   Compiling anyhow v1.0.65
   Compiling libm v0.2.5
   Compiling tinyvec v1.6.0
   Compiling itertools v0.10.4
   Compiling log v0.4.17
   Compiling path-dedot v3.0.17
   Compiling form_urlencoded v1.1.0
   Compiling nibble_vec v0.1.0
   Compiling phf_shared v0.10.0
   Compiling http v0.2.8
   Compiling rustls-pemfile v1.0.1
   Compiling httparse v1.8.0
   Compiling crc32fast v1.3.2
   Compiling fxhash v0.2.1
   Compiling async-trait v0.1.57
   Compiling proc-macro-hack v0.5.19
   Compiling unreachable v0.1.1
   Compiling swc_ecma_ast v0.94.14
   Compiling encoding_rs v0.8.31
   Compiling better_scoped_tls v0.1.0
   Compiling lexical-util v0.8.5
   Compiling getrandom v0.1.16
   Compiling pem-rfc7468 v0.6.0
   Compiling ash v0.37.0+1.3.209
   Compiling khronos-egl v4.1.0
   Compiling miniz_oxide v0.5.4
   Compiling num-bigint-dig v0.8.1
   Compiling codespan-reporting v0.11.1
   Compiling wgpu-core v0.13.2
   Compiling alloc-stdlib v0.2.2
   Compiling proc-macro2 v0.4.30
   Compiling syn v0.15.44
   Compiling bit-set v0.5.3
   Compiling simd-abstraction v0.7.0
   Compiling unic-char-property v0.9.0
   Compiling swc_bundler v0.192.45
   Compiling unic-ucd-version v0.9.0
   Compiling raw-window-handle v0.4.3
   Compiling crc v2.1.0
   Compiling lru-cache v0.1.2
   Compiling semver v0.9.0
   Compiling io-lifetimes v0.7.3
   Compiling crossbeam-utils v0.8.11
   Compiling clap_lex v0.1.1
   Compiling parking_lot_core v0.8.5
   Compiling rustix v0.35.9
   Compiling semver v1.0.14
   Compiling pulldown-cmark v0.9.2
   Compiling mitata v0.0.7
   Compiling walkdir v2.3.2
   Compiling test_napi v0.1.0 (/home/[retracted]/tmp/deno/test_napi)
   Compiling pretty_assertions v1.3.0
   Compiling proc-macro2 v1.0.43
   Compiling libc v0.2.126
   Compiling lock_api v0.4.8
   Compiling indexmap v1.9.1
   Compiling generic-array v0.14.6
   Compiling slab v0.4.7
   Compiling ahash v0.7.6
   Compiling tokio v1.21.1
   Compiling num-traits v0.2.15
   Compiling gpu-alloc v0.5.3
   Compiling radix_trie v0.2.1
   Compiling rustls-native-certs v0.6.2
   Compiling unicode-normalization v0.1.22
   Compiling debug_unreachable v0.1.1
   Compiling http-body v0.4.5
   Compiling lexical-write-integer v0.8.5
   Compiling lexical-parse-integer v0.8.6
   Compiling brotli-decompressor v2.3.2
   Compiling unic-ucd-ident v0.9.0
   Compiling base64-simd v0.7.0
   Compiling rustc_version v0.2.3
   Compiling quote v1.0.21
   Compiling getrandom v0.2.7
   Compiling jobserver v0.1.24
   Compiling fslock v0.1.8
   Compiling which v4.3.0
   Compiling signal-hook-registry v1.4.0
   Compiling socket2 v0.4.7
   Compiling num_cpus v1.13.1
   Compiling hostname v0.3.1
   Compiling memmap2 v0.5.7
   Compiling aho-corasick v0.7.19
   Compiling cpufeatures v0.2.5
   Compiling atty v0.2.14
   Compiling filetime v0.2.17
   Compiling os_pipe v1.0.1
   Compiling xattr v0.2.3
   Compiling inotify-sys v0.1.5
   Compiling terminal_size v0.1.17
   Compiling errno v0.1.8
   Compiling netif v0.1.6
   Compiling tempfile v3.3.0
   Compiling generic-array v0.12.4
   Compiling mio v0.8.4
   Compiling want v0.3.0
   Compiling flate2 v1.0.24
   Compiling idna v0.3.0
   Compiling idna v0.2.3
   Compiling lexical-write-float v0.8.5
   Compiling lexical-parse-float v0.8.5
   Compiling quote v0.6.13
   Compiling brotli v3.3.4
   Compiling crossbeam-channel v0.5.6
   Compiling fs3 v0.5.0
   Compiling syn v1.0.99
   Compiling rand_core v0.6.4
   Compiling cc v1.0.73
   Compiling parking_lot v0.12.1
   Compiling v8 v0.54.0
   Compiling rand_core v0.5.1
   Compiling resolv-conf v0.7.0
   Compiling regex v1.6.0
   Compiling tar v0.4.38
   Compiling inotify v0.9.6
   Compiling console v0.15.1
   Compiling pty v0.2.2
   Compiling parking_lot v0.11.2
   Compiling nix v0.24.2
   Compiling digest v0.8.1
   Compiling block-buffer v0.10.3
   Compiling digest v0.9.0
   Compiling block-buffer v0.9.0
   Compiling block-padding v0.3.2
   Compiling spirv v0.2.0+1.5.4
   Compiling lexical-core v0.8.5
   Compiling rand_chacha v0.3.1
   Compiling crypto-common v0.1.6
   Compiling ff v0.12.0
   Compiling hashbrown v0.12.3
   Compiling fd-lock v3.0.6
   Compiling ring v0.16.20
   Compiling libsqlite3-sys v0.25.1
   Compiling zstd-sys v2.0.1+zstd.1.5.2
   Compiling libffi-sys v2.0.0
   Compiling lzzzz v1.0.3
   Compiling fancy-regex v0.10.0
   Compiling Inflector v0.11.4
   Compiling glibc_version v0.1.2
   Compiling synstructure v0.12.6
   Compiling pmutil v0.5.3
   Compiling darling_core v0.13.4
   Compiling indicatif v0.17.1
   Compiling sha-1 v0.9.8
   Compiling inout v0.1.3
   Compiling chrono v0.4.22
   Compiling lexical v6.1.1
   Compiling digest v0.10.5
   Compiling universal-hash v0.5.0
   Compiling aead v0.5.1
   Compiling rand v0.8.5
   Compiling group v0.12.0
   Compiling gpu-descriptor v0.2.3
   Compiling hashlink v0.8.0
   Compiling serde_derive v1.0.144
   Compiling futures-macro v0.3.24
   Compiling thiserror-impl v1.0.35
   Compiling tokio-macros v1.8.0
   Compiling tracing-attributes v0.1.22
   Compiling derive_more v0.99.17
   Compiling pin-project-internal v1.0.12
   Compiling enum-as-inner v0.5.1
   Compiling serde_repr v0.1.9
   Compiling async-stream-impl v0.3.3
   Compiling tower-lsp-macros v0.6.0
   Compiling rustyline-derive v0.7.0
   Compiling dashmap v5.4.0
   Compiling swc_macros_common v0.3.6
   Compiling swc_eq_ignore_macros v0.1.1
   Compiling is-macro v0.2.1
   Compiling auto_impl v0.5.0
   Compiling dynasm v1.2.3
   Compiling dlopen_derive v0.1.4
   Compiling cipher v0.4.3
   Compiling zeroize_derive v1.3.2
   Compiling polyval v0.6.0
   Compiling hmac v0.12.1
   Compiling sha2 v0.10.6
   Compiling signature v1.6.3
   Compiling sha-1 v0.10.0
   Compiling phf_generator v0.10.0
   Compiling rustls v0.20.6
   Compiling darling_macro v0.13.4
   Compiling twox-hash v1.6.3
   Compiling tracing v0.1.36
   Compiling pin-project v1.0.12
   Compiling async-stream v0.3.3
   Compiling aes v0.8.1
   Compiling ctr v0.9.1
   Compiling cbc v0.1.2
   Compiling swc_visit_macros v0.5.4
   Compiling from_variant v0.1.4
   Compiling string_enum v0.3.2
   Compiling enum_kind v0.2.1
   Compiling swc_ecma_transforms_macros v0.5.0
   Compiling swc_config_macro v0.1.0
   Compiling swc_ecma_codegen_macros v0.7.1
   Compiling ghash v0.5.0
   Compiling dlopen v0.1.8
   Compiling hkdf v0.12.3
   Compiling string_cache_codegen v0.5.2
   Compiling phf_macros v0.10.0
   Compiling zeroize v1.5.7
   Compiling webpki v0.22.0
   Compiling sct v0.7.0
   Compiling darling v0.13.4
   Compiling fly-accept-encoding v0.2.0
   Compiling libffi v3.0.1
   Compiling rusqlite v0.28.0
   Compiling futures-executor v0.3.24
   Compiling tower v0.4.13
   Compiling aes-kw v0.2.1
   Compiling toml v0.5.9
   Compiling url v2.3.1
   Compiling serde_bytes v0.11.7
   Compiling bitflags_serde_shim v0.2.2
   Compiling uuid v1.1.2
   Compiling arrayvec v0.7.2
   Compiling serde_urlencoded v0.7.1
   Compiling ron v0.7.1
   Compiling triomphe v0.1.8
   Compiling string_cache v0.8.4
   Compiling text_lines v0.6.0
   Compiling tokio-util v0.7.4
   Compiling async-compression v0.3.14
   Compiling tokio-socks v0.5.1
   Compiling tokio-stream v0.1.9
   Compiling aes-gcm v0.10.1
   Compiling dynasmrt v1.2.3
   Compiling der v0.6.0
   Compiling crypto-bigint v0.4.8
   Compiling curve25519-dalek v3.2.0
   Compiling curve25519-dalek v2.1.3
   Compiling swc_atoms v0.4.23
   Compiling webpki-roots v0.22.4
   Compiling ast_node v0.8.6
   Compiling futures v0.3.24
   Compiling phf v0.10.1
   Compiling naga v0.9.0
   Compiling serde_v8 v0.68.0 (/home/[retracted]/tmp/deno/serde_v8)
   Compiling wgpu-types v0.13.2
   Compiling trust-dns-proto v0.22.0
   Compiling urlpattern v0.2.0
   Compiling swc_visit v0.5.3
   Compiling proc-macro-crate v1.2.1
   Compiling env_logger v0.9.0
   Compiling rustyline v10.0.0
   Compiling petgraph v0.6.2
   Compiling clap v3.1.12
   Compiling dprint-core v0.59.0
   Compiling h2 v0.3.14
   Compiling rfc6979 v0.3.0
   Compiling x25519-dalek v2.0.0-pre.1
   Compiling spki v0.6.0
   Compiling sourcemap v6.1.0
   Compiling tokio-rustls v0.23.4
   Compiling tungstenite v0.16.0
   Compiling napi_sym v0.5.0 (/home/[retracted]/tmp/deno/cli/napi_sym)
   Compiling notify v5.0.0
   Compiling deno_ops v0.35.0 (/home/[retracted]/tmp/deno/ops)
   Compiling trust-dns-resolver v0.22.0
   Compiling swc_config v0.1.4
   Compiling lsp-types v0.93.2
   Compiling import_map v0.12.1
   Compiling jsonc-parser v0.21.0
   Compiling wgpu-hal v0.13.2
   Compiling clap_complete v3.1.2
   Compiling dprint-plugin-markdown v0.14.1
   Compiling pkcs8 v0.9.0
   Compiling tokio-tungstenite v0.16.1
   Compiling hyper v0.14.20
   Compiling dprint-plugin-json v0.15.6
   Compiling deno_core v0.157.0 (/home/[retracted]/tmp/deno/core)
   Compiling clap_complete_fig v3.1.5
   Compiling sec1 v0.3.0
   Compiling pkcs1 v0.4.0
   Compiling swc_common v0.29.10
   Compiling deno_task_shell v0.7.0
   Compiling hyper-rustls v0.23.0
   Compiling deno_tls v0.62.0 (/home/[retracted]/tmp/deno/ext/tls)
   Compiling deno_web v0.106.0 (/home/[retracted]/tmp/deno/ext/web)
   Compiling deno_url v0.75.0 (/home/[retracted]/tmp/deno/ext/url)
   Compiling deno_webidl v0.75.0 (/home/[retracted]/tmp/deno/ext/webidl)
   Compiling deno_napi v0.5.0 (/home/[retracted]/tmp/deno/ext/napi)
   Compiling deno_ffi v0.62.0 (/home/[retracted]/tmp/deno/ext/ffi)
   Compiling deno_node v0.12.0 (/home/[retracted]/tmp/deno/ext/node)
   Compiling deno_broadcast_channel v0.69.0 (/home/[retracted]/tmp/deno/ext/broadcast_channel)
   Compiling deno_console v0.75.0 (/home/[retracted]/tmp/deno/ext/console)
warning: unused variable: `sym`
  --> ext/ffi/fast_call.rs:24:34
   |
24 | pub(crate) fn compile_trampoline(sym: &Symbol) -> Trampoline {
   |                                  ^^^ help: if this is intentional, prefix it with an underscore: `_sym`                                                    
   |
   = note: `#[warn(unused_variables)]` on by default

   Compiling deno_bench_util v0.69.0 (/home/[retracted]/tmp/deno/bench_util)
   Compiling deno_cache v0.7.0 (/home/[retracted]/tmp/deno/ext/cache)
   Compiling elliptic-curve v0.12.3
warning: `deno_ffi` (lib) generated 1 warning
   Compiling rsa v0.7.0-pre
   Compiling swc_fast_graph v0.17.11
   Compiling swc_ecma_loader v0.41.11
   Compiling tower-lsp v0.17.0
   Compiling reqwest v0.11.11
   Compiling deno_webgpu v0.76.0 (/home/[retracted]/tmp/deno/ext/webgpu)
   Compiling deno_websocket v0.80.0 (/home/[retracted]/tmp/deno/ext/websocket)
   Compiling deno_net v0.67.0 (/home/[retracted]/tmp/deno/ext/net)
   Compiling deno_webstorage v0.70.0 (/home/[retracted]/tmp/deno/ext/webstorage)
   Compiling ecdsa v0.14.7
   Compiling swc_graph_analyzer v0.18.11
   Compiling deno_fetch v0.98.0 (/home/[retracted]/tmp/deno/ext/fetch)
   Compiling deno_http v0.69.0 (/home/[retracted]/tmp/deno/ext/http)
   Compiling deno_flash v0.11.0 (/home/[retracted]/tmp/deno/ext/flash)
   Compiling p256 v0.11.1
   Compiling p384 v0.11.2
   Compiling swc_ecma_visit v0.80.14
   Compiling swc_ecma_parser v0.122.19
   Compiling swc_ecma_codegen v0.127.23
   Compiling deno_crypto v0.89.0 (/home/[retracted]/tmp/deno/ext/crypto)
   Compiling test_util v0.1.0 (/home/[retracted]/tmp/deno/test_util)
   Compiling dprint-swc-ext v0.5.0
   Compiling deno_runtime v0.83.0 (/home/[retracted]/tmp/deno/runtime)
   Compiling swc_ecma_utils v0.105.24
   Compiling swc_ecma_dep_graph v0.94.19
   Compiling swc_ecma_transforms_base v0.111.33
   Compiling swc_ecma_transforms_classes v0.100.32
   Compiling swc_ecma_transforms_optimization v0.167.26
   Compiling swc_ecma_transforms_react v0.155.21
   Compiling swc_ecma_transforms_proposal v0.144.20
   Compiling swc_ecma_transforms_typescript v0.159.22
   Compiling deno_ast v0.20.0
   Compiling deno_lint v0.34.0
   Compiling deno_graph v0.37.1
   Compiling dprint-plugin-typescript v0.76.0
   Compiling eszip v0.29.0
   Compiling deno_emit v0.10.0
   Compiling deno_doc v0.48.0
   Compiling zstd-safe v5.0.2+zstd.1.5.2
   Compiling zstd v0.11.2+zstd.1.5.2
   Compiling deno v1.27.1 (/home/[retracted]/tmp/deno/cli)
error: failed to run custom build command for `deno v1.27.1 (/home/[retracted]/tmp/deno/cli)`

Caused by:
  process didn't exit successfully: `/home/[retracted]/tmp/deno/target/debug/build/deno-2c98b6fe55143aa0/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Cross compiling with snapshot is not supported.', cli/build.rs:338:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by sigmaSd** [comment]
Its not currently possible https://github.com/LukeChannings/deno-arm64#why-cant-you-just-cross-compile

**Comment by dsherret** [comment]
See https://github.com/denoland/deno/issues/13948 and there was a past PR that tried a solution. We'd like to do this, but it's hard.
