### ISSUE TITLE
Error with module resolution loading `sharp` native module as dependency via `npm:` specifier

### ISSUE THREAD

**Issue by k-right** [denoland/deno#16578]
Trying to get `payload` running on Deno unstable. Module resolution seems to get confused on the `sharp` module (specifically loading its native component).

```bash
deno run --unstable --allow-read --allow-env index.ts
```

```
error: Uncaught Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-x64.node'
Require stack:
- /Users/x/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.31.2/lib/sharp.js
- /Users/x/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.31.2/lib/constructor.js
- /Users/x/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.31.2/lib/index.js
- /Users/x/Library/Caches/deno/npm/registry.npmjs.org/payload/1.1.21/dist/uploads/generateFileData.js
- /Users/x/Library/Caches/deno/npm/registry.npmjs.org/payload/1.1.21/dist/collections/operations/create.js
- /Users/x/Library/Caches/deno/npm/registry.npmjs.org/payload/1.1.21/dist/collections/operations/local/create.js
- /Users/x/Library/Caches/deno/npm/registry.npmjs.org/payload/1.1.21/dist/collections/operations/local/index.js
- /Users/x/Library/Caches/deno/npm/registry.npmjs.org/payload/1.1.21/dist/index.js
- /Users/x/Library/Caches/deno/npm/registry.npmjs.org/payload/1.1.21/dist/index.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-x64 runtime: "npm install --platform=darwin --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (file:///Users/x/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.31.2/lib/sharp.js:34:9)
    at Object.<anonymous> (file:///Users/x/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.31.2/lib/sharp.js:37:4)
    at Module._compile (deno:ext/node/02_require.js:717:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:750:12)
    at Module.load (deno:ext/node/02_require.js:634:34)
    at Function.Module._load (deno:ext/node/02_require.js:491:14)
    at Module.require (deno:ext/node/02_require.js:656:21)
    at require (deno:ext/node/02_require.js:790:18)
    at Object.<anonymous> (file:///Users/x/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.31.2/lib/constructor.js:8:1)
    at Object.<anonymous> (file:///Users/x/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.31.2/lib/constructor.js:425:4)
```

Minimal example to reproduce:

```ts
import express from 'npm:express@4.18.2'
import payload from 'npm:payload@1.1.21'

const app = express();

payload.init({
  secret: process.env.PAYLOAD_SECRET,
  mongoURL: process.env.MONGO_URL,
  express: app,
});

app.listen(process.env.PAYLOAD_PORT, process.env.PAYLOAD_ADDR, async () => {
  console.log(`listening on http://${process.env.PAYLOAD_ADDR}:${process.env.PAYLOAD_PORT}/`);
});
```

**Comment by k-right** [comment]
```bash
cd ~/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.31.2
npm i
```

```bash
deno run --unstable --allow-read --allow-env --allow-ffi index.ts
```

```
dyld: lazy symbol binding failed: Symbol not found: _pthread_jit_write_protect_supported_np
  Referenced from: /Users/x/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.31.2/build/Release/../.././vendor/8.13.3/darwin-x64/lib/libvips-cpp.42.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _pthread_jit_write_protect_supported_np
  Referenced from: /Users/x/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.31.2/build/Release/../.././vendor/8.13.3/darwin-x64/lib/libvips-cpp.42.dylib
  Expected in: /usr/lib/libSystem.B.dylib

[1]    48222 abort      deno run --unstable --allow-read --allow-env --allow-ffi index.ts
```

**Comment by littledivy** [comment]
@k-right It seems like a recent bug in Sharp: https://github.com/lovell/sharp/issues/3438

**Comment by bartlomieju** [comment]
Seems this is the same problem as https://github.com/denoland/deno/issues/17085

**Comment by bartlomieju** [comment]
@k-right it seems this example involves several other packages. Could you try to boil it down into two separate issues - one for `sharp` support and one for the error coming from `mongoose`?

**Comment by hahnbeelee** [comment]
I've seen the sharp error happen on old versions of Mac OS's

**Comment by bartlomieju** [comment]
`napi_add_finalizer` is now available and working. @k-right any chance you could try this again and let us know if the problem persists?

**Comment by zwn** [comment]
I tried while checking
- #19854 

When all binary files are in place, `sharp` can be imported (meaning I can run `deno` repl and paste `import sharp from 'npm:sharp';` and not get an error).

**Comment by bartlomieju** [comment]
@zwn by "when all binary files are in place" do you mean that you manually run postinstall script?

**Comment by zwn** [comment]
@bartlomieju I just tried to import `sharp` and when it said some file is missing I've put it into the place where it was expected.

There were two parts to make it working:
- node_modules/.deno/sharp@0.32.3/node_modules/sharp/build/Release/sharp-linux-x64.node
- node_modules/.deno/sharp@0.32.3/node_modules/sharp/vendor/*

**Comment by birkskyum** [comment]
Related to
- #20071

**Comment by shriharip** [comment]
facing same issue. 
simple reproducible code is also the same :)

```
something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-x64.node'
Require stack:
- /Users/shrihari/projects/advedaweb/node_modules/.deno/sharp@0.31.3/node_modules/sharp/lib/sharp.js
- /Users/shrihari/projects/advedaweb/node_modules/.deno/sharp@0.31.3/node_modules/sharp/lib/constructor.js
- /Users/shrihari/projects/advedaweb/node_modules/.deno/sharp@0.31.3/node_modules/sharp/lib/index.js
- /Users/shrihari/projects/advedaweb/node_modules/.deno/payload@1.15.6/node_modules/payload/dist/uploads/generateFileData.js
- /Users/shrihari/projects/advedaweb/node_modules/.deno/payload@1.15.6/node_modules/payload/dist/collections/operations/create.js
- /Users/shrihari/projects/advedaweb/node_modules/.deno/payload@1.15.6/node_modules/payload/dist/collections/requestHandlers/create.js
- /Users/shrihari/projects/advedaweb/node_modules/.deno/payload@1.15.6/node_modules/payload/dist/collections/buildEndpoints.js
- /Users/shrihari/projects/advedaweb/node_modules/.deno/payload@1.15.6/node_modules/payload/dist/collections/initHTTP.js
- /Users/shrihari/projects/advedaweb/node_modules/.deno/payload@1.15.6/node_modules/payload/dist/initHTTP.js
- /Users/shrihari/projects/advedaweb/node_modules/.deno/payload@1.15.6/node_modules/payload/dist/index.js
- /Users/shrihari/projects
```

**Comment by birkskyum** [comment]
This issue specific to sharp can be closed since sharp v0.33.

**Comment by janzheng** [comment]
Trying to deploy to Deno Deploy and getting this. Works locally though!

```
error: The deployment failed: UNCAUGHT_EXCEPTION

Error: abort(Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install). Build with -s ASSERTIONS=1 for more info.
    at process.bA (file:///node_modules/.deno/jq-web@0.5.1/node_modules/jq-web/jq.asm.bundle.min.js:1:1694567)
    at process.emit (ext:deno_node/_events.mjs:393:28)
    at process.Process.emit (node:process:414:40)
    at Object.internals.nodeProcessUnhandledRejectionCallback (node:process:632:15)
    at processUnhandledPromiseRejection (ext:deno_deploy/main.js:251:15)
    at eventLoopTick (ext:core/01_core.js:225:25)
```

**Comment by jonasiwnl** [comment]
@janzheng , did you end up solving this?

**Comment by marvinhagemeister** [comment]
Deno Deploy does not support running node native addons at the time of this writing (might change in the future). For now, only JS/TS, JSX or WASM are supported.

**Comment by janzheng** [comment]
> [@janzheng](https://github.com/janzheng) , did you end up solving this?

it's not natively supported; ended up using a completely other stack (Cloudflare workers)

**Comment by littledivy** [comment]
This is fixed. `npm:sharp` now installs and runs correctly. With a node_modules dir and the install step allowed (`{"nodeModulesDir":"auto"}` + `deno install --allow-scripts`, or `deno run --allow-scripts`), `npm:sharp@0.33` loads and works end-to-end — verified by encoding a PNG via `sharp({create:...}).png().toBuffer()` on a current build. The earlier module-resolution error no longer occurs. Closing as resolved.
