### ISSUE TITLE
Issues on the latest version deno_core crate

### ISSUE THREAD

**Issue by Dennis-Zhang-SH** [denoland/deno#16607]
Hi guys,

I am learning deno_core crate to build a simple JS runtime by reading following link
https://deno.com/blog/roll-your-own-javascript-runtime

While I met 2 problems on the latest version, I can run debug mode on the specific version on the article, but not the latest version, it returns some ld error on my old mac mini. The release mode is fine to go.

```
﻿﻿   Compiling js_runtime v0.1.0 (/Users/dennis/Documents/code/js_runtime)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "x86_64" "-m64" "/var/folders/5t/0v5p906d4r1159_b21w_tpvw0000gn/T/rustc22VttD/symbols.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.12jlxqfj9oh0453v.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.16ruq2hb66vs9kp9.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.17clqwvhyp18ldig.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.18ltdyn9fywkasfe.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.1em5gw57vg3lc3l5.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.1hz8tynyep91yt23.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.1k6ckkm5vunx84bu.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.1len2f6gl6q2aaw8.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.1pf1j5l6baatiu8k.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.1pk2a11qgkq42zom.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.1supq3w09tp4livz.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.1xq4lityobqwmdvw.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.20p4als3vwy1d8gg.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.20su6ak68kwa0944.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.22gmzpf37n055avr.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.22ma9e9lsvjb0h1v.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.2cw71lg3lmofl491.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.2daj2rvuqbjrl5e7.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.2dc75irll8r577uf.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.2e0v7zy6hi0n7pes.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.2gl47uspjxa62o4z.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.2jj5wq3z0uuytwh6.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.2p2ij413lhyuzugq.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.2pxkt2x23y64ai2m.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.2t9420dpvd8aovya.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.2tck7jpcyp2dhsk6.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.318phlwddea7tapl.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.3f2r4zrrri5gu8b8.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.3hkaiuoscr67vx5e.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.3ppouqy03jhqk87t.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.3px1vfe5mo0f4elj.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.3vxd3m4p5ldly7mt.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.42p91agc497qgc49.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.478lonw37an2c6xg.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.4hgxlgv97om00rhz.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.4i1n1dt0h7mmm0s2.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.4ungphtxqa7oyt3s.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.4y0xe1h8mavvec3g.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.54ed0pb7y7lzlh6w.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.54ehqkosh3lugwai.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.590p5wphjc633402.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.5ao1vdrv31anic7u.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.5cidkvdkhks5jt0m.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.5eg807x5i7eo56wp.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.5knht3u86e6t149.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.ky69njh20y0t4wa.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.tgc4okja3us4zzn.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.wwas16m21a6glbi.rcgu.o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d.6nuzxyfmzk0338.rcgu.o" "-L" "/Users/dennis/Documents/code/js_runtime/target/debug/deps" "-L" "/Users/dennis/Documents/code/js_runtime/target/debug/gn_out/obj" "-L" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libtokio-646f4e4bb4f6df5f.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libsignal_hook_registry-15358a6dcdb26ed1.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libnum_cpus-2af57abe0f40ac30.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libsocket2-f327a910d30a955c.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libmio-2de6af0249557a75.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libdeno_core-d2075b65e7907dea.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libsourcemap-0ae2f5727a1171d3.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libbase64-f3d4ac817edfa954.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libregex-f51ad4e0559bf15d.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libaho_corasick-3bb07aad6139f631.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libregex_syntax-d76deefdcfedebf3.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libif_chain-dc7991118b5a60e4.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libserde_json-fd5dccc5b89355d7.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libryu-485d057268194265.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libitoa-9f894203e7ebf532.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libindexmap-caaf20b297ed8fd6.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libhashbrown-381a8ed1d2997f06.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/liburl-a159209caacc0437.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libidna-489c866984369eba.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libunicode_normalization-fd2cb87acd71ce36.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libtinyvec-c37d8941dbe2fb4e.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libtinyvec_macros-c2922170ab77ef72.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libunicode_bidi-4017099cb0016da4.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libform_urlencoded-ede402085ce625f4.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libpercent_encoding-4092d1a251596e38.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libserde_v8-26cc6de52d5a2a27.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libbytes-8e15392a3cf41030.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libserde-078ce9cc22ae40e9.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libparking_lot-923819f75129613c.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libparking_lot_core-d22144ae80590d41.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libsmallvec-312fa31985208aa7.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/liblock_api-69d41460e1e2da05.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libscopeguard-10151765ec32c2fb.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libanyhow-f6a00daca8206170.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libv8-6d2d66fe2f60f981.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/liblibc-f4cacfdec23be4c2.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/liblazy_static-7564bf02a5110b4b.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libbitflags-95e2b50e6e8e5130.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/liblog-86765e1caa4d13ae.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libcfg_if-422f2268079734ae.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libpin_project-2840fba36f63d222.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libfutures-74eeb3c40c17b6c7.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libfutures_executor-b4f8a5cdfd144582.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libfutures_util-5b3d49fa2c643295.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libmemchr-b60ddd97a9a15a2a.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libfutures_io-920655d885c0c05e.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libslab-fd38a4ac6a6ce0f7.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libfutures_channel-5309b77030d4da2b.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libpin_project_lite-648eb78079c48cfc.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libfutures_sink-47f1cd287953bea6.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libfutures_task-807ff4795d4556fb.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libpin_utils-a201d44beae808df.rlib" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/libfutures_core-ebacce172480f814.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-b80af3af0eb55523.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-41e0d9e950b571e9.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-65b358c31ecfc4a1.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libmemchr-d704bb0c865e41a0.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-86367ac319ee82d9.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-377d8495d8a9283b.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-204129267883501a.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd_detect-718604cf3d9431db.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-07b15630ccf51366.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libminiz_oxide-af6869cacce7810c.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libadler-93f8c992dd4fe422.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-9838a33e4eec9cf7.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-9f7f7415b21b2c00.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-177ca04931a429cc.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-47bcfebe3e84a4ab.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-b6cf8e9c2b704fbc.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-030bef4529720381.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-e5bf6795ffb21202.rlib" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-315ef7713cc82d0e.rlib" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/Users/dennis/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/Users/dennis/Documents/code/js_runtime/target/debug/deps/js_runtime-a4e7b3c189f1a21d" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: Undefined symbols for architecture x86_64:
            "_v8__Isolate__SetWasmAsyncResolvePromiseCallback", referenced from:
                deno_core::runtime::JsRuntime::setup_isolate::hd1477012b662ef33 in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.8.rcgu.o)
            "_v8__CFunctionInfo__New", referenced from:
                v8::template::_$LT$impl$u20$v8..function..FunctionBuilder$LT$v8..data..FunctionTemplate$GT$$GT$::build_fast::h66a7095b03f118d2 in libv8-6d2d66fe2f60f981.rlib(v8-6d2d66fe2f60f981.v8.d670f51a-cgu.14.rcgu.o)
            "_v8__CTypeInfo__New", referenced from:
                v8::template::_$LT$impl$u20$v8..function..FunctionBuilder$LT$v8..data..FunctionTemplate$GT$$GT$::build_fast::h66a7095b03f118d2 in libv8-6d2d66fe2f60f981.rlib(v8-6d2d66fe2f60f981.v8.d670f51a-cgu.14.rcgu.o)
            "_v8__internal__Internals__kIsolateEmbedderDataOffset", referenced from:
                v8::isolate::Isolate::new::ha584f8afad05d683 in libv8-6d2d66fe2f60f981.rlib(v8-6d2d66fe2f60f981.v8.d670f51a-cgu.8.rcgu.o)
            "_v8__CTypeInfo__New__From__Slice", referenced from:
                v8::fast_api::CTypeInfo::new_from_slice::hf775250f0baa9e83 in libv8-6d2d66fe2f60f981.rlib(v8-6d2d66fe2f60f981.v8.d670f51a-cgu.2.rcgu.o)
            "_v8__ArrayBuffer__WasDetached", referenced from:
                deno_core::ops_builtin_v8::op_serialize::call::hb852e7e42f52270c in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.5.rcgu.o)
                deno_core::ops_builtin_v8::op_arraybuffer_was_detached::call::h08ace56194ec57fd in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.5.rcgu.o)
            "_v8__ArrayBuffer__Data", referenced from:
                deno_core::ops_builtin_v8::op_decode::v8_func::h826f79ca9ea263d2 in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.5.rcgu.o)
                deno_core::ops_builtin::op_wasm_streaming_feed::v8_func::h1494db5920b85f4b in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.3.rcgu.o)
            "_v8__FunctionCallbackInfo__kArgsLength", referenced from:
                deno_core::ops_builtin_v8::op_ref_op::v8_func::h9e439047f9fb5e88 in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.5.rcgu.o)
                deno_core::ops_builtin_v8::op_unref_op::v8_func::h9bd380dd4c9353b2 in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.5.rcgu.o)
                deno_core::ops_builtin_v8::op_set_macrotask_callback::v8_func::h50864ec054bd44b7 in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.5.rcgu.o)
                deno_core::ops_builtin_v8::op_set_next_tick_callback::v8_func::h359378c3a0d50cdc in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.5.rcgu.o)
                deno_core::ops_builtin_v8::op_set_promise_reject_callback::v8_func::h79c4e5e7a54aaccc in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.5.rcgu.o)
                deno_core::ops_builtin_v8::op_run_microtasks::v8_func::he72320fc16d85931 in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.5.rcgu.o)
                deno_core::ops_builtin_v8::op_has_tick_scheduled::v8_func::h9e73e11830674eac in libdeno_core-d2075b65e7907dea.rlib(deno_core-d2075b65e7907dea.deno_core.dbe5baa0-cgu.5.rcgu.o)
                ...
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: could not compile `js_runtime` due to previous error
```

The other problem is can not run the example JS file, return with error:
```
   Compiling js_runtime v0.1.0 (/Users/dennis/Documents/code/js_runtime)
    Finished release [optimized] target(s) in 3.04s
     Running `target/release/js_runtime`
[out]: "Hello" "runjs!" {"name":"test"}
[err]: "Boom!"
[err]: "Unable to read file" "./log.txt" {}
TypeError: invalid promise id: expected type `v8::data::Integer`, got `v8::data::Value`
    at Object.opAsync (deno:core/01_core.js:229:23)
    at Object.writeFile ([runjs:runtime.js]:23:25)
    at file:///Users/dennis/Documents/code/js_runtime/example.js:16:13

```

But on the sepecific version everything is fine.

So is there any version discrimination like stable and beta which I don't know? Please knowleadge me, thanks.

**Comment by littledivy** [comment]
@Dennis-Zhang-SH This repo is updated to work with latest deno_core:  https://github.com/denoland/roll-your-own-javascript-runtime

**Comment by littledivy** [comment]
The first problem seems like cache issue. Can you try building after `cargo clean`

**Comment by Dennis-Zhang-SH** [comment]
@littledivy Hi, I just run cargo clean and update to the latest version, the first problem disappeared but I still met second problem.

**Comment by bartlomieju** [comment]
You need to call `Deno.core.initializeAsyncOps();` before executing your code, see https://github.com/denoland/roll-your-own-javascript-runtime/blob/main/src/runtime.js
