### ISSUE TITLE
Unhandled rejection when aborting cloned request with a static body

### ISSUE THREAD

**Issue by 0f-0b** [denoland/deno#16648]
The code below causes an unhandled rejection in Deno but not in browsers. This does not happen if `body` is a `ReadableStream`.

```js
// a.js
const req = new Request("http://example.com/", {
  body: "",
  method: "POST",
  signal: AbortSignal.timeout(0),
});
fetch(req.clone()).catch(() => {});
```

```shellsession
$ deno run --allow-net a.js
error: Uncaught (in promise) TypeError: Cannot cancel a locked ReadableStream.
    at ReadableStream.cancel (deno:ext/web/06_streams.js:4685:11)
    at InnerBody.cancel (deno:ext/fetch/22_body.js:165:29)
    at abortFetch (deno:ext/fetch/26_fetch.js:476:22)
    at onabort (deno:ext/fetch/26_fetch.js:409:11)
    at AbortSignal.[[[signalAbort]]] (deno:ext/web/03_abort_signal.js:80:11)
    at deno:ext/web/03_abort_signal.js:183:37
    at AbortSignal.[[[signalAbort]]] (deno:ext/web/03_abort_signal.js:80:11)
    at deno:ext/web/03_abort_signal.js:183:37
    at AbortSignal.[[[signalAbort]]] (deno:ext/web/03_abort_signal.js:80:11)
    at deno:ext/web/03_abort_signal.js:183:37
$ deno --version
deno 1.28.0+d6fd171 (canary, x86_64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
```

**Comment by crowlKats** [comment]
simplified test case:
```js
const req = new ReadableStream({
  start(controller) {
    controller.enqueue(new Uint8Array([]));
    controller.close();
  },
})
await fetch("http://example.com/", {
  body: req,
  method: "POST",
  signal: AbortSignal.timeout(0),
});
```
