### ISSUE TITLE
Uncaught Error: Error resolving package config for 'npm:sinon'.: [ERR_INVALID_PACKAGE_TARGET] Invalid "exports" main target 

### ISSUE THREAD

**Issue by Lesiuk** [denoland/deno#16649]
Deno 1.28.0

Code:
```
import sinon from "npm:sinon";
console.log(sinon);
```

Result:
```
error: Uncaught Error: Error resolving package config for 'npm:sinon'.: [ERR_INVALID_PACKAGE_TARGET] Invalid "exports" main target {"require":"./lib/sinon.js","import":"./pkg/sinon-esm.js"} defined in the package config /Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/sinon/14.0.2package.json imported from file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/sinon/14.0.2/; target must start with "./"
    at <anonymous> (deno:cli/tsc/99_main_compiler.js:616:28)
```

Exports looks like this:
```
  "exports": {
    ".": {
      "require": "./lib/sinon.js",
      "import": "./pkg/sinon-esm.js"
    },
    "./*": "./*"
  },
```

**Comment by bartlomieju** [comment]
@Lesiuk can you provide a command that reproduces it? If I do `deno run -A main.js` or `deno run -A main.ts` I do a console log.

**Comment by Lesiuk** [comment]
It's `deno test`.

```
sg0227518@MAVT022LT04V deno % deno test sinon.ts 
Check file:///Users/xxx/WebstormProjects/deno/sinon.ts
error: Uncaught Error: Error resolving package config for 'npm:sinon'.: [ERR_INVALID_PACKAGE_TARGET] Invalid "exports" main target {"require":"./lib/sinon.js","import":"./pkg/sinon-esm.js"} defined in the package config /Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/sinon/14.0.2package.json imported from file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/sinon/14.0.2/; target must start with "./"
    at <anonymous> (deno:cli/tsc/99_main_compiler.js:616:28)
```

**Comment by Lesiuk** [comment]
It's strange that deno run works correctly, but deno test is not.

**Comment by Lesiuk** [comment]
When I change file name to js then it works correctly.

**Comment by bartlomieju** [comment]
Thanks, I'll investigate
