### ISSUE TITLE
Error: getaddrinfo ENOTFOUND localhost

### ISSUE THREAD

**Issue by KieranP** [denoland/deno#16643]
Tried simple deno 1.28.0 demo for Vite vanilla setup, not working.

```
$ deno --version
deno 1.28.0 (release, x86_64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
```

```
$ deno run -A npm:create-vite-extra
✔ Project name: … vite-project
✔ Select a template: › deno-vanilla

Scaffolding project in /Users/kieran/test/vite-project...

Done. Now run:

  cd vite-project
  deno task dev

$ cd vite-project
$ deno task dev
Task dev deno run -A --node-modules-dir npm:vite
error when starting dev server:
Error: getaddrinfo ENOTFOUND localhost
    at __node_internal_captureLargerStackTrace (https://deno.land/std@0.164.0/node/internal/errors.ts:113:11)
    at __node_internal_ (https://deno.land/std@0.164.0/node/internal/errors.ts:335:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (https://deno.land/std@0.164.0/node/internal/dns/promises.ts:67:17)
    at https://deno.land/std@0.164.0/node/internal_binding/cares_wrap.ts:111:9
```

**Comment by brenelz** [comment]
I'd guess maybe you have something running on that port already?

**Comment by flashtel** [comment]
https://forum.arduino.cc/t/bug-arduino-ide2-macos-10-15-7/1063016

**Comment by KieranP** [comment]
@flashtel Thanks for following up, but in my case, my /etc/hosts file is normal and contains the appropriate localhost lines. 

```
127.0.0.1                 localhost
255.255.255.255 broadcasthost
::1                           localhost
```

Tried latest version of Deno, same issue:

```
$ deno --version
deno 1.30.3 (release, x86_64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4

$ deno run -A npm:create-vite-extra
✔ Project name: … vite-project
✔ Select a template: › deno-vanilla

Scaffolding project in /Users/kieran/Desktop/vite-project...

Done. Now run:

  cd vite-project
  deno task dev

$ cd vite-project
$ deno task dev
Task dev deno run -A --node-modules-dir npm:vite
error when starting dev server:
Error: getaddrinfo ENOTFOUND localhost
    at __node_internal_captureLargerStackTrace (https://deno.land/std@0.177.0/node/internal/errors.ts:113:11)
    at __node_internal_ (https://deno.land/std@0.177.0/node/internal/errors.ts:335:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (https://deno.land/std@0.177.0/node/internal/dns/promises.ts:67:17)
    at https://deno.land/std@0.177.0/node/internal_binding/cares_wrap.ts:111:9
```

**Comment by adamgreg** [comment]
I think I have run into the same issue when I tried switching to using an `npm:` specifier for the `postgres` package instead of getting it from `https://deno.land/x`.

The following works when running with `--allow-net=localhost:5432`:

```ts
    import postgres from "https://deno.land/x/postgresjs@v3.4.3/mod.js";
    const sql = postgres();
    await sql`SELECT 1`;
```

Whereas the following does NOT work when running with `--allow-net=localhost:5432` but DOES work with a plain `--allow-net` flag:

```ts
    import postgres from "npm:postgres@3.4.3";
    const sql = postgres();
    await sql`SELECT 1`;
```

The behaviour is the same for a remote host specified by hostname (but not by IP). It seems to me like DNS resolution within node modules requires additional net permissions. The only way I've been able to make it work is with a blanket `--allow-net`. I tried `--allow-net=remote_host:5432,:53` when using a remote host, and that did not help. For now I'm going back to using the module from `deno.land/x`.

@bartlomieju I believe #21736 and #21735 may be related to this issue.

**Comment by bartlomieju** [comment]
Gonna close this one as Vite is now fully supported in Deno. Please open a new issue if you face a similar problem.
