### ISSUE TITLE
Deno.Command  Uncaught TypeError

### ISSUE THREAD

**Issue by xuybin** [denoland/deno#16664]
deno run -A --unstable test.ts
```
error: Uncaught TypeError: Wasn't spawned
const reader = mergeReadableStreams(child.stdout, child.stderr)
                                         ^
    at Command.get stdout (deno:runtime/js/40_spawn.js:367:15)
    at file:///./test.ts:9:43
```
./test.ts 
```
import { mergeReadableStreams } from "https://deno.land/std@0.164.0/streams/mod.ts";
const child = new Deno.Command("cd", {
  args: ["."],
  stdout: "piped",
  stderr: "piped",
  stdin: "piped",
});

const reader = mergeReadableStreams(child.stdout, child.stderr)
  .pipeThrough(
    new TextDecoderStream(),
  ).getReader();

```

**Comment by crowlKats** [comment]
you need to call `child.spawn()` to start the subprocess so you can use the subprocess' IO
