### ISSUE TITLE
Error: Uncaught ConnectionError due to TLSSocket._start not set in deno_std/node

### ISSUE THREAD

**Issue by jerebtw** [denoland/deno#16681]
I tried to use npm:mssql and go this problem:

(With node this works without a problem)

```
error: Uncaught ConnectionError: Failed to connect to SQLServer:undefined - tlssock._start is not a function
    at file:///C:/Users/jerebtw/AppData/Local/deno/npm/registry.npmjs.org/mssql/9.0.1/lib/tedious/connection-pool.js:70:17
    at Connection.onConnect (file:///C:/Users/jerebtw/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/connection.js:1012:9)
    at Object.onceWrapper (https://deno.land/std@0.165.0/node/_events.mjs:504:26)
    at Connection.emit (https://deno.land/std@0.165.0/node/_events.mjs:379:28)
    at Connection.emit (file:///C:/Users/jerebtw/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/connection.js:1040:18)
    at Connection.socketError (file:///C:/Users/jerebtw/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/connection.js:1395:12)
    at file:///C:/Users/jerebtw/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/connection.js:2402:25
    at Object.runMicrotasks (deno:core/01_core.js:377:30)
    at processTicksAndRejections (https://deno.land/std@0.165.0/node/_next_tick.ts:62:10)
```

```ts
import sql from "npm:mssql";

const connectionPool = new sql.ConnectionPool({
  server: "SQLServer\\Test",
  database: "Test",
  user: "user",
  password: "password",
  options: {
    trustedConnection: true,
    trustServerCertificate: true,
  },
});

const connection = await connectionPool.connect();
console.log("Connected");
```

**Comment by dsherret** [comment]
Investigated and this error occurs here:

* https://github.com/denoland/deno_std/blob/bc345306e520e758e8af9b00144c393c9c066c52/node/_tls_wrap.ts#L373
* https://github.com/tediousjs/tedious/blob/e43e9c912d05f1d9a359960a02afafb118f30a6f/src/message-io.ts#L74

```
TypeError: tlssock._start is not a function
    at Object.connect (https://deno.land/std@0.165.0/node/_tls_wrap.ts:373:13)
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/message-io.js:74:24
    at new Promise (<anonymous>)
    at MessageIO.startTls (file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/message-io.js:71:12)
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/connection.js:2401:34
    at Object.runMicrotasks (deno:core/01_core.js:377:30)
    at processTicksAndRejections (https://deno.land/std@0.165.0/node/_next_tick.ts:62:10)
```

It seems that `_start` function is never set in deno_std. I opened https://github.com/denoland/deno_std/issues/2909
