### ISSUE TITLE
Support for npm MSSQL package - tlssock._start is not a function

### ISSUE THREAD

**Issue by shammelburg** [denoland/deno#16685]
Hi,

I'm having a connection issue with `mssql` 

I tried this with deno 1.28.1

Below is an example of what I've tried, both on my local SQL Server instance and Azure SQL Databases, same result. 

```
import sql from 'npm:mssql@9.0.1'

const run = async () => {
    try {
        await sql.connect('Server=krypton;Database=mydb;User Id=user;Password=password')
        const result = await sql.query('select 1 from [schema].[table]')
        console.log(result)
    } catch (error) {
        console.log('------------- MSSQL ERROR START ---------------')
        console.log(error)
        console.log('------------- MSSQL ERROR END ---------------')
    }
}
run()
```

```
------------- MSSQL ERROR START ---------------
ConnectionError: Failed to connect to krypton:1433 - tlssock._start is not a function
    at file:///C:/Users/Sander%20Hammelburg/AppData/Local/deno/npm/registry.npmjs.org/mssql/9.0.1/lib/tedious/connection-pool.js:70:17
    at Connection.onConnect (file:///C:/Users/Sander%20Hammelburg/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/connection.js:1012:9)  
    at Object.onceWrapper (https://deno.land/std@0.165.0/node/_events.mjs:504:26)
    at Connection.emit (https://deno.land/std@0.165.0/node/_events.mjs:379:28)
    at Connection.emit (file:///C:/Users/Sander%20Hammelburg/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/connection.js:1040:18)      
    at Connection.socketError (file:///C:/Users/Sander%20Hammelburg/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/connection.js:1395:12)
    at file:///C:/Users/Sander%20Hammelburg/AppData/Local/deno/npm/registry.npmjs.org/tedious/15.1.2/lib/connection.js:2402:25
    at Object.runMicrotasks (deno:core/01_core.js:377:30)
    at processTicksAndRejections (https://deno.land/std@0.165.0/node/_next_tick.ts:62:10)
------------- MSSQL ERROR END ---------------
```

Many thanks

**Comment by bartlomieju** [comment]
Seems like this was already reported in https://github.com/denoland/deno/issues/16681
