### ISSUE TITLE
Uncaught AddrInUse when restarting server in watch mode after saving file 

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#16699]
Source: https://stackoverflow.com/questions/74444443/deno-watcher-uncaught-addrinuse-only-one-usage-of-each-socket-address

Reproduction:

- Run the code below with `deno run -A --watch server.ts`:

```ts
import express, { Express, Request, Response } from "npm:express@4.18";
import { v4 as uuidv4 } from 'npm:uuid@9.0.0';
const app: Express = express();

app.use("/", (_req: Request, res: Response) => {
    res.send(`uuid: ${uuidv4()}.`);
})

app.listen(8000, () => {
    console.log("App Running: http://localhost:8000");
});
```

- Make a change and save the file (either with auto-save or manually)
- When the file watcher restarts the error is thrown

```
Watcher File change detected! Restarting!
error: Uncaught AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
Watcher Process finished. Restarting on file change...
```

I found that this error can happen when there is another process listening on the same port: https://stackoverflow.com/a/62190276/12769288, so maybe the file watcher tries to restart the server while the previous one is still listening?

Additionally the same error seems to happen on occasion in one of the tests: https://github.com/denoland/deno/issues/16044

**Comment by wesbos** [comment]
Having this issue too. I can't use --watch with an express server because it says the port is in use after the first restart.

I think deno is _too fast_ and it restarts the app before the express server can release the port.

**Comment by wesbos** [comment]
I don't think it's time bound after doing some tests. I think maybe an issue with the `beforeExit` event not firing?

**Comment by bartlomieju** [comment]
The fix is in https://github.com/denoland/deno/pull/16616. I'll try to land that PR tonight.

**Comment by wesbos** [comment]
Still an issue in 1.28.3

**Comment by GJZwiers** [comment]
Seems like it resurfaced in 1.28.3 because I can't reproduce it on 1.28.2

**Comment by jakub-gawryl** [comment]
I can confirm that I have very same issue on Windows 10 + WSL 2 linux subsystem but in my case there's additional info: 
```
Watcher File change detected! Restarting!
error: Uncaught AddrInUse: Address already in use (os error 98)
    core.runMicrotasks();
         ^
    at Object.runMicrotasks (deno:core/01_core.js:377:30)
    at processTicksAndRejections (https://deno.land/std@0.167.0/node/_next_tick.ts:62:10)
Watcher Process finished. Restarting on file change...
```

**Comment by felipe300** [comment]
I'm having the same problem with linux Pop!OS

```bash
Watcher File change detected! Restarting!
error: Uncaught AddrInUse: Address already in use (os error 98)
    core.runMicrotasks();
         ^
    at Object.runMicrotasks (deno:core/01_core.js:377:30)
    at processTicksAndRejections (https://deno.land/std@0.167.0/node/_next_tick.ts:62:10)

```

**Comment by synthbeat** [comment]
> I'm having the same problem with linux Pop!OS
> 
> ```shell
> Watcher File change detected! Restarting!
> error: Uncaught AddrInUse: Address already in use (os error 98)
>     core.runMicrotasks();
>          ^
>     at Object.runMicrotasks (deno:core/01_core.js:377:30)
>     at processTicksAndRejections (https://deno.land/std@0.167.0/node/_next_tick.ts:62:10)
> ```

Can confirm same bug still present on macOS.

deno 1.29.1 (release, x86_64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4

**Comment by jesusandres31** [comment]
still same error on deno 1.29.2 (release, x86_64-pc-windows-msvc)

**Comment by bartlomieju** [comment]
The work to fix this issue is being done out-of-bounds in another repo. We expect to ship the rewrite in v1.31 in February.

**Comment by geric** [comment]
no longer an issue on 1.31.0.

**Comment by GJZwiers** [comment]
Cannot reproduce anymore either, I will close this now.

**Comment by MihaiSturza** [comment]
i found this issue is still there while using the unstable FlashServer

**Comment by ynwd** [comment]
```ts
await Deno.serve(() => new Response("Hello World!"));
```

```
deno run -A --unstable --watch main.ts   
```

```
Watcher File change detected! Restarting!
error: Uncaught (in promise) AddrInUse: Address already in use (os error 48)
Watcher Process finished. Restarting on file change...
```

**Comment by markc** [comment]
Same here with the basic test suggested by @ynwd...

    ~ deno -V
    deno 1.31.2

    deno run -A --unstable --watch main.ts
    Watcher Process started.
    Listening on http://127.0.0.1:9000/

    # edit main.ts

    Watcher File change detected! Restarting!
    error: Uncaught AddrInUse: Address already in use (os error 98)
    Watcher Process finished. Restarting on file change...

    ~ sudo netstat -tanup | grep 9000
    tcp  0  0  127.0.0.1:9000  0.0.0.0:*  LISTEN  143534/deno

**Comment by sstiglitz** [comment]
I ran into the same problem on 1.31.1, upgraded to 1.31.2 with fingers crossed, but same thing.

As a workaround to the problem, this seems to work for me.

```ts
import { Server } from 'https://deno.land/std@0.179.0/http/server.ts'

const handler = () => new Response('Hello World!')
const hostname = 'localhost'
const port = 8080

const server = new Server({ hostname, port, handler })
console.log(`Starting to listen on port ${port}`)
server.listenAndServe()

globalThis.addEventListener('unload', () => {
  server.close()
})
```

**Comment by markc** [comment]
@sstiglitz would you have any idea how this strategy could be applied to Deno Fresh?

**Comment by csulit** [comment]
Still an issue with the latest version.

Still an issue 

Watcher File change detected! Restarting!
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'port')
  port = (server.addrs[0] as Deno.NetAddr).port;
                                           ^
    at serve (https://deno.land/std@0.150.0/http/server.ts:591:44)
    at start (https://deno.land/x/fresh@1.1.4/src/server/mod.ts:70:11)
    at async file:///Users/christianangelosulit/Documents/GitHub/kmc/deno_project/my-project/main.ts:13:1
Watcher Process finished. Restarting on file change...
^C
xxx@Christians-MacBook-Pro-2 my-project % 
xxx@Christians-MacBook-Pro-2 my-project % 
xxx@Christians-MacBook-Pro-2 my-project % deno upgrade
Looking up latest version
Local deno version 1.31.2 is the most recent release

**Comment by markc** [comment]
For now, until the issue is fixed, the easiest workaround is to downgrade to v1.30.0

    sudo deno upgrade --version 1.30.0

**Comment by GJZwiers** [comment]
For the people getting this isue when using `std/http/server.ts`, the issue should get fixed in the next patch release.

For the people getting this issue when using `Deno.serve`, I have made a separate issue: https://github.com/denoland/deno/issues/18186.

@Csulit It seems you are getting a different kind of error message, possibly a bug in Fresh. I suggest creating an issue over in that repository.

**Comment by ryansb** [comment]
For brew users, the workaround is:

```bash
# the cask version that pointed to deno@1.30.0
FORMULA_URL='https://raw.githubusercontent.com/Homebrew/homebrew-core/2b3035ebfc70660dc8753678b43404d5d8016f99/Formula/deno.rb'
# get the .rb file locally
curl -O $FORMULA_URL
# replace the installed deno with the v1.30.0 version
brew uninstall deno
brew install ./deno.rb
```

**Comment by DwieDave** [comment]
> # the cask version that pointed to deno@1.30.0

Do you have an URL to deno@1.31.1 because that for me was the last version without this error.
How did you get the URL to the old formula version?

**Comment by mrtornado** [comment]
I had the same issue here after I upgraded to 1.31.1 so I downgraded to 1.31.0 since it was working fine for me. Just stay at 1.31.0 until we have a fix.

**Comment by youwei997** [comment]
Thanks, 1.31.0 is normal. I had a problem with the update to 1.31.2 before, and I feel that this kind of problem should not have happened

**Comment by youwei997** [comment]
> I had the same issue here after I upgraded to 1.31.1 so I downgraded to 1.31.0 since it was working fine for me. Just stay at 1.31.0 until we have a fix.

Thanks, 1.31.0 is normal. I had a problem with the update to 1.31.2 before, and I feel that this kind of problem should not have happened

**Comment by CarlosAmaral** [comment]
Same problem on version `1.31.2` with fresh

**Comment by GJZwiers** [comment]
The issue is fixed on version `1.31.3` so closing this, but the `Deno.serve` bug seems to be there still, for which https://github.com/denoland/deno/issues/16267 is still open.

**Comment by RrNn** [comment]
Looks like it crept in again on version [1.32.3](https://github.com/denoland/deno/releases/tag/v1.32.3)

**Comment by GJZwiers** [comment]
Can reproduce it as well on 1.32.3, reopening issue.

**Comment by bartlomieju** [comment]
@GJZwiers this problem has been fixed and will be released in v1.32.4 next week.

**Comment by GJZwiers** [comment]
@bartlomieju Thanks, it seems fixed indeed. I will close this again after 1.32.4 is released.

**Comment by starrematte** [comment]
Hi all. Until the next week release, I found a solution by using the `serveListener`:

``` typescript
import { serveListener } from "https://deno.land/std@0.182.0/http/server.ts";

const listener = Deno.listen({ port: 8080 })

await serveListener(listener, (req) => {
  console.log("handling", JSON.stringify(req.url))
  return new Response("hello there!", { status: 200 })
})

```

Cheers!

**Comment by keelii** [comment]
Same problem on version 1.33.2:

```bash
➜  express5 deno --version
deno 1.33.2 (release, x86_64-apple-darwin)
v8 11.4.183.1
typescript 5.0.3
```

```js
import express from "npm:express"

const app = express()

app.get('/', (req, res) => {
    res.send('hello world')
})

app.listen(3000)

console.log("Serve is listen on port: ", 3000)
```

**Comment by sant123** [comment]
I'm having the same issue 😕 

![image](https://user-images.githubusercontent.com/7959437/236384460-3609642e-f504-433d-9d2c-fa68b9dd2cd2.png)

![image](https://user-images.githubusercontent.com/7959437/236384488-a6309ac7-f6ac-4740-953c-8351d208ada2.png)

**Comment by bartlomieju** [comment]
See https://github.com/denoland/deno/issues/18960, it will be fixed next week.

**Comment by ooyay** [comment]
still in 1.33.2 at my koa project, but doing this its woking..

```ts
const server = app.listen(PORT)
addEventListener('unload', () => {
  server.close()
})

**Comment by lionel-rowe** [comment]
@bartlomieju I'm still having the same issue while using [fresh](https://github.com/denoland/fresh)@1.1.2, as of [the latest commit](https://github.com/denoland/deno/commit/dad7744f2c7492ceece67ed28a8e5651fba797b6) (including #18998) built with `cargo build --release`, WSL on Windows 11 with Ubuntu 22.04.2 LTS.

**Comment by bartlomieju** [comment]
CC @mmastrac

**Comment by bartlomieju** [comment]
@lionel-rowe was that a debug or release build?

**Comment by dsherret** [comment]
Release (`cargo build --release`)

**Comment by xxxhussein** [comment]
same thing in 1.34.3

**Comment by avalero** [comment]
Sill an issue on Deno 1.40

**Comment by PierreCapo** [comment]
Same issue on recent Deno versions. I am on MacOS 14.2. It makes the watcher completely unusable sadly

**Comment by emehmet** [comment]
Same issue on Deno v1.43.3. I use Apllo server and expressjs on Linux debian 12. It's like every refresh opens a different thread. Each opened thread is giving a different addrinuse error.

**Comment by StephenHaney** [comment]
Having this issue with Deno.serve and a Hono router in Deno v1.45.4.

Also, my Deno.serve is still running even though I've exited the terminal completely – maybe related?

**Comment by sveisvei** [comment]
Reproducable with adding 
```
addEventListener("hmr", (e) => {
   console.log("HMR triggered", e);
});
```

**Comment by maliknajjar** [comment]
same issue in deno v1.46.2
when I run the hono server without watch and press on CTRL+C it shutdown gracefully
but when I use the watch mode it doesn't. it shuts down immediately
Im adding SIGTERM and SIGINT signals to shutdown gracefully

**Comment by noelforte** [comment]
Chiming in that this is reproducable in Deno 2.0.0, I'm using Signal Listeners for `SIGINT` and `SIGTERM` to gracefully shut down the server and remove the UNIX domain socket file that `.serve()` is running on, but when running with `--watch` the server exits immidiately without letting my handlers clean up. 

If this is intentional behavior then there should be documentation on the proper way to clean up `.sock` files when exiting.

**Comment by invalidred** [comment]
I'm on Deno 2.0.3, added a "Deno.addSignalListener" like so

```
    const cronJob = startPublishCronJob(context);
    cronJob.start();
    Deno.addSignalListener('SIGINT', () => {
      console.log('Terminating publish cronJob');
      cronJob.stop();
      Deno.exit();
    })
```

and the issue ` Uncaught (in promise) AddrInUse: Address already in use (os error 48): Address already in use (os error 48)` started surfacing in watch mode.

**Comment by altpharoouq** [comment]
@invalidred Did you fix the issue? I'm getting the same error.

**Comment by satyarohith** [comment]
Divy and Satya tested the following script on both Windows & macOS with `deno 2.3.1` and we couldn't trigger the error:
```
import express, { Express, Request, Response } from "npm:express@4.18";
import { v4 as uuidv4 } from 'npm:uuid@9.0.0';
const app: Express = express();

app.use("/", (_req: Request, res: Response) => {
    res.send(`uuid: ${uuidv4()}.`);
})

app.listen(8000, () => {
    console.log("App Running: http://localhost:8000");
});
```

@altpharoouq/@invalidred can you provide a reproducible example to trigger the bug?

**Comment by k3dom** [comment]
Getting the same issue on 2.3.6.
