### ISSUE TITLE
'npm:graphql-tag' does not provide an export named 'gql'

### ISSUE THREAD

**Issue by lcswillems** [denoland/deno#16708]
This is my TS script:

```
import { gql } from "npm:graphql-tag";

gql;
```

When I run it with `deno run -A main.ts`, I get this error:

```
error: Uncaught SyntaxError: The requested module 'npm:graphql-tag' does not provide an export named 'gql'
import { gql } from "npm:graphql-tag";
```

This is anormal because the graphql-tag does export a gql object.

**Comment by brenelz** [comment]
I think its a default export like follows:

```
import gql from "npm:graphql-tag";

const query = gql.default`
  {
    user(id: 5) {
      firstName
      lastName
    }
  }`;

console.log(query);

```

**Comment by lcswillems** [comment]
I don't think so.

To be more concrete about my use case, this TS code:

```
import Client, { connect } from "npm:@dagger.io/dagger@0.1.0";

// initialize Dagger client
connect(async (client: Client) => {
  // get Node image
  // get Node version
  const node = await client.container().from("node:16").exec(["node", "-v"]);

  // execute
  const version = await node.stdout().contents();

  // print output
  console.log("Hello from Dagger and Node " + version.contents);
});
```

doesn't work with Deno (because of the error above) while it works in Node.js.

**Comment by NReilingh** [comment]
Experienced the same issue when making a similar effort to that of OP.

I discovered that I was able to (at least partially) use @dagger.io/dagger by importing it from esm.sh as in the following:

```typescript
import Client, { connect } from "https://esm.sh/@dagger.io/dagger@0.6.0";

import process from 'node:process';

connect(async (client: Client) => {

  const node = await client.container().from("node:16").exec(["node", "-v"]);

  const version = await node.stdout().contents();

  console.log("Hello from Dagger and Node " + version.contents);

}, { LogOutput: process.stdout });
```

You will find that `deno run -A main.ts` now fails with a different error:

<details><summary><code>Uncaught InitEngineSessionBinaryError: failed to download dagger cli binary: TypeError: d.pipe is not a function</code></summary>

```
error: Uncaught InitEngineSessionBinaryError: failed to download dagger cli binary: TypeError: d.pipe is not a function
    at G.<anonymous> (https://esm.sh/v124/@dagger.io/dagger@0.6.0/deno/dagger.mjs:8:23837)
    at Generator.throw (<anonymous>)
    at T (https://esm.sh/v124/@dagger.io/dagger@0.6.0/deno/dagger.mjs:8:22256)
    at eventLoopTick (ext:core/01_core.js:181:11)
Caused by: TypeError: d.pipe is not a function
    at https://esm.sh/v124/@dagger.io/dagger@0.6.0/deno/dagger.mjs:9:679
    at new Promise (<anonymous>)
    at G.<anonymous> (https://esm.sh/v124/@dagger.io/dagger@0.6.0/deno/dagger.mjs:9:618)
    at Generator.next (<anonymous>)
    at l (https://esm.sh/v124/@dagger.io/dagger@0.6.0/deno/dagger.mjs:8:22205)
    at eventLoopTick (ext:core/01_core.js:181:11)
```

</details>

... however, this can be worked around using the [Dagger CLI](https://docs.dagger.io/cli) with `dagger run deno run -A main.ts`. This is because `dagger run` sets up a session which it provides to the Dagger SDK using environment variables, whereas otherwise the SDK will attempt to download and run the Dagger CLI itself to create the session. The listed error appears to be related to this mechanism, which is not needed when invoking Deno from within the Dagger CLI.

P.S. Dagger now has an issue for Deno support: https://github.com/dagger/dagger/issues/4368

**Comment by danimydev** [comment]
Hey, I just encountered this issue, after some failures this ended up working for me.

```typescript
import * as graphqlTag from "graphql-tag";
const typeDefs = graphqlTag.default.gql(Deno.readTextFileSync("./schema.graphql"));
```
