### ISSUE TITLE
`npm:aws-cdk synth` fails (windows only)

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#16714]
Steps to reproduce:

- Run `mkdir infra && cd infra`
- Run `deno run -A npm:aws-cdk init --language typescript`
- Run `deno run -A npm:aws-cdk synth`

Normally this prints a CloudFormation template to the terminal, but on Deno + Windows it throws:

```
'\"npx ts-node --prefer-ts-exts bin/infra.ts\"' is not recognized as an internal or external command,
operable program or batch file.

Subprocess exited with error 1
```

The command in the error can be found in the `app` field in `cdk.json`

**Comment by antspk** [comment]
I made it work by changing it to:
```json
{
   "app": "deno run --allow-all bin/infra.ts",
}
```

This seems to solve synth error, however when attempting to run deploy command it fails this error:
```
 ❌ Deployment failed: Error: Stack Deployments Failed: Error: process is not defined
    at deployStacks (file:///Users/deno/Library/Caches/deno/npm/registry.npmjs.org/aws-cdk/2.55.1/lib/deploy.ts:61:11)
    at Object.runMicrotasks (deno:core/01_core.js:386:30)
    at processTicksAndRejections (https://deno.land/std@0.168.0/node/_next_tick.ts:50:14)
    at CdkToolkit.deploy (file:///Users/deno/Library/Caches/deno/npm/registry.npmjs.org/aws-cdk/2.55.1/lib/cdk-toolkit.ts:339:7)
    at initCommandLine (file:///Users/deno/Library/Caches/deno/npm/registry.npmjs.org/aws-cdk/2.55.1/lib/cli.ts:374:12)
```

The internal cli code seems to be using node's `process` const which causes the failure.

I'm attempting to sort of polyfill that like this:
```typescript
import * as process from "https://deno.land/std@0.168.0/node/process.ts";
import * as cdk from "npm:aws-cdk";

// @ts-ignore
window.process = process;

await cdk.cli();
```

But now I'm facing another error:
```shell
error: Could not resolve 'npm:aws-cdk'.

Caused by:
    not found
```

The deno version I'm using is: 1.29.1

**Comment by antspk** [comment]
I just actually moved past that as well:
```typescript
import * as process from "https://deno.land/std@0.168.0/node/process.ts";
// @ts-ignore
window.process = process;

import * as cdk from "npm:aws-cdk@2.55.1/lib/index.js";

await cdk.cli();
```
With this I'm setting global `process` variable that can be picked up by the cli code, this seems to somewhat work, but I get a lot of these errors:
```shell
Do you wish to deploy these changes (y/n)? y
DenoCdkAppStack (deno-cdk-app): deploying... [1/1]
not implemented: ClientRequest.setTimeout
not implemented: ClientRequest.setTimeout
not implemented: ClientRequest.setTimeout
[0%] start: Publishing 05eb0bfd143df5eec65e862d423b8fceff79b1a38261f0c3c452550f5985ab7a:current_account-current_region
[0%] start: Publishing 7029d7175344d4c4ca6be03f47bc39aa49697e5bfb874cf93f7eeb62292245b9:current_account-current_region
[0%] start: Publishing bebbc9d8aba66b0da2315302559e158c66a6c1df5fc8c4a54bd5f2f8dd665443:current_account-current_region
not implemented: ClientRequest.setTimeout
```

And the deployment doesn't seem to work.

**Comment by GJZwiers** [comment]
On windows I still get the error when the command is changed. Seems like maybe the escaped double quotes are kept in the command causing it to be invalid?

```
'\"deno run --allow-all bin/infra.ts\"' is not recognized as an internal or external command,
operable program or batch file.

Subprocess exited with error 1
```

**Comment by GJZwiers** [comment]
This no longer happens on the latest canary version of `std` and `deno run -A npm:aws-cdk synth` can be used successfully. Closing this issue.
