### ISSUE TITLE
VS code error when typing ctx

### ISSUE THREAD

**Issue by spaceexperiment** [denoland/deno#16715]
I have this 
```
import { Application } from "./deps.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response.body = "hello world";
});

await app.listen({ port: 8000 });
```

whenever I start typing `app.use((ctx))` before I get a chance to finish the function `(ctx) => ...` vscode throws an error.

Here is the error
```
Unable to get completion info from TypeScript: Error: Debug Failure. False expression.
    at getCompletionEntryCodeActionsAndSourceDisplay (deno:cli/tsc/00_typescript.js:135811:22)
    at Object.getCompletionEntryDetails (deno:cli/tsc/00_typescript.js:135749:30)
    at Object.getCompletionEntryDetails (deno:cli/tsc/00_typescript.js:168220:35)
    at serverRequest (deno:cli/tsc/99_main_compiler.js:1006:27)
    at [deno:cli/lsp/tsc.rs:3425:27]:1:12
[Error - 9:25:28 PM] Request completionItem/resolve failed.
  Message: Internal error
  Code: -32603 
```

My vscode settings
```
{
  "deno.enable": true,
  "deno.lint": true,
  "[typescript]": {
    "editor.defaultFormatter": "denoland.vscode-deno",
    "editor.formatOnSave": true
  },
}
```

**Comment by nayeemrmn** [comment]
@spaceexperiment Are you still experiencing this bug? If so, please provide repro instructions like the exact typing order. I haven't been able to reproduce it.

**Comment by spaceexperiment** [comment]
@nayeemrmn Just tested again, wasn't able to reproduce the same issue.

**Comment by spaceexperiment** [comment]
I guess we can close this issue?
