### ISSUE TITLE
Puppeteer with firefox does not work as I follow the docs

### ISSUE THREAD

**Issue by meepeek** [denoland/deno#16727]
The following code works fine without param product: 'firefox'
```
import { puppeteer } from "../_deps.ts";

const browser = await puppeteer.default.launch({headless: false, product: 'firefox'});
const page = await browser.newPage();

await browser.close();
```
The error log getting from running the code is as follow
```
thee@test % PUPPETEER_PRODUCT=firefox deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts
Already downloaded at /Users/thee/Library/Caches/deno/deno_puppeteer/firefox/mac-109.0a1/Firefox Nightly.app/Contents/MacOS/firefox
thee@test % deno run -A pair_id_to_symbol_info.ts                                                           
error: Uncaught NotFound: No such file or directory (os error 2)
    this.proc = Deno.run({
                     ^
    at opRun (deno:runtime/js/40_process.js:33:16)
    at Object.run (deno:runtime/js/40_process.js:116:17)
    at BrowserRunner.start (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:64:22)
    at FirefoxLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:271:12)
    at async file:///Users/thee/git-repo/family-fund-mono-repo/deno/service/stock_data/collector/symbol/investing_com/test/pair_id_to_symbol_info.ts:4:17
thee@test % deno --version
deno 1.28.1 (release, aarch64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
thee@test % 
```

**Comment by dsherret** [comment]
I think open a bug in https://github.com/lucacasonato/deno-puppeteer ?
