### ISSUE TITLE
Support npm:pm2

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#16753]
> @iugo how is it same error? What command are you trying to run?

run command `deno run -A npm:pm2 --help`.

same error, error info is `x.y.z is not a function`.

_Originally posted by @iugo in https://github.com/denoland/deno/issues/16679#issuecomment-1322852714_

**Comment by khrj** [comment]
Min. example

```js
import chalk from "npm:chalk@3"
console.log(chalk.bold.green("Hello"))
```

Errors:

```
error: Uncaught TypeError: chalk.bold.green is not a function
console.log(chalk.bold.green("Hello"))
                       ^
```

**Comment by khrj** [comment]
The same issue is also present when using `createRequire`

![image](https://user-images.githubusercontent.com/44947946/203253542-fde58efc-600f-4418-bff8-67876a0f4970.png)

**Comment by khrj** [comment]
I've dissected through the code for chalk v3 and have managed to get pure JS code that works in node, but fails in Deno. I'm not completely sure yet but it seems like Node is handling object prototypes differently from Deno, I'll try to get a cleaner example and then post it here

**Comment by khrj** [comment]
Note that the code works in node and not in Deno even when not using npm specifiers / createRequire, so this isn't an issue with the npm compatibility layer (or std/node)

**Comment by khrj** [comment]
Duplicate of https://github.com/denoland/deno/issues/13321

**Comment by bartlomieju** [comment]
If this is because of chalk@3 then it's because of missing "__proto__" that Deno doesn't support and will not in the future. So the best bet is to ask pm2 maintainers to update their dependencies.

**Comment by khrj** [comment]
Yes, it is because of that -- is there no chance of implementing __proto__ to internally call `Object.setPrototypeOf`? I've run grep through the node_modules of the top 10 packages on npm and nearly all of them have `.__proto__` somewhere.

**Comment by iuioiua** [comment]
FYI, @khrj is aiming to fix this in https://github.com/Unitech/pm2/pull/5489

**Comment by khrj** [comment]
Note that even after proto is fixed, pm2 will still be broken by #16784

**Comment by bartlomieju** [comment]
This still doesn't work for me. It appears that we're not correctly handling "ipc" option in `child_process` module in `new ChildProcess()`:

```js
Spawning PM2 daemon with pm2_home=/Users/ib/.pm2
spawning
caught error Error: Not implemented: toDenoStdio pipe=string (ipc)
    at notImplemented (ext:deno_node/_utils.ts:27:9)
    at toDenoStdio (ext:deno_node/internal/child_process.ts:379:5)
    at new ChildProcess (ext:deno_node/internal/child_process.ts:197:16)
    at Object.spawn (node:child_process:192:10)
    at module.exports.Client.launchDaemon (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/pm2/5.3.1/lib/Client.js:256:40)
    at file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/pm2/5.3.1/lib/Client.js:104:10
    at file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/pm2/5.3.1/lib/Client.js:321:14
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:37:11)
    at eventLoopTick (ext:core/01_core.js:166:29)
error: Uncaught TypeError: Cannot read properties of undefined (reading 'unref')
    at ChildProcess.unref (ext:deno_node/internal/child_process.ts:323:19)
    at module.exports.Client.launchDaemon (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/pm2/5.3.1/lib/Client.js:274:9)
    at file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/pm2/5.3.1/lib/Client.js:104:10
    at file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/pm2/5.3.1/lib/Client.js:321:14
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:37:11)
    at eventLoopTick (ext:core/01_core.js:166:29)

```

CC @littledivy is it something you could look at? Since we already support IPC in subprocesses it feels like there's something misconfigured that makes it crash.

**Comment by littledivy** [comment]
@bartlomieju I'm not getting the IPC error. It fails on `.unref`
```
$ deno run -A --unstable-unsafe-proto npm:pm2 --help
[PM2] Spawning PM2 daemon with pm2_home=/home/divy/.pm2
error: Uncaught TypeError: Cannot read properties of undefined (reading 'unref')
    at ChildProcess.unref (ext:deno_node/internal/child_process.ts:221:19)
    at module.exports.Client.launchDaemon (file:///home/divy/.cache/deno/npm/registry.npmjs.org/pm2/5.3.1/lib/Client.js:274:9)
    at file:///home/divy/.cache/deno/npm/registry.npmjs.org/pm2/5.3.1/lib/Client.js:104:10
    at file:///home/divy/.cache/deno/npm/registry.npmjs.org/pm2/5.3.1/lib/Client.js:321:14
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:25:11)
    at eventLoopTick (ext:core/01_core.js:166:29)
```

**Comment by bartlomieju** [comment]
@littledivy - correct. I added additional logs to surface that error (the catch handler for when the process is spawned).

**Comment by littledivy** [comment]
Ah, I see the problem now. Our implementation only supports non-stdio IPC.

We need to implement support for `stdio` as raw fds and "ipc" in `Deno.Command`.

```js
const process = new Deno.Command(command, {
  stdout: "pipe",
  // or stdout: 3
}).spawn();
```

**Comment by bartlomieju** [comment]
Huh, i thought we already had it. Is it any different than the current IPC support we have?

**Comment by littledivy** [comment]
This should be straightforward to implement:

- Add "ipc" (or maybe "ipc_for_internal_use") in `Deno.Command`'s stdin, stdout, stderr. Set the `args.ipc` FD and the ipc code path should automatically setup the channels.

- Allow numeric rids in `Deno.Command`'s stdio options that deserialize to `StdioOrRid` in `runtime/ops/process.rs`, there is already code to map file rids to stdio in there from `Deno.run`.

- Finally, allow "ipc" and numeric values in the `toDenoStdio` conversion in `ext/node/child_process.ts`

**Comment by littledivy** [comment]
stdio IPC support landed. A few more things to solve before this works:

By default, pm2 spawns its daemon using node (hard-coded). The
daemon fails to start in non-BYONM context because of Node doesn't 
understand Deno npm resolution doesn't work.

In BYONM context the daemon spawns but expects IPC between Deno and Node
doesn't work because of implementation differences currently.

We have 2 options:
- Override `node <daemon>` to `deno run <daemon>` in child_process#spawn
- Try to connect with Node IPC

**Comment by birkskyum** [comment]
It would in general be great to have a way to override nested uses of node with deno, even by default, similar to the '--bun' flag used in that runtime (which will also be default eventually)

**Comment by OIRNOIR** [comment]
Any progress on this?
I'm trying to import pm2 to log uncaught errors:

```
pm2.launchBus((_err, pm2_bus) => {
	pm2_bus.on(
		"process:exception",
		(packet: {
			data: { stack: string; errors?: Error[] };
			process: pm2.ProcessDescription;
		}) => {
			logUncaughtException(packet);
		}
	);
});
```
but it fails with an internal `TypeError: this.set is not a function`.

**Comment by bartlomieju** [comment]
You need to use `--unstable-unsafe-proto` flag

**Comment by OIRNOIR** [comment]
Thanks!

**Comment by bartlomieju** [comment]
Gonna close this one as solved. With https://github.com/denoland/deno/pull/35192 and https://github.com/denoland/deno/pull/34738 in Deno 2.9 it will be very clear what you need to do to use `npm:pm2`. Thanks everyone for reports!
