### ISSUE TITLE
ReferenceError, bootstrap script using undefined values

### ISSUE THREAD

**Issue by orvitpng** [denoland/deno#16801]
Unsure what this error is about..

Using Windows 11, runtime 0.87, core 0.161.
```rs
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let main_module = deno_core::resolve_path("/home/carter/Code/evo/test.js")?;
    let mut worker = deno_runtime::worker::MainWorker::bootstrap_from_options(
        main_module.clone(),
        deno_runtime::permissions::Permissions::allow_all(),
        Default::default()
    );
    worker.execute_main_module(&main_module).await?;
    worker.run_event_loop(false).await?;

    Ok(())
}
```

```
thread 'main' panicked at 'Failed to execute bootstrap script: ReferenceError: bootstrap is not defined
    at [deno:C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\deno_runtime-0.87.0\worker.rs:264:24]:1:1', C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\deno_runtime-0.87.0\worker.rs:265:8
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\result.rs:1785
   3: enum2$<core::result::Result<tuple$<>,anyhow::Error> >::expect<tuple$<>,anyhow::Error>
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\result.rs:1064
   4: deno_runtime::worker::MainWorker::bootstrap
             at C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\deno_runtime-0.87.0\worker.rs:263
   5: deno_runtime::worker::MainWorker::bootstrap_from_options
             at C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\deno_runtime-0.87.0\worker.rs:139
   6: evo_runtime::main::async_block$0
             at .\src\main.rs:7
   7: core::future::from_generator::impl$1::poll<enum2$<evo_runtime::main::async_block_env$0> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
   8: tokio::park::thread::impl$5::block_on::closure$0<core::future::from_generator::GenFuture<enum2$<evo_runtime::main::async_block_env$0> > >
             at C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\park\thread.rs:267
   9: tokio::coop::with_budget::closure$0<enum2$<core::task::poll::Poll<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::future::from_generator::GenFuture<enum2$<evo_runtime::main::async_block_
             at C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\coop.rs:102
  10: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum2$<core::task::poll::Poll<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > >,tokio::par
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\thread\local.rs:445
  11: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum2$<core::task::poll::Poll<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > >,tokio::park::t
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\thread\local.rs:421
  12: tokio::coop::with_budget
             at C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\coop.rs:95
  13: tokio::coop::budget
             at C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\coop.rs:72
  14: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<enum2$<evo_runtime::main::async_block_env$0> > >
             at C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\park\thread.rs:267
  15: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<enum2$<evo_runtime::main::async_block_env$0> > >
             at C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\runtime\enter.rs:152
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<core::future::from_generator::GenFuture<enum2$<evo_runtime::main::async_block_env$0> > >
             at C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\runtime\scheduler\multi_thread\mod.rs:79
  17: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<enum2$<evo_runtime::main::async_block_env$0> > >
             at C:\Users\cd4sh\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\runtime\mod.rs:492
  18: evo_runtime::main
             at .\src\main.rs:15
  19: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,anyhow::Error> > (*)(),tuple$<> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\evo_runtime.exe` (exit code: 101)
```

**Comment by bartlomieju** [comment]
Please provide contents of `Code/evo/test.js`

**Comment by orvitpng** [comment]
@bartlomieju I don't see how that is necessary as the trace never even reaches the line to execute.
```js
console.log("Hello, world!");
console.log(Deno.version);
```

**Comment by bartlomieju** [comment]
@crowlKats please take a look

**Comment by bartlomieju** [comment]
Discussed offline. Our recent work in https://github.com/denoland/deno/pull/16597 broke it. Please downgrade to previous version for now, we'll fix it in the next release.
