### ISSUE TITLE
:bug: panic/error source map is incorrect for script files using CRLF EOLs and multiline comments

### ISSUE THREAD

**Issue by rivy** [denoland/deno#16815]
When running scripts with CRLF line endings, `deno` panics will display a broken/incorrect source mapping for panics if the script contains multiline comments with internal line feeds.

Minimal example script:

```typescript
/*
*/
const s = Deno.readTextFileSync('');
const x = 1;
```

- [*ex.CRLF.ts*](https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.CRLF.ts)
- [*ex.LF.ts*](https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.LF.ts)

The scripts from the gist have identical content except for CRLF vs LF line endings.

When executed, the CRLF EOL version has incorrect source mapping for the panic display (the correct output from the LF EOL is included for reference)...

```shell
>:: WinOS
>deno run -A https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.CRLF.ts
error: Uncaught NotFound: The system cannot find the path specified. (os error 3)
const x = 1;
          ^
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:42:16)
    at https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.CRLF.ts:4:11

>deno run -A https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.LF.ts
error: Uncaught NotFound: The system cannot find the path specified. (os error 3)
const s = Deno.readTextFileSync('');
               ^
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:42:16)
    at https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.LF.ts:3:16
```

```shell
$ # POSIX
$ deno run -A https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.CRLF.ts
Download https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.CRLF.ts
error: Uncaught NotFound: No such file or directory (os error 2)
Warning Couldn't format source line: Column 13 is out of bounds (source may have changed at runtime)
    at Object.opSync (deno:core/01_core.js:170:12)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:41:17)
    at https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.CRLF.ts:4:13

$ deno run -A https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.LF.ts
Download https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.LF.ts
error: Uncaught NotFound: No such file or directory (os error 2)
const s = Deno.readTextFileSync('');
               ^
    at Object.opSync (deno:core/01_core.js:170:12)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:41:17)
    at https://gist.githubusercontent.com/rivy/8cd9b3b276923994eba647fa17d05228/raw/d70259217e762cf3aab59b758650b8cec99bafb1/ex.LF.ts:3:16
```

**Comment by jinnosukeKato** [comment]
I also encountered the same issue.
My environment is as follows.

OS: Windows11
```sh
> deno --version
deno 1.30.3 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```
