### ISSUE TITLE
Deno.run() doesn't find `.cmd` executables in the PATH

### ISSUE THREAD

**Issue by NfNitLoop** [denoland/deno#16942]
# Problem:

`Deno.run()` is unable to execute .cmd files unless they include the `.cmd` extension.

# Expected:

When running on Windows, "foo" should be able to execute command `foo` whether it has an `.exe` or `.cmd` extension. (And possibly others? Do people still use `.bat`?)

# Reproduction:

```typescript
// bug.ts
async function run(...cmd: string[]) {
    const p = Deno.run({cmd})
    await p.status()
}

// is an .exe:
await run("protoc", "--version")

// workaround works, but requires always checking for Windows.
await run("npm.cmd", "--version")

// Does not work:
await run("npm", "--version")
```

# Output:

```
deno run -A bug.ts

libprotoc 3.20.2
7.19.0
error: Uncaught (in promise) NotFound: program not found
    const p = Deno.run({cmd})
                   ^
    at opRun (deno:runtime/js/40_process.js:33:16)
    at Object.run (deno:runtime/js/40_process.js:116:17)
    at run (file:///C:/Users/Cody/code/feoblog-client/private/protobuf/bug.ts:3:20)
    at file:///C:/Users/Cody/code/feoblog-client/private/protobuf/bug.ts:9:7
```

Note:in both the Windows Command Prompt and PowerShell, both `protoc` and `npm` are runnable as commands without specifying a file extension: 

```
> get-command protoc |Format-List

Name            : protoc.exe
CommandType     : Application
Definition      : C:\ProgramData\chocolatey\bin\protoc.exe
Extension       : .exe
Path            : C:\ProgramData\chocolatey\bin\protoc.exe
FileVersionInfo : File:             C:\ProgramData\chocolatey\bin\protoc.exe
                  InternalName:     protoc.exe
                  OriginalFilename: protoc.exe
                  FileVersion:      3.20.2.0
                  FileDescription:  Compiled with MSVC 19.0.24215.1 - Chocolatey
                  Shim
                  Product:          Protocol Buffers - Google's Data Interchange
                  Format - Chocolatey Shim
                  ProductVersion:   3.20.2.0 - Chocolatey Shim: 1.0.0
                  Debug:            False
                  Patched:          False
                  PreRelease:       False
                  PrivateBuild:     False
                  SpecialBuild:     False
                  Language:         Language Neutral


> get-command npm |Format-List

Name            : npm.cmd
CommandType     : Application
Definition      : C:\Program Files\nodejs\npm.cmd
Extension       : .cmd
Path            : C:\Program Files\nodejs\npm.cmd
FileVersionInfo : File:             C:\Program Files\nodejs\npm.cmd
                  InternalName:
                  OriginalFilename:
                  FileVersion:
                  FileDescription:
                  Product:
                  ProductVersion:
                  Debug:            False
                  Patched:          False
                  PreRelease:       False
                  PrivateBuild:     False
                  SpecialBuild:     False
                  Language:

```

# Workaround

You can check whether you're on windows and add a `.cmd`. However, this also requires you to know whether a particular tool is distributed on Windows as an `.exe` or a `.cmd`.  (i.e.: a blanket: "if windows, add .cmd" isn't a suitable fix, since it breaks anything that's distributed as an `.exe`.)

**Comment by dsherret** [comment]
By the way, https://github.com/dsherret/deno_which will search the PATH using the PATHEXT on Windows to find the executable path. It might be useful for you. The annoyance is it requires permissions to read all the directories specified on the PATH in order to find the executable.
