### ISSUE TITLE
bug(permissions): `revoke()` and `request()` don't modify `desc.path` for FFI

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#17020]
Should these lines include `desc.name === "ffi"` like `query()`?

https://github.com/denoland/deno/blob/890b0653104388bfef60ca7ebd0af758caf5f0be/runtime/js/10_permissions.js#L200

https://github.com/denoland/deno/blob/890b0653104388bfef60ca7ebd0af758caf5f0be/runtime/js/10_permissions.js#L219

**Comment by bartlomieju** [comment]
@iuioiua could you come up with a test that would demonstrate this bug?

**Comment by iuioiua** [comment]
Yep, it's a bug.

Code:
```ts
const path = new URL(import.meta.url);

await Deno.permissions.request({ name: "read", path });
await Deno.permissions.request({ name: "write", path });
await Deno.permissions.request({ name: "ffi", path });
```

Output:
```
asher@Ashers-MacBook-Air deno_std % deno run --unstable x.ts
✅ Granted read access to "/Users/asher/Documents/GitHub/deno_std/x.ts".
✅ Granted write access to "/Users/asher/Documents/GitHub/deno_std/x.ts".
error: Uncaught TypeError: Error parsing args at position 0: serde_v8 error: ExpectedString
await Deno.permissions.request({ name: "ffi", path });
                       ^
    at opRequest (deno:runtime/js/10_permissions.js:66:16)
    at Permissions.request (deno:runtime/js/10_permissions.js:225:21)
    at file:///Users/asher/Documents/GitHub/deno_std/x.ts:5:24
```
