### ISSUE TITLE
npm compat: nodejs-polars fails

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#17038]
```ts
import pl from "npm:nodejs-polars";
```
 ```
error: Could not find npm package 'nodejs-polars-android-arm64' matching 0.6.0. Try retrieving the latest npm package information by running with --reload
```

My system is not arm, its linux x86_64

**Comment by dsherret** [comment]
1. The nodejs-polars has an optional dependency on nodejs-polars-android-arm64: 0.6.0
2. nodejs-polars-android-arm64 does not have a version 0.6.0 published. The last published version is 0.5.4. This is likely a bug where they forgot to publish 0.6.0.
3. Deno is unnecessarily downloading optional dependencies. This is tracked in #15544

So let's track this in #15544.

**Comment by sigmaSd** [comment]
So using `import pl from "npm:nodejs-polars@0.5.4";` actually work

but trying to use it fails with an error
```ts
df = pl.DataFrame(
     {
         "A": [1, 2, 3, 4, 5],
         "fruits": ["banana", "banana", "apple", "apple", "banana"],
         "B": [5, 4, 3, 2, 1],
         "cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
     }
 )
```
```
Uncaught TypeError: polars_internal_1.default.JsSeries.newOptF64 is not a function
    at Float64 (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/datatypes.js:56:51)
    at arrayToJsSeries (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/internals/construction.js:143:18)
    at SeriesConstructor (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/series/series.js:652:55)
    at file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/dataframe.js:604:36
    at Array.map (<anonymous>)
    at objToDF (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/dataframe.js:600:41)
    at Object.DataFrameConstructor [as DataFrame] (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/dataframe.js:597:36)
    at <anonymous>:2:9
```

**Comment by dsherret** [comment]
Looks like some Node API related bug. Could you open a separate issue?
