### ISSUE TITLE
Error while using ioredis in deno 

### ISSUE THREAD

**Issue by SagarMahadik** [denoland/deno#17046]
I am trying to connect ioredis in deno app, the same works correctly on local machine, but fails on the Deno Deply.

**Import statement:**
import Redis from "https://esm.sh/ioredis";

**Error**

TypeError: Deno.unrefTimer is not a function
    at Timeout.unref (https://deno.land/std@0.165.0/node/internal/timers.mjs:42:10)
    at setUnrefTimeout (https://deno.land/std@0.165.0/node/timers.ts:26:38)
    at Socket.setStreamTimeout [as setTimeout] (https://deno.land/std@0.165.0/node/internal/stream_base_commons.ts:249:26)
    at https://esm.sh/v99/ioredis@4.28.5/deno/ioredis.js:105:37312
    at w (https://esm.sh/v99/standard-as-callback@2.1.0/deno/standard-as-callback.js:2:693)
    at https://esm.sh/v99/standard-as-callback@2.1.0/deno/standard-as-callback.js:2:1136

**Comment by hironichu** [comment]
Hello there,

The Deploy api is not the same as the CLI !
You can see the available APIs for Deploy here : https://deno.com/deploy/docs/runtime-api
( However there are a very few exception of some that aren't shown in this page but works.. Like Deno.listen.. and others )
Also due to how UnrefTimer has to work with the Event loop.. i may be wrong but it might just never be added to Deploy


As for a workaround I do not think Ioredis will work in Deploy for now.. 
What I suggest is either waiting for NPM support in Deploy (planned for 2023).. which may add support for that but don't take my word for it..  
Or use Deno CLI directly

**Comment by SagarMahadik** [comment]
@hironichu Thank you for your feedback.

Can you please help me with resource to understand how to deploy Deno CLI directly.

**Comment by hironichu** [comment]
My suggestion would be use Fly.io if you'd want to deploy a Deno app.

Basically what you're running on your computer would run there.

I don't know the details on how it can be setup, but it's the only free and simple solution i am aware of.

**Comment by SagarMahadik** [comment]
Thanks..Will give it a shot..

**Comment by littledivy** [comment]
Verified on a current build that `Deno.unrefTimer` is now implemented (`typeof Deno.unrefTimer === "function"`), so the CLI error in this report no longer reproduces. The remaining concern was specifically Deno Deploy not exposing the API, which is tracked outside this repository, and npm support (including `npm:ioredis`) has since landed. Closing as resolved for the Deno CLI.
