### ISSUE TITLE
Module resolution fails only when using `--node-modules-dir`

### ISSUE THREAD

**Issue by ayame113** [denoland/deno#17057]
I'm trying to run npm:firebase-tools with Deno.

If I don't use `--node-modules-dir` it runs fine.
```shell
> deno run -A --unstable npm:firebase-tools --version
11.17.0
```

But if I use `--node-modules-dir` I get an error.

```shell
> deno run -A --unstable --node-modules-dir npm:firebase-tools --version
error: Uncaught Error: Cannot find module 'readable-stream/passthrough'
Require stack:
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\lazystream@1.0.1\node_modules\lazystream\lib\lazystream.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\archiver-utils@2.1.0\node_modules\archiver-utils\index.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\archiver@5.3.1\node_modules\archiver\lib\core.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\archiver@5.3.1\node_modules\archiver\index.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\archiveDirectory.js 
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\extensions\extensionsHelper.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\deploy\extensions\planner.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\extensions\manifest.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorShared.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\emulator\functionsEmulator.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\emulator\controller.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\emulator\commandUtils.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\commands\database-get.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\commands\index.js   
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\index.js
- C:\Users\ayame\work\study\mon-cloudflare-endpoint\node_modules\.deno\firebase-tools@11.18.0\node_modules\firebase-tools\lib\bin\firebase.js     
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:624:17)
    at Function.Module._load (deno:ext/node/02_require.js:456:29)
    at Module.require (deno:ext/node/02_require.js:667:21)
    at require (deno:ext/node/02_require.js:807:18)
    at Object.<anonymous> (file:///C:/Users/ayame/work/study/mon-cloudflare-endpoint/node_modules/.deno/lazystream@1.0.1/node_modules/lazystream/lib/lazystream.js:2:19)
    at Object.<anonymous> (file:///C:/Users/ayame/work/study/mon-cloudflare-endpoint/node_modules/.deno/lazystream@1.0.1/node_modules/lazystream/lib/lazystream.js:56:4)
    at Module._compile (deno:ext/node/02_require.js:734:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:767:12)
    at Module.load (deno:ext/node/02_require.js:645:34)
    at Function.Module._load (deno:ext/node/02_require.js:502:14)
```

Viewing dependencies with `deno info`, it seems that there is only one version of the `readable-stream` package in the `node_modules` directory, even though it uses multiple versions of the `readable-stream` package.

```shell
> deno info npm:firebase-tools | findstr readable-stream
隨上・隨上・隨上・隨乗㈹讌ｳ隨擾ｽｬ npm:readable-stream@3.6.0 (119.43KB)
隨上・隨上・隨上・隨乗喚讌ｳ隨擾ｽｬ npm:readable-stream@2.3.7 (85.66KB)
隨上・隨上・隨乗喚讌ｳ隨渉 npm:readable-stream@2.3.7 (85.66KB) *
隨上・隨乗㈹讌ｳ隨渉 npm:readable-stream@3.6.0 (119.43KB) *
隨上・隨上・隨上・隨乗喚讌ｳ隨渉 npm:readable-stream@3.6.0 (119.43KB) *
隨上・隨上・隨乗喚讌ｳ隨渉 npm:readable-stream@3.6.0 (119.43KB) *
隨上・  隨上・隨上・隨乗喚讌ｳ隨渉 npm:readable-stream@3.6.0 (119.43KB) *
隨上・  隨上・隨乗喚讌ｳ隨渉 npm:readable-stream@3.6.0 (119.43KB) *
隨上・  隨乗喚讌ｳ隨渉 npm:readable-stream@3.6.0 (119.43KB) *
隨上・隨上・隨上・  隨乗㈹讌ｳ隨擾ｽｬ npm:readable-stream@1.1.14 (83.42KB)
隨上・隨上・  隨上・隨上・隨乗喚讌ｳ隨渉 npm:readable-stream@3.6.0 (119.43KB) *
隨上・  隨上・  隨上・隨乗㈹讌ｳ隨渉 npm:to-readable-stream@1.0.0 (2.72KB)
隨上・隨上・隨乗喚讌ｳ隨渉 npm:readable-stream@2.3.7 (85.66KB) *
隨上・隨乗㈹讌ｳ隨渉 npm:readable-stream@2.3.7 (85.66KB) *
隨上・隨乗㈹讌ｳ隨渉 npm:readable-stream@3.6.0 (119.43KB) *
隨上・  隨乗㈹讌ｳ隨渉 npm:readable-stream@3.6.0 (119.43KB) *
```

```shell
> Get-ChildItem -Directory -Name ./node_modules | findstr readable-stream
readable-stream
to-readable-stream
```

This problem occurs on Deno1.29 and windows.

```shell
> deno --version
deno 1.29.0 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by sigmaSd** [comment]
Maye its the same issue https://github.com/denoland/deno/issues/17068  

Does it skip the current directory when searching for node_modules ?

You can tell by running it without permissions, and it will prompt for the places its looking in

**Comment by dsherret** [comment]
@sigmaSd no, it's unrelated
