### ISSUE TITLE
npm compat: typescript-to-lua

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#17068]
https://github.com/TypeScriptToLua/TypeScriptToLua

`deno run  --node-modules-dir npm:typescript-to-lua a.ts`

it fails with 
```
error: Uncaught Error: Cannot find module 'typescript'
Require stack:
- /home/mrcool/.cache/deno/npm/registry.npmjs.org/typescript-to-lua/1.10.1/dist/tstl.js
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:624:17)
    at Function.Module._load (deno:ext/node/02_require.js:456:29)
    at Module.require (deno:ext/node/02_require.js:667:21)
    at require (deno:ext/node/02_require.js:807:18)
    at Object.<anonymous> (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/typescript-to-lua/1.10.1/dist/tstl.js:3:12)
    at Object.<anonymous> (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/typescript-to-lua/1.10.1/dist/tstl.js:177:4)
    at Module._compile (deno:ext/node/02_require.js:734:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:767:12)
    at Module.load (deno:ext/node/02_require.js:645:34)
    at Function.Module._load (deno:ext/node/02_require.js:502:14)
```

For some reason the search for node-modules-dir seems to be one directory up then needed,

If i'm in dir foo, and run the above command it says `Deno requests read access to "/parentOffoo/node_modules".`

So it seems it skipped the current dir

Taking a project that use tstl as an example https://github.com/jose-elias-alvarez/typescript.nvim

If I run npm install then deno run with the above command it actually works

**Comment by sigmaSd** [comment]
- touch a.ts # just an empty file
- deno run -A --node-modules-dir npm:typescript-to-lua a.ts

```
rror: Uncaught Error: Cannot find module 'typescript'
Require stack:
- /tmp/qb/node_modules/.deno/typescript-to-lua@1.10.1/node_modules/typescript-to-lua/dist/tstl.js
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:624:17)
    at Function.Module._load (deno:ext/node/02_require.js:456:29)
    at Module.require (deno:ext/node/02_require.js:667:21)
    at require (deno:ext/node/02_require.js:807:18)
    at Object.<anonymous> (file:///tmp/qb/node_modules/.deno/typescript-to-lua@1.10.1/node_modules/typescript-to-lua/dist/tstl.js:3:12)
    at Object.<anonymous> (file:///tmp/qb/node_modules/.deno/typescript-to-lua@1.10.1/node_modules/typescript-to-lua/dist/tstl.js:177:4)
    at Module._compile (deno:ext/node/02_require.js:734:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:767:12)
    at Module.load (deno:ext/node/02_require.js:645:34)
    at Function.Module._load (deno:ext/node/02_require.js:502:14)
```

meta 
```
deno 1.29.1 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```

If I don't give -A I can see the first folder its looking in is one directory off (doesn't seem to start searching from current dir)

![image](https://user-images.githubusercontent.com/22427111/208184291-f22fc300-2acf-4c65-a0d5-c7f076739e7a.png)

**Comment by dsherret** [comment]
It will search from the current dir. It just is implicitly granted read permissions to the `node_modules` directory so it doesn't show up there.

Does your node_modules/.deno/typescript-to-lua@1.10.1/node_modules folder contain a typescript directory? Also, does this occur when you delete your deno cache ($DENO_DIR) and node_modules directory? I'm not able to reproduce it on either Windows or Mac.

**Comment by sigmaSd** [comment]
I don't have typescript folder

I deleted the whole cache and now it works, I don't need even  --node-modules-dir flag

Thanks

**Comment by dsherret** [comment]
If there was no typescript folder then I think it was maybe some out of date information being stored in the cache before we had peer dependency support. That's strange though.

**Comment by sigmaSd** [comment]
I understand these bugs are annoying to hunt, so far it seems to work tough if I can reproduce something I can open a pr with more details

The only other thing I can think about is npm interaction with deno, as if I use deno run --node-modules-dir then sometimes I use npm install not sure if that can mess something
