### ISSUE TITLE
npm compat: vite env-esm & devalue

### ISSUE THREAD

**Issue by andykais** [denoland/deno#17070]
I am attempting to run sveltekit in deno and I see these errors:
`deno run --reload -A npm:vite dev`
```
  VITE v4.0.1  ready in 2806 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
The following dependencies are imported but could not be resolved:

  esm-env (imported by /Users/andrew.kaiser/Library/Caches/deno/npm/registry.npmjs.org/@sveltejs/kit/1.0.0/src/runtime/app/environment.js)
  devalue (imported by /Users/andrew.kaiser/Library/Caches/deno/npm/registry.npmjs.org/@sveltejs/kit/1.0.0/src/runtime/client/client.js)

Are they installed?
TypeError: Cannot read properties of undefined (reading 'body')
    at handleResponse (deno:ext/flash/01_http.js:259:19)
    at deno:ext/flash/01_http.js:578:25
Failed to load url esm-env (resolved id: esm-env). Does the file exist?
TypeError: Cannot read properties of undefined (reading 'body')
    at handleResponse (deno:ext/flash/01_http.js:259:19)
    at deno:ext/flash/01_http.js:578:25
4:15:10 PM [vite-plugin-svelte] ssr compile done.
package           	files	  time	   avg
deno-sveltekit-1.0	    1	30.8ms	30.8ms
```

I was curious if these modules had trouble resolving in deno, but that does not appear to be the case:

```
$ deno repl
Deno 1.29.1
exit using ctrl+d, ctrl+c, or close()
> import * as test from 'npm:esm-env'
undefined
> test
Module { BROWSER: false, DEV: false }
> import * as test from 'npm:devalue'
undefined
> test
Module {
  parse: [Function: parse],
  stringify: [Function: stringify],
  uneval: [Function: uneval],
  unflatten: [Function: unflatten]
}
```

so my best guess is that vite/sveltekit is doing something weird here like executing a node program via cli. When I look at each permission grant I can see they do execute esbuild directly, so perhaps that is whats going on?
```
⚠️  ┌ Deno requests run access to "/Users/andrew/Library/Caches/deno/npm/registry.npmjs.org/@esbuild/darwin-arm64/0.16.7/bin/esbuild".
   ├ Requested by `Deno.Command().spawn()` API
   ├ Run again with --allow-run to bypass this prompt.
   └ Allow? [y/n] (y = yes, allow; n = no, deny) >
```

**Comment by andykais** [comment]
[edit] moving this report to the vite issue
