### ISSUE TITLE
npm compat: module imported via .node file is missing exports

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#17085]
```ts
import pl from "npm:nodejs-polars@0.5.4" // latest version that works with deno
```

```ts
df = pl.DataFrame(
     {
         "A": [1, 2, 3, 4, 5],
         "fruits": ["banana", "banana", "apple", "apple", "banana"],
         "B": [5, 4, 3, 2, 1],
         "cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
     }
 )
```

errors with 
```
Uncaught TypeError: polars_internal_1.default.JsSeries.newOptF64 is not a function
    at Float64 (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/datatypes.js:56:51)
    at arrayToJsSeries (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/internals/construction.js:143:18)
    at SeriesConstructor (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/series/series.js:652:55)
    at file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/dataframe.js:604:36
    at Array.map (<anonymous>)
    at objToDF (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/dataframe.js:600:41)
    at Object.DataFrameConstructor [as DataFrame] (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.5.4/bin/dataframe.js:597:36)
    at <anonymous>:2:9
```

**Comment by lilnasy** [comment]
Ran into the same issue [here](https://github.com/denoland/deno/issues/16460#issuecomment-1324234921).

**Comment by bartlomieju** [comment]
Note to self: discussed with Divy, this is a bug in our implementation of `napi_define_class`
