### ISSUE TITLE
Don't die on uncaught exceptions in REPL

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno#1709]
It isn't useful in REPL, only in scripts.

**Comment by bartlomieju** [comment]
Tried in v0.3.8 and REPL does not die with uncaught exception:
```ts
$ deno
> foobar()
<unknown>:1:0
foobar()
^
Uncaught ReferenceError: foobar is not defined
    at <unknown>:1:1
    at evaluate (js/repl.ts:87:34)
    at replLoop (js/repl.ts:145:13)
```

I guess we can close this now @sh7dm
