### ISSUE TITLE
Can we use a NPM package that depends on other NPM package BUT replace it with native Deno one?

### ISSUE THREAD

**Issue by emilekm2142** [denoland/deno#17118]
Hello.
I wanna use a package `npm:chatgpt` that depends on pupeteer. Since Pupeteer has it's native version for Deno, is there a possibility not to use the NPM one? Trying to use Pupeteer from NPM gives an error after the browser is opened:

```
error: Uncaught ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: {
      open: [Function: onOpen] { [Symbol(kIsForOnEventAttribute)]: false, [Symbol(kListener)]: [Function] },
      error: [Function: onError] { [Symbol(kIsForOnEventAttribute)]: false, [Symbol(kListener)]: [Function] }
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: "nodebuffer",
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: Buffer(0) [],
    _closeTimer: null,
    _extensions: {},
    _paused: false,
    _protocol: "",
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: "ws://127.0.0.1:56103/devtools/browser/a3621c99-e77f-4da1-886a-5bb182b5b4a8",
    _originalIpc: false,
    _originalSecure: false,
    _originalHostOrSocketPath: "127.0.0.1:56103",
    _req: null,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: "error",
  [Symbol(kError)]: Error: Unexpected server response: 101
    at ClientRequest.<anonymous> (file:///Users/user/Library/Caches/deno/npm/registry.npmjs.org/ws/8.11.0/lib/websocket.js:886:7)
    at ClientRequest.emit (https://deno.land/std@0.168.0/node/_events.mjs:379:28)
    at ClientRequest._final (https://deno.land/std@0.168.0/node/http.ts:156:10),
  [Symbol(kMessage)]: "Unexpected server response: 101"
}

```

**Comment by bartlomieju** [comment]
You can try to use an import map to remap `puppeteer` to another package.

**Comment by littledivy** [comment]
This is answerable with existing tooling: you can remap a transitive dependency via an import map / the `imports` field in `deno.json` (e.g. map `puppeteer` to another module). Separately, npm support has matured significantly since this was filed and `npm:puppeteer` generally works directly under Deno, so the original WebSocket error is unlikely to reproduce on current versions. Closing as resolved — happy to reopen with a fresh repro on a current Deno if the remap approach doesn't work.
