### ISSUE TITLE
Uncaught exception in a filtered test still results in all following tests to print "<name> ... cancelled (0ms)"

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#17122]
### Current

```
/m/a/P/g/d/deno ❯❯❯ cargo run test -A --unstable cli/tests/unit/fetch_test.ts --filter fetchInitFormDataMultipleFilesBody
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/deno test -A --unstable cli/tests/unit/fetch_test.ts --filter fetchInitFormDataMultipleFilesBody`
running 1 test from ./cli/tests/unit/fetch_test.ts
fetchInitFormDataMultipleFilesBody ...
Uncaught error from ./cli/tests/unit/fetch_test.ts FAILED
fetchRequiresOneArgument ... cancelled (0ms)
fetchProtocolError ... cancelled (0ms)
fetchConnectionError ... cancelled (0ms)
fetchDnsError ... cancelled (0ms)
fetchInvalidUriError ... cancelled (0ms)
fetchJsonSuccess ... cancelled (0ms)
fetchPerm ... cancelled (0ms)
fetchUrl ... cancelled (0ms)
fetchURL ... cancelled (0ms)
fetchHeaders ... cancelled (0ms)
fetchBlob ... cancelled (0ms)
fetchBodyUsedReader ... cancelled (0ms)
fetchBodyUsedCancelStream ... cancelled (0ms)
fetchAsyncIterator ... cancelled (0ms)
fetchBodyReader ... cancelled (0ms)
fetchBodyReaderBigBody ... cancelled (0ms)
responseClone ... cancelled (0ms)
fetchMultipartFormDataSuccess ... cancelled (0ms)
fetchMultipartFormBadContentType ... cancelled (0ms)
fetchURLEncodedFormDataSuccess ... cancelled (0ms)
fetchInitFormDataBinaryFileBody ... cancelled (0ms)
fetchInitFormDataMultipleFilesBody ... cancelled (0ms)
fetchWithRedirection ... cancelled (0ms)
fetchWithRelativeRedirection ... cancelled (0ms)
fetchWithRelativeRedirectionUrl ... cancelled (0ms)
fetchWithInfRedirection ... cancelled (0ms)
fetchInitStringBody ... cancelled (0ms)
fetchRequestInitStringBody ... cancelled (0ms)
fetchSeparateInit ... cancelled (0ms)
fetchInitTypedArrayBody ... cancelled (0ms)
fetchInitArrayBufferBody ... cancelled (0ms)
fetchInitURLSearchParamsBody ... cancelled (0ms)
fetchInitBlobBody ... cancelled (0ms)
fetchInitFormDataBody ... cancelled (0ms)
fetchInitFormDataBlobFilenameBody ... cancelled (0ms)
fetchInitFormDataTextFileBody ... cancelled (0ms)
fetchUserAgent ... cancelled (0ms)
fetchRequest ... cancelled (0ms)
fetchRequestAcceptHeaders ... cancelled (0ms)
fetchPostBodyString ... cancelled (0ms)
fetchPostBodyTypedArray ... cancelled (0ms)
fetchUserSetContentLength ... cancelled (0ms)
fetchUserSetTransferEncoding ... cancelled (0ms)
fetchWithNonAsciiRedirection ... cancelled (0ms)
fetchWithManualRedirection ... cancelled (0ms)
fetchWithErrorRedirection ... cancelled (0ms)
responseRedirect ... cancelled (0ms)
responseRedirectTakeURLObjectAsParameter ... cancelled (0ms)
responseWithoutBody ... cancelled (0ms)
fetchBodyReadTwice ... cancelled (0ms)
fetchBodyReaderAfterRead ... cancelled (0ms)
fetchBodyReaderWithCancelAndNewReader ... cancelled (0ms)
fetchBodyReaderWithReadCancelAndNewReader ... cancelled (0ms)
fetchResourceCloseAfterStreamCancel ... cancelled (0ms)
fetchNullBodyStatus ... cancelled (0ms)
fetchResponseContentLength ... cancelled (0ms)
fetchResponseConstructorNullBody ... cancelled (0ms)
fetchResponseConstructorInvalidStatus ... cancelled (0ms)
fetchResponseEmptyConstructor ... cancelled (0ms)
fetchCustomHttpClientParamCertificateSuccess ... cancelled (0ms)
fetchCustomClientUserAgent ... cancelled (0ms)
fetchPostBodyReadableStream ... cancelled (0ms)
fetchWritableRespProps ... cancelled (0ms)
fetchFilterOutCustomHostHeader ... cancelled (0ms)
fetchNoServerReadableStreamBody ... cancelled (0ms)
fetchHeadRespBody ... cancelled (0ms)
fetchClientCertWrongPrivateKey ... cancelled (0ms)
fetchClientCertBadPrivateKey ... cancelled (0ms)
fetchClientCertNotPrivateKey ... cancelled (0ms)
fetchCustomClientPrivateKey ... cancelled (0ms)
fetchAbortWhileUploadStreaming ... cancelled (0ms)
fetchAbortWhileUploadStreamingWithReason ... cancelled (0ms)
fetchAbortWhileUploadStreamingWithPrimitiveReason ... cancelled (0ms)
fetchHeaderValueShouldNotPanic ... cancelled (0ms)
fetchHeaderNameShouldNotPanic ... cancelled (0ms)
fetchSupportsHttp1Only ... cancelled (0ms)
fetchSupportsHttp2 ... cancelled (0ms)
fetchPrefersHttp2 ... cancelled (0ms)
fetchFilePerm ... cancelled (0ms)
fetchFilePermDoesNotExist ... cancelled (0ms)
fetchFileBadMethod ... cancelled (0ms)
fetchFileDoesNotExist ... cancelled (0ms)
fetchFile ... cancelled (0ms)
fetchContentLengthPost ... cancelled (0ms)
fetchContentLengthPut ... cancelled (0ms)
fetchContentLengthPatch ... cancelled (0ms)
fetchContentLengthPostWithStringBody ... cancelled (0ms)
fetchContentLengthPostWithBufferBody ... cancelled (0ms)
staticResponseJson ... cancelled (0ms)
fetchWithInvalidContentLengthAndTransferEncoding ... cancelled (0ms)
fetchWithInvalidContentLength ... cancelled (0ms)
fetchWithInvalidContentLength ... cancelled (0ms)
fetchWithInvalidContentLength ... cancelled (0ms)
fetchBlobUrl ... cancelled (0ms)
fetchResponseStreamIsLockedWhileReading ... cancelled (0ms)
fetchConstructorClones ... cancelled (0ms)
fetchRequestBodyErrorCatchable ... cancelled (0ms)

 ERRORS 

./cli/tests/unit/fetch_test.ts (uncaught error)
error: (in promise) TypeError: request body receiver not connected (request closed)
    at async deno:ext/fetch/26_fetch.js:251:42
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./cli/tests/unit/fetch_test.ts (uncaught error)

FAILED | 0 passed | 98 failed | 96 filtered out (100ms)

error: Test failed
```

### Expected

```
/m/a/P/g/d/deno ❯❯❯ cargo run test -A --unstable cli/tests/unit/fetch_test.ts --filter fetchInitFormDataMultipleFilesBody
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/deno test -A --unstable cli/tests/unit/fetch_test.ts --filter fetchInitFormDataMultipleFilesBody`
running 1 test from ./cli/tests/unit/fetch_test.ts
fetchInitFormDataMultipleFilesBody ...
Uncaught error from ./cli/tests/unit/fetch_test.ts FAILED

 ERRORS 

./cli/tests/unit/fetch_test.ts (uncaught error)
error: (in promise) TypeError: request body receiver not connected (request closed)
    at async deno:ext/fetch/26_fetch.js:251:42
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./cli/tests/unit/fetch_test.ts (uncaught error)

FAILED | 0 passed | 98 failed | 96 filtered out (100ms)

error: Test failed
```

**Comment by bartlomieju** [comment]
Can't repeat on Deno v1.32.4
