### ISSUE TITLE
thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)'

### ISSUE THREAD

**Issue by crucialfelix** [denoland/deno#17154]
Hello Denosaurs,

I'm sorry I made you panic. I scraped some website with a bad href on it.

I will certainly check the input before using it, but I guess fetch shouldn't have panicked.

```
❯ RUST_BACKTRACE=full deno
Deno 1.26.2
exit using ctrl+d, ctrl+c, or close()
> const url = new URL("http://{{google/")
undefined
> fetch(url)

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.26.2
Args: ["deno"]

thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /Users/ib/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.11/src/into_url.rs:70:14
stack backtrace:
   0:        0x103884d90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1543c132bc4e188c
   1:        0x102ff60f0 - core::fmt::write::hda8e8eb84b49cbfc
   2:        0x10385c034 - std::io::Write::write_fmt::hb84c8996aec7120c
   3:        0x10388964c - std::panicking::default_hook::{{closure}}::hdf06011cb093de6a
   4:        0x103889330 - std::panicking::default_hook::hd7ceb942fff7b170
   5:        0x102f2a340 - deno::setup_panic_hook::{{closure}}::h33d7245fd7f0feca
   6:        0x10388a0a4 - std::panicking::rust_panic_with_hook::h053d4067a63a6fcb
   7:        0x103889f3c - std::panicking::begin_panic_handler::{{closure}}::hea9e6c546a23e8ff
   8:        0x103889eb4 - std::sys_common::backtrace::__rust_end_short_backtrace::hd64e012cf32134c6
   9:        0x103889e80 - _rust_begin_unwind
  10:        0x102ff422c - core::panicking::panic_fmt::hbfde5533e1c0592e
  11:        0x102ffa51c - core::result::unwrap_failed::h68832e989a8867c1
  12:        0x1037e2ba0 - reqwest::into_url::expect_uri::h61350ed14de79f1e
  13:        0x1037e5190 - reqwest::async_impl::request::RequestBuilder::send::h40b57f53f6c95199
  14:        0x1034fc350 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd3bac049086045d7
  15:        0x1031a2f64 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::haa33cef5cbbf8229
  16:        0x1031a1448 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::hc6e2cc95d4f429c3
```

**Comment by bartlomieju** [comment]
This can be reproduced with `deno run` too:
```
const url = new URL("http://{{google/")
fetch(url);
```
```
deno run --allow-net test.js
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.29.1
Args: ["deno", "run", "foo.js"]

thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /Users/ib/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.11/src/into_url.rs:70:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
