### ISSUE TITLE
npm-compat: z3-solver

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#17171]
```ts
import { init } from "npm:z3-solver";
const { Context } = await init();
const { Solver, Int, And } = new Context("main");

const x = Int.const("x");

const solver = new Solver();
solver.add(And(x.ge(0), x.le(9)));
console.log(await solver.check()); // line that fails
```
error:
```
error: Uncaught RangeError: Maximum call stack size exceeded
    this._events = Object.create(null);
                          ^
    at Function.create (<anonymous>)
    at _Worker.EventEmitter.init (https://deno.land/std@0.170.0/node/_events.mjs:176:27)
    at new EventEmitter (https://deno.land/std@0.170.0/node/_events.mjs:56:21)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:49:5)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
```

Also there seem to be a lint issue ? 
![image](https://user-images.githubusercontent.com/22427111/209286241-15bbde5e-616e-4009-98c5-2adb99788877.png)

The node packagae [has z3-solver/browser](https://www.npmjs.com/package/z3-solver) recomends z3-solver/browser for browsers, but I don't know how to use this with deno becasue using
```ts
import { init } from "npm:z3-solver/browser";
```
errors
```
error: Unable to load /home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.11.2/browser imported from file:///home/mrcool/dev/deno/lab/qqq.ts

Caused by:
```

**Comment by sigmaSd** [comment]
One interesting thing though
```ts
import { init } from "npm:z3-solver";
const { Context } = await init();
```
Actually downloads the wasm file as part of the deno downloading dependencies part

So I didn't even need to give --allow-net, is this something I can do with my own deno modules ?

**Comment by sigmaSd** [comment]
now this causes a deno panic 

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.37.0+f0a022b
Args: ["deno", "run", "-A", "a.ts"]

thread 'main' panicked at 'Custom error class must have a builder registered: Uncaught Error: Unable to build custom error for "NotFound"
  Maximum call stack size exceeded', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.218.0/error.rs:132:7
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: deno_core::error::to_v8_error
   3: deno_node::ops::require::op_require_read_closest_package_json<P>::v8_fn_ptr
   4: Builtins_CallApiCallbackGeneric
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by scarf005** [comment]
sorry for the necropost, but this also causes infinite hanging.

```ts
import { init } from "npm:z3-solver"

const { Context } = await init()
const { Int, And, solve } = Context("main")

const x = Int.const("x")
console.log(await solve(And(x.ge(10), x.le(9))))
```

### System Info

deno 1.39.1+140e8be (canary, x86_64-unknown-linux-gnu)
v8 12.0.267.8
typescript 5.3.3

**Comment by sullrich84** [comment]
Advent of quality control :)

**Comment by rich-dtk** [comment]
I ran into a similar bug when trying to use the Optimize solver in deno.  I was also able to reproduce the bug in https://github.com/denoland/deno/issues/17171#issuecomment-1868450461
I then tried variations (replacing solver call with equivalent create Solver and add assertions. I tried three cases as shown below:
```
import { init } from "npm:z3-solver";
const z3 = await init();

enum ExperimentEnum {
  A,
  B,
  C,
}
const expirement = ExperimentEnum.A; // ExperimentEnum.A, ExperimentEnum.B, ExperimentEnum.C
const ctx = z3.Context("main");
const x = ctx.Int.const("x");
const s = ctx.Sort.declare("S");
const bs = ctx.Bool.sort();
const edge = ctx.Function.declare("edge", s, s, bs);

const a = ctx.Const("a", s);
const b = ctx.Const("b", s);
const c = ctx.Const("c", s);

async function main(expirement: ExperimentEnum) {
  const solver = new ctx.Solver();
  const assertions = [];
  if (expirement === ExperimentEnum.A) {
    assertions.push(ctx.And(x.ge(0), x.le(9)));
  } else if (expirement === ExperimentEnum.B) {
    assertions.push(ctx.And(x.ge(10), x.le(9)));
  } else if (expirement === ExperimentEnum.C) {
    assertions.push(ctx.And(x.ge(10), x.le(9)));
    solver.add(edge.call(a, b));
    solver.add(edge.call(b, c));
  }
  solver.add(...assertions);
  console.log(await solver.check());
}
await main(expirement);
```
Case A and C work fine returning sat, and unsat respectively. However, case B gives me the error:
```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.39.4
Args: ["/root/.asdf/installs/deno/1.39.4/bin/deno", "run", "--allow-all", "--unstable", "test1.ts"]

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.245.0/error.rs:132:7:
Custom error class must have a builder registered: Uncaught RangeError: Maximum call stack size exceeded
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: deno_core::error::to_v8_error::panic_cold_display
   3: deno_core::error::to_v8_error
   4: deno_node::ops::require::op_require_read_closest_package_json<P>::v8_fn_ptr
   5: Builtins_CallApiCallbackGeneric
```

**Comment by sigmaSd** [comment]
Obviously not the same, but in the meantime, its possible to use libpython for this, here is an example of the original snippet
```ts
import { python } from "https://deno.land/x/python@0.4.3/mod.ts";

const z3 = python.import("z3");
const x = z3.Int("x");
const solver = z3.Solver();
solver.add(z3.And(x.__ge__(0), x.__le__(9)));
console.log(solver.check());
console.log(solver.model());
```

**Comment by sigmaSd** [comment]
The error have changed in the last version
```
error: Uncaught (in worker "") (in promise) TypeError: Cannot set property location of #<DedicatedWorkerGlobalScope> which has only a getter
    at Function.assign (<anonymous>)
    at Object.<anonymous> (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.13.0/build/z3-built.worker.js:30:10)
    at Object.<anonymous> (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.13.0/build/z3-built.worker.js:208:4)
    at Module._compile (node:module:718:34)
    at Object.Module._extensions..js (node:module:732:10)
    at Module.load (node:module:643:32)
    at Function.Module._load (node:module:524:12)
    at Module.require (node:module:662:19)
    at require (node:module:776:16)
    at data:text/javascript,import { createRequi......3-built.worker.js");:1:176
```

deno 1.42.0+bca0fe1

**Comment by sigmaSd** [comment]
I just noticed that this issue is untagged, @satyarohith would be great if you tag this issue with npm-compat so it doesn't get lost

**Comment by sigmaSd** [comment]
current error
```
worker: onmessage() captured an uncaught exception: RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
error: Uncaught (in worker "em-pthread-1") RangeError: Maximum call stack size exceeded
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
    at postMessage (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js:466:40)
Pthread 0x01d1bf70 sent an error! undefined:undefined: Uncaught RangeError: Maximum call stack size exceeded
error: Uncaught (in promise) [Object: null prototype] {
  message: "Uncaught RangeError: Maximum call stack size exceeded",
  fileName: "file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.14.0/build/z3-built.js",
  lineNumber: 466,
  columnNumber: 40
}
```

**Comment by Macil** [comment]
I figured out what the issue is. It's in this part of `npm:z3-solver/build/z3-built.js` (which comes from [Emscripten when it's used with the `-pthread` flag for multithreading support](https://emscripten.org/docs/porting/pthreads.html)):


```js
if (ENVIRONMENT_IS_PTHREAD) {
  var wasmModuleReceived;

  // Node.js support
  if (ENVIRONMENT_IS_NODE) {
    // Create as web-worker-like an environment as we can.

    var parentPort = worker_threads['parentPort'];
    parentPort.on('message', (msg) => onmessage({ data: msg }));

    Object.assign(globalThis, {
      self: global,
      postMessage: (msg) => parentPort.postMessage(msg),
    });
  }
```

## Background

- In browsers, inside workers there are `self` (equivalent to `globalThis`) and `postMessage` globals. The worker can listen for messages from the parent by setting a message handler with `self.onmessage = function() { ... };` and can send messages to the parent by calling the global `postMessage` function. Emscripten's JS uses these inside the worker.
- In Node.js, inside workers there are no `self` or `postMessage` globals or support for receiving messages through an `onmessage` function attached to the global. Emscripten creates its own functional versions of these globals using Node's `worker_threads` module inside the worker so the rest of its code can pretend it's running inside a browser's web worker.
- In Deno (and Bun, which works the same as Deno in all of this here), the `postMessage` global exists, and you can listen for messages from the parent either through setting `globalThis.onMessage = function() { ... };` or by using the `node:worker_threads` module.

## What goes wrong

1. Deno's implementation of worker_thread's parentPort's `postMessage` [calls the port's original `postMessage` method](https://github.com/denoland/deno/blob/ee7c483df4bdc271edd0264c66246cc3297c6351/ext/node/polyfills/worker_threads.ts#L617-L632), which this code has just overridden to call worker_thread's parentPort's `postMessage`, so you get an infinite recursive loop which causes the "RangeError: Maximum call stack size exceeded" error.
2. In Deno, this code subscribes to messages from the parent twice (once by setting `self.onmessage` and twice by using     `parentPort.on('message', ...)`, both pointing to the same handler function) and will handle them all twice, causing other fatal errors if you get past the above issue.

## Possible solutions

This issue could be solved in Emscripten and/or Deno. Personally I suspect it makes the most sense to just fix this in Emscripten, but depending on the amount of pre-existing Emscripten code using this pattern and the importance of supporting it, then it could make sense to work around it in Deno too.

### In Emscripten

If the code was changed to the following, then it works fine in Node and Deno by feature-detecting native `postMessage` support and only patching it in if necessary, which also has the benefit of being compatible with any possible future versions of Node that could decide to more directly mimic the browser worker APIs like Deno:

```js
if (ENVIRONMENT_IS_PTHREAD) {
  var wasmModuleReceived;

  // Node.js support
  if (ENVIRONMENT_IS_NODE) {
    // Create as web-worker-like an environment as we can.
    Object.assign(globalThis, { self: global });

    // Deno already implements the following behavior so we must not doubly implement it
    if (!globalThis.postMessage) {
      var parentPort = worker_threads['parentPort'];
      parentPort.on('message', (msg) => onmessage({ data: msg }));

      Object.assign(globalThis, {
        postMessage: (msg) => parentPort.postMessage(msg),
      });
    }
  }
```

### In Deno

Problem 1 could be worked around if Deno's implementation of `node:worker_threads` did not rely on the port's public `postMessage` method and instead directly triggered whatever native code that a port's original `postMessage` method uses.

Problem 2 could be worked around if Deno was made to stop delivering messages to a worker's `globalThis.onmessage` function if `parentPort.on('message', ...)` is called in the worker.

These two workarounds would continue to work even if Emscripten later updated to use the above code.

**Comment by Macil** [comment]
I submitted a PR to Emscripten to fix this, and in the meantime for running Z3 on Deno specifically, I made a [JSR package](https://jsr.io/@macil/z3-solver) with my patch included.

**Comment by sigmaSd** [comment]
Thanks for your work @Macil
