### ISSUE TITLE
ts-node doesn't work in Deno

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#17176]
```
deno run -A npm:ts-node
error: Uncaught Error: Empty filepath.
    at pathDirname (deno:ext/node/02_require.js:50:13)
    at new Module (deno:ext/node/02_require.js:255:17)
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:553:30)
    at Function.resolve (deno:ext/node/02_require.js:811:21)
    at projectLocalResolveHelper (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/util.js:117:24)
    at resolveCompiler (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/configuration.js:232:22)
    at resolveAndLoadCompiler (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/configuration.js:225:26)
    at findAndReadConfig (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/configuration.js:48:28)
    at phase3 (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/bin.js:253:67)
    at bootstrap (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/bin.js:46:30)

```

Related to https://github.com/denoland/deno/issues/17175

**Comment by bartlomieju** [comment]
Even if we fix #17175 there are two different errors depending if we run with `--node-modules-dir` or not:
```
./deno/target/debug/deno run -A npm:ts-node
error: Uncaught Error: Cannot find module 'typescript'
Require stack:
- /Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/util.js
- /Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/bin.js
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:637:17)
    at Function.resolve (deno:ext/node/02_require.js:824:21)
    at projectLocalResolveHelper (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/util.js:117:24)
    at resolveCompiler (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/configuration.js:232:22)
    at resolveAndLoadCompiler (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/configuration.js:225:26)
    at findAndReadConfig (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/configuration.js:48:28)
    at phase3 (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/bin.js:253:67)
    at bootstrap (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/bin.js:46:30)
    at main (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/bin.js:32:12)
    at Object.<anonymous> (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/ts-node/10.9.1/dist/bin.js:578:5)

```

```
error: Uncaught TypeError: module_1.Module._preloadModules is not a function
    at <anonymous> (file:///Users/ib/dev/vite_deno_resolve/node_modules/.deno/ts-node@10.9.1/node_modules/ts-node/dist/index.js:136:21)

```

**Comment by marvinhagemeister** [comment]
The current error with Deno 1.45.2 is:

```sh
error: Uncaught Error: Not implemented: repl.start
    at <anonymous> (ext:deno_node/_utils.ts:9:9)
```

**Comment by scarf005** [comment]
The current error with Deno 2.1.9 is:

```
$ deno run -A npm:ts-node
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'fileExists')
    at readConfig (file:///run/media/home/scarf/repo/typescript-runtime-type-benchmarks/node_modules/.deno/ts-node@10.9.2/node_modules/ts-node/dist/configuration.js:91:33)
    at findAndReadConfig (file:///run/media/home/scarf/repo/typescript-runtime-type-benchmarks/node_modules/.deno/ts-node@10.9.2/node_modules/ts-node/dist/configuration.js:50:84)
    at phase3 (file:///run/media/home/scarf/repo/typescript-runtime-type-benchmarks/node_modules/.deno/ts-node@10.9.2/node_modules/ts-node/dist/bin.js:253:67)
    at bootstrap (file:///run/media/home/scarf/repo/typescript-runtime-type-benchmarks/node_modules/.deno/ts-node@10.9.2/node_modules/ts-node/dist/bin.js:46:30)
    at main (file:///run/media/home/scarf/repo/typescript-runtime-type-benchmarks/node_modules/.deno/ts-node@10.9.2/node_modules/ts-node/dist/bin.js:32:12)
    at Object.<anonymous> (file:///run/media/home/scarf/repo/typescript-runtime-type-benchmarks/node_modules/.deno/ts-node@10.9.2/node_modules/ts-node/dist/bin.js:578:5)
    at Object.<anonymous> (file:///run/media/home/scarf/repo/typescript-runtime-type-benchmarks/node_modules/.deno/ts-node@10.9.2/node_modules/ts-node/dist/bin.js:581:4)
    at Module._compile (node:module:743:34)
    at loadMaybeCjs (node:module:768:10)
    at Object.Module._extensions..js (node:module:753:12)
```

**Comment by bartlomieju** [comment]
Unable to reproduce on Deno 2.7.4 canary.

The original `Empty filepath` error in `Module._resolveFilename` no longer occurs. ts-node now bootstraps correctly — it resolves the TypeScript compiler, starts the REPL, and can compile files:

```
$ deno run -A npm:ts-node /tmp/test.ts
# ts-node runs, compiles the file, and executes it (fails only on missing tsconfig lib settings, not a Deno issue)

$ deno run -A npm:ts-node
# REPL starts (fails on ESM in vm.Script, separate issue)
```

Closing as fixed. Please reopen if you can still reproduce on a recent Deno version.
