### ISSUE TITLE
Get panic trying to run code, can reproduce

### ISSUE THREAD

**Issue by nikitavoloboev** [denoland/deno#17196]
On [this repo](https://github.com/nikitavoloboev/ts/tree/857257ee8b3182662bef08c64ccf7de8f90b2dad).

I followed instructions for setting up https://www.edgedb.com/docs/clients/js/querybuilder

When I try run: `deno run --watch -q -A --unstable main.ts`

I get panic:

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.29.1
Args: ["/opt/homebrew/bin/deno", "run", "--watch", "-q", "-A", "--unstable", "main.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /private/tmp/deno-20221216-7813-mihsf/deno/serde_v8/de.rs:573:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am not sure why and how to solve it. These were official instructions on EdgeDB documentation.

**Comment by nikitavoloboev** [comment]
Running with `RUST_BACKTRACE=1` on:

```
Task watch deno run --watch -q -A --unstable main.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.29.1
Args: ["/opt/homebrew/bin/deno", "run", "--watch", "-q", "-A", "--unstable", "main.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /private/tmp/deno-20221216-7813-mihsf/deno/serde_v8/de.rs:573:47
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: serde_v8::de::from_v8
   4: deno_core::error::JsError::inner_from_v8_exception
   5: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bartlomieju** [comment]
@nikitavoloboev could you provide contents of `main.ts`?

**Comment by nikitavoloboev** [comment]
```
import * as edgedb from "https://deno.land/x/edgedb/mod.ts"
import e from "./dbschema/edgeql-js/index.ts"

const client = edgedb.createClient()
// const query = `select "Hello world!";`

const query = e.select(e.Movie, () => ({
  id: true,
  title: true,
  actors: { name: true },
}))

const result = await client.query(query)
console.log(result)
```

**Comment by nikitavoloboev** [comment]
Ok it's issue on my side.
