### ISSUE TITLE
intermittent linking failure on OSX

### ISSUE THREAD

**Issue by ry** [denoland/deno#1719]
Somehow I get this link failure - but if i re-run build.py it goes away
```
Error 1 ~/src/deno> ./tools/build.py
ninja: Entering directory `/Users/rld/src/deno/target/debug'
[5/7] LINK ./deno
FAILED: deno
TOOL_VERSION=1546319521 ../../build/toolchain/mac/linker_driver.py ../../third_party/llvm-build/Release+Asserts/bin/clang++  -L /Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib empty_crate.4j5rjes6ztanke8o.rcgu.o -L /Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib /Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-edeacefc1391b975.rlib /Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-661c88e34f871df0.rlib /Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-f7c06680fdd716f3.rlib /Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-f2e753da53df829c.rlib /Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-961b28aeeb5bc8e1.rlib /Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-b6f6b59b6a29ec3a.rlib /Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-f31526d6d86acb04.rlib -stdlib=libc++ -arch x86_64 -segprot PROTECTED_MEMORY rw r -Werror -nostdlib++ -isysroot ../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10.0 -Wl,-ObjC -Lrust_crates -o "./deno" -Wl,-filelist,"./deno.rsp"  rust_crates/libansi_term.rlib rust_crates/libatty.rlib rust_crates/libdirs.rlib rust_crates/libflatbuffers.rlib rust_crates/libfutures.rlib rust_crates/libgetopts.rlib rust_crates/libhttp.rlib rust_crates/libhyper.rlib rust_crates/libhyper_rustls.rlib rust_crates/liblazy_static.rlib rust_crates/liblibc.rlib rust_crates/liblog.rlib rust_crates/librand.rlib rust_crates/libregex.rlib rust_crates/libremove_dir_all.rlib rust_crates/libring.rlib rust_crates/librustyline.rlib rust_crates/libserde_json.rlib rust_crates/libsource_map_mappings.rlib rust_crates/libtempfile.rlib rust_crates/libtokio.rlib rust_crates/libtokio_executor.rlib rust_crates/libtokio_fs.rlib rust_crates/libtokio_io.rlib rust_crates/libtokio_process.rlib rust_crates/libtokio_threadpool.rlib rust_crates/liburl.rlib rust_crates/libsmallvec.rlib rust_crates/libunreachable.rlib rust_crates/libvoid.rlib rust_crates/libunicode_width.rlib rust_crates/libbytes.rlib rust_crates/libfnv.rlib rust_crates/libitoa.rlib rust_crates/libbyteorder.rlib rust_crates/libiovec.rlib rust_crates/libfutures_cpupool.rlib rust_crates/libh2.rlib rust_crates/libhttparse.rlib rust_crates/libnet2.rlib rust_crates/libtime.rlib rust_crates/libtokio_reactor.rlib rust_crates/libtokio_tcp.rlib rust_crates/libtokio_timer.rlib rust_crates/libwant.rlib rust_crates/libnum_cpus.rlib rust_crates/libindexmap.rlib rust_crates/libslab.rlib rust_crates/libstring.rlib rust_crates/libcfg_if.rlib rust_crates/libmio.rlib rust_crates/libtokio_codec.rlib rust_crates/libtokio_current_thread.rlib rust_crates/libtokio_sync.rlib rust_crates/libtokio_udp.rlib rust_crates/libtokio_uds.rlib rust_crates/liblazycell.rlib rust_crates/libcrossbeam_utils.rlib rust_crates/libcrossbeam.rlib rust_crates/libcrossbeam_channel.rlib rust_crates/libcrossbeam_deque.rlib rust_crates/libcrossbeam_epoch.rlib rust_crates/libparking_lot.rlib rust_crates/liblock_api.rlib rust_crates/libparking_lot_core.rlib rust_crates/libscopeguard.rlib rust_crates/librand_chacha.rlib rust_crates/librand_hc.rlib rust_crates/librand_isaac.rlib rust_crates/librand_os.rlib rust_crates/librand_pcg.rlib rust_crates/librand_xorshift.rlib rust_crates/librand_core.rlib -framework Security rust_crates/libarrayvec.rlib rust_crates/libmemoffset.rlib rust_crates/libnodrop.rlib rust_crates/libmio_uds.rlib rust_crates/libtry_lock.rlib rust_crates/libct_logs.rlib rust_crates/librustls.rlib rust_crates/libtokio_rustls.rlib rust_crates/libwebpki.rlib rust_crates/libwebpki_roots.rlib rust_crates/libsct.rlib rust_crates/libuntrusted.rlib rust_crates/libbase64.rlib rust_crates/libaho_corasick.rlib rust_crates/libmemchr.rlib rust_crates/libregex_syntax.rlib rust_crates/libthread_local.rlib rust_crates/libutf8_ranges.rlib rust_crates/libucd_util.rlib rust_crates/libunicode_segmentation.rlib rust_crates/libnix.rlib rust_crates/libutf8parse.rlib rust_crates/libbitflags.rlib rust_crates/libryu.rlib rust_crates/libserde.rlib rust_crates/libvlq.rlib rust_crates/libtokio_signal.rlib rust_crates/libsignal_hook.rlib rust_crates/libarc_swap.rlib rust_crates/libidna.rlib rust_crates/libmatches.rlib rust_crates/libpercent_encoding.rlib rust_crates/libunicode_bidi.rlib rust_crates/libunicode_normalization.rlib rust_crates/deno_bin-9bac5ee0.o
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/mac/linker_driver.py", line 229, in <module>
    Main(sys.argv)
  File "../../build/toolchain/mac/linker_driver.py", line 79, in Main
    subprocess.check_call(compiler_driver_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../third_party/llvm-build/Release+Asserts/bin/clang++', '-L', '/Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib', 'empty_crate.4j5rjes6ztanke8o.rcgu.o', '-L', '/Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib', '/Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-edeacefc1391b975.rlib', '/Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-661c88e34f871df0.rlib', '/Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-f7c06680fdd716f3.rlib', '/Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-f2e753da53df829c.rlib', '/Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-961b28aeeb5bc8e1.rlib', '/Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-b6f6b59b6a29ec3a.rlib', '/Users/rld/.rustup/toolchains/1.32.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-f31526d6d86acb04.rlib', '-stdlib=libc++', '-arch', 'x86_64', '-segprot', 'PROTECTED_MEMORY', 'rw', 'r', '-Werror', '-nostdlib++', '-isysroot', '../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk', '-mmacosx-version-min=10.10.0', '-Wl,-ObjC', '-Lrust_crates', '-o', './deno', '-Wl,-filelist,./deno.rsp', 'rust_crates/libansi_term.rlib', 'rust_crates/libatty.rlib', 'rust_crates/libdirs.rlib', 'rust_crates/libflatbuffers.rlib', 'rust_crates/libfutures.rlib', 'rust_crates/libgetopts.rlib', 'rust_crates/libhttp.rlib', 'rust_crates/libhyper.rlib', 'rust_crates/libhyper_rustls.rlib', 'rust_crates/liblazy_static.rlib', 'rust_crates/liblibc.rlib', 'rust_crates/liblog.rlib', 'rust_crates/librand.rlib', 'rust_crates/libregex.rlib', 'rust_crates/libremove_dir_all.rlib', 'rust_crates/libring.rlib', 'rust_crates/librustyline.rlib', 'rust_crates/libserde_json.rlib', 'rust_crates/libsource_map_mappings.rlib', 'rust_crates/libtempfile.rlib', 'rust_crates/libtokio.rlib', 'rust_crates/libtokio_executor.rlib', 'rust_crates/libtokio_fs.rlib', 'rust_crates/libtokio_io.rlib', 'rust_crates/libtokio_process.rlib', 'rust_crates/libtokio_threadpool.rlib', 'rust_crates/liburl.rlib', 'rust_crates/libsmallvec.rlib', 'rust_crates/libunreachable.rlib', 'rust_crates/libvoid.rlib', 'rust_crates/libunicode_width.rlib', 'rust_crates/libbytes.rlib', 'rust_crates/libfnv.rlib', 'rust_crates/libitoa.rlib', 'rust_crates/libbyteorder.rlib', 'rust_crates/libiovec.rlib', 'rust_crates/libfutures_cpupool.rlib', 'rust_crates/libh2.rlib', 'rust_crates/libhttparse.rlib', 'rust_crates/libnet2.rlib', 'rust_crates/libtime.rlib', 'rust_crates/libtokio_reactor.rlib', 'rust_crates/libtokio_tcp.rlib', 'rust_crates/libtokio_timer.rlib', 'rust_crates/libwant.rlib', 'rust_crates/libnum_cpus.rlib', 'rust_crates/libindexmap.rlib', 'rust_crates/libslab.rlib', 'rust_crates/libstring.rlib', 'rust_crates/libcfg_if.rlib', 'rust_crates/libmio.rlib', 'rust_crates/libtokio_codec.rlib', 'rust_crates/libtokio_current_thread.rlib', 'rust_crates/libtokio_sync.rlib', 'rust_crates/libtokio_udp.rlib', 'rust_crates/libtokio_uds.rlib', 'rust_crates/liblazycell.rlib', 'rust_crates/libcrossbeam_utils.rlib', 'rust_crates/libcrossbeam.rlib', 'rust_crates/libcrossbeam_channel.rlib', 'rust_crates/libcrossbeam_deque.rlib', 'rust_crates/libcrossbeam_epoch.rlib', 'rust_crates/libparking_lot.rlib', 'rust_crates/liblock_api.rlib', 'rust_crates/libparking_lot_core.rlib', 'rust_crates/libscopeguard.rlib', 'rust_crates/librand_chacha.rlib', 'rust_crates/librand_hc.rlib', 'rust_crates/librand_isaac.rlib', 'rust_crates/librand_os.rlib', 'rust_crates/librand_pcg.rlib', 'rust_crates/librand_xorshift.rlib', 'rust_crates/librand_core.rlib', '-framework', 'Security', 'rust_crates/libarrayvec.rlib', 'rust_crates/libmemoffset.rlib', 'rust_crates/libnodrop.rlib', 'rust_crates/libmio_uds.rlib', 'rust_crates/libtry_lock.rlib', 'rust_crates/libct_logs.rlib', 'rust_crates/librustls.rlib', 'rust_crates/libtokio_rustls.rlib', 'rust_crates/libwebpki.rlib', 'rust_crates/libwebpki_roots.rlib', 'rust_crates/libsct.rlib', 'rust_crates/libuntrusted.rlib', 'rust_crates/libbase64.rlib', 'rust_crates/libaho_corasick.rlib', 'rust_crates/libmemchr.rlib', 'rust_crates/libregex_syntax.rlib', 'rust_crates/libthread_local.rlib', 'rust_crates/libutf8_ranges.rlib', 'rust_crates/libucd_util.rlib', 'rust_crates/libunicode_segmentation.rlib', 'rust_crates/libnix.rlib', 'rust_crates/libutf8parse.rlib', 'rust_crates/libbitflags.rlib', 'rust_crates/libryu.rlib', 'rust_crates/libserde.rlib', 'rust_crates/libvlq.rlib', 'rust_crates/libtokio_signal.rlib', 'rust_crates/libsignal_hook.rlib', 'rust_crates/libarc_swap.rlib', 'rust_crates/libidna.rlib', 'rust_crates/libmatches.rlib', 'rust_crates/libpercent_encoding.rlib', 'rust_crates/libunicode_bidi.rlib', 'rust_crates/libunicode_normalization.rlib', 'rust_crates/deno_bin-9bac5ee0.o']' returned non-zero exit status 254
[6/7] LINK ./test_rs
ninja: build stopped: subcommand failed.
Error 1 ~/src/deno
```

**Comment by ry** [comment]
stale
