### ISSUE TITLE
NPM compatibility - Crypto module cannot be resolved

### ISSUE THREAD

**Issue by Mic-R** [denoland/deno#17257]
On usage of the NPM Module [@azure/storage-blob](https://www.npmjs.com/package/@azure/storage-blob) in the following context:

```
import * as AzureStorageBlob from "npm:@azure/storage-blob"

const BlobClient = AzureStorageBlob.BlobServiceClient.fromConnectionString(configs.azureconnectionstring);
const containerClient = BlobClient.getContainerClient(configs.azure_container);

//fetch image
//...


let uuid = crypto.randomUUID();
const response = await fetch(image.url);
await containerClient.getBlockBlobClient(`${user.id}/${uuid}${image.url.substring(image.url.lastIndexOf("."))}`).upload(response.body, response.body.length);
```

the following error is thrown:

```
error: Uncaught (in promise) Error: Cannot find module 'crypto'
Require stack:
- C:\Users\micha\AppData\Local\deno\npm\registry.npmjs.org\uuid\8.3.2\dist\rng.js
- C:\Users\micha\AppData\Local\deno\npm\registry.npmjs.org\uuid\8.3.2\dist\v1.js
- C:\Users\micha\AppData\Local\deno\npm\registry.npmjs.org\uuid\8.3.2\./dist/index.js
- C:\Users\micha\AppData\Local\deno\npm\registry.npmjs.org\@azure\core-http\2.3.1\dist\index.js
- C:\Users\micha\AppData\Local\deno\npm\registry.npmjs.org\@azure\storage-blob\12.12.0\dist\index.js
- C:\Users\micha\AppData\Local\deno\npm\registry.npmjs.org\@azure\storage-blob\12.12.0\dist\index.js
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:624:17)
    at Function.Module._load (deno:ext/node/02_require.js:456:29)
    at Module.require (deno:ext/node/02_require.js:667:21)
    at require (deno:ext/node/02_require.js:807:18)
    at Object.<anonymous> (file:///C:/Users/micha/AppData/Local/deno/npm/registry.npmjs.org/uuid/8.3.2/dist/rng.js:8:38)
    at Object.<anonymous> (file:///C:/Users/micha/AppData/Local/deno/npm/registry.npmjs.org/uuid/8.3.2/dist/rng.js:25:4)
    at Module._compile (deno:ext/node/02_require.js:734:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:767:12)
    at Module.load (deno:ext/node/02_require.js:645:34)
    at Function.Module._load (deno:ext/node/02_require.js:502:14)
```

but following the Deno Documentation, this shouldn't be an issue, it seems to be a Deno Bug.

Deno Version:

```
deno 1.29.1 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by GJZwiers** [comment]
As discussed on Discord I will try to debug this sometime soon.

**Comment by GJZwiers** [comment]
@Mic-R I am not able to reproduce your error so far. This is what I've tried:

- Made an Azure storage account `denostorageaccount`
- Got the connection string by going to the the Storage Account -> Access Keys -> key1 -> Connection string
- Made a container `testcontainer` by going to the Storage Account -> Containers
- Create `main.ts` with the following code :

```js
import * as AzureStorageBlob from "npm:@azure/storage-blob";

const BlobClient = AzureStorageBlob.BlobServiceClient.fromConnectionString(
  "<my_connection_string>",
);
const containerClient = BlobClient.getContainerClient("testcontainer");
console.log(containerClient);

const uuid = crypto.randomUUID();

await containerClient
  .getBlockBlobClient(uuid)
  .upload("hello", "hello".length);

```

This runs fine with `deno run --allow-env --allow-read --allow-sys main.ts` and uploads a blob to Azure, but I don't have your entire code example. Maybe the problem is with uploading `response.body` instead of a simple string? Could you share the rest of your code?

**Comment by bartlomieju** [comment]
Also output of `deno --version` would be useful

**Comment by Mic-R** [comment]
@bartlomieju I updatet my original post

**Comment by GJZwiers** [comment]
@Mic-R Could you add how you get the `image` variable?

**Comment by Mic-R** [comment]
> This runs fine with `deno run --allow-env --allow-read --allow-sys main.ts` and uploads a blob to Azure, but I don't have your entire code example. Maybe the problem is with uploading `response.body` instead of a simple string? Could you share the rest of your code?

Hey there @GJZwiers,
I may not share more of my code, but as far as I see this, the only thing I have not yet declared is image.url. As the variable name suggests it references to an url that returns an image. To simplify our case here, let's say the image var is static (it's actually being retrieved from an event handler, but let's ignore that, I could independently verify that this isn't the issue).

Following [this](https://learn.microsoft.com/en-us/javascript/api/@azure/storage-blob/blockblobclient?view=azure-node-latest#@azure-storage-blob-blockblobclient-uploadbrowserdata) piece of doc, I should be able to upload an arraybuffer

**Comment by GJZwiers** [comment]
If I fetch a png image from a URL it will return `response.body` as a `ReadableStream` type, which in TypeScript is not an accepted type for the `upload` call. But I can upload the response as an ArrayBuffer which also uploads to Azure storage.

```ts
const response = await fetch(new URL("https://commons.wikimedia.org/wiki/File:Example.png"));

const buffer = await response.arrayBuffer();
await containerClient
  .getBlockBlobClient(uuid)
  .upload(buffer, buffer.byteLength);
```

Without a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) that shows how to generate the error I'm afraid this is going to be difficult to debug further.

**Comment by Mic-R** [comment]
@GJZwiers I have given you my example, I don't have anything else I could use to prove my point

**Comment by bartlomieju** [comment]
> @GJZwiers I have given you my example, I don't have anything else I could use to prove my point

Do you have any environmental variables set? In Deno there's `DENO_NODE_COMPAT_URL` that might cause a different version of compat layer to be loaded.

**Comment by Mic-R** [comment]
I do not have that env var set

**Comment by Mic-R** [comment]
Ok, so I finally got the OK to publish this fully: https://github.com/BTE-Germany/EventBot/tree/Azure

This is the Codebase, the concerned file is: https://github.com/BTE-Germany/EventBot/blob/Azure/src/events/messageCreate.ts

(Yes the code is messy, I will clean it up at some point)

**Comment by bartlomieju** [comment]
@GJZwiers could you try that repo?

**Comment by GJZwiers** [comment]
I have tried to minimize the code in that repo without the external stuff like the Prisma database, but I end up with more or less the code that I tried earlier, which unfortunately does not reproduce the error. It would seem the issue is not with `@azure/storage-blob`, but that is hard to say without a clearer reproduction.

**Comment by bartlomieju** [comment]
I'm gonna close this one as we don't have a reliable way to reproduce it. Also Deno's node compat got a lot better since this issue was opened and there's a good chance this works correctly now.
