### ISSUE TITLE
Http - invalid HTTP method parsed console spam

### ISSUE THREAD

**Issue by Lesiuk** [denoland/deno#17266]
My deno http server is visible from the internet, and I am getting lots of "invalid HTTP method parsed" in the console. Probably some kind of bots are trying to connect and are sending invalid http requests. Is there any way we can suppress those messages?

```
[uncaught application error]: Http - invalid HTTP method parsed

    at async HttpConn.nextRequest (deno:ext/http/01_http.js:92:23)
    at async serve (https://deno.land/x/oak@v11.1.0/http_server_native.ts:112:34)
```

When I am looking at oaks code, I can see those are thrown inside try catch block. 
https://github.com/oakserver/oak/blob/main/http_server_native.ts#L112
Why didn't try catch work for them?

**Comment by Lesiuk** [comment]
I've tried using
```javascript

I tried adding an error listener, as suggested, but the early eof still gets logged.
Is this correct:

app.addEventListener('error', (e) => {
    const lowerMsg = e.error?.message?.toLowerCase();

    if (lowerMsg?.includes('invalid HTTP method parsed')) { return }
    console.error(e.error);
})
```

But it still get's logged.
