### ISSUE TITLE
WebSocket crash

### ISSUE THREAD

**Issue by milaz** [denoland/deno#17283]
Error 'IO error: Broken pipe (os error 32)' contains boxed error of unknown type:
  Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
  Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
error: Uncaught (in promise) Error: IO error: Broken pipe (os error 32): Broken pipe (os error 32)
    at async deno:ext/websocket/01_websocket.js:514:13

This situation can happen, but maybe there is a better way to handle it than crashing the whole server.

**Comment by Lesiuk** [comment]
I had this issue multiple times. It's when there is a connected client and disconnects without properly closing the connection, and we are sending the message.

**Comment by milaz** [comment]
Yes, this is the correct diagnosis. When the client is not closing the connection properly, it can force the server to crash.
I think, there must be try .. except block around this call: https://github.com/denoland/deno/blob/82e930726ee5dbac8e6eae0962c07c72daf9843c/ext/websocket/01_websocket.js#L514

**Comment by huumn** [comment]
I'm experiencing this issue with:
```
deno 1.34.0 (release, aarch64-apple-darwin)
v8 11.5.150.1
typescript 5.0.4
```

I can't seem to produce a minimal reproduction but it only happens when I write to a websocket the client has closed and the server still thinks is open ... then the client opens a new connection. If I make the client wait for the close to succeed before the client opens a new connection it only happens *sometimes* which makes me think there's some kind of race condition.

```js
error: Uncaught (in promise) TypeError: Broken pipe (os error 32)
        ws.send(`["EVENT", "${subId}", ${e}]`)
           ^
    at WebSocket.send (ext:deno_websocket/01_websocket.js:368:9)
```

There might be an issue with my server's code given the lack of reproduction, but `readyState = 1` when this error occurs.

It makes sense that I can't write to a closed connection, but I can't
1. detect the close before writing (deno doesn't even seem aware of the close)
2. catch this error

So I'm not sure how to handle this.

**Comment by huumn** [comment]
I'm still failing to minimally reproduce. At this point I suspect it somehow involves the event loop and requires other async/event activity to reproduce.

Just in case anyone is interested in a more involved reproduction, I've push one to this branch: https://github.com/stackernews/booger/tree/deno-1.34.0-crash

If I run the server with `deno task dev` and then run `deno test -A test/nip-01.test.js` ... the first run succeeds (because the server doesn't write after the client closes). But on subsequent runs of `deno test -A test/nip-01.test.js`, the crash is triggered because the server will write after the client closes (given there's more state in the db).

After downgrading through all intermediate minor versions, I do not have this issue on
```
deno 1.32.1 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.2
```

**Comment by quentinadam** [comment]
I am again experiencing the issue, also in the latest version of Deno 1.39.2

**Comment by jflatow** [comment]
I also started experiencing this (again) with Deno 1.39.1 and Deno 1.40.3
