### ISSUE TITLE
run::flash_shutdown is flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17356]
https://github.com/denoland/deno/actions/runs/3896814455/jobs/6653795998

```
---- run::flash_shutdown stdout ----
deno_exe path /home/runner/work/deno/deno/target/release/deno
deno_exe args run --unstable --allow-net run/flash_shutdown/main.ts
deno_exe cwd "/home/runner/work/deno/deno/cli/tests/testdata"
OUTPUT

OUTPUT
thread 'run::flash_shutdown' panicked at 'process terminated by signal, expected exit code: 0, actual signal: 11', test_util/src/lib.rs:1988:9
stack backtrace:
   0:     0x55cd19f38820 - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55cd19f38820 - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cd19f38820 - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55cd19f38820 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55cd19f607ee - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0x55cd19f314a5 - std::io::Write::write_fmt::h83acae7663784f8d
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0x55cd19f385e5 - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55cd19f385e5 - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55cd19f3aadf - std::panicking::default_hook::***closure***::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0x55cd19f3a79e - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:283:9
  10:     0x55cd190a03e7 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4c8ba2ff1efc4933
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:2001:9
  11:     0x55cd190a03e7 - test::test_main::***closure***::h6f51e750f77a5665
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:135:21
  12:     0x55cd19f3b259 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h44df53ea2a13204b
error: test failed, to rerun pass `-p deno --test run_tests`
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:2001:9
  13:     0x55cd19f3b259 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:692:13
  14:     0x55cd19f3afd7 - std::panicking::begin_panic_handler::***closure***::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:579:13
  15:     0x55cd19f38ccc - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  16:     0x55cd19f3acf2 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  17:     0x55cd19f5e6a3 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  18:     0x55cd19fbcb81 - test_util::CheckOutputIntegrationTest::run::h57530b9d6683c11f
  19:     0x55cd19f7a3ef - core::ops::function::FnOnce::call_once::h838e5302380886c1
  20:     0x55cd190a956f - core::ops::function::FnOnce::call_once::h7ea560e562d0dae0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  21:     0x55cd190a956f - test::__rust_begin_short_backtrace::h73d1d8a49aac517f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:599:18
  22:     0x55cd19078e7c - test::run_test::***closure***::ha3a9210f4cabf9b9
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:590:30
  23:     0x55cd19078e7c - core::ops::function::FnOnce::call_once***vtable.shim***::hb314a42de38ef4d3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  24:     0x55cd190a85e8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdcd2b49f84ba5417
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  25:     0x55cd190a85e8 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::habf1097914f7b07a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panic/unwind_safe.rs:271:9
  26:     0x55cd190a85e8 - std::panicking::try::do_call::h1caa06a85929919a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  27:     0x55cd190a85e8 - std::panicking::try::h38c9bd776104366d
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  28:     0x55cd190a85e8 - std::panic::catch_unwind::hda661301fd29b4c3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  29:     0x55cd190a85e8 - test::run_test_in_process::h7d62dd6940863012
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:622:27
  30:     0x55cd190a85e8 - test::run_test::run_test_inner::***closure***::h3c52f4ad0f76ed0a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:516:39
  31:     0x55cd19073434 - test::run_test::run_test_inner::***closure***::h7be919206b54d94c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:543:37
  32:     0x55cd19073434 - std::sys_common::backtrace::__rust_begin_short_backtrace::h13193f7ccaefcf4a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:121:18
  33:     0x55cd19078bb5 - std::thread::Builder::spawn_unchecked_::***closure***::***closure***::hc84098ba72231f5c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/thread/mod.rs:551:17
  34:     0x55cd19078bb5 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h123188401ca189e5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panic/unwind_safe.rs:271:9
  35:     0x55cd19078bb5 - std::panicking::try::do_call::haa3d41b5f9f4eed7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  36:     0x55cd19078bb5 - std::panicking::try::he2c792842af193f0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  37:     0x55cd19078bb5 - std::panic::catch_unwind::hb9419113823bcafd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  38:     0x55cd19078bb5 - std::thread::Builder::spawn_unchecked_::***closure***::h79bea04e334b86a8
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/thread/mod.rs:550:30
  39:     0x55cd19078bb5 - core::ops::function::FnOnce::call_once***vtable.shim***::h79ff5c025ceea159
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  40:     0x55cd19f40443 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4273f95ec44459b3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  41:     0x55cd19f40443 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70f28fa4ddc269e5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  42:     0x55cd19f40443 - std::sys::unix::thread::Thread::new::thread_start::h85a9c16b988e2bd0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys/unix/thread.rs:108:17
  43:     0x7fde8f9aa609 - start_thread
  44:     0x7fde8f77e133 - clone
  45:                0x0 - <unknown>
```

**Comment by dsherret** [comment]
Slightly different error for the same test:

```
---- integration::run::flash_shutdown stdout ----
deno_exe path C:\a\deno\deno\target\release\deno.exe
deno_exe args run --unstable --allow-net run/flash_shutdown/main.ts
deno_exe cwd "C:\\a\\deno\\deno\\cli\\tests\\testdata"
OUTPUT
error: Uncaught (in promise) AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)

OUTPUT
thread 'integration::run::flash_shutdown' panicked at 'bad exit code, expected: 0, actual: 1', test_util\src\lib.rs:1977:9
stack backtrace:
   0:     0x7ff696bd15c1 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff696bd15c1 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff696bd15c1 - std::sys_common::backtrace::_print_fmt
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:65
   3:     0x7ff696bd15c1 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff696a3e89b - core::fmt::write
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\fmt\mod.rs:1209
   5:     0x7ff696bbe9ca - std::io::Write::write_fmt<alloc::vec::Vec<u8,alloc::alloc::Global> >
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\io\mod.rs:1682
   6:     0x7ff696bd601b - std::sys_common::backtrace::_print
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:47
   7:     0x7ff696bd601b - std::sys_common::backtrace::print
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff696bd5c01 - std::panicking::default_hook::closure$1
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:267
   9:     0x7ff696bd5793 - std::panicking::default_hook
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:283
  10:     0x7ff696bd6878 - alloc::boxed::impl$47::call
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\alloc\src\boxed.rs:2001
  11:     0x7ff696bd6878 - std::panicking::rust_panic_with_hook
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:692
  12:     0x7ff696bd65e5 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:579
  13:     0x7ff696bd652f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:137
  14:     0x7ff696bd6504 - std::panicking::begin_panic_handler
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
  15:     0x7ff697a7cd55 - core::panicking::panic_fmt
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
  16:     0x7ff696c2d36f - core::fmt::impl$0::write_fmt<std::io::Write::write_fmt::Adapter<enum2$<test::console::OutputLocation<std::io::stdio::StdoutLock> > > >
  17:     0x7ff696877d4b - __ImageBase
  18:     0x7ff696bf88df - core::ops::function::FnOnce::call_once
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\ops\function.rs:251
  19:     0x7ff696bf88df - test::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,alloc::string::String> >,enum2$<core::result::Result<tuple$<>,alloc::string::String> > (*)()>
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\test\src\lib.rs:599
  20:     0x7ff696bf88c0 - test::run_test::closure$1
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\test\src\lib.rs:590
  21:     0x7ff696bf88c0 - core::ops::function::FnOnce::call_once<test::run_test::closure_env$1,tuple$<> >
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\ops\function.rs:251
  22:     0x7ff696bf9091 - alloc::boxed::impl$45::call_once
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\alloc\src\boxed.rs:1987
  23:     0x7ff696bf9091 - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panic\unwind_safe.rs:271
  24:     0x7ff696bf9091 - std::panicking::try::do_call
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:483
  25:     0x7ff696bf9091 - std::panicking::try
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:447
  26:     0x7ff696bf9091 - std::panic::catch_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panic.rs:137
  27:     0x7ff696bf9091 - test::run_test_in_process
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\test\src\lib.rs:622
  28:     0x7ff696bf9091 - test::run_test::run_test_inner::closure$0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\test\src\lib.rs:516
  29:     0x7ff696bfae91 - test::run_test::run_test_inner::closure$1
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\test\src\lib.rs:543
  30:     0x7ff696bfae91 - std::sys_common::backtrace::__rust_begin_short_backtrace<test::run_test::run_test_inner::closure_env$1,tuple$<> >
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:121
  31:     0x7ff696bfab8a - std::thread::impl$0::spawn_unchecked_::closure$1::closure$0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\thread\mod.rs:551
  32:     0x7ff696bfab8a - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panic\unwind_safe.rs:271
  33:     0x7ff696bfab8a - std::panicking::try::do_call
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:483
  34:     0x7ff696bfab8a - std::panicking::try
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:447
  35:     0x7ff696bfab8a - std::panic::catch_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panic.rs:137
  36:     0x7ff696bfab8a - std::thread::impl$0::spawn_unchecked_::closure$1
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\thread\mod.rs:550
  37:     0x7ff696bfab8a - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<test::run_test::run_test_inner::closure_env$1,tuple$<> >,tuple$<> >
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\ops\function.rs:251
  38:     0x7ff696bcc89b - alloc::boxed::impl$45::call_once
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\alloc\src\boxed.rs:1987
  39:     0x7ff696bcc89b - alloc::boxed::impl$45::call_once
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\alloc\src\boxed.rs:1987
  40:     0x7ff696bcc89b - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys\windows\thread.rs:56
  41:     0x7ffa0ef74ed0 - BaseThreadInitThunk
  42:     0x7ffa1109e40b - RtlUserThreadStart


failures:
    integration::run::flash_shutdown
```

https://github.com/denoland/deno/actions/runs/3911043100/jobs/6684903982
