### ISSUE TITLE
watcher::lint_watch_test is flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17360]
https://github.com/denoland/deno/actions/runs/3897639058/jobs/6655515542

```
failures:

---- watcher::lint_watch_test stdout ----
STDERR: Watcher Lint started.
STDERR: (no-unused-vars) `a` is never used
STDERR: let a = 5;
STDERR:     ^
STDERR:     at /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/deno-cli-test-1673481772707-13/badly_linted.js:1:5
STDERR: 
STDERR:     hint: If this is intentional, prefix it with an underscore like `_a`
STDERR:     help: for further information visit https://lint.deno.land/#no-unused-vars
STDERR: 
STDERR: (prefer-const) `a` is never reassigned
STDERR: let a = 5;
STDERR:     ^
STDERR:     at /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/deno-cli-test-1673481772707-13/badly_linted.js:1:5
STDERR: 
STDERR:     hint: Use `const` instead
STDERR:     help: for further information visit https://lint.deno.land/#prefer-const
STDERR: 
STDERR: Found 2 problems
STDERR: Checked 1 file
STDERR: Watcher Lint finished. Restarting on file change...
STDERR: Watcher File change detected! Restarting!
STDERR: Checked 1 file
STDERR: Watcher Lint finished. Restarting on file change...
thread 'watcher::lint_watch_test' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"(prefer-const) `_a` is never reassigned\n"`', cli/tests/watcher_tests.rs:135:5
stack backtrace:
   0:        0x1087f4022 - std::backtrace_rs::backtrace::libunwind::trace::h74d17ea919046bae
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1087f4022 - std::backtrace_rs::backtrace::trace_unsynchronized::h2fc77fd5a14165ac
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1087f4022 - std::sys_common::backtrace::_print_fmt::h2687aa7717781133
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x1087f4022 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdc69a6f447628e71
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x108811e7a - core::fmt::write::hb9e764fa47ae8444
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:        0x1087f048c - std::io::Write::write_fmt::h55cbab6d9bd3b1cc
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:        0x1087f3dea - std::sys_common::backtrace::_print::h882e8250b822b8b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x1087f3dea - std::sys_common::backtrace::print::h488fe4c0b1fb9d50
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x1087f6016 - std::panicking::default_hook::***closure***::h5618ea3156b8b833
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:        0x1087f5cf6 - std::panicking::default_hook::h0421c26a8a92801c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:283:9
  10:        0x108616349 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h30410c450cfcec6d
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:2001:9
  11:        0x108616349 - test::test_main::***closure***::h97f5cfefb46a837f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:135:21
  12:        0x1087f6781 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h43102c9332c70021
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:2001:9
  13:        0x1087f6781 - std::panicking::rust_panic_with_hook::h57383cd32463c250
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:692:13
  14:        0x1087f6513 - std::panicking::begin_panic_handler::***closure***::h1d1f7305cfe67fdd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:579:13
  15:        0x1087f44b8 - std::sys_common::backtrace::__rust_end_short_backtrace::hd8e12e82ff026bae
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  16:        0x1087f61dd - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  17:        0x108821f03 - core::panicking::panic_fmt::h7894cd1015cfee41
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  18:        0x10881040a - core::panicking::assert_failed_inner::h811f6cef9620601c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:246:17
  19:        0x10881a4a1 - core::panicking::assert_failed::h65bd4ae37c20a13c
  20:        0x1085d5514 - watcher_tests::watcher::lint_watch_test::h802983ce8c5f5977
  21:        0x1085d4875 - watcher_tests::watcher::lint_watch_test::***closure***::h3c3f7df813f77508
  22:        0x1085e87a8 - core::ops::function::FnOnce::call_once::h2db2432c3444ea11
  23:        0x10861eca2 - core::ops::function::FnOnce::call_once::h1b37aa53eb0288c2
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  24:        0x10861eca2 - test::__rust_begin_short_backtrace::h91dc8defba47b824
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:599:18
  25:        0x1085efb11 - test::run_test::***closure***::h59fe59b3e2e9c134
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:590:30
  26:        0x1085efb11 - core::ops::function::FnOnce::call_once***vtable.shim***::hfe07c7668eb7cef4
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  27:        0x10861d9d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h119e8c1162dcbe11
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  28:        0x10861d9d5 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1e21bee716778d6a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panic/unwind_safe.rs:271:9
  29:        0x10861d9d5 - std::panicking::try::do_call::h505c645f6cc32320
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  30:        0x10861d9d5 - std::panicking::try::hcd4ccdd51a99574c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  31:        0x10861d9d5 - std::panic::catch_unwind::he644ea552303b474
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  32:        0x10861d9d5 - test::run_test_in_process::h474e3e304fb437ec
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:622:27
  33:        0x10861d9d5 - test::run_test::run_test_inner::***closure***::he043dad562eb79eb
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:516:39
  34:        0x1085e99c0 - test::run_test::run_test_inner::***closure***::hf330fd255ef63160
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/test/src/lib.rs:543:37
  35:        0x1085e99c0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h129fabb09c3ec406
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:121:18
  36:        0x1085ef75c - std::thread::Builder::spawn_unchecked_::***closure***::***closure***::h1e1ef254b91ed487
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/thread/mod.rs:551:17
  37:        0x1085ef75c - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7d22885f3d408005
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panic/unwind_safe.rs:271:9
  38:        0x1085ef75c - std::panicking::try::do_call::h17eed10251f2fb85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  39:        0x1085ef75c - std::panicking::try::h1d7b2274374038bc
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  40:        0x1085ef75c - std::panic::catch_unwind::hb1c659c5dd663245
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  41:        0x1085ef75c - std::thread::Builder::spawn_unchecked_::***closure***::h0a23b620e97f84a3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/thread/mod.rs:550:30
  42:        0x1085ef75c - core::ops::function::FnOnce::call_once***vtable.shim***::h659d68ce1aa86c29
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  43:        0x1087fbad7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2611f89e824929e3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  44:        0x1087fbad7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb87e0c9c6cb0305b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  45:        0x1087fbad7 - std::sys::unix::thread::Thread::new::thread_start::h7b576c3bd89f934a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys/unix/thread.rs:108:17
  46:     0x7ff8020564e1 - __pthread_start


failures:
    watcher::lint_watch_test
```

**Comment by GJZwiers** [comment]
I have had this one fail together with watcher::test_watch one time: https://github.com/denoland/deno/actions/runs/3877106874/jobs/6611730995

**Comment by GJZwiers** [comment]
Another flake together with `integration::run::worker_close_nested` and `worker_drop_handle_race_terminate`: https://github.com/denoland/deno/actions/runs/4166588607/jobs/7211106272#step:36:3814
