### ISSUE TITLE
deno panics when using prisma cli commands

### ISSUE THREAD

**Issue by Siris01** [denoland/deno#17396]
I am using a manually built version of deno which includes this [commit](https://github.com/denoland/deno/commit/dd2829be0c1f5c40ec38a045ea0a14bec34a82c5). 
The issue **does not** occur with the latest release (1.29.2)

## Steps to reproduce

- Run `deno run --allow-read --allow-env --allow-write npm:prisma@^4.5 init`
- Run `deno run -A --unstable npm:prisma format`

## Stacktrace
```
Prisma schema loaded from prisma/schema.prisma
Formatted /home/ubuntu/invi/config/prisma/schema.prisma in 134ms 🚀
Warning: Not implemented: ChildProcess.prototype.disconnect

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux aarch64
Version: 1.29.2
Args: ["deno", "run", "-A", "--unstable", "npm:prisma", "format", "--schema=./prisma/schema.prisma"]

thread 'main' panicked at 'already borrowed: BorrowMutError', cli/napi/env.rs:85:51
stack backtrace:
   0:     0xaaaab9a102bc - std::backtrace_rs::backtrace::libunwind::trace::h8e94cda3a371544e
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xaaaab9a102bc - std::backtrace_rs::backtrace::trace_unsynchronized::h813157bbdde28662
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaab9a102bc - std::sys_common::backtrace::_print_fmt::h34887c448c3eb497
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0xaaaab9a102bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf93aabc87608898c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xaaaab915c654 - core::fmt::write::hd85235e6dd4a938a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0xaaaab99e547c - std::io::Write::write_fmt::hb4554bbda772d72d
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0xaaaab9a1248c - std::sys_common::backtrace::_print::h79b720bdee2b231c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0xaaaab9a1248c - std::sys_common::backtrace::print::h9cf9c4706df49acb
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0xaaaab9a120f4 - std::panicking::default_hook::{{closure}}::hc23880dedf49de0f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0xaaaab9a11df8 - std::panicking::default_hook::h7fd63ca96b235b7d
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:     0xaaaab910b828 - deno::setup_panic_hook::{{closure}}::h6b73b22e52911361
  11:     0xaaaab9a12d64 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::had0fcc23898ff3c4
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:2001:9
  12:     0xaaaab9a12d64 - std::panicking::rust_panic_with_hook::h5e3e0b54a2bedbd6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:692:13
  13:     0xaaaab9a12b2c - std::panicking::begin_panic_handler::{{closure}}::habceb6baa9148946
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:579:13
  14:     0xaaaab9a12aa0 - std::sys_common::backtrace::__rust_end_short_backtrace::h346bfd6236afcab4
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  15:     0xaaaab9a12a7c - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  16:     0xaaaab8e3a060 - core::panicking::panic_fmt::h8af736328ba90ade
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  17:     0xaaaab8e3a22c - core::result::unwrap_failed::h2e845aa8c8d1ecd0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
  18:     0xaaaab8e66ee8 - core::cell::RefCell<T>::borrow_mut::h0e51aa29864fc4e9
  19:     0xaaaab8e66f74 - napi_remove_env_cleanup_hook
  20:     0xaaaab95ebf14 - core::ptr::drop_in_place<deno_napi::NapiState>::h7f23312a881b4378
  21:     0xaaaab93665ec - core::ptr::drop_in_place<deno_core::gotham_state::GothamState>::h1094fd80bb5a9261
  22:     0xaaaab91fda0c - core::ptr::drop_in_place<deno_core::ops::OpCtx>::hdb4e3f6608ea5f84
  23:     0xaaaab91f006c - core::ptr::drop_in_place<core::cell::RefCell<deno_core::runtime::ContextState>>::h1b8db0d541c0fdeb
  24:     0xaaaab92262bc - v8::isolate::RawSlot::drop_internal::h9f350f9216d4f773
  25:     0xaaaab922b578 - core::ptr::drop_in_place<v8::context::ContextAnnex>::h2178ff422f0c432e
  26:     0xaaaab922b624 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdfcb060169a4ec3e
  27:     0xaaaab9b46928 - <v8::isolate::OwnedIsolate as core::ops::drop::Drop>::drop::h022b25b50018ace9
  28:     0xaaaab8e8f4ec - core::ptr::drop_in_place<deno_core::runtime::JsRuntime>::hc3fd4115cf3b6c68
  29:     0xaaaab8e8f4a8 - core::ptr::drop_in_place<deno_runtime::worker::MainWorker>::h38233115bbe1bbe0
  30:     0xaaaab8e8f414 - core::ptr::drop_in_place<deno::worker::CliMainWorker>::h151da09d9af94623
  31:     0xaaaab8ec8564 - deno::tools::run::run_script::{{closure}}::h5dca8a05bd4b49a5
  32:     0xaaaab8eadf80 - deno::run_subcommand::{{closure}}::h6c8f2b0b39705afe
  33:     0xaaaab8e9cdd8 - deno::main::{{closure}}::hc958af14a4cc55c6
  34:     0xaaaab8e85d14 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h149e95405f7c8902
  35:     0xaaaab8e84d04 - deno_runtime::tokio_util::run_local::hab841faeb9ce8e20
  36:     0xaaaab8e845e0 - deno::main::hb4b6a8db2c8c187a
  37:     0xaaaab8e6607c - std::sys_common::backtrace::__rust_begin_short_backtrace::h8c9de86e8666a6a1
  38:     0xaaaab8e83058 - main
  39:     0xffff9c0373fc - <unknown>
  40:     0xffff9c0374cc - __libc_start_main
  41:     0xaaaab8e63970 - _start
  42:                0x0 - <unknown>
  ```
  
  ## Other issue
  I also faced another similar error:
  ```
  thread 'main' panicked at 'already mutably borrowed: BorrowError', /home/ubuntu/.cargogit/checkouts/deno-22855delc03c9128/0ae8384/ext/napi/lib.rs:508:60 
  ```
  Which seems to be caused by the same commit. However I cannot reliably reproduce this

**Comment by bartlomieju** [comment]
That's unfortunate, I tested it two days ago and wasn't hitting any problems. I'll fix it tonight.

**Comment by bartlomieju** [comment]
@Siris01 which version of Prisma are you using? I'm running a loop with the command that panicked for you and I'm unable to reproduce this panic.

**Comment by Siris01** [comment]
Sorry, yeah im using 4.8.1 too
