### ISSUE TITLE
serde_v8 gives unhelpful errors for some APIs

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#17406]
Consider code below:
```js
Deno.dlopen("./foo.so", { "add": { paramaters: ["i64"], result: "i64" } });
```

There's a type there - `paramaters` instead of `parameters`.

If we run with `--check` flag it's okay, because TS will give us a nice error:
```
❯ deno run --unstable -A --check foo.ts
Check file:///Users/ib/dev/deno/foo.ts
error: TS2322 [ERROR]: Type '{ paramaters: string[]; result: "i64"; }' is not assignable to type 'ForeignFunction<readonly NativeType[], NativeResultType, boolean> | ForeignStatic<NativeType>'.
  Object literal may only specify known properties, and 'paramaters' does not exist in type 'ForeignFunction<readonly NativeType[], NativeResultType, boolean> | ForeignStatic<NativeType>'.
Deno.dlopen("./foo.so", { "add": { paramaters: ["i64"], result: "i64" } });
                                   ~~~~~~~~~~~~~~~~~~~
    at file:///Users/ib/dev/deno/foo.ts:1:36

```

But running without type checking:
```
error: Uncaught TypeError: Error parsing args at position 0: data did not match any variant of untagged enum ForeignSymbol
Deno.dlopen("./foo.so", { "add": { paramaters: ["i64"], result: "i64" } });
     ^
    at new DynamicLibrary (deno:ext/ffi/00_ffi.js:276:39)
    at Object.dlopen (deno:ext/ffi/00_ffi.js:374:12)
    at file:///Users/ib/dev/deno/foo.js:1:6

```

It's a guessing game 🤷 if you don't know what's wrong then you can't really say how to fix it. Ideally the error would say something like: "`paramater` is not recognized option".

**Comment by crowlKats** [comment]
Similar to #15389

**Comment by bartlomieju** [comment]
@crowlKats could you look into fixing this problem?

**Comment by bartlomieju** [comment]
This is now fixed:

```
error: Uncaught TypeError: Error parsing args at position 0: missing field `parameters`
Deno.dlopen("./foo.so", { "add": { paramaters: ["i64"], result: "i64" } });
```
