### ISSUE TITLE
npm:mocha - Fails when running in parallel mode

### ISSUE THREAD

**Issue by char8x** [denoland/deno#17413]
## Problem
Fails when running mocha in parallel mode
```sh
deno run -A npm:mocha@10.2.0 --parallel 'test.mjs'
```
### test.mjs
```js
import chai from "npm:chai";
const assert = chai.assert;

describe("Example", () => {
  it("test", () => {
    assert.equal(1, 1);
  });
});
```
## Error Output
```sh
Warning: Not implemented: process.connected

error: could not find npm package for 'file:///Users/xxxx/Library/Caches/deno/npm/registry.npmjs.org/mocha/10.2.0/lib/nodejs/worker.js'

  1) Uncaught error outside test suite

  0 passing (15ms)
  1 failing

  1) Uncaught error outside test suite:
     Uncaught Error: Workerpool Worker terminated Unexpectedly
    exitCode: `1`
    signalCode: `null`
    workerpool.script: `/Users/xxxx/Library/Caches/deno/npm/registry.npmjs.org/mocha/10.2.0/lib/nodejs/worker.js`
    spawnArgs: `/opt/homebrew/bin/deno,run,--unstable,--node-modules-dir,-A,/Users/xxxx/Library/Caches/deno/npm/registry.npmjs.org/mocha/10.2.0/lib/nodejs/worker.js`
    spawnfile: `/opt/homebrew/bin/deno`
    stdout: `null`
    stderr: `null`

      at ChildProcess.<anonymous> (file:///Users/xxxx/Library/Caches/deno/npm/registry.npmjs.org/workerpool/6.2.1/src/WorkerHandler.js:294:13)
      at ChildProcess.emit (https://deno.land/std@0.172.0/node/_events.mjs:379:28)
      at https://deno.land/std@0.172.0/node/internal/child_process.ts:223:16
```

## Env

Deno: 1.29.3
macOS: 12.6.2

**Comment by bartlomieju** [comment]
Fixed — closing.

Verified on a current build: `deno run -A npm:mocha@10.2.0 --parallel test.mjs` now runs mocha's parallel worker pool correctly. The original failure (`could not find npm package for '.../mocha/10.2.0/lib/nodejs/worker.js'` -> "Workerpool Worker terminated Unexpectedly") no longer reproduces.

Running the original repro passes:
```
  Example
    ✔ test
  1 passing
```

Note: the repro as written now errors for an unrelated reason — it imports unpinned `npm:chai`, which today resolves to chai@6, an ESM-only release that dropped the default export, so `import chai from "npm:chai"` throws `does not provide an export named 'default'`. That's chai's own API change, not a Deno issue; pinning `npm:chai@4` (current at the time this was filed) makes it green. The parallel-mocha bug itself is resolved.
