### ISSUE TITLE
deno asks for `NODE_CLUSTER_SCHED_POLICY` every time on `deno run`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#17414]
## Summary
```ts
// hello.ts
console.log('hello world')
```
from deno 1.29.3, every `deno run` reqeusts env access to `NODE_CLUSTER_SCHED_POLICY`, which is a bit inconvenient.

## Log
```
$ deno --version
deno 1.29.3 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4

$ deno run hello.ts 
⚠️  ┌ Deno requests env access to "NODE_CLUSTER_SCHED_POLICY".
   ├ Run again with --allow-env to bypass this prompt.
   └ Allow? [y/n] (y = yes, allow; n = no, deny) > 

❌ Denied env access to "NODE_CLUSTER_SCHED_POLICY".
error: Uncaught PermissionDenied: Requires env access to `NODE_CLUSTER_SCHED_POLICY`, run again with the --allow-env flag
    return Deno.env.get(name);
                    ^
    at Object.getEnv [as get] (deno:runtime/js/30_os.js:86:16)
    at denoEnvGet (https://deno.land/std@0.172.0/node/_process/process.ts:38:21)
    at Object.get (https://deno.land/std@0.172.0/node/_process/process.ts:59:24)
    at https://deno.land/std@0.172.0/node/internal/cluster/primary.ts:45:41
```

**Comment by bartlomieju** [comment]
CC @kt3k could you take a look?
