### ISSUE TITLE
Deno panics when using prisma

### ISSUE THREAD

**Issue by Siris01** [denoland/deno#17457]
Deno version - `12.9.4` (built from source)
Prisma version - `4.8.1`

# schema.prisma
```prisma 
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["deno"]
  output          = "./generated/client"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model user {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

# run.ts
```typescript
import { createRequire } from "https://deno.land/std@0.171.0/node/module.ts";
const require = createRequire(import.meta.url);

const { PrismaClient } = require("./generated/client");
const prisma = new PrismaClient();

await prisma.user.findMany().then(() => console.log("ok"));
```

# Steps to reproduce
- `deno run -A --unstable npm:prisma init`
- `deno run -A --unstable npm:prisma db push --schema ./schema.prisma` ( Also generates client automatically)
- Run `run.ts` multiple times (could use a bash for-loop), it should panic at least once in 20-25 times

# Stacktrace
```rust
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux aarch64
Version: 1.29.4
Args: ["/home/ubuntu/.cargo/bin/deno", "run", "--unstable", "--allow-env", "--allow-read", "--allow-write", "--allow-ffi", "--allow-sys", "--allow-run", "--allow-net", "src/main.ts"]

thread 'main' panicked at 'already mutably borrowed: BorrowError', /home/ubuntu/.cargo/git/checkouts/deno-22855de1c03c9128/f2a5f6d/ext/napi/lib.rs:536:60
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
   3: deno_napi::init::{{closure}}
   4: deno_core::runtime::JsRuntime::poll_event_loop
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: deno::tools::run::run_script::{{closure}}
  11: deno::run_subcommand::{{closure}}
  12: deno::main::{{closure}}
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: deno_runtime::tokio_util::run_local
  15: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Reference - #17396 (was mentioned here but without any reproduction steps)
PS - Thank you quickly fixing all the other napi related bugs!

**Comment by Siris01** [comment]
```bash
success=0
failure=0

for i in {1..50}
do
   deno run -A --unstable repr.ts
   if [ $? -ne 0 ];
   then
      failure=$((failure+1))
   else 
      success=$((success+1))
   fi
done

echo "Success: $success"
echo "Failure: $failure"
```

Success: 38
Failure: 12

**Comment by bartlomieju** [comment]
Thanks for reporting and sorry for the problem. I'll try to fix it this week.

**Comment by waptik** [comment]
I was about about to report this problem. It all started when i upgraded to deno v1.29.3 and prisma v4.18.1.
I'm using mysql and it occurs when running `deno run -A --unstable npm:prisma generate --data-proxy`

**Comment by waptik** [comment]
@bartlomieju is it possbile to lock prisma version to `v4.7.1` in the meantime?

**Comment by bartlomieju** [comment]
> @bartlomieju is it possbile to lock prisma version to `v4.7.1` in the meantime?

I haven't tried it, I know prisma worked in Deno 1.29.2; sorry for the problems.

**Comment by waptik** [comment]
> > @bartlomieju is it possbile to lock prisma version to `v4.7.1` in the meantime?
> 
> I haven't tried it, I know prisma worked in Deno 1.29.2; sorry for the problems.

No problem. I just saw that there's a new version of Deno 1.29.4. So after upgrading to that version, prisma started working properly.

Also one small issue, when using `db pull` the execution doesn't exit console. I have to manually press `ctrl+c` to exit the execution process

![image](https://user-images.githubusercontent.com/1687551/212952332-7aa7b5bc-5d74-43ba-bedc-f6daf515a785.png)

**Comment by waptik** [comment]
> @waptik could you open a separate issue for this? I'll look into it

Okay, I'll do that at later in the day. Thanks

**Comment by Siris01** [comment]
Hey @bartlomieju, unfortunately I don't think the PR fully fixed the issue, deno still panics (but noticeably, a lot less frequently than before) with the same steps as mentioned above.

Here's the stack trace if you need it:
```rust
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux aarch64
Version: 1.29.4
Args: ["deno", "run", "-A", "--unstable", "repr.ts"]

thread 'main' panicked at 'already mutably borrowed: BorrowError', /home/ubuntu/.cargo/git/checkouts/deno-22855de1c03c9128/f1b275e/ext/napi/lib.rs:536:62
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
   3: deno_napi::init::{{closure}}
   4: deno_core::runtime::JsRuntime::poll_event_loop
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: deno::tools::run::run_script::{{closure}}
  11: deno::run_subcommand::{{closure}}
  12: deno::main::{{closure}}
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: deno_runtime::tokio_util::run_local
  15: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bartlomieju** [comment]
@Siris01 thanks for letting me know; did you build Deno yourself off of the `main` branch?

**Comment by bartlomieju** [comment]
Cool, thanks for checking. I'll try another fix.

**Comment by Siris01** [comment]
Thank you, this seems to have fully fixed the issue!
