### ISSUE TITLE
{Linux}  Permission denied (os error 13)

### ISSUE THREAD

**Issue by ngdangtu-vn** [denoland/deno#17474]
From the latest deno, the old bug was brought back from #3251

```
deno 1.29.4 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```

Mine is TuxedoOS distro base on Ubuntu. Here is my code:

```Typescript
#!/usr/bin/env -S deno  -Ldebug -q run --allow-read --allow-net --prompt

const config: Deno.ListenTlsOptions = {
	hostname: '127.0.0.1',
	port: 444,
	cert: await Deno.readTextFile('./server/localhost.crt'),
	key: await Deno.readTextFile('./server/localhost.key'),
}

/**
 * main()
 */
const server: Deno.TlsListener = Deno.listenTls(config)
for await (const connection of server) handle(connection)


async function handle(connection: Deno.TlsConn)
{
	const http = Deno.serveHttp(connection)

	for await (const evt of http)
	{
		const request: Request = evt.request
		console.log(request)
	}
}
```

Run with `-Ldebug`

```
DEBUG RS - deno::js:33 - Deno isolate init with snapshots.
DEBUG JS - args []
DEBUG RS - deno::worker:66 - main_module file:///home/user/work/lab/toy-project/serve.ts
DEBUG RS - deno::proc_state:327 - Preparing module load.
DEBUG RS - deno::cache::parsed_source:156 - Loading cached module analyzer.
DEBUG RS - deno::proc_state:406 - Creating module graph.
DEBUG RS - deno::file_fetcher:551 - FileFetcher::fetch() - specifier: file:///home/user/work/lab/toy-project/serve.ts
DEBUG RS - deno_runtime::permissions:55 - ⚠️️  Granted read access to "/home/user/work/lab/toy-project/serve.ts"
DEBUG RS - deno::proc_state:498 - Prepared module load.
DEBUG RS - deno_runtime::permissions:55 - ⚠️️  Granted read access to "./server/localhost.crt"
DEBUG RS - deno_runtime::permissions:55 - ⚠️️  Granted read access to "./server/localhost.key"
DEBUG RS - deno_runtime::permissions:55 - ⚠️️  Granted net access to "127.0.0.1:444"
error: Uncaught (in promise) PermissionDenied: Permission denied (os error 13)
const server: Deno.TlsListener = Deno.listenTls(config)
                                      ^
    at Object.listenTls (deno:ext/net/02_tls.js:73:42)
    at file:///home/user/work/lab/toy-project/serve.ts:17:39
```

**Comment by ngdangtu-vn** [comment]
Could it be blocked by `ufw`? My ufw is active and allow Apache2 from Anywhere.

**Comment by kt3k** [comment]
What happens if you change the port number to, for example, 8444? Also what happens if you run the program as root user? (ie. `sudo deno run ...`

**Comment by kt3k** [comment]
Listening on port number <= 1024 is often disabled for a normal user. See https://serverfault.com/questions/112795/how-to-run-a-server-on-port-80-as-a-normal-user-on-linux

**Comment by jtoppine** [comment]
> Listening on port number <= 1024 is often disabled for a normal user. See https://serverfault.com/questions/112795/how-to-run-a-server-on-port-80-as-a-normal-user-on-linux

Just gonna comment here that I think it would be great to have this solution very prominently shown on deno docs. Specifically the   `sudo setcap 'cap_net_bind_service=+ep' /path/to/deno `

This is a very commonly asked question. It is amazing how many people don't know about this solution, and go on to advice running deno as root or similarly bad ideas as workaround. Linux packages for servers like apache or nginx generally handle this permission obstacle somehow automatically. Deno doesn't automatically handle it, opening ports like 80 or 443 is very common use case, and the "correct" solution is quite obscure. All this makes it a very frustrating experience for newbies.

**Comment by ngdangtu-vn** [comment]
[kt3k](https://github.com/kt3k)
> Listening on port number <= 1024 is often disabled for a normal user.

You were right. I usually use 80/443 on Apache but Apache runs as demon so I never know about this.

[jtoppine](https://github.com/jtoppine)
> All this makes it a very frustrating obstacle for newbies.

You are right, should we put this (https://serverfault.com/questions/112795/how-to-run-a-server-on-port-80-as-a-normal-user-on-linux - thanks to kt3k) to the error?

**Comment by bartlomieju** [comment]
Closing, as this is not a Deno bug. The repro binds to port 444, a privileged port (<=1024). On Linux, binding to those ports as a non-root user requires `CAP_NET_BIND_SERVICE`, so the kernel returns `EACCES` (os error 13), which Deno surfaces as `PermissionDenied`. This is unrelated to Deno's `--allow-net` permission (granted in the debug log) and unrelated to #3251.

As diagnosed in-thread by @kt3k, the fix is one of:
- use a high port (e.g. 8444),
- run with `sudo`, or
- grant the capability: `sudo setcap 'cap_net_bind_service=+ep' /path/to/deno`.

The reporter confirmed this resolved it. The remaining suggestion here, surfacing the `setcap` hint in the error message when binding a privileged port fails on Linux, is a reasonable DX enhancement, but it is better tracked as a separate focused issue than under this invalid bug report. Closing as not-a-bug.
