### ISSUE TITLE
panick when Deno.readDir pointed at dir with input/output errors

### ISSUE THREAD

**Issue by Sembiance** [denoland/deno#17518]
When using `deno 1.29.4` on `Linux 5.18.8` if you attempt to call `Deno.readDir()` with a directory that has input/output errors, Deno panics.

Reproduction steps (requries `fuseiso` be installed):
1. `wget https://telparia.com/wip/denoCrash.iso`
2. `mkdir mountPoint`
3. `fuseiso denoCrash.iso mountPoint`
4. `deno eval 'await Deno.readDir("mountPoint")'`

Cleanup with: `fusermount -u mountPoint`

Output of `RUST_BACKTRACE=1 deno eval 'await Deno.readDir("mountPoint")'`:
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.29.4
Args: ["deno", "eval", "await Deno.readDir(\"mountPoint\")"]

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: Uncategorized, message: "Input/output error" }', runtime/ops/fs.rs:1302:27
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bartlomieju** [comment]
Duplicate of #17446, and the underlying panic is fixed. The backtrace here points at the same `unwrap()` on a `DirEntry` that returned `EIO` (`runtime/ops/fs.rs:1302` at the time). That code moved to `ext/fs/std_fs.rs` and the `unwrap()` is gone, replaced with `entry.ok()?`:

```rust
fn read_dir(path: &Path) -> FsResult<Vec<FsDirEntry>> {
  let entries = fs::read_dir(path)?
    .filter_map(|entry| {
      let entry = entry.ok()?;   // was unwrap() — EIO entry is now skipped, no panic
      ...
```

So an entry that fails with `EIO` is dropped via `filter_map` instead of crashing the runtime. Closing as a duplicate of #17446.

Note: Deno currently skips such entries silently, whereas Node surfaces `EIO`. If visible error propagation is wanted, that is worth a separate focused issue.
