### ISSUE TITLE
Connection error with @azure/keyvault-secrets

### ISSUE THREAD

**Issue by js-writer** [denoland/deno#17540]
My code:

```
import { DefaultAzureCredential } from "npm:@azure/identity@^3.1";
import { SecretClient } from "npm:@azure/keyvault-secrets@^4.6";

const credentials = new DefaultAzureCredential();

const client = new SecretClient(<URL>, credentials);


client.getSecret(<Secret-key>).then(res => console.log(res))
.catch(e => {
    console.log("Error!!!", e);
})
```

I'm getting my secret but Deno seams to keep connection and after few seconds I'm getting this error:

error: Uncaught TypeError: error sending request for url (http://169.254.169.254/metadata/identity/oauth2/token): error trying to connect: tcp connect error: Próba połączenia nie powiodła się, ponieważ połączona strona nie odpowiedziała poprawnie po ustalonym okresie czasu lub utworzone połączenie nie powiodło się, ponieważ połączony host nie odpowiedział. (os error 10060)
      await mayResponse,
      ^
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async ClientRequest._final (https://deno.land/std@0.173.0/node/http.ts:147:7)

This is a problem because it crash server.
Permissions I'm using are: deno run --allow-env --allow-read --allow-sys --allow-net --allow-run
But even with --allow-all I have this issue.

Deno version: 1.29.4

In Node version everything is working fine.

BTW.
For Deno I needed to do: Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
and 
Connect-AzAccount  
To have it working in powerShell while for Node simple azure-cli was enough.

P.S
Sorry for Polish text, but I hope Bartek will understand.

**Comment by js-writer** [comment]
Ok I figured it out.
Because Deno is not azure supported app I needed to use AzurePowerShellCredential instead of DefaultAzureCredential. And know it is working the same way as Node.
