### ISSUE TITLE
ASI - Deno fmt panic on property preceeding generator method

### ISSUE THREAD

**Issue by UrielCh** [denoland/deno#17559]
```bash
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.30.0
Args: ["deno", "fmt", "struct.ts"]

thread 'tokio-runtime-worker' panicked at 'Formatting succeeded initially, but failed when ensuring a stable format. This indicates a bug in the formatter where the text it produces is not syntatically correct. As a temporary workfaround you can ignore this file (/mnt/c/ml/deno-pystruct/struct.ts).

Expected ',', got ':' at /mnt/c/ml/deno-pystruct/struct.ts:520:22

    *iter_unpack(buffer: ArrayBuffer, offset = 0): Generator<PackSupportedType, vo...
                       ~', cli/tools/fmt.rs:429:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://github.com/UrielCh/deno-pystruct/blob/main/struct.ts

reference to other fmt panic:
#14527
#14728

**Comment by kefniark** [comment]
I have a similar issue when I use the new settings `"semiColons": false`

```sh
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env     
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.30.0
Args: ["C:\\Users\\kevin\\scoop\\apps\\deno\\current\\deno.exe", "fmt"]

thread 'tokio-runtime-worker' panicked at 'Formatting succeeded initially, but failed when ensuring a stable format. This indicates a bug in the formatter where the text it produces is not syntatically correct. As a temporary workfaround you can ignore this file (C:\Users\kevin\Documents\GitHub\deno-trad\frontend\dist\assets\index-e28ea02d.js).

Expected ';', '}' or <eof> at C:\Users\kevin\Documents\GitHub\deno-trad\frontend\dist\assets\index-e28ea02d.js:4426:31

        do i.push(n.call(this)) while (!this.expectOptionalToken(r))
                                ~~~~~', cli\tools\fmt.rs:429:13 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by dsherret** [comment]
@kefniark that's unrelated to this. Could you open an issue here? https://github.com/dprint/dprint-plugin-typescript/issues/new?assignees=&labels=&template=deno-fmt-bug-report.md&title=

**Comment by dsherret** [comment]
Oh wait, I see it's the same error now. Sorry
