### ISSUE TITLE
Deno can't find command

### ISSUE THREAD

**Issue by js-writer** [denoland/deno#17558]
I'm trying to use npm @azure/identity (v.3.1.3) with Deno but there is some problem with login to azure when I use AzureCliCredential.

I'm getting this error:

```
CredentialUnavailableError: '\"az account get-access-token --output json --resource https://vault.azure.net --tenant <myTenant>\"' is not recognized as an internal or external command,
operable program or batch file.

    at file:///C:/Users/<user>/AppData/Local/deno/npm/registry.npmjs.org/@azure/identity/3.1.3/dist/index.js:2489:31
    at Object.runMicrotasks (deno:core/01_core.js:386:30)
    at processTicksAndRejections (https://deno.land/std@0.173.0/node/_next_tick.ts:62:10)
    at async Object.withSpan (file:///C:/Users/<user>/AppData/Local/deno/npm/registry.npmjs.org/@azure/core-tracing/1.0.1/dist/index.js:140:28)
    at async tryGetAccessToken (file:///C:/Users/<user>/AppData/Local/deno/npm/registry.npmjs.org/@azure/core-rest-pipeline/1.10.1/dist/index.js:1997:32)
    at async beginRefresh (file:///C:/Users/<user>/AppData/Local/deno/npm/registry.npmjs.org/@azure/core-rest-pipeline/1.10.1/dist/index.js:2005:17)
    at async Object.authorizeRequestOnChallenge (file:///C:/Users/<user>/AppData/Local/deno/npm/registry.npmjs.org/@azure/keyvault-secrets/4.6.0/dist/index.js:1243:29)
    at async Object.sendRequest (file:///C:/Users/<user>/AppData/Local/deno/npm/registry.npmjs.org/@azure/core-rest-pipeline/1.10.1/dist/index.js:2198:43)
```

In node version everything is fine. So I think Deno is doing something in a different way.

I check this file @azure/identity/3.1.3/dist/index.js:2489:31 and the code looks like this:

```
return new Promise((resolve, reject) => {
            try {
                child_process__default["default"].execFile("az", [
                    "account",
                    "get-access-token",
                    "--output",
                    "json",
                    "--resource",
                    resource,
                    ...tenantSection,
                ], { cwd: cliCredentialInternals.getSafeWorkingDir(), shell: true }, (error, stdout, stderr) => {
                    resolve({ stdout: stdout, stderr: stderr, error });
                });
            }
            catch (err) {
                reject(err);
            }
        });
```
So Deno somehow doesn't see az command from azure-cli... 

I'm working on Windows 10. Deno 1.29.4

**Comment by GJZwiers** [comment]
This is the [link to the code on Github](https://github.com/Azure/azure-sdk-for-js/blob/21ff34e2589f255e8ffa7f7d5d65ca40434ec34d/sdk/identity/identity/src/credentials/azureCliCredential.ts#L48). I think the error is quite similar to the one I encountered in https://github.com/denoland/deno/issues/16714.

**Comment by js-writer** [comment]
Thx for github code.
Yes, I think it looks similar.

**Comment by GJZwiers** [comment]
So this problem appears to happen with `child_process.execFile` and also `child_process.exec`, possibly when it is used together with `promisify` from `util`.

```js
import { exec as _exec } from 'node:child_process';
import { promisify } from 'node:util';

const exec = promisify(_exec);

const { stdout, stderr } = await exec('npm view aws-cdk version');
```

```
deno run -A .\asdf.mjs
error: Uncaught Error: Command failed: npm view aws-cdk version
'\"npm view aws-cdk version\"' is not recognized as an internal or external command,
operable program or batch file.

      ex = new ExecFileError(
           ^
    at ChildProcess.exithandler (https://deno.land/std@0.174.0/node/child_process.ts:520:12)
    at ChildProcess.emit (https://deno.land/std@0.174.0/node/_events.mjs:379:28)
    at https://deno.land/std@0.174.0/node/internal/child_process.ts:232:16
    at Object.runMicrotasks (deno:core/01_core.js:386:30)
    at processTicksAndRejections (https://deno.land/std@0.174.0/node/_next_tick.ts:62:10)
```

**Comment by GJZwiers** [comment]
Okay it's not due to promisify:

```js
import { exec } from 'node:child_process';

const { stdout, stderr } = exec('npm view aws-cdk version');
stderr.on("data", (chunk) => {
    console.log(chunk);
});
```

```
deno run -A .\asdf.mjs
'\"npm view aws-cdk version\"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bartlomieju** [comment]
Gonna close this one as there's been no feedback in almost 2 years.
