### ISSUE TITLE
fetch() won't work inside docker container: denoland/deno:debian

### ISSUE THREAD

**Issue by coderbuzz** [denoland/deno#17557]
I'm facing a problem with fetch(), this code working fine on local Mac.
But won't work when running inside docker container using **denoland/deno:debian** image behind **Traefik** reverse proxy

``` typescript
fetch('http://localhost:9000/path') // Work! -> hit using localhost 
fetch('https://appdomain.com/path') // Not Work! -> hit using domain, it should route to it self (localhost:9000) by Traefik
```

``` console
error: Uncaught (in promise) TypeError: error sending request for url (https://appdomain.com/path/): error trying to connect: tcp connect error: Connection timed out (os error 110)
at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
at async fetch (deno:ext/fetch/26_fetch.js:491:9)
```

Update:
1. Sample code:

``` typescript
async function main() {
  console.log('Calling fetch...')
  // const result = await fetch('https://dummyjson.com/products/1') // Pointing to another domain OK!
  const result = await fetch('https://appdomain/path/') // Pointing to self using domain os error 110 above
  console.log('result', result)

  setTimeout(main, 5000)
}

main()
```

``` console
HTTP Server started ~ http://localhost:9000/
Calling fetch...

error: Uncaught (in promise) TypeError: error sending request for url (https://appdomain.com/path/): error trying to connect: tcp connect error: Connection timed out (os error 110)
at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
at async fetch (deno:ext/fetch/26_fetch.js:491:9)
```

**Comment by coderbuzz** [comment]
It seem related to Traefik routing configuration.
