### ISSUE TITLE
`Deno.watchFs()` is returns `serde_v8 error: ExpectedString`

### ISSUE THREAD

**Issue by skanehira** [denoland/deno#17561]
When I run `Deno.watchFs(undefined)`, it returns `serde_v8 error: ExpectedString`.

```sh
> Deno.watchFs(undefined)
Uncaught TypeError: Error parsing args at position 0: serde_v8 error: ExpectedString
    at new FsWatcher (deno:runtime/js/40_fs_events.js:19:23)
    at Object.watchFs (deno:runtime/js/40_fs_events.js:64:12)
    at <anonymous>:2:6
> 
```

I think we should validate `""`,`undefined`, `null` and throw error.

https://github.com/denoland/deno/blob/7f38f30a5c0eb06c5b85d1c7ac26a480c210aab6/runtime/js/40_fs_events.js#L64

I will create a PR if my opinion is accepted :)

**Comment by magurotuna** [comment]
I agree that the error message is not friendly, but if we decided to check if the passed argument is either `""`, `undefined`, or `null`, then we might end up wishing to check other posibilities, like number, bool, etc. So I think the check on the argument type should be delegated to TypeScript layer. WIth this regard, we have proper type declarations for `Deno.watchFs` so running `Deno.watchFs(undefined)` with `deno run --check` gives us a friendly error message - in my opinion it suffices.

```
magurotuna@magurotuna:/tmp$ deno run --check watchfs.ts
Check file:///tmp/watchfs.ts
error: TS2345 [ERROR]: Argument of type 'undefined' is not assignable to parameter of type 'string | string[]'.
Deno.watchFs(undefined);
             ~~~~~~~~~
    at file:///tmp/watchfs.ts:1:14
```

**Comment by skanehira** [comment]
Thank you, Agreed 👍
