### ISSUE TITLE
"unexpected end of file" error for some requests using fetch

### ISSUE THREAD

**Issue by ricardopieper** [denoland/deno#17565]
Hello!

I'm reporting an issue that I also found on Node.js. I am having a bit of trouble explaining the issue there (https://github.com/nodejs/node/issues/46359) but I think I finally found the root cause, at least in Node. You can look at the Node.js issue because I think many things there are useful to understand the issue I'm creating here.

Here's my environment:

```
deno 1.30.0 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
Darwin MacBook-Pro-de-Ricardo.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
```

I start a new repl session on Deno, and for this particular URL this happens:

```
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> let x = await fetch("https://elza-c332f.firebaseapp.com/__/auth/handler.js")
console.log(await x.text())
Uncaught TypeError: error decoding response body: unexpected end of file
    at async readableStreamCollectIntoUint8Array (deno:ext/web/06_streams.js:822:21)
    at async consumeBody (deno:ext/fetch/22_body.js:232:11)
    at async <anonymous>:3:13
```

Ok, the first thing that the Node.js team thought is "the server is just returning a truncated response". If this issue is happening both on Deno and Node, it's easy to believe this to be true. But if you think about the wider context, this is a Firebase response. Just imagine if *Firebase*, a google-backed service, widely used everywhere in the world, would start returning a truncated script file! This is Firebase Auth, many services would stop working correctly. It's a massive problem that would've been investigated for at least 2 days now by the Firebase devs. And this is just not happening, everything on their servers is looking OK (their SDK isn't, which is partly the reason why I ended up here).

And indeed, browsers deal with this URL just fine:

![image](https://user-images.githubusercontent.com/4030858/215145657-ead3f853-5814-4c46-8db6-f168ea16963b.png)

Python also has no issue at all decompressing this content:

```
>>> import requests; x = requests.get("https://elza-c332f.firebaseapp.com/__/auth/handler.js", {'accept-encoding': 'gzip'})
>>> x.headers
{'Connection': 'keep-alive', 'Content-Length': '85989', 'Cache-Control': 'max-age=1800', 'Content-Encoding': 'gzip', 'Content-Type': 'text/javascript; charset=utf-8', 'Strict-Transport-Security': 'max-age=31556926; includeSubDomains; preload', 'Accept-Ranges': 'bytes', 'Date': 'Fri, 27 Jan 2023 15:18:10 GMT', 'X-Served-By': 'cache-cgh11125-CGH', 'X-Cache': 'HIT', 'X-Cache-Hits': '1', 'X-Timer': 'S1674832691.732797,VS0,VE1', 'Vary': 'x-fh-requested-host, accept-encoding', 'alt-svc': 'h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400'}
>>> len(x.content) == 274237
```

However, gzip also has the same problem as deno & node:

```
$ curl --http1.1 -o compressed -H 'accept-encoding: gzip' https://elza-c332f.firebaseapp.com/__/auth/handler.js
# downloads 85,989 bytes

$ gzip -c -d compressed | wc -c
gzip: compressed: unexpected end of file
gzip: compressed: uncompress failed
  262144
```

If I take this compressed file that curl downloaded and try decompressing it on some online decompressing websites, I get mixed results:
 
 - https://extract.me/ just gives me a truncated response, there's 12kb missing from the result.
 - https://gzip.swimburger.net/ works just fine, all 274237 bytes are there.

So this file is definitely decompressable, all the bytes seem to be there. But some implementations are not being able to decompress it for some reason, and this includes the gzip command line utility, node, deno, and potentially others.

You might ask: Why is he trying to download this file from node? The answer is that I'm gonna run some things on Vercel, Firefox and Safari are not dealing with all the auth redirects the same way Chrome does, some local storage/cookie things are not happening, and I am proxying the request through Vercel so that the auth and app domain are the same. This worked using a lower-level node API that doesn't download it in gzipped format (no accept-encoding: gzip). 

The only thing I ask from the Deno team is to at least take a look at this. Maybe the issue is simply fixable by using a newer version of zlib, if that's what you guys are using?

**Comment by ricardopieper** [comment]
Added more details in the node.js issue.

**Comment by ricardopieper** [comment]
If you guys are using zlib, you can close the issue. This is intended behavior and the zlib developer confirmed the byte stream is finishing prematurely, just enough that browsers can handle it.

**Comment by bartlomieju** [comment]
Confirmed this still reproduces on current Deno, but it's working as intended. Reproduced locally without the original URL: gzip a payload, drop the trailing bytes (removing the gzip CRC32+ISIZE trailer to simulate the server's prematurely-finished stream), serve it with `content-encoding: gzip`, then fetch it:

```
RESULT: ERROR - TypeError: unexpected end of file
```

The stream is genuinely truncated, and our decoding goes through zlib, which (correctly) rejects an incomplete gzip stream - the same as Node, the `gzip` CLI, and zlib itself. As you noted, the zlib maintainer confirmed the byte stream is finishing prematurely.

Some decoders (browsers, Python `requests`) are lenient and return whatever they managed to decode, but that means silently surfacing partial/corrupt data, which we don't want to do by default. The right fix is on the server returning the truncated response.

Closing as not planned per the above (and your own follow-up that this is intended zlib behavior).
