### ISSUE TITLE
Dynamic import of npm packages that depend on the Node API fails

### ISSUE THREAD

**Issue by tennashi** [denoland/deno#17579]
## Environment
```shellsession
$ deno --version
deno 1.30.0 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```

## Details
* `main.ts`
```ts
import * as cp from "https://deno.land/std/node/child_process.ts";
import { createProtocolConnection, Logger, InitializeRequest } from "npm:vscode-languageserver-protocol";
import { StreamMessageReader, StreamMessageWriter } from "npm:vscode-languageserver-protocol/node.js";

class NullLogger implements Logger {
  error(_message: string): void { }
  warn(_message: string): void { }
  info(_message: string): void { }
  log(_message: string): void { }
}

const svc = cp.spawn("deno", ["lsp"])

const clientConn = createProtocolConnection(
  new StreamMessageReader(svc.stdout),
  new StreamMessageWriter(svc.stdin),
  new NullLogger(),
);

clientConn.listen();

console.log(
  await clientConn.sendRequest(
    InitializeRequest.type,
    {
      rootUri: 'file:///home/test',
      processId: svc.pid,
      capabilities: {},
      workspaceFolders: null,
    },
  ),
)
```

* `dynimport.ts`
```ts
import { toFileUrl } from "https://deno.land/std/path/mod.ts";

await import(toFileUrl('/path/to/main.ts').href)
```

`deno run -A main.ts` is working.

<details><summary>`deno run -A main.ts`</summary><div>

```shellsession
$ deno run -A main.ts
{
  capabilities: {
    textDocumentSync: { openClose: true, change: 2, save: {} },
    selectionRangeProvider: true,
    hoverProvider: true,
    completionProvider: {
      resolveProvider: true,
      triggerCharacters: [
        ".", '"', "'",
        "`", "/", "@",
        "<", "#"
      ],
      allCommitCharacters: [ ".", ",", ";", "(" ]
    },
    signatureHelpProvider: { triggerCharacters: [ ",", "(", "<" ], retriggerCharacters: [ ")" ] },
    definitionProvider: true,
    typeDefinitionProvider: true,
    implementationProvider: true,
    referencesProvider: true,
    documentHighlightProvider: true,
    documentSymbolProvider: { label: "Deno" },
    workspaceSymbolProvider: true,
    codeActionProvider: true,
    codeLensProvider: { resolveProvider: true },
    documentFormattingProvider: true,
    renameProvider: true,
    foldingRangeProvider: true,
    workspace: { workspaceFolders: { supported: true, changeNotifications: true } },
    callHierarchyProvider: true,
    semanticTokensProvider: {
      legend: { tokenTypes: [Array], tokenModifiers: [Array] },
      range: true,
      full: true
    },
    inlayHintProvider: true,
    experimental: { denoConfigTasks: true, testingApi: true }
  },
  serverInfo: {
    name: "deno-language-server",
    version: "1.29.1 (release, x86_64-unknown-linux-gnu)"
  }
}
^C
```
</div></details>

But, `deno run -A dynimport.ts` returns an import error.

```shellsession
$ deno run -A dynimport.ts
error: Uncaught Error: Cannot find module 'util'
Require stack:
- /home/tennashi/.cache/deno/npm/registry.npmjs.org/vscode-jsonrpc/8.0.2/lib/node/ril.js
- /home/tennashi/.cache/deno/npm/registry.npmjs.org/vscode-jsonrpc/8.0.2/lib/node/main.js
- /home/tennashi/.cache/deno/npm/registry.npmjs.org/vscode-jsonrpc/8.0.2/node.js
- /home/tennashi/.cache/deno/npm/registry.npmjs.org/vscode-languageserver-protocol/3.17.2/lib/node/main.js
- /home/tennashi/.cache/deno/npm/registry.npmjs.org/vscode-languageserver-protocol/3.17.2/lib/node/main.js
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:637:17)
    at Function.Module._load (deno:ext/node/02_require.js:469:29)
    at Module.require (deno:ext/node/02_require.js:680:21)
    at require (deno:ext/node/02_require.js:820:18)
    at Object.<anonymous> (file:///home/tennashi/.cache/deno/npm/registry.npmjs.org/vscode-jsonrpc/8.0.2/lib/node/ril.js:8:16)
    at Object.<anonymous> (file:///home/tennashi/.cache/deno/npm/registry.npmjs.org/vscode-jsonrpc/8.0.2/lib/node/ril.js:165:4)
    at Module._compile (deno:ext/node/02_require.js:747:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:780:12)
    at Module.load (deno:ext/node/02_require.js:658:34)
    at Function.Module._load (deno:ext/node/02_require.js:515:14)
```

Sorry if this is covered by other issues.

**Comment by bartlomieju** [comment]
@dsherret can you take a look? I feel this is related to https://github.com/denoland/deno/issues/15826
