### ISSUE TITLE
Run in accordance with the documentation code error ”error: Uncaught Error: Not implemented: isContext“

### ISSUE THREAD

**Issue by dong-lufei** [denoland/deno#17593]
https://deno.land/manual@v1.30.0/advanced/jsx_dom/jsdom

```
import { JSDOM } from "https://esm.sh/jsdom@21.1.0";
import { assert } from "https://deno.land/std@0.175.0/testing/asserts.ts";

const { window: { document } } = new JSDOM(
  `<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello from Deno</title>
  </head>
  <body>
    <h1>Hello from Deno</h1>
    <form>
      <input name="user">
      <button>
        Submit
      </button>
    </form>
  </body>
</html>`,
  {
    url: "https://example.com/",
    referrer: "https://example.org/",
    contentType: "text/html",
    storageQuota: 10000000,
  },
);

const h1 = document.querySelector("h1");
assert(h1);

console.log(h1.textContent);
```
$ deno run -A main.ts
error: Uncaught Error: Not implemented: isContext
  throw new Error(message);
        ^
    at notImplemented (https://deno.land/std@0.175.0/node/_utils.ts:23:9)
    at Object.isContext (https://deno.land/std@0.175.0/node/vm.ts:62:3)
    at new Qme (https://esm.sh/v106/jsdom@21.1.0/deno/jsdom.js:800:91199)
    at E3.createWindow (https://esm.sh/v106/jsdom@21.1.0/deno/jsdom.js:800:88766)
    at new Ty (https://esm.sh/v106/jsdom@21.1.0/deno/jsdom.js:800:106273)
    at file:///E:/test/deno/jsdom-deno/main.ts:4:34

**Comment by lino-levan** [comment]
Duplicate of https://github.com/denoland/deno_std/issues/2667 and I believe at least one other issue I remember seeing a while ago but I can't seem to find it.

**Comment by bartlomieju** [comment]
`node:vm` is now fully supported as of Deno 2.1.
