### ISSUE TITLE
fetch across multiple apps on same domain

### ISSUE THREAD

**Issue by tdillon** [denoland/deno#17627]
I'm attempting to `fetch` various resources on the same domain.  The resources are provided by different applications using different context roots (`app-A` and `app-B` in my examples below).  Each application requires its own authentication.  I'm experiencing an error which feels like a bug in Deno.  Am I doing something wrong?

# Notes

- I don't know how to reproduce outside of my corporate environment
- Executing the exact same code in Firefox or Chrome works

# Error Message

```
error: Uncaught (in promise) TypeError: error sending request for url (https://my-domain/app-B/bar.json): connection error: An existing connection was 
forcibly closed by the remote host. (os error 10054)
const responseAppB = await fetch(`https://my-domain/app-B/bar.json`, {
                     ^
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async file:///C:/.../deno-api-scripting/test.ts:10:22
```

# Deno Version Info

```shell
$ deno --version
deno 1.30.1 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```

# Script That Errors

```typescript
const responseAppA = await fetch(`https://my-domain/app-A/foo.json`, {
    headers: {
        'Authorization': 'Bearer app-a-token',
        'Content-Type': 'application/json',
    }
})

const responseDataAppA = await responseAppA.json()  // 🔴 The next fetch will error if this .json() is executed.

const responseAppB = await fetch(`https://my-domain/app-B/bar.json`, {
    headers: {
        'Authorization': 'Bearer app-b-token',
    }
})

const responseDataAppB = await responseAppB.json()
```

# Script Does Not Error

```typescript
const responseAppA = await fetch(`https://my-domain/app-A/foo.json`, {
    headers: {
        'Authorization': 'Bearer app-a-token',
        'Content-Type': 'application/json',
    }
})

const responseAppB = await fetch(`https://my-domain/app-B/bar.json`, {
    headers: {
        'Authorization': 'Bearer app-b-token',
    }
})

const responseDataAppA = await responseAppA.json()  // 🟢 Everything works when .json() executes after the second fetch.
const responseDataAppB = await responseAppB.json()
```

**Comment by lino-levan** [comment]
Maybe I'm not understanding something but why is the `Content-Type` header being set in the first one? This shouldn't affect anything but /shrug this seems like a weird bug.

**Comment by tdillon** [comment]
> Maybe I'm not understanding something but why is the `Content-Type` header being set in the first one? This shouldn't affect anything but /shrug this seems like a weird bug.

The `Content-Type` header was just a copy/paste hold over.  My real code does more than GETs.  I've removed the `Content-Type` header locally and the issue still exists.  Sorry about that.  Should I update the description to avoid future confusion?

**Comment by lino-levan** [comment]
I don't think it should matter, so I think it's fine.

**Comment by tdillon** [comment]
The issue exists with `1.33.0`.  The stacktrace has one extra level (i.e., `eventLoopTick`).

```shell
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
    at async file:///C:/.../deno-api-scripting/test.ts:10:22
```

**Comment by bartlomieju** [comment]
Took a look at this. The root cause is **HTTP keep-alive connection reuse**, and it reproduces locally:

1. `fetch` A -> server replies with `Connection: keep-alive`.
2. `await a.json()` drains the body, which **returns the connection to the pool** as reusable.
3. `fetch` B grabs that **same pooled connection** and sends on it.
4. The server (e.g. a gateway routing `app-A` vs `app-B` to different backends/auth contexts) **resets** that connection -> `ECONNRESET` ("forcibly closed", os error 10054 on Windows / 54 on macOS).

This also explains the `.json()` ordering quirk exactly:
- Read body A **before** firing B -> connection is idle in the pool -> B reuses the dead connection -> error
- Fire both fetches **before** reading bodies -> A's connection is still "in use", so B opens a **fresh** one -> works

**Good news:** on current Deno this is largely self-healing. reqwest now transparently retries a reset-on-reused-connection on a fresh connection for GET and for POST with a buffered body, so the original example no longer fails for me. The one case that still surfaces the error is a **non-replayable streaming request body** (`body: ReadableStream`, `duplex: "half"`) -- reqwest can't rewind the stream to retry.

**Workaround today:** disable idle connection reuse on a custom client:

```ts
const client = Deno.createHttpClient({ poolMaxIdlePerHost: 0 });
await fetch(urlA, { client });
await fetch(urlB, { client, method: "POST", body /* stream */, duplex: "half" });
```

Each request then gets its own connection, so the reused-then-reset race can't happen. (Note: `Connection: close` as a request header does **not** work -- it's a forbidden header and gets stripped by `fetch`.)

Net: the common cases are already fixed via retry; the remaining gap is streaming request bodies, which can't be safely auto-retried in general. The `poolMaxIdlePerHost: 0` client option sidesteps it.
