### ISSUE TITLE
lsp crashing with a simple import

### ISSUE THREAD

**Issue by Olyno** [denoland/deno#17640]
**Describe the bug**

**To Reproduce**

Trying to import the supabase package from unpkg or esm.sh, it makes in both cases crash the lsp server.

```ts
import { createClient } from 'https://unpkg.com/@supabase/supabase-js@2';

console.log(createClient);
```

Here is the error output:
```
Starting Deno language server...
  version: 1.30.1 (release, x86_64-unknown-linux-gnu)
  executable: /home/Olyno/.deno/bin/deno
Connected to "Visual Studio Code" 1.75.0
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://deno.land
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.30.1
Args: ["/home/Olyno/.deno/bin/deno", "lsp"]

thread 'main' panicked at 'internal error: entered unreachable code', cli/lsp/documents.rs:1455:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 1:10:24 AM] The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

I'm wondering if it's not an issue with organization level imports, because i don't have this issue with the ``http`` module from the ``std`` module.

**Expected behavior**

It shouldn't make it crash.

**Screenshots**

/

**Versions**

vscode: 1.75.0 deno: 1.30.1 extension: v3.17.0

**Comment by sylc** [comment]
I'm using the latest canary and i can still see a similar issue

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.30.2+f8ecd23
Args: ["C:\\Users\\sylva\\.deno\\bin\\deno.EXE", "lsp"]

thread 'main' panicked at 'internal error: entered unreachable code', cli\lsp\documents.rs:1455:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 11:40:44 AM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.30.2+f8ecd23 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\sylva\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.75.0
  Auto-resolved configuration file: "file:///C:/Users/sylva/Documents/Projects/checkin/deno.json"
Setting import map from configuration file: "./import_map.json"
  Resolved import map: "file:///C:/Users/sylva/Documents/Projects/checkin/import_map.json"
Enabling import suggestions for: https://deno.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.30.2+f8ecd23
Args: ["C:\\Users\\sylva\\.deno\\bin\\deno.EXE", "lsp"]

thread 'main' panicked at 'internal error: entered unreachable code', cli\lsp\documents.rs:1455:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 11:40:47 AM] The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

```

**Comment by dsherret** [comment]
Main has been red the past two commits. If you run `deno -V` it will show the commit hash. I would recommend downgrading to `deno upgrade --version 1.30.0` if this affects you.

**Comment by sylc** [comment]
ok thanks.

**Comment by dsherret** [comment]
This is now in the latest canary (CI just passed on main). Should work now with `deno upgrade --canary`

For people with M1 which currently doesn't have canary builds, I recommend downgrading to 1.30.0: `deno upgrade --version 1.30.0`
