### ISSUE TITLE
create-react-app does not run correctly

### ISSUE THREAD

**Issue by ry** [denoland/deno#17669]
```
# deno run -A npm:create-react-app cra-repo

Creating a new React app in /private/tmp/foobar/cra-repo.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...


added 1417 packages in 1m

231 packages are looking for funding
  run `npm fund` for details
error: Uncaught ReferenceError: require is not defined
        const init = require('react-scripts/scripts/init.js');
                     ^
    at file:///private/tmp/foobar/cra-repo/$deno$eval.js:2:22

Aborting installation.
  node  has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Done.
```

**Comment by Antonio476587** [comment]
I have executed the command without the --allow-all (-A) flag, and it stopped after I allowed it to use Deno.Command().spawn()

``` bash
added 1416 packages in 2m

231 packages are looking for funding
  run `npm fund` for details
✅ Granted run access to "/home/theheredero/.deno/bin/deno".
error: Uncaught ReferenceError: require is not defined
        const init = require('react-scripts/scripts/init.js');
                     ^
    at file:///home/theheredero/cra-repo_3/$deno$eval.js:2:22

Aborting installation.
  node  has failed.

Deleting generated file... package.json
Deleting generated file... node_modules
Done.
```

Then I went to the create-react-app file, and [the issue is created here](https://github.com/facebook/create-react-app/blob/d960b9e38c062584ff6cfb1a70e1512509a966e7/packages/create-react-app/createReactApp.js#L484) in the execeuteNodeScript function. It is passing the string to the subprocess that is causing the error.

``` javascript
          `
        const init = require('${packageName}/scripts/init.js');
        init.apply(null, JSON.parse(process.argv[1]));
      `
```

Maybe we can apply the InternalTransformations to the subprocesses, I think it is better than replacing strings with regex.

**Comment by bartlomieju** [comment]
The originally reported error here (`ReferenceError: require is not defined`) is fixed: `require` is now defined in node-compat `-e` eval, so `require('react-scripts/scripts/init.js')` succeeds and execution gets well past the original failure point.

create-react-app still does not complete, but for a separate reason: Deno's node-compat `-e` eval includes a synthetic `$deno$eval` path in `process.argv[1]`, whereas Node inserts no script path for `-e` (argv is `[execPath, ...scriptArgs]`). That off-by-one makes CRA's `JSON.parse(process.argv[1])` read the eval path instead of its JSON payload.

Since the error this issue was filed about is resolved, closing this. The remaining `process.argv` discrepancy is a narrower, one-line-reproducible bug and is better tracked in a fresh focused issue if anyone needs CRA specifically (create-react-app is also deprecated upstream).
