### ISSUE TITLE
Deno Language Server crash with Visual Studio Code

### ISSUE THREAD

**Issue by lviggiani** [denoland/deno#17693]
It happens all the times I start VSCode.
Here is the console output

```
Starting Deno language server...
  version: 1.30.1 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\viggiani\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.75.0
  Auto-resolved configuration file: "file:///C:/Users/viggiani/Projects/wstest/deno.jsonc"
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://deno.land
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.30.1
Args: ["C:\\Users\\viggiani\\.deno\\bin\\deno.EXE", "lsp"]

thread 'main' panicked at 'internal error: entered unreachable code', cli\lsp\documents.rs:1455:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 10:56:49 AM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.30.1 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\viggiani\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.75.0
  Auto-resolved configuration file: "file:///C:/Users/viggiani/Projects/wstest/deno.jsonc"
Enabling import suggestions for: https://deno.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.30.1
Args: ["C:\\Users\\viggiani\\.deno\\bin\\deno.EXE", "lsp"]

thread 'main' panicked at 'internal error: entered unreachable code', cli\lsp\documents.rs:1455:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 10:56:54 AM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.30.1 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\viggiani\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.75.0
  Auto-resolved configuration file: "file:///C:/Users/viggiani/Projects/wstest/deno.jsonc"
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://deno.land
Enabling import suggestions for: https://crux.land
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.30.1
Args: ["C:\\Users\\viggiani\\.deno\\bin\\deno.EXE", "lsp"]

thread 'main' panicked at 'internal error: entered unreachable code', cli\lsp\documents.rs:1455:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 10:56:55 AM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.30.1 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\viggiani\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.75.0
  Auto-resolved configuration file: "file:///C:/Users/viggiani/Projects/wstest/deno.jsonc"
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://deno.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.30.1
Args: ["C:\\Users\\viggiani\\.deno\\bin\\deno.EXE", "lsp"]

thread 'main' panicked at 'internal error: entered unreachable code', cli\lsp\documents.rs:1455:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 10:56:56 AM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.30.1 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\viggiani\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.75.0
  Auto-resolved configuration file: "file:///C:/Users/viggiani/Projects/wstest/deno.jsonc"
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://deno.land
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.30.1
Args: ["C:\\Users\\viggiani\\.deno\\bin\\deno.EXE", "lsp"]

thread 'main' panicked at 'internal error: entered unreachable code', cli\lsp\documents.rs:1455:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 10:56:57 AM] The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by sigmaSd** [comment]
This was fixed in recent version, consider updating to 1.30.3

**Comment by lviggiani** [comment]
Ok, sorry for reporting on outdated package
