### ISSUE TITLE
error: Uncaught (in promise) PermissionDenied: 拒绝访问。 (os error 5)     at async Object.pull (deno:ext/web/06_streams.js:689:29)

### ISSUE THREAD

**Issue by hide-own** [denoland/deno#17700]
Deno 版本信息

```shell
PS C:\Users\king\Desktop\test> deno --version
deno 1.29.1 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```

权限问题

```shell
PS C:\Users\king\Desktop\test> deno run -A test.ts   
error: Uncaught (in promise) PermissionDenied: 拒绝访问。 (os error 5)
    at async Object.pull (deno:ext/web/06_streams.js:689:29)
```

### 文件 test.ts

```ts
if (Deno.env.get("test")) {
    let i = 0
    while (i <100000) {
        i++;
        console.log(i, (new Date).toLocaleTimeString())
    }
    console.log("exited")
} else {
    const tmpFile = Deno.makeTempFileSync({prefix: "zzz.txt"})
    const w1 = Deno.openSync(tmpFile,  {create: true, write: true, append: true});
    const w2 = Deno.openSync("./test2.txt",  {create: true, write: true, append: true});

    addEventListener("unload", () => Deno.removeSync(tmpFile))

    const process = Deno.run({
        cmd: [
            Deno.execPath(),
            "run",
            "--allow-all",
            "--unstable",
            import.meta.url,
        ],
        cwd: Deno.cwd(),
        env: {
            ...Deno.env.toObject(),
            test: "test",
        },
        stdin: 'inherit',
        stdout: w1.rid,
        stderr: w1.rid,
    });

    w2.readable.pipeTo(new WritableStream({
        write: async (chunk, ctr  ) =>   {
            console.log("data:", (new TextDecoder).Decode(chunk))
            await w2.write(chunk)
            return
        }
    }))

    await process.status()
}
```

**Comment by Antonio476587** [comment]
The issue is that you aren't giving the read access option when you are opening  _`w2`_, therefore, when you request the ReadableStream instance, the file descriptors do not match.

``` typescript
const w2 = Deno.openSync("./test2.txt",  {create: true, write: true, append: true});
```
make instead
``` typescript
const w2 = Deno.openSync("./test2.txt",  {create: true, write: true, append: true, read: true});
```

and I recommend you to just use _`append: true`_ instead of _`write: true, append: true`_ , it will have same effect.

**Comment by bartlomieju** [comment]
This is most likely related to spawning a subprocess, if you use `Deno.Command` API instead of `Deno.run` API you should get better error message what goes wrong. Gonna close this one since there's been no feedback on this issue for almost 2 years now.
