### ISSUE TITLE
Deno can panic on import of 'npm:ws:@latest' and similar invalid modules

### ISSUE THREAD

**Issue by bershanskiy** [denoland/deno#17748]
The following line crashed deno:
```js
import 'npm:ws:';
```

### Explanation

This error occurs in `cli/npm/registry.rs` in `get_package_url`. Code extracts package name from 'npm:ws:' as `ws:` and attempts to `self.base_url.join(name).unwrap()`. After `.join()` the URL turns into WebSockets URL without a host, so `.unwrap()` fails.

### Example output
```
anton@anton-XPS-17-9700:~$ RUST_BACKTRACE=full deno
Deno 1.30.3+8b5be96
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> import a from 'npm:ws:';

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.30.3+8b5be96
Args: ["deno"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EmptyHost', cli/npm/registry.rs:461:30
stack backtrace:
   0:     0x560cbe9915ba - std::backtrace_rs::backtrace::libunwind::trace::h34aec3ef6cd8ad7e
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x560cbe9915ba - std::backtrace_rs::backtrace::trace_unsynchronized::h8035d38698d0f7a8
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560cbe9915ba - std::sys_common::backtrace::_print_fmt::hff968f6695a1ba22
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x560cbe9915ba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7eea0efe77acf1ec
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x560cbe9be1ee - core::fmt::write::hc553f17407eb0b48
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/fmt/mod.rs:1208:17
   5:     0x560cbe9881a5 - std::io::Write::write_fmt::h62e5f01a089f48c0
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/io/mod.rs:1682:15
   6:     0x560cbe991385 - std::sys_common::backtrace::_print::h52d116aff3db4cd1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x560cbe991385 - std::sys_common::backtrace::print::h9e7d2f98fb7af075
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x560cbe99317f - std::panicking::default_hook::{{closure}}::hf74999dab2d0a95c
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:267:22
   9:     0x560cbe992ebb - std::panicking::default_hook::hc11ca7d10c44c42f
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:286:9
  10:     0x560cbed47a61 - deno::setup_panic_hook::{{closure}}::h89041d6370fa8b02
  11:     0x560cbe99390d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha7dbb2d260f78172
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/alloc/src/boxed.rs:2032:9
  12:     0x560cbe99390d - std::panicking::rust_panic_with_hook::hdb4da1ae79c845a5
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:692:13
  13:     0x560cbe993689 - std::panicking::begin_panic_handler::{{closure}}::h02b5b35b126d5cf2
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:579:13
  14:     0x560cbe991a6c - std::sys_common::backtrace::__rust_end_short_backtrace::h6c6853376cf416d1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x560cbe993392 - rust_begin_unwind
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
  16:     0x560cbe9bb493 - core::panicking::panic_fmt::hfd9e949092070b66
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
  17:     0x560cbe9bb9a3 - core::result::unwrap_failed::h4d34d8346233eb49
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
  18:     0x560cbea8f2b2 - core::result::Result<T,E>::unwrap::ha68bf21dd1a70b73
  19:     0x560cbec9c247 - deno::npm::registry::RealNpmRegistryApiInner::get_package_url::hc3bc1b5be27d4875
  20:     0x560cbec99a7d - deno::npm::registry::RealNpmRegistryApiInner::maybe_package_info::{{closure}}::ha2767fbd432706bc
  21:     0x560cbec989cd - <deno::npm::registry::RealNpmRegistryApi as deno::npm::registry::NpmRegistryApi>::maybe_package_info::{{closure}}::hf17df452ab568c0d
  22:     0x560cbec97bc2 - deno::npm::registry::NpmRegistryApi::package_info::{{closure}}::h60c159289e26c8db
  23:     0x560cbecadf87 - deno::npm::resolution::NpmResolution::add_package_reqs_to_snapshot::{{closure}}::{{closure}}::h5f7e10f70d52123a
  24:     0x560cbead46fe - tokio::runtime::task::raw::poll::h712f4ec87c69f80d
  25:     0x560cbe9f8180 - deno_runtime::tokio_util::run_local::h51ab2b12f83c89c0
  26:     0x560cbed47e66 - deno::main::h8dec71d8dc0b74be
  27:     0x560cbea2f777 - std::sys_common::backtrace::__rust_begin_short_backtrace::h29755b18d2006b32
  28:     0x560cbea359c1 - std::rt::lang_start::{{closure}}::h9a2364e579277711
  29:     0x560cbe97d7ec - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h9ab31282e87f134a
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:606:13
  30:     0x560cbe97d7ec - std::panicking::try::do_call::h42ddf5b01d0b4bc7
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  31:     0x560cbe97d7ec - std::panicking::try::hfb70320d7386c61a
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  32:     0x560cbe97d7ec - std::panic::catch_unwind::h978c9edbad2bb4d4
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  33:     0x560cbe97d7ec - std::rt::lang_start_internal::{{closure}}::h04ede5bd2f26b553
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:48
  34:     0x560cbe97d7ec - std::panicking::try::do_call::ha6b9da35a0885c93
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  35:     0x560cbe97d7ec - std::panicking::try::h3325520cab3a642e
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  36:     0x560cbe97d7ec - std::panic::catch_unwind::h160beec6f047175b
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  37:     0x560cbe97d7ec - std::rt::lang_start_internal::h79190e3a877a769d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:20
  38:     0x560cbedaa875 - main
  39:     0x7fa575988d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  40:     0x7fa575988e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  41:     0x560cbd87e029 - _start
  42:                0x0 - <unknown>
```

**Comment by bershanskiy** [comment]
This reproduces reliably within Dark Reader (this is non-reduced test case):

Steps:
1. check out Dark Reader `git clone https://github.com/darkreader/darkreader.git`
2. deno run darkreader/tasks/build.js --release

Together with this patch it produces nice output:
Patch:
```diff
diff --git a/cli/npm/registry.rs b/cli/npm/registry.rs
index fea6996ab..dd98b8b5d 100644
--- a/cli/npm/registry.rs
+++ b/cli/npm/registry.rs
@@ -458,6 +458,7 @@ impl RealNpmRegistryApiInner {
   }
 
   fn get_package_url(&self, name: &str) -> Url {
+    log::warn!("HERE {} {:?}", &name, self.base_url.join(name));
     self.base_url.join(name).unwrap()
   }
```

Output:
```
HERE @rollup/plugin-node-resolve: Ok(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("registry.npmjs.org")), port: None, path: "/@rollup/plugin-node-resolve:", query: None, fragment: None })
HERE @rollup/plugin-replace: Ok(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("registry.npmjs.org")), port: None, path: "/@rollup/plugin-replace:", query: None, fragment: None })
HERE @rollup/plugin-typescript2: Ok(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("registry.npmjs.org")), port: None, path: "/@rollup/plugin-typescript2:", query: None, fragment: None })
HERE @rollup/plugin-typescript: Ok(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("registry.npmjs.org")), port: None, path: "/@rollup/plugin-typescript:", query: None, fragment: None })
HERE chokidar: Ok(Url { scheme: "chokidar", cannot_be_a_base: true, username: "", password: None, host: None, port: None, path: "", query: None, fragment: None })
HERE chokidar: Ok(Url { scheme: "chokidar", cannot_be_a_base: true, username: "", password: None, host: None, port: None, path: "", query: None, fragment: None })
HERE less Ok(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("registry.npmjs.org")), port: None, path: "/less", query: None, fragment: None })
HERE prettier: Ok(Url { scheme: "prettier", cannot_be_a_base: true, username: "", password: None, host: None, port: None, path: "", query: None, fragment: None })
HERE prettier: Ok(Url { scheme: "prettier", cannot_be_a_base: true, username: "", password: None, host: None, port: None, path: "", query: None, fragment: None })
HERE rollup: Ok(Url { scheme: "rollup", cannot_be_a_base: true, username: "", password: None, host: None, port: None, path: "", query: None, fragment: None })
HERE rollup: Ok(Url { scheme: "rollup", cannot_be_a_base: true, username: "", password: None, host: None, port: None, path: "", query: None, fragment: None })
HERE typescript: Ok(Url { scheme: "typescript", cannot_be_a_base: true, username: "", password: None, host: None, port: None, path: "", query: None, fragment: None })
HERE typescript: Ok(Url { scheme: "typescript", cannot_be_a_base: true, username: "", password: None, host: None, port: None, path: "", query: None, fragment: None })
HERE ws: Err(EmptyHost)

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.30.3
Args: ["deno/target/debug/deno", "run", "darkreader/tasks/build.js", "--release"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EmptyHost', cli/npm/registry.rs:462:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by GJZwiers** [comment]
It probably should not panic but the import syntax is incorrect, it should be `npm:ws@latest` instead of `npm:ws:@latest`

**Comment by GJZwiers** [comment]
Oh I see, it is interpreting it as a websocket URL `ws:` instead of an `npm:` URL.

I'm not familiar with the spec but I think `npm:ws:@latest` might be an invalid URL? If so Deno should probably throw an error instead of the panic

**Comment by bershanskiy** [comment]
I'm not sure whether `npm:ws:@latest` is a valid URL or not, but I do not think it is a valid npm package name.

Specifically, [official npm validator states](https://github.com/npm/validate-npm-package-name#invalid-names) that these names are invalid: `"excited!"`, `" leading-space:and:weirdchars"`. This is because npm bans all not URL-safe characters. I ran validator on `ws:` and this name was never valid.

I think, it is reasonable to validate `npm` package names according to the official criteria even before attempting to construct the URL (thus avoiding the whole class of issues).

**Comment by bershanskiy** [comment]
The same crash can be achieved with other protocols and package names like like `npm:wss:@latest`.
