### ISSUE TITLE
denols panicked

### ISSUE THREAD

**Issue by alarbada** [denoland/deno#17746]
I received a panic using nvim with lspconfig.

Logs:

```

[ERROR][2023-02-12 11:24:21] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Error converting specifier settings (file:///home/guillem/projects/typescript/lol/src/views/mod.tsx): Error converting specifier settings: invalid type: null, expected struct SpecifierSettings
" [ERROR][2023-02-12 11:24:34] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Error converting specifier settings (file:///home/guillem/projects/typescript/lol/src/views/mod.tsx): Error converting specifier settings: invalid type: null, expected struct SpecifierSettings
" [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" 'Starting Deno language server...
 version: 1.30.3 (release, x86_64-unknown-linux-gnu)
 executable: /home/guillem/.deno/bin/deno
Connected to "Neovim" 0.8.1
 Auto-resolved configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" 'Setting import map defined in configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
 Resolved import map: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Server ready.
" [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "failed to update settings: invalid type: null, expected struct WorkspaceSettings
" [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" ' Auto-resolved configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
Setting import map defined in configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
 Resolved import map: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "failed to update settings: invalid type: null, expected struct WorkspaceSettings
" [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" ' Auto-resolved configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" 'Setting import map defined in configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
 Resolved import map: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Error converting specifier settings (file:///home/guillem/projects/typescript/lol/src/server.tsx): Error converting specifier settings: invalid type: null, expected struct SpecifierSettings
" [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Error converting specifier settings (file:///home/guillem/projects/typescript/lol/src/views/mod.tsx): Error converting specifier settings: invalid type: null, expected struct SpecifierSettings
" [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Error converting specifier settings (file:///home/guillem/projects/typescript/lol/src/views/shared.tsx): Error converting specifier settings: invalid type: null, expected struct SpecifierSettings
" [ERROR][2023-02-12 11:30:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Error converting specifier settings (file:///home/guillem/projects/typescript/lol/src/views/icons.tsx): Error converting specifier settings: invalid type: null, expected struct SpecifierSettings
" [ERROR][2023-02-12 11:31:15] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.30.3
Args: [\"deno\", \"lsp\"]

thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/alloc/src/string.rs:1819:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
" [START][2023-02-12 11:32:59] LSP logging initiated [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Starting Deno language server...
" [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" ' version: 1.30.3 (release, x86_64-unknown-linux-gnu)
 executable: /home/guillem/.deno/bin/deno
Connected to "Neovim" 0.8.1
' [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" ' Auto-resolved configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" 'Setting import map defined in configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
 Resolved import map: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Server ready.
" [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "failed to update settings: invalid type: null, expected struct WorkspaceSettings
" [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" ' Auto-resolved configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
Setting import map defined in configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
 Resolved import map: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "failed to update settings: invalid type: null, expected struct WorkspaceSettings
" [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" ' Auto-resolved configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" 'Setting import map defined in configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
 Resolved import map: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:32:59] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Error converting specifier settings (file:///home/guillem/projects/typescript/lol/src/views/mod.tsx): Error converting specifier settings: invalid type: null, expected struct SpecifierSettings
" [ERROR][2023-02-12 11:33:01] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.30.3
Args: [" [ERROR][2023-02-12 11:33:01] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "\"deno\", \"lsp\"]

thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/alloc/src/string.rs:1819:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
" [ERROR][2023-02-12 11:33:45] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Starting Deno language server...
" [ERROR][2023-02-12 11:33:45] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" ' version: 1.30.3 (release, x86_64-unknown-linux-gnu)
 executable: /home/guillem/.deno/bin/deno
Connected to "Neovim" 0.8.1
 Auto-resolved configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:33:45] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" 'Setting import map defined in configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
 Resolved import map: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:33:45] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Server ready.
" [ERROR][2023-02-12 11:33:46] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "failed to update settings: invalid type: null, expected struct WorkspaceSettings
" [ERROR][2023-02-12 11:33:46] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" ' Auto-resolved configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
Setting import map defined in configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
 Resolved import map: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:33:46] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "failed to update settings: invalid type: null, expected struct WorkspaceSettings
" [ERROR][2023-02-12 11:33:46] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" ' Auto-resolved configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
Setting import map defined in configuration file: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
 Resolved import map: "file:///home/guillem/projects/typescript/lol/deno.jsonc"
' [ERROR][2023-02-12 11:33:46] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Error converting specifier settings (file:///home/guillem/projects/typescript/lol/static/main.js): Error converting specifier settings: invalid type: null, expected struct SpecifierSettings
" [ERROR][2023-02-12 11:34:19] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Error converting specifier settings (file:///home/guillem/projects/typescript/lol/static/main.js): Error converting specifier settings: invalid type: null, expected struct SpecifierSettings
" [ERROR][2023-02-12 11:34:25] .../vim/lsp/rpc.lua:733 "rpc" "deno" "stderr" "Error converting specifier settings (file:///home/guillem/projects/typescript/lol/src/server.tsx): Error converting specifier settings: invalid type: null, expected struct SpecifierSettings
"
```

I'm not sure how did I manage to make that panic, I'm sorry. For additional context, I was toying with the nvim lspconfig commands :LspRestart, :LspStop, :LspStart

An additional bug is that those commands don't work, and I don't know why.

**Comment by not-rusty** [comment]
Reported the denols restarting but in #17747

**Comment by nayeemrmn** [comment]
@alarbada Do you still get this in 1.37.0? If so, please share your vscode settings and file structure.

**Comment by nayeemrmn** [comment]
Actually looking at the logs I think this was fixed by #20358. Closing for now -- please report if the issue persists.

**Comment by vuau** [comment]
I'm facing a similar issue with LSP. Lots of stderr in the log. I'm using deno 1.37.1

```
[START][2023-09-29 11:54:23] LSP logging initiated
[ERROR][2023-09-29 11:54:23] .../vim/lsp/rpc.lua:734	"rpc"	"/home/au/.deno/bin/deno"	"stderr"	'Starting Deno language server...\n  version: 1.31.0 (release, x86_64-unknown-linux-gnu)\n  executable: /home/au/.deno/bin/deno\nConnected to "Neovim" 0.9.2\n  Auto-resolved configuration file: "file:///home/au/Work/seagull/deno.jsonc"\n'
[ERROR][2023-09-29 11:54:23] .../vim/lsp/rpc.lua:734	"rpc"	"/home/au/.deno/bin/deno"	"stderr"	'Setting import map from workspace settings: "./import_map.json"\nWarning: Import map "./import_map.json" configured in "file:///home/au/Work/seagull/deno.jsonc" being ignored due to an import map being explicitly configured in workspace settings.\n  Resolved import map: "file:///home/au/Work/seagull/import_map.json"\n'
[ERROR][2023-09-29 11:54:23] .../vim/lsp/rpc.lua:734	"rpc"	"/home/au/.deno/bin/deno"	"stderr"	"Server ready.\n"
[ERROR][2023-09-29 11:54:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/au/.deno/bin/deno"	"stderr"	"Enabling import suggestions for: https://deno.land\n"
[ERROR][2023-09-29 11:54:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/au/.deno/bin/deno"	"stderr"	"Enabling import suggestions for: https://x.nest.land\n"
[ERROR][2023-09-29 11:54:25] .../vim/lsp/rpc.lua:734	"rpc"	"/home/au/.deno/bin/deno"	"stderr"	"Download https://x.nest.land/.well-known/deno-import-intellisense.json\n"
[ERROR][2024-09-29 11:54:26] .../vim/lsp/rpc.lua:734	"rpc"	"/home/au/.deno/bin/deno"	"stderr"	"Download https://intellisense.nest.land/deno-import-intellisense.json\n"
```

**Comment by nayeemrmn** [comment]
> I'm facing a similar issue with LSP. Lots of stderr in the log. I'm using deno 1.37.1

@vuau Fortunately none of those are errors, they're regular startup logs formatted that way by nvim because they're printed as diagnostics in stderr. Well, one of them is a network error for fetching a registry config but that shouldn't be a persistent issue with the LSP.

**Comment by vuau** [comment]
> @vuau Fortunately none of those are errors, they're regular startup logs formatted that way by nvim because they're printed as diagnostics in stderr. Well, one of them is a network error for fetching a registry config but that shouldn't be a persistent issue with the LSP.

Thanks. So, they are normal logs. It's weird that LSP stopped working since I upgraded deno from 1.36 to the latest 1.37.1 few days ago (though my nvim config is still the same, copied from https://docs.deno.com/runtime/manual/getting_started/setup_your_environment#neovim-06-using-the-built-in-language-server)
