### ISSUE TITLE
Uncaught TypeError: core.runMicrotasks is not a function

### ISSUE THREAD

**Issue by vikaskaliramna** [denoland/deno#17742]
I was porting a project from Node to Deno, it works perfectly fine but shows this error in the end for no reason. Doesn't affect my code or it's output.

My project uses `node/path`, `node/fs` and `node/process` as it's dependencies at some locations.

```shell
error: Uncaught TypeError: core.runMicrotasks is not a function
    core.runMicrotasks();
         ^
    at processTicksAndRejections (https://deno.land/std@0.149.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.149.0/node/process.ts:276:7
    at innerInvokeEventListeners (internal:ext/web/02_event.js:776:9)
    at invokeEventListeners (internal:ext/web/02_event.js:816:7)
    at dispatch (internal:ext/web/02_event.js:685:11)
    at dispatchEvent (internal:ext/web/02_event.js:1066:14)
    at [internal:cli\worker.rs:90:39]:1:1
```

**Comment by petamoriken** [comment]
Probably increasing the version of deno_std will solve this issue. `Deno.core` is removed by #16881

**Comment by vikaskaliramna** [comment]
Thanks :D
The Google search recommended Deno's older version of standard library on top. I opened it and copied the link without checking the version.
