### ISSUE TITLE
hello_runtime.rs failed to operate as expected !

### ISSUE THREAD

**Issue by lifegit** [denoland/deno#17789]
`deno / runtime / examples / hello_runtime.rs` Unable to execute snapshot();

repo: [hello_runtime.rs](https://github.com/lifegit/deno/blob/fixbug/runtime/examples/hello_runtime.rs)

error:
```<unknown>:10: Uncaught TypeError: Cannot read properties of undefined (reading 'ops')
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', core/runtime.rs:986:64
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
   3: core::option::Option<T>::unwrap
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:778:21
   4: deno_core::runtime::JsRuntime::snapshot
             at ./core/runtime.rs:986:15
   5: intervals_mod3::main::{{closure}}
             at ./runtime/examples/intervals_mod3.rs:80:18
   6: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/workspace/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.24.2/src/runtime/park.rs:283:63
   7: tokio::runtime::coop::with_budget
             at /Users/workspace/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.24.2/src/runtime/coop.rs:102:5
   8: tokio::runtime::coop::budget
             at /Users/workspace/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.24.2/src/runtime/coop.rs:68:5
   9: tokio::runtime::park::CachedParkThread::block_on
             at /Users/workspace/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.24.2/src/runtime/park.rs:283:31
  10: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/workspace/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.24.2/src/runtime/context.rs:315:13
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/workspace/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.24.2/src/runtime/scheduler/multi_thread/mod.rs:66:9
  12: tokio::runtime::runtime::Runtime::block_on
             at /Users/workspace/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.24.2/src/runtime/runtime.rs:284:45
  13: intervals_mod3::main
             at ./runtime/examples/intervals_mod3.rs:81:3
  14: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bartlomieju** [comment]
We can look into the issue after 1.31 is released and changes to `deno_core` stop being so frequent

**Comment by bartlomieju** [comment]
I can no longer reproduce it.
