### ISSUE TITLE
NPM error: 'import', and 'export' cannot be used outside of module code at ...

### ISSUE THREAD

**Issue by aW4KeNiNG** [denoland/deno#17784]
Hi.

I'm trying to use the [Kobalte](https://github.com/kobaltedev/kobalte) lib on a Deno project but I'm getting the next error:

```
error: 'import', and 'export' cannot be used outside of module code at file:///C:/Users/aw4ke/AppData/Local/deno/npm/registry.npmjs.org/@kobalte/core/0.6.0/dist/esm/index.js:1:1

  import { access, accessWith, getDocument, EventKey, getActiveElement, contains, ...

```

You can replicate the issue with the next code:

```typescript
import { Button } from 'npm:@kobalte/core';

console.log(typeof Button);
```

and ` deno run -A .\test.ts`

There is a similar opened issue (#17231) using another lib , but I have tried esm.sh, skypack.dev, etc... and it doesn't work either.

Any help is appreciated.

**Comment by axetroy** [comment]
same with me, and here is a more simple entry point definition.

```json
  "main": "dist/cjs/index.js",
  "exports": {
    ".": {
      "require": "./dist/cjs/index.js",
      "import": "./dist/esm/index.js"
    }
  },
```

```js
import { FileSystemWalker } from "npm:file-system-walker@1.0.12";
```

**Comment by GJZwiers** [comment]
I did some debugging, the problem appears to be that while the right ESM entry point is used, the closest `package.json` does not have a `type` field specified, causing Deno to apply CommonJS module resolution https://github.com/denoland/deno/blob/da5b5d4688f03e578565966b1c0634a187f7729d/cli/node/mod.rs#L473-L482

**Comment by Swimburger** [comment]
> I did some debugging, the problem appears to be that while the right ESM entry point is used, the closest `package.json` does not have a `type` field specified, causing Deno to apply CommonJS module resolution
> 
> https://github.com/denoland/deno/blob/da5b5d4688f03e578565966b1c0634a187f7729d/cli/node/mod.rs#L473-L482

We're running into this with our own NPM module we maintain.
Does this mean module authors should specify `"type": "module"`? 
Would that cause other incompatibility issues with other runtimes?

**Comment by bartlomieju** [comment]
Running the reproduction results in:
```
deno run bar.ts
error: Uncaught SyntaxError: The requested module 'solid-js/web' does not provide an export named 'use'
    at <anonymous> (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/@kobalte/core/0.13.7/dist/chunk/DIKSCYO5.js:3:10)
```
which is the same error you get in Node.js:
```
file:///Users/ib/dev/scratch_express/node_modules/@kobalte/core/dist/chunk/DIKSCYO5.js:3
import { use, spread, mergeProps, insert, createComponent, effect, style, setAttribute, template } from 'solid-js/web';
         ^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'use'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:180:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:263:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v23.2.0
```
