### ISSUE TITLE
`integration::run::worker_close_nested` is flaky

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#17801]
```
failures:

---- integration::run::worker_close_nested stdout ----
deno_exe path /Users/runner/work/deno/deno/target/debug/deno
command /Users/runner/work/deno/deno/target/debug/deno run --quiet --reload --allow-read run/worker_close_nested.js
command cwd "/Users/runner/work/deno/deno/cli/tests/testdata"
output path /Users/runner/work/deno/deno/cli/tests/testdata/run/worker_close_nested.js.out
thread 'integration::run::worker_close_nested' panicked at 'assertion failed: `(left == right)`: at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5

Diff < left / right > :
 Starting the main thread
 Starting the parent worker
>Starting the child worker
 About to close
 Closing
<Starting the child worker
 

', /Users/runner/work/deno/deno/test_util/src/builders.rs:600:7
stack backtrace:
   0:        0x10fefc596 - std::backtrace_rs::backtrace::libunwind::trace::hc9dfa8fe361e3efc
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10fefc596 - std::backtrace_rs::backtrace::trace_unsynchronized::h54fa2028ee859793
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10fefc596 - std::sys_common::backtrace::_print_fmt::h56162487b269e1b0
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10fefc596 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0a1c410dd2eebc30
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10ff1c1ba - core::fmt::write::hfa389e524187f2c6
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:        0x10fef5c7c - std::io::Write::write_fmt::h8747775546b87593
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:        0x10fefc37a - std::sys_common::backtrace::_print::h5b3935a85ecb7241
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x10fefc37a - std::sys_common::backtrace::print::hc90b083c930997af
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x10fefec33 - std::panicking::default_hook::{{closure}}::h75efc5c6aebec0e0
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:        0x10fefe917 - std::panicking::default_hook::hc8ee2f0ee4fbe744
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:283:9
  10:        0x10e58d299 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h193af6945c130c12
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
  11:        0x10e58d299 - test::test_main::{{closure}}::h7fff73895f91ba46
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:135:21
  12:        0x10feff399 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h246eb8d2cc68ecae
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
  13:        0x10feff399 - std::panicking::rust_panic_with_hook::h479ead1480e59d8d
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
  14:        0x10feff134 - std::panicking::begin_panic_handler::{{closure}}::h69ffc77690b7f126
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
  15:        0x10fefca38 - std::sys_common::backtrace::__rust_end_short_backtrace::h7fbeef7420a96564
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
  16:        0x10fefedfd - rust_begin_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  17:        0x10ff3c4e3 - core::panicking::panic_fmt::h9b5d807e24bcaaed
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  18:        0x10e5151b7 - test_util::builders::TestCommandOutput::inner_assert_matches_text::hfe09c4191ae14dcf
  19:        0x10e51476c - test_util::builders::TestCommandOutput::inner_assert_matches_file::h20e4cb8306128d16
  20:        0x10e5144de - test_util::builders::TestCommandOutput::assert_matches_file::hd1203d1d919fe812
  21:        0x10e32ce00 - integration_tests::integration::run::worker_close_nested::hff8ecf730b7d9da4
  22:        0x10e32cbb5 - integration_tests::integration::run::worker_close_nested::{{closure}}::hd46130a315c75d48
  23:        0x10e495f58 - core::ops::function::FnOnce::call_once::hfa07c7e56a54c4b1
  24:        0x10e591f02 - core::ops::function::FnOnce::call_once::h7b38f0ebf139547d
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
  25:        0x10e591f02 - test::__rust_begin_short_backtrace::hc4abc8aba46e68e5
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:656:18
  26:        0x10e563e11 - test::run_test::{{closure}}::h180106ca287e913b
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:647:30
  27:        0x10e563e11 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc57d4a1c0a034f0d
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
  28:        0x10e590b6c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h48c9211d80130008
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  29:        0x10e590b6c - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2eecf99771cbe25c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panic/unwind_safe.rs:271:9
  30:        0x10e590b6c - std::panicking::try::do_call::ha85e55508d8728b9
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  31:        0x10e590b6c - std::panicking::try::ha43845960313057b
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  32:        0x10e590b6c - std::panic::catch_unwind::h95aa774e3476a286
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  33:        0x10e590b6c - test::run_test_in_process::h1b0ecbe225c20e34
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:679:27
  34:        0x10e590b6c - test::run_test::run_test_inner::{{closure}}::h554ecfa54d058608
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:573:39
  35:        0x10e55e68b - test::run_test::run_test_inner::{{closure}}::hf3f343e208f66252
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:600:37
  36:        0x10e55e68b - std::sys_common::backtrace::__rust_begin_short_backtrace::h1d0c4ba44e8beeda
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:121:18
  37:        0x10e563ea3 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hdf6dd9b600fdb20f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/thread/mod.rs:558:17
  38:        0x10e563ea3 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h56a3fcca401ca806
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panic/unwind_safe.rs:271:9
  39:        0x10e563ea3 - std::panicking::try::do_call::hbdeb9fa6e5388b0b
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  40:        0x10e563ea3 - std::panicking::try::h575e4a35e5d4b971
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  41:        0x10e563ea3 - std::panic::catch_unwind::h1f343331f0e309f5
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  42:        0x10e563ea3 - std::thread::Builder::spawn_unchecked_::{{closure}}::hf2e4a821eb495542
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/thread/mod.rs:557:30
  43:        0x10e563ea3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hcf71d85cb62948e4
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
  44:        0x10ff049e7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfefc519d8e3fd603
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  45:        0x10ff049e7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h76b0afcd73b86311
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  46:        0x10ff049e7 - std::sys::unix::thread::Thread::new::thread_start::hb363cecb84f4c49a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  47:     0x7ff81a86e4e1 - __pthread_start


failures:
    integration::run::worker_close_nested
```

**Comment by dsherret** [comment]
https://github.com/denoland/deno/actions/runs/9071262640/job/24924629399

```
---- run::worker_close_nested stdout ----
command C:\a\deno\deno\target\release\deno.exe run --quiet --reload --allow-read run/worker_close_nested.js
command cwd C:\a\deno\deno\tests\testdata
output path C:\a\deno\deno\tests\testdata\run/worker_close_nested.js.out
thread 'run::worker_close_nested' panicked at tests\integration\run_tests.rs:2372:1:
assertion failed: `(left == right)`

Diff < left / right > :
 Starting the main thread
 Starting the parent worker
>Starting the child worker
 About to close
 Closing
<Starting the child worker
```
