### ISSUE TITLE
Uncaught TypeError: Cannot read property 'rid' of undefined

### ISSUE THREAD

**Issue by zy445566** [denoland/deno#1782]
I get an error when I run this code.
```js
import * as deno from "deno";
let process =new deno.Process();
console.log(process)
```
error info:
```sh
Uncaught TypeError: Cannot read property 'rid' of undefined
    at Process (deno/js/process.ts:44:20)
    at /Users/noder/Documents/GitHub/node2deno/test/test.js:2:14
```

**Comment by bartlomieju** [comment]
Hey @zy445566! You shouldn't be instatiating `Process` by hand. `deno.Process` is constructed automatically when you do: `deno.run({ ... })` - there's no documentation for this yet (#1715), but I'll add it tonight.

**Comment by zy445566** [comment]
sorry,I made a mistake.
right code:
```js
import * as deno from "deno";
let process = deno.run({args:['deno','test2.js'],cwd:'/test'});
console.log(process)
```
