### ISSUE TITLE
Node compatibility: "Uncaught Error: Not implemented: crypto.Cipheriv"

### ISSUE THREAD

**Issue by matt1** [denoland/deno#17848]
**Describe the bug**

Trying to use https://github.com/codetheweb/tuyapi

Attempting to connect to a device using protocol v3.3 triggers this stack-trace

    at notImplemented (https://deno.land/std@0.170.0/node/_utils.ts:23:9)
    at new Cipheriv (https://deno.land/std@0.170.0/node/internal/crypto/cipher.ts:140:5)
    at Object.createCipheriv (https://deno.land/std@0.170.0/node/crypto.ts:187:10)
    at F._encryptPre34 (https://esm.sh/v102/tuyapi@7.5.1/deno/tuyapi.js:2:1741)
    at F.encrypt (https://esm.sh/v102/tuyapi@7.5.1/deno/tuyapi.js:2:1699)
    at C._encodePre34 (https://esm.sh/v102/tuyapi@7.5.1/deno/tuyapi.js:2:8787)
    at C.encode (https://esm.sh/v102/tuyapi@7.5.1/deno/tuyapi.js:2:8678)
    at v.get (https://esm.sh/v102/tuyapi@7.5.1/deno/tuyapi.js:2:11788)
    at v._finishConnect (https://esm.sh/v102/tuyapi@7.5.1/deno/tuyapi.js:2:14825)
    at Socket.<anonymous> (https://esm.sh/v102/tuyapi@7.5.1/deno/tuyapi.js:2:16523)

**Steps to Reproduce**

Bit awkward as you need a v3.3 physical "smart" device (e.g. a smart lightbulb).  This is reliably triggered using the "basic usage" example in https://github.com/codetheweb/tuyapi

**Expected behavior**

crypto.Cipheriv implemented

**Environment**

$ deno --version
deno 1.29.3 (release, aarch64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4

**Comment by JAForbes** [comment]
If it helps I hit the same issue with cryptr, easy repro:

```typescript
import Cryptr from "https://esm.sh/cryptr@6.2.0";

const cryptr = new Cryptr('secret')
cryptr.encrypt('test') // Uncaught Error: Not implemented: crypto.Cipheriv
```

**Comment by bartlomieju** [comment]
This is being worked on in #18091

**Comment by kt3k** [comment]
Reopened this issue as tuyapi module uses `'aes-128-ecb'` algorithm, which is not yet supported by #18091
