### ISSUE TITLE
Not implemented: crypto.generateKeyPairSync error with mineflayer

### ISSUE THREAD

**Issue by link-discord** [denoland/deno#17849]
**Describe the bug**

Using mineflayer from npm causes a "not implemented" error with the crypto module from the node compatibility layer

**Steps to Reproduce**

Running the code in this `index.ts` file
```js
import mineflayer from 'npm:mineflayer'

const bot = mineflayer.createBot({
    username: 'use any value here',
    host: 'localhost',
    auth: 'microsoft'
})

bot.on('login', () => {
    console.log('Succesfully logged in!')
})
```

Results in this error
```js
% deno run --allow-all index.ts
Error: Not implemented: crypto.generateKeyPairSync
    at notImplemented (https://deno.land/std@0.164.0/node/_utils.ts:23:9)
    at Object.generateKeyPairSync (https://deno.land/std@0.164.0/node/internal/crypto/keygen.ts:662:3)
    at MicrosoftAuthFlow.initTokenManagers (file:///C:/Users/Link/AppData/Local/deno/npm/registry.npmjs.org/prismarine-auth/1.7.0/src/MicrosoftAuthFlow.js:66:28)
    at new MicrosoftAuthFlow (file:///C:/Users/Link/AppData/Local/deno/npm/registry.npmjs.org/prismarine-auth/1.7.0/src/MicrosoftAuthFlow.js:33:10)
    at Object.authenticate (file:///C:/Users/Link/AppData/Local/deno/npm/registry.npmjs.org/minecraft-protocol/1.36.1/src/client/microsoftAuth.js:16:20)
    at Object.createClient (file:///C:/Users/Link/AppData/Local/deno/npm/registry.npmjs.org/minecraft-protocol/1.36.1/src/createClient.js:46:23)
    at Object.createBot (file:///C:/Users/Link/AppData/Local/deno/npm/registry.npmjs.org/mineflayer/4.5.1/lib/loader.js:94:35)
    at file:///C:/Users/Link/OneDrive/Documents/minecraft/bots/deno/index.ts:3:12
```

Cause of this bug is this line that is used inside a dependency of the package

```js
const keyPair = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' })
```

The error triggers when the `createBot` method has this option
```js
auth: 'microsoft'
```

**Expected behavior**

```js
% node index.ts
Succesfully logged in!
```

**Environment**

- OS: Windows 11
- deno version: 1.28.0
- std version: 0.164.0

**Comment by littledivy** [comment]
We're tracking all missing APIs from `node:crypto` in https://github.com/denoland/deno/issues/18455. Closing.
