### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by watzon** [denoland/deno#17854]
**Describe the bug**

This is happening while using `bullmq` with the new npm imports. (`import { Queue } from 'npm:bullmq';`) Occasionally something happens in the background that calls `Worker.addListener` which calls out to the node/_events.mjs shim and crashes the program. Upon inspection there are two places in that file that call a method on `process`, even though I'm pretty sure `process` doesn't exist in Deno.

```
Error in middleware while handling update 276535518 ReferenceError: process is not defined
    at _addListener (https://deno.land/std@0.174.0/node/_events.mjs:464:7)
    at Worker.addListener (https://deno.land/std@0.174.0/node/_events.mjs:478:10)
    at Worker.on (file:///home/watzon/.cache/deno/npm/registry.npmjs.org/bullmq/3.5.11/dist/cjs/classes/worker.js:94:15)
    at file:///home/watzon/Projects/personal/pixeldreams/src/commands/dream.ts:268:22
    at async https://deno.land/x/grammy@v1.13.1/composer.ts:144:13
    at async https://deno.land/x/grammy@v1.13.1/composer.ts:141:9
    at async https://deno.land/x/grammy@v1.13.1/composer.ts:663:13
    at async https://deno.land/x/grammy@v1.13.1/composer.ts:144:13
    at async https://deno.land/x/grammy@v1.13.1/composer.ts:141:9
    at async https://deno.land/x/grammy@v1.13.1/composer.ts:144:13
```

**Steps to Reproduce**

Haven't been able to find a reproducible example yet. It happens sporadically for me.

**Expected behavior**

I'd think nothing in the standard library should be referencing process.

**Environment**

- OS: Fedora 36
- deno version: 1.3.0
- std version: 0.174.0

**Comment by bartlomieju** [comment]
This problem will be fixes in Deno v1.31.

**Comment by anasouardini** [comment]
Is it not fixed, or is this a different error?

### deno version:
```bash
╰─> -_- % deno --version
deno 1.36.4 (release, x86_64-unknown-linux-gnu)
v8 11.6.189.12
typescript 5.1.6
```

### Error:
```bash
╰─> -_- % deno run --allow-all index.ts
error: Uncaught TypeError: Cannot read properties of undefined (reading 'argv')
  length: process.argv.length,
                  ^
    at file:///home/venego/home/scripts/installer/installer.ts:706:19
```

### Source code:
```bash
const args = {
  length: process.argv.length,
  option: process.argv[1],
  ...
```
