### ISSUE TITLE
cowsay errors when using a local node-modules-dir

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17890]
Tested in 1.30.3 and main:

```
> deno run -A --node-modules-dir npm:cowsay hi
error: Uncaught TypeError: require(...).usage is not a function
    at Object.<anonymous> (file:///V:/scratch-vue/vite-project/node_modules/.deno/cowsay@1.5.0/node_modules/cowsay/cli.js:2:3)
    at Object.<anonymous> (file:///V:/scratch-vue/vite-project/node_modules/.deno/cowsay@1.5.0/node_modules/cowsay/cli.js:84:4)
    at Module._compile (internal:ext/node/02_require.js:747:36)
    at Object.Module._extensions..js (internal:ext/node/02_require.js:780:12)
    at Module.load (internal:ext/node/02_require.js:658:34)
    at Function.Module._load (internal:ext/node/02_require.js:515:14)
    at loadCjsModule ([internal:cli\node\mod.rs:473:30]:5:42)
    at [internal:cli\node\mod.rs:473:30]:6:7
```

**Comment by kt3k** [comment]
Removing `!usesLocalNodeModulesDir` condition from [here](https://github.com/denoland/deno/blob/b15f9e60a040e2e450e7ca9971a5fc07dbf8b94c/ext/node/02_require.js#L375) seems resolving the case of cowsay. Going to check if this causes the regression or not
