### ISSUE TITLE
`node/http.ts` `http.request` should support `socketPath` option

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#17910]
**Describe the bug**

**Steps to Reproduce**

```ts
> var Docker = (await import('npm:dockerode@3.3.4')).default
undefined
> var docker = new Docker({socketPath: '/var/run/docker.sock'});
undefined
> await docker.listContainers()
Uncaught TypeError: error sending request for url (http://localhost/containers/json): error trying to connect: tcp connect error: Connection refused (os error 111)
    at async mainFetch (internal:ext/fetch/26_fetch.js:267:14)
    at async fetch (internal:ext/fetch/26_fetch.js:491:9)
    at async ClientRequest._final (https://deno.land/std@0.177.0/node/http.ts:147:7)
```

**Expected behavior**

```ts
> var Docker = (await import('dockerode')).default
undefined
> var docker = new Docker({socketPath: '/var/run/docker.sock'});
undefined
> await docker.listContainers()
[
  {
    Id: ...
```

**Environment**

- OS: [e.g. Ubuntu 20.04, MacOS 11] ArchLinux
- deno version: 1.30.3
- std version: https://deno.land/std@0.177.0/node/http.ts:147:7

**Comment by loynoir** [comment]
@kt3k 

https://github.com/denoland/deno/issues/8821#issuecomment-1408439707

https://deno.land/x/socket_fetch@v0.1/mod.ts

Maybe can merge that library into `node/http.ts` logic?

**Comment by danopia** [comment]
> https://deno.land/x/socket_fetch@v0.1/mod.ts
> 
> Maybe can merge that library into `node/http.ts` logic?

Unfortunately my socket_fetch library is incomplete :( It can only perform GET requests and is not optimized. I use it to query specific things but it's not in a shape to be dropped into npm libraries I think.

Ideally Deno ships some sort of Unix socket fetch client instead :)

**Comment by loynoir** [comment]
Workaround

```js
import { fetch, Agent } from 'undici'

const resp = await fetch('http://localhost/version', {
  dispatcher: new Agent({
    connect: {
      socketPath: '/var/run/docker.sock'
    }
  })
})

console.log(await resp.text())
```

```sh
$ deno run --unstable -A ./reproduce.mjs
{"Platform":...
```

**Comment by loynoir** [comment]
Related 

[feat] Make backend js ecosystem future better

https://github.com/denoland/deno/issues/17910

**Comment by janka102** [comment]
I believe this was fixed in https://github.com/denoland/deno/pull/33208, just like this other issue https://github.com/denoland/deno/issues/27675.

I tried the minimal reproduction above with deno v2.7.14 and it succeeds.
