### ISSUE TITLE
Incompatibility with "npm:/@google-cloud/storage"

### ISSUE THREAD

**Issue by avalero** [denoland/deno#17987]
Deno v.1.31.1

Cannot upload files to google cloud storage ("npm:/@google-cloud/storage"). It throws the following error.

```
Error: Not implemented: crypto.Sign
    at notImplemented (internal:deno_node/polyfills/_utils.ts:7:11)
    at new Sign (internal:deno_node/polyfills/internal/crypto/sig.ts:10:9)
    at Object.createSign (internal:deno_node/polyfills/crypto.ts:41:12)
    at Object.sign (file:///home/avalero/.cache/deno/npm/registry.npmjs.org/jwa/2.0.0/index.js:151:25)
    at Object.jwsSign [as sign] (file:///home/avalero/.cache/deno/npm/registry.npmjs.org/jws/4.0.0/lib/sign-stream.js:32:24)
    at GoogleToken.requestToken (file:///home/avalero/.cache/deno/npm/registry.npmjs.org/gtoken/6.1.2/build/src/index.js:232:31)
    at GoogleToken.getTokenAsyncInner (file:///home/avalero/.cache/deno/npm/registry.npmjs.org/gtoken/6.1.2/build/src/index.js:166:21)
    at GoogleToken.getTokenAsync (file:///home/avalero/.cache/deno/npm/registry.npmjs.org/gtoken/6.1.2/build/src/index.js:145:55)
    at GoogleToken.getToken (file:///home/avalero/.cache/deno/npm/registry.npmjs.org/gtoken/6.1.2/build/src/index.js:97:21)
    at JWT.refreshTokenNoCache (file:///home/avalero/.cache/deno/npm/registry.npmjs.org/google-auth-library/8.7.0/build/src/auth/jwtclient.js:172:36)
```

**Comment by GJZwiers** [comment]
It is a known issue, there was a PR to fix it that got postponed for a bit: https://github.com/denoland/deno_std/pull/3190, I believe it may be reopened sometime in the near future

**Comment by littledivy** [comment]
We're tracking all missing APIs from `node:crypto` in https://github.com/denoland/deno/issues/18455. Closing.
