### ISSUE TITLE
HTTP server example on homepage throws error

### ISSUE THREAD

**Issue by saadq** [denoland/deno#1800]
**mod.ts** (Copied from https://deno.land homepage)

```ts
import { serve } from "https://deno.land/x/http/server.ts";
const s = serve("0.0.0.0:8000");

async function main() {
  for await (const req of s) {
    req.respond({ body: new TextEncoder().encode("Hello World\n") });
  }
}

main();
```

```bash
$ deno mod.ts --allow-net
Compiling /Users/me/Desktop/test/mod.ts
Downloading https://deno.land/x/http/server.ts...
Downloading https://deno.land/x/io/bufio.ts...
Downloading https://deno.land/x/textproto/mod.ts...
Downloading https://deno.land/x/http/http_status.ts...
Downloading https://deno.land/x/testing/mod.ts...
Downloading https://deno.land/x/util/deferred.ts... NOT FOUND
Uncaught NotFound: Cannot resolve module "../util/deferred.ts" from "/Users/me/.deno/deps/https/deno.land/x/http/server.ts"
    at DenoError (deno/js/errors.ts:19:5)
    at maybeError (deno/js/errors.ts:38:12)
    at maybeThrowError (deno/js/errors.ts:26:15)
    at sendSync (deno/js/dispatch.ts:67:5)
    at codeFetch (deno/js/os.ts:66:19)
    at _resolveModule (deno/js/compiler.ts:252:38)
    at resolveModuleNames (deno/js/compiler.ts:488:31)
    at compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:32750:71)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:20688:69)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:20909:20)
```

**Comment by linweiwei123** [comment]
I have the same problem

**Comment by hearsay316** [comment]
for await (const { res }  of s) {
run error,
 error TS2339: Property 'res' does not exist on type 'ServerRequest'.

5     for await (const { res } of s) {
                         ~~~
 for await (const req  of s) {   is ok

**Comment by saadq** [comment]
Yeah, it looks like the way `serve()` should be used has changed. Usage should now be like on the website:

```ts
import { serve } from "https://deno.land/x/std@v0.2.10/http/server.ts";
const s = serve("0.0.0.0:8000");

async function main() {
  for await (const req of s) {
    req.respond({ body: new TextEncoder().encode("Hello World\n") });
  }
}

main();
```
