### ISSUE TITLE
Implement "ascii" encoding for node:fs writeFile() polyfill

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#18078]
Not sure if this still belongs in the `deno_std` issue tracker now that node polyfills have been embedded in the Deno binary. Feel free to move if so.

I'd like to use [`npm:@poki/cli`](https://www.npmjs.com/package/@poki/cli) but it throws `Not implemented: "ascii" encoding`.
Not sure if this is easy to reproduce because you need a developer account to use the poki cli, but the error I get seems clear enough:

```
error: Uncaught Error: Not implemented: "ascii" encoding
    at notImplemented (internal:deno_node/polyfills/_utils.ts:7:11)
    at checkEncoding (internal:deno_node/polyfills/_fs/_fs_common.ts:40:9)
    at Object.writeFileSync (internal:deno_node/polyfills/_fs/_fs_writeFile.ts:60:22)
    at IncomingMessageForClient.<anonymous> (file:///home/jesper/.cache/deno/npm/registry.npmjs.org/@poki/cli/0.1.12/bin/index.js:185:44)
    at IncomingMessageForClient.emit (internal:deno_node/polyfills/_events.mjs:379:28)
    at Ea (internal:deno_node/polyfills/_stream.mjs:12:43461)
    at processTicksAndRejections (internal:deno_node/polyfills/_next_tick.ts:31:29)
```

**Comment by GJZwiers** [comment]
Repro:

```ts
import * as fs from "node:fs";

fs.writeFile("file.txt", "Hello world!", { encoding: "ascii" }, () => {});
```

**Comment by Farsen976** [comment]
Hello, 
I'm new to this project, but I would like to start to contribute so just to confirm what to do, we just had to include "ascii" into this [encodings](https://github.com/denoland/deno/blob/main/ext/node/polyfills/_fs/_fs_common.ts#L77) array and remove it from the `notImplementedEncodings` array ? Or there is extra stuff to do ?

**Comment by Farsen976** [comment]
Here my PR #18097
