### ISSUE TITLE
[vite] Trying to import ESM module using require()

### ISSUE THREAD

**Issue by jackfiszr** [denoland/deno#18119]
When I try to `import { quasar, transformAssetUrls } from "npm:@quasar/vite-plugin@1.3.0";` in vite.config.mjs of a create-vite-extra project, I get:

```
failed to load config from /home/jack/dev/vite-project2/vite.config.mjs
error when starting dev server:
Error: Trying to import ESM module: /home/jack/dev/vite-project2/node_modules/.deno/vite@4.1.4/node_modules/vite/dist/node/index.js using require()
    at Object.Module._extensions..js (internal:deno_node_loading/02_require.js:774:13)
    at Module.load (internal:deno_node_loading/02_require.js:656:32)
    at Function.Module._load (internal:deno_node_loading/02_require.js:513:12)
    at Module.require (internal:deno_node_loading/02_require.js:678:19)
    at require (internal:deno_node_loading/02_require.js:818:16)
    at Object.<anonymous> (file:///home/jack/dev/vite-project2/node_modules/.deno/@quasar+vite-plugin@1.3.0/node_modules/@quasar/vite-plugin/dist/index.js:5:12)
    at Object.<anonymous> (file:///home/jack/dev/vite-project2/node_modules/.deno/@quasar+vite-plugin@1.3.0/node_modules/@quasar/vite-plugin/dist/index.js:441:4)
    at Module._compile (internal:deno_node_loading/02_require.js:745:34)
    at Object.Module._extensions..js (internal:deno_node_loading/02_require.js:778:10)
    at Module.load (internal:deno_node_loading/02_require.js:656:32)
```
Looks similar to #17448

This happens since Deno v1.31. It used to work before.

**Comment by bartlomieju** [comment]
I believe this is now solved as Deno has much better support for Vite and can now `require(ESM)` too as of Deno 2.
