### ISSUE TITLE
AsyncLocalStorage().enterWith is not a function

### ISSUE THREAD

**Issue by arjunyel** [denoland/deno#18127]
Node compatibility issue https://nodejs.org/api/async_context.html#asynclocalstorageenterwithstore

```typescript
import { Client } from 'npm:@temporalio/client';

const client = new Client();
const result = await client.workflow.execute<(arg: string) => Promise<void>>(
'',
{
  taskQueue: 'default',
  workflowId: 'my-business-id',
  args: ['Temporal'],
}
);
console.log(result); // Hello, Temporal!
```

```bash
TypeError: callContextStorage.enterWith is not a function
    at Function.createCtorOptions (file:///Users/a/Library/Caches/deno/npm/registry.npmjs.org/@temporalio/client/1.6.0/lib/connection.js:161:22)
    at Function.lazy (file:///Users/a/Library/Caches/deno/npm/registry.npmjs.org/@temporalio/client/1.6.0/lib/connection.js:245:24)
    at new BaseClient (file:///Users/a/Library/Caches/deno/npm/registry.npmjs.org/@temporalio/client/1.6.0/lib/base-client.js:20:74)
    at new Client (file:///Users/a/Library/Caches/deno/npm/registry.npmjs.org/@temporalio/client/1.6.0/lib/client.js:14:9)
```

**Comment by rracariu** [comment]
Same happens when running SvelteKit 2.5.0 in dev mode:
```bash
deno task dev
```
Prints this:
```bash
TypeError: async_local_storage.enterWith is not a function
    at Object.before_handle (file:///Users/deno/my-app/node_modules/.deno/@sveltejs+kit@2.5.0/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:532:27)
    at Module.respond (/Users/deno/my-app/node_modules/.deno/@sveltejs+kit@2.5.0/node_modules/@sveltejs/kit/src/runtime/server/respond.js, <anonymous>:302:12)
    at async file:///Users/deno/my-app/node_modules/.deno/@sveltejs+kit@2.5.0/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22 {
  stack: "TypeError: async_local_storage.enterWith is not a function\n" +
    "    at Object.before_handle (file:///User"... 448 more characters
}
Error: Not found: /favicon.ico
    at resolve (/Users/deno/my-app/node_modules/.deno/@sveltejs+kit@2.5.0/node_modules/@sveltejs/kit/src/runtime/server/respond.js, <anonymous>:533:13)
    at resolve (/Users/deno/my-app/node_modules/.deno/@sveltejs+kit@2.5.0/node_modules/@sveltejs/kit/src/runtime/server/respond.js, <anonymous>:333:5)
    at Object.#options.hooks.handle (/Users/deno/my-app/node_modules/.deno/@sveltejs+kit@2.5.0/node_modules/@sveltejs/kit/src/runtime/server/index.js, <anonymous>:80:56)
    at Module.respond (/Users/deno/my-app/node_modules/.deno/@sveltejs+kit@2.5.0/node_modules/@sveltejs/kit/src/runtime/server/respond.js, <anonymous>:330:40)
    at eventLoopTick (ext:core/01_core.js:64:7) {
  stack: "Error: Not found: /favicon.ico\n" +
    "    at resolve (/Users/deno/my-app/node_modules/.deno/@svel"... 650 more characters,
  status: 404,
  text: "Not Found"
}
```
