### ISSUE TITLE
constants can be destroyed in the repl ?

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#18165]
I found a weird issue in the repl

If I input the following line in the repl `import {} from "https://deno.land/x/dax@0.24.1/mod.ts"; const URL = "aze";` (as one line)

I get an error:

```
Uncaught ReferenceError: URL is not defined
    at getWasmFileUrl (https://deno.land/x/dax@0.24.1/src/lib/mod.ts:7:15)
    at https://deno.land/x/dax@0.24.1/src/lib/mod.ts:63:14
```

**Comment by sigmaSd** [comment]
I see now it seems that the repl just makes any variable a global , here is an example that make it clear

```bash
deno
Deno 2.5.2+3d7e939
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> const globalThis = undefined
undefined
> Deno
[Internal Formatting Error] TypeError: Cannot read properties of undefined (reading 'Intl')
    at formatRaw (ext:deno_console/01_console.js:814:49)
    at formatValue (ext:deno_console/01_console.js:545:10)
    at formatProperty (ext:deno_console/01_console.js:1650:11)
    at formatRaw (ext:deno_console/01_console.js:960:9)
    at formatValue (ext:deno_console/01_console.js:545:10)
    at Object.inspectArgs (ext:deno_console/01_console.js:3033:28)
    at Object.<anonymous> (<anonymous>:3:25)
> 
```
