### ISSUE TITLE
node:readline doesn't work with Deno.stdin: "Uncaught TypeError: input.on is not a function"

### ISSUE THREAD

**Issue by neongreen** [denoland/deno#18184]
```ts
// readline.ts

import * as readline from 'node:readline'

const rl = readline.createInterface({
	input: Deno.stdin,
	output: Deno.stdout,
})

rl.question(">", line => {
	console.log('Got line', line)
})
```

```bash
deno run readline.ts
error: Uncaught TypeError: input.on is not a function
const rl = readline.createInterface({
                    ^
    at InterfaceConstructor (ext:deno_node/internal/readline/interface.mjs:270:9)
    at new Interface (ext:deno_node/_readline.mjs:97:4)
    at Module.createInterface (ext:deno_node/_readline.mjs:199:10)
    at file:///private/tmp/readline.ts:3:21
```

**Comment by neongreen** [comment]
Deno version: 1.31.2

OS: macOS Ventura 13.2

**Comment by sigmaSd** [comment]
```ts
import { stdin, stdout } from "node:process";
import { createInterface } from "node:readline";

let intf = createInterface({ input: stdin, output: stdout });
```
this doesn't work for me (deno 1.37.2) it fails with 

```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'next')
const rl = readline.createInterface({ input: stdin, output: stdout });
                    ^
    at emitKeypressEvents (ext:deno_node/internal/readline/emitKeypressEvents.mjs:56:26)
    at InterfaceConstructor (ext:deno_node/internal/readline/interface.mjs:303:5)
    at new Interface (ext:deno_node/_readline.mjs:99:4)
    at Object.createInterface (ext:deno_node/_readline.mjs:201:10)
    at file:///home/mrcool/dev/deno/lab/a.ts:4:21
```

**Comment by K-ETFreeman** [comment]
just stuck for me
i do deno run index.js and now its frozen completely

**Comment by burgil** [comment]
Hello! I found the solution!

https://docs.deno.com/examples/prompts/

They made it possible to use native API's (finally thanks Deno I'm starting to love you)

# New Code: (Solution for us, the users)

```ts
const answer = prompt("How much is 21 + 21?");
console.log("answer:", answer);
```

# Old Code:

```ts
// const rl = readline.createInterface({
//     input: process.stdin,
//     output: process.stdout
// });
// rl.question(questionPrompt, (answer) => {
//     rl.close();
// });
```

# Why and How? (This is the solution for the Deno team, or at least a lead)

**Tip:** If you want to see why this hangs, replace `output: process.stdout` with `Deno.stdout` and the error will reveal itself:

```bash
error: Uncaught (in promise) TypeError: expected typed ArrayBufferView
            rl.question(`\x1b[36m${noQuestion ? question : `${question} \x1b[32m(y/n)\x1b[0m: `}\x1b[0m`, (answer) => {
               ^
    at write (ext:deno_io/12_io.js:52:15)
    at Stdout.write (ext:deno_io/12_io.js:188:12)
    at Interface.[_writeToOutput] [as _writeToOutput] (ext:deno_node/internal/readline/interface.mjs:432:19)
    at Interface.prompt (ext:deno_node/internal/readline/interface.mjs:391:27)
    at Interface.[kQuestion] (ext:deno_node/internal/readline/interface.mjs:405:12)
    at Interface.question (ext:deno_node/_readline.mjs:146:20)
    at askQuestion
```
```ts
// const rl = readline.createInterface({
//     input: process.stdin,
//     output: Deno.stdout
// });
```

Adding `Deno.stdin` to the `input` of the `createInterface` options result in:

```bash
error: Uncaught (in promise) TypeError: input.on is not a function
            const rl = readline.createInterface({
                                ^
    at InterfaceConstructor (ext:deno_node/internal/readline/interface.mjs:280:9)
    at Module.createInterface (ext:deno_node/_readline.mjs:201:10)
    at askQuestion
```
```ts
// const rl = readline.createInterface({
//     input: Deno.stdin,
//     output: Deno.stdout
// });
```

**Comment by bartlomieju** [comment]
`node:readline` works on current canary - the original snippet just passes the wrong `input`. `Deno.stdin` is a Deno `Reader`/`Writer`, not a Node `Readable` stream, so it has no `.on()` and Node's `readline` (correctly) rejects it. This is by design: when using `node:readline`, give it Node streams from `node:process`.

Working usage:

```ts
import { stdin, stdout } from "node:process";
import { createInterface } from "node:readline";

const rl = createInterface({ input: stdin, output: stdout });

// Either:
rl.on("line", (line) => {
  console.log("Got line:", line);
  rl.close();
});

// Or:
rl.question("Q> ", (answer) => {
  console.log("answer:", answer);
  rl.close();
});
```

Both forms work, including writing the prompt to stdout. The earlier failures in this thread (raw-mode/`ExpectedBuffer` on output, `Cannot read properties of undefined (reading 'next')` in `emitKeypressEvents`, `expected typed ArrayBufferView` from `Stdout.write`) are all resolved when using `node:process` stdin/stdout.

If you prefer a native API, `prompt()` also works for simple cases.

Closing - the remaining `Deno.stdin` case is not something Node's `readline` accepts (use `process.stdin`).
