### ISSUE TITLE
`deno run -A npm:aws-cdk --app "deno run -A app.ts" destroy` throws `process is not defined`

### ISSUE THREAD

**Issue by misterjoshua** [denoland/deno#18198]
Hi. For the following AWS CDK app, I get an error when running `deno run -A npm:aws-cdk --app "deno run -A app.ts" destroy`:

`app.ts:`
```ts
import cdk from 'npm:aws-cdk-lib';

const app = new cdk.App();

new cdk.Stack(app, 'my-stack');
```

**Here's the output:**

```sh
$ deno run -A npm:aws-cdk destroy --app "deno run -A app.ts"
not implemented: ClientRequest.setTimeout

process is not defined
<hangs here indefinitely>
```

**Versions:**
```
$ deno --version
deno 1.31.2 (release, x86_64-unknown-linux-gnu)
v8 11.0.226.19
typescript 4.9.4

$ deno run -A npm:aws-cdk --version
2.69.0 (build 60a5b2a)
```

**Notes:**
- Broadly speaking, the synth and deploy commands work.
- The cdk deploy command is very noisy about `ClientRequest.setTimeout` not being implemented, but it deploys the CloudFormation stack nonetheless.
- This "process is not defined" error only happens during the cdk destroy command.

**Comment by bartlomieju** [comment]
@misterjoshua I just tested this on latest Deno (v1.34.1) and I get this error:
```
$ deno run -A npm:aws-cdk destroy --app "deno run -A app.ts"
Are you sure you want to delete: my-stack (y/n)? y
my-stack: destroying... [1/1]

 ❌  my-stack: destroy failed Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
    at SdkProvider.resolveEnvironment (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/aws-cdk/2.70.0/lib/index.js:284:46682)
    at eventLoopTick (ext:core/01_core.js:182:11)
    at async CloudFormationDeployments.prepareSdkFor (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/aws-cdk/2.70.0/lib/index.js:372:86165)
    at async CloudFormationDeployments.destroyStack (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/aws-cdk/2.70.0/lib/index.js:372:85288)
    at async CdkToolkit.destroy (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/aws-cdk/2.70.0/lib/index.js:374:152953)
    at async exec4 (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/aws-cdk/2.70.0/lib/index.js:429:51795)
****************************************************
*** Newer version of CDK is available [2.81.0]   ***
*** Upgrade recommended (npm install -g aws-cdk) ***
****************************************************

Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment

```

Which appears to be correct since I didn't have this stack before. I consider this is now fixed, let me know if you hit any more problems.
