### ISSUE TITLE
Unable to connect to altas mongoDB using mongoose.

### ISSUE THREAD

**Issue by mdmusaibali** [denoland/deno#18278]
Connection code:

```
import mongoose from "npm:mongoose";
try {
  const MONGO_URL = Deno.env.get("MONGO_URL");
  if (MONGO_URL) {
    await mongoose.connect(
      "mongodb+srv://<username>:<password>@cluster0.byaerrd.mongodb.net/<db-name>?retryWrites=true&w=majority"
    );
    console.log("Connected to db");
  }
} catch (error) {
  if (error instanceof Error) {
    console.log("Cannot connect to DB", error);
  }
}
```

If mongo URL is local i.e "mongodb://localhost:27017/test" it works fine but when url contains srv it fails.
Error when above code in run:

```
Cannot connect to DB MongoAPIError: Server record does not share hostname with parent URI
    at resolveSRVRecord (file:///home/mdmusaibali/.cache/deno/npm/registry.npmjs.org/mongodb/5.1.0/lib/connection_string.js:60:19)
    at async MongoClient.connect (file:///home/mdmusaibali/.cache/deno/npm/registry.npmjs.org/mongodb/5.1.0/lib/mongo_client.js:117:27)
    at async _createMongoClient (file:///home/mdmusaibali/.cache/deno/npm/registry.npmjs.org/mongoose/7.0.2/lib/connection.js:859:3)
    at async NativeConnection.openUri (file:///home/mdmusaibali/.cache/deno/npm/registry.npmjs.org/mongoose/7.0.2/lib/connection.js:728:5)
    at async file:///home/mdmusaibali/Documents/GitHub/pda-paper-validation-deno-ts/db/mongo.ts:5:5
```

**Comment by youwei997** [comment]
Excuse me, did you connect with nodejs properly? I recently used nodejs or MongoDBCompass to connect to altas mongoDB and couldn't connect

**Comment by alexander01202** [comment]
I get this error using node js

**Comment by mateo-gomez** [comment]
you just have to resolve mongo dns with this snippet:

```ts
import { resolveMongoDNS } from 'https://deno.land/x/resolve_mongo_dns/mod.ts';
import mongoose from 'npm:mongoose';

const URI = '...'; // Your MongoDB connection URI

const newURI = await resolveMongoDNS(URI);

await mongoose.connect(newURI);
```

**Comment by bartlomieju** [comment]
The whole Node compat layer has been rewritten and MongoDB now works correctly. Closing as resolved.
