### ISSUE TITLE
node: Error when using `npm:portfinder`

### ISSUE THREAD

**Issue by ayame113** [denoland/deno#18301]
I'm having trouble running [portfinder](https://www.npmjs.com/package/portfinder), a package that finds available ports, on Deno.

Running the code below in Node.js correctly finds available ports.

```ts
import { getPortPromise } from "npm:portfinder";
// import { getPortPromise } from "portfinder";

console.log(await getPortPromise());
```

However, when I run it on Deno, I get the following error:

```shell
> deno run -A ./tmp.mjs
error: Uncaught Error: No open ports available
    at Server.onError (file:///C:/Users/ayame/AppData/Local/deno/npm/registry.npmjs.org/portfinder/1.0.32/lib/portfinder.js:58:23)
    at Object.onceWrapper (https://deno.land/std@0.168.0/node/_events.mjs:504:26)
    at Server.emit (https://deno.land/std@0.168.0/node/_events.mjs:379:28)
    at _emitErrorNT (https://deno.land/std@0.168.0/node/net.ts:1806:10)
    at processTicksAndRejections (https://deno.land/std@0.168.0/node/_next_tick.ts:41:15)
```

This problem should affect [many packages that depend on portfinder](https://www.npmjs.com/browse/depended/portfinder).

```
> deno --version
deno 1.29.0 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by mmastrac** [comment]
Will fix as part of https://github.com/denoland/deno_core/pull/440
