### ISSUE TITLE
Node - add ClientRequest#setNoDelay

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#18316]
We're missing this: https://nodejs.org/api/http.html#requestsetnodelaynodelay

https://github.com/denoland/deno_std/blob/main/node/http.ts

Seems like we're missing a few methods on there actually.

Related denoland/deno#17852

**Comment by Joel-PeakMetrics** [comment]
Hello,

I'm seeing this failure as well using the OpenSearch client on Deno.

```
Error streaming agents: TypeError: request.setNoDelay is not a function
```

**Comment by nathanpuri** [comment]
I'm see this error when attempting to use PubNub (latest version), which uses superagent:
```
TypeError: req.setNoDelay is not a function
    at Request.request (file:///deno-dir/npm/registry.npmjs.org/superagent/6.1.0/lib/node/index.js:798:7)
    at Request.end (file:///deno-dir/npm/registry.npmjs.org/superagent/6.1.0/lib/node/index.js:951:8)
    at default_1.xdr (file:///deno-dir/npm/registry.npmjs.org/pubnub/7.3.1/lib/networking/modules/web-node.js:108:8)
    at default_1.get (file:///deno-dir/npm/registry.npmjs.org/pubnub/7.3.1/lib/networking/modules/web-node.js:200:16)
    at default_1.GET (file:///deno-dir/npm/registry.npmjs.org/pubnub/7.3.1/lib/networking/index.js:64:30)
    at class_1.default_1 (file:///deno-dir/npm/registry.npmjs.org/pubnub/7.3.1/lib/core/components/endpoint.js:273:35)
    ...
```
This is caused by simple `this.pubnub.publish(...)` call.

Are there any workarounds?
