### ISSUE TITLE
`npm:ssh2` times out waiting for handshake

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#18313]
`npm:ssh2` does not work in Deno right now, it hangs for a bit and then throws.

```ts
import { Client } from "npm:ssh2";

const client = new Client();
client.on("ready", () => {
  console.log("Client :: ready");
  client.exec("uptime", (err, stream) => {
    if (err) throw err;
    stream.on("close", (code, signal) => {
      console.log("Stream :: close :: code: " + code + ", signal: " + signal);
      client.end();
    }).on("data", (data) => {
      console.log("STDOUT: " + data);
    }).stderr.on("data", (data) => {
      console.log("STDERR: " + data);
    });
  });
}).connect({
  host: "<some_ip>",
  port: 22,
  username: "<some_user>",
  privateKey: Deno.readFileSync(/path/to/my/key.pem"),
});
```

```
error: Uncaught Error: Timed out while waiting for handshake
    at Timeout.<anonymous> (file:///C:/Users/GJZwiers/AppData/Local/deno/npm/registry.npmjs.org/ssh2/1.11.0/lib/client.js:1014:23)
    at https://deno.land/std@0.164.0/node/timers.ts:21:15
    at Object.action (deno:ext/web/02_timers.js:147:13)
    at handleTimerMacrotask (deno:ext/web/02_timers.js:64:12)
```

It looks like `ssh2` uses a number of methods from Node `crypto` that are not implemented in `std` yet:

- ~createDecipheriv~
- createDiffieHellman
- createDiffieHellmanGroup
- createECDH,
- ~createHmac~
- createPublicKey
- createSign
-  createVerify
- diffieHellman
- generateKeyPairSync
- sign
- verify
 
Deno version: 1.28.0

**Comment by GJZwiers** [comment]
Closing in favor of https://github.com/denoland/deno/issues/18455
