### ISSUE TITLE
[Feature] `vm.isContext`

### ISSUE THREAD

**Issue by Industrial** [denoland/deno#18315]
**Is your feature request related to a problem? Please describe.**
I can't get `jsdom` to work.

```
error: Error: Not implemented: isContext
  throw new Error(message);
        ^
    at notImplemented (https://deno.land/std@0.154.0/node/_utils.ts:23:9)
    at Object.isContext (https://deno.land/std@0.154.0/node/vm.ts:62:3)
    at new Window (file:///home/tom/.cache/deno/npm/registry.npmjs.org/jsdom/20.0.0/lib/jsdom/browser/Window.js:252:10)
    at exports.createWindow (file:///home/tom/.cache/deno/npm/registry.npmjs.org/jsdom/20.0.0/lib/jsdom/browser/Window.js:97:10)
    at new JSDOM (file:///home/tom/.cache/deno/npm/registry.npmjs.org/jsdom/20.0.0/lib/api.js:36:20)
    at file:///home/tom/Code/code9/deno/test-fresh/components/Container.test.tsx:10:36
```

**Describe the solution you'd like**
Implement `vm.isContext` (and probably `vm.createContext`)

**Describe alternatives you've considered**
https://deno.land/manual@v1.25.3/jsx_dom/linkedom
https://deno.land/manual@v1.25.3/jsx_dom/deno_dom

**Comment by guy-borderless** [comment]
for running with [@mozilla/readability](https://github.com/mozilla/readability) I could only get it working with deno-dom-wasm. 

```typescript
import { DOMParser } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts"
import { Readability } from "npm:@mozilla/readability"

 const document = new DOMParser().parseFromString(
    htmlString,
    "text/html",
  )!
  const reader = new Readability(document)
```

Would love to have happy-dom and jsdom support for readability.js support.
