### ISSUE TITLE
node: implement dgram.Socket APIs

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#18324]
`dgram.Socket` is needed to run [multicast-dns](https://www.npmjs.com/package/multicast-dns) in compat mode. (feature request from community)

- [ ] `socket.addMembership()`
- [ ] `socket.addSourceSpecificMembership()`
- [ ] `socket.dropMembership()`
- [ ] `socket.dropSourceSpecificMembership()`
- [ ] `socket.setBroadcast()`
- [ ] `socket.setMulticastInterface()`
- [ ] `socket.setMulticastLoopback()`
- [ ] `socket.setMulticastTtl()`
- [ ] `socket.setTtl()`
- [x] `socket.ref()` #21777
- [x] `socket.unref()` #21777

**Comment by hey-ab** [comment]
I'm sorely missing the implementation of the rest of dgram's methods, someone please!

**Comment by hey-ab** [comment]
I looked at the source code and I see that the methods in the [list above](https://github.com/denoland/deno/issues/18324#issuecomment-1478034481), have already been released. But I still can't use the libraries that depend on `dgram`.

Here is for an example code that works in Node but doesn't work in Deno:

```typescript
import dgram from "node:dgram";

const socket = dgram.createSocket({
  type: "udp4",
  reuseAddr: true,
});

socket.bind(5353)

socket.on("error", (err) => {
  console.error(err);
});
```

When running in Deno, I get this error:
```
Error: bind EADDRINUSE 0.0.0.0:5353
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:91:9)
    at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:215:10)
    at node:dgram:273:20
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:36:15)
    at eventLoopTick (ext:core/01_core.js:180:29) {
  errno: -48,
  code: "EADDRINUSE",
  syscall: "bind",
  address: "0.0.0.0",
  port: 5353
}
```
@cmorten maybe you can help me figure out the problem?

**Comment by cmorten** [comment]
Hi @hey-ab 👋 

Trying to refresh mem as this was a while ago! From what I can see the TODO list I posted still stands - much of the dgram module is yet to be implemented.

R.E. your specific issue, I think it’s most likely due to the socket reuse capability never being implemented, see https://github.com/denoland/deno/blob/main/ext/node/polyfills/internal_binding/udp_wrap.ts#L322

**Comment by hey-ab** [comment]
Hmm... That's sad, unfortunately I've never written in Rust and won't be able to help out. 😢
Am I correct in assuming that my PR is still valid in this case? https://github.com/denoland/deno-docs/pull/150

**Comment by cmorten** [comment]
> Hmm... That's sad, unfortunately I've never written in Rust and won't be able to help out. 😢 ~Am I correct in assuming that my PR is still valid in this case? [denoland/deno-docs#150](https://github.com/denoland/deno-docs/pull/150)~

When I say Deno APIs I meant JS/TS using the `Deno.*` namespace (e.g. https://deno.land/api@v1.37.0?unstable=&s=Deno.listenDatagram) - it might be that Rust isn’t needed here, often it’s hooking up the appropriate calls. Worth doing the analysis to see if possible or if there’s a feature gap on APIs or their options.

That said if there’s functionality that is required which Deno doesn’t support then yes, some Rust needed.

**Comment by bartlomieju** [comment]
This seems to be mostly done as of Deno v2.2.2.

**Comment by 2color** [comment]
Thanks for all the work here.

Just want to point out that I just noticed that the todo list reported by @cmorten [above](https://github.com/denoland/deno/issues/18324#issuecomment-1478034481) is still open.

See [context](https://github.com/ipfs/helia/issues/73#issuecomment-2864091259) for how this impacts Helia and js-libp2p use with Deno.

**Comment by littledivy** [comment]
Reopening issue since this is not entirely implemented and work is ongoing (eg: https://github.com/denoland/deno/pull/29207).

**Comment by bukhalo** [comment]
Thank you all for your work. As I see it, we are very close to full support for `node:dgram` in Deno. I'm really looking forward to when Deno can be used for smart home software. [Homebridge](https://github.com/homebridge/homebridge) (HomeKit) support is sorely lacking. They use the [Ciao](https://github.com/homebridge/ciao) library, to support multicast dns. There are several methods that are missing for full support:

- setMulticastInterface (https://github.com/homebridge/ciao/blob/335f6145d188a9af0805a2b5f3764c087da8cd0f/src/MDNSServer.ts#L521)
- setTTL (https://github.com/homebridge/ciao/blob/335f6145d188a9af0805a2b5f3764c087da8cd0f/src/MDNSServer.ts#L524)

We're very much looking forward to it 🙏

**Comment by 2color** [comment]
Thanks for adding `socket.addMembership` and `socket.setMulticastTTL` @littledivy.

I just tried it with Deno 2.3.5, and I'm now getting the following error :

```
error: Uncaught (in promise) Error: Adding membership 239.255.255.250 failed - addMembership EINVAL
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:91:3)
    at __node_internal_errnoException (ext:deno_node/internal/errors.ts:139:10)
    at Socket.addMembership (node:dgram:145:13)
    at Socket.<anonymous> (file:///Users/danielnorman/dev/deno_helia/node_modules/.deno/@achingbrain+ssdp@4.1.0/node_modules/@achingbrain/ssdp/dist/src/create-sockets.js:20:28)
    at Socket.emit (ext:deno_node/_events.mjs:394:28)
    at startListening (node:dgram:709:10)
    at node:dgram:279:7
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:39:15)
    at eventLoopTick (ext:core/01_core.js:175:29)
```

I suspect this is related to the passed multicastAddress `239.255.255.250`, which is the SSDP address and should be valid.

Seems like a validation error from https://github.com/denoland/deno/blob/22a615c7eb3dc2410783bb4991431102f7f5e15a/ext/net/ops.rs#L267-L281

Any idea?

I'm running: 
```
deno 2.3.5 (stable, release, aarch64-apple-darwin)
v8 13.7.152.6-rusty
typescript 5.8.3
```

**Comment by 2color** [comment]
See https://github.com/denoland/deno/pull/29207/files#r2131890283 for `socket.addMembership` related bug. 

And here's a small reproduction: https://github.com/ipshipyard/deno_helia/blob/main/ssdp.ts

**Comment by Apollon77** [comment]
Hey, is there any chance to get this finished ...? :-) This would be (at least from now seeing) the main things needed to have "matter,js" (the JavaScript Matter implementation) also run via Deno and to see if this could get less RAM usage or such.
See also https://github.com/project-chip/matter.js/discussions/1712
