### ISSUE TITLE
parallel\test-child-process-spawn-event.js fails on Windows due to use of "echo"

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#18359]
```
const subprocess = spawn('echo', ['ok']);

let didSpawn = false;
subprocess.on('spawn', function() {
  didSpawn = true;
});
```

```
------- output -------
Error: "parallel\test-child-process-spawn-event.js" failed
You can repeat only this test with the command: ./target/debug/deno test -A --import-map cli/tests/node_compat/import_map.json cli/tests/node_compat/test.ts -- parallel\test-child-process-spawn-event.js
----- output end -----
  Node.js compatibility "parallel\test-child-process-spawn-event.js" ... FAILED (106ms)
    error: AssertionError: Failed assertion: error: Uncaught AssertionError: function should not have been called at unknown
    called with arguments: NotFound: program not found
        at spawnChildInner (ext:runtime/40_process.js:162:17)
        at spawnChild (ext:runtime/40_process.js:182:10)
        at Command.spawn (ext:runtime/40_process.js:439:12)
        at new ChildProcess (ext:deno_node/internal/child_process.ts:108:16)
        at spawn (ext:deno_node/child_process.ts:102:12)
        at Object.<anonymous> (file:///V:/deno/cli/tests/node_compat/test/parallel/test-child-process-spawn-event.js:13:20)
        at Object.<anonymous> (file:///V:/deno/cli/tests/node_compat/test/parallel/test-child-process-spawn-event.js:36:4)
        at Module._compile (ext:deno_node/01_require.js:938:34)
        at Object.Module._extensions..js (ext:deno_node/01_require.js:971:10)
        at Module.load (ext:deno_node/01_require.js:849:32) {
      code: 'ENOENT'
    }
        at new AssertionError (ext:deno_node/assertion_error.ts:411:15)
        at createAssertionError (ext:deno_node/assert.ts:21:19)
        at Function.fail (ext:deno_node/assert.ts:282:15)
        at ChildProcess.mustNotCall (file:///V:/deno/cli/tests/node_compat/test/common/index.js:301:12)
        at ChildProcess.emit (ext:deno_node/_events.mjs:379:28)
        at ext:deno_node/internal/child_process.ts:211:18
        at processTicksAndRejections (ext:deno_node/_next_tick.ts:23:21)

        throw new AssertionError(msg);
              ^
        at assert (file:///V:/deno/test_util/std/testing/asserts.ts:141:11)
        at fail (file:///V:/deno/test_util/std/testing/asserts.ts:602:3)
        at fn (file:///V:/deno/cli/tests/node_compat/test.ts:103:9)
        at async testStepSanitizer (ext:cli/40_testing.js:449:5)
        at async TestContext.step (ext:cli/40_testing.js:1352:11)
        at async runTest (file:///V:/deno/cli/tests/node_compat/test.ts:53:3)
        at async file:///V:/deno/cli/tests/node_compat/test.ts:116:5
----- output end -----
```

I think we should just ignore this test on Windows because I am getting ENOENT trying this out in node.js as well.

**Comment by bartlomieju** [comment]
This test is now enabled https://github.com/denoland/deno/blob/1c5a7189e57cd1d3d0cc3ce7a2f6725ac5ede3ea/tests/node_compat/config.jsonc#L203
