### ISSUE TITLE
Error: bind UNKNOWN 0.0.0.0:41234

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#18405]
### Brief
- deno version <= 1.30.3, `node:dgram` work
- 1.30.3 < deno version <= 1.32.1, `node:dgram` does not work

### Reproduce
Example copy from https://nodejs.org/api/dgram.html

```js
import dgram from 'node:dgram';

const server = dgram.createSocket('udp4');

server.on('error', (err) => {
  console.error(`server error:\n${err.stack}`);
  server.close();
});

server.on('message', (msg, rinfo) => {
  console.log(`server got: ${msg} from ${rinfo.address}:${rinfo.port}`);
});

server.on('listening', () => {
  const address = server.address();
  console.log(`server listening ${address.address}:${address.port}`);
});

server.bind(41234);
```

### Expected
```sh
$ "$deno_1_30_3" run -A reproduce.mjs 
server listening 0.0.0.0:41234
```

### Actual
```sh
$ deno --version
deno 1.32.1 (release, x86_64-unknown-linux-gnu)
v8 11.2.214.9
typescript 5.0.2
$ deno run -A reproduce.mjs 
server error:
Error: bind UNKNOWN 0.0.0.0:41234
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:89:11)
    at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:213:12)
    at ext:deno_node/dgram.ts:271:28
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:34:29)
```

### Suggestion
- Add example script to test.

**Comment by nabil-mansouri** [comment]
Hi! I got the same issue. To resolve it run deno using "--unstable" flags.
If you dont use this flag Deno.listenDatagram is undefined:
https://github.com/denoland/deno_std/blob/0.177.0/node/internal_binding/udp_wrap.ts#L36
https://github.com/denoland/deno_std/blob/0.177.0/node/internal_binding/udp_wrap.ts#L323

**Comment by bartlomieju** [comment]
Fixed - this works on current Deno with no flags. The root cause was that `Deno.listenDatagram` (which `node:dgram` is built on) used to be behind `--unstable`; UDP is stable now, so no flag is needed.

Running the repro:

```
$ deno run -A reproduce.mjs
server listening 0.0.0.0:41234
```

And a full UDP round-trip (binding + sending + receiving a datagram) works:

```
server listening 0.0.0.0:41234
server got: ping from 127.0.0.1:54819
```

Closing as resolved.
