### ISSUE TITLE
npm:better-sqlite3 npm:node-libcurl not working

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#18444]
### Brief
Node native addon seems not yet supported.

Are there workaround for below cases?

### Case: better-sqlite3
```js
import Database from 'npm:better-sqlite3'
const db = new Database(':memory:')
void db
```
```txt
error: Uncaught Error: Could not locate the bindings file. Tried:
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/build/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/build/Debug/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/build/Release/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/out/Debug/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/Debug/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/out/Release/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/Release/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/build/default/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/compiled/18.12.1/linux/x64/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/addon-build/release/install-root/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/addon-build/debug/install-root/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/addon-build/default/install-root/better_sqlite3.node
 → /home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/lib/binding/node-v108-linux-x64/better_sqlite3.node
    at bindings (file:///home/vscode/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/bindings.js:126:9)
    at new Database (file:///home/vscode/.cache/deno/npm/registry.npmjs.org/better-sqlite3/8.2.0/lib/database.js:48:64)
    at file:///tmp/tmp.79CLe5jynp/reproduce.mjs:2:12
```

### Case: node-libcurl
Related 
https://github.com/denoland/deno/issues/17910
https://github.com/denoland/deno/issues/8821
https://github.com/denoland/deno/issues/7660

```js
import { curly } from 'npm:node-libcurl'
await curly.get('https://stackoverflow.com/')
```

```txt
error: Uncaught Error: Cannot find module '../lib/binding/node_libcurl.node'
Require stack:
- /home/vscode/.cache/deno/npm/registry.npmjs.org/node-libcurl/3.0.0/dist/Easy.js
- /home/vscode/.cache/deno/npm/registry.npmjs.org/node-libcurl/3.0.0/dist/Curl.js
- /home/vscode/.cache/deno/npm/registry.npmjs.org/node-libcurl/3.0.0/dist/index.js
- /home/vscode/.cache/deno/npm/registry.npmjs.org/node-libcurl/3.0.0/dist/index.js
    at Function.Module._resolveFilename (ext:deno_node/01_require.js:825:15)
    at Function.Module._load (ext:deno_node/01_require.js:657:27)
    at Module.require (ext:deno_node/01_require.js:871:19)
    at require (ext:deno_node/01_require.js:1011:16)
    at Object.<anonymous> (file:///home/vscode/.cache/deno/npm/registry.npmjs.org/node-libcurl/3.0.0/dist/Easy.js:5:18)
    at Object.<anonymous> (file:///home/vscode/.cache/deno/npm/registry.npmjs.org/node-libcurl/3.0.0/dist/Easy.js:15:4)
    at Module._compile (ext:deno_node/01_require.js:938:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:971:10)
    at Module.load (ext:deno_node/01_require.js:849:32)
    at Function.Module._load (ext:deno_node/01_require.js:703:12)
```

**Comment by ry** [comment]
Node-API is supported. I'll rename this issue to `npm:better-sqlite3` not working.

**Comment by loynoir** [comment]
@ry

And 'npm:node-libcurl'.
Related 
https://github.com/denoland/deno/issues/17910
https://github.com/denoland/deno/issues/8821
https://github.com/denoland/deno/issues/7660

**Comment by andykais** [comment]
also related https://github.com/denoland/deno/issues/15717. `better-sqlite3` does not work in 1.33.1

**Comment by drewbitt** [comment]
Still an issue in v1.35.2

I comment to bring attention to this as the latest blog post states
> Next month, we will focus our efforts on getting [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js), [google-cloud-node](https://github.com/googleapis/google-cloud-node) and various DB drivers working. If you find a package that doesn’t work, please report an issue at [denoland/deno repo](https://github.com/denoland/deno/issues/new).

So hope this gets picked up.

**Comment by ducktype** [comment]
Still an issue in v1.41.0.

**Comment by reggi** [comment]
I'd like one deno / node sqlite / pg (with typed tables) library 🤞 🙏 

Open to any libraries that do this.

It's the only thing making me have to choose deno / node whenever I start a new project. 

Currently messing with sequelize / sqlite3 and seeing this error too:

```
error: Uncaught (in promise) Error: Could not locate the bindings file. Tried:
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/build/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/build/Debug/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/build/Release/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/out/Debug/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/Debug/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/out/Release/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/Release/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/build/default/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/compiled/20.11.1/darwin/arm64/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/addon-build/release/install-root/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/addon-build/debug/install-root/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/addon-build/default/install-root/node_sqlite3.node
 → /Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/lib/binding/node-v108-darwin-arm64/node_sqlite3.node
    at bindings (file:///Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/bindings/1.5.0/bindings.js:126:9)
    at Object.<anonymous> (file:///Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/sqlite3/5.1.7/lib/sqlite3-binding.js:1:291)
    at Object.<anonymous> (file:///Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/sqlite3/5.1.7/lib/sqlite3-binding.js:3:4)
    at Module._compile (node:module:718:34)
    at Object.Module._extensions..js (node:module:732:10)
    at Module.load (node:module:643:32)
    at Function.Module._load (node:module:524:12)
    at Module.require (node:module:662:19)
    at require (node:module:776:16)
    at Object.<anonymous> (file:///Users/thomasreggi/Library/Caches/deno/npm/registry.npmjs.org/sqlite3/5.1.7/lib/sqlite3.js:2:17)
```

**Comment by loynoir** [comment]
Close in favor of https://github.com/denoland/deno/issues/19130

**Comment by loynoir** [comment]
Quote myself https://github.com/denoland/deno/issues/15717#issuecomment-1557396582

> I think it is blocked by #19130
> 
> Expect to search under `/home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0`.
> 
> But actually search under `/home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0`
