### ISSUE TITLE
integration::cert::cafile_compile is flaky

### ISSUE THREAD

**Issue by aapoalas** [denoland/deno#18442]
See: https://github.com/denoland/deno/actions/runs/4523853079/jobs/7967278237

```
---- integration::cert::cafile_compile stdout ----
deno_exe path /home/runner/work/deno/deno/target/release/deno
command /home/runner/work/deno/deno/target/release/deno compile --quiet --cert ./tls/RootCA.pem --allow-net --output /tmp/deno-cli-testa7DbqO/cert ./cert/cafile_ts_fetch.ts
command cwd "/home/runner/work/deno/deno/cli/tests/testdata"
command /tmp/deno-cli-testa7DbqO/cert 
command cwd "/home/runner/work/deno/deno/cli/tests/testdata"
[test_util/src/lib.rs:2061] part = "\nHello\n"
[test_util/src/lib.rs:2061] i = 1
[test_util/src/lib.rs:2070] "exit false " = "exit false "
[test_util/src/lib.rs:2070] i = 1
OUTPUT START
error: Uncaught (in promise) TypeError: error sending request for url (https://localhost:5545/cert/cafile_ts_fetch.ts.out): error trying to connect: Connection reset by peer (os error 104)
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)

OUTPUT END
EXPECTED START
[WILDCARD]
Hello

EXPECTED END
thread 'integration::cert::cafile_compile' panicked at 'pattern match failed at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5'
```

**Comment by bartlomieju** [comment]
Doesn't exist anymore
