### ISSUE TITLE
Deno fmt panic

### ISSUE THREAD

**Issue by Hexagon** [denoland/deno#18446]
Tried with both `1.31.3` and `1.32.1`, same error,

**Full backtrace**

```
PS C:\Users\user\source\pup> $env:RUST_BACKTRACE="full"; deno fmt

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.32.1
Args: ["C:\\Users\\user\\.deno\\bin\\deno.exe", "fmt"]

thread 'tokio-runtime-worker' panicked at 'capacity overflow', library\alloc\src\raw_vec.rs:518:5
stack backtrace:
   0:     0x7ff752f8a399 - napi_release_threadsafe_function
   1:     0x7ff7521c02ab - napi_release_threadsafe_function
   2:     0x7ff752f64bda - napi_release_threadsafe_function
   3:     0x7ff752f8eaab - napi_release_threadsafe_function
   4:     0x7ff752f8e6a1 - napi_release_threadsafe_function
   5:     0x7ff752f8e2b5 - napi_release_threadsafe_function
   6:     0x7ff75208029c - napi_fatal_error
   7:     0x7ff752f8f2f7 - napi_release_threadsafe_function
   8:     0x7ff752f8f034 - napi_release_threadsafe_function
   9:     0x7ff752f8efaf - napi_release_threadsafe_function
  10:     0x7ff752f8ef84 - napi_release_threadsafe_function
  11:     0x7ff75426c885 - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff752156148 - napi_release_threadsafe_function
  13:     0x7ff752157c87 - napi_release_threadsafe_function
  14:     0x7ff752caaf33 - napi_release_threadsafe_function
  15:     0x7ff752cb3c4d - napi_release_threadsafe_function
  16:     0x7ff751fe4533 - napi_fatal_error
  17:     0x7ff752cb76ea - napi_release_threadsafe_function
  18:     0x7ff752cb4e4a - napi_release_threadsafe_function
  19:     0x7ff752cb70c0 - napi_release_threadsafe_function
  20:     0x7ff751fe4d42 - napi_fatal_error
  21:     0x7ff751d27a02 - napi_cancel_async_work
  22:     0x7ff75310d6a8 - napi_release_threadsafe_function
  23:     0x7ff75310d252 - napi_release_threadsafe_function
  24:     0x7ff752f862fa - napi_release_threadsafe_function
  25:     0x7ff97f747614 - BaseThreadInitThunk
  26:     0x7ff97f8826a1 - RtlUserThreadStart
```

**deno.json**

```json
{
  "fmt": {
    "options": {
      "lineWidth": 200,
      "semiColons": false
    }
  },
  "lint": {
    "files": {
      "exclude": ["plugins/web-interface/static/js"]
    }
  },
  "tasks": {
    "update-deps": "deno run --allow-read=. --allow-write=. --allow-net https://deno.land/x/udd/main.ts --dry-run deps.ts test/deps.ts",
    "build-schema": "deno run --allow-write tools/build-schema.ts && deno fmt",
    "check": "deno fmt --check && deno lint && deno check pup.ts && deno test --allow-read --allow-write --allow-env --allow-net",
    "build": "deno task check && deno task build-schema"
  }
}
```

**Comment by Hexagon** [comment]
I've traced the problem to this file

```
> deno fmt .\docs\service.md

============================================================
Deno has panicked. 
[...]
```
[service.md](https://github.com/denoland/deno/files/11072853/service.md)

**Comment by lucacasonato** [comment]
I can reproduce with an even more minimal reproduction:

```json
{},

a
```

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.32.1
Args: ["deno", "fmt", "test.json"]

thread 'tokio-runtime-worker' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: alloc::raw_vec::capacity_overflow
   3: alloc::str::<impl str>::repeat
   4: dprint_core::formatting::utils::string_utils::format_diagnostic
   5: dprint_plugin_json::format_text::format_text
   6: deno::tools::fmt::format_json
   7: deno::tools::fmt::format_file
   8: tokio::runtime::task::raw::poll
```

on an unrelated note, the stack trace seems completely wrong on windows. it includes a bunch of napi symbols that are definitely not executing in fmt (I hope!). @littledivy what is this?

**Comment by lucacasonato** [comment]
https://github.com/dprint/dprint-plugin-json/issues/13
