### ISSUE TITLE
integration::compile::dynamic_import_unanalyzable is flaky

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#18481]
```
failures:

---- integration::compile::dynamic_import_unanalyzable stdout ----
thread 'integration::compile::dynamic_import_unanalyzable' panicked at 'assertion failed: output.status.success()', cli/tests/integration/compile_tests.rs:780:3
stack backtrace:
   0:     0x561c2a8bcf6a - std::backtrace_rs::backtrace::libunwind::trace::h595f06c70adcc478
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x561c2a8bcf6a - std::backtrace_rs::backtrace::trace_unsynchronized::h177a0149c76cdde9
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561c2a8bcf6a - std::sys_common::backtrace::_print_fmt::hc0701fd2c3530c58
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x561c2a8bcf6a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4cd115d8750fd6c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x561c2a8e5a9e - core::fmt::write::h93e2f5923c7eca08
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:     0x561c2a8b5d15 - std::io::Write::write_fmt::h9959f96ab67fa35c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:     0x561c2a8bcd35 - std::sys_common::backtrace::_print::h1835ef8a8f9066da
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x561c2a8bcd35 - std::sys_common::backtrace::print::hcb5e6388b9235f41
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x561c2a8bf17f - std::panicking::default_hook::{{closure}}::h9c084969ccf9a722
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:     0x561c2a8bee3f - std::panicking::default_hook::h68fa2ba3c3c6c12f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:283:9
  10:     0x561c29946097 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h12a0781208308044
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
  11:     0x561c29946097 - test::test_main::{{closure}}::h7ad7ae943fdfb9b7
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:135:21
  12:     0x561c2a8bf90a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4e6ced11e07d8b24
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
  13:     0x561c2a8bf90a - std::panicking::rust_panic_with_hook::h8d5c434518ef298c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
  14:     0x561c2a8bf642 - std::panicking::begin_panic_handler::{{closure}}::hf33414f5dabf6faf
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:577:13
  15:     0x561c2a8bd41c - std::sys_common::backtrace::__rust_end_short_backtrace::hc50389427413bb75
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
  16:     0x561c2a8bf392 - rust_begin_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  17:     0x561c2a8e3e73 - core::panicking::panic_fmt::h2de7a7938f816de8
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  18:     0x561c2a8e3f0d - core::panicking::panic::h90931f06a97cc5e0
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:114:5
  19:     0x561c2ab325c9 - integration_tests::integration::compile::dynamic_import_unanalyzable::h9cf045b78f57adcf
  20:     0x561c2ab32209 - integration_tests::integration::compile::dynamic_import_unanalyzable::{{closure}}::h63d0f8c1140fddb4
  21:     0x561c2ab51b30 - core::ops::function::FnOnce::call_once::h55596660022b3279
  22:     0x561c2994b45f - core::ops::function::FnOnce::call_once::h5b1ab081051ac2d3
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
  23:     0x561c2994b45f - test::__rust_begin_short_backtrace::h0902cdf9b17ba060
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:656:18
  24:     0x561c2991bedc - test::run_test::{{closure}}::hc66856f071e0d4b5
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:647:30
  25:     0x561c2991bedc - core::ops::function::FnOnce::call_once{{vtable.shim}}::hfe8467ce5b66122f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
  26:     0x561c2994a4ba - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6346cb5ef99d424d
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  27:     0x561c2994a4ba - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf405595759a815ec
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panic/unwind_safe.rs:271:9
  28:     0x561c2994a4ba - std::panicking::try::do_call::hbd504df9f6e6d606
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  29:     0x561c2994a4ba - std::panicking::try::h4fcf155df21db1e7
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  30:     0x561c2994a4ba - std::panic::catch_unwind::h4a3018fee09e7c4d
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  31:     0x561c2994a4ba - test::run_test_in_process::h667c4ecb9c983a95
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:679:27
  32:     0x561c2994a4ba - test::run_test::run_test_inner::{{closure}}::h690aa8210278754c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:573:39
  33:     0x561c299163f1 - test::run_test::run_test_inner::{{closure}}::h6be3c1dde7c2ea52
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/test/src/lib.rs:600:37
  34:     0x561c299163f1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h444f8e9def80f8c3
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:121:18
  35:     0x561c2991bb6b - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hce8a8eb131e754e8
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/thread/mod.rs:558:17
  36:     0x561c2991bb6b - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h165ba069286ffa15
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panic/unwind_safe.rs:271:9
  37:     0x561c2991bb6b - std::panicking::try::do_call::hf7f2bd9cbae9cb83
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  38:     0x561c2991bb6b - std::panicking::try::h73e30af22766724c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  39:     0x561c2991bb6b - std::panic::catch_unwind::h371266288ddf26f1
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  40:     0x561c2991bb6b - std::thread::Builder::spawn_unchecked_::{{closure}}::h72a18812a02d75ce
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/thread/mod.rs:557:30
  41:     0x561c2991bb6b - core::ops::function::FnOnce::call_once{{vtable.shim}}::h12fb468c971a9b21
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
  42:     0x561c2a8c5353 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1c0f3664d7ced314
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  43:     0x561c2a8c5353 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h67647c21c6c4968a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  44:     0x561c2a8c5353 - std::sys::unix::thread::Thread::new::thread_start::h355d348ba593a22c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  45:     0x7f270e317b43 - <unknown>
  46:     0x7f270e3a9a00 - <unknown>
  47:                0x0 - <unknown>


failures:
    integration::compile::dynamic_import_unanalyzable

test result: FAILED. 1048 passed; 1 failed; 17 ignored; 0 measured; 0 filtered out; finished in 101.73s

error: test failed, to rerun pass `-p deno --test integration_tests`
Error: Process completed with exit code 101.
```

**Comment by andreubotella** [comment]
Can you link at the CI job with this failure?

**Comment by GJZwiers** [comment]
https://github.com/denoland/deno/actions/runs/4546997546/jobs/8016318404

**Comment by andreubotella** [comment]
The test checks the status code before checking the stdout/stderr, so there's no way to see what's wrong from the logs alone. I'll try to run a modified version of this test in a loop.
