### ISSUE TITLE
`parallel/test-http-url.parse-post.js` is flaky

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#18487]
```
Node.js compatibility ... Node.js compatibility "parallel/test-http-url.parse-post.js" => ./cli/tests/node_compat/test.ts:53:11
error: AssertionError: Failed assertion.
    throw new AssertionError(msg);
          ^
    at assert (file:///Users/runner/work/deno/deno/test_util/std/testing/asserts.ts:141:11)
    at fail (file:///Users/runner/work/deno/deno/test_util/std/testing/asserts.ts:602:3)
    at fn (file:///Users/runner/work/deno/deno/cli/tests/node_compat/test.ts:103:9)
    at async testStepSanitizer (ext:cli/40_testing.js:460:5)
    at async runTest (ext:cli/40_testing.js:782:20)
    at async TestContext.step (ext:cli/40_testing.js:1221:22)
    at async runTest (file:///Users/runner/work/deno/deno/cli/tests/node_compat/test.ts:53:3)
    at async Promise.all (index 202)
    at async file:///Users/runner/work/deno/deno/cli/tests/node_compat/test.ts:122:3

 FAILURES 
```

**Comment by bartlomieju** [comment]
Discussed with @kt3k. We spotted that we're spawning as many subprocesses as there are test files in `parallel/` directory. We're gonna chance it to spawn as many processes in parallel as there are cores on the machines to bring it more in line with how Node.js is doing this.

**Comment by GJZwiers** [comment]
Since https://github.com/denoland/deno/pull/18505 the `test-http-url.parse-*` tests have not been flaky anymore but `test-child-process-exec-timeout-kill.js` has failed a couple of times in the `debug macos 12` CI:

```
Node.js compatibility ... Node.js compatibility "parallel/test-child-process-exec-timeout-kill.js" => ./cli/tests/node_compat/test.ts:54:11
error: AssertionError: Failed assertion: error: Uncaught AssertionError: Values are not strictly equal:


    [Diff] Actual / Expected


-   false
+   true

    at new AssertionError (ext:deno_node/assertion_error.ts:411:15)
    at toNode (ext:deno_node/assert.ts:43:23)
    at Function.strictEqual (ext:deno_node/assert.ts:214:5)
    at file:///Users/runner/work/deno/deno/cli/tests/node_compat/test/parallel/test-child-process-exec-timeout-kill.js:42:10
    at file:///Users/runner/work/deno/deno/cli/tests/node_compat/test/common/index.js:286:15
    at ChildProcess.exithandler (ext:deno_node/child_process.ts:284:9)
    at ChildProcess.emit (ext:deno_node/_events.mjs:379:28)
    at ext:deno_node/internal/child_process.ts:158:26
    at Object.runMicrotasks (ext:core/01_core.js:406:30)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:51:14)

    throw new AssertionError(msg);
          ^
    at assert (file:///Users/runner/work/deno/deno/test_util/std/testing/asserts.ts:141:11)
    at fail (file:///Users/runner/work/deno/deno/test_util/std/testing/asserts.ts:602:3)
    at fn (file:///Users/runner/work/deno/deno/cli/tests/node_compat/test.ts:104:9)
    at async testStepSanitizer (ext:cli/40_testing.js:460:5)
    at async runTest (ext:cli/40_testing.js:782:20)
    at async TestContext.step (ext:cli/40_testing.js:1221:22)
    at async runTest (file:///Users/runner/work/deno/deno/cli/tests/node_compat/test.ts:54:3)

 FAILURES 

Node.js compatibility ... Node.js compatibility "parallel/test-child-process-exec-timeout-kill.js" => ./cli/tests/node_compat/test.ts:54:11

FAILED | 1 passed (522 steps) | 1 failed (1 step) (48s)


error: Test failed
```
