### ISSUE TITLE
"Deno has panicked." when running a script that processes a lot of json objects

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#18501]
More info below

```
➜  strfry-policies git:(develop) ✗ cat ~/Archive/mostr-events-2023-03-28.jsonl | deno task filter ./entrypoint.example.ts > ~/Downloads/profiles2.jsonl
Task filter deno run -A scripts/filter.ts "./entrypoint.example.ts"

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.32.1
Args: ["deno", "run", "-A", "./entrypoint.example.ts"]

thread 'main' panicked at 'OS can't spawn worker thread: Resource temporarily unavailable (os error 11)', ext/io/lib.rs:496:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffd61202f10

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffe0b9eff10

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffffdc00c90

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffd3f8b3e10

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffc008b4c90

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffd404a8f90

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffeb85de910

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffe4e93e110

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7fff7bcdd890

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffe01c55c90

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffe0d194a90

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7fff8311bb90

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffc3667f210

#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffd3f300090./entrypoint.example.ts: 2: Cannot fork
error: Uncaught WouldBlock: Resource temporarily unavailable (os error 11)
  const policy = Deno.run({
                      ^
    at opRun (ext:runtime/40_process.js:46:14)
    at Object.run (ext:runtime/40_process.js:132:15)
    at file:///home/alex/Projects/strfry-policies/scripts/filter.ts:16:23
➜  strfry-policies git:(develop) ✗         
```

The input file is a 4GB jsonl file (one json object on every line):

```
➜  strfry-policies git:(develop) ✗ ls -alh ~/Archive/mostr-events-2023-03-28.jsonl                                                                  
-rw-rw-r-- 1 alex alex 4.3G Mar 29 21:07 /home/alex/Archive/mostr-events-2023-03-28.jsonl
➜  strfry-policies git:(develop) ✗ wc -l ~/Archive/mostr-events-2023-03-28.jsonl
6029259 /home/alex/Archive/mostr-events-2023-03-28.jsonl
➜  strfry-policies git:(develop) ✗ 
```

- I'm running this script: https://gitlab.com/soapbox-pub/strfry-policies/-/blob/develop/scripts/filter.ts
- It only happens after ~20 minutes of processing this really large file
- deno 1.32.1

**Comment by petamoriken** [comment]
If it caused by memory leak, it may be resolved in Deno v1.32.2.
https://github.com/denoland/deno/issues/18369

**Comment by aapoalas** [comment]
Based on the error message this is more likely an actual issue of resource exhaustion (OS thread pool or something?) in Deno.

**Comment by alexgleason** [comment]
I don't know if this is still an issue, but a lot has changed since then so I will close this.
