### ISSUE TITLE
Error loading `package.json` with `fraction.js`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#18535]
Ran into an error with resolving the `fraction.js` module which is pulled in by `autoprefixer`. The problem is that `deno` looks for the `package.json` in the wrong path.

Expected: `node_modules/fraction.js/package.json`
Actual: `node_modules/fraction.js/fraction.js/package.json`

Steps to reproduce:

1. `mkdir foo && cd foo`
2. `echo '{ "name": "foo", "scripts": { "build": "microbundle" }, "dependencies": { "microbundle": "0.15.1"}}' >> package.json`
3. `deno task build`

Error:

```sh
error: Uncaught Error: Error loading package.json at /foo/node_modules/.deno/autoprefixer@10.4.14/node_modules/fraction.js/fraction.js/package.json. Not a directory (os error 20)
    at resolveExports (ext:deno_node/01_require.js:508:14)
    at Function.Module._findPath (ext:deno_node/01_require.js:547:31)
    at Function.Module._resolveFilename (ext:deno_node/01_require.js:808:27)
    at Function.Module._load (ext:deno_node/01_require.js:657:27)
    at Module.require (ext:deno_node/01_require.js:871:19)
    at require (ext:deno_node/01_require.js:1011:16)
    at Object.<anonymous> (file:///foo/node_modules/.deno/autoprefixer@10.4.14/node_modules/autoprefixer/lib/resolution.js:1:270)
    at Object.<anonymous> (file:///foo/node_modules/.deno/autoprefixer@10.4.14/node_modules/autoprefixer/lib/resolution.js:99:4)
    at Module._compile (ext:deno_node/01_require.js:938:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:971:10)
```

**Comment by marvinhagemeister** [comment]
Investigated a little bit and the incorrect module path is added here:

https://github.com/denoland/deno/blob/cbd14085e629556f5a00d994a5d2b1ef78ee47ce/ext/node/polyfills/01_require.js#L618-L626

I'm not sure yet what this branch is doing.
