### ISSUE TITLE
Deno.Command().spawn() fails with unclear error message on undefined envs

### ISSUE THREAD

**Issue by Hexagon** [denoland/deno#18556]
Minimal reproduction:

```ts
// test.ts
const commander = new Deno.Command(
    "deno",
    { 
        args: ["run","test_client.ts"], 
        env: {
            HELLO: undefined
        }
    }
);

commander.spawn();
```

**Expected outcome:**

Command runs, ignoring HELLO (alternatively setting HELLO to an empty string internally)

**Actual outcome:**

```
error: Uncaught TypeError: Error parsing args at position 0: serde_v8 error: ExpectedString
commander.spawn();
          ^
    at spawnChildInner (ext:runtime/40_process.js:162:17)
    at spawnChild (ext:runtime/40_process.js:182:10)
    at Command.spawn (ext:runtime/40_process.js:439:12)
    at file:///C:/Users/user/source/pup/test.ts:12:11
```

The error message points to the line containing .spawn(), but there is no indication that the problem is withing the environment variables, making it a tricky debug.

**Comment by GJZwiers** [comment]
Related: https://github.com/denoland/deno/issues/17406 https://github.com/denoland/deno/issues/15389

**Comment by waterbang** [comment]
Are there any other solutions, or should I go back to using `Deno.run`? I haven't encountered this issue on my Mac, only on Windows.
