### ISSUE TITLE
Error loading package.json importing `@google-cloud/storage`

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#18600]
```js
import { Storage } from "npm:@google-cloud/storage";
```

```
divy@mini ~/gh> deno run -A --reload gcloud_storage.mjs
error: Uncaught Error: Error loading package.json at /Users/divy/gh/node_modules/.deno/json-bigint@1.0.0/node_modules/bignumber.js/bignumber.js/package.json. Not a directory (os error 20)
    at resolveExports (ext:deno_node/01_require.js:510:14)
    at Function.Module._findPath (ext:deno_node/01_require.js:549:31)
    at Function.Module._resolveFilename (ext:deno_node/01_require.js:809:27)
    at Function.Module._load (ext:deno_node/01_require.js:659:27)
    at Module.require (ext:deno_node/01_require.js:891:19)
    at require (ext:deno_node/01_require.js:1031:16)
    at Object.<anonymous> (file:///Users/divy/gh/node_modules/.deno/json-bigint@1.0.0/node_modules/json-bigint/lib/stringify.js:1:269)
    at Object.<anonymous> (file:///Users/divy/gh/node_modules/.deno/json-bigint@1.0.0/node_modules/json-bigint/lib/stringify.js:386:4)
    at Module._compile (ext:deno_node/01_require.js:958:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:991:10)
```

**Comment by littledivy** [comment]
Related https://github.com/denoland/deno/issues/18535 https://github.com/denoland/deno/issues/17947
