### ISSUE TITLE
Different error code given vs Node for `fs.readFile` when path is a directory on Windows

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#18629]
We're giving ENOENT and Node.js is giving EISDIR:

```
> deno
Deno 1.32.3
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> import fs from "node:fs"
undefined
> fs.readFileSync("cli/tests/")
Uncaught NotFound: The system cannot find the path specified. (os error 3): readfile 'cli/tests/'
    at Object.readFileSync (ext:deno_fs/30_fs.js:679:14)
    at Object.readFileSync (ext:deno_node/_fs/_fs_readFile.ts:35:23)
    at <anonymous>:2:4
> _error.code
"ENOENT"
> close()
V:\deno [main ↑478 +0 ~1 -0 !]
> node
Welcome to Node.js v18.12.1.
Type ".help" for more information.
> fs.readFileSync("cli/tests/")
Uncaught Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:748:3)
    at tryReadSync (node:fs:448:20)
    at Object.readFileSync (node:fs:494:19) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
```

I believe this unit test here is incorrect and should be `EISDIR` for both windows and linux, but I'm unsure:

https://github.com/denoland/deno/blob/5d9172467eee8cdceefa944199459ddd410f7388/cli/tests/unit/read_file_test.ts#L173-L186

I discovered this when running the unit tests in Node for [node_shims](https://github.com/denoland/node_shims).

Related: #17958 (cc @kamilogorek), #18309

**Comment by bartlomieju** [comment]
Closing — this is no longer reproducible. `fs.readFileSync` on a directory now correctly returns `EISDIR` on all platforms. Tested on current Deno and it matches Node.js behavior:

```
readFileSync error code: EISDIR
readFileSync error message: EISDIR: illegal operation on a directory, open '/tmp'
```

This was fixed as part of the error mapping improvements since Deno 1.32.
