### ISSUE TITLE
TypeError: t is not a function from esm.sh/v114/axios@0.26.1/esnext/axios.mjs

### ISSUE THREAD

**Issue by ChuckJonas** [denoland/deno#18645]
I'm trying to run OpenAI npm package in a supabase function and running into this error:

```ts

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { Configuration, OpenAIApi } from "npm:openai";

console.log("Hello from Functions!");

const configuration = new Configuration({
  apiKey: Deno.env.get("OPENAI_API_KEY"),
});

serve(async (req) => {
  const openai = new OpenAIApi(configuration);
  const testChat = await openai.createChatCompletion({
    model: "gpt-4",
    messages: [
      {
        role: "user",
        content: `Hello, what can you do?`,
      },
    ],
  });

  return new Response(JSON.stringify(testChat), {
    headers: { "Content-Type": "application/json" },
  });
});
```

```
TypeError: t is not a function
    at Ke.exports (https://esm.sh/v114/axios@0.26.1/esnext/axios.mjs:523:16)
    at T.request (https://esm.sh/v114/axios@0.26.1/esnext/axios.mjs:681:17)
    at Function.request (https://esm.sh/v114/axios@0.26.1/esnext/axios.mjs:29:22)
    at https://esm.sh/v114/openai@3.2.1/esnext/openai.mjs:147:22
    at https://esm.sh/v114/openai@3.2.1/esnext/openai.mjs:866:91
    at async Server.<anonymous> (file:///home/deno/functions/testing/index.ts:12:22)
    at async Server.#respond (https://deno.land/std@0.168.0/http/server.ts:221:24)
 ```
 
Sorry, I'm still very new to deno so not really sure how to deal with these types of dependency issues...

**Comment by bartlomieju** [comment]
Thanks for the report. Revisiting this one:

This isn't a bug in Deno itself. The stack trace is entirely inside esm.sh's transpiled axios (`esm.sh/v114/axios@0.26.1/esnext/axios.mjs`). Back in early 2023 the Supabase edge runtime resolved `npm:` specifiers through esm.sh, so `TypeError: t is not a function` was an artifact of esm.sh's transpilation of axios, not Deno's own npm support. Stock Deno resolves `npm:openai` directly from the npm registry and never goes through esm.sh.

I confirmed on the latest canary (`deno 2.8.1+61f96bf`) that the exact scenario works: running `npm:openai@3.2.1` (the axios-based version from the issue) and calling `createChatCompletion` builds and dispatches the request correctly, returning a normal `401` with a dummy API key. There's no `t is not a function`.

On top of that, `openai` v4+ dropped axios entirely in favor of `fetch`, so the offending code path no longer exists in current versions of the package.

Closing as this isn't reproducible with Deno's npm support. If you hit something similar on a current Deno version (not through esm.sh/Supabase's runtime), please open a new issue with a minimal repro.
