### ISSUE TITLE
infisical imported through npm doesn't work as expected

### ISSUE THREAD

**Issue by uriva** [denoland/deno#18650]
```js
import infisical from "npm:infisical-node";
await infisical.connect({
  debug: true,
  token: Deno.env.toObject().infisical,
});
```

```
Error: Not implemented: crypto.Decipheriv
    at notImplemented (ext:deno_node/_utils.ts:7:11)
    at new Decipheriv (ext:deno_node/internal/crypto/cipher.ts:67:9)
    at Object.createDecipheriv (ext:deno_node/crypto.ts:26:12)
    at decryptSymmetric (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.0.37/lib/utils/crypto.js:100:27)
    at Function.<anonymous> (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.0.37/lib/services/SecretService.js:75:70)
    at step (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.0.37/lib/services/SecretService.js:33:23)
    at Object.next (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.0.37/lib/services/SecretService.js:14:53)
    at fulfilled (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.0.37/lib/services/SecretService.js:5:58)
    at Object.runMicrotasks (ext:core/01_core.js:406:30)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:51:14)
Failed to set up the Infisical client. Please ensure that your token is valid and try again.
```

**Comment by bartlomieju** [comment]
`crypto.Decipheriv` is now available.

**Comment by uriva** [comment]
still not working:

```
Error: Not implemented: crypto.Decipheriv.prototype.setAuthTag
    at notImplemented (ext:deno_node/_utils.ts:9:11)
    at Decipheriv.setAuthTag (ext:deno_node/internal/crypto/cipher.ts:126:9)
    at decryptSymmetric128BitHexKeyUTF8 (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.3.1/lib/utils/crypto.js:161:14)
    at file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.3.1/lib/helpers/key.js:51:78
    at step (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.3.1/lib/helpers/key.js:33:23)
    at Object.next (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.3.1/lib/helpers/key.js:14:53)
    at fulfilled (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.3.1/lib/helpers/key.js:5:58)
    at Object.runMicrotasks (ext:core/01_core.js:836:30)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:14)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:5)
```
