### ISSUE TITLE
Type checking doesn't work with express

### ISSUE THREAD

**Issue by ry** [denoland/deno#18686]
With the following code:
```ts
import express, { Request, Response } from 'npm:express';

const app = express();

app.get("/", (req: Request, res: Response) => {
  res.send("Foo\n");
});

app.listen(3000);
console.log("http://localhost:3000/");
```
I get this error:
```
# deno check main.ts
Check file:///private/tmp/express-test/main.ts
error: TS2305 [ERROR]: Module '"internal:///missing_dependency.d.ts"' has no exported member 'Request'.
import express, { Request, Response } from 'npm:express';
                  ~~~~~~~
    at file:///private/tmp/express-test/main.ts:2:19

TS2305 [ERROR]: Module '"internal:///missing_dependency.d.ts"' has no exported member 'Response'.
import express, { Request, Response } from 'npm:express';
                           ~~~~~~~~
    at file:///private/tmp/express-test/main.ts:2:28

Found 2 errors.
```

**Comment by dsherret** [comment]
See https://deno.land/manual@v1.32.4/node/npm_specifiers#typescript-types
