### ISSUE TITLE
test-child-process-execFile-promisified-abortController.js is flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#18692]
```
------- output -------
"parallel/test-child-process-execFile-promisified-abortController.js" failed:

error: Uncaught AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   NotFound
+   AbortError


    at new AssertionError (ext:deno_node/assertion_error.ts:411:15)
    at toNode (ext:deno_node/assert.ts:43:23)
    at deepStrictEqual (ext:deno_node/assert.ts:262:5)
    at validateThrownError (ext:deno_node/assert.ts:614:17)
    at rejects_onRejected (ext:deno_node/assert.ts:377:13)


You can repeat only this test with the command:
  
  ./target/debug/deno test -A cli/tests/node_compat/test.ts -- parallel/test-child-process-execFile-promisified-abortController.js

----- output end -----
  Node.js compatibility "parallel/test-child-process-execFile-promisified-abortController.js" ... FAILED (308ms)
```

https://github.com/denoland/deno/actions/runs/4692127173/jobs/8317459787
https://github.com/denoland/deno/actions/runs/4703617350/jobs/8342330353

**Comment by bartlomieju** [comment]
No longer flaky
