### ISSUE TITLE
Deno build on riscv64

### ISSUE THREAD

**Issue by hack3ric** [denoland/deno#18702]
I've successfully built Deno (1.32.3, 1.32.4 in progress) in qemu-user and run on HiFive Unmatched on [Arch Linux riscv64](https://archlinux.felixc.at).

Some tweaks I did:

- Use system `clang`, `lld`, `gn` and `ninja` to manually build V8.
- Apply https://github.com/denoland/rusty_v8/pull/1209 to allow passing extra GN args when building V8. The following steps will contain newly added environment variables from that PR.
- `NO_PRINT_GN_ARGS=1`. GN somehow segfaults when printing arguments, but it is trivial for now and doesn't affect generating build files.
- Enable `v8_enable_shared_ro_heap`. This is intentially [disabled](https://github.com/denoland/rusty_v8/blob/5dce1eaeef6457b7571b12c9c6170a362a62bb38/.gn#L52), but we need to wait for pointer compression to meet rusty_v8's [requirement](https://github.com/denoland/rusty_v8/blob/5dce1eaeef6457b7571b12c9c6170a362a62bb38/src/binding.cc#L2907) and disable it.
- Replace `ring` with [felixonmars/ring](https://github.com/felixonmars/ring) to provide C fallback for platforms without assembly crypto implementation.

Environment variables exported:
```sh
local _extra_gn_args=(
  'custom_toolchain="//build/toolchain/linux/unbundle:default"'
  'host_toolchain="//build/toolchain/linux/unbundle:default"'
  'v8_enable_shared_ro_heap=true'
)

export CC=clang CXX=clang++ AR=ar NM=nm
export CFLAGS="${CFLAGS//-fstack-clash-protection/}" CXXFLAGS="${CXXFLAGS//-fstack-clash-protection/}"
export V8_FROM_SOURCE=1
export CLANG_BASE_PATH=/usr
export GN=/usr/bin/gn NINJA=/usr/bin/ninja
export EXTRA_GN_ARGS="${_extra_gn_args[@]}"
export NO_PRINT_GN_ARGS=1
```

Build script for Arch Linux can be found in https://github.com/felixonmars/archriscv-packages/pull/2510. Patch Arch Linux's official PKGBUILD and build it:

```sh
pacman -S asp
asp checkout deno
cd deno/repos/community-x86_64
curl -L https://github.com/felixonmars/archriscv-packages/pull/2510.patch | git apply
makepkg -s
```

## Caveats

Note that current build runs TypeScript scripts normally, but in REPL errors will appear (while not affecting basic auto completion functionality):

```
ERROR TSLS = Error: Could not find source file: 'file://<working_dir>/$deno$repl.ts'.
    at getValidSourceFile (ext:deno_tsc/00_typescript.js:133358:23)
    at Object.getSemanticDiagnostics (ext:deno_tsc/00_typescript.js:133600:32)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1059:34)
    at [ext:cli/lsp/tsc.rs:3496:26]:1:12
```

This is triggered only by TypeScript LSP's `getDiagnostics` request. Other LSP requests with specifiers containing `$deno$repl.ts` seem to not fail. I'm yet to find out why.

**Comment by kxxt** [comment]
The errors from TypeScript LSP is perhaps caused by some path manipulation operations in `00_typescript.js`.

In function `pathForLibFile` in `00_typescript.js`:

```js
function hexEncode(s) {
  // helper function for debugging
  let result = "";
  for(let i=0; i < s.length; i++) {
    let hex = s.charCodeAt(i).toString(16);
    result += ("000" + hex).slice(-4);
  }
  return result;
}
function pathForLibFile(libFileName) {
  const core = globalThis.Deno.core;
  core.print(`entering pathForLibFile(${libFileName}): \n`);
  const components = libFileName.split(".");
  let path = components[1];
  core.print(`!!!!! path = ${path}, components = ${components}\n`, true);
  let i = 2;
  while (components[i] && components[i] !== "d") {
    let expr = (i === 2 ? "/" : "-") + components[i];
    core.print(`!!!!! path += ${hexEncode(expr)}\n`, true);
    path += expr;
    i++;
  }
  const resolveFrom = combinePaths(currentDirectory, `__lib_node_modules_lookup_${libFileName}__.ts`);
  core.print(`pathForLibFile(${libFileName}): \n    defaultLibraryPath = ${defaultLibraryPath}\n    resolveFrom = ${resolveFrom}\n    path = ${path}\n`, true);
  const localOverrideModuleResult = resolveModuleName("@typescript/lib-" + path, resolveFrom, { moduleResolution: 2 /* Node10 */ }, host, moduleResolutionCache);
  if (localOverrideModuleResult == null ? void 0 : localOverrideModuleResult.resolvedModule) {
    return localOverrideModuleResult.resolvedModule.resolvedFileName;
  }
  return combinePaths(defaultLibraryPath, libFileName);
}
```

The while loop is producing wrong results on riscv64:

```
before call processRootFile: lib.deno.ns.d.ts   entering pathForLibFile(lib.deno.ns.d.ts):
!!!!! path = deno, components = lib,deno,ns,d,ts        !!!!! path += 0060006e0073      !!!!! path += 000b0064  !!!!! path += 000b00740073      pathForLibFile(lib.deno.ns.d.ts):
defaultLibraryPath = asset:///lib.esnext.d.ts
resolveFrom = cache:///__lib_node_modules_lookup_lib.deno.ns.d.ts__.ts
path = deno`ns
d
ts   resolveModuleName(@typescript/lib-deno`ns
d
ts, cache:///__lib_node_modules_lookup_lib.deno.ns.d.ts__.ts, [object Object], [object Object], undefined, undefined, undefined)
```
![image](https://user-images.githubusercontent.com/18085551/235035294-d5f1b153-75b3-448a-8bfa-3c2d0b1d6c09.png)

The log doesn't look nice. There are some extra characters:

```
for "ns", there is an extra U+0060(`) before it
for "d" and "ts", there is an extra U+000B(Line Tabulation) before it
(The loop actually shouldn't reach here, the correct result is "deno/ns")
```

It looks like a V8 bug.

By explicitly use char codes I can workaround this bug:

```js
// while (components[i] && components[i] !== "d") {
while (components[i] && components[i].charCodeAt(0) !== 100) {
// let expr = (i === 2 ? "/" : "-") + components[i];
  let expr;
  if (i === 2)
        expr = String.fromCharCode(47) + components[i];
  else
        expr = String.fromCharCode(45) + components[i];
```

But there are other places that have bugs about path manipulation operations. So only fixing this one place can't let that error go away.

Any suggestions and helps will be well appreciated!

**Comment by hack3ric** [comment]
Hello, I want to update the status of Deno on riscv64.

On 1.33.1 https://github.com/denoland/rusty_v8/pull/1209 is merged and released. The `$deno$repl.ts` problem disappeared after disabling `v8_enable_shared_ro_heap` (as GN parameter restriction was removed in https://github.com/denoland/rusty_v8/commit/07f2e9f3b63ada1a4cd3205a5b13f2ba25cd2ca6). Other parameters are unchanged.

```sh
local _extra_gn_args=(
  'custom_toolchain="//build/toolchain/linux/unbundle:default"'
  'host_toolchain="//build/toolchain/linux/unbundle:default"'
)

export CC=clang CXX=clang++ AR=ar NM=nm
export CFLAGS="${CFLAGS//-fstack-clash-protection/}" CXXFLAGS="${CXXFLAGS//-fstack-clash-protection/}"
export V8_FROM_SOURCE=1
export CLANG_BASE_PATH=/usr
export GN=/usr/bin/gn NINJA=/usr/bin/ninja
export EXTRA_GN_ARGS="${_extra_gn_args[@]}"
export NO_PRINT_GN_ARGS=1
```

As a side note, V8's pointer compression on riscv64 is fixed in https://chromium-review.googlesource.com/c/v8/v8/+/4559353. If the aforementioned restriction is added back, Deno is likely to still work properly.

**Comment by tuler** [comment]
What is the status of deno on riscv64 now that deno v2 is out? Any effort in progress?

**Comment by hack3ric** [comment]
> What is the status of deno on riscv64 now that deno v2 is out? Any effort in progress?

Pretty much usable AFAIK, at least on recent versions <2. 1.46.0 needs to disable pointer compression like before. Progress are tracked in [Arch Linux RISC-V's deno patch against Arch Linux PKGBUILD](https://github.com/felixonmars/archriscv-packages/blob/master/deno/riscv64.patch) (if this file does not exist then the [original PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/deno/-/blob/main/PKGBUILD) will build fine.)

As for Deno 2.0, I haven't looked at it yet, but as long as it doesn't have groundbreaking changes in (rusty-)V8, it should build and work with no to little effort of porting.

**Comment by shodan8192** [comment]
Hello, I'm trying `deno-1.46.3-2-riscv64` from `archriscv.felixc.at` on LicheeRV Nano board with @Fishwaldo's Debian. 

On some scripts I get `Illegal instruction`, for example it can be triggered by :
```shell
echo 'import mqtt from "npm:mqtt"' | deno run -
```
Through `gdb` I've found that it's caused by `vle8.v` which I believe is RVV 1.0 instruction. Is my example giving the same error on HiFive Unmatched ?

**Comment by hack3ric** [comment]
Hi @shodan8192 My guess is that your SBI on Lichee Pi Nano treats RVV 0.7 in C906 cores as RVV 1.0. Could you try upgrading OpenSBI and see if it works?

**Comment by shodan8192** [comment]
My system report `rv64imafdvcsu` ISA .
SiFive U740 doesn't have any vector extension, that's why I've asked if my example works on it. If yes - then I have to disable RVV in kernel, if not, then `deno` should be compiled targeting cpu without vector extension.

**Comment by hack3ric** [comment]
This is not statically compiled code, it's generated by V8.

In terms of your question -- yes, it runs fine on Unmatched, and SG2042 (which has its RVV 0.7 hidden so application won't recognize it as RVV anymore)

**Comment by shodan8192** [comment]
Now that's clear. I didn't knew that V8 make use of vector instructions if they're available, thats why I though they were generated by compiler. So I'll try to disable RVV 0.7 and make things work. Thanks @hack3ric !

**Comment by shodan8192** [comment]
Sorry for spam, but I can't get it to work on Lichee Pi Nano with 5.10 kernel.

I've removed `CONFIG_VECTOR` and `CONFIG_VECTOR_0_7` from kernel config and set `riscv,isa = "rv64imafdc"` in dts file then rebuild - and nothing changed. Testing with this code :

```c
#include <sys/auxv.h>
#include <stdio.h>
#include <asm/hwcap.h>

void main() {
  unsigned long hw_cap = getauxval(AT_HWCAP);
  printf("I %s\n", hw_cap & COMPAT_HWCAP_ISA_I ? "detected" : "not found");
  printf("M %s\n", hw_cap & COMPAT_HWCAP_ISA_M ? "detected" : "not found");
  printf("A %s\n", hw_cap & COMPAT_HWCAP_ISA_A ? "detected" : "not found");
  printf("F %s\n", hw_cap & COMPAT_HWCAP_ISA_F ? "detected" : "not found");
  printf("D %s\n", hw_cap & COMPAT_HWCAP_ISA_D ? "detected" : "not found");
  printf("C %s\n", hw_cap & COMPAT_HWCAP_ISA_C ? "detected" : "not found");
  printf("V %s\n", hw_cap & COMPAT_HWCAP_ISA_V ? "detected" : "not found");
}
```
shows :
```
I detected
M detected
A detected
F detected
D detected
C detected
V not found
```

/proc/cpuinfo :
```
processor	: 0
hart		: 0
isa		: rv64imafdc
mmu		: sv39
```
Running my example with **V8 JIT disabled** :
```
echo 'import mqtt from "npm:mqtt"' | deno run --v8-flags=--jitless -
```
also **crashes with SIGILL**, so it seems it's not in V8 generated code. What else I can try to see what happening ?

**Comment by hack3ric** [comment]
It could be another problem with C906. fence.tso was originally not included in G, and C906 doesn't implement it in hardware. Newer OpenSBI for LicheeRV Nano (and other boards that uses C906 cores) should emulate it. Could you try upgrading that?

**Comment by shodan8192** [comment]
I'm using OpenSBI already patched for `fence.tso` emulation.

**Comment by hack3ric** [comment]
I still cannot reproduce this on LicheeRV Nano running Arch Linux RISC-V (kernel 6.11.3-arch1-1), so I'm out of ideas...

**Comment by shodan8192** [comment]
Kernel 6.11 have `riscv_hwprobe` syscall. If it's used to get cpu capabilities, and kernel 5.11 doesn't have it, then it can be erroneously assumed that cpu has RVV.

Where I can find image of Arch Linux you using ?

**Comment by hack3ric** [comment]
I'm using one of our team's build machine. There's no image right now, but I assume you can flash Debian first, replace the chroot, and then modify extlinux.conf or something so it boots to Arch-managed kernel.

Deno on Arch RISC-V is built against newer version of glibc (2.40 actually), and it may not work under your Debian image. As you mentioned in the email the [detection method used in V8](https://github.com/v8/v8/blob/main/src/base/cpu.cc#L964-L1009) is compile-time.

```
$ echo '#include <stdio.h>' | gcc -dM -E - | grep GLIBC
#define __GLIBC_USE(F) __GLIBC_USE_ ## F
#define __GLIBC_PREREQ(maj,min) ((__GLIBC__ << 16) + __GLIBC_MINOR__ >= ((maj) << 16) + (min))
#define __GLIBC_USE_IEC_60559_TYPES_EXT 0
#define __GLIBC__ 2
#define __GLIBC_USE_IEC_60559_BFP_EXT 0
#define __GLIBC_USE_DEPRECATED_GETS 0
#define __GLIBC_USE_C23_STRTOL 0
#define __GLIBC_USE_DEPRECATED_SCANF 0
#define __GLIBC_USE_LIB_EXT2 0
#define __GLIBC_USE_IEC_60559_FUNCS_EXT 0
#define __GLIBC_USE_IEC_60559_FUNCS_EXT_C23 0
#define __GLIBC_USE_IEC_60559_BFP_EXT_C23 0
#define __GLIBC_USE_ISOC23 0
#define __GLIBC_MINOR__ 40
#define __GLIBC_USE_IEC_60559_EXT 0
```

You *could* try to compile and install a newer version of glibc (>=2.40) on Debian though. But yeah, use other distros' packages is considered a bad idea :(

**Comment by shodan8192** [comment]
In my Debian image there's the same version of glibc `ldd (Debian GLIBC 2.40-3) 2.40` as in your Arch. I think that deno is quite distro-agnostic and should run on any Linux with recent glibc version.

I've exluded V8 as crash cause by disabling JIT, and by src code analysing - in my case V8 doesn't try use of `rvv` nor `fpu`, because detection method doesn't cover my case (glibc 2.40 and old kernel without `hwprobe`)

Actually `hwprobe` syscall is called triple times before crash and only last of them originating from V8 :
```
syscall_0x102(0x3fffbf6570, 0x1, 0, 0, 0, 0) = -1 ENOSYS (Function not implemented)
syscall_0x102(0x3fffbf6570, 0x1, 0, 0, 0, 0) = -1 ENOSYS (Function not implemented)
syscall_0x102(0x3fffbeded8, 0x1, 0, 0, 0, 0x2ab59305d0) = -1 ENOSYS (Function not implemented)
```
I'll investigate it further.

**Comment by shodan8192** [comment]
OK, so I found the problem. In my example crash occur, when npm tgz package is downloaded and is about to decompress. Deno is using `flate2` library for that : https://github.com/denoland/deno/blob/2c8a0e791732ab00907ca11c3a4918ad26ead03f/cli/npm/managed/cache/tarball_extract.rs#L17 with `zlib-ng` C library as the backend, which currently has this issue : https://github.com/zlib-ng/zlib-ng/issues/1705 due to RVV detection method.

On my system, if I spoof kernel version to`6.10.4` deno works without crash.

**Comment by ifsheldon** [comment]
Does Deno have a plan to create official RISC-V builds?

**Comment by marvinhagemeister** [comment]
No

**Comment by spital** [comment]
playing with codex a bit, have working rv64 / riscv64 / RISC-V `deno` working with rust_v8 in Debian 13 Trixie, if anybody is interested in PR, pls lmk.
```
./deno-riscv64-1464/target/release/deno --version
deno 2.7.5 (stable, release, riscv64gc-unknown-linux-gnu)
v8 14.6.202.9-rusty
typescript 5.9.2
```

**Comment by balupton** [comment]
@spital interested in deno for riscv, as deno is the only dependency of https://github.com/bevry/dorothy that doesn't run on riscv, preventing dorothy from running on riscv

**Comment by spital** [comment]
@balupton I have been experimenting with Deno on riscv64 recently, and my current read is:

- riscv64 is feasible from source,
- but it is not yet something I would recommend Dorothy users install from an arbitrary third-party binary,
- the useful next step is probably reproducible build documentation, patch tracking, and eventually CI, rather than a one-off binary.

I have a local/personal riscv64 build experiment that can be useful as a proof of feasibility, but I would rather not present it as an official or safe distribution path.

For Dorothy, what would be most useful to you?

1. a documented build recipe for a specific distro, for example Debian or Arch riscv64,
2. a small test matrix for the Deno features Dorothy actually needs,
3. help identifying the remaining upstream patches needed,
4. or a path toward an unofficial but reproducible CI-produced artifact?

Happy to help investigate this, especially if we can keep the goal narrow and practical.

**Comment by balupton** [comment]
@spital I have a VisionFive and VisionFive 2 (however I could never figure out how to get the VisionFive 2 to work), which I can use for CI and builds. The ideal would be a prebuilt binary, however Dorothy's infrastructure also supports building dependency binaries from source. Dorothy also has a comprehensive CI suite, so we can detect downstream integration issues and report back. Debian would be most useful, as Debian is more supported on the VisionFive's.

One of the main use cases for Deno in Dorothy is handling of regular expressions.

**Comment by spital** [comment]
Prebuilt binary:
https://files.catbox.moe/c955f8.zip

Test:
```bash
docker run -it -v$(pwd):/shared --platform=linux/riscv64 debian:13 bash -c 'apt update;apt install -y libatomic1;uname -m;/shared/deno --version'
```

Expected:
```
riscv64
deno 2.7.5 (stable, release, riscv64gc-unknown-linux-gnu)
v8 14.6.202.9-rusty
typescript 5.9.2
```

You may post issues at:
https://github.com/spital/deno-riscv64/issues

But no promises.

**Comment by littledivy** [comment]
@spital We're happy to land your patch in rusty_v8. If the CI is fast enough we can distribute prebuilt rusty_v8 archives for riscv64 as part of the releases.

**Comment by Xeonacid** [comment]
> [@spital](https://github.com/spital) We're happy to land your patch in rusty_v8. If the CI is fast enough we can distribute prebuilt rusty_v8 archives for riscv64 as part of the releases.

Thanks for your interest in that! Could you please review and merge https://github.com/denoland/rusty_v8/pull/1948? The build lasts for 72min and 100min for release and debug builds, respectively. I think that's acceptable.

**Comment by spital** [comment]
Openai codex with librusty_v8 build worked (note: JOB_NUM was 2, took over a day)

https://github.com/spital/codex-riscv64/issues/1

but now the blocker may be Debian 13 riscv64 image I used, not sure about Ubuntu 24 and clang > 21

**Comment by hack3ric** [comment]
not working on riscv anymore fow now but still want to say thank you for continuing this work :)
