### ISSUE TITLE
worker_permissions_data_local and worker_permissions_blob_remote are flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#18710]
```
failures:

---- integration::worker::worker_permissions_data_local stdout ----
deno_exe path /Users/runner/work/deno/deno/target/release/deno
command /Users/runner/work/deno/deno/target/release/deno run --quiet --reload --allow-net=localhost:4545 workers/permissions_data_local.ts
command cwd "/Users/runner/work/deno/deno/cli/tests/testdata"
output path /Users/runner/work/deno/deno/cli/tests/testdata/workers/permissions_data_local.ts.out
[test_util/src/lib.rs:2148] part = "local_file.ts\", run again with the --allow-read flag\n    at data:application/javascript;base64,"
[test_util/src/lib.rs:2148] i = 1
[test_util/src/lib.rs:2154] "found " = "found "
[test_util/src/lib.rs:2154] found = 1
[test_util/src/lib.rs:2148] part = ":1:8\nerror: Uncaught (in promise) Error: Unhandled error in child worker.\n    at Worker.#pollControl ("
[test_util/src/lib.rs:2148] i = 2
[test_util/src/lib.rs:2154] "found " = "found "
[test_util/src/lib.rs:2154] found = 44
[test_util/src/lib.rs:2148] part = ")\n    at eventLoopTick (ext:core/01_core.js:"
[test_util/src/lib.rs:2148] i = 3
[test_util/src/lib.rs:2157] "exit false " = "exit false "
[test_util/src/lib.rs:2157] i = 3
OUTPUT START
error: Uncaught (in worker "") Requires read access to "/local_file.ts", run again with the --allow-read flag
    at data:application/javascript;base64,aW1wb3J0ICJmaWxlOi8vL2xvY2FsX2ZpbGUudHMiOw==:1:8
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:157:19)

OUTPUT END
EXPECTED START
error: Uncaught (in worker "") Requires read access to "[WILDCARD]local_file.ts", run again with the --allow-read flag
    at data:application/javascript;base64,[WILDCARD]:1:8
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl ([WILDCARD])
    at eventLoopTick (ext:core/01_core.js:[WILDCARD])

EXPECTED END
thread 'integration::worker::worker_permissions_data_local' panicked at 'pattern match failed', cli/tests/integration/worker_tests.rs:87:1
stack backtrace:
   0:        0x100e7ee46 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h47bed05ceb7970ee
   1:        0x100d1770a - core::fmt::write::hefd823d99333384a
   2:        0x100e738bc - std::io::Write::write_fmt::hd6cfc6ec52823bda
   3:        0x100e85cea - std::sys_common::backtrace::print::hc9e298c4664da113
   4:        0x100e85913 - std::panicking::default_hook::***closure***::hb97411d6e916e1d2
   5:        0x100e8559f - std::panicking::default_hook::hc3ac81176817192f
   6:        0x100e866a2 - std::panicking::rust_panic_with_hook::hc11209fa2686218a
   7:        0x100e86428 - std::panicking::begin_panic_handler::***closure***::h5bad1bd665ab68a6
   8:        0x100e863b8 - std::sys_common::backtrace::__rust_end_short_backtrace::h6f4efa73918edf57
   9:        0x100e86382 - _rust_begin_unwind
  10:        0x101ef38e3 - core::panicking::panic_fmt::hb5474ac70e328787
  11:        0x100c4b300 - test_util::builders::TestCommandOutput::assert_matches_file::he06ccad0ed67b1cf
  12:        0x100bd1045 - core::ops::function::FnOnce::call_once::h8870f30dc23c1198
  13:        0x100e9eea2 - test::__rust_begin_short_backtrace::h04732ed1b0d13b9c
  14:        0x100e9ee81 - core::ops::function::FnOnce::call_once***vtable.shim***::h2d0f0110c4caa4c6
  15:        0x100e9f2b0 - test::run_test::run_test_inner::***closure***::he439a141fa1b3e3d
  16:        0x100ea1fdc - std::sys_common::backtrace::__rust_begin_short_backtrace::hce1badd8587a639f
  17:        0x100ea1e32 - core::ops::function::FnOnce::call_once***vtable.shim***::hce3f92b3efd31c27
  18:        0x100e88d29 - std::sys::unix::thread::Thread::new::thread_start::had0599fead9033cd
  19:     0x7ff8036124e1 - __pthread_start


failures:
    integration::worker::worker_permissions_data_local
```

https://github.com/denoland/deno/actions/runs/4702041362/jobs/8338819347

**Comment by dsherret** [comment]
Similarly `worker_permissions_blob_remote`. It seems to be the same underlying issue:

```
---- integration::worker::worker_permissions_blob_remote stdout ----
deno_exe path /Users/runner/work/deno/deno/target/release/deno
command /Users/runner/work/deno/deno/target/release/deno run --quiet --reload --allow-net=localhost:4545 workers/permissions_blob_remote.ts
command cwd "/Users/runner/work/deno/deno/cli/tests/testdata"
output path /Users/runner/work/deno/deno/cli/tests/testdata/workers/permissions_blob_remote.ts.out
[test_util/src/lib.rs:2148] part = ":1:8\nerror: Uncaught (in promise) Error: Unhandled error in child worker.\n    at Worker.#pollControl ("
[test_util/src/lib.rs:2148] i = 1
[test_util/src/lib.rs:2154] "found " = "found "
[test_util/src/lib.rs:2154] found = 36
[test_util/src/lib.rs:2148] part = ")\n    at eventLoopTick (ext:core/01_core.js:"
[test_util/src/lib.rs:2148] i = 2
[test_util/src/lib.rs:2157] "exit false " = "exit false "
[test_util/src/lib.rs:2157] i = 2
OUTPUT START
error: Uncaught (in worker "") Requires net access to "example.com", run again with the --allow-net flag
    at blob:null/9a73239c-7464-4472-a61c-a21ddaf9ca22:1:8
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:157:19)

OUTPUT END
EXPECTED START
error: Uncaught (in worker "") Requires net access to "example.com", run again with the --allow-net flag
    at blob:null/[WILDCARD]:1:8
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl ([WILDCARD])
    at eventLoopTick (ext:core/01_core.js:[WILDCARD])

EXPECTED END
thread 'integration::worker::worker_permissions_blob_remote' panicked at 'pattern match failed', cli/tests/integration/worker_tests.rs:80:1
stack backtrace:
   0:        0x10a3bbe46 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h47bed05ceb7970ee
   1:        0x10a25470a - core::fmt::write::hefd823d99333384a
   2:        0x10a3b08bc - std::io::Write::write_fmt::hd6cfc6ec52823bda
   3:        0x10a3c2cea - std::sys_common::backtrace::print::hc9e298c4664da113
   4:        0x10a3c2913 - std::panicking::default_hook::***closure***::hb97411d6e916e1d2
   5:        0x10a3c259f - std::panicking::default_hook::hc3ac81176817192f
   6:        0x10a3c36a2 - std::panicking::rust_panic_with_hook::hc11209fa2686218a
   7:        0x10a3c3428 - std::panicking::begin_panic_handler::***closure***::h5bad1bd665ab68a6
   8:        0x10a3c33b8 - std::sys_common::backtrace::__rust_end_short_backtrace::h6f4efa73918edf57
   9:        0x10a3c3382 - _rust_begin_unwind
  10:        0x10b4308e3 - core::panicking::panic_fmt::hb5474ac70e328787
  11:        0x10a188300 - test_util::builders::TestCommandOutput::assert_matches_file::he06ccad0ed67b1cf
  12:        0x10a13ea8c - core::ops::function::FnOnce::call_once::hc69eab10c66c0ded
  13:        0x10a3dbea2 - test::__rust_begin_short_backtrace::h04732ed1b0d13b9c
  14:        0x10a3dbe81 - core::ops::function::FnOnce::call_once***vtable.shim***::h2d0f0110c4caa4c6
  15:        0x10a3dc2b0 - test::run_test::run_test_inner::***closure***::he439a141fa1b3e3d
  16:        0x10a3defdc - std::sys_common::backtrace::__rust_begin_short_backtrace::hce1badd8587a639f
  17:        0x10a3dee32 - core::ops::function::FnOnce::call_once***vtable.shim***::hce3f92b3efd31c27
  18:        0x10a3c5d29 - std::sys::unix::thread::Thread::new::thread_start::had0599fead9033cd
  19:     0x7ff80af0b4e1 - __pthread_start


failures:
    integration::worker::worker_permissions_blob_remote
```

**Comment by dsherret** [comment]
@bartlomieju do you think this is caused by https://github.com/denoland/deno/pull/18611 ?
