### ISSUE TITLE
error: `koa` not working when used with `koa-session`

### ISSUE THREAD

**Issue by jcs224** [denoland/deno#18776]
I tried getting a Koa project going on Deno. The core Koa project seems to work fine, but the `koa-session` library is trying to access a value that Deno doesn't seem to recognize. Here is the error:

```
TypeError: Cannot read properties of undefined (reading 'encrypted')
      at Object.get protocol (file:///workspace/node_modules/.deno/koa@2.14.2/node_modules/koa/lib/request.js:402:21)
      at Object.get secure (file:///workspace/node_modules/.deno/koa@2.14.2/node_modules/koa/lib/request.js:418:29)
      at Object.get cookies (file:///workspace/node_modules/.deno/koa@2.14.2/node_modules/koa/lib/context.js:172:30)
      at ContextSession.initFromCookie (file:///workspace/node_modules/.deno/koa-session@5.13.1/node_modules/koa-session/lib/context.js:112:24)
      at ContextSession.get (file:///workspace/node_modules/.deno/koa-session@5.13.1/node_modules/koa-session/lib/context.js:38:39)
      at Object.get (file:///workspace/node_modules/.deno/koa-session@5.13.1/node_modules/koa-session/index.js:138:38)
      at Object.get (file:///workspace/node_modules/.deno/koa-passport@3.0.0/node_modules/koa-passport/lib/framework/request.js:94:21)
      at initialize (file:///workspace/node_modules/.deno/passport@0.3.2/node_modules/passport/lib/middleware/initialize.js:48:13)
      at file:///workspace/node_modules/.deno/koa-passport@3.0.0/node_modules/koa-passport/lib/framework/koa.js:188:7
      at new Promise (<anonymous>)
```

To help narrow in on it further, here's the file and line that seems to error:
https://github.com/koajs/koa/blob/master/lib/request.js#L402

And here's the reproduction:
https://codesandbox.io/p/sandbox/competent-rubin-h8dbzx?file=%2Fserver.js

**Comment by bartlomieju** [comment]
I just checked and it appears to be working with Deno v1.35.0 and later.
