### ISSUE TITLE
integration::worker::worker_permissions_dynamic_remote is flaky

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#18787]
```
failures:

---- integration::worker::worker_permissions_dynamic_remote stdout ----
deno_exe path /Users/runner/work/deno/deno/target/debug/deno
command /Users/runner/work/deno/deno/target/debug/deno run --quiet --reload --allow-net --unstable workers/permissions_dynamic_remote.ts
command cwd "/Users/runner/work/deno/deno/cli/tests/testdata"
output path /Users/runner/work/deno/deno/cli/tests/testdata/workers/permissions_dynamic_remote.ts.out
[test_util/src/lib.rs:2148] part = "error: Uncaught (in promise) Error: Unhandled error in child worker.\n    at Worker.#pollControl ("
[test_util/src/lib.rs:2148] i = 1
[test_util/src/lib.rs:2154] "found " = "found "
[test_util/src/lib.rs:2154] found = 0
[test_util/src/lib.rs:2148] part = ")\n    at eventLoopTick (ext:core/01_core.js:"
[test_util/src/lib.rs:2148] i = 2
[test_util/src/lib.rs:2157] "exit false " = "exit false "
[test_util/src/lib.rs:2157] i = 2
OUTPUT START
error: Uncaught (in worker "") (in promise) TypeError: Requires net access to "example.com", run again with the --allow-net flag
await import("https://example.com/some/file.ts");
^
    at async http://localhost:4545/workers/dynamic_remote.ts:2:1
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:157:19)

OUTPUT END
EXPECTED START
error: Uncaught (in worker "") (in promise) TypeError: Requires net access to "example.com", run again with the --allow-net flag
await import("https://example.com/some/file.ts");
^
    at async http://localhost:4545/workers/dynamic_remote.ts:2:1
[WILDCARD]error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl ([WILDCARD])
    at eventLoopTick (ext:core/01_core.js:[WILDCARD])

EXPECTED END
thread 'integration::worker::worker_permissions_dynamic_remote' panicked at 'pattern match failed', cli/tests/integration/worker_tests.rs:66:1
stack backtrace:
   0:        0x10af9b8b6 - std::backtrace_rs::backtrace::libunwind::trace::hb6e20554c370f2e3
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10af9b8b6 - std::backtrace_rs::backtrace::trace_unsynchronized::h4cf6d4d5ecaf68bc
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10af9b8b6 - std::sys_common::backtrace::_print_fmt::h082ea160697d6d76
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10af9b8b6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h47bed05ceb7970ee
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10afbb23a - core::fmt::write::hefd823d99333384a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/fmt/mod.rs:1213:17
   5:        0x10af94f1c - std::io::Write::write_fmt::hd6cfc6ec52823bda
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/io/mod.rs:1682:15
   6:        0x10af9b69a - std::sys_common::backtrace::_print::hb9f21d71c6f0ffcc
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x10af9b69a - std::sys_common::backtrace::print::hc9e298c4664da113
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x10af9e093 - std::panicking::default_hook::{{closure}}::hb97411d6e916e1d2
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:267:22
   9:        0x10af9dd77 - std::panicking::default_hook::hc3ac81176817192f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:283:9
  10:        0x109689969 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h33b65fc09dc4712b
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002:9
  11:        0x109689969 - test::test_main::{{closure}}::h04be999e4627aa40
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:135:21
  12:        0x10af9e7f9 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h37363efbc7b1d5b1
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002:9
  13:        0x10af9e7f9 - std::panicking::rust_panic_with_hook::hc11209fa2686218a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:692:13
  14:        0x10af9e553 - std::panicking::begin_panic_handler::{{closure}}::h5bad1bd665ab68a6
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:577:13
  15:        0x10af9bd58 - std::sys_common::backtrace::__rust_end_short_backtrace::h6f4efa73918edf57
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
  16:        0x10af9e25d - rust_begin_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  17:        0x10afda8f3 - core::panicking::panic_fmt::hb5474ac70e328787
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  18:        0x109393f37 - test_util::builders::TestCommandOutput::inner_assert_matches_text::h26c319fc6a28b65f
  19:        0x10939394a - test_util::builders::TestCommandOutput::inner_assert_matches_file::h620945381a9afdf8
  20:        0x109393696 - test_util::builders::TestCommandOutput::assert_matches_file::hfc1ef03a17d491e7
  21:        0x1094bdc47 - integration_tests::integration::worker::worker_permissions_dynamic_remote::h0bf2a942ecd997c8
  22:        0x1094bd9f5 - integration_tests::integration::worker::worker_permissions_dynamic_remote::{{closure}}::hb1443cfc56aa1dc2
  23:        0x1093d08c8 - core::ops::function::FnOnce::call_once::h34eec8d8cf2226ca
  24:        0x10968e522 - core::ops::function::FnOnce::call_once::hdf207f94935181ff
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
  25:        0x10968e522 - test::__rust_begin_short_backtrace::h04732ed1b0d13b9c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:656:18
  26:        0x109660331 - test::run_test::{{closure}}::h6881e1606cdff666
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:647:30
  27:        0x109660331 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2d0f0110c4caa4c6
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
  28:        0x10968d23c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h76c402d58a93693d
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
  29:        0x10968d23c - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd0f3495dbedaa699
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
  30:        0x10968d23c - std::panicking::try::do_call::h046c53cf7d073423
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  31:        0x10968d23c - std::panicking::try::h338489c947964f34
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  32:        0x10968d23c - std::panic::catch_unwind::h8fefe5e585fb41ad
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  33:        0x10968d23c - test::run_test_in_process::hddf2afe31fc4920d
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:679:27
  34:        0x10968d23c - test::run_test::run_test_inner::{{closure}}::he439a141fa1b3e3d
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:573:39
  35:        0x10965ad5b - test::run_test::run_test_inner::{{closure}}::h43822ae05f9c70f8
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:600:37
  36:        0x10965ad5b - std::sys_common::backtrace::__rust_begin_short_backtrace::hce1badd8587a639f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:121:18
  37:        0x1096604e3 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h625dd5713e9f7e66
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/thread/mod.rs:558:17
  38:        0x1096604e3 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4430965d4790624c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
  39:        0x1096604e3 - std::panicking::try::do_call::ha35797bb6f94cf09
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  40:        0x1096604e3 - std::panicking::try::h7ba3e8b1fb3a832b
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  41:        0x1096604e3 - std::panic::catch_unwind::h3090ad4243b194a8
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  42:        0x1096604e3 - std::thread::Builder::spawn_unchecked_::{{closure}}::h544199ababb8db19
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/thread/mod.rs:557:30
  43:        0x1096604e3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hce3f92b3efd31c27
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
  44:        0x10afa4017 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd4e8d9c741b0560c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
  45:        0x10afa4017 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4d806e24df99a0d6
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
  46:        0x10afa4017 - std::sys::unix::thread::Thread::new::thread_start::had0599fead9033cd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys/unix/thread.rs:108:17
  47:     0x7ff812a9c4e1 - __pthread_start


failures:
    integration::worker::worker_permissions_dynamic_remote

test result: FAILED. 1073 passed; 1 failed; 6 ignored; 0 measured; 0 filtered out; finished in 352.70s
```

https://github.com/denoland/deno/actions/runs/4758311059/jobs/8456199843

**Comment by bartlomieju** [comment]
Fixed in https://github.com/denoland/deno/pull/18813
