### ISSUE TITLE
Deno.test() and `ignore: undefined`

### ISSUE THREAD

**Issue by cscheid** [denoland/deno#18784]
On 1.32.5, it seems that `Deno.test` doesn't like a configuration object where `ignore` is set to undefined.

In 1.28.2, we could say `Deno.test({ name = "...", ..., ignore: undefined })` and the test would work. In 1.32.5, this fails with the somewhat cryptic error message:

```
error: TypeError: Error parsing args at position 0: missing field `ignore`
  Deno.test(args);
       ^
    at Object.test (ext:cli/40_testing.js:675:30)
    at test (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/tests/test.ts:264:8)
```

It turns out that something in the rust side of Deno 1.32.5 now gets angry if you pass that optional field with an undefined. (the type for `Deno.TestDefinition` has ignore?: boolean). It's slightly annoying to not be able to write

```
const ignore: boolean | undefined = ...;
Deno.test({
  ignore,
  ...
})
```

Right now, we're working around by adding the following slightly silly check:

```
  if (args.ignore === undefined) {
    delete args.ignore;
  }
```

We can easily (if uglily) work around on our side, but I'm wondering if you consider this to be a bug.

**Comment by bartlomieju** [comment]
CC @nayeemrmn could you take a look?

**Comment by nayeemrmn** [comment]
Yeah it would be good form to add `#[serde(default)]` for boolean fields on rust options deserializers.
