### ISSUE TITLE
npm:mongodb URLSearchParams problem with whatwg-url

### ISSUE THREAD

**Issue by emehmet** [denoland/deno#18822]
Hi,

I am trying to use the npm:mongodb module. When I run my code, sometimes it runs correctly, but sometimes it throws an error like this;

```js
Error connecting to MongoDB:  TypeError: Cannot read properties of undefined (reading 'constructor')
    at new ConnectionString (file:///D:/deno.land/deno-gps-server-with-mqtt/node_modules/.deno/mongodb@5.3.0/node_modules/mongodb-connection-string-url/lib/index.js:153:98)
    at parseOptions (file:///D:/deno.land/deno-gps-server-with-mqtt/node_modules/.deno/mongodb@5.3.0/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (file:///D:/deno.land/deno-gps-server-with-mqtt/node_modules/.deno/mongodb@5.3.0/node_modules/mongodb/lib/mongo_client.js:46:63)
    at MongoDBDatabase.connect (file:///D:/deno.land/deno-gps-server-with-mqtt/src/db/Mongo.ts:156:27)
    at DBWorker.connectToDbAndPrepare (file:///D:/deno.land/deno-gps-server-with-mqtt/src/DBWorker.ts:45:28)
    at default.runServer (file:///D:/deno.land/deno-gps-server-with-mqtt/src/gps_server.ts:111:27)
    at file:///D:/deno.land/deno-gps-server-with-mqtt/src/main.ts:104:10
```

When I investigated the reason for this, I saw that searchParams was undefined on this.searchParams.constructor in the file:///D:/deno.land/deno-gps-server-with-mqtt/node_modules/.deno/mongodb@5.3.0/node_modules/mongodb-connection-string-url/lib/index.js:153:98 line.

I thought this might be related to the whatwg-url package and when I looked at the version in node_modules, I saw that it was 5.0.0. When I ran my code while keeping the package.json file of this module open, I noticed something. 
If my code is executed properly, the whatwg-url files change and the version becomes 11.0.0. But if my code gives the undefined error above, the whatwg-url package.json file changes and the version becomes 5.0.0.0. I don't understand the reason for this. 

You can see a video about this.

[Screen record](https://youtu.be/4BmXW0otpQs)

**Comment by dsherret** [comment]
Would you be able to share your code or the `deno info --json src/main.ts` output? Also, what version of Deno are you using?

**Comment by emehmet** [comment]
deno 1.32.5 (release, x86_64-pc-windows-msvc)
v8 11.2.214.9
typescript 5.0.3
