### ISSUE TITLE
deno-canvas fails to load image

### ISSUE THREAD

**Issue by backspaces** [denoland/deno#18876]
I put the following into module, denoerror.js, and run it via:

> deno run -A denoerror.js

With a https string, it produces an empty image. With a URL object, it produces an error.

Here is the denoerror.js file:
```
// Imports for canvas and image, see docs:
// https://deno.land/x/canvas@v1.4.1
// https://github.com/DjDeveloperr/deno-canvas
import {
    createCanvas,
    loadImage,
} from 'https://deno.land/x/canvas@v1.4.1/mod.ts'

// make sure above works:
console.log('createCanvas', createCanvas)
console.log('loadImage', loadImage)

// create a url to a mozilla image. (Droping the url in browser showed it exists)
const imgPath = 'https://developer.mozilla.org/assets/mdn_contributor.png'
const imgUrl = new URL(imgPath)

console.log('imgPath', imgPath)
console.log('imgUrl', imgUrl)

// load the image using http path. Result is empty object.
let img = await loadImage(imgPath)
console.log('img', img)

// try with Url object. Fails with error
img = await loadImage(imgUrl)
console.log('img', img)
```

Running it results in:
```
deno run -A denoerror.js
createCanvas [Function: createCanvas]
loadImage [AsyncFunction: loadImage]
imgPath https://developer.mozilla.org/assets/mdn_contributor.png
imgUrl URL {
  href: "https://developer.mozilla.org/assets/mdn_contributor.png",
  origin: "https://developer.mozilla.org",
  protocol: "https:",
  username: "",
  password: "",
  host: "developer.mozilla.org",
  hostname: "developer.mozilla.org",
  port: "",
  pathname: "/assets/mdn_contributor.png",
  hash: "",
  search: ""
}
img Image {}
error: Uncaught (in promise) TypeError: url.startsWith is not a function
  } else if (url.startsWith("http")) {
                 ^
    at loadImage (https://deno.land/x/canvas@v1.4.1/src/canvas.ts:23:18)
    at file:///Users/owen/Dropbox/src/agentscript/tests/denoerror.js:25:13
    at eventLoopTick (ext:core/01_core.js:165:11)

```

**Comment by sigmaSd** [comment]
this 
```
let img = await loadImage(imgPath)
console.log('img', img)
```
is correct,  `Image {}` is not an empty object, its an image Object, it has apis that you can check on docs of the module that uses it

this img = await loadImage(imgUrl) fails as expected becuase the fn doesn't expect a URL object
