### ISSUE TITLE
[npm] Non-canonicalized referrer causing module resolution errors

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#18924]
Ran into this issue while trying to get [Remix](https://remix.run/) to start with deno. Managed to create an isolated test case.

When deno installs an npm package behind the scenes it stores direct dependencies under `node_modules/<DEP>` and all other dependencies in a flat directory structure under `node_modules/.deno/<OTHER_DEP>@<VERSION>`.  Something in our resolution is wrong because although we install the `get-intrensic` package, we're unable to resolve it. 

My assumption is that we're missing a symlink in `node_modules`, but need to dig deeper.

### Steps to reproduce

1. Clone https://github.com/marvinhagemeister/deno-npm-dep-bug
2. Run `deno run -A index.js`

### Actual output

```sh
error: Uncaught Error: Cannot find module 'get-intrinsic'
```

### Expected output

```sh
true it works
```

**Comment by marvinhagemeister** [comment]
FWIW: Ran into the same bug with [SvelteKit](https://kit.svelte.dev/). Upon trying to run it with deno it cannot resolve a module.

**Comment by marvinhagemeister** [comment]
And can confirm that the same issue occurs when trying to run [Nuxt](https://nuxtjs.org/) with deno.

**Comment by dsherret** [comment]
The symlinks seem to be correct. Previously it was indeterministically creating some node_modules/<package-name> folders so it just happened to work and fixing this has exposed existing issues in the resolution.

![image](https://user-images.githubusercontent.com/1609021/235373108-c595b51e-14db-49fb-8ff2-54cfc2cc456e.png)

The error message is the following:

```
> deno run index.js  
✅ Granted read access to "V:\node_modules".
error: Uncaught Error: Cannot find module 'get-intrinsic'
Require stack:
- V:\deno-npm-dep-bug\node_modules\.deno\define-properties@1.2.0\node_modules\has-property-descriptors\./index.js
- V:\deno-npm-dep-bug\node_modules\.deno\define-properties@1.2.0\node_modules\define-properties\index.js
- V:\deno-npm-dep-bug\node_modules\.deno\define-properties@1.2.0\node_modules\define-properties\index.js
    at Function.Module._resolveFilename (ext:deno_node/01_require.js:834:15)
    at Function.Module._load (ext:deno_node/01_require.js:667:27)
    at Module.require (ext:deno_node/01_require.js:899:19)
    at require (ext:deno_node/01_require.js:1039:16)
    at Object.<anonymous> (file:///V:/deno-npm-dep-bug/node_modules/.deno/define-properties@1.2.0/node_modules/has-property-descriptors/index.js:3:20)
    at Object.<anonymous> (file:///V:/deno-npm-dep-bug/node_modules/.deno/define-properties@1.2.0/node_modules/has-property-descriptors/index.js:35:4)
    at Module._compile (ext:deno_node/01_require.js:966:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:999:10)
    at Module.load (ext:deno_node/01_require.js:877:32)
    at Function.Module._load (ext:deno_node/01_require.js:713:12)
```

I think probably the issue is that `V:\deno-npm-dep-bug\node_modules\.deno\define-properties@1.2.0\node_modules\has-property-descriptors\./index.js` is not canonicalized.
