### ISSUE TITLE
Error while `Kv.Set`  proxyfied object

### ISSUE THREAD

**Issue by shevernitskiy** [denoland/deno#18921]
I had a strange error.

Here is example

```ts
export async function persistent<T extends object>(
  defaults: T,
  callbacks: {
    read: () => Promise<T> | T;
    save: (value: T) => void;
  },
): Promise<T> {
  const readed = await callbacks.read();
  const store = { ...defaults, ...readed };

  const handler = {
    get(target: object, key: string | symbol) {
      if (key == "isProxy") return true;
      const prop = target[key];
      if (typeof prop == "undefined") return;
      if (!prop.isProxy && typeof prop === "object") {
        target[key] = new Proxy(prop, handler);
      }
      return target[key];
    },
    set(target: object, key: string | symbol, value: any) {
      target[key] = value;
      callbacks.save(store);
      return true;
    },
  };

  return new Proxy<T>(store, handler);
}

type Schema = {
  name: string;
  job: {
    salary: number;
  };
};

const defaults: Schema = {
  name: "John",
  job: {
    salary: 0,
  },
};

const kv = await Deno.openKv("./kv.db");

const state = await persistent<Schema>(defaults, {
  read: async () => {
    const readed = await kv.get<Schema>(["state"]);
    return readed.value ?? defaults;
  },
  save: (value: Schema) => kv.set(["state"], value),
});

state.name = "No deep proxy"; //works
state.job.salary = 69; // error here!

```

Error output:
```shell
error: Uncaught (in promise) TypeError: #<Object> could not be cloned.
  save: (value: Schema) => kv.set(["state"], value),
                              ^
    at Object.serialize (ext:core/01_core.js:489:14)
    at serializeValue (ext:deno_kv/01_db.ts:281:25)
    at Kv.set (ext:deno_kv/01_db.ts:60:17)
    at Object.save (file:///E:/programming/ts/persistent-object/run.ts:50:31)
    at Object.set (file:///E:/programming/ts/persistent-object/run.ts:22:17)
    at file:///E:/programming/ts/persistent-object/run.ts:54:17
 ```
 
Not nested mutation works well, deep nested fails. The same example but with file read/save works well.
 I know that get/set kv method is async. 

- deno 1.33.1 (release, x86_64-pc-windows-msvc)
- v8 11.4.183.1
- typescript 5.0.3

**Comment by gliheng** [comment]
When you save it the second time, store passed to deno was actually ```
job: Proxy(Object) {salary: 69}
name: "No deep proxy"
```

I changed this line `target[key] = new Proxy(prop, handler)` to `return new Proxy(prop, handler)` and it works.

**Comment by shevernitskiy** [comment]
> When you save it the second time, store passed to deno was actually
> 
> ```
> job: Proxy(Object) {salary: 69}
> name: "No deep proxy"
> ```
> 
> I changed this line `target[key] = new Proxy(prop, handler)` to `return new Proxy(prop, handler)` and it works.

Is really is! Thanks!
