### ISSUE TITLE
needs better stack trace...

### ISSUE THREAD

**Issue by jimmywarting** [denoland/deno#18946]
can't for the life of me figure out where this error comes from:

this is all i have to work on in a large codebase:

```
error: Uncaught (in promise) Interrupted: operation canceled
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async Object.pull (ext:deno_web/06_streams.js:744:27)
```

...which isn't much.

**Comment by bartlomieju** [comment]
Unfortunately this appears to be a limitation of V8 - we tried several times to provide better async stack traces, but we never got far. I can give it another go later this week, but can't promise much.

**Comment by sigmaSd** [comment]
Here is a reproduction from dsherret

```ts
async function a() {
  await new Promise((_resolve, reject) => {
    setTimeout(() => {
      reject(new Error("test"));
    }, 20);
  });
}

try {
  await a();
} catch (err) {
  console.log(err.stack);
}
```

**Comment by nayeemrmn** [comment]
> Here is a reproduction from dsherret
> 
> ```ts
> async function a() {
>   await new Promise((_resolve, reject) => {
>     setTimeout(() => {
>       reject(new Error("test"));
>     }, 20);
>   });
> }
> 
> try {
>   await a();
> } catch (err) {
>   console.log(err.stack);
> }
> ```

```
Error: test
    at file:///home/nayeem/projects/deno/temp.ts:4:14
    at Object.action (ext:deno_web/02_timers.js:153:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:67:10)
    at eventLoopTick (ext:core/01_core.js:189:21)
```

This behaves as expected, the error is constructed in the timeout callback so that's all there is to give in its stack.
![image](https://github.com/denoland/deno/assets/29990554/aaa38fd9-6eb6-43a9-8e9f-02cc0ccb079a)

**Comment by sigmaSd** [comment]
I see, so is this similar 


```js
import { $ } from "https://deno.land/x/dax@0.32.0/mod.ts";
await $`donotexistbinary`;
```
```
Uncaught Error: Command not found: donotexistbinary
    at resolveCommand (https://deno.land/x/dax@0.32.0/src/shell.ts:773:11)
    at eventLoopTick (ext:core/01_core.js:182:11)
    at async executeCommandArgs (https://deno.land/x/dax@0.32.0/src/shell.ts:5
71:27)
    at async executeSimpleCommand (https://deno.land/x/dax@0.32.0/src/shell.ts
:560:10)
    at async executeSequentialList (https://deno.land/x/dax@0.32.0/src/shell.t
s:386:20)
    at async spawn (https://deno.land/x/dax@0.32.0/src/shell.ts:375:18)
    at async CommandChild.pipedStdoutBuffer (https://deno.land/x/dax@0.32.0/sr
c/command.ts:572:20)
```
the stack trace doesn't reach user code

And if it's the case, are there ways to improve it, because it's annoying when it happens in dax

**Comment by devsnek** [comment]
This is a limitation of executing async callbacks. The callers are no longer on the stack when the callback runs so they can't appear in a stack trace.
