### ISSUE TITLE
HTTPS request with encrypted private key

### ISSUE THREAD

**Issue by denizdogan** [denoland/deno#19052]
In Node.js, one can do the following in order to make HTTP requests to a server with custom certificates and an (encrypted) private key:

```
    httpsAgent: new Agent({
      ca: ca,
      key: key,
      passphrase: secret,
      cert: key,
      secureProtocol: "TLSv1_2_method",
      rejectUnauthorized: true,
      requestCert: true,
    }),
```

Is there anything like this in Deno? I couldn't find any such option in `Deno.createHttpClient`.

If this does not exist, and we want it, I could start working on a PR.

**Comment by jshbrntt** [comment]
I found this issue of Deno caused `401 Unauthorized` errors when trying to use [`@kubernetes/client-node`](https://github.com/kubernetes-client/javascript) to communicate with a locally running [`k3s`](https://k3s.io/) which generates cluster.

Because API authentication is done through certificates presented by the client when connecting over HTTPS, and it is not possible to customize the HTTPS agent to make use of the client cert and key. Then the library cannot authenticate correctly with the cluster's API server.

This does not appear to be an issue in Node.

### Test script
```typescript
import * as k8s from '@kubernetes/client-node';

const kc = new k8s.KubeConfig()
kc.loadFromFile('../../kubeconfig');

const k8sCoreApi = kc.makeApiClient(k8s.CoreV1Api);

try {
  const nodeList = await k8sCoreApi.listNode();
  for (const item of nodeList.items) {
    console.log(item.metadata?.name);
  }
} catch (error) {
  console.error(error);
}
```

### Deno
```shell
$ deno run -A main.ts
FetchError: request to https://localhost:6443/api/v1/nodes failed, reason: connection error
    at HttpsClientRequest.<anonymous> (file:///Users/joshua.barnett/Library/Caches/deno/npm/registry.npmjs.org/node-fetch/2.7.0/lib/index.js:1501:11)
    at HttpsClientRequest.emit (ext:deno_node/_events.mjs:393:28)
    at node:http:477:16
    at eventLoopTick (ext:core/01_core.js:177:7) {
  message: "request to https://localhost:6443/api/v1/nodes failed, reason: connection error",
  type: "system",
  errno: undefined,
  code: undefined
}
```

### Node
```shell
$ node main.mjs 
V1NodeSystemInfo {
  architecture: 'arm64',
  bootID: 'ef3ef8ec-0c02-4934-9de3-ff00fbee2448',
  containerRuntimeVersion: 'containerd://2.0.2-k3s2',
  kernelVersion: '6.12.5-linuxkit',
  kubeProxyVersion: 'v1.32.2+k3s1',
  kubeletVersion: 'v1.32.2+k3s1',
  machineID: '',
  operatingSystem: 'linux',
  osImage: 'K3s v1.32.2+k3s1',
  systemUUID: ''
}
```

**Comment by Crylion** [comment]
Same problem here :/
I need to use an encrypted key to use the Bosch smarthome rest api (https://github.com/BoschSmartHome/bosch-shc-api-docs/tree/master/best_practice#host-verification), but when I use node-fetch to do so, it only works using nodejs.
Running the app with deno, it throws the same cryptic `reason: connection error` error that @jshbrntt mentioned

**Comment by Crylion** [comment]
Honestly, even the most simplified test with an already decrypted key produces the same error and I just can't figure out why, because the node internals are such a headache to debug.

Example:
```
import https from 'node:https';

const cert = Deno.readTextFileSync(path.resolve(import.meta.dirname ?? '', '../bosch-cert.pem'));
const key = Deno.readTextFileSync(path.resolve(import.meta.dirname ?? '', '../bosch-key.pem'));

const httpsAgent = new https.Agent({
  cert: cert,
  key: key,
  rejectUnauthorized: false
});

https.request({
  hostname: Deno.env.get('BOSCH_SERVER_URL'),
  port: 8444,
  path: '/smarthome/rooms',
  headers: {
    'api-version': '3.12',
    'Content-Type': 'application/json'
  },
  method: 'GET',
  agent: this.httpsAgent
}, (res) => {
  res.on('data', (d) => {
    process.stdout.write(d);
  });
})
```

Results in the very unhelpful:
```
error: Uncaught (in promise) Http: connection error
    at async node:http:400:21
```

**Comment by bartlomieju** [comment]
This works now. The real-world cases reported here all used `node:https.Agent` with `cert`/`key`/`passphrase`, and that path is fully functional on current canary (`deno 2.8.1`), including encrypted (passphrase-protected) client keys.

Verified end-to-end with a mutual-TLS setup, a server that requires and verifies client certs, and a client presenting an AES-256 encrypted client key + passphrase over `node:https`:

```js
// client.mjs
import https from "node:https";
import fs from "node:fs";
const agent = new https.Agent({
  cert: fs.readFileSync("client.crt"),
  key: fs.readFileSync("client.key"),   // BEGIN ENCRYPTED PRIVATE KEY
  passphrase: "secret",
  ca: fs.readFileSync("ca.crt"),
});
// -> server responds: "hello client CN=test-client" (handshake + client-cert verification succeed)
```

The node TLS layer decrypts passphrase-protected keys before handing them to rustls (`ext/node/polyfills/_tls_common.ts`), and `_tls_wrap.js` has full client-cert / mTLS support. So `@kubernetes/client-node`, the Bosch SHC API, and similar libraries that rely on `https.Agent` client certs now work.

Native `Deno.createHttpClient` also supports client certs via `{ cert, key }` (verified with mTLS). It does not yet take a `passphrase` for encrypted keys, but you can decrypt first with `node:crypto`:

```js
import { createPrivateKey } from "node:crypto";
const key = createPrivateKey({ key: encryptedPem, passphrase: "secret" })
  .export({ type: "pkcs8", format: "pem" });
const client = Deno.createHttpClient({ cert, key });
```

Closing as resolved. If a first-class `passphrase` option on `Deno.createHttpClient` is wanted, that is worth a small focused feature request.

**Comment by Crylion** [comment]
@bartlomieju Very nice! It's very rare that a stale issue like that, that just a few of people shared, actually gets resolved. Same code from a year ago just magically works now 😁
