### ISSUE TITLE
[node compact] `yeoman generator` CJS `module.parent.filename` got `Uncaught TypeError: Cannot read properties of undefined (reading 'filename')`

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#19105]
### Keyword

- yeoman generator

- CJS `module.parent.filename`

### Version

```sh
$ deno --version
deno 1.33.2 (release, x86_64-unknown-linux-gnu)
v8 11.4.183.1
typescript 5.0.3
```

### Reproduce
```sh
$ deno run -A npm:yo webapp
error: Uncaught TypeError: Cannot read properties of undefined (reading 'filename')
    at Object.<anonymous> (file:///home/vscode/.cache/deno/npm/verdaccio/meow/5.0.0/index.js:15:46)
    at Object.<anonymous> (file:///home/vscode/.cache/deno/npm/verdaccio/meow/5.0.0/index.js:114:4)
    at Module._compile (ext:deno_node/01_require.js:968:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:1001:10)
    at Module.load (ext:deno_node/01_require.js:879:32)
    at Function.Module._load (ext:deno_node/01_require.js:713:12)
    at Module.require (ext:deno_node/01_require.js:901:19)
    at require (ext:deno_node/01_require.js:1041:16)
    at Object.<anonymous> (file:///home/vscode/.cache/deno/npm/verdaccio/yo/4.3.1/lib/cli.js:9:14)
    at Object.<anonymous> (file:///home/vscode/.cache/deno/npm/verdaccio/yo/4.3.1/lib/cli.js:190:4)
```

**Comment by marvinhagemeister** [comment]
Thanks for filing a report. I'd love to take a look at this but I'm not sure how I can reproduce this error on my end. Do you have a repository you can share where we can run the given command `deno run -A npm:yo webapp` to reproduce the error?

**Comment by loynoir** [comment]
@marvinhagemeister 

I believe 

```sh
$ deno run -A npm:yo webapp
```

is a very neat equivalent, compared to node

```sh
$ npm install --global yo generator-webapp
$ yo webapp
```

And `yeoman` generate project scaffold.

So, should run command within any empty directory.

**Comment by marvinhagemeister** [comment]
Thank you for providing the steps to reproduce this issue. I can see the error on my machine now.

Can confirm that the issue is that deno doesn't shim the `module.parent` property. For reference: Node's documentation has a little passage on how it's supposed to work: https://nodejs.org/api/modules.html#moduleparent .

**Comment by bartlomieju** [comment]
I just tried on Deno v2.1.2 and this works correctly: `deno run -A --unstable-proto npm:yo webapp.
