### ISSUE TITLE
"node:http" doesn't implement "Server.unref()" API

### ISSUE THREAD

**Issue by tigitz** [denoland/deno#19113]
A simple crawling example from the documentation:

```ts
// Add import of CheerioCrawler
import { RequestQueue, CheerioCrawler } from 'npm:crawlee';

const requestQueue = await RequestQueue.open();
await requestQueue.addRequest({ url: 'https://crawlee.dev' });

// Create the crawler and add the queue with our URL
// and a request handler to process the page.
const crawler = new CheerioCrawler({
    requestQueue,
    // The `$` argument is the Cheerio object
    // which contains parsed HTML of the website.
    async requestHandler({ $, request }) {
        // Extract <title> text with Cheerio.
        // See Cheerio documentation for API docs.
        const title = $('title').text();
        console.log(`The title of "${request.url}" is: ${title}.`);
    }
})

// Start the crawler and wait for it to finish
await crawler.run();
```
Straight up raise the following error
```
error: Uncaught TypeError: server.server.unref is not a function
    at Object.<anonymous> (file:///home/deno/.cache/deno/npm/registry.npmjs.org/@crawlee/browser-pool/3.3.2/proxy-server.js:8:15)
    at Object.<anonymous> (file:///home/deno/.cache/deno/npm/registry.npmjs.org/@crawlee/browser-pool/3.3.2/proxy-server.js:19:4)
    at Module._compile (ext:deno_node/01_require.js:966:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:999:10)
    at Module.load (ext:deno_node/01_require.js:877:32)
    at Function.Module._load (ext:deno_node/01_require.js:713:12)
    at Module.require (ext:deno_node/01_require.js:899:19)
    at require (ext:deno_node/01_require.js:1039:16)
    at Object.<anonymous> (file:///home/deno/.cache/deno/npm/registry.npmjs.org/@crawlee/browser-pool/3.3.2/playwright/playwright-plugin.js:13:24)
    at Object.<anonymous> (file:///home/deno/.cache/deno/npm/registry.npmjs.org/@crawlee/browser-pool/3.3.2/playwright/playwright-plugin.js:174:4)
```

Looking for this error in previous issues it might be related to:
- https://github.com/denoland/deno/issues/16647
- https://github.com/denoland/deno/issues/16899

@bartlomieju friendly ping for your April/May NPM compatibility list

**Comment by bartlomieju** [comment]
@mmastrac any thoughts on implementing `Deno.serve().unref()`? It's probably useful to have it available on our server API and doing that would make fixing this issue a couple lines of code.
