### ISSUE TITLE
Unable to print `URL.prototype` in repl

### ISSUE THREAD

**Issue by nicolo-ribaudo** [denoland/deno#19128]
I was trying to see what methods `URL.prototype` contains, but I get this inspection error:
```
➜ deno
Deno 1.33.3
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> URL.prototype
TypeError: Illegal invocation
    at Module.assertBranded (ext:deno_webidl/00_webidl.js:1003:11)
    at URL.get href (ext:deno_url/00_url.js:518:12)
    at URL.[Deno.privateCustomInspect] (ext:deno_url/00_url.js:393:18)
    at formatValue (ext:deno_console/01_console.js:652:48)
    at Object.inspectArgs (ext:deno_console/01_console.js:3097:28)
    at <anonymous>:3:55
```

`delete URL.prototype[Symbol.for("Deno.privateCustomInspect")]` works around the problem.

**Comment by crowlKats** [comment]
Closing as this is fixed.
