### ISSUE TITLE
[`napi`] current `require()` implement `stackTrace` may not correct

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#19130]
### Given

- `napi` module `napi-example@1.0.0` contains gyp related code, and js code

```js
module.exports.foobar = require('bindings')('foobar')
```

- publish `napi-example@1.0.0` to private npm

### Actual

Looking for wrong `bindings/1.5.0/build/foobar.node`.

<details>
  <summary markdown="span">detail</summary>

```js
> var mod = await import('npm:napi-example@1.0.0')
Uncaught Error: Could not locate the bindings file. Tried:
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/build/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/build/Debug/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/build/Release/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/out/Debug/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/Debug/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/out/Release/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/Release/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/build/default/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/compiled/18.12.1/linux/x64/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/addon-build/release/install-root/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/addon-build/debug/install-root/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/addon-build/default/install-root/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/lib/binding/node-v108-linux-x64/foobar.node
    at bindings (file:///home/vscode/.cache/deno/npm/private-npm/bindings/1.5.0/bindings.js:126:9)
    at Object.<anonymous> (file:///home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/internal/extension/cjs-wrapper.cjs:1:286)
    at Object.<anonymous> (file:///home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/internal/extension/cjs-wrapper.cjs:17:4)
    at Module._compile (ext:deno_node/01_require.js:968:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:1001:10)
    at Module.load (ext:deno_node/01_require.js:879:32)
    at Function.Module._load (ext:deno_node/01_require.js:713:12)
    at Module.require (ext:deno_node/01_require.js:901:19)
    at require (ext:deno_node/01_require.js:1041:16)
    at file:///home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/internal/extension/cjs-wrapper.cjs:3:13
```

</details>

### Expected

Looking for correct `napi-example/1.0.0/build/foobar.node`.

<details>
  <summary markdown="span">detail</summary>

```txt
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/build/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/build/Debug/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/build/Release/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/out/Debug/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/Debug/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/out/Release/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/Release/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/build/default/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/compiled/18.12.1/linux/x64/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/addon-build/release/install-root/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/addon-build/debug/install-root/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/addon-build/default/install-root/foobar.node
 → /home/vscode/.cache/deno/npm/private-npm/napi-example/1.0.0/lib/binding/node-v108-linux-x64/foobar.node
```

</details>

### Related

https://github.com/TooTallNate/node-bindings/blob/1.5.0/bindings.js#L82

### Workaround

```js
module.exports.foobar = require('../hard/coded/path/to/foobar.node')
```

**Comment by ealib** [comment]
Perhaps it is related to the missing functionality of importing native Node.js modules. See issue #17246 .

**Comment by ealib** [comment]
@loynoir excuse me, but I do not understand what you mean by "controling variates".

I understand, however, that the bug you report here has nothing to do with #17246 , but is related to the implementation of `import` in Deno.

I did not intentionally try Node ESM import, because I do not want to maintain [double-sided code](https://github.com/nodejs/node/issues/40541) since Deno should make the use of Node.js modules prefixed with `"npm:..."` transparent. 

I mean, if @bartlomieju says that `import ... from "npm: ..."` will never be able to distinguish between ES/TS source modules and native binary modules, then I'll be content and use `import`.

**Comment by bartlomieju** [comment]
@loynoir any chance you could provide a reproducible example (or a repo) that I could try for debugging this problem?

**Comment by reggi** [comment]
```
deno eval 'import "npm:sqlite3"'
```
