### ISSUE TITLE
`URLPattern.prototype`: get access throws `TypeError`

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno#19140]
via `deno repl`:

```console
> URLPattern.prototype
TypeError: Illegal invocation
    at Module.assertBranded (ext:deno_webidl/00_webidl.js:1003:11)
    at URLPattern.get protocol (ext:deno_url/01_urlpattern.js:84:12)
    at URLPattern.[Deno.customInspect] (ext:deno_url/01_urlpattern.js:215:24)
    at formatValue (ext:deno_console/01_console.js:643:41)
    at Object.inspectArgs (ext:deno_console/01_console.js:3097:28)
    at <anonymous>:3:55
```

should instead return something more like accessing `URLSearchParams`:

```console
> URLSearchParams.prototype
Object [URLSearchParams] {
  append: [Function: append],
  delete: [Function: delete],
  getAll: [Function: getAll],
  get: [Function: get],
  has: [Function: has],
  set: [Function: set],
  sort: [Function: sort],
  toString: [Function: toString],
  size: [Getter],
  entries: [Function: entries],
  keys: [Function: keys],
  values: [Function: values],
  forEach: [Function: forEach]
}
```

**Comment by crowlKats** [comment]
Closing as fixed
