### ISSUE TITLE
deno_fetch panic `Unknown TLS backend passed to "use_preconfigured_tls"`

### ISSUE THREAD

**Issue by hasezoey** [denoland/deno#19177]
full error:

```txt
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.33.3
Args: ["deno", "run", "--allow-read", "--allow-write", "./test.mjs"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: "Unknown TLS backend passed to `use_preconfigured_tls`" }', /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_fetch-0.128.0/lib.rs:703:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: deno_fetch::create_http_client
   4: once_cell::imp::OnceCell<T>::initialize::{{closure}}
   5: once_cell::imp::initialize_or_wait
   6: once_cell::imp::OnceCell<T>::initialize
   7: deno::http_util::HttpClient::download_text::{{closure}}
   8: <deno::tools::upgrade::RealUpdateCheckerEnvironment as deno::tools::upgrade::UpdateCheckerEnvironment>::latest_version::{{closure}}
   9: deno::tools::upgrade::check_for_upgrades::{{closure}}
  10: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  11: tokio::runtime::task::core::Core<T,S>::poll
  12: tokio::runtime::task::harness::Harness<T,S>::poll
  13: tokio::runtime::scheduler::current_thread::Context::run_task
  14: tokio::macros::scoped_tls::ScopedKey<T>::set
  15: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  16: tokio::runtime::runtime::Runtime::block_on
  17: deno_runtime::tokio_util::run_local
  18: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

code that results in this issue:

```js
import { createUnzip } from 'node:zlib';
import { createReadStream, createWriteStream } from 'node:fs';

const writestream = createWriteStream('./archive.tar');

createReadStream('./archive.tgz').pipe(createUnzip()).pipe(writestream);

console.log('done');
```

run with `deno run --allow-read --allow-write ./test.mjs`

archive used for testing (related to another issue i am debugging) is `https://fastdl.mongodb.org/linux/mongodb-linux-aarch64-ubuntu2204-6.0.4.tgz` renamed to `archive.tgz`

versions:
deno 1.33.3 (also happens on 1.33.2 and maybe before)
manjaro 22.1.1
installed through `cargo install deno`

PS: a re-install of deno does not solve the issue

**Comment by mmastrac** [comment]
This suggests there might be a conflict between rustls versions used by deno-fetch and reqwest. 

https://github.com/seanmonstar/reqwest/blob/abb729fc3d68ff1446b697e468ab1181c686489d/src/async_impl/client.rs#L1377

Does this happen if you use the pre-built Deno binaries, or build from a git clone of `main`?

**Comment by hasezoey** [comment]
downloading and running https://github.com/denoland/deno/releases/download/v1.33.4/deno-x86_64-unknown-linux-gnu.zip and https://github.com/denoland/deno/releases/download/v1.33.3/deno-x86_64-unknown-linux-gnu.zip do not result in the error after run

in deno 1.33.4 installed through cargo also does not have any problems anymore, the same also when re-installing 1.33.3

i have no clue what happened or why it is fixed, but the issue is solved for me for now

PS: i did not update the system in the time i have created the issue
