### ISSUE TITLE
ReadError: The server aborted pending request (supposedly at IncomingMessageForClient._destroy (ext:deno_node/http.ts:759:18))

### ISSUE THREAD

**Issue by tigitz** [denoland/deno#19238]
After https://github.com/denoland/deno/issues/19215 was fixed I've tried to run the code example in https://github.com/denoland/deno/issues/19113 again.

Deno was built from source from latest commit: https://github.com/denoland/deno/commit/787e1f0f92e81f025ec0dfdce2acff15900267fc

I've stumbled upon this error this time:

```
ERROR CheerioCrawler: Request failed and reached maximum retries. ReadError: The server aborted pending request
    at IncomingMessageForClient.<anonymous> (file:///home/psegatori/.cache/deno/npm/registry.npmjs.org/got-cjs/12.5.4/dist/source/core/index.js:618:31)
    at Object.onceWrapper (ext:deno_node/_stream.mjs:1927:32)
    at IncomingMessageForClient.emit (ext:deno_node/_stream.mjs:1857:11)
    at IncomingMessageForClient.origin.emit (file:///home/psegatori/.cache/deno/npm/registry.npmjs.org/@szmarczak/http-timer/4.0.6/dist/source/index.js:43:20)
    at IncomingMessageForClient._destroy (ext:deno_node/http.ts:759:18)
    at _destroy (ext:deno_node/_stream.mjs:1538:15)
    at IncomingMessageForClient.destroy (ext:deno_node/_stream.mjs:1508:9)
    at endReadableNT (ext:deno_node/_stream.mjs:3655:20)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:31:29)
    at runNextTicks (ext:deno_node/_next_tick.ts:69:5)
```
@crowlKats @bartlomieju friendly ping for the follow-up as it might be related to the last fix.

Thanks for your patience and hard work guys. Hopefully we're close :slightly_smiling_face:

**Comment by bartlomieju** [comment]
Hey @tigitz, I just tried your example again and I get a completely different error like this:
```
env CRAWLEE_VERBOSE_LOG=true ../deno/target/debug/deno run -A --node-modules-dir crawlee.js
INFO  CheerioCrawler: Starting the crawl
WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Error: Errors { invalid_mapping, disallowed_character }
    at Object.toASCII (ext:deno_node/punycode.ts:5:16)
    at file:///Users/ib/dev/try_http_client/node_modules/.deno/psl@1.9.0/node_modules/psl/index.js:44:34
    at Array.reduce (<anonymous>)
    at Object.internals.findRule (file:///Users/ib/dev/try_http_client/node_modules/.deno/psl@1.9.0/node_modules/psl/index.js:41:26)
    at Object.exports.parse (file:///Users/ib/dev/try_http_client/node_modules/.deno/psl@1.9.0/node_modules/psl/index.js:198:24)
    at Object.exports.get (file:///Users/ib/dev/try_http_client/node_modules/.deno/psl@1.9.0/node_modules/psl/index.js:258:18)
    at Object.getPublicSuffix (file:///Users/ib/dev/try_http_client/node_modules/.deno/tough-cookie@4.1.2/node_modules/tough-cookie/lib/pubsuffix-psl.js:70:14)
    at permuteDomain (file:///Users/ib/dev/try_http_client/node_modules/.deno/tough-cookie@4.1.2/node_modules/tough-cookie/lib/permuteDomain.js:38:28)
    at MemoryCookieStore.findCookies (file:///Users/ib/dev/try_http_client/node_modules/.deno/tough-cookie@4.1.2/node_modules/tough-cookie/lib/memstore.js:99:21)
    at MemoryCookieStore.findCookies (file:///Users/ib/dev/try_http_client/node_modules/.deno/universalify@0.2.0/node_modules/universalify/index.js:5:67)
```

Could you provide the reproduction you're using to get the error you see?

**Comment by tigitz** [comment]
@bartlomieju yeah you're hitting https://github.com/denoland/deno/issues/19214 that I've manually edited in the lib to bypass this specific test and check if the following logic would succeed. 

Which it didn't as per this issue.

**Comment by bartlomieju** [comment]
Could you tell me how I can bypass that check myself?

**Comment by tigitz** [comment]
Sure I'm on the phone right now so sorry for the formating but it's something along the line of

```js
 
 ​    ​if​ ​(​rule​.​punySuffix​ ​===​ ​-​1​)​ ​{ 
       if(rule​.​suffix === '个��.hk' ) {
         rule​.​punySuffix​ ​=​ 'foobar' 
     } else{
 ​      ​rule​.​punySuffix​ ​=​ ​Punycode​.​toASCII​(​rule​.​suffix​)​;
} 
 ​    ​}

```

At https://github.com/lupomontero/psl/blob/main/index.js#L44

Thanks for the follow up 👍
