### ISSUE TITLE
node:http - top level promise is never resolved

### ISSUE THREAD

**Issue by jasl** [denoland/deno#19263]
This piece of code won't work on 1.34.0 but worked on 1.33.3

```
import { Akord, Auth } from "npm:@akord/akord-js@4.10.1";
import { AkordWallet } from "npm:@akord/crypto";

Auth.configure({ storage: localStorage });
Auth.configure({ apiKey: "l8WMh6UsTd7LiGzI5cHeI5G9rpSVB5yC2gnNsfCa" });

const wallet = await AkordWallet.importFromBackupPhrase("poverty gate report bullet culture gift review pottery door spell try choice");
const akord = await Akord.init(wallet);

const { vaultId } = await akord.vault.create("my first vault");
console.log(vaultId);
```

> The sensitive key is just for testing, so ok to be public here, I'll delete the account after the issue close

```
$ deno --version
deno 1.34.0 (release, aarch64-apple-darwin)
v8 11.5.150.1
typescript 5.0.4

$ deno run --allow-all test.ts
error: Top-level await promise never resolved
const { vaultId } = await akord.vault.create("my first vault");
                    ^
    at <anonymous> (file:///Users/jasl/Workspaces/BlockChain/cybros-network/tmp/test2.ts:10:21)
```

The behavior in 1.33.3 is expected

```
$ deno --version
deno 1.33.3 (release, x86_64-unknown-linux-gnu)
v8 11.4.183.2
typescript 5.0.4

$ deno run --allow-all test.ts
error: Uncaught (in promise) Error: Invalid authorization header.
    at throwError (file:///home/jasl/.cache/deno/npm/registry.npmjs.org/@akord/akord-js/4.10.1/lib/errors/error.js:14:19)
    at ApiClient.<anonymous> (file:///home/jasl/.cache/deno/npm/registry.npmjs.org/@akord/akord-js/4.10.1/lib/api/api-client.js:288:40)
    at Generator.throw (<anonymous>)
    at rejected (file:///home/jasl/.cache/deno/npm/registry.npmjs.org/@akord/akord-js/4.10.1/lib/api/api-client.js:6:65)
    at Object.runMicrotasks (ext:core/01_core.js:830:30)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:51:14)
    at runNextTicks (ext:deno_node/_next_tick.ts:69:5)
    at eventLoopTick (ext:core/01_core.js:187:21)
```

**Comment by bartlomieju** [comment]
Thanks for the report, this is probably related to the `node:http` client rewrite we did. We'll look into it.
