### ISSUE TITLE
Panic when running `deno check`/`deno test`

### ISSUE THREAD

**Issue by jonasb** [denoland/deno#19299]
When running `RUST_BACKTRACE=1 deno check -q src/mod.ts` in `libraries/deno-postgres` in https://github.com/dossierhq/dossierhq/ I get this panic.

**Note:** the repo is a mono repo using [rush](https://rushjs.io/) as the mono rep orchestrator, with [pnpm](https://pnpm.io/) as the package manager. So `libraries/deno-postgres/node_modules` is created by pnpm, not by deno.

```
Platform: macos aarch64
Version: 1.34.0
Args: ["deno", "check", "-q", "src/mod.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/npm/resolvers/local.rs:89:29
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::Option<T>::unwrap
   4: deno::npm::resolvers::local::LocalNpmPackageResolver::resolve_package_root
   5: <deno::npm::resolvers::local::LocalNpmPackageResolver as deno::npm::resolvers::common::NpmPackageFsResolver>::resolve_package_folder_from_specifier
   6: deno::npm::resolvers::CliNpmResolver::resolve_package_folder_from_specifier
   7: <deno::npm::resolvers::CliNpmResolver as deno_node::NpmResolver>::in_npm_package
   8: deno::tsc::op_is_node_file::call
   9: deno::tsc::op_is_node_file::v8_fn_ptr
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Same for `RUST_BACKTRACE=1 deno test -A`:

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.34.0
Args: ["deno", "test", "-A"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/npm/resolvers/local.rs:89:29
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::Option<T>::unwrap
   4: deno::npm::resolvers::local::LocalNpmPackageResolver::resolve_package_root
   5: <deno::npm::resolvers::local::LocalNpmPackageResolver as deno::npm::resolvers::common::NpmPackageFsResolver>::resolve_package_folder_from_specifier
   6: deno::npm::resolvers::CliNpmResolver::resolve_package_folder_from_specifier
   7: <deno::npm::resolvers::CliNpmResolver as deno_node::NpmResolver>::in_npm_package
   8: deno::tsc::op_is_node_file::call
   9: deno::tsc::op_is_node_file::v8_fn_ptr
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by verikono** [comment]
`============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.34.3
Args: ["deno", "test", "--watch"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/npm/resolvers/local.rs:94:29
stack backtrace:
   0:     0x55df702a697a - std::backtrace_rs::backtrace::libunwind::trace::ha271a8a7e1f3d4ef
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55df702a697a - std::backtrace_rs::backtrace::trace_unsynchronized::h85739da0352c791a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55df702a697a - std::sys_common::backtrace::_print_fmt::hbc6ebcfb2910b329
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55df702a697a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55df702d315e - core::fmt::write::h25eb51b9526b8e0c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/fmt/mod.rs:1213:17
   5:     0x55df7029d705 - std::io::Write::write_fmt::ha9edec5fb1621933
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/io/mod.rs:1682:15
   6:     0x55df702a6745 - std::sys_common::backtrace::_print::hf8657cd429fc3452
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55df702a6745 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55df702a853f - std::panicking::default_hook::{{closure}}::h22a91871f4454152
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:267:22
   9:     0x55df702a827b - std::panicking::default_hook::h21ddc36de0cd4ae7
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:286:9
  10:     0x55df706a3eb7 - deno::setup_panic_hook::{{closure}}::hfcd28287625df769
  11:     0x55df702a8cca - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6f7e3c94ecc52e2f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002:9
  12:     0x55df702a8cca - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:692:13
  13:     0x55df702a8a02 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:577:13
  14:     0x55df702a6e2c - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x55df702a8752 - rust_begin_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  16:     0x55df702d0613 - core::panicking::panic_fmt::hd1d46bcde3c61d72
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  17:     0x55df702d06ad - core::panicking::panic::h056c466ab4571cf2
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
  18:     0x55df703a97e7 - core::option::Option<T>::unwrap::h2991178b7645a5e4
  19:     0x55df70611dee - deno::npm::resolvers::local::LocalNpmPackageResolver::resolve_package_root::h973e892587e929ff
  20:     0x55df707152b6 - <deno::npm::resolvers::local::LocalNpmPackageResolver as deno::npm::resolvers::common::NpmPackageFsResolver>::resolve_package_folder_from_specifier::h27ff473b9b063652
  21:     0x55df706165b8 - deno::npm::resolvers::CliNpmResolver::resolve_package_folder_from_specifier::hc80926650667a64b
  22:     0x55df70617e3f - <deno::npm::resolvers::CliNpmResolver as deno_node::NpmResolver>::in_npm_package::h597891bfaf3d41f3
  23:     0x55df7073dc4e - deno::tsc::op_is_node_file::call::h096203796fce8180
  24:     0x55df7073d968 - deno::tsc::op_is_node_file::v8_fn_ptr::h7824cb309ec45b7b
  25:     0x55df6f2ea64e - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
                               at ./../../../../v8/src/builtins/builtins-api.cc:113:36
  26:     0x55df6f2e9cf7 - _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
                               at ./../../../../v8/src/builtins/builtins-api.cc:135:1
  27:     0x55df70175236 - Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit`

**Comment by verikono** [comment]
I put together a repo that will produce this issue for you:
https://github.com/verikono/deno-npm-symlinks

At it's core i believe the panic happens because repo packages are exposed to the mono repo as symlinks inside of /node_modules. Put simply; the panic occurs when the package location is a symbolic link and resolved via package.json.

that being said;

this repo is an npm-workspaces mono repo setup so as to be as vanilla as possible.

I hope that helps;

happy 4th!

**Comment by jonasb** [comment]
Verified that the bug still appears in deno v 1.36.0

**Comment by jonasb** [comment]
Found a workaround, there's a newish configuration option in `deno.json`:
```
{
  "nodeModulesDir": false
}
```

If I set it the Deno stops using `node_modules`.

**Comment by bartlomieju** [comment]
I can't reproduce the panic on Deno v2.2.0, there are some type checking errors which seems to be actual errors. Gonna close this one.
