### ISSUE TITLE
socket.end is not a function

### ISSUE THREAD

**Issue by tian-sheng-low** [denoland/deno#19324]
Using the exact code from https://deno.com/manual@v1.34.1/node/how_to_with_npm/apollo, stopping the server after making at least one query will raise the following error. This only happens with Deno v1.33.2 onward.

```
stop() threw during undefined shutdown
TypeError: socket.end is not a function
    at file:///Users/user/Library/Caches/deno/npm/registry.npmjs.org/@apollo/server/4.7.1/dist/esm/plugin/drainHttpServer/stoppable.js:40:24
    at Map.forEach (<anonymous>)
    at Stopper.stop (file:///Users/user/Library/Caches/deno/npm/registry.npmjs.org/@apollo/server/4.7.1/dist/esm/plugin/drainHttpServer/stoppable.js:38:36)
    at eventLoopTick (ext:core/01_core.js:188:13)
    at async drainServer (file:///Users/user/Library/Caches/deno/npm/registry.npmjs.org/@apollo/server/4.7.1/dist/esm/plugin/drainHttpServer/index.js:15:21)
    at async Promise.all (index 0)
    at async drainServers (file:///Users/user/Library/Caches/deno/npm/registry.npmjs.org/@apollo/server/4.7.1/dist/esm/ApolloServer.js:173:21)
    at async ApolloServer.stop (file:///Users/user/Library/Caches/deno/npm/registry.npmjs.org/@apollo/server/4.7.1/dist/esm/ApolloServer.js:352:13)
    at async signalHandler (file:///Users/user/Library/Caches/deno/npm/registry.npmjs.org/@apollo/server/4.7.1/dist/esm/ApolloServer.js:233:17)
```

**Comment by tian-sheng-low** [comment]
Hi, is there any progress regarding this issue?

**Comment by bartlomieju** [comment]
No, not yet. We will try to fix it and release in July

**Comment by tian-sheng-low** [comment]
I see, thanks for the swift response!
Looking forward to it!
