### ISSUE TITLE
Panic api_register_module_v1 not found: GetProcAddress

### ISSUE THREAD

**Issue by albertosantini** [denoland/deno#19389]
With Deno `1.34.1`
```
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
...
```
It is Fresh project and the web app correctly works.

When I save a project file, Deno panics.

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.34.1
Args: ["C:\\woot\\usr\\bin\\deno.exe", "run", "-A", "--watch=static/,routes/", "dev.ts"]

thread 'main' panicked at 'napi_register_module_v1 not found: GetProcAddress { source: Os { code: 127, kind: Uncategorized, message: "The specified procedure could not be found." } }', D:\a\deno\deno\ext\napi\lib.rs:655:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With Deno `1.34.0` is ok

**Comment by bartlomieju** [comment]
Could you share your project? It appears one of the dependencies you are using tries to load an N-API module that is not present when trying to load it.

**Comment by albertosantini** [comment]
Well, I thought the same, but downgrading to `1.34.0` (`deno upgrade --version 1.34.0`) and following the same steps (starting the app and saving a file to trigger the watch), without any modification to the project, it correctly work.

Sorry, at the moment the repo is not public.
Finally any hint to catch the offending module?

**Comment by albertosantini** [comment]
With `RUST_BACKTRACE=1`, but I don't see any relevant info to find the offending module.

```
Watcher File change detected! Restarting!

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.34.1
Args: ["C:\\woot\\usr\\bin\\deno.exe", "run", "-A", "--watch=static/,routes/", "dev.ts"]

thread 'main' panicked at 'napi_register_module_v1 not found: GetProcAddress { source: Os { code: 127, kind: Uncategorized, message: "The specified procedure could not be found." } }', D:\a\deno\deno\ext\napi\lib.rs:655:8
stack backtrace:
   0:     0x7ff6bbe3ab29 - napi_release_threadsafe_function
   1:     0x7ff6bafa388b - napi_release_threadsafe_function
   2:     0x7ff6bbe14eca - napi_release_threadsafe_function
   3:     0x7ff6bbe3f23b - napi_release_threadsafe_function
   4:     0x7ff6bbe3ee31 - napi_release_threadsafe_function
   5:     0x7ff6bbe3ea45 - napi_release_threadsafe_function
   6:     0x7ff6baddd214 - napi_fatal_error
   7:     0x7ff6bbe3fa87 - napi_release_threadsafe_function
   8:     0x7ff6bbe3f7f6 - napi_release_threadsafe_function
   9:     0x7ff6bbe3f73f - napi_release_threadsafe_function
  10:     0x7ff6bbe3f714 - napi_release_threadsafe_function
  11:     0x7ff6bd0a2715 - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff6bd0a2bd6 - CrashForExceptionInNonABICompliantCodeRange
  13:     0x7ff6bb8d7ea0 - napi_release_threadsafe_function
  14:     0x7ff6bb8d2d5f - napi_release_threadsafe_function
  15:     0x7ff6bc3c98fb - CrashForExceptionInNonABICompliantCodeRange
  16:     0x7ff6bc3c8fb1 - CrashForExceptionInNonABICompliantCodeRange
  17:     0x7ff6bce43dfa - CrashForExceptionInNonABICompliantCodeRange
  18:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  19:     0x7ff63d044450 - <unknown>
  20:     0x7ff63d043a78 - <unknown>
  21:     0x7ff63d037012 - <unknown>
  22:     0x7ff63d0371d5 - <unknown>
  23:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  24:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  25:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  26:     0x7ff63d044977 - <unknown>
  27:     0x7ff63d044e0b - <unknown>
  28:     0x7ff63d044450 - <unknown>
  29:     0x7ff63d043a78 - <unknown>
  30:     0x7ff63d037012 - <unknown>
  31:     0x7ff63d0371d5 - <unknown>
  32:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  33:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  34:     0x7ff63d044977 - <unknown>
  35:     0x7ff63d044e0b - <unknown>
  36:     0x7ff63d044450 - <unknown>
  37:     0x7ff63d043a78 - <unknown>
  38:     0x7ff63d037012 - <unknown>
  39:     0x7ff63d0371d5 - <unknown>
  40:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  41:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  42:     0x7ff63d044977 - <unknown>
  43:     0x7ff63d044e0b - <unknown>
  44:     0x7ff63d044450 - <unknown>
  45:     0x7ff63d043a78 - <unknown>
  46:     0x7ff63d037012 - <unknown>
  47:     0x7ff63d0371d5 - <unknown>
  48:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  49:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  50:     0x7ff63d044977 - <unknown>
  51:     0x7ff63d044e0b - <unknown>
  52:     0x7ff63d044450 - <unknown>
  53:     0x7ff63d043a78 - <unknown>
  54:     0x7ff63d037012 - <unknown>
  55:     0x7ff63d0371d5 - <unknown>
  56:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  57:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  58:     0x7ff63d044977 - <unknown>
  59:     0x7ff63d044e0b - <unknown>
  60:     0x7ff63d044450 - <unknown>
  61:     0x7ff63d043a78 - <unknown>
  62:     0x7ff63d037012 - <unknown>
  63:     0x7ff63d0371d5 - <unknown>
  64:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  65:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  66:     0x7ff63d044977 - <unknown>
  67:     0x7ff63d044e0b - <unknown>
  68:     0x7ff63d044450 - <unknown>
  69:     0x7ff63d043a78 - <unknown>
  70:     0x7ff63d037012 - <unknown>
  71:     0x7ff63d0371d5 - <unknown>
  72:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  73:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  74:     0x7ff63d044977 - <unknown>
  75:     0x7ff63d044e0b - <unknown>
  76:     0x7ff63d044450 - <unknown>
  77:     0x7ff63d043a78 - <unknown>
  78:     0x7ff63d037012 - <unknown>
  79:     0x7ff63d0371d5 - <unknown>
  80:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  81:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  82:     0x7ff63d044977 - <unknown>
  83:     0x7ff63d044e0b - <unknown>
  84:     0x7ff63d044450 - <unknown>
  85:     0x7ff63d043a78 - <unknown>
  86:     0x7ff63d037012 - <unknown>
  87:     0x7ff63d0371d5 - <unknown>
  88:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  89:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  90:     0x7ff63d044977 - <unknown>
  91:     0x7ff63d044e0b - <unknown>
  92:     0x7ff63d044450 - <unknown>
  93:     0x7ff63d043a78 - <unknown>
  94:     0x7ff63d037012 - <unknown>
  95:     0x7ff63d0371d5 - <unknown>
  96:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
  97:     0x7ff6bcdae5dc - CrashForExceptionInNonABICompliantCodeRange
 128:     0x7ff6bc08d971 - napi_release_threadsafe_function
 129:     0x7ff6bb1a9334 - napi_release_threadsafe_function
 130:     0x7ff6bb19afc7 - napi_release_threadsafe_function
 131:     0x7ff6ba928bf5 - <unknown>
 132:     0x7ff6badc5b9a - napi_fatal_error
 133:     0x7ff6badc17e5 - napi_fatal_error
 134:     0x7ff6bad8e3c1 - napi_fatal_error
 135:     0x7ff6bab54a7e - napi_cancel_async_work
 136:     0x7ff6baa42bf0 - napi_cancel_async_work
 137:     0x7ff6baddeda4 - napi_fatal_error
 138:     0x7ff6ba97373e - <unknown>
 139:     0x7ff6baec4fd3 - napi_release_threadsafe_function
 140:     0x7ff6bd0554cc - CrashForExceptionInNonABICompliantCodeRange
 141:     0x7fff44c826ad - BaseThreadInitThunk
 142:     0x7fff4554a9f8 - RtlUserThreadStart
```

**Comment by albertosantini** [comment]
Sigh... using `--reload`, same beaviour.
`deno run --reload -A --watch=static/,routes/ dev.ts`

**Comment by albertosantini** [comment]
This is the content of `import_map.json`. 
These deps are included when a Fresh project is created, and, as I said above, it correctly works.
```
{
  "imports": {
    "@/": "./",
    "$fresh/": "https://deno.land/x/fresh@1.1.6/",
    "preact": "https://esm.sh/preact@10.13.1",
    "preact/": "https://esm.sh/preact@10.13.1/",
    "preact-render-to-string": "https://esm.sh/*preact-render-to-string@5.2.6",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.1.3",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.2.3",
    "twind": "https://esm.sh/twind@0.16.19",
    "twind/": "https://esm.sh/twind@0.16.19/",
    "$std/": "https://deno.land/std@0.190.0/"
  }
}
```

The only "new" dep I added is `supabase`:
`import { createClient } from "npm:@supabase/supabase-js";`

It should be the guilty.

**Comment by bartlomieju** [comment]
Thanks for the pointers. First of all, we certainly shouldn't be panicking there, but it should be a graceful error. I will look into fixing that today. Secondly, it appears that supabase or one of its dependencies is trying to load a N-API extension. I will try to fire up my Windows machine and see if I can repeat it. Am I correct in assuming that this problem happens only when you actually use `createClient` function, or just importing it is enough to trigger the panic?

**Comment by albertosantini** [comment]
Well, when I start the web app, it works as expected.
Deno panics when I save any file in the project: the watcher triggers, the app is reloaded and Deno panics.

For reference `utils/supabase.ts`

```
import { createClient } from "npm:@supabase/supabase-js";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
const SUPABASE_KEY = Deno.env.get("SUPABASE_KEY");

if (!SUPABASE_URL || !SUPABASE_KEY) {
  throw new Error(
      "env `SUPABASE_URL` and `SUPABASE_KEY` must be set",
  );
}

export const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
    auth: {
        persistSession: false
    }
});
``

**Comment by bartlomieju** [comment]
Thanks, this should enough to debug the problem.

**Comment by bartlomieju** [comment]
@albertosantini could you try with Deno v1.34.2 and let me know the result?

**Comment by albertosantini** [comment]
Perfect. It works fine.

After saving a file of the project, the watcher is triggered and the app is reloaded as usual.

Thanks a lot for your efforts.
