### ISSUE TITLE
`console.log` causes "Uncaught BrokenPipe: Broken pipe (os error 32)" error

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19401]
Calling `console.log` inside a child process seems to cause a broken pipe error.

### Steps to reproduce

1. Create file `child.js` with these contents:
  ```js
  console.log("ready");

  setTimeout(() => {
    console.log("boom"); // This line causes it
  }, 100);
  ```
2. Create file `parent.js` with these contents:
  ```js
  import {
    TextLineStream,
  } from "https://deno.land/std@0.190.0/streams/text_line_stream.ts";

  const serverProcess = new Deno.Command(
    Deno.execPath(),
    { args: ["run", "-A", "child.js"], stdout: "piped" },
  ).spawn();
  
  const lines = serverProcess.stdout
    .pipeThrough(new TextDecoderStream())
    .pipeThrough(new TextLineStream());

  for await (const line of lines) {
    if (line.includes("ready")) {
      break;
    }
  }
  ```
3. Run `deno run -A parent.js`

## Error

```sh
error: Uncaught BrokenPipe: Broken pipe (os error 32)
  console.log("boom");
          ^
    at Object.print (ext:core/01_core.js:824:32)
    at Console.<anonymous> (ext:runtime/98_global_scope.js:126:46)
    at console.log (ext:deno_console/01_console.js:3217:20)
    at file:///project/child.js:4:11
    at Object.action (ext:deno_web/02_timers.js:152:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:66:10)
    at eventLoopTick (ext:core/01_core.js:189:21)
```

**Comment by sigmaSd** [comment]
I think this is all expected, this line `  if (line.includes("ready")) break` exits the program after the first log of the child

when the child tries to log again the parent have already exited , so the stdout is closed aka broken pipe

**Comment by sigmaSd** [comment]
I don't follow the logic , the stdout pipe is closed therefore trying to log it should crash (not never crash)

In the pr you're just ignoring the error

Also this is not specfic to deno, its just how linux pipes works, here is an example in rust 
```rs
use std::process::{Command, Stdio};

fn main() {
    std::fs::write(
        "./log.rs",
        "fn main() {
    std::thread::sleep_ms(1000);
    println!(\"hello\");
}",
    )
    .unwrap();
    Command::new("rustc")
        .arg("log.rs")
        .spawn()
        .unwrap()
        .wait()
        .unwrap();
    Command::new("./log")
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();
}
```

**Comment by marvinhagemeister** [comment]
Good point! It sounds like that's a difference in how JS runtimes operate vs Linux pipes. Looking at node for example, they have two test cases that verify that calling `console.log` doesn't crash the child process:

1. https://github.com/nodejs/node/blob/main/test/parallel/test-process-external-stdio-close.js
2. https://github.com/nodejs/node/blob/main/test/parallel/test-process-external-stdio-close-spawn.js

I ported the snippet from the original comment to node and can confirm that this is true and they do not crash. Even calling `child.stdout.destroy()` explicitly from the parent before the child logs doesn't make it throw the broken pipe error.

**Comment by marvinhagemeister** [comment]
Spoke with @crowlKats who knows more than me about web streams and it seems like the proper solution is to prevent the stream to be canceled.

```diff
  import { TextLineStream } from "https://deno.land/std@0.190.0/streams/text_line_stream.ts";

  const serverProcess = new Deno.Command(Deno.execPath(), {
    args: ["run", "-A", "child.js"],
    stdout: "piped",
  }).spawn();
 
  const lines = serverProcess.stdout
    .pipeThrough(new TextDecoderStream(), {})
-   .pipeThrough(new TextLineStream());
+   .pipeThrough(new TextLineStream(), {
+     preventCancel: true,
+   });

  for await (const line of lines) {
    if (line.includes("ready")) {
      break;
    }
  }
```

**Comment by bartlomieju** [comment]
@marvinhagemeister is this issue still relevant?

**Comment by bartlomieju** [comment]
Closing due to lack of response to the information request. Please reopen if you can provide the requested details.
