### ISSUE TITLE
deno lsp panicked

### ISSUE THREAD

**Issue by wangzishi** [denoland/deno#19410]
I'm using the deno extension in vscode, but after configuring it, it crashes every time I open it.
[Here is my code repository](https://github.com/illusion-tech/selwyn-s-thorns).

```
Starting Deno language server...
  version: 1.34.1 (release, x86_64-unknown-linux-gnu)
  executable: /home/wangzishi/.cargo/bin/deno
Connected to "Visual Studio Code" 1.78.2
  Auto-resolved configuration file: "file:///home/wangzishi/projects/selwyn-s-thorns/deno.json"
  Auto-resolved package.json: "file:///home/wangzishi/projects/selwyn-s-thorns/package.json"
Setting import map defined in configuration file: "file:///home/wangzishi/projects/selwyn-s-thorns/deno.json"
  Resolved import map: "file:///home/wangzishi/projects/selwyn-s-thorns/deno.json"
Enabling import suggestions for: https://deno.land
client asked to cancel request 1, but no such pending request exists, ignoring
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.34.1
Args: ["/home/wangzishi/.cargo/bin/deno", "lsp"]

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/wangzishi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dprint-swc-ext-0.9.0/src/view/generated.rs:14469:17
stack backtrace:
   0:     0x55f16839b0a1 - std::backtrace_rs::backtrace::libunwind::trace::h49c88cf40170b5d6
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55f16839b0a1 - std::backtrace_rs::backtrace::trace_unsynchronized::hdc6cc34fd8a53678
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f16839b0a1 - std::sys_common::backtrace::_print_fmt::h0c7289f3a8de0b23
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55f16839b0a1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc8e96ca3c7ab0680
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55f1683ca60f - core::fmt::rt::Argument::fmt::h304ace7fe8bb186b
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/core/src/fmt/rt.rs:138:9
   5:     0x55f1683ca60f - core::fmt::write::ha469f5b722d475f3
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/core/src/fmt/mod.rs:1094:21
   6:     0x55f168395a31 - std::io::Write::write_fmt::h9a4844905af525b3
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/io/mod.rs:1713:15
   7:     0x55f16839aeb5 - std::sys_common::backtrace::_print::ha35f1d4a0d8accc0
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55f16839aeb5 - std::sys_common::backtrace::print::h690d5e347a585903
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55f16839ca27 - std::panicking::default_hook::{{closure}}::h819f1ab5f2b6d32d
  10:     0x55f16839c814 - std::panicking::default_hook::hcdf96a30790dc6bb
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/panicking.rs:288:9
  11:     0x55f164d96e2e - deno::setup_panic_hook::{{closure}}::hfec51db27da56358
  12:     0x55f16839d03d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4d61e66e458ff2d1
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/alloc/src/boxed.rs:1999:9
  13:     0x55f16839d03d - std::panicking::rust_panic_with_hook::hb101d99ddd165575
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/panicking.rs:709:13
  14:     0x55f16839cd91 - std::panicking::begin_panic_handler::{{closure}}::h6826cb5e0c9d0ead
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/panicking.rs:595:13
  15:     0x55f16839b4d6 - std::sys_common::backtrace::__rust_end_short_backtrace::h7a916e155aec8921
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys_common/backtrace.rs:151:18
  16:     0x55f16839cb22 - rust_begin_unwind
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/panicking.rs:593:5
  17:     0x55f164a9ea73 - core::panicking::panic_fmt::h1e09a982e3a0f5bf
               client asked to cancel request 4, but no such pending request exists, ignoring
successfully cancelled request with ID: 7
successfully cancelled request with ID: 8
                at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/core/src/panicking.rs:67:14
  18:     0x55f164a9eb03 - core::panicking::panic::h6095d4fd94a5d06f
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/core/src/panicking.rs:117:5
  19:     0x55f165f4d8dc - dprint_swc_ext::view::generated::MemberExpr::parent::hb368986f2badd5d5
  20:     0x55f16588f08d - <deno_lint::rules::no_deprecated_deno_api::NoDeprecatedDenoApiHandler as deno_lint::handler::Handler>::member_expr::hc8f144bda7970181
  21:     0x55f16588e9e5 - deno_lint::handler::Traverse::traverse::h2ff697e2131ec057
  22:     0x55f16588e9ac - deno_lint::handler::Traverse::traverse::h2ff697e2131ec057
  23:     0x55f16588e9ac - deno_lint::handler::Traverse::traverse::h2ff697e2131ec057
  24:     0x55f16588ec7c - <deno_lint::rules::no_deprecated_deno_api::NoDeprecatedDenoApi as deno_lint::rules::LintRule>::lint_program_with_ast_view::he1a01757a0a56f07
  25:     0x55f165936440 - deno_lint::linter::Linter::lint_program::{{closure}}::h3320180a743d929e
  26:     0x55f165924f5c - dprint_swc_ext::view::generated::with_ast_view::h242a7fb8933b4589
  27:     0x55f1658a79f5 - deno_ast::parsed_source::ParsedSource::with_view::h10893a13c4f02229
  28:     0x55f16586c4f8 - deno_lint::linter::Linter::lint_program::hdc5284759e65dcfa
  29:     0x55f16586bf73 - deno_lint::linter::Linter::lint_with_ast::hd563418236636f39
  30:     0x55f164bd9d73 - deno::lsp::analysis::get_lint_references::h071d81fcc26d922c
  31:     0x55f164e747d6 - deno::lsp::diagnostics::generate_document_lint_diagnostics::h6a671b9e87d62d9e
  32:     0x55f1653c711c - <deno_core::task::MaskFutureAsSend<F> as core::future::future::Future>::poll::h19602b8468ce05e9
  33:     0x55f16516ff01 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h0a487c5c7827b450
  34:     0x55f164cd252b - tokio::runtime::task::core::Core<T,S>::poll::h062bf18413814fea
  35:     0x55f164f13c31 - tokio::runtime::task::harness::Harness<client asked to cancel request 5, but no such pending request exists, ignoring
successfully cancelled request with ID: 6
T,S>::poll::h77407757317169cb
  36:     0x55f164ce2b4a - tokio::runtime::scheduler::client asked to cancel request 2, but no such pending request exists, ignoring
current_thread::client asked to cancel request 3, but no such pending request exists, ignoring
CurrentThread::successfully cancelled request with ID: 9
block_on::hf945de2042985380
  37successfully cancelled request with ID: 10
:     0x55f164d5b946 - tokio::runtime::runtime::Runtime::successfully cancelled request with ID: 11
block_on::h2f94044d0a034649
  successfully cancelled request with ID: 12
38:     0x55f1653081ae - stdsuccessfully cancelled request with ID: 13
::sys_common::backtrace::__rust_begin_short_backtracesuccessfully cancelled request with ID: 14
::h63242aae3bf8b0aa
 successfully cancelled request with ID: 15
 39:    successfully cancelled request with ID: 16
 0x55f164c271ec - core::ops::function::successfully cancelled request with ID: 17
FnOnce::call_once{{vtablesuccessfully cancelled request with ID: 18
.shim}}::hb920b23eaa8229af
successfully cancelled request with ID: 19
  40:     0x55f1683a3d45 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h21e0e0330758bd13
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/alloc/src/boxed.rs:1985:9
  41:     0x55f1683a3d45 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h07c258ba6721b777
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/alloc/src/boxed.rs:1985:9
  42:     0x55f1683a3d45 - std::sys::unix::thread::Thread::new::thread_start::h3bd04e8df530c8c3
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys/unix/thread.rs:108:17
successfully cancelled request with ID: 20
  43:     0x7f068b494b43 - <unknown>
  44:     0x7f068b526a00 - <unknown>
  45:                0x0 - <unknown>
[Info  - 05:26:00] Connection to server got closed. Server will restart.
```

**Comment by dsherret** [comment]
See https://github.com/denoland/deno/issues/19381#issuecomment-1579333424 or https://github.com/denoland/deno/issues/19148
