### ISSUE TITLE
Deno.serve() WebSocket request throws ReferenceError

### ISSUE THREAD

**Issue by Mqxx** [denoland/deno#19471]
If I execute this code and then print the `request` in the console I get a `ReferenceError`.

```
error: Uncaught ReferenceError: assert is not defined
        console.log(request);
                ^
    at getKeys (ext:deno_console/01_console.js:1363:7)
    at formatRaw (ext:deno_console/01_console.js:909:14)
    at formatValue (ext:deno_console/01_console.js:710:10)
    at inspect (ext:deno_console/01_console.js:3513:10)
    at Request.[Deno.customInspect] (ext:deno_fetch/23_request.js:485:12)
    at formatValue (ext:deno_console/01_console.js:643:41)
    at inspectArgs (ext:deno_console/01_console.js:3138:17)
    at console.log (ext:deno_console/01_console.js:3207:7)
    at WebSocket.<anonymous> (file:///H:/Files/Projects/TypeScript/main.ts:5:17)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:791:7)
```

```ts
export function WebSocketServer(options : Deno.ServeOptions | Deno.ServeTlsOptions, handler : (webSocket : WebSocket, request? : Request) => void) {
    Deno.serve({...options, onListen({hostname, port}) {
        console.log(`Listening on ws://${hostname}:${port}/ (WebSocketServer)`);
    }}, (request) => {
        if (request.headers.get("upgrade") != "websocket") {
            return new Response(null, { status: 501 });
        }
        const {socket, response} = Deno.upgradeWebSocket(request);

        handler(socket, request);

        return response;
    })
}

WebSocketServer({port: 8000, hostname: 'localhost'}, (webSocket, request) => {
    webSocket.addEventListener('message', () => {
        console.log(request); 
    })
})
```

**Comment by Mqxx** [comment]
@crowlKats What else I wanted to say. The error occurs only when I call the request after `Deno.upgradeWebSocket()`. I guess because the request is modified by the function.
