### ISSUE TITLE
@azure/storage-blob works in NodeJS but not in Deno

### ISSUE THREAD

**Issue by eikooc** [denoland/deno#19482]
Hi there. I do not know if this issue makes sense to be in this repository, so please close it if appropriate.

I am experiencing a bug with the NPM library `@azure/storage-blob`. It worked some time ago, but recently stopped working. I've tested it with various versions of Deno and all of them fail with the same error. I have also logged the [issue on a ticket](https://github.com/Azure/azure-sdk-for-js/issues/13281) in the [azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js) repository.

I created a small reproducible example to show the error:
```ts
import * as AzureBlob from "npm:@azure/storage-blob@12.14.0";
const main = async () => {
  const blobServiceClient = AzureBlob.BlobServiceClient.fromConnectionString(
    "REDACTED",
  );
  const containerClient = blobServiceClient.getContainerClient(
    "documents",
  );
  await containerClient.createIfNotExists();
  const blobCursor = await containerClient.listBlobsByHierarchy("/", {
    prefix: "foo",
  });

  const blobs: AzureBlob.BlobItem[] = [];
  for await (const blob of blobCursor) {
    blobs.push(blob as AzureBlob.BlobItem);
  }

  return blobs;
};

console.log(await main());
```

And this is the `deno.lock` file if that is important:
```json
{
  "version": "2",
  "remote": {},
  "npm": {
    "specifiers": {
      "@azure/storage-blob@12.14.0": "@azure/storage-blob@12.14.0"
    },
    "packages": {
      "@azure/abort-controller@1.1.0": {
        "integrity": "sha512-TrRLIoSQVzfAJX9H1JeFjzAoDGcoK1IYX1UImfceTZpsyYfWr09Ss1aHW1y5TrrR3iq6RZLBwJ3E24uwPhwahw==",
        "dependencies": {
          "tslib": "tslib@2.5.3"
        }
      },
      "@azure/core-auth@1.4.0": {
        "integrity": "sha512-HFrcTgmuSuukRf/EdPmqBrc5l6Q5Uu+2TbuhaKbgaCpP2TfAeiNaQPAadxO+CYBRHGUzIDteMAjFspFLDLnKVQ==",
        "dependencies": {
          "@azure/abort-controller": "@azure/abort-controller@1.1.0",
          "tslib": "tslib@2.5.3"
        }
      },
      "@azure/core-http@3.0.2": {
        "integrity": "sha512-o1wR9JrmoM0xEAa0Ue7Sp8j+uJvmqYaGoHOCT5qaVYmvgmnZDC0OvQimPA/JR3u77Sz6D1y3Xmk1y69cDU9q9A==",
        "dependencies": {
          "@azure/abort-controller": "@azure/abort-controller@1.1.0",
          "@azure/core-auth": "@azure/core-auth@1.4.0",
          "@azure/core-tracing": "@azure/core-tracing@1.0.0-preview.13",
          "@azure/core-util": "@azure/core-util@1.3.2",
          "@azure/logger": "@azure/logger@1.0.4",
          "@types/node-fetch": "@types/node-fetch@2.6.4",
          "@types/tunnel": "@types/tunnel@0.0.3",
          "form-data": "form-data@4.0.0",
          "node-fetch": "node-fetch@2.6.11",
          "process": "process@0.11.10",
          "tslib": "tslib@2.5.3",
          "tunnel": "tunnel@0.0.6",
          "uuid": "uuid@8.3.2",
          "xml2js": "xml2js@0.5.0"
        }
      },
      "@azure/core-lro@2.5.3": {
        "integrity": "sha512-ubkOf2YCnVtq7KqEJQqAI8dDD5rH1M6OP5kW0KO/JQyTaxLA0N0pjFWvvaysCj9eHMNBcuuoZXhhl0ypjod2DA==",
        "dependencies": {
          "@azure/abort-controller": "@azure/abort-controller@1.1.0",
          "@azure/core-util": "@azure/core-util@1.3.2",
          "@azure/logger": "@azure/logger@1.0.4",
          "tslib": "tslib@2.5.3"
        }
      },
      "@azure/core-paging@1.5.0": {
        "integrity": "sha512-zqWdVIt+2Z+3wqxEOGzR5hXFZ8MGKK52x4vFLw8n58pR6ZfKRx3EXYTxTaYxYHc/PexPUTyimcTWFJbji9Z6Iw==",
        "dependencies": {
          "tslib": "tslib@2.5.3"
        }
      },
      "@azure/core-tracing@1.0.0-preview.13": {
        "integrity": "sha512-KxDlhXyMlh2Jhj2ykX6vNEU0Vou4nHr025KoSEiz7cS3BNiHNaZcdECk/DmLkEB0as5T7b/TpRcehJ5yV6NeXQ==",
        "dependencies": {
          "@opentelemetry/api": "@opentelemetry/api@1.4.1",
          "tslib": "tslib@2.5.3"
        }
      },
      "@azure/core-util@1.3.2": {
        "integrity": "sha512-2bECOUh88RvL1pMZTcc6OzfobBeWDBf5oBbhjIhT1MV9otMVWCzpOJkkiKtrnO88y5GGBelgY8At73KGAdbkeQ==",
        "dependencies": {
          "@azure/abort-controller": "@azure/abort-controller@1.1.0",
          "tslib": "tslib@2.5.3"
        }
      },
      "@azure/logger@1.0.4": {
        "integrity": "sha512-ustrPY8MryhloQj7OWGe+HrYx+aoiOxzbXTtgblbV3xwCqpzUK36phH3XNHQKj3EPonyFUuDTfR3qFhTEAuZEg==",
        "dependencies": {
          "tslib": "tslib@2.5.3"
        }
      },
      "@azure/storage-blob@12.14.0": {
        "integrity": "sha512-g8GNUDpMisGXzBeD+sKphhH5yLwesB4JkHr1U6be/X3F+cAMcyGLPD1P89g2M7wbEtUJWoikry1rlr83nNRBzg==",
        "dependencies": {
          "@azure/abort-controller": "@azure/abort-controller@1.1.0",
          "@azure/core-http": "@azure/core-http@3.0.2",
          "@azure/core-lro": "@azure/core-lro@2.5.3",
          "@azure/core-paging": "@azure/core-paging@1.5.0",
          "@azure/core-tracing": "@azure/core-tracing@1.0.0-preview.13",
          "@azure/logger": "@azure/logger@1.0.4",
          "events": "events@3.3.0",
          "tslib": "tslib@2.5.3"
        }
      },
      "@opentelemetry/api@1.4.1": {
        "integrity": "sha512-O2yRJce1GOc6PAy3QxFM4NzFiWzvScDC1/5ihYBL6BUEVdq0XMWN01sppE+H6bBXbaFYipjwFLEWLg5PaSOThA==",
        "dependencies": {}
      },
      "@types/node-fetch@2.6.4": {
        "integrity": "sha512-1ZX9fcN4Rvkvgv4E6PAY5WXUFWFcRWxZa3EW83UjycOB9ljJCedb2CupIP4RZMEwF/M3eTcCihbBRgwtGbg5Rg==",
        "dependencies": {
          "@types/node": "@types/node@20.2.5",
          "form-data": "form-data@3.0.1"
        }
      },
      "@types/node@20.2.5": {
        "integrity": "sha512-JJulVEQXmiY9Px5axXHeYGLSjhkZEnD+MDPDGbCbIAbMslkKwmygtZFy1X6s/075Yo94sf8GuSlFfPzysQrWZQ==",
        "dependencies": {}
      },
      "@types/tunnel@0.0.3": {
        "integrity": "sha512-sOUTGn6h1SfQ+gbgqC364jLFBw2lnFqkgF3q0WovEHRLMrVD1sd5aufqi/aJObLekJO+Aq5z646U4Oxy6shXMA==",
        "dependencies": {
          "@types/node": "@types/node@20.2.5"
        }
      },
      "asynckit@0.4.0": {
        "integrity": "sha512-Oei9OH4tRh0YqU3GxhX79dM/mwVgvbZJaSNaRk+bshkj0S5cfHcgYakreBjrHwatXKbz+IoIdYLxrKim2MjW0Q==",
        "dependencies": {}
      },
      "combined-stream@1.0.8": {
        "integrity": "sha512-FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==",
        "dependencies": {
          "delayed-stream": "delayed-stream@1.0.0"
        }
      },
      "delayed-stream@1.0.0": {
        "integrity": "sha512-ZySD7Nf91aLB0RxL4KGrKHBXl7Eds1DAmEdcoVawXnLD7SDhpNgtuII2aAkg7a7QS41jxPSZ17p4VdGnMHk3MQ==",
        "dependencies": {}
      },
      "events@3.3.0": {
        "integrity": "sha512-mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q==",
        "dependencies": {}
      },
      "form-data@3.0.1": {
        "integrity": "sha512-RHkBKtLWUVwd7SqRIvCZMEvAMoGUp0XU+seQiZejj0COz3RI3hWP4sCv3gZWWLjJTd7rGwcsF5eKZGii0r/hbg==",
        "dependencies": {
          "asynckit": "asynckit@0.4.0",
          "combined-stream": "combined-stream@1.0.8",
          "mime-types": "mime-types@2.1.35"
        }
      },
      "form-data@4.0.0": {
        "integrity": "sha512-ETEklSGi5t0QMZuiXoA/Q6vcnxcLQP5vdugSpuAyi6SVGi2clPPp+xgEhuMaHC+zGgn31Kd235W35f7Hykkaww==",
        "dependencies": {
          "asynckit": "asynckit@0.4.0",
          "combined-stream": "combined-stream@1.0.8",
          "mime-types": "mime-types@2.1.35"
        }
      },
      "mime-db@1.52.0": {
        "integrity": "sha512-sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==",
        "dependencies": {}
      },
      "mime-types@2.1.35": {
        "integrity": "sha512-ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==",
        "dependencies": {
          "mime-db": "mime-db@1.52.0"
        }
      },
      "node-fetch@2.6.11": {
        "integrity": "sha512-4I6pdBY1EthSqDmJkiNk3JIT8cswwR9nfeW/cPdUagJYEQG7R95WRH74wpz7ma8Gh/9dI9FP+OU+0E4FvtA55w==",
        "dependencies": {
          "whatwg-url": "whatwg-url@5.0.0"
        }
      },
      "process@0.11.10": {
        "integrity": "sha512-cdGef/drWFoydD1JsMzuFf8100nZl+GT+yacc2bEced5f9Rjk4z+WtFUTBu9PhOi9j/jfmBPu0mMEY4wIdAF8A==",
        "dependencies": {}
      },
      "sax@1.2.4": {
        "integrity": "sha512-NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==",
        "dependencies": {}
      },
      "tr46@0.0.3": {
        "integrity": "sha512-N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==",
        "dependencies": {}
      },
      "tslib@2.5.3": {
        "integrity": "sha512-mSxlJJwl3BMEQCUNnxXBU9jP4JBktcEGhURcPR6VQVlnP0FdDEsIaz0C35dXNGLyRfrATNofF0F5p2KPxQgB+w==",
        "dependencies": {}
      },
      "tunnel@0.0.6": {
        "integrity": "sha512-1h/Lnq9yajKY2PEbBadPXj3VxsDDu844OnaAo52UVmIzIvwwtBPIuNvkjuzBlTWpfJyUbG3ez0KSBibQkj4ojg==",
        "dependencies": {}
      },
      "uuid@8.3.2": {
        "integrity": "sha512-+NYs2QeMWy+GWFOEm9xnn6HCDp0l7QBD7ml8zLUmJ+93Q5NF0NocErnwkTkXVFNiX3/fpC6afS8Dhb/gz7R7eg==",
        "dependencies": {}
      },
      "webidl-conversions@3.0.1": {
        "integrity": "sha512-2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ==",
        "dependencies": {}
      },
      "whatwg-url@5.0.0": {
        "integrity": "sha512-saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==",
        "dependencies": {
          "tr46": "tr46@0.0.3",
          "webidl-conversions": "webidl-conversions@3.0.1"
        }
      },
      "xml2js@0.5.0": {
        "integrity": "sha512-drPFnkQJik/O+uPKpqSgr22mpuFHqKdbS835iAQrUC73L2F5WkboIRd63ai/2Yg6I1jzifPFKH2NTK+cfglkIA==",
        "dependencies": {
          "sax": "sax@1.2.4",
          "xmlbuilder": "xmlbuilder@11.0.1"
        }
      },
      "xmlbuilder@11.0.1": {
        "integrity": "sha512-fDlsI/kFEx7gLvbecc0/ohLG50fugQp8ryHzMTuW9vSa1GJ0XYWKnhsUx7oie3G98+r56aTQIUB4kht42R3JvA==",
        "dependencies": {}
      }
    }
  }
}
```

And this is the error when running the code:

> error: Uncaught TypeError: Cannot read properties of undefined (reading 'listenerCount')
at IncomingMessageForClient. (file:///home/codespace/.cache/deno/npm/registry.npmjs.org/node-fetch/2.6.11/lib/index.js:1746:36
)
at Object.onceWrapper (ext:deno_node/_stream.mjs:1927:32)
at IncomingMessageForClient.emit (ext:deno_node/_stream.mjs:1852:9)
at emitCloseNT (ext:deno_node/_stream.mjs:1557:15)
at processTicksAndRejections (ext:deno_node/_next_tick.ts:28:29)
at runNextTicks (ext:deno_node/_next_tick.ts:69:5)
at eventLoopTick (ext:core/01_core.js:189:21)

It seems like the issue is with some `node-fetch` thing.

**Comment by bartlomieju** [comment]
This should be fixed by https://github.com/denoland/deno/pull/19509 and will be released in v1.34.3.
