### ISSUE TITLE
npm specifiers in deno compile with @azure/storage-blob

### ISSUE THREAD

**Issue by thyldrm** [denoland/deno#19500]
Hello,

We have a facing issue with 'npm:@azure/storage-blob' this package. In Deno run command this package will work fine and there is no error but after i compile the related script there is an error below here;

```
error: Uncaught Error: Cannot find module '@azure/core-tracing'
Require stack:
- /tmp/deno-compile-ctapi/node_modules/localhost/@azure/core-http/3.0.2/dist/index.js
- /tmp/deno-compile-ctapi/node_modules/localhost/@azure/storage-blob/12.14.0/dist/index.js
- /tmp/deno-compile-ctapi/node_modules/localhost/@azure/storage-blob/12.14.0/dist/index.js
    at Function.Module._resolveFilename (ext:deno_node/01_require.js:840:15)
    at Function.Module._load (ext:deno_node/01_require.js:673:27)
    at Module.require (ext:deno_node/01_require.js:907:19)
    at require (ext:deno_node/01_require.js:1047:16)
    at Object.<anonymous> (file:///tmp/deno-compile-ctapi/node_modules/localhost/@azure/core-http/3.0.2/dist/index.js:20:19)
    at Object.<anonymous> (file:///tmp/deno-compile-ctapi/node_modules/localhost/@azure/core-http/3.0.2/dist/index.js:5467:4)
    at Module._compile (ext:deno_node/01_require.js:974:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:1007:10)
    at Module.load (ext:deno_node/01_require.js:885:32)
    at Function.Module._load (ext:deno_node/01_require.js:719:12)
error: Uncaught Error: Cannot find module '@azure/core-tracing'
Require stack:
```

**Comment by thyldrm** [comment]
I leave such a compile example and the error to give more information

`deno compile --output exampleExectubaleName --unstable npm:@azure/core-tracing`

```
Failed caching npm package '@azure/core-tracing@1.0.1'.

Caused by:
    An npm specifier not found in cache: "@azure/core-tracing", --cached-only is specified.
```
