### ISSUE TITLE
`node:https` does not support `https` URLs

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#19510]
```ts
import { join } from "https://deno.land/std@0.190.0/path/mod.ts";
import { DenoDir } from "https://deno.land/x/deno_cache@0.4.1/deno_dir.ts";
import {
  /** @ts-ignore this does actually exist */
  PUPPETEER_REVISIONS,
} from "npm:puppeteer-core@20.7.1";
import { Browser, install } from "npm:@puppeteer/browsers@1.4.1";

const dir = new DenoDir();
const path = join(
  dir.root,
  "puppeteer",
  "chrome",
  PUPPETEER_REVISIONS.chrome,
);
const installed = await install({
  cacheDir: path,
  browser: Browser.CHROME,
  buildId: PUPPETEER_REVISIONS.chrome,
});
console.log(installed.path);
```

```
error: TypeError: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (ext:deno_node/http.ts:204:19)
    at new HttpsClientRequest (ext:deno_node/https.ts:70:79)
```

**Comment by yastanotheruser** [comment]
This seems to be an issue with the `agent-base` package and not Deno itself, used by the `proxy-agent` package, which is the HTTP agent used by the Puppeteer installer. The base agent class uses the stack trace to detect whether it's being used in a secure context or not, but this method is currently not compatible with Deno package naming.

https://github.com/TooTallNate/proxy-agents/blob/e1e80ab78cef88fd1e800b07611581dce3142550/packages/agent-base/src/index.ts#L71

**Comment by bartlomieju** [comment]
Wow, that's a beautiful (_painful_) hack. Thanks for the pointer @yastanotheruser, you saved me a couple hours of debugging. Fortunately the fix on our side is not that bad and I'll try to squeeze it into v1.34.3.

**Comment by yastanotheruser** [comment]
How would this hack be supported? I was gonna open a PR in Nate's repo to support Deno package naming, to make it even more painful haha.

**Comment by bartlomieju** [comment]
Eg. when I add `console.log` in that function you linked I get:
```
stack line Error
stack line     at ProxyAgent.isSecureEndpoint (file:///Users/ib/dev/try_puppeteer/node_modules/.deno/agent-base@7.1.0/node_modules/agent-base/dist/index.js:59:27)
stack line     at ProxyAgent.get protocol (file:///Users/ib/dev/try_puppeteer/node_modules/.deno/agent-base@7.1.0/node_modules/agent-base/dist/index.js:106:19)
stack line     at new ClientRequest (ext:deno_node/http.ts:195:43)
stack line     at new HttpsClientRequest (ext:deno_node/https.ts:70:79)
stack line     at Module.request (ext:deno_node/https.ts:119:12)
stack line     at httpRequest (file:///Users/ib/dev/try_puppeteer/node_modules/.deno/@puppeteer+browsers@1.4.1/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:54:17)
stack line     at file:///Users/ib/dev/try_puppeteer/node_modules/.deno/@puppeteer+browsers@1.4.1/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:70:25
stack line     at new Promise (<anonymous>)
stack line     at downloadFile (file:///Users/ib/dev/try_puppeteer/node_modules/.deno/@puppeteer+browsers@1.4.1/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:63:12)
stack line     at install (file:///Users/ib/dev/try_puppeteer/node_modules/.deno/@puppeteer+browsers@1.4.1/node_modules/@puppeteer/browsers/lib/esm/install.js:92:19)
```

`stack line     at Module.request (ext:deno_node/https.ts:119:12)` <--- this line should have `(node:http:119:12)` instead

**Comment by yastanotheruser** [comment]
ohh I see, that would work fine
