### ISSUE TITLE
Figure out how to reconcile `@types/node`'s `AbortSignal` and `AbortController` with Deno's

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#19527]
The following code errors:

```ts
import { writeFile } from "node:fs";

const controller = new AbortController();
const signal = controller.signal;

// error here about duplicate AbortSignal types (`AbortSignal` is not assignable to type `AbortSignal`)
writeFile("file.txt", "content", { signal }, (err) => {
});
```

This is because we explicitly keep `AbortSignal` and `AbortController` over in the Node globalThis symbol:

https://github.com/denoland/deno/blob/0733943fe7de30fa54d6cd8ee34f7393e8bb7482/cli/tsc/99_main_compiler.js#L1290-L1291

When disabling these globals, the errors are the following:

```
> ../deno/target/debug/deno check --all a.ts
Check file:///V:/scratch/a.ts
error: TS2300 [ERROR]: Duplicate identifier 'AbortController'.
declare class AbortController {
              ~~~~~~~~~~~~~~~
    at asset:///lib.deno.web.d.ts:295:15

    'AbortController' was also declared here.
    interface AbortController {
              ~~~~~~~~~~~~~~~
        at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/node/18.11.18/globals.d.ts:47:11    and here.
    declare var AbortController: typeof globalThis extends {onmessage: any; AbortController: infer T}
                ~~~~~~~~~~~~~~~
        at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/node/18.11.18/globals.d.ts:67:13

TS2320 [ERROR]: Interface 'AbortSignal' cannot simultaneously extend types 'EventTarget' and 'EventTarget'.
  Named property 'dispatchEvent' of types 'EventTarget' and 'EventTarget' are not identical.
interface AbortSignal extends EventTarget {
          ~~~~~~~~~~~
    at asset:///lib.deno.web.d.ts:313:11

TS2300 [ERROR]: Duplicate identifier 'AbortController'.
interface AbortController {
          ~~~~~~~~~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/node/18.11.18/globals.d.ts:47:11

    'AbortController' was also declared here.
    declare class AbortController {
                  ~~~~~~~~~~~~~~~
        at asset:///lib.deno.web.d.ts:295:15

TS2300 [ERROR]: Duplicate identifier 'AbortController'.
declare var AbortController: typeof globalThis extends {onmessage: any; AbortController: infer T}
            ~~~~~~~~~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/node/18.11.18/globals.d.ts:67:13

    'AbortController' was also declared here.
    declare class AbortController {
                  ~~~~~~~~~~~~~~~
        at asset:///lib.deno.web.d.ts:295:15

Found 4 errors.
```

Because `EventTarget` is different in `@types/node`.

**Comment by littledivy** [comment]
No longer reproducible.

> This is currently handled by TYPES_NODE_IGNORABLE_NAMES in cli/tsc/mod.rs, which causes the TypeScript fork to drop @types/node's redeclarations of these globals so Deno's stay canonical. The bundled cli/tsc/dts/node/globals.d.cts is also pre-stripped of declare var AbortController/AbortSignal for the same reason. The issue's original reproduction (writeFile("file.txt", "content", { signal }, cb)) currently checks cleanly, but until now nothing protected that.
