### ISSUE TITLE
NPM compat: Dependency `exports.require` in dependency `package.json` is not respected

### ISSUE THREAD

**Issue by jacobmischka** [denoland/deno#19539]
I'm trying to import a dependency that has [`superjson`](https://www.npmjs.com/package/superjson) as a dependency, which it itself has [`copy-anything`](https://www.npmjs.com/package/copy-anything) as a dependency.

The compiled superjson file which is imported calls `var copy_anything_1 = require("copy-anything");`, which then fails in deno with:

```
error: Uncaught Error: Trying to import ESM module: /home/mischka/projects/basic-interval-deno/node_modules/.deno/copy-anything@3.0.5/node_modules/copy-anything/dist/index.js using require()
    at Object.Module._extensions..js (internal:deno_node_loading/02_require.js:774:13)
    at Module.load (internal:deno_node_loading/02_require.js:656:32)
    at Function.Module._load (internal:deno_node_loading/02_require.js:513:12)
    at Module.require (internal:deno_node_loading/02_require.js:678:19)
    at require (internal:deno_node_loading/02_require.js:818:16)
    at Object.<anonymous> (file:///home/mischka/projects/basic-interval-deno/node_modules/.deno/superjson@1.12.3/node_modules/superjson/dist/index.js:40:23)
    at Object.<anonymous> (file:///home/mischka/projects/basic-interval-deno/node_modules/.deno/superjson@1.12.3/node_modules/superjson/dist/index.js:118:4)
    at Module._compile (internal:deno_node_loading/02_require.js:745:34)
    at Object.Module._extensions..js (internal:deno_node_loading/02_require.js:778:10)
    at Module.load (internal:deno_node_loading/02_require.js:656:32)
```

The `copy-anything` [`package.json`](https://github.com/mesqueeb/copy-anything/blob/production/package.json) defines an `exports.require` path, which points to a commonjs file, which should be `require`d instead, which is why it works in Node.

Minimum reproducible code:

```ts
import * as superjson from 'npm:superjson'

console.log(superjson.load)
```

**Comment by jacobmischka** [comment]
Er, sorry, I just realized this was on a pretty old version of deno (`1.31.1`). This is no longer the case.
