### ISSUE TITLE
socket.setKeepAlive is not a function

### ISSUE THREAD

**Issue by thyldrm** [denoland/deno#19535]
I encountered a new error with the Deno 1.34.3 update. Below I leave the necessary snippet and error.

```
 const response = await axios.get(url, { responseType: 'arraybuffer', headers: headers });
```

```
error: Uncaught TypeError: socket.setKeepAlive is not a function
    at RedirectableRequest.handleRequestSocket (file:///Users/ct/node_modules/.deno/axios@1.2.2/node_modules/axios/lib/adapters/http.js:539:14)
    at RedirectableRequest.emit (ext:deno_node/_stream.mjs:1852:9)
    at HttpsClientRequest.eventHandlers.<computed> (file:///Users/ct/node_modules/.deno/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:14:24)
    at HttpsClientRequest.emit (ext:deno_node/_stream.mjs:1852:9)
    at ext:deno_node/http.ts:385:18
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:23:21)
    at runNextTicks (ext:deno_node/_next_tick.ts:69:5)
    at eventLoopTick (ext:core/01_core.js:189:21)
Process exited with code 1
```

**Comment by bartlomieju** [comment]
This is because we currently don't properly polyfill the `socket` event.

**Comment by Xentox-Phil** [comment]
I have encountered the exact same issue pls fix this... Thank you very much! i downgraded to version 1.33.4 via `deno upgrade --version 1.33.4`

**Comment by Joel-PeakMetrics** [comment]
I'm running into this as well. Using AWS SDK's glueclient.
```
$ deno run -A gluetest.ts
error: Uncaught TypeError: socket.setKeepAlive is not a function
    at HttpsClientRequest.<anonymous> (file:///.../node_modules/.deno/@aws-sdk+node-http-handler@3.360.0/node_modules/@aws-sdk/node-http-handler/dist-cjs/set-socket-keep-alive.js:9:16)
    at HttpsClientRequest.emit (ext:deno_node/_stream.mjs:1852:9)
    at ext:deno_node/http.ts:385:18
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:23:21)
    at runNextTicks (ext:deno_node/_next_tick.ts:69:5)
    at eventLoopTick (ext:core/01_core.js:189:21)
```
