### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'close')

### ISSUE THREAD

**Issue by eikooc** [denoland/deno#19552]
Hi, I've been trying to recreate a bug where I experience the same issue as described in #19078.
While trying to create a minimal example for that. I stumbled upon this error.
I do not know if it happens in nodejs also, but I would think it shouldn't crash the application.
The error only comes if the collection exists and has data in it and if I do not `await` the `client.close` call.

Reproduction example:
```ts
import * as mongo from "npm:mongodb@5.5.0";
import { Application } from "https://deno.land/x/oak/mod.ts";

const url =
  "mongodb+srv://user:password@mongo.mongodb.net/?retryWrites=true&w=majority";
const client = new mongo.MongoClient(url);
await client.connect();
await client.db("admin").command({ ping: 1 });
const db = client.db("some-db");

const app = new Application();

app.use(async (ctx) => {
  client.close(true);
  ctx.response.body = await db.collection("some-collection").findOne({});
});

console.log("listening on port 8000");
await app.listen({ port: 8000 });
```
The error:
```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'close')
    at file:///home/user/.cache/deno/npm/registry.npmjs.org/mongodb/5.5.0/lib/mongo_client.js:222:22
    at new Promise (<anonymous>)
    at MongoClient.close (file:///home/user/.cache/deno/npm/registry.npmjs.org/mongodb/5.5.0/lib/mongo_client.js:221:15)
    at eventLoopTick (ext:core/01_core.js:183:11)
```

**Comment by eikooc** [comment]
I believe this has been solved in Deno v1.37
