### ISSUE TITLE
Type error with node compat's Readable.fromWeb()

### ISSUE THREAD

**Issue by bradenmacdonald** [denoland/deno#19620]
This code should be fine, but doesn't pass type check:

```typescript
import { Readable } from "node:stream";
const webStream = new ReadableStream();
Readable.fromWeb(webStream);
```

Running `deno check` gives this output:

```
error: TS2345 [ERROR]: Argument of type 'ReadableStream<any>' is not assignable to parameter of type 'import("stream/web").ReadableStream<any>'.
  Property 'values' is missing in type 'ReadableStream<any>' but required in type 'import("stream/web").ReadableStream<any>'.
Readable.fromWeb(webStream);
                 ~~~~~~~~~
    at file://~/Desktop/type-bug.ts:3:18

    'values' is declared here.
            values(options?: { preventCancel?: boolean }): AsyncIterableIterator<R>;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at file://~/Library/Caches/deno/npm/registry.npmjs.org/@types/node/18.11.18/stream/web.d.ts:142:9
```

## Details

Deno ships the right type definitions:

https://github.com/denoland/deno/blob/a8d472f88e79703b1890bfdc87d7a3bb20b21428/ext/node/polyfills/_stream.d.ts#L55-L66

But they aren't getting used. Instead Deno is using the third party type definitions in `npm:@types/node/18.11.18`, which now includes the experimental `ReadableStream.values()` method, which Deno's `ReadableStream` doesn't have.

**Comment by bradenmacdonald** [comment]
A similar issue is happening with `Writable.fromWeb`:

```
Argument of type 'WritableStream<any>' is not assignable to parameter of type 'import("stream/web").WritableStream<any>'.
  The types of 'getWriter().closed' are incompatible between these types.
    Type 'Promise<void>' is not assignable to type 'Promise<undefined>'.
      Type 'void' is not assignable to type 'undefined'.
```

**Comment by petamoriken** [comment]
I tried it with Deno v1.38.3 and no error was shown.

**Comment by bradenmacdonald** [comment]
Weird, because it's now showing me a slightly different error with Deno 1.38.3.

Running the code through `deno check -r` gives:

```
error: TS2345 [ERROR]: Argument of type 'ReadableStream<any>' is not assignable to parameter of type 'import("stream/web").ReadableStream<any>'.
  Types of property 'getReader' are incompatible.
    Type '{ (options: { mode: "byob"; }): ReadableStreamBYOBReader; (options?: { mode?: undefined; } | undefined): ReadableStreamDefaultReader<any>; }' is not assignable to type '() => ReadableStreamDefaultReader<any>'.
      Target signature provides too few arguments. Expected 1 or more, but got 0.
Readable.fromWeb(webStream);
                 ~~~~~~~~~
```

**Comment by tazmaniax** [comment]
I'm getting the same error passing in a Deno fetch body to Readable.fromWeb()....

<img width="1172" alt="CleanShot 2024-01-06 at 14 10 10@2x" src="https://github.com/denoland/deno/assets/1079943/9c214464-99fd-4397-b885-d6f2314f8e22">

**Comment by tazmaniax** [comment]
This issue is still happening with Deno 1.40.4

**Comment by Siilwyn** [comment]
@tazmaniax please vote ( :+1: ) on the author's issue message for visibility, also for posterity 1.42.1 still has this issue. I'd love a workaround.

**Comment by tazmaniax** [comment]
@Siilwyn if your use case is streaming content from Deno fetch to AWS S3 then I found a solution that doesn't use Readable.fromWeb(), which was probably the wrong approach to begin with, and instead uses a custom AWS request handler that you can see referenced [here](https://github.com/denoland/deno/discussions/22184#discussioncomment-8485001). Let me know if that's interesting.

**Comment by Siilwyn** [comment]
Sadly not, bumped into this using:
```js
Readable.toWeb(process.stdout).pipeThrough(new TextDecoderStream())
```

**Comment by dylanellington** [comment]
A lot has changed with Deno since this bug was last updated, but we still have this issue today. Is there any more recent preferred solutions known to workaround this for now? Like others have stated id rather not use non AWS libraries for working with S3 if possible.

**Comment by juanepedroso** [comment]
This is an issue in nodejs ecosystem too.
