### ISSUE TITLE
`jsxImportSource` cannot use  `importMap`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#19676]
## Summary

found while testing solidjs + vite on deno. `jsx` was set to `preserve`.

pasting url directly to `jsxImportSource` works but will fail if specified via import map.

## Minimal reproduction
```
 tree
.
├── deno.json
└── main.tsx
```
```tsx
// main.tsx
export default () => <h1>Hi</h1>
```
```json
// deno.json
{
  "imports": { "solid-js": "npm:solid-js@1.7.2" },
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "solid-js"
  }
}
```

```ts
 ~/r/e/l/test  deno check --config=den
o.json main.tsx
Check file:///home/scarf/repo/etc/learn/test/main.tsx
error: TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
export default () => <h1>Hi</h1>
                     ~~~~
    at file:///home/scarf/repo/etc/learn/test/main.tsx:1:22

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
export default () => <h1>Hi</h1>
                           ~~~~~
    at file:///home/scarf/repo/etc/learn/test/main.tsx:1:28
```

## Workaround

```json
{
  "imports": { "solid-js": "npm:solid-js@1.7.2" },
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "npm:solid-js@1.7.2"
  }
}
```
however it'd be nice to not having to duplicate urls.

**Comment by lucacasonato** [comment]
There is no bug here. When specifying something for jsxImportSource, the actual imported specifier will be `<jsxImportSource>/jsx-runtime`. Your import map does not remap this specifier. If you add `"solid-js/": "npm:/solid-js@1.2.3/"` to your import map, it should work

**Comment by scarf005** [comment]
@lucacasonato thank you for the suggestion. however it does not seem to work for me; all the following configurations failed to type check and produced the same error as before:

```json
{
  "imports": {
    "solid-js": "npm:solid-js@1.7.2",
    "solid-js/": "npm:/solid-js@1.2.3/"
  },
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "solid-js"
  }
}
```
```json
{
  "imports": {
    "solid-js": "npm:solid-js@1.7.2",
    "solid-js/jsx-runtime": "npm:solid-js@1.7.2"
  },
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "solid-js"
  }
}
```
```json
{
  "imports": {
    "solid-js": "npm:solid-js@1.7.2",
    "solid-js/jsx-runtime": "npm:/solid-js@1.7.2/"
  },
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "solid-js"
  }
}
```

<details><summary>error log</summary>

```
deno.stable check --config deno.json main.tsx
Check file:///home/scarf/repo/etc/learn/test/main.tsx
error: TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
export default () => <h1>Hi</h1>;
                     ~~~~
    at file:///home/scarf/repo/etc/learn/test/main.tsx:3:22

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
export default () => <h1>Hi</h1>;
                           ~~~~~
    at file:///home/scarf/repo/etc/learn/test/main.tsx:3:28

Found 2 errors.
```

</details> 

Could you help me identify what I might be missing?

## Others

```ts
import "npm:/solid-js@1.7.2/jsx-runtime"
```
LSP correctly resolves jsx-runtime, so I don't think that's the issue.
```
$ deno --version
deno 1.34.3 (release, x86_64-unknown-linux-gnu)
v8 11.5.150.2
typescript 5.0.4
```

**Comment by dsherret** [comment]
The bug here is we don't error when someone uses the "preserve" jsx setting. I opened https://github.com/denoland/deno/issues/19953
