### ISSUE TITLE
serveTls rejects valid SSL certificate - "invalid private key"

### ISSUE THREAD

**Issue by tjcrowder** [denoland/deno#19673]
I can't get a valid SSL certificate to work with `serveTls`, I don't know whether it's a bug or a setup problem.

Here's the short version of the error (I include a version with `RUST_BACKTRACE=full` at the end of the issue, FWIW):

```text
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.34.3
Args: ["c:\\bin\\deno.exe", "run", "-A", "main.ts"]

thread 'main' panicked at 'invalid key or certificate: General("invalid private key")', C:\a\deno\deno\ext\net\ops_tls.rs:1060:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The *panic* part is covered by #19520 ("Panic on invalid SSL certificate"), but this SSL certificate is **valid**.

I assume this is because I don't have something set up. Here's what I have:

* A Windows 10 workstation (work machine)
* Deno v1.34.3 -- just the standalone executable
* `DENO_TLS_CA_STORE=system` in the environment (prior to this, Deno couldn't read `https` URLs, so I guess it's seeing this variable; I don't know whether it's related at all for *serving* HTTPS).

Some other relevant info:

* The certificate isn't signed directly by a public CA, the company has an intermediate certificate. So it's thiscert -> intermediate -> public CA
* The certificate works just fine in Node.js (both in a Create React App app, and in a really basic test I threw together)
* A test with `serve` works just fine serving HTTP; Deno itself seems happy

Sadly, I can't share the certificate and key files, so I'm just looking for what setup steps or other things I might be missing.

Here's the test code I'm using with Deno:

```ts
import { serveTls } from "https://deno.land/std@0.192.0/http/server.ts";

const port = 5001;

function handler(/*req: Request*/): Response {
    return new Response("Hello, World!");
}

serveTls(handler, {
    port,
    certFile: "./host.crt",
    keyFile: "./host.key",
});
```

To rule out path problems and the like I also tried a version that read the files manually then used the `cert` and `key` options, but the result was the same.

FWIW, here's the test code I used on Node.js that's working (probably not ideal, just threw it together):

```js
import fs from "fs";
import https from "https";
import express from "express";

const port = 8000;

const options = {
    cert: fs.readFileSync("./host.crt"),
    key: fs.readFileSync("./host.key"),
};

const app = express();

https.createServer(options, app).listen(port, () => {
    console.log(`Listening on port ${port}`);
});

app.get("/", (req, res) => {
    res.writeHead(200);
    res.end("Hello world\n");
});
```

For whatever reason, Deno doesn't seem to like the private key.

I can't share the certs, but just to show the general format (PEM, I think):

`host.crt`:
```text
-----BEGIN CERTIFICATE-----
(stuff)
-----END CERTIFICATE-----
```

`host.key`:
```text
-----BEGIN RSA PRIVATE KEY-----
(stuff)
-----END RSA PRIVATE KEY-----
```

Below is the run with `RUST_BACKTRACE=full` set. Thanks in advance!

```text
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.34.3
Args: ["c:\\bin\\deno.exe", "run", "-A", "main.ts"]

thread 'main' panicked at 'invalid key or certificate: General("invalid private key")', C:\a\deno\deno\ext\net\ops_tls.rs:1060:6
stack backtrace:
   0:     0x7ff72ef810f9 - napi_release_threadsafe_function
   1:     0x7ff72e04cfcb - napi_release_threadsafe_function
   2:     0x7ff72ef5b44a - napi_release_threadsafe_function
   3:     0x7ff72ef8580b - napi_release_threadsafe_function
   4:     0x7ff72ef85401 - napi_release_threadsafe_function
   5:     0x7ff72ef85015 - napi_release_threadsafe_function
   6:     0x7ff72de82d1c - napi_fatal_error
   7:     0x7ff72ef86057 - napi_release_threadsafe_function
   8:     0x7ff72ef85dc6 - napi_release_threadsafe_function
   9:     0x7ff72ef85d0f - napi_release_threadsafe_function
  10:     0x7ff72ef85ce4 - napi_release_threadsafe_function
  11:     0x7ff7301ed5b5 - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff7301eda76 - CrashForExceptionInNonABICompliantCodeRange
  13:     0x7ff72ea3fa7f - napi_release_threadsafe_function
  14:     0x7ff72ea39b7c - napi_release_threadsafe_function
  15:     0x7ff72ea35fa0 - napi_release_threadsafe_function
  16:     0x7ff72f51457b - CrashForExceptionInNonABICompliantCodeRange
  17:     0x7ff72f513c31 - CrashForExceptionInNonABICompliantCodeRange
  18:     0x7ff72ff8ea7a - CrashForExceptionInNonABICompliantCodeRange
  19:     0x7ff72fef925c - CrashForExceptionInNonABICompliantCodeRange
  20:     0x7ff72fef925c - CrashForExceptionInNonABICompliantCodeRange
  21:     0x7ff72fef925c - CrashForExceptionInNonABICompliantCodeRange
  22:     0x7ff72ff3848d - CrashForExceptionInNonABICompliantCodeRange
  23:     0x7ff72fef729c - CrashForExceptionInNonABICompliantCodeRange
  24:     0x7ff72fef6e97 - CrashForExceptionInNonABICompliantCodeRange
  25:     0x7ff72f3314f8 - napi_release_threadsafe_function
  26:     0x7ff72f332045 - napi_release_threadsafe_function
  27:     0x7ff72f3321ed - napi_release_threadsafe_function
  28:     0x7ff72f33a095 - napi_release_threadsafe_function
  29:     0x7ff72f339781 - napi_release_threadsafe_function
  30:     0x7ff72f3391a4 - napi_release_threadsafe_function
  31:     0x7ff72f3343d4 - napi_release_threadsafe_function
  32:     0x7ff72f1e83f1 - napi_release_threadsafe_function
  33:     0x7ff72f1d86a7 - napi_release_threadsafe_function
  34:     0x7ff72e2448eb - napi_release_threadsafe_function
  35:     0x7ff72de6779b - napi_fatal_error
  36:     0x7ff72de63498 - napi_fatal_error
  37:     0x7ff72de61805 - napi_fatal_error
  38:     0x7ff72de2b9b5 - napi_fatal_error
  39:     0x7ff72dbf99fd - napi_cancel_async_work
  40:     0x7ff72dae2120 - napi_cancel_async_work
  41:     0x7ff72de84d0d - napi_fatal_error
  42:     0x7ff72da16dc0 - <unknown>
  43:     0x7ff72df6b963 - napi_release_threadsafe_function
  44:     0x7ff7301a02cc - CrashForExceptionInNonABICompliantCodeRange
  45:     0x7fff2ce974b4 - BaseThreadInitThunk
  46:     0x7fff2e8426a1 - RtlUserThreadStart
```

**Comment by bartlomieju** [comment]
This is resolved on current Deno. The root cause was that traditional PKCS#1 RSA keys (`-----BEGIN RSA PRIVATE KEY-----`, the format in your `host.key`) weren't accepted by Deno's TLS stack back on 1.34.3 - only PKCS#8 (`-----BEGIN PRIVATE KEY-----`) worked, hence the "invalid private key" rejection of an otherwise valid key.

Verified now with a self-signed cert:

- PKCS#1 key (`-----BEGIN RSA PRIVATE KEY-----`): accepted, server starts
- PKCS#8 key (`-----BEGIN PRIVATE KEY-----`): accepted, server starts
- Invalid/garbage key: no panic - returns a clean `InvalidData: Unable to decode key`

So both issues are fixed: valid PKCS#1 keys are accepted, and the panic on an undecodable key (tracked in #19520) is gone too.

Closing as resolved. If you still hit a problem with your specific certificate chain on a current version, please open a new issue with details.
