### ISSUE TITLE
`BadResource: failed to write` error when using `Deno.serve` with `fresh`

### ISSUE THREAD

**Issue by Kyiro** [denoland/deno#19687]
I wasn't really sure if this belongs here or fresh but it really seems like an issue with `Deno.serve` itself

# Information
```
deno 1.34.3 (release, x86_64-pc-windows-msvc)
v8 11.5.150.2
typescript 5.0.4
```
# Steps to reproduce
1. Create a new Fresh project
```
deno run -A -r https://fresh.deno.dev
```
2. Update `main.ts`
```ts
await start(manifest, {
    experimentalDenoServe: true
});
```
3. Update `deno.json` to run with `--unstable`
4. Run the app and refresh the website in a web browser over and over
```ts
error: Uncaught (in promise) BadResource: failed to write
    at ext:deno_http/00_serve.js:430:29
    at Object.action (ext:deno_web/02_timers.js:153:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:67:10)
    at eventLoopTick (ext:core/01_core.js:189:21)
 ```

**Comment by mmastrac** [comment]
I suspect this is probably the same issue we fixed in #19154, but in a different path. It's something we need to fix but the error itself should in theory be harmless. When the browser terminates the connection before the stream has been fully written, we can get this error.

I'll be revisiting the deno stream code in a few weeks and this will likely get cleaned up then.

**Comment by Kyiro** [comment]
> It's something we need to fix but the error itself should in theory be harmless
It causes the whole program to fail
```ts
error: Uncaught (in promise) BadResource: failed to write    
    at ext:deno_http/00_serve.js:430:29
    at Object.action (ext:deno_web/02_timers.js:153:11)      
    at handleTimerMacrotask (ext:deno_web/02_timers.js:67:10)
    at eventLoopTick (ext:core/01_core.js:189:21)
Watcher Process failed. Restarting on file change...
```

**Comment by mmastrac** [comment]
Thanks for the update. I'll look at this today.
