### ISSUE TITLE
[BUG]: wasm network error despite `-A`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19698]
Tried updating `esbuild` in fresh https://github.com/denoland/fresh/pull/1402 , but I'm running into a weird network error.

```sh
TypeError: NetworkError when attempting to fetch resource.
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
    at async tryToInstantiateModule (https://deno.land/x/esbuild@v0.18.11/wasm.js:1765:682)
```

## Steps to reproduce

1. Clone https://github.com/denoland/fresh
2. Run `git checkout update-esbuild`
3. Run `deno run -A tests/fixture/main_wasm.ts`
4. Go to the website address that's displayed -> Terminal throws network errors

**Comment by marvinhagemeister** [comment]
Aha I found the cause. It was trying to load a file that didn't exist on disk, so it wasn't really a network error at all. The error message is pretty confusing in that regard and it doesn't show you which url it tried to fetch.
