### ISSUE TITLE
Deno coverage panic

### ISSUE THREAD

**Issue by spixy** [denoland/deno#19700]
CLI input:
>RUST_BACKTRACE=1 deno coverage --exclude="(\/resource\/)|(test\.(js|mjs|ts|jsx|tsx))$" tmp/coverageData/ --lcov > tmp/coverageData/coverageFile.lcov  

CLI output:
```
============================================================
Deno has panicked. This is a bug in Deno. . . .

Platform: linux x86_64
Version: 1.32.4
Args: ["deno", "coverage", "--exclude=(\\/resource\\/)|(test\\.(js|mjs|ts|jsx|tsx))$", "tmp/coverageData/", "--lcov"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    (\/resource\/)|(test\.(js|mjs|ts|jsx|tsx))$
     ^^
error: unrecognized escape sequence
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)', cli/tools/coverage/mod.rs:597:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::unwrap
   4: deno::tools::coverage::cover_files::{{closure}}
   5: deno::run_subcommand::{{closure}}
   6: deno::main::{{closure}}
   7: tokio::task::local::LocalSet::run_until::{{closure}}
   8: deno_runtime::tokio_util::run_local
   9: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Hint:**
look at mismatch between my input arg (`--exclude="(\/resource\/)|(test\.(js|mjs|ts|jsx|tsx))$"`)
and arg reported by deno: (`"--exclude=(\\/resource\\/)|(test\\.(js|mjs|ts|jsx|tsx))$"`)

**Comment by bartlomieju** [comment]
@spixy are you still able to reproduce this problem on latest Deno? We've done several improvements to `deno coverage` since this issue has been opened and I think this might already be fixed.

**Comment by bartlomieju** [comment]
Not able to reproduce this
