### ISSUE TITLE
importing express breaks other npm declaration files (`d.ts`) on latest canary

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#19712]
# Summary

```ts
// @deno-types=npm:@types/express
import * as express from "npm:express"
```
adding express and corresponding type declaration breaks type declarations from other npm-imported packages only on latest canary (aaabff7).

## Minimal reproduction

```
.
├── deno.jsonc
└── server.ts
```

<details><summary>deno.jsonc</summary>

```jsonc
{
  "fmt": {
    "semiColons": false,
    "lineWidth": 100
  },
  "lock": false,
  "nodeModulesDir": false,
  "compilerOptions": {
    "exactOptionalPropertyTypes": true,
    "noImplicitOverride": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "strict": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "noErrorTruncation": true,
    "noImplicitThis": true,
    "noUncheckedIndexedAccess": true
  }
}
```

</details> 

```ts
// @deno-types=npm:@types/express@4.17.17
import * as express from "npm:express@4.18.2"

import {
  AppRoute,
  initContract,
  ServerInferRequest as InferReq,
  ServerInferResponses as InferRes,
} from "npm:@ts-rest/core@3.26.3"
import { z } from "npm:zod@3.21.4"
import { initServer } from "npm:@ts-rest/express@3.26.3"

const c = initContract()
export const contract = c.router(
  { getTodo: { method: "GET", path: "/todos/:id", responses: { 200: z.string() } } },
)

type ServerInferRoute<T extends AppRoute> = (req: InferReq<T>) => Promise<InferRes<T>>

type GetTodo = ServerInferRoute<typeof contract.getTodo>
const getTodo: GetTodo = async ({ params: { id } }) => ({ status: 200, body: id } as const)

const s = initServer()
s.router(contract, { getTodo })

```

<details><summary> <b>errors</b> when checked with canary (<code>1.34.3+aaabff7</code>)</summary>

```
 ~/r/regression  deno.canary check --reload server.ts       6.1s  2023년 07월 04일 (화) 오후 09시 58분 39초
Check file:///home/scarf/repo/regression/server.ts
error: TS2322 [ERROR]: Type 'GetTodo' is not assignable to type 'AppRouteImplementationOrOptions<{ responses: { 200: ZodString; }; method: "GET"; path: "/todos/:id"; }>'.
  Type 'GetTodo' is not assignable to type 'AppRouteQueryImplementation<{ responses: { 200: ZodString; }; method: "GET"; path: "/todos/:id"; }>'.
    Types of parameters 'req' and 'input' are incompatible.
      Property 'params' is missing in type '{ [x: string]: any; } & { req: TsRestRequest<{ responses: { 200: ZodString; }; method: "GET"; path: "/todos/:id"; }>; res: Response<any, Record<string, any>, number>; }' but required in type '{ params: { id: string; }; }'.
s.router(contract, { getTodo })
                     ~~~~~~~
    at file:///home/scarf/repo/regression/server.ts:24:22

    'params' is declared here.
        params: [keyof PathParamsWithCustomValidators<T>] extends [never] ? never : Prettify<PathParamsWithCustomValidators<T>>;
        ~~~~~~
        at file:///home/scarf/.cache/deno/npm/registry.npmjs.org/@ts-rest/core/3.26.3/src/lib/infer-types.d.ts:39:5    The expected type comes from property 'getTodo' which is declared here on type 'RecursiveRouterObj<RecursivelyApplyOptions<{ getTodo: { method: "GET"; path: "/todos/:id"; responses: { 200: ZodString; }; }; }, {}>>'
      { getTodo: { method: "GET", path: "/todos/:id", responses: { 200: z.string() } } },
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at file:///home/scarf/repo/regression/server.ts:15:5
 !  ~/r/regression                                             
```

</details> 

<details><summary>does <b>not error</b> when checked with stable (<code>1.34.3</code>)</summary>

```
 ~/r/regression  deno.stable check --reload server.ts              2023년 07월 04일 (화) 오후 09시 58분 32초
Check file:///home/scarf/repo/regression/server.ts
 ~/r/regression                                             
```

</details> 

1. **both** will not emit error if the first two lines (express and its type declaration) are removed from the code, which suggest that inclusion of a package may break another package's type declarations.
2. the regression is only limited to declaration files (`d.ts`) as both times the scripts can be ran without runtime errors.

## Confirmation that it's not due to typescript version increment

```
.
├── package.json
├── pnpm-lock.yaml
├── server.ts
└── tsconfig.json
```

<details><summary>package.json</summary>

```json
{
  "name": "regression2",
  "dependencies": {
    "@ts-rest/core": "^3.26.3",
    "@ts-rest/express": "^3.26.3",
    "@types/express": "^4.17.17",
    "express": "^4.18.2",
    "zod": "^3.21.4"
  }
}
```

</details> 

```
$ tsc --version 
Version 5.1.6
$ tsc --init
$ tsc --noemit --project .
```
it will pass type checks.

## System Option

```
$ deno.stable --version
deno 1.34.3 (release, x86_64-unknown-linux-gnu)
v8 11.5.150.2
typescript 5.0.4

$ deno.canary --version
deno 1.34.3+aaabff7 (canary, x86_64-unknown-linux-gnu)
v8 11.6.189.7
typescript 5.1.6
```

**Comment by dsherret** [comment]
Remove the express import and you'll see:

```
V:\scratch
> ../deno/target/debug/deno check --all main.ts
Check file:///V:/scratch/main.ts
error: TS2305 [ERROR]: Module '"internal:///missing_dependency.d.ts"' has no exported member 'Express'.
import { Express, NextFunction, Response } from 'express-serve-static-core';
         ~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@ts-rest/express/3.26.3/src/lib/types.d.ts:2:10

TS2305 [ERROR]: Module '"internal:///missing_dependency.d.ts"' has no exported member 'NextFunction'.
import { Express, NextFunction, Response } from 'express-serve-static-core';
                  ~~~~~~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@ts-rest/express/3.26.3/src/lib/types.d.ts:2:19

TS2305 [ERROR]: Module '"internal:///missing_dependency.d.ts"' has no exported member 'Response'.
import { Express, NextFunction, Response } from 'express-serve-static-core';
                                ~~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@ts-rest/express/3.26.3/src/lib/types.d.ts:2:33

TS2305 [ERROR]: Module '"internal:///missing_dependency.d.ts"' has no exported member 'IRouter'.
import type { IRouter } from 'express-serve-static-core';
              ~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@ts-rest/express/3.26.3/src/lib/ts-rest-express.d.ts:2:15

Found 4 errors.
```

Then add the express import, and with `--all` you'll see:

```
> ../deno/target/debug/deno check --all main.ts
Check file:///V:/scratch/main.ts
error: TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    export interface Server extends NodeJS.EventEmitter {
                                    ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/connect/3.4.35/index.d.ts:36:37

TS2580 [ERROR]: Cannot find name 'Buffer'.
        verify?(req: http.IncomingMessage, res: http.ServerResponse, buf: Buffer, encoding: string): void;
                                                                          ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/body-parser/1.19.2/index.d.ts:65:75

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        pipe<T extends NodeJS.WritableStream>(res: T): T;
                       ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/send/0.17.1/index.d.ts:197:24

TS2339 [ERROR]: Property 'headers' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
type AppRouteQueryImplementation<T extends AppRouteQuery> = (input: ServerInferRequest<T, Express['request']['headers']> & {
                                                                                                             ~~~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@ts-rest/express/3.26.3/src/lib/types.d.ts:4:110

TS2339 [ERROR]: Property 'headers' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
type AppRouteMutationImplementation<T extends AppRouteMutation> = (input: ServerInferRequest<T, Express['request']['headers']> & {
                                                                                                                   ~~~~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@ts-rest/express/3.26.3/src/lib/types.d.ts:8:116

TS2322 [ERROR]: Type 'GetTodo' is not assignable to type 'AppRouteImplementationOrOptions<{ responses: { 200: ZodString; }; method: "GET"; path: "/todos/:id"; }>'.
  Type 'GetTodo' is not assignable to type 'AppRouteQueryImplementation<{ responses: { 200: ZodString; }; method: "GET"; path: "/todos/:id"; }>'.
    Types of parameters 'req' and 'input' are incompatible.
      Property 'params' is missing in type '{ [x: string]: any; } & { req: TsRestRequest<{ responses: { 200: ZodString; }; method: "GET"; path: "/todos/:id"; }>; res: Response<any, Record<string, any>, number>; }' but required in type '{ params: { id: string; }; }'.
s.router(contract, { getTodo })
                     ~~~~~~~
    at file:///V:/scratch/main.ts:24:22

    'params' is declared here.
        params: [keyof PathParamsWithCustomValidators<T>] extends [never] ? never : Prettify<PathParamsWithCustomValidators<T>>;
        ~~~~~~
        at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@ts-rest/core/3.26.3/src/lib/infer-types.d.ts:39:5    The expected type comes from property 'getTodo' which is declared here on type 'RecursiveRouterObj<RecursivelyApplyOptions<{ getTodo: { method: "GET"; path: "/todos/:id"; responses: { 200: ZodString; }; }; }, {}>>'
      { getTodo: { method: "GET", path: "/todos/:id", responses: { 200: z.string() } } },
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at file:///V:/scratch/main.ts:15:5

Found 6 errors.
```

Ensure `npm:@types/node` is imported, by adding the following to the top of the file:

```ts
/// <reference types="npm:@types/node" />
```

Then now it works:

```
> ../deno/target/debug/deno check --all main.ts
Check file:///V:/scratch/main.ts
```

**Comment by dsherret** [comment]
I need to implement this issue sometime. It would have just made this work: https://github.com/denoland/deno/issues/18385 (it's a little challenging though).

Btw, not sure if this is related, but maybe: https://github.com/colinhacks/zod/issues/2523

**Comment by scarf005** [comment]
thanks, it correctly type checks after adding reference types.
closing in favor of #18385.

**Comment by scarf005** [comment]
and yes, your speculation is correct, zod type extraction does not seem to work correctly onwards from typescript 5.1.3.
