### ISSUE TITLE
[Bug] Deno has panicked

### ISSUE THREAD

**Issue by KaKi87** [denoland/deno#19711]
Hello,

The following app : https://git.kaki87.net/KaKi87/deno-api

Has crashed on my server with the following output :

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.34.1
Args: ["deno", "run", "-A", "./main.js"]                                                  
thread 'main' panicked at 'OS can't spawn worker thread: Resource temporarily unavailable (os error 11)', /home/runner/work/deno/deno/core/task.rs:71:16                            stack backtrace:                                                                             0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5                                                                                     1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14                                                                                    2: <deno_fs::std_fs::RealFs as deno_fs::interface::FileSystem>::read_file_async::{{closure}}                                                                                        3: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll       4: deno_core::runtime::queue_async_op                                                     5: deno_fs::ops::op_fs_read_file_async::v8_fn_ptr                                         6: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi                                                                                                at ./../../../../v8/src/builtins/builtins-api.cc:113:36
   7: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE                                         at ./../../../../v8/src/builtins/builtins-api.cc:135:1                          8: Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Thanks

**Comment by KaKi87** [comment]
Hello,

It happened again :

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.36.0
Args: ["deno", "run", "-A", "./main.js"]

thread 'main' panicked at 'OS can't spawn worker thread: Resource temporarily unavailable (os error 11)', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.199.0/task.rs:71:16
stack backtrace:
   0:     0x5636bcc12c01 - Builtins_InvokeIntrinsicWideHandler
   1:     0x5636bcc43bef - gimli::read::unit::DebugInfoUnitHeadersIter<R>::next::ha158606bae7f90e7
   2:     0x5636bcc0bfa1 - Builtins_ShiftRightLogicalWideHandler
   3:     0x5636bcc12a15 - Builtins_CallRuntimeWideHandler
   4:     0x5636bcc14587 - Builtins_TestLessThanWideHandler
   5:     0x5636bcc14374 - Builtins_TestEqualStrictWideHandler
   6:     0x5636bd01eff0 - deno::tools::coverage::CoverageCollector::stop_collecting::{{closure}}::hf312e5d26cc880a0
   7:     0x5636bcc14c0d - Builtins_TestLessThanWideHandler
   8:     0x5636bcc149a7 - Builtins_TestLessThanWideHandler
   9:     0x5636bcc13036 - Builtins_InvokeIntrinsicWideHandler
  10:     0x5636bcc146f2 - Builtins_TestLessThanWideHandler
  11:     0x5636bcc40ad3 - gimli::leb128::low_bits_of_byte::h6f8be13b371b247a
                               at /cargo/registry/src/index.crates.io-6f17d22bba15001f/gimli-0.28.0/src/leb128.rs:53:5
  12:     0x5636bcc40ad3 - gimli::leb128::read::signed::h68fc591e1f8963ec
                               at /cargo/registry/src/index.crates.io-6f17d22bba15001f/gimli-0.28.0/src/leb128.rs:140:38
  13:     0x5636bcc40ad3 - gimli::read::reader::Reader::read_sleb128::h12e50f1f7262a34d
                               at /cargo/registry/src/index.crates.io-6f17d22bba15001f/gimli-0.28.0/src/read/reader.rs:433:9
  14:     0x5636bcc40ad3 - gimli::read::line::parse_attribute::ha323cb37133727e4
                               at /cargo/registry/src/index.crates.io-6f17d22bba15001f/gimli-0.28.0/src/read/line.rs:1839:24
  15:     0x5636bd9ed0df - trust_dns_proto::rr::record_data::RData::read::h1de13c68f022c20e
  16:     0x5636bd55d04a - deno_net::ops_tls::op_net_connect_tls<NP>::v8_fn_ptr::h3ce5f55c5f46f18f
  17:     0x5636bd4c361e - tokio::runtime::task::raw::poll::hacd61e8a39b26556
  18:     0x5636bca46edc - _ZN2v88internal8compiler10turboshaft21ValueNumberingReducerINS2_12ReducerStackINS2_9AssemblerINS2_12reducer_listIJNS2_18AssertTypesReducerES3_NS2_20TypeInferenceReducerEEEEEEJS8_NS2_11ReducerBaseEEEEE9AddOrFindINS2_12ComparisonOpEEENS2_7OpIndexESG_
                               at ./../../../../v8/src/compiler/turboshaft/value-numbering-reducer.h:146:19
```

Thanks

**Comment by KaKi87** [comment]
It keeps happening :

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.36.4
Args: ["/home/kaki/.deno/bin/deno", "run", "--allow-read", "--allow-env", "--allow-sys=hostname", "--allow-net", "--allow-run", "./main.js"]

thread 'main' panicked at 'OS can't spawn worker thread: Resource temporarily unavailable (os error 11)', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/client/connect/dns.rs:121:24
stack backtrace:
   0:     0x55ef2a9e70f1 - _ZN2v88internal8compiler10turboshaft22MachineLoweringReducerINS2_12ReducerStackINS2_9AssemblerINS2_12reducer_listIJNS2_15VariableReducerES3_NS2_18FastApiCallReducerENS2_27RequiredOptimizationReducerENS2_21Selec
tLoweringReducerENS2_49MachineOptimizationReducerSignallingNanImpossibleEEEEEEJS8_S9_SA_SB_NS2_11ReducerBaseEEEEE22ReduceStringToCaseIntlENS2_1VINS0_6StringEEENS2_18StringToCaseIntlOp4KindE
                               at ./../../../../v8/src/compiler/turboshaft/machine-lowering-reducer.h:1862
   1:     0x55ef2aa1c90f - Emit<v8::internal::compiler::turboshaft::FrameStateOp, v8::base::Vector<v8::internal::compiler::turboshaft::OpIndex>, bool, const v8::internal::compiler::turboshaft::FrameStateData *>
                               at ./../../../../v8/src/compiler/turboshaft/assembler.h:3578:44
   2:     0x55ef2a9dfd77 - _ZN2v88internal8compiler10turboshaft20AssemblerOpInterfaceINS2_9AssemblerINS2_12reducer_listIJNS2_15VariableReducerENS2_22MachineLoweringReducerENS2_18FastApiCallReducerENS2_27RequiredOptimizationReducerENS2_21
SelectLoweringReducerENS2_49MachineOptimizationReducerSignallingNanImpossibleEEEEEEE24ControlFlowHelper_ElseIfIZNS7_INS2_12ReducerStackISD_JS8_S9_SA_SB_NS2_11ReducerBaseEEEEE16ReduceFloatUnaryENS2_7OpIndexENS2_12FloatUnaryOp4KindENS2_19FloatRepresentationEEUlvE1_EEbOT_ 
                               at ./../../../../v8/src/compiler/turboshaft/assembler.h:3376:20
   3:     0x55ef2a9e6f05 - Emit<v8::internal::compiler::turboshaft::AtomicWord32PairOp, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::turboshaft::OpIndex, v8::internal::compiler::turboshaft::AtomicWord32PairOp::OpKind, int>
                               at ./../../../../v8/src/compiler/turboshaft/assembler.h:3578:44
   4:     0x55ef2a9e8b93 - _ZN2v88internal8compiler10turboshaft22MachineLoweringReducerINS2_12ReducerStackINS2_9AssemblerINS2_12reducer_listIJNS2_15VariableReducerES3_NS2_18FastApiCallReducerENS2_27RequiredOptimizationReducerENS2_21SelectLoweringReducerENS2_49MachineOptimizationReducerSignallingNanImpossibleEEEEEEJS8_S9_SA_SB_NS2_11ReducerBaseEEEEE14ReduceObjectIsENS2_1VINS0_6ObjectEEENS2_10ObjectIsOp4KindENSK_16InputAssumptionsE
                               at ./../../../../v8/src/compiler/turboshaft/machine-lowering-reducer.h:184:23
   5:     0x55ef2a9e8924 - _ZN2v88internal8compiler10turboshaft22MachineLoweringReducerINS2_12ReducerStackINS2_9AssemblerINS2_12reducer_listIJNS2_15VariableReducerES3_NS2_18FastApiCallReducerENS2_27RequiredOptimizationReducerENS2_21SelectLoweringReducerENS2_49MachineOptimizationReducerSignallingNanImpossibleEEEEEEJS8_S9_SA_SB_NS2_11ReducerBaseEEEEE14ReduceObjectIsENS2_1VINS0_6ObjectEEENS2_10ObjectIsOp4KindENSK_16InputAssumptionsE
                               at ./../../../../v8/src/compiler/turboshaft/machine-lowering-reducer.h:254:25
   6:     0x55ef2ae09f55 - core::ptr::drop_in_place<lock_api::mutex::Mutex<parking_lot::raw_mutex::RawMutex,std::collections::hash::map::HashMap<alloc::string::String,alloc::sync::Arc<alloc::vec::Vec<alloc::string::String>>>>>::hcf004358603a9d02
   7:     0x55ef2a9e92fe - _ZN2v88internal8compiler10turboshaft22MachineLoweringReducerINS2_12ReducerStackINS2_9AssemblerINS2_12reducer_listIJNS2_15VariableReducerES3_NS2_18FastApiCallReducerENS2_27RequiredOptimizationReducerENS2_21SelectLoweringReducerENS2_49MachineOptimizationReducerSignallingNanImpossibleEEEEEEJS8_S9_SA_SB_NS2_11ReducerBaseEEEEE14ReduceObjectIsENS2_1VINS0_6ObjectEEENS2_10ObjectIsOp4KindENSK_16InputAssumptionsE
                               at ./../../../../v8/src/compiler/turboshaft/machine-lowering-reducer.h:233:11
   8:     0x55ef2a9e9087 - _ZN2v88internal8compiler10turboshaft22MachineLoweringReducerINS2_12ReducerStackINS2_9AssemblerINS2_12reducer_listIJNS2_15VariableReducerES3_NS2_18FastApiCallReducerENS2_27RequiredOptimizationReducerENS2_21SelectLoweringReducerENS2_49MachineOptimizationReducerSignallingNanImpossibleEEEEEEJS8_S9_SA_SB_NS2_11ReducerBaseEEEEE14ReduceObjectIsENS2_1VINS0_6ObjectEEENS2_10ObjectIsOp4KindENSK_16InputAssumptionsE
   9:     0x55ef2a9e7556 - _ZN2v88internal8compiler10turboshaft20AssemblerOpInterfaceINS2_9AssemblerINS2_12reducer_listIJNS2_15VariableReducerENS2_22MachineLoweringReducerENS2_18FastApiCallReducerENS2_27RequiredOptimizationReducerENS2_21SelectLoweringReducerENS2_49MachineOptimizationReducerSignallingNanImpossibleEEEEEEE15CallRuntimeImplINS2_1VINS0_6StringEEENSt2Cr5tupleIJSI_EEEEET_PNS0_7IsolateENS0_7Runtime10FunctionIdEPKNS2_16TSCallDescriptorENS2_7OpIndexESU_RKT0_
                               at ./../../../../v8/src/compiler/turboshaft/assembler.h:2372:22
  10:     0x55ef2a9e8dd2 - _ZN2v88internal8compiler10turboshaft22MachineLoweringReducerINS2_12ReducerStackINS2_9AssemblerINS2_12reducer_listIJNS2_15VariableReducerES3_NS2_18FastApiCallReducerENS2_27RequiredOptimizationReducerENS2_21SelectLoweringReducerENS2_49MachineOptimizationReducerSignallingNanImpossibleEEEEEEJS8_S9_SA_SB_NS2_11ReducerBaseEEEEE14ReduceObjectIsENS2_1VINS0_6ObjectEEENS2_10ObjectIsOp4KindENSK_16InputAssumptionsE
                               at ./../../../../v8/src/compiler/turboshaft/machine-lowering-reducer.h:340:11
  11:     0x55ef2aa197f3 - _ZN2v88internal8compiler10turboshaft9LabelBaseILb0EJNS2_13FloatWithBitsILm64EEEEE6GotoIfINS2_9AssemblerINS2_12reducer_listIJNS2_15VariableReducerENS2_22MachineLoweringReducerENS2_18FastApiCallReducerENS2_27RequiredOptimizationReducerENS2_21SelectLoweringReducerEEEEEEEEvRT_NS2_7OpIndexENS0_10BranchHintERKNSt2Cr5tupleIJNS2_1VIS5_EEEEE
                               at ./../../../../v8/src/compiler/turboshaft/assembler.h:161
  12:     0x55ef2b96de39 - tokio::runtime::task::raw::drop_abort_handle::he89b6f10e5c429ce
  13:     0x55ef2b8782ce - deno_runtime::worker::MainWorker::from_options::h4fc1b5babbb6e7af
  14:     0x55ef2b8236c9 - deno_http::http_next::op_http_serve_on<HTTP>::v8_fn_ptr::h9b7a54f36e5afc94
  15:     0x55ef2b822d07 - deno_http::http_next::op_http_serve_on<HTTP>::v8_fn_ptr::h9b7a54f36e5afc94
  16:     0x55ef2b872465 - deno_runtime::web_worker::WebWorker::bootstrap::hbabdb7cfb32ea648
  17:     0x55ef2b875c88 - deno_runtime::web_worker::run_web_worker::{{closure}}::hf387edadbb72766e
  18:     0x55ef2b8645b0 - deno_runtime::permissions::parse_path_list::h01325f82a631f930
  19:     0x55ef2b85deec - deno_runtime::permissions::UnaryPermission<deno_runtime::permissions::FfiDescriptor>::revoke::he77be86ef5c69870
  20:     0x55ef2b848b7a - deno_runtime::permissions::PermissionState::fmt_access::h465fe1d910c081eb
  21:     0x55ef2b86e70b - deno_runtime::web_worker::WebWorker::from_options::h6211e22013806645
  22:     0x55ef2b2f62db - dprint_core::configuration::get_nullable_value::h72b017530762bf41
  23:     0x55ef2b371f41 - core::str::<impl str>::trim_end_matches::hfa29f815dab300e4
  24:     0x55ef2b808a7f - deno_core::resources::Resource::write_error::h9ee38c9e63f7b391
  25:     0x55ef2b816a0e - deno_core::resources::Resource::read_byob::{{closure}}::he6a8af3ded494041
  26:     0x55ef2a816edc - _ZN2v88internal8compiler23EffectControlLinearizer16LowerObjectIsSmiEPNS1_4NodeE
                               at ./../../../../v8/src/compiler/effect-control-linearizer.cc:4906:10
```

Someone, please ?

@bartlomieju @dsherret @lucacasonato @nayeemrmn @littledivy @kt3k @crowlKats @mmastrac @marcosc90 @aapoalas

Thanks

**Comment by bartlomieju** [comment]
@KaKi87 are you still experiencing this problem in latest Deno? Can you provide a reproduction code?

**Comment by KaKi87** [comment]
The app is linked in my original post. I think I fixed the issue by replacing `Deno.run` with `Deno.Command` :

```diff
diff --git a/lib/exec.js b/lib/exec.js
index 5bf600c..0c94f75 100644
--- a/lib/exec.js
+++ b/lib/exec.js
@@ -1,11 +1,15 @@
-export default async (...args) => {
+export default async (command, ...args) => {
-    const command = Deno.run({
-        cmd: args,
-        stdout: 'piped',
-        stderr: 'piped'
-    });
+    const {
+        stdout,
+        stderr
+    } = await (new Deno.Command(
+        command,
+        {
+            args
+        }
+    )).output();
     return {
-        stdout: new TextDecoder().decode(await command.output()),
+        stdout: new TextDecoder().decode(stdout),
-        stderr: new TextDecoder().decode(await command.stderrOutput())
+        stderr: new TextDecoder().decode(stderr)
     };
 };
\ No newline at end of file
```

**Comment by satyarohith** [comment]
Deno.run is deprecated so we're closing this issue as it's no longer relevant.
