### ISSUE TITLE
Error with ext/node - `node:streams/promises`

### ISSUE THREAD

**Issue by swgn** [denoland/deno#19817]
I am receiving the following error when using `node:streams/promises` with https://github.com/porsager/postgres/issues/609

```
TypeError [ERR_INVALID_ARG_TYPE] The "streams[stream.length - 1]" property must be of type function. Received an instance of Writable
    at __node_internal_ (ext:deno_node/_stream.mjs:379:15)
    at popCallback (ext:deno_node/_stream.mjs:5084:7)
    at pipeline (ext:deno_node/_stream.mjs:5165:41)
```
Appears related to the streams/promises pollyfill changes pushed for v1.33.

This worked as expected up until https://github.com/denoland/deno/pull/19045; has remained broken in subsequent releases.

Many thanks.

**Comment by swgn** [comment]
Legend, thank you!
