### ISSUE TITLE
Deno.bench panics with 'already mutably borrowed: BorrowError' when crypto.getRandomValues throws QuotaExceededError after another benchmark that calls crypto.getRandomValues

### ISSUE THREAD

**Issue by publictheta** [denoland/deno#19829]
This code throws a `QuotaExceededError`, and Deno handles it correctly. The benchmark fails, but Deno does not panic.

`ok.ts`:

```ts
Deno.bench(function cryptoGetRandomValuesUint32x100000() {
    crypto.getRandomValues(new Uint32Array(100000)); // throws QuotaExceededError
});
```

```shell
deno bench ok.ts
```

```
benchmark                               time (avg)             (min … max)       p75       p99      p995
-------------------------------------------------------------------------- -----------------------------
cryptoGetRandomValuesUint32x100000  error: QuotaExceededError: The ArrayBufferView's byte length (400000) exceeds the number of bytes of entropy available via this API (65536)
    crypto.getRandomValues(new Uint32Array(100000));
           ^
    at Crypto.getRandomValues (ext:deno_crypto/00_crypto.js:4724:9)
    at cryptoGetRandomValuesUint32x100000 (.../panic.ts:2:12)
error: Bench failed
```

However, if I add another benchmark that calls `crypto.getRandomValues`, Deno panics. The order of the benchmarks matters. `Uint8Array` does not cause the panic, but the others (`Uint8ClampedArray`, `Int8Array`, `Uint16Array`, `Int16Array`, etc.) do.

`panic.ts`:

```ts
Deno.bench(function cryptoGetRandomValuesUint32x1() {
    crypto.getRandomValues(new Uint32Array(1));
});

Deno.bench(function cryptoGetRandomValuesUint32x100000() {
    crypto.getRandomValues(new Uint32Array(100000)); // throws QuotaExceededError
});
```

```shell
RUST_BACKTRACE=1 deno bench panic.ts
```

```
benchmark                               time (avg)             (min … max)       p75       p99      p995
-------------------------------------------------------------------------- -----------------------------
cryptoGetRandomValuesUint32x1             1.8 µs/iter   (985.79 ns … 2.34 µs)   2.11 µs   2.34 µs   2.34 µs

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.35.0
Args: ["deno", "bench", "panic.ts"]

thread 'tokio-runtime-worker' panicked at 'already mutably borrowed: BorrowError', .../cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.194.0/ops_builtin_v8.rs:827:1
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: deno_core::ops_builtin_v8::op_apply_source_map::v8_fn_ptr
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by littledivy** [comment]
```
$ deno bench -A test.mjs
    CPU | Apple M1 Pro
Runtime | Deno 2.1.6 (aarch64-apple-darwin)

file:///Users/divy/gh/deno_core/test.mjs

benchmark                            time/iter (avg)        iter/s      (min … max)           p75      p99     p995
------------------------------------ ----------------------------- --------------------- --------------------------
cryptoGetRandomValuesUint32x1               231.8 ns     4,315,000 (220.3 ns … 255.1 ns) 235.2 ns 247.5 ns 251.6 ns
cryptoGetRandomValuesUint32x100000   error: QuotaExceededError: The ArrayBufferView's byte length (400000) exceeds the number of bytes of entropy available via this API (65536)
    crypto.getRandomValues(new Uint32Array(100000)); // throws QuotaExceededError
           ^
    at Crypto.getRandomValues (ext:deno_crypto/00_crypto.js:5161:5)
    at cryptoGetRandomValuesUint32x100000 (file:///Users/divy/gh/deno_core/test.mjs:6:12)
```

No longer panics in Deno 2
