### ISSUE TITLE
More helpful error message when requiring a module that fails to parse with require?

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#19842]
When `require` fails to parse a module, perhaps it should say what file it failed to parse?

For example:

```
// main.ts
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

console.log(require("./other.ts"));

// other.ts
import "./somethingElse.ts"
```

It will error with just:

```
error: Uncaught SyntaxError: Cannot use import statement outside a module
    at Object.evalContext (ext:core/01_core.js:842:14)
    at wrapSafe (node:module:696:27)
    at Module._compile (node:module:706:29)
    at Object.Module._extensions..js (node:module:738:12)
    at Module.load (node:module:653:34)
    at Function.Module._load (node:module:535:16)
    at Module.require (node:module:672:23)
    at require (node:module:772:20)
    at ...etc.../main.ts:1:7
```

It would be useful if it said that it failed to parse other.ts and provide that path.

**Comment by dsherret** [comment]
This is the error that Node gives. There is definitely some improvement we can make here:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/david/dev/deno-graphql-issue/modules/m1/graphql/resolvers.js from /home/david/dev/deno-graphql-issue/noop.js not supported.
Instead change the require of resolvers.js in /home/david/dev/deno-graphql-issue/noop.js to a dynamic import() which is available in all CommonJS modules.
    at file:///home/david/dev/deno-graphql-issue/node_modules/@graphql-tools/load-files/esm/index.js:103:33
    at Array.map (<anonymous>)
    at loadFilesSync (file:///home/david/dev/deno-graphql-issue/node_modules/@graphql-tools/load-files/esm/index.js:94:10)
    at file:///home/david/dev/deno-graphql-issue/asdf.js:5:23 {
  code: 'ERR_REQUIRE_ESM'
}
```
