### ISSUE TITLE
Error in ReadableStream/TransformStream is swallowed in Deno.serve

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno#19867]
The following `Deno.serve` code  has a subtle error (toUppperCase -> toUpperCase). When running this code, there is nothing to implicate the failing TransformStream handler.

```ts
Deno.serve((req) => new Response(
          new ReadableStream({
          start(c) {
             c.enqueue(new TextEncoder().encode('test'));
             c.close();
           }
          }).pipeThrough(new TextDecoderStream())
          .pipeThrough(
            new TransformStream({
              transform(value, c) {
                const transformedValue = value.toUppperCase();
                console.log(value);
                c.enqueue(value.toUpperCase());
              },
              flush() {
                console.log('flush');
              },
            })
          )
          .pipeThrough(new TextEncoderStream())
      , {headers:{'Access-Control-Allow-Origin':'*'}}));
```

What should happen:

 - A stack trace implicating the transformer callback function should be printed
 - Should anything be printed to the HTTP output? If we haven't printed anything, we should probably return a 500

What actually happens:

 - No error is printed

The following test case works as expected:

```ts
Deno.serve((req) => new Response(
          new ReadableStream({
          start(c) {
             c.enqueue(new TextEncoder().encode('test'));
             c.close();
           }
          }).pipeThrough(new TextDecoderStream())
          .pipeThrough(
            new TransformStream({
              transform(value, c) {
                const transformedValue = value.toUpperCase();
                console.log(value);
                c.enqueue(value.toUpperCase());
              },
              flush() {
                console.log('flush');
              },
            })
          )
          .pipeThrough(new TextEncoderStream())
      , {headers:{'Access-Control-Allow-Origin':'*'}}));
```

**Comment by jollytoad** [comment]
This is repeatable with a much simpler case without any TransformStream:

```ts
#!/usr/bin/env -S deno run --allow-net --watch

await Deno.serve(() => {
  return new Response(ReadableStream.from(content()));
}).finished;

// deno-lint-ignore require-yield
function* content() {
  throw new Error("EPIC FAIL");
}
```

Hit the server and the request fails, but no errors are logged.

Also applies using `deno serve` too:

```ts
#!/usr/bin/env -S deno serve --allow-net --watch

export default {
  fetch() {
    return new Response(ReadableStream.from(content()));
  }
}

// deno-lint-ignore require-yield
function* content() {
  throw new Error("EPIC FAIL");
}
```

This is surely a bug in Deno, unhandled errors should never be silently discarded by a runtime.

If a stream throws an error under other circumstances (eg. pipe to stdout), then a error is produced, I'd expect similar behaviour when passing the steam to Response...

```ts
#!/usr/bin/env -S deno run --allow-net --watch

await ReadableStream.from(content()).pipeTo(Deno.stdout.writable);

// deno-lint-ignore require-yield
function* content() {
  throw new Error("EPIC FAIL");
}
```

```
error: Uncaught (in promise) Error: EPIC FAIL
  throw new Error("EPIC FAIL");
        ^
    at content (.../fail.ts:7:9)
    at content.next (<anonymous>)
    at Object.next (ext:deno_webidl/00_webidl.js:990:27)
    at Object.next (ext:deno_webidl/00_webidl.js:998:52)
    at ReadableStreamDefaultController.<anonymous> (ext:deno_web/06_streams.js:5186:30)
    at readableStreamDefaultControllerCallPullIfNeeded (ext:deno_web/06_streams.js:1694:49)
    at ReadableStreamDefaultController.[[[PullSteps]]] (ext:deno_web/06_streams.js:6083:7)
    at readableStreamDefaultReaderRead (ext:deno_web/06_streams.js:2508:36)
    at ext:deno_web/06_streams.js:2737:9
    at new Promise (<anonymous>)
```
