### ISSUE TITLE
incorrect npm:redis type defs

### ISSUE THREAD

**Issue by topperspal** [denoland/deno#19939]
```ts
const resInsert = await redis.rPush("list", "a");  // type string
const resPos = await redis.lPos("list", "a");  // type string
```
but if we log **typeof** it shows number

```ts
console.log(typeof resInsert); // number
```

I migrated from deno redis to npm:redis, but now I need to revert it😔

**Comment by dsherret** [comment]
Sorry, try adding the `@types/node` package via `/// <reference types="npm:@types/node" />`:

```
/// <reference types="npm:@types/node" />
import { createClient } from "npm:redis@4.6"

const client = createClient();

const resInsert = await client.rPush("list", "a"); // number
```

The issue here can be seen by type checking with `--all`, which will show type checking errors in npm packages in addition to your local modules:

```
> deno check --all main.ts
Check file:///V:/scratch/main.ts
error: TS2580 [ERROR]: Cannot find name 'Buffer'.
export type RedisCommandRawReply = string | number | Buffer | null | undefined | Array<RedisCommandRawReply>;
                                                     ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@redis/client/1.5.8/dist/lib/commands/index.d.ts:5:54

...etc...

TS2580 [ERROR]: Cannot find name 'Buffer'.
    onReplyChunk(chunk: Buffer): void;
                        ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@redis/client/1.5.8/dist/lib/client/commands-queue.d.ts:38:25

Found 15 errors.
```

**Comment by dsherret** [comment]
This is because of #18385. In the future that will cause those types to be automatically included.

**Comment by bartlomieju** [comment]
This is resolved on current canary (deno 2.8.1+d95ceb5 (canary, release, aarch64-apple-darwin)). The fix @dsherret referenced (#18385, auto-including node types for npm packages) has landed, so `npm:redis` now resolves its return types correctly under a normal `deno check`:

```ts
import { createClient } from "npm:redis@4.6";
const client = createClient();
const resInsert = await client.rPush("list", "a");
const n: number = resInsert;          // deno check -> passes
const wrong: string = resInsert;      // deno check -> TS2322: Type 'number' is not assignable to type 'string'
```

So `rPush` (and `lPos`) now infer as `number`, matching the runtime value — the originally reported mismatch is gone.

Note: `deno check --all` still reports errors *inside* the redis package itself (`/// <reference types="node" />` not resolving without an explicit `@types/node` dep). That's a separate concern about type-checking npm package internals with `--all`, not the inferred-type bug reported here. Closing as resolved; if the `--all` behavior matters to anyone, a fresh issue with a minimal repro would be the way to track it.
