### ISSUE TITLE
Serving static file using Express

### ISSUE THREAD

**Issue by crohncapstan** [denoland/deno#19932]
**Describe the bug**
I'm trying to migrate to Deno, but I'm facing a bug when I try to create a simple ExpressJS project: serving static files throws an error;
Register a simple middleware in Express to serve static files isn't a simple task as I used to think.

**Steps to Reproduce**

`./src/main.ts`
```ts
//#region IMPORTS
// NATIVE
import { load as loadEnv } from "std/dotenv/mod.ts";
import { resolve } from "std/path/mod.ts";

// NPM
import express from "npm:express@~4.18.2";
import "npm:hbs@~4.2.0";
import createError from "npm:http-errors@~2.0.0";
import cookieParser from "npm:cookie-parser@~1.4.6";
//#endregion IMPORTS

const env = await loadEnv();
const port: number = parseInt(env["PORT"]);
const app = express();

// view engine setup
app.set("views", resolve(Deno.cwd(), "src", "views"));
app.set("view engine", "hbs");
app.set("view options", { layout: "_shared/layout" });

app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// #####################################################################################
app.use('/static', express.static(resolve(Deno.cwd(), 'src', 'public'))); // <----------
// #####################################################################################

app.listen(port);
```

Then
```sh
deno run -A --watch ./src/main.ts
```

**Expected behavior**
When a client requests a simple asset, like a `*.css` file, it should be served by the server.

**Current behavior**

```sh
error: Uncaught TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (file:///<PROJECT_ROOT>/node_modules/.deno/etag@1.8.1/node_modules/etag/index.js:83:11)
    at SendStream.setHeader (file:///<PROJECT_ROOT>/node_modules/.deno/send@0.18.0/node_modules/send/index.js:880:15)
    at SendStream.send (file:///<PROJECT_ROOT>/node_modules/.deno/send@0.18.0/node_modules/send/index.js:620:8)
    at onstat (file:///<PROJECT_ROOT>/node_modules/.deno/send@0.18.0/node_modules/send/index.js:725:10)
    at Deno.stat.then.denoErrorToNodeError.syscall (ext:deno_node/_fs/_fs_stat.ts:85:34)
    at eventLoopTick (ext:core/01_core.js:183:11)
```

**Environment**

- OS: Microsoft Windows 11 Pro 10.0.22621 Build 22621
- deno 1.35.2 (release, x86_64-pc-windows-msvc)
- v8 11.6.189.7
- typescript 5.1.6
- std version: 0.195.0

**Comment by littledivy** [comment]
Fixed by https://github.com/denoland/deno/pull/22294

This works:
```typescript
import serveStatic from "npm:serve-static"
import express from "npm:express@~4.18.2";
import cookieParser from "npm:cookie-parser@~1.4.6";

const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

app.use('/static', serveStatic(Deno.cwd()));
app.listen(8080);
```
