### ISSUE TITLE
Deployment failed via GitHub JumpBox

### ISSUE THREAD

**Issue by eikmei** [denoland/deno#20019]
- Get these errors during deployment after upgraded Deno and Nessie versions

> <details>
> <summary>Error list</summary>
> 
> ```
> err: Check https://deno.land/x/nessie@2.0.10/cli.ts
> err: error: TS2339 [ERROR]: Property 'setRaw' does not exist on type 'Reader & ReaderSync & Closer & { readonly rid: number; }'.
> err:   Deno.stdin.setRaw(true);
> err:              ~~~~~~
> err:     at https://deno.land/x/cliffy@v0.25.2/ansi/cursor_position.ts:31:14
> err: TS2339 [ERROR]: Property 'setRaw' does not exist on type 'Reader & ReaderSync & Closer & { readonly rid: number; }'.
> err:   Deno.stdin.setRaw(false);
> err:              ~~~~~~
> err:     at https://deno.land/x/cliffy@v0.25.2/ansi/cursor_position.ts:34:14
> err: TS2339 [ERROR]: Property 'setRaw' does not exist on type 'Reader & ReaderSync & Closer & { readonly rid: number; }'.
> err:       (Deno.stdin.setRaw as setRaw)(
> err:                   ~~~~~~
> err:     at https://deno.land/x/cliffy@v0.25.2/prompt/_generic_prompt.ts:299:19
> err: TS2339 [ERROR]: Property 'setRaw' does not exist on type 'Reader & ReaderSync & Closer & { readonly rid: number; }'.
> err:       Deno.stdin.setRaw(false);
> err:                  ~~~~~~
> err:     at https://deno.land/x/cliffy@v0.25.2/prompt/_generic_prompt.ts:307:18
> err: TS2344 [ERROR]: Type '[]' does not satisfy the constraint 'void | Record<string, unknown>'.
> err:   Type '[]' is not assignable to type 'Record<string, unknown>'.
> err:     Index signature for type 'string' is missing in type '[]'.
> err:   CliffyCommand<void, [], O, void, undefined>
> err:                       ~~
> err:     at https://deno.land/x/nessie@2.0.10/cli/commands.ts:39:23
> err: TS2344 [ERROR]: Type '[]' does not satisfy the constraint 'void | Record<string, unknown>'.
> err:   Type '[]' is not assignable to type 'Record<string, unknown>'.
> err:   await new CliffyCommand<void, [], CommandOptions>()
> err:                                 ~~
> err:     at https://deno.land/x/nessie@2.0.10/cli.ts:29:33
> err: TS2345 [ERROR]: Argument of type 'TCliffyAction<any[], CommandOptionsInit>' is not assignable to parameter of type 'IAction<{ mode?: string | undefined; } & { dialect?: string | undefined; }, [], void, void | ({ debug?: true | undefined; } & { config: string | StringType; } & { seedTemplate?: StringType | undefined; } & { ...; }) | (Record<...> & ... 3 more ... & { ...; }), void, void, [] | ([] & Record<...>), Command<...> | Comm...'.
> err:   The 'this' types of each signature are incompatible.
> err:     Type 'Command<void | ({ debug?: true | undefined; } & { config: string | StringType; } & { seedTemplate?: StringType | undefined; } & { migrationTemplate?: StringType | undefined; }) | (Record<...> & ... 3 more ... & { ...; }), ... 6 more ..., Command<...> | Command<...>>' is not assignable to type 'Command<CommandOptionsInit, void, void, any[], void, Command<void, [], CommandOptionsInit, void, undefined, { number: number; integer: number; string: string; boolean: boolean; file: string; }, void, undefined>, void, undefined>'.
> err:       Types of property '_parent' are incompatible.
> err:         Type 'Command<any, any, any, any, any, any, any, any> | Command<void, [], CommandOptions, unknown[], ({ debug?: true | undefined; } & { config: string | StringType; } & { ...; } & { ...; }) | (Record<...> & ... 3 more ... & { ...; }), void | Record<...>, void | Record<...>, Command<...> | undefined> | undefined' is not assignable to type 'undefined'.
> err:           Type 'Command<any, any, any, any, any, any, any, any>' is not assignable to type 'undefined'.
> err:     .action(initNessie)
> err:             ~~~~~~~~~~
> err:     at https://deno.land/x/nessie@2.0.10/cli.ts:78:13
> err: TS2345 [ERROR]: Argument of type 'TCliffyAction<any[], CommandOptionsMakeMigration>' is not assignable to parameter of type 'IAction<void, [StringType], void, { debug?: true | undefined; } & { config: string | StringType; } & { seedTemplate?: StringType | undefined; } & { ...; }, void, void, [] | ([] & Record<...>), Command<...> | Command<...>> & IAction<...>'.
> err:   Type 'TCliffyAction<any[], CommandOptionsMakeMigration>' is not assignable to type 'IAction<void, [StringType], void, { debug?: true | undefined; } & { config: string | StringType; } & { seedTemplate?: StringType | undefined; } & { ...; }, void, void, [] | ([] & Record<...>), Command<...> | Command<...>>'.
> err:     The 'this' types of each signature are incompatible.
> err:       Type 'Command<{ debug?: true | undefined; } & { config: string | StringType; } & { seedTemplate?: StringType | undefined; } & { migrationTemplate?: StringType | undefined; }, ... 6 more ..., Command<...> | Command<...>>' is not assignable to type 'Command<CommandOptionsMakeMigration, void, void, any[], void, Command<void, [], CommandOptionsMakeMigration, void, undefined, { ...; }, void, undefined>, void, undefined>'.
> err:         Types of property '_parent' are incompatible.
> err:           Type 'Command<any, any, any, any, any, any, any, any> | Command<void, [], CommandOptions, unknown[], ({ debug?: true | undefined; } & { config: string | StringType; } & { ...; } & { ...; }) | (Record<...> & ... 3 more ... & { ...; }), void | Record<...>, void | Record<...>, Command<...> | undefined> | undefined' is not assignable to type 'undefined'.
> err:             Type 'Command<any, any, any, any, any, any, any, any>' is not assignable to type 'undefined'.
> err:     .action(makeMigration)
> err:             ~~~~~~~~~~~~~
> err:     at https://deno.land/x/nessie@2.0.10/cli.ts:84:13
> err: TS2349 [ERROR]: This expression is not callable.
> err:   Each member of the union type '{ <C extends Command<void | (G & Record<string, unknown>) | undefined, void | T | undefined, void | Record<string, unknown>, unknown[], void | Record<string, unknown>, void | Record<...>, void | Record<...>, Command<...>>, G extends { ...; } & ... 2 more ... & { ...; }, T extends [] | ([] & Record<...>)>(name: strin...' has signatures, but none of those signatures are compatible with each other.
> err:     .command(
> err:      ~~~~~~~
> err:     at https://deno.land/x/nessie@2.0.10/cli.ts:85:6
> err: Found 9 errors.
> ```
> </details>

- Did not get these errors on local run

<br />

Version info used in the project
|  | Previous | Current | Remarks | 
| ----- | ------ | ------ | ------ |
| Deno | 1.18.0 | 1.34.1 | |
| Nessie | 2.0.5 | 2.0.10 |  |
| mySQL | 2.10.2 | 2.10.3 | https://deno.land/x/mysql@v2.10.3/mod.ts |
| Postgres | | 0.15.0 | https://deno.land/x/postgres@v0.15.0/mod.ts | 
| std | | 0.74.0 | https://deno.land/std@0.74.0/fs/mod.ts |
| dotenv | | 3.1.0 | https://deno.land/x/dotenv@v3.1.0/mod.ts |
| s3 | | 0.5.0 | https://deno.land/x/s3@0.5.0/mod.ts|

**Comment by lucacasonato** [comment]
Those errors look like they are from an old version of Deno.

**Comment by eikmei** [comment]
Any idea why we get the error from old version after upgraded? 
Do you have suggestions to solve this?

**Comment by dsherret** [comment]
The old version of Deno doesn't have new apis like `setRaw`, which the updated dependency uses.

**Comment by eikmei** [comment]
From the errors, seems like the error from `https://deno.land/x/nessie@2.0.10` and `https://deno.land/x/cliffy@v0.25.2`.
Does that mean need to change the version for the modules? But my repo do not use `cliffy` modules.

**Comment by bartlomieju** [comment]
This isn't a Deno bug - as noted in the thread, the errors come from the deployment environment running an outdated Deno version.

The `TS2339: Property 'setRaw' does not exist` errors happen because the upgraded dependencies (nessie 2.0.10 / cliffy 0.25.2) use `Deno.stdin.setRaw`, but the deploy box ("JumpBox") was running an older Deno that predates that API. `setRaw` exists in current Deno (typed in lib.deno.ns.d.ts and present at runtime), so upgrading Deno in the deployment environment resolves those errors.

The remaining `TS2344`/`TS2345` `_parent`/`CliffyCommand` errors are an upstream cliffy type-compatibility issue (sensitive to TypeScript/cliffy versions), not a Deno bug - aligning the cliffy/nessie versions fixes those.

Since there's nothing to fix in Deno here, closing. If you hit a reproducible issue on a current Deno version, please open a fresh issue.
