### ISSUE TITLE
`dev.ts` breaks node compat for mongodb

### ISSUE THREAD

**Issue by Kyiro** [denoland/deno#20027]
Using a newly generated Fresh project, adding the code snippet below to `main.ts` and running the project via `dev.ts` breaks mongodb for whatever reason. Starting with `main.ts` works perfectly fine.
```ts
import { MongoClient } from "npm:mongodb";

const mongoClient = new MongoClient("mongodb://localhost:27017");

await mongoClient.connect();
```
```ts
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'stderr')
    at resolveLogPath (file:///C:/Users/Kyiro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/5.6.0/lib/mongo_logger.js:110:38)
    at Function.resolveOptions (file:///C:/Users/Kyiro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/5.6.0/lib/mongo_logger.js:343:29)
    at parseOptions (file:///C:/Users/Kyiro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/5.6.0/lib/connection_string.js:397:66)      
    at new MongoClient (file:///C:/Users/Kyiro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/5.6.0/lib/mongo_client.js:48:63)```

**Comment by marvinhagemeister** [comment]
FYI: Transferring this issue to the `deno` repository because it's not an issue in Fresh.
