### ISSUE TITLE
Uncaught PermissionDenied: Permission denied (os error 13) this.proc = Deno.run({

### ISSUE THREAD

**Issue by Mxa30** [denoland/deno#20053]
I'm using Deno with Puppeteer to scrape some webpages. However when I use `puppeteer.launch()`, I get the error below. If I use `puppeteer.connect()` it works fine. I assume that is because it's not trying to start a chrome instance on my computer. I've been looking around on how to fix this but I can't seem to find any solution. The only reference to this issue I can find is [this one](https://github.com/denoland/deno/issues/5816#issuecomment-1137142724) but I don't see a concrete solution here either.

I'm wondering if someone could help me out to set up my environment correctly to use puppeteer without a third party browser instance.

```
error: Uncaught PermissionDenied: Permission denied (os error 13)
    this.proc = Deno.run({
                     ^
    at opRun (ext:runtime/40_process.js:46:14)
    at Object.run (ext:runtime/40_process.js:132:15)
    at BrowserRunner.start (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:64:22)
    at ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:108:12)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async main (file:///Users/***/src/index.ts:12:21)
```

Further info:
- Puppeteer import: `import puppeteer from "https://deno.land/x/puppeteer@16.2.0/mod.ts";`
- MacBook Air M1 2020
- Multiple versions of Chrome for testing installed under `/Users/***/.cache/puppeteer/chrome`

**Comment by bartlomieju** [comment]
CC @marvinhagemeister

**Comment by marvinhagemeister** [comment]
@Mxa30 can you share the full snippet that you used to launch puppeteer?

**Comment by Mxa30** [comment]
@marvinhagemeister below snippet is enough to reproduce the issue on my machine

```ts
import puppeteer from "https://deno.land/x/puppeteer@16.2.0/mod.ts";

async function main() {
      const browser = await puppeteer.launch();
}

main();
```

**Comment by sigmaSd** [comment]
You can strace the program to see which binary you're not allowed to run, 

As mentioned on the other issue your user account probably doesn't have execute privilege on the browser binaries, strace will validate this assumption

**Comment by sigmaSd** [comment]
Maybe you can try using dtruss https://opensource.apple.com/source/dtrace/dtrace-147/DTTk/dtruss.auto.html

**Comment by Mxa30** [comment]
I did try that but it gave me permission errors. Doesn't seem like you can use dtruss to trace executables that are in your system files. I'll try to get it to work though.

**Comment by Mxa30** [comment]
Update: using the code below form [this post](https://stackoverflow.com/a/74122849) it does seem to work just fine. Will look into this more.

```ts
const browser = await puppeteer.launch({
        executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    });
```

**Comment by lino-levan** [comment]
If you're just looking for a puppeteer-like API that works well with Deno, you could always use https://deno.land/x/astral. It shares a very similar API to puppeteer, so in a lot of cases it's a drop-in replacement. Still probably a bug that /x/puppeteer doesn't work though.

**Comment by Mxa30** [comment]
I think I found the path that is causing the error. When I use the following code I get the same `PermissionDenied` error

```ts
const browser = await puppeteer.launch({
        executablePath: "/Users/max/.cache/puppeteer/chrome/mac_arm-116.0.5845.96/chrome-mac-arm64/Google Chrome for Testing.app"
    });
```

Full error (I did replace path names with *):
```
PermissionDenied: Permission denied (os error 13)
    at opRun (ext:runtime/40_process.js:46:14)
    at Object.run (ext:runtime/40_process.js:132:15)
    at BrowserRunner.start (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:64:22)
    at ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:108:12)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async *.* (file:///Users/max/Documents/*/*/*/*/*/*.ts:6:25)
    at async *.* (file:///Users/max/Documents/*/*/*/*/*.ts:11:25)
    at async Promise.all (index 3)
    at async main (file:///Users/max/Documents/*/*/*/index.ts:26:33) {
  name: "PermissionDenied",
  code: "EACCES"
```

Image below shows permissions on the executable file:  
<img width="376" alt="Screenshot 2023-08-22 at 21 38 40" src="https://github.com/denoland/deno/assets/26234065/66eab6af-0d82-4506-853c-20ad6942df04">

**Comment by Mxa30** [comment]
I also noticed that when running `$deno upgrade`, I get the following error: `error: You do not have write permission to /opt/homebrew/bin/deno`

Maybe that has to do with it. How would I go about resolving this?

**Comment by bartlomieju** [comment]
This is a usage issue rather than a Deno bug. `os error 13` (EACCES) here is the OS refusing to execute a directory: the `executablePath` was pointing at the `.app` bundle directory (`…/Google Chrome for Testing.app`) instead of the actual binary inside it (`…/Contents/MacOS/…`). As you found, pointing at the real binary (e.g. `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`) works. Deno is correctly surfacing the EACCES that `exec()` returns for a directory.

A couple of notes for anyone landing here:
- `deno-puppeteer@16.2.0` is quite old. For browser automation on current Deno, `@astral/astral` (Deno-native) is the recommended option, and `npm:puppeteer` also works on Deno 2.
- If you do use puppeteer, make sure `executablePath` resolves to the Chrome binary, not the `.app` bundle.

Closing as answered. Happy to reopen if there is an actual Deno-side bug to track here.
