### ISSUE TITLE
invalid peer certificate: NotValidForName on fetch() for unsecure http addresses

### ISSUE THREAD

**Issue by starrematte** [denoland/deno#20074]
Hi all,
I'm having an issue when calling an external http address that does not have a security certificate installed on (if installed it works perfectly).

I noticed that Deno (or the Rust layer) automatically assumes that it will be an https request and switch to "https". Additionally it puts also an "#undefined" after the URL.

```
Uncaught TypeError: error sending request for url (https://exampleservice.withno.certificate#undefined): error trying to connect: invalid peer certificate: NotValidForName
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
```
I looked in the Rust [documentation](https://docs.rs/rustls/latest/src/rustls/error.rs.html#:~:text=///%20The%20subject%20names%20in%20an%20end%2Dentity%20certificate%20do%20not%20include%0A%20%20%20%20///%20the%20expected%20name.%0A%20%20%20%20NotValidForName%2C) for this kind of error and says the follow: 
```
/// The subject names in an end-entity certificate do not include
/// the expected name.
NotValidForName
```
My deno specs:
```
deno 1.35.3 (release, x86_64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6
```

Thank you in advance!

**Comment by mmastrac** [comment]
It might be that your site is redirecting to a secure site. When it does, we require a valid certificate for fetch to work.

What do you get if you run this command against the site with no certificate?

```
curl -D- http://exampleservice.withno.certificate
```

**Comment by sant123** [comment]
I'm facing the same issue, the error I get is this with the curl command above:

```text
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by sant123** [comment]
I'm using Fedora 39 and this solved my issue https://docs.fedoraproject.org/en-US/quick-docs/using-shared-system-certificates/#_adding_new_certificates

**Comment by bartlomieju** [comment]
Closing as resolved. There were really two things in this report:

**1. The certificate failure is expected behavior.** As @mmastrac noted, the `http` site redirects to `https`, and Deno (like any compliant client) then requires a valid certificate for the https target. `NotValidForName` / `unable to get local issuer certificate` are cert/trust problems on the server or local-trust-store side, not Deno bugs — which is consistent with @sant123 fixing it by adding certificates to the system trust store. If a self-signed or custom CA is genuinely needed, `--cert` / `DENO_CERT` (or `--unsafely-ignore-certificate-errors` for local testing) are the supported escape hatches.

**2. The `#undefined` artifact in the error URL is fixed.** The original message appended a stray `#undefined` to the URL. That no longer happens. On current canary (deno 2.8.1+d95ceb5 (canary, release, aarch64-apple-darwin)) the message is clean and more informative:

```
error sending request for url (https://wrong.host.badssl.com/): client error (Connect): invalid peer certificate: certificate not valid for name "wrong.host.badssl.com"; certificate is only valid for DnsName("*.badssl.com") or DnsName("badssl.com")
```

Since the cert behavior is working as intended and the one real defect (the malformed URL) is gone, I'm closing this. Thanks all.

**Comment by bartlomieju** [comment]
Checked on current Deno (2.8.1) and this is not an actionable bug:

- **http -> https** is the server redirecting to its secure URL (as mmastrac noted); Deno follows the redirect, it does not fabricate `https`.
- The **`#undefined`** appended to the error URL no longer appears. TLS errors now report a clean URL, e.g. `error sending request for url (https://wrong.host.badssl.com/): ... invalid peer certificate: certificate not valid for name "wrong.host.badssl.com"`.
- **`NotValidForName`** is correct behavior: the certificate does not match the hostname, and Deno requires valid certificates. The messages are also much more descriptive now.
- The `unable to get local issuer certificate` case is a missing CA in the system trust store (system configuration), which @sant123 resolved by adding the cert to the system store.

For the legitimate cases: a missing/custom CA can be supplied via `DENO_CERT` / `--cert`, and if you really need to bypass verification you can use `--unsafely-ignore-certificate-errors`.

Closing as resolved/not a bug. Happy to reopen if there is a concrete Deno-side defect to track.
