### ISSUE TITLE
Prisma CLI: `error: Uncaught ReferenceError: module is not defined`

### ISSUE THREAD

**Issue by janpio** [denoland/deno#20099]
When executing Prisma CLI set up commands in a certain order, you can end up with this error message:
```
error: Uncaught ReferenceError: module is not defined
module.exports = __toCommonJS(generator_exports);
^
    at file:///C:/Users/Jan/Documents/throwaway/20572/broken/fresh-project/node_modules/@prisma/client/generator-build/index.js:15188:1
```

It only happens when in the same run some Npm packages are installed via `npm install`. These are the commands:

```
deno upgrade
deno run -A -r https://fresh.deno.dev/
deno run -A npm:prisma init
// modify the schema.prisma file
deno run -A npm:prisma generate
```

In the "modify schema file" step, you just paste the following into your `prisma/schema.prisma` file:
```
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```
Without this the `generate` step will fail with an error message.

This has originally been reported by a Prisma user, but I can reproduce: https://github.com/prisma/prisma/issues/20572

**Comment by bartlomieju** [comment]
I've been trying to repeat this problem on Deno v1.36.3 and I'm unable to ever hit this error :/ However running `deno run -A npm:prisma generate` prints:
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Warning: [Prisma auto-install on generate] Prisma could not find a package.json file in the inferred project root /Users/ib/dev/try_prisma2/fresh-project. During the next step, when an auto-install of Prisma package(s) will be attempted, it will then be created by your package manager on the appropriate level if necessary.

added 2 packages in 2s

added 2 packages, and audited 5 packages in 4s

found 0 vulnerabilities

✔ Installed the @prisma/client and prisma packages in your project
```
And never finishes the project.

**Comment by janpio** [comment]
I can still reproduce the above in 1.36.1 (the version I currently had installed). 
Currently uses `prisma@5.1.1` because that seems to be in cache.

After `deno upgrade` to 1.36.3, I still get the same problem:
```
C:\Users\Jan\Documents\throwaway\deno20099\1.36.3>deno run -A npm:prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Warning: [Prisma auto-install on generate] Prisma could not find a package.json file in the inferred project root C:\Users\Jan\Documents\throwaway\deno20099\1.36.3. During the next step, when an auto-install of Prisma package(s) will be attempted, it will then be created by your package manager on the appropriate level if necessary.

added 2 packages in 4s

added 2 packages, and audited 5 packages in 1s

found 0 vulnerabilities

✔ Installed the @prisma/client and prisma packages in your project
Error: Generator "C:\\Users\\Jan\\Documents\\throwaway\\deno20099\\1.36.3\\node_modules\\@prisma\\client\\generator-build\\index.js" failed:

error: Uncaught ReferenceError: module is not defined
module.exports = __toCommonJS(generator_exports);
^
    at file:///C:/Users/Jan/Documents/throwaway/deno20099/1.36.3/node_modules/@prisma/client/generator-build/index.js:15188:1


C:\Users\Jan\Documents\throwaway\deno20099\1.36.3>deno run -A npm:prisma -v
Environment variables loaded from .env
Error: Command failed: C:\Users\Jan\Documents\throwaway\deno20099\1.36.3\node_modules\.deno\@prisma+engines@5.1.1\node_modules\@prisma\engines\schema-engine-windows.exe --version
[... unrelated output caused by https://github.com/denoland/deno/issues/19544]
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules\.deno\@prisma+engines@5.1.1\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : E_CANNOT_RESOLVE_VERSION (at node_modules\.deno\@prisma+engines@5.1.1\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.1.1-1.6a3747c37ff169c90047725a05a6ef02e32ac97e
Default Engines Hash    : 6a3747c37ff169c90047725a05a6ef02e32ac97e
Studio                  : 0.492.0
Warning: Not implemented: ChildProcess.prototype.disconnect

C:\Users\Jan\Documents\throwaway\deno20099\1.36.3>deno --version
deno 1.36.3 (release, x86_64-pc-windows-msvc)
v8 11.6.189.12
typescript 5.1.6
```

**Comment by bartlomieju** [comment]
I'll try to reproduce on a Windows machine 👍

**Comment by bartlomieju** [comment]
Thanks @janpio, I'll get to the bottom of it 👍

**Comment by janpio** [comment]
Update:
Sometimes in the last 16 minutes it did finish:
```
found 0 vulnerabilities

✔ Installed the @prisma/client and prisma packages in your project
Error: Generator "/mnt/c/Users/Jan/Documents/throwaway/deno20099/wsl/node_modules/@prisma/client/generator-build/index.js" failed:

Download https://registry.npmjs.org/@codspeed/benchmark.js-plugin
Download https://registry.npmjs.org/@faker-js/faker
Download https://registry.npmjs.org/@fast-check/jest
Download https://registry.npmjs.org/@jest/create-cache-key-function
Download https://registry.npmjs.org/@jest/globals
...
Download https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.1.tgz
Download https://registry.npmjs.org/emoji-regex/-/emoji-regex-9.2.2.tgz
Download https://registry.npmjs.org/eastasianwidth/-/eastasianwidth-0.2.0.tgz
Download https://registry.npmjs.org/p-try/-/p-try-1.0.0.tgz
Download https://registry.npmjs.org/@tootallnate/once/-/once-1.1.2.tgz
Download https://registry.npmjs.org/unique-slug/-/unique-slug-3.0.0.tgz
Download https://registry.npmjs.org/@smithy/is-array-buffer/-/is-array-buffer-2.0.0.tgz
Download https://registry.npmjs.org/@smithy/util-hex-encoding/-/util-hex-encoding-2.0.0.tgz
Download https://registry.npmjs.org/@smithy/eventstream-codec/-/eventstream-codec-2.0.5.tgz
Download https://registry.npmjs.org/@smithy/util-uri-escape/-/util-uri-escape-2.0.0.tgz
error: Uncaught ReferenceError: module is not defined
module.exports = __toCommonJS(generator_exports);
^
    at file:///mnt/c/Users/Jan/Documents/throwaway/deno20099/wsl/node_modules/@prisma/client/generator-build/index.js:15360:1
```

**Comment by SYip** [comment]
Same issue with a Mac machine.

```
deno --version
deno 1.36.3 (release, aarch64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6
```

Error for me:
```
The database is already in sync with the Prisma schema.

Running generate... (Use --skip-generate to skip the generators)
Error: Generator "{HOME_PATH}/node_modules/@prisma/client/generator-build/index.js" failed:

error: Module not found "file:///{PROJECT_PATH}/{HOME_PATH}/node_modules/@prisma/client/generator-build/index.js".
```

Looks like it is trying to access the `generator-build/index.js` in a wrong directory.

**Comment by janpio** [comment]
Can you check if `file:///{PROJECT_PATH}/{HOME_PATH}/node_modules/@prisma/client/generator-build/index.js` exists in your setup @SYip? It should.

**Comment by SYip** [comment]
> Can you check if `file:///{PROJECT_PATH}/{HOME_PATH}/node_modules/@prisma/client/generator-build/index.js` exists in your setup @SYip? It should.

No, the file does not exist under {PROJECT_PATH}, but the file exist in file:///{{HOME_PATH}/node_modules/@prisma/client/generator-build/index.js

**Comment by varun050303** [comment]
error: Uncaught (in promise) ReferenceError: module is not defined

**Comment by bartlomieju** [comment]
This was fixed by the CommonJS detection rework in Deno 2.

The error came from Prisma's generator (`node_modules/@prisma/client/generator-build/index.js`), a CommonJS file (`module.exports = ...`) being executed as ESM, where `module` is undefined. Deno 2 now auto-detects CommonJS for `.js` files inside node_modules packages, so such files load as CJS correctly.

Verified on a current build: a CommonJS package in `node_modules` with no `"type"` field imported from ESM loads and exports correctly, rather than throwing `ReferenceError: module is not defined`. Standalone `.js` files using `module.exports` also no longer crash cryptically; they produce a clear, actionable error with a `--unstable-detect-cjs` hint and docs link.

The exact original command sequence can't be replayed because Prisma itself has changed since 2023 (newer versions use `prisma.config.ts`), but the specific CJS-loaded-as-ESM failure this issue reports no longer occurs. Closing as resolved.
