### ISSUE TITLE
node compat: support npm scripts lifecycle  

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#20137]
https://docs.npmjs.com/cli/v9/using-npm/scripts#life-cycle-operation-order

tree-sitter uses `install.js` for example, to reproduce the issue
```
mkdir a && cd a && npm init
npm install --save-dev tree-sitter-cli
# modify package.json to include "scripts": {"ts":"tree-sitter"}
```

`npm ts -h` works
`deno task ts -h` errors:
```
Warning Currently only basic package.json `scripts` are supported. Programs like `rimraf` or `cross-env` will not work correctly. This will be fixed in an upcoming release.
Task ts tree-sitter "-h"
error: Uncaught NotFound: Failed to spawn: /home/mrcool/dev/deno/lab/tmp/JbS/a/node_modules/.deno/tree-sitter-cli@0.20.8/node_modules/tree-sitter-cli/tree-sitter: No such file or directory (os error 2)
    at spawnChildInner (ext:runtime/40_process.js:162:17)
    at spawnChild (ext:runtime/40_process.js:182:10)
    at Command.spawn (ext:runtime/40_process.js:440:12)
    at new ChildProcess (ext:deno_node/internal/child_process.ts:110:16)
    at spawn (node:child_process:104:12)
    at Object.<anonymous> (file:///home/mrcool/dev/deno/lab/tmp/JbS/a/node_modules/.deno/tree-sitter-cli@0.20.8/node_modules/tree-sitter-cli/cli.js:7:1)
    at Object.<anonymous> (file:///home/mrcool/dev/deno/lab/tmp/JbS/a/node_modules/.deno/tree-sitter-cli@0.20.8/node_modules/tree-sitter-cli/cli.js:13:4)
    at Module._compile (node:module:731:36)
    at Object.Module._extensions..js (node:module:745:12)
    at Module.load (node:module:656:34)
```

The problem is the [tree-sitter package ](https://github.com/tree-sitter/tree-sitter/blob/master/cli/npm/package.json) have an `install.js`  that needs to be called automatically to download ts binary

**Comment by lucacasonato** [comment]
Duplicate of https://github.com/denoland/deno/issues/16164
