### ISSUE TITLE
Error: Not implemented: udp.UDP.prototype.unref

### ISSUE THREAD

**Issue by osdevisnot** [denoland/deno#20138]
I am attempting to setup a deno service to report metrics using Datadog's DogStatsD server based on [hot-shots](https://www.npmjs.com/package/hot-shots)

The code extract looks like this:
```js
import { default as StatsD } from "npm:hot-shots@10.0.0";
const client = new StatsD({ port: 8020, globalTags: { env: ENV } });
```

However, this results in an exception:
```
Error: Not implemented: udp.UDP.prototype.unref
    at notImplemented (ext:deno_node/_utils.ts:9:11)
    at UDP.unref (ext:deno_node/internal_binding/udp_wrap.ts:205:9)
    at Socket.unref (node:dgram:686:20)
    at createUdpTransport (file:///Users/abhisheksh/Library/Caches/deno/npm/registry.npmjs.org/hot-shots/10.0.0/lib/transport.js:49:10)
    at module.exports (file:///Users/abhisheksh/Library/Caches/deno/npm/registry.npmjs.org/hot-shots/10.0.0/lib/transport.js:160:19)
    at trySetNewSocket (file:///Users/abhisheksh/Library/Caches/deno/npm/registry.npmjs.org/hot-shots/10.0.0/lib/statsd.js:619:19)
    at new Client (file:///Users/abhisheksh/Library/Caches/deno/npm/registry.npmjs.org/hot-shots/10.0.0/lib/statsd.js:118:5)
    at file:///Users/abhisheksh/code/zillow-home-loans/experimental/javascript/services/zhl-todos/src/main.ts:14:16
```

For additional context, the client created above is then passed to a [statsd plugin](https://the-guild.dev/graphql/envelop/plugins/use-statsd) for GraphQL Envelop.

Any insights on possible solutions here?

**Comment by CosminPerRam** [comment]
Hey, any progress/insights on this?
