### ISSUE TITLE
s390x support

### ISSUE THREAD

**Issue by xet7** [denoland/deno#20212]
Hi,
I'm trying to build deno at Ubuntu 23.04 Docker container at s390x https://github.com/wekan/wekan/wiki/s390x

Previous 390x issue at #6212

(unrelated: I did build deno at Linux arm64, it did work for me for my small test of deno with main.js at https://github.com/wekan/wekan-node20 )

At s390x, host OS is RHEL, kernel is this:
```
Linux 23.04 4.18.0-477.21.1.el8_8.s390x #1 SMP Thu Jul 20 08:54:46 EDT 2023 s390x s390x s390x GNU/Linux
```
Because there is no prebuilt binary for rusty_v8 https://github.com/denoland/rusty_v8.git , I'm trying to build it with this:
```
git submodule update --init --recursive
apt install gn pkg-config libglib2.0-dev curl clang
CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true RUST_BACKTRACE=full V8_FROM_SOURCE=1 cargo build -vv
```
I'm getting this build log:

```
warning: /home/ubuntu/repos/rusty_v8/Cargo.toml: file `/home/ubuntu/repos/rusty_v8/build.rs` found to be present in multiple build targets:
  * `integration-test` target `build`
  * `build-script` target `build-script-build`
warning: v8 v0.75.0 (/home/ubuntu/repos/rusty_v8) ignoring invalid dependency `gn` which is missing a lib target
       Fresh unicode-ident v1.0.11
       Fresh proc-macro2 v1.0.66
       Fresh cfg-if v1.0.0
       Fresh quote v1.0.33
       Fresh syn v2.0.29
       Fresh libc v0.2.147
       Fresh autocfg v1.1.0
       Fresh cc v1.0.82
       Fresh once_cell v1.18.0
       Fresh pin-project-lite v0.2.12
       Fresh memchr v2.5.0
       Fresh scopeguard v1.2.0
       Fresh lock_api v0.4.10
       Fresh smallvec v1.11.0
       Fresh bytes v1.4.0
       Fresh futures-core v0.3.28
       Fresh num_cpus v1.16.0
       Fresh log v0.4.20
       Fresh parking_lot_core v0.9.8
       Fresh futures-sink v0.3.28
       Fresh parking_lot v0.12.1
warning: unnecessary parentheses around match arm expression
   --> /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:625:21
    |
625 |         "x86_64" => ("win64"),
    |                     ^       ^
    |
    = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
    |
625 -         "x86_64" => ("win64"),
625 +         "x86_64" => "win64",
    |

warning: unnecessary parentheses around match arm expression
   --> /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:626:18
    |
626 |         "x86" => ("win32"),
    |                  ^       ^
    |
help: remove these parentheses
    |
626 -         "x86" => ("win32"),
626 +         "x86" => "win32",
    |

       Fresh tokio-macros v2.1.0
warning: `ring` (build script) generated 2 warnings
       Fresh serde_derive v1.0.183
       Fresh socket2 v0.5.3
       Fresh mio v0.8.8
       Fresh signal-hook-registry v1.4.1
       Fresh tokio v1.32.0
       Fresh serde v1.0.183
   Compiling ring v0.16.20
   Compiling pkg-config v0.3.27
     Running `/home/ubuntu/repos/rusty_v8/target/debug/build/ring-005636f0991fc9fe/build-script-build`
     Running `CARGO=/home/ubuntu/.rustup/toolchains/1.71.0-s390x-unknown-linux-gnu/bin/cargo CARGO_CRATE_NAME=pkg_config CARGO_MANIFEST_DIR=/home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/pkg-config-0.3.27 CARGO_PKG_AUTHORS='Alex Crichton <alex@alexcrichton.com>' CARGO_PKG_DESCRIPTION='A library to run the pkg-config system tool at build time in order to be used in
Cargo build scripts.
' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='MIT OR Apache-2.0' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=pkg-config CARGO_PKG_README=README.md CARGO_PKG_REPOSITORY='https://github.com/rust-lang/pkg-config-rs' CARGO_PKG_RUST_VERSION=1.30 CARGO_PKG_VERSION=0.3.27 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=3 CARGO_PKG_VERSION_PATCH=27 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/home/ubuntu/repos/rusty_v8/target/debug/deps:/home/ubuntu/.rustup/toolchains/1.71.0-s390x-unknown-linux-gnu/lib:/home/ubuntu/.rustup/toolchains/1.71.0-s390x-unknown-linux-gnu/lib' /home/ubuntu/.rustup/toolchains/1.71.0-s390x-unknown-linux-gnu/bin/rustc --crate-name pkg_config /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/pkg-config-0.3.27/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=148 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=ff58e2f50a8e37fc -C extra-filename=-ff58e2f50a8e37fc --out-dir /home/ubuntu/repos/rusty_v8/target/debug/deps -L dependency=/home/ubuntu/repos/rusty_v8/target/debug/deps --cap-lints warn`
[ring 0.16.20] thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:358:10
[ring 0.16.20] stack backtrace:
[ring 0.16.20]    0:      0x2aa3305884a - std::backtrace_rs::backtrace::libunwind::trace::h25e7fe748e2e67b6
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
[ring 0.16.20]    1:      0x2aa3305884a - std::backtrace_rs::backtrace::trace_unsynchronized::hdfd3647e51eb3c67
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
[ring 0.16.20]    2:      0x2aa3305884a - std::sys_common::backtrace::_print_fmt::h3691bc17b8e37de6
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:65:5
[ring 0.16.20]    3:      0x2aa3305884a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h56a591d7fba44b4c
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:44:22
[ring 0.16.20]    4:      0x2aa3308a4c2 - core::fmt::rt::Argument::fmt::h1aba04ac2e21bd48
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/fmt/rt.rs:138:9
[ring 0.16.20]    5:      0x2aa3308a4c2 - core::fmt::write::hb157e8ca4966859b
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/fmt/mod.rs:1094:21
[ring 0.16.20]    6:      0x2aa330537f0 - std::io::Write::write_fmt::h8ff192f93fb62e4f
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/io/mod.rs:1713:15
[ring 0.16.20]    7:      0x2aa3305b388 - std::sys_common::backtrace::_print::h55aeaa035ac20811
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:47:5
[ring 0.16.20]    8:      0x2aa3305b388 - std::sys_common::backtrace::print::ha45f3ccfae20a3e1
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:34:9
[ring 0.16.20]    9:      0x2aa3305b388 - std::panicking::default_hook::{{closure}}::h8bdcf59834f675d3
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:269:22
[ring 0.16.20]   10:      0x2aa3305afda - std::panicking::default_hook::haf2908d7746d135d
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:288:9
[ring 0.16.20]   11:      0x2aa3305c87e - std::panicking::rust_panic_with_hook::he8e9fd1852a5b967
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:705:13
[ring 0.16.20]   12:      0x2aa3305c6c4 - std::panicking::begin_panic_handler::{{closure}}::h53c992f0695521a5
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:595:13
[ring 0.16.20]   13:      0x2aa33058e60 - std::sys_common::backtrace::__rust_end_short_backtrace::hd4278d171bf3ca2d
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:151:18
[ring 0.16.20]   14:      0x2aa3305c41e - rust_begin_unwind
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
[ring 0.16.20]   15:      0x2aa32f9208c - core::panicking::panic_fmt::h2a4712b1f23ba34d
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
[ring 0.16.20]   16:      0x2aa32f9212c - core::panicking::panic::hf1d94ded276e6d61
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:117:5
[ring 0.16.20]   17:      0x2aa32fa974e - core::option::Option<T>::unwrap::hacdca296b2a04308
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:935:21
[ring 0.16.20]   18:      0x2aa32f97014 - build_script_build::build_c_code::hfbcd14447931ecea
[ring 0.16.20]                                at /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:352:34
[ring 0.16.20]   19:      0x2aa32f96724 - build_script_build::ring_build_rs_main::h58724306326eca3c
[ring 0.16.20]                                at /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:279:5
[ring 0.16.20]   20:      0x2aa32f96130 - build_script_build::main::heb09bccfac30f96c
[ring 0.16.20]                                at /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:240:13
[ring 0.16.20]   21:      0x2aa32f9d312 - core::ops::function::FnOnce::call_once::h8c1b68a709cb7b26
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
[ring 0.16.20]   22:      0x2aa32f9e3b6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5ae0fcdf6dcdc8cd
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:135:18
[ring 0.16.20]   23:      0x2aa32f9f4dc - std::rt::lang_start::{{closure}}::h39ff9a4ed27f411b
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:166:18
[ring 0.16.20]   24:      0x2aa3305b732 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h897c9eb934d4c615
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:284:13
[ring 0.16.20]   25:      0x2aa3305b732 - std::panicking::try::do_call::h035d036e6e279544
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
[ring 0.16.20]   26:      0x2aa33071b50 - __rust_try
[ring 0.16.20]   27:      0x2aa3305b77c - std::panicking::try::he46f5ddb7ad50b57
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
[ring 0.16.20]   28:      0x2aa3305b77c - std::panic::catch_unwind::hc6d8f9ec66d692c3
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
[ring 0.16.20]   29:      0x2aa3305b77c - std::rt::lang_start_internal::{{closure}}::hcdff5b5312031daf
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:148:48
[ring 0.16.20]   30:      0x2aa3305b77c - std::panicking::try::do_call::h4e1d2dfa7cb2f76b
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
[ring 0.16.20]   31:      0x2aa33071b50 - __rust_try
[ring 0.16.20]   32:      0x2aa3304bbaa - std::panicking::try::h978c95ec708510b2
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
[ring 0.16.20]   33:      0x2aa3304bbaa - std::panic::catch_unwind::h60fc3f9d4f67d9f0
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
[ring 0.16.20]   34:      0x2aa3304bbaa - std::rt::lang_start_internal::hd333daf6d73ddfb2
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:148:20
[ring 0.16.20]   35:      0x2aa32f9f4a0 - std::rt::lang_start::h67374d6273eb001f
[ring 0.16.20]                                at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:165:17
[ring 0.16.20]   36:      0x2aa32f9bc2e - main
[ring 0.16.20]   37:      0x3ff840aa188 - <unknown>
[ring 0.16.20]   38:      0x3ff840aa270 - __libc_start_main
[ring 0.16.20]   39:      0x2aa32f92744 - <unknown>
[ring 0.16.20]   40:                0x0 - <unknown>
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/ubuntu/repos/rusty_v8/target/debug/build/ring-005636f0991fc9fe/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:358:10
  stack backtrace:
     0:      0x2aa3305884a - std::backtrace_rs::backtrace::libunwind::trace::h25e7fe748e2e67b6
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:      0x2aa3305884a - std::backtrace_rs::backtrace::trace_unsynchronized::hdfd3647e51eb3c67
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:      0x2aa3305884a - std::sys_common::backtrace::_print_fmt::h3691bc17b8e37de6
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:65:5
     3:      0x2aa3305884a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h56a591d7fba44b4c
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:44:22
     4:      0x2aa3308a4c2 - core::fmt::rt::Argument::fmt::h1aba04ac2e21bd48
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/fmt/rt.rs:138:9
     5:      0x2aa3308a4c2 - core::fmt::write::hb157e8ca4966859b
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/fmt/mod.rs:1094:21
     6:      0x2aa330537f0 - std::io::Write::write_fmt::h8ff192f93fb62e4f
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/io/mod.rs:1713:15
     7:      0x2aa3305b388 - std::sys_common::backtrace::_print::h55aeaa035ac20811
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:47:5
     8:      0x2aa3305b388 - std::sys_common::backtrace::print::ha45f3ccfae20a3e1
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:34:9
     9:      0x2aa3305b388 - std::panicking::default_hook::{{closure}}::h8bdcf59834f675d3
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:269:22
    10:      0x2aa3305afda - std::panicking::default_hook::haf2908d7746d135d
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:288:9
    11:      0x2aa3305c87e - std::panicking::rust_panic_with_hook::he8e9fd1852a5b967
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:705:13
    12:      0x2aa3305c6c4 - std::panicking::begin_panic_handler::{{closure}}::h53c992f0695521a5
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:595:13
    13:      0x2aa33058e60 - std::sys_common::backtrace::__rust_end_short_backtrace::hd4278d171bf3ca2d
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:151:18
    14:      0x2aa3305c41e - rust_begin_unwind
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
    15:      0x2aa32f9208c - core::panicking::panic_fmt::h2a4712b1f23ba34d
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
    16:      0x2aa32f9212c - core::panicking::panic::hf1d94ded276e6d61
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:117:5
    17:      0x2aa32fa974e - core::option::Option<T>::unwrap::hacdca296b2a04308
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:935:21
    18:      0x2aa32f97014 - build_script_build::build_c_code::hfbcd14447931ecea
                                 at /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:352:34
    19:      0x2aa32f96724 - build_script_build::ring_build_rs_main::h58724306326eca3c
                                 at /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:279:5
    20:      0x2aa32f96130 - build_script_build::main::heb09bccfac30f96c
                                 at /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:240:13
    21:      0x2aa32f9d312 - core::ops::function::FnOnce::call_once::h8c1b68a709cb7b26
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
    22:      0x2aa32f9e3b6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5ae0fcdf6dcdc8cd
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:135:18
    23:      0x2aa32f9f4dc - std::rt::lang_start::{{closure}}::h39ff9a4ed27f411b
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:166:18
    24:      0x2aa3305b732 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h897c9eb934d4c615
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:284:13
    25:      0x2aa3305b732 - std::panicking::try::do_call::h035d036e6e279544
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
    26:      0x2aa33071b50 - __rust_try
    27:      0x2aa3305b77c - std::panicking::try::he46f5ddb7ad50b57
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
    28:      0x2aa3305b77c - std::panic::catch_unwind::hc6d8f9ec66d692c3
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
    29:      0x2aa3305b77c - std::rt::lang_start_internal::{{closure}}::hcdff5b5312031daf
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:148:48
    30:      0x2aa3305b77c - std::panicking::try::do_call::h4e1d2dfa7cb2f76b
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
    31:      0x2aa33071b50 - __rust_try
    32:      0x2aa3304bbaa - std::panicking::try::h978c95ec708510b2
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
    33:      0x2aa3304bbaa - std::panic::catch_unwind::h60fc3f9d4f67d9f0
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
    34:      0x2aa3304bbaa - std::rt::lang_start_internal::hd333daf6d73ddfb2
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:148:20
    35:      0x2aa32f9f4a0 - std::rt::lang_start::h67374d6273eb001f
                                 at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:165:17
    36:      0x2aa32f9bc2e - main
    37:      0x3ff840aa188 - <unknown>
    38:      0x3ff840aa270 - __libc_start_main
    39:      0x2aa32f92744 - <unknown>
    40:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
```
So there error is this:
```
[ring 0.16.20]   39:      0x2aa2dc92744 - <unknown>
[ring 0.16.20]   40:                0x0 - <unknown>
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/ubuntu/repos/rusty_v8/target/debug/build/ring-005636f0991fc9fe/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:358:10
  stack backtrace:
     0:      0x2aa2dd5884a - std::backtr
```
In that file `/home/ubuntu/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:358:10` is this code, where unwrap causes value None, that should be somehow handled differently?
```
    let (_, _, perlasm_format) = ASM_TARGETS
        .iter()
        .find(|entry| {
            let &(entry_arch, entry_os, _) = *entry;
            entry_arch == target.arch && is_none_or_equals(entry_os, &target.os)
        });
        .unwrap();
```
Or is this about s390x CPU-specific assembler code?

**Comment by xet7** [comment]
Also, there is no ninja_gn binaries for s390x https://github.com/denoland/ninja_gn_binaries

**Comment by lucacasonato** [comment]
It seems from the error messages like `ring` (a crypto dependency) does not support s390x.

I'll close this issue, because it's not actionable for us, but we're happy to land minimally invasive patches if this helps running on s390x. We'll just not be undertaking this work proactively at this time.
