### ISSUE TITLE
Confusing error message: '"deno:///missing_dependency.d.ts"' has no exported member 'X'

### ISSUE THREAD

**Issue by patreeceeo** [denoland/deno#20231]
I'm working on creating a minimum reproducing example, but I do know this happens:

1. On every version of Deno that I've tried, from 1.26.0 to 1.36.1
1. When triple slash directives are involved
1. Only with `deno check` and not via the language server
1. Even when the exported member it's referring to via file/line number _is_ in fact exported from the module it's being imported from

Lately I've had to commit code with `--no-verify` because it's been so prevalent 😬

**Comment by sigmaSd** [comment]
Can you explain more I don't follow your example
the error is 
```
error: Uncaught SyntaxError: The requested module 'bitecs' does not provide an export named 'TYPES_ENUM'
import {TYPES_ENUM as Types} from 'bitecs';
```
which is correct because bitecs have this `var TYPES_ENUM = {`, which indeed doesn't export the type, prefixing it with `export` fixes the issue

**Comment by patreeceeo** [comment]
Apologies, I got the steps to reproduce wrong. Step 2 should be `deno check src/test.ts`. With that, I get:

```
error: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'TYPES_ENUM'.
```

**Comment by patreeceeo** [comment]
I'll update the original post

**Comment by patreeceeo** [comment]
Er, wait, I had it right before. Were you using `deno run` or `deno check`? because I get the same (better) error you were getting with `deno run`.

**Comment by lucacasonato** [comment]
@dsherret any ideas?

**Comment by bartlomieju** [comment]
This is resolved on current canary (deno 2.8.1+d95ceb5 (canary, release, aarch64-apple-darwin)). Running the linked repro (`deno check src/test.ts`) now produces a clear, correctly-located diagnostic instead of the confusing synthetic-module error.

**Before:**
```
TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'TYPES_ENUM'.
```

**Now:**
```
TS2307 [ERROR]: Cannot find module 'file:///.../public/index.d.ts'.
    at file:///.../public/index.mjs:2:22
error: Type checking failed.
```

The diagnostic now names the actual missing file referenced by the triple-slash directive (`public/index.d.ts`) and points at the real source location (`index.mjs:2:22`), rather than framing a missing file as a missing export on a synthetic `missing_dependency.d.ts` module. That's the confusion this issue was about, so I'm closing it as resolved. Thanks for the clear repro, @patreeceeo.
