### ISSUE TITLE
Invalid cross-device link (os error 18) when importing from npm

### ISSUE THREAD

**Issue by chefnaphtha** [denoland/deno#20246]
importing a npm package throws this error:
```
An error occurred during route handling or page rendering. Error: Build failed with 1 error:
scripts/pow/utils.ts:1:23: ERROR: [plugin: deno-loader] Invalid cross-device link (os error 18): link '/home/frosty/.cache/deno/npm/registry.npmjs.org/create-hash/1.2.0/browser.js' -> '/tmp/861f62db/browser.js'
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.18.11/mod.js:1615:15)
    at https://deno.land/x/esbuild@v0.18.11/mod.js:1027:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.18.11/mod.js:1450:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.18.11/mod.js:1025:7)
    at https://deno.land/x/esbuild@v0.18.11/mod.js:1054:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.18.11/mod.js:676:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.18.11/mod.js:731:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.18.11/mod.js:652:7)
    at https://deno.land/x/esbuild@v0.18.11/mod.js:1901:11
    at eventLoopTick (ext:core/01_core.js:183:11) {
  errors: [
    {
      detail: Error: Invalid cross-device link (os error 18): link '/home/frosty/.cache/deno/npm/registry.npmjs.org/create-hash/1.2.0/browser.js' -> '/tmp/861f62db/browser.js'
    at async Object.link (ext:deno_fs/30_fs.js:401:3)
    at async linkRecursive (https://deno.land/x/esbuild_deno_loader@0.8.1/src/loader_native.ts:165:5)
    at async linkRecursive (https://deno.land/x/esbuild_deno_loader@0.8.1/src/loader_native.ts:162:7)
    at async NativeLoader.#nodeModulesDirForPackageInner (https://deno.land/x/esbuild_deno_loader@0.8.1/src/loader_native.ts:126:5)
    at async NativeLoader.nodeModulesDirForPackage (https://deno.land/x/esbuild_deno_loader@0.8.1/src/loader_native.ts:80:17)
    at async onResolve (https://deno.land/x/esbuild_deno_loader@0.8.1/src/plugin_deno_loader.ts:261:28)
    at async requestCallbacks.on-resolve (https://deno.land/x/esbuild@v0.18.11/mod.js:1339:22)
    at async handleRequest (https://deno.land/x/esbuild@v0.18.11/mod.js:702:13) {
        code: "EXDEV"
      },
      id: "",
      location: {
        column: 23,
        file: "scripts/pow/utils.ts",
        length: 17,
        line: 1,
        lineText: "import createHash from 'npm:create-hash'",
        namespace: "",
        suggestion: ""
      },
      notes: [],
      pluginName: "deno-loader",
      text: "Invalid cross-device link (os error 18): link '/home/frosty/.cache/deno/npm/registry.npmjs.org/creat"... 54 more characters
    }
  ],
  warnings: []
}
```
not sure if this has anything to do with npm but i don't think it does
looks like this will be fixed by https://github.com/denoland/deno/pull/19879 but a patch would be nice until it gets merged

any way to set the build directory to anything other than /tmp?

**Comment by StarLederer** [comment]
This is a common issue that usually occurs when using a (Docker) container and binding `~/.cache` or `~/.cache/deno` to the host system. Are you doing that?

**Comment by chefnaphtha** [comment]
> This is a common issue that usually occurs when using a (Docker) container and binding `~/.cache` or `~/.cache/deno` to the host system. Are you doing that?

nope, straight deno running on bare metal from the arch extra repo

**Comment by cavoirom** [comment]
I faced the same issue on Arch Linux, deno-v1.36.4. It ran correctly on macOS.

**Comment by lucacasonato** [comment]
This is an issue with `esbuild_deno_loader`. Please open an issue there. The problem occurs because your `DENO_DIR` is not on your main boot drive.
