### ISSUE TITLE
npm:docker-modem doesn't work (and @testcontainers/* as a result)

### ISSUE THREAD

**Issue by gflarity** [denoland/deno#20255]
The blog post said we should report, so here we go:

I just trying to use testcontainers (@testcontainers/postgresql) with Deno when I got this strange error:

```
error: Error: (HTTP code 400) unexpected - starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24
    at file:///Users/geoff/Library/Caches/deno/npm/registry.npmjs.org/docker-modem/3.0.8/lib/modem.js:343:17
    at getCause (file:///Users/geoff/Library/Caches/deno/npm/registry.npmjs.org/docker-modem/3.0.8/lib/modem.js:373:7)
    at Modem.buildPayload (file:///Users/geoff/Library/Caches/deno/npm/registry.npmjs.org/docker-modem/3.0.8/lib/modem.js:342:5)
    at IncomingMessageForClient.<anonymous> (file:///Users/geoff/Library/Caches/deno/npm/registry.npmjs.org/docker-modem/3.0.8/lib/modem.js:310:16)
```

So it seems there might be some http client compatibility issues, as the docker api is just HTTP last time I checked...

Here's the repro code which was inspired by [this Testcontainer Node quickstart repo](https://github.com/AtomicJar/testcontainers-cloud-nodejs-example) (which runs fine using node): 

```typescript
import { PostgreSqlContainer } from "npm:@testcontainers/postgresql";
import postgres from "https://deno.land/x/postgresjs/mod.js";

Deno.test("hello postgres", async () => {
  const initScript = `
            create table guides
            (
                id    bigserial     not null,
                title varchar(1023) not null,
                url   varchar(1023) not null,
                primary key (id)
            );

            insert into guides(title, url)
            values ('Getting started with Testcontainers',
                    'https://testcontainers.com/getting-started/'),
                   ('Getting started with Testcontainers for Java',
                    'https://testcontainers.com/guides/getting-started-with-testcontainers-for-java/'),
                   ('Getting started with Testcontainers for .NET',
                    'https://testcontainers.com/guides/getting-started-with-testcontainers-for-dotnet/'),
                   ('Getting started with Testcontainers for Node.js',
                    'https://testcontainers.com/guides/getting-started-with-testcontainers-for-nodejs/'),
                   ('Getting started with Testcontainers for Go',
                    'https://testcontainers.com/guides/getting-started-with-testcontainers-for-go/'),
                   ('Testcontainers container lifecycle management using JUnit 5',
                    'https://testcontainers.com/guides/testcontainers-container-lifecycle/')
            ;
        `;

  const container = await new PostgreSqlContainer("postgres:14-alpine",)
    .withCopyContentToContainer([
      { content: initScript, target: "/docker-entrypoint-initdb.d/init.sql" },
    ])
    .start();

  const sql = postgres(container.getConnectionUri());
  const res = await sql`select title, url from guides`;
  console.log(res);
});
```

**Comment by brad-jones** [comment]
I just ran into something similar. When I debugged I saw requests being made to http://localhost instead of /var/run/docker.sock.
Looks very similar to https://github.com/apocas/dockerode/issues/747

**Comment by dionjwa** [comment]
I am also hitting this. Is there any workaround?

**Comment by dionjwa** [comment]
I adapted the workaround proposed by https://github.com/apocas/dockerode/issues/747#issuecomment-1962746418
to use pure `deno` and avoid the `socat` dependency, it works in my own tools:


```typescript
/******************************************************
 * Begin workarounds for this showstopper issue:
 * https://github.com/apocas/dockerode/issues/747
*/
async function startProxy() {
  // Listen on TCP port 3000
  const tcpListener = Deno.listen({ port: 3000 });
  console.log("Listening on TCP port 3000");

  for await (const tcpConn of tcpListener) {
    handleConnection(tcpConn);
  }
}
async function handleConnection(tcpConn: Deno.Conn) {
  try {
    // Connect to the Unix socket at /var/run/docker.sock
    const unixConn = await Deno.connect({ transport: "unix", path: "/var/run/docker.sock" });

    // Bidirectional forwarding
    const tcpToUnix = copy(tcpConn, unixConn);
    const unixToTcp = copy(unixConn, tcpConn);

    // Wait for both copy operations to complete
    await Promise.all([tcpToUnix, unixToTcp]);

  } catch (error) {
    console.error("Error handling connection:", error);
  } finally {
    tcpConn.close();
  }
}
// Utility function to copy data from one stream to another
async function copy(src: Deno.Reader, dst: Deno.Writer) {
  const buffer = new Uint8Array(1024);
  while (true) {
    const bytesRead = await src.read(buffer);
    if (bytesRead === null) break;
    let offset = 0;
    while (offset < bytesRead) {
      const bytesWritten = await dst.write(buffer.subarray(offset, bytesRead));
      offset += bytesWritten;
    }
  }
}
// Start the proxy
startProxy();
// and this now needs to be changed because of the above:
// const docker = new Docker({socketPath: "/var/run/docker.sock"});
const docker = new Docker({protocol: 'http', host: 'localhost', port: 3000});
/******************************************************
 * End workarounds for this showstopper issue:
 * https://github.com/apocas/dockerode/issues/747
*/

```

**Comment by felipecrs** [comment]
This is the only thing keeping me from adopting Deno in one of my projects btw (lack of testcontainers support).

**Comment by Karrq** [comment]
Thanks @dionjwa, was hitting the same issue on Deno 2, but thanks to the workaround I can continue!

**Comment by felipecrs** [comment]
I've tried to combine @dionjwa's solution to work with testcontainers:

```ts
// docker-proxy.ts

import type { Reader, Writer } from "jsr:@std/io@0.225";

export async function startProxy() {
  const tcpListener = Deno.listen({ port: 2375 });

  for await (const tcpConn of tcpListener) {
    handleConnection(tcpConn);
  }
  return tcpListener;
}

async function handleConnection(tcpConn: Deno.Conn) {
  try {
    // Connect to the Unix socket at /var/run/docker.sock
    const unixConn = await Deno.connect({
      transport: "unix",
      path: "/var/run/docker.sock",
    });

    // Bidirectional forwarding
    const tcpToUnix = copy(tcpConn, unixConn);
    const unixToTcp = copy(unixConn, tcpConn);

    // Wait for both copy operations to complete
    await Promise.all([tcpToUnix, unixToTcp]);
  } catch (error) {
    console.error("Error handling connection:", error);
  } finally {
    tcpConn.close();
  }
}

// Utility function to copy data from one stream to another
async function copy(src: Reader, dst: Writer) {
  const buffer = new Uint8Array(1024);
  while (true) {
    const bytesRead = await src.read(buffer);
    if (bytesRead === null) break;
    let offset = 0;
    while (offset < bytesRead) {
      const bytesWritten = await dst.write(buffer.subarray(offset, bytesRead));
      offset += bytesWritten;
    }
  }
}
```


```ts
// main.ts

import { GenericContainer } from "testcontainers";

import { startProxy } from "./docker-proxy.ts";

startProxy();

Deno.env.set("DOCKER_HOST", "tcp://localhost:2375");

const container = new GenericContainer("alpine");
const startedContainer = await container.start();
await startedContainer.stop();
```

Then:

```console
❯ deno run -A main.ts
error: Uncaught (in promise) TypeError: stream.socket.unref is not a function
    at DockerContainerClient.logs (file:///home/felipecrs/.cache/deno/npm/registry.npmjs.org/testcontainers/10.13.2/build/container-runtime/clients/container/docker-container-client.js:165:27)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async LogWaitStrategy.waitUntilReady (file:///home/felipecrs/.cache/deno/npm/registry.npmjs.org/testcontainers/10.13.2/build/wait-strategies/log-wait-strategy.js:22:24)
    at async waitForContainer (file:///home/felipecrs/.cache/deno/npm/registry.npmjs.org/testcontainers/10.13.2/build/wait-strategies/wait-for-container.js:8:9)
    at async GenericContainer.startContainer (file:///home/felipecrs/.cache/deno/npm/registry.npmjs.org/testcontainers/10.13.2/build/generic-container/generic-container.js:143:9)
    at async createNewReaper (file:///home/felipecrs/.cache/deno/npm/registry.npmjs.org/testcontainers/10.13.2/build/reaper/reaper.js:62:30)
    at async file:///home/felipecrs/.cache/deno/npm/registry.npmjs.org/testcontainers/10.13.2/build/reaper/reaper.js:29:20
    at async withFileLock (file:///home/felipecrs/.cache/deno/npm/registry.npmjs.org/testcontainers/10.13.2/build/common/file-lock.js:41:16)
    at async getReaper (file:///home/felipecrs/.cache/deno/npm/registry.npmjs.org/testcontainers/10.13.2/build/reaper/reaper.js:19:14)
    at async GenericContainer.start (file:///home/felipecrs/.cache/deno/npm/registry.npmjs.org/testcontainers/10.13.2/build/generic-container/generic-container.js:75:28)
```

Which refs to a function not yet implemented apparently:

- https://github.com/testcontainers/testcontainers-node/blob/08da47baeaa9a43f29aec3a9bb1ce67a3bc1849f/packages/testcontainers/src/container-runtime/clients/container/docker-container-client.ts#L168

I believe it could be related to this issue:

- https://github.com/denoland/deno/issues/18324

Which is a different compatibility issue.

**Comment by taras** [comment]
I couldn't get @mortezaPRK's code to work, but I got @felipecrs's code running with @mortezaPRK's monkey patch. Here is the final version for reference. 

```ts
import { copy } from "jsr:@std/io@0.225";
import { ClientRequest } from "node:HTTP";

const originalSocket = ClientRequest.prototype.onSocket;
ClientRequest.prototype.onSocket = function (socket) {
  socket.unref = function () {
    return this;
  };
  return originalSocket.call(this, socket);
};

export async function startProxy() {
  const tcpListener = Deno.listen({ port: 2375 });

  for await (const tcpConn of tcpListener) {
    handleConnection(tcpConn);
  }
  return tcpListener;
}

async function handleConnection(tcpConn: Deno.Conn) {
  let unixConn: Deno.Conn | undefined;

  try {
    unixConn = await Deno.connect({
      transport: "unix",
      path: "/var/run/docker.sock",
    });

    const copyPromises = [
      copy(tcpConn, unixConn).catch((err) => {
        if (err.code !== "EPIPE") {
          console.error("TCP -> Unix error:", err);
        }
      }),
      copy(unixConn, tcpConn).catch((err) => {
        if (err.code !== "EPIPE") {
          console.error("Unix -> TCP error:", err);
        }
      }),
    ];

    // Wait for either copy operation to complete or fail
    await Promise.all(copyPromises).finally(() => {
      // Ensure both connections are properly closed
      try {
        unixConn?.close();
        tcpConn.close();
      } catch (closeErr) {
        console.error("Error during connection cleanup:", closeErr);
      }
    });
  } catch (error) {
    console.error("Connection error:", error);
  } finally {
    // Extra safety: ensure connections are closed even if something goes wrong above
    try {
      unixConn?.close();
      tcpConn.close();
    } catch {
      // Ignore errors during emergency cleanup
    }
  }
}

import { GenericContainer } from "testcontainers";

startProxy();

Deno.env.set("DOCKER_HOST", "tcp://localhost:2375");

const container = new GenericContainer("minio/minio:latest");

const startedContainer = await container.start();

await startedContainer.stop();
```

**Comment by DanielSharkov** [comment]
Hi @taras, thank you for this **great workaround!** ❤️

Why are we awaiting both promises `TCP > UNIX` and `UNIX > TCP`?
I ran into an issue where the `UNIX > TCP` promise never resolved, causing open connections that blocked the process from exiting. I had to tweak the code slightly for my needs to prevent this _(https://github.com/apocas/dockerode/issues/747#issuecomment-2676878778)_.
Wouldn’t it be more correct to just use `Promise.race` to handle the first completed promise and cancel the unfinished one? Since we’re only interested in a single response, this might be the better approach.

**Comment by taras** [comment]
Hey @DanielSharkov, 

What change did you make in your tweak?

> Wouldn’t it be more correct to just use Promise.race to handle the first completed promise and cancel the unfinished one?

That sounds like a good idea. Have you tried it? Does it work?

**Comment by DanielSharkov** [comment]
You can find the full code in the mentioned issue: https://github.com/apocas/dockerode/issues/747#issuecomment-2676878778
I replaced `Promise.all` with `Promise.race` to wait for only one of the connections to finish. Because of this, I also needed to ignore the throw `EINTR` in addition to `err.code !== 'EPIPE'`, since we now actually cancel one of the connections.
When I want to stop the container, I also do `tcpListener.close()` and then await the connection handlers to complete (the `for await`).
Other changes are more a matter of preference.

And yes, it works _(on my machine…)_. With this solution, my script was no longer blocked and could exit properly.

**Comment by BlindKai** [comment]
Hey, guys!
I was trying to set `testcontainers-node` on Deno v2.2.3 and unfortunately, all the given examples result either failures on the stream level such as:
```
Error handling connection: BrokenPipe: Broken pipe (os error 32)
    at write (ext:deno_net/01_net.js:64:21)
    at TcpConn.write (ext:deno_net/01_net.js:128:12)
    at writeAll (https://jsr.io/@std/io/0.225.2/write_all.ts:32:30)
    at Module.copy (https://jsr.io/@std/io/0.225.2/copy.ts:40:11)
    at eventLoopTick (ext:core/01_core.js:177:7)
    at async Promise.all (index 1)
    at async handleConnection (file:///home/kai/deno/deno-rest-api/tests/infra/proxy.ts:23:5) {
  name: "BrokenPipe",
  code: "EPIPE"
}
``` 

Or it does not work at all. I also tried different dependencies, such as `dockerode` and `docker-modem`, directly, but all of those failed on the HTTP level.

The only way I made it work was to run it with a TCP host. (This way **is not secure by default**).
- https://docs.docker.com/engine/daemon/remote-access/
- https://docs.docker.com/engine/security/protect-access/

**Comment by pvillega** [comment]
Is this something we can expect fixed at some point, or is there an alternative to testcontainers for Deno that we can use? I ask, as I see the original issue was created in 2023. I've tried the workarounds, but they have their issues, like `leaks` on the tests.

**Comment by felipecrs** [comment]
I realized the leaks (which prevent tests from passing) are not being caused by the proxy itself. They are being caused by testcontainers (which may still be a Deno incompatibility).

You can verify that by avoiding spawning the proxy by making your docker daemon listen on TCP port directly.

Or you can use socat:

```json
// deno.jsonc
  "tasks": {
    "test": "pkgx socat TCP-L:2375,fork UNIX:/var/run/docker.sock & DOCKER_HOST=tcp://localhost:2375 deno test -A",
  },
```

**Comment by felipecrs** [comment]
Yeah, I can reproduce the leaks even when using /var/run/docker.sock with the testcontainers example:

https://testcontainers.com/guides/getting-started-with-testcontainers-for-nodejs/

```
❯ npx jest --detectLeaks
 FAIL  ./customer-repository.test.js
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:150:18)
      at node_modules/@jest/core/build/TestScheduler.js:254:19
      at node_modules/emittery/index.js:363:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:361:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        5.484 s, estimated 17 s
Ran all test suites.
```

Which means the leaks always existed. It would be nice if Deno allowed to bypass leaks detection.

**Comment by felipecrs** [comment]
Some updates:

1. My `socat` example above is not great because the `deno task` would never return
2. `Deno.env.set("TESTCONTAINERS_RYUK_DISABLED", "true")` resolved all leaks coming from testcontainers for my test suite (https://github.com/testcontainers/testcontainers-node/issues/967)
3. @DanielSharkov's [docker proxy code](https://github.com/apocas/dockerode/issues/747#issuecomment-2676878778) works perfectly. No leaks whatsoever.
4. You can bypass leaks detection in Deno: https://docs.deno.com/runtime/fundamentals/testing/#sanitizers
