### ISSUE TITLE
watchFs throws NotFound if the file being watch doesn't exist, no way to get file created event.

### ISSUE THREAD

**Issue by justinmchase** [denoland/deno#20329]
Suppose you have a script like this:

#### main.ts
```ts
for await (const event of Deno.watchFs("example.txt")) {
  console.log(event)
}
```

If the file `example.txt` does not exist and you run this script:
```sh
deno run -A main.ts
```

Then you'll get an error such as:

> NotFound: No path was found. about ["example.txt"]
  at new FsWatcher (ext:runtime/40_fs_events.js:17:21)
  at Object.watchFs (ext:runtime/40_fs_events.js:60:10)

But if you create the file, then start it it will work:

```sh
echo "hi" > example.txt
deno run -A main.ts
```

Not too surprising, but if you then _delete_ the file the watcher will continue to work just fine and if you recreate the file it will then fire off the events as expected.

What is _unexpected_ is that if the file does not exist on the initial call to `watchFs` then the call fails with an exception. What I expect to happen is for the call to succeed and for it to return events if at some point in the future the file is created successfully.

How can I watch for the file to be created?

**Comment by justinmchase** [comment]
I don't think it should be needed, tbh, but an "easy" workaround is to just ensure that the file exists already. Also, the std lib has a nice function for this:

```ts
import { ensureFile } from "std/fs/mod.ts";

await ensureFile("./example.txt");
```
