### ISSUE TITLE
Support Nitro (unjs)

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#20339]
Nitro - [Website](https://nitro.unjs.io/) - [GitHub](https://github.com/unjs/nitro)

Nitro is used as a server of Nuxt, Analog, SolidStart etc.

Repro:

- deno run -A npm:giget@latest nitro nitro-app
- cd nitro-app
- deno run -A npm:nitropack dev

```rust
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

[nitro 8:54:27 PM] ✔ Nitro built in 464 ms
error: Uncaught (in worker "$DENO_STD_NODE_WORKER_THREAD") TypeError: Cannot read properties of undefined (reading 'env')
    at file:///Users/admin/repos/deno-kitchensink/examples/nitro-app-2/.nitro/dev/index.mjs:1:58
error: Uncaught TypeError: Cannot create property 'message' on string 'Uncaught TypeError: Cannot read properties of undefined (reading 'env')'
    at _Worker.<anonymous> (file:///Users/admin/repos/deno-kitchensink/examples/nitro-app-2/node_modules/.deno/nitropack@2.6.2/node_modules/nitropack/dist/shared/nitro.f2f272d0.mjs:208:19)
    at Object.onceWrapper (ext:deno_node/_events.mjs:507:26)
    at _Worker.emit (ext:deno_node/_events.mjs:382:28)
    at Worker.<anonymous> (node:worker_threads:97:52)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:750:7)
    at invokeEventListeners (ext:deno_web/02_event.js:797:5)
    at dispatch (ext:deno_web/02_event.js:654:9)
    at Worker.dispatchEvent (ext:deno_web/02_event.js:1039:12)
    at Worker.#handleError (ext:runtime/11_workers.js:133:10)
    at Worker.#pollControl (ext:runtime/11_workers.js:158:33)
    at eventLoopTick (ext:core/01_core.js:183:11)
```

**Comment by bartlomieju** [comment]
The problem here appears to be that `process.env` is not defined - the file being executed (`./nitro/dev/index.mjs`) is not considered to be a Node file (even though it should).

**Comment by bartlomieju** [comment]
@littledivy suggests that this file is `require()`d and the context that it is evaluated in should have Node globals available. I will verify this.

**Comment by birkskyum** [comment]
Another nitro ticket is the issue of uWebSockets.js 

> error: npm package 'uWebSockets.js' does not exist.

- https://github.com/denoland/deno/issues/20604#issuecomment-1967933402
- https://github.com/denoland/deno/issues/22606

**Comment by birkskyum** [comment]
@kt3k , any update on this?

If i run without DENO_FUTURE=1 i get:

```sh
➜ deno run -A npm:nitropack dev              
error: npm package 'uWebSockets.js' does not exist.
```

With DENO_FUTURE=1, i don't really know how to execute the package:

```sh
➜ DENO_FUTURE=1 deno run -A npm:nitropack dev
error: Could not find a matching package for 'npm:nitropack' in a package.json file. You must specify this as a package.json dependency when the node_modules folder is not managed by Deno.
```
