### ISSUE TITLE
crypto.publicEncrypt: ASN.1 error: PEM error: PEM Base64 error: invalid Base64 encoding

### ISSUE THREAD

**Issue by dmoebius** [denoland/deno#20379]
There's something wrong with deno's implementation of node's `crypto.publicEncrypt()`:

Example: `test_crypto.mjs`
```javascript
import crypto from 'node:crypto'
import {Buffer} from 'node:buffer'

const publicKey =
    '-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDgtQn2JZ34ZC28NWYpAUd98iZ37BUrX/aKzmFbt7clFSs6sXqHauqKWqdtLkF2KexO40H1YTX8z2lSgBBOAxLsvaklV8k4cBFK9snQXE9/DDaFt6Rr7iVZMldczhC0JNgTz+SHXT6CBHuX3e9SdB1Ua44oncaTWz7OBGLbCiK45wIDAQAB\n-----END PUBLIC KEY-----'
const msg = Buffer.from('my secret message')

const rsaEncrypt = (msg, pubKey) => {
    msg = Buffer.concat([msg, Buffer.alloc(128 - msg.length)]) //pad to 128 bytes
    return crypto.publicEncrypt(
        { key: pubKey, padding: crypto.constants.RSA_NO_PADDING },
        msg,
    )
}

const encrypt = rsaEncrypt(msg, publicKey).toString('hex')
console.log(encrypt)
```

On node this runs fine:
```
$ node test_crypto.mjs
0cfd860a382edfbd3543f95c096fdd611bbafb028133b18b0e99e81e20fdb157ec41b71b77654c9504994a34b54851947519a443cbccd3b8845697f00cccfc8047ad73ea3aa900477388bac6a8731b1fb83de8678c1391b00a8af07096cb03ddedb1a49abd175a5932fdea341a52c3310d8f29a9f0e82f1eaef0cbe7ed1ec2d9
```

On deno:
```
$ deno run -A test_crypto.mjs 
error: Uncaught Error: ASN.1 error: PEM error: PEM Base64 error: invalid Base64 encoding
    return crypto.publicEncrypt(
                  ^
    at Object.publicEncrypt (ext:deno_node/internal/crypto/cipher.ts:193:14)
    at rsaEncrypt (file:///home/dmoebius/src/test_crypto.mjs:10:19)
    at file:///home/dmoebius/src/test_crypto.mjs:16:17
```

Environment:
```
$ deno --version
deno 1.36.3 (release, x86_64-unknown-linux-gnu)
v8 11.6.189.12
typescript 5.1.6

$ uname -a
Linux gordon 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux
```

**Comment by dmoebius** [comment]
I see that `RSA_NO_PADDING` is not supported in ` crypto.publicEncrypt()`, which delegates to `op_node_public_encrypt`:
https://github.com/denoland/deno/blob/main/ext/node/ops/crypto/mod.rs#L200

However, with `RSA_PKCS1_PADDING` you'll get the same error, because it bails out at line:
```
 let key = RsaPublicKey::from_public_key_pem((&key).try_into()?)?;
```
The question is why does the Rust implementaion doesn't accept my publicKey, whereas Node does?!?

Seems to be more of a Rust problem.

**Comment by dmoebius** [comment]
The RustCrypto RSA library doesn't deal with PEMs having lines longer than 64 chars: https://github.com/RustCrypto/RSA/issues/362 
Unfortunately this issue has been closed, but I asked to reopen it.

**Comment by littledivy** [comment]
We want to continue with the stricter interpretation of `rfc7468`. This comment provides reason: https://github.com/RustCrypto/RSA/issues/362#issuecomment-1710072304
