### ISSUE TITLE
node:child_process can not run when env has a undefined value

### ISSUE THREAD

**Issue by zuisong** [denoland/deno#20373]
node:child_process can not run when env has a undefined value.

The code below can run normally with node, but not with deno.

```ts
// filename: aaaa.mjs
import child_process from 'node:child_process';
import process from 'node:process';

child_process.spawn("ls", [], {
	stdio: [process.stdin, process.stdout, process.stderr],
   env: {
        VAR_NAME: undefined
    }
});
```

<img width="1376" alt="image" src="https://github.com/denoland/deno/assets/19145952/e291da05-aeea-4e16-9296-08436888cf33">

**Comment by zuisong** [comment]
Should we handle null values?

rome / biome can not run on deno because `null` env value, but the values in the type definition are non-null.

example:
```ts
// demo.mjs
import child_process from "node:child_process";
import process from "node:process";

child_process.spawn("echo", ["hello"], {
  stdio: [process.stdin, process.stdout, process.stderr],
  env: {
    NULL_VAR: null,
  },
});
```


output:
```
❯ node demo.mjs 
hello

❯ deno run -A demo.mjs
error: Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at ext:deno_node/internal/child_process.ts:100:53
    at mapValues (ext:deno_node/internal/child_process.ts:27:25)
    at new ChildProcess (ext:deno_node/internal/child_process.ts:100:23)
    at Object.spawn (node:child_process:104:10)
    at file:///Users/chen/mydata/docsify-kroki/demo.mjs:10:15

```
