### ISSUE TITLE
[kv] panic in fresh project

### ISSUE THREAD

**Issue by cknight** [denoland/deno#20464]
My fresh project is in a strange state.  When I run with `dev.ts` I get a panic:

```sh
chris@chris-desktop:~/dev/deno/kv_enqueue_test$ RUST_BACKTRACE=1 deno task start
Task start deno run -A --unstable --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 4 routes and 0 islands.
Starting main...
Listening for messages...
error: Uncaught (in promise) ReferenceError: Cannot access 'manifest' before initialization
await start(manifest, config);
            ^
    at file:///home/chris/dev/deno/kv_enqueue_test/main.ts:24:13
    at eventLoopTick (ext:core/01_core.js:183:11)
Watcher Process failed. Restarting on file change...

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.36.4
Args: ["/home/chris/.deno/bin/deno", "run", "-A", "--unstable", "--watch=static/,routes/", "dev.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Attempted to use a closed database', ext/kv/sqlite.rs:440:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
   4: <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   5: tokio::runtime::task::raw::poll
   6: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The code it is complaining about is here in `main.ts` on the last line of code:
```ts
/// <reference no-default-lib="true" />
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />
/// <reference lib="deno.unstable" />

import "$std/dotenv/load.ts";

import { start } from "$fresh/server.ts";
import manifest from "./fresh.gen.ts";
import config from "./fresh.config.ts";

console.log("Starting main...");

export const kv = await Deno.openKv();

kv.listenQueue(async (msg) => {
  console.log(msg);
});
console.log("Listening for messages...");

await start(manifest, config);
```

This was working fine earlier, not entirely sure what I've done to make it start panicing.  Running the same code with `main.ts` instead of `dev.ts` makes it work with no errors.

**Comment by littledivy** [comment]
This is fixed in newer Deno versions
