### ISSUE TITLE
Deno.inspect inconsistent when formatting intrinsic objects

### ISSUE THREAD

**Issue by rotu** [denoland/deno#20476]
When trying to inspect an [intrinsic object](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-well-known-intrinsic-objects) with `null` prototype, `Deno.reflect` acts weird. I'm not clear what to expect here - how much the behavior should follow the object itself versus that of the original intrinsic object.

I think the right way to get the value of a property on a null-prototype object is e.g.: `Reflect.get(ArrayBuffer.prototype, 'byteLength', myObject)`.

And the right way to invoke a function is e.g.: `Reflect.apply(Map.prototype.entries, myObject, [])`

---

`Object.setPrototypeOf(new Map([[1,2]]),null)`

```
[Internal Formatting Error] TypeError: Method Map.prototype.entries called on incompatible receiver #<Object>
    at MapIterator.entries (<anonymous>)
    at new SafeIterator (ext:core/00_primordials.js:317:26)
    at formatMap (ext:deno_console/01_console.js:1414:22)
    at formatRaw (ext:deno_console/01_console.js:1038:14)
    at formatValue (ext:deno_console/01_console.js:721:10)
    at Object.inspectArgs (ext:deno_console/01_console.js:3114:28)
    at <anonymous>:3:55
```
---

`Object.setPrototypeOf(new Set([1]),null)`

```
[Internal Formatting Error] TypeError: Method Set.prototype.values called on incompatible receiver #<Object>
    at SetIterator.values (<anonymous>)
    at new SafeIterator (ext:core/00_primordials.js:317:26)
    at formatSet (ext:deno_console/01_console.js:1391:22)
    at formatRaw (ext:deno_console/01_console.js:1038:14)
    at formatValue (ext:deno_console/01_console.js:721:10)
    at Object.inspectArgs (ext:deno_console/01_console.js:3114:28)
    at <anonymous>:3:55
```
---

`Object.setPrototypeOf(new Uint8Array([1,2]),null)`)
```
[(2): null prototype] [ 1n, 2n ]
```
(Note the elements are rendered with the `n` suffix as if bigints.

---

`Object.setPrototypeOf(new ArrayBuffer(10), null)`
```
[ArrayBuffer: null prototype] {
  [Uint8Contents]: <00 00 00 00 00 00 00 00 00 00>,
  byteLength: undefined
}
```
Note the `byteLength` property is shown even though its value is not properly rendered.

---

`Object.setPrototypeOf(new Error('oops'), null)`
Note the (non-enumerable) `stack` and `message` own properties are omitted.

```
[Error: null prototype] {}
```

**Comment by rotu** [comment]
These are *very* corner cases :-). It would help a ton to have a general expectation here (even if that expectation is just to print the intrinsic name and the instance's properties as if it were an ordinary object)
