### ISSUE TITLE
Deno can't find npm module, but same code works on Node.js

### ISSUE THREAD

**Issue by Classy-Bear** [denoland/deno#20474]
Hi Team,

Grateful for all the amazing work you guys do for this project.

I'm facing some issues while trying to use a **certain package** that works as expected in Node.js but not on Deno.js.  While other packages works as expected, this one not. Deno for some reason can't find this module.

Package: [odbc](https://www.npmjs.com/package/odbc)

Error:  
```
error: Uncaught Error: Cannot find module 'C:\Users\awesomeUser\AppData\Local\deno\npm\registry.npmjs.org\odbc\2.4.8\lib\bindings\napi-v6\odbc.node'
Require stack:
- C:\Users\awesomeUser\AppData\Local\deno\npm\registry.npmjs.org\odbc\2.4.8\lib\odbc.js
- C:\Users\awesomeUser\AppData\Local\deno\npm\registry.npmjs.org\odbc\2.4.8\lib\odbc.js
    at Function.Module._resolveFilename (node:module:624:15)
    at Function.Module._load (node:module:502:27)
    at Module.require (node:module:677:19)
    at require (node:module:791:16)
    at Object.<anonymous> (file:///C:/Users/awesomeUser/AppData/Local/deno/npm/registry.npmjs.org/odbc/2.4.8/lib/odbc.js:6:20)
    at Object.<anonymous> (file:///C:/Users/awesomeUser/AppData/Local/deno/npm/registry.npmjs.org/odbc/2.4.8/lib/odbc.js:58:4)
    at Module._compile (node:module:733:34)
    at Object.Module._extensions..js (node:module:747:10)
    at Module.load (node:module:658:32)
    at Function.Module._load (node:module:539:12)
```

Steps to reproduce:
1. `deno init`
2. Paste the follwing on `main.ts`:
```
import odbc from "npm:odbc@2.4.8";

if (import.meta.main) {
  connectToDatabase();
}

async function connectToDatabase() {
  const connection1 = await odbc.connect(
    "Driver={SQL Server};Server=myServer;Database=myDB;Trusted_Connection=yes;",
  );
  connection1.query(
    "select * from myTable ",
    (error, result) => {
      if (error) console.error(error);
      console.log(result);
    },
  );
}
```
3. `deno run main.ts`

Node code:
```
const odbc = require('odbc');

async function connectToDatabase() {
    const connection1 = await odbc.connect(
    "Driver={SQL Server};Server=myServer;Database=myDB;Trusted_Connection=yes;",
  );
  connection1.query("select * from myTable", (error, result) => {
    if (error) console.error(error);
    console.log(result);
  });
}

connectToDatabase();
```

**Comment by dsherret** [comment]
This is because Deno doesn't run install scripts in npm packages. Same thing happens in npm & node with `--ignore-scripts`:

```
> npm install --ignore-scripts odbc
...
added 61 packages, and audited 73 packages in 2s
> node test.js
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'V:\scratch\node_modules\odbc\lib\bindings\napi-v6\odbc.node'
Require stack:
...
```

One way to get around it is to open the package and manually run `npm run install`. It's definitely not ideal.

Follow #16164 for updates on this issue.

**Comment by Classy-Bear** [comment]
Got you, thanks @dsherret . Apologies for the duplicate.

**Comment by dsherret** [comment]
No need to apologize. It's difficult to figure this out. We'll slowly improve things over time.
