### ISSUE TITLE
Error: invalid data at https://deno.land/x/fresh@1.4.2/plugins/twind.ts:1:30

### ISSUE THREAD

**Issue by shaz-r** [denoland/deno#20499]
Versions:

```
❯ sw_vers 
ProductName:            macOS
ProductVersion:         13.5.1
BuildVersion:           22G90

❯ system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: Mac mini
      Model Identifier: Macmini9,1
      Model Number: Z12P000LSX/A
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 8422.141.2
      OS Loader Version: 8422.141.2
      Serial Number (system): x
      Hardware UUID: x
      Provisioning UDID: x
      Activation Lock Status: Enabled

❯ deno --version
deno 1.36.2 (release, aarch64-apple-darwin)
v8 11.7.439.1
typescript 5.1.6

```

Steps to reproduce:

```
❯ deno run -A -r https://fresh.deno.dev

 🍋 Fresh: The next-gen web framework. 

Project Name [fresh-project] fresh-project
Let's set up your new Fresh project.

Fresh has built in support for styling using Tailwind CSS. Do you want to use this? [y/N] y
Do you use VS Code? [y/N] y
The manifest has been generated for 5 routes and 1 islands.

Project initialized!

Enter your project directory using cd fresh-project.
Run deno task start to start the project. CTRL-C to stop.

Stuck? Join our Discord https://discord.gg/deno 

Happy hacking! 🦕

~/Code 12s
❯ cd fresh-project 

~/Code/fresh-project
❯ deno task start
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
error: invalid data
    at https://deno.land/x/fresh@1.4.2/plugins/twind.ts:1:30
Watcher Process failed. Restarting on file change...

```

Unsure if I've missed a step somewhere, or it's an actual bug - any help appreciated.

**Comment by lucacasonato** [comment]
This should be fixed in recent deno versions. Can you try again?

**Comment by lucacasonato** [comment]
Closing as I've gotten no response from OP.
