### ISSUE TITLE
Compiled Deno program panics on mac if permission denied error occurs

### ISSUE THREAD

**Issue by jordan-octavia-blue** [denoland/deno#20567]
I'm reporting the panic as instructed.  I believe this occurred due to Mac's OS level permissions.  I was attempting to run it on a file on Desktop, which I think is protected by default.  I would be more idea for me to be able to handle this in my program rather than it panicking.
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.36.1
Args: ["/Users/jordanoleary/.eden/bin/eden", "--preview"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', cli/standalone/mod.rs:96:49
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
   4: <deno::standalone::EmbeddedModuleLoader as deno_core::modules::loaders::ModuleLoader>::resolve
   5: deno_core::modules::RecursiveModuleLoad::new
   6: deno_core::modules::RecursiveModuleLoad::main
   7: deno::worker::CliMainWorker::execute_main_module_possibly_with_npm::{{closure}}
   8: deno::worker::CliMainWorker::run::{{closure}}
   9: deno::standalone::run::{{closure}}
  10: <deno_core::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
  11: tokio::runtime::task::raw::poll
  12: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.```

**Comment by aminnairi** [comment]
Experiencing this too on Arch if I don't set the permission properly when compiling my program, thing is it is not clear from this error what permission has been missed and trial & error is painful when attempting multiple options.

**Comment by bartlomieju** [comment]
This has been fixed.

The panic was an `unwrap()` on `std::env::current_dir()` in the compiled-binary module loader (`EmbeddedModuleLoader::resolve`, then at `cli/standalone/mod.rs:96`). On macOS, running from an OS-protected location (Desktop/Documents) made reading the cwd return `PermissionDenied`, and the `unwrap()` turned that into a panic.

The standalone runtime has since been refactored into the `denort` crate, and that call site now propagates the error instead of unwrapping (`cli/rt/run.rs`):

```rust
let current_dir =
  self.sys.env_current_dir().map_err(JsErrorBox::from_err)?;
deno_core::resolve_path(".", &current_dir)
  .map_err(JsErrorBox::from_err)?
```

So a `PermissionDenied` from reading the cwd now surfaces as a normal recoverable `ModuleLoaderError` rather than crashing with "Deno has panicked". Closing as resolved.
