### ISSUE TITLE
swagger-ui-express cannot loaded

### ISSUE THREAD

**Issue by jefripunza** [denoland/deno#20596]
my code :
`javascript
import SwagInit from "npm:swagger-autogen@2.23.1";
// @deno-types="npm:@types/swagger-ui-express@4.1.3"
import swaggerUi from "npm:swagger-ui-express@5.0.0";
import doc from "../swagger.ts";

  const swaggerAutogen = SwagInit();

  const endpointsFiles = [...Deno.readDirSync(modules_dir)]
    .filter((dirEntry) => !dirEntry.name.startsWith("#") && !dirEntry.isFile)
    .map(
      (dirEntry) => `${modules_dir}/${dirEntry.name}/${dirEntry.name}.router.ts`
    )
    .filter((dir_path) => {
      try {
        return Deno.statSync(dir_path).isFile;
      } catch (error) {
        return false;
      }
    });

  await swaggerAutogen(swagger_json_file, endpointsFiles, doc);

  const swagger_text = await Deno.readTextFile(swagger_json_file);
  const swagger_json = JSON.parse(swagger_text);
  console.log({ swagger_json });

  app.use("/swagger", swaggerUi.serve, swaggerUi.setup(swagger_json));`

and i have error result :

`error: Uncaught (in promise) TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (file:///C:/Users/jefripunza/AppData/Local/deno/npm/registry.npmjs.org/etag/1.8.1/index.js:83:11)
    at SendStream.setHeader (file:///C:/Users/jefripunza/AppData/Local/deno/npm/registry.npmjs.org/send/0.18.0/index.js:880:15)
    at SendStream.send (file:///C:/Users/jefripunza/AppData/Local/deno/npm/registry.npmjs.org/send/0.18.0/index.js:620:8)
    at onstat (file:///C:/Users/jefripunza/AppData/Local/deno/npm/registry.npmjs.org/send/0.18.0/index.js:725:10)
    at Deno.stat.then.denoErrorToNodeError.syscall (ext:deno_node/_fs/_fs_stat.ts:85:32)
    at eventLoopTick (ext:core/01_core.js:183:11)`

what's the solutions??? 🥲

**Comment by jefripunza** [comment]
up, please help me...

**Comment by bartlomieju** [comment]
Cannot reproduce on Deno 2.8.1. Tested with `swagger-ui-express@5.0.0` behind `express@4.18.2`, fetching `/swagger/`, `swagger-ui.css`, the JS bundles, and the favicon — all return 200 with the expected payloads, no `argument entity must be string, Buffer, or fs.Stats` error.

The original failure came from `etag@1.8.1`'s `isstats()` check, which requires `ctime`/`mtime` to be `Date` instances and `ino`/`size` to be numbers. Our `node:fs` `Stats` shim satisfies that today, so closing as fixed. Please reopen if you can still reproduce on a current Deno release.
