### ISSUE TITLE
Support Histoire

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#20606]
**Platform**

Darwin 22.6.0 arm64 arm

**Version**

deno 1.37.0

**Repro**

- Download this example https://stackblitz.com/edit/histoire-vue3-starter
- `deno task story:dev`

**Expected**

Histoire dev server start

**Actual**

```rust
➜ deno task story:dev
Warning Currently only basic package.json `scripts` are supported. Programs like `rimraf` or `cross-env` will not work correctly. This will be fixed in an upcoming release.
Task story:dev histoire dev
Error while loading /Users/admin/repos/histoire-vue3-starter/histoire.config.ts
error: Uncaught (in promise) NotFound: No such file or directory (os error 2): readfile 'module'
    at Object.readFileSync (ext:deno_fs/30_fs.js:702:14)
    at readFileSync (ext:deno_node/_fs/_fs_readFile.ts:45:21)
    at jiti (file:///Users/admin/repos/histoire-vue3-starter/node_modules/.deno/jiti@1.19.3/node_modules/jiti/dist/jiti.js:1:253424)
    at data::2:19
    at data::6:4
    at evalModule (file:///Users/admin/repos/histoire-vue3-starter/node_modules/.deno/jiti@1.19.3/node_modules/jiti/dist/jiti.js:1:255456)
    at jiti (file:///Users/admin/repos/histoire-vue3-starter/node_modules/.deno/jiti@1.19.3/node_modules/jiti/dist/jiti.js:1:253384)
```

**Comment by birkskyum** [comment]
With 1.44.2 this now breaks on:

```sh
➜ DENO_FUTURE=1 deno task story:dev
Task story:dev histoire dev
Error while loading histoire.config.ts
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'env')
```

**Comment by birkskyum** [comment]
just seeing a gray screen now

**Comment by birkskyum** [comment]
Trying to build the whole install/build the whole histoire repo, and hit this again...
- #25648

**Comment by birkskyum** [comment]
For easier testing, I made a repo here that uses latest deno 2.4.2 (with deno.json), and the upcoming Histoire 1.0

https://github.com/birkskyum/histoire-vue3-deno-demo

```sh

➜ deno task story:dev
Task story:dev deno run -A npm:histoire dev
3:35:10 PM [vite] (client) Re-optimizing dependencies because vite config has changed
Failed to resolve dependency: shiki, present in client 'optimizeDeps.include'
Port 6006 is in use, trying another one...
Using 5 threads for story collection
Collect stories start all
  ➜  Local:   http://127.0.0.1:6007/
  ➜  Network: use --host to expose
Error while collecting story /Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo/src/BaseButton.story.vue:

Error while collecting story /Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo/src/InjectDemo.story.vue:

/Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo/node_modules/.histoire/plugins/builtin_tailwind-tokens/Tailwind.story.js 605ms (setup:35ms, execute:8ms, run:562ms)
Collect stories end 984ms
3:35:12 PM [vite] (client) Pre-transform error: Failed to load PostCSS config (searchPath: /Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo): [ReferenceError] module is not defined
ReferenceError: module is not defined
    at file:///Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo/postcss.config.js?t=1753882510082:1:1
  Plugin: vite:css
  File: virtual:$histoire-theme.css
3:35:12 PM [vite] (client) Pre-transform error: Failed to load PostCSS config (searchPath: /Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo): [ReferenceError] module is not defined
ReferenceError: module is not defined
    at file:///Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo/postcss.config.js?t=1753882510082:1:1
  Plugin: vite:css
  File: virtual:$histoire-theme.css (x2)
3:35:12 PM [vite] (client) Pre-transform error: Failed to load PostCSS config (searchPath: /Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo): [ReferenceError] module is not defined
ReferenceError: module is not defined
    at file:///Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo/postcss.config.js?t=1753882510082:1:1
  Plugin: vite:css
  File: virtual:$histoire-theme.css (x3)
3:35:12 PM [vite] Internal server error: Failed to load PostCSS config (searchPath: /Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo): [ReferenceError] module is not defined
ReferenceError: module is not defined
    at file:///Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo/postcss.config.js?t=1753882510082:1:1
  Plugin: vite:css
  File: virtual:$histoire-theme.css
3:35:12 PM [vite] Internal server error: Failed to load PostCSS config (searchPath: /Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo): [ReferenceError] module is not defined
ReferenceError: module is not defined
    at file:///Users/admin/repos/deno-kitchensink/histoire-vue3-deno-demo/postcss.config.js?t=1753882510082:1:1
  Plugin: vite:css
```

**Comment by bartlomieju** [comment]
@birkskyum have you tried running with `DENO_COMPAT=1` env var? I think this might get you over the finish line here.

**Comment by birkskyum** [comment]
Excellent, that works for both deno.json and package.json! test repo [here](https://github.com/birkskyum/histoire-vue3-deno-demo)
