### ISSUE TITLE
Support SolidStart (SolidJS/Vite based)

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#20604]
**Platform**

Darwin 22.6.0 arm64 arm

**Version**

deno 1.37.0

**Repro**

- `deno run -A npm:create-solid`
- `deno task dev`

**Expected**

Dev server start

**Actual**

```rust
➜ deno task dev
Warning Currently only basic package.json `scripts` are supported. Programs like `rimraf` or `cross-env` will not work correctly. This will be fixed in an upcoming release.
Task dev solid-start dev
 solid-start dev 
 version  0.3.5
TypeError: worker.unref is not a function
    at startWorkerThreadService (file:///Users/admin/repos/deno-kitchensink/my-solidstart-app/node_modules/.deno/esbuild@0.17.19/node_modules/esbuild/lib/main.js:2292:10)
    at Object.transformSync (file:///Users/admin/repos/deno-kitchensink/my-solidstart-app/node_modules/.deno/esbuild@0.17.19/node_modules/esbuild/lib/main.js:2040:29)
    at Router.createRouteConfig (file:///Users/admin/repos/deno-kitchensink/my-solidstart-app/node_modules/.deno/solid-start@0.3.5/node_modules/solid-start/fs-router/router.js:188:19)
```

**Related to:**

- #19826

**Comment by birkskyum** [comment]
I tried this with the latest version of solid start (same repro instructions), and got a new output:

```sh
➜ deno task dev
Task dev vinxi dev
TypeError: Cannot read properties of undefined (reading 'cwd')
    at defineConfig (data::54:59)
    at data::3:26
    at data::6:4
    at evalModule (file:///Users/admin/repos/solidstart-app/node_modules/.deno/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:256697)
    at Object.jiti (file:///Users/admin/repos/solidstart-app/node_modules/.deno/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:254625)
    at resolveConfig (file:///Users/admin/repos/solidstart-app/node_modules/.deno/vinxi@0.0.52/node_modules/c12/dist/index.mjs:288:24)
    at loadConfig (file:///Users/admin/repos/solidstart-app/node_modules/.deno/vinxi@0.0.52/node_modules/c12/dist/index.mjs:116:40)
    at loadApp (file:///Users/admin/repos/solidstart-app/node_modules/.deno/vinxi@0.0.52/node_modules/vinxi/lib/load-app.js:35:29)
    at async Object.run (file:///Users/admin/repos/solidstart-app/node_modules/.deno/vinxi@0.0.52/node_modules/vinxi/bin/cli.mjs:65:17)
    at async runCommand (file:///Users/admin/repos/solidstart-app/node_modules/.deno/vinxi@0.0.52/node_modules/citty/dist/index.mjs:316:16)
    at async runCommand (file:///Users/admin/repos/solidstart-app/node_modules/.deno/vinxi@0.0.52/node_modules/citty/dist/index.mjs:307:11)
    at async runMain (file:///Users/admin/repos/solidstart-app/node_modules/.deno/vinxi@0.0.52/node_modules/citty/dist/index.mjs:441:7)
```

**Comment by birkskyum** [comment]
This one is a blocker for the new solid-start which is built on vinxi:

- #22502

**Comment by birkskyum** [comment]
SolidStart 0.6.0 is out ([release notes](https://github.com/solidjs/solid-start/releases/tag/v0.6.0))

Running the `basic` example gives:

```sh
➜ deno task dev        
error: npm package 'uWebSockets.js' does not exist.
```

Same error as:
- https://github.com/denoland/deno/issues/22606

**Comment by birkskyum** [comment]
With the BYONM flag, SolidStart is also stuck at
- https://github.com/denoland/deno/issues/23043

**Comment by birkskyum** [comment]
Interesting, now the `bare` example (can be selected from the cli on project creation) actually works.

The FileRoutes component (in the `basic` example) breaks with the following error:

```sh
(base) birkskyum@Birks-MacBook-Pro solid-project % deno task dev  
Task dev vinxi dev
vinxi v0.3.11
vinxi starting dev server

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ReferenceError: document is not defined
    at eval (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/vinxi@0.3.11/node_modules/vinxi/runtime/style.js, <anonymous>:34:19)
    at Array.forEach (<anonymous>)
    at Module.appendStyles (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/vinxi@0.3.11/node_modules/vinxi/runtime/style.js, <anonymous>:33:10)
    at Promise.Comp [as resolved] (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+start@1.0.0-rc.0_solid-js@1.8.16_vinxi@0.3.11_vite@5.2.7/node_modules/@solidjs/start/dist/router/lazyRoute.js, <anonymous>:26:33)
    at wrap (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:598:30)
    at Module.createComponent (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:349:15)
    at Object.outlet (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routing.js, <anonymous>:440:53)
    at Object.get children (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:133:23)
    at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:216:35
    at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:179:49
    at createMemo (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:95:9)
    at children (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:179:16)
    at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:216:14
    at createMemo (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:95:9)
    at provider (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:211:12)
    at Module.createComponent (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:349:15)
    at children (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:130:49)
    at Show (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:417:9)
    at Module.createComponent (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:349:15)
    at eval (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:125:38)
    at Routes (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:122:51)
    at Module.createComponent (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:349:15)
    at Object.get children (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:35:95)
    at Object.get children (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:70:22)
    at Object.get children (/Users/birkskyum/repos/deno-kitchensink/solid-project/src/app.tsx, <anonymous>:28:26)
    at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:685:41
    at catchError (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:152:12)
    at Object.get children (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:685:18)
    at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:216:35
    at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:179:49
    at createMemo (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:95:9)
    at children (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:179:16)
    at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:216:14
    at createMemo (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:95:9)
    at provider (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:211:12)
    at createComponent (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:349:15)
    at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:682:7
    at runWithOwner (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:190:12)
    at runSuspense (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:681:12)
    at Object.completed (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:662:21)
    at notifySuspense (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:632:7)
    at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:612:11
    at async Function.allSettled (<anonymous>)

**Comment by birkskyum** [comment]
`deno task build` game me this:

```sh

⚙  Preparing app for node-server...

 ERROR  No such file or directory (os error 2)                                                                                                     
 ERROR  No such file or directory (os error 2) 
```

**Comment by bartlomieju** [comment]
> Interesting, running the the `bare` example (can be selected from the cli on project creation) actually works now 🎉
> 
> The FileRoutes component (in the `basic` example) breaks with the following error:
> 
> ```shell
> (base) birkskyum@Birks-MacBook-Pro solid-project % deno task dev  
> Task dev vinxi dev
> vinxi v0.3.11
> vinxi starting dev server
> 
>   ➜ Local:    http://localhost:3000/
>   ➜ Network:  use --host to expose
> 
> ReferenceError: document is not defined
>     at eval (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/vinxi@0.3.11/node_modules/vinxi/runtime/style.js, <anonymous>:34:19)
>     at Array.forEach (<anonymous>)
>     at Module.appendStyles (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/vinxi@0.3.11/node_modules/vinxi/runtime/style.js, <anonymous>:33:10)
>     at Promise.Comp [as resolved] (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+start@1.0.0-rc.0_solid-js@1.8.16_vinxi@0.3.11_vite@5.2.7/node_modules/@solidjs/start/dist/router/lazyRoute.js, <anonymous>:26:33)
>     at wrap (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:598:30)
>     at Module.createComponent (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:349:15)
>     at Object.outlet (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routing.js, <anonymous>:440:53)
>     at Object.get children (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:133:23)
>     at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:216:35
>     at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:179:49
>     at createMemo (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:95:9)
>     at children (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:179:16)
>     at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:216:14
>     at createMemo (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:95:9)
>     at provider (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:211:12)
>     at Module.createComponent (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:349:15)
>     at children (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:130:49)
>     at Show (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:417:9)
>     at Module.createComponent (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:349:15)
>     at eval (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:125:38)
>     at Routes (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:122:51)
>     at Module.createComponent (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:349:15)
>     at Object.get children (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:35:95)
>     at Object.get children (/Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/@solidjs+router@0.13.1_solid-js@1.8.16/node_modules/@solidjs/router/dist/routers/components.jsx, <anonymous>:70:22)
>     at Object.get children (/Users/birkskyum/repos/deno-kitchensink/solid-project/src/app.tsx, <anonymous>:28:26)
>     at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:685:41
>     at catchError (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:152:12)
>     at Object.get children (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:685:18)
>     at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:216:35
>     at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:179:49
>     at createMemo (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:95:9)
>     at children (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:179:16)
>     at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:216:14
>     at createMemo (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:95:9)
>     at provider (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:211:12)
>     at createComponent (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:349:15)
>     at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:682:7
>     at runWithOwner (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:190:12)
>     at runSuspense (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:681:12)
>     at Object.completed (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:662:21)
>     at notifySuspense (file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:632:7)
>     at file:///Users/birkskyum/repos/deno-kitchensink/solid-project/node_modules/.pnpm/solid-js@1.8.16/node_modules/solid-js/dist/server.js:612:11
>     at async Function.allSettled (<anonymous>)
> ```

I think this will work if you run with `DENO_FUTURE=1` - this will remove `window` variable which should fix the problem - I think the package is using `window` check to decide if it's running in the browser.

**Comment by littledivy** [comment]
Yup, it works with `DENO_FUTURE=1`:

![image](https://github.com/denoland/deno/assets/34997667/6934d8f3-53cf-489a-a5ee-158d1fc0f4b4)

**Comment by birkskyum** [comment]
Interesting, I've never heard of that flag before. Does indeed fix the FileRoutes. The build error didn't change.

**Comment by carere** [comment]
@birkskyum Do you have an example Repo ?

**Comment by carere** [comment]
Here is my package.json:
```json
{
  "name": "solid-spa-deno",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "optimize": "vite optimize"
  },
  "dependencies": {
    "solid-js": "^1.8.16",
    "@solidjs/router": "^0.13.1"
  },
  "devDependencies": {
    "autoprefixer": "latest",
    "cssnano": "latest",
    "tailwindcss": "latest",
    "postcss": "latest",
    "postcss-import": "latest",
    "typescript": "latest",
    "vite": "latest",
    "vite-plugin-solid": "latest"
  }
}
```

And here is my deno.jsonc
```json
{
  "unstable": ["byonm", "bare-node-builtins"],
  "imports": {
    "solid-js": "https://esm.sh/solid-js@1.8.16"
  },
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "solid-js",
    "lib": ["dom", "deno.ns"],
    "types": ["vite/client"]
  }
}
```

I'm trying to get the types for JSX working, but I don't know why it's not working. Do you guys have  some example of configuration with the byonm unstable flag ?

**Comment by birkskyum** [comment]
@carere , since you're not using SolidStart this is not the right ticket. You'd want to replace react with preserve in the tsconfig.

**Comment by carere** [comment]
Ok, it's seems to be a problem with the cache of a specific file, I renamed it, and it works.
But I"m only able to make it work with the canary version of Deno.
When I use the stable 1.42.0, even so I add unstable flag byonm in deno.json or DENO_FUTURE=1 before my command, I still get the `Deno.internal.rid error`.

Do you guys also use Canary version ?

**Comment by birkskyum** [comment]
@carere , generally yes.

**Comment by littledivy** [comment]
Fixed by #23469 

Tested `dev`, `build` and `serve` on various SolidStart projects. 

![demo](https://github.com/denoland/deno/assets/34997667/d7e2fb52-e391-42ab-bc85-abfa9ec43bdd)

**Comment by birkskyum** [comment]
Amazing! I'll be testing this today to see if it can handle a real project.

**Comment by birkskyum** [comment]
The basics appear to work, which is great, but there are still some rough edges. First thing I tried was i.e. to enable https in one of the solid-start examples by changed the `app.config.ts` to this:

```ts
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  server: {
    https:true
  }
});

```

It'll break with: 

```ts
➜ DENO_FUTURE=1 deno task dev  
Task dev vinxi dev
vinxi v0.3.11
vinxi starting dev server

 ERROR  Not implemented: crypto.KeyObject.prototype.asymmetricKeyType                                                                                                                     3:17:44 PM

  at notImplemented (ext:deno_node/_utils.ts:6:9)
  at KeyObject.export (ext:deno_node/internal/crypto/keys.ts:74:5)
  at ext:deno_node/internal/crypto/keygen.ts:45:37
  at eventLoopTick (ext:core/01_core.js:168:7) 



 ERROR  Not implemented: crypto.KeyObject.prototype.asymmetricKeyType                                                                                                                     3:17:44 PM
```
