### ISSUE TITLE
Support Storybook [tracking]

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#20610]
Storybook - [Website](https://storybook.js.org/) - [GitHub](https://github.com/storybookjs/storybook)

Open issues with Deno 2:

- https://github.com/denoland/deno/issues/26404
- https://github.com/denoland/deno/issues/26405

**Comment by birkskyum** [comment]
Error in Deno 1.40

```sh
➜ deno run -A npm:storybook@latest init
error: Uncaught TypeError: The associated stream is already closing.
    at WritableStreamDefaultWriter.close (ext:deno_web/06_streams.js:6569:9)
    at HttpsClientRequest.end (node:http:445:23)
    at Readable.<anonymous> (ext:deno_node/_stream.mjs:5374:15)
    at Object.onceWrapper (ext:deno_node/_stream.mjs:1929:32)
    at Readable.emit (ext:deno_node/_stream.mjs:1859:11)
    at endReadableNT (ext:deno_node/_stream.mjs:3648:16)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:33:15)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:66:21)
```

**Comment by birkskyum** [comment]
Ran the init command with pnpx, and tried to build storybook gave this:

```sh
➜ DENO_FUTURE=1 deno task build-storybook
Task build-storybook storybook build
@storybook/cli v8.0.8

info => Cleaning outputDir: storybook-static
info => Loading presets
Error: Cannot find module '@storybook/builder-vite'
```

**Comment by birkskyum** [comment]
appear to be stuck installing with deno 2 rc 2
<img width="612" alt="Screenshot 2024-09-18 at 02 07 45" src="https://github.com/user-attachments/assets/4204a21c-3fae-4f7a-b6d3-f8ec2b308e22">

**Comment by birkskyum** [comment]
Fails the init with deno 2 rc 2:

```sh
➜ deno run -A npm:storybook@latest init
╭──────────────────────────────────────────────────────╮
│                                                      │
│   Adding Storybook version 8.3.1 to your project..   │
│                                                      │
╰──────────────────────────────────────────────────────╯
 • Detecting project type. ✓
Installing dependencies...

npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm error Cannot read properties of null (reading 'matches')
npm error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-09-18T00_08_22_605Z-debug-0.log
An error occurred while installing dependencies.
```

**Comment by birkskyum** [comment]
initializing with
- `npx storybook@latest init`
- `deno install`
- `deno task storybook`

gives this error

```sh
⇣8% ➜ deno task storybook
Task storybook storybook dev -p 6006
@storybook/core v8.3.1


============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 2.0.0-rc.2+aaf2bf4
Args: ["/Users/admin/.deno/bin/deno", "run", "-A", "npm:storybook@8.3.1", "dev", "-p", "6006"]

thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.309.0/modules/map.rs:1205:24:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bartlomieju** [comment]
CC @devsnek looks like it's related to `require(esm)`.

**Comment by birkskyum** [comment]
Now I see some install issue with `npm:storybook-solidjs-vite` module not found
- #25813

**Comment by birkskyum** [comment]
With deno 2 rc.6 is gives:

```
➜ deno task storybook           
Task storybook storybook dev -p 6006
@storybook/core v8.3.1

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: storybook-solidjs-vite/preset.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error: ReferenceError: module is not defined
    at file://./node_modules/.deno/storybook-solidjs-vite@1.0.0-beta.2/node_modules/storybook-solidjs-vite/dist/preset.js:31:1
    at loadESMFromCJS (node:module:770:21)
    at Module._compile (node:module:725:12)
    at Module._extensions..js (node:module:767:10)
    at Object.newLoader (file://./node_modules/.deno/esbuild-register@3.6.0/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.extensions..js (file://./node_modules/.deno/esbuild-register@3.6.0/node_modules/esbuild-register/dist/node.js:4833:24)
    at Module.load (node:module:665:32)
    at Function.Module._load (node:module:537:12)
    at Module.require (node:module:684:19)
    at require (node:module:808:16)
    at loadESMFromCJS (node:module:770:21)
    at Module._compile (node:module:725:12)
    at Module._extensions..js (node:module:767:10)
    at Object.newLoader (file://./node_modules/.deno/esbuild-register@3.6.0/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.extensions..js (file://./node_modules/.deno/esbuild-register@3.6.0/node_modules/esbuild-register/dist/node.js:4833:24)
    at Module.load (node:module:665:32)
    at Function.Module._load (node:module:537:12)
    at Module.require (node:module:684:19)
    at require (node:module:808:16)
    at interopRequireDefault (file://./node_modules/.deno/@storybook+core@8.3.1/node_modules/@storybook/core/dist/common/index.cjs:134633:11)

More info: 

    at loadPreset (file://./node_modules/.deno/@storybook+core@8.3.1/node_modules/@storybook/core/dist/common/index.cjs:139445:13)
    at eventLoopTick (ext:core/01_core.js:175:7)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by birkskyum** [comment]
Repro:

- `deno run -A npm:storybook@latest init` (select vue 3 + vite)
- `deno task storybook`
```

Error:

```
➜ deno task storybook
Task storybook storybook dev -p 6006
@storybook/core v8.3.6

NotFound: No such file or directory (os error 2): readfile 'chromatic.config.json'
    at Object.readFileSync (ext:deno_fs/30_fs.js:733:10)
    at Object.readFileSync (ext:deno_node/_fs/_fs_readFile.ts:52:21)
    at Object.Ege (file://./node_modules/.deno/chromatic@11.12.6/node_modules/chromatic/dist/chunk-P6VYOOE6.js:827:1175)
    at Object.Uir [as experimental_serverChannel] (file://./node_modules/.deno/@chromatic-com+storybook@1.9.0/node_modules/@chromatic-com/storybook/dist/preset.js:595:402)
    at file://./node_modules/.deno/@storybook+core@8.3.6/node_modules/@storybook/core/dist/common/index.cjs:139480:18
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async storybookDevServer (file://./node_modules/.deno/@storybook+core@8.3.6/node_modules/@storybook/core/dist/core-server/index.cjs:47285:11)
    at async buildOrThrow (file://./node_modules/.deno/@storybook+core@8.3.6/node_modules/@storybook/core/dist/core-server/index.cjs:46581:12)
    at async buildDevStandalone (file://./node_modules/.deno/@storybook+core@8.3.6/node_modules/@storybook/core/dist/core-server/index.cjs:48518:78)
    at async withTelemetry (file://./node_modules/.deno/@storybook+core@8.3.6/node_modules/@storybook/core/dist/core-server/index.cjs:47080:12)


```

**Comment by birkskyum** [comment]
Issues:
- #26404

**Comment by kt3k** [comment]
Now I see this error while running `deno task storybook`. Is `chromatic.config.json` supposed to exist in cwd?

```
$ deno task storybook
Task storybook storybook dev -p 6006
@storybook/core v8.4.5

NotFound: No such file or directory (os error 2): readfile 'chromatic.config.json': No such file or directory (os error 2): readfile 'chromatic.config.json': No such file or directory (os error 2)
    at Object.readFileSync (ext:deno_fs/30_fs.js:733:10)
    at Object.readFileSync (ext:deno_node/_fs/_fs_readFile.ts:52:21)
    at Object.Ooe (file://./node_modules/.deno/chromatic@11.18.1/node_modules/chromatic/dist/chunk-44ZQWA3Z.js:706:1340)
    at Object.Uir [as experimental_serverChannel] (file://./node_modules/.deno/@chromatic-com+storybook@1.9.0/node_modules/@chromatic-com/storybook/dist/preset.js:595:402)
    at file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/common/index.cjs:16512:18
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async storybookDevServer (file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/core-server/index.cjs:35955:96)
    at async buildOrThrow (file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/core-server/index.cjs:35017:12)
    at async buildDevStandalone (file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/core-server/index.cjs:37190:78)
    at async withTelemetry (file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/core-server/index.cjs:35757:12)
```

**Comment by kt3k** [comment]
Now I see the below error:

```
$ deno task storybook
Task storybook storybook dev -p 6006
@storybook/core v8.4.5

TypeError: g.start is not a function
    at storybookDevServer (file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/core-server/index.cjs:35974:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async buildOrThrow (file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/core-server/index.cjs:35017:12)
    at async buildDevStandalone (file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/core-server/index.cjs:37190:78)
    at async withTelemetry (file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/core-server/index.cjs:35757:12)
    at async dev (file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/cli/bin/index.cjs:2591:3)
    at async s.<anonymous> (file://./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/cli/bin/index.cjs:2643:74)
```

**Comment by kt3k** [comment]
It looks like a wrong branch of conditional exports is taken for the dynamic import `import("@storybook/core/builder-manager")` from `./node_modules/.deno/@storybook+core@8.4.5/node_modules/@storybook/core/dist/core-server/index.cjs` (I'll create an issue for it)

**Comment by kt3k** [comment]
I was able to start the storybook server by `deno task storybook` with the canary a750314

I was also able to build the static storybook by `deno task build-storybook` 🎉

**Comment by kfp** [comment]
Works for me in deno 2.1.2!

**Comment by kt3k** [comment]
Closing as fixed! @kfp Thanks for checking!

@birkskyum Thank you for tracking this for long time!

**Comment by birkskyum** [comment]
@kt3k are the subtickets resolved?

https://github.com/denoland/deno/issues/20610

**Comment by kt3k** [comment]
Ah, `storybook init` seems still failing with `ERESOLVE - Dependency resolution error.`.

**Comment by valentinpalkovic** [comment]
Hey folks,

One of the Storybook Core developers here 👋

If someone wants to work on the issues and needs guidance or help or even just some Storybook context, I am happy to help. Time-wise I will not able to work on the Deno-related issues myself, but I try to assist where I can. Maybe we can adjust some code parts at Storybook that we can more easily support Deno.

**Comment by kt3k** [comment]
`storybook init` now seems compatible with Deno at the latest version of storybook:

```
deno -A npm:storybook@8.5.2 init
```

This successfully generated storybook project and started the preview server.

@birkskyum Can you confirm the above on your environment?


---

Note: the compatibility seems fixed at 8.5.0-alpha.11. You can check it by `deno -A npm:storybook@8.5.0-alpha.11 init`

**Comment by birkskyum** [comment]
@kt3k , this appear to be very close. I left a stacktrace inside #26405 

I don't know if there's a problem in the react typescript template... it would of course be great to have storybook use `deno i` to install packages, because I think it might be `npm i` that is somehow breaking.

**Comment by RCVarley** [comment]
**os**: MacOS 15.3.2 (24D81)
**deno**: 2.2.6
**node**: 22.13.1 (nvm)
**storybook**: 8.6.11
**command**: `deno run -A npm:storybook@latest init`
**options**: Documentation & Tests
**error**:
```
7540 silly placeDep ROOT @types/node@18.19.84 OK for: ts-node@10.9.2 want: *
7541 verbose stack TypeError: Cannot read properties of null (reading 'matches')
7541 verbose stack     at Link.matches (/Users/ryan/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1117:41)
7541 verbose stack     at Link.canDedupe (/Users/ryan/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1071:15)
7541 verbose stack     at PlaceDep.pruneDedupable (/Users/ryan/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:426:14)
7541 verbose stack     at new PlaceDep (/Users/ryan/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:278:14)
7541 verbose stack     at new PlaceDep (/Users/ryan/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:314:26)
7541 verbose stack     at #buildDepStep (/Users/ryan/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:920:18)
7541 verbose stack     at async Arborist.buildIdealTree (/Users/ryan/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
7541 verbose stack     at async Promise.all (index 1)
7541 verbose stack     at async Arborist.reify (/Users/ryan/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
7541 verbose stack     at async Install.exec (/Users/ryan/.nvm/versions/node/v22.13.1/lib/node_modules/npm/lib/commands/install.js:150:5)
7542 error Cannot read properties of null (reading 'matches')
7543 silly unfinished npm timer reify 1743264029061
7544 silly unfinished npm timer reify:loadTrees 1743264029061
7545 silly unfinished npm timer idealTree:buildDeps 1743264029275
7546 silly unfinished npm timer idealTree:node_modules/.deno/signal-exit@4.1.0/node_modules/signal-exit 1743264092692
7548 verbose os Darwin 24.3.0
7549 verbose node v22.13.1
7550 verbose npm  v10.9.2
```

**Comment by kt3k** [comment]
`storybook init` now seems fixed (https://github.com/denoland/deno/issues/26405). Can anyone confirm that with the latest Deno?

**Comment by bartlomieju** [comment]
Storybook is fully working on Deno 2.7.4 canary. Both linked sub-issues are resolved.

**Repro steps:**

```sh
# Create a React+Vite project
deno run -A npm:create-vite@latest sb-test --template react-ts
cd sb-test
deno install

# Init Storybook
deno run -A npm:storybook@latest init --yes

# Install deps (storybook init adds new packages)
deno install

# Run Storybook
deno task storybook
```

**Result:** Storybook 10.2.17 starts successfully, serves on http://localhost:6006, and the frontend loads and works correctly.

```
┌  storybook v10.2.17
│
●  Starting...
│  Storybook ready!
│  - Local: http://localhost:6006/
│
●  183 ms for manager and 228 ms for preview
```

**Sub-issue status:**
- #26404 (runtime `NotFound: readfile 'chromatic.config.json'` crash) — already closed, confirmed fixed
- #26405 (`npm error Cannot read properties of null` during init) — no longer occurs with Storybook 10.x + Deno 2.7.4

Closing as fixed. Please reopen if you can still reproduce on a recent Deno version.

**Comment by SDVoGo** [comment]
Not in my end.

```cmd
deno run -A npm:storybook@latest init --yes
"npx.cmd" is not recognized as an internal or external command, operable program or batch file ```

deno 2.7.4 (stable, release, x86_64-pc-windows-msvc)

**Comment by bartlomieju** [comment]
@SDVoGo The `"npx.cmd" is not recognized` error happens because Storybook's `init` command internally shells out to `npx` to run setup steps. Since Deno doesn't ship npm/npx binaries, that call fails when you don't have Node.js installed alongside Deno.

As a workaround on Windows, you can create an `npx.cmd` shim that redirects to Deno's equivalent `deno run` / `deno x` functionality. Create a file called `npx.cmd` somewhere on your `PATH` (e.g. in `%USERPROFILE%\.deno\bin\`) with:

```cmd
@echo off
deno run -A npm:%*
```

This will make Storybook's `npx <package>` calls go through Deno instead. Note that this is a rough shim and may not cover every npx usage pattern, but it should be enough to get `storybook init` working.
