### ISSUE TITLE
Support npm:tsx (esbuild)

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#20625]
tsx - [GitHub](https://github.com/esbuild-kit/tsx)

This compiler is used many places in peoples package.json scripts, so it would be great if deno is able to execute it, until it's replaced with i.e. deno everywhere.

**Platform**

Darwin 22.6.0 arm64 arm

**Version**

deno 1.37.0

**Repro**

```ts
// index.ts
console.log("Print this");
```

- `deno run npm:tsx index.ts`

It actually breaks even without a file provided, so just `deno run npm:tsx`;

**Expected**

`> Print this`

**Actual**

```rust
➜ deno run npm:tsx index.  
error: Uncaught TypeError: ws.WriteStream.prototype.hasColors is not a function
    at file:///Users/admin/repos/compile-with-tsx/node_modules/.deno/tsx@3.12.10/node_modules/tsx/dist/cli.js:18:332
```

**Comment by littledivy** [comment]
https://github.com/privatenumber/tsx/blob/2c829258a6ca238b7a22c85cc8a09a531267d472/src/run.ts#L39-L40

tsx depends on `--require` with a preflight CJS.

**Comment by marvinhagemeister** [comment]
The missing `hasColors` method error is resolved in `main` and it fails now with this error:

```sh
error: unexpected argument '--require' found

  tip: a similar argument exists: '--quiet'

Usage: deno run --allow-all --quiet [SCRIPT_ARG]...

For more information, try '--help'.
```

**Comment by birkskyum** [comment]
deno 2.0.0-rc.2+aaf2bf4

```sh
> deno run -A npm:tsx index.ts

error: unexpected argument '--require' found

  tip: to pass '--require' as a value, use '-- --require'

Usage: deno run [OPTIONS] [SCRIPT_ARG]...
```

**Comment by birkskyum** [comment]
@marvinhagemeister , is this likely to be upsteam issue with the flag similar to the tauri issue here?
- https://github.com/denoland/deno/issues/25904

**Comment by pi0** [comment]
I am experiencing similar issue with latest vitest (v4) on deno: https://github.com/h3js/srvx/pull/138 (reported to https://github.com/vitest-dev/vitest/issues/8896)

**Comment by birkskyum** [comment]
Hmm, now i see

```sh
❯ deno run -A npm:tsx index.ts
error: Uncaught (in promise) Error: This version of Node.js (v24.2.0) does not support module.register(). Please upgrade to Node v18.19 or v20.6 and above.
    at register (file:///Users/admin/repos/deno-kitchensink/tsx/node_modules/.deno/tsx@4.21.0/node_modules/tsx/dist/register-B7jrtLTO.mjs:1:581)
    at file:///Users/admin/repos/deno-kitchensink/tsx/node_modules/.deno/tsx@4.21.0/node_modules/tsx/dist/esm/index.mjs:2:5894
```

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/33763 and https://github.com/denoland/deno/pull/33849
