### ISSUE TITLE
Deno Basic example  import fails - error import received corrupt message of InvalidContentType

### ISSUE THREAD

**Issue by surfmuggle** [denoland/deno#20709]
Working through the [tutorial manage dependencies](https://docs.deno.com/runtime/tutorials/manage_dependencies) i got this error

> error: Import 'https://x.nest.land/ramda@0.27.0/source/index.js' failed: error sending request for url (https://x.nest.land/ramda@0.27.0/source/index.js): error trying to connect: received corrupt message of type InvalidContentType
>     at file:///C:/Apps/Deno/deps.ts:9:8

The file deps.ts looks like this

```ts
/**
 * deps.ts
 *              This module re-exports the required methods 
 *              from the dependant remote Ramda module.
 */
export {
  add,
  multiply,
} from "https://x.nest.land/ramda@0.27.0/source/index.js";
```

Line 9 is this line `from "https://x.nest.land/ramda@0.27.0/source/index.js";`

Opening the url [x.nest.land/ramda...](https://x.nest.land/ramda@0.27.0/source/index.js)  with a browser works. It contains a bunch of exports

```ts
export { default as F } from './F.js';
export { default as T } from './T.js';
export { default as __ } from './__.js';
....
```

I assume that the error above is due to the fact that i am behind a corporate proxy. [This answer](https://stackoverflow.com/a/61997862/819887) suggests to create two environmental variables under windows: `HTTP_PROXY` and `HTTPS_PROXY`. The same is said in the [deno docs about proxies](https://docs.deno.com/runtime/manual/basics/modules/proxies)

But on my windows box these variables were already set like this for our proxy server

```console
http://[user_id]:[PASSWORD]@ourproxy.some.company:8080
```
Questions
 - What can i do to avoid this import error - can i use a downloaded copy of the file and how?
 - How can i fix the presumed proxy problem?

**Comment by lucacasonato** [comment]
Can you try run with `DENO_TLS_CA_STORE=system`?

**Comment by surfmuggle** [comment]
I did add the [environment variable](https://docs.deno.com/runtime/manual/getting_started/setup_your_environment#environment-variables) `DENO_TLS_CA_STORE=system` as suggested.  After that  i tried `deno run -A HelloDeno\helloFetch.ts ` 

```ts
/**
 * helloFetch.ts
 */
export {}
const site = await fetch("https://www.deno.com");
console.log(await site.text());
```
and got this error: 
> C:\Apps\Deno>deno run -A HelloDeno\helloFetch.ts 
> 
> ============================================================
> Deno has panicked. This is a bug in Deno. Please report this
> at https://github.com/denoland/deno/issues/new.
> If you can reliably reproduce this panic, include the
> reproduction steps and re-run with the RUST_BACKTRACE=1 env
> var set and include the backtrace in your report.
> 
> Platform: windows x86_64
> Version: 1.37.1
> Args: ["deno", "run", "-A", "HelloDeno\\helloFetch.ts"]
> 
> thread 'main' panicked at 'Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)', cli\args\mod.rs:504:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by surfmuggle** [comment]
I did add `RUST_BACKTRACE=1` as a user environement variable `HKEY_CURRENT_USER\Environment` but it seems to make no difference

```shell
C:\Users\myuser>SET RUST
RUST_BACKTRACE=1

C:\Users\myuser>SET DENO
DENO_TLS_CA_STORE=system
```

**Comment by lucacasonato** [comment]
Do you happen to know what proxy you are using?

**Comment by surfmuggle** [comment]
About the proxy - i am not sure: 

 - my "normal client" connections (for instance with the browser) are probably tunneled by `ZSATunnel.exe`; this assumption is based on [this reply here](https://superuser.com/questions/346372/how-do-i-know-what-proxy-server-im-using) and the command `netstat -ban` and 
 - under proxy settings a script like `http://127.0.0.1:xxx/localproxy-xxx.pac` is loaded.  This file contains different proxy ips.  Running `tracert  127.0.0.1` results in 1 hop and contains `kubernetes.docker.internal`
 -  There is also a programm titled `Zscaler Client connector`. 
 -  But i also have a programm `Check Point Mobile` to connect into the VPN. 
 - for connections for tools like `eclipse, npm, node etc` we have a dedicated `dev-proxy` dns-entry that could be different from the normal `browsing traffic`. Inside the [pac-file](https://learn.microsoft.com/en-us/internet-explorer/ie11-ieak/proxy-auto-config-examples) the ip range for this `dev-proxy`is marked for `DIRECT` connections

**Comment by surfmuggle** [comment]
If i try to connect to the internet with go i also encounter a problem ( see [Go Rest Client](https://stackoverflow.com/questions/77206983/) or [Go package installation fails](https://stackoverflow.com/questions/77210474/))

> `proxyconnect tcp: tls: first record does not look like a TLS handshake and explain the cause:`
> 
> This is because the proxy answers with an plain HTTP error to the strange HTTP request (which is actually the start of the TLS handshake).

Could it be that the underlying cause also is responsible for the problems i have with deno?

**Comment by surfmuggle** [comment]
Just to provide an update. I downloaded the [current release v1.39.4](https://github.com/denoland/deno/releases/tag/v1.39.4) and entered
```cmd
C:\Apps\Deno>SET RUST_BACKTRACE=full

C:\Apps\Deno>deno upgrade
Looking up latest version

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.39.4
Args: ["deno", "upgrade"]

thread 'main' panicked at cli\args\mod.rs:579:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
stack backtrace:
   0:     0x7ff707cf3c3a - onig_get_syntax
   1:     0x7ff706812cad - onig_get_start_by_callout_args
   2:     0x7ff707cd2361 - onig_get_syntax
   3:     0x7ff707cf788a - onig_get_syntax
   4:     0x7ff707cf71df - onig_get_syntax
   5:     0x7ff707cf6d51 - onig_get_syntax
   6:     0x7ff706607df9 - napi_fatal_error
   7:     0x7ff707cf7bf3 - onig_get_syntax
   8:     0x7ff707cf7aa5 - onig_get_syntax
   9:     0x7ff707cf79e9 - onig_get_syntax
  10:     0x7ff707cf79d4 - onig_get_syntax
  11:     0x7ff7092922f7 - onig_unicode_define_user_property
  12:     0x7ff7092928a3 - onig_unicode_define_user_property
  13:     0x7ff706350cf3 - napi_close_callback_scope
  14:     0x7ff70630083c - napi_close_callback_scope
  15:     0x7ff707b08aba - onig_get_syntax
  16:     0x7ff70634f82c - napi_close_callback_scope
  17:     0x7ff706300999 - napi_close_callback_scope
  18:     0x7ff707b08aba - onig_get_syntax
  19:     0x7ff706388dd3 - napi_close_callback_scope
  20:     0x7ff706388e4f - napi_close_callback_scope
  21:     0x7ff706389236 - napi_close_callback_scope
  22:     0x7ff706594f98 - napi_fatal_error
  23:     0x7ff7065f1127 - napi_fatal_error
  24:     0x7ff7060b21bd - <unknown>
  25:     0x7ff7066d91c5 - napi_release_threadsafe_function
  26:     0x7ff7061bf1d6 - napi_close_callback_scope
  27:     0x7ff706609eaa - napi_fatal_error
  28:     0x7ff70609d0ea - <unknown>
  29:     0x7ff7060a8c51 - <unknown>
  30:     0x7ff709237bbc - onig_unicode_define_user_property
  31:     0x7ffe65da7344 - BaseThreadInitThunk
  32:     0x7ffe66d426b1 - RtlUserThreadStart
```

**Comment by bartlomieju** [comment]
This problem should no longer occur - if there's a problem with loading certs Deno now provides a graceful error with suggestions how to proceed.
