### ISSUE TITLE
--v8-flags conflict

### ISSUE THREAD

**Issue by danilovmy** [denoland/deno#20752]
if i use those flags:

```
--v8-flags='--jitless'
--v8-flags='--lite-mode' 
```
this flags are discussed here: https://github.com/denoland/deno/issues/6621

i recieve conflict message:

```
Warning: disabling flag --expose_wasm due to conflicting flags                                                                                                                                     
error: Uncaught ReferenceError: WebAssembly is not defined                                                                                                                                         
        const instance = await WebAssembly.instantiate(module, imports);                                                                                                                           
                         ^                                                                                                                                                                         
    at load (https://deno.land/x/denoflate@1.2.1/pkg/denoflate.js:216:26)                                                                                                                          
    at init (https://deno.land/x/denoflate@1.2.1/pkg/denoflate.js:247:40)                                                                                                                          
    at async https://deno.land/x/denoflate@1.2.1/mod.ts:13:1  
```

**Comment by littledivy** [comment]
WebAssembly in V8 is not exposed when --jitless is enabled. 

Related upstream bug: https://bugs.chromium.org/p/v8/issues/detail?id=10329
