### ISSUE TITLE
formatError would emit confusing error message if source of error holds global builder in REPL

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#2083]
e.g.
```
> new Worker
Uncaught Error: assert
    at assert (js/util.ts:28:11)
    at createBuilder (js/flatbuffers.ts:24:3)
    at formatError (js/format_error.ts:8:19)
    at evaluate (js/repl.ts:95:30)
    at replLoop (js/repl.ts:145:13)
```
This failing `assert` is due to `gb.inUse`, which means that an error occurred while on the TS side with the global builder still held, that `formatError` for error formatting in REPL would not be able to use this builder (not yet released. This builder is only released upon actually completing a `sendInternal`.)

**Comment by bartlomieju** [comment]
This problem is partially solved after removal of Flatbuffers:
```
> new Worker
error: Uncaught TypeError: Cannot read property 'startsWith' of undefined
► file:///Users/biwanczuk/dev/deno/js/workers.ts:140:19
    at WorkerImpl (file:///Users/biwanczuk/dev/deno/js/workers.ts:140:19)
    at <unknown>:1:1
    at evaluate (file:///Users/biwanczuk/dev/deno/js/repl.ts:86:34)
    at replLoop (file:///Users/biwanczuk/dev/deno/js/repl.ts:176:13)
```
Still error message is a bit cryptic, for comparison error returned in Chrome:
```
VM115:1 Uncaught TypeError: Failed to construct 'Worker': 1 argument required, but only 0 present.
```

**Comment by bartlomieju** [comment]
This issue is no longer relevant as we don't use Flatbuffers anymore
