### ISSUE TITLE
Can't compile IBM/zos-node-accessor

### ISSUE THREAD

**Issue by rupurt** [denoland/deno#20858]
I'm trying to compile a binary while using [IBM/zos-node-accessor](https://github.com/IBM/zos-node-accessor) which I'm adding as a dependency through `esm.sh`. It works fine when using `deno run ...`. The error can be reliably be reproduced every time when compiling on the `main` branch of [https://github.com/rupurt/evac](https://github.com/rupurt/evac).

**Command:**

```shell
RUST_BACKTRACE=full deno compile --allow-env --allow-read --allow-net --lock deno.lock --output ./evac src/main.ts
```
**Stacktrace:**

```shell
Platform: linux x86_64
Version: 1.28.0
Args: ["/home/alex/.asdf/installs/deno/1.28.0/bin/deno", "compile", "--allow-env", "--allow-read", "--allow-net", "--lock", "deno.lock", "--output", "./evac", "src/main.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResolutionError(InvalidSpecifier { error: ImportPrefixMissing("fs", Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("esm.sh")), port: None, path: "/v132/@types/node@18.16.19/fs.d.ts", query: None, fragment: None })), range: Range { specifier: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("esm.sh")), port: None, path: "/v132/@types/node@18.16.19/fs.d.ts", query: None, fragment: None }, start: Position { line: 3975, character: 18 }, end: Position { line: 3975, character: 22 } } })', cli/main.rs:153:17
stack backtrace:
   0:     0x55555849cfcd - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55555849cfcd - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55555849cfcd - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55555849cfcd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5555584c8d7c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x555558494781 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x55555849ed25 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55555849ed25 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55555849ed25 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x55555849ea41 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x55555887460a - deno::setup_panic_hook::{{closure}}::h42b1dedb14ba0532
  11:     0x55555849f3ca - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:702:17
  12:     0x55555849f207 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
  13:     0x55555849d4c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x55555849ef39 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  15:     0x5555584c6163 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  16:     0x5555584c6473 - core::result::unwrap_failed::h42ad8e915aa0a906
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
  17:     0x5555588661ca - deno::compile_command::{{closure}}::h6c611ec09e637212
  18:     0x55555870c790 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdc8bbf4252577f0d
  19:     0x555558877f49 - deno::main::{{closure}}::h2bd64d54d16bc4e2
  20:     0x55555869ea4b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h21bdaf6e87f87ce6
  21:     0x5555584fd6b9 - deno_runtime::tokio_util::run_local::h10ae01c0df024149
  22:     0x5555588748a9 - deno::main::h3257248bed248507
  23:     0x555558532bb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h03d4eef0cef2231b
  24:     0x55555853a079 - std::rt::lang_start::{{closure}}::h8e2a5fdfbbdeb4e5
  25:     0x555558489f3e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  26:     0x555558489f3e - std::panicking::try::do_call::h84ca51609826746f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  27:     0x555558489f3e - std::panicking::try::hd58075e533b8e0cb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  28:     0x555558489f3e - std::panic::catch_unwind::h1ebac24d83cb6ce2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  29:     0x555558489f3e - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  30:     0x555558489f3e - std::panicking::try::do_call::h7630182e534a0a32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  31:     0x555558489f3e - std::panicking::try::h05b6544f0c6331dc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  32:     0x555558489f3e - std::panic::catch_unwind::h77b2ba8fd3309f34
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  33:     0x555558489f3e - std::rt::lang_start_internal::h6612c8a7a6861b8b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  34:     0x55555889d232 - main
  35:     0x7ffff7c29d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  36:     0x7ffff7c29e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  37:     0x555557431029 - _start
  38:                0x0 - <unknown>
```

**Comment by rupurt** [comment]
Upgraded to 1.37 and it's fixed
