### ISSUE TITLE
HTTP_PROXY and HTTPS_PROXY not honored in Windows

### ISSUE THREAD

**Issue by bak-fts** [denoland/deno#20870]
Setting HTTP_PROXY and HTTPS_PROXY in Git Bash like so:
```bash
export https_proxy=http://127.0.0.1:3128
export http_proxy=$https_proxy
export ftp_proxy=$https_proxy
export HTTPS_PROXY=$https_proxy
export HTTP_PROXY=$https_proxy
export FTP_PROXY=$https_proxy
```

And also set HTTP_PROXY and HTTPS_PROXY in "Edit environment variables for your account" dialogue to the same value.

In the Deno repl, env vars are set but not respected:
```deno
> Deno.env.get("HTTPS_PROXY")
"http://127.0.0.1:3128"
> await fetch("https://google.com");
Uncaught TypeError: error sending request for url (https://google.com/): error t
rying to connect: tcp connect error: No connection could be made because the tar
get machine actively refused it. (os error 10061)
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:504:7)
    at async <anonymous>:2:1
Uncaught (in promise) TypeError: error sending request for url (https://google.c
om/): error trying to connect: tcp connect error: No connection could be made be
cause the target machine actively refused it. (os error 10061)
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:504:7)
```

Is there a special process to getting Deno working behind corporate proxy on Windows?

**Comment by bak-fts** [comment]
I failed to apply the Windows environment variables correctly.
