### ISSUE TITLE
Axios config options `timeout` throw error

### ISSUE THREAD

**Issue by drag0n-app** [denoland/deno#20923]
deno version 1.37.2
axios version 1.5.1
macOS 14.0 M1

deno run -A ./test.js
```
import axios from 'npm:axios@1.5.1';

axios.get('https://www.deno.com/', {
    timeout: 1000
}).catch(error => {
    console.log(error.message)
});
```
throw error
```
error: Uncaught TypeError: socket.setTimeout is not a function
    at RedirectableRequest.destroyOnTimeout (file:///Users/xxx/Desktop/test/node_modules/.deno/follow-redirects@1.15.3/node_modules/follow-redirects/index.js:168:12)
    at RedirectableRequest.emit (ext:deno_node/_stream.mjs:1857:11)
    at HttpsClientRequest.eventHandlers.<computed> (file:///Users/xxx/Desktop/test/node_modules/.deno/follow-redirects@1.15.3/node_modules/follow-redirects/index.js:14:24)
    at HttpsClientRequest.emit (ext:deno_node/_stream.mjs:1857:11)
    at node:http:409:12
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:25:11)
    at eventLoopTick (ext:core/01_core.js:180:29)
```

**Comment by MarybethGasman** [comment]
Seems like the ext/node/polyfills/http.ts@FakeSocket class, does not include an implementation for the setTimeout function. Maybe I could possibly fix this issue.

**Comment by JonathonRP** [comment]
Just to document here - 'I get this error 'Uncaught TypeError: socket.setTimeout is not a function' when I run 'deno run -A npm:sanity@latest init --env'?'

**Comment by RoXuS** [comment]
same here
```
Warning: Not implemented: Http2Session.socket
Warning: Not implemented: Http2Session.goaway
```
With npm:firebase-admin/firestore.
