### ISSUE TITLE
[node compatibility] undici as `http socketPath` workaround, now not working at version `5.26.3`, may due to `tls.connect` `highWaterMark`

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#20928]
Background

- Was able to use `npm:undici@5.22.1` as `http socketPath` workaround.

- But now unable to use `npm:undici@5.26.3`  as `http socketPath` workaround.

Reproduce

```ts
import { describe, it } from "https://deno.land/std@0.196.0/testing/bdd.ts";
import {
  fetch as undiciFetch,
  // getGlobalAgent, setGlobalAgent, Agent
// } from "npm:undici@5.22.1";
} from "npm:undici@5.26.3";

describe("reproduce", () => {
  it("reproduce", async () => {
    // const agent = new Agent()
    // setGlobalAgent(agent)
    const resp = await undiciFetch("https://unpkg.com");
    await resp.text();
    // await agent.destroy()
  });
});
```

```txt
error: TypeError: fetch failed
    at fetch (file:///home/vscode/.cache/deno/npm/x-registry-yarnpkg-com/undici/5.26.3/index.js:110:15)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Object.<anonymous> (file:///tmp/x.ts:7:18)
    at async Function.runTest (https://deno.land/std@0.196.0/testing/_test_suite.ts:358:7)
    at async Function.runTest (https://deno.land/std@0.196.0/testing/_test_suite.ts:346:9)
    at async fn (https://deno.land/std@0.196.0/testing/_test_suite.ts:316:13)
Caused by: AssertionError
    at new AssertionError (ext:deno_node/assertion_error.ts:414:11)
    at toNode (node:assert:44:15)
    at assert (node:assert:61:3)
    at new Parser (file:///home/vscode/.cache/deno/npm/x-registry-yarnpkg-com/undici/5.26.3/lib/client.js:568:5)
    at connect (file:///home/vscode/.cache/deno/npm/x-registry-yarnpkg-com/undici/5.26.3/lib/client.js:1269:25)
```

Related

- https://github.com/nodejs/undici/issues/2206

- https://github.com/denoland/deno/issues/17910

**Comment by loynoir** [comment]
`undici/lib/client.js`

```js
class Parser {
  constructor (client, socket, { exports }) {
    assert(Number.isFinite(client[kMaxHeadersSize]) && client[kMaxHeadersSize] > 0)
```

`client[kMaxHeadersSize])`

- node got `16384`

- deno got `undefined`

Seems like `16384` somehow comes from `undici/lib/core/connect.js` within node, but deno does not.

```js
      socket = tls.connect({
        highWaterMark: 16384, // TLS in node can't have bigger HWM anyway...
        ...options,
        servername,
        session,
        localAddress,
        // TODO(HTTP/2): Add support for h2c
        ALPNProtocols: allowH2 ? ['http/1.1', 'h2'] : ['http/1.1'],
        socket: httpSocket, // upgrade socket connection
        port: port || 443,
        host: hostname
      })
```

**Comment by loynoir** [comment]
Close in favor of a cleaner issue.
