### ISSUE TITLE
`InvalidContentType` when trying to write to connection over `connectTls` on port 587

### ISSUE THREAD

**Issue by Unkn0wn0x** [denoland/deno#20951]
If I try to write into a open connection on port `587` via `connectTls`, I'm getting the error:
```
InvalidData: received corrupt message of type InvalidContentType
    at async write (ext:deno_net/01_net.js:32:10)
    at async sendEmail (<anonymous>:11:5)
    at async <anonymous>:17:1 {
  name: "InvalidData"
}
```

This is the code example I used / how the issue can be reproduced:
```
async function sendEmail() {

    const encoder = new TextEncoder();

    try {

        const conn = await Deno.connectTls({
            hostname: "smtp.mydomain.com",
            port: 587
        });

        await conn.write(encoder.encode("EHLO mydomain.com\r\n"));
        conn.close();

    } catch (error) {
        console.error(error);
    }
}

await sendEmail();
```

If I try to start the connection via `connect` and then switch the connection over with `startTls`, I'm getting the same error:
```
InvalidData: received corrupt message of type InvalidContentType
    at async write (ext:deno_net/01_net.js:32:10)
    at async sendEmail (<anonymous>:13:5)
    at async <anonymous>:19:1 {
  name: "InvalidData"
}
```

Code example:
```
async function sendEmail() {

    const encoder = new TextEncoder();

    let conn;
    try {

        conn = await Deno.connect({
            hostname: "smtp.mydomain.com",
            port: 587
        });
        const tlsConn = await Deno.startTls(conn, { hostname: "smtp.mydomain.com" });

        await tlsConn.write(encoder.encode("EHLO mydomain.com\r\n"));

        tlsConn.close();

    } catch (error) {
        console.error(error);
    }
}

await sendEmail();
```

This affects sending emails over a secure connection via Deno. On the other hand, when port `465` on the SMTP server is available, it works without any problems.

If I run `openssl s_client -debug -starttls smtp -crlf smtp.mydomain.com:587` everything seems to work fine.

Any ideas how to fix this bug? It affects the Deno mailing packages like:
* https://github.com/EC-Nordbund/denomailer/
* https://github.com/EC-Nordbund/denomailer/issues/74

Could also be related to:
* https://github.com/denoland/deno/issues/7528
* https://github.com/denoland/deno/issues/6432

Especially:
* https://github.com/denoland/deno/issues/6432#issuecomment-677962754
* https://github.com/rustls/rustls/blob/30f0545477c083209093c0a02d7ae4ad9e06ef13/rustls/src/error.rs

Thanks in advance.

**Comment by hongkongkiwi** [comment]
Just hit this, port 587 on nodemailer using deno fails, but port 465 works fine.

**Comment by bartlomieju** [comment]
I dug into this on current canary (deno 2.8.1+d95ceb5 (canary, release, aarch64-apple-darwin)), and the STARTTLS-on-587 path works correctly — the failures in the original report come from how the connection is upgraded rather than a bug in `connectTls`/`startTls`.

**Why the two examples fail (it's a usage issue):**

Port **587 is STARTTLS** — the connection starts in **plaintext** and is upgraded mid-session. Port **465 is implicit TLS** (TLS from the first byte), which is exactly why 465 worked for you and 587 didn't.

- Example 1 calls `connectTls` directly on 587, so the TLS handshake reads the server's plaintext `220` greeting and rustls correctly reports a non-TLS record: `received corrupt message of type InvalidContentType`.
- Example 2 calls `startTls` immediately, before doing the SMTP dialogue. You must complete `EHLO` -> `STARTTLS` -> read `220` **first**, then upgrade. (That's also why `openssl s_client -starttls smtp` worked — it performs that dialogue before the handshake.)

**The correct sequence works** (verified against both Gmail and Office 365 on 587):

```ts
const enc = new TextEncoder();
const host = "smtp.gmail.com";
const conn = await Deno.connect({ hostname: host, port: 587 });

// plaintext SMTP dialogue first
await readLine(conn);                                   // 220 greeting
await conn.write(enc.encode("EHLO test.local\r\n"));
await readLine(conn);                                   // 250-...
await conn.write(enc.encode("STARTTLS\r\n"));
await readLine(conn);                                   // 220 Ready to start TLS

// now upgrade
const tls = await Deno.startTls(conn, { hostname: host });
await tls.write(enc.encode("EHLO test.local\r\n"));      // works over TLS
```

**On the nodemailer report:** I also tested `nodemailer` (`createTransport({ host, port: 587, secure: false })` + `verify()`) against Gmail on current Deno, and the STARTTLS upgrade succeeds — it no longer hits `InvalidContentType`. So whatever bit the mailing libraries earlier is resolved on current versions. Deno mailers like denomailer/nodemailer perform the plaintext dialogue before upgrading, which is the correct pattern shown above.

Closing as resolved, since the underlying capability works correctly. If anyone still sees `InvalidContentType` against a *specific* SMTP server with a correctly-sequenced STARTTLS (or via an up-to-date nodemailer/denomailer), please open a fresh issue with that server and a minimal repro and we'll take a look.
