### ISSUE TITLE
Bug: Deno compiled app crashes on npm:@fastify/swagger

### ISSUE THREAD

**Issue by Tzahile** [denoland/deno#20950]
Hi,
I created a Deno app, and I'm using `npm:fastify`.
All works well so far, except for one thing;

I added swagger plugin to the server, and when I run `Deno run` it works.
The problem starts when I compile my app, and then try to reach the swagger path (on `http://localhost:8000/docs`):

<img width="1286" alt="image" src="https://github.com/denoland/deno/assets/13683050/4fc0a982-515e-4c6f-8c21-d79a90f28238">

My deps.ts file:
```ts
/**
 * deps.ts
 *
 * This module re-exports the required methods from the dependant remote modules.
 */

import Fastify from "npm:fastify";
import pg from "npm:@fastify/postgres";
import swagger from "npm:@fastify/swagger";
import swaggerUI from "npm:@fastify/swagger-ui";

export { load } from "https://deno.land/std@0.204.0/dotenv/mod.ts";
export { Fastify, pg, swagger, swaggerUI };
```

and my main.ts:
```ts
import { load, Fastify, swagger, swaggerUI, pg } from "./deps.ts";

await load({ export: true });

export const server = Fastify({
  logger: true,
});

// Plugins
server.register(pg, {
  connectionString: `${Deno.env.get("DB_HOST")}://${Deno.env.get("DB_USER")}:${Deno.env.get("DB_PASSWORD")
    }@${Deno.env.get("DB_HOST")}:${Deno.env.get("DB_PORT")}/${Deno.env.get("DB_NAME")
    }`,
});
server.register(swagger, {});
server.register(swaggerUI, {
  routePrefix: "/docs",
});

// Run the app
if (import.meta.main) {
  try {
    await server.listen({ host: '0.0.0.0', port: 8000 });
  } catch (err) {
    server.log.error(err);
    Deno.exit(1);
  }
}
```

I guess this is a problem with the compatibility of Deno and Node, and I'd like to know how can I take care of it.
Thanks in advance!

**Comment by littledivy** [comment]
Closing as this seems to work as expected with latest Deno:

```js
import Fastify from "npm:fastify";
import swagger from "npm:@fastify/swagger";
import swaggerUI from "npm:@fastify/swagger-ui";

export const server = Fastify({
  logger: true,
});

server.register(swagger, {});
server.register(swaggerUI, {
  routePrefix: "/docs",
});

await server.listen({ host: '0.0.0.0', port: 8080 });
```

```
$ deno -V
deno 1.45.4
$ deno run -A server.ts
{"level":30,"time":1722245507067,"pid":84383,"hostname":"divy","msg":"Server listening at http://0.0.0.0:8080"}
{"level":30,"time":1722245508306,"pid":84383,"hostname":"divy","reqId":"req-1","req":{"method":"GET","url":"/","hostname":"localhost:8080","remoteAddress":"127.0.0.1","remotePort":34282},"msg":"incoming request"}
{"level":30,"time":1722245508307,"pid":84383,"hostname":"divy","reqId":"req-1","msg":"Route GET:/ not found"}
{"level":30,"time":1722245508309,"pid":84383,"hostname":"divy","reqId":"req-1","res":{"statusCode":404},"responseTime":2.310178000000178,"msg":"request completed"}
{"level":30,"time":1722245520451,"pid":84383,"hostname":"divy","reqId":"req-2","req":{"method":"GET","url":"/docs","hostname":"localhost:8080","remoteAddress":"127.0.0.1","remotePort":58450},"msg":"incoming request"}
{"level":30,"time":1722245520452,"pid":84383,"hostname":"divy","reqId":"req-2","res":{"statusCode":200},"responseTime":0.3852360000000772,"msg":"request completed"}
```

**Comment by littledivy** [comment]
Oh oops, stills happens with `deno compile`:

```
error: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toUTCString')
    at SendStream.setHeader (file:///tmp/deno-compile-server/node_modules/localhost/@fastify/send/2.1.0/lib/SendStream.js:886:33)
    at SendStream.send (file:///tmp/deno-compile-server/node_modules/localhost/@fastify/send/2.1.0/lib/SendStream.js:623:8)
    at onstat (file:///tmp/deno-compile-server/node_modules/localhost/@fastify/send/2.1.0/lib/SendStream.js:730:10)
    at Deno.stat.then.denoErrorToNodeError.syscall (ext:deno_node/_fs/_fs_stat.ts:149:32)
    at eventLoopTick (ext:core/01_core.js:168:7)
```

**Comment by valVk** [comment]
The same issue for deno 2.0.3

Repository to reproduce with nestjs (express) + swagger

https://github.com/serbanmarti/deno2_nestjs_example

**Comment by angelraymondi** [comment]
Same here 😭

**Comment by angelraymondi** [comment]
This error happens because when you run `fs.stat` inside the compiled binary, Stats.mtime returns null although the file exists and you can read it.

```ts
fs.stat(someFilePath, (err, stats) => {
  console.log(err, stats)
});
```

OUTPUT:
```ts
null Stats {
  dev: 0,
  ino: null,
  mode: 0,
  nlink: null,
  uid: null,
  gid: null,
  rdev: null,
  size: 1,
  blksize: null,
  blocks: null,
  mtime: null,
  atime: null,
  birthtime: null,
  mtimeMs: null,
  atimeMs: null,
  birthtimeMs: null,
  isFile: [Function: isFile],
  isDirectory: [Function: isDirectory],
  isSymbolicLink: [Function: isSymbolicLink],
  isBlockDevice: [Function: isBlockDevice],
  isFIFO: [Function: isFIFO],
  isCharacterDevice: [Function: isCharacterDevice],
  isSocket: [Function: isSocket],
  ctime: null,
  ctimeMs: null
}
```

**Comment by angelraymondi** [comment]
Ok so, I found a workaround to this problem.

[/home/USER/.cache/deno/npm/registry.npmjs.org/send/0.19.0/index.js]
Edit

**Comment by niklaswimmer** [comment]
Experiencing the same problem, also with `express`, trying to serve some static html files.

<details><summary>Output (running with <code>DEBUG='*'</code>)</summary>
<pre>
  express:router dispatching GET /index.html +18s
  express:router query  : /index.html +0ms
  express:router expressInit  : /index.html +1ms
  express:router serveStatic  : /index.html +0ms
  send stat "C:\Users\NIKLAS~1\AppData\Local\Temp\deno-compile-myCompiledProgram.exe\html\index.html" +0ms
  send pipe "C:\Users\NIKLAS~1\AppData\Local\Temp\deno-compile-myCompiledProgram.exe\html\index.html" +3ms
  send accept ranges +0ms
  send cache-control public, max-age=0 +0ms
error: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toUTCString')
    var modified = stat.mtime.toUTCString()
                              ^
    at SendStream.setHeader (file:///C:/Users/NIKLAS~1/AppData/Local/Temp/deno-compile-myCompiledProgram.exe/node_modules/.deno/send@0.19.0/node_modules/send/index.js:873:31)
    at SendStream.send (file:///C:/Users/NIKLAS~1/AppData/Local/Temp/deno-compile-myCompiledProgram.exe/node_modules/.deno/send@0.19.0/node_modules/send/index.js:619:8)
    at onstat (file:///C:/Users/NIKLAS~1/AppData/Local/Temp/deno-compile-myCompiledProgram.exe/node_modules/.deno/send@0.19.0/node_modules/send/index.js:724:10)
    at Deno.stat.then.denoErrorToNodeError.syscall (ext:deno_node/_fs/_fs_stat.ts:151:32)
    at eventLoopTick (ext:core/01_core.js:177:7)
</pre>
</details>

Maybe someone can rename the issue title? This is about stat not working correctly with `deno compile` and not about any specific broken package (I believe).

I have no idea what magic `deno compile` uses, but I will just guess here. I tried finding the path mentioned in the stacktrace (`C:/Users/NIKLAS~1/AppData/Local/Temp/deno-compile-myCompiledProgram.exe/node_modules/.deno/send@0.19.0/node_modules/send/index.js`), but the `deno-compile-myCompiledProgram.exe` folder does not exist, not even while the program is running. So my thinking is that Deno just pretends those files exist and its internal file routines translate any calls to those files to something else. If that is the case, it may just be that `stat` is not yet properly implemented (given how most fields are set to `0` or `null` as per other people's comments).

If all that is correct, may I ask for some pointers on what it would take to actually implement stat properly?

**Comment by niklaswimmer** [comment]
Line 260 forwards stat calls into the virtual file system used by the standalone executable produced by `deno compile`.

https://github.com/denoland/deno/blob/1f6f56197995cd39cae7172b97d0ac4990eb9ee6/cli/rt/file_system.rs#L258-L264

The stats from the virtual file system are converted into actual stats here:

https://github.com/denoland/deno/blob/1f6f56197995cd39cae7172b97d0ac4990eb9ee6/cli/rt/file_system.rs#L1252-L1276

So yeah, `mtime` is `null`, because it is not just not set. For everyone familiar with how `deno compile` works this was probably no new information.

I see two options going forward:
1. retrieve this information during `deno compile` and store it alongside the file content, so that it can be retrieved later. That is the most correct solution, but would result in storing stats for every file in your `node_modules` too, so it may end up adding quite a bit of overhead to the final executable's file size.
2. reuse the stats of the executable itself. Not so correct, but probably also simpler to implement.

There may be other options as well.

Personally, I would consider just not crashing a big step up, so I am in favor of doing number 2. My thinking is that we could stat the executable if the path is from the vfs (using [current_exe](https://doc.rust-lang.org/stable/std/env/fn.current_exe.html) to retrieve its path) and use the information we get from that to enrich the stat information we get from the vfs. Stating the executable could of course be cached, since its information probably does not change during execution?

**Comment by angelraymondi** [comment]
@niklaswimmer Yeah, I also noticed that. I solved it by moving the `public` and `views` folder into another called `src` and excluding it from the compilation. And then I had to create a copy of the `src` folder in the same directory as my compiled binary.

So it went from this:
```
public/
   ...
views/
   ...
main.ts
deno.json
deno.lock
```

To this:
```
src/
   public/
     ...
   views/
     ...
main.ts
deno.json
deno.lock
```

And then this:
```
src/
   public/
     ...
   views/
     ...
app.exe
```

```ts
app.use(express.static("./src/public"));
app.set("views", "./src/views");
```

I solved it this way, and don't know if there is another way to solve it.
Hope someone finds another solution to this.

**Comment by niklaswimmer** [comment]
Hello @angelraymondi, I think this is the only work around right now. In my case, the whole point of using compile would be to avoid having to copy multiple files around so it is basically a non-starter.

I am looking at implementing a fix for this in Deno, but no significant progress yet.

**Comment by niklaswimmer** [comment]
This has been fixed in #28731, they implemented option 1, i.e. the file's `mtime` is read during `deno compile` and then used for all the time fields at runtime.

This issue can be closed.

**Comment by valVk** [comment]
> The same issue for deno 2.0.3
> 
> Repository to reproduce with nestjs (express) + swagger
> 
> https://github.com/serbanmarti/deno2_nestjs_example

deno 2.3.3

Everything works
