### ISSUE TITLE
Bug: `Deno.permissions.querySync is not a function` (Deno Deploy Runtime)

### ISSUE THREAD

**Issue by carere** [denoland/deno#20952]
Everything is in the title, I'm deployed an API, and my database is EdgeDB, when I try to establish a connection with it, Edgedb try to read some env var. Thus, it call `Deno.permissions.querySync`, and I get the error highlighted in the title.
Here is my stack trace for more info.
```
TypeError: Deno.permissions.querySync is not a function
  at getEnv (https://deno.land/x/edgedb@v1.3.0/_src/adapter.shared.deno.ts:36:36)
  at parseConnectDsnAndArgs (https://deno.land/x/edgedb@v1.3.0/_src/conUtils.ts:538:36)
  at eventLoopTick (ext:core/01_core.js:183:11)
  at async ClientPool._parseConnectArguments (https://deno.land/x/edgedb@v1.3.0/_src/conUtils.ts:99:11)
  at async ClientPool.getNewConnection (https://deno.land/x/edgedb@v1.3.0/_src/baseClient.ts:375:20)
  at async ClientConnectionHolder._getConnection (https://deno.land/x/edgedb@v1.3.0/_src/baseClient.ts:62:26)
  at async ClientConnectionHolder.retryingFetch (https://deno.land/x/edgedb@v1.3.0/_src/baseClient.ts:175:20)
  at async Client.querySingle (https://deno.land/x/edgedb@v1.3.0/_src/baseClient.ts:615:14)
  at async Object.getKey (file:///src/shinzo/server/lucia/ashiso.adapter.ts:81:17)
  at async Auth.useKey (file:///node_modules/.deno/lucia@2.7.1/node_modules/lucia/dist/auth/index.js:192:29)
```

It's really annoying, since my API is totally unusable actually...
Is there a way to fix this ? Is this normal ? Should I do something on Deno Deploy ? If yes what ?

Best regards,

**Comment by nhrones** [comment]
I think env vars need to be set manually in Deploy.
https://docs.deno.com/deploy/manual/environment-variables
