### ISSUE TITLE
Bad resource ID when consuming body in Deno.serve in 1.37.0

### ISSUE THREAD

**Issue by florian-imi** [denoland/deno#20971]
Noticing occasional `BadResource: Bad resource ID` when load testing in 1.37.(0|1|2), fixed by downgrading 1.36.4. Seeing about ~10 out of 2000 requests.

Unfortunately I can't provide a minimally reproducible code.

```
BadResource: Bad resource ID
    at readableStreamCollectIntoUint8Array (ext:deno_web/06_streams.js:949:28)
    at InnerBody.consume (ext:deno_fetch/22_body.js:161:14)
    at consumeBody (ext:deno_fetch/22_body.js:240:34)
    at Request.arrayBuffer (ext:deno_fetch/22_body.js:283:16)
    at _Context.arrayBuffer XXX
    at _Context.proxy XXX
    at Object.GetCaptcha XXX
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async XXX
    at async ext:deno_http/00_serve.js:442:22 {
  name: "BadResource"
}
```

**Comment by mmastrac** [comment]
Thanks for the info! Could you describe the hander that is failing? Is it streaming or consuming a fetch request to an external service?

I can try to run some experiments and if you could provide the rough functionality shape of the response handler I can target some testing

**Comment by florian-imi** [comment]
Yes, it is dumping the array buffer. It is not directly used in the response, there's no piping of the streams.

**Comment by mpcref** [comment]
Same issue with v1.38.0. I also can't reliably reproduce this. What I can say is that I never seem to encounter this bug locally but once deployed to fly.io (using the same docker image) I get this error regularly. 

```
BadResource: Bad resource ID
at readableStreamCollectIntoUint8Array (ext:deno_web/06_streams.js:1065:28)
at InnerBody.consume (ext:deno_fetch/22_body.js:161:14)
at consumeBody (ext:deno_fetch/22_body.js:240:34)
at Request.json (ext:deno_fetch/22_body.js:310:16)
```

**Comment by mmastrac** [comment]
This may be fixed by https://github.com/denoland/deno/pull/20217

**Comment by mmastrac** [comment]
@mpcref Could you describe the structure of your response handler? We'd like to narrow down what might be causing this.

**Comment by mpcref** [comment]
I can confirm that downgrading to 1.36.4 seems to have fixed the problem.

These are the relevant parts of the code:

```js
async function getResult(request) {
  const payload = await request.json(); // this line triggers the exception
  return "ok";
}

async function createResponse(request) {
  const result = await getResult(request);
  return new Response(result);
}

Deno.serve(
  {
    port: 8080,
    onListen({ port }) {
      log.info(`Listening on port ${port}`);
    }
  },
  createResponse
);
```

**Comment by mmastrac** [comment]
@mpcref Ahh, thanks! It looks like we may be disposing of the request body too quickly. I'll see if we can get a reliable test.

**Comment by mpcref** [comment]
always think twice when disposing of a body. 😉

**Comment by mpcref** [comment]
I can't reliably reproduce the issue either and it only occurs on my production environment. If you could give me some more context about the error (what does "Bad resource ID" even mean?) I might be able to help.

**Comment by e271828-** [comment]
@mmastrac what is the status on this?

**Comment by mmastrac** [comment]
Unfortunately we've been unable to reproduce this, but if there's any way we could get a minimal reproducer it would really help.

"Bad Resource ID" often means something is getting closed too early, but as the resources are generally managed by fetch itself, it suggests some sort of interaction with the server causing the resource to get closed too early, or that one of our APIs is being used in a way that it gives a poor error message.

**Comment by florian-imi** [comment]
I've tried reproducing it with my original setup using 1.40.5 and can no longer reproduce it. fwiw, I could only reproduce it once using 1.37.2 either -- not as predictable as when I originally filed this. Gonna close this for now.
