### ISSUE TITLE
Node test `process.stdin readable with a TTY` fails on OSX

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno#21112]
Repro:

`cargo run -- test -A '/Users/matt/Documents/github/deno/deno/cli/tests/unit_node/process_test.ts' --filter TTY`

```
FAILED | 0 passed | 2 failed | 45 filtered out (4ms)

error: Uncaught BadResource: Bad resource ID
    at Stdin.close (ext:deno_io/12_io.js:244:10)
    at ReadStream.<anonymous> (ext:deno_node/_process/streams.mjs:177:37)
    at ReadStream.emit (ext:deno_node/_stream.mjs:1852:9)
    at node:net:878:14
    at ext:core/01_core.js:677:9
    at Object.runMicrotasks (ext:core/01_core.js:857:30)
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at eventLoopTick (ext:core/01_core.js:180:29)
```

**Comment by mmastrac** [comment]
Looks like it was fallout from #21026 @littledivy 

`git bisect` says:

```
f62e22a6998bc4d0e2b2fc3df8d6a81aac264e7a is the first bad commit
commit f62e22a6998bc4d0e2b2fc3df8d6a81aac264e7a
Author: Divy Srivastava <dj.srivastava23@gmail.com>
Date:   Tue Oct 31 04:54:43 2023 -0700

    fix(ext/node): tty streams extends net socket (#21026)
    
    Workaround the circular references issue by using a initializer function
    to give tty stream class to `initStdin`.
```

**Comment by jirutka** [comment]
This test fails even on Alpine Linux.
