### ISSUE TITLE
Uncaught Error: Error loading package.json at /Users/xxx/node_modules/.deno/

### ISSUE THREAD

**Issue by diqye** [denoland/deno#21126]
```
~/p/denotest>deno --version                                                                                           4.786s 12:25
deno 1.32.3 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
```

test.hs
```typescript
import cos from "npm:tencentcloud-sdk-nodejs@4.0.727"
console.log(cos)
```
and then run 
```bash
deno run -A test.hs
```
resulting
```
error: Uncaught Error: Error loading package.json at /Users/xxx/node_modules/.deno/json-bigint@1.0.0/node_modules/bignumber.js/bignumber.js/package.json. Not a directory (os error 20)
    at resolveExports (ext:deno_node/01_require.js:510:14)
    at Function.Module._findPath (ext:deno_node/01_require.js:549:31)
```

**Comment by diqye** [comment]
Be resolved while i `deno upgrade`
```
diqye@bogon denotest % deno --version
deno 1.38.0 (release, aarch64-apple-darwin)
v8 12.0.267.1
typescript 5.2.2
```

**Comment by dsherret** [comment]
Yeah, that's a super old version of Deno. The npm support has come a long way since then.
