### ISSUE TITLE
The Deno.serve() exception under root user with fetch()

### ISSUE THREAD

**Issue by drag0n-app** [denoland/deno#21231]
Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-87-generic x86_64)

1. run server.ts with root user:
```ts
Deno.serve({port:1000}, () => {
  return new Response("Hello World")
})
```

2. run fetch.ts with root user: **fetch with local ip address**
```ts
for (let i = 0; i < 100; i++) {
  const res = await fetch('http://127.0.0.1:1000/')
  console.log(res.headers)
  const text = await res.text()
  console.log(i, text)
}
```
response with wrong content length, and body content is null:
```
Headers {
  connection: "close",
  "content-length": "0",
  "proxy-connection": "close"
}
0
...
```

3. run fetch.ts with root user: **fetch with LAN ip address**
```ts
for (let i = 0; i < 100; i++) {
  const res = await fetch('http://192.168.100.12:1000/')
  console.log(res.headers)
  const text = await res.text()
  console.log(i, text)
}
```
response with exception: **connection closed before message completed**
```ts
Headers {
  connection: "keep-alive",
  "content-length": "11",
  "content-type": "text/plain;charset=UTF-8",
  date: "Fri, 17 Nov 2023 03:41:02 GMT",
  "keep-alive": "timeout=4",
  "proxy-connection": "keep-alive",
  vary: "Accept-Encoding"
}
0 Hello World
Headers {
  connection: "keep-alive",
  "content-length": "11",
  "content-type": "text/plain;charset=UTF-8",
  date: "Fri, 17 Nov 2023 03:41:02 GMT",
  "keep-alive": "timeout=4",
  "proxy-connection": "keep-alive",
  vary: "Accept-Encoding"
}
1 Hello World
error: Uncaught (in promise) TypeError: error sending request for url (http://192.168.100.12:1000/): connection closed before message completed
  const res = await fetch('http://192.168.100.12:1000/')
              ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:504:7)
    at async file:///home/test/fetch.ts:9:15
...
```
4. **but run fetch.ts with not root user everything is OK!** 
What's wrong with me? Or is there something wrong with deno?

**Comment by mmastrac** [comment]
If you use curl as root against a server running as root do you get the same behaviour?

**Comment by codesculpture** [comment]
Working Fine in Windows, Not Reproducable

**Comment by mmastrac** [comment]
Thanks for the follow-up report! Let us know if you run into any further problems.
