### ISSUE TITLE
deno vite 5 uncaught typeerror cannot read properties of undefined (reading getReport)

### ISSUE THREAD

**Issue by JonathonRP** [denoland/deno#21304]
Vite 5 report module doesn't exist in 'node:process'

**Comment by kt3k** [comment]
What commands did you try to get the above error?

**Comment by hermann-p** [comment]
Same here. Follow the [Deno-React tutorial](https://docs.deno.com/runtime/tutorials/how_to_with_npm/react) by running `deno run `-A npm:create-vite-extra` and finishing the wizard (I tried deno-react with typescript and with typescript-swc). Then enter the created project folder and execute `deno task dev` or `deno task build`.

<details>
<summary>The exact error message</summary>

```
deno task dev
Task dev deno run -A --unstable --node-modules-dir npm:vite
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getReport')
    at isMusl (file:///[..]/vite-project/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:5:30)
    at getPackageBase (file:///[..]/vite-project/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:53:28)
    at Object.<anonymous> (file:///[..]/vite-project/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:28:21)
    at Object.<anonymous> (file:///[..]/vite-project/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:81:4)
    at Module._compile (node:module:733:34)
    at Object.Module._extensions..js (node:module:747:10)
    at Module.load (node:module:658:32)
    at Function.Module._load (node:module:539:12)
    at Module.require (node:module:677:19)
    at require (node:module:791:16)
```
</details>

**Comment by JonathonRP** [comment]
Mine is with sveltekit but the same command of running 'deno task dev' - 'vite dev' and same error

**Comment by kt3k** [comment]
@hermann-p @JonathonRP Can you upgrade deno to the latest by the command `deno upgrade`, and try it again? I saw (a bit different) error with Deno 1.37.1, but it worked without error with 1.37.2 or above (with `deno-react` and `TS + SWC` selected)

Also please try remove local `node_modules` if they exist.

**Comment by JonathonRP** [comment]
I have been using Deno 1.37.2 but I can try 1.37.3

**Comment by Danielduel** [comment]
Merged, latest main should be fixed.

**Comment by Danielduel** [comment]
@JonathonRP it is not part of 1.38.5, could you check the canary build? `deno upgrade --canary`

**Comment by JonathonRP** [comment]
> @JonathonRP it is not part of 1.38.5, could you check the canary build? `deno upgrade --canary`

Oh okay, let me check tomorrow and update 👍

**Comment by lukvxx** [comment]
@Danielduel @kt3k  it seems like the same error is happening on deno deploy

![image](https://github.com/denoland/deno/assets/44476930/123c33e1-17fc-4b57-a978-68a82a96918e)

To reproduce it run `deno run -A npm:create-vite-extra ` and deploy it. The local build is working fine for me, building it over a github action also works just deploying it throws this `getReport()` error.
Do you by any chance know who I can contact?

**Comment by Danielduel** [comment]
Afaik Deno deploy doesn't run canary builds.
You can ask on deno's discord.
Btw - why do you want to run vite on deno deploy?

**Comment by lukvxx** [comment]
I wanted to deploy a vue app

**Comment by cknight** [comment]
Deploy is a custom separate runtime with changes from Deno brought over to Deploy.  I believe there's generally a few week lag time for those changes to make it into Deploy, though likely longer at the moment with the holidays.

**Comment by lukvxx** [comment]
Thanks a lot & happy holidays 🎄
