### ISSUE TITLE
Deno panic: HTTP state error: Expected to be last strong reference

### ISSUE THREAD

**Issue by jtoppine** [denoland/deno#21309]
Reporting this because the message asks me to. 

Will report back if I get more info or a reliable reproduction. 

Testing on my own code (a web app), this currently happens with ~20-30% likelyhood on manual testing (ie. start server, navigate to a page, navigate to another page - boom).  So it's not like a long running process, under heavy load, or anything.

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.
Platform: linux x86_64
Version: 1.38.2
Args: ["/home/jtoppine/.deno/bin/deno", "run", "--unstable", "--no-prompt", "--quiet", "--allow-all", "--allow-hrtime", "--allow-net", "--allow-read", "/tmp/sm-dev-kitchensink/keepers-tmp/subprocess-service-3a7869109b9e210fa57da176621cb4eb.js"]
thread 'main' panicked at ext/http/service.rs:255:5:
HTTP state error: Expected to be last strong reference
stack backtrace:
   0:     0x561c0c9d902c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x561c0c9d902c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561c0c9d902c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x561c0c9d902c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x561c0ca0e1ec - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x561c0ca0e1ec - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x561c0c9d203e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x561c0c9d8e14 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x561c0c9d8e14 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x561c0c9dac13 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x561c0c9da92c - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x561c0ce58e7b - deno::setup_panic_hook::{{closure}}::h82143ceff14613d5
  12:     0x561c0c9db37e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h05249de742e1768e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2021:9
  13:     0x561c0c9db37e - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:711:13
  14:     0x561c0c9db0c1 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13
  15:     0x561c0c9d9556 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x561c0c9dae52 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  17:     0x561c0ca0b213 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  18:     0x561c0db0a8ac - deno_http::service::HttpRecord::recycle::h8ef4d604b04a3b33
  19:     0x561c0daf758f - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h7c01ae34ad81fe60
  20:     0x561c0db22da6 - deno_http::http_next::op_http_set_response_body_resource::v8_fn_ptr::h0db62f232947d412
  21:     0x561c0c7eb95d - Builtins_CallApiCallbackGeneric

```

**Comment by bartlomieju** [comment]
Thanks for the report. Already fixed in https://github.com/denoland/deno/pull/21252, will be released in v1.38.3 tonight.
