### ISSUE TITLE
Error thrown within a microtask swallows any error previously thrown in a macrotask during the current eventloop tick

### ISSUE THREAD

**Issue by arnauorriols** [denoland/deno#21324]
```js
function test() {
  queueMicrotask(() => {throw new Error("microtask error");});
  throw new Error("macrotask error");
}
```

### Deno
```bash
$ deno run /tmp/test.js 
error: Uncaught Error: microtask error
  queueMicrotask(() => {throw new Error("microtask error");});
                              ^
    at file:///tmp/test.js:2:31
    at ext:core/01_core.js:608:9
```

### Firefox
![image](https://github.com/denoland/deno/assets/4871949/c79c97cd-7d58-4cf3-8799-516f2ddf1d92)

### Bun
```bash
$ bun /tmp/test.js 
1 | function test() {
2 |   queueMicrotask(() => {throw new Error("microtask error");});
                                  ^
error: microtask error
      at /private/tmp/test.js:2:30
1 | function test() {
2 |   queueMicrotask(() => {throw new Error("microtask error");});
3 |   throw new Error("main task error");
            ^
error: main task error
      at test (/private/tmp/test.js:3:8)
      at /private/tmp/test.js:6:0
```

##

**Comment by mmastrac** [comment]
Thanks for the concise repro. I'll take a look at this in deno_core.
