### ISSUE TITLE
ReadableStream Transferable fail

### ISSUE THREAD

**Issue by xuybin** [denoland/deno#21344]
stream.mjs
```
import { ReadableStream } from "node:stream/web";

async function* asyncIterableGenerator() {
  yield "a";
  yield "b";
  yield "c";
}

(async () => {
  const stream = ReadableStream.from(asyncIterableGenerator());

  const { port1, port2 } = new MessageChannel();

  port1.onmessage = ({ data }) => {
    data.getReader().read().then((chunk) => {
      console.log(chunk);
    });
  };

  port2.postMessage(stream, [stream]);
})();
``` 
D:\deno -V
deno 1.38.3

D:\deno run -A stream.mjs
error: Uncaught (in promise) DataCloneError: Value not transferable
  port2.postMessage(stream, [stream]);
        ^
    at serializeJsMessageData (ext:deno_web/13_message_port.js:341:13)
    at MessagePort.postMessage (ext:deno_web/13_message_port.js:138:18)
    at file:///D:/stream.mjs:20:9
    at file:///D:/stream.mjs:21:3

**Comment by crowlKats** [comment]
Duplicate of #21344

**Comment by bartlomieju** [comment]
@crowlKats you linked this issue here. Seems like a mistake.
