### ISSUE TITLE
Deno panics on N-API threadsafe function

### ISSUE THREAD

**Issue by ben-laird** [denoland/deno#21376]
Hello,

I'm working on a project with Deno and Prisma as well as some home-brewed resource management logic, and I ran into this error. The error resolved when I cleared out the database and retried upserting the test records. I don't have a reproducible GitHub repo yet, as the project is very new and volatile; in the meantime, hopefully the info below will help. It's likely an issue with my own code or database, but just thought I'd submit this issue to be sure.

<details>
<summary>`deno.json`</summary>

```json
{
  "nodeModulesDir": true,
  "tasks": {
    "start": "deno run -A --env=experiments/weaviate/.env experiments/weaviate/bin.ts"
  },
  "imports": {
    "ex/": "./experiments/",
    "lib/": "./lib/"
  }
}
```
</details>

<details>
<summary>
Running `deno run -A prisma/seed.ts` multiple times, using `Promise.all()` form (throws or panics):
</summary>

```sh
$ RUST_BACKTRACE=1 deno run -A prisma/seed.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.38.3
Args: ["deno", "run", "-A", "prisma/seed.ts"]

thread '<unnamed>' panicked at cli/napi/threadsafe_functions.rs:113:40:
called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
   4: _napi_call_threadsafe_function
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: _napi_register_module_v1
   9: _napi_register_module_v1
  10: _napi_register_module_v1
  11: _napi_register_module_v1
  12: _napi_register_module_v1
  13: _napi_register_module_v1
  14: __pthread_joiner_wake
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```sh
$ RUST_BACKTRACE=1 deno run -A prisma/seed.ts
error: Uncaught PrismaClientUnknownRequestError: 
Invalid `prisma.user.upsert()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RecordDoesNotExist, transient: false })
    at ni.handleRequestError (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:124:6989)
    at ni.handleAndLogRequestError (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:124:6206)
    at ni.request (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:124:5926)
    at async l (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:129:10023)
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/experiments/prisma/prisma/seed.ts:24:12
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/resource.ts:79:41
    at async Promise.all (index 1)
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/resource.ts:78:17
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/resource.ts:70:16
    at async deferBlock (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/deferrable.ts:68:15)

$ RUST_BACKTRACE=1 deno run -A prisma/seed.ts
error: Uncaught PrismaClientUnknownRequestError: 
Invalid `prisma.user.upsert()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RecordDoesNotExist, transient: false })
    at ni.handleRequestError (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:124:6989)
    at ni.handleAndLogRequestError (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:124:6206)
    at ni.request (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:124:5926)
    at async l (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:129:10023)
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/experiments/prisma/prisma/seed.ts:24:12
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/resource.ts:79:41
    at async Promise.all (index 1)
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/resource.ts:78:17
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/resource.ts:70:16
    at async deferBlock (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/deferrable.ts:68:15)
```

```sh
$ deno run -A prisma/seed.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.38.3
Args: ["deno", "run", "-A", "prisma/seed.ts"]

thread '<unnamed>' panicked at cli/napi/threadsafe_functions.rs:113:40:
called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
</details>

<details>
<summary>
Running `deno run -A prisma/seed.ts` once, using `Promise.allSettled()` form (does not throw/panic):
</summary>

```sh
[
  { status: "fulfilled", value: { id: 0, name: "Jenny" } },
  {
    status: "rejected",
    reason: PrismaClientUnknownRequestError: 
Invalid `prisma.user.upsert()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RecordDoesNotExist, transient: false })
    at ni.handleRequestError (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:124:6989)
    at ni.handleAndLogRequestError (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:124:6206)
    at ni.request (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:124:5926)
    at async l (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/node_modules/.deno/@prisma+client@5.6.0/node_modules/@prisma/client/runtime/library.js:129:10023)
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/experiments/prisma/prisma/seed.ts:24:12
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/resource.ts:89:41
    at async Function.allSettled (<anonymous>)
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/resource.ts:88:17
    at async file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/resource.ts:70:16
    at async deferBlock (file:///Users/benlaird/Desktop/Life/Projects/Wonder-Guard/lib/resource/deferrable.ts:68:15) {
      name: "PrismaClientUnknownRequestError",
      clientVersion: "5.6.0"
    }
  },
  { status: "fulfilled", value: { id: 2, name: "Jordan" } },
  { status: "fulfilled", value: { id: 3, name: "Reuben" } }
]
```
</details>

Thanks so much for your help!

EDIT: [minimal reproduction repo](https://github.com/bug-squashing/denoland-deno-21376/tree/issue) set up!

**Comment by devsnek** [comment]
Prisma should be working as of https://github.com/denoland/deno/pull/24101. Let us know if you run into any other issues.
