### ISSUE TITLE
Compatibility node-firebird

### ISSUE THREAD

**Issue by paulhendrix** [denoland/deno#21419]
Version: Deno 1.38.3

Package: `npm: node-firebird`

```ts
import * as fb from "npm:node-firebird";

let options = {};
options.host = "localhost";
options.port = 3050;
options.database = "test1";
options.user = "SYSDBA";
options.password = "masterkey";

fb.attach(options, function (err, db) {
  console.log("debug1");
});
```

callback is never called, under node.js works ok

**Comment by paulhendrix** [comment]
I managed to trace the internal error that occurs, and the cause is a missing function 'removeAllListeners'. 
Now, how can we fix it?

TypeError: cb.response.removeAllListeners is not a function
    at exports.Connection.Connection.attach (file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:3687:21)
    at file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:1757:25
    at cb (file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:3615:13)
    at doCallback (file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:1368:5)
    at file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:3140:21
    at decodeResponse (file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:3419:24)
    at Socket.<anonymous> (file:///test/firebird/problem_deno/node_modules/.deno/node-firebird@1.1.8/node_modules/node-firebird/lib/index.js:3115:13)
    at Socket.emit (ext:deno_node/_stream.mjs:1851:9)
    at addChunk (ext:deno_node/_stream.mjs:2873:16)
    at readableAddChunk (ext:deno_node/_stream.mjs:2852:13) {stack: 'TypeError: cb.response.removeAllListeners is …eAddChunk (ext:deno_node/_stream.mjs:2852:13)', message: 'cb.response.removeAllListeners is not a function', __callSiteEvals: Array(10)}

**Comment by bartlomieju** [comment]
@paulhendrix thanks for opening the issue and sorry for a slow response. Do you still experience this problem using Deno v1.44.x?

**Comment by bartlomieju** [comment]
Closing this for now, due to lack of response. Please reopen if the problem perists.

**Comment by awunnenb** [comment]
the attachment works but if i start db.query nothing happens. No error message, no result.
