### ISSUE TITLE
Reading from Deno.stdin prevent Exception being thrown

### ISSUE THREAD

**Issue by terrywh** [denoland/deno#21420]
Version: Deno 1.38.4
Reading from stdin prevents Exception being thrown;

``` js
setTimeout(() => {
    throw new Error("this will not fire!")
}, 100);
const buffer = new Uint8Array(1024);
await Deno.stdin.read(buffer);
```

**Comment by bartlomieju** [comment]
Works fine in Deno v2.x

```
deno run main.ts
error: Uncaught Error: this will not fire!
    throw new Error("this will not fire!")
          ^
    at file:///Users/ib/dev/try_primate/app/main.ts:2:11
    at callback (ext:deno_web/02_timers.js:58:7)
    at eventLoopTick (ext:core/01_core.js:212:1
```
