### ISSUE TITLE
Relative import path not prefixed when importing unrar

### ISSUE THREAD

**Issue by arthurwolf** [denoland/deno#21440]
Version: latest

After a full day banging my head against walls trying to get ESM to work and failing, somebody recommended I try deno.

I just tried, and it does this:

```
run --check backend/index.ts
error: Relative import path "unrar" not prefixed with / or ./ or ../
    at file:///home/arthur/dev/ai/manga/ui/backend/index.ts:17:34
```

which is weird that it would fail like this, thinking unrar is a relative import when it seemingly had no problem with the 10 other modules before that:

```
import express from 'express';
import multer from 'multer';
import cors from 'cors';
import fs from 'fs';
import {fileTypeFromBuffer} from 'file-type';
import {readChunk} from 'read-chunk';
import path from 'path';
import {glob} from 'glob';
// Database.
import sequelize from '../../src/db/database';
import Book from '../../src/db/book';
import Page from '../../src/db/page';

// Zip and rar stuff.
import unzipper from 'unzipper';
import tar from 'tar';
import { Extract as Unrar } from 'unrar';

console.log("z");
```

what's going on here?

thanks

**Comment by bartlomieju** [comment]
> not sure what a mao file is (and Google wasn't very helpful about that)

I meant "import map" :)

**Comment by codingiswhyicry** [comment]
Experiencing this after an upgrade to deno 1.39.1, which no longer has support for import maps (I think). Error started occurring after changing from import maps -> content in root level deno.json file.

**Comment by dsherret** [comment]
Sorry, I closed the wrong issue.

**Comment by dsherret** [comment]
@codingiswhyicry see issue https://github.com/denoland/deno/issues/23057 for that one, which is unrelated to this (it's fixed now)

**Comment by codingiswhyicry** [comment]
Thanks so much :-)

**Comment by dsherret** [comment]
@arthurwolf I tried running that code sample and there's a lot of missing dependencies not defined in the package.json like cors, multer, express. When I try to run:

```ts
import { Extract as Unrar } from 'unrar';
console.log("z");
```

With a package.json like:

```json
{
  "dependencies": {
    "unrar": "^0.2.0"
  }
}
```

I get:

```
error: Uncaught SyntaxError: The requested module 'unrar' does not provide an export named 'Extract'
import { Extract as Unrar } from 'unrar';
         ^
```

Looking at that package, it doesn't seem to provide an `Extract` export. Would you be able to provide a fully reproducible example of the error you're encoutering?

**Comment by Jamesernator** [comment]
I am getting this also when importing in the REPL, the cause is importing a node-style module from outside of it's package, i.e. if we have:

```
base/
  example-package/
     node_modules/
     package.json
     example.js
```

If while in `base/` we import from that package in the repl I get the error:

```
% deno
Deno 1.43.5
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> await import("./example-package/example.js")
Uncaught TypeError: Relative import path "glob" not prefixed with / or ./ or ../
    at file:///home/jamesernator/projects/example-package/example.js:1:22
    at async <anonymous>:1:22
```

**Comment by MrMarble** [comment]
I'm also facing this issue using deno workspaces with deno 2.0
My package was running fine on its own, but after moving it to a workspace I can't run any task as all fail with the same error

#### root deno.json
```json
{
  "lock": true,
  "workspace": [
    "packages/www"
  ],
  "compilerOptions": { "jsx": "react-jsx", "jsxImportSource": "preact" },
  "nodeModulesDir": "auto"
```

#### www deno.json
```json
{
  "tasks": {
    "check": "deno fmt --check && deno lint && deno check **/*.ts && deno check **/*.tsx",
    "cli": "echo \"import '\\$fresh/src/dev/cli.ts'\" | deno run --unstable -A -",
    "manifest": "deno task cli manifest $(pwd)",
    "start": "deno run -A --watch=static/,routes/ dev.ts",
    "build": "deno run -A dev.ts build",
    "preview": "deno run -A main.ts",
    "update": "deno run -A -r https://fresh.deno.dev/update ."
  },
  "lint": { "rules": { "tags": ["fresh", "recommended"] } },
  "exclude": ["**/_fresh/*"],
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.7.2/",
    "$std/": "https://deno.land/std@0.216.0/",
    "@neondatabase/serverless": "npm:@neondatabase/serverless@^0.9.5",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.2.2",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.5.1",
    "drizzle-orm": "npm:drizzle-orm@^0.33.0",
    "postgres": "npm:postgres@^3.4.4",
    "preact": "https://esm.sh/preact@10.22.0",
    "preact/": "https://esm.sh/preact@10.22.0/",
    "react-masonry-component": "https://esm.sh/react-masonry-component@6.3.0",
    "tailwindcss": "npm:tailwindcss@3.4.1",
    "tailwindcss/": "npm:/tailwindcss@3.4.1/",
    "tailwindcss/plugin": "npm:/tailwindcss@3.4.1/plugin.js"
  }
}
```

running `deno install` creates the `node_modules` folder and the `deno.lock` file but trying to run any of the task defined on `packages/www/deno.json` will fail

```shell
$ cd ./packages/www/
$ deno task build   
Task build deno run -A dev.ts build
error: Relative import path "preact" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs"
    at https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:46
```

**Comment by dsherret** [comment]
@MrMarble in workspaces the imports are scoped to the current package. The https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs module uses a `"preact"` bare specifier. You might need to move the preact import up to the root of the workspace so that it applies everywhere:

```json
{
  "lock": true,
  "workspace": [
    "packages/www"
  ],
  "compilerOptions": { "jsx": "react-jsx", "jsxImportSource": "preact" },
  "nodeModulesDir": "auto",
  "imports": {
    "preact": "https://esm.sh/preact@10.22.0",
    "preact/": "https://esm.sh/preact@10.22.0/"
  }
}
```

**Comment by MrMarble** [comment]
@dsherret I moved the `preact` imports and after that I got similar errors with other packages so I just moved them but now I'm getting some obscure error I don't fully understand

#### root deno.json
```json
{
  "lock": true,
  "workspace": [
    "packages/www"
  ],
  "imports": {
    "preact": "https://esm.sh/preact@10.22.0",
    "preact/": "https://esm.sh/preact@10.22.0/",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.5.1",
    "tailwindcss": "npm:tailwindcss@3.4.1",
    "tailwindcss/": "npm:/tailwindcss@3.4.1/",
    "tailwindcss/plugin": "npm:/tailwindcss@3.4.1/plugin.js"
  },
  "compilerOptions": { "jsx": "react-jsx", "jsxImportSource": "preact" },
  "nodeModulesDir": "auto"
}
```

#### www deno.json
```json
{
  "tasks": {
    "check": "deno fmt --check && deno lint && deno check **/*.ts && deno check **/*.tsx",
    "cli": "echo \"import '\\$fresh/src/dev/cli.ts'\" | deno run --unstable -A -",
    "manifest": "deno task cli manifest $(pwd)",
    "start": "deno run -A --watch=static/,routes/ dev.ts",
    "build": "deno run -A dev.ts build",
    "preview": "deno run -A main.ts",
    "update": "deno run -A -r https://fresh.deno.dev/update ."
  },
  "lint": { "rules": { "tags": ["fresh", "recommended"] } },
  "exclude": ["**/_fresh/*"],
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.7.2/",
    "$std/": "https://deno.land/std@0.216.0/",
    "@neondatabase/serverless": "npm:@neondatabase/serverless@^0.9.5",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.2.2",
    "drizzle-orm": "npm:drizzle-orm@^0.33.0",
    "postgres": "npm:postgres@^3.4.4",
    "react-masonry-component": "https://esm.sh/react-masonry-component@6.3.0"
  },
}
```

```shell
$ cd ./packages/www
$ deno task build
Task build deno run -A dev.ts build
The manifest has been generated for 9 routes and 3 islands.
X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    islands/Filters.tsx:1:33:
      1 │ import { useRef, useState } from "preact/hooks";
        ╵                                  ~~~~~~~~~~~~~~

X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    https://deno.land/x/fresh@1.7.2/src/runtime/entrypoints/main.ts:13:7:
      13 │ } from "preact";
         ╵        ~~~~~~~~

X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    islands/Load.tsx:3:34:
      3 │ import { useEffect, useRef } from "preact/hooks";
        ╵                                   ~~~~~~~~~~~~~~

X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    https://esm.sh/v135/@preact/signals@1.2.2/X-ZS8q/denonext/signals.mjs:2:59:
      2 │ import{Component as y,options as v,isValidElement as S}from"preact";import{useMemo as c,useRef as h,useEffect as k}from"preact/hooks";import{Signal as m,computed a... 
        ╵                                                            ~~~~~~~~

X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    https://esm.sh/v135/@preact/signals@1.2.2/X-ZS8q/denonext/signals.mjs:2:119:
      2 │ ...ent as S}from"preact";import{useMemo as c,useRef as h,useEffect as k}from"preact/hooks";import{Signal as m,computed as b,signal as g,effect as p}from"@preact/si... 
        ╵                                                                             ~~~~~~~~~~~~~~

X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    https://esm.sh/v135/@preact/signals@1.2.2/X-ZS8q/denonext/signals.mjs:2:195:
      2 │ .../hooks";import{Signal as m,computed as b,signal as g,effect as p}from"@preact/signals-core";import{Signal as M,batch as N,computed as O,effect as P,signal as R,... 
        ╵                                                                         ~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    https://deno.land/x/fresh@1.7.2/src/runtime/head.ts:1:49:
      1 │ import { ComponentChildren, createContext } from "preact";
        ╵                                                  ~~~~~~~~

X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    https://deno.land/x/fresh@1.7.2/src/runtime/csp.ts:1:30:
      1 │ import { createContext } from "preact";
        ╵                               ~~~~~~~~

X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    https://deno.land/x/fresh@1.7.2/src/runtime/head.ts:2:27:
      2 │ import { useContext } from "preact/hooks";
        ╵                            ~~~~~~~~~~~~~~

X [ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

    https://deno.land/x/fresh@1.7.2/src/runtime/csp.ts:2:27:
      2 │ import { useContext } from "preact/hooks";
        ╵                            ~~~~~~~~~~~~~~

error: Uncaught (in promise) Error: Build failed with 10 errors:
https://deno.land/x/fresh@1.7.2/src/runtime/csp.ts:1:30: ERROR: [plugin: deno-resolver] specifier was a bare specifier, but was not remapped to anything by importMap.
https://deno.land/x/fresh@1.7.2/src/runtime/csp.ts:2:27: ERROR: [plugin: deno-resolver] specifier was a bare specifier, but was not remapped to anything by importMap.
https://deno.land/x/fresh@1.7.2/src/runtime/entrypoints/main.ts:13:7: ERROR: [plugin: deno-resolver] specifier was a bare specifier, but was not remapped to anything by importMap.
https://deno.land/x/fresh@1.7.2/src/runtime/head.ts:1:49: ERROR: [plugin: deno-resolver] specifier was a bare specifier, but was not remapped to anything by importMap.
https://deno.land/x/fresh@1.7.2/src/runtime/head.ts:2:27: ERROR: [plugin: deno-resolver] specifier was a bare specifier, but was not remapped to anything by importMap.
...
  let error = new Error(text);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.20.2/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1034:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.20.2/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.20.2/mod.js:1032:7)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1061:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.20.2/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.20.2/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.20.2/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.20.2/mod.js:1974:11
    at eventLoopTick (ext:core/01_core.js:175:7)
```

what do I need to change now?

**Comment by dsherret** [comment]
@MrMarble workspaces aren't supported in fresh yet (in this case, you may be able to work around it by duplicating the preact imports in both the workspace and workspace member). Follow https://github.com/lucacasonato/esbuild_deno_loader/pull/145 for updates and also look out for a fresh release that supports workspaces.

**Comment by AndryHTC** [comment]
I could never use the `deno.json` file to set the import map, 1.x nor 2.x.

Tried again now to deploy Supabase Functions and only works if I put the imports into a file named `import_map.json`

**Comment by marvinhagemeister** [comment]
@MrMarble Does updating Fresh to 1.7.3 help? We landed some improvements to the esbuild deno loader.

**Comment by MrMarble** [comment]
@marvinhagemeister I can confirm that with the same setup described avobe, running `deno task build` on my fresh package does work on 1.7.3

**Comment by wesbos** [comment]
Also hitting this trying to run a start script that imports an app from the parent. I'm just trying to run an existing node app to see how Deno 2.0.2 handles it.

`app.ts in root dir` contains the app

`bin/start.ts` starts the app and looks like this:

```ts
import app from '../app.ts'
```

`deno run ./bin/start.ts` from the root dir gives the error:

```
error: Relative import path "path" not prefixed with / or ./ or ../
  hint: If you want to use a built-in Node module, add a "node:" prefix (ex. "node:path").
```

Funny enough, if I change the import from `../app.ts` to `./app.ts`, the it finds the file - but that in incorrect.

Node runs it fine.

So there is some difference between where the app file is located and the directory you run it from? 

I should probably just move my start file out of that sub-folder, but I thought I'd log the issue as it was a very common express.js pattern a while back and others may hit this.

**Comment by dsherret** [comment]
@wesbos it looks like Deno isn't surfacing where the error comes from for some reason, which is a bug (it should say `at <url-goes-here>:<location>` in the message).

> hint: If you want to use a built-in Node module, add a "node:" prefix (ex. "node:path").

Probably running with `--unstable-bare-node-builtins` will make it work https://docs.deno.com/runtime/reference/cli/unstable_flags/ -- We've yet to stabilize that

**Comment by wesbos** [comment]
Oh sorry it does show me where the import error is coming from - it points right to the `import  app from '../app.ts'` but it doesn't show me where that node API is being used - should it? It's just an import. 

Ill try it with that flag

**Comment by wesbos** [comment]
I moved the file out of that nested folder and I'm working my way through adding `node:` prefix to builtins - seems I'm past this. Thanks!

**Comment by ltaoo** [comment]
I encountered the same issue, but the file path that caused the error is not displayed, and it runs normally with node. 

![image](https://github.com/user-attachments/assets/3ec1b19c-daf1-4703-89cd-74b645a2fd28)

Steps to reproduce.

```bash
git clone https://github.com/lobehub/lobe-chat
pnpm i
DOCKER=true npm run build
cp -r public .next/standalone/public
cp -r .next/static .next/standalone/.next/static
mv .next/standalone/server.js .next/standalone/server.cjs
```

start the server using deno

```bash
cd .next/standalone
deno --allow-all ./server.cjs
```

If I open a page in the browser, the terminal will display the following messages.

![image](https://github.com/user-attachments/assets/4b7affd7-8b25-466a-872a-48e3c9be6b38)

**Comment by ltaoo** [comment]
the latest version 1.42.1  has this error, the version 1.36.11 I used before was fine.

**Comment by dsherret** [comment]
I'm going to close this one. I think probably the original issue was because Deno was previously not doing node resolution when there's a package.json, but now as of Deno 2.0 it does that by default.

For other issues, please open specific issues for specific problems. Errors like `Relative import path "fs" not prefixed with ...` where the module quoted is a built-in node module fail because Deno requires explicit `node:` imports for those modules (ex. change "fs" to "node:fs"). Alternatively, run with `--unstable-bare-node-builtins` https://docs.deno.com/runtime/reference/cli/unstable_flags/#--unstable-bare-node-builtins
