### ISSUE TITLE
thread 'main' panicked at ext/websocket/lib.rs:723:67:

### ISSUE THREAD

**Issue by benStre** [denoland/deno#21523]
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.
Platform: linux x86_64
Version: 1.38.5
Args: ["deno", "run", "-Aq", "--reload", "--config", "/app/deno.json", "--import-map", "/app/.datex-cache/importmap.lock.json", "https://cdn.unyt.org/uix@0.1.26/src/app/start.ts", "--config", "/app/deno.json", "--import-map", "/app/.datex-cache/importmap.lock.json", "-r", "--port", "80", "--stage", "prod_1", "--cache-path", "/datex-cache"]
thread 'main' panicked at ext/websocket/lib.rs:723:67:
called `Result::unwrap()` on an `Err` value: Bad resource ID
```

Deno version: 1.38.5

**Comment by littledivy** [comment]
Panic is fixed in 1.39
