### ISSUE TITLE
deno coverage panic

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#21580]
Version: Deno 1.39.0

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.39.0
Args: ["deno", "coverage", "mod.ts"]

thread 'main' panicked at cli/tools/coverage/reporter.rs:55:38:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
   3: core::option::Option<T>::unwrap
   4: deno::tools::coverage::reporter::CoverageReporter::collect_summary
   5: <deno::tools::coverage::reporter::SummaryCoverageReporter as deno::tools::coverage::reporter::CoverageReporter>::done
   6: deno::tools::coverage::cover_files::{{closure}}
   7: deno::spawn_subcommand::{{closure}}
   8: <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   9: tokio::runtime::task::raw::poll
  10: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This seems to be unreleated to the file I run against, it just always panic

**Comment by sigmaSd** [comment]
oh I forgot to run deno test before

**Comment by bartlomieju** [comment]
We shouldn't panic in a situation when no coverage files are found, it's definitely a bug.

**Comment by sigmaSd** [comment]
The last blog post shows this example `deno coverage`  but running that errors with 
```
error: the following required arguments were not provided:
  <files>...

Usage: deno coverage <files>...

For more information, try '--help'.
```
