### ISSUE TITLE
Deno jupyter kernel crashes when an imported module contains tests

### ISSUE THREAD

**Issue by zebreus** [denoland/deno#21594]
When a file with a test like:

```typescript
// fileWithTest.ts
import { assertEquals } from "https://deno.land/std@0.209.0/assert/mod.ts";

export const addOne = (x: number) => x + 1;

Deno.test("url test", () => {
  assertEquals(addOne(6), 7);
});
```

is imported, the deno jupyter kernel crashes:

![Screenshot from 2023-12-15 11-15-44](https://github.com/denoland/deno/assets/1557253/1558628b-516a-4f35-b35b-45d351253c90)

[Link to the repro notebook](https://github.com/zebreus/deno-kernel-test-bug/blob/master/notebook.ipynb)

**Comment by bartlomieju** [comment]
Which Deno version are you using?

**Comment by zebreus** [comment]
I am using a freshly installed deno 1.39.0. I run the kernel in vscode with the jupyter and deno extensions installed.

```console
$ deno --version
deno 1.39.0 (release, x86_64-unknown-linux-gnu)
v8 12.0.267.8
typescript 5.3.3
```

The issue can easily reproduced in gitpod (but also happens locally): https://gitpod.io/new/#https://github.com/zebreus/deno-kernel-test-bug

Jupyter log with `RUST_BACKTRACE=full`:
```
Jupyter Extension Version: 2023.9.100.
Python Extension not installed.
Platform: linux (x64).
Workspace folder /workspace/deno-kernel-test-bug, Home = /home/gitpod
15:25:03.838 [info] User belongs to experiment group 'NewJupyterSession'
15:25:04.237 [info] Start refreshing Kernel Picker (1702653904237)
15:25:04.257 [info] Not using Pylance
15:25:04.287 [warn] Disposing old controller startUsingLocalKernelSpec:'.deno.~d/.deno/bin/deno./.~d/.deno/bin/deno#--unstable#jupyter#--kernel#--conn#{connection_file}' for view = 'jupyter-notebook'
15:25:04.304 [warn] Disposing old controller startUsingLocalKernelSpec:'.deno.~d/.deno/bin/deno./.~d/.deno/bin/deno#--unstable#jupyter#--kernel#--conn#{connection_file} (Interactive)' for view = 'interactive'
15:25:04.305 [info] End refreshing Kernel Picker (1702653904237)
15:25:09.598 [info] Starting Kernel startUsingLocalKernelSpec, .deno.~/.deno/bin/deno./.~/.deno/bin/deno#--unstable#jupyter#--kernel#--conn#{connection_file}  for '/workspace/deno-kernel-test-bug/notebook.ipynb' (disableUI=true)
15:25:09.620 [info] Launching Raw Kernel Deno # ~/.deno/bin/deno
15:25:09.665 [info] Process Execution: ~/.deno/bin/deno --unstable jupyter --kernel --conn ~/.local/share/jupyter/runtime/kernel-v2-4973PvK15E4K0Uew.json
    > cwd: /workspace/deno-kernel-test-bug
15:25:09.899 [info] Started Kernel Deno (pid: 5322)
15:25:09.899 [info] Started new session 48ae5464-bab3-4e61-aac4-8af3ea1b9dcc
15:25:11.671 [info] Handle Execution of Cells 2,4 for /workspace/deno-kernel-test-bug/notebook.ipynb
15:25:11.681 [info] Kernel acknowledged execution of cell 2 @ 1702653911681
15:25:11.690 [info] End cell 2 execution @ 1702653911689, started @ 1702653911681, elapsed time = 0.008s
15:25:11.693 [info] Kernel acknowledged execution of cell 4 @ 1702653911693
15:25:11.705 [warn] StdErr from Kernel Process ============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.39.0
Args: ["~/.deno/bin/deno", "--unstable", "jupyter", "--kernel", "--conn", "~/.local/share/jupyter/runtime/kernel-v2-4973PvK15E4K0Uew.json"]

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.238.0/gotham_state.rs:82:3:
required type alloc::rc::Rc<deno_core::ops_metrics::OpMetricsSummaryTracker> is not present in GothamState container
stack backtrace:
15:25:11.706 [warn] StdErr from Kernel Process 0:     0x556ef3d8691c - <unknown>
   1:     0x556ef3dbbb3c - <unknown>
   2:     0x556ef3d7fb8e - <unknown>
   3:     0x556ef3d86704 - <unknown>
   4:     0x556ef3d884c3 - <unknown>
   5:     0x556ef3d881e4 - <unknown>
   6:     0x556ef423bf99 - <unknown>
   7:     0x556ef3d88c31 - <unknown>
   8:     0x556ef3d889b1 - <unknown>
   9:     0x556ef3d86e46 - <unknown>
  10:     0x556ef3d88702 - <unknown>
  11:     0x556ef3db8b65 - <unknown>
  12:     0x556ef401a03d - <unknown>
  13:     0x556ef4019abe - <unknown>
  14:     0x556ef42b6283 - <unknown>
  15:     0x556ef3b9995d - <unknown>
15:25:11.718 [error] Disposing session as kernel process died ExitCode: 1, Reason: 
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.39.0
Args: ["~/.deno/bin/deno", "--unstable", "jupyter", "--kernel", "--conn", "~/.local/share/jupyter/runtime/kernel-v2-4973PvK15E4K0Uew.json"]

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.238.0/gotham_state.rs:82:3:
required type alloc::rc::Rc<deno_core::ops_metrics::OpMetricsSummaryTracker> is not present in GothamState container
stack backtrace:
   0:     0x556ef3d8691c - <unknown>
   1:     0x556ef3dbbb3c - <unknown>
   2:     0x556ef3d7fb8e - <unknown>
   3:     0x556ef3d86704 - <unknown>
   4:     0x556ef3d884c3 - <unknown>
   5:     0x556ef3d881e4 - <unknown>
   6:     0x556ef423bf99 - <unknown>
   7:     0x556ef3d88c31 - <unknown>
   8:     0x556ef3d889b1 - <unknown>
   9:     0x556ef3d86e46 - <unknown>
  10:     0x556ef3d88702 - <unknown>
  11:     0x556ef3db8b65 - <unknown>
  12:     0x556ef401a03d - <unknown>
  13:     0x556ef4019abe - <unknown>
  14:     0x556ef42b6283 - <unknown>
  15:     0x556ef3b9995d - <unknown>

15:25:11.719 [info] Dispose Kernel process 5322.
15:25:11.720 [error] Raw kernel process exited code: 1
15:25:11.724 [error] Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (/workspace/.vscode-remote/extensions/ms-toolsai.jupyter-2023.9.100-universal/out/extension.node.js:2:32375)
    at /workspace/.vscode-remote/extensions/ms-toolsai.jupyter-2023.9.100-universal/out/extension.node.js:2:51383
    at Map.forEach (<anonymous>)
    at v._clearKernelState (/workspace/.vscode-remote/extensions/ms-toolsai.jupyter-2023.9.100-universal/out/extension.node.js:2:51368)
    at v.dispose (/workspace/.vscode-remote/extensions/ms-toolsai.jupyter-2023.9.100-universal/out/extension.node.js:2:44850)
    at /workspace/.vscode-remote/extensions/ms-toolsai.jupyter-2023.9.100-universal/out/extension.node.js:24:109965
    at ce (/workspace/.vscode-remote/extensions/ms-toolsai.jupyter-2023.9.100-universal/out/extension.node.js:2:2156310)
    at vy.dispose (/workspace/.vscode-remote/extensions/ms-toolsai.jupyter-2023.9.100-universal/out/extension.node.js:24:109941)
    at wy.dispose (/workspace/.vscode-remote/extensions/ms-toolsai.jupyter-2023.9.100-universal/out/extension.node.js:24:113311)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
15:25:11.726 [warn] Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
15:25:11.728 [info] End cell 4 execution @ 1702653911728, started @ 1702653911693, elapsed time = 0.035s
15:25:11.728 [warn] Cancel all remaining cells due to cancellation or failure in execution
15:25:11.804 [info] End cell 4 execution @ undefined, started @ undefined, elapsed time = 0s
```

**Comment by bartlomieju** [comment]
Thanks. This will be enough info to fix it.
