### ISSUE TITLE
Deno UDP/Datagram truncates messages greater than 1024 bytes

### ISSUE THREAD

**Issue by billywhizz** [denoland/deno#21609]
Version: deno 1.39.0 (release, x86_64-unknown-linux-gnu)

I was doing some benchmarking and noticed this issue. Whenever I try to send a message larger than 1024 bytes I only ever receive 1024 bytes on the other end.

This script should reproduce the issue

```JavaScript
function assert(condition, message, ErrorType = Error) {
  if (!condition) {
    if (message && message.constructor.name === "Function") {
      throw new ErrorType(message(condition));
    }
    throw new ErrorType(message || "Assertion failed");
  }
  return condition;
}

async function start_pong() {
  let msg = await pong.receive();
  while (msg) {
    assert(msg[0].length === size, () => `${msg[0].length} !== ${size}`);
    console.log(`pong_receive ${msg[0].length}`);
    break;
  }
  pong.close();
}

const encoder = new TextEncoder();
const ping = Deno.listenDatagram({ port: 4000, transport: "udp" });
const pong = Deno.listenDatagram({ port: 4001, transport: "udp" });
const size = Math.min(parseInt(Deno.args[0] || "1", 10), 65536);
start_pong().catch((err) => console.error(err.stack));
const buf = encoder.encode("1".repeat(size));
assert(buf.length === size);
await ping.send(buf, pong.addr);
ping.close();

```

run it like so and you will see the issue

```shell
deno run -A --unstable repro.js 1025
Error: 1024 !== 1025
    at assert (file:///media/andrew/OCZ/source2023/billywhizz/deno/repro.js:4:13)
    at start_pong (file:///media/andrew/OCZ/source2023/billywhizz/deno/repro.js:14:5)
    at eventLoopTick (ext:core/01_core.js:181:11)
```

I have implemented a fix and a test for this and will submit a PR referencing this issue shortly.

**Comment by billywhizz** [comment]
PR [here](https://github.com/denoland/deno/pull/21611)

**Comment by billywhizz** [comment]
dang. [looks like](https://github.com/denoland/deno/actions/runs/7237178618/job/19716512557?pr=21611#step:41:2676) there must be some difference on macos for this limit. i will take a look.

**Comment by billywhizz** [comment]
now fixed on mac but [breaking](https://github.com/denoland/deno/actions/runs/7241727148/job/19726162574#step:41:2671) on windows. i'll see if i can run on windows to see what error message looks like there.
