### ISSUE TITLE
Deno.HttpServer leaky connection: connection closed before message completed error

### ISSUE THREAD

**Issue by andykais** [denoland/deno#21661]
```
deno 1.39.0 (release, x86_64-unknown-linux-gnu)
v8 12.0.267.8
typescript 5.3.3
```

I am attempting to build a http server benchmark. It does not currently seem to be possible to start/stop a `Deno.HttpServer` with the same port. The server starts without any problem, but the secondary fetch then fails with the error `connection closed before message completed`. Full stacktrace is collapsed below.

```ts
const server_1 = Deno.serve({
  port: 8000,
  handler(req) {
    return new Response('hello world')
  },
})

const response_1 = await fetch('http://0.0.0.0:8000').then(r => r.text())
console.log({response_1})
await server_1.shutdown()

const server_2 = Deno.serve({
  port: 8000,
  handler(req) {
    return new Response('hello world')
  },
})
const response_2 = await fetch('http://0.0.0.0:8000').then(r => r.text())
console.log({response_2})
```

<details>
<summary>`deno run --check --unstable --allow-net repro.ts` output</summary>
<pre>
Listening on http://localhost:8000/
{ response_1: "hello world" }
Listening on http://localhost:8000/
error: Uncaught (in promise) TypeError: error sending request for url (http://0.0.0.0:8000/): connection closed before message completed
const response_2 = await fetch('http://0.0.0.0:8000').then(r => r.text())
                   ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:164:12)
    at async fetch (ext:deno_fetch/26_fetch.js:385:7)
    at async file:///home/andrew/Code/scratchwork/deno-thumbnail-sqlite-benchmark/repro_reopen_closed.ts:19:20
</pre>
</details>

## related issues
Bundling a few possibly related issues, since I found a few in the repo, but none that directly lined up with my repro of starting/shutting down and starting a new http server in the same process:
- https://github.com/denoland/deno/issues/17754
- https://github.com/denoland/deno/issues/19143
- https://github.com/denoland/deno/issues/19062
- https://github.com/denoland/deno/issues/11595

**Comment by mmastrac** [comment]
This is an issue with the connection pool in fetch. We haven't figured out a great way to fix this one yet.

**Comment by Hajime-san** [comment]
This was fixed in:
- https://github.com/denoland/deno/pull/32566

```bash
% deno --version
deno 2.8.0 (stable, release, aarch64-apple-darwin)
v8 14.9.207.2-rusty
typescript 6.0.3

% deno run --allow-net repro.ts
Listening on http://0.0.0.0:8000/ (http://localhost:8000/)
{ response_1: "hello world" }
Listening on http://0.0.0.0:8000/ (http://localhost:8000/)
{ response_2: "hello world" }
```
