### ISSUE TITLE
TypeError: setImmediate(...).unref is not a function

### ISSUE THREAD

**Issue by DMeechan** [denoland/deno#21660]
Version: Deno 1.39.0

The code below runs fine using Node v18.17.1 but throws an error with Deno 1.39.0:

```ts
import { TLRU } from "npm:tlru@1.0.2";

const timeBasedCache = new TLRU();
timeBasedCache.set("some key", "some value");
timeBasedCache.clear();

console.log("Done")
```

Gives the following error:

```js
error: Uncaught (in promise) TypeError: setImmediate(...).unref is not a function
    at Scheduler.timeoutItem (file:///home/project/node_modules/.deno/fun-dispatcher@1.2.6/node_modules/fun-dispatcher/dist/index.js:49:36)
    at Scheduler.flush (file:///home/project/node_modules/.deno/fun-dispatcher@1.2.6/node_modules/fun-dispatcher/dist/index.js:106:18)
    at TLRU.clear (file:///home/project/node_modules/.deno/tlru@1.0.2/node_modules/tlru/dist/index.js:48:24)
    at file:///home/project/timeout-error-example.ts:8:16
```

The stacktrace leads to this file in [fun-dispatcher](https://github.com/tinovyatkin/fun-dispatcher/tree/master): https://github.com/tinovyatkin/fun-dispatcher/blob/e821d2cc42e36f5bd341c9acb90bed15f32bab08/src/index.ts#L64

**Comment by mmastrac** [comment]
I discovered that setImmediate _can_ meaningfully use ref/unref. Not sure if anyone is relying on this behaviour:

```
node -e "let i = setImmediate(() => setImmediate(() => { console.log(2) })); i.unref()"
```
