### ISSUE TITLE
deno failed build openwrt

### ISSUE THREAD

**Issue by predators46** [denoland/deno#21696]
Version: Deno 1.39.1

```
Running `/home/open/wrt/build_dir/target-aarch64_generic_musl/deno-1.39.1/target/release/build/v8-a085429beb7abfb8/build-script-build`
error: failed to run custom build command for `v8 v0.82.0`
Caused by:
  process didn't exit successfully: `/home/open/wrt/build_dir/target-aarch64_generic_musl/deno-1.39.1/target/release/build/v8-a085429beb7abfb8/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=.gn
  cargo:rerun-if-changed=BUILD.gn
  cargo:rerun-if-changed=src/binding.cc
  cargo:rerun-if-env-changed=CCACHE
  cargo:rerun-if-env-changed=CLANG_BASE_PATH
  cargo:rerun-if-env-changed=CXXSTDLIB
  cargo:rerun-if-env-changed=DENO_TRYBUILD
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=GN
  cargo:rerun-if-env-changed=GN_ARGS
  cargo:rerun-if-env-changed=HOST
  cargo:rerun-if-env-changed=NINJA
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=RUSTY_V8_ARCHIVE
  cargo:rerun-if-env-changed=RUSTY_V8_MIRROR
  cargo:rerun-if-env-changed=SCCACHE
  cargo:rerun-if-env-changed=V8_FORCE_DEBUG
  cargo:rerun-if-env-changed=V8_FROM_SOURCE
  cargo:rerun-if-env-changed=PYTHON
  cargo:rerun-if-env-changed=DISABLE_CLANG
  cargo:rerun-if-env-changed=EXTRA_GN_ARGS
  cargo:rerun-if-env-changed=NO_PRINT_GN_ARGS
  cargo:rustc-link-lib=static=rusty_v8
  download lockfile: "/home/open/wrt/build_dir/target-aarch64_generic_musl/deno-1.39.1/target/aarch64-unknown-linux-musl/release/build/lib_download.fslock"
  static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.82.0/librusty_v8_release_aarch64-unknown-linux-musl.a
  cargo:rustc-link-search=/home/open/wrt/build_dir/target-aarch64_generic_musl/deno-1.39.1/target/aarch64-unknown-linux-musl/release/gn_out/obj
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.82.0/librusty_v8_release_aarch64-unknown-linux-musl.a
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.82.0/librusty_v8_release_aarch64-unknown-linux-musl.a...
  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to
get local issuer certificate (_ssl.c:1006)>
  Retrying in 5 s ...
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.82.0/librusty_v8_release_aarch64-unknown-linux-musl.a...
  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to
get local issuer certificate (_ssl.c:1006)>
  Retrying in 10 s ...
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.82.0/librusty_v8_release_aarch64-unknown-linux-musl.a...
  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to
get local issuer certificate (_ssl.c:1006)>
  Retrying in 20 s ...
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.82.0/librusty_v8_release_aarch64-unknown-linux-musl.a...
  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to
get local issuer certificate (_ssl.c:1006)>
  Python downloader failed, trying with curl.
  --- stderr
  Traceback (most recent call last):
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/urllib/request.py", line 1348, in do_open
      h.request(req.get_method(), req.selector, req.data, headers,
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/http/client.py", line 1286, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/http/client.py", line 1332, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/http/client.py", line 1281, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/http/client.py", line 1041, in _send_output
      self.send(msg)
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/http/client.py", line 979,
in send
      self.connect()
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/http/client.py", line 1458, in connect
      self.sock = self._context.wrap_socket(self.sock,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/ssl.py", line 517, in wrap_socket
      return self.sslsocket_class._create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/ssl.py", line 1108, in _create
      self.do_handshake()
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/ssl.py", line 1379, in do_handshake
      self._sslobj.do_handshake()
  ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/home/open/wrt/dl/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.82.0/./tools/download_file.py", line 64, in <module>
      sys.exit(main())
               ^^^^^^
    File "/home/open/wrt/dl/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.82.0/./tools/download_file.py", line 59, in main
      DownloadUrl(args.url, f)
    File "/home/open/wrt/dl/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.82.0/./tools/download_file.py", line 45, in DownloadUrl
      raise e
    File "/home/open/wrt/dl/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.82.0/./tools/download_file.py", line 29, in DownloadUrl
      response = urlopen(url)
                 ^^^^^^^^^^^^
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/urllib/request.py", line 216, in urlopen
      return opener.open(url, data, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/urllib/request.py", line 519, in open
      response = self._open(req, data)
                 ^^^^^^^^^^^^^^^^^^^^^
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/urllib/request.py", line 536, in _open
      result = self._call_chain(self.handle_open, protocol, protocol +
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/urllib/request.py", line 496, in _call_chain
      result = func(*args)
               ^^^^^^^^^^^
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/urllib/request.py", line 1391, in https_open
      return self.do_open(http.client.HTTPSConnection, req,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/open/wrt/staging_dir/hostpkg/lib/python3.11/urllib/request.py", line 1351, in do_open
      raise URLError(err)
  urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
  thread 'main' panicked at /home/open/wrt/dl/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.82.0/build.rs:431:3:
  assertion failed: status.success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.39.1 (/home/open/wrt/build_dir/target-aarch64_generic_musl/deno-1.39.1/cli)`, intermediate artifacts can be found at `/home/open/wrt/build_dir/target-aarch64_generic_musl/deno-1.39.1/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
make[2]: *** [Makefile:50: /home/open/wrt/build_dir/target-aarch64_generic_musl/deno-1.39.1/.built] Error 101
make[2]: Leaving directory '/home/open/wrt/feeds/packages/lang/deno'
time: package/feeds/packages/deno/compile#246.91#19.02#359.43
    ERROR: package/feeds/packages/deno failed to build.
make[1]: *** [package/Makefile:128: package/feeds/packages/deno/compile] Error 1
make[1]: Leaving directory '/home/open/wrt'
make: *** [/home/open/wrt/include/toplevel.mk:225: package/deno/compile] Error 2
open@localhost:~/wrt$ a
```

**Comment by littledivy** [comment]
I am not familiar with Openwrt but linux arm64 (gnu and musl) Deno builds are currently not supported.

**Comment by bartlomieju** [comment]
This isn't a Deno bug - it's a TLS/CA-certificate problem in the OpenWrt build host. Past the traceback, the root cause is a single error:

```
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
 unable to get local issuer certificate (_ssl.c:1006)>
```

The `v8` crate's build script (`download_file.py`) is downloading the prebuilt `librusty_v8_release_aarch64-unknown-linux-musl.a` from GitHub releases, and the build host's Python can't verify the TLS certificate because its staging environment has no CA bundle. The `assertion failed: status.success()` panic is just the build script reacting to that failed download. The prebuilt library itself exists, so the download would succeed with working TLS.

Workarounds, all on the environment side:

- install `ca-certificates` in the OpenWrt host env, or point `SSL_CERT_FILE` / `SSL_CERT_DIR` at a valid CA bundle;
- or pre-download the archive and set `RUSTY_V8_ARCHIVE=/path/to/librusty_v8.a` to skip the network entirely (or use `RUSTY_V8_MIRROR`).

Also note the earlier comment that linux arm64 builds aren't supported is now outdated - Deno ships official Linux aarch64 builds. But that wasn't the cause here anyway.

Since this is a local certificate-verification issue rather than a Deno defect, closing it. If you hit a genuine build failure after the download succeeds, please open a fresh issue with that output.
