### ISSUE TITLE
`nuxt dev` needs --enable-source-maps

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#21750]
In https://github.com/nuxt/cli/blob/1aa509522c8794c8faef2f634bed4ae3577eef83/src/commands/dev.ts#L170:

```ts
    childProc = fork(globalThis.__nuxt_cli__?.entry!, ['_dev', ...rawArgs], {
      execArgv: [
        '--enable-source-maps',
        process.argv.includes('--inspect') && '--inspect',
      ].filter(Boolean) as string[],
```

```
 divy@mini ~/g/myapp (main) [1]> ../deno/target/release/deno task dev
Task dev nuxt dev
Nuxt 3.9.0 with Nitro 2.8.1                                                      12:21:12 PM
                                                                                 12:21:12 PM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

error: unexpected argument '--enable-source-maps' found

  tip: a similar argument exists: '--unstable-workspaces'

Usage: deno run --unstable --node-modules-dir[=<node-modules-dir>] --allow-all --unstable-workspaces [SCRIPT_ARG]...

For more information, try '--help'.


 ERROR  [unhandledRejection] Unknown signal: 0                                   12:21:12 PM

  at toDenoSignal (ext:deno_node/internal/child_process.ts:283:11)
  at ChildProcess.kill (ext:deno_node/internal/child_process.ts:197:53)
  at kill (node_modules/.deno/nuxt@3.9.0/node_modules/nuxi/dist/chunks/dev.mjs:247:17)
  at process.<anonymous> (node_modules/.deno/nuxt@3.9.0/node_modules/nuxi/dist/chunks/dev.mjs:292:7)
  at Object.onceWrapper (ext:deno_node/_events.mjs:508:26)
  at process.emit (ext:deno_node/_events.mjs:395:35)
  at process.emit (node:process:376:20)
  at process.exit (node:process:61:13)
  at ChildProcess.<anonymous> (node_modules/.deno/nuxt@3.9.0/node_modules/nuxi/dist/chunks/dev.mjs:271:17)
  at ChildProcess.emit (ext:deno_node/_events.mjs:383:28)
```

**Comment by rracariu** [comment]
related https://github.com/nuxt/cli/issues/286
