### ISSUE TITLE
Error: read UNKNOWN with node-postgres

### ISSUE THREAD

**Issue by patrickalima98** [denoland/deno#21776]
Hi, 

When using Deno Deploy I get this Uncaught (in promise) Error: read UNKNOWN error when running the script below:
```shell
Error: read UNKNOWN
    at file:///node_modules/.deno/pg-pool@3.6.1/node_modules/pg-pool/index.js:45:11
    at Object.runMicrotasks (ext:core/01_core.js:790:30)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:184:21)
    at async Server.<anonymous> (file:///src/main.tsx:18:22)
    at async Server.#respond (https://deno.land/std@0.114.0/http/server.ts:350:24) {
  errno: -4094,
  code: "UNKNOWN",
  syscall: "read"
}

```

## How to reproduce
Create pg-test.ts and replace the postgres connection info (Host, Password, User, etc...), and deploy it to a project in deno deploy, after upload, call the endpoint of script.

```ts
import { serve } from "https://deno.land/std@0.114.0/http/server.ts";
// import * as postgres from "https://deno.land/x/postgres@v0.14.2/mod.ts"
import postgres from "npm:pg";

// Get the connection string from the environment variable "DATABASE_URL"
const connectionString = "postgres://USER:PASS@HOST/DBNAMEsslmode=require";

// Create a database pool with three connections that are lazily established
const connection = new postgres.Pool({connectionString});

// Connect to the database
// const connection = await pool.connect();
  // connection.release();

serve(async (req) => {
  try {
      // Run the query
      const result = await connection.query(`
        SELECT version();
      `);

      // Encode the result as JSON
      const body = JSON.stringify(result.rows, null, 2);

      // Return the result as JSON
      return new Response(body, {
        headers: { "content-type": "application/json" },
      });
  } catch (err) {
    console.error(err);
    // If an error occurs, return a 500 response
    return new Response(`Internal Server Error\n\n${err.message}`, {
      status: 500,
    });
  } finally {
    // Release the connection back into the pool
    connection.release();
  }
});
```
Version: Deno Deploy

I get the same problem with last deno version: `1.39.1`.

PS: The same script works perfect with `https://deno.land/x/postgres@v0.14.2/mod.ts`

**Comment by bartlomieju** [comment]
Do you still experience this problem in February 2025?

**Comment by bartlomieju** [comment]
Closing as resolved — this no longer reproduces on current Deno, and the subsystem responsible for it has been rewritten.

**Root cause:** `read UNKNOWN` / errno `-4094` is libuv's `UV_UNKNOWN`. When this was filed (Deno 1.39.1), `node:net` was a pure-JS polyfill over Deno's async `conn.read()` that translated read errors to errno codes via a hand-written JS map. Any read error whose kind wasn't in that map fell through to `UNKNOWN (-4094)`, which is what `pg` surfaced when a pooled connection hit an unmapped socket error (common on Deno Deploy, where idle pooled sockets get reset by the platform/DB).

**Why it's fixed:** `node:net` is now libuv-backed. Reads go through `uv_read_start` → `on_uv_read`, and the errno handed up is a real libuv error from `uv_translate_sys_error`, so `ECONNRESET`/`EPIPE`/`ETIMEDOUT`/EOF all map correctly. `UV_UNKNOWN` is now only possible for an OS error libuv itself can't translate (essentially never).

**Verification** (current `main`, real Postgres in Docker, `npm:pg`):
- Plain TCP and TLS queries work.
- Backend terminated mid-query (plain + TLS): clean `57P01` / `Connection terminated unexpectedly`.
- TCP proxy hard-drop mid-query over TLS: `Connection terminated unexpectedly`.
- `docker kill` (kernel RST) mid-query: `Connection terminated unexpectedly`.

No scenario produced `read UNKNOWN` — every disconnect maps to a proper error. If anyone still hits this on a current release, please reopen with a minimal repro and the exact version.
