### ISSUE TITLE
Compiled binary throws zlib dependency error

### ISSUE THREAD

**Issue by 7flash** [denoland/deno#21809]
Version: Deno 1.39.1

Jan05-2100.ts

```ts
import { Database } from "https://deno.land/x/sqlite3@0.10.0/mod.ts";

const db = new Database("test.db");

const [version] = db.prepare("select sqlite_version()").value<[string]>()!;
console.log(version);

db.close();
```

Compile it

```
deno compile Jan05-2100.ts
```

Then run

```
./Jan05-2100
error: Uncaught (in promise) Error: Failed to load SQLite3 Dynamic Library
  throw new Error("Failed to load SQLite3 Dynamic Library", {
        ^
    at https://deno.land/x/sqlite3@0.10.0/src/ffi.ts:543:9
    at eventLoopTick (ext:core/01_core.js:181:11)
Caused by: Error: Could not open library: Could not open library: dlopen(/Users/gur/Library/Caches/deno/plug/https/github.com/104011a9e1238b1ae4e9c5bd462569d5bdcb9ae2d6b36d982871dbce44f79c44.dylib, 0x0005): Library not loaded: /opt/homebrew/opt/zlib/lib/libz.1.dylib
  Referenced from: <61850E31-E458-361A-ADCC-2CD22831D197> /Users/gur/Library/Caches/deno/plug/https/github.com/104011a9e1238b1ae4e9c5bd462569d5bdcb9ae2d6b36d982871dbce44f79c44.dylib (built for macOS 14.0 which is newer than running OS)
  Reason: tried: '/opt/homebrew/opt/zlib/lib/libz.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/zlib/lib/libz.1.dylib' (no such file), '/opt/homebrew/opt/zlib/lib/libz.1.dylib' (no such file)
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:454:46)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:591:10)
    at dlopen (https://deno.land/x/plug@1.0.1/mod.ts:125:15)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async https://deno.land/x/sqlite3@0.10.0/src/ffi.ts:531:12
```

This error solved by installing zlib

```
brew install zlib
```

Then works

```
./Jan05-2100
3.44.0
```

It's expected to work regardless user machine has zlib installed

https://github.com/denoland/deno/issues/4045

**Comment by mmastrac** [comment]
Is this a homebrew binary? If so, the homebrew project links against its own zlib and `deno compile` binaries will also link against them.

We may need to consider a warning flag when using `deno compile` on binaries that don't embed zlib.

**Comment by 7flash** [comment]
> Is this a homebrew binary?

If you mean my deno installation, it's managed by [rtx(mise)](https://github.com/jdx/rtx)

```
which deno
/Users/gur/.local/share/rtx/installs/deno/latest/bin/deno
```

> on binaries that don't embed zlib

If you mean sqlite3, it's ffi library

Anyway, what should I do, to make sure it works on users machine?

**Comment by littledivy** [comment]
@7flash Deno does not dynamically link to zlib. It seems that the sqlite3 library depends on zlib installation. You can try confirming with `otool -L /path/to/sqlite.dylib`

Output for me is:

```
$ otool -L libsqlite3_aarch64.dylib
libsqlite3_aarch64.dylib:
	/usr/local/lib/libsqlite3-3.44.0.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/opt/homebrew/opt/zlib/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.13)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
```

This is most likely a bug in `x/sqlite3`. Please open an issue in it's issue tracker: https://github.com/denodrivers/sqlite3/issues

**Comment by bartlomieju** [comment]
Gonna close this one due to lack of activity.
