### ISSUE TITLE
node:test mock not implemented

### ISSUE THREAD

**Issue by EdJoPaTo** [denoland/deno#21868]
While there exists a [`std` implementation for mock / spy](https://deno.land/std@0.211.0/testing/mock.ts) logic, `node:test` does not work as it is not implemented.
Running the following example (as `test.mjs` without the `number` type annotation) works fine with `node --test`.

```ts
import { strictEqual } from "node:assert";
import { test } from "node:test";

test("foo", (t) => {
  const fn = t.mock.fn((a: number, b: number) => a + b);
  strictEqual(fn(2, 3), 5);
  strictEqual(fn.mock.callCount(), 1);
});
```

```plaintext
$ deno test
Check file:///tmp/test.ts
running 1 test from ./test.ts
foo ... FAILED (3ms)

 ERRORS

foo => ./test.ts:4:1
error: Error: Not implemented: test.TestContext.mock
    at notImplemented (ext:deno_node/_utils.ts:9:9)
    at NodeTestContext.get mock (node:test:26:5)
    at file:///tmp/test.ts:5:16
    at node:test:99:13

 FAILURES

foo => ./test.ts:4:1

FAILED | 0 passed | 1 failed (6ms)

error: Test failed
```

```plaintext
$ deno --version
deno 1.39.2 (release, x86_64-unknown-linux-gnu)
v8 12.0.267.8
typescript 5.3.3
```

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/31954.
