### ISSUE TITLE
Bug: Missing transient dependency

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#21884]
The `tailwindcss` package directly depends on `@alloc/quick-lru` but for some reason that is flagged as being missing.

## Steps to reproduce

1. Clone https://github.com/cknight/partial-form-test
2. Run `deno task start`

## Error

```sh
error: Uncaught (in promise) Error: Cannot find module '@alloc/quick-lru'
Require stack:
- /Users/marvinh/dev/test/fresh-dep/node_modules/.deno/tailwindcss@3.3.5/node_modules/tailwindcss/lib/lib/setupTrackingContext.js
- /Users/marvinh/dev/test/fresh-dep/node_modules/.deno/tailwindcss@3.3.5/node_modules/tailwindcss/lib/plugin.js
- /Users/marvinh/dev/test/fresh-dep/node_modules/.deno/tailwindcss@3.3.5/node_modules/tailwindcss/lib/index.js
- /Users/marvinh/dev/test/fresh-dep/node_modules/.deno/tailwindcss@3.3.5/node_modules/tailwindcss/lib/index.js
    at Function.Module._resolveFilename (node:module:622:15)
    at Function.Module._load (node:module:500:27)
    at Module.require (node:module:675:19)
    at require (node:module:789:16)
    at Object.<anonymous> (file:///Users/marvinh/dev/test/fresh-dep/node_modules/.deno/tailwindcss@3.3.5/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:17:58)
    at Object.<anonymous> (file:///Users/marvinh/dev/test/fresh-dep/node_modules/.deno/tailwindcss@3.3.5/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:168:4)
    at Module._compile (node:module:731:34)
    at Object.Module._extensions..js (node:module:745:10)
    at Module.load (node:module:656:32)
    at Function.Module._load (node:module:537:12)
```

Version: Deno 1.39.2

**Comment by khiemn159** [comment]
I got the same bug today, the reason might be missing some files in node_modules folder. My quick fix is to delete node_modules folder and run `deno task start` again. It will redownload node_modules including missing files.

**Comment by newwingbird** [comment]
I also fixed it this way.
> I My quick fix is to delete node_modules folder and run `deno task start` again. It will redownload node_modules including missing files.

**Comment by nermalcat69** [comment]
Still facing this problem

**Comment by fosterushka** [comment]
bump
