### ISSUE TITLE
Deno process does not exit with Promise.

### ISSUE THREAD

**Issue by jabed-dev** [denoland/deno#21907]
Version: Deno 1.39.2

```ts
import { WebUI } from 'https://deno.land/x/webui/mod.ts';

const WebWindow = new WebUI();
WebWindow.setSize(400, 700);
WebWindow.setPosition(500, 20);

const promise1 = new Promise((resolve) => setTimeout(resolve, 500, 'close'));
const promise2 = new Promise((resolve) => {
  // ⚠️ Here this line is paused. not exit process
  WebWindow.showBrowser('https://deno.com', WebUI.Browser.Edge);
  resolve('pause');
  // setTimeout(resolve, 1000, 'pause');
});

Promise.race([promise1, promise2]).then((response) => {
  console.log(response);
  Deno.exit(0);
});

// $ deno run --allow-all --unstable app.ts
```

![deno-webui](https://github.com/denoland/deno/assets/59810760/9791c2ca-1cf9-4367-86ca-a957bfad5700)

**Comment by marvinhagemeister** [comment]
FYI: This looks to be something OS specific. The `webui` module seems to only work on windows. On macOS I get this error:

```sh
error: Uncaught (in promise) TypeError: Deno.dlopen is not a function
  return Deno.dlopen(
              ^
    at loadLib (https://deno.land/x/webui@2.4.4/src/lib.ts:9:15)
    at new WebUI (https://deno.land/x/webui@2.4.4/src/webui.ts:43:17)
    at file:///Users/marvinh/dev/test/deno-webui/foo.ts:3:19
    at eventLoopTick (ext:core/01_core.js:182:7)
```

**Comment by jabed-dev** [comment]
You can use `AnyBrowser`

```js
WebWindow.showBrowser('https://deno.com', WebUI.Browser.Edge);
```
