### ISSUE TITLE
Incorrect order of close vs error event with Node.js `net` polyfill on ECONNREFUSED

### ISSUE THREAD

**Issue by vkarpov15** [denoland/deno#21951]
Version: Deno v1.39.4.

Consider the following script, assuming that you don't have anything running on port 27025 you should get an ENOENT error.

```
import net from 'node:net';
const socket = net.createConnection('mongodb://127.0.0.1:27025/test');
socket.on('close', () => console.log('close'));
socket.on('error', err => console.log('Error', err));
```

In Deno v1.39.4, this script outputs the following. Notice that `close` comes _before_ `error`. I believe this event order is incorrect: [the Node.js docs indicate the `close` event means that no further events should be emitted](https://nodejs.org/api/stream.html#event-close).

```
$ deno run --unstable --node-modules-dir --allow-net --allow-read --allow-sys --allow-env gh-14237.js
:white_check_mark: Granted write access to "mongodb://127.0.0.1:27025/test".
close
Error Error: connect ENOENT mongodb://127.0.0.1:27025/test
  at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:91:9)
  at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:215:10)
  at PipeConnectWrap._afterConnect [as oncomplete] (node:net:170:16)
  at Pipe.afterConnect (ext:deno_node/internal_binding/connection_wrap.ts:43:11)
  at ext:deno_node/internal_binding/pipe_wrap.ts:138:14 {
 errno: -2,
 code: "ENOENT",
 syscall: "connect",
 address: "mongodb://127.0.0.1:27025/test"
}
```

In Node v21.4.0, consider the following slightly modified but equivalent script.

```javascript
const net = require('net');
const socket = net.createConnection('mongodb://127.0.0.1:27025/test');
socket.on('close', () => console.log('close'));
socket.on('error', err => console.log('Error', err));
```

In the output, the event order is reversed: `close` comes _after_ `error`:

```
$ node gh-14237-2.js
Error Error: connect ENOENT mongodb://127.0.0.1:27025/test
  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
 errno: -2,
 code: 'ENOENT',
 syscall: 'connect',
 address: 'mongodb://127.0.0.1:27025/test'
}
close
```

I think this issue is the root cause of #19078 and https://github.com/Automattic/mongoose/issues/14237.

**Comment by lucacasonato** [comment]
I can still reproduce this in 1.44.2
