### ISSUE TITLE
Request ip is undefined

### ISSUE THREAD

**Issue by Momoshikin** [denoland/deno#21980]
I'm using **express** and **mongo** on Deno, and i'm also trying to use **express-rate-limit**, however, i'm getting the following error on rate-limit because the `request.ip` on every request is undefined

```js
ValidationError: An undefined 'request.ip' was detected. This might indicate a misconfiguration or the connection being destroyed prematurely. See https://express-rate-limit.github.io/ERR_ERL_UNDEFINED_IP_ADDRESS/ for more information.
    at Object.ip (file:///node_modules/.deno/express-rate-limit@7.1.5/node_modules/express-rate-limit/dist/index.mjs:97:13)
    at Object.wrappedValidations.<computed> [as ip] (file:///node_modules/.deno/express-rate-limit@7.1.5/node_modules/express-rate-limit/dist/index.mjs:296:22)
    at Object.keyGenerator (file:///node_modules/.deno/express-rate-limit@7.1.5/node_modules/express-rate-limit/dist/index.mjs:549:20)
    at file:///node_modules/.deno/express-rate-limit@7.1.5/node_modules/express-rate-limit/dist/index.mjs:601:32
    at Object.runMicrotasks (ext:core/01_core.js:934:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:189:21)
    at async file:///node_modules/.deno/express-rate-limit@7.1.5/node_modules/express-rate-limit/dist/index.mjs:583:5 {
  name: "ValidationError",
  code: "ERR_ERL_UNDEFINED_IP_ADDRESS",
  help: "https://express-rate-limit.github.io/ERR_ERL_UNDEFINED_IP_ADDRESS/"
}
```

I've found this [answer](https://stackoverflow.com/questions/62494060/express-rate-limit-not-working-when-deployed-to-heroku) on a similar question that suggests adding `app.set('trust proxy', 1);` i tried it, but the ip continues undefined.

How to reproduce:

```js
"use strict"

import express    from 'express';
import bodyParser from 'body-parser';
import mongoose   from 'mongoose';
import rateLimit  from 'express-rate-limit';

const app = express();

mongoose.connect("...");
const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() { console.log('Connected to MongoDB'); });

app.use(bodyParser.json());
app.set('trust proxy', 1);

const limiter = rateLimit({  windowMs: 1 * 60 * 1000,  max: 3, });
app.post('/api/users', limiter, async (req, res) =>
{
    console.log('ip:', req.ip);
    console.log('conn:', req.connection)
    console.log('conn.remoteAddress:', req.connection.remoteAddress)
    console.log('client:', req.client);
    console.log('headers:', req.headers);
    console.log('rawHeaders:', req.rawHeaders);
    console.log('X-Forwarded-For:', req.headers['x-forwarded-for']);
    console.dir('req:', req);
    try {
        const variable = await db.collection("users").findOne({ [req.body.user]: { $exists: true } })
        if (!variable) return res.status(404).send('Not found');
        res.send(variable);
    } 
    catch (error) { res.status(500).send('Internal Server Error');  }
});

app.listen(5000, () => { console.log(`running`); });
```

Testing locally i'm able to see my ip on all these variables, while on Deno this is what being printed:

```
ip: undefined

conn: FakeSocket {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    remoteAddress: undefined,
    remotePort: undefined,
    encrypted: undefined,
    writable: true,
    readable: true,
    [Symbol(kCapture)]: false
  }

conn.remoteAddress: undefined

client: undefined

headers:
{
  "accept-encoding": "gzip, deflate",
  "accept-language": "en-US,en,*",
  "content-length": "14",
  "content-type": "application/json",
  host: "....deno.dev",
  "user-agent": "Mozilla/5.0"
}

rawHeaders: undefined

X-Forwarded-For: undefined

req: <ref *1> IncomingMessageForServer {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: false,
      defaultEncoding: "utf8",
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _read: [AsyncFunction: read],
    _destroy: [Function: destroy],
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    url: "/api/users",
    method: "POST",
    socket: FakeSocket {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      remoteAddress: undefined,
      remotePort: undefined,
      encrypted: undefined,
      writable: true,
      readable: true,
      [Symbol(kCapture)]: false
    },
    next: [Function: next],
    baseUrl: "",
    originalUrl: "/api/users",
    _parsedUrl: Url {
      protocol: null,
      slashes: null,
      auth: null,
      host: null,
      port: null,
      hostname: null,
      hash: null
```

The ip is undefined and its missing all headers, i'm not sure if this is a bug or if i'm missing something, any help is appreciated.

**Comment by Momoshikin** [comment]
@bartlomieju This issue also has been reported at https://github.com/denoland/deno/issues/18310
Reported in 2022 and still hasn't been fixed, I'm not expecting this to be fixed any time soon them?

**Comment by marvinhagemeister** [comment]
Here is a smaller reproduction case:

```ts
import express from "express";

const app = express();

app.get("/", (req, res) => {
  console.log("ip:", req.ip);
  res.status(200);
});

app.listen(5000, () => {
  console.log(`running on http://localhost:5000`);
});

await fetch("http://localhost:5000");
```

In node `req.ip` prints `::1` whereas it's undefined in Deno. Haven't yet tracked down why that is.

**Comment by marvinhagemeister** [comment]
An even smaller reproduction:

```ts
import http from "node:http";

http.createServer(function (req, res) {
  console.log(req.socket.remoteAddress);
  res.end(req.socket.remoteAddress); //end the response
}).listen(8080, () => {
  console.log("listening on http://localhost:8080");
});
```
