### ISSUE TITLE
Receiving an issue while using deno: KV collect expired failed: database disk image is malformed

### ISSUE THREAD

**Issue by mcgear** [denoland/deno#21990]
I am receiving an error and it told me to post it here, sorry if it should be posted in denoKv

```
2024-01-18T20:28:07.592702027Z Deno has panicked. This is a bug in Deno. Please report this
2024-01-18T20:28:07.592705627Z at https://github.com/denoland/deno/issues/new.
2024-01-18T20:28:07.592709227Z If you can reliably reproduce this panic, include the
2024-01-18T20:28:07.595724140Z reproduction steps and re-run with the RUST_BACKTRACE=1 env
2024-01-18T20:28:07.595740840Z var set and include the backtrace in your report.
2024-01-18T20:28:07.595745940Z
2024-01-18T20:28:07.595749540Z Platform: linux x86_64
2024-01-18T20:28:07.595753240Z Version: 1.38.3
2024-01-18T20:28:07.612258110Z Args: ["deno<unnamed>", ' panicked at "run/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/denokv_sqlite-0.2.1/lib.rs", :137:17:
2024-01-18T20:28:07.613381214Z "KV collect expired failed: database disk image is malformed-A
2024-01-18T20:28:07.613923617Z "stack backtrace:
2024-01-18T20:28:07.613940017Z , "--unstable", "main.ts"]
2024-01-18T20:28:07.613944317Z
2024-01-18T20:28:07.613947917Z thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/denokv_sqlite-0.2.1/lib.rs:137:17:
2024-01-18T20:28:07.614546519Z KV collect expired failed: database disk image is malformed
2024-01-18T20:28:07.777222905Z Using snapshot found at [36m/app/_fresh[39m
2024-01-18T20:28:07.809555642Z
2024-01-18T20:28:07.810283845Z [48;5;121m[38;5;0m 🍋 Fresh ready [39m[49m
2024-01-18T20:28:07.810305745Z     [1mLocal:[22m [36mhttp://localhost:8000/[39m
2024-01-18T20:28:07.810313045Z
2024-01-18T20:28:07.928877845Z    0: rust_begin_unwind
2024-01-18T20:28:07.934042267Z              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
2024-01-18T20:28:07.934061867Z    1: core::panicking::panic_fmt
2024-01-18T20:28:07.934067367Z              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
2024-01-18T20:28:07.944977913Z    2: denokv_sqlite::sqlite_thread::{{closure}}
2024-01-18T20:28:07.947630424Z note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2024-01-18T20:28:07.952122443Z stack backtrace:
2024-01-18T20:28:07.952744246Z    0: rust_begin_unwind
2024-01-18T20:28:07.962813388Z              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
2024-01-18T20:28:07.962834488Z    1: core::panicking::panic_fmt
2024-01-18T20:28:07.962839788Z              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
2024-01-18T20:28:08.248307689Z
2024-01-18T20:28:08.366Z ERROR - Container biotech-manager-web_0_1a976689 for site biotech-manager-web has exited, failing site start
2024-01-18T20:28:08.376Z ERROR - Container biotech-manager-web_0_1a976689 didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.
2024-01-18T20:28:08.402Z INFO  - Stopping site biotech-manager-web because it failed during startup.
```

**Comment by bartlomieju** [comment]
The reported panic is no longer reproducible on current Deno - a malformed KV database now surfaces a catchable error instead of crashing the process.

Tested with a deliberately corrupted SQLite KV file, two ways:

- Foreground KV operation on the corrupt DB -> `Error: database disk image is malformed` (catchable), no panic.
- Idling with a pending expiry, so the background "collect expired" path (the one in the original backtrace) runs -> same `Error: database disk image is malformed` as a normal promise rejection, no panic.

In both cases the process does not abort with "Deno has panicked", so the original failure (a hard panic killing the container on startup) doesn't happen anymore.

Note the underlying cause is unchanged and environmental: as @losfair pointed out, the SQLite file itself was corrupted - typically from broken file locking (e.g. NFS), copying the DB while open, or copying without the `-wal` file. Deno isn't producing bad data; it now just reports the corruption gracefully.

Closing since the panic is resolved into a graceful error. If you can still reproduce an actual panic ("Deno has panicked") on a current version, please reopen with the database/filesystem details and a repro.
