### ISSUE TITLE
Can not run `drizzle-kit`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#22006]
Version: Deno 1.39.1

```
❯❯❯ deno run -A npm:drizzle-kit
error: Uncaught Error: Cannot find module 'drizzle-orm/pg-core'
Require stack:
- /Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/drizzle-kit/0.20.13/bin.cjs
    at Function.Module._resolveFilename (node:module:622:15)
    at Function.Module._load (node:module:500:27)
    at Module.require (node:module:675:19)
    at require (node:module:789:16)
    at src/serializer/pgImports.ts (file:///Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/drizzle-kit/0.20.13/bin.cjs:12132:22)
    at __init (file:///Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/drizzle-kit/0.20.13/bin.cjs:8:56)
    at src/utils.ts (file:///Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/drizzle-kit/0.20.13/bin.cjs:60405:5)
    at __init (file:///Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/drizzle-kit/0.20.13/bin.cjs:8:56)
    at Object.<anonymous> (file:///Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/drizzle-kit/0.20.13/bin.cjs:62056:1)
    at Object.<anonymous> (file:///Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/drizzle-kit/0.20.13/bin.cjs:63876:4)
```

**Comment by lucacasonato** [comment]
Duplicate of https://github.com/denoland/deno/issues/19826
