### ISSUE TITLE
[lsp] naming a file `main\da.ts` breaks the LSP

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#22052]
Version: Deno 1.39.4

```
Error getting document symbols for "file:///mnt/artemis/Projects/github.com/denoland/deno/foo/main\da.ts": Error: Could not find file: 'file:///mnt/artemis/Projects/github.com/denoland/deno/foo/main\da.ts'.
    at SyntaxTreeCache.getCurrentSourceFile (ext:deno_tsc/00_typescript.js:144782:19)
    at Object.getNavigationTree2 [as getNavigationTree] (ext:deno_tsc/00_typescript.js:143500:48)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1070:53)
    at [ext:cli/lsp/tsc.rs:4557:26]:1:12
[Error - 17:58:50] Request textDocument/documentSymbol failed.
  Message: Internal error
  Code: -32603 
```

**Comment by nayeemrmn** [comment]
This is caused by https://github.com/servo/rust-url/issues/901. We could work around it in the document URL mapper, but it wouldn't fix other places where `Url::from_file_path()` is used.

**Comment by lucacasonato** [comment]
Yikes. Good find

**Comment by nayeemrmn** [comment]
This should be fixed now.
