### ISSUE TITLE
Deno.serve crash when import std/dotenv/load.ts

### ISSUE THREAD

**Issue by gabobaxx** [denoland/deno#22136]
Version: Deno 1.40.2
Version: Fresh 1.6.3

```
error: Uncaught (in promise) PermissionDenied: Permission denied (os error 13)
    await Deno.serve(
               ^
    at listen (ext:deno_net/01_net.js:517:35)
    at Object.serve (ext:deno_http/00_serve.js:592:16)
    at bootServer (https://deno.land/x/fresh@1.6.3/src/server/boot.ts:78:16)
    at startServer (https://deno.land/x/fresh@1.6.3/src/server/boot.ts:39:11)
    at dev (https://deno.land/x/fresh@1.6.3/src/dev/dev_command.ts:58:11)
    at eventLoopTick (ext:core/01_core.js:63:7)
    at async file:///home/gabo/workspaces/projects/refribenco/refribenco.com/dev.ts:6:1
```

![2024-01-26-164803_965x379_scrot](https://github.com/denoland/deno/assets/59029788/683d5a29-9352-4f5b-ad7b-d0ffc9b2cdab)
![code](https://github.com/denoland/deno/assets/59029788/e5168b69-08ab-49c3-b31c-3d1bf0e2c68a)

**Comment by kt3k** [comment]
Are you on Linux?

Do you have `PORT` set in `.env` file?

**Comment by gabobaxx** [comment]
> Are you on Linux?
> 
> 
> 
> Do you have `PORT` set in `.env` file?

Yes, I'm on Linux. And Yes, I forgot that PORT was set in .env 😅

Now, it is working. Thanks 🙏

**Comment by kt3k** [comment]
Glad to hear it's fixed!
