### ISSUE TITLE
killSuccess is flaky on linux

### ISSUE THREAD

**Issue by ry** [denoland/deno#2219]
[example log](https://travis-ci.com/denoland/deno/jobs/195813103)
```
test killSuccess_permR0W0N0E0U1H0 Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 68, in <module>
    import os
  File "/usr/lib/python2.7/os.py", line 398, in <module>
    import UserDict
  File "/usr/lib/python2.7/UserDict.py", line 83, in <module>
    import _abcoll
  File "/usr/lib/python2.7/_abcoll.py", line 11, in <module>
    from abc import ABCMeta, abstractmethod
  File "/usr/lib/python2.7/abc.py", line 4, in <module>
    """Abstract Base Classes (ABCs) according to PEP 3119."""
KeyboardInterrupt
... FAILED
Error: 
    [Diff] Left / Right
-   1
+   undefined
    at assertEquals (/home/travis/build/denoland/deno/js/deps/https/deno.land/std/testing/pretty.ts:66:11)
    at assertEquals (/home/travis/build/denoland/deno/js/deps/https/deno.land/std/testing/asserts.ts:53:5)
    at killSuccess (/home/travis/build/denoland/deno/js/process_test.ts:233:9)
    at async runTestsSerial (/home/travis/build/denoland/deno/js/deps/https/deno.land/std/testing/mod.ts:112:13)
    at async runTests (/home/travis/build/denoland/deno/js/deps/https/deno.land/std/testing/mod.ts:147:9)
    at async main (/home/travis/build/denoland/deno/js/deps/https/deno.land/std/testing/main.ts:5:5)
```
cc @kevinkassimo

**Comment by kevinkassimo** [comment]
It fails due to the following lines:
```ts
const status = await p.status();
// ...
assertEquals(status.code, undefined); // status.code sometimes becomes 1 instead of undefined
```
I think this might instead imply flakiness of some other `process` related APIs. Needs investigation

**Comment by kevinkassimo** [comment]
Also could not reproduce the failure in my Ubuntu virtual machine.
