### ISSUE TITLE
[bug][NPM] `Error: listen UNKNOWN: unknown error` running npm:@web/test-runner

### ISSUE THREAD

**Issue by niedzielski** [denoland/deno#22218]
Version: Deno 1.40.2
deno 1.40.2 (release, x86_64-unknown-linux-gnu)
v8 12.1.285.6
typescript 5.3.3

When I try to run [npm:@web/test-runner](https://modern-web.dev/guides/test-runner/getting-started), I get an error that looks kind of like address in use:

```
$ deno run --allow-env --allow-ffi --allow-net --allow-read --allow-sys npm:@web/test-runner
Error: listen UNKNOWN: unknown error ffff::eeee:dddd:cccc:bbbb:8000
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:91:9)
    at __node_internal_uvExceptionWithHostPort (ext:deno_node/internal/errors.ts:122:10)
    at Server._setupListenHandle [as _listen2] (node:net:1179:16)
    at _listenInCluster (node:net:1011:12)
    at doListen (node:net:1021:7)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:36:15)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:70:21) {
  code: "UNKNOWN",
  errno: -4094,
  syscall: "listen",
  address: "ffff::eeee:dddd:cccc:bbbb",
  port: 8000
}
```

(I've mangled the IP.) The port does not appear to be in use. The expected output for no tests is:

```
$ npx @web/test-runner 

Error: Did not find any tests to run. Use the "files" or "groups" option to configure test files.
```

**Comment by bartlomieju** [comment]
I can't reproduce it anymore on v.2.7.4, I get the expected output when no tests are found.
