### ISSUE TITLE
Improve compatibility with node-stream-zip

### ISSUE THREAD

**Issue by prabhu** [denoland/deno#22238]
Version: Deno 1.40.3

https://github.com/antelle/node-stream-zip

Attempting to unzip using this package results in an out of range error.

```js
const zip = new StreamZip.async({ file: zipFile });
const entriesCount = await zip.entriesCount;
const entries = await zip.entries();
```

```shell
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0. Received -52
    at __node_internal_ (ext:deno_node/internal/fs/utils.mjs:713:13)
    at Object.read (ext:deno_node/_fs/_fs_read.ts:57:3)
    at FsRead.read (file:///mnt/work/CycloneDX/cdxgen/node_modules/.deno/node-stream-zip@1.15.0/node_modules/node-stream-zip/node_stream_zip.js:979:16)
    at FsRead.readCallback (file:///mnt/work/CycloneDX/cdxgen/node_modules/.deno/node-stream-zip@1.15.0/node_modules/node-stream-zip/node_stream_zip.js:998:18)
    at ext:deno_node/_fs/_fs_read.ts:72:7
    at eventLoopTick (ext:core/01_core.js:64:7) {
  code: "ERR_OUT_OF_RANGE",
  name: "RangeError"
}
```

**Comment by nathanwhit** [comment]
Looks like this was fixed by #25049, and is now working on the latest version of deno (1.46.1).

Feel free to reopen if you still experience issues!
