### ISSUE TITLE
Deno.fstatSync is not a function

### ISSUE THREAD

**Issue by felix-schindler** [denoland/deno#22319]
Version: Deno v1.40

I can see [in the documentation](https://deno.land/api@v1.40.3?s=Deno.fstatSync) that `Deno.fstatSync` will be removed in the future.

> [!CAUTION]
> Use file.statSync() instead. [Deno.fstatSync](https://deno.land/api?s=Deno.fstatSync) will be removed in Deno 2.0.

But I'm pretty sure it should be a function right now.

I'm encountering this issue when deploying [something](https://github.com/felix-schindler/ip-lookup) to Deno Deploy. It seems to occur within the Node compatibility layer.

```
Uploading 1 asset(s) (94.2%)
Uploading 1 asset(s) (100.0%)
Deploying... (100.0%)
Finishing deployment...
Error: The deployment failed: UNCAUGHT_EXCEPTION

TypeError: Deno.fstatSync is not a function
    at Object.fstatSync (ext:deno_node/_fs/_fs_fstat.ts:14:23)
    at preload (file:///node_modules/.deno/geoip-lite@1.4.9/node_modules/geoip-lite/lib/geoip.js:323:17)
    at Object.<anonymous> (file:///node_modules/.deno/geoip-lite@1.4.9/node_modules/geoip-lite/lib/geoip.js:535:1)
    at Object.<anonymous> (file:///node_modules/.deno/geoip-lite@1.4.9/node_modules/geoip-lite/lib/geoip.js:541:4)
    at Module._compile (node:module:731:34)
    at Object.Module._extensions..js (node:module:745:10)
    at Module.load (node:module:656:32)
    at Function.Module._load (node:module:537:12)
    at Module.require (node:module:675:19)
    at require (node:module:789:[16](https://github.com/felix-schindler/ip-lookup/actions/runs/7810963252/job/21305222667#step:6:17))
```

**Comment by lucacasonato** [comment]
The node compat code is calling out to `Deno.fstatSync`. It shouldn't do this - looks like a bug.

**Comment by iuioiua** [comment]
This should be fixed. I'll close this now. @felix-schindler, please re-open this issue if this is still an issue for you.

**Comment by felix-schindler** [comment]
I mean... I guess it's a different error now so should be fixed! 😂

https://github.com/felix-schindler/ip-lookup/commit/06f2f4c6a5b901457ee28c70afb70da97a4cb606#commitcomment-143237743

<img width="469" alt="Screenshot 2024-06-18 at 11 57 42" src="https://github.com/denoland/deno/assets/65357346/4e84b718-49da-463c-9025-c5a53b1444ee">

**Comment by iuioiua** [comment]
Can you please report the bug [here](https://github.com/denoland/deploy_feedback/issues/new?assignees=&labels=&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)?
