### ISSUE TITLE
REPL fails to parse a function which contains a regular expression

### ISSUE THREAD

**Issue by kellnerd** [denoland/deno#22328]
Version: Deno 1.40.2

```ts
function test(input: string): string {
  return input.replace(/a/, 'b');
}
```

Pasting the above code into a Deno REPL causes a parser error:

```ts
$ deno
Deno 1.40.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> function test(input: string): string {
  return input.replace(/a/, 'b');
parse error: Expected '}', got '<eof>' at 2:33
> }
```

Defining the regular expression on a separate line does not help, the REPL only errors one line earlier:

```ts
> function test(input: string): string {
  const regex = /a/;
parse error: Expected '}', got '<eof>' at 2:20
>   return input.replace(regex, "b");
Uncaught SyntaxError: Illegal return statement
> }
```

The only thing which works is defining a global variable:

```ts
> const regex = /a/;
undefined
> function test(input: string): string {
  return input.replace(regex, "b");
}
undefined
```

**Comment by safaa-mojahed** [comment]
@kellnerd 
I tried the above code on Deno 1.43.6 and it worked
![image](https://github.com/denoland/deno/assets/42294003/8150bbe7-1a5c-413d-9de3-210674c83cbf)

I used Cntr + s to add a new line

**Comment by lucacasonato** [comment]
I also can not reproduce in Deno 1.44.2+78b12a4

**Comment by kellnerd** [comment]
You are right, I can no longer reproduce this either by pasting all three lines at once.
But if I type the code into the REPL, the error still occurs as soon as I hit enter at the end of the second line.

**Comment by tats-u** [comment]
Regex literals cause syntax errors in conditional expressions in `if`, `while`, and `for`:

```js
PS> deno
Deno 2.8.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> if (/regex/) {
error: SyntaxError: Expected '}', got '<eof>'
  |
1 | if (/regex/) {
  |            ~
    at file:///repl.tsx:1:12
```

```js
PS> node
Welcome to Node.js v24.16.0.
Type ".help" for more information.
> if (/regex/) {
| console.log("Deno sucks!")
| }
Deno sucks!
undefined
```

```js
> while(/regex/)
parse error: Expression expected at 1:7
> while(/regex/) {
error: SyntaxError: Expected '}', got '<eof>'
  |
1 | while(/regex/) {
  |              ~
    at file:///repl.tsx:1:14
> for(;/regex/;) {
error: SyntaxError: Expected '}', got '<eof>'
  |
1 | for(;/regex/;) {
  |              ~
    at file:///repl.tsx:1:14
```

Also, related to #24963

**Comment by tats-u** [comment]
@lucacasonato Reproducible by copying all the 3 lines and pasting them on the Deno REPL at once in the current version:

```
PS> deno
Deno 2.8.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> function test(input: string): string {
  return input.replace(/a/, 'b');
error: SyntaxError: Expected '}', got '<eof>'
  |
2 |   return input.replace(/a/, 'b');
  |                                ~
    at file:///repl.tsx:2:32
> }
```

Windows 11 + Windows Terminal
