### ISSUE TITLE
Deno panic on `deno check` when import map has https scopes

### ISSUE THREAD

**Issue by JumpLink** [denoland/deno#22353]
## Deno Version
Deno Version 1.40.4 and 1.40.3 (Possibly also older)

## Error

```bash
RUST_BACKTRACE=1 deno check test.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.40.3
Args: ["/home/jumplink/AppImages/gearlever_cursor_0efde0.appimage", "check", "test.ts"]

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/import_map-0.18.2/src/ext.rs:127:62:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:127:5
   3: core::option::Option<T>::unwrap
   4: import_map::ext::create_synthetic_import_map
   5: deno::args::CliOptions::resolve_import_map::{{closure}}
   6: deno::factory::CliFactory::maybe_import_map::{{closure}}
   7: deno::factory::CliFactory::resolver::{{closure}}
   8: deno::factory::CliFactory::module_graph_builder::{{closure}}
   9: deno::factory::CliFactory::module_load_preparer::{{closure}}
  10: deno::spawn_subcommand::{{closure}}
  11: <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
  12: tokio::runtime::task::raw::poll
  13: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Reproduce

```bash
touch test.ts
deno check test.ts
```

**Comment by JumpLink** [comment]
The error also occurs with Deno version 1.40.4

**Comment by dsherret** [comment]
@JumpLink what's the content of your import map/deno.json file?

**Comment by JumpLink** [comment]
@dsherret Oh you are right, without the deno.json the problem does not occur, you can find [my deno.json file here](https://github.com/beabee-communityrm/telegram-bot/blob/7162206b6b835ab782dc4a5f810af459a1659eda/deno.jsonc).
