### ISSUE TITLE
WritableStream write() only accepts Uint8Array and not any ArrayBufferView

### ISSUE THREAD

**Issue by e3dio** [denoland/deno#22381]
Version: Deno 1.40.4

Using `Deno.connect()` and writing to stream, `writer.write()` is supposed to take any `ArrayBufferView` but instead throws for anything other than `Uint8Array`

```js
const port = 3006;
const server = Deno.serve({ port }, r => new Response());
const tcp = await Deno.connect({ port });
const w = tcp.writable.getWriter();

await w.write(new Uint8Array(1));
await w.write(new Uint16Array(1)); // throws
await w.write(new Uint32Array(1)); // throws
await w.write(new BigUint64Array(1)); // throws
await w.write(new ArrayBuffer(1)); // throws
await w.write(new DataView(new ArrayBuffer(1))); // throws
```

If the stream only accepts writing with `Uint8Array`, the error message should say `Uint8Array` not `ArrayBufferView`

```
TypeError: expected typed ArrayBufferView
await w.write(new Uint16Array(1));
        ^
    at Object.write (ext:deno_web/06_streams.js:1155:20)
    at Module.invokeCallbackFunction (ext:deno_webidl/00_webidl.js:944:16)
    at WritableStreamDefaultController.writeAlgorithm (ext:deno_web/06_streams.js:3915:14)
    at writableStreamDefaultControllerProcessWrite (ext:deno_web/06_streams.js:4485:55)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (ext:deno_web/06_streams.js:4388:5)
    at writableStreamDefaultControllerWrite (ext:deno_web/06_streams.js:4532:3)
    at writableStreamDefaultWriterWrite (ext:deno_web/06_streams.js:4679:3)
    at WritableStreamDefaultWriter.write (ext:deno_web/06_streams.js:6602:12)
```

**Comment by Iuriiiiiii** [comment]
Something new about this?
