### ISSUE TITLE
LSP frequently fails to suggest quick fix auto-import

### ISSUE THREAD

**Issue by cknight** [denoland/deno#22391]
Version: Deno 1.40.4
VS Code extension version: v3.33.3

I am often (but not always) finding recently that after typing the name of an exported function in another of my modules, the quick fix popup doesn't give a suggestion to import:

<img width="585" alt="image" src="https://github.com/denoland/deno/assets/1248238/35f479df-e406-4fac-9a5b-2d35874361a6">

The function `getExportStatus` exists in my project in another module and is not new.  
```ts
export function getExportStatus(id: string): ExportStatus | undefined {
  return exportStatus.get(id);
}
```
The following info is in the output tab:

```
Starting Deno language server...
  version: 1.40.4 (release, aarch64-apple-darwin)
  executable: /Users/chris/.deno/bin/deno
Connected to "Visual Studio Code" 1.86.1
  Auto-resolved configuration file: "file:///Users/chris/dev/deno/kv-client/deno.json"
Setting import map defined in configuration file: "file:///Users/chris/dev/deno/kv-client/deno.json"
  Resolved import map: "file:///Users/chris/dev/deno/kv-client/deno.json"
Enabling import suggestions for: https://deno.land
Server ready.
Error getting actions from TypeScript: Error: Debug Failure. 7006
    at doChange32 (ext:deno_tsc/00_typescript.js:153635:22)
    at ext:deno_tsc/00_typescript.js:154498:27
    at Function.with (ext:deno_tsc/00_typescript.js:168701:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:154497:68)
    at ext:deno_tsc/00_typescript.js:145974:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:145974:12)
    at ext:deno_tsc/00_typescript.js:143585:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:143583:14)
Error getting actions from TypeScript: Error: Debug Failure. 7006
    at doChange32 (ext:deno_tsc/00_typescript.js:153635:22)
    at ext:deno_tsc/00_typescript.js:154498:27
    at Function.with (ext:deno_tsc/00_typescript.js:168701:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:154497:68)
    at ext:deno_tsc/00_typescript.js:145974:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:145974:12)
    at ext:deno_tsc/00_typescript.js:143585:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:143583:14)
Unable to get completion info from TypeScript: TypeError: host.watchNodeModulesForPackageJsonChanges is not a function
    at Object.set (ext:deno_tsc/00_typescript.js:179660:24)
    at Object.getModuleSpecifiersWithCacheInfo (ext:deno_tsc/00_typescript.js:45041:36)
    at getModuleSpecifiers2 (ext:deno_tsc/00_typescript.js:149583:308)
    at ext:deno_tsc/00_typescript.js:149598:58
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at getNewImportFixes (ext:deno_tsc/00_typescript.js:149596:19)
    at getFixesForAddImport (ext:deno_tsc/00_typescript.js:149650:69)
    at getImportFixes (ext:deno_tsc/00_typescript.js:149412:54)
    at Object.getModuleSpecifierForBestExportInfo (ext:deno_tsc/00_typescript.js:149300:52)
    at Object.tryResolve (ext:deno_tsc/00_typescript.js:156668:34)
Error getting actions from TypeScript: Error: Debug Failure. 7006
    at doChange32 (ext:deno_tsc/00_typescript.js:153635:22)
    at ext:deno_tsc/00_typescript.js:154498:27
    at Function.with (ext:deno_tsc/00_typescript.js:168701:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:154497:68)
    at ext:deno_tsc/00_typescript.js:145974:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:145974:12)
    at ext:deno_tsc/00_typescript.js:143585:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:143583:14)
Error getting actions from TypeScript: Error: Debug Failure. 7006
    at doChange32 (ext:deno_tsc/00_typescript.js:153635:22)
    at ext:deno_tsc/00_typescript.js:154498:27
    at Function.with (ext:deno_tsc/00_typescript.js:168701:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:154497:68)
    at ext:deno_tsc/00_typescript.js:145974:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:145974:12)
    at ext:deno_tsc/00_typescript.js:143585:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:143583:14)
Unable to get completion info from TypeScript: TypeError: host.watchNodeModulesForPackageJsonChanges is not a function
    at Object.set (ext:deno_tsc/00_typescript.js:179660:24)
    at Object.getModuleSpecifiersWithCacheInfo (ext:deno_tsc/00_typescript.js:45041:36)
    at getModuleSpecifiers2 (ext:deno_tsc/00_typescript.js:149583:308)
    at ext:deno_tsc/00_typescript.js:149598:58
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at getNewImportFixes (ext:deno_tsc/00_typescript.js:149596:19)
    at getFixesForAddImport (ext:deno_tsc/00_typescript.js:149650:69)
    at getImportFixes (ext:deno_tsc/00_typescript.js:149412:54)
    at Object.getModuleSpecifierForBestExportInfo (ext:deno_tsc/00_typescript.js:149300:52)
    at Object.tryResolve (ext:deno_tsc/00_typescript.js:156668:34)
Unable to get completion info from TypeScript: TypeError: host.watchNodeModulesForPackageJsonChanges is not a function
    at Object.set (ext:deno_tsc/00_typescript.js:179660:24)
    at Object.getModuleSpecifiersWithCacheInfo (ext:deno_tsc/00_typescript.js:45041:36)
    at getModuleSpecifiers2 (ext:deno_tsc/00_typescript.js:149583:308)
    at ext:deno_tsc/00_typescript.js:149598:58
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at getNewImportFixes (ext:deno_tsc/00_typescript.js:149596:19)
    at getFixesForAddImport (ext:deno_tsc/00_typescript.js:149650:69)
    at getImportFixes (ext:deno_tsc/00_typescript.js:149412:54)
    at Object.getModuleSpecifierForBestExportInfo (ext:deno_tsc/00_typescript.js:149300:52)
    at Object.tryResolve (ext:deno_tsc/00_typescript.js:156668:34)
Unable to get completion info from TypeScript: TypeError: host.watchNodeModulesForPackageJsonChanges is not a function
    at Object.set (ext:deno_tsc/00_typescript.js:179660:24)
    at Object.getModuleSpecifiersWithCacheInfo (ext:deno_tsc/00_typescript.js:45041:36)
    at getModuleSpecifiers2 (ext:deno_tsc/00_typescript.js:149583:308)
    at ext:deno_tsc/00_typescript.js:149598:58
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at getNewImportFixes (ext:deno_tsc/00_typescript.js:149596:19)
    at getFixesForAddImport (ext:deno_tsc/00_typescript.js:149650:69)
    at getImportFixes (ext:deno_tsc/00_typescript.js:149412:54)
    at Object.getModuleSpecifierForBestExportInfo (ext:deno_tsc/00_typescript.js:149300:52)
    at Object.tryResolve (ext:deno_tsc/00_typescript.js:156668:34)
Error getting actions from TypeScript: Error: Debug Failure. 7006
    at doChange32 (ext:deno_tsc/00_typescript.js:153635:22)
    at ext:deno_tsc/00_typescript.js:154498:27
    at Function.with (ext:deno_tsc/00_typescript.js:168701:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:154497:68)
    at ext:deno_tsc/00_typescript.js:145974:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:145974:12)
    at ext:deno_tsc/00_typescript.js:143585:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:143583:14)
Error getting actions from TypeScript: Error: Debug Failure. 7006
    at doChange32 (ext:deno_tsc/00_typescript.js:153635:22)
    at ext:deno_tsc/00_typescript.js:154498:27
    at Function.with (ext:deno_tsc/00_typescript.js:168701:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:154497:68)
    at ext:deno_tsc/00_typescript.js:145974:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:145974:12)
    at ext:deno_tsc/00_typescript.js:143585:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:143583:14)
Error getting actions from TypeScript: Error: Debug Failure. 7005
    at doChange32 (ext:deno_tsc/00_typescript.js:153635:22)
    at ext:deno_tsc/00_typescript.js:154498:27
    at Function.with (ext:deno_tsc/00_typescript.js:168701:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:154497:68)
    at ext:deno_tsc/00_typescript.js:145974:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:145974:12)
    at ext:deno_tsc/00_typescript.js:143585:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:143583:14)
Error getting actions from TypeScript: Error: Debug Failure. 7006
    at doChange32 (ext:deno_tsc/00_typescript.js:153635:22)
    at ext:deno_tsc/00_typescript.js:154498:27
    at Function.with (ext:deno_tsc/00_typescript.js:168701:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:154497:68)
    at ext:deno_tsc/00_typescript.js:145974:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:145974:12)
    at ext:deno_tsc/00_typescript.js:143585:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:143583:14)
Unable to get completion info from TypeScript: TypeError: host.watchNodeModulesForPackageJsonChanges is not a function
    at Object.set (ext:deno_tsc/00_typescript.js:179660:24)
    at Object.getModuleSpecifiersWithCacheInfo (ext:deno_tsc/00_typescript.js:45041:36)
    at getModuleSpecifiers2 (ext:deno_tsc/00_typescript.js:149583:308)
    at ext:deno_tsc/00_typescript.js:149598:58
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at getNewImportFixes (ext:deno_tsc/00_typescript.js:149596:19)
    at getFixesForAddImport (ext:deno_tsc/00_typescript.js:149650:69)
    at getImportFixes (ext:deno_tsc/00_typescript.js:149412:54)
    at Object.getModuleSpecifierForBestExportInfo (ext:deno_tsc/00_typescript.js:149300:52)
    at Object.tryResolve (ext:deno_tsc/00_typescript.js:156668:34)
```

<details>
<summary>Deno Language Server Status</summary>
# Deno Language Server Status

## Workspace Settings

```json
{
  "enable": true,
  "disablePaths": [],
  "enablePaths": null,
  "cache": null,
  "cacheOnSave": false,
  "certificateStores": null,
  "config": null,
  "importMap": null,
  "codeLens": {
    "implementations": false,
    "references": false,
    "referencesAllFunctions": false,
    "test": false
  },
  "internalDebug": false,
  "internalInspect": false,
  "logFile": false,
  "lint": true,
  "documentPreloadLimit": 1000,
  "suggest": {
    "imports": {
      "autoDiscover": true,
      "hosts": {
        "https://deno.land": true
      }
    }
  },
  "testing": {
    "args": [
      "--allow-all",
      "--no-check"
    ]
  },
  "tlsCertificate": null,
  "unsafelyIgnoreCertificateErrors": null,
  "unstable": true,
  "javascript": {
    "inlayHints": {
      "parameterNames": {
        "enabled": "none",
        "suppressWhenArgumentMatchesName": true
      },
      "parameterTypes": {
        "enabled": false
      },
      "variableTypes": {
        "enabled": false,
        "suppressWhenTypeMatchesName": true
      },
      "propertyDeclarationTypes": {
        "enabled": false
      },
      "functionLikeReturnTypes": {
        "enabled": false
      },
      "enumMemberValues": {
        "enabled": false
      }
    },
    "preferences": {
      "importModuleSpecifier": "shortest",
      "jsxAttributeCompletionStyle": "auto",
      "autoImportFileExcludePatterns": [],
      "useAliasesForRenames": true,
      "quoteStyle": "auto"
    },
    "suggest": {
      "completeFunctionCalls": false,
      "includeAutomaticOptionalChainCompletions": true,
      "includeCompletionsForImportStatements": true,
      "names": true,
      "paths": true,
      "autoImports": true,
      "enabled": true,
      "classMemberSnippets": {
        "enabled": true
      },
      "objectLiteralMethodSnippets": {
        "enabled": true
      }
    },
    "updateImportsOnFileMove": {
      "enabled": "prompt"
    }
  },
  "typescript": {
    "inlayHints": {
      "parameterNames": {
        "enabled": "none",
        "suppressWhenArgumentMatchesName": true
      },
      "parameterTypes": {
        "enabled": false
      },
      "variableTypes": {
        "enabled": false,
        "suppressWhenTypeMatchesName": true
      },
      "propertyDeclarationTypes": {
        "enabled": false
      },
      "functionLikeReturnTypes": {
        "enabled": false
      },
      "enumMemberValues": {
        "enabled": false
      }
    },
    "preferences": {
      "importModuleSpecifier": "shortest",
      "jsxAttributeCompletionStyle": "auto",
      "autoImportFileExcludePatterns": [],
      "useAliasesForRenames": true,
      "quoteStyle": "auto"
    },
    "suggest": {
      "completeFunctionCalls": false,
      "includeAutomaticOptionalChainCompletions": true,
      "includeCompletionsForImportStatements": true,
      "names": true,
      "paths": true,
      "autoImports": true,
      "enabled": true,
      "classMemberSnippets": {
        "enabled": true
      },
      "objectLiteralMethodSnippets": {
        "enabled": true
      }
    },
    "updateImportsOnFileMove": {
      "enabled": "prompt"
    }
  }
}
```

## Workspace Details

  - Documents in memory: 826

(... data trimmed to fit GitHub issue content limit  ...)

## Performance (last 3 000 entries)

|Name|Count|Duration|
|---|---|---|
|lsp.code_action|19|13.453ms|
|lsp.code_lens|7|0.005ms|
|lsp.completion|2|51.668ms|
|lsp.did_change|2|14.795ms|
|lsp.document_highlight|4|1.78ms|
|lsp.document_symbol|5|16.805ms|
|lsp.folding_range|4|23.843ms|
|lsp.get_navigation_tree|5|16.741ms|
|lsp.goto_definition|1|1.065ms|
|lsp.hover|3|2.281ms|
|lsp.semantic_tokens_full|4|2.907ms|
|lsp.testing_update|2|12.433ms|
|lsp.update_diagnostics_deps|2|1.772ms|
|lsp.update_diagnostics_lint|2|23.861ms|
|lsp.update_diagnostics_ts|1|34.006ms|
|tsc.host.$getDiagnostics|1|33.015ms|
|tsc.host.getApplicableRefactors|19|1.57ms|
|tsc.host.getCodeFixesAtPosition|6|16.91ms|
|tsc.host.getCompletionsAtPosition|2|49.276ms|
|tsc.host.getDefinitionAndBoundSpan|1|0.455ms|
|tsc.host.getDocumentHighlights|5|75.581ms|
|tsc.host.getEncodedSemanticClassifications|4|1.957ms|
|tsc.host.getNavigationTree|2|0.339ms|
|tsc.host.getOutliningSpans|4|1.035ms|
|tsc.host.getQuickInfoAtPosition|3|0.606ms|
|tsc.op.op_load|3|0.013ms|
|tsc.op.op_project_version|94|0.001ms|
|tsc.op.op_resolve|829|0.051ms|
|tsc.op.op_script_names|2|8.531ms|
|tsc.op.op_script_version|1917|0.009ms|
|tsc.request.getApplicableRefactors|19|6.898ms|
|tsc.request.getCodeFixesAtPosition|6|17.446ms|
|tsc.request.getCompletionsAtPosition|2|51.063ms|
|tsc.request.getDefinitionAndBoundSpan|1|0.71ms|
|tsc.request.getDocumentHighlights|4|1.151ms|
|tsc.request.getEncodedSemanticClassifications|4|2.432ms|
|tsc.request.getNavigationTree|2|41.342ms|
|tsc.request.getOutliningSpans|4|21.256ms|
|tsc.request.getQuickInfoAtPosition|3|1.195ms|

## Performance (total)

|Name|Count|Duration|
|---|---|---|
|lsp.cache|1|3393.498ms|
|lsp.code_action|1155|16365.674ms|
|lsp.code_action_resolve|1|51.041ms|
|lsp.code_lens|646|2.888ms|
|lsp.completion|222|10359.437ms|
|lsp.completion_resolve|219|5066.828ms|
|lsp.did_change|1596|14082.196ms|
|lsp.did_close|2|16.787ms|
|lsp.did_open|14|14.557ms|
|lsp.document_highlight|145|486.631ms|
|lsp.document_symbol|1280|10038.880ms|
|lsp.folding_range|599|3979.212ms|
|lsp.formatting|2|3.766ms|
|lsp.get_navigation_tree|1280|9976.189ms|
|lsp.goto_definition|14|33.267ms|
|lsp.hover|315|1841.520ms|
|lsp.initialize|1|80.976ms|
|lsp.references|1|25.608ms|
|lsp.rename|4|24.339ms|
|lsp.semantic_tokens_full|706|10759.617ms|
|lsp.semantic_tokens_range|11|971.865ms|
|lsp.signature_help|103|2079.651ms|
|lsp.testing_update|1501|16013.786ms|
|lsp.update_cache|1|0.000ms|
|lsp.update_diagnostics_deps|1502|1918.849ms|
|lsp.update_diagnostics_lint|1502|27063.964ms|
|lsp.update_diagnostics_ts|668|32692.185ms|
|lsp.update_import_map|1|0.067ms|
|lsp.update_registries|1|2.026ms|
|lsp.update_tsconfig|2|73.798ms|
|lsp.virtual_text_document|2|2.101ms|
|tsc.host.$configure|2|0.694ms|
|tsc.host.$getAssets|1|0.785ms|
|tsc.host.$getDiagnostics|666|38759.316ms|
|tsc.host.$getSupportedCodeFixes|1|0.222ms|
|tsc.host.$restart|1|0.143ms|
|tsc.host.findReferences|1|23.728ms|
|tsc.host.findRenameLocations|4|14.575ms|
|tsc.host.getApplicableRefactors|1143|3972.424ms|
|tsc.host.getCodeFixesAtPosition|283|3459.824ms|
|tsc.host.getCompletionEntryDetails|200|5002.579ms|
|tsc.host.getCompletionsAtPosition|209|8858.561ms|
|tsc.host.getDefinitionAndBoundSpan|14|19.037ms|
|tsc.host.getDocumentHighlights|144|1391.598ms|
|tsc.host.getEditsForRefactor|1|44.373ms|
|tsc.host.getEncodedSemanticClassifications|717|7006.289ms|
|tsc.host.getNavigationTree|772|615.582ms|
|tsc.host.getOutliningSpans|599|672.383ms|
|tsc.host.getQuickInfoAtPosition|315|1360.378ms|
|tsc.host.getSignatureHelpItems|103|1891.932ms|
|tsc.op.op_is_node_file|140|0.370ms|
|tsc.op.op_load|1979|55.840ms|
|tsc.op.op_project_version|23920|9.657ms|
|tsc.op.op_resolve|40993|1807.383ms|
|tsc.op.op_script_names|1028|10788.398ms|
|tsc.op.op_script_version|848219|6742.918ms|
|tsc.request.$configure|2|73.703ms|
|tsc.request.$getAssets|1|1.012ms|
|tsc.request.$getSupportedCodeFixes|1|0.274ms|
|tsc.request.$restart|1|1.661ms|
|tsc.request.findReferences|1|24.721ms|
|tsc.request.findRenameLocations|4|16.942ms|
|tsc.request.getApplicableRefactors|1153|11264.269ms|
|tsc.request.getCodeFixesAtPosition|283|3910.072ms|
|tsc.request.getCompletionEntryDetails|201|5007.252ms|
|tsc.request.getCompletionsAtPosition|209|9672.904ms|
|tsc.request.getDefinitionAndBoundSpan|14|24.673ms|
|tsc.request.getDocumentHighlights|145|344.712ms|
|tsc.request.getEditsForRefactor|1|46.041ms|
|tsc.request.getEncodedSemanticClassifications|717|11450.897ms|
|tsc.request.getNavigationTree|773|9722.786ms|
|tsc.request.getOutliningSpans|599|3767.937ms|
|tsc.request.getQuickInfoAtPosition|315|1528.332ms|
|tsc.request.getSignatureHelpItems|103|2046.542ms|

</details>

**Comment by cknight** [comment]
This is happening to be semi-frequently, perhaps several times per day.  However, I've found that if I restart the LSP it resolves the issue and it can then find the import.

**Comment by nayeemrmn** [comment]
@cknight @sergeysolovev Can you try running on `deno upgrade --canary`? #23131 may have fixed this.

**Comment by sergeysolovev** [comment]
> @cknight @sergeysolovev Can you try running on `deno upgrade --canary`? #23131 may have fixed this.

Upgraded to 99720d0713ecc17245e9b08652aadcb160d92cb8, it seems to be working, amazing! I’m going to test it more

**Comment by nayeemrmn** [comment]
Great! I'm going to close this for now, let's see if there are more reports.

**Comment by sergeysolovev** [comment]
I’m afraid it still doesn’t work for me. Steps: Add a new file with a new class, try to “Quick fix”-import it from another file - it’s not suggested in the list until I restart the language server. The only thing I see in the output is this:

```
Error getting actions from TypeScript: Error: Debug Failure. 7006
    at doChange33 (ext:deno_tsc/00_typescript.js:155332:22)
    at ext:deno_tsc/00_typescript.js:156195:27
    at Function.with (ext:deno_tsc/00_typescript.js:170707:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:156194:68)
    at ext:deno_tsc/00_typescript.js:147417:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:147417:12)
    at ext:deno_tsc/00_typescript.js:145014:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:145012:14)
```

I don’t have any issues like this when working from macos, only using Remote SSH into linux with Deno LSP installed on a remote machine.

**Comment by lucacasonato** [comment]
@sergeysolovev I can not reproduce this.

Can you open a new issue with a concrete reproduction?

**Comment by sergeysolovev** [comment]
@lucacasonato it’s been working fine for quite a while since I posted that last comment, amazing job!
