### ISSUE TITLE
Crashing when used with Mongo via NPM and SOCKS proxy

### ISSUE THREAD

**Issue by benlavalley** [denoland/deno#22390]
Deno 1.40.4 /  mongodb@6.3.0 via NPM / MacOS 14.2.1 

When used without a proxy, Mongo will connect fine. When used with a SOCKS 5 proxy, it crashes.

Can be reproduced by just running this snippet of code with a correct Socks5 proxy. If you fudge the username/password you'll see it fails to connect, but when they are correct -- and you'll see the logs in the proxy that it DOES make a connection -- it crashes immediately.

```
import { MongoClient } from 'npm:mongodb'

const url = 'mongodb+srv://mongouser:mongopassword@mongohost/yourmongodb?proxyHost=PROXYHOST&proxyPort=PROXYPORT&proxyUsername=PROXYUSERNAME&proxyPassword=PROXYPASSWORD'

const query = (db) => (collection) =>
  db
    .collection(collection)
    .find({}, { limit: 10 })
    .toArray()

async function main() {
  let client = new MongoClient(url)
  await client.connect()

  const db = client.db('users')

  await Promise.all(Array(10).fill('listingsAndReviews').map(query(db)))
    .then(res => console.log('results: ', res))
    .finally(() => client.close())
}

main()
Deno.serve((_req: Request) => {
  return new Response("Hello, world!");
});

```

Crash log:
Listening on http://localhost:8000/
error: Uncaught Error: write EBADF
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:91:9)
    at __node_internal_errnoException (ext:deno_node/internal/errors.ts:139:10)
    at WriteWrap.onWriteComplete [as oncomplete] (ext:deno_node/internal/stream_base_commons.ts:90:16)
    at TCP.#write (ext:deno_node/internal_binding/stream_wrap.ts:280:13)
    at Object.runMicrotasks (ext:core/01_core.js:586:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:72:21)

**Comment by mahdiyari** [comment]
I'm facing a similar issue on PostgreSQL using `npm:pg` library. It is reproducible for my application but I can't provide a snippet.
I can't catch the error using trycatch. I'm running the code in a worker and it crashes the worker without letting me to catch it inside the worker.

```
error: Uncaught (in worker "") Error: write EBADF
at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
at __node_internal_errnoException (ext:deno_node/internal/errors.ts:141:10)
at WriteWrap.onWriteComplete [as oncomplete] (ext:deno_node/internal/stream_base_commons.ts:90:16)
at TCP.#write (ext:deno_node/internal_binding/stream_wrap.ts:291:13)
at eventLoopTick (ext:core/01_core.js:175:7)
```

I grab a connection from the pool. Then BEGIN a transaction and run a lot of queries using that connection. The queries might run back to back but they all await.

**Comment by mahdiyari** [comment]
Turns out because of low `idle_in_transaction_session_timeout ` postgres kills the connection. But regardless a panic like this feels wrong. Increasing that timeout fixed my issue.

**Comment by Sleepful** [comment]
I was also facing the `Error: write EBADF` with the `npm:pg ` driver (which I could not change), it was a blocker to use `graphile-worker`. This was happening on Deno `2.0.3`.

The error went away once I upgraded to Deno version `2.1.4`.

**Comment by bartlomieju** [comment]
Unable to reproduce on Deno 2.7.4 canary. The `write EBADF` crash no longer occurs.

**Repro setup:**

Docker containers for MongoDB and SOCKS5 proxy:
```yaml
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
  socks-proxy:
    image: serjs/go-socks5-proxy
    ports: ["1080:1080"]
    environment:
      PROXY_USER: proxyuser
      PROXY_PASSWORD: proxypass
```

Test script:
```ts
import "npm:socks@2.7.1";
import { MongoClient } from "npm:mongodb@6.3.0";

const url = "mongodb://testuser:testpass@host.docker.internal:27017/admin?authSource=admin&directConnection=true&proxyHost=127.0.0.1&proxyPort=1080&proxyUsername=proxyuser&proxyPassword=proxypass";

const client = new MongoClient(url);
await client.connect();
const db = client.db("testdb");
await db.collection("test").insertOne({ hello: "world" });
const results = await db.collection("test").find({}).toArray();
console.log(results);
await Promise.all(Array(10).fill("test").map(c => db.collection(c).find({}, { limit: 10 }).toArray()));
await client.close();
```

**Result:** Connected, inserted, queried, ran 10 parallel queries, and closed cleanly. No `EBADF` error.

Closing as fixed. Please reopen if you can still reproduce on a recent Deno version.
