### ISSUE TITLE
Import modules from npm TypeORM error

### ISSUE THREAD

**Issue by asdfjklkk** [denoland/deno#22429]
Version: Deno 1.40.5

Hello: 
the following problem occurs when I use Deno version 1.40.x, but there is no problem when I use 1.39.4. Please help me, thank you.

Error message below:
Unable to resolve signature of class decorator when called as an expression.
  The runtime will invoke the decorator with 2 arguments, but the decorator expects 1

Runtime error below:
error: Uncaught (in promise) TypeError
    at Reflect.getMetadata (file:///C:/Users/xxx/AppData/Local/deno/npm/registry.npmjs.org/reflect-metadata/0.1.14/Reflect.js:354:23)
    at file:///C:/Users/xxx/AppData/Local/deno/npm/registry.npmjs.org/typeorm/0.3.19/decorator/columns/Column.js:26:23
    at memberDec (file:///D:/Temp/xxx/Deno1.39.4VersionDebugTypeORM/main.ts:78:14)
    at applyMemberDec (file:///D:/Temp/xxx/Deno1.39.4VersionDebugTypeORM/main.ts:159:18)
    at applyMemberDecs (file:///D:/Temp/xxx/Deno1.39.4VersionDebugTypeORM/main.ts:304:7)
    at applyDecs2203R (file:///D:/Temp/xxx/Deno1.39.4VersionDebugTypeORM/main.ts:366:13)
    at _apply_decs_2203_r (file:///D:/Temp/xxx/Deno1.39.4VersionDebugTypeORM/main.ts:377:56)
    at Function.<static_initializer> (file:///D:/Temp/VisualSxxxudioCodeProjects/Deno1.39.4VersionDebugTypeORM/main.ts:31:10)
    at file:///D:/Temp/xxx/Deno1.39.4VersionDebugTypeORM/main.ts:27:93

My Code:

`import {
    Column,
    Entity,
  } from "npm:typeorm@0.3.19";

@Entity({ database: "MGERP", schema: "dbo", name: "SYS_EMP" })
class SysEmpData {
  @Column({ name: "EMP_ID", type: "varchar", primary: true }) 
  //@PrimaryColumn({ name: "EMP_ID", type: "varchar" })
  public EmpId?: string;

  @Column({ name: "LOGIN_ID", type: "varchar" }) 
  public LoginId?: string;

  @Column({ name: "EMP_NAME", type: "varchar" }) 
  public EmpName?: string;

  @Column({ name: "TEAM_ID", type: "varchar" }) 
  public TeamId?: string;

  @Column({ name: "TEAM_NAME", type: "varchar", select: false, insert: false, update: false }) 
  public TeamName?: string;

  @Column({ name: "RANK_ID", type: "varchar" }) 
  public RankId?: string;

  @Column({ name: "RANK_NAME", type: "varchar", select: false, insert: false, update: false }) 
  public RankName?: string;

  @Column({ name: "EMAIL", type: "varchar" }) 
  public Email?: string;

  public constructor() {
  }
}`

**Comment by dsherret** [comment]
Try adding the following to your deno.json:

```json
{
  "compilerOptions": {
    "experimentalDecorators": true
  }
}
```

The default was changed to use ES decorators in 1.40 (https://deno.com/blog/v1.40#decorators)

**Comment by asdfjklkk** [comment]
@dsherret 
Problem solved, thank you very much.
