### ISSUE TITLE
bug: terminal-related tests fail in `deno_std` since 1.40.5

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#22445]
To reproduce, upgrade to 1.40.5 or canary and run `deno task test` while in the `std` repo. A series of tests that test terminal output are failing when run locally but not in CI. E.g.
```
Snapshot Test - Options ... msg ... missing snapshot => ./testing/snapshot_test.ts:256:13
error: AssertionError: Snapshot does not match:


    [Diff] Actual / Expected


-   [32m"[CUSTOM ERROR MESSAGE - MISSING SNAPSHOT]"[39m
+   "[CUSTOM ERROR MESSAGE - MISSING SNAPSHOT]"


    throw new AssertionError(
          ^
    at assertSnapshot (file:///Users/asher/GitHub/deno_std/testing/snapshot.ts:591:11)
    at async file:///Users/asher/GitHub/deno_std/testing/snapshot_test.ts:266:9
    at async innerWrapped (ext:cli/40_test.js:359:5)
    at async asyncOpSanitizer (ext:cli/40_test.js:181:27)
    at async exitSanitizer (ext:cli/40_test.js:288:27)
    at async Object.outerWrapped [as fn] (ext:cli/40_test.js:302:14)
    at async TestContext.step (ext:cli/40_test.js:648:22)
    at async file:///Users/asher/GitHub/deno_std/testing/snapshot_test.ts:256:5
```
I suspect this was caused by #21910. CC @crowlKats

**Comment by mmastrac** [comment]
I noticed that deno test | more is busted:

```
17:20 $ deno test /tmp/test.ts  | more
ESC[0mESC[38;5;245mrunning 10000 tests from ../../../../../../tmp/test.tsESC[0m
test0 ... ESC[0mESC[32mokESC[0m ESC[0mESC[38;5;245m(0ms)ESC[0m
test1 ... ESC[0mESC[32mokESC[0m ESC[0mESC[38;5;245m(0ms)ESC[0m
test2 ... ESC[0mESC[32mokESC[0m ESC[0mESC[38;5;245m(0ms)ESC[0m
test3 ... ESC[0mESC[32mokESC[0m ESC[0mESC[38;5;245m(0ms)ESC[0m
test4 ... ESC[0mESC[32mokESC[0m ESC[0mESC[38;5;245m(0ms)ESC[0m
test5 ... ESC[0mESC[32mokESC[0m ESC[0mESC[38;5;245m(0ms)ESC[0m
test6 ... ESC[0mESC[32mokESC[0m ESC[0mESC[38;5;245m(0ms)ESC[0m
```

**Comment by bartlomieju** [comment]
It might be caused by https://github.com/denoland/deno/pull/21910

**Comment by iuioiua** [comment]
This is fixed now.
