### ISSUE TITLE
Deno panic observed while evaluating a simple script in jitless mode - "unable to convert" at runtime\bindings.rs:131

### ISSUE THREAD

**Issue by std-move** [denoland/deno#22453]
Version: Deno 1.40.4 & 1.40.5 (1.40.3 and older seem to be fine)
Platform: Windows 11 x64 (10.0.22631.2861)

Input script (zipped): [panicking_input_script.zip](https://github.com/denoland/deno/files/14319572/panicking_input_script.zip)
Command to reproduce: `deno run --v8-flags=--jitless panicking_input_script.js`
Works fine without `--v8-flags=--jitless`

Note that in both 1.40.4 and 1.40.3, v8 version 12.1.285.6 is used. So this seems like a deno problem.

<details>
  <summary>Full backtrace</summary>

   ```
deno run --v8-flags=--jitless panicking_input_script.js
Warning: disabling flag --expose_wasm due to conflicting flags

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.40.4
Args: ["deno", "run", "--v8-flags=--jitless", "panicking_input_script.js"]

thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\deno_core-0.260.0\runtime\bindings.rs:131:25:
unable to convert
stack backtrace:
   0:     0x7ff7befeb5c3 - onig_get_syntax
   1:     0x7ff7bdacb7cd - onig_get_start_by_callout_args
   2:     0x7ff7befc9ca1 - onig_get_syntax
   3:     0x7ff7befef20a - onig_get_syntax
   4:     0x7ff7befeeb5f - onig_get_syntax
   5:     0x7ff7befee6d1 - onig_get_syntax
   6:     0x7ff7bd8badb1 - napi_fatal_error
   7:     0x7ff7befef573 - onig_get_syntax
   8:     0x7ff7befef3eb - onig_get_syntax
   9:     0x7ff7befef369 - onig_get_syntax
  10:     0x7ff7befef354 - onig_get_syntax
  11:     0x7ff7c05f3be7 - onig_unicode_define_user_property
  12:     0x7ff7bdc759f0 - onig_get_start_by_callout_args
  13:     0x7ff7bdc62021 - onig_get_start_by_callout_args
  14:     0x7ff7bdc5a56c - onig_get_start_by_callout_args
  15:     0x7ff7be85589c - onig_builtin_fail
  16:     0x7ff7bd887a1a - napi_fatal_error
  17:     0x7ff7bd886996 - napi_fatal_error
  18:     0x7ff7bd825c7c - napi_fatal_error
  19:     0x7ff7bd8ad562 - napi_fatal_error
  20:     0x7ff7bd3730a6 - <unknown>
  21:     0x7ff7bd98ee25 - napi_release_threadsafe_function
  22:     0x7ff7bd46e027 - napi_close_callback_scope
  23:     0x7ff7bd8bcd3c - napi_fatal_error
  24:     0x7ff7bd34cffe - <unknown>
  25:     0x7ff7bd355253 - <unknown>
  26:     0x7ff7c0597ebc - onig_unicode_define_user_property
  27:     0x7ffb1723257d - BaseThreadInitThunk
  28:     0x7ffb18b4aa58 - RtlUserThreadStart
```
</details>

Kindly do the needful for the same.

**Comment by std-move** [comment]
This is still an issue in the latest elease (version 1.41.3). Deno is panicking. Attaching full backtrace.
<details>
  <summary>Full backtrace</summary>

   ```
deno run --v8-flags=--jitless panicking_input_script.js
Warning: disabling flag --expose_wasm due to conflicting flags

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.41.3
Args: ["deno", "run", "--v8-flags=--jitless", "panicking_input_script.js"]

thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\deno_core-0.270.0\runtime\bindings.rs:199:25:
unable to convert
stack backtrace:
   0:     0x7ff69c050c62 - napi_release_threadsafe_function
   1:     0x7ff69aa9620d - napi_release_threadsafe_function
   2:     0x7ff69c02ebd1 - napi_release_threadsafe_function
   3:     0x7ff69c05461a - napi_release_threadsafe_function
   4:     0x7ff69c053f5f - napi_release_threadsafe_function
   5:     0x7ff69c053abb - napi_release_threadsafe_function
   6:     0x7ff69a84bf6c - napi_fatal_error
   7:     0x7ff69c054983 - napi_release_threadsafe_function
   8:     0x7ff69c0547fb - napi_release_threadsafe_function
   9:     0x7ff69c054779 - napi_release_threadsafe_function
  10:     0x7ff69c054762 - napi_release_threadsafe_function
  11:     0x7ff69d73f2d7 - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff69ac56e50 - napi_release_threadsafe_function
  13:     0x7ff69ac3aedd - napi_release_threadsafe_function
  14:     0x7ff69ac317dc - napi_release_threadsafe_function
  15:     0x7ff69b8985ec - napi_release_threadsafe_function
  16:     0x7ff69a8169ef - napi_fatal_error
  17:     0x7ff69a815701 - napi_fatal_error
  18:     0x7ff69a7b0db0 - napi_fatal_error
  19:     0x7ff69a82b2e5 - napi_fatal_error
  20:     0x7ff69a2bc42b - <unknown>
  21:     0x7ff69a92d715 - napi_release_threadsafe_function
  22:     0x7ff69a3d1787 - napi_cancel_async_work
  23:     0x7ff69a84e0bb - napi_fatal_error
  24:     0x7ff69a2a3e9b - <unknown>
  25:     0x7ff69a92d839 - napi_release_threadsafe_function
  26:     0x7ff69d6e30cc - CrashForExceptionInNonABICompliantCodeRange
  27:     0x7ffb1723257d - BaseThreadInitThunk
  28:     0x7ffb18b4aa58 - RtlUserThreadStart
```
</details>

Obviously this is a serious bug that should be fixed as `jitless` makes security issues much less likely to occur.

@littledivy Please take care and do the needful.

**Comment by 0f-0b** [comment]
The panic can be reproduced with an empty script.

```shellsession
$ RUST_BACKTRACE=1 deno run --v8-flags=--jitless /dev/null
Warning: disabling flag --expose_wasm due to conflicting flags

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.41.3+86cdf37
Args: ["deno", "run", "--v8-flags=--jitless", "/dev/null"]

thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.272.0/runtime/bindings.rs:199:25:
unable to convert
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: deno_core::runtime::bindings::get
   3: deno_core::runtime::jsruntime::JsRuntime::new_inner
   4: deno_core::runtime::jsruntime::JsRuntime::new
   5: deno_runtime::worker::MainWorker::from_options
   6: deno::worker::CliMainWorkerFactory::create_custom_worker::{{closure}}
   7: deno::worker::CliMainWorkerFactory::create_main_worker::{{closure}}
   8: deno::tools::run::run_script::{{closure}}
   9: deno::spawn_subcommand::{{closure}}
  10: <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
  11: tokio::runtime::task::raw::poll
  12: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Presumably this is caused by Deno [expecting the `WebAssembly` namespace to exist](https://github.com/denoland/deno_core/blob/a3d16d5439863bc9ae3dd0cfc2412c2e9214ea13/core/runtime/jsruntime.rs#L1267) which is not the case in JIT-less mode.
