### ISSUE TITLE
`deno compile` stops working after `deno vendor`

### ISSUE THREAD

**Issue by StarLederer** [denoland/deno#22494]
Version:
```
deno 1.38.2 (release, x86_64-unknown-linux-gnu)
v8 12.0.267.1
typescript 5.2.2
```

I am trying to vendor the dependencies of the following program (minimum reproduction) using `deno vendor`:
```ts
import { JSZip } from "https://deno.land/x/jszip@0.11.0/mod.ts";

const zip = new JSZip();
```

And then create an executable using `deno compile`. Unfortunately, even though the code compiles successfully before vendoring, I now get the following error:
```Check file:///home/team-output/deleteme/index.ts
error: Uncaught AssertionError: "data" is unexpectedly null for "https://esm.sh/v135/node.ns.d.ts".
    at assert (ext:deno_tsc/99_main_compiler.js:130:13)
    at Object.getSourceFile (ext:deno_tsc/99_main_compiler.js:574:7)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:120340:25)
    at findSourceFile (ext:deno_tsc/00_typescript.js:120260:22)
    at ext:deno_tsc/00_typescript.js:120209:24
    at getSourceFileFromReferenceWorker (ext:deno_tsc/00_typescript.js:120178:28)
    at processSourceFile (ext:deno_tsc/00_typescript.js:120207:7)
    at ext:deno_tsc/00_typescript.js:120479:9
    at forEach (ext:deno_tsc/00_typescript.js:55:24)
    at processReferencedFiles (ext:deno_tsc/00_typescript.js:120478:7)

```

Running the same program using `deno run --no-remote` works.

**Comment by lucacasonato** [comment]
`deno vendor` is deprecated, please use `vendor: true` in your `deno.json` instead.

**Comment by StarLederer** [comment]
Very interesting! Thanks a lot

**Comment by flaviavelosoqueiroz** [comment]
Hi everyone! How are you doing?
I'm having the same issue even when using vendor: true.

```
error: Module not found "https://esm.sh/v135/node.ns.d.ts".
at https://esm.sh/v135/@types/opossum@8.1.8/X-ZS9idWZmZXIsY3J5cHRvLGRucyxldmVudHMsZnMsaHR0cCxuZXQscXVlcnlzdHJpbmcscmVhZGxpbmUsc3RyZWFtLHRscyx1cmw/index.d.ts:1:21

```

Could you please help me?

Here are my settings:

deno 1.38.4 (release, aarch64-apple-darwin)
v8 12.0.267.1
typescript 5.2.2
