### ISSUE TITLE
node-compat: Missing `import { isBuiltin } from "node:module";`

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#22502]
Version: Deno 1.40.5

I tried running an example of `vinxi`, and got this:

```sh
[11:21:44 PM]  ERROR  The requested module 'node:module' does not provide an export named 'isBuiltin' at file:///Users/admin/repos/vinxi/examples/solid/spa/basic/node_modules/.deno/vinxi@0.3.3/node_modules/vinxi/lib/manifest/collect-styles.js:3:10

  at async Object.run (node_modules/.deno/vinxi@0.3.3/node_modules/vinxi/bin/cli.mjs:158:33)
  at async runCommand (node_modules/.deno/vinxi@0.3.3/node_modules/citty/dist/index.mjs:316:16)
  at async runCommand (node_modules/.deno/vinxi@0.3.3/node_modules/citty/dist/index.mjs:307:11)
  at async runMain (node_modules/.deno/vinxi@0.3.3/node_modules/citty/dist/index.mjs:445:7) 
```

Related to:
- #22337

**Comment by Farsen976** [comment]
Hey 👋, 
I'd like to tackle this task, in which file should I define the missing import?

**Comment by bartlomieju** [comment]
@Farsen976 you need to add it to `ext/node/polyfills/01_require.js`. You'll need to add a `isBuiltin` function that will check if the module is available in `nativeModuleExports` object.

**Comment by dsherret** [comment]
@Farsen976 it looks like you did a commit for this? Would you be able to open a PR with that commit? (Ideally with a test too)
