### ISSUE TITLE
/tools/format.js not working

### ISSUE THREAD

**Issue by muddlebee** [denoland/deno#22541]
Version: Latest

when I try to run  `./tools/format.js` from https://docs.deno.com/runtime/manual/references/contributing/#submitting-a-pr-to-deno

I get error 

```
→ ./tools/format.js 
error: Module not found "file:///home/muddles/Codes/denoland/deno/tests/util/std/path/mod.ts".
    at file:///home/muddles/Codes/denoland/deno/tools/util.js:8:8
```
    
```
→ deno run --allow-read --allow-write --allow-run ./tools/lint.js
error: Module not found "file:///home/muddles/Codes/denoland/deno/tests/util/std/path/mod.ts".
    at file:///home/muddles/Codes/denoland/deno/tools/util.js:8:8

```

**Comment by bartlomieju** [comment]
Please run `git submodule update --init --recursive`
