### ISSUE TITLE
Private class members are broken when you use a dynamic import to import @google-labs/breadboard

### ISSUE THREAD

**Issue by tmcw** [denoland/deno#22593]
Version: Deno 1.41.0

Here's a testcase:

mod.js:

```js
import { base } from "npm:@google-labs/breadboard@0.11.2";
import { Core, core } from "npm:@google-labs/core-kit@0.4.0";

const { result } = core.secrets({});
const output = base.output({});
```

importwrap:

```js
import("./mod.js");
```

Running this produces:

```
➜ deno run importwrap.ts
[Function: undefined]
error: Uncaught (in promise) TypeError: Cannot read private member #scope from an object whose class did not declare it
    at BuilderNode.addIncomingEdge (file:///Users/tmcw/tmp/20240226093347-26811/node_modules/.deno/@google-labs+breadboard@0.11.2/node_modules/@google-labs/breadboard/dist/src/new/grammar/node.js:108:32)
    at file:///Users/tmcw/tmp/20240226093347-26811/node_modules/.deno/@google-labs+breadboard@0.11.2/node_modules/@google-labs/breadboard/dist/src/new/grammar/node.js:103:32
    at Array.forEach (<anonymous>)
    at BuilderNode.addInputsFromNode (file:///Users/tmcw/tmp/20240226093347-26811/node_modules/.deno/@google-labs+breadboard@0.11.2/node_modules/@google-labs/breadboard/dist/src/new/grammar/node.js:96:22)
    at Value.to (file:///Users/tmcw/tmp/20240226093347-26811/node_modules/.deno/@google-labs+core-kit@0.4.0/node_modules/@google-labs/breadboard/dist/src/new/grammar/value.js:44:16)
    at file:///Users/tmcw/tmp/20240226093347-26811/mod.js:8:20
```

A static import, on the other hand, works  correctly:

```js
import x from "./mod.js";
```

**Comment by lucacasonato** [comment]
Closing as there was no response from the OP.
