### ISSUE TITLE
Deno workers: Uncaught (in worker "") Error: The language "undefined" has no grammar

### ISSUE THREAD

**Issue by tsaxking** [denoland/deno#22599]
Version info:
deno 1.40.3 (release, x86_64-unknown-linux-gnu)
v8 12.1.285.6
typescript 5.3.3

I am trying to start a server that starts up 10 other servers to spread the load off the main server using workers and any time I import something that has imports from 'npm' or 'https://deno.land/...', it throws this error and will not continue:
`error: Uncaught (in worker "") Error: The language "undefined" has no grammar.
    at Object.highlight (https://esm.sh/v133/prismjs@1.27.0/denonext/prismjs.mjs:3:4499)
    at https://esm.sh/v133/prismjs@1.27.0/denonext/prismjs.mjs:3:7533
    at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
    at invokeEventListeners (ext:deno_web/02_event.js:801:5)
    at dispatch (ext:deno_web/02_event.js:658:9)
    at dispatchEvent (ext:deno_web/02_event.js:1043:12)
    at pollForMessages (ext:runtime_main/js/99_main.js:286:7)
    at eventLoopTick (ext:core/01_core.js:64:7)`

Does anyone know what this issue is and how to handle it?

**Comment by lucacasonato** [comment]
Are you loading prism?
