### ISSUE TITLE
Deno REPL panicked with `already borrowed: BorrowMutError` when awaiting rejected promise returning async function

### ISSUE THREAD

**Issue by Piroro-hs** [denoland/deno#22592]
Version: Deno 1.40.4

```
Deno 1.40.4
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> async function test1() { throw "This one does not panic"; }
undefined
> await test1()
Uncaught "This one does not panic"
> async function test2() { return Promise.reject(); }
undefined
> await test2()

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.40.4
Args: ["deno"]

thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.260.0/runtime/exception_state.rs:143:62:
already borrowed: BorrowMutError
stack backtrace:
   0:     0x6491328145ca - <unknown>
   1:     0x649131732820 - <unknown>
   2:     0x6491327da40c - <unknown>
   3:     0x64913281749f - <unknown>
   4:     0x649132816d23 - <unknown>
   5:     0x649132816a47 - <unknown>
   6:     0x64913161fb0b - <unknown>
   7:     0x649132817a50 - <unknown>
   8:     0x6491328177ec - <unknown>
   9:     0x649132817746 - <unknown>
  10:     0x649132817731 - <unknown>
  11:     0x649131092bd4 - <unknown>
  12:     0x649131093096 - <unknown>
  13:     0x64913188f66b - <unknown>
  14:     0x649132d2c8d2 - <unknown>
  15:     0x6491336a5a7a - <unknown>
  16:     0x649133414af6 - <unknown>
```

**Comment by bartlomieju** [comment]
CC @mmastrac

**Comment by mmastrac** [comment]
Stack trace:

```
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::cell::panic_already_borrowed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/cell.rs:761:5
   3: core::cell::RefCell<T>::borrow_mut
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/cell.rs:1051:25
   4: deno_core::runtime::exception_state::ExceptionState::track_promise_rejection
             at /Users/matt/Documents/github/deno/deno_core/core/runtime/exception_state.rs:143:30
   5: deno_core::runtime::bindings::promise_reject_callback
             at /Users/matt/Documents/github/deno/deno_core/core/runtime/bindings.rs:676:3
```
