### ISSUE TITLE
`npm:@11ty/eleventy --serve` not working

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#22608]
```
divy@mini ~/g/n/11ty (main)> echo '# Page header' > index.md
divy@mini ~/g/n/11ty (main)> ls
index.md
divy@mini ~/g/n/11ty (main)> deno run -A npm:@11ty/eleventy
[11ty] Writing _site/index.html from ./index.md (liquid)
[11ty] Wrote 1 file in 0.04 seconds (v2.0.1)
divy@mini ~/g/n/11ty (main)> deno run -A npm:@11ty/eleventy --serve
[11ty] Writing _site/index.html from ./index.md (liquid)
[11ty] Wrote 1 file in 0.05 seconds (v2.0.1)
[11ty] Watching…
[11ty] Server at http://localhost:8080/
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] this.getHeaders is not a function (via TypeError)
[11ty]
[11ty] Original error stack trace: TypeError: this.getHeaders is not a function
[11ty]     at ServerResponse.resp.end (file:///Users/divy/Library/Caches/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/1.0.4/server/wrapResponse.js:98:66)
[11ty]     at EleventyDevServer.renderFile (file:///Users/divy/Library/Caches/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/1.0.4/server.js:411:18)
[11ty]     at EleventyDevServer.eleventyProjectMiddleware (file:///Users/divy/Library/Caches/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/1.0.4/server.js:462:23)
[11ty]     at EleventyDevServer.eleventyDevServerMiddleware (file:///Users/divy/Library/Caches/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/1.0.4/server.js:430:5)
[11ty]     at EleventyDevServer.onRequestHandler (file:///Users/divy/Library/Caches/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/1.0.4/server.js:548:11)
[11ty]     at ServerImpl.emit (ext:deno_node/_events.mjs:383:28)
[11ty]     at node:http:1295:16
[11ty]     at new Promise (<anonymous>)
[11ty]     at handler (node:http:1293:16)
[11ty]     at ext:deno_http/00_serve.js:455:24
```

**Comment by littledivy** [comment]
Fixed in https://github.com/denoland/deno/commit/dc16c996dd83164011f3931a8bb49f25624601af !
