### ISSUE TITLE
Calling `createImageBitmap` with a `Blob`, "TypeError: expected typed ArrayBufferView" occurred.

### ISSUE THREAD

**Issue by disjukr** [denoland/deno#22649]
Version: Deno 1.41.1

#### `sprite`
![sprite](https://github.com/denoland/deno/assets/690661/7612b2b7-519b-437b-a5f8-c95518ef79cf)

#### `test.ts`
```ts
const blob = await (await fetch(
  "https://github.com/denoland/deno/assets/690661/7612b2b7-519b-437b-a5f8-c95518ef79cf",
)).blob();

console.log(blob);
createImageBitmap(blob);
```

```sh
$ deno run -A test.ts
Blob { size: 1553, type: "image/png" }
error: Uncaught (in promise) TypeError: expected typed ArrayBufferView
    at ext:deno_canvas/01_image.js:241:50
    at eventLoopTick (ext:core/01_core.js:166:7)
```

**Comment by Hajime-san** [comment]
Seems related `ops`

https://github.com/denoland/deno/issues/22381
