### ISSUE TITLE
Compiled app can't load node native module (*.node) 

### ISSUE THREAD

**Issue by ar37-rs** [denoland/deno#22652]
Testing slint-ui simple deno example from: https://slint.dev/releases/1.4.1/docs/node
using ```deno run -A index.ts``` it has no problem and working great, but when trying to run the binary after being successfully compiled using ```deno compile -A index.ts``` it emits an error like so:
```
error: Uncaught (in promise) TypeError: LoadLibraryExW failed
  module.exports = op_napi_open(filename, globalThis);
                   ^
    at Object.Module._extensions..node (node:module:778:20)
    at Module.load (node:module:656:32)
    at Function.Module._load (node:module:537:12)
    at Module.require (node:module:675:19)
    at require (node:module:789:16)
    at Object.<anonymous> (file:///C:/Users/admin/AppData/Local/Temp/deno-compile-deno_slint.exe/node_modules/localhost/slint-ui/1.4.1/rust-module.cjs:72:29)
    at Object.<anonymous> (file:///C:/Users/admin/AppData/Local/Temp/deno-compile-deno_slint.exe/node_modules/localhost/slint-ui/1.4.1/rust-module.cjs:320:4)
    at Module._compile (node:module:731:34)
    at Object.Module._extensions..js (node:module:745:10)
    at Module.load (node:module:656:32)
```

Version: Deno 1.41.1

**Comment by DemonMartin** [comment]
Encountering this Issue when trying to use `ffi-rs` too...

**Comment by devsnek** [comment]
This should be fixed in https://github.com/denoland/deno/pull/24101, let us know if you run into any other issues.
