### ISSUE TITLE
Deno panicked running `jsr-io/jsr`

### ISSUE THREAD

**Issue by rauno56** [denoland/deno#22704]
1. Cloned https://github.com/jsr-io/jsr
2. `cd frontend`
3. `RUST_BACKTRACE=full deno task start`

<details>
<summary>Output:</summary>

```
❯ RUST_BACKTRACE=full deno task start
Task start deno run -A --watch=static/,routes/ dev.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.41.1
Args: ["deno", "task", "start"]

thread 'main' panicked at library/std/src/env.rs:171:83:
called `Result::unwrap()` on an `Err` value: "\u{7f}ELF\u{2}\u{1}\u{1}\u{3}>\u{1}\x93\u{2}@\xBC/\u{8}@8\u{c}@/-\u{6}\u{4}@@@\xA0\u{2}\xA0\u{2}\u{8}\u{3}\u{4}\xE0\u{2}\xE0\u{2}\xE0\u{2}\u{1c}\u{1c}\u{1}\u{1}\u{4}\xF4\xEC\x92\u{2}\xF4\xEC\x92\u{2}\u{10}\u{1}\u{5}\xF0\x92\u{2}\x93\u{2}\x93\u{2}\xF0\xF6&\u{3}\xF0\xF6&\u{3}\u{10}\u{1}\u{6}\xF0\xE6\xB9\u{5}\xF0\u{6}\xBA\u{5}\xF0\u{6}\xBA\u{5}\x90\xE9#\x90\xE9#\u{10}\u{1}\u{6}\x80\xD0\xDD\u{5}\x80\xDE\u{5}\x80\xDE\u{5}\xE8\xFA\u{1}H>\u{4}\u{10}\u{7}\u{4}\xF0\xE6\xB9\u{5}\xF0\u{6}\xBA\u{5}\xF0\u{6}\xBA\u{5}\xD8"
stack backtrace:
   0:     0x56312d01f186 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x56312d01f186 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56312d01f186 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x56312d01f186 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56312d053d90 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x56312d053d90 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x56312d018ebf - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x56312d01ef64 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56312d01ef64 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56312d020cd7 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x56312d020a39 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x56312d53d047 - deno::setup_panic_hook::{{closure}}::h3aebbcb41bc2cbd8
  12:     0x56312d021366 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbc5ccf4eb663e1e5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
  13:     0x56312d021366 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
  14:     0x56312d0210b2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  15:     0x56312d01f686 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x56312d020e10 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  17:     0x56312d050e25 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  18:     0x56312d051373 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  19:     0x56312d010554 - core::result::Result<T,E>::unwrap::hb221085af2ba891b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
  20:     0x56312d010554 - <std::env::Vars as core::iter::traits::iterator::Iterator>::next::{{closure}}::h0fe919a1e85834b0
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/env.rs:171:67
  21:     0x56312d010554 - core::option::Option<T>::map::h487623aec850f0aa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1072:29
  22:     0x56312d010554 - <std::env::Vars as core::iter::traits::iterator::Iterator>::next::h3d9b8977c6e77401
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/env.rs:171:27
  23:     0x56312d4dbe10 - deno::tools::task::collect_env_vars::h0668c6f05879ddab
  24:     0x56312d4d9ac0 - deno::tools::task::execute_script::{{closure}}::hbcde3ba8e5ce4ecd
  25:     0x56312d52323b - deno::spawn_subcommand::{{closure}}::h1f2c1c560582a533
  26:     0x56312d2c2692 - <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll::h9524bdb868211d83
  27:     0x56312d1cda7a - tokio::runtime::task::raw::poll::hb677540859192a8b
  28:     0x56312d53e6b0 - deno::main::hdaaf91afd009e61e
  29:     0x56312d0d50a9 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc53d8089649d4a69
  30:     0x56312d0dcb60 - std::rt::lang_start::{{closure}}::h79e87bff65294280
  31:     0x56312d00cc91 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  32:     0x56312d00cc91 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  33:     0x56312d00cc91 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  34:     0x56312d00cc91 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  35:     0x56312d00cc91 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  36:     0x56312d00cc91 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  37:     0x56312d00cc91 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  38:     0x56312d00cc91 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  39:     0x56312d00cc91 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  40:     0x56312d5dd285 - main
  41:     0x7f9b3e98d14a - __libc_start_call_main
  42:     0x7f9b3e98d20b - __libc_start_main_impl
  43:     0x56312bd14029 - _start
  44:                0x0 - <unknown>
```

</details>

**Comment by littledivy** [comment]
Check if the environment variables are valid UTF-8.

**Comment by bartlomieju** [comment]
I can't reproduce this one. Closing since there's been no activity here.
