### ISSUE TITLE
npm:opentranslate Cannot find module 'tslib'

### ISSUE THREAD

**Issue by guy-borderless** [denoland/deno#22739]
Version: Deno 1.41.1

`error: Uncaught (in promise) Error: Cannot find module 'tslib'
...
at Object.<anonymous> (file:///home/guy/prj/curr/borderless/borderless-services/node_modules/.deno/@opentranslate+google@1.4.2/node_modules/@opentranslate/google/dist/index.js:3:17)`

node_modules/@opentranslate/google/dist/index.js: 
`
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
...
`

my code is [from here](https://github.com/OpenTranslate/OpenTranslate/tree/master/packages/service-google):
`
import Google from "npm:@opentranslate/google"

const google = new Google.default({
  config: {
    order: ["com"],
    // search all at the same time
    concurrent: true,
    // googleapi as fallback
    apiAsFallback: true,
  },
})

google.translate(
  ` text.`,
  "es",
  "en",
).then(console.log)
`

**Comment by guy-borderless** [comment]
How come it works on node?

**Comment by dsherret** [comment]
It doesn't on its own:

```
>node index.js
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- C:\Users\WDAGUtilityAccount\example\node_modules\@opentranslate\google\dist\index.js
- C:\Users\WDAGUtilityAccount\example\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\WDAGUtilityAccount\example\node_modules\@opentranslate\google\dist\index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\WDAGUtilityAccount\\example\\node_modules\\@opentranslate\\google\\dist\\index.js',
    'C:\\Users\\WDAGUtilityAccount\\example\\index.js'
  ]
}

Node.js v20.11.1
```

It probably just works by chance in other scenarios because some other library has defined tslib as a dependency and then `@opentranslate/google` pulls it in.
