### ISSUE TITLE
JSR (REPL): Could not find constraint in list of versions when library is not cached

### ISSUE THREAD

**Issue by retraigo** [denoland/deno#22748]
Version: Deno 1.41.1

Moved from https://github.com/jsr-io/jsr/issues/191

Steps to reproduce:
1. Cache a version of your JSR module.
2. Publish a new version.
3. Import the new version inside the REPL or a Jupyter notebook.

![image](https://github.com/denoland/deno/assets/56877379/8b4c3d3f-853c-45bc-a5e9-a299a3298be3)

There isn't a time frame within publishing of a new version for this issue to happen. It happens even days later as long as it hasn't been cached already.

I can cache it when using `deno run` or when using the command "Deno: Cache Dependencies". Only Jupyter and the REPL have this issue.

**Comment by maxmcd** [comment]
I think I am seeing a similar issue where a new jsr version cannot be imported:
```
Could not find version of '@pomdtr/val-town-sqlite-explorer' that matches specified version constraint '0.0.4'
    at [0m[36mhttps://esm.town/v/pomdtr/sqliteExplorerBug?v=2[0m:[0m[33m2[0m:[0m[33m27[0m
```

version 0.0.4 was published 40 minutes ago, is the 404 on the new version being cached? 

We're seeing this when using a dynamic import, not in the REPL.

**Comment by waterbang** [comment]
```bash
Could not find version of '@std/assert' that matches specified version constraint '~1.0.6'
    at https://jsr.io/@cliffy/prompt/1.0.0-rc.7/select.ts:18:23 (jsr:/@std/assert@~1.0.6/equal)
Could not find version of '@std/encoding' that matches specified version constraint '~1.0.5'
    at https://jsr.io/@cliffy/ansi/1.0.0-rc.7/ansi_escapes.ts:1:30 (jsr:/@std/encoding@~1.0.5/base64)
```

**Comment by bartlomieju** [comment]
No longer reproducible on current `main`. Tested by caching `jsr:@std/path@0.225.0`, then importing `jsr:@std/path@1.0.0` in the REPL — it correctly downloaded and used the new version without any "Could not find constraint in list of versions" error.
