### ISSUE TITLE
jupyter kernel crashes with korean characters intermittently

### ISSUE THREAD

**Issue by jeiea** [denoland/deno#22771]
I haven't discovered a consistent method to replicate it, but I've encountered it on at least two occasions in the most recent version, prompting me to raise an issue.

```
22:19:18.872 [info] Handle Execution of Cells 1 for ~/Documents/sample.ipynb
22:19:18.877 [info] Kernel acknowledged execution of cell 1 @ 1709817558876
22:19:18.885 [info] End cell 1 execution after 0.008s, completed @ 1709817558884, started @ 1709817558876
22:19:41.088 [info] Handle Execution of Cells 1 for ~/Documents/sample.ipynb
22:19:41.094 [info] Kernel acknowledged execution of cell 1 @ 1709817581094
22:19:41.102 [info] End cell 1 execution after 0.008s, completed @ 1709817581102, started @ 1709817581094
22:31:07.597 [warn] StdErr from Kernel Process Unrecognized shell message type: inspect_request
22:31:08.061 [info] Too many pending requests 1 for kernel 3e4d70c4-2c66-4e4e-a2b2-2957e06b90ac, waiting for it to be ready.
22:31:08.259 [info] Too many pending requests 1 for kernel 3e4d70c4-2c66-4e4e-a2b2-2957e06b90ac, waiting for it to be ready.
22:31:08.348 [info] Too many pending requests 1 for kernel 3e4d70c4-2c66-4e4e-a2b2-2957e06b90ac, waiting for it to be ready.
22:31:09.228 [info] Too many pending requests 1 for kernel 3e4d70c4-2c66-4e4e-a2b2-2957e06b90ac, waiting for it to be ready.
22:31:30.722 [info] Too many pending requests 1 for kernel 3e4d70c4-2c66-4e4e-a2b2-2957e06b90ac, waiting for it to be ready.
22:31:30.811 [info] Too many pending requests 1 for kernel 3e4d70c4-2c66-4e4e-a2b2-2957e06b90ac, waiting for it to be ready.
22:35:08.815 [warn] StdErr from Kernel Process ============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.41.1
Args: ["~/.asdf/installs/deno/1.41.1/bin/deno", "jupyter", "--kernel", "--conn", "~/Library/Jupyter/runtime/kernel-v2-43528NrdzWLxteu5K.json"]
22:35:08.815 [warn] StdErr from Kernel Process thread 'main' panicked at cli/tools/jupyter/server.rs:575:19:
byte index 83 is not a char boundary; it is inside '서' (bytes 82..85) of `function getLunchPlace(me) {
  '서';
}

ge`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
22:35:08.820 [error] Disposing session as kernel process died ExitCode: 1, Reason: [0m[33mWarning[0m "deno jupyter" is unstable and might change in the future.
Unrecognized shell message type: inspect_request

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.41.1
Args: ["~/.asdf/installs/deno/1.41.1/bin/deno", "jupyter", "--kernel", "--conn", "~/Library/Jupyter/runtime/kernel-v2-43528NrdzWLxteu5K.json"]

thread 'main' panicked at cli/tools/jupyter/server.rs:575:19:
byte index 83 is not a char boundary; it is inside '서' (bytes 82..85) of `function getLunchPlace(me) {
  '서';
}

ge`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

22:35:08.820 [info] Dispose Kernel process 54711.
22:35:08.852 [info] End cell 1 execution after 0s, completed @ undefined, started @ undefined
```

**Comment by jwmdykes** [comment]
```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 2.3.1
Args: ["C:\\Users\\~\\AppData\\Local\\Microsoft\\WinGet\\Links\\deno.exe", "jupyter", "--kernel", "--conn", "c:\\Users\\~\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3b3df1ab4830701d966b4504380fccc7973406c53.json"]

View stack trace at:
https://panic.deno.com/v2.3.1/x86_64-pc-windows-msvc/ssynUgvn2oCyxkgpC-mkgpC8u3gpCigq2hE6-uwXwgt2hE8yjiGgujyRix53Dq8n1Vmm52H-88gIwg02Do3hwE401-oCut0L49inB

thread '<unnamed>' panicked at cli\tools\jupyter\server.rs:733:19:
byte index 1 is not a char boundary; it is inside 'ㄱ' (bytes 0..3) of `ㄱ`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Same issue. Here is the stack trace:

0.0
deno_panic::win64::trace()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\deno_panic-0.1.0\src\win64.rs:107

0.1
deno::setup_panic_hook::closure$0()

unknown
C:\a\deno\deno\cli\main.rs:394

1.0
std::panicking::rust_panic_with_hook()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\panicking.rs:838

2.0
std::panicking::begin_panic_handler::closure$0()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\panicking.rs:701

3.0
std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\sys\backtrace.rs:168

4.0
std::panicking::begin_panic_handler()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\panicking.rs:692

5.0
core::panicking::panic_fmt()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\core\src\panicking.rs:75

6.0
core::str::slice_error_fail_rt()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\core\src\str\mod.rs:89

7.0
core::str::slice_error_fail()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\core\src\str\mod.rs:68

8.0
core::str::traits::impl$10::get()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\core\src\str\traits.rs:434

8.1
core::str::traits::impl$10::index()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\core\src\str\traits.rs:465

9.0
deno::tools::jupyter::server::get_expr_from_line_at_pos()

unknown
C:\a\deno\deno\cli\tools\jupyter\server.rs:733

9.1
deno::tools::jupyter::server::impl$0::handle_shell_message::async_fn$0()

unknown
C:\a\deno\deno\cli\tools\jupyter\server.rs:313

9.2
deno::tools::jupyter::server::impl$0::handle_shell::async_fn$0()

unknown
C:\a\deno\deno\cli\tools\jupyter\server.rs:253

9.3
deno::tools::jupyter::server::impl$0::start::async_fn$0::async_block$3()

unknown
C:\a\deno\deno\cli\tools\jupyter\server.rs:158

10.0
core::ptr::drop_in_place()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\core\src\ptr\mod.rs:523

10.1
tokio::runtime::task::core::impl$6::poll::closure$0()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\task\core.rs:329

10.2
tokio::loom::std::unsafe_cell::UnsafeCell::with_mut()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\loom\std\unsafe_cell.rs:16

10.3
tokio::runtime::task::core::Core::poll()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\task\core.rs:317

10.4
tokio::runtime::task::harness::poll_future::closure$0()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\task\harness.rs:485

10.5
core::panic::unwind_safe::impl$25::call_once()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\core\src\panic\unwind_safe.rs:272

10.6
std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<deno_unsync::tokio::task::MaskFutureAsSend<enum2$<deno::tools::jupyter::server::impl$0::start::async_fn$0::async_block_env$3> >,alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle,alloc::alloc::Global> > >,enum2$<core::task::poll::Poll<deno_unsync::tokio::task::MaskResultAsSend<tuple$<> > > > >()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\panicking.rs:584

12.0
std::panicking::try()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\panicking.rs:547

12.1
std::panic::catch_unwind()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\panic.rs:358

12.2
tokio::runtime::task::harness::poll_future()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\task\harness.rs:473

12.3
tokio::runtime::task::harness::Harness::poll_inner()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\task\harness.rs:208

12.4
tokio::runtime::task::harness::Harness::poll()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\task\harness.rs:153

12.5
tokio::runtime::task::raw::poll<deno_unsync::tokio::task::MaskFutureAsSend<enum2$<deno::tools::jupyter::server::impl$0::start::async_fn$0::async_block_env$3> >,alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle,alloc::alloc::Global> >()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\task\raw.rs:271

13.0
tokio::runtime::coop::with_budget()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\coop.rs:108

13.1
tokio::runtime::coop::budget()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\coop.rs:73

13.2
tokio::runtime::scheduler::current_thread::impl$3::run_task::closure$0()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\scheduler\current_thread\mod.rs:343

13.3
tokio::runtime::scheduler::current_thread::Context::enter()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\scheduler\current_thread\mod.rs:404

13.4
tokio::runtime::scheduler::current_thread::Context::run_task()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\scheduler\current_thread\mod.rs:343

13.5
tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\scheduler\current_thread\mod.rs:699

13.6
tokio::runtime::scheduler::current_thread::impl$8::enter::closure$0()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\scheduler\current_thread\mod.rs:737

13.7
tokio::runtime::context::scoped::Scoped::set()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\context\scoped.rs:40

13.8
tokio::runtime::context::set_scheduler::closure$0()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\context.rs:176

13.9
std::thread::local::LocalKey::try_with()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\thread\local.rs:308

13.10
std::thread::local::LocalKey::with()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\thread\local.rs:272

13.11
tokio::runtime::context::set_scheduler()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\context.rs:176

13.12
tokio::runtime::scheduler::current_thread::CoreGuard::enter()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\scheduler\current_thread\mod.rs:737

13.13
tokio::runtime::scheduler::current_thread::CoreGuard::block_on()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\scheduler\current_thread\mod.rs:646

13.14
tokio::runtime::scheduler::current_thread::impl$0::block_on::closure$0()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\scheduler\current_thread\mod.rs:175

13.15
tokio::runtime::context::runtime::enter_runtime()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\context\runtime.rs:65

13.16
tokio::runtime::scheduler::current_thread::CurrentThread::block_on()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\scheduler\current_thread\mod.rs:167

13.17
tokio::runtime::runtime::Runtime::block_on<tokio::runtime::task::join::JoinHandle<deno_unsync::tokio::task::MaskResultAsSend<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > > >()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.36.0\src\runtime\runtime.rs:348

14.0
core::result::Result::unwrap()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\core\src\result.rs:1107

14.1
deno_runtime::tokio_util::create_and_run_current_thread_inner()

unknown
C:\a\deno\deno\runtime\tokio_util.rs:111

14.2
deno_runtime::tokio_util::create_and_run_current_thread()

unknown
C:\a\deno\deno\runtime\tokio_util.rs:126

14.3
deno::tools::jupyter::kernel::async_fn$0::closure$4()

unknown
C:\a\deno\deno\cli\tools\jupyter\mod.rs:185

14.4
std::sys::backtrace::__rust_begin_short_backtrace<deno::tools::jupyter::kernel::async_fn$0::closure_env$4,enum2$<core::result::Result<tuple$<>,anyhow::Error> > >()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\sys\backtrace.rs:152

15.0
std::thread::impl$0::spawn_unchecked_::closure$1::closure$0()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\thread\mod.rs:564

15.1
core::panic::unwind_safe::impl$25::call_once()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\core\src\panic\unwind_safe.rs:272

15.2
std::panicking::try::do_call()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\panicking.rs:584

15.3
std::panicking::try()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\panicking.rs:547

15.4
std::panic::catch_unwind()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\panic.rs:358

15.5
std::thread::impl$0::spawn_unchecked_::closure$1()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\thread\mod.rs:562

15.6
core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<deno::tools::jupyter::kernel::async_fn$0::closure_env$4,enum2$<core::result::Result<tuple$<>,anyhow::Error> > >,tuple$<> >()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\core\src\ops\function.rs:250

16.0
alloc::boxed::impl$8::drop()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\alloc\src\boxed.rs:1700

16.1
alloc::boxed::impl$28::call_once()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\alloc\src\boxed.rs:1993

16.2
alloc::boxed::impl$28::call_once()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\alloc\src\boxed.rs:1993

16.3
std::sys::pal::windows::thread::impl$0::new::thread_start()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\std\src\sys\pal\windows\thread.rs:56

17.0
deno_tower_lsp::service::layers::impl$11::call()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\deno_tower_lsp-0.4.3\src\service\layers.rs:262

17.1
tower::util::boxed::unsync::impl$3::call<deno_tower_lsp::service::layers::NormalService<deno_tower_lsp::jsonrpc::router::MethodHandler<tuple$<lsp_types::signature_help::SignatureHelpParams>,enum2$<core::result::Result<enum2$<core::option::Option<lsp_types::signature_help::SignatureHelp> >,deno_tower_lsp::jsonrpc::error::Error> >,deno_tower_lsp::service::ExitedError> >,deno_tower_lsp::jsonrpc::request::RequestWithCancellation>()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tower-0.5.2\src\util\boxed\unsync.rs:84

18.0
alloc::boxed::impl$30::call()

unknown
\rustc\4d91de4e48198da2e33413efdcd9cd2cc0c46688\library\alloc\src\boxed.rs:2007

18.1
deno_unsync::sync::value_creator::MultiRuntimeAsyncValueCreator::create_shared_future<enum2$<core::result::Result<tuple$<>,alloc::sync::Arc<deno_error::JsErrorBox,alloc::alloc::Global> > > >()

unknown
C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\deno_unsync-0.4.2\src\sync\value_creator.rs:102

**Comment by jwmdykes** [comment]
From `cli\tools\jupyter\server.r` we have these two functions:

```rust
// TODO(bartlomieju): dedup with repl::editor
fn is_word_boundary(c: char) -> bool {
  if matches!(c, '.' | '_' | '$') {
    false
  } else {
    char::is_ascii_whitespace(&c) || char::is_ascii_punctuation(&c)
  }
}
```

```rust
// TODO(bartlomieju): dedup with repl::editor
fn get_expr_from_line_at_pos(line: &str, cursor_pos: usize) -> &str {
  let start = line[..cursor_pos].rfind(is_word_boundary).unwrap_or(0);
  let end = line[cursor_pos..]
    .rfind(is_word_boundary)
    .map(|i| cursor_pos + i)
    .unwrap_or(cursor_pos);

  let word = &line[start..end];
  let word = word.strip_prefix(is_word_boundary).unwrap_or(word);
  let word = word.strip_suffix(is_word_boundary).unwrap_or(word);

  word
}
```

This is wrong. It's not dealing with multi-byte characters correctly. For example, 

```rust
fn main() {
    let line = "test안ing";
    // or any other multi-byte utf-8 character will work, for example:
    // let line = "test😀ing";
    // let line = "testыing";

    let cursor_pos = 5; // Cursor in the middle of '안' (byte index)

    // This will panic because cursor_pos 5 is not a character boundary
    let word = get_expr_from_line_at_pos(line, cursor_pos);
    println!("word: {}", word);
}
```

this will panic. [Here's a rust playground demonstrating the panic.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=16ec9f776c8de2894bffc60725adde28)

This might affect the repl too? Because there are these comments on the affected functions:

// TODO(bartlomieju): dedup with repl::editor
