### ISSUE TITLE
npm-compat: ts-results issues

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#22806]
Version: Deno 1.41.2

```ts
// import { Err, Ok, Result } from "https://esm.sh/ts-results@3.3.0"; // works
import { Err, Ok, Result } from "npm:ts-results@3.3.0"; // fails

console.log(Result.wrap(() => Deno.readTextFileSync("/etc/hostsz")));
```

error
```
error: Uncaught (in promise) Error: Cannot find module 'tslib'
```

also note the npm package tries to read the node_modules dir when used with npm:, while using it from esm doesn't do this (so no need to give read all permission)

![image](https://github.com/denoland/deno/assets/22427111/bb477059-ad31-4ef6-9958-959190fa3bb2)

**Comment by dsherret** [comment]
The exact same error happens in Node:

```
> node main.js
node:internal/modules/cjs/loader:1152
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- V:\scratch\node_modules\ts-results\index.js
- V:\scratch\main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at V:\scratch\node_modules\ts-results\index.js:12:19
    at V:\scratch\node_modules\ts-results\index.js:3:17
    at Object.<anonymous> (V:\scratch\node_modules\ts-results\index.js:9:3)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'V:\\scratch\\node_modules\\ts-results\\index.js',
    'V:\\scratch\\main.js'
  ]
}

Node.js v21.6.1
```

It's because ts-results uses the tslib package, but doesn't define it as a dependency (which it should).

This bug was fixed in this PR, but they never did a release: https://github.com/vultix/ts-results/pull/38

**Comment by sigmaSd** [comment]
I see thanks

**Comment by ry** [comment]
See also https://jsr.io/@oxi/result
