### ISSUE TITLE
`deno publish` failed to resolve types from import in workspace

### ISSUE THREAD

**Issue by JOTSR** [denoland/deno#22819]
Version: Deno 1.41.2

Currently porting [cliffy](https://github.com/c4spar/deno-cliffy) to `jsr` (commit [587cfd1](https://github.com/JOTSR/deno-cliffy/tree/587cfd103bec5a166c0e979066426f1e9c85fbb5)).
While running `deno publish --dry-run` on `cliffy` [PR#679](https://github.com/c4spar/deno-cliffy/pull/679), types imported in [@cliffy/command/type.ts](https://github.com/JOTSR/deno-cliffy/blob/587cfd103bec5a166c0e979066426f1e9c85fbb5/command/type.ts) failed check on `deno publish --dry-run`.

```sh
error: Failed ensuring public API type output is valid.

TS2304 [ERROR]: Cannot find name 'ArgumentValue'.
  public abstract parse(type: ArgumentValue): TValue;
                              ~~~~~~~~~~~~~
    at file:///.../deno-cliffy/command/type.ts:35:31

TS2304 [ERROR]: Cannot find name 'Command'.
   */ public values?(cmd: Command, parent?: Command): ValuesHandlerResult;
                          ~~~~~~~
    at file:///.../deno-cliffy/command/type.ts:42:10

TS2304 [ERROR]: Cannot find name 'Command'.
   */ public values?(cmd: Command, parent?: Command): ValuesHandlerResult;
                                            ~~~~~~~
    at file:///.../deno-cliffy/command/type.ts:43:14

TS2304 [ERROR]: Cannot find name 'ValuesHandlerResult'.
   */ public values?(cmd: Command, parent?: Command): ValuesHandlerResult;
                                                      ~~~~~~~~~~~~~~~~~~~
    at file:///.../deno-cliffy/command/type.ts:44:6

TS2304 [ERROR]: Cannot find name 'Command'.
   */ public complete?(cmd: Command, parent?: Command): CompleteHandlerResult;
                            ~~~~~~~
    at file:///.../deno-cliffy/command/type.ts:51:10

TS2304 [ERROR]: Cannot find name 'Command'.
   */ public complete?(cmd: Command, parent?: Command): CompleteHandlerResult;
                                              ~~~~~~~
    at file:///.../deno-cliffy/command/type.ts:52:14

TS2304 [ERROR]: Cannot find name 'CompleteHandlerResult'.
   */ public complete?(cmd: Command, parent?: Command): CompleteHandlerResult;
                                                        ~~~~~~~~~~~~~~~~~~~~~
    at file:///.../deno-cliffy/command/type.ts:53:6

Found 7 errors.

You may have discovered a bug in Deno. Please open an issue at: https://github.com/denoland/deno/issues/
```

**Comment by dsherret** [comment]
Strange. I'm able to reproduce and see what's happening, but not in a unit test yet. This is definitely a bug and I'll try to fix it over the weekend or on Monday.
