### ISSUE TITLE
Unexpected publish errors

### ISSUE THREAD

**Issue by roj1512** [denoland/deno#22829]
There are no slow types in the codebase, but if the `--allow-slow-types` flag is not provided when publishing, the following errors are thrown:

```error: Failed ensuring public API type output is valid.

TS2612 [ERROR]: Property 'stateChangeHandler' will overwrite the base property in 'ClientAbstract'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
  protected stateChangeHandler!: (connected: boolean) => void;
            ~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/client/4_client.ts:787:13

TS1166 [ERROR]: A computed property name in a class property declaration must have a simple literal type or a 'unique symbol' type.
  private [getEntity]!: unknown;
          ~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/client/4_client.ts:1497:11

TS2304 [ERROR]: Cannot find name 'getEntity'.
  private [getEntity]!: unknown;
           ~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/client/4_client.ts:1497:12

TS1166 [ERROR]: A computed property name in a class property declaration must have a simple literal type or a 'unique symbol' type.
  private [getEntity]!: unknown;
          ~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/client/4_client.ts:1498:11

TS2304 [ERROR]: Cannot find name 'getEntity'.
  private [getEntity]!: unknown;
           ~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/client/4_client.ts:1498:12

TS1166 [ERROR]: A computed property name in a class property declaration must have a simple literal type or a 'unique symbol' type.
  private [getEntity]!: unknown;
          ~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/client/4_client.ts:1499:11

TS2304 [ERROR]: Cannot find name 'getEntity'.
  private [getEntity]!: unknown;
           ~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/client/4_client.ts:1499:12

TS1166 [ERROR]: A computed property name in a class property declaration must have a simple literal type or a 'unique symbol' type.
  private [getEntity]!: unknown;
          ~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/client/4_client.ts:1500:11

TS2304 [ERROR]: Cannot find name 'getEntity'.
    joinChatlistUpdates: chatlists_joinChatlistUpdates_,
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21717:26

TS2304 [ERROR]: Cannot find name 'chatlists_hideChatlistUpdates_'.
    hideChatlistUpdates: chatlists_hideChatlistUpdates_,
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21718:26

TS2304 [ERROR]: Cannot find name 'chatlists_getLeaveChatlistSuggestions_'.
    getLeaveChatlistSuggestions: chatlists_getLeaveChatlistSuggestions_,
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21719:34

TS2304 [ERROR]: Cannot find name 'chatlists_leaveChatlist_'.
    leaveChatlist: chatlists_leaveChatlist_
                   ~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21720:20

TS2304 [ERROR]: Cannot find name 'stories_canSendStory_'.
    canSendStory: stories_canSendStory_,
                  ~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21723:19

TS2304 [ERROR]: Cannot find name 'stories_sendStory_'.
    sendStory: stories_sendStory_,
               ~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21724:16

TS2304 [ERROR]: Cannot find name 'stories_editStory_'.
    editStory: stories_editStory_,
               ~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21725:16

TS2304 [ERROR]: Cannot find name 'stories_deleteStories_'.
    deleteStories: stories_deleteStories_,
                   ~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21726:20

TS2304 [ERROR]: Cannot find name 'stories_togglePinned_'.
    togglePinned: stories_togglePinned_,
                  ~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21727:19

TS2304 [ERROR]: Cannot find name 'stories_getAllStories_'.
    getAllStories: stories_getAllStories_,
                   ~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21728:20

TS2304 [ERROR]: Cannot find name 'stories_getPinnedStories_'.
    getPinnedStories: stories_getPinnedStories_,
                      ~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21729:23

TS2304 [ERROR]: Cannot find name 'stories_getStoriesArchive_'.
    getStoriesArchive: stories_getStoriesArchive_,
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21730:24

TS2304 [ERROR]: Cannot find name 'stories_getStoriesByID_'.
    getStoriesByID: stories_getStoriesByID_,
                    ~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21731:21

TS2304 [ERROR]: Cannot find name 'stories_toggleAllStoriesHidden_'.
    toggleAllStoriesHidden: stories_toggleAllStoriesHidden_,
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21732:29

TS2304 [ERROR]: Cannot find name 'stories_readStories_'.
    readStories: stories_readStories_,
                 ~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21733:18

TS2304 [ERROR]: Cannot find name 'stories_incrementStoryViews_'.
    incrementStoryViews: stories_incrementStoryViews_,
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21734:26

TS2304 [ERROR]: Cannot find name 'stories_getStoryViewsList_'.
    getStoryViewsList: stories_getStoryViewsList_,
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21735:24

TS2304 [ERROR]: Cannot find name 'stories_getStoriesViews_'.
    getStoriesViews: stories_getStoriesViews_,
                     ~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21736:22

TS2304 [ERROR]: Cannot find name 'stories_exportStoryLink_'.
    exportStoryLink: stories_exportStoryLink_,
                     ~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21737:22

TS2304 [ERROR]: Cannot find name 'stories_report_'.
    report: stories_report_,
            ~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21738:13

TS2304 [ERROR]: Cannot find name 'stories_activateStealthMode_'.
    activateStealthMode: stories_activateStealthMode_,
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21739:26

TS2304 [ERROR]: Cannot find name 'stories_sendReaction_'.
    sendReaction: stories_sendReaction_,
                  ~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21740:19

TS2304 [ERROR]: Cannot find name 'stories_getPeerStories_'.
    getPeerStories: stories_getPeerStories_,
                    ~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21741:21

TS2304 [ERROR]: Cannot find name 'stories_getAllReadPeerStories_'.
    getAllReadPeerStories: stories_getAllReadPeerStories_,
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21742:28

TS2304 [ERROR]: Cannot find name 'stories_getPeerMaxIDs_'.
    getPeerMaxIDs: stories_getPeerMaxIDs_,
                   ~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21743:20

TS2304 [ERROR]: Cannot find name 'stories_getChatsToSend_'.
    getChatsToSend: stories_getChatsToSend_,
                    ~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21744:21

TS2304 [ERROR]: Cannot find name 'stories_togglePeerStoriesHidden_'.
    togglePeerStoriesHidden: stories_togglePeerStoriesHidden_,
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21745:30

TS2304 [ERROR]: Cannot find name 'stories_getStoryReactionsList_'.
    getStoryReactionsList: stories_getStoryReactionsList_
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21746:28

TS2304 [ERROR]: Cannot find name 'premium_getBoostsList_'.
    getBoostsList: premium_getBoostsList_,
                   ~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21749:20

TS2304 [ERROR]: Cannot find name 'premium_getMyBoosts_'.
    getMyBoosts: premium_getMyBoosts_,
                 ~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21750:18

TS2304 [ERROR]: Cannot find name 'premium_applyBoost_'.
    applyBoost: premium_applyBoost_,
                ~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21751:17

TS2304 [ERROR]: Cannot find name 'premium_getBoostsStatus_'.
    getBoostsStatus: premium_getBoostsStatus_,
                     ~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21752:22

TS2304 [ERROR]: Cannot find name 'premium_getUserBoosts_'.
    getUserBoosts: premium_getUserBoosts_
                   ~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/tl/3_functions.ts:21753:20

TS1016 [ERROR]: A required parameter cannot follow an optional parameter.
  constructor(major?: number | null, minor?: number | null, fileType: FileType, dcId: number, params: FileIDParams){}
                                                            ~~~~~~~~
    at file:///home/runner/work/MTKruto/MTKruto/types/0__file_id.ts:62:89

Found 1512 errors.

You may have discovered a bug in Deno. Please open an issue at: https://github.com/denoland/deno/issues/
Error: Process completed with exit code 1.
```

Version: Deno 1.41.2

**Comment by dsherret** [comment]
@roj1512 do you have a repo I could use to reproduce the problem?

**Comment by roj1512** [comment]
Yes, just clone https://github.com/MTKruto/MTKruto.

Reproduction steps are:

deno run -A https://esm.sh/gh/mtkruto/tools@4ca0c02076/pre_jsr.ts 0.0.0
deno publish --dry-run --allow-dirty
