### ISSUE TITLE
Different test failure reporting between 1.40 and 1.41

### ISSUE THREAD

**Issue by dpclark4** [denoland/deno#22837]
Hi, I noticed some differing behavior between Deno 1.40 and 1.41 around tests involving I/O. I have a test that opens a file, does some assertions, and then tries to close the file. If an assertion fails in the middle of the test, the test runner would indicate the assertion failure in 1.40, but in 1.41 it does not. Without indicating that the assertion failed (causing the test to abort, leaving the file open), it is more difficult to troubleshoot a failed test.

Sample test:
```
import { assertEquals } from "https://deno.land/std@0.219.0/assert/mod.ts";

Deno.test("always fails", async () => {
  const file = await Deno.create("something.txt");
  assertEquals(1, 2);
  file.close();
});

```

1.40
```
❯ deno --version
deno 1.40.0 (release, aarch64-apple-darwin)
v8 12.1.285.6
typescript 5.3.3
~/programming/deno-ex                                                                                                                                       15:13:34
❯ deno test -A
running 1 test from ./test.ts
always fails ... FAILED (2ms)

 ERRORS

always fails => ./test.ts:3:6
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   1
+   2

  throw new AssertionError(message);
        ^
    at assertEquals (https://deno.land/std@0.219.0/assert/assert_equals.ts:52:9)
    at file:///Users/danclark/programming/deno-ex/test.ts:5:3

 FAILURES

always fails => ./test.ts:3:6

FAILED | 0 passed | 1 failed (3ms)

error: Test failed
```

1.41
```
❯ deno --version
deno 1.41.2 (release, aarch64-apple-darwin)
v8 12.1.285.27
typescript 5.3.3
❯ deno test -A
Check file:///Users/danclark/programming/deno-ex/test.ts
running 1 test from ./test.ts
always fails ... FAILED (2ms)

 ERRORS

always fails => ./test.ts:3:6
error: Leaks detected:
  - A file was opened during the test, but not closed during the test. Close the file handle by calling `file.close()`.

 FAILURES

always fails => ./test.ts:3:6

FAILED | 0 passed | 1 failed (3ms)

error: Test failed
```

**Comment by fserb** [comment]
Same issue while trying to tests Deno.serve. The server leak overrides the assert error (which is the thing I actually care about). It makes writing serve test code a hassle, since I need to `try/finally` every assert, otherwise I can't see the error, because the server always leaks when the assert fails.

**Comment by fserb** [comment]
thank you so much. :)
