### ISSUE TITLE
Bug: cannot find exported interface

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#22843]
Steps to reproduce:

1. Clone https://github.com/mobxjs/mobx-state-tree 
2. Create a file `foo.ts` at the cloned root with these contents:
  ```ts
  import * as mod from "./src/index";
  console.log(mod);
  ```
3. Run `deno run -A --unstable-byonm --unstable-sloppy-imports foo.ts`

Error:
```sh
deno-git run -A --unstable-byonm --unstable-sloppy-imports foo.ts
Warning Sloppy imports are not recommended and have a negative impact on performance.
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/foo.ts:1:22
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/index.ts:156:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:6:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:7:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:8:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:9:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:10:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:11:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:12:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:13:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:14:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:15:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:16:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:17:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:18:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:19:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:20:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:21:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:22:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:23:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:24:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:25:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:26:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:27:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:28:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:29:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:30:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:31:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:32:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:33:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:34:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:35:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:36:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:37:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:38:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:39:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:40:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:41:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:42:15
Warning Sloppy module resolution (hint: specify path to index.ts file in directory instead)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/internal.ts:43:15
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/mst-operations.ts:35:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/node/BaseNode.ts:11:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/node/scalar-node.ts:10:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/node/object-node.ts:40:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/type/type.ts:26:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/middlewares/create-action-tracking-middleware.ts:1:54
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/middlewares/createActionTrackingMiddleware2.ts:1:70
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/middlewares/on-action.ts:28:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/action.ts:14:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/actionContext.ts:1:53
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/actionContext.ts:2:41
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/type/type-checker.ts:12:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/node/identifier-cache.ts:2:79
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/node/create-node.ts:10:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/node/node-utils.ts:17:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/process.ts:1:53
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/flow.ts:1:61
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/flow.ts:9:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/core/json-patch.ts:1:40
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/utils.ts:7:28
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/snapshotProcessor.ts:21:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/complex-types/map.ts:55:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/complex-types/array.ts:49:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/complex-types/model.ts:59:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/primitives.ts:20:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/literal.ts:16:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/literal.ts:17:27
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/refinement.ts:17:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/refinement.ts:18:50
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/enumeration.ts:1:70
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/union.ts:20:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/optional.ts:17:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/maybe.ts:9:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/late.ts:14:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/lazy.ts:2:25
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/lazy.ts:3:23
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/lazy.ts:15:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/frozen.ts:16:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/reference.ts:32:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/identifier.ts:16:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/utility-types/custom.ts:11:8
Warning Sloppy module resolution (hint: add .ts extension)
    at file:///Users/marvinh/dev/oss/mobx-state-tree/src/types/index.ts:32:8
error: Uncaught SyntaxError: The requested module './internal' does not provide an export named 'IModelType'
  IModelType,
  ^
    at <anonymous> (file:///Users/marvinh/dev/oss/mobx-state-tree/src/index.ts:6:3)
```

Checking the files the `IModelType` interface is definitely exported.

Version: Deno 1.41.1 , also git `bb6e4c7414ea9d2cd4cebaa6c3cb053d9de355e5` from March 11th 2024

**Comment by marvinhagemeister** [comment]
Closing, I cannot reproduce this issue anymore. Not sure which PR fixed it.
