### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_graph-0.69.6/src/graph.rs:1525:63: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#22852]
Check CI output here: https://gitlab.com/soapbox-pub/mostr/-/jobs/6369700712

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.
Platform: linux x86_64
Version: 1.41.1
Args: ["/usr/bin/deno", "test", "-A", "--unstable-ffi"]
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba1[500](https://gitlab.com/soapbox-pub/mostr/-/jobs/6369700712#L500)1f/deno_graph-0.69.6/src/graph.rs:1525:63:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by alexgleason** [comment]
Here it is with `RUST_BACKTRACE=1`:

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.
Platform: linux x86_64
Version: 1.41.1
Args: ["/usr/bin/deno", "test", "-A", "--unstable-ffi"]
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba1[500](https://gitlab.com/soapbox-pub/mostr/-/jobs/6369780061#L500)1f/deno_graph-0.69.6/src/graph.rs:1525:63:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: core::option::Option<T>::unwrap
   4: deno_graph::graph::ModuleGraph::build_fast_check_type_graph
   5: deno::graph_util::ModuleGraphBuilder::build_fast_check_graph
   6: deno::tools::check::TypeChecker::check_diagnostics::{{closure}}
   7: deno::tools::check::TypeChecker::check::{{closure}}
   8: deno::module_loader::ModuleLoadPreparer::prepare_module_load::{{closure}}
   9: <deno::module_loader::CliModuleLoader as deno_core::modules::loaders::ModuleLoader>::prepare_load::{{closure}}
  10: deno_core::modules::recursive_load::RecursiveModuleLoad::prepare::{{closure}}
  11: deno_core::modules::map::ModuleMap::load_dynamic_import::{{closure}}
  12: deno_core::modules::map::ModuleMap::poll_progress
  13: deno_core::runtime::jsruntime::JsRuntime::poll_event_loop
  14: deno_core::runtime::jsruntime::JsRuntime::run_event_loop::{{closure}}
  15: deno_runtime::worker::MainWorker::run_event_loop::{{closure}}
  16: deno::worker::CliMainWorker::evaluate_module_possibly_with_npm::{{closure}}
  17: deno::worker::CliMainWorker::execute_side_module_possibly_with_npm::{{closure}}
  18: <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
  19: tokio::runtime::task::raw::poll
  20: tokio::runtime::runtime::Runtime::block_on
  21: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://gitlab.com/soapbox-pub/mostr/-/jobs/6369780061

**Comment by dsherret** [comment]
You can temporarily work around this by using `--no-check`. I will fix this either today or tomorrow.
