### ISSUE TITLE
Panic on `deno -h | grep "--env"`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#22863]
Steps to reproduce:

1. Run `deno -h | grep "--env"`

Error:

```sh
grep: unrecognized option `--env'
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.41.1
Args: ["deno", "-h"]

thread 'main' panicked at cli/main.rs:343:21:
called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Version: Deno 1.41.1

**Comment by mmastrac** [comment]
Also fails with a shorter repo:

```
$ deno -h | echo
```

**Comment by dylanpyle** [comment]
not sure if this should be tracked separately, but `deno --version` panics in the same manner:

```
$ deno --version | echo


============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.42.1
Args: ["deno", "--version"]

thread 'main' panicked at cli/main.rs:359:19:
called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
