### ISSUE TITLE
`node_unit_tests::_fs_statfs_test` is flaky on windows

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno#22897]
https://github.com/denoland/deno/actions/runs/8268046545/job/22619967572?pr=22647#step:39:3153
```
[_fs/_fs_statfs_test 031.70] fs.statfsSync() => ./tests/unit_node/_fs/_fs_statfs_test.ts:53:6
[_fs/_fs_statfs_test 031.70] error: NotFound: The system cannot find the file specified. (os error 2)
[_fs/_fs_statfs_test 031.70]     const statFs = fs.statfsSync(filePath);
[_fs/_fs_statfs_test 031.70]                       ^
[_fs/_fs_statfs_test 031.70]     at Module.statfsSync (ext:deno_node/_fs/_fs_statfs.js:41:18)
[_fs/_fs_statfs_test 031.70]     at fn (file:///D:/a/deno/deno/tests/unit_node/_fs/_fs_statfs_test.ts:56:23)
[_fs/_fs_statfs_test 031.70] 
[_fs/_fs_statfs_test 031.70]  FAILURES 
```

**Comment by satyarohith** [comment]
https://github.com/denoland/deno/actions/runs/8269428776/job/22624718078?pr=22884#step:39:3232

**Comment by satyarohith** [comment]
https://github.com/denoland/deno/actions/runs/8269428776/job/22626471003?pr=22884#step:39:3114
