### ISSUE TITLE
Rejected assertions are masked by sanitizer

### ISSUE THREAD

**Issue by aricart** [denoland/deno#22922]
deno 1.41.2 (release, x86_64-apple-darwin)
v8 12.1.285.27
typescript 5.3.3

if you have a test that initiates networking or any other resource that will trigger cleanup failures and an assertion failure, the test runner will report that the test failed - but the errors are `error: Leaks detected: `

Instead, the test should fail on the test assertion that failed.

```
deno test -A --filter "ordered - fetch deleted consumer"
...
running 1 test from ./jetstream/tests/consumersordered_test.ts
ordered - fetch deleted consumer ...
(some output elided)
ordered - fetch deleted consumer ... FAILED (124ms)

 ERRORS 

ordered - fetch deleted consumer => ./jetstream/tests/consumersordered_test.ts:788:6
error: Leaks detected:
  - 2 async calls to op_read were started in this test, but never completed.
  - 2 timers were started in this test, but never completed. This is often caused by not calling `clearTimeout`.
  - A TCP connection was opened/accepted during the test, but not closed during the test. Close the TCP connection by calling `tcpConn.close()`.
  - A child process stderr was opened during the test, but not closed during the test. Close the child process stderr by calling `proc.stderr.close()` or `await child.stderr.cancel()`.
  - A child process was started during the test, but not closed during the test. Close the child process by calling `proc.kill()` or `proc.close()`.
  - An async operation to wait for a subprocess to exit was started in this test, but never completed. This is often caused by not awaiting the result of a `Deno.Process#status` call.
  - An interval was started in this test, but never completed. This is often caused by not calling `clearInterval`.
To get more details where leaks occurred, run again with the --trace-leaks flag.

 FAILURES 

ordered - fetch deleted consumer => ./jetstream/tests/consumersordered_test.ts:788:6

FAILED | 0 passed | 1 failed | 920 filtered out (2s)
```

Running the same test with a try catch on the assertion:

```
~/D/c/s/g/n/nats.deno (reject-consumer-deleted|●3✚5) [1]$ deno test -A --filter "ordered - fetch deleted consumer"
...
Check file:///Users/aricart/Dropbox/code/src/github.com/nats-io/nats.deno/tests/util_test.ts
running 1 test from ./jetstream/tests/consumersordered_test.ts
ordered - fetch deleted consumer ...
------- post-test output -------
....
Uncaught error from ./jetstream/tests/consumersordered_test.ts FAILED
ordered - fetch deleted consumer ... cancelled (0ms)
------- post-test output -------
...
AssertionError: Expected function to reject.
    at assertRejects (https://deno.land/std@0.219.0/assert/assert_rejects.ts:105:11)
    at eventLoopTick (ext:core/01_core.js:169:7) {
  name: "AssertionError"
}
----- post-test output end -----

 ERRORS 

./jetstream/tests/consumersordered_test.ts (uncaught error)
error: (in promise) AssertionError: Expected function to reject.
    throw new AssertionError(
          ^
    at assertRejects (https://deno.land/std@0.219.0/assert/assert_rejects.ts:105:11)
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./jetstream/tests/consumersordered_test.ts (uncaught error)

FAILED | 0 passed | 2 failed | 920 filtered out (3s)

error: Test failed
```

**Comment by bartlomieju** [comment]
This problem was fixed in https://github.com/denoland/deno/pull/22904 and will be released in Deno v1.41.3 today.
