### ISSUE TITLE
`kv.watch` panics with no keys

### ISSUE THREAD

**Issue by Enva2712** [denoland/deno#22953]
Version: Deno 1.41.3

```typescript
const kv = await Deno.openKv();
for await (const _ of kv.watch([])) {}
```
<details><summary>backtrace</summary>

```
Platform: linux x86_64
Version: 1.41.3
Args: ["deno", "run", "--unstable-kv", "repro.ts"]

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.29/src/future/select_all.rs:40:5:
assertion failed: !ret.inner.is_empty()
stack backtrace:
   0:     0x559d89b601a6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x559d89b601a6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559d89b601a6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x559d89b601a6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x559d89b94db0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x559d89b94db0 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x559d89b59ebf - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x559d89b5ff84 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x559d89b5ff84 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x559d89b61cf7 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x559d89b61a59 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x559d8a081f21 - deno::setup_panic_hook::{{closure}}::h0aecdb76b11a1e06
  12:     0x559d89b62386 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbc5ccf4eb663e1e5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
  13:     0x559d89b62386 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
  14:     0x559d89b62099 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:649:13
  15:     0x559d89b606a6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x559d89b61e30 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  17:     0x559d89b91e45 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  18:     0x559d89b91f03 - core::panicking::panic::hb837a5ebbbe5b188
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
  19:     0x559d8ac0d5a1 - <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next::hd0d01f3a08533c17
  20:     0x559d8ac0974d - deno_kv::op_kv_watch_next::call::{{closure}}::h760165a2e6ade4ea
  21:     0x559d8ac0034f - <deno_core::runtime::op_driver::futures_unordered_driver::FuturesUnorderedDriver<C> as deno_core::runtime::op_driver::OpDriver<C>>::submit_op_fallible::h8001971024c9cd26
  22:     0x559d8ac0849a - deno_kv::op_kv_watch_next::v8_fn_ptr::hb2564c8c9222f3b2
  23:     0x559d899685e4 - Builtins_CallApiCallbackGeneric
```

</details>

[failing assert](https://github.com/rust-lang/futures-rs/blob/0.3.29/futures-util/src/future/select_all.rs#L40)

**Comment by Leokuma** [comment]
As of 2.4.2 this error doesn't happen anymore. It did happen in 1.41.3. I don't know when it was fixed.

**Comment by bartlomieju** [comment]
This no longer reproduces on Deno 2.8.1. The repro:

```ts
const kv = await Deno.openKv();
for await (const _ of kv.watch([])) {}
```

now exits cleanly — watching an empty key array simply yields nothing and the async iterator completes immediately instead of panicking in `futures-util`'s `select_all`. The KV watch code path was since rewritten in JS, removing the Rust assertion that caused the panic. Closing as resolved.
