### ISSUE TITLE
`node:worker_threads` don't share resources with main Instance

### ISSUE THREAD

**Issue by mash-graz** [denoland/deno#23012]
Version: upstream (2f7b9660)

`deno` seems to show a significant different behavior when it comes to accessibility of resources between main instance and workers. In `node` and `bun` you can open a file, send the file descriptor resp. RID to the worker and access its content in this other context. Using deno, you will get just an `BadResource` Error. The received RID isn't present in the resource table of the client.

Here a small demonstration script:
```js
import { isMainThread, parentPort, Worker } from "node:worker_threads";
import fs from "node:fs";


if (isMainThread) { // --- code running on the main instance ---
 
  // open a File in the contex if the Main Thread
  const fd = fs.openSync(import.meta.filename);

  globalThis.Deno && console.log("ResourceTable (Main):\n", Deno.resources());

  // run this script also as 'node:worker_thread'
  const w = new Worker(import.meta.filename);

  // send file descriptor to the worker side
  console.log(`Send open file RID: ${fd}`);
  w.postMessage(fd)

} else { // --- code running on the worker side ---

  // receive file descriptor and try to read file content
  parentPort.on("message", (msg) => {
    const received_fd = msg;
    console.log(`Received RID:  ${received_fd}`);

    globalThis.Deno && console.log("ResourceTable (Worker):\n", Deno.resources());

    fs.read(received_fd, (err, br, buf) => {
      if (err) {
        console.log(`ERROR: ${err}`)
      } else {
        console.log(`READ: ${br} bytes`)
      }

      // cleanup and exit worker
      globalThis.Deno ? close() : parentPort.unref();
    });
  });
}
```

the output using deno:
```sh
❯ ../deno/target/debug/deno run -A cross_realm_fd_reuse.mjs
ResourceTable (Main):
 { "0": "stdin", "1": "stdout", "2": "stderr", "3": "fsFile" }
Send open file RID: 3
Received RID:  3
ResourceTable (Worker):
 { "0": "stdin", "1": "stdout", "2": "stderr" }
ERROR: BadResource: Bad resource ID
```

on `node`:
```sh
❯ node cross_realm_fd_reuse.mjs
Send open file RID: 17
Received RID:  17
READ: 1133 bytes
```

and `bun`:
```sh
❯ /tmp/bun cross_realm_fd_reuse.mjs
Send open file RID: 12
Received RID:  12
READ: 1133 bytes
```

Although I understand `deno`s radical different answer in this case very well, because it helps to prevent all sort of thread related troubles, it's still a significant different behavior resp. incompatibility.

The `deno_core` docu states about `Resources`:
>Resources are not thread-safe - they can only be accessed from the thread that the JsRuntime lives on.

I'm not sure if this inevitable applies to `node:worker_threads`, therefore I'm asking here, how to work around this incompatibility.

Otherwise I would have to write rather complex adaptations for an existing software to bypass this differences in behavior (https://github.com/bytecodealliance/jco/issues/400).

**Comment by bartlomieju** [comment]
This is a bug in `fs.open()` and not in `node:worker_threads`. Most polyfills in `fs` are currently wrong as they don't work on actual file descriptors but Deno's own "resources". This is outright wrong and needs to be fixed.

**Comment by mash-graz** [comment]
I'm not sure, if I'm able to understand your explanation.

Right now all operations in `/ext/node/polyfills/_fs/...` just translate the calling options to finally call their counterparts in `ext/fs`. And this calls use the resource table as an additional indirection instead of real file descriptors. The file descriptors are present in this table, but they can't be easily shared between mainThread and worker. 

And if I got it right, you argue, that the `/ext/node` file operations shouldn't take this indirection over the resource table, but simply use and return plain file descriptor numbers to achieve better compatibility.

**Comment by mash-graz** [comment]
> No, they are not. Resource ID is not a File Descriptor. Even though they are both number, the rid does not correspond to the actual value of FD of the OS.

I never thought, that `Resource IDs` in `deno` are identical to file descriptors.
But we can already get the file descriptors from an entry in the Resource table simply by:

```rust
#[op2(fast)]
pub fn op_fs_get_fd(
  state: &mut OpState,
  #[smi] rid: ResourceId,
) -> Result<i32, AnyError>{
  let file = FileResource::get_file(state, rid)?;
  let fd = match file.backing_fd() {
    Some(fd) => fd,
    None => return Err(generic_error("fd not found")),
  };
  Ok(fd)
}
```
That's why I'm rather confused about your explanation, that file descriptors aren't accessible via this RIDs.

The question, how this kind of handlers or complete resource entries should be shared/replicated/transfered between threads/workers without fear, looks much more difficile to me.

Nevertheless, I really understand that this topic is indeed a rather complex one and it has to be handled very carefully by those, who are really familiar with its design and security implications.

**Comment by bartlomieju** [comment]
A bunch of tests were disabled in https://github.com/denoland/deno/pull/25285 for these APIs as they showed incorrect behavior using resource IDs instead of file descriptors.

**Comment by SebastienGllmt** [comment]
I believe I'm hitting the same error when trying to create WASM component from my Javascript code using Deno (using jco, same as OP)

I get the same error
```bash
(jco componentize) BadResource: Bad resource ID
    at ext:deno_node/_fs/_fs_read.ts:75:39
    at Object.read (ext:deno_node/_fs/_fs_read.ts:88:5)
    at <computed> (ext:deno_node/internal/fs/streams.mjs:238:8)
    at new Promise (<anonymous>)
    at ReadStream._read (ext:deno_node/internal/fs/streams.mjs:236:9)
    at ReadStream.Readable.read (node:_stream_readable:617:12)
    at pollStateCheck (file:///project/node_modules/.deno/@bytecodealliance+preview2-shim@0.17.5/node_modules/@bytecodealliance/preview2-shim/lib/io/worker-thread.js:1016:28)
    at handle (file:///project/node_modules/.deno/@bytecodealliance+preview2-shim@0.17.5/node_modules/@bytecodealliance/preview2-shim/lib/io/worker-thread.js:631:9)
    at file:///project/node_modules/.deno/@bytecodealliance+preview2-shim@0.17.5/node_modules/@bytecodealliance/preview2-shim/lib/synckit/index.js:114:48
    at file:///project/node_modules/.deno/@bytecodealliance+preview2-shim@0.17.5/node_modules/@bytecodealliance/preview2-shim/lib/synckit/index.js:121:15 {
  code: undefined
}
```

The demo script by OP is nice, but I created a simple example repo to test jco itself instead of the worker thread behavior in isolation in case that helps: https://github.com/SebastienGllmt/deno-jco

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/33039.
