### ISSUE TITLE
Build environment issue

### ISSUE THREAD

**Issue by potham** [denoland/deno#2304]
Hi,

took latest branch from master and try to setup build environment, facing following issue. 

```
D:\deno-git\deno>python tools/setup.py
binary download
python D:\deno-git\deno\third_party\depot_tools\download_from_google_storage.py --platform=win32 --no_auth --bucket=chromium-gn --sha1_file D:\deno-git\deno\third_party\v8\buildtools\win\gn.exe.sha1
0> Failed to fetch file gs://chromium-gn/e20768d93a6b4400de0d03bb8ceb46facdbe3883 for D:\deno-git\deno\third_party\v8\buildtools\win\gn.exe, skipping. [Err: Traceback (most recent call last):
  File "D:\deno-git\deno\third_party\depot_tools\gsutil.py", line 182, in <module>
    sys.exit(main())
  File "D:\deno-git\deno\third_party\depot_tools\gsutil.py", line 179, in main
    clean=args.clean)
  File "D:\deno-git\deno\third_party\depot_tools\gsutil.py", line 128, in run_gsutil
    gsutil_bin = ensure_gsutil(force_version, target, clean)
  File "D:\deno-git\deno\third_party\depot_tools\gsutil.py", line 118, in ensure_gsutil
    raise InvalidGsutilError()
__main__.InvalidGsutilError
]
Failed to fetch file gs://chromium-gn/e20768d93a6b4400de0d03bb8ceb46facdbe3883 for D:\deno-git\deno\third_party\v8\buildtools\win\gn.exe. [Err: Traceback (most recent call last):
  File "D:\deno-git\deno\third_party\depot_tools\gsutil.py", line 182, in <module>
    sys.exit(main())
  File "D:\deno-git\deno\third_party\depot_tools\gsutil.py", line 179, in main
    clean=args.clean)
  File "D:\deno-git\deno\third_party\depot_tools\gsutil.py", line 128, in run_gsutil
    gsutil_bin = ensure_gsutil(force_version, target, clean)
  File "D:\deno-git\deno\third_party\depot_tools\gsutil.py", line 118, in ensure_gsutil
    raise InvalidGsutilError()
__main__.InvalidGsutilError
]
Downloading 1 files took 49.010000 second(s)
```
did anyone face this kind of issue?

**Comment by bartlomieju** [comment]
Hi @potham thanks for opening the issue, do you still experience this problem with latest `master`?

**Comment by maxuuell** [comment]
I have a similar case, but I don't get the error `Failed to fetch`.  

When I run `./tools/setup.py` it just hangs with 

```
binary download
python /Users/mdemers/Documents/repos/deno/third_party/depot_tools/download_from_google_storage.py --platform=darwin --no_auth --bucket=chromium-gn --sha1_file 
/Users/mdemers/Documents/repos/deno/third_party/v8/buildtools/mac/gn.sha1
```

Just cloned the repo today.

**Comment by bartlomieju** [comment]
Closing as stale, reopen is issue persists
