### ISSUE TITLE
Bug: ESM module incorrectly detected as CJS

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23059]
Steps to reproduce:

1. Run this snippet:
  ```ts
  import Bookmarks from "npm:@arcgis/core@4.29/widgets/Bookmarks.js";
  console.log(Bookmarks);
```

Error:

```sh
error: 'import', and 'export' cannot be used outside of module code at file:///Users/marvinhagemeister/Library/Caches/deno/npm/registry.npmjs.org/@stencil/core/4.9.0/internal/client/index.js:24:1

  import { BUILD, NAMESPACE } from '@stencil/core/internal/app-data';
  ~~~~~~
```

Version: Deno 1.41.3

**Comment by dsherret** [comment]
That's expected. The same thing happens in Node:

```
> node main.mjs
file:///V:/scratch/node_modules/@esri/calcite-components/dist/components/index.js:7
export { getAssetPath, setAssetPath, setNonce, setPlatformOptions } from '@stencil/core/internal/client/index.js';
         ^^^^^^^^^^^^
SyntaxError: Named export 'getAssetPath' not found. The requested module '@stencil/core/internal/client/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@stencil/core/internal/client/index.js';
const { getAssetPath, setAssetPath, setNonce, setPlatformOptions } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)

Node.js v21.6.1
```

That said, in the next version of Deno we're changing this to load CJS modules that uses ES module syntax to work, but the following error occurs due to the Node ESM code doing a directory import:

```
> deno run main.mjs
error: [ERR_UNSUPPORTED_DIR_IMPORT] Directory import 'file:///V:/scratch/node_modules/@esri/calcite-components/node_modules/@stencil/core/internal/app-data' is not supported resolving ES modules imported from file:///V:/scratch/node_modules/@esri/calcite-components/node_modules/@stencil/core/internal/client/index.js
```

**Comment by marvinhagemeister** [comment]
Good point, maybe that's one of those modules that assume to be put through a bundler by default.

**Comment by dsherret** [comment]
I think so. Btw, for the `ERR_UNSUPPORTED_DIR_IMPORT`, I wonder if we should apply sloppy import resolution within npm packages when sloppy imports is enabled.

**Comment by bartlomieju** [comment]
I know get
```
error: Uncaught (in promise) ReferenceError: Element is not defined
    at file:///deno/npm/registry.npmjs.org/@arcgis/core/4.29.10/core/domUtils.js:5:447
```

I think we can close this one an open a new one?

**Comment by bartlomieju** [comment]
This is no longer reproducible on current `main`. The `@stencil/core` internal module is now correctly loaded as ESM.

The original error:
```
error: 'import', and 'export' cannot be used outside of module code at .../@stencil/core/4.9.0/internal/client/index.js
```

is gone. The command now gets past module loading and only fails with a runtime `ReferenceError: Element is not defined`, which is expected since `Element` is a browser API not available in Deno's default environment — unrelated to the CJS/ESM detection issue.
