### ISSUE TITLE
URL.revokeObjectURL fails for blobs ("relative URL without a base")

### ISSUE THREAD

**Issue by FND** [denoland/deno#23085]
Version: Deno 1.41.3

Reduced test case:

```javascript
// sample.js
const code = 'console.log("hello world");';
const blob = new Blob([code], { type: "text/javascript" });
const worker = new Worker(URL.createObjectURL(blob), { type: "module" });
URL.revokeObjectURL(blob);
```

(Line 4 is optional; the error occurs even without instantiating a worker.)

```shell
$ deno run sample.js
hello world
error: Uncaught (in promise) URIError: relative URL without a base
URL.revokeObjectURL(blob);
    ^
    at Function.revokeObjectURL (ext:deno_web/09_file.js:703:3)
    at file:///…/sample.js:4:5
```

(FWIW, deferring `revokeObjectURL` invocation via `setTimeout` doesn't seem to make a difference.)

I don't see any obvious connection to [related issues](https://github.com/denoland/deno/issues?q=revokeObjectURL).

```shell
$ deno --version
deno 1.41.3 (release, aarch64-apple-darwin)
v8 12.3.219.9
typescript 5.3.3
```

**Comment by xBZZZZ** [comment]
`URL.revokeObjectURL` takes blob url, not Blob object:
```javascript
// sample.js
const code = 'console.log("hello world");';
const bloburl = URL.createObjectURL(new Blob([code], { type: "text/javascript" }));
const worker = new Worker(bloburl, { type: "module" });
URL.revokeObjectURL(bloburl);
```
