### ISSUE TITLE
[1.42.0] Regression: Cannot read properties of undefined (reading 'Symbol(Deno.internal.rid)')

### ISSUE THREAD

**Issue by rracariu** [denoland/deno#23107]
In `Deno 1.42.0` when running SvelteKit app in `dev` mode I get this error:
```sh
deno task dev
```

```sh
VITE v5.2.6  ready in 1062 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Symbol(Deno.internal.rid)')
    at TTY.#read (ext:deno_node/internal_binding/stream_wrap.ts:220:45)
    at TTY.readStart (ext:deno_node/internal_binding/stream_wrap.ts:90:17)
    at _tryReadStart (node:net:276:30)
    at ReadStream._read (node:net:856:7)
    at ReadStream.Readable.read (ext:deno_node/_stream.mjs:2999:16)
    at ReadStream.read (node:net:789:34)
    at resume_ (ext:deno_node/_stream.mjs:3349:16)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:33:15)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:175:21)
``` 

This is not the case with Deno 1.41.3

```
deno 1.42.0 (release, aarch64-apple-darwin)
v8 12.3.219.9
typescript 5.4.3
```

**Comment by littledivy** [comment]
Fixed in https://github.com/denoland/deno/commit/de0b230078daebbbec82ea5d7aabb9f0a429125f
