### ISSUE TITLE
Can't parse default export expression containing "as assertion" with ts instantiation

### ISSUE THREAD

**Issue by xl-soft** [denoland/deno#23118]
Version: Deno 1.41.2
 Deno can not lint this code
```
Error linting: /home/software/smartshell-sdk/src/graphql/mutation/login.ts
   Expected ';', got ',' at file:///home/software/smartshell-sdk/src/graphql/mutation/login.ts:31:33

  export default module<QueryInput, QueryResponse> as ShellSdkModule
                                  ~
Error linting: /home/software/smartshell-sdk/src/graphql/query/userClubs.ts
   Expected ';', got ',' at file:///home/software/smartshell-sdk/src/graphql/query/userClubs.ts:39:33

  export default module<QueryInput, QueryResponse[]> as ShellSdkModule
  ```
for some reason it expects comma be a semicolon
also affects jsr linter

**Comment by dsherret** [comment]
Let's track this in https://github.com/denoland/deno/issues/22375 as that's linked to the swc issue (https://github.com/swc-project/swc/issues/8627)

**Comment by dsherret** [comment]
By the way, as a workaround, I think it's possible to do:

```ts
const temp = module<QueryInput, QueryResponse[]>;
export default  temp  as ShellSdkModule
```
