### ISSUE TITLE
Stack in awaited thenable object does not include parent

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#23146]
This seems like something in v8 because it happens in node, chrome, and Deno.

```js
const obj = {
  then(onfulfilled, onrejected) {
    console.log(new Error().stack); // bad
    return Promise.resolve(1).then(onfulfilled, onrejected);
  }
};

await test();
await new Promise(resolve => {
  console.log(new Error().stack); // good
  resolve();
});

async function test() {
  console.log(new Error().stack); // good
  await obj;
  console.log(new Error().stack); // good
}
```

Output:

```
> deno run main.mjs
Error
    at test (file:///V:/scratch/main.mjs:15:15)
    at file:///V:/scratch/main.mjs:8:7
Error
    at Object.then (file:///V:/scratch/main.mjs:3:17)
Error
    at test (file:///V:/scratch/main.mjs:17:15)
    at async file:///V:/scratch/main.mjs:8:1
Error
    at file:///V:/scratch/main.mjs:10:15
    at new Promise (<anonymous>)
    at file:///V:/scratch/main.mjs:9:7
```

Version: Deno 1.42.0

**Comment by dsherret** [comment]
v8 PR: https://chromium-review.googlesource.com/c/v8/v8/+/6826001

**Comment by dsherret** [comment]
This is fixed now.
