### ISSUE TITLE
Bug: `MessageChannel` port.on is not a function (vitest)

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23185]
Tried to run  `vitest` with Deno and ran into an issue in relation to `MessageChannel` ports being passed around.

## Steps to reproduce

1. Create file `foo.ts` with these contents:
  ```ts
  import Tinypool from "npm:tinypool";

  const pool = new Tinypool({
    filename: new URL("./worker.mjs", import.meta.url).href,
  });
  const result = await pool.run({ a: 4, b: 6 });
  console.log(result); // Prints 10

  await pool.destroy();
  ```
2. Create file `worker.mjs` with these contents:
  ```ts
  export default ({ a, b }) =>  a + b);
  ```
3. Run `deno run -A foo.ts`

## Error

```sh
error: Uncaught (in promise) TypeError: this.port.on is not a function
    at new WorkerInfo (file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/tinypool/0.8.3/dist/esm/index.js:522:15)
    at ThreadPool._addNewWorker (file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/tinypool/0.8.3/dist/esm/index.js:705:24)
    at ThreadPool._ensureMinimumWorkers (file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/tinypool/0.8.3/dist/esm/index.js:663:12)
    at new ThreadPool (file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/tinypool/0.8.3/dist/esm/index.js:648:10)
    at new Tinypool (file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/tinypool/0.8.3/dist/esm/index.js:950:31)
    at file:///Users/marvinh/dev/test/deno-worker/foo.ts:4:14
```

Version: Deno 1.42.1

**Comment by bartlomieju** [comment]
It was fixed earlier today in https://github.com/denoland/deno/pull/22999
