### ISSUE TITLE
node:module register is not a function

### ISSUE THREAD

**Issue by ry** [denoland/deno#23201]
Version: deno 1.42.1+92a8ada

https://nodejs.org/docs/latest/api/module.html#moduleregisterspecifier-parenturl-options

```
# npm init @observablehq
# cd hello-framework
# deno task dev --debug
Task dev observable preview "--debug"

Unexpected error: N.register is not a function
The full error follows

error: Uncaught (in promise) TypeError: N.register is not a function
    at C (file:///Users/ry/src/hello-framework/node_modules/.deno/@observablehq+framework@1.2.0/node_modules/tsx/dist/esm/index.mjs:1:695)
    at file:///Users/ry/src/hello-framework/node_modules/.deno/@observablehq+framework@1.2.0/node_modules/tsx/dist/esm/index.mjs:5:1913
```

**Comment by bartlomieju** [comment]
This is trouble, it's essentially custom loaders: https://nodejs.org/docs/latest/api/module.html#customization-hooks that need to be executed before the actual code is executed.

**Comment by marvinhagemeister** [comment]
The the `observable` package only used `module.register()` to add support for running TS code, this works now thanks to https://github.com/denoland/deno/pull/24965 . There the function is merely stubbed, but that's enough to unblock `observable`.

**Comment by terrablue** [comment]
I would benefit from Deno supporting that. @bartlomieju FWIW, Node has a static and dynamic mode for that. With the `--import` flag, it indeed needs to run before any code is loaded, but programmatically (this issue's case), it can be executed at any time in the lifecycle of the program, but then only applies to thereafter dynamically imported modules.

Interestingly enough, normal (static) imports from post-registration dynamically loaded modules seem to also work in my tests.

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/33763 and https://github.com/denoland/deno/pull/33849

**Comment by AugustinMauroy** [comment]
hey guy's I'm testing if customization hooks work on deno to document it on my project (nodejs-loader).
but your docs said that it's should work. but I can do it ...

```js
import * as module from 'node:module';

module.register('@nodejs-loaders/yaml', import.meta.url);

console.log(await import('./foo.yaml'));
```

```js
import * as module from 'node:module';
import * as aliasLoader from '@nodejs-loaders/yaml/yaml.loader.mjs';

module.registerHooks(aliasLoader);

console.log(await import('./foo.yaml'));
```

output with `register`
```
deno script.ts 
✅ Granted read access to "/@nodejs-loaders/yaml".
error: Uncaught (in promise) TypeError: Expected a JavaScript or TypeScript module, but identified a Unknown module. Importing these types of modules is currently not supported.
  Specifier: file:///foo.yaml
console.log(await import('./foo.yaml'));
            ^
    at async file:///script.ts:7:13
```

output with `registerHooks` 
```
deno script.ts                            
error: Uncaught (in promise) TypeError: TypeError: Cannot read properties of null (reading 'split')
console.log(await import('./foo.yaml'));
            ^
    at async file:///script.ts:7:13
```

I use `deno 2.7.14+930550d`

**Comment by bartlomieju** [comment]
FYI we reverted support for `module.register()` in https://github.com/denoland/deno/pull/34077 after all. For the reasoning see https://github.com/denoland/deno/issues/34059#issuecomment-4453467967. Please use new `module.registerHooks()` API instead.

**Comment by AugustinMauroy** [comment]
Okay make sense!
