### ISSUE TITLE
issue with slow type lint

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#23260]
Version: deno 1.42.1 (release, x86_64-unknown-linux-gnu)

trying to deno publish this project I get this error
```
error[missing-explicit-type]: missing explicit type in the public API
   --> /home/mrcool/dev/deno/camera/src/ffi.ts:323:7
    |
323 | const SYMBOLS = {
    |       ^^^^^^^ this symbol is missing an explicit type
```

but I'm using `satisfies Deno.ForeignLibraryInterface;`  https://github.com/sigmaSd/Camera/blob/master/src/ffi.ts#L391C3-L391C42

Changing that line to `as const` gives me another error
```
Checking for slow types in the public API...
Check file:///home/mrcool/dev/deno/camera/src/camera.ts
Check file:///home/mrcool/dev/deno/camera/src/openpnp.ts
Check file:///home/mrcool/dev/deno/camera/src/ffi.ts
error: Failed ensuring public API type output is valid.

TS2344 [ERROR]: Type '{ readonly Cap_createContext: { readonly parameters: readonly []; readonly result: string; }; readonly Cap_getDeviceCount: { readonly parameters: readonly [string]; readonly result: "u32"; }; readonly Cap_getDeviceName: { ...; }; ... 11 more ...; readonly Cap_hasNewFrame: { ...; }; }' does not satisfy the constraint 'ForeignLibraryInterface'.
  Property 'Cap_createContext' is incompatible with index signature.
    Type '{ readonly parameters: readonly []; readonly result: string; }' is not assignable to type 'ForeignFunction<readonly NativeType[], NativeResultType, boolean> | ForeignStatic<NativeType>'.
      Type '{ readonly parameters: readonly []; readonly result: string; }' is not assignable to type 'ForeignFunction<readonly NativeType[], NativeResultType, boolean>'.
        Types of property 'result' are incompatible.
          Type 'string' is not assignable to type 'NativeResultType'.
 */ export const LIBRARY: Deno.DynamicLibrary<typeof SYMBOLS> = {} as never;
                                              ~~~~~~~~~~~~~~
    at file:///home/mrcool/dev/deno/camera/src/ffi.ts:396:28

TS2344 [ERROR]: Type '{ readonly Cap_createContext: { readonly parameters: readonly []; readonly result: string; }; readonly Cap_getDeviceCount: { readonly parameters: readonly [string]; readonly result: "u32"; }; readonly Cap_getDeviceName: { ...; }; ... 11 more ...; readonly Cap_hasNewFrame: { ...; }; }' does not satisfy the constraint 'ForeignLibraryInterface'.
 */ export function instantiate(): Promise<Deno.DynamicLibrary<typeof SYMBOLS>> {
                                                               ~~~~~~~~~~~~~~
    at file:///home/mrcool/dev/deno/camera/src/ffi.ts:403:8

Found 2 errors.

You may have discovered a bug in Deno. Please open an issue at: https://github.com/denoland/deno/issues/
```

**Comment by sigmaSd** [comment]
Answer from aapoalas 
>You need to mark all the CapContext etc properties as const as well. Otherwise it's taking the "pointer" to mean "just some string".

![image](https://github.com/denoland/deno/assets/22427111/7f7d493a-4fff-4197-93c9-d1bd0663a664)
