### ISSUE TITLE
Unexpected type checking fail with jsr when mapped type has a named type

### ISSUE THREAD

**Issue by kuuote** [denoland/deno#23284]
Version: Deno 1.42.1

# To Reproduce

Save following code and execute `deno check a.ts`:
 
```typescript
import * as u from "jsr:/@core/unknownutil@3.17.2";

const a = u.isObjectOf({
  a: u.isOptionalOf(u.isUnknown),
});

type A = u.PredicateType<typeof a>;

const aa: A = {}; 
```

Outputs following error:

```
error: TS2741 [ERROR]: Property 'a' is missing in type '{}' but required in type '{ a: unknown; }'.
const aa: A = {};
      ~~
    at file:///tmp/a.ts:9:7

    'a' is declared here.
      a: u.isOptionalOf(u.isUnknown),
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at file:///tmp/a.ts:4:3
```

# Note

Same library version from npm passes type cheking.

```typescript
import * as u from "npm:unknownutil@3.17.2";

const a = u.isObjectOf({
  a: u.isOptionalOf(u.isUnknown),
});

type A = u.PredicateType<typeof a>;

const aa: A = {}; 
```

**Comment by dsherret** [comment]
Sorry we missed this one earlier. I have a fix at https://github.com/swc-project/swc/pull/9038
