### ISSUE TITLE
`op_message_port_recv_message_sync`  BorrowMutErrror in node:worker

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#23362]
To reproduce:
1. Add a stub for `AsyncResource#asyncId()` 
2. Follow steps provided in https://github.com/denoland/deno/issues/23263#issue-2229676258

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.42.3
Args: ["/home/divy/gh/littledivy/deno/target/debug/deno", "run", "-A", "foo.ts"]

thread 'worker-1' panicked at ext/web/message_port.rs:238:33:
already borrowed: BorrowMutError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by marvinhagemeister** [comment]
@bartlomieju Reopening, I can still reproduce the issue with the same reproduction from https://github.com/denoland/deno/issues/23263#issue-2229676258 with a Deno git build (0a7f46b8c) that includes the referenced PR here.

```sh
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.42.4
Args: ["/Users/marvinh/dev/denoland/deno/target/debug/deno", "run", "-A", "main.ts"]

thread 'worker-1' panicked at ext/web/message_port.rs:239:33:
already borrowed: BorrowMutError
```
