### ISSUE TITLE
`Deno.read` and `Deno.write` cause crash when invalid args are passed

### ISSUE THREAD

**Issue by diskkid** [denoland/deno#2341]
Passing invalid arguments to `Deno.read` and `Deno.write` (like `Deno.read()`, `Deno.read(null, null)`, and so on) cause a crash in Rust, without raising a JavaScript exception.

Here is my reproduction code.

```ts
try {
  Deno.write(null, null)
} catch (e) {
  console.log(e)
}
```

```sh
$ RUST_BACKTRACE=1 deno run crash_write.ts 

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: core::option::Option<T>::unwrap
             at /rustc/d595b113584f8f446957469951fd5d31adc2a44e/src/libcore/macros.rs:12
  10: deno_bin::dispatch_minimal::ops::write
             at ../../cli/dispatch_minimal.rs:154
  11: deno_bin::dispatch_minimal::dispatch_minimal
             at ../../cli/dispatch_minimal.rs:96
  12: deno_bin::ops::dispatch_all
             at ../../cli/ops.rs:88
  13: deno_bin::state::ThreadSafeState::dispatch
             at ../../cli/state.rs:86
  14: deno_bin::worker::Worker::new::{{closure}}
             at ../../cli/worker.rs:39
  15: deno::isolate::Isolate::pre_dispatch
             at ../../core/isolate.rs:195
  16: _ZN4deno4SendERKN2v820FunctionCallbackInfoINS0_5ValueEEE
             at ./../../core/libdeno/binding.cc:242
  17: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
             at ../../third_party/v8/src/api-arguments-inl.h:157
  18: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
             at ./../../third_party/v8/src/builtins/builtins-api.cc:109
  19: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
             at ./../../third_party/v8/src/builtins/builtins-api.cc:139
  20: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
             at ./../../third_party/v8/src/builtins/builtins-api.cc:127
  21: <unknown>
fatal runtime error: failed to initiate panic, error 5
zsh: abort (core dumped)  RUST_BACKTRACE=1 deno run crash_write.ts
```

**Comment by NamPNQ** [comment]
it is the user's problem.

**Comment by kitsonk** [comment]
As stated in the related PR, better handling in Rust is needed, not parameter checking in JavaScript.
