### ISSUE TITLE
`deno test` panics by deadlock at `cli/tools/test/channel.rs:428:7`

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno#23415]
## What happens

`deno test --parallel --junit-path=foo.xml` occasionally panics. The error log says "Test flush deadlock 2, sender closed = false" (full log is below)

## Log

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.42.2
Args: ["deno", "test", "-A", "--quiet", "--unstable-http", "--cert", "./local_certs/pki/root_ca.crt", "--no-check", "--parallel", "./tests/e2e_integration", "--junit-path=reports/e2e.xml"]

thread 'tokio-runtime-worker' panicked at cli/tools/test/channel.rs:428:7:
Test flush deadlock 2, sender closed = false
stack backtrace:
   0:     0x555992d58626 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
   1:     0x555992d8d310 - core::fmt::write::he40921d4802ce2ac
   2:     0x555992d51f0f - std::io::Write::write_fmt::h5de5a4e7037c9b20
   3:     0x555992d58404 - std::sys_common::backtrace::print::h11c067a88e3bdb22
   4:     0x555992d5a177 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
   5:     0x555992d59ed9 - std::panicking::default_hook::h1633e272b4150cf3
   6:     0x555993298420 - deno::setup_panic_hook::{{closure}}::h42df80e2e5b0ac9c
   7:     0x555992d5a806 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
   8:     0x555992d5a552 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
   9:     0x555992d58b26 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
  10:     0x555992d5a2a4 - rust_begin_unwind
  11:     0x555992d8a3a5 - core::panicking::panic_fmt::ha6effc2775a0749c
  12:     0x555993235819 - deno::tools::test::channel::TestEventSender::flush::h75a4895e86b06cb1
  13:     0x5559932355e7 - deno::tools::test::channel::TestEventSender::send::h17920caffadfe4b9
  14:     0x55599331359d - deno::ops::testing::op_test_event_step_result_ok::v8_fn_ptr_metrics::ha89a5aedbab9e1b3
  15:     0x555992b605e4 - Builtins_CallApiCallbackGeneric
```

If `RUST_BACKTRACE=1` may be helpful I can add it and wait until this panic occurs again.

## Other Info

Version: Deno 1.42.2

We will bump the version to the latest (1.42.4) soon and see if this issue remains. Once it's proved to remain, I'll update the version info here.

#23210 <- I guess this issue should have fixed this panic and is included in v1.42.2, but with 1.42.2 we still see this panic happen

(Update) with v1.42.4 we still get this panic.

**Comment by lucacasonato** [comment]
@magurotuna Are you still seeing this?

**Comment by magurotuna** [comment]
No apparently this was fixed at some point. Closing.
