### ISSUE TITLE
Error.cause is not inspect-formatted when printed by console.log

### ISSUE THREAD

**Issue by exe-dealer** [denoland/deno#23416]
```
$ deno --version
deno 1.42.4 (release, x86_64-unknown-linux-gnu)
v8 12.3.219.9
typescript 5.4.3
```

```js
// $ cat example.js
const err = Error('boom', {
  cause: {
    code: 100500,
  },
});

console.log(err);
```

actual behavior

```
$ deno run example.js
Error: boom
    at file:///home/v.nezhutin/pgwire/example.js:1:13
Caused by [object Object]
```

expected behavior

```
$ deno run example.js
Error: boom
    at file:///home/v.nezhutin/pgwire/example.js:1:13
Caused by: { code: 100500 }
```

**Comment by exe-dealer** [comment]
mdn says that its ok to use non Error object as Error.cause https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause#providing_structured_data_as_the_error_cause
