### ISSUE TITLE
Deno.rename not handling [ characters

### ISSUE THREAD

**Issue by will-weiss** [denoland/deno#23428]
Version: Deno 1.42.0

Hello! When trying to run Deno.rename on a file with a `[` character in the name, I receive an error informing me the file doesn't exist, even though it does. Thanks in advance!

```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2): rename 'routes/app/facilities/[facility_id]/inventory.tsx' -> 'routes/app/organizations/[facility_id]/inventory.tsx'
      await Deno.rename(path, newFilePath)
      ^
    at async Object.rename (ext:deno_fs/30_fs.js:273:3)
    at async file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/scripts/rename.ts:44:7
```

**Comment by will-weiss** [comment]
Got it, thanks @dsherret! That was definitely the problem as the parent folder indeed doesn't exist. If rename doesn't behave like `mv`, perhaps a better error message would call out the first non-existent directory. Something like:

```
error: Uncaught (in promise) NotFound: No such directory 'routes/app/organizations' (os error 2): rename 'routes/app/facilities/[facility_id]/inventory.tsx' -> 'routes/app/organizations/[facility_id]/inventory.tsx'
      await Deno.rename(path, newFilePath)
```

**Comment by will-weiss** [comment]
Got it, thanks @dsherret! That was definitely the problem as the parent folder indeed doesn't exist. Testing out `mv` that functions exactly the same way, so I guess that can be expected. I'll close this ticket
