### ISSUE TITLE
Cannot find module @rollup/rollup-linux-x64-gnu

### ISSUE THREAD

**Issue by rroblf01** [denoland/deno#23440]
Version: Deno canary
OS: Windows 11 WSL
```
deno upgrade --canary
Looking up latest canary version
Local deno version 5e2a747685490b31efa778241fccf938bd33722d is the most recent release
```

I was trying to run an ng serve (Angular 17.3.2) with deno canary, but I'm getting this error.

```
deno run -A npm:@angular/cli serve

error: Uncaught Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (file:///mnt/c/Users/Sheik/Documents/proyectos/typefast/node_modules/rollup/dist/native.js:59:9)
    at Object.<anonymous> (file:///mnt/c/Users/Sheik/Documents/proyectos/typefast/node_modules/rollup/dist/native.js:68:76)
    at Object.<anonymous> (file:///mnt/c/Users/Sheik/Documents/proyectos/typefast/node_modules/rollup/dist/native.js:107:4)
    at Module._compile (node:module:653:34)
    at Object.Module._extensions..js (node:module:667:10)
    at Module.load (node:module:591:32)
    at Function.Module._load (node:module:486:12)
    at Module.require (node:module:603:19)
    at require (node:module:709:16)
    at file:///mnt/c/Users/Sheik/Documents/proyectos/typefast/node_modules/rollup/dist/native.js:3:13
Caused by: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
Require stack:
- /mnt/c/Users/Sheik/Documents/proyectos/typefast/node_modules/rollup/dist/native.js
- /mnt/c/Users/Sheik/Documents/proyectos/typefast/node_modules/rollup/dist/native.js
    at Function.Module._resolveFilename (node:module:566:15)
    at Function.Module._load (node:module:453:27)
    at Module.require (node:module:603:19)
    at require (node:module:709:16)
    at requireWithFriendlyError (file:///mnt/c/Users/Sheik/Documents/proyectos/typefast/node_modules/rollup/dist/native.js:41:10)
    at Object.<anonymous> (file:///mnt/c/Users/Sheik/Documents/proyectos/typefast/node_modules/rollup/dist/native.js:68:76)
    at Object.<anonymous> (file:///mnt/c/Users/Sheik/Documents/proyectos/typefast/node_modules/rollup/dist/native.js:107:4)
    at Module._compile (node:module:653:34)
    at Object.Module._extensions..js (node:module:667:10)
    at Module.load (node:module:591:32)
 ```

**Comment by joshcancode** [comment]
For anyone having this issue, my issue was that I was executing this from an external drive mounted with the "noexec" flag. Moving this to my host drive or remounting the drive without "noexec" fixed the issue.
