### ISSUE TITLE
Loading @napi-rs/cli bindings in built npm package on windows / deploy

### ISSUE THREAD

**Issue by WingZer0o** [denoland/deno#23465]
Version: deno 1.42.4 (release, x86_64-pc-windows-msvc)

My personal cryptographic NPM package that creates Rust bindings to a TS lib through @napi-rs/cli seems to be working fine on Debian in WSL. However, when running on Windows or attempting to deploy the project to deploy I get the following error(s).

Perhaps this is an error in the way I constructed my NPM package? I am not the most experienced with crafting NPM packages and Deno.

No rush or anything, Would be happy to help investigate the issue or possibly submit a PR if the issue is not with my lib. 

Windows  Error
```
error: Uncaught (in promise) TypeError: LoadLibraryExW failed
    at Object.Module._extensions..node (node:module:698:20)
    at Module.load (node:module:591:32)
    at Function.Module._load (node:module:486:12)
    at Module.require (node:module:603:19)
    at require (node:module:709:16)
    at Object.<anonymous> (file:///C:/Users/mtmul/AppData/Local/deno/npm/registry.npmjs.org/cas-typescript-sdk/1.0.16/lib/password-hashers/argon2-wrapper.js:4:17)
    at Object.<anonymous> (file:///C:/Users/mtmul/AppData/Local/deno/npm/registry.npmjs.org/cas-typescript-sdk/1.0.16/lib/password-hashers/argon2-wrapper.js:21:4)
    at Module._compile (node:module:653:34)
    at Object.Module._extensions..js (node:module:667:10)
    at Module.load (node:module:591:32)
```

Deploy Error
```
error: The deployment failed: UNCAUGHT_EXCEPTION

Error: Node API is not supported in this environment
    at Object.Module._extensions..node (node:module:697:20)
    at Module.load (node:module:590:32)
    at Function.Module._load (node:module:485:12)
    at Module.require (node:module:602:19)
    at require (node:module:708:16)
    at Object.<anonymous> (file:///node_modules/.deno/cas-typescript-sdk@1.0.16/node_modules/cas-typescript-sdk/lib/password-hashers/argon2-wrapper.js:4:17)
    at Object.<anonymous> (file:///node_modules/.deno/cas-typescript-sdk@1.0.16/node_modules/cas-typescript-sdk/lib/password-hashers/argon2-wrapper.js:21:4)
    at Module._compile (node:module:652:34)
    at Object.Module._extensions..js (node:module:666:10)
    at Module.load (node:module:590:32)
```

index.ts
```typescript
import { Application } from "https://deno.land/x/oak/mod.ts";
import router from "./router-one.ts";

const app = new Application();
app.use(router.routes());

await app.listen({ port: 8080 });
```

router-one.ts
```typescript
import { RouteParams, Router } from "https://deno.land/x/oak/mod.ts";
import { AESWrapper } from "npm:cas-typescript-sdk";

const router = new Router();

router.post("/testing", async (context) => {
  const body: TestingBody = await context.request.body.json();
  const aes = new AESWrapper();
  const nonce = aes.aesNonce();
  const key = aes.aes256Key();
  const encoder = new TextEncoder();
  const tohashBytes: Array<number> = Array.from(encoder.encode(body.email));
  const encrypted = aes.aes256Encrypt(key, nonce, tohashBytes);
  const decrypted = aes.aes256Decrypt(key, nonce, encrypted);
  const decoder = new TextDecoder();
  const decoded = decoder.decode(new Uint8Array(decrypted));
  context.response.body = decoded;
});

class TestingBody {
  public email!: string;
}

export default router;
```

Compiled TS file where the error points to
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AESWrapper = void 0;
const index_1 = require("../../index");
class AESWrapper {
    aes128Key() {
        return (0, index_1.aes128Key)();
    }
    aes256Key() {
        return (0, index_1.aes256Key)();
    }
    aesNonce() {
        return (0, index_1.aesNonce)();
    }
    aes128Encrypt(aesKey, nonce, plaintext) {
        return (0, index_1.aes128Encrypt)(aesKey, nonce, plaintext);
    }
    aes128Decrypt(aesKey, nonce, ciphertext) {
        return (0, index_1.aes128Decrypt)(aesKey, nonce, ciphertext);
    }
    aes256Encrypt(aesKey, nonce, plaintext) {
        return (0, index_1.aes256Encrypt)(aesKey, nonce, plaintext);
    }
    aes256Decrypt(aesKey, nonce, ciphertext) {
        return (0, index_1.aes256Decrypt)(aesKey, nonce, ciphertext);
    }
    aes256KeyFromX25519SharedSecret(shared_secret) {
        return (0, index_1.aes256KeyFromX25519SharedSecret)(shared_secret);
    }
    aes128KeyFromX25519SharedSecret(shared_secret) {
        return (0, index_1.aes128KeyFromX25519SharedSecret)(shared_secret);
    }
}
exports.AESWrapper = AESWrapper;
```

**Comment by lucacasonato** [comment]
NAPI is not supported on Deploy, that is correct. Deploy does not support suprocesses or node addons.

Are you using a binary built for Windows on Windows (and not accidentially a Linux binary?). Does it work on Windows in Node?

**Comment by WingZer0o** [comment]
This wasn't being done in deploy this was being done on my local machine. Its not a very popular library so usage would be low so I imagine its not a major priority. But yes this does work on Windows for node. Example below.

```typescript
import {AESWrapper} from "cas-typescript-sdk";



const aes = new AESWrapper();
  const nonce = aes.generateAESNonce();
  const key = aes.aes256Key();
  const encoder = new TextEncoder();
  const tohashBytes: Array<number> = Array.from(encoder.encode("sometestemail@outlook.com"));
  const encrypted = aes.aes256Encrypt(key, nonce, tohashBytes);
  const decrypted = aes.aes256Decrypt(key, nonce, encrypted);
  const decoder = new TextDecoder();
  const decoded = decoder.decode(new Uint8Array(decrypted));
  console.log(decoded);
```

**Comment by devsnek** [comment]
@WingZer0o if you rename `node.exe` to something else does it break in node as well?

**Comment by WingZer0o** [comment]
I don't have a node.exe in my current library, I have an index.node that is
compiled from @napi-rs is that what you are referring to?

**Comment by devsnek** [comment]
@WingZer0o I mean, on the windows computer you are running this on, when you run your code with Node.js, you're presumably using a `node.exe` binary. Can you try renaming it to something else and running your code? I believe this is due to an issue where native modules link against `node.exe` rather than the current process. `node-gyp` has a fix for this (https://github.com/nodejs/node-gyp/blob/main/src/win_delay_load_hook.cc) but `napi-rs` does not.

**Comment by WingZer0o** [comment]
Sorry about the terribly late response on this I forgot and have been contributing as much with this library. 

I was not using a binary this just using a tsc compiled typescript file then performing a `node index.js` test.

**Comment by WingZer0o** [comment]
Still haven't had time to get around to retesting this with the latest versions of Deno. I have some resign work in the core FFI layer that needs to be moved over first. Will give this another go.
