### ISSUE TITLE
SolidStart - Running server with https breaks

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#23471]
Repro

```sh
deno run -A npm:create-solid 
npm i
DENO_FUTURE=1 deno task dev
```

Enable https in one of the solid-start examples by changed the `app.config.ts` to this:

```ts
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  server: {
    https:true
  }
});

```

When run with `DENO_FUTURE=1 deno task dev` it'll break with: 

```ts
➜ DENO_FUTURE=1 deno task dev  
Task dev vinxi dev
vinxi v0.3.11
vinxi starting dev server

 ERROR  Not implemented: crypto.KeyObject.prototype.asymmetricKeyType                                                                                                                     3:17:44 PM

  at notImplemented (ext:deno_node/_utils.ts:6:9)
  at KeyObject.export (ext:deno_node/internal/crypto/keys.ts:74:5)
  at ext:deno_node/internal/crypto/keygen.ts:45:37
  at eventLoopTick (ext:core/01_core.js:168:7) 



 ERROR  Not implemented: crypto.KeyObject.prototype.asymmetricKeyType                                                                                                                     3:17:44 PM
```

Related to
- #21124
- #20604 
- #18928

**Comment by birkskyum** [comment]
Now getting slightly different error, but probably just a rename:

```sh
➜ DENO_FUTURE=1 deno task dev
Task dev vinxi dev
vinxi v0.3.11
vinxi starting dev server

 ERROR  Not implemented: crypto.PrivateKeyObject.prototype.export                                                                             4:36:45 PM

  at notImplemented (ext:deno_node/_utils.ts:6:9)
  at PrivateKeyObject.export (ext:deno_node/internal/crypto/keys.ts:201:5)
  at ext:deno_node/internal/crypto/keygen.ts:51:39
  at eventLoopTick (ext:core/01_core.js:168:7) 



 ERROR  Not implemented: crypto.PrivateKeyObject.prototype.export   
```

**Comment by birkskyum** [comment]
Now prints:

```ts
➜ DENO_FUTURE=1 deno task dev
Task dev vinxi dev
vinxi v0.4.1
vinxi starting dev server

 ERROR  Assignment to constant variable.                                                                                                                                                           10:57:41 AM

  at ext:deno_node/internal/crypto/keygen.ts:51:19
  at eventLoopTick (ext:core/01_core.js:174:7) 



 ERROR  Assignment to constant variable. 
```

**Comment by birkskyum** [comment]
Alright, with the latest fix I now get this:

```sh
⇣4% ➜ DENO_FUTURE=1 RUST_BACKTRACE=1 /Users/admin/repos/deno/target/debug/deno task dev
Task dev vinxi dev
vinxi v0.4.1
vinxi starting dev server

  ➜ Local:    https://localhost:3000/
  ➜ Network:  use --host to expose


============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.45.5
Args: ["/Users/admin/repos/deno/target/debug/deno", "run", "--ext=js", "-A", "/Users/admin/repos/deno-kitchensink/https-solid/node_modules/.bin/../vinxi/bin/cli.mjs", "dev"]

thread 'worker-1' panicked at /Users/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.303.0/gotham_state.rs:74:3:
required type deno_runtime::ops::bootstrap::SnapshotOptions is not present in GothamState container
stack backtrace:
   0: rust_begin_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
   2: deno_core::gotham_state::missing
             at /Users/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.303.0/gotham_state.rs:74:3
   3: deno_core::gotham_state::GothamState::take::{{closure}}
             at /Users/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.303.0/gotham_state.rs:69:39
   4: core::option::Option<T>::unwrap_or_else
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/option.rs:980:21
   5: deno_core::gotham_state::GothamState::take
             at /Users/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.303.0/gotham_state.rs:69:5
   6: deno_runtime::ops::bootstrap::op_snapshot_options::op_snapshot_options::call
             at /Users/admin/repos/deno/runtime/ops/bootstrap.rs:69:3
   7: deno_runtime::ops::bootstrap::op_snapshot_options::op_snapshot_options::slow_function_impl
             at /Users/admin/repos/deno/runtime/ops/bootstrap.rs:66:1
   8: deno_runtime::ops::bootstrap::op_snapshot_options::op_snapshot_options::v8_fn_ptr
             at /Users/admin/repos/deno/runtime/ops/bootstrap.rs:66:1
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by birkskyum** [comment]
Tried using the latest canary `deno 1.45.5+6522478` instead of a local build, and it did the trick!
