### ISSUE TITLE
SolidStart - with-authjs example breaks

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#23474]
deno 1.42.4+04c6785

Repro:

- deno run -A npm:create-solid
- select SolidStart, TypeScript, **with-authjs**
- npm i
- rename .env.example -> .env, and add some random string for the DISCORD_CLIENT_ID/SECRET
- DENO_FUTURE=1 deno task dev

Error on the server - doesn't load the .env:

```zig
➜ DENO_FUTURE=1 deno task dev                                                               
Task dev vinxi dev
vinxi v0.3.11
vinxi starting dev server

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

10:25:50 PM [vite] Error when evaluating SSR module /src/server/auth.ts:
|- TypeError: Cannot read properties of undefined (reading 'env')
    at eval (/Users/admin/repos/deno-kitchensink/authjs/src/server/auth.ts, <anonymous>:7:23)
    at async instantiateModule (file:///Users/admin/repos/deno-kitchensink/authjs/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:55036:9)

10:25:50 PM [vite] Error when evaluating SSR module /src/routes/api/auth/[...solidauth].ts?pick=GET: failed to import "/src/server/auth.ts"
|- TypeError: Cannot read properties of undefined (reading 'env')
    at eval (/Users/admin/repos/deno-kitchensink/authjs/src/server/auth.ts, <anonymous>:7:23)
    at async instantiateModule (file:///Users/admin/repos/deno-kitchensink/authjs/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:55036:9)

[h3] [unhandled] TypeError: Cannot read properties of undefined (reading 'env')
    at eval (/Users/admin/repos/deno-kitchensink/authjs/src/server/auth.ts, <anonymous>:7:23)
    at async instantiateModule (file:///Users/admin/repos/deno-kitchensink/authjs/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:55036:9)
Caused by TypeError: Cannot read properties of undefined (reading 'env')
    at eval (/Users/admin/repos/deno-kitchensink/authjs/src/server/auth.ts, <anonymous>:7:23)
    at async instantiateModule (file:///Users/admin/repos/deno-kitchensink/authjs/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:55036:9) {
  cause: TypeError: Cannot read properties of undefined (reading 'env')
    at eval (/Users/admin/repos/deno-kitchensink/authjs/src/server/auth.ts, <anonymous>:7:23)
    at async instantiateModule (file:///Users/admin/repos/deno-kitchensink/authjs/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:55036:9),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
```

Expected:
Similar to when running with node, I expected to see this (ofc. the login button won't work with wrong keys):
<img width="536" alt="Screenshot 2024-04-20 at 22 15 00" src="https://github.com/denoland/deno/assets/74932975/dc6f2b0d-3303-4bdf-9853-72e7d3923839">

Blocked by:
- #21124

- #24061 
- #20604 
- #20886
- #13451
- #21806

**Comment by birkskyum** [comment]
It seems like this is working now
deno 1.45.5+6522478
