### ISSUE TITLE
bug: WPT failing due to `PermissionDenied: permission denied: readfile '/etc/hosts'` error

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#23500]
To reproduce, run:
```
deno run --unstable --allow-write --allow-read --allow-net --allow-env --allow-run --lock=tools/deno.lock.json ./tests/wpt/wpt.ts setup
```
Output:
```
⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
INFO:manifest:Downloading manifest from https://github.com/web-platform-tests/wpt/releases/download/merge_pr_45682/MANIFEST-daa07cf3c47652ed67e637f2a39bbc34f91cfe10.json.bz2
INFO:manifest:Manifest downloaded
INFO:manifest:Updating manifest
error: Uncaught (in promise) PermissionDenied: permission denied: readfile '/etc/hosts'
  const hostsFile = await Deno.readTextFile(hostsPath);
                               ^
    at Object.readTextFile (ext:deno_fs/30_fs.js:878:24)
    at setup (file:///Users/asher/GitHub/deno/tests/wpt/wpt.ts:110:32)
    at file:///Users/asher/GitHub/deno/tests/wpt/wpt.ts:71:11
    at eventLoopTick (ext:core/01_core.js:168:7)
```
It seems likely that this was caused by #23208, which, once included in the canary, caused https://github.com/denoland/deno/actions/runs/8768910601/job/24063832309 to fail.

CC @mmastrac

**Comment by bartlomieju** [comment]
You can fix it by using `-A` permission instead

**Comment by iuioiua** [comment]
So this is intentional? If so, is there some issue or documentation to refer to?
