### ISSUE TITLE
setAsyncHandler fails in core/examples/http_bench.js

### ISSUE THREAD

**Issue by base698** [denoland/deno#2351]
Probably pebkac, but running this example fails on checking to make sure the setAsyncHandler is null: https://github.com/denoland/deno/blob/master/core/shared_queue.js#L148

```
$ deno run ./core/examples/http_bench.js

shared_queue.js:59:12
      throw Error("assert");
            ^
Uncaught Error: assert
    at assert (shared_queue.js:59:13)
    at setAsyncHandler (shared_queue.js:148:5)
    at main (file://workspaces/deno/core/examples/http_bench.js:126:13)
    at file:///workspaces/deno/core/examples/http_bench.js:143:1
```

**Comment by ry** [comment]
It's a standalone executable. Try this
```
./tools/build.py deno_core_http_bench --release
./target/release/deno_core_http_bench
```
