### ISSUE TITLE
Bug: DOMException error when running parcel

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23522]
## Steps to reproduce

1. Create `index.html` file with these contents:
  ```html
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8"/>
      <title>My First Parcel App</title>
    </head>
    <body>
      <h1>Hello, World!</h1>
    </body>
  </html>
  ```
2. Run `npm init -y && npm i parcel`
3. Run `DENO_FUTURE=1 deno run -A npm:parcel index.html`

## Error

```sh
DOMException: #<Object> could not be cloned.
    at new DOMException (ext:deno_web/01_dom_exception.js:116:20)
    at ext:deno_web/13_message_port.js:389:11
    at Object.serialize (ext:core/01_core.js:672:14)
    at serializeJsMessageData (ext:deno_web/13_message_port.js:388:31)
    at new NodeWorker (node:worker_threads:129:38)
    at ThreadsWorker.start (file:///Users/marvinh/dev/test/deno-parcel/node_modules/.pnpm/@parcel+workers@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:38:19)
    at Worker.fork (file:///Users/marvinh/dev/test/deno-parcel/node_modules/.pnpm/@parcel+workers@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/workers/lib/Worker.js:90:23)
    at WorkerFarm.startChild (file:///Users/marvinh/dev/test/deno-parcel/node_modules/.pnpm/@parcel+workers@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/workers/lib/WorkerFarm.js:229:12)
    at WorkerFarm.startMaxWorkers (file:///Users/marvinh/dev/test/deno-parcel/node_modules/.pnpm/@parcel+workers@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/workers/lib/WorkerFarm.js:389:14)
    at new WorkerFarm (file:///Users/marvinh/dev/test/deno-parcel/node_modules/.pnpm/@parcel+workers@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/workers/lib/WorkerFarm.js:136:10)
```

Related https://github.com/denoland/deno/issues/23281

Version: Deno 1.42.4 (git 5294885a5 2024-04-24)

**Comment by marvinhagemeister** [comment]
Whoops, you're right. It looks like I had `parcel` installed via npm. I'll update the reproduction instructions.

**Comment by bartlomieju** [comment]
I tracked down the problem to the fact that `env` is passed to worker on startup to be sent to the worker environment. It appears that `env` is not a regular object (but maybe some kind of proxy) that causes this error. Opened: https://github.com/denoland/deno/pull/23536

That said, even if we fix this, running this program still completely freezes the terminal and you need to manually kill the process from a separate terminal.

**Comment by marvinhagemeister** [comment]
@bartlomieju Looks like I closed https://github.com/denoland/deno/issues/23281 prematurely
