### ISSUE TITLE
Panic when passing wildcard to allow-net

### ISSUE THREAD

**Issue by iMarv** [denoland/deno#23552]
Platform: linux x86_64
Version: 1.42.1
Args: ["deno", "run", "--allow-read", "--allow-write=notion-next", "--allow-net=api.notion.com,*.amazonaws.com", "--allow-env", "main.ts"]

thread 'main' panicked at runtime/permissions/lib.rs:741:22:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar

**Comment by yazan-nidal** [comment]
Please provide a reproducible example and more info

**Comment by iMarv** [comment]
That in itself should be reproducible with an empty main.ts, as it seems to be a bug with parsing in the cli itself.

**Comment by yazan-nidal** [comment]
Hi @mmastrac @iMarv,
I checked the issue and ,
it was fixed by this PR 
https://github.com/denoland/deno/pull/23590
so can u please review it?

**Comment by yazan-nidal** [comment]
@iMarv @mmastrac 
 
 what the expected outcome?

**Comment by iMarv** [comment]
It should not panic I guess. 

I am not a maintainer, but I would figure that it shall throw some error that wildcards are not allowed.

**Comment by lucacasonato** [comment]
This now does not panic anymore

**Comment by joscha** [comment]
I can still see this panicking
```
Task test:single deno test --allow-env=API_KEY,NODE_EXTRA_CA_CERTS '--allow-net=api.affinity.co,*.amazonaws.com:443' --doc --allow-read=./src/v1/tests/ "src/v1/tests/entity_files_test.ts"

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.45.2
Args: ["/nix/store/xiz264k79b2419vp0b82v15k552whcgp-deno-1.45.2/bin/deno", "test", "--allow-env=API_KEY,NODE_EXTRA_CA_CERTS", "--allow-net=api.affinity.co,*.amazonaws.com:443", "--doc", "--allow-read=./src/v1/tests/", "src/v1/tests/entity_files_test.ts"]

thread 'main' panicked at cli/args/flags.rs:4628:60:
called `Result::unwrap()` on an `Err` value: ErrorInner { kind: InvalidValue, context: FlatMap { keys: [], values: [] }, message: Some(Raw("invalid host: '*.amazonaws.com'\n\nCaused by:\n    invalid char found in FQDN")), source: None, help_flag: None, styles: Styles { header: Style { fg: None, bg: None, underline: None, effects: Effects() }, error: Style { fg: None, bg: None, underline: None, effects: Effects() }, usage: Style { fg: None, bg: None, underline: None, effects: Effects() }, literal: Style { fg: None, bg: None, underline: None, effects: Effects() }, placeholder: Style { fg: None, bg: None, underline: None, effects: Effects() }, valid: Style { fg: None, bg: None, underline: None, effects: Effects() }, invalid: Style { fg: None, bg: None, underline: None, effects: Effects() } }, color_when: Never, color_help_when: Never, backtrace: None }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I can't see this issue mentioned on https://github.com/denoland/deno/releases anywhere, so I am not sure if it's fixed somewhere upstream from 1.45.2?

**Comment by joscha** [comment]
#24397 is closed against `1.45.0` which means in `1.45.2` (see above) it shouldn't panic anymore?

**Comment by bartlomieju** [comment]
I can confirm that it still panics on latest Deno

**Comment by yazan-abdalrahman** [comment]
> I can confirm that it still panics on latest Deno
@bartlomieju 

![image](https://github.com/user-attachments/assets/af5a67f6-9c6f-4648-b420-48d687eedf75)
 
I will work on it, okay?

**Comment by yazan-abdalrahman** [comment]
Panic when passing wildcard to allow-net #23552
Open
[iMarv](https://github.com/iMarv) opened this issue on Apr 25 · 10 comments
Open
[Panic when passing wildcard to allow-net](https://github.com/denoland/deno/issues/23552#top)
#23552
[iMarv](https://github.com/iMarv) opened this issue on Apr 25 · 10 comments
Comments
@[iMarv](https://github.com/iMarv)
iMarv commented [on Apr 25](https://github.com/denoland/deno/issues/23552#issue-2263388413)
Platform: linux x86_64
Version: 1.42.1
Args: ["deno", "run", "--allow-read", "--allow-write=notion-next", "--allow-net=api.notion.com,*.amazonaws.com", "--allow-env", "main.ts"]

thread 'main' panicked at runtime/permissions/lib.rs:741:22:
called Result::unwrap() on an Err value: InvalidLabelChar

@[marvinhagemeister](https://github.com/marvinhagemeister) marvinhagemeister added [bug](https://github.com/denoland/deno/labels/bug) [cli](https://github.com/denoland/deno/labels/cli) labels [on Apr 25](https://github.com/denoland/deno/issues/23552#event-12607881255)
@[yazan-nidal](https://github.com/yazan-nidal)
yazan-nidal commented [on Apr 28](https://github.com/denoland/deno/issues/23552#issuecomment-2081495152)
Please provide a reproducible example and more info

@[mmastrac](https://github.com/mmastrac) mmastrac mentioned this issue [on Apr 28](https://github.com/denoland/deno/issues/23552#ref-pullrequest-2267549516)
https://github.com/denoland/deno/pull/23590
 Closed
@[iMarv](https://github.com/iMarv)
Author
iMarv commented [on Apr 29](https://github.com/denoland/deno/issues/23552#issuecomment-2082028649)
That in itself should be reproducible with an empty main.ts, as it seems to be a bug with parsing in the cli itself.

@[yazan-nidal](https://github.com/yazan-nidal)
yazan-nidal commented [on Apr 29](https://github.com/denoland/deno/issues/23552#issuecomment-2082706583)
Hi @mmastrac @iMarv,
I checked the issue and ,
it was fixed by this PR
https://github.com/denoland/deno/pull/23590
so can u please review it?

@[yazan-nidal](https://github.com/yazan-nidal)
yazan-nidal commented [on May 2](https://github.com/denoland/deno/issues/23552#issuecomment-2090578479)
@iMarv @mmastrac

what the expected outcome?

@[iMarv](https://github.com/iMarv)
Author
iMarv commented [on May 4](https://github.com/denoland/deno/issues/23552#issuecomment-2094255945)
It should not panic I guess.

I am not a maintainer, but I would figure that it shall throw some error that wildcards are not allowed.

[yazan-nidal](https://github.com/yazan-nidal) added a commit to yazan-nidal/deno that referenced this issue [on May 6](https://github.com/denoland/deno/issues/23552#ref-commit-ea3cc59)
@yazan-nidal
[Implement improvements(v2) for error handling and dot handling in fqd…](https://github.com/yazan-nidal/deno/commit/ea3cc59c5598228483a7da52be4b87086a65ec5a) …
[ea3cc59](https://github.com/yazan-nidal/deno/commit/ea3cc59c5598228483a7da52be4b87086a65ec5a)
[yazan-nidal](https://github.com/yazan-nidal) added a commit to yazan-nidal/deno that referenced this issue [on May 7](https://github.com/denoland/deno/issues/23552#ref-commit-589d407)
@yazan-nidal
[add failed parse domain tests](https://github.com/yazan-nidal/deno/commit/589d407e7c875db08ea158b0b69faba65473516d) …
[589d407](https://github.com/yazan-nidal/deno/commit/589d407e7c875db08ea158b0b69faba65473516d)
@[dsherret](https://github.com/dsherret) dsherret mentioned this issue [on May 23](https://github.com/denoland/deno/issues/23552#ref-issue-2313012145)
https://github.com/denoland/deno/issues/23963
Closed
@[yazan-abdalrahman](https://github.com/yazan-abdalrahman) yazan-abdalrahman mentioned this issue [on Jun 2](https://github.com/denoland/deno/issues/23552#ref-pullrequest-2329641343)
https://github.com/denoland/deno/pull/24080
 Closed
[littledivy](https://github.com/littledivy) added a commit to littledivy/deno that referenced this issue [on Jun 26](https://github.com/denoland/deno/issues/23552#ref-commit-f03b3e2)
@littledivy
[fix(runtime): fix panic on invalid fqdn](https://github.com/littledivy/deno/commit/f03b3e2e0294720446dc8ed6cf666242686cc8b1) …
[f03b3e2](https://github.com/littledivy/deno/commit/f03b3e2e0294720446dc8ed6cf666242686cc8b1)
@[yazan-abdalrahman](https://github.com/yazan-abdalrahman) yazan-abdalrahman mentioned this issue [on Jun 27](https://github.com/denoland/deno/issues/23552#ref-issue-2376557753)
https://github.com/denoland/deno/issues/24354
Closed
@lucacasonato
Member
[lucacasonato](https://github.com/lucacasonato) commented [on Jul 6](https://github.com/denoland/deno/issues/23552#issuecomment-2211486659)
This now does not panic anymore

@[lucacasonato](https://github.com/lucacasonato) lucacasonato closed this as [not planned](https://github.com/denoland/deno/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22) [on Jul 6](https://github.com/denoland/deno/issues/23552#event-13409892260)
@[joscha](https://github.com/joscha)
joscha commented [on Jul 29](https://github.com/denoland/deno/issues/23552#issuecomment-2256336420)
I can still see this panicking

Task test:single deno test --allow-env=API_KEY,NODE_EXTRA_CA_CERTS '--allow-net=api.affinity.co,*.amazonaws.com:443' --doc --allow-read=./src/v1/tests/ "src/v1/tests/entity_files_test.ts"

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.45.2
Args: ["/nix/store/xiz264k79b2419vp0b82v15k552whcgp-deno-1.45.2/bin/deno", "test", "--allow-env=API_KEY,NODE_EXTRA_CA_CERTS", "--allow-net=api.affinity.co,*.amazonaws.com:443", "--doc", "--allow-read=./src/v1/tests/", "src/v1/tests/entity_files_test.ts"]

thread 'main' panicked at cli/args/flags.rs:4628:60:
called `Result::unwrap()` on an `Err` value: ErrorInner { kind: InvalidValue, context: FlatMap { keys: [], values: [] }, message: Some(Raw("invalid host: '*.amazonaws.com'\n\nCaused by:\n    invalid char found in FQDN")), source: None, help_flag: None, styles: Styles { header: Style { fg: None, bg: None, underline: None, effects: Effects() }, error: Style { fg: None, bg: None, underline: None, effects: Effects() }, usage: Style { fg: None, bg: None, underline: None, effects: Effects() }, literal: Style { fg: None, bg: None, underline: None, effects: Effects() }, placeholder: Style { fg: None, bg: None, underline: None, effects: Effects() }, valid: Style { fg: None, bg: None, underline: None, effects: Effects() }, invalid: Style { fg: None, bg: None, underline: None, effects: Effects() } }, color_when: Never, color_help_when: Never, backtrace: None }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
I can't see this issue mentioned on https://github.com/denoland/deno/releases anywhere, so I am not sure if it's fixed somewhere upstream from 1.45.2?

@[joscha](https://github.com/joscha)
joscha commented [on Jul 29](https://github.com/denoland/deno/issues/23552#issuecomment-2256342980)
https://github.com/denoland/deno/pull/24397 is closed against 1.45.0 which means in 1.45.2 (see above) it shouldn't panic anymore?

@[bartlomieju](https://github.com/bartlomieju) bartlomieju reopened this [on Jul 29](https://github.com/denoland/deno/issues/23552#event-13683735486)
@bartlomieju
Member
[bartlomieju](https://github.com/bartlomieju) commented [on Jul 29](https://github.com/denoland/deno/issues/23552#issuecomment-2256455360)
I can confirm that it still panics on latest Deno

@yazan-abdalrahman
Contributor
[yazan-abdalrahman](https://github.com/yazan-abdalrahman) commented [on Aug 14](https://github.com/denoland/deno/issues/23552#issuecomment-2288185334)
I can confirm that it still panics on latest Deno
@bartlomieju

image

I will work on it, okay?

@[yazan-abdalrahman](https://github.com/yazan-abdalrahman) yazan-abdalrahman mentioned this issue [on Aug 14](https://github.com/denoland/deno/issues/23552#ref-pullrequest-2466099298)
https://github.com/denoland/deno/pull/25044

**Comment by yazan-abdalrahman** [comment]
It was fixed in the last release,

```
PS D:\yad\deno> .\target\debug\deno run  --allow-net=www.google.*om .\main.js
error: invalid host: 'www.google.*om'

Caused by:
    invalid char found in FQDN
PS D:\yad\deno> .\target\debug\deno -v                                       
deno 2.0.1
PS D:\yad\deno> 
```

**Comment by bartlomieju** [comment]
No longer panics on current `main`. `--allow-net='*.amazonaws.com'` works without any `InvalidLabelChar` error.
