### ISSUE TITLE
node:fs/promises watcher polyfill is not AsyncIterable

### ISSUE THREAD

**Issue by jldec** [denoland/deno#23562]
Version: Deno 1.42.4

The deno polyfill for `node fsPromises.watch()` does not appear to return an `AsyncIterator` [as documented](https://nodejs.org/docs/v20.12.1/api/fs.html#fspromiseswatchfilename-options) here for node.

Using the returned watcher with `for await` throws `TypeError: watcher is not async iterable`.

```
$ deno run fswatch-node.js
✅ Granted read access to <CWD>.
Watching for file changes in /Users/jldec/opral/deno, press Ctrl+C to exit.
error: Uncaught (in promise) TypeError: watcher is not async iterable
  for await (const event of watcher) {
                            ^
    at run (file:///Users/jldec/opral/deno/fswatch-node.js:8:29)
    at file:///Users/jldec/opral/deno/fswatch-node.js:13:1
```

## repro

**fswatch-node.js** from: https://github.com/jldec/deno-node-fs-promises-watch
```js
import process from "node:process"
import fs from "node:fs/promises"

async function run() {
  const watcher = fs.watch(process.cwd(), { recursive: true })
  console.log(`Watching for file changes in ${process.cwd()}, press Ctrl+C to exit.`);

  for await (const event of watcher) {
    console.log(">>>> event", event)
  }
}

run()
```

**Comment by aguilera51284** [comment]
Is this issue still unreviewed? :(

**Comment by BlackAsLight** [comment]
Looking at the code in question it seems it would need to call .ref() on that return line https://github.com/denoland/deno/blob/main/ext/node/polyfills/_fs/_fs_watch.ts#L155, but it would be returning an async iterator for a Deno.FsEvent instead of a node one which has different property names.

**Comment by sntran** [comment]
I have also encountered this, and it seems that the `watch` in question was [promisified](https://github.com/denoland/deno/blob/700cd200c18d4a54f98c3633b898236038e8e550/ext/node/polyfills/_fs/_fs_watch.ts#L158) instead of being an `AsyncIterator` like `node:fs/promises`.

`await watch(path)` does not fulfill the promise.
