### ISSUE TITLE
Port listeners not closing properly

### ISSUE THREAD

**Issue by zekth** [denoland/deno#2358]
Here is the explanation of a problem i've spottend in this PR: https://github.com/denoland/deno/pull/2269

`listenner.close();` does not wait the real drop of the `tokio tcplistenner`. So there is a bit of time when the port will be free. It also may be due to `TIME_WAIT` or `CLOSE_WAIT` tcp flag: http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html

https://github.com/denoland/deno/blob/master/cli/resources.rs#L176

I have found some answers but i don't know if it's revelant for our case:
https://stackoverflow.com/questions/48334079/is-it-possible-to-close-a-tcplistener-in-tokio

**example:**
```ts
async function main() {
  const listener1 = Deno.listen("tcp", ":4500");
  listener1.accept().then(
    async (conn): Promise<void> => {
      await conn.write(new Uint8Array([1, 2, 3]));
      conn.close();
    }
  );
  const conn = await Deno.dial("tcp", "127.0.0.1:4500");

  const buf = new Uint8Array(1024);
  const readResult = await conn.read(buf);
  listener1.close();
  conn.close();
  const listener2 = Deno.listen("tcp", ":4500");
  listener2.close();
}
main();
```

output:
```
Uncaught AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at maybeThrowError (js/errors.ts:39:15)
    at sendSync (js/dispatch.ts:114:5)
    at listen (js/net.ts:152:19)
    at main (file:///C:/Users/vlegoff/Desktop/deno Demo/foo.ts:15:26)
```

**Comment by kitsonk** [comment]
Not sure if this is still a problem or not.

**Comment by zekth** [comment]
Closing as there is no activity for 1 year

**Comment by satyarohith** [comment]
This issue no longer exists with `1.9.0`.

Tested with a script updated to match the new APIs.
```ts
async function main() {
  const listener1 = Deno.listen({ port: 4500 });
  listener1.accept().then(
    async (conn): Promise<void> => {
      await conn.write(new TextEncoder().encode("Hello world"));
      conn.close();
    },
  );
  const conn = await Deno.connect({ hostname: "127.0.0.1", port: 4500 });
  const buf = new Uint8Array(1024);
  await conn.read(buf);
  console.log(new TextDecoder().decode(buf));
  listener1.close();
  conn.close();

  const listener2 = Deno.listen({ port: 4500 });
  listener2.accept().then(
    async (conn): Promise<void> => {
      await conn.write(new TextEncoder().encode("Hello Wakanda"));
      conn.close();
    },
  );
  const conn2 = await Deno.connect({ hostname: "127.0.0.1", port: 4500 });
  const buf2 = new Uint8Array(1024);
  await conn2.read(buf2);
  console.log(new TextDecoder().decode(buf2));
  listener2.close();
  conn2.close();
}
main();
```
