### ISSUE TITLE
LSP Errors in main

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#23643]
Version: Deno 1.43.1 (ee122c5af6b8251329c213b4042a6d71ff5d9b71)

I pulled main and noted that I am getting a lot of unexpected errors in the Deno Language Server log:

```
Error during TS request "getOutliningSpans":
  [object Object]
Error during TS request "getDocumentHighlights":
  [object Object]
Error during TS request "getDocumentHighlights":
  [object Object]
```

Feels like there is some issue with object coercion when commenting to the TypeScript language server.  I don't know when it was introduced.

**Comment by bartlomieju** [comment]
Hey Kit, is there a repro we can try? Is it by any chance happening in `oak` repo?

**Comment by kitsonk** [comment]
I am getting on vscode with:

- https://github.com/kitsonk/kv-toolbox
- https://github.com/oakserver/oak
- https://github.com/kitsonk/google-datastore

Pretty much any repo where the Deno Language Server is active and on switching tabs or opening a new document. I have closed and re-opened multiple times and the error persists.  It doesn't appear to be quite the same consistently on every file, but it happens quite frequently.  I have seen many different commands into tsc failing, but it always appears to be only one per document.

**Comment by bartlomieju** [comment]
Thanks. This should be now fixed in canary, let us know if the problem persists.

**Comment by kitsonk** [comment]
That fixed the first problem, but now I tend so see a lot of these:

```
Error during TS request "getCodeFixesAtPosition":
  Error: Debug Failure. 7010
    at doChange33 (ext:deno_tsc/00_typescript.js:155332:22)
    at ext:deno_tsc/00_typescript.js:156195:27
    at Function.with (ext:deno_tsc/00_typescript.js:170707:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:156194:68)
    at ext:deno_tsc/00_typescript.js:147417:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:147417:12)
    at ext:deno_tsc/00_typescript.js:145014:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:145012:14)
Error getting actions from TypeScript: The response was not received for the request.
ERROR TSLS = Error: Debug Failure. 7005
    at doChange33 (ext:deno_tsc/00_typescript.js:155332:22)
    at ext:deno_tsc/00_typescript.js:156195:27
    at Function.with (ext:deno_tsc/00_typescript.js:170707:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:156194:68)
    at ext:deno_tsc/00_typescript.js:147417:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:147417:12)
    at ext:deno_tsc/00_typescript.js:145014:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:145012:14)
Error during TS request "getCodeFixesAtPosition":
  Error: Debug Failure. 7005
    at doChange33 (ext:deno_tsc/00_typescript.js:155332:22)
    at ext:deno_tsc/00_typescript.js:156195:27
    at Function.with (ext:deno_tsc/00_typescript.js:170707:11)
    at Object.getCodeActions (ext:deno_tsc/00_typescript.js:156194:68)
    at ext:deno_tsc/00_typescript.js:147417:48
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getFixes (ext:deno_tsc/00_typescript.js:147417:12)
    at ext:deno_tsc/00_typescript.js:145014:35
    at flatMap (ext:deno_tsc/00_typescript.js:303:19)
    at Object.getCodeFixesAtPosition (ext:deno_tsc/00_typescript.js:145012:14)
Error getting actions from TypeScript: The response was not received for the request.
```

I don't notice anything awry, but it does seem that there is some sort of underlying noise that was previously being swallowed.
