### ISSUE TITLE
Test fails in v1.43

### ISSUE THREAD

**Issue by ker0olos** [denoland/deno#23665]
the following test passes in `v1.42.0` but fails in `v1.43.1`

```ts
import {
  afterEach,
  beforeEach,
  describe,
  it,
} from 'https://deno.land/std@0.224.0/testing/bdd.ts';
import { MongoMemoryServer } from 'npm:mongodb-memory-server-core';
import { MongoClient, ObjectId } from 'npm:mongodb';
import { assert } from 'https://deno.land/std@0.224.0/assert/assert.ts';

let mongod: MongoMemoryServer;
let client: MongoClient;

describe({
  name: 'deno',
  fn: () => {
    beforeEach(async () => {
      mongod = await MongoMemoryServer.create();
      client = new MongoClient(mongod.getUri());
      await client.connect();
    });

    afterEach(async () => {
      await client.close();
      await mongod.stop();
    });

    it('test', async () => {
      const _id = new ObjectId();

      const { insertedId } = await client.db().collection('test').insertOne({
        _id,
      });

      assert(insertedId.equals(_id));
    });
  },
});


```

```
error: Error: connect ECONNREFUSED 127.0.0.1:59453 - Local (undefined:undefined)
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:62:9)
    at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:148:10)
    at TCPConnectWrap._afterConnect [as oncomplete] (node:net:130:16)
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./db/deno.test.ts (uncaught error)

FAILED | 0 passed | 2 failed (608ms)

error: Test failed
```

**Comment by ker0olos** [comment]
Still failing in `v1.43.2`
