### ISSUE TITLE
Deno has panicked: thread 'main' panicked at .. lib.rs:696:19

### ISSUE THREAD

**Issue by tenkoverse** [denoland/deno#23753]
I tried creating a simple deno project to see if temporal was compatible yet and ran into an immediate error. 

### How to reproduce

1. You need to download and run [temporal dev server ](https://github.com/temporalio/cli) with ```temporal server start-dev```

2. You need to setup a basic project with the following ```package.json```

```
{
    "name": "@deno/my-example-project",
    "description": "An example app created with Deno",
    "type": "module",
    "dependencies": {
        "@temporalio/client": "^1.9.3",
        "@temporalio/workflow": "^1.9.3"
    }
}
```

3. Create an ```index.ts``` file with the following code
```typescript
// index.ts
import { Connection } from '@temporalio/client';

async function run() {
  const connection = await Connection.connect({ address: 'localhost:7233' });
}

run()
```

4. Run the deno script with ```RUST_BACKTRACE=full deno run index.ts``` and get the following error.

```
✅ Granted all env access.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.43.1
Args: ["deno", "run", "index.ts"]

thread 'main' panicked at /private/tmp/deno-20240502-7308-5t0ks3/deno/runtime/permissions/lib.rs:696:19:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
stack backtrace:
   0:        0x10a8a2f96 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h39dedd9998475f7a
   1:        0x109717733 - core::fmt::write::h996a70950ef02a8b
   2:        0x10a8a54a8 - std::io::Write::write_fmt::hd6709b73e8721808
   3:        0x10a8a2d89 - std::sys_common::backtrace::print::h0c71c33392329482
   4:        0x10a88a119 - std::panicking::default_hook::{{closure}}::h7c2dc6602e4afdfe
   5:        0x10a889e6f - std::panicking::default_hook::hb8432d7d4b595a9c
   6:        0x1095da68a - deno::setup_panic_hook::{{closure}}::h3f9769bf6d337e73
   7:        0x10a88a7f8 - std::panicking::rust_panic_with_hook::h55cf7f98a5172bf4
   8:        0x10a8a32f4 - std::panicking::begin_panic_handler::{{closure}}::hfb4dd0b5a9ef6466
   9:        0x10a8a3249 - std::sys_common::backtrace::__rust_end_short_backtrace::hcbbcf4c6d355f082
  10:        0x10a88a3f6 - _rust_begin_unwind
  11:        0x10c08f325 - core::panicking::panic_fmt::ha2d9edabf12b6300
  12:        0x10c08f7e5 - core::result::unwrap_failed::hfcb5ffb2b31a1c75
  13:        0x10a028ddf - deno_permissions::NetDescriptor::new::haccae388f134fc6c
  14:        0x10a239aa6 - deno_net::ops::op_dns_resolve::op_dns_resolve<NP>::call::{{closure}}::h8de8a8872c51ed8f
  15:        0x10a235485 - deno_net::ops::op_dns_resolve::op_dns_resolve<NP>::v8_fn_ptr::h63b0228cb8da46d3
```

```
deno 1.43.1 (release, x86_64-apple-darwin)
v8 12.4.254.12
typescript 5.4.3
```

Possible related issues: https://github.com/denoland/deno/issues/23294 https://github.com/denoland/deno/issues/23292

**Comment by bartlomieju** [comment]
@tenkoverse can you still reproduce this problem on latest (v2.5) Deno? I really can't
