### ISSUE TITLE
thread '<unnamed>' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_v8-0.181.0/de.rs:628:53

### ISSUE THREAD

**Issue by ayoreis** [denoland/deno#23779]
Only panics when running `deno` or `deno repl`, not with `deno run`.

- Deno 1.43.2 (1.43.3 is not in the ArchLinux registry yet)
- ArchLinux (up-to-date)

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.42.2
Args: ["deno"]

thread '<unnamed>' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_v8-0.181.0/de.rs:628:53:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x56fd34ba3a84 - <unknown>
   1:     0x56fd33aa99c3 - <unknown>
   2:     0x56fd34b6beae - <unknown>
   3:     0x56fd34ba6e5a - <unknown>
   4:     0x56fd34ba6749 - <unknown>
   5:     0x56fd34ba632f - <unknown>
   6:     0x56fd33970a77 - <unknown>
   7:     0x56fd34ba740d - <unknown>
   8:     0x56fd34ba716c - <unknown>
   9:     0x56fd34ba70f9 - <unknown>
  10:     0x56fd34ba70e6 - <unknown>
  11:     0x56fd333a97b5 - <unknown>
  12:     0x56fd333a988e - <unknown>
  13:     0x56fd333a9be8 - <unknown>
  14:     0x56fd33b9f536 - <unknown>
  15:     0x56fd335a4a7f - <unknown>
  16:     0x56fd335a46e0 - <unknown>
  17:     0x56fd336e4cb3 - <unknown>
  18:     0x56fd357f25e4 - <unknown>
```

**Comment by ayoreis** [comment]
Fixed in 1.43.2.
