### ISSUE TITLE
Run SvelteKit dev server without DENO_FUTURE=1

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#23843]
Things are much better after #17248 - I just want to point out that when running i.e.:

```sh
deno run -A npm:create-svelte@latest my-sveltekit-app (demo app, typescript, svelte 5 preview)
deno task dev
```

Then going to the localhost address will error with a :

```sh
11:34:45 AM [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "/src/routes/Counter.svelte"
|- ReferenceError: requestAnimationFrame is not defined
    at eval (/Users/admin/repos/deno-kitchensink/my-sveltekit-app/node_modules/.deno/svelte@5.0.0-next.128/node_modules/svelte/src/internal/client/timing.js, <anonymous>:8:45)
    at async instantiateModule (file:///Users/admin/repos/deno-kitchensink/my-sveltekit-app/node_modules/.deno/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:55058:9)

ReferenceError: requestAnimationFrame is not defined
    at eval (/Users/admin/repos/deno-kitchensink/my-sveltekit-app/node_modules/.deno/svelte@5.0.0-next.128/node_modules/svelte/src/internal/client/timing.js, <anonymous>:8:45)
    at async instantiateModule (file:///Users/admin/repos/deno-kitchensink/my-sveltekit-app/node_modules/.deno/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:55058:9) {
  stack: "ReferenceError: requestAnimationFrame is not defined\n" +
    "    at eval (/Users/admin/repos/deno-kitchensin"... 311 more characters
}
```

But it works if instead using the byonm:

```sh
pnpm i
DENO_FUTURE=1 deno task dev
```

**Comment by littledivy** [comment]
DENO_FUTURE=1 removes the `window` global. SvelteKit assumes its running in a browser with it.

For framework compatibility, we are focusing on making it work with `DENO_FUTURE` only (going to be default in Deno 2)

**Comment by algoflows** [comment]
Is there anyway to deploy this to deno deploy?
