### ISSUE TITLE
Invalid cron schedule

### ISSUE THREAD

**Issue by Lorenzo0111** [denoland/deno#23848]
Version: Deno 1.43.3

When I run the following code with `deno run --unstable-cron test.ts` I get an exception but the cron expression is correct.
Error:
```ts
error: Uncaught (in promise) TypeError: Invalid cron schedule
Deno.cron("Example cron", "0 * 7-12 * * *", () => {
     ^
    at Object.cron (ext:deno_cron/01_cron.ts:75:15)
    at file:///home/lorenzo/projects/supplenze-bot/test.ts:1:6
```

Code:
```ts
Deno.cron("Example cron", "0 * 7-12 * * *", () => {
  console.log("Hello world");
});

```

**Comment by Lorenzo0111** [comment]
Found that the expression was wrong
