### ISSUE TITLE
Bug: Express errors when sending big file

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23912]
## Steps to reproduce

1. Create a new directory and `cd` into it
2. Run `npm init -y && npm i express && deno init`
3. Create file `server.mjs` with these contents:
  ```ts
  import express from "express";
  
  const app = express();
  
  app.get("/", (_req, res) => {
    res.sendFile("home.html", {
      root: import.meta.dirname,
    });
  });

  const port = 3000;
  app.listen(port, () => {
    console.log(`Server listening on port ${port}`);
  });
  ```
4. Create file `home.html` with the contents from here (too big to put as inline snippet) https://gist.github.com/marvinhagemeister/2b1cde3a3527637d12332550ab65eae4 . Alternative any other big (>3MB) html file should work
5. Run `deno run -A server.mjs`
6. Run `wrk -d 10 --latency http://localhost:3000/`

## Error
```sh
error: Uncaught (in promise) TypeError: The stream controller cannot close or enqueue.
    at ReadableStreamDefaultController.enqueue (ext:deno_web/06_streams.js:6057:13)
    at Function.#enqueue (node:http:917:18)
    at ServerResponse.write [as _write] (node:http:949:32)
    at writeOrBuffer (ext:deno_node/_stream.mjs:3947:16)
    at _write (ext:deno_node/_stream.mjs:3892:14)
    at ServerResponse.Writable.write (ext:deno_node/_stream.mjs:3895:14)
    at ReadStream.ondata (ext:deno_node/_stream.mjs:3179:26)
    at ReadStream.emit (ext:deno_node/_stream.mjs:1851:9)
    at addChunk (ext:deno_node/_stream.mjs:2873:16)
    at readableAddChunk (ext:deno_node/_stream.mjs:2852:13)
```

Version: Deno 1.43.5

**Comment by marvinhagemeister** [comment]
I can still reproduce it with 1.44.4 or with git from today (2024-06-05)

**Comment by bartlomieju** [comment]
Appears to be fixed now that https://github.com/denoland/deno/pull/33208 is landed
