### ISSUE TITLE
Next 15 dev mode error with turbopack

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#23942]
Running with `--unstable-unsafe-proto`:

```
divy@divy test-app-15]$ DENO_FUTURE=1 deno task dev
Task dev next dev --turbo
  ▲ Next.js 14.3.0-canary.73 (turbo)
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1832ms
 ○ Compiling / ...
(node:149677) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:149684) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
 ✓ Compiled / in 1478ms
 ⨯ Error: Invariant: Missing ActionQueueContext
    at useReducerWithReduxDevtoolsImpl (/home/divy/gh/test-app-15/.next/server/chunks/ssr/node_modules_fad749._.js:4438:15)
    at Router (/home/divy/gh/test-app-15/.next/server/chunks/ssr/node_modules_fad749._.js:14548:273)
    at cb (ext:deno_node/internal/timers.mjs:64:31)
    at eventLoopTick (ext:core/01_core.js:203:13)
digest: "4219805756"
Error: Invariant: Missing ActionQueueContext
    at useReducerWithReduxDevtoolsImpl (file:///home/divy/gh/test-app-15/.next/server/chunks/ssr/node_modules_fad749._.js:4438:15)
    at Router (file:///home/divy/gh/test-app-15/.next/server/chunks/ssr/node_modules_fad749._.js:14548:273)
    at o8 (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10724)
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:20994
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21722)
    at ai (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55125)
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:20594)
    at ai (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55125)
    at an (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11210)
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21685
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21722)
    at ai (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55125)
    at an (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11210)
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21685
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21722)
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:51821)
    at ai (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55125)
    at an (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11210)
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21685
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21722)
    at ai (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55125)
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64092
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64821
    at ag (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64829)
    at Timeout._onTimeout (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6918)
    at cb (ext:deno_node/internal/timers.mjs:64:31)
    at eventLoopTick (ext:core/01_core.js:203:13)
```

**Comment by bartlomieju** [comment]
Do it work if you run with `--unstable-unsafe-proto`?

**Comment by littledivy** [comment]
Yes, that fixes the original error. Now I get another one:

```
divy@divy test-app-15]$ deno task dev
Task dev next dev --turbo
  ▲ Next.js 14.3.0-canary.73 (turbo)
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1832ms
 ○ Compiling / ...
(node:149677) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:149684) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
 ✓ Compiled / in 1478ms
 ⨯ Error: Invariant: Missing ActionQueueContext
    at useReducerWithReduxDevtoolsImpl (/home/divy/gh/test-app-15/.next/server/chunks/ssr/node_modules_fad749._.js:4438:15)
    at Router (/home/divy/gh/test-app-15/.next/server/chunks/ssr/node_modules_fad749._.js:14548:273)
    at cb (ext:deno_node/internal/timers.mjs:64:31)
    at eventLoopTick (ext:core/01_core.js:203:13)
digest: "4219805756"
Error: Invariant: Missing ActionQueueContext
    at useReducerWithReduxDevtoolsImpl (file:///home/divy/gh/test-app-15/.next/server/chunks/ssr/node_modules_fad749._.js:4438:15)
    at Router (file:///home/divy/gh/test-app-15/.next/server/chunks/ssr/node_modules_fad749._.js:14548:273)
    at o8 (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10724)
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:20994
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21722)
    at ai (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55125)
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:20594)
    at ai (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55125)
    at an (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11210)
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21685
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21722)
    at ai (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55125)
    at an (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11210)
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21685
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21722)
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:51821)
    at ai (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55125)
    at an (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11210)
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21685
    at ao (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:21722)
    at ai (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55125)
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64092
    at file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64821
    at ag (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:64829)
    at Timeout._onTimeout (file:///home/divy/gh/test-app-15/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6918)
    at cb (ext:deno_node/internal/timers.mjs:64:31)
    at eventLoopTick (ext:core/01_core.js:203:13)
```

**Comment by littledivy** [comment]
Oh never mind, it works! (I wasn't using DENO_FUTURE=1 which removes window global)


![image](https://github.com/denoland/deno/assets/34997667/2fcba659-7014-43dc-8445-ee7e431fd02f)
