### ISSUE TITLE
Got UnexpectedEof when reading from a TlsConn

### ISSUE THREAD

**Issue by 1yefuwang1** [denoland/deno#23960]
Version: deno 1.43.6 (release, x86_64-unknown-linux-gnu)
The following code throws UnexpectedEof consistently after all html was printed to stdout.
```js
import { writeAll } from "jsr:@std/io";

const conn = await Deno.connectTls({ hostname: "www.google.com", port: 443 });
await writeAll(conn, new TextEncoder().encode("GET / HTTP/1.0\r\n\r\n"));
await conn.readable.pipeTo(Deno.stdout.writable);
```
The callstack is:
```
error: Uncaught (in promise) UnexpectedEof: unexpected end of file
    at Object.pull (ext:deno_web/06_streams.js:996:30)
    at Module.invokeCallbackFunction (ext:deno_webidl/00_webidl.js:946:16)
    at ReadableByteStreamController.pullAlgorithm (ext:deno_web/06_streams.js:3563:14)
    at readableByteStreamControllerCallPullIfNeeded (ext:deno_web/06_streams.js:1242:49)
    at ReadableByteStreamController.[[[PullSteps]]] (ext:deno_web/06_streams.js:5983:5)
    at readableStreamDefaultReaderRead (ext:deno_web/06_streams.js:2513:36)
    at ext:deno_web/06_streams.js:2742:9
    at new Promise (<anonymous>)
    at ext:deno_web/06_streams.js:2741:14
    at eventLoopTick (ext:core/01_core.js:168:7)
```

The problem doesn't exist when working with normal Tcp socket.
The following code works fine.
```js
import { writeAll } from "jsr:@std/io";

const conn = await Deno.connect({ hostname: "www.google.com", port: 80 });
await writeAll(conn, new TextEncoder().encode("GET / HTTP/1.0\r\n\r\n"));
await conn.readable.pipeTo(Deno.stdout.writable);
```

**Comment by 1yefuwang1** [comment]
Instead of using `pipeTo` API, I decide to go with reader API with the following code but still encounter the UnexpectedEof after all html was printed.

```js
import { writeAll } from "jsr:@std/io";

const conn = await Deno.connectTls({ hostname: "www.google.com", port: 443 });
await writeAll(conn, new TextEncoder().encode("GET / HTTP/1.0\r\n\r\n"));
// await conn.readable.pipeTo(Deno.stdout.writable);

const reader = conn.readable.getReader(/*{ mode: "byob" }*/);

while (true) {
  const {done, value} = await reader.read();
  if (done) {
    if (value) {
      await writeAll(Deno.stdout, value);
    }
    console.log(`done`);
    break;
  }
  await writeAll(Deno.stdout, value);
}
```

Callstack:
```
error: Uncaught (in promise) UnexpectedEof: unexpected end of file
  const {done, value} = await reader.read();
                                     ^
    at Object.pull (ext:deno_web/06_streams.js:996:30)
    at Module.invokeCallbackFunction (ext:deno_webidl/00_webidl.js:946:16)
    at ReadableByteStreamController.pullAlgorithm (ext:deno_web/06_streams.js:3563:14)
    at readableByteStreamControllerCallPullIfNeeded (ext:deno_web/06_streams.js:1242:49)
    at ReadableByteStreamController.[[[PullSteps]]] (ext:deno_web/06_streams.js:5983:5)
    at readableStreamDefaultReaderRead (ext:deno_web/06_streams.js:2513:36)
    at ReadableStreamDefaultReader.read (ext:deno_web/06_streams.js:5480:5)
    at file:///home/wyf/deno/main.ts:10:38
    at eventLoopTick (ext:core/01_core.js:168:7)
```

It seems `Eof` is not signaled by returning `done=true`.

**Comment by 1yefuwang1** [comment]
I can still reproduce it with 1.44.1. I'm using wsl btw.

**Comment by lucacasonato** [comment]
I can reproduce - this indeed looks like a bug,

**Comment by 1yefuwang1** [comment]
Unfortunately, this issue still exists in deno 2:
```
deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2
```

```
error: Uncaught (in promise) UnexpectedEof: peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof
    at Object.pull (ext:deno_web/06_streams.js:988:30)
    at Module.invokeCallbackFunction (ext:deno_webidl/00_webidl.js:982:16)
    at ReadableByteStreamController.pullAlgorithm (ext:deno_web/06_streams.js:3559:14)
    at readableByteStreamControllerCallPullIfNeeded (ext:deno_web/06_streams.js:1234:49)
    at ReadableByteStreamController.[[[PullSteps]]] (ext:deno_web/06_streams.js:5987:5)
    at readableStreamDefaultReaderRead (ext:deno_web/06_streams.js:2509:36)
    at ext:deno_web/06_streams.js:2738:9
    at new Promise (<anonymous>)
    at ext:deno_web/06_streams.js:2737:14
    at eventLoopTick (ext:core/01_core.js:175:7)
```

**Comment by sawrubgupta** [comment]
I am also facing it. Any solution

**Comment by lenovouser** [comment]
I am also experiencing this regularly and have switched projects away from Deno due to this

**Comment by uriva** [comment]
same here
