### ISSUE TITLE
npm import fails for `@googlemaps/google-maps-services-js`

### ISSUE THREAD

**Issue by uriva** [denoland/deno#23978]
deno 1.43.6 (release, x86_64-unknown-linux-gnu)
v8 12.4.254.13
typescript 5.4.5

in deno repl:
```
> import x from "npm:@googlemaps/google-maps-services-js@3.4.0";
Uncaught Error: Cannot find module 'core-js/modules/es.string.replace.js'
Require stack:
- /home/uri/.cache/deno/npm/registry.npmjs.org/@googlemaps/url-signature/1.0.34/dist/index.umd.js
- /home/uri/.cache/deno/npm/registry.npmjs.org/@googlemaps/google-maps-services-js/3.4.0/dist/serialize.js
- /home/uri/.cache/deno/npm/registry.npmjs.org/@googlemaps/google-maps-services-js/3.4.0/dist/directions.js
- /home/uri/.cache/deno/npm/registry.npmjs.org/@googlemaps/google-maps-services-js/3.4.0/dist/client.js
- /home/uri/.cache/deno/npm/registry.npmjs.org/@googlemaps/google-maps-services-js/3.4.0/dist/geolocate.js
- /home/uri/.cache/deno/npm/registry.npmjs.org/@googlemaps/google-maps-services-js/3.4.0/dist/index.js
- /home/uri/.cache/deno/npm/registry.npmjs.org/@googlemaps/google-maps-services-js/3.4.0/dist/index.js
    at Function.Module._resolveFilename (node:module:564:15)
    at Function.Module._load (node:module:451:27)
    at Module.require (node:module:609:19)
    at require (node:module:715:16)
    at file:///home/uri/.cache/deno/npm/registry.npmjs.org/@googlemaps/url-signature/1.0.34/dist/index.umd.js:1:333
    at Object.<anonymous> (file:///home/uri/.cache/deno/npm/registry.npmjs.org/@googlemaps/url-signature/1.0.34/dist/index.umd.js:1:1061)
    at Object.<anonymous> (file:///home/uri/.cache/deno/npm/registry.npmjs.org/@googlemaps/url-signature/1.0.34/dist/index.umd.js:3:4)
    at Module._compile (node:module:659:34)
    at Object.Module._extensions..js (node:module:673:10)
    at Module.load (node:module:597:32)
```

**Comment by dsherret** [comment]
I get the same error in Node.js:

```
> cat index.js
const data = require("@googlemaps/google-maps-services-js");
> node index.js
node:internal/modules/cjs/loader:1152
  throw err;
  ^

Error: Cannot find module 'core-js/modules/es.string.replace.js'
Require stack:
- V:\scratch\node_modules\@googlemaps\url-signature\dist\index.umd.js
- V:\scratch\node_modules\@googlemaps\google-maps-services-js\dist\serialize.js
- V:\scratch\node_modules\@googlemaps\google-maps-services-js\dist\directions.js
- V:\scratch\node_modules\@googlemaps\google-maps-services-js\dist\client.js
- V:\scratch\node_modules\@googlemaps\google-maps-services-js\dist\geolocate.js
- V:\scratch\node_modules\@googlemaps\google-maps-services-js\dist\index.js
- V:\scratch\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at V:\scratch\node_modules\@googlemaps\url-signature\dist\index.umd.js:1:79
    at Object.<anonymous> (V:\scratch\node_modules\@googlemaps\url-signature\dist\index.umd.js:1:807)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'V:\\scratch\\node_modules\\@googlemaps\\url-signature\\dist\\index.umd.js',
    'V:\\scratch\\node_modules\\@googlemaps\\google-maps-services-js\\dist\\serialize.js',
    'V:\\scratch\\node_modules\\@googlemaps\\google-maps-services-js\\dist\\directions.js',
    'V:\\scratch\\node_modules\\@googlemaps\\google-maps-services-js\\dist\\client.js',
    'V:\\scratch\\node_modules\\@googlemaps\\google-maps-services-js\\dist\\geolocate.js',
    'V:\\scratch\\node_modules\\@googlemaps\\google-maps-services-js\\dist\\index.js',
    'V:\\scratch\\index.js'
  ]
}
```

**Comment by dsherret** [comment]
https://github.com/googlemaps/google-maps-services-js/issues/1194
