### ISSUE TITLE
Support Tanstack Start (tanstack.com)

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#24061]
Version: Deno 1.44.0

Repro:

Clone https://github.com/tanstack/tanstack.com
pnpm i   (using pnpm v 8.10.2) 
DENO_FUTURE=1 deno task dev

Error:

```sh
➜ DENO_FUTURE=1 deno task dev
Task dev vinxi dev
vinxi v0.3.11
vinxi starting dev server

 ERROR  Cannot read properties of undefined (reading 'env')                                                                                                                                      2:23:41 PM

  at Object.plugins (app.config.timestamp_1717158220687.js:14:32)
  at Object.plugins (node_modules/.pnpm/zod@3.22.4/node_modules/zod/lib/index.mjs:3193:40)
  at Object.plugins (node_modules/.pnpm/@tanstack+start@1.34.2_@opentelemetry+api@1.8.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3_vite@5.1.4/node_modules/@tanstack/start/dist/esm/config/index.js:152:59)
  at Object.plugins (node_modules/.pnpm/@tanstack+start@1.34.2_@opentelemetry+api@1.8.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3_vite@5.1.4/node_modules/@tanstack/start/dist/esm/config/index.js:211:45)
  at createViteHandler (node_modules/.pnpm/vinxi@0.3.11_@opentelemetry+api@1.8.0/node_modules/vinxi/lib/dev-server.js:58:31)
  at async Object.handler (node_modules/.pnpm/vinxi@0.3.11_@opentelemetry+api@1.8.0/node_modules/vinxi/lib/router-modes.js:147:27)
  at async Promise.all (index 1)
  at async createDevServer (node_modules/.pnpm/vinxi@0.3.11_@opentelemetry+api@1.8.0/node_modules/vinxi/lib/dev-server.js:155:5)
  at async Object.run (node_modules/.pnpm/vinxi@0.3.11_@opentelemetry+api@1.8.0/node_modules/vinxi/bin/cli.mjs:182:17)
  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16) 



 ERROR  Cannot read properties of undefined (reading 'env')    
```

Seems like it's breaking at:

`authToken: process.env.SENTRY_AUTH_TOKEN,`

But it works fine with `pnpm run dev`

**Comment by reeceorbuck** [comment]
I think I have a similar error- broke between 1.43.5 -> 1.43.6 and still failing in 1.44.0
importing from "npm:@azure/identity" will fail as cannot read properties of undefined (process.versions).

The debugger shows the process class is completely missing several properties: versions, env (your error), and several others.

**Comment by tesharp** [comment]
Same problem. Have to revert to 1.43.5 for azure/identity to work.

**Comment by bartlomieju** [comment]
@reeceorbuck @tesharp could you please share some reproduction code that causes the failure you're describing?

**Comment by reeceorbuck** [comment]
import { ClientSecretCredential } from "npm:@azure/identity";
const test = new ClientSecretCredential("a","b","c",);


A script with these two lines will throw.

**Comment by reeceorbuck** [comment]
> @reeceorbuck @tesharp could you please share some reproduction code that causes the failure you're describing?

Just responded with short piece of code that shows my issue. Sorry I'm totally unfamiliar with GitHub conventions

**Comment by bartlomieju** [comment]
Thanks, I can now reproduce the problem.

**Comment by birkskyum** [comment]
The error now is (deno 1.45.5+6522478):
```
 ERROR  process is not defined                                                                            
```

instead of the 

```
 ERROR  Cannot read properties of undefined (reading 'env')
```

**Comment by birkskyum** [comment]
Related to
- #24978

**Comment by birkskyum** [comment]
I'll focus on triaging this for Deno 2, which prompts this install error instead:
- #25648

**Comment by birkskyum** [comment]
`deno task run` show this on localhost:

<img width="173" alt="Screenshot 2024-09-24 at 11 38 55" src="https://github.com/user-attachments/assets/46f725c8-10f5-4e38-894f-c6d79cfd1b28">

**Comment by birkskyum** [comment]
I'm seeing now:

```sh
tanstack.com on  main via ⬢ v20.18.1 via 🅒 base took 3.8s 
➜ deno task dev
Task dev vinxi dev & pnpm dev:convex
vinxi v0.5.1

> tanstack.com@ dev:convex /Users/admin/repos/deno-kitchensink/tanstack.com
> convex dev --tail-logs

[sentry-vite-plugin] Warning: No auth token provided. Will not create release. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[sentry-vite-plugin] Warning: No auth token provided. Will not upload source maps. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
vinxi starting dev server
Welcome to developing with Convex, let's get you logged in.
? Device name: (Computer2) 
♻️  Generating routes...
✅ Processed routes in 464ms
[sentry-vite-plugin] Info: Sending telemetry data on issues and performance to Sentry. To disable telemetry, set `options.telemetry` to `false`.
[get-port] Unable to find an available port (tried 3000 on host "localhost"). Using alternative port 3001.

  ➜ Local:    http://localhost:3001/
  ➜ Network:  use --host to expose

ServerFn Request: /Users/admin/repos/deno-kitchensink/tanstack.com/app/components/ThemeToggle.tsx - $$function1

ServerFn Response: 200
 - Payload: {"result":"auto","context":{}}

ServerFn Request: /Users/admin/repos/deno-kitchensink/tanstack.com/app/server/sponsors.ts - $$function0

Warning: useRouter must be used inside a <RouterProvider> component!
Error in renderToPipeableStream: TypeError: Cannot read properties of null (reading '__store')
    at useRouterState (file:///Users/admin/repos/deno-kitchensink/tanstack.com/node_modules/.deno/@tanstack+react-router@1.87.9/node_modules/@tanstack/react-router/dist/esm/useRouterState.js:11:26)
    at useMatch (file:///Users/admin/repos/deno-kitchensink/tanstack.com/node_modules/.deno/@tanstack+react-router@1.87.9/node_modules/@tanstack/react-router/dist/esm/useMatch.js:9:26)
    at useLoaderData (file:///Users/admin/repos/deno-kitchensink/tanstack.com/node_modules/.deno/@tanstack+react-router@1.87.9/node_modules/@tanstack/react-router/dist/esm/useLoaderData.js:3:10)
    at RootRoute.Route.useLoaderData (file:///Users/admin/repos/deno-kitchensink/tanstack.com/node_modules/.deno/@tanstack+react-router@1.87.9/node_modules/@tanstack/react-router/dist/esm/route.js:146:14)
    at RootDocument (/Users/admin/repos/deno-kitchensink/tanstack.com/app/routes/__root.tsx, <anonymous>:138:33)
    at renderWithHooks (file:///Users/admin/repos/deno-kitchensink/tanstack.com/node_modules/.deno/react-dom@18.3.1/node_modules/react-dom/cjs/react-dom-server.node.development.js:5724:16)
    at renderIndeterminateComponent (file:///Users/admin/repos/deno-kitchensink/tanstack.com/node_modules/.deno/react-dom@18.3.1/node_modules/react-dom/cjs/react-dom-server.node.development.js:5798:15)
    at renderElement (file:///Users/admin/repos/deno-kitchensink/tanstack.com/node_modules/.deno/react-dom@18.3.1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6023:7)
    at renderNodeDestructiveImpl (file:///Users/admin/repos/deno-kitchensink/tanstack.com/node_modules/.deno/react-dom@18.3.1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (file:///Users/admin/repos/deno-kitchensink/tanstack.com/node_modules/.deno/react-dom@18.3.1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14) undefined
Missing github credentials, returning mock data.
Missing airtable credentials, returning mock data.
Missing airtable credentials, returning mock data.
Missing airtable credentials, returning mock data.
Missing github credentials, returning mock data.
ServerFn Response: 200
 - Payload: {"result":[],"context":{}}
 - ```

**Comment by birkskyum** [comment]
works with deno 2.2.0
