### ISSUE TITLE
thread 'worker-2' panicked at cli/npm/managed/resolution.rs:231:72: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#24063]
Version: Deno 1.44.0

After upgrading from Deno 1.43.3 to v1.44.0, I am experiencing this crash on startup of my application:

```
May 31 16:25:51 gleasonator deno[1399]: ============================================================
May 31 16:25:51 gleasonator deno[1399]: Deno has panicked. This is a bug in Deno. Please report this
May 31 16:25:51 gleasonator deno[1399]: at https://github.com/denoland/deno/issues/new.
May 31 16:25:51 gleasonator deno[1399]: If you can reliably reproduce this panic, include the
May 31 16:25:51 gleasonator deno[1399]: reproduction steps and re-run with the RUST_BACKTRACE=1 env
May 31 16:25:51 gleasonator deno[1399]: var set and include the backtrace in your report.
May 31 16:25:51 gleasonator deno[1399]: Platform: linux x86_64
May 31 16:25:51 gleasonator deno[1399]: Version: 1.44.0
May 31 16:25:51 gleasonator deno[1399]: Args: ["/usr/local/bin/deno", "run", "-A", "--unstable-ffi", "--cert", "/home/ditto/ca-certificate.crt", "--inspect", "src/server.ts"]
May 31 16:25:51 gleasonator deno[1399]: thread 'worker-2' panicked at cli/npm/managed/resolution.rs:231:72:
May 31 16:25:51 gleasonator deno[1399]: called `Option::unwrap()` on a `None` value
```

**Comment by bartlomieju** [comment]
Can you please provide reproduction code?

**Comment by alexgleason** [comment]
It's a giant codebase: https://gitlab.com/soapbox-pub/ditto

Oddly enough after adding `RUST_BACKTRACE=full` the server magically started working again. I wonder if it was in between states from old and new?

Now everything seems fine.

It passes CI as well: https://gitlab.com/soapbox-pub/ditto/-/merge_requests/338

However at least 2 people reported this problem to me separately after upgrading Deno. So, this is impacting users of my software.

I have a handful of web workers, some of which import from npm as the error seems to indicate: https://gitlab.com/soapbox-pub/ditto/-/tree/main/src/workers?ref_type=heads But I wasn't able to pinpoint which one was the problem, because it was crashing too soon to tell.

**Comment by alexgleason** [comment]
Never mind. It's happening again.

I suspect it might be related to this: https://gitlab.com/soapbox-pub/ditto/-/blob/main/src/workers/policy.worker.ts?ref_type=heads#L15 as mentioned in #23965 

```typescript
const Policy = (await import(path)).default;
this.policy = new Policy();
```

...which happens in a worker.

But I am still in the process of debugging it.

**Comment by alexgleason** [comment]
I reduced how often I was calling the dynamic import (I was hammering it), and now it does not crash in the middle of the server running.

But the server will still refuse to start with the same error randomly. When I start or restart the server.

**Comment by dsherret** [comment]
It's probably related to https://github.com/denoland/deno/pull/23634 -- I think one worker could clear the npm cache while another still needs it.

To mitigate the issue, I'd recommend removing `"lock": false,` from the lockfile. That will also improve your startup performance.

**Comment by dsherret** [comment]
Oh wait, sorry that won't mitigate the issue. Anyway, I'm looking into fixing this one.

**Comment by alexgleason** [comment]
Finally got a chance to test and wanted to confirm this is fixed in the latest version. Thank you @dsherret !!
