### ISSUE TITLE
Doc tests don't play nice with blockquotes

### ISSUE THREAD

**Issue by lishaduck** [denoland/deno#24164]
Version: Deno 1.44.1

Doc tests don't fail to parse if they're in a blockquote.

`deno fmt` agrees this is how it should be formatted, and it renders correctly in the vscode preview.

In a README.md:

````md
> ```ts
> import { foo } from "./baz"
> ```
````

`deno test  --doc` provides:

```console
error: The module's source code could not be parsed: Unexpected token `{`. Expected `.` or `(` at file:///Users/.../Developer/libs/README.md$1-4.ts:1:10

  > import { foo } from "./baz"
           ~
```

**Comment by MujahedSafaa** [comment]
Hi @dsherret, @nayeemrmn 

I've debugged the code and identified a potential issue in deno_graph, but I'm not entirely certain. Could you provide some insight on whether I'm on the right track or suggest other areas where the error might be?

**Comment by MujahedSafaa** [comment]
Hi @caspervonb @dsherret 
I did a workaround and found that when the content is extracted from the fenced blocks it extracted with the blockquotes which cause the parse error. 
![image](https://github.com/user-attachments/assets/b6c8ea2f-fc8c-4029-996e-be4d4e91c863)
![image](https://github.com/user-attachments/assets/db51332d-3e94-4867-ab01-a1e7e0a44256)
![image](https://github.com/user-attachments/assets/414e364c-cac7-486e-87ae-32acd120f1fd)

I tried to solve the problem using the regex but I didn't find any regex that could extract the ">" from each line of the content.
I  could solve the issue using a manual extraction for the ">" if all the lines start with this character otherwise I will do nothing.
Do you have any suggestions for the issue or other approaches??

**Comment by bartlomieju** [comment]
Still reproduces on Deno 2.8.1.

Minimal repro (`README.md`):

```md
> ```ts
> const x: number = 1;
> ```
```

`deno test --doc README.md`:

```
error: SyntaxError: Expression expected
  |
1 | > const x: number = 1;
  |   ~~~~~
    at file:///.../README.md$3-7.ts:1:3
```

Root cause: doc-test extraction is regex-based rather than a real markdown parse (`cli/util/extract.rs`). The fenced-block regex captures everything between the ``` ``` ``` fences verbatim, and the per-line regex only strips a shebang or an optional leading `# ` — it has no notion of `> ` blockquote prefixes. So inside a blockquote every line keeps its `> ` and the extracted source isn't valid TS. The same approach would also mishandle nested blockquotes (`> > `) and other markdown container indentation.

Fix direction: strip the blockquote prefix during extraction (add `> ` handling to the per-line processing), or more robustly replace the regex extractor with an actual markdown parser so container blocks are handled correctly.
