### ISSUE TITLE
thread 'main' panicked at runtime\worker.rs:701:7

### ISSUE THREAD

**Issue by joy-stacks** [denoland/deno#24208]
**NestJs**

Platform: windows11 x64
Version: 1.42.1

run **`deno run --watch -A src/main.ts`** success
![image](https://github.com/denoland/deno/assets/101572433/cd144570-9915-4111-935a-67fb70c11e9d)

but run **`deno compile --output dist/main --target x86_64-pc-windows-msvc src/main.ts`**
run `main.exe` failed

error message:

thread 'main' panicked at runtime\worker.rs:701:7:
Bootstrap exception: TypeError: testEnabled is not a function
    at init (ext:deno_node/internal/util/debuglog.ts:51:15)
    at debug (ext:deno_node/internal/util/debuglog.ts:54:5)
    at logger (ext:deno_node/internal/util/debuglog.ts:69:29)
    at readableAddChunk (ext:deno_node/_stream.mjs:2797:7)
    at Readable.push (ext:deno_node/_stream.mjs:2791:14)
    at initStdin (ext:deno_node/_process/streams.mjs:185:13)
    at Object.internals.__bootstrapNodeProcess (node:process:652:22)
    at initialize (ext:deno_node/02_init.js:34:15)
    at bootstrapMainRuntime (ext:runtime_main/js/99_main.js:873:7)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at C:\a\deno\deno\runtime\tokio_util.rs:103:36:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1), ...)
thread 'main' panicked at ext\io\lib.rs:131:38:
called `Result::unwrap()` on an `Err` value: Os { code: 50, kind: Uncategorized, message: "The request is not supported。" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at C:\a\deno\deno\runtime\tokio_util.rs:103:36:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1), ...)

**Comment by satyarohith** [comment]
@joy-stacks thanks for opening the issue. Can you provide steps to reproduce the error?

**Comment by lucacasonato** [comment]
@satyarohith I think we can trace this down without a reproduction? In the `deno_compile` case, we are not passing in some flags to the worker setup during bootstrap that causes this "testEnabled is not a function error" during runtime bootstrapping.

**Comment by joy-stacks** [comment]
> @joy-stacks thanks for opening the issue. Can you provide steps to reproduce the error?
https://codesandbox.io/p/github/joy-stacks/deno-demo/main

**Comment by joy-stacks** [comment]
> @joy-stacks thanks for opening the issue. Can you provide steps to reproduce the error?

@satyarohith https://codesandbox.io/p/github/joy-stacks/deno-demo/main

**Comment by satyarohith** [comment]
Thanks for the reproducible @joy-stacks! The added windows label to the issue as the compiled program works fine on unix platform.
