### ISSUE TITLE
ext/node: executionAsyncResource is not a function

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno#24231]
Encountered a new error when running dd-trace example with https://github.com/denoland/deno/pull/24229
```
error: Uncaught TypeError: executionAsyncResource is not a function
    at AsyncResourceStorage._executionAsyncResource (file:///Users/sr/c/satyarohith/deno_dd_trace_example/node_modules/.deno/dd-trace@5.17.0/node_modules/dd-trace/packages/datadog-core/src/storage/async_resource.js:104:12)
    at AsyncResourceStorage.getStore (file:///Users/sr/c/satyarohith/deno_dd_trace_example/node_modules/.deno/dd-trace@5.17.0/node_modules/dd-trace/packages/datadog-core/src/storage/async_resource.js:45:27)
    at withNoop (file:///Users/sr/c/satyarohith/deno_dd_trace_example/node_modules/.deno/dd-trace@5.17.0/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:17:25)
    at error (file:///Users/sr/c/satyarohith/deno_dd_trace_example/node_modules/.deno/dd-trace@5.17.0/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:65:3)
    at Channel.publish (node:diagnostics_channel:140:9)
    at Object.error (file:///Users/sr/c/satyarohith/deno_dd_trace_example/node_modules/.deno/dd-trace@5.17.0/node_modules/dd-trace/packages/dd-trace/src/log/index.js:67:20)
    at Tracer.init (file:///Users/sr/c/satyarohith/deno_dd_trace_example/node_modules/.deno/dd-trace@5.17.0/node_modules/dd-trace/packages/dd-trace/src/proxy.js:153:11)
    at file:///Users/sr/c/satyarohith/deno_dd_trace_example/main.mjs:3:9
```

Reproducible:
```js
import { open } from 'node:fs';
import { executionAsyncId, executionAsyncResource } from 'node:async_hooks';

console.log(executionAsyncId(), executionAsyncResource());  // 1 {}
open(new URL(import.meta.url), 'r', (err, fd) => {
  console.log(executionAsyncId(), executionAsyncResource());  // 7 FSReqWrap
});
```
Current output:
```
➜  ~ node a.mjs
0 {}
11 FSReqCallback { oncomplete: [Function (anonymous)] }
➜  ~ denod run -A a.mjs
error: Uncaught SyntaxError: The requested module 'node:async_hooks' does not provide an export named 'executionAsyncResource'
import { executionAsyncId, executionAsyncResource } from 'node:async_hooks';
                           ^
    at <anonymous> (file:///Users/sr/a.mjs:2:28)
```

Ref: #23744

**Comment by bartlomieju** [comment]
Can't reproduce on Deno 2.7.
