### ISSUE TITLE
TransformStream with preact-render-to-string renderToPipeableStream

### ISSUE THREAD

**Issue by igorbrasileiro** [denoland/deno#24280]
Version: Deno 1.44.2

I'm trying to use preact-render-to-string renderToPipeableStream API with deno, following this snippet below 

```tsx
// routes/index.ts
// fresh project
import { lazy, Suspense } from "preact/compat";
import { renderToPipeableStream } from "https://esm.sh/v135/preact-render-to-string@6.5.5/stream-node";

const LazyComp = lazy(() => import("../components/Lazy.tsx"));

export const handler = {
  GET: () => {
    const { readable, writable } = new TransformStream();

    const stream = renderToPipeableStream(<Home />, {
      onShellReady() {
        stream.pipe(writable);
      },
    });

    return new Response(readable, {
      headers: { "Content-Type": "text/plain" },
    });
  },
};

export default function Home() {
  return (
    <div class="px-4 py-8 mx-auto bg-[#86efac]">
        <Suspense fallback={"... working"}>
          <LazyComp />
        </Suspense>
    </div>
  );
}
```
I'm getting this error
```
error: Uncaught (in promise) TypeError: dest.on is not a function
    at PassThrough.Readable.pipe (ext:deno_node/_stream.mjs:3123:12)
    at Object.pipe (https://esm.sh/v135/preact-render-to-string@6.5.5/denonext/stream-node.js:2:8391)
    at Object.onShellReady (file:///Users/igorbrasileiro/dev/renderToPipeableStream/routes/index.tsx:12:16)
    at https://esm.sh/v135/preact-render-to-string@6.5.5/denonext/stream-node.js:2:8312
    at eventLoopTick (ext:core/01_core.js:168:7)
Watcher Process failed. Restarting on file change...
```

**Comment by lucacasonato** [comment]
`renderToPipeableStream` is to create a Node stream - you want a web `ReadableStream`. You can get this with:

```js
import { renderToReadableStream } from "https://esm.sh/v135/preact-render-to-string@6.5.5/stream";
```
