### ISSUE TITLE
`GPURenderBundleEncoder.setIndexBuffer` `size` parameter defaults to `0`

### ISSUE THREAD

**Issue by 0f-0b** [denoland/deno#24288]
```ts
const adapter = await navigator.gpu.requestAdapter();
if (!adapter) {
  throw "no adapter";
}
const device = await adapter.requestDevice();
const buffer = device.createBuffer({ size: 2, usage: GPUBufferUsage.INDEX });
const encoder = device.createRenderBundleEncoder({ colorFormats: [] });
encoder.setIndexBuffer(buffer, "uint16");
```

```shellsession
$ deno run --unstable-webgpu a.ts
error: Uncaught (in promise) TypeError: size must be larger than 0
encoder.setIndexBuffer(buffer, "uint16");
        ^
    at GPURenderBundleEncoder.setIndexBuffer (ext:deno_webgpu/01_webgpu.js:4943:5)
    at …/a.ts:8:9
$ deno --version
deno 1.44.4+6ab1433 (canary, aarch64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5
```

**Comment by Hajime-san** [comment]
I found some diff between deno's implementation and current spec around this issue.

- https://www.w3.org/TR/2024/WD-webgpu-20240813

## GPURenderCommandsMixin

> [GPURenderCommandsMixin](https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpurendercommandsmixin) defines rendering commands common to [GPURenderPassEncoder](https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpurenderpassencoder) and [GPURenderBundleEncoder](https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpurenderbundleencoder).

> [GPURenderCommandsMixin](https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpurendercommandsmixin) assumes the presence of [GPUObjectBase](https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpuobjectbase), [GPUCommandsMixin](https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpucommandsmixin), and [GPUBindingCommandsMixin](https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpubindingcommandsmixin) members on the same object. It must only be included by interfaces which also include those mixins.

- https://github.com/gpuweb/gpuweb/pull/2452

## GPUDebugCommandsMixin

[GPUDebugCommandsMixin](https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpudebugcommandsmixin) is also common to [GPURenderPassEncoder](https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpurenderpassencoder) and [GPUComputePassEncoder](https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpucomputepassencoder)


## GPUBindingCommandsMixin

The `setBindGroup()` method has two overloads, and the `bindGroup` argument to be nullable.

- https://www.w3.org/TR/2024/WD-webgpu-20240813/#gpubindingcommandsmixin

upstream wgpu
- https://github.com/gfx-rs/wgpu/issues/4738
- https://github.com/gfx-rs/wgpu/pull/5778#issuecomment-2173803806
