### ISSUE TITLE
Does not function on Deno Deploy but functions when running locally

### ISSUE THREAD

**Issue by uptownhr** [denoland/deno#24298]
Version: Deno 1.44.0

Here is the repo that is resulting in a different behavior when I run locally vs when ran in deno cloud. 

My Github Project: [Tiny Url](https://github.com/uptownhr/tiny-url)

## Local STR
1. clone 
2. `deno task dev`
3. visit http://localhost:3000

Expected Behavior: you'll see an empty array as your response and not a 500

## Deno Cloud
1. clone
2. `deployctl deploy`
3. visit the auto-generated deno url

Expected Behavior: empty array
Actual Behavior: I see a 500 error

Reason for 500 error from Deno Cloud Logs

```

    at async file:///node_modules/.deno/@nestjs+core@10.3.9/node_modules/@nestjs/core/router/router-proxy.js:9:17
6/20/2024, 8:59:58 PM
gcp-us-west2
    at async file:///node_modules/.deno/@nestjs+core@10.3.9/node_modules/@nestjs/core/router/router-execution-context.js:46:28
6/20/2024, 8:59:58 PM
gcp-us-west2
    at eventLoopTick (ext:core/01_core.js:175:21)
6/20/2024, 8:59:58 PM
gcp-us-west2
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
6/20/2024, 8:59:58 PM
gcp-us-west2
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
6/20/2024, 8:59:58 PM
gcp-us-west2
    at Object.runMicrotasks (ext:core/01_core.js:642:26)
6/20/2024, 8:59:58 PM
gcp-us-west2
    at file:///node_modules/.deno/@nestjs+core@10.3.9/node_modules/@nestjs/core/router/router-execution-context.js:38:29
6/20/2024, 8:59:58 PM
gcp-us-west2
    at RedirectController.create (file:///src/controller.ts:30:30)
6/20/2024, 8:59:58 PM
gcp-us-west2
TypeError: Cannot read properties of undefined (reading 'create')
6/20/2024, 8:59:58 PM
gcp-us-west2
[Nest] 2  - 06/21/2024, 3:59:58 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'create')
6/20/2024, 8:59:58 PM
```

I believe this means that the dependency injection of NestJS failed to inject the RedirectController here.

**Comment by uptownhr** [comment]
Closing in favor of the [deploy feedback repo](https://github.com/denoland/deploy_feedback/issues/680)
