### ISSUE TITLE
connection error: unexpected end of file

### ISSUE THREAD

**Issue by hemanth** [denoland/deno#24315]
```sh
export DENO_TLS_CA_STORE=system
```

```sh
~/labs
❯ deno --version
deno 1.43.5 (release, aarch64-apple-darwin)
v8 12.4.254.13
typescript 5.4.5
```

```sh
~/labs
❯ deno run -A -r https://fresh.deno.dev
error: error sending request for url (https://deno.land/std@0.208.0/fs/_util.ts): connection error: unexpected end of file
    at https://deno.land/std@0.208.0/fs/ensure_dir.ts:2:33
```

Am I missing something here?

**Comment by SzilvasiPeter** [comment]
I have a similar problem when creating a fresh workspace:

```
error: error sending request from [2a00:1110:20b:2a16:44ac:91e9:845b:d622]:37652 for https://deno.land/std@0.208.0/fs/_util.ts ([2600:1901:0:6d85::]:443): client error (SendRequest): connection error: peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof
    at https://deno.land/std@0.208.0/fs/ensure_dir.ts:2:33
```

> Note: I am using the `--unsafely-ignore-certificate-errors` flag because corporate network blocks the request.

**Comment by bartlomieju** [comment]
I'm unable to reproduce this on the latest canary (`deno 2.8.1+d95ceb5`, aarch64-apple-darwin). Both the exact module fetch from the report and a full `deno run` against `https://deno.land/std@0.208.0` succeed with `DENO_TLS_CA_STORE=system` set:

```
$ DENO_TLS_CA_STORE=system deno eval "const r = await fetch('https://deno.land/std@0.208.0/fs/_util.ts'); console.log(r.status, (await r.text()).length)"
200 2495
```

This was originally reported on 1.43.5 and the underlying TLS/networking stack has changed substantially since then. Closing as it no longer reproduces. If anyone still hits `connection error: unexpected end of file` with a recent version, please comment with your version and a reproduction and we'll reopen.
