### ISSUE TITLE
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists. || pragmaFrag cannot be set when runtime is automatic

### ISSUE THREAD

**Issue by j-Cis** [denoland/deno#24316]
I have a problem, VSCode highlights all preact/html elements in red as an error.
**JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.**

![err1-Snipaste_2024-04-14_08-58-53](https://github.com/denoland/fresh/assets/24595339/4ad2d820-15dc-40ed-a7dd-815707a73abd)

I noticed that if I add these 3 lines to each element, the problem of highlighting the error disappears, but then this creates another problem, this time with compilation.

```typescript
/** @jsx h */
/** @jsxFrag Fragment */
import { h, Fragment } from "preact";
```

![err2-Snipaste_2024-04-14_09-05-20](https://github.com/denoland/fresh/assets/24595339/50429940-a415-4cbc-b629-e282c7b15596)

```bash
Watcher File change detected! Restarting!
error: Uncaught (in promise) TypeError: pragma cannot be set when runtime is automatic at file:///A:/_CODE/SVG_DENO/svg-chart-family/routes/index.tsx:1:1

pragmaFrag cannot be set when runtime is automatic at file:///A:/_CODE/SVG_DENO/svg-chart-family/routes/index.tsx:2:1
  const manifest = (await import(toFileUrl(join(dir, "fresh.gen.ts")).href))
                    ^
    at async dev (https://deno.land/x/fresh@1.6.8/src/dev/dev_command.ts:38:21)
    at async file:///A:/_CODE/SVG_DENO/svg-chart-family/dev.ts:8:1
Watcher Process failed. Restarting on file change...
```

[This problem was also noticed in deno: https://github.com/denoland/deno/issues/23339](https://github.com/denoland/deno/issues/23339)

**Comment by bartlomieju** [comment]
Resolved on current Deno. The two parts of this report:

1. **`JSX element implicitly has type 'any' ... no interface 'JSX.IntrinsicElements'`** - fixed. With the standard Fresh/Preact config (`"jsx": "react-jsx"`, `"jsxImportSource": "preact"`), type-checking passes cleanly with no pragmas:

   ```
   Check file:///.../comp.tsx     # exit 0, no JSX.IntrinsicElements error
   ```

   The automatic JSX runtime resolves the JSX types from preact, so the editor red squiggles are gone (the LSP uses the same config). This matches @nayeemrmn's earlier "this is fixed now" comment.

2. **`pragma cannot be set when runtime is automatic`** - this is correct behavior, not a bug. `@jsx` / `@jsxFrag` pragmas belong to the classic JSX runtime and genuinely can't be combined with `react-jsx` (automatic). Those pragmas were only added as a workaround for #1; now that #1 is fixed, you don't add them, and Preact JSX works via the automatic runtime.

The other report in this thread (shared multi-root VSCode workspace) was a workspace configuration issue that resolved when opening the Fresh app in a single-folder workspace.

Closing as resolved. If anyone still sees `JSX.IntrinsicElements` errors on a current Deno + Fresh setup, please open a fresh issue with a minimal repro and your `deno.json`.
