### ISSUE TITLE
bug: panic from invalid `host` values for `net` permission

### ISSUE THREAD

**Issue by jeremyBanks** [denoland/deno#24354]
Deno 1.44.4 will panic if an invalid `host` parameter value is specified for the `net` permission, either on the command line or with the runtime permission API.

## To Reproduce

```
deno repl --allow-net='.example.com'
```

or

```
deno run --allow-net='*' main.ts
```

or

```typescript
Deno.permissions.request({ name: "net", host: "*" });
```

## Actual Result

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.44.4
Args: ["deno", "repl", "--allow-net=*"]

thread 'main' panicked at runtime/permissions/lib.rs:744:22:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <deno_permissions::NetDescriptor as deno_permissions::Descriptor>::parse
   4: deno_permissions::Permissions::new_unary
   5: deno_permissions::Permissions::from_options
   6: deno::tools::repl::run::{{closure}}
   7: deno::spawn_subcommand::{{closure}}
   8: <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   9: tokio::runtime::task::raw::poll
  10: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Expected Result

An error message (for CLI) or exception (for runtime), like you get if you specify an invalid value for `--allow-sys`:

```
$ deno run --allow-sys=foobar
error: invalid value 'foobar' for '--allow-sys[=<API_NAME>...]': unknown system info kind "foobar"

For more information, try '--help'.


Caused by:
    unknown system info kind "foobar"
```

```
$ deno run test.ts 
error: Uncaught (in promise) TypeError: unknown system info kind "foobar"
Deno.permissions.request({ name: "sys", kind: "foobar" });
                 ^
    at opRequest (ext:runtime/10_permissions.js:73:10)
    at Permissions.requestSync (ext:runtime/10_permissions.js:261:20)
    at Permissions.request (ext:runtime/10_permissions.js:246:34)
    at file:///mnt/d/example/test.ts:1:18
```

**Comment by yazan-abdalrahman** [comment]
hi, @jeremyBanks 
There is a previous issue for this here: https://github.com/denoland/deno/issues/23552

**Comment by dsherret** [comment]
Yeah same underlying issue. Let's track this in #23552
