### ISSUE TITLE
Deno panic on file with typo (un-commented URL)

### ISSUE THREAD

**Issue by dylanpyle** [denoland/deno#24417]
The following file reliably panics, rather than throwing a syntax error, on latest deno (v1.44.4), macOS 14.5:

```
$ cat broken.ts
https://fake.com

interface Fake {
}
```

```
$ deno run broken.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.44.4
Args: ["deno", "run", "broken.ts"]

thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_typescript-0.189.1/src/strip_type.rs:14:5:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
$ RUST_BACKTRACE=1 deno run broken.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.44.4
Args: ["deno", "run", "broken.ts"]

thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_typescript-0.189.1/src/strip_type.rs:14:5:
internal error: entered unreachable code
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <swc_ecma_transforms_typescript::strip_type::StripType as swc_ecma_visit::VisitMut>::visit_mut_ts_type
   4: swc_ecma_visit::visit_mut_decl
   5: <swc_ecma_transforms_typescript::strip_type::StripType as swc_ecma_visit::VisitMut>::visit_mut_module_items
   6: <swc_ecma_transforms_typescript::typescript::TypeScript as swc_ecma_visit::VisitMut>::visit_mut_program
   7: <swc_ecma_ast::module::Program as swc_ecma_visit::FoldWith<V>>::fold_with
   8: deno_ast::transpiling::fold_program
   9: deno_ast::transpiling::transpile
  10: deno_ast::transpiling::<impl deno_ast::parsed_source::ParsedSource>::transpile
  11: deno::emit::EmitParsedSourceHelper::transpile
  12: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by yazan-abdalrahman** [comment]
@bartlomieju  What is the expected outcome here? Should it handle the panic and return an error?

**Comment by petamoriken** [comment]
The URL line is treated as a label (`https:`) and a line comment (`//fake.com`), so the result should just be expected to succeed.

**Comment by dsherret** [comment]
This no longer panics for me.
