### ISSUE TITLE
Bug: Panic when attaching inspector to `jest`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24424]
```sh
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.44.4
Args: ["/Users/marvinh/dev/denoland/deno/target/debug/deno", "run", "-A", "--inspect-brk", "node_modules/.bin/jest", "--runInBand", "foo.test.js"]

thread 'main' panicked at /Users/marvinh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.292.0/ops.rs:54:5:
op op_fs_stat_sync was not marked as #[op2(reentrant)], but re-entrantly invoked op op_apply_source_map
stack backtrace:
   0:        0x10b51143c - std::backtrace_rs::backtrace::libunwind::trace::he4f0a5f56afe8e37
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:        0x10b51143c - std::backtrace_rs::backtrace::trace_unsynchronized::habb302958e80f800
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10b51143c - std::sys_common::backtrace::_print_fmt::h9819d35e2a5cda77
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
   3:        0x10b51143c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10b537640 - core::fmt::rt::Argument::fmt::h626862aa6242248a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
   5:        0x10b537640 - core::fmt::write::heedef092c8c0962e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
   6:        0x10b50b140 - std::io::Write::write_fmt::h7178e8e2ea928914
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
   7:        0x10b511294 - std::sys_common::backtrace::_print::ha0f584bc7bfb9d2b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x10b511294 - std::sys_common::backtrace::print::h417292deb95532ed
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x10b512940 - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
  10:        0x10b512634 - std::panicking::default_hook::h24535936bc1f51de
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:298:9
  11:        0x103fff21c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4268b40f785d0b26
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
  12:        0x104068e88 - deno::setup_panic_hook::{{closure}}::hd99cad0e4ad7e689
                               at /Users/marvinh/dev/denoland/deno/cli/main.rs:262:5
  13:        0x10b5132a8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd294eb67051ac295
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
  14:        0x10b5132a8 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:799:13
  15:        0x10b512cb0 - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:664:13
  16:        0x10b5118c4 - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
  17:        0x10b512a20 - rust_begin_unwind
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
  18:        0x10b5347a0 - core::panicking::panic_fmt::hc2b459a5bd3dce66
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
  19:        0x109afd4e4 - deno_core::ops::reentrancy_check::hcde311841f14936d
                               at /Users/marvinh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.292.0/ops.rs:54:5
  20:        0x109d6d660 - deno_core::ops_builtin_v8::op_apply_source_map::op_apply_source_map::slow_function_impl::h4fa99cd699a9ffb8
                               at /Users/marvinh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.292.0/ops_builtin_v8.rs:1050:1
  21:        0x109d6d660 - deno_core::ops_builtin_v8::op_apply_source_map::op_apply_source_map::v8_fn_ptr::h6a5ad5f61bcbdcef
                               at /Users/marvinh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.292.0/ops_builtin_v8.rs:1050:1
```

## Steps to reproduce

1. Run `npm init -y && npm i jest`
2. Create a test file `foo.test.js` with these contents:
  ```js
  it("should work", () => {
    console.log("hey")
  });
  ```
3. Run `DENO_FUTURE=1 deno run -A --inspect-brk npm:jest --runInBand foo.test.js`
4. Attach to the inspector in chrome by going to `chrome://inspect`
5. -> Panic

Version: Deno 1.44.4 (git 496ea5903)

**Comment by bartlomieju** [comment]
No longer reproduces on Deno v2.6.10
