### ISSUE TITLE
http writes don't work after detaching socket

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#24429]
Initially added in https://github.com/denoland/deno/commit/dc16c996dd83164011f3931a8bb49f25624601af. The test reports false positive because of header buffering and doesn't really attempt to send data.

To repro add another `res.write` here:
https://github.com/denoland/deno/blob/147411e64b22fe74cb258125acab83f9182c9f81/tests/unit_node/http_test.ts#L1049-L1050

```
deno test -A --unstable --config=tests/config/deno.json tests/unit_node/http_test.ts --filter=detachSocket

error: TypeError: this[#resolve] is not a function
    at ServerResponse.respond (node:http:1169:18)
    at ServerResponse.write [as _write] (node:http:1072:18)
    at writeOrBuffer (ext:deno_node/_stream.mjs:3956:16)
    at _write (ext:deno_node/_stream.mjs:3901:14)
    at ServerResponse.Writable.write (ext:deno_node/_stream.mjs:3904:14)
    at file:///Users/divy/gh/deno/tests/unit_node/http_test.ts:1053:7
```

**Comment by bartlomieju** [comment]
The original crash (`TypeError: this[#resolve] is not a function` when calling `res.write()` after `res.detachSocket()`) is fixed on Deno canary (2.7.12+8258225). Multiple writes after detaching the socket no longer throw.
