### ISSUE TITLE
File hash value error in AWS SDK S3

### ISSUE THREAD

**Issue by fushihara** [denoland/deno#24551]
I am uploading files to S3 using the AWS SDK, but at certain phials the upload fails and I get a XAmzContentSHA256Mismatch error.
The same error will certainly occur with certain files.
I tried to minimize the file size for verification purposes, but if I just shorten it by a few bytes, it is fine, but if I shave 1kb off, it does not reproduce.
The test.bin is a video file of about 2 GB.
Password for 7z file is 4wprhsks35uxyn42
https://27.gigafile.nu/0811-l99208e89d489e095fa22681739fa57b0
![image](https://github.com/user-attachments/assets/1e95c057-5c59-413c-a766-2e2296d3f111)

I think it is a Deno issue as I could not reproduce it in node.js.
The values of the error codes ClientComputedContentSHA256 and S3ComputedContentSHA256 are always the same.
Of course, requestId, etc. will be different each time.

I debugged and checked various variables, but I think the contents of the Buffer used to calculate the ClientComputedContentSHA256 hash value and the contents of the request body that was actually PUT to the AWS api are different.

```
>deno --version
deno 1.45.1 (release, x86_64-pc-windows-msvc)
v8 12.7.224.12
typescript 5.5.2
```

bucket name and profile name must be valid values in your aws environment
Uncomment out to see the detailed and voluminous log.

```ts
import { Readable } from "node:stream";
import { S3Client, StorageClass } from "npm:@aws-sdk/client-s3@3.614.0";
import { Upload } from "npm:@aws-sdk/lib-storage@3.614.0"

const BUCKET_NAME="your-bucket";
Deno.env.set("AWS_REGION", "ap-northeast-1")
Deno.env.set("AWS_PROFILE", "xxxxxxxxxx")
await putSingleFile("./test.bin", BUCKET_NAME, "test.bin", "STANDARD");
export async function putSingleFile(fromFile: string, toBucket: string, toPath: string, storageClass: StorageClass) {
  const client = new S3Client({
    // logger: {
    //   debug: console.debug.bind(console),
    //   error: (...args: any[]) => {
    //     if (args?.[0]?.input?.Body != null) {
    //       args[0].input.Body = "empty";
    //     }
    //     console.error.call(console, args);
    //   },
    //   info: (...args: any[]) => {
    //     if (args?.[0]?.input?.Body != null) {
    //       args[0].input.Body = "empty";
    //     }
    //     console.log.call(console, args);
    //   },
    //   warn: console.warn.bind(console),
    //   trace: console.debug.bind(console),
    // },
  });
  const fileHandler = await Deno.open(fromFile, { read: true });
  const rs = Readable.from(fileHandler.readable)
  const multipartUpload = new Upload({
    client: client,
    params: {
      Bucket: toBucket,
      Key: toPath,
      Body: rs,
      StorageClass: "STANDARD",
    }
  });
  console.log(`UPLOAD START   "${fromFile}" to "s3://${toBucket}/${toPath}" ${storageClass}`);
  try {
    const done = await multipartUpload.done();
    console.log(`UPLOAD SUCCESS . Etag:${done.ETag ?? ""}`);
    return true;
  } catch (error) {
    console.error(`UPLOAD FAILED.`, error);
    return false;
  }
}
/**
UPLOAD FAILED. XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed.
    at throwDefaultError (file:///C:/Users/xxx/AppData/Local/deno/npm/registry.npmjs.org/@smithy/smithy-client/3.1.7/dist-cjs/index.js:839:20)
    at file:///C:/Users/xxx/AppData/Local/deno/npm/registry.npmjs.org/@smithy/smithy-client/3.1.7/dist-cjs/index.js:848:5
    at de_CommandError (file:///C:/Users/xxx/AppData/Local/deno/npm/registry.npmjs.org/@aws-sdk/client-s3/3.614.0_1/dist-cjs/index.js:4741:14)
    at Object.runMicrotasks (ext:core/01_core.js:642:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:175:21)
    at async file:///C:/Users/xxx/AppData/Local/deno/npm/registry.npmjs.org/@smithy/middleware-serde/3.0.3/dist-cjs/index.js:35:20
    at async file:///C:/Users/xxx/AppData/Local/deno/npm/registry.npmjs.org/@aws-sdk/middleware-signing/3.609.0/dist-cjs/index.js:226:18
    at async file:///C:/Users/xxx/AppData/Local/deno/npm/registry.npmjs.org/@smithy/middleware-retry/3.0.9/dist-cjs/index.js:320:38 {
  name: "XAmzContentSHA256Mismatch",
  "$fault": "client",
  "$metadata": {
    httpStatusCode: 400,
    requestId: "MK9607579BKYJ695",
    extendedRequestId: "daBW36U5gWXb1tTeq/x1Z1v+bf4m6mAJWZSXebRxLd9pGxGRS3X5hr1oZkoYYuzmmlvbCbirYVc=",
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: "XAmzContentSHA256Mismatch",
  ClientComputedContentSHA256: "749d27efcde2194c9b0d6692bad5880740f90e70a5e4200b3e0ace34744b3102",
  S3ComputedContentSHA256: "6fdb427a9655231378d35541c14ded99a0c7fc7ccfd8b8d33db4312bc73e6feb",
  RequestId: "MK9607579BKYJ695",
  HostId: "daBW36U5gWXb1tTeq/x1Z1v+bf4m6mAJWZSXebRxLd9pGxGRS3X5hr1oZkoYYuzmmlvbCbirYVc=",
  message: "The provided 'x-amz-content-sha256' header does not match what was computed."
}
*/
```

**Comment by fushihara** [comment]
I have identified the problem and created a lightweight reproduction code and will close this issue.
Here is the new issue

https://github.com/denoland/deno/issues/24571
