### ISSUE TITLE
Bug with deno install?

### ISSUE THREAD

**Issue by nshiab** [denoland/deno#24582]
Version: .45.2 (release, aarch64-apple-darwin)
v8 12.7.224.12
typescript 5.5.2

Hi!

I am trying to install the simple-data-analysis library, which uses duckdb. But when I run this:
```
DENO_FUTURE=1 deno install --node-modules-dir --allow-scripts npm:simple-data-analysis
```

I get this error:
```
⚠️ `deno install` behavior will change in Deno 2. To preserve the current behavior use the `-g` or `--global` flag.
Created deno.json configuration file.
Add simple-data-analysis - npm:simple-data-analysis@^3.3.2
Warning Trying to set up 'arrow2csv' bin for "/Users/naelshiab/Desktop/test-deno/node_modules/.deno/apache-arrow@16.1.0/node_modules/apache-arrow", but the entry point "/Users/naelshiab/Desktop/test-deno/node_modules/.deno/apache-arrow@16.1.0/node_modules/apache-arrow/bin/arrow2csv.cjs" doesn't exist.
error: Uncaught (in promise) ReferenceError: require is not defined
require('../lib/main');
^
    at file:///Users/naelshiab/Desktop/test-deno/node_modules/.deno/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp:4:1
error: script 'install' in 'duckdb@1.0.0' failed with exit code 1
```

And because DuckDB is not installed, I can't use the library. This will cause an error:

```
deno run index.ts
```

```ts
import { SimpleDB } from "simple-data-analysis";

const sdb = new SimpleDB();
const table = sdb.newTable();
await table.loadArray([{ first: "nael", last: "shiab" }]);
await table.logTable()
```

```
error: Uncaught (in promise) Error: Cannot find module '/Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/binding/duckdb.node'
Require stack:
- /Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/duckdb-binding.js
- /Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/duckdb.js
- /Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/duckdb.js
    at Function.Module._resolveFilename (node:module:608:15)
    at Function.Module._load (node:module:486:27)
    at Module.require (node:module:674:19)
    at require (node:module:785:16)
    at Object.<anonymous> (file:///Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/duckdb-binding.js:4:15)
    at Object.<anonymous> (file:///Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/1.0.0/lib/duckdb-binding.js:7:4)
    at Module._compile (node:module:730:34)
    at Object.Module._extensions..js (node:module:744:10)
    at Module.load (node:module:655:32)
    at Function.Module._load (node:module:523:12)
```

What am I doing wrong?

Thank you for all of your work.

**Comment by marvinhagemeister** [comment]
Looking into it the error is correct because the `package.json` says that it would have a file at `bin/arrow2csv.cjs` but it's absent in the files shipped in the npm tarball. Npm seems to silently ignore that error during installation and it doesn't create an entry in `node_modules/.bin` either. We should do the same in Deno, although we could print a warning in the console about the broken entry.

**Comment by nshiab** [comment]
Thank you!

**Comment by marvinhagemeister** [comment]
Seems like there is already an issue for that on their tracker https://github.com/apache/arrow/issues/42229

**Comment by nathanwhit** [comment]
Actually the arrow message is a bit of a misdirect (and already only a warning), it's not the root problem here.

The actual bug is with `--allow-scripts` combined with only passing the `--node-modules-dir` _flag_ (as opposed to having `"nodeModulesDir": true` in `deno.json`).

This was fixed in https://github.com/denoland/deno/pull/24533, so this should be fixed on canary (and will be in the next patch release).

You can also work around this right now by creating a `deno.json` file with:

```json
{
  "nodeModulesDir": true
}
```

That will work even on `1.45.2`.

Let us know if you continue to have problems!

**Comment by nshiab** [comment]
Wonderful! Thanks @nathanwhit!
