### ISSUE TITLE
File with just `+` does not report syntax error

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#24617]
Create a file `main.ts`.

```ts
+
```

Then run `deno info main.ts`

No diagnostic is raised.

Change the file to:

```ts
a+
```

Running `deno info main.ts` now:

```
error: The module's source code could not be parsed: Expression expected at file:///home/lucacasonato/Downloads/publishing_tasks_903afdc4-681b-403c-bc23-1768af7eaad9/index.ts:1:2

  a+
   ~
```

**Comment by lucacasonato** [comment]
Same issue with:

```ts
void
```

**Comment by dsherret** [comment]
This is by design. Certain diagnostics are only surfaced when transpiling:

```
> deno run main.ts 
error: Expression expected at file:///V:/scratch/main.ts:1:1

  +
  ~
```

**Comment by dsherret** [comment]
The main reason for this issue was resolved in https://github.com/denoland/deno/pull/24620

Maybe we should close this one?
