### ISSUE TITLE
Non-zero exit code in a test case causes the test to fail since 1.44.0

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno#24624]
### Summary

Since 1.44.0, non-zero exit code in a test case has started to cause the test case to fail.

Not sure if this behavior is intended or not, but in [deployctl] repo I found there are a couple of test cases affected by this change, so I'm concerned this breaks tests in other repos as well.

[deployctl]: https://github.com/denoland/deployctl

### Reproducible Code

```ts
Deno.test(function denoExit() {
  try {
    Deno.exit(1);
  } catch { /* noop */ }
});

```

### Before 1.44.0

```console
❯ deno --version
deno 1.43.6 (release, aarch64-apple-darwin)
v8 12.4.254.13
typescript 5.4.5

❯ deno test main_test.ts
running 1 test from ./main_test.ts
denoExit ... ok (0ms)

ok | 1 passed | 0 failed (0ms)
```

### 1.44.0 and later

```console
❯ deno test main_test.ts
running 1 test from ./main_test.ts
denoExit ... FAILED (0ms)

 ERRORS

denoExit => ./main_test.ts:1:6
error: Error: Test case finished with exit code set to 1.
    at exitSanitizer (ext:cli/40_test.js:113:15)
    at async outerWrapped (ext:cli/40_test.js:134:14)

 FAILURES

denoExit => ./main_test.ts:1:6

FAILED | 0 passed | 1 failed (1ms)

error: Test failed
```

### Workaround

Forcibly setting the exit code to 0 resolves the issue.

```diff
Deno.test(function denoExit() {
  try {
    Deno.exit(1);
  } catch {
+    Deno.exitCode = 0;
  }
});
```

```console
❯ deno --version
deno 1.44.0 (release, aarch64-apple-darwin)
v8 12.6.228.3
typescript 5.4.5

❯ deno test main_test.ts
running 1 test from ./main_test.ts
denoExit ... ok (0ms)

ok | 1 passed | 0 failed (0ms)
```

### Additional Info

Related PR https://github.com/denoland/deno/pull/23609

**Comment by lucacasonato** [comment]
This is expected behaviour.
