### ISSUE TITLE
Import error on startup when a Fresh project is a workspace member

### ISSUE THREAD

**Issue by dahlia** [denoland/deno#24622]
If a Fresh project is a workspace member, an import error occurs on startup.  Here's how to reproduce it:

```sh
echo '{"workspace": ["fresh"]}' > deno.json
deno run -A -r https://fresh.deno.dev fresh
cd fresh/
deno task start
```

Here's the error message:

```
error: Relative import path "preact" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs"
    at https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:46
```

**Comment by marvinhagemeister** [comment]
This seems to occur when a dependency of a workspace member refers to something in the import map of said member. In this case fresh is expected to resolve the `preact` dependency based on the import map of the workspace member. This error seems to only happen with transient dependencies of http imports from what I can tell.

**Comment by darkship** [comment]
is this the same issue as when a `island` imports something from a workspace member?

```
[ERROR] specifier was a bare specifier, but was not remapped to anything by importMap. [plugin deno-resolver]

islands/SunriseManualButton.tsx:1:25:
1 │ import { postJSON } from '@scope/libs';



 Error: Build failed with 2 errors:
 islands/ShutterIsland.tsx:6:25: ERROR: [plugin: deno-resolver] specifier was a bare specifier, but was not remapped to anything by importMap.
 islands/SunriseManualButton.tsx:1:25: ERROR: [plugin: deno-resolver] specifier was a bare specifier, but was not remapped to anything by importMap.
   at failureErrorWithLog (https://deno.land/x/esbuild@v0.20.2/mod.js:1626:15)
   at https://deno.land/x/esbuild@v0.20.2/mod.js:1034:25
   at runOnEndCallbacks (https://deno.land/x/esbuild@v0.20.2/mod.js:1461:45)
   at buildResponseToResult (https://deno.land/x/esbuild@v0.20.2/mod.js:1032:7)
   at https://deno.land/x/esbuild@v0.20.2/mod.js:1061:16
   at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.20.2/mod.js:679:9)
   at handleIncomingPacket (https://deno.land/x/esbuild@v0.20.2/mod.js:739:9)
   at readFromStdout (https://deno.land/x/esbuild@v0.20.2/mod.js:655:7)
   at https://deno.land/x/esbuild@v0.20.2/mod.js:1974:11
   at eventLoopTick (ext:core/01_core.js:168:7) {
   errors: [Getter/Setter],
   warnings: [Getter/Setter]


```

seems to work for not island components

**Comment by sergeysolovev** [comment]
I have the same issue with preact. Trying to make a fresh app a workspace member (it’s been a subfolder)

**Comment by hoomp3** [comment]
issue still happening

**Comment by arvati** [comment]
yes issue still happens.
even If you transfer import maps into parent package , Islands does not work , since fresh start can not find preact.

**Comment by fckpro** [comment]
+1

**Comment by phenomenal-hardy** [comment]
having exact same issue when using workspace and deno.

ward.

**Comment by theTechGoose** [comment]
If you move your imports from the bottom level deno.json to the top level the app compiles.

**Comment by DLoT** [comment]
I got it to work by adding the dependencies of the fresh app into my root deno.jsonc 

root deno config
`
{
  "workspace": [
    "./projects/fresh-app"
  ],
  "tasks": {
    "dev:fresh-app": "cd projects/fresh-app && deno run -A --node-modules-dir start"
  },
  "nodeModulesDir": "auto",
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.7.3/",
    "preact": "https://esm.sh/preact@10.22.0",
    "preact/": "https://esm.sh/preact@10.22.0/",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.2.2",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.5.1",
    "$std/": "https://deno.land/std@0.216.0/"
  },
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact",
    "lib": [
      "deno.window",
      "dom"
    ],
    "strict": true
  }
}`

project deno config
`
{
  "tasks": {
    "check": "deno fmt --check && deno lint && deno check **/*.ts && deno check **/*.tsx",
    "cli": "echo \"import '\\$fresh/src/dev/cli.ts'\" | deno run --unstable -A -",
    "manifest": "deno task cli manifest $(pwd)",
    "start": "deno run -A --watch=static/,routes/ dev.ts",
    "build": "deno run -A dev.ts build",
    "preview": "deno run -A main.ts",
    "update": "deno run -A -r https://fresh.deno.dev/update ."
  },
  "lint": {
    "rules": {
      "tags": [
        "fresh",
        "recommended"
      ]
    }
  },
  "exclude": [
    "**/_fresh/*"
  ],
  "fmt": {
    "lineWidth": 120,
    "singleQuote": true
  },
  "imports": {
  }
}`


-> deno task dev:fresh-app

**Comment by theTechGoose** [comment]
I came across this and it took me several days to resolve. If I had just followed directions it would have not been so much. Here are plain as day instructions to get it up and running

Move all of your imports from your fresh deno.json to your workspace json.

add the following into your entrypoint:
```

globalThis.React = await import("preact/compat");
declare global {
  //@ts-ignore
  var React: typeof import("preact/compat");
  namespace JSX {
    interface IntrinsicElements {
      [elemName: string]: any;
    }
}
}
```

**Comment by drernie** [comment]
Moving the contents of my project import into the root fixed the issue for me, without needing to munge anything else.  But perhaps that is because I am not (yet) using React directly.

**Comment by egorkarimov** [comment]
+1 
What is the state for the Fresh to support the Deno workspaces/monorepo out of the box? Moving deps to the root deno.json is not great...

**Comment by tansanDOTeth** [comment]
I just adopted fresh for a project thinking it would have the best outcome in terms of integration with the latest Deno since its from the Deno team. Kind of disappointed to find out that adding workspaces would break my fresh app unless I move all the dependencies to the parent.

**Comment by marvinhagemeister** [comment]
This is resolved in Fresh 2 and that version works with workspaces. It's currently in [alpha status](https://fresh.deno.dev/docs/canary/introduction) but we've been using it for about a year in production already. We're working on getting it released it soon, but there are some API changes we want to make.

**Comment by tansanDOTeth** [comment]
> This is resolved in Fresh 2 and that version works with workspaces. It's currently in [alpha status](https://fresh.deno.dev/docs/canary/introduction) but we've been using it for about a year in production already. We're working on getting releasing it soon, but there are some API changes we want to make.

That sounds promising. I'll look into upgrading this week!

**Comment by codingwesley** [comment]
@DLoT  Thanks your job, save my time.

**Comment by bartlomieju** [comment]
Closing this as it's specific to Fresh 1's use of esm.sh HTTP imports, where transient dependencies use bare specifiers (like `preact`) that fail to resolve against the workspace member's import map.

This issue does not affect Fresh 2, which uses npm/jsr packages instead of esm.sh URLs. If you're hitting this, upgrading to Fresh 2 is the recommended workaround. You can scaffold a new Fresh 2 project with:

```sh
deno run -A jsr:@fresh/init my-project
```

Or follow the migration guide at https://fresh.deno.dev/docs/concepts/updating.
