### ISSUE TITLE
ERR_MULTIPLE_CALLBACK is thrown during running `test` script in commander.js repo

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#24646]
Steps to reproduce:

- clone https://github.com/tj/commander.js
- run `deno install`
- run `deno task test`

3 cases fail with `Jest worker encountered 4 child process exceptions, exceeding retry limit`, and the root cause of them seems `error: Uncaught Error: Callback called multiple times` during running each case. That error seems thrown at https://github.com/denoland/deno/blob/main/ext/node/polyfills/_stream.mjs#L3986

```
error: Uncaught Error: Callback called multiple times
Error: 
    at new ERR_MULTIPLE_CALLBACK (ext:deno_node/internal/errors.ts:1225:17)
    at onwrite (ext:deno_node/_stream.mjs:3986:32)
    at Writable.write [as _write] (ext:deno_node/_process/streams.mjs:43:7)
    at writeOrBuffer (ext:deno_node/_stream.mjs:3956:16)
    at _write (ext:deno_node/_stream.mjs:3901:14)
    at Writable.write (ext:deno_node/_stream.mjs:3904:14)
    at Object.writeOut (<anonymous>:23305:31)
    at Object.write (<anonymous>:28122:42)
    at Command.outputHelp (<anonymous>:28213:13)
    at Command._outputHelpIfRequested (<anonymous>:28498:12)
    at Command._parseCommand (<anonymous>:26225:10)
    at Command.parse (<anonymous>:25279:10)
    at Object.<anonymous> (<anonymous>:52:15)
    at Promise.then.completed (<anonymous>:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (<anonymous>:231:10)
    at _callCircusTest (<anonymous>:316:40)
    at Object.runMicrotasks (ext:core/01_core.js:642:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:175:21)
    at async _runTest (<anonymous>:252:3)
    at async _runTestsForDescribeBlock (<anonymous>:126:9)
    at async _runTestsForDescribeBlock (<anonymous>:121:9)
    at async run (<anonymous>:71:3)
    at async runAndTransformResultsToJestFormat (<anonymous>:122:21)
    at jestAdapter (file:///Users/kt3k/oss/commander.js/node_modules/.deno/jest-circus@29.7.0/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (file:///Users/kt3k/oss/commander.js/node_modules/.deno/jest-runner@29.7.0/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (file:///Users/kt3k/oss/commander.js/node_modules/.deno/jest-runner@29.7.0/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (file:///Users/kt3k/oss/commander.js/node_modules/.deno/jest-runner@29.7.0/node_modules/jest-runner/build/testWorker.js:106:12)
```

Version: Deno 1.45.2

**Comment by bartlomieju** [comment]
Still reproduces on the latest development build (same 3 test suites fail):

```
Test Suites: 3 failed, 107 passed, 110 total
Tests:       1274 passed, 1274 total
```

Some observations:
- The tests **pass** when run individually (`jest tests/command.configureOutput.test.js`) or in-band (`--runInBand`)
- The tests **fail** only when Jest runs the full suite with forked worker processes, suggesting a race/load-dependent issue
- All pass with Node
- The `ERR_MULTIPLE_CALLBACK` originates from `onwrite()` in the `_stream_writable` implementation — the `kExpectWriteCb` flag is already cleared when `state.onwrite` is called a second time
- The `_write` in `createWritableStdioStream` (`ext:deno_node/_process/streams.mjs`) uses synchronous `writer.writeSync()` and then calls `cb()` synchronously — so the double-callback likely involves the stream being destroyed or erroring while a synchronous write sequence is in progress in a child process with piped stdout/stderr
