### ISSUE TITLE
Bug: Node http error sending request

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24670]
Reported via discord: https://discord.com/channels/684898665143206084/1264926772646907975/1264932423104467025

## Steps to reproduce

1. Run this script:
  ```ts
  fetch("https://www.christianrock.net/iphonecrdn.php")
    .then(console.log);
  ```

Version: Deno 1.45.2

**Comment by bartlomieju** [comment]
Current error:
```
await fetch("https://www.christianrock.net/iphonecrdn.php")
  .then(console.log)
Uncaught TypeError: client error (Connect)
    at async mainFetch (ext:deno_fetch/26_fetch.js:170:12)
    at async fetch (ext:deno_fetch/26_fetch.js:391:7)
    at async <anonymous>:1:22
```

**Comment by timharek** [comment]
It's the same for [Bjorn Lunden](https://www.bjornlunden.se/)'s APIs, eg. https://apigateway.blinfo.se/auth/oauth/v2/token

**Comment by bartlomieju** [comment]
Triaged this today (Deno 2.8.2 canary):

**The original URL is no longer reproducible.** `fetch("https://www.christianrock.net/iphonecrdn.php")` returns 200. The server now negotiates TLS 1.3 with `TLS_AES_256_GCM_SHA384`, a standard modern config, so the server's TLS setup was upgraded since this was reported.

**The URL from https://github.com/denoland/deno/issues/24670#issuecomment-2285614922 (apigateway.blinfo.se) still fails**, with:

```
client error (Connect): received fatal alert: HandshakeFailure
```

The root cause is on the server side: it rejects TLS 1.3 entirely and accepts only TLS 1.2 with `ECDHE-RSA-AES256-SHA384`, a CBC cipher suite. Probing it with all common TLS 1.2 AEAD suites (ECDHE AES-GCM 128/256, ChaCha20-Poly1305, plain AES-GCM) shows it rejects every one of them. rustls, which Deno uses for TLS, intentionally does not implement CBC cipher suites because of their padding-oracle history, and upstream will not add them. curl and Node happen to work because OpenSSL still supports CBC.

So this is not something Deno can fix: servers that offer no AEAD cipher suites at all cannot be reached through rustls, by design. The fix has to happen on the server (enable at least one TLS 1.2 GCM/ChaCha20 suite, or TLS 1.3), which is what happened with the originally reported URL.

Closing as not planned.
