### ISSUE TITLE
Error using `node:dgram` with link-local IPv6 addresses

### ISSUE THREAD

**Issue by nathanwhit** [denoland/deno#24694]
Repro:

```js
import { strictEqual } from "node:assert";
import { createSocket } from "node:dgram";
import { networkInterfaces } from "node:os";
import process from "node:process";

const isWindows = process.platform === "win32";

function linklocal() {
  for (const [ifname, entries] of Object.entries(networkInterfaces())) {
    for (const { address, family, scopeid } of entries) {
      if (family === "IPv6" && address.startsWith("fe80:")) {
        return { address, ifname, scopeid };
      }
    }
  }
}
const iface = linklocal();

if (!iface) {
  process.exit(0);
}

const address = isWindows ? iface.address : `${iface.address}%${iface.ifname}`;
const message = "Hello, local world!";

// Create a client socket for sending to the link-local address.
const client = createSocket("udp6");

// Create the server socket listening on the link-local address.
const server = createSocket("udp6");

server.on(
  "listening",
  () => {
    const port = server.address().port;
    client.send(message, 0, message.length, port, address);
  },
);

server.on(
  "message",
  (buf, info) => {
    const received = buf.toString();
    strictEqual(received, message);
    // Check that the sender address is the one bound,
    // including the link local scope identifier.
    strictEqual(
      info.address,
      isWindows ? `${iface.address}%${iface.scopeid}` : address,
    );
    server.close();
    client.close();
  },
);

server.bind({ address });
```

Output:

```
error: Uncaught Error: bind UNKNOWN fe80::1%lo0
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:217:10)
    at node:dgram:273:20
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:36:15)
    at eventLoopTick (ext:core/01_core.js:165:29)
```

Expect no output, and for the program to exit cleanly.

**Comment by bartlomieju** [comment]
Fixed in #32381
