### ISSUE TITLE
Errors thrown from `process.nextTick` don't emit `uncaughtException` events

### ISSUE THREAD

**Issue by nathanwhit** [denoland/deno#24713]
AFAIK this means that if something throws from `process.nextTick`, it's unrecoverable.

Repro:

```js
import process from "node:process";

process.on("uncaughtException", (e) => {
  console.error("uncaught exception handler", e);
});

process.nextTick(() => {
  throw new Error();
});

await new Promise((r) => setTimeout(r, 0));
console.error("done");
```

Deno:

```
error: Uncaught Error
  throw new Error();
        ^
    at file:///home/nexttick.mjs:8:9
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:25:11)
    at eventLoopTick (ext:core/01_core.js:165:29)
```

Node:

```
uncaught exception handler Error
    at file:///home/nexttick.mjs:8:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
done
```

**Comment by bartlomieju** [comment]
This will require changes in `deno_core` 😬
