### ISSUE TITLE
[Sveltekit] Module import fails starting from Deno 1.45.0

### ISSUE THREAD

**Issue by rracariu** [denoland/deno#24722]
Starting from version 1.45.0 I'm getting this error when running `DENO_FUTURE=1 deno run -A --inspect npm:vite dev`

```
error when starting dev server:
TypeError: [ERR_INVALID_PACKAGE_TARGET] Invalid "exports" main target {"types":"./index.d.ts","import":"./index.js"} defined in the package config /project/node_modules/sveltekit-adapter-deno/package.json imported from 'file:///project/svelte.config.js?ts=1721926075403'; target must start with "./"
    at file:///project/svelte.config.js?ts=1721926075403:9:25
    at async load_config (file:///project/node_modules/@sveltejs/kit/src/core/config/index.js:70:17)
    at async sveltekit (file:///project/node_modules/@sveltejs/kit/src/exports/vite/index.js:130:24)
    at async Promise.all (index 0)
    at async asyncFlatten (file:///project/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:17369:12)
    at async resolveConfig (file:///project/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:66463:27)
    at async _createServer (file:///project/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:63050:18)
    at async CAC.<anonymous> (file:///project/node_modules/vite/dist/node/cli.js:735:20)
```

The import looks like `import denoAdapter from 'sveltekit-adapter-deno';`

Version: deno 1.45.3 (release, aarch64-apple-darwin)
v8 12.7.224.13
typescript 5.5.2

**Comment by dsherret** [comment]
Caused by https://github.com/denoland/deno/pull/24492/files#diff-05634a82e4e5d22732b8ea32675a5422616fc7800d08ada3f5598f85dbf7ce41R216-R225
