### ISSUE TITLE
Bug: npm postinstall scripts should run with `deno run -A`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24739]
When you import an npm package that requires postinstall scripts to be run, it is not executed during installation despite passing `-A`.

## Steps to reproduce

1. create file `main.ts` with these contents:
  ```ts
  import sqlite3Init from "npm:sqlite3";

  const sqlite3 = sqlite3Init.verbose();
  const db = new sqlite3.Database(":memory:");
  
  db.serialize(() => {
    db.run("CREATE TABLE lorem (info TEXT)");
  
    const stmt = db.prepare("INSERT INTO lorem VALUES (?)");
    for (let i = 0; i < 10; i++) {
      stmt.run("Ipsum " + i);
    }
    stmt.finalize();
  
    db.each("SELECT rowid AS id, info FROM lorem", (err, row) => {
      console.log(row.id + ": " + row.info);
    });
  });
  
  db.close();
  ```
2. Run `DENO_FUTURE=1 deno run -A main.ts`

Output:

```sh
$ DENO_FUTURE=1 deno run -A main.ts
warning: Packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed.
    This may cause the packages to not work correctly. To run them, use the `--allow-scripts` flag with `deno cache` or `deno install`
    (e.g. `deno cache --allow-scripts=pkg1,pkg2 <entrypoint>` or `deno install --allow-scripts=pkg1,pkg2`):
      npm:sqlite3@5.1.7
error: Uncaught (in promise) Error: Could not locate the bindings file. Tried:
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/build/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/build/Debug/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/build/Release/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/out/Debug/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/Debug/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/out/Release/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/Release/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/build/default/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/compiled/20.11.1/darwin/arm64/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/addon-build/release/install-root/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/addon-build/debug/install-root/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/addon-build/default/install-root/node_sqlite3.node
 → /Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/lib/binding/node-v108-darwin-arm64/node_sqlite3.node
    at bindings (file:///Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/bindings@1.5.0/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (file:///Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/lib/sqlite3-binding.js:1:291)
    at Object.<anonymous> (file:///Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/lib/sqlite3-binding.js:3:4)
    at Module._compile (node:module:1028:34)
    at Object.Module._extensions..js (node:module:1066:10)
    at Module.load (node:module:913:32)
    at Function.Module._load (node:module:722:12)
    at Module.require (node:module:935:19)
    at require (node:module:1122:16)
    at Object.<anonymous> (file:///Users/marvinh/dev/test/deno-sqlite32/node_modules/.deno/sqlite3@5.1.7/node_modules/sqlite3/lib/sqlite3.js:2:17)
```

Version: Deno 1.45.3 (git 7776636c2 2024-07-26)

**Comment by bartlomieju** [comment]
Duplicate of https://github.com/denoland/deno/issues/24523

**Comment by bartlomieju** [comment]
Not a duplicate after all

**Comment by dsherret** [comment]
We discussed this one in the CLI meeting and won't do this one because it introduces a security issue of possibly running install scripts for a package that you're not even going to use when running a script in your repo with `-A`.

**Comment by G0x209C** [comment]
And this is breaking...
