### ISSUE TITLE
package.json cannot resolve jsr dependencies inside workspace

### ISSUE THREAD

**Issue by andykais** [denoland/deno#24781]
Version: Deno 1.45.3

I am working on building a sveltekit project that can be developed in deno and ran in deno production. So far I have been able to get vite dev & vite build to work with a custom adapter. The code is here in a [barebones example repo](https://github.com/andykais/sveltekit-deno). The issue is that deno dependencies seem to behave differently inside a workspace. 

If I take the linked repo above and drop it inside a workspace in another repo I get errors like this 
```
failed to load config from /home/andrew/Code/development/forager/packages/web/vite.config.ts
error when starting dev server:
TypeError: npm package '@jsr/andykais__ts-rpc' does not exist.
    at file:///home/andrew/Code/development/forager/packages/web/vite.config.ts.timestamp-1722216203693-cbe5226eadf6e.mjs:2:27
    at async loadConfigFromBundledFile (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/vite/5.3.5/dist/node/chunks/dep-mCdpKltl.js:66365:15)
    at async loadConfigFromFile (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/vite/5.3.5/dist/node/chunks/dep-mCdpKltl.js:66206:24)
    at async resolveConfig (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/vite/5.3.5/dist/node/chunks/dep-mCdpKltl.js:65816:24)
    at async _createServer (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/vite/5.3.5/dist/node/chunks/dep-mCdpKltl.js:62432:18)
    at async CAC.<anonymous> (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/vite/5.3.5/dist/node/cli.js:735:20)
```

Where the simple top level deno.json might look like so:

```json
{
  "workspace": [
    "./packages/web"
  ]
}
```

I suspect this is because deno is not treating the current directory like a "node project", since I can achieve a similar error by adding a deno.json file to the current directory

**Comment by dsherret** [comment]
The `.npmrc` file is only discovered at the root of the workspace. You might need to move it there.

**Comment by andykais** [comment]
hmm I dont think that is the solution @dsherret. I tried moving `.npmrc` to the top of the workspace (and tried copying it into both places) and I still get the same error

**Comment by dsherret** [comment]
@andykais can you link to a repo that I can clone and run a set of steps to reproduce the behaviour?

Ex. 1. Clone .... 2. Run `deno run ....`

**Comment by andykais** [comment]
sure thing. @dsherret I created a branch on the sample repo using workspaces that repros the issue with steps to run: https://github.com/andykais/sveltekit-deno/tree/workspace-repro. Let me know if there is other info I can provide

**Comment by andykais** [comment]
I will say one other oddity is that `vite` appears to require `package.json` to run correctly. This seems to be related to both how it imports its `vite.config.ts` file. I have attempted to set up import maps for all its dependencies in a deno.json file, but that doesnt seem to work nicely, especially since it doesnt seem to understand nested npm dependencies from an import map declaration. I dont want to side track this current discussion though, so I can create a separate issue for that topic

**Comment by andykais** [comment]
> I will say one other oddity is that vite appears to require package.json to run correctly.

Just a small follow up that I discovered this is called out in the deno docs https://jsr.io/docs/with/vite, so at least the part about using package.json is expected.

The workspace + package.json issue does still persist in deno `1.46.1`, and attempting to use
 `DENO_FUTURE=1 deno install` gives a similar error output:
```
error: npm package '@jsr/andykais__ts-rpc' does not exist.
```

**Comment by andykais** [comment]
I just wanted to poke this issue again to share that this issue is adding a decent amount of extra steps and churn to my development workflow. I have a project structure like so:
```
monorepo/
  deno.json
  packages/
    core/
      deno.json (name: @forager/core)
    cli/
      deno.json (name: @forager/cli, depends on @forager/core and @forager/web)
web/
  package.json (name: @forager/web, depends on @forager/core)
```

where `monorepo/deno.json` is the workspace file, and `web/package.json` needs special treatment because of the aforementioned bug. I am going to lay out what the standard workflow is right now for updating these different packages. If I update `@forager/core`, generally I can then update `@forager/cli` at the same time, and things function as expected. Then I just make two pushes to github bumping the version number on `@forager/core` and then `@forager/cli`. This all works very well. The issue comes in when I want to manage developing the `@forager/web` package, which is in the 'middle' of the dependency tree and lives outside the deno workspace. There is no good mechanism to locally link workspace dependencies _into_ `@forager/web`, nor is there a good way to link dependencies _out_ of `@forager/web` to `@forager/cli`. This means that every change is only testable by publishing a public version on jsr, then updating that dependency locally. Luckily, my libraries here are not popular 😅 so I can push broken/debugging versions all the time and prove those out. If this were a live library with real users though, this workflow would become problematic very quickly. It also just creats a lot of confusion on jsr seeing many different minor & patch versions on jsr when ideally I can just iterate on all of these things locally at the same time

**Comment by reallyely** [comment]
I appreciate the info you have here. There's some scattered information out there about this compatibility issue at the intersection of Vite, Deno & Workspaces but little comprehensive solution.  Worse, it's hard to track what solutions are relevant given the Deno 2.0 shift. Hope you're able to find a solid solution.

**Comment by andykais** [comment]
This is still busted on latest deno canary.
```
deno 2.3.0-rc.2+326fd3a (canary, release, aarch64-apple-darwin)
v8 13.5.212.10-rusty
typescript 5.7.3
```

@dsherret is this something I should open in the vite repo? I see no [open issues related to this topic](https://github.com/vitejs/vite/issues?q=is%3Aissue%20state%3Aopen%20deno%20workspace%20) in their repo. Fwiw, my guess at this issue is a disconnect  between how the package is defined in the package.json (`"@std/datetime": "npm:@jsr/std__datetime@^0.225.4"`) and how it is stored in node_modules (`node_modules/@std/datetime/`)

based on the error:
```
error: npm package '@jsr/std__datetime' does not exist.
```

**Comment by andykais** [comment]
given the latest deno blog post that local npm packages are now supported, could I possibly work around the need to publish a jsr package, then update my dependency by packaging my `@forager/core` lib using https://github.com/denoland/dnt, then referencing it locally?

**Comment by andykais** [comment]
I have found a way to work around this. The changes are in a pr here https://github.com/andykais/forager/pull/27. Its a bit hacky, but it at least lets me avoid publishing a new package every time I want to integrate it into my sveltekit app. It seems like this is a pretty rare problem, so I haven't made that pr particularly readable on how it was solved, but I did leave a few comments in the pr description for those who are curious

**Comment by bartlomieju** [comment]
The titled bug no longer reproduces on canary `2.8.1`. I tested the minimized repro (a `package.json` inside a Deno workspace depending on a jsr package via the `@jsr/` npm registry):

```jsonc
// deno.json
{ "workspace": ["./web"] }
```
```
# .npmrc
@jsr:registry=https://npm.jsr.io
```
```jsonc
// web/package.json
{ "dependencies": { "@std/datetime": "npm:@jsr/std__datetime@^0.225.4" } }
```

- `deno install` succeeds (fetches `@jsr/std__datetime` from npm.jsr.io)
- `deno run` of `import { format } from "@std/datetime"` works (`typeof format === "function"`)

The original `npm package '@jsr/std__datetime' does not exist` error is gone.

The remaining item from this thread, ergonomics of locally linking a workspace member into a `package.json`-based subpackage without publishing to jsr, is a separate workspace-linking concern rather than the resolution bug in the title. Closing this as resolved; please open a focused issue for the local-linking workflow if that is still a pain point.
