### ISSUE TITLE
Deno panic while calling `fetch` `Result::unwrap()` after `Object.defineProperty`

### ISSUE THREAD

**Issue by vdata1** [denoland/deno#24784]
Hi, 
I want to report a Deno panic caused by `fetch` after changing `Array`'s property. It can reproduced by running the following code snippet: 

```javascript
 Object.defineProperty(Array.prototype, '1', {
  set: function () {
  }
});

const response = await fetch('https://example.com');
```

Deno output: 

```shell
Platform: macos x86_64
Version: 1.45.4
Args: ["deno", "run", "12.js"]

thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_v8-0.208.0/de.rs:268:61:
called `Result::unwrap()` on an `Err` value: BadType { actual: "v8::data::Value", expected: "v8::data::Object" }
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize
   4: deno_fetch::op_fetch::op_fetch<FP>::v8_fn_ptr
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Thanks,

**Comment by littledivy** [comment]
Panic was fixed, it now throws an error:
```
Uncaught TypeError: serde_v8 error: invalid type; expected: object, got: undefined
    at mainFetch (ext:deno_fetch/26_fetch.js:152:43)
    at ext:deno_fetch/26_fetch.js:353:9
    at new Promise (<anonymous>)
    at fetch (ext:deno_fetch/26_fetch.js:316:18)
    at <anonymous>:4:24
>
```

**Comment by bartlomieju** [comment]
This no longer panics on current Deno (v2.7.x) — it now throws a proper TypeError instead:

```
error: Uncaught (in promise) TypeError: expected type `v8::data::Array`, got `v8::data::Value`
```

Closing as resolved.
