### ISSUE TITLE
🐛(WinOS) Unable to open 'CONIN$' or 'CONOUT$' for all versions >= 1.43.0

### ISSUE THREAD

**Issue by rivy** [denoland/deno#24791]
Version: Deno 1.43.0+

For versions of Deno > 1.43.0, it's no longer possible to open the special files *CONIN$* or *CONOUT$*.

```shell
❯ deno --version
deno 1.43.1 (release, x86_64-pc-windows-msvc)
v8 12.4.254.12
typescript 5.4.3
❯ deno eval "const f = Deno.openSync('CONOUT$', {read: true, write:true}); console.log({f, isTTY: f.isTerminal()});"
error: Uncaught (in promise) NotFound: The system cannot find the file specified. (os error 2): open 'CONIN$'
...
```

**Comment by piscisaureus** [comment]
@rivy if you try to open `\\.\CONIN$` and/pr `\\.\CONOUT$`, does that still work?

**Comment by rivy** [comment]
Thanks for taking some time to look at this issue.

And, no, unfortunately, the same error occurs. Here's the full output for both cases (*CONOUT$* and *//./CONOUT$*)...

```shell
❯ deno --version
deno 1.45.5 (release, x86_64-pc-windows-msvc)
v8 12.7.224.13
typescript 5.5.2

C:\W\System32❯ deno eval "const f = Deno.openSync('CONOUT$', {read: true, write:true}); console.log({f, tty: Deno.isatty(f.
rid)});"
error: Uncaught (in promise) NotFound: The system cannot find the file specified. (os error 2): open 'CONOUT$'
const f = Deno.openSync('CONOUT$', {read: true, write:true}); console.log({f, tty: Deno.isatty(f.rid)});
               ^
    at Object.openSync (ext:deno_fs/30_fs.js:620:15)
    at file:///C:/Windows/System32/$deno$eval:1:16

C:\W\System32❯ deno eval "const f = Deno.openSync('//./CONOUT$', {read: true, write:true}); console.log({f, tty: Deno.isatt
y(f.rid)});"
error: Uncaught (in promise) NotFound: entity not found: open '//./CONOUT$'
const f = Deno.openSync('//./CONOUT$', {read: true, write:true}); console.log({f, tty: Deno.isatty(f.rid)});
               ^
    at Object.openSync (ext:deno_fs/30_fs.js:620:15)
    at file:///C:/Windows/System32/$deno$eval:1:16
```

For comparison, this is the output from v1.42.0...

```shell
❯ deno --version
deno 1.42.0 (release, x86_64-pc-windows-msvc)
v8 12.3.219.9
typescript 5.4.3

C:\W\System32❯ deno eval "const f = Deno.openSync('CONOUT$', {read: true, write:true}); console.log({f, tty: Deno.isatty(f.
rid)});"
{ f: FsFile {}, tty: true }

C:\W\System32❯ deno eval "const f = Deno.openSync('//./CONOUT$', {read: true, write:true}); console.log({f, tty: Deno.isatt
y(f.rid)});"
{ f: FsFile {}, tty: true }
```

Changing to backslashes, *\\\\.\CONOUT$* using '\\\\\\\\.\\\\CONOUT$', also fails in all cases.

**Comment by rivy** [comment]
For comparison, `node` works for '//./CONOUT$', but *not* 'CONOUT$'. And `bun` works for both...

```shell
❯ node --version
v20.10.0

C:\W\System32❯ node -e "const fs = require('node:fs'); const tty = require('node:tty'); const f = fs.openSync('CONOUT$'); c
onsole.log({f, TTY: tty.isatty(f)});"
node:fs:581
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open 'C:\Windows\System32\CONOUT$'
    at Object.openSync (node:fs:581:18)
    at [eval]:1:78
    at runScriptInThisContext (node:internal/vm:144:10)
    at node:internal/process/execution:109:14
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:92:62)
    at evalScript (node:internal/process/execution:123:10)
    at node:internal/main/eval_string:51:3 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Windows\\System32\\CONOUT$'
}

Node.js v20.10.0

C:\W\System32❯ node -e "const fs = require('node:fs'); const tty = require('node:tty'); const f = fs.openSync('//./CONOUT$'
); console.log({f, TTY: tty.isatty(f)});"
{ f: 3, TTY: true }

C:\W\System32❯ bun --version
1.1.21

C:\W\System32❯ bun -e "const fs = require('node:fs'); const tty = require('node:tty'); const f = fs.openSync('CONOUT$'); co
nsole.log({f, TTY: tty.isatty(f)});"
{
  f: 3,
  TTY: true,
}

C:\W\System32❯ bun -e "const fs = require('node:fs'); const tty = require('node:tty'); const f = fs.openSync('//./CONOUT$')
; console.log({f, TTY: tty.isatty(f)});"
{
  f: 3,
  TTY: true,
}
```

**Comment by rivy** [comment]
More data points, using node-compatibility, from `deno`, `node`, and `bun`...

```shell
❯ deno --version
deno 1.45.5 (release, x86_64-pc-windows-msvc)
v8 12.7.224.13
typescript 5.5.2

C:\W\System32❯ deno eval "import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('CONOUT$'); console.l
og({f, TTY: tty.isatty(f)});"
error: Uncaught (in promise) NotFound: The system cannot find the file specified. (os error 2): open 'CONOUT$'
import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('CONOUT$'); console.log({f, TTY: tty.isatty(f)});
                                                                   ^
    at Object.openSync (ext:deno_fs/30_fs.js:620:15)
    at Object.openSync (ext:deno_node/_fs/_fs_open.ts:100:15)
    at file:///C:/Windows/System32/$deno$eval:1:68

C:\W\System32❯ deno eval "import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('//./CONOUT$'); conso
le.log({f, TTY: tty.isatty(f)});"
error: Uncaught (in promise) NotFound: entity not found: open '//./CONOUT$'
import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('//./CONOUT$'); console.log({f, TTY: tty.isatty(f)});
                                                                   ^
    at Object.openSync (ext:deno_fs/30_fs.js:620:15)
    at Object.openSync (ext:deno_node/_fs/_fs_open.ts:100:15)
    at file:///C:/Windows/System32/$deno$eval:1:68

C:\W\System32❯ deno eval "import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('\\\\.\\CONOUT$'); co
nsole.log({f, TTY: tty.isatty(f)});"
{ f: 3, TTY: true }

C:\W\System32❯ node --version
v20.10.0

C:\W\System32❯ node --input-type module -e "import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('CO
NOUT$'); console.log({f, TTY: tty.isatty(f)});"
node:fs:581
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open 'C:\Windows\System32\CONOUT$'
    at Object.openSync (node:fs:581:18)
    at file:///C:/Windows/System32/[eval1]:1:68
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.eval (node:internal/modules/esm/loader:218:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Windows\\System32\\CONOUT$'
}

Node.js v20.10.0
C:\W\System32❯ node --input-type module -e "import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('//./CONOUT$'); console.log({f, TTY: tty.isatty(f)});"
{ f: 3, TTY: true }

C:\W\System32❯ node --input-type module -e "import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('\\\\.\\CONOUT$'); console.log({f, TTY: tty.isatty(f)});"
{ f: 3, TTY: true }

C:\W\System32❯ bun --version
1.1.21

C:\W\System32❯ bun -e "import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('CONOUT$'); console.log(
{f, TTY: tty.isatty(f)});"
{
  f: 3,
  TTY: true,
}

C:\W\System32❯ bun -e "import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('//./CONOUT$'); console.
log({f, TTY: tty.isatty(f)});"
{
  f: 3,
  TTY: true,
}

C:\W\System32❯ bun -e "import fs from 'node:fs'; import tty from 'node:tty'; const f = fs.openSync('\\\\.\\CONOUT$'); conso
le.log({f, TTY: tty.isatty(f)});"
{
  f: 3,
  TTY: true,
}
```

**Comment by piscisaureus** [comment]
IMO node's behavior is the desirable one. A "bare path" should just create open/create a file named `CONIN$` (or `con`, `aux`, `nul` etc) in the current directory.

To open the device, prefixing with `\\.\` or `\\?\` should work. This is the bug.

**Comment by rivy** [comment]
I agree with your assertion that `CONIN$` and `CONOUT$` or paths with any special "legacy" base file name ([CON, PRN, AUX, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9]) prefixed with device prefixes `\\.\` or `\\?\` should just work (using either slashes or backslashes).

Would the plan be that using the bare names (or name + <any extension> for the "legacy" names) result in errors?

And what would be the plan to handle operating on actual files with those names? ... conversion to a compatible fully qualified "skip-normalization" (`\\?\...`) format prior to file API calls? ... at Deno-level? Userland-level?

Ultimately, however this is finally implemented, it's not obvious, differs from baseline Win32 file API behavior, and is a change from prior functionality. So, IMO, it should be documented, although it's not clear to me where it would be best to place that type of documentation.

> ref: [MSDN ~ File path formats (WinOS)](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats) @@ <https://archive.is/Kuwgp>

**Comment by yazan-abdalrahman** [comment]
@piscisaureus  @lucacasonato 
Hello, I recognized the major cause of the issue and will work on it.

**Comment by rivy** [comment]
@yazan-abdalrahman , I see that you're working on a solution for this issue in PR #25851.

Can you explain what the ultimate solution will look like?

Are you just planning to pass-thru `CONIN$` and `CONOUT$` and all the legacy device names (with optional extensions)?

That method would require a user-land file name filter to change any of those special file names into a hands-off/skip-normalization format (eg, `\\?\...`) prior to file creation/opening.

Alternatively, `deno` could handle that instead by changing all of the special filenames into the `\\?\..` format, ie, creating/opening an actual file with the special name. That would require the user to specifically prefix any "special" file name with `\\?\..` themselves when they actually want access to the device instead of a file of that name. I think that would be a less surprising method and lead to overall better user code.

Example user code...

```ts
// open *files* with special names
... = Deno.openSync('CONIN$', {read: true, write: true});
... = Deno.openSync('CONOUT$', {read: true, write: true});
... = Deno.openSync('CON', {read: true, write: true});
... = Deno.openSync('NUL', {read: true, write: true});
... = Deno.openSync('NUL.txt', {read: true, write: true});
... = Deno.openSync('NUL.tar.gz', {read: true, write: true});

// open a *device* with special names (no file is created/opened)
... = Deno.openSync('//./CONIN$', {read: true, write: true});
... = Deno.openSync('//?/CONIN$', {read: true, write: true});
... = Deno.openSync('\\\\.\\CONIN$', {read: true, write: true});
... = Deno.openSync('\\\\?\\CONIN$', {read: true, write: true});
... = Deno.openSync('//./CONOUT$', {read: true, write: true});
... = Deno.openSync('//./CON', {read: true, write: true});
... = Deno.openSync('//./NUL', {read: true, write: true});
```

This would require documentation of `open()` to note the variance from standard Win32 CreateFile(), but I think it's a much more user-friendly and least surprise method of handing the issue.

**Comment by bartlomieju** [comment]
Note for anyone picking this up: #25851 attempted a fix but has been closed — it targeted `ext/fs/std_fs.rs::open_with_access_check`, which #30005 has since refactored away.

The device-path special-casing now lives in `runtime/permissions/lib.rs` (the `is_windows_device_path` check, currently only matching the `\\.\` prefix and duplicated across three sites). A fresh implementation should:
- add recognition for the special console devices (`CONIN$`/`CONOUT$`) and the `//./`, `//?/`, `\\?\` prefix forms in that file;
- factor the triplicated check into a shared helper;
- avoid over-matching — e.g. a bare `ends_with("$")` would wrongly catch UNC admin shares like `\\server\C$`, and Windows device names need case-insensitive comparison.
