### ISSUE TITLE
v1.45.5 broke `npm:mongodb` - MongoRuntimeError: Server returned an invalid signature

### ISSUE THREAD

**Issue by raaymax** [denoland/deno#24841]
For Deno version 1.45.5
```
❯ deno upgrade --version 1.45.5
Downloading https://github.com/denoland/deno/releases/download/v1.45.5/deno-aarch64-apple-darwin.zip
Deno is upgrading to version 1.45.5
Archive:  /var/folders/4f/6rr3fjvx2wq742xvnz3lf1740000gn/T/.tmphD2C0k/deno.zip
  inflating: deno
Upgraded successfully
❯ deno run -A db_check.ts
error: Uncaught (in promise) MongoRuntimeError: Server returned an invalid signature
    at continueScramConversation (file:///Users/raay/Workspace/CodeCat/Quack/Chat/node_modules/.deno/mongodb@6.1.0/node_modules/mongodb/lib/cmap/auth/scram.js:136:15)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async performInitialHandshake (file:///Users/raay/Workspace/CodeCat/Quack/Chat/node_modules/.deno/mongodb@6.1.0/node_modules/mongodb/lib/cmap/connect.js:114:13)
```
And for Deno version 1.45.4 everything works as expected
```
❯ deno upgrade --version 1.45.4
Downloading https://github.com/denoland/deno/releases/download/v1.45.4/deno-aarch64-apple-darwin.zip
Deno is upgrading to version 1.45.4
Archive:  /var/folders/4f/6rr3fjvx2wq742xvnz3lf1740000gn/T/.tmpWlMTNY/deno.zip
  inflating: deno
Upgraded successfully
❯ deno run -A db_check.ts
[
  {
    _id: new ObjectId("66ac1bb58871e47b2b40a4d4"),
    name: "deno",
    skills: [ "dancing", "hiding" ]
  },
  {
    _id: new ObjectId("66ac1bd3eb1c757eb35b4fc5"),
    name: "deno",
    skills: [ "dancing", "hiding" ]
  }
]
```

**Comment by lucacasonato** [comment]
Can you send along the script you are using to test?

**Comment by JetLua** [comment]
> Can you send along the script you are using to test?

```ts
import {MongoClient} from 'mongodb'

//Normal if not using the SRV format：mongodb://127.0.0.1:27017/rax?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.12
const client = new MongoClient('mongodb+srv://***')

const db = client.db('*')

db.collection('*').find({})
```

**Comment by Joeao** [comment]
Also getting this error on 1.45.5, but not when rolling back to 1.45.4

```ts
import mongoose from "npm:mongoose@^8.5.2";

await mongoose.connect("mongodb+srv://<user>:<pass>@cluster0.<site>.mongodb.net/main");
```

**Comment by raaymax** [comment]
I was using this code https://docs.deno.com/examples/mongo/

**Comment by lucacasonato** [comment]
Bisected to 1ba88a7892fa1b0d7cf229b0cd5709575901ebd0
