### ISSUE TITLE
npm:log4js don't work

### ISSUE THREAD

**Issue by wangfeng1994** [denoland/deno#24858]
Version: Deno 1.45.5
app.mjs

```js
import log4js from "log4js";

const logger = log4js.getLogger();
logger.level = "info";
logger.debug("Got cheese.");
logger.info("Cheese is Comté.");
logger.warn("Cheese is quite smelly.");
logger.error("Cheese is too ripe!");
logger.fatal("Cheese was breeding ground for listeria.");

```
output
![image](https://github.com/user-attachments/assets/95e86229-a798-4199-a783-07a67b01d1e3)

**Comment by birkskyum** [comment]
This breaks Karma too. In new project:

```
➜ pnpm i karma karma-jasmine karma-chrome-launcher jasmine-core
➜ DENO_FUTURE=1 deno run ./node_modules/karma/bin/karma start
✅ Granted all env access.
✅ Granted all read access.
✅ Granted all net access.
error: Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at Object.send (file:///Users/admin/repos/deno-kitchensink/karma-test/node_modules/.pnpm/log4js@6.9.1/node_modules/log4js/lib/clustering.js:95:36)
    at Logger._log (file:///Users/admin/repos/deno-kitchensink/karma-test/node_modules/.pnpm/log4js@6.9.1/node_modules/log4js/lib/logger.js:195:16)
    at Logger.log (file:///Users/admin/repos/deno-kitchensink/karma-test/node_modules/.pnpm/log4js@6.9.1/node_modules/log4js/lib/logger.js:155:12)
    at Logger.<computed> [as error] (file:///Users/admin/repos/deno-kitchensink/karma-test/node_modules/.pnpm/log4js@6.9.1/node_modules/log4js/lib/logger.js:235:10)
    at Process.<anonymous> (file:///Users/admin/repos/deno-kitchensink/karma-test/node_modules/.pnpm/karma@6.4.4/node_modules/karma/lib/server.js:400:16)
    at Process.emit (ext:deno_node/_events.mjs:387:28)
    at Process.emit (node:process:390:40)
    at Object.internals.nodeProcessUnhandledRejectionCallback (node:process:610:15)
    at processUnhandledPromiseRejection (ext:runtime_main/js/99_main.js:495:15)
    at eventLoopTick (ext:core/01_core.js:224:25)
```
