### ISSUE TITLE
Bug: Vitest fails with `Failed to cast callsite method 'getFileName' return value`

### ISSUE THREAD

**Issue by yasaichi** [denoland/deno#24869]
~~Version: Deno x.x.x~~ Commit hash: [71ca61e](https://github.com/denoland/deno/commit/71ca61e189cca9215982ce4598b7a4da8430c584)

Thank you for your recent effort to get Vitest working in Deno. After I saw https://github.com/denoland/deno/issues/24825 merged, I tried it against my codebase and ran into the following error:

```
TypeError: Failed to cast callsite method 'getFileName' return value to correct value: BadType { actual: "v8::data::Value", expected: "v8::data::String" }.
 ❯ wrapCallSite node_modules/.pnpm/vite-node@2.0.5_@types+node@20.14.11_terser@5.31.3/node_modules/vite-node/dist/source-map.mjs:800:24
 ❯ Function.prepareStackTrace node_modules/.pnpm/vite-node@2.0.5_@types+node@20.14.11_terser@5.31.3/node_modules/vite-node/dist/source-map.mjs:857:10
 ❯ processError node_modules/.pnpm/@vitest+utils@2.0.5/node_modules/@vitest/utils/dist/error.js:94:11
 ❯ collectTests node_modules/.pnpm/@vitest+runner@2.0.5/node_modules/@vitest/runner/dist/index.js:784:21
 ❯ Object.runMicrotasks ext:core/01_core.js:653:26
 ❯ processTicksAndRejections ext:deno_node/_next_tick.ts:53:10
 ❯ runNextTicks ext:deno_node/_next_tick.ts:71:3
 ❯ eventLoopTick ext:core/01_core.js:175:21
 ❯ startTests node_modules/.pnpm/@vitest+runner@2.0.5/node_modules/@vitest/runner/dist/index.js:1179:17
 ❯ node_modules/.pnpm/vitest@2.0.5_@types+node@20.14.11_terser@5.31.3/node_modules/vitest/dist/chunks/runBaseTests.CyvqmuC9.js:130:11
```

As I could not make a minimum setup to reproduce the error, I will put some information about the environment instead.

- Deno version: Built from source of which commit hash is [71ca61e](https://github.com/denoland/deno/commit/71ca61e189cca9215982ce4598b7a4da8430c584)
- Vitest
  - Version: 2.0.5
  - Command: `DENO_FUTURE=1 /path/to/deno run -A npm:vitest run`
  - Config: 

```ts
// vitest.config.ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    alias: [
      {
        find: /^@app\/(.+)$/,
        replacement: './libs/$1/src/index.ts',
      },
    ],
    root: './',
  },
});
```

I hope it will be useful to solve the issue. Thank you in advance.

**Comment by yasaichi** [comment]
Related to https://github.com/denoland/deno/issues/23882.

**Comment by marvinhagemeister** [comment]
I was able to narrow this down to a small reproduction snippet.

## Steps to reproduce

Run this script:

```ts
Error.prepareStackTrace = (err, frames) => {
  return frames.map((frame) => frame.getFileName());
};

new Promise((_, reject) => {
  reject(new Error("fail").stack);
});
```

Output:

```sh
error: Uncaught (in promise) TypeError: Failed to cast callsite method 'getFileName' return value to correct value: BadType { actual: "v8::data::Value", expected: "v8::data::String" }.
  return frames.map((frame) => frame.getFileName());
                                     ^
    at file:///Users/marvinh/dev/test/deno-error2/main.ts:2:38
    at Array.map (<anonymous>)
    at Function.Error.prepareStackTrace (file:///Users/marvinh/dev/test/deno-error2/main.ts:2:17)
    at file:///Users/marvinh/dev/test/deno-error2/main.ts:6:28
    at new Promise (<anonymous>)
    at file:///Users/marvinh/dev/test/deno-error2/main.ts:5:1
```

Version: Deno 1.45.5

**Comment by marvinhagemeister** [comment]
Removing the `node compat` label because this is reproducible without importing anything node related.
