### ISSUE TITLE
deno_node: fs.stat(): different error message when using an invalid file path

### ISSUE THREAD

**Issue by hansSchall** [denoland/deno#24899]
Version: Deno 1.44.0, Windows 11

Consider this code:

```typescript
import {stat} from "node:fs";
//    vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv This is obviously not a valid file path
stat("jsr:@std/assert@0.223.0/mod.ts", (err,stats)=>console.log(err));
```

Node.js:

```
[Error: ENOENT: no such file or directory, stat 'D:\dev\...\jsr:@std\assert@0.223.0\mod.ts'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'D:\\dev\\...\\jsr:@std\\assert@0.223.0\\mod.ts'
}
```

Deno:

```
Error: EINVAL: invalid argument, stat
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:62:9)
    at __node_internal_uvException (ext:deno_node/internal/errors.ts:127:10)
    at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1775:14)
    at ext:deno_node/_fs/_fs_stat.ts:138:95
    at eventLoopTick (ext:core/01_core.js:168:7) {
  errno: -4071,
  syscall: "stat",
  code: "EINVAL"
}
```

Instead of reporting that the path does not exist, deno_node throws a completely different error message breaking most error handlers.

The paths rejected are not even consistent, things like `foo:bar@1` work unless they conatin a `/`

I discovered this error while playing around with my Vite plugin: https://github.com/deno-plc/vite-plugin-deno (therefore the jsr: url). Unfortunalely Vite/esbuild reads the file directly (even when a plugin handles the import) and tries to resolve the nearest tsconfig.json. Instead of catching the `no such file or directory` error it gets a totally different error message and aborts the build.

This bug affects all node applications that rely on fs.stat to check if a file exists.

For everyone looking here because they get the same error, this workaround fixed it at least in my case: (it is a bit hacky, but it just redirects all invalid paths to not-existing but valid paths)

```typescript
const deno_stat = Deno.stat;

Deno.stat = (...args) => {
    const path = args[0].toString().replaceAll("\\", "/");

    if (path.includes("/jsr:@")) {
        return deno_stat("./not-existing");
    } else {
        return deno_stat(...args);
    }
};
```

**Comment by marvinhagemeister** [comment]
@hansSchall Can you update Deno to the latest version and try again? I just tried to reproduce the error with Deno 1.45.5 and I get the correct error message.

```sh
Error: ENOENT: no such file or directory, stat
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_uvException (ext:deno_node/internal/errors.ts:186:10)
    at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1890:14)
    at ext:deno_node/_fs/_fs_stat.ts:149:95
    at eventLoopTick (ext:core/01_core.js:168:7) {
  errno: -2,
  syscall: "stat",
  code: "ENOENT"
}
```

**Comment by hansSchall** [comment]
Deno 1.45.5 does not work either
```
PS D:\dev\...> deno
Deno 1.45.5
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> import {stat} from "node:fs"
undefined
> stat("jsr:@std/assert@0.223.0/mod.ts", (err,stats)=>console.log(err));
Error: EINVAL: invalid argument, stat
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_uvException (ext:deno_node/internal/errors.ts:186:10)
    at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1890:14)
    at ext:deno_node/_fs/_fs_stat.ts:149:95
    at eventLoopTick (ext:core/01_core.js:168:7) {
  errno: -4071,
  syscall: "stat",
  code: "EINVAL"
}
undefined
>
```

**Comment by marvinhagemeister** [comment]
Can confirm. This error is depends on the OS. I cannot reproduce it with macOS, but I can on windows.

**Comment by bartlomieju** [comment]
Seems related to https://github.com/denoland/deno/issues/26411
