### ISSUE TITLE
Bug: `frame.getScriptNameOrSourceURL()` missing on `Error`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24898]
Seems like we missed one: `.getScriptNameOrSourceURL()`. Interestingly this API is not documented on https://v8.dev/docs/stack-trace-api . This causes `vitest` to throw an error.

## Steps to reproduce

```ts
Error.prepareStackTrace = (err, frames) => {
  return frames.map((frame) => {
    return frame.getScriptNameOrSourceURL();
  });
};

console.log(new Error("fail").stack);
```

Output Deno:

```sh
error: Uncaught (in promise) TypeError: frame.getScriptNameOrSourceURL is not a function
    return frame.getScriptNameOrSourceURL();
                 ^
    at file:///Users/marvinh/dev/test/deno-error2/foo.mjs:3:18
    at Array.map (<anonymous>)
    at Function.Error.prepareStackTrace (file:///Users/marvinh/dev/test/deno-error2/foo.mjs:2:17)
    at file:///Users/marvinh/dev/test/deno-error2/foo.mjs:7:31
```

Output Node:

```sh
[
  'file:///Users/marvinh/dev/test/deno-error2/foo.mjs',
  'node:internal/modules/esm/module_job',
  'node:internal/modules/esm/loader',
  'node:internal/modules/run_main'
]
```

Output Chrome:

```sh
['']
```

Version: Deno 1.45.5

**Comment by yasaichi** [comment]
This issue is just what I am going to create. I ran into the same error when I tested https://github.com/denoland/deno/issues/24869 against my codebase using Vitest.
