### ISSUE TITLE
npm:bcrypt doesn't work properly in Deno

### ISSUE THREAD

**Issue by MrBns** [denoland/deno#24937]
Version: Deno 1.45.5

Sorry for my weakness in English,
I have been testing my small nodejs project. So I have mapped all the npm library to prefix with `npm:--`.  I  found that `npm:bcrypt` not working properly with deno. 

Here is my output when I run `deno run ./src/index.ts`

```txt
Require stack:
- /mnt/Project/project/fiverr/nada-vlink-app/server/node_modules/.deno/bcrypt@5.1.1/node_modules/bcrypt/bcrypt.js
- /mnt/Project/project/fiverr/nada-vlink-app/server/node_modules/.deno/bcrypt@5.1.1/node_modules/bcrypt/bcrypt.js
    at Function.Module._resolveFilename (node:module:608:15)
    at Function.Module._load (node:module:486:27)
    at Module.require (node:module:674:19)
    at require (node:module:785:16)
    at Object.<anonymous> (file:///mnt/Project/project/fiverr/nada-vlink-app/server/node_modules/.deno/bcrypt@5.1.1/node_modules/bcrypt/bcrypt.js:6:16)
    at Object.<anonymous> (file:///mnt/Project/project/fiverr/nada-vlink-app/server/node_modules/.deno/bcrypt@5.1.1/node_modules/bcrypt/bcrypt.js:238:4)
    at Module._compile (node:module:730:34)
    at Object.Module._extensions..js (node:module:744:10)
    at Module.load (node:module:655:32)
    at Function.Module._load (node:module:523:12)
```

I know there is a lots of bcrypto alternative available in Deno. I created this Report just to let denoland know about this issue.

**Comment by lucacasonato** [comment]
Caused by #16164 - will track there.
