### ISSUE TITLE
 npm:@temporalio/client doesn't work properly in Deno

### ISSUE THREAD

**Issue by patrickalima98** [denoland/deno#24974]
Version: Deno 1.44.2

I'm trying to use the @temporalio/client  [typescript SDK](https://docs.temporal.io/develop/typescript) with Deno to start my Workflows from my project. With the NPM layer compability i can start my workflows and connect to my [Temporal Server](https://temporal.io/).

But after some time or when i disconnect from my server, I'm getting some `node:http2` and `grpc` errors:

```shell
error: Uncaught TypeError: Cannot read properties of undefined (reading 'message')
    at new ERR_HTTP2_STREAM_CANCEL (ext:deno_node/internal/errors.ts:1704:51)
    at closeSession (node:http2:225:20)
    at ClientHttp2Session.destroy (node:http2:173:5)
    at file:///mnt/projects/xxxxxxxxxxxxxx/node_modules/.deno/@grpc+grpc-js@1.11.1/node_modules/@grpc/grpc-js/build/src/transport.js:255:26
    at eventLoopTick (ext:core/01_core.js:203:13)
Watcher Process failed. Restarting on file change...
```

Simple script to test:

Connect wrapper:
```ts
import { Connection, Client } from 'npm:@temporalio/client';

export default async function ({
  buildId = '1.0',
  workflowId,
  workflowTypeOrFunc
}: any) {
  try {
  // Connect to the default Server location
  const connection = await Connection.connect({
    address: Deno.env.get('TEMPORAL_SERVER_ADDRESS'),
  });

  const client = new Client({
    connection,
  });

    await client.taskQueue.updateBuildIdCompatibility('taskQueue', {
      operation: 'addNewIdInNewDefaultSet',
      buildId,
    });

    const handle = await client.workflow.start(workflowTypeOrFunc, {
      taskQueue: 'TEMPORAL_QUEUE',
      args: [],
      workflowId: workflowId,
      searchAttributes: {
        Product: ['Store Evt Driver']
      }
    });

    console.log(`Started workflow ${handle.workflowId}`);

  } catch (err: any) {
    console.error('Error starting workflow:', err);
  }
}

```

Running:

```ts
await temporalClient({ workflowId: crypto.randomUUID(), workflowTypeOrFunc: 'wfFunctionName' });
```

**Comment by marvinhagemeister** [comment]
Does the error occur in the latest Deno version too? You can upgrade your Deno version by running `deno upgrade`

**Comment by patrickalima98** [comment]
Hi @marvinhagemeister tested here with the latest version 1.45.5, getting the same error.

**Comment by bartlomieju** [comment]
ref https://github.com/denoland/deno/pull/30955

**Comment by bartlomieju** [comment]
Looks like we fixed it in https://github.com/denoland/deno/pull/33208
