### ISSUE TITLE
Crash when using Chrome DevTools and a WASM module after an uncaught exception

### ISSUE THREAD

**Issue by hgruniaux** [denoland/deno#24990]
Deno crashed when using the Chrome DevTools and a WASM module. The crash seems to happen a bit after loading the WASM module when an uncaught WASM exception is thrown.

I'm not sure what the problem is, so I can't provide a minimum test. But I remain at your disposal if necessary.

I hope there isn't yet a ticket for this bug.

Logs:
```
Platform: linux x86_64
Version: 1.45.5
Args: ["deno", "run", "--allow-read", "--inspect-wait", "bigloo.mjs", "test.wasm"]

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.299.0/error.rs:1245:36:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: deno_core::error::format_location
   5: <extern "C" fn(A0,A1,A2) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
   6: _ZN2v88internal10ErrorUtils16FormatStackTraceEPNS0_7IsolateENS0_6HandleINS0_8JSObjectEEENS4_INS0_6ObjectEEE
   7: _ZN2v88internal10ErrorUtils17GetFormattedStackEPNS0_7IsolateENS0_6HandleINS0_8JSObjectEEE
   8: _ZN2v88internal9Accessors16ErrorStackGetterERKNS_20FunctionCallbackInfoINS_5ValueEEE
   9: _ZN2v88internal25FunctionCallbackArguments4CallENS0_6TaggedINS0_20FunctionTemplateInfoEEE
  10: _ZN2v88internal8Builtins17InvokeApiFunctionEPNS0_7IsolateEbNS0_6HandleINS0_20FunctionTemplateInfoEEENS4_INS0_6ObjectEEEiPS8_NS4_INS0_10HeapObjectEEE
  11: _ZN2v88internal6Object23GetPropertyWithAccessorEPNS0_14LookupIteratorE
  12: _ZN2v88internal6Object11GetPropertyEPNS0_14LookupIteratorEb
  13: _ZN2v88internal7Runtime17GetObjectPropertyEPNS0_7IsolateENS0_6HandleINS0_6ObjectEEES6_S6_Pb
  14: _ZN2v86Object3GetENS_5LocalINS_7ContextEEENS1_INS_5ValueEEE
  15: _ZN12v8_inspector12_GLOBAL__N_119descriptionForErrorEN2v85LocalINS1_7ContextEEENS2_INS1_6ObjectEEENS0_9ErrorTypeE
  16: _ZN12v8_inspector11ValueMirror6createEN2v85LocalINS1_7ContextEEENS2_INS1_5ValueEEE
  17: _ZN12v8_inspector14InjectedScript18wrapEvaluateResultEN2v810MaybeLocalINS1_5ValueEEERKNS1_8TryCatchERKNS_8String16ERKNS_11WrapOptionsEbPNSt2Cr10unique_ptrINS_8protocol7Runtime12RemoteObjectENSE_14default_deleteISI_EEEEPN8v8_crdtp6detail8PtrMaybeINSH_16ExceptionDetailsEEE
  18: _ZN12v8_inspector19V8DebuggerAgentImpl19evaluateOnCallFrameERKNS_8String16ES3_N8v8_crdtp6detail10ValueMaybeIS1_EENS6_IbEES8_S8_S8_S8_NS6_IdEEPNSt2Cr10unique_ptrINS_8protocol7Runtime12RemoteObjectENSA_14default_deleteISE_EEEEPNS5_8PtrMaybeINSD_16ExceptionDetailsEEE
  19: _ZN12v8_inspector8protocol8Debugger20DomainDispatcherImpl19evaluateOnCallFrameERKN8v8_crdtp12DispatchableE
  20: _ZN8v8_crdtp14UberDispatcher14DispatchResult3RunEv
  21: _ZN12v8_inspector22V8InspectorSessionImpl23dispatchProtocolMessageENS_10StringViewE
  22: deno_core::inspector::JsRuntimeInspector::poll_sessions
  23: v8_inspector__V8InspectorClient__BASE__runMessageLoopOnPause
  24: _ZN12v8_inspector10V8Debugger18handleProgramBreakEN2v85LocalINS1_7ContextEEENS2_INS1_5ValueEEERKNSt2Cr6vectorIiNS7_9allocatorIiEEEENS1_4base7EnumSetINS1_5debug11BreakReasonEiEENSG_13ExceptionTypeEb
  25: _ZN12v8_inspector10V8Debugger15ExceptionThrownEN2v85LocalINS1_7ContextEEENS2_INS1_5ValueEEES6_bNS1_5debug13ExceptionTypeE
  26: _ZN2v88internal5Debug11OnExceptionENS0_6HandleINS0_6ObjectEEENS0_11MaybeHandleINS0_9JSPromiseEEENS_5debug13ExceptionTypeE
  27: _ZN2v88internal5Debug7OnThrowENS0_6HandleINS0_6ObjectEEE
  28: _ZN2v88internal7Isolate5ThrowENS0_6TaggedINS0_6ObjectEEEPNS0_15MessageLocationE
  29: _ZN2v88internal17Runtime_WasmThrowEiPmPNS0_7IsolateE
  30: Builtins_WasmCEntry
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lucacasonato** [comment]
I can see in the code where it is going wrong, but I can not reproduce it. Could you share the full reproduction (doesn't have to be minimized)?

**Comment by hgruniaux** [comment]
I tried to reproduce it, but I lost the original file.
However, I still crash Deno (with the attached file, not minified). I'm not sure if this is the same bug.
```
Platform: linux x86_64
Version: 1.45.5
Args: ["deno", "run", "--allow-read", "--inspect-wait", "runtime/Wlib/runtime.mjs", "test.wasm"]

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.299.0/error.rs:1245:36:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: deno_core::error::format_location
   5: <extern "C" fn(A0,A1,A2) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
   6: _ZN2v88internal10ErrorUtils16FormatStackTraceEPNS0_7IsolateENS0_6HandleINS0_8JSObjectEEENS4_INS0_6ObjectEEE
   7: _ZN2v88internal10ErrorUtils17GetFormattedStackEPNS0_7IsolateENS0_6HandleINS0_8JSObjectEEE
   8: _ZN2v88internal9Accessors16ErrorStackGetterERKNS_20FunctionCallbackInfoINS_5ValueEEE
   9: _ZN2v88internal25FunctionCallbackArguments4CallENS0_6TaggedINS0_20FunctionTemplateInfoEEE
  10: _ZN2v88internal8Builtins17InvokeApiFunctionEPNS0_7IsolateEbNS0_6HandleINS0_20FunctionTemplateInfoEEENS4_INS0_6ObjectEEEiPS8_NS4_INS0_10HeapObjectEEE
  11: _ZN2v88internal6Object23GetPropertyWithAccessorEPNS0_14LookupIteratorE
  12: _ZN2v88internal6Object11GetPropertyEPNS0_14LookupIteratorEb
  13: _ZN2v88internal7Runtime17GetObjectPropertyEPNS0_7IsolateENS0_6HandleINS0_6ObjectEEES6_S6_Pb
  14: _ZN2v86Object3GetENS_5LocalINS_7ContextEEENS1_INS_5ValueEEE
  15: _ZN12v8_inspector12_GLOBAL__N_119descriptionForErrorEN2v85LocalINS1_7ContextEEENS2_INS1_6ObjectEEENS0_9ErrorTypeE
  16: _ZN12v8_inspector11ValueMirror6createEN2v85LocalINS1_7ContextEEENS2_INS1_5ValueEEE
  17: _ZN12v8_inspector14InjectedScript18wrapEvaluateResultEN2v810MaybeLocalINS1_5ValueEEERKNS1_8TryCatchERKNS_8String16ERKNS_11WrapOptionsEbPNSt2Cr10unique_ptrINS_8protocol7Runtime12RemoteObjectENSE_14default_deleteISI_EEEEPN8v8_crdtp6detail8PtrMaybeINSH_16ExceptionDetailsEEE
  18: _ZN12v8_inspector19V8DebuggerAgentImpl19evaluateOnCallFrameERKNS_8String16ES3_N8v8_crdtp6detail10ValueMaybeIS1_EENS6_IbEES8_S8_S8_S8_NS6_IdEEPNSt2Cr10unique_ptrINS_8protocol7Runtime12RemoteObjectENSA_14default_deleteISE_EEEEPNS5_8PtrMaybeINSD_16ExceptionDetailsEEE
  19: _ZN12v8_inspector8protocol8Debugger20DomainDispatcherImpl19evaluateOnCallFrameERKN8v8_crdtp12DispatchableE
  20: _ZN8v8_crdtp14UberDispatcher14DispatchResult3RunEv
  21: _ZN12v8_inspector22V8InspectorSessionImpl23dispatchProtocolMessageENS_10StringViewE
  22: deno_core::inspector::JsRuntimeInspector::poll_sessions
  23: v8_inspector__V8InspectorClient__BASE__runMessageLoopOnPause
  24: _ZN12v8_inspector10V8Debugger18handleProgramBreakEN2v85LocalINS1_7ContextEEENS2_INS1_5ValueEEERKNSt2Cr6vectorIiNS7_9allocatorIiEEEENS1_4base7EnumSetINS1_5debug11BreakReasonEiEENSG_13ExceptionTypeEb
  25: _ZN12v8_inspector10V8Debugger21BreakProgramRequestedEN2v85LocalINS1_7ContextEEERKNSt2Cr6vectorIiNS5_9allocatorIiEEEENS1_4base7EnumSetINS1_5debug11BreakReasonEiEE
  26: _ZN2v88internal5Debug12OnDebugBreakENS0_6HandleINS0_10FixedArrayEEENS0_10StepActionENS_4base7EnumSetINS_5debug11BreakReasonEiEE
  27: _ZN2v88internal22Runtime_WasmDebugBreakEiPmPNS0_7IsolateE
  28: Builtins_WasmCEntry
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
[test.zip](https://github.com/user-attachments/files/16600360/test.zip)

**Comment by lucacasonato** [comment]
@hgruniaux Can you provide the full reproduction, including the JS file that imports this wasm file?

**Comment by hgruniaux** [comment]
I think the crash happened when double clicking on a WASM symbol. The JS file is below.

Also, sometimes I have a Hyper parsing error when using DevTools with the same file, it is quite random.

[runtime.zip](https://github.com/user-attachments/files/16601134/runtime.zip)

**Comment by lucacasonato** [comment]
Running this code I only get this error message, but no panic:

```
error: Uncaught (in promise) RuntimeError: dereferencing a null pointer
    at bigloo_strcmp_2520 (wasm://wasm/__runtime-011d1046:1:957676)
    at BGl_getenvz00zz__osz00_4503 (wasm://wasm/__runtime-011d1046:1:1157033)
    at BGl_toplevelzd2initzd2zz__paramz00 (wasm://wasm/__runtime-011d1046:1:1166730)
    at BGl_modulezd2initializa7ationz75zz__paramz00_4711 (wasm://wasm/__runtime-011d1046:1:1166077)
    at BGl_importedzd2moduleszd2initz00zz__r4_ports_6_10_1z00 (wasm://wasm/__runtime-011d1046:1:955700)
    at BGl_modulezd2initializa7ationz75zz__r4_ports_6_10_1z00_2103 (wasm://wasm/__runtime-011d1046:1:930932)
    at BGl_importedzd2moduleszd2initz00zz__r4_input_6_10_2z00 (wasm://wasm/__runtime-011d1046:1:870071)
    at BGl_modulezd2initializa7ationz75zz__r4_input_6_10_2z00 (wasm://wasm/__runtime-011d1046:1:852189)
    at BGl_importedzd2moduleszd2initz00zz__errorz00 (wasm://wasm/__runtime-011d1046:1:1094664)
    at BGl_modulezd2initializa7ationz75zz__errorz00_3574 (wasm://wasm/__runtime-011d1046:1:1073056)
```

Can you provide me with a reproduction in the form of:

1. Download these files
2. `deno run ...`
3. Connect Chrome inspector
4. Set a break point on line xxx
5. etc

**Comment by hgruniaux** [comment]
Sorry for my inaccurate information. I'll try to go into more detail here:
- Download the above `test.wasm` and `runtime.mjs` files and put them in the same folder
- `deno run --allow-read --inspect-wait runtime.mjs test.wasm`
- Connect Chrome inspector (I use the one in Microsoft Edge)
- No need for any break point. It should crash at startup (after the exception is uncaught).

If no such crash happens, then play with the devtools and the wasm file, and after a few actions, it should crash. Honestly, it seems to be quite random. The last two tries I crashed immediately (I didn't touch anything in the inspector), and the try just before I played about 30 seconds before crashing (I *went at the end of the WASM file in the inspector*).

**Comment by lucacasonato** [comment]
Thank you - I just managed to reproduce it. Looking into what is causing it.

**Comment by lucacasonato** [comment]
@hgruniaux Can you still reproduce the issue in the latest canary release? (`deno upgrade --canary`). I have so far only reproduced it twice, and have tried for upwards of 20 minutes now. It seems to somehow be machine or timing related, because I am having a real hard time reproducing reliably.

**Comment by hgruniaux** [comment]
It didn't crash in the last few days after upgrading to canary release. However, I don't think I triggered the same scenario as previously. But, at least I don't have crashes anymore.

Does the canary release contain a fix?

**Comment by lucacasonato** [comment]
It is likely yes - we did some refactors to the code that was causing panics. If it is not panicking anymore, let's consider it fixed. If you run into it again, can you re-open the issue?
