### ISSUE TITLE
gpujs doesn't work

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#25018]
Version: deno 1.46.0-rc.0+085058c (canary, x86_64-unknown-linux-gnu)

```ts
import { GPU } from "npm:gpu.js";
const gpu = new GPU();
const multiplyMatrix = gpu.createKernel(function (a, b) {
  let sum = 0;
  for (let i = 0; i < 512; i++) {
    sum += a[this.thread.y][i] * b[i][this.thread.x];
  }
  return sum;
}).setOutput([512, 512]);

const c = multiplyMatrix(a, b);
```

```
error: Uncaught (in promise) Error: Could not locate the bindings file. Tried:
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/build/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/build/Debug/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/build/Release/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/out/Debug/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/Debug/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/out/Release/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/Release/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/build/default/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/compiled/20.11.1/linux/x64/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/addon-build/release/install-root/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/addon-build/debug/install-root/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/addon-build/default/install-root/webgl.node
 → /home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/lib/binding/node-v108-linux-x64/webgl.node
    at bindings (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/bindings/1.5.0/bindings.js:126:9)
    at Object.<anonymous> (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/src/javascript/native-gl.js:1:294)
    at Object.<anonymous> (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/src/javascript/native-gl.js:15:4)
    at Module._compile (node:module:736:34)
    at Object.Module._extensions..js (node:module:757:11)
    at Module.load (node:module:655:32)
    at Function.Module._load (node:module:523:13)
    at Module.require (node:module:674:19)
    at require (node:module:798:16)
    at Object.<anonymous> (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/gl/5.0.3/src/javascript/webgl-rendering-context.js:4:58)
    ```

**Comment by sigmaSd** [comment]
`deno install` doesn't show any warnings/error, it would be great if it told me that there a scripts I can run with --allow-scripts
