### ISSUE TITLE
Support pglite

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#25028]
Running npm:pglite in Deno v1.45.5, I am seeing this error when making queries:

```sh
➜  ~ deno         
Deno 1.45.5
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> import { PGlite } from "npm:@electric-sql/pglite@0.2.0";
undefined
> const db = new PGlite("./pgdata");
undefined
> prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
> await db.query('create table test (id int);');
Uncaught TypeError: expected typed ArrayBufferView
    at Module.writeSync (ext:deno_io/12_io.js:122:15)
    at innerWriteSync (ext:deno_node/_fs/_fs_write.mjs:35:27)
    at Object.writeSync (ext:deno_node/_fs/_fs_write.mjs:53:12)
    at file:///home/alex/.cache/deno/npm/registry.npmjs.org/@electric-sql/pglite/0.2.0/dist/postgres.js:9:125306
    at Object.tryFSOperation (file:///home/alex/.cache/deno/npm/registry.npmjs.org/@electric-sql/pglite/0.2.0/dist/postgres.js:9:121629)
    at Object.write (file:///home/alex/.cache/deno/npm/registry.npmjs.org/@electric-sql/pglite/0.2.0/dist/postgres.js:9:125284)
    at Object.write (file:///home/alex/.cache/deno/npm/registry.npmjs.org/@electric-sql/pglite/0.2.0/dist/postgres.js:9:142636)
    at doWritev (file:///home/alex/.cache/deno/npm/registry.npmjs.org/@electric-sql/pglite/0.2.0/dist/postgres.js:9:216886)
    at _fd_write (file:///home/alex/.cache/deno/npm/registry.npmjs.org/@electric-sql/pglite/0.2.0/dist/postgres.js:9:218357)
    at <anonymous> (wasm://wasm/01c8086e:1:5297298)
```

This package works in Node.js and Bun, but not Deno.

I opened a separate issue in the pglite repository: https://github.com/electric-sql/pglite/issues/191

**Comment by nathanwhit** [comment]
This now gets farther, but still fails later with an incredibly cryptic error originating from WASM

```
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
error: Uncaught (in promise) RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (file:///Users/nathanwhit/Library/Caches/deno/npm/registry.npmjs.org/@electric-sql/pglite/0.2.0/dist/postgres.js:9:76250)
    at __abort_js (file:///Users/nathanwhit/Library/Caches/deno/npm/registry.npmjs.org/@electric-sql/pglite/0.2.0/dist/postgres.js:9:189060)
    at <anonymous> (wasm://wasm/01c8086e:1:5297547)
    at <anonymous> (wasm://wasm/01c8086e:1:1979957)
    at <anonymous> (wasm://wasm/01c8086e:1:1969165)
    at <anonymous> (wasm://wasm/01c8086e:1:2251556)
    at <anonymous> (wasm://wasm/01c8086e:1:2229558)
    at <anonymous> (wasm://wasm/01c8086e:1:2266472)
    at <anonymous> (wasm://wasm/01c8086e:1:3323992)
    at <anonymous> (wasm://wasm/01c8086e:1:5119845)
```

**Comment by alexgleason** [comment]
@nathanwhit I think this issue was closed by accident.

**Comment by nathanwhit** [comment]
> Hey, PGlite maintainer here, please let me know if there is anything I can do to help make this happen. I would love for us to have proper Deno support. (the published asked seems to somewhat work in in-memory mode)

Hello, thanks for the help!

> this is mostly outside our control without patching Emscripten, when you try to run PGlite from a local build, rather than the published package, you will get errors such as:

That issue with the local build is likely https://github.com/denoland/deno/issues/22655

Currently we only do node interop (exposing node globals) for published packages. So when you're using the published package, those process checks pass and `ENVIRONMENT_IS_NODE` will be true.

---

> @nathanwhit I think this issue was closed by accident.

I did some more debugging, and the issue ended up being a bug in my fix for the first issue (😅) and another bug in our handling of offsets in `fs.read`. That should be fixed now (https://github.com/denoland/deno/pull/25049), and now the original report works for me without errors.

```ts
import { PGlite } from "npm:@electric-sql/pglite";

const db = new PGlite("./pgdata");

const res = await db.query("create table test (id int);");
console.log(res);
```

```bash
❯ ./dev-deno run -A main.ts
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
{ rows: [], fields: [], affectedRows: 0 }
```

The fix will be in the next canary release (which should be published whenever CI finishes, usually ~90 min), and then in the next stable release.

For now I'll reopen this. Once the canary is published, I'll let you know so you can test it out and we can confirm whether this is fixed

**Comment by alexgleason** [comment]
@nathanwhit That's amazing, can't wait to test it!

**Comment by samwillis** [comment]
@nathanwhit thats all amazing, very excited that this is going to work.

Once we get this working I would like to add Deno to our CI so we can ensure we don't break it after all this hard work. Is there a way to trigger the node compat by tricking Deno into thinking it's a published package?

**Comment by alexgleason** [comment]
That is so awesome @nathanwhit, it's working perfectly on the canary:

![image](https://github.com/user-attachments/assets/3849a454-b587-4fe3-aeb6-51122c102c73)

Even works when I restart deno and repoen the directory. Thanks again!!

**Comment by maxmcd** [comment]
@samwillis fyi, this can be solved by setting the `--location` flag:

```
> Uncaught TypeError: Cannot read properties of undefined (reading 'pathname')
    at loadPackage (file:///Users/samwillis/Code/pglite/packages/pglite/dist/postgres.js:38:29)
    at file:///Users/samwillis/Code/pglite/packages/pglite/dist/postgres.js:441:7
    at file:///Users/samwillis/Code/pglite/packages/pglite/dist/postgres.js:3951:7
    at Dt.Tr (file:///Users/samwillis/Code/pglite/packages/pglite/dist/index.js:1:53885)
    at eventLoopTick (ext:core/01_core.js:168:7)
```
