### ISSUE TITLE
Different behavior for fetch call between Node.js & Deno

### ISSUE THREAD

**Issue by MiguelRipoll23** [denoland/deno#25082]
Version: Deno 1.45.5

Seems like Deno is handling differently the second fetch call and the server (router) thinks the user is unathenticated and ends up in a redirection loop. I

Code to reproduce (requires LiveBox router)
```
await login()
  .then((urn) => getConnectedDevices(urn))
  .catch((error) => {
    console.error("An error occurred:", error);
  });

async function login() {
  const bodyParams = new URLSearchParams({
    GO: "status.htm",
    pws: "md5 password here",
    usr: "admin",
    ui_pws: "password here",
    login: "acceso",
  });

  return fetch("http://livebox.home" + "/login.cgi", {
    method: "POST",
    body: bodyParams.toString(),
  })
    .then((response) => {
      console.log("#1", response);
      return response.text();
    })
    .then((responseText) => {
      return responseText.split("'")[1];
    })
    .catch((error) => {
      console.error("Login failed:", error);
    });
}

async function getConnectedDevices(urn) {
  const headers = {
    Cookie: `urn=${urn}`,
  };

  return fetch("http://livebox.home" + "/cgi/cgi_network_connected.js", {
    method: "GET",
    headers,
  })
    .then((response) => {
      console.log("#2", response);
    })
    .catch((error) => {
      console.error("Failed to get connected devices:", error);
    });
}
```

**Deno**
First fetch call:
```
{
  body: ReadableStream { locked: false },
  bodyUsed: false,
  headers: Headers {
    "cache-control": "no-cache,no-store,must-revalidate, post-check=0,pre-check=0",
    connection: "close",
    "content-language": "en",
    "content-type": "text/html",
    date: "Sun, 18 Aug 2024 16:14:12 GMT",
    expires: "0",
    pragma: "no-cache",
    server: "httpd"
  },
  ok: true,
  redirected: true,
  status: 200,
  statusText: "OK",
  url: "http://livebox.home/status.htm"
}
```
Second fetch call:

> Failed to get connected devices: TypeError: Fetch failed: Maximum number of redirects (20) reached
>     at ext:deno_fetch/26_fetch.js:370:25
>     at eventLoopTick (ext:core/01_core.js:168:7)
>     at async fetch (ext:deno_fetch/26_fetch.js:391:7)
>     at async file:///C:/Users/migue/Documents/GitHub/livebox-reporter/test.mjs:1:1

**Node.js**
```
Response {
  status: 200,
  statusText: 'Ok',
  headers: Headers {
    server: 'httpd',
    date: 'Sun, 18 Aug 2024 16:13:06 GMT',
    pragma: 'no-cache',
    'cache-control': 'no-cache,no-store,must-revalidate, post-check=0,pre-check=0',
    expires: '0',
    'content-type': 'text/html',
    'content-language': 'en',
    connection: 'close'
  },
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
  bodyUsed: false,
  ok: true,
  redirected: true,
  type: 'basic',
  url: 'http://livebox.home/status.htm'
}
Response {
  status: 200,
  statusText: 'Ok',
  headers: Headers {
    server: 'httpd',
    date: 'Sun, 18 Aug 2024 16:13:06 GMT',
    pragma: 'no-cache',
    'cache-control': 'no-cache,no-store,must-revalidate, post-check=0,pre-check=0',
    expires: '0',
    'content-type': 'text/javascript',
    cookie: 'urn=383213244bad3d16',
    'set-cookie': 'PATH=/; HttpOnly;',
    'content-language': 'en',
    connection: 'close'
  },
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
  bodyUsed: false,
  ok: true,
  redirected: false,
  type: 'basic',
  url: 'http://livebox.home/cgi/cgi_network_connected.js'
}
```

Browser:

![image](https://github.com/user-attachments/assets/00ce75ee-f7d0-466a-a7ee-190a61b0709c)

Thanks.

**Comment by MiguelRipoll23** [comment]
Another user reporting a similar scenerario: 
https://stackoverflow.com/questions/78285531/deno-fetch-post-not-working-as-expected

**Comment by lucacasonato** [comment]
Hey - without a more minimal reproduction (including a server we can actually hit), this is unfortunately impossible to fix, because we can not determine what difference there is between Deno and Node.

**Comment by kt3k** [comment]
@MiguelRipoll23 What was the 'urn' value in the first example in Deno?

**Comment by MiguelRipoll23** [comment]
It’s a token set by the router’s login page. I tried to obtain more information about what’s happening but unfortunately there’s no additional data I can provide.

Feel free to close the issue, if I see the problem in a way you can reproduce it I will reopen.

**Comment by DasKoebi** [comment]
I have a similar problem with deno (version: 2.06) and node. I want to download
a GitHub action job log from a recent run. I use the GitHub REST API for this:
[Download Job Logs](https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#download-job-logs-for-a-workflow-run)

### Test file

```js
const TOKEN = "your PAT";

const URL =
    "https://api.github.com/repos/{owner}/{repo}/actions/jobs/{job_id}/logs";

const myHeaders = new Headers();

myHeaders.append("Accept", "application/vnd.github.v3+json");
myHeaders.append("Authorization", `Bearer ${TOKEN}`);
myHeaders.append("X-GitHub-Api-Version", "2022-11-28");

const requestOptions = {
    method: "GET",
    headers: myHeaders,
    redirect: "follow",
};

fetch(
    URL,
    requestOptions,
)
    .then((response) => response.text())
    .then((result) => console.log(result))
    .catch((error) => console.error(error));
```

When I run this code in deno, I get the following error message:

```
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.
RequestId:<Request-ID>
Time:2024-11-12T08:13:13.6041229Z</Message></Error>
```

But if I execute the same file with Node, I get the log file.

After some testing, I realized that GitHub redirects to
`*.blob.core.windows.net`. And with the current [fetch spec (4.4.13)](https://fetch.spec.whatwg.org/#http-redirect-fetch:~:text=I.e.%2C%20the%20moment%20another%20origin%20is%20seen%20after%20the%20initial%20request%2C%20the%20%60Authorization%60%20header%20is%20removed.),
it looks like the fetch used in deno deletes the `Authorization` header for
cross origin redirects and node does not. Deno is spec conform here, but in my
opinion it doesn't make much sense on the server side.

**Comment by bartlomieju** [comment]
Closing this as working-as-intended.

The behavior @DasKoebi isolated is the key: Deno strips sensitive headers (`Authorization`, `Cookie`) when a redirect crosses origins. This is mandated by the WHATWG fetch spec ([HTTP-redirect fetch, §4.4](https://fetch.spec.whatwg.org/#http-redirect-fetch)) — the moment a redirect targets a different origin, those headers are dropped. Deno is spec-conformant here, and the Node difference has largely closed too: recent undici (Node's `fetch`) also strips these headers on cross-origin redirects, so both runtimes now behave the same per spec.

The original LiveBox redirect loop couldn't be narrowed to a minimal, hardware-independent reproduction, so there's nothing actionable left on it.

If anyone hits a case where headers are stripped on a **same-origin** redirect (which should *not* happen), please open a fresh issue with a minimal reproduction that doesn't require special hardware. Thanks all!
