### ISSUE TITLE
next.js dev server doesn't start

### ISSUE THREAD

**Issue by ry** [denoland/deno#25080]
Canary Deno 1.46.0-rc.0+35a17f3

```
/tmp/my-app# deno run dev
Task dev next dev
  ▲ Next.js 14.2.5
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1329ms
 ○ Compiling / ...
 ✓ Compiled / in 2.2s (532 modules)
 GET / 200 in 2385ms
TypeError: Invalid URL: '2'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
    at async file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/router-server.js:368:24)
    at async requestHandlerImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async ServerImpl.requestListener (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/start-server.js:141:13)
TypeError: Invalid URL: '5'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
    at async file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/router-server.js:368:24)
    at async requestHandlerImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async ServerImpl.requestListener (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/start-server.js:141:13)
TypeError: Invalid URL: '5'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
    at async file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/router-server.js:368:24)
    at async requestHandlerImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async ServerImpl.requestListener (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/lib/start-server.js:141:13)
TypeError: Invalid URL: '2'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
TypeError: Invalid URL: '5'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
TypeError: Invalid URL: '5'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
TypeError: Invalid URL: '5'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
TypeError: Invalid URL: 'g'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
TypeError: Invalid URL: 'g'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
TypeError: Invalid URL: '5'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
TypeError: Invalid URL: 'g'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
TypeError: Invalid URL: 'g'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at parseUrl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/shared/lib/router/utils/parse-url.js:17:23)
    at DevServer.handleRequestImpl (file:///private/tmp/my-app/node_modules/.deno/next@14.2.5/node_modules/next/dist/server/base-server.js:544:48)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
```

**Comment by marvinhagemeister** [comment]
Minimal reproduction:

```ts
import * as http from "node:http";

const server = http.createServer((req, res) => {
  // BUG: For some reason `req.url` is always exactly one character
  if (!req.url?.includes("foo/bar")) {
    throw new Error("fail");
  }
  return res.end();
});

server.listen(async () => {
  const addr = server.address()! as any;
  const res = await fetch(`http://${addr.address}:${addr.port}/foo/bar`);
  await res.text();
});
```
