### ISSUE TITLE
Feature request: Possibility to pass arguments to workers

### ISSUE THREAD

**Issue by franz101** [denoland/deno#25129]
Possibility to pass arguments to workers
```
const { isMainThread, workerData, Worker } = require("worker_threads");

if (isMainThread) {
  console.log(`Main thread: Process ID: ${process.pid}`);
  new Worker(__filename, {
    workerData: [7, 6, 2, 3],
  });
  new Worker(__filename, {
    workerData: [1, 3, 4, 3],
  });
} else {
  console.log(`Worker!, Process ID: ${process.pid}`);
  console.log(`${workerData} in sorted is ${workerData.sort()}`);
}

```
source:
https://github.com/officialgio/Worker-Threads-Sample-/blob/main/Threads/threads.js

**Comment by marvinhagemeister** [comment]
I'm not sure what the ask here is. The snippet works as expected:

```sh
Main thread: Process ID: 65469
Worker!, Process ID: 65469
7,6,2,3 in sorted is 2,3,6,7
Worker!, Process ID: 65469
1,3,4,3 in sorted is 1,3,3,4
```

**Comment by marvinhagemeister** [comment]
For me this prints the expected output:

```sh
Main thread: Process ID: 70762
Worker!, Process ID: 70762
7,6,2,3 in sorted is 2,3,6,7
Worker!, Process ID: 70762
1,3,4,3 in sorted is 1,3,3,4
```

I'm not sure what the ask here is. Can you elaborate what the missing feature is that you're looking for? I feel like the request here would be much more clear if there was a short explanation included.

**Comment by franz101** [comment]
```

import { isMainThread, workerData, Worker } from "node:worker_threads";

const filename = import.meta.resolve("./threads.js")
if (isMainThread) {
  console.log(`Main thread: Process ID: ${Deno.pid}`);
  new Worker(filename, {
    workerData: [7, 6, 2, 3],
  });
  new Worker(filename, {
    workerData: [1, 3, 4, 3],
  });
} else {
  console.log(`Worker!, Process ID: ${Deno.pid}`);
  console.log(`${workerData} in sorted is ${workerData.sort()}`);
}


```

Yes this works

but what about the normal worker:
```

import { isMainThread, workerData } from "node:worker_threads";

const filename = import.meta.resolve("./threads.js")
if (isMainThread) {
  console.log(`Main thread: Process ID: ${Deno.pid}`);
  new Worker(filename, { type: "module" },
   {
    workerData: [7, 6, 2, 3],
  }
)
} else {
  console.log(`Worker!, Process ID: ${Deno.pid}`);
  console.log(`${workerData} in sorted is ${workerData.sort()}`);
}

```

**Comment by franz101** [comment]
```
error: Uncaught (in worker "") (in promise) TypeError: Cannot read properties of null (reading 'sort')
  console.log(`${workerData} in sorted is ${workerData.sort()}`);
                                                       ^
   
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:168:7)
```

**Comment by bartlomieju** [comment]
This is not a bug, Web Worker API doesn't support passing data to workers in this way: https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker

**Comment by Mutefish0** [comment]
you can pass arguments with url query:

`main.ts`
```ts
new Worker(import.meta.resolve("./worker.ts?a=1"), {
  type: "module",
}); 
```

`worker.ts`
```ts
const url = new URL(import.meta.url);
console.log("a: ", url.searchParams.get("a"));
```

**Comment by lucacasonato** [comment]
As Bartek mentioned, this is working as intended.

**Comment by franz101** [comment]
thanks for helping out, the arguments actually do the job 👍
