### ISSUE TITLE
Bug: No named export `gql` in `graphq-tag` found

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25311]
Reported in Discord:  https://discord.com/channels/684898665143206084/1279102082452029520/1279102082452029520

## Steps to reproduce

Run this snippet:

```ts
import { gql } from "npm:graphql-tag@2.12.6";
console.log(gql);
```

Output:

```sh
error: Uncaught SyntaxError: The requested module 'npm:graphql-tag@2.12.6' does not provide an export named 'gql'
import { gql } from "npm:graphql-tag@2.12.6";
         ^
    at <anonymous> (file:///Users/marvinh/dev/test/deno-graphql-tag/main.ts:1:10)
```

The problem occurs because Deno picks the wrong entry point.

```jsonc
  "main": "./main.js", // <- deno picks this one
  "module": "./lib/index.js", // <- ...but it should have picked this
  "jsnext:main": "./lib/index.js",
```

Version: Deno 1.46.2+d71eebb

**Comment by dsherret** [comment]
> The problem occurs because Deno picks the wrong entry point.

Deno is picking the same entry point as Node. I believe that's correct. I think probably there is something wrong with the cjs export analysis.

**Comment by igl** [comment]
The module is clearly cjs and re-exports a function from a UMD module

```js
module.exports = require('./lib/graphql-tag.umd.js').gql;
```

- `gql` is a function that has a "default" property that is referencing itself.
- the bundler also adds this prop on the `gql` function `Object.defineProperty(exports, '__esModule', { value: true });`


They use roll-up to generate it and it has been 3 years since the last update. These hybrid packages make me mad.

**Comment by jlsnow301** [comment]
We just upgraded to apollo v4 and our deno branch is getting this error, could this be related? @bartlomieju 
```
Error: Failed to load external module @apollo/client-6729fda47ea2d428: SyntaxError: The requested module 'graphql-tag' does not provide an export named 'disableExperimentalFragmentVariables' at file:///home/runner/work/{OURORG}/{OURAPP}/node_modules/.deno/@apollo+client@4.2.0/node_modules/@apollo/client/core/index.js:185:3
    at Context.externalImport [as y] (.next/server/chunks/ssr/[turbopack]_runtime.js:607:15)
    at async (.next/server/chunks/ssr/[root-of-the-server]__10a2~_9._.js:1:273)
```

**Comment by bartlomieju** [comment]
@jlsnow301 Yes, this is the same root cause. graphql-tag's main entry is `module.exports = require("./lib/index.js").gql`, where the inner file is a UMD bundle that attaches its named exports (`gql`, `disableExperimentalFragmentVariables`, `resetCaches`, etc.) inside the factory IIFE. Our static analysis couldn't see those attachments, so the wrapper ended up advertising no named exports at all, which is why `@apollo/client` fails to import `disableExperimentalFragmentVariables` from it.

#34689 fixes this: when the member's attached names can't be determined statically, we now fall back to re-exporting the inner module wholesale (matching Node's behavior for `require(X).Y`), so the full set of graphql-tag's named exports comes through again. Should land soon.
