### ISSUE TITLE
[webgpu] backend not found when use onnxruntime-web

### ISSUE THREAD

**Issue by jlucaso1** [denoland/deno#25397]
Version: Deno 1.46.2

```ts
import { InferenceSession } from "npm:onnxruntime-web";

const modelFile = await Deno.readFile("./model.onnx");

InferenceSession.create(modelFile, {
  executionProviders: ["webgpu"],
});
```
`DENO_FUTURE=1 deno run -A main.ts`

The error:
```
error: Uncaught (in promise) Error: no available backend found. ERR: [webgpu] backend not found.
    at resolveBackendAndExecutionProviders (file:///home/jlucaso/.cache/deno/npm/registry.npmjs.org/onnxruntime-common/1.19.0/dist/esm/backend-impl.js:120:15)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Function.create (file:///home/jlucaso/.cache/deno/npm/registry.npmjs.org/onnxruntime-common/1.19.0/dist/esm/inference-session-impl.js:180:52)
```

**Comment by wesbos** [comment]
Looks like the upstream issue was fixed yesterday.

Running Deno canary deno 2.1.2+8626ec7 and also trying to. use Transformers.js with WebGPU, seems it's still looking 

Still getting and error:

error: Uncaught (in promise) Error: Unsupported device: "webgpu". Should be one of: cpu.

Does this mean transformers.js needs to update onnx runtime? cc @xenova

**Comment by bartlomieju** [comment]
**Still reproducible on Deno 2.7.4 (2026-03-09)**

**Root cause:** The `onnxruntime-web` package's `exports` map has a `"node"` condition that Deno matches:

```json
".": {
  "node": { "import": "./dist/ort.node.min.mjs" },
  "import": { "default": "./dist/ort.bundle.min.mjs" }
}
```

Deno resolves the `"node"` condition (built-in, always matched), which points to `ort.node.min.mjs` — a build that does **not** register the webgpu backend. The browser builds (`ort.wasm.mjs`, `ort.webgpu.mjs`, etc.) do register it.

The `--conditions` flag can't help here since it only adds custom conditions — `"node"` is a built-in condition that always takes priority.

**Workaround:** Use the `/webgpu` subpath export directly:

```ts
import { InferenceSession } from "npm:onnxruntime-web/webgpu";

const modelFile = await Deno.readFile("./model.onnx");
const session = await InferenceSession.create(modelFile, {
  executionProviders: ["webgpu"],
});
```

This resolves to `ort.webgpu.min.mjs` which correctly registers the webgpu backend. Confirmed working on Deno 2.7.4 with `--unstable-webgpu`.
