### ISSUE TITLE
Drizzle-kit with libsql client behaves differently on deno

### ISSUE THREAD

**Issue by cotyhamilton** [denoland/deno#25476]
When running drizzle-kit with deno it appears that `@libsql/client/web` is being resolved instead of `@libsql/client`

[turso doc with warning about diff clients](https://docs.turso.tech/sdk/ts/reference#local-development)

versions:
```
deno 1.46.3 (stable, release, aarch64-apple-darwin)
v8 12.9.202.5-rusty
typescript 5.5.2
```

## Repro

```bash
npm init -y
npm i drizzle-orm @libsql/client
npm i -D drizzle-kit
touch drizzle.config.js schema.js
```

```js
// drizzle.config.js
import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: "./schema.js",
  out: "./migrations",
  dialect: "sqlite",
  dbCredentials: {
    url: "file:./db.sqlite",
  },
});
```

```bash
# generate migrations (will be empty but this step is needed)
npx drizzle-kit generate
# or
deno run -A npm:drizzle-kit generate
```

**node/npm 👍**

```bash
npx drizzle-kit migrate

No config path provided, using default 'drizzle.config.js'
Reading config file '/Users/cotyhamilton/dev/drizzle-test/drizzle.config.js'
```

**deno 👎**

```bash
deno run -A npm:drizzle-kit migrate

No config path provided, using default 'drizzle.config.js'
Reading config file '/Users/cotyhamilton/dev/drizzle-test/drizzle.config.js'
LibsqlError: URL_SCHEME_NOT_SUPPORTED: The client that uses Web standard APIs supports only "libsql:", "wss:", "ws:", "https:" and "http:" URLs, got "file:". For more information, please read https://github.com/libsql/libsql-client-ts#supported-urls
    at _createClient (file:///Users/cotyhamilton/dev/drizzle-test/node_modules/@libsql/client/lib-esm/web.js:19:15)
    at createClient (file:///Users/cotyhamilton/dev/drizzle-test/node_modules/@libsql/client/lib-esm/web.js:8:12)
    at connectToSQLite (file:///Users/cotyhamilton/dev/drizzle-test/node_modules/.deno/drizzle-kit@0.24.2/node_modules/drizzle-kit/bin.cjs:72100:26)
    at async Object.handler (file:///Users/cotyhamilton/dev/drizzle-test/node_modules/.deno/drizzle-kit@0.24.2/node_modules/drizzle-kit/bin.cjs:83589:39)
    at async run (file:///Users/cotyhamilton/dev/drizzle-test/node_modules/.deno/drizzle-kit@0.24.2/node_modules/drizzle-kit/bin.cjs:82063:7) {
  code: "URL_SCHEME_NOT_SUPPORTED",
  rawCode: undefined,
  name: "LibsqlError"
}
```

The same issue occurs if you just use `deno` for all steps instead of npm/npx

## Additional

This happens only when using a file url, other schemes work as expected in deno (since `@libsql/client/web` client being used)

I have no assumption on what is happening here, and I recognize it's possible the issue lives entirely within drizzle-kit, but wanted to make issue here since it possibly deals with node compat

**Comment by cotyhamilton** [comment]
Nvm 🤦🏻‍♀️

Issue is in libsql, I didn't even know these package.json options existed

<img width="461" alt="Screenshot 2024-09-05 at 7 13 52 PM" src="https://github.com/user-attachments/assets/354931a2-2e54-4185-943c-927b5c1aa7e2">

https://github.com/wintercg/admin/issues/36
