### ISSUE TITLE
deno fails to run puppeteer

### ISSUE THREAD

**Issue by begoon** [denoland/deno#25528]
Version: Deno 1.46.3

index.ts:
```typescript
import puppeteer from "puppeteer";

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto("https://jsr.io");
await page.pdf({ path: "example.pdf", format: "A4" });

await browser.close();
```

package.json:
```json
{ "dependencies": { "puppeteer": "^23.3.0" } }
```

```sh
deno run -A index.ts
```

```txt
Warning: Not implemented: ClientRequest.options.createConnection
error: Uncaught (in promise) TypeError: fileHandle.writeFile is not a function
    at getReadableAsTypedArray (file:///Users/alexander/github/tmpz/puppeteer/node_modules/.deno/puppeteer-core@23.3.0/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:154:34)
    at eventLoopTick (ext:core/01_core.js:214:9)
    at async CdpPage.pdf (file:///Users/alexander/github/tmpz/puppeteer/node_modules/.deno/puppeteer-core@23.3.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:825:28)
    at async file:///Users/alexander/github/tmpz/puppeteer/index.ts:6:1

```

However:

```sh
bun index.ts
```

works.

**Comment by kt3k** [comment]
Looks like `FileHandle` class misses `writeFile` method (and also many others such as `appendFile`, `chmod`, `chown`, `createReadStream`, etc), and that causes the above error.

https://github.com/denoland/deno/blob/c4d088863e93b70fa0729f326ad14376ca90b0a6/ext/node/polyfills/internal/fs/handle.ts#L27

I'll work on this issue.

**Comment by nitasn** [comment]
Same here (macOS M1), though I got a different error.

```
import puppeteer from "npm:puppeteer";
await puppeteer.launch();
```

$ deno -A code.ts
error: Uncaught (in promise) Error: Could not find Chrome (ver. 131.0.6778.87). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /Users/nitsan/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///Users/nitsan/Library/Caches/deno/npm/registry.npmjs.org/puppeteer-core/23.10.3/lib/esm/puppeteer/node/BrowserLauncher.js:266:27)
    at ChromeLauncher.computeLaunchArguments (file:///Users/nitsan/Library/Caches/deno/npm/registry.npmjs.org/puppeteer-core/23.10.3/lib/esm/puppeteer/node/ChromeLauncher.js:85:24)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async ChromeLauncher.launch (file:///Users/nitsan/Library/Caches/deno/npm/registry.npmjs.org/puppeteer-core/23.10.3/lib/esm/puppeteer/node/BrowserLauncher.js:45:28)
    at async file:///Users/nitsan/Desktop/fun/code.ts:3:1

**Comment by kt3k** [comment]
`npm:puppeteer` depends on lifecycle script for downloading Chrome. You first need to enable lifecycle script by setting the below in deno.json:

```
{
  "nodeModulesDir": "auto"
}
```

Then you need to run the command:

```
deno install --allow-scripts=npm:puppeteer@23.4.0
```

(The version number may vary. This command should appear in the error message when `"nodeModulesDir": "auto"` is set)

This command should download Chrome at appropriate path, and should make puppeteer dependency work
