### ISSUE TITLE
`process.stdout` should be an instance of `node:tty` `WriteStream`

### ISSUE THREAD

**Issue by nathanwhit** [denoland/deno#25602]
There's code that checks whether stdout is a tty by doing an instanceof check, e.g. in angular: https://github.com/angular/angular-cli/blob/d66aaa3ca458e05b535bec7c1dcb98b0e9c5202e/packages/angular/cli/src/utilities/color.ts#L14-L16

**Comment by vteivans** [comment]
I'm having the same issue running NestJS with Deno: 
```
Watcher File change detected! Restarting!
Warning experimentalDecorators compiler option is deprecated and may be removed at any time
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'write')
    at .../my_project/node_modules/.deno/@nestjs+common@10.4.4/node_modules/@nestjs/common/services/console-logger.service.js:132:50
    at Array.forEach (<anonymous>)
    at ConsoleLogger.printMessages (.../my_project/node_modules/.deno/@nestjs+common@10.4.4/node_modules/@nestjs/common/services/console-logger.service.js:126:18)
    at ConsoleLogger.error (.../my_project/node_modules/.deno/@nestjs+common@10.4.4/node_modules/@nestjs/common/services/console-logger.service.js:52:14)
    at Logger.error (.../my_project/node_modules/.deno/@nestjs+common@10.4.4/node_modules/@nestjs/common/services/logger.service.js:43:29)
    at Logger.descriptor.value (.../my_project/node_modules/.deno/@nestjs+common@10.4.4/node_modules/@nestjs/common/services/logger.service.js:163:27)
    at loadAdapter (.../my_project/node_modules/.deno/@nestjs+core@10.4.4/node_modules/@nestjs/core/helpers/load-adapter.js:12:16)
    at NestFactoryStatic.createHttpAdapter (.../my_project/node_modules/.deno/@nestjs+core@10.4.4/node_modules/@nestjs/core/nest-factory.js:164:67)
    at NestFactoryStatic.create (.../my_project/node_modules/.deno/@nestjs+core@10.4.4/node_modules/@nestjs/core/nest-factory.js:36:21)
    at bootstrap (.../my_project/main.ts:11:33)
Watcher Process failed. Restarting on file change...
```
