### ISSUE TITLE
Bug in deno, trying to create a Next.js project using deno on OpenBSD 7.5

### ISSUE THREAD

**Issue by wesley974** [denoland/deno#25621]
Hi,

I'm trying Deno on OpenBSD 7.5.
Below the sequence to reproduce the bug:

```
test# deno run -A npm:create-next-app@latest my-next-app
✔ Would you like to use TypeScript? … No / Yes
✔ Would you like to use ESLint? … No / Yes
✔ Would you like to use Tailwind CSS? … No / Yes
✔ Would you like to use `src/` directory? … No / Yes
✔ Would you like to use App Router? (recommended) … No / Yes
✔ Would you like to customize the default import alias (@/*)? … No / Yes
Creating a new Next.js app in /root/test/my-next-app.

Using npm.

Initializing project with template: app


Installing dependencies:
- react
- react-dom
- next


============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: openbsd x86_64
Version: 1.36.4
Args: ["deno", "run", "-A", "npm:create-next-app@latest", "my-next-app"]

thread 'main' panicked at runtime/ops/os/mod.rs:67:40:
called `Result::unwrap()` on an `Err` value: Error { kind: Uncategorized, message: "no current exe available (short)" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And with RUST_BACKTRACE=full:

```
test# RUST_BACKTRACE=full deno run -A npm:create-next-app@latest my-next-app
✔ Would you like to use TypeScript? … No / Yes
✔ Would you like to use ESLint? … No / Yes
✔ Would you like to use Tailwind CSS? … No / Yes
✔ Would you like to use `src/` directory? … No / Yes
✔ Would you like to use App Router? (recommended) … No / Yes
✔ Would you like to customize the default import alias (@/*)? … No / Yes
Creating a new Next.js app in /root/test/my-next-app.

Using npm.

Initializing project with template: app


Installing dependencies:
- react
- react-dom
- next


============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: openbsd x86_64
Version: 1.36.4
Args: ["deno", "run", "-A", "npm:create-next-app@latest", "my-next-app"]

thread 'main' panicked at runtime/ops/os/mod.rs:67:40:
called `Result::unwrap()` on an `Err` value: Error { kind: Uncategorized, message: "no current exe available (short)" }
stack backtrace:
   0:      0xc112804f4cd - <unknown>
   1:      0xc112806cf11 - <unknown>
   2:      0xc1128010d24 - <unknown>
   3:      0xc112804f2a3 - <unknown>
   4:      0xc1128011ae7 - <unknown>
   5:      0xc1128011750 - <unknown>
   6:      0xc1124f2aae8 - <unknown>
   7:      0xc112801218c - <unknown>
   8:      0xc112804fb97 - <unknown>
   9:      0xc112804f70d - <unknown>
  10:      0xc1128011d27 - <unknown>
  11:      0xc11280732aa - <unknown>
  12:      0xc1128073f5a - <unknown>
  13:      0xc1125a8f72e - <unknown>
  14:      0xc1125a8ef9b - <unknown>
  ```
  
If someone can help me get it working.

Merci!

**Comment by nathanwhit** [comment]
Hello!

It looks like the version of deno you're using is fairly old (released over a year ago). I'd suggest upgrading to the latest version (`deno upgrade`) and trying again.

**Comment by littledivy** [comment]
OpenBSD is not officially supported so `deno upgrade` probably won't work. You can upgrade to the [latest port](https://github.com/openbsd/ports/blob/4c85c4c08f37ac7f0fdf778dab229e9902bea9e2/lang/deno/Makefile#L9) (it seems to be at 1.45)

That said, the port has several patches on top of deno and v8. I would open an issue on their tracker.

**Comment by wesley974** [comment]
I tried installing the last OpenBSD Snapshots (actually: 7.6-beta)

```
test# uname -a
OpenBSD test.local 7.6 GENERIC#306 amd64
test# deno run -A npm:create-next-app@latest my-next-app
ld.so: deno: can't load library 'libonig.so.8.0'
Killed
test# pkg_add oniguruma
quirks-7.49 signed on 2024-09-13T15:15:19Z
oniguruma-6.9.9: ok
test# ls /usr/local/lib/libonig.so.8.0
/usr/local/lib/libonig.so.8.0
test# deno run -A npm:create-next-app@latest my-next-app
error: Uncaught TypeError: Failed to get cpu info
    at Object.cpus (node:os:63:10)
    at Object.423 (file:///root/.cache/deno/npm/registry.npmjs.org/create-next-app/14.2.11/dist/index.js:33:19721)
    at __nccwpck_require__ (file:///root/.cache/deno/npm/registry.npmjs.org/create-next-app/14.2.11/dist/index.js:73:59379)
    at Object.8695 (file:///root/.cache/deno/npm/registry.npmjs.org/create-next-app/14.2.11/dist/index.js:33:4682)
    at __nccwpck_require__ (file:///root/.cache/deno/npm/registry.npmjs.org/create-next-app/14.2.11/dist/index.js:73:59379)
    at Module.8776 (file:///root/.cache/deno/npm/registry.npmjs.org/create-next-app/14.2.11/dist/index.js:73:35050)
    at __nccwpck_require__ (file:///root/.cache/deno/npm/registry.npmjs.org/create-next-app/14.2.11/dist/index.js:73:59379)
    at file:///root/.cache/deno/npm/registry.npmjs.org/create-next-app/14.2.11/dist/index.js:73:60243
    at Object.<anonymous> (file:///root/.cache/deno/npm/registry.npmjs.org/create-next-app/14.2.11/dist/index.js:73:60287)
    at Object.<anonymous> (file:///root/.cache/deno/npm/registry.npmjs.org/create-next-app/14.2.11/dist/index.js:74:4)
```
🙄

**Comment by littledivy** [comment]
That code is not from this repo. It is part of a patch in the above mentioned port https://github.com/openbsd/ports/blob/4c85c4c08f37ac7f0fdf778dab229e9902bea9e2/lang/deno/patches/patch-ext_node_ops_os_cpus_rs#L8-L12 so please open an issue with them.

Happy to accept PRs if they want to upstream the patches.

**Comment by VlkrS** [comment]
> That code is not from this repo. It is part of a patch in the above mentioned port https://github.com/openbsd/ports/blob/4c85c4c08f37ac7f0fdf778dab229e9902bea9e2/lang/deno/patches/patch-ext_node_ops_os_cpus_rs#L8-L12 so please open an issue with them.
> 
> Happy to accept PRs if they want to upstream the patches.

Indeed, I haven't gotten around to implement os.cpus() for OpenBSD yet. 
I usually send PRs for all patches that make sense to integrate upstream, but aside from that missing implementation, it's all workarounds to locate the current ```deno``` executable, and you probably don't want those.
