### ISSUE TITLE
 Unable to load pdf-parse.d.ts: The system cannot find the path specified. (os error 3)

### ISSUE THREAD

**Issue by mcgear** [denoland/deno#25682]
Version: Deno 1.46.3

I am doing some work with langchain, and trying to create a JSR package that contains calls to PDFLoader. THe issue i am running into is:
```
error: Uncaught Error: Unable to load C:\Users\MyUser\AppData\Local\deno\npm\registry.npmjs.org\@langchain\community\0.3.0\src\types\pdf-parse.d.ts: The system cannot find the path specified. (os error 3)
    at Object.getSourceFile (ext:deno_tsc/99_main_compiler.js:648:28)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126064:23)
    at findSourceFile (ext:deno_tsc/00_typescript.js:125980:20)
    at ext:deno_tsc/00_typescript.js:125929:22
    at getSourceFileFromReferenceWorker (ext:deno_tsc/00_typescript.js:125900:26)
    at processSourceFile (ext:deno_tsc/00_typescript.js:125927:5)
    at ext:deno_tsc/00_typescript.js:126221:7
    at forEach (ext:deno_tsc/00_typescript.js:2388:22)
    at processReferencedFiles (ext:deno_tsc/00_typescript.js:126220:5)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126123:9)
```
    
Previously, this was resolved by using a call to `import * as _parse from "npm:pdf-parse@1.1.1";` somewhere in the imports, but that no longer seems to fix the issue... at least it doesn't fix it in the context of tests or deno publish commands.

**Comment by nayeemrmn** [comment]
Can you share your code or a small reproduction? Namely the list of dependencies.

**Comment by nayeemrmn** [comment]
If this is still an issue, please provide some info to investigate with. Closing for now
