### ISSUE TITLE
`deno upgrade` results in error: Failed to unpack archive

### ISSUE THREAD

**Issue by thdoan** [denoland/deno#25703]
```
$ deno --version
deno 1.44.4 (release, x86_64-pc-windows-msvc)
v8 12.6.228.9
typescript 5.4.5
```

Steps to reproduce:

1. Download and unzip [Simple Wiki](https://github.com/lumeland/theme-simple-wiki/archive/refs/heads/main.zip) to any folder
2. Open terminal and navigate to folder in step 1
3. `deno task update-deps` -- output:

```
Task update-deps deno run -A 'https://deno.land/x/nudd@v0.2.8/cli.ts' update deno.json plugins.ts
A new release of Deno is available: 1.44.4 → 1.46.3 Run `deno upgrade` to install it.
deno.json
plugins.ts
error: Uncaught (in promise) TypeError: error sending request for url (https://cdn.deno.land/lume_markdown_plugins/meta/versions.json): error trying to connect: received corrupt message of type InvalidContentType
    return await readJson(url, (json) => {
           ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:170:12)
    at async fetch (ext:deno_fetch/26_fetch.js:391:7)
    at async DenoLand.versions (https://deno.land/x/nudd@v0.2.8/registry/denoland.ts:26:12)
    at async DenoLand.latestVersion (https://deno.land/x/nudd@v0.2.8/registry/utils.ts:25:22)
    at async updateCode (https://deno.land/x/nudd@v0.2.8/commands/update.ts:146:24)
    at async update (https://deno.land/x/nudd@v0.2.8/commands/update.ts:118:26)
    at async https://deno.land/x/nudd@v0.2.8/commands/update.ts:64:21
    at async Promise.all (index 1)
    at async run (https://deno.land/x/nudd@v0.2.8/commands/update.ts:63:3)
    at async https://deno.land/x/nudd@v0.2.8/cli.ts:120:3
```

4. `deno upgrade` -- output:

```
Looking up latest version
Found latest version 1.46.3
Downloading https://github.com/denoland/deno/releases/download/v1.46.3/deno-x86_64-pc-windows-msvc.zip
Deno is upgrading to version 1.46.3
deno.exe: Can't restore time
tar.exe: Error exit delayed from previous errors.
error: Failed to unpack archive.
```

I think I've reached a dead end.

**Comment by thdoan** [comment]
Update: I was finally able to upgrade Deno by manually downloading the exe and copying it over the existing `deno.exe`. At first, I wasn't able to copy over this file because of a file lock (probably same reason why it failed in the terminal), so I had to use another utility to remove the file system lock and reboot my PC before I was able to copy over this file.

**Comment by yazan-abdalrahman** [comment]
@thdoan 
I cannot reproduce it 
![image](https://github.com/user-attachments/assets/9b40cb97-4de1-42a5-b980-0e53c9e35d9e)

**Comment by bartlomieju** [comment]
This was fixed https://github.com/denoland/deno/pull/24926 and latest Deno releases don't suffer from this problem.
