### ISSUE TITLE
bug: `deno test --doc` incorrectly evaluates snippets

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#25718]
To reproduce:
1. `git clone https://github.com/denoland/std.git`
2. Run `deno test --doc log/mod.ts` using latest canary and get the following:
```
error: TS2304 [ERROR]: Cannot find name 'logger'.
    logger.debug(`running ${a} + ${b}`);
    ~~~~~~
    at file:///Users/asher/GitHub/std/log/mod.ts$121-131.ts:3:5

TS2304 [ERROR]: Cannot find name 'logger'.
    logger().debug(`running ${a} + ${b}`);
    ~~~~~~
    at file:///Users/asher/GitHub/std/log/mod.ts$78-95.ts:3:5

TS2304 [ERROR]: Cannot find name 'logger'.
    logger().debug(`running ${a} * ${b}`);
    ~~~~~~
    at file:///Users/asher/GitHub/std/log/mod.ts$78-95.ts:7:5
```

These same snippets run fine:
```ts
import { getLogger } from "@std/log";

const logger = getLogger("my-awesome-module");

export function sum(a: number, b: number) {
  logger.debug(`running ${a} + ${b}`); // no message will be logged, because getLogger() was called before log.setup()
  return a + b;
}
```
```ts
import { getLogger } from "@std/log";

function logger() {
  return getLogger("my-awesome-module");
}

export function sum(a: number, b: number) {
  logger().debug(`running ${a} + ${b}`);
  return a + b;
}

export function mult(a: number, b: number) {
  logger().debug(`running ${a} * ${b}`);
  return a * b;
}
```

Version: Deno 2.0.0-rc.3+c3bc692

**Comment by magurotuna** [comment]
Here's why this issue happens - this code snippet

```ts
import { getLogger } from "@std/log";

const logger = getLogger("my-awesome-module");

export function sum(a: number, b: number) {
  logger.debug(`running ${a} + ${b}`); // no message will be logged, because getLogger() was called before log.setup()
  return a + b;
}
```

is first virtually converted into

```ts
import { getLogger } from "@std/log";

Deno.test("<test-name>", async () => {
  const logger = getLogger("my-awesome-module");

  export function sum(a: number, b: number) {
    logger.debug(`running ${a} + ${b}`); // no message will be logged, because getLogger() was called before log.setup()
    return a + b;
  }
});
```

but right after this, the code converter (precisely speaking, swc) detects that `export function` is not on the top level scope, which violates the spec. So this ends up being turned into:

```ts
import { getLogger } from "@std/log";

Deno.test("<test-name>", async () => {
  const logger = getLogger("my-awesome-module");
});

export function sum(a: number, b: number) {
  logger.debug(`running ${a} + ${b}`); // no message will be logged, because getLogger() was called before log.setup()
  return a + b;
}
```

Therefore `logger` unintentionally becomes an undeclared variable in the body of `sum` function.

I'll try to consider what would be the best fix for this.

**Comment by iuioiua** [comment]
I suggest printing a warning for a snippet containing exported symbols. I don't think snippets would typically contain them. In the meantime, I'll remove the `export` keywords from `std`.

**Comment by magurotuna** [comment]
That sounds like a sensible solution, though I had started with the difference approach which can be seen #2570. The idea is to remove `export` to allow items annotated with `export` can be put inside `Deno.test` scope. What do you think about this approach?
