### ISSUE TITLE
deno 2 panick with rc3

### ISSUE THREAD

**Issue by daweijs** [denoland/deno#25740]
```bash
david@fixe ~/project_2 (main)> cat server.ts 
import { Hono } from "@hono/hono";
const app = new Hono();
app.get("/hello", (c) => c.json("hello world"));
export default app;


david@fixe ~/project_2 (main)> deno upgrade 2.0.0-rc.2
Current Deno version: v2.0.0-rc.2
Version 2.0.0-rc.2 is already installed
david@fixe ~/project_2 (main)> deno serve -A server.ts
deno serve: Listening on http://0.0.0.0:8000/
^C⏎                                                                                                                   


                                                                    
david@fixe ~/project_2 (main) [SIGINT]> deno upgrade 2.0.0-rc.3
Current Deno version: v2.0.0-rc.2
Downloading https://dl.deno.land/release/v2.0.0-rc.3/deno-x86_64-unknown-linux-gnu.zip
Deno is upgrading to version 2.0.0-rc.3
Upgraded successfully to Deno v2.0.0-rc.3 (release candidate)



david@fixe ~/project_2 (main)> deno serve -A server.ts
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 2.0.0-rc.3
Args: ["deno", "serve", "-A", "server.ts"]

thread 'main' panicked at cli/args/flags.rs:671:9:
assertion failed: value.is_none()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


david@fixe ~/project_2 (main) [1]> RUST_BACKTRACE=1 deno serve -A server.ts
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 2.0.0-rc.3
Args: ["deno", "serve", "-A", "server.ts"]

thread 'main' panicked at cli/args/flags.rs:671:9:
assertion failed: value.is_none()
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: deno::args::flags::PermissionFlags::to_options::handle_allow
   4: deno::args::CliOptions::permissions_options
   5: deno::factory::CliFactory::create_permissions_container
   6: deno::spawn_subcommand::{{closure}}
   7: <deno_unsync::tokio::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   8: tokio::runtime::task::raw::poll
   9: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.



david@fixe ~/project_2 (main)> RUST_BACKTRACE=full deno serve -A server.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 2.0.0-rc.3
Args: ["deno", "serve", "-A", "server.ts"]

thread 'main' panicked at cli/args/flags.rs:671:9:
assertion failed: value.is_none()
stack backtrace:
   0:     0x558bc72126d5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
   1:     0x558bc72450bb - core::fmt::write::hc6043626647b98ea
   2:     0x558bc720c71f - std::io::Write::write_fmt::h0d24b3e0473045db
   3:     0x558bc72124ae - std::sys_common::backtrace::print::h45eb8174d25a1e76
   4:     0x558bc7213f19 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
   5:     0x558bc7213cba - std::panicking::default_hook::hb5d3b27aa9f6dcda
   6:     0x558bc7842b56 - deno::setup_panic_hook::{{closure}}::h35e977bb4cd7d55f
   7:     0x558bc721458b - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
   8:     0x558bc72142cb - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
   9:     0x558bc7212b99 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
  10:     0x558bc7214037 - rust_begin_unwind
  11:     0x558bc7241fd3 - core::panicking::panic_fmt::ha02418e5cd774672
  12:     0x558bc724207c - core::panicking::panic::h6c780fb115b2371d
  13:     0x558bc75ffff4 - deno::args::flags::PermissionFlags::to_options::handle_allow::h03da6d1196c9415e
  14:     0x558bc761f36b - deno::args::CliOptions::permissions_options::h3f7008c7fcf2d680
  15:     0x558bc76319f2 - deno::factory::CliFactory::create_permissions_container::hf17dd936d26f9e59
  16:     0x558bc782c08a - deno::spawn_subcommand::{{closure}}::h2c42c43e12ab5ca9
  17:     0x558bc72584fa - <deno_unsync::tokio::task::MaskFutureAsSend<F> as core::future::future::Future>::poll::h683b54e429b9884b
  18:     0x558bc7485557 - tokio::runtime::task::raw::poll::h6efccdb12cd32784
  19:     0x558bc784478d - deno::main::h857dca3c96a303fc
  20:     0x558bc73525df - std::sys_common::backtrace::__rust_begin_short_backtrace::h8a6b6f592f5c5e49
  21:     0x558bc735a35d - std::rt::lang_start::{{closure}}::h96fd2c199829d241
  22:     0x558bc720069d - std::rt::lang_start_internal::hcee5ed89fc25829a
  23:     0x558bc78dab55 - main
  24:     0x7f2d1e4bf1ca - <unknown>
  25:     0x7f2d1e4bf28b - __libc_start_main
  26:     0x558bc5ba1029 - _start
  27:                0x0 - <unknown>
```

**Comment by bartlomieju** [comment]
Thanks for the report, we will fix it soon. In the meantime you can downgrade to rc2 to have it working: `deno upgrade v2.0.0-rc.2`
