### ISSUE TITLE
Deno test outputs error locations with file:// url format

### ISSUE THREAD

**Issue by sidesteps** [denoland/deno#25791]
Version: Deno 1.46.2

When running `deno test`
On test fail, the output is 
```
  throw new AssertionError(message);
        ^
    at assertEquals (https://deno.land/std@0.214.0/assert/assert_equals.ts:52:9)
    at file:///home/sstep/wif/serv/test/serv.test.js:174:9
```

Because of `file://` format of the error location, it is not usable as a 'click and go to location' string in editors.
For example in vim, you would press `gF` to get to the location of error. But because it is in `file://` format it messes it up as a location pointer.

Perhaps it is better to show paths without file:// qualifier?

**Comment by marvinhagemeister** [comment]
Related https://github.com/denoland/deno/issues/19261

**Comment by bartlomieju** [comment]
Revisiting this on current Deno (2.x). The behavior has partly changed since 1.46.2:

- The test-summary line now prints an editor-jumpable **relative** path, e.g. `failing => ./serv.test.js:174:9`.
- Stack frames still use the `file://` URL scheme, e.g. `at file:///home/.../serv.test.js:174:9`.

The `file://` scheme in stack frames is intentional and consistent with how Deno reports module locations everywhere else (it's how Deno identifies modules: remote, `jsr:`, `npm:`, and local all share one URL space). Most modern terminals (iTerm2, WezTerm, VS Code's integrated terminal, etc.) and editors recognize `file://` URLs as clickable links and handle the `:line:col` suffix fine, so "jump to location" works in the common case. The vim `gF` friction is real but specific to `'isfname'`/`'path'` handling and is usually solved with editor-side config rather than changing Deno's canonical location format.

Given the summary line already provides a plain relative path and the stack-frame format is deliberate, closing as not planned. Happy to reopen if there's a concrete editor/terminal where neither form is usable.
