### ISSUE TITLE
web cache API expirenation not work

### ISSUE THREAD

**Issue by Octo8080X** [denoland/deno#25795]
Version: Deno 1.46.3

It appears that the Web Cache API expiration date cannot be set.

Example

```ts
    export const cache = await caches.open("cache");
    
    const cached = await cache.match(req.url);
    if (cached) {
      console.log(`cache hit ${req.url}`);
      return cached;
    }

    const newResponse = new Response("text", {
      headers: { ...res.headers, "Expires": new Date(Date.now() + 10 * 1000).toUTCString(), },
    });

    await cache.put(req.url, newResponse.clone());

    return newResponse;
```

The cache does not disappear over time and hits forever.

**Comment by BlackAsLight** [comment]
What are the other headers in `res.header`? Specifically a Cache-Control header.

**Comment by 0f-0b** [comment]
[Relevant spec section](https://w3c.github.io/ServiceWorker/#cache-lifetimes).

**Comment by Octo8080X** [comment]
Test code is available.
There seems to be a similar problem with cli; neither Expires nor Cache-Control may be working.

```typescript
import { assertEquals } from "@std/assert";
import {
  describe,
  it,
  beforeEach,
} from "@std/testing/bdd";
import { FakeTime } from "@std/testing/time";

describe("Web cache API", () => {
  let cache: Cache;
  let cacheName: string

  beforeEach(async () => {
    cacheName = crypto.randomUUID();
    cache = await caches.open(cacheName);
   });

  it("no expires", async () => {
    const rand = crypto.randomUUID();
    await cache.put(`https://example.com/${rand}`, (new Response("Hello, world!")).clone());
    const res = await cache.match(`https://example.com/${rand}`)

    assertEquals(await res?.text(), "Hello, world!");
  })

  it("set Expires", async () => {
    using time = new FakeTime();
    const rand = crypto.randomUUID();
    await cache.put(`https://example.com/${rand}`, (new Response("Hello, world!",{
      headers: {
        "Expires": new Date(Date.now() + 3 * 1000).toUTCString(),
      } 
    })).clone());

    time.tick(1000000)
    const res = await cache.match(`https://example.com/${rand}`)

    assertEquals(res, undefined); // <= ERROR
  })

  it("set Cache-Control", async () => {
    using time = new FakeTime();
    const rand = crypto.randomUUID();
    await cache.put(`https://example.com/${rand}`, (new Response("Hello, world!",{
      headers: {
        "Cache-Control": "max-age=3",
      } 
    })).clone());

    time.tick(1000000)
    const res = await cache.match(`https://example.com/${rand}`)

    assertEquals(res, undefined); // <= ERROR
  })
})
```

```sh
 deno test
running 1 test from ./main_test.ts
Web cache API ...
  no expires ... ok (20ms)
  set Expires ... FAILED (12ms)
  set Cache-Control ... FAILED (6ms)
Web cache API ... FAILED (due to 2 failed steps) (40ms)

 ERRORS

Web cache API ... set Expires => https://jsr.io/@std/testing/1.0.3/_test_suite.ts:349:15
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   Response {
-     body: ReadableStream {
-       locked: false,
-     },
-     bodyUsed: false,
-     headers: Headers {
-       "content-type": "text/plain;charset=UTF-8",
-       expires: "Wed, 25 Sep 2024 15:13:15 GMT",
-     },
-     ok: true,
-     redirected: false,
-     status: 200,
-     statusText: "",
-     url: "",
-   }
+   undefined

  throw new AssertionError(message);
        ^
    at assertEquals (https://jsr.io/@std/assert/1.0.6/equals.ts:51:9)
    at Object.<anonymous> (file://hoge/test/test467-webcache/main_test.ts:38:5)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Function.runTest (https://jsr.io/@std/testing/1.0.3/_test_suite.ts:384:7)
    at async Function.runTest (https://jsr.io/@std/testing/1.0.3/_test_suite.ts:372:9)
    at async fn (https://jsr.io/@std/testing/1.0.3/_test_suite.ts:333:13)

Web cache API ... set Cache-Control => https://jsr.io/@std/testing/1.0.3/_test_suite.ts:349:15
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   Response {
-     body: ReadableStream {
-       locked: false,
-     },
-     bodyUsed: false,
-     headers: Headers {
-       "cache-control": "max-age=3",
-       "content-type": "text/plain;charset=UTF-8",
-     },
-     ok: true,
-     redirected: false,
-     status: 200,
-     statusText: "",
-     url: "",
-   }
+   undefined

  throw new AssertionError(message);
        ^
    at assertEquals (https://jsr.io/@std/assert/1.0.6/equals.ts:51:9)
    at Object.<anonymous> (file:///hoge/test/test467-webcache/main_test.ts:53:5)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Function.runTest (https://jsr.io/@std/testing/1.0.3/_test_suite.ts:384:7)
    at async Function.runTest (https://jsr.io/@std/testing/1.0.3/_test_suite.ts:372:9)
    at async fn (https://jsr.io/@std/testing/1.0.3/_test_suite.ts:333:13)

 FAILURES

Web cache API ... set Expires => https://jsr.io/@std/testing/1.0.3/_test_suite.ts:349:15
Web cache API ... set Cache-Control => https://jsr.io/@std/testing/1.0.3/_test_suite.ts:349:15

FAILED | 0 passed (1 step) | 1 failed (2 steps) (47ms)

error: Test failed
```
```

**Comment by tmcw** [comment]
Can confirm, using the Deno.caches interface at scale with max-age does expire old cache entries and eventually fills up `/tmp`.

**Comment by aod** [comment]
Bumped. It's kind of sad how it also was introduced **last year** for Deno Deploy but it seems it doesn't even work standalone with Deno itself. I'm new to this, did even work in the past? There aren't even tests in the codebase for it: https://github.com/denoland/deno/blob/1dd0db2e16f079424c42a4c06a51bc70d6e76df8/tests/unit/cache_api_test.ts. I can't understand how that's even possible. And of course, it's an open source project, there's only so much you can expect. I hope maintainers can take look at this soon.
