### ISSUE TITLE
Deno installation failed in WSL2.

### ISSUE THREAD

**Issue by Souvlaki42** [denoland/deno#25852]
Version: Deno 1.46.3
When trying to install this in WSL2 Ubuntu using the shell script I got this error:
```shell
Deno was installed successfully to ~/.deno/bin/deno
error: Uncaught (in promise) PermissionDenied: Permission denied (os error 13): stat '/mnt/c/Windows/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps/fish'
    at async Object.stat (ext:deno_fs/30_fs.js:420:15)
    at async ae (https://jsr.io/@deno/installer-shell-setup/0.2.2/bundled.esm.js:1:399)
    at async le (https://jsr.io/@deno/installer-shell-setup/0.2.2/bundled.esm.js:1:341)
    at async Z.exists (https://jsr.io/@deno/installer-shell-setup/0.2.2/bundled.esm.js:16:112)
    at async _t (https://jsr.io/@deno/installer-shell-setup/0.2.2/bundled.esm.js:27:473)
    at async Tt (https://jsr.io/@deno/installer-shell-setup/0.2.2/bundled.esm.js:27:539)
    at async Dt (https://jsr.io/@deno/installer-shell-setup/0.2.2/bundled.esm.js:30:543)
    at async https://jsr.io/@deno/installer-shell-setup/0.2.2/bundled.esm.js:30:575

```
I suspect it has to do with this function but I'm not sure tbh:
```bash
run_shell_setup() {
        $exe run -A jsr:@deno/installer-shell-setup/bundled "$deno_install"

}
```
Can someone help me?

**Comment by bartlomieju** [comment]
Sorry for the problem, we just updated the installation script and the error should be gone.

**Comment by Souvlaki42** [comment]
It works now. Thank you very much for fixing it so fast.
