### ISSUE TITLE
Uncaught Error: Not implemented: Pipe.prototype.listen - Windows

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [denoland/deno#25867]
Version: Deno 2.0.0-rc.5 (release candidate, release, x86_64-pc-windows-msvc)

When I run `deno run -A .\node_modules\nx\bin\nx.js serve projectName` 

I get the following error

```
detached processes are not currently supported on Windows
detached processes are not currently supported on Windows
detached processes are not currently supported on Windows
errorerror: : Uncaught Error: Not implemented: Pipe.prototype.listen - Windows
    at notImplemented (ext:deno_node/_utils.ts:9:9)
    at Pipe.listen (ext:deno_node/internal_binding/pipe_wrap.ts:144:7)
    at Server._setupListenHandle [as _listen2] (node:net:1178:28)
    at _listenInCluster (node:net:1012:12)
    at Server.listen (node:net:1278:7)
    at Object.<anonymous> (file:///<HOME>/deno-2-test/node_modules/.deno/nx@19.7.4/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:146:8)
    at Object.<anonymous> (file:///<HOME>/deno-2-test/node_modules/.deno/nx@19.7.4/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:160:4)
    at Module._compile (node:module:748:34)
    at Object.Module._extensions..js (node:module:767:10)
    at Module.load (node:module:665:32)Uncaught Error: Not implemented: Pipe.prototype.listen - Windows
    at notImplemented (ext:deno_node/_utils.ts:9:9)
    at Pipe.listen (ext:deno_node/internal_binding/pipe_wrap.ts:144:7)
    at Server._setupListenHandle [as _listen2] (node:net:1178:28)
    at _listenInCluster (node:net:1012:12)
    at Server.listen (node:net:1278:7)
    at Object.<anonymous> (file:///<HOME>/deno-2-test/node_modules/.deno/nx@19.7.4/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:146:8)
    at Object.<anonymous> (file:///<HOME>/deno-2-test/node_modules/.deno/nx@19.7.4/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:160:4)
    at Module._compile (node:module:748:34)
    at Object.Module._extensions..js (node:module:767:10)
    at Module.load (node:module:665:32)

error: Uncaught Error: Not implemented: Pipe.prototype.listen - Windows
    at notImplemented (ext:deno_node/_utils.ts:9:9)
    at Pipe.listen (ext:deno_node/internal_binding/pipe_wrap.ts:144:7)
    at Server._setupListenHandle [as _listen2] (node:net:1178:28)
    at _listenInCluster (node:net:1012:12)
    at Server.listen (node:net:1278:7)
    at Object.<anonymous> (file:///<HOME>/deno-2-test/node_modules/.deno/nx@19.7.4/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:146:8)
    at Object.<anonymous> (file:///<HOME>/deno-2-test/node_modules/.deno/nx@19.7.4/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:160:4)
    at Module._compile (node:module:748:34)
    at Object.Module._extensions..js (node:module:767:10)
    at Module.load (node:module:665:32)

 NX   Failed to start plugin worker.
```

Is that a compatibility issue, a nx issue or a windows issue?

**Comment by bartlomieju** [comment]
It's a compatibility issue. This API is not yet supported in Deno.

**Comment by sschneider-ihre-pvs** [comment]
ok. At least I got that question out of the way :D

**Comment by sschneider-ihre-pvs** [comment]
Is there a workaround or something?

**Comment by Ionaru** [comment]
Steps to reproduce:

1. Create a new simple NX workspace
```
deno run -A npm:create-nx-workspace@latest deno-nx --preset node-standalone --ci skip --docker false --framework none --interactive false
```

2. Navigate to the created folder
```
cd deno-nx
```

3. Run the program through NX
```
deno run start
```

Output will be the same as in the post above.

Error originates from the `server.listen(socketPath);` line here: https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/plugins/isolation/plugin-worker.ts#L134

A "support NX" issue was previously closed, but it seems like it doesn't work correctly yet: https://github.com/denoland/deno/issues/22966

**Comment by hinogi** [comment]
Just to update it is still around in 2.0.4

**Comment by Ionaru** [comment]
Using Deno `v2.1.1` and nx `v20.0.3` I am getting a different error, but the cause remains the same.

```
Task start nx serve
detached processes are not currently supported on Windows

 NX   Nx Daemon was not able to compute the project graph.

Log file with the error: C:\Users\<HOME>\Projects\deno-nx\.nx\workspace-data\d\daemon-error.log
Please file an issue at https://github.com/nrwl/nx
Nx Daemon is going to be disabled until you run "nx reset".

detached processes are not currently supported on Windows
detached processes are not currently supported on Windows
detached processes are not currently supported on Windows
detached processes are not currently supported on Windows
detached processes are not currently supported on Windows
error: Unable to load C:\Users\<HOME>\Projects\deno-nx\node_modules\nx\src\project-graph\plugins\isolation\plugin-worker

Caused by:
    The system cannot find the file specified. (os error 2)
error: Unable to load C:\Users\<HOME>\Projects\deno-nx\node_modules\nx\src\project-graph\plugins\isolation\plugin-worker

Caused by:
    The system cannot find the file specified. (os error 2)
error: Unable to load C:\Users\<HOME>\Projects\deno-nx\node_modules\nx\src\project-graph\plugins\isolation\plugin-worker

Caused by:
    The system cannot find the file specified. (os error 2)
error: Unable to load C:\Users\<HOME>\Projects\deno-nx\node_modules\nx\src\project-graph\plugins\isolation\plugin-worker

Caused by:
    The system cannot find the file specified. (os error 2)
error: Unable to load C:\Users\<HOME>\Projects\deno-nx\node_modules\nx\src\project-graph\plugins\isolation\plugin-worker

Caused by:
    The system cannot find the file specified. (os error 2)
```

Contents of `.nx\workspace-data\d\daemon-error.log`:

```
Failed to start or connect to the Nx Daemon process.

Messages from the log:
[NX Daemon Server] - 2024-11-21T22:18:16.075Z - Started listening on: \\.\pipe\nx\C:\Users\<HOME>\AppData\Local\Temp\3de1672c0e15e6f0136e\d.sock
[NX Daemon Server] - 2024-11-21T22:18:16.078Z - [WATCHER]: Subscribed to changes within: C:\Users\<HOME>\Projects\deno-nx (native)
[NX Daemon Server] - 2024-11-21T22:18:16.088Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-11-21T22:18:16.090Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2024-11-21T22:18:16.090Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-11-21T22:18:16.091Z - [REQUEST]: Responding to the client. Shutdown initiated
[NX Daemon Server] - 2024-11-21T22:18:16.092Z - Done responding to the client Shutdown initiated
[NX Daemon Server] - 2024-11-21T22:18:16.093Z - Handled FORCE_SHUTDOWN. Handling time: 0. Response time: 2.
[NX Daemon Server] - 2024-11-21T22:18:16.093Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2024-11-21T22:18:16.093Z - [WATCHER]: Stopping the watcher for C:\Users\<HOME>\Projects\deno-nx (sources)
[NX Daemon Server] - 2024-11-21T22:18:16.093Z - [WATCHER]: Stopping the watcher for C:\Users\<HOME>\Projects\deno-nx (outputs)

 NX   Not implemented: Pipe.prototype.listen - Windows
```

**Comment by steve02081504** [comment]
this'll also make `npm:node-notifier` not work :)

**Comment by byronburdette** [comment]
I'm getting this same error when attempting to start Nuxt development server while following the [Nuxt tutorial](https://docs.deno.com/examples/nuxt_tutorial/)

```
my@LAPTOP MINGW64 ~/WebstormProjects/2test
$ deno --version
deno 2.5.0 (stable, release, x86_64-pc-windows-msvc)
v8 14.0.365.4-rusty
typescript 5.9.2

my@LAPTOP MINGW64 ~/WebstormProjects/2test
$ deno task dev
Task dev nuxt dev
Nuxt 4.1.2 with Nitro 2.12.6                                                                                                                               nuxi 1:11:06 PM
                                                                                                                                                                1:11:06 PM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Alt + D in the browser (v2.6.3)                                                                                                     1:11:07 PM


 WARN  Runtime config option public may not be able to be serialized.                                                                                           1:11:08 PM

√ Vite client built in 50ms                                                                                                                                     1:11:09 PM

 ERROR  Cannot start nuxt:  Not implemented: Pipe.prototype.listen - Windows                                                                                    1:11:09 PM

    at notImplemented (ext:deno_node/_utils.ts:9:9)
    at Pipe.listen (ext:deno_node/internal_binding/pipe_wrap.ts:144:7)
    at Server._setupListenHandle [as _listen2] (node:net:1359:28)
    at _listenInCluster (node:net:1191:12)
    at Server.listen (node:net:1489:5)
    at createViteNodeSocketServer (/C:/Users/byron/WebstormProjects/2test/node_modules/.deno/@nuxt+vite-builder@4.1.2/node_modules/@nuxt/vite-builder/dist/index.mjs:513:10)
    at /C:/Users/byron/WebstormProjects/2test/node_modules/.deno/@nuxt+vite-builder@4.1.2/node_modules/@nuxt/vite-builder/dist/index.mjs:328:24
    at /C:/Users/byron/WebstormProjects/2test/node_modules/.deno/hookable@5.5.3/node_modules/hookable/dist/index.mjs:48:66
    at /C:/Users/byron/WebstormProjects/2test/node_modules/.deno/hookable@5.5.3/node_modules/hookable/dist/index.mjs:48:56
    at eventLoopTick (ext:core/01_core.js:179:7)
```

**Comment by steve02081504** [comment]
> I'm getting this same error when attempting to start Nuxt development server while following the [Nuxt tutorial](https://docs.deno.com/examples/nuxt_tutorial/)

for now the only thing ya can do is uh
just use node or bun

**Comment by N0vatrium** [comment]
@byronburdette it's not written on the nuxt tutorial buf if you check their repo you can see that they added this to `nuxt.config.ts`

`nitro: {
    preset: "deno",
  }`

This fixed my issue

**Comment by bartlomieju** [comment]
Fixed in https://github.com/denoland/deno/pull/31624
