### ISSUE TITLE
Deno 2.0.0-rc.5 - Panicked - Failed to find N-API version: DlSym

### ISSUE THREAD

**Issue by tenkoverse** [denoland/deno#25879]
```
deno 2.0.0-rc.5 (release candidate, release, x86_64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

I tried creating a simple deno project to see if temporal was compatible yet. I was successfully able to start a temporal client and create a workflow (not previously possible when I last tried using deno 1.43.1 - see https://github.com/denoland/deno/issues/23753).  

However, the next step is to run a worker to process a workflow. I ran into another panic error. 

### How to reproduce

1. You need to download and run [temporal dev server ](https://github.com/temporalio/cli) with ```temporal server start-dev```

2. You need to setup a basic deno project with the following files  ```activities.ts```,  ```workflows.ts```,  ```worker.ts```,  ```client.ts```

3. Create each file listed above with the contents listed below.

```typescript
// activities.ts
export function greet(name: string): string {
    return `Hello, ${name}!`;
}
```

```typescript
// workflows.ts
import * as workflow from 'npm:@temporalio/workflow';
import type * as activities from './activities.ts';

const { greet } = workflow.proxyActivities<typeof activities>({
  startToCloseTimeout: '1 minute',
});

export async function example(name: string): Promise<string> {
  return await greet(name);
}
```

```typescript
// worker.ts
import { Worker } from 'npm:@temporalio/worker';
import * as activities from './activities.ts';

async function run() {
    const worker = await Worker.create({
        workflowsPath: '/Users/ ... /workflows.ts',  // < THIS NEEDS TO BE YOUR EXACT PATH
        // temporal docs say to use require.resolve('./workflows'), but this doesnt work in deno, i would love to know how to do this in deno. 
        taskQueue: 'hello-world',
        activities,
    });

    await worker.run();
}

run();


```

```typescript
// client.ts
import { Connection, Client } from 'npm:@temporalio/client';
import { example } from './workflows.ts';

async function run() {
    const connection = await Connection.connect({ address: 'localhost:7233' });

    const client = new Client({
      connection,
    });
    
    await client.workflow.start(example, {
        taskQueue: 'hello-world',
        args: ['Temporal'],
        workflowId: 'workflow-1',
    });
}
  
run()
```

4. Run the deno temporal ```client.ts``` to start a workflow. It should work. Visit ``localhost:7233`` to see if the workflow was created.  

```typescript
deno -A client.ts
```

5. Run the deno temporal ```worker.ts``` to attempt to start a worker to process the workflow. 

```typescript
RUST_BACKTRACE=full deno -A worker.ts
```

and get the following error.

```
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/neon-runtime-0.10.1/src/napi/bindings/functions.rs:360:43:
Failed to find N-API version: DlSym { desc: "dlsym(RTLD_DEFAULT, napi_get_version): symbol not found" }
stack backtrace:
   0:        0x12ec79527 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::haf41a54e7ed5fe07
   1:        0x12e84a6db - core::fmt::write::h526161fad96c5ad5
   2:        0x12ec479b2 - std::io::Write::write_fmt::h4de0398536c8b0e4
   3:        0x12ec7b011 - std::panicking::default_hook::{{closure}}::hffeef89117b5d267
   4:        0x12ec7aa68 - std::panicking::default_hook::h2f20b53f3264c5d5
   5:        0x12ec7ca59 - std::panicking::rust_panic_with_hook::h7919e8c602131afa
   6:        0x12ec7bb35 - std::panicking::begin_panic_handler::{{closure}}::h7bd628128f542977
   7:        0x12ec7ba99 - std::sys::backtrace::__rust_end_short_backtrace::ha2fdb908654ed930
   8:        0x12ec7ba8c - _rust_begin_unwind
   9:        0x12f1c8bfa - core::panicking::panic_fmt::h292eaa4d42e451fa
  10:        0x12f1c9125 - core::result::unwrap_failed::hc10b3a255072c9c6
  11:        0x12e8d9191 - neon_runtime::napi::bindings::functions::load::h01cef81ec132fc63
  12:        0x12e8d6f17 - std::sync::once::Once::call_once::{{closure}}::hd32f1b65d3843264
  13:        0x12f1ea6df - std::sys::sync::once::queue::Once::call::hee0776cd3b3b4bb0
  14:        0x12f09dde4 - _napi_register_module_v1
  15:        0x1075a639d - deno_napi::op_napi_open::op_napi_open<NP>::v8_fn_ptr::h3246228212bb28ed
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x12ec79527 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::haf41a54e7ed5fe07
   1:        0x12e84a6db - core::fmt::write::h526161fad96c5ad5
   2:        0x12ec479b2 - std::io::Write::write_fmt::h4de0398536c8b0e4
   3:        0x12ec7b011 - std::panicking::default_hook::{{closure}}::hffeef89117b5d267
   4:        0x12ec7aa68 - std::panicking::default_hook::h2f20b53f3264c5d5
   5:        0x12ec7ca59 - std::panicking::rust_panic_with_hook::h7919e8c602131afa
   6:        0x12ec7bb02 - std::panicking::begin_panic_handler::{{closure}}::h7bd628128f542977
   7:        0x12ec7ba99 - std::sys::backtrace::__rust_end_short_backtrace::ha2fdb908654ed930
   8:        0x12ec7ba8c - _rust_begin_unwind
   9:        0x12f1c926c - core::panicking::panic_nounwind_fmt::h12cc2ce627e784e8
  10:        0x12f1c92e5 - core::panicking::panic_nounwind::h770250030017ec94
  11:        0x12f1c9289 - core::panicking::panic_cannot_unwind::h37f7072994988adf
  12:        0x12f09e28d - _napi_register_module_v1
  13:        0x1075a639d - deno_napi::op_napi_open::op_napi_open<NP>::v8_fn_ptr::h3246228212bb28ed
thread caused non-unwinding panic. aborting.
zsh: abort      RUST_BACKTRACE=full deno -A worker.ts
```

**Comment by littledivy** [comment]
Seems to be macOS specific. Cannot reproduce on x86_64 Linux.

**Comment by littledivy** [comment]
I get the following output on arm macOS, no panics:

```
2024-09-27T03:16:10.312Z [INFO] Creating worker {
  sdkComponent: 'worker',
  taskQueue: 'hello-world',
  options: {
    namespace: 'default',
    identity: '17827@divy-macbook.local',
    useVersioning: false,
    buildId: undefined,
    shutdownGraceTime: 0,
    enableNonLocalActivities: true,
    maxConcurrentWorkflowTaskPolls: 10,
    maxConcurrentActivityTaskPolls: 10,
    stickyQueueScheduleToStartTimeout: '10s',
    maxHeartbeatThrottleInterval: '60s',
    defaultHeartbeatThrottleInterval: '30s',
    isolateExecutionTimeout: '5s',
    workflowThreadPoolSize: 1,
    maxCachedWorkflows: 731,
    showStackTraceSources: false,
    debugMode: false,
    interceptors: { activity: [], workflowModules: [] },
    nonStickyToStickyPollRatio: 0.2,
    sinks: { __temporal_logger: [Object] },
    workflowsPath: '/Users/divy/gh/temporalio-deno-bug/workflows.ts',
    taskQueue: 'hello-world',
    activities: Map(1) { 'greet' => [Function: greet] },
    tuner: {
      workflowTaskSlotSupplier: [Object],
      activityTaskSlotSupplier: [Object],
      localActivityTaskSlotSupplier: [Object]
    },
    reuseV8Context: true,
    shutdownGraceTimeMs: 0,
    shutdownForceTimeMs: undefined,
    stickyQueueScheduleToStartTimeoutMs: 10000,
    isolateExecutionTimeoutMs: 5000,
    maxHeartbeatThrottleIntervalMs: 60000,
    defaultHeartbeatThrottleIntervalMs: 30000,
    loadedDataConverter: {
      payloadConverter: [DefaultPayloadConverter],
      failureConverter: [DefaultFailureConverter],
      payloadCodecs: []
    }
  }
}
2024-09-27T03:16:11.043Z [INFO] asset workflow-bundle-2e5ab17633d55b5fbb35.js 884 KiB [emitted] [immutable] (name: main)
runtime modules 937 bytes 4 modules
modules by path ./node_modules/@temporalio/ 222 KiB
  modules by path ./node_modules/@temporalio/common/lib/ 82.6 KiB
    modules by path ./node_modules/@temporalio/common/lib/*.js 57.8 KiB 16 modules
    modules by path ./node_modules/@temporalio/common/lib/converter/*.js 24.8 KiB 5 modules
  modules by path ./node_modules/@temporalio/workflow/ 139 KiB
    ./node_modules/@temporalio/workflow/lib/worker-interface.js 8.52 KiB [built] [code generated]
    ./node_modules/@temporalio/workflow/lib/global-overrides.js 4.12 KiB [built] [code generated]
    + 17 modules
./workflows-autogenerated-entrypoint.cjs 433 bytes [built] [code generated]
./workflows.ts 221 bytes [built] [code generated]
__temporal_custom_payload_converter (ignored) 15 bytes [built] [code generated]
__temporal_custom_failure_converter (ignored) 15 bytes [built] [code generated]
./node_modules/long/umd/index.js 43.1 KiB [built] [code generated]
./node_modules/ms/dist/index.cjs 3.41 KiB [built] [code generated]
webpack 5.95.0 compiled successfully in 435 ms { sdkComponent: 'worker', taskQueue: 'hello-world' }
2024-09-27T03:16:11.045Z [INFO] Workflow bundle created { sdkComponent: 'worker', taskQueue: 'hello-world', size: '0.86MB' }
error: Uncaught (in promise) Error: Not implemented: v8.promiseHooks.createHook
```

```
$ deno -V
deno 2.0.0-rc.6
```

**Comment by littledivy** [comment]
Seems to be the same issue that causes https://github.com/denoland/deno/issues/25940.

**Comment by monktastic** [comment]
@tenkoverse @littledivy This may be a silly question, but when I try to run `worker.ts`, I get:

```
ERROR in npm:@temporalio/workflow
Module build failed: UnhandledSchemeError: Reading from "npm:@temporalio/workflow" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "npm:" URIs.
```

Is there an obvious way to fix this?

**Comment by pravin-pk** [comment]
@monktastic I'm also facing the same issue. Any resolution that you found?
