### ISSUE TITLE
tools/setup.py fails on windows

### ISSUE THREAD

**Issue by ry** [denoland/deno#2590]
```
C:\Users\ry\deno>python tools/setup.py
binary download
python C:\Users\ry\deno\third_party\depot_tools\download_from_google_storage.py --platform=win32 --no_auth --bucket=chromium-gn --sha1_file C:\Users\ry\deno\third_party\v8\buildtools\win\gn.exe.sha1
python C:\Users\ry\deno\third_party\depot_tools\download_from_google_storage.py --platform=win32 --no_auth --bucket=chromium-clang-format --sha1_file C:\Users\ry\deno\third_party\v8\buildtools\win\clang-format.exe.sha1
python C:\Users\ry\deno\third_party\v8\tools\clang\scripts\update.py
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-362913-80fee257-1.tgz .......... Done.
Traceback (most recent call last):
  File "C:\Users\ry\deno\third_party\v8\tools\clang\scripts\update.py", line 324, in <module>
    sys.exit(main())
  File "C:\Users\ry\deno\third_party\v8\tools\clang\scripts\update.py", line 320, in main
    return UpdateClang()
  File "C:\Users\ry\deno\third_party\v8\tools\clang\scripts\update.py", line 258, in UpdateClang
    CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
  File "C:\Users\ry\deno\third_party\v8\tools\clang\scripts\update.py", line 229, in CopyDiaDllTo
    GetWinSDKDir()
  File "C:\Users\ry\deno\third_party\v8\tools\clang\scripts\update.py", line 202, in GetWinSDKDir
    import vs_toolchain
ImportError: No module named vs_toolchain
```

**Comment by ry** [comment]
sorry - duplicate of https://github.com/denoland/deno/issues/1898
