### ISSUE TITLE
/etc/hosts seems to be ignored

### ISSUE THREAD

**Issue by studiowebux** [denoland/deno#25927]
Version: Deno 1.46.3 and 2.0.0-rc.7
OS: Macos Sequoia

Hello

I am trying to use this code:

```ts
import dns from "node:dns";

dns.lookup("mongo-1", (err, address, family) => {
  console.error(err);
  console.log("address: %j family: IPv%s", address, family);
});
```

I also have the issue with the `mongodb` package from NPM.

It prints:

```bash
Error: getaddrinfo ENOTFOUND mongo-1
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_ (ext:deno_node/internal/errors.ts:246:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:37:26)
    at ext:deno_node/internal_binding/cares_wrap.ts:78:9
    at eventLoopTick (ext:core/01_core.js:175:7) {
  errno: -3007,
  code: "ENOTFOUND",
  syscall: "getaddrinfo",
  hostname: "mongo-1"
}
address: %j family: IPvundefined undefined
```

`/etc/hosts`

```txt
127.0.0.1 mongo-1
```

I tested using bash (netcat) and mongoDB Compass and the name `mongo-1` works as expected.

I tried this command as well: `sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder` without success.

Thank you.

**Comment by littledivy** [comment]
Caused by `dns.lookup` using `Deno.resolveDns` which uses [`trust_dns_resolver`](https://docs.rs/trust-dns-resolver/latest/trust_dns_resolver/) - a 100% in-process DNS resolver

**Comment by lucacasonato** [comment]
@littledivy I don't think that is necessarily the issue. If you don't pass `nameservers` to `Deno.resolveDns`, we use system resolver (through `/etc/resolv.conf`)

**Comment by jyecusch** [comment]
The same thing occurs in Docker with extra hosts defined. Here is an example using `Deno.resolveDns` directly: https://github.com/jyecusch/deno-dns-example

**Comment by shunkica** [comment]
I am using the npm:mysql package with deno 2 and it can not resolve hostnames which are defined in /etc/hosts

**Comment by j11e** [comment]
Even without Docker, `/etc/hosts` is not actually read when performing DNS lookups.

On macOS 15.0.1, using Deno 2.0.3 and node 22.10.0:

```javascript
import * as dns from "node:dns";

dns.lookup("nonexistent-domain.net", (_err, address, family) => {
    console.log(`address: ${address} family: IPv${family}`);
});
``` 

After adding in my /etc/hosts file: `1.2.3.4  nonexistent-domain.net`, the output will is:

- for node, `address: 1.2.3.4 family: IPv4`
- for deno, `address: undefined family: IPvundefined`

**Comment by shunkica** [comment]
I don't use Rust but I did a very shallow dive into what could cause this and it seems that `tokio::net` is used for resolution, and in the documentation of that library the `lookup_host` function is described like this:

```
The returned iterator may not actually yield any values depending on the outcome of any resolution performed.

This API is not intended to cover all DNS use cases. Anything beyond the basic use case should be done with a specialized library.
```

**Comment by ginkcode** [comment]
I got the same issues with `ioredis` and the extra_hosts from docker compose, which simply write to `/etc/hosts`

**Comment by vseplet** [comment]
Hello, comrades! I'm from 2025 and I want to tell you that fetch in deno 2.2.8 on MacOS still ignores /etc/hosts!
