### ISSUE TITLE
Failed to get cpu info crash on aarch64

### ISSUE THREAD

**Issue by solb** [denoland/deno#25929]
The latest Deno 2 release candidate crashes inside the Node compatibility function `os.cpus()` when run on an Android device under Termux. To reproduce:

```
$ curl -O https://dl.deno.land/release/v2.0.0-rc.7/deno-aarch64-unknown-linux-gnu.zip
$ unzip deno-aarch64-unknown-linux-gnu.zip
$ apt install glibc-repo
$ apt install glibc-runner
$ grun ./deno eval 'console.log("success")'
success
$ echo 'import {cpus} from "node:os";' >cpus.js
$ echo 'console.log(cpus());' >>cpus.js
$ grun ./deno --allow-sys=cpus cpus.js
error: Uncaught (in promise) TypeError: Failed to get cpu info
  at cpus (node:os:63:10)
  at file:///data/data/com.termux/files/home/cpus.js:2:13
```

I don't have another ARM device handy, but I'm curious whether this affects all aarch64 machines or just the Termux glibc wrapper script.

Version: Deno 2.0.0-rc.7

**Comment by FriendlySpiritCat** [comment]
When I used Deno to create a Vite project, I encountered the same issue.

```shell
deno run -A npm:create-vite vite-deno

cd vite-deno
deno install
deno run dev

error: Uncaught (in promise) TypeError: Failed to get cpu info
    at cpus (node:os:66:10)
    at Object.getReport (ext:deno_node/internal/process/report.ts:42:13)
    at isMusl (file:///data/data/com.termux/files/home/dev/vite-deno/node_modules/.deno/rollup@4.34.8/node_modules/rollup/dist/native.js:5:30)
    at getPackageBase (file:///data/data/com.termux/files/home/dev/vite-deno/node_modules/.deno/rollup@4.34.8/node_modules/rollup/dist/native.js:82:28)
    at Object.<anonymous> (file:///data/data/com.termux/files/home/dev/vite-deno/node_modules/.deno/rollup@4.34.8/node_modules/rollup/dist/native.js:42:21)
    at Object.<anonymous> (file:///data/data/com.termux/files/home/dev/vite-deno/node_modules/.deno/rollup@4.34.8/node_modules/rollup/dist/native.js:112:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:755:12)
    at Module.load (node:module:662:32)
``` 

I found that the problem was caused by the shebang in the main module of the package. So, I replaced the shebang of all main modules in node_modules/.bin with "#!/data/data/com.termux/files/usr/bin/env node". After that, the error disappeared, but it was replaced by an Android platform compatibility error (which can be fixed by installing the appropriate platform-specific package).

The question is, why didn't "termux-exec" automatically handle the shebang issue for us?

**Comment by StellanWay** [comment]
Affects Deno 2.2.13 built for Android's bionic as well unfortunately.

```
error: Uncaught (in promise) TypeError: Failed to get cpu info 
  at Object.cpus (node:os:66:10)
```

**Comment by jiesou** [comment]
Any updates?
in termux, installed by `pkg`
deno 2.4.5

```bash
$ deno run --allow-all npm:vite
error: Uncaught (in promise) TypeError: Failed to get cpu info
    at cpus (node:os:67:10)
    at Object.getReport (ext:deno_node/internal/process/report.ts:42:13)
    at file:///data/data/com.termux/files/home/.dev/ElectricDriveTestSystem/client/node_modules/.deno/rollup@4.52.2/node_modules/rollup/dist/native.js:36:17
    at Object.<anonymous> (file:///data/data/com.termux/files/home/.dev/ElectricDriveTestSystem/client/node_modules/.deno/rollup@4.52.2/node_modules/rollup/dist/native.js:119:3)
    at Module._compile (node:module:759:34)
    at loadMaybeCjs (node:module:784:10)
    at Object.Module._extensions..js (node:module:769:12)
    at Module.load (node:module:677:32)
    at Module._load (node:module:535:12)
    at Module.require (node:module:696:19)
```

**Comment by kisaragi-hiu** [comment]
After turning the reproduction into a script, I can reproduce this for versions as early as 1.40.3, which is just after os.cpus() was implemented (1.39.2). For 1.39.2~1.40.2, the url I'm using returns 404 so I didn't test them.

This means this error was not introduced in the 2.0 development cycle.

I'm testing this in Termux on Android in an aarch64 device; in this environment /proc is unreadable.

From reading [the code](https://github.com/denoland/deno/blob/5cee3a317d1c9e64a7d6c09763921fe854ad086c/ext/node/ops/os/cpus.rs#L250) my suspicion is that this error would happen whenever /proc is unreadable (on Android or Linux). (It makes sense that cpu_info returns None if there's an error, but os.cpus() should not expose that.)

The script:

```sh
# denotest.sh
#
# https://github.com/denoland/deno/issues/25929
# install these first (in this order because glibc-runner is only available after the repo is installed)
# apt install glibc-repo
# apt install glibc-runner
set -euo pipefail

ver="$1"
url=https://dl.deno.land/release/$ver/deno-aarch64-unknown-linux-gnu.zip
mkdir -p deno-"$ver"-test
cd deno-"$ver"-test
echo "Downloading $url..."
# fail if 404; write to filename like wget
[ -f deno-aarch64-unknown-linux-gnu.zip ] || curl -f -O "$url"
echo "Unzipping..."
# overwrite without prompt
unzip -o deno-aarch64-unknown-linux-gnu.zip
echo 'console.log("success; Deno:", Deno.version.deno)' >runs.js
grun ./deno run runs.js
echo 'import {cpus} from "node:os";' >cpus.js
echo 'console.log("cpus:");' >>cpus.js
echo 'console.log(cpus());' >>cpus.js
# cpus perm was added in 1.40.4
grun ./deno run --allow-sys cpus.js
```

**Comment by kisaragi-hiu** [comment]
In Node, [the internal `getCPUs` function](https://github.com/nodejs/node/blob/fb84f35fec81805349e856267e1a6e6ebe4f3a49/src/node_os.cc#L437) ([impl](https://github.com/nodejs/node/blob/fb84f35fec81805349e856267e1a6e6ebe4f3a49/src/node_os.cc#L109)) seems to effectively (I don't know libuv and C++ well) return either an Array or undefined from JS's view, and in [os.cpus()](https://github.com/nodejs/node/blob/fb84f35fec81805349e856267e1a6e6ebe4f3a49/lib/os.js#L140) if getCPUs() returns undefined then it will return an empty array.

In Deno, currently [cpu_info](https://github.com/denoland/deno/blob/5cee3a317d1c9e64a7d6c09763921fe854ad086c/ext/node/ops/os/cpus.rs#L245) returns Option<Vec<CpuInfo>>, then [op_cpus](https://github.com/denoland/deno/blob/5cee3a317d1c9e64a7d6c09763921fe854ad086c/ext/node/ops/os/mod.rs#L270) wraps it to normally return CpuInfo[] normally, but when cpu_info() is None this returns the error [`OsError::FailedToGetCpuInfo` ("Failed to get cpu info")](https://github.com/denoland/deno/blob/5cee3a317d1c9e64a7d6c09763921fe854ad086c/ext/node/ops/os/mod.rs#L28), which from JS means it throws the error. Deno's [os.cpus()](https://github.com/denoland/deno/blob/5cee3a317d1c9e64a7d6c09763921fe854ad086c/ext/node/polyfills/os.ts#L149) then simply returns what op_cpus returns. So if cpu_info encounters an error (like being unable to read /proc), os.cpus() throws an error instead of returning an empty array like the Node counterpart does.

---

If I simulate how the os.cpus() implementation reacts to /proc being unreadable by:

- editing `ext/node/ops/os/cpus.rs` to read from, say, /tmp/procstat instead of /proc/stat, and /tmp/proccpuinfo instead of /proc/cpuinfo
- then `cargo build`
- then `./target/debug/deno repl --allow-sys` then run `import os from "node:os"; os.cpus()`

then `os.cpus()` throws instead of returning an empty array. If I then populate these two files with the correct values (`cat /proc/stat > /tmp/procstat; cat /proc/cpuinfo > /tmp/proccpuinfo`) I can see that os.cpus() returns the expected value.

If I do the same thing to Node:

- edit Node's `deps/uv/src/unix/linux.c` to change /proc/stat to /tmp/procstat and /proc/cpuinfo to /tmp/proccpuinfo
- `./configure --without-npm --with-intl=system-icu --shared-{brotli,cares,nghttp2,nghttp3,ngtcp2,openssl,simdjson,zlib}` on my system
- `make -j12` (this takes about an hour on my system)
- `./node` then run `os.cpus()`

with /tmp/procstat and /tmp/proccpuinfo both being nonexistant, this returns an empty array. The value is still as expected if the files are populated with the correct values.
