### ISSUE TITLE
Next.js in Deno Error - dyld[26083]: missing symbol called

### ISSUE THREAD

**Issue by tenkoverse** [denoland/deno#25940]
Version: deno 2.0.0-rc.7
Platform: Intel based mac (macbook pro AND mac mini)

I have run into an error running React/Next as per the [tutorial in the docs](https://docs.deno.com/runtime/fundamentals/web_dev/#react%2Fnext).

Here is what I did.

```bash
deno run -A npm:create-next-app@latest my-next-app

✔ Would you like to use TypeScript? … No / [Yes]
✔ Would you like to use ESLint? … [No] / Yes
✔ Would you like to use Tailwind CSS? … No / [Yes]
✔ Would you like to use `src/` directory? … No / [Yes]
✔ Would you like to use App Router? (recommended) … No / [Yes]
✔ Would you like to customize the default import alias (@/*)? … [No] / Yes

Creating a new Next.js app in /Users/ .. user .. /Documents/deno_test/my-next-app.

Using npm.

Initializing project with template: app-tw 


Installing dependencies:
- react
- react-dom
- next

Installing devDependencies:
- typescript
- @types/node
- @types/react
- @types/react-dom
- postcss
- tailwindcss


added 138 packages, and audited 139 packages in 10s

31 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Success! Created my-next-app at /Users/ .. user .. /Documents/deno_test/my-next-app
```

```bash
cd my-next-app 
```

```bash
deno task dev


Task dev next dev
  ▲ Next.js 14.2.13
  - Local:        http://localhost:3000

 ✓ Starting...
dyld[26302]: missing symbol called
error: Uncaught (in promise) TypeError: Unknown signal: 0
    at toDenoSignal (ext:deno_node/internal/child_process.ts:389:11)
    at ChildProcess.kill (ext:deno_node/internal/child_process.ts:298:53)
    at handleSessionStop (file:///Users/ ... user ... /Documents/deno_test/my-next-app/node_modules/next/dist/cli/next-dev.js:84:51)
    at ChildProcess.<anonymous> (file:///Users/ ... user ... /Documents/deno_test/my-next-app/node_modules/next/dist/cli/next-dev.js:253:23)
    at ChildProcess.emit (ext:deno_node/_events.mjs:393:28)
    at ext:deno_node/internal/child_process.ts:277:16
    at eventLoopTick (ext:core/01_core.js:175:7)

```

I have tried this flow on 2 machines and both have the same issue. 

I am running 
```bash
node -v
v20.14.0

npm -v
10.7.0
```

If I run with npm instead, it works. 

```bash

npm run dev

> my-next-app@0.1.0 dev
> next dev

  ▲ Next.js 14.2.13
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1516ms
 
 ```

**Comment by littledivy** [comment]
I've tracked it down to an issue with `sui` - the tool we use to prepare RC releases. This will not be an issue in stable releases. 

https://github.com/denoland/sui/issues/29

**Comment by hongkongkiwi** [comment]
Same issue here on a M1 Mac Mini

**Comment by lucacasonato** [comment]
As a temporary workaround, you can use canary instead of rc: `deno upgrade canary`

**Comment by littledivy** [comment]
Just released `2.0.0-rc.9` with the fix. @tenkoverse can you give it a try?

**Comment by hongkongkiwi** [comment]
Same problem for me with canary on Mac M1 Mini.
```
deno run --allow-all --unstable-sloppy-imports lambda.ts
dyld[44083]: missing symbol called
```

Here's the version
```
deno 2.0.0-rc.9+3881b71 (canary, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

**Comment by littledivy** [comment]
@hongkongkiwi That looks like a different issue. Can you open a new issue with reproduction?

**Comment by jrasanen** [comment]
On Apple Silicon, I get the `missing symbol called`-error quite easily.

> deno --version
> deno 2.1.4 (stable, release, aarch64-apple-darwin)
> v8 13.0.245.12-rusty
> typescript 5.6.2

package.json

```json
{
  "name": "denoissue",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "pdf-img-convert": "^2.0.0"
  }
}
```

index.ts
```typescript
import * as pdf2img from "npm:pdf-img-convert@2.0.0"

console.log(pdf2img.convert("meheh"))
```

And I get the following:

```sh
$ deno run -A index.ts
dyld[72411]: missing symbol called
fish: Job 1, 'deno run -A index.ts' terminated by signal SIGABRT (Abort)
```
