### ISSUE TITLE
Bug: Cannot open current file

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25946]
## Steps to reproduce

Run this script:

```ts
const _file = await Deno.readTextFile(import.meta.url);
```

Output:

```sh
error: Uncaught (in promise) NotFound: No such file or directory (os error 2): open 'file:///Users/marvinh/dev/test/deno-leaks/foo.ts'
const _file = await Deno.open(import.meta.url);
                         ^
    at Object.open (ext:deno_fs/30_fs.js:538:21)
    at file:///Users/marvinh/dev/test/deno-leaks/foo.ts:1:26
```

Version: Deno 2.0.0-rc.7+05ca699

**Comment by bartlomieju** [comment]
This is not a bug. We don't support strings starting with `file://` in FS APIs.

**Comment by marvinhagemeister** [comment]
Gotcha, that makes sense
