### ISSUE TITLE
__dirname is not defined with Deno 2 RC

### ISSUE THREAD

**Issue by studiowebux** [denoland/deno#25970]
Version: Deno 2.0.0

Ref: 
- https://github.com/DjDeveloperr/deno-canvas/issues/41
- [Original Ticket] https://github.com/denoland/deno/issues/25928

Moved second issue in dedicated ticket.

Was working with 1.45.x and 1.46.x

```
RUST_BACKTRACE=full deno run game:start
Task game:start deno run -A --watch src/bin/main.tsx
Watcher Process started.
error: Uncaught (in promise) ReferenceError: __dirname is not defined
        Ca = za ? require("path").dirname(Ca) + "/" : __dirname + "/",
                                                      ^
    at Module.<anonymous> (https://deno.land/x/canvas@v1.4.1/src/lib.js:3784:55)
    at init (https://deno.land/x/canvas@v1.4.1/src/canvaskit.ts:9:20)
    at init (https://deno.land/x/canvas@v1.4.1/src/canvas.ts:9:18)
    at https://deno.land/x/canvas@v1.4.1/mod.ts:3:22
Watcher Process failed. Restarting on file change...
```

This one I ain't sure what to check, is it related to deno 2 ?

I just tried this package : jsr:@gfx/canvas@0.5.6 seems to work as a replacement.

Thank you.

**Comment by studiowebux** [comment]
Ticket is opened in the deno-canvas repository https://github.com/DjDeveloperr/deno-canvas/issues/41
