### ISSUE TITLE
Better DX by referring URL link for common or known errors in the terminal

### ISSUE THREAD

**Issue by realChakrawarti** [denoland/deno#26016]
## Issue
I have the following code,

```ts
import data from './data.json'

console.log(data);
```

And I get following error as output in the terminal

```bash

> deno main.ts

error: Expected a JavaScript or TypeScript module, but identified a Json module. Consider importing Json modules with an import attribute with the type of "json".

Specifier: file:///<path>/data.json
    at file:///<path>/main.ts:1:18
```

## Requested change

I had to search to find the link which shows the solution with an example, https://docs.deno.com/examples/importing-json/ which I expect to be part of the error output in the terminal. 

```bash
> deno main.ts

error: Expected a JavaScript or TypeScript module, but identified a Json module. Consider importing Json modules with an import attribute with the type of "json".

Refer: https://docs.deno.com/examples/importing-json/

Specifier: file:///<path>/data.json
    at file:///<path>/main.ts:1:18
```

Could something like this be added for all known errors/warnings. Thanks.

**Comment by cu8code** [comment]
@lucacasonato has this issue been resolved I would love to solve this.

**Comment by cu8code** [comment]
![image](https://github.com/user-attachments/assets/763d3059-1ce3-412f-91fb-30af04691bae)
seems to be solve
