### ISSUE TITLE
createImageBitmap from blob [v.2.0.0-rc10]

### ISSUE THREAD

**Issue by mcioffi** [denoland/deno#26032]
**Version**: Deno 2.0.0-rc10

The Web Canvas API in Deno for [createImageBitmap](https://docs.deno.com/api/web/~/createImageBitmap) supports blobs. Added earlier this year in https://github.com/denoland/deno/pull/21898

### Observations
Currently seeing failures against standard jpg/pngs. The same code in a non-Deno environment, e.g. browser, works. Omission of jpg [seems intentional](https://github.com/denoland/deno/blob/2de4faa483982478e9a36ad4ab891a887b4779f1/ext/canvas/01_image.js#L235) from the deno library , but is worth bringing up as its widely supported in [web apis](https://developer.mozilla.org/en-US/docs/Web/API/Window/createImageBitmap)

```
async function loadImage(url) {
  try{
    const response = await fetch(url);
    const blob = await response.blob();
    const imageBitmap = await createImageBitmap(blob);
    return imageBitmap;
  }
  catch (error) {
    console.log(error)
  }
}
```

```
const jpg = await loadImage("https://deno.com/images/artwork/deno_city.jpeg")

InvalidStateError: Unsupported type 'image/jpeg'
    at ext:deno_canvas/01_image.js:236:15
    at eventLoopTick (ext:core/01_core.js:175:7)
```

```
const png = await loadImage("https://deno.com/images/artwork/deno_news.png")

TypeError: Color type 'Rgb8' not supported
    at ext:deno_canvas/01_image.js:241:50
    at eventLoopTick (ext:core/01_core.js:175:7)
```

### Environment
![Screenshot 2024-10-04 at 3 35 58 PM](https://github.com/user-attachments/assets/e13bc516-7057-4c82-a8b4-9b40377753dc)

**Comment by petamoriken** [comment]
related #25517
