### ISSUE TITLE
NodeJS namespace-dependent types resolve to 'any' type

### ISSUE THREAD

**Issue by kawmra** [denoland/deno#26072]
Version: Deno 2.0.0-rc.10

Types that rely on the NodeJS namespace are turning into `any` because the NodeJS namespace isn't available. 
For instance, in JSZip, types that use `NodeJs.ReadableStream` end up as `any`.

<img width="854" alt="image" src="https://github.com/user-attachments/assets/22121efe-2a27-493d-954d-80b4fa1bb80c">

```ts
import JSZip from "npm:jszip@3.10.1";
declare const data: unknown;
await JSZip.loadAsync(data);
//                    ^ the first argument accepts any so no errors happen
```

**Comment by dsherret** [comment]
```
% deno check --all index.ts
Check file:///Users/david/dev/scratch2/index.ts
error: TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    stream: NodeJS.ReadableStream;
            ~~~~~~
    at file:///Users/david/Library/Caches/deno/npm/registry.npmjs.org/jszip/3.10.1/index.d.ts:35:13

TS2580 [ERROR]: Cannot find name 'Buffer'.
    nodebuffer: Buffer;
                ~~~~~~
    at file:///Users/david/Library/Caches/deno/npm/registry.npmjs.org/jszip/3.10.1/index.d.ts:47:17

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        nodeStream(type?: 'nodebuffer', onUpdate?: OnUpdateCallback): NodeJS.ReadableStream;
                                                                      ~~~~~~
    at file:///Users/david/Library/Caches/deno/npm/registry.npmjs.org/jszip/3.10.1/index.d.ts:97:71

TS2580 [ERROR]: Cannot find name 'Buffer'.
        decodeFileName?: (bytes: string[] | Uint8Array | Buffer) => string;
                                                         ~~~~~~
    at file:///Users/david/Library/Caches/deno/npm/registry.npmjs.org/jszip/3.10.1/index.d.ts:170:58

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    generateNodeStream(options?: JSZip.JSZipGeneratorOptions<'nodebuffer'>, onUpdate?: JSZip.OnUpdateCallback): NodeJS.ReadableStream;
                                                                                                                ~~~~~~
    at file:///Users/david/Library/Caches/deno/npm/registry.npmjs.org/jszip/3.10.1/index.d.ts:294:113

Found 5 errors.
```

To fix the issue, you'll need to include the `@types/node` package. If you're just using a single file script, you can include node types this way, which will fix the type errors:

```ts
/// <reference types="npm:@types/node" />
import JSZip from "npm:jszip@3.10.1";
declare const data: unknown;
await JSZip.loadAsync(data);
```

See https://docs.deno.com/runtime/fundamentals/node/#including-node-types

**Comment by kawmra** [comment]
I missed it! Thank you.
