### ISSUE TITLE
Issues regarding integration of Clerk with NextJS

### ISSUE THREAD

**Issue by StilauGamer** [denoland/deno#26086]
Version: Deno 2.0

### What is the issue?
Basically, if you are trying to integrate Clerk with NextJS it will immediately crash when the first page is trying to compile.
It passes the middleware compilation, but when it hits the page compilation; it crashes immediately.

**Note:** A default NextJS application, with no Clerk added will **not** crash. Its when Clerk is added, it crashes.

Error that occurs upon page compilation:
```
error: Uncaught TypeError: Failed to decompress
    at BrotliDecompress.transform [as _transform] (ext:deno_node/_brotli.js:69:23)
    at BrotliDecompress.Transform._write (ext:deno_node/_stream.mjs:4563:12)
    at writeOrBuffer (ext:deno_node/_stream.mjs:3520:16)
    at _write (ext:deno_node/_stream.mjs:3465:14)
    at BrotliDecompress.Writable.write (ext:deno_node/_stream.mjs:3468:14)
    at Readable.ondata (ext:deno_node/_stream.mjs:2744:26)
    at Readable.emit (ext:deno_node/_events.mjs:393:28)
    at resume_ (ext:deno_node/_stream.mjs:2915:7)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:36:15)
    at runNextTicks (ext:deno_node/_next_tick.ts:75:3)
    at eventLoopTick (ext:core/01_core.js:182:21)
error: Uncaught (in promise) TypeError: Unknown signal: 0
    at toDenoSignal (ext:deno_node/internal/child_process.ts:389:11)
    at ChildProcess.kill (ext:deno_node/internal/child_process.ts:298:53)
    at handleSessionStop (file:///F:/Scripts/ClerkDenoTesting/node_modules/.deno/next@14.2.15/node_modules/next/dist/cli/next-dev.js:84:51)
    at ChildProcess.<anonymous> (file:///F:/Scripts/ClerkDenoTesting/node_modules/.deno/next@14.2.15/node_modules/next/dist/cli/next-dev.js:253:23)
    at ChildProcess.emit (ext:deno_node/_events.mjs:393:28)
    at ext:deno_node/internal/child_process.ts:277:16
    at eventLoopTick (ext:core/01_core.js:175:7)
```

### How to reproduce?
Its quite simple to reproduce.
Just follow these small steps and you should be having the same issues:

1. Create a new NextJS project with: `deno run -A npm:create-next-app@latest` and follow the setup instruction.
2. When created, follow the default Clerk integration: https://clerk.com/docs/quickstarts/nextjs, the only thing needed from here is adding the packages, adding tokens to the `.env` file, adding the middleware.ts file and adding the `ClerkProvider` to your layout.tsx.
3. Run up the application with: `deno task dev`, let it start up and try opening the page.

If you followed the instructions correctly, it should have crashed by now! :)

**Comment by Tauqeer-Ahmed-99** [comment]
I am also facing same issue.
Maybe something related to deno latest release.

When I unintsalled deno started working fine with npm.

CC: @marvinhagemeister

**Comment by CaptainN** [comment]
Not sure this is related, or something completely different - from running (with sharp defined in package.json):

```
deno install --allow-scripts=npm:sharp
```

I get an error related BrotliDecompress:

```
Warning node-gyp was used in a script, but was not listed as a dependency. Either add it as a dependency or install it globally (e.g. `npm install -g node-gyp`)
error: script 'install' in 'sharp@0.32.6' failed with exit code 1
stdout:
sharp: Using cached /Users/kevin.newman/.npm/_libvips/libvips-8.14.5-darwin-arm64v8.tar.br
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies

stderr:
sharp: Installation error: Not implemented: BrotliDecompress.prototype.constructor
Error launching 'node-gyp': No such file or directory (os error 2)
```

**Comment by maxiicodes** [comment]
I'm also not sure if it's related, but I get the same BrotliDecompress error as @CaptainN.

Command:
```
deno install --allow-scripts=npm:sharp@0.32.6,npm:vue-demi@0.14.10
```

Error:
```
Warning node-gyp was used in a script, but was not listed as a dependency. Either add it as a dependency or install it globally (e.g. `npm install -g node-gyp`)
error: script 'install' in 'sharp@0.32.6' failed with exit code 1
stdout:
sharp: Using cached /var/home/maggsii/.npm/_libvips/libvips-8.14.5-linux-x64.tar.br
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies

stderr:
sharp: Installation error: Not implemented: BrotliDecompress.prototype.constructor
Error launching 'node-gyp': No such file or directory (os error 2)

error: failed to run scripts for packages: sharp@0.32.6
```

**Comment by teddybee** [comment]
I have the same issue with nextjs 15.0.3 and deno 2.0.6
```
TypeError: Failed to decompress
    at BrotliDecompress.transform [as _transform] (ext:deno_node/_brotli.js:69:23)
    at Transform._write (ext:deno_node/_stream.mjs:4563:12)
    at writeOrBuffer (ext:deno_node/_stream.mjs:3520:16)
    at _write (ext:deno_node/_stream.mjs:3465:14)
    at Writable.write (ext:deno_node/_stream.mjs:3468:14)
    at Readable.ondata (ext:deno_node/_stream.mjs:2744:26)
    at Readable.emit (ext:deno_node/_events.mjs:393:28)
    at Readable.read (ext:deno_node/_stream.mjs:2597:14)
    at flow (ext:deno_node/_stream.mjs:2933:38)
    at resume_ (ext:deno_node/_stream.mjs:2915:7)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:36:15)
    at runNextTicks (ext:deno_node/_next_tick.ts:76:3)
    at eventLoopTick (ext:core/01_core.js:182:21)
```

**Comment by sigmachirality** [comment]
Just writing a comment here to note that I'm also running into this error

**Comment by sigmachirality** [comment]
Hoping that https://github.com/denoland/deno/pull/27455 will fix. Happy to test and report back when it is merged

**Comment by sarimabbas** [comment]
I am facing a somewhat similar issue, not sure if related to brotli decompress: 

```
 ✓ Compiled /src/middleware in 647ms (215 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ⨯ Error: Attempt to export a nullable value for "File"
    at eventLoopTick (ext:core/01_core.js:175:7) {
```

@littledivy  thanks so much for the fix 🙏  

@sigmachirality do you mind sharing how you will test? Is there a way to install/compile Deno from main branch? Thanks!

**Comment by sigmachirality** [comment]
Can confirm now running into the same issue.

What's interesting is I can clone and run https://github.com/clerk/nextjs-auth-starter-template and run it without any issues. However, if I lock my main codebase to the versions in the `deno.lock` found in `nextjs-auth-starter-template` it doesn't resolve the issue...

**Comment by sigmachirality** [comment]
The issue is probably still with Clerk (removing `middleware.ts` containing the Clerk middleware does not hit the issue), but 

```
import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";

const isProtectedRoute = createRouteMatcher(["/dashboard(.*)"]);

export default clerkMiddleware(async (auth, req) => {
  if (isProtectedRoute(req)) await auth.protect();
});

export const config = {
  matcher: ["/((?!.*\\..*|_next).*)", "/"],
};
```

Is still sufficient to reproduce the issue in our codebase that isn't `nextjs-auth-starter-template`.

**Comment by und-miller** [comment]
Having the same issue when implementing a barebone middleware in nextjs:

```typescript
import {NextResponse, type NextRequest } from 'next/server';

export function middleware(request: NextRequest) {
  console.log("middleware", request);
  return NextResponse.next()
}
```

Results in the following error: 
```
⨯ Error: Attempt to export a nullable value for "File" at eventLoopTick (ext:core/01_core.js:175:7) {
   name: "Error"
}
```

**Comment by bartlomieju** [comment]
I believe the last problem was fixed in https://github.com/denoland/deno/pull/32182. Closing for now. If you run into another problem please open a new issue.
