### ISSUE TITLE
Fails with http2 in fastify

### ISSUE THREAD

**Issue by Krutsch** [denoland/deno#26088]
Version: Deno 2

This code:
```javascript
import Fastify from "fastify";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

const fastify = Fastify({
  http2: true,
  https: {
    key: await readFile(join(process.cwd(), "localhost-key.pem")),
    cert: await readFile(join(process.cwd(), "localhost.pem")),
  },
});
fastify.get("/", (_req, reply) => {
  reply.send("Hello World");
});
await fastify.listen({ port: 3000, host: "::" });
```

fails with error:

```bash
PS C:\Users\...> deno run -A example.ts  
error: Uncaught (in promise) Error: Not implemented: http2.createSecureServer
    at notImplemented (ext:deno_node/_utils.ts:9:9)
    at Object.createSecureServer (node:http2:1296:3)
    at getServerInstance (file:///C:/Users/.../node_modules/fastify/lib/server.js:278:24)
    at createServer (file:///C:/Users/.../node_modules/fastify/lib/server.js:24:18)
    at fastify (file:///C:/Users/.../node_modules/fastify/fastify.js:181:30)
    at file:///C:/Users/.../example.ts:5:17
    at eventLoopTick (ext:core/01_core.js:175:7)
```

However, it will work without http2 but logs: `Not implemented: Server.setTimeout()`

**Comment by raaymax** [comment]
Same here. I tried to use `vite` with `vite-plugin-http2-proxy` and got the same error.
Additionally in docs there is no info that this is not yet ready... 
https://docs.deno.com/api/node/http2/~/createSecureServer

**Comment by adamszigeti** [comment]
Deno fails to run Vite as well because of this reason.

**Comment by bartlomieju** [comment]
Which version of Vite and Fastify are you using?

**Comment by Krutsch** [comment]
I am using the latest version - 5.0.0

**Comment by adamszigeti** [comment]
In my case, Vite is also the latest version (5.4.9), though the bug is most certainly not in Vite. As I understand, the problem is that Deno's Node compatibility module for `http2`'s `createSecureServer` throws a "not implemented" error.

Bun will ship this support in their next release (1.1.31 - see: https://github.com/oven-sh/bun/issues/8823, though how stable it will be is yet to be seen given my experiences with their Node compatibility).

I think related issues include: #3326, and it's tracking issue #23714.

**Comment by bartlomieju** [comment]
Thanks, I asked @littledivy to take care of it

**Comment by Ewok167** [comment]
+

**Comment by FadhiliNjagi** [comment]
Hi! Just checking in—any updates on this? 😊

**Comment by ChrisCottrell** [comment]
I've also noticed this issue when trying to use @vitejs/plugin-basic-ssl

**Comment by soundstep** [comment]
I'm running into this issue to run a vite dev server in HTTPS. Shouldn't this be working because it looks like node:http2 is implemented in Deno?
https://docs.deno.com/api/node/http2/

**Comment by soundstep** [comment]
FYI, I created a separated general issue: https://github.com/denoland/deno/issues/29206 with a small reproduction repo.

https://github.com/denoland/deno/issues/29206

**Comment by alexanderameye** [comment]
Getting the same issue using `deno` + `vite` + the `vitejs/plugin-basic-ssl` package. Any solution?

**Comment by c410-f3r** [comment]
@bartlomieju Does the team still plan to address this issue in the near future?

**Comment by FadhiliNjagi** [comment]
> [@bartlomieju](https://github.com/bartlomieju) Does the team still plan to address this issue in the near future?

Prefixing this with appreciation for the work that has gone into Deno so far, which is impressive. Fixing this would enhance the node compatibility and win over node users using Vite, Fastify, etc.

**Comment by bartlomieju** [comment]
Yes, we plan to work on fixing this issue in the next few weeks.

**Comment by rmaclean** [comment]
Any update to this? been a lot more than a few weeks @bartlomieju

**Comment by c410-f3r** [comment]
Looks like they are replacing `h2` (Rust) with `nghttp2` (C), in other words, a considerable rewrite.

**Comment by bartlomieju** [comment]
@rmaclean this is still in progress. As pointed out in the comment above it's a big refactor. Follow the above PR for updates.

**Comment by bartlomieju** [comment]
The original error (`Not implemented: http2.createSecureServer`) is fixed on Deno canary — the server starts successfully now.

However, the H2 response over TLS doesn't get delivered to clients (the connection hangs). This is tracked in #33072 (`http2.createSecureServer` gives empty response — confirmed specific to the TLS + HTTP/2 path, plain `http2.createServer` works fine).

Closing in favor of #33072.
