### ISSUE TITLE
vite can't resolve local module in deno workspace from a node project

### ISSUE THREAD

**Issue by cam-mcevenue** [denoland/deno#26138]
Version: Deno 2.0.0

**Reproduction Repo linked below** :
[https://github.com/cam-mcevenue/deno-monorepo-repro/tree/main](https://github.com/cam-mcevenue/deno-monorepo-repro/tree/main)

I am attempting to build a sveltekit project within a deno monorepo. 

I have two directories `apps/web` which contains the sveltekit demo project and `packages/foo` which contains a typescript module for testing. 

```jsonc
// deno.json (root)
{
  "nodeModulesDir": "auto",
  "workspace": ["./packages/foo", "./packages/bar", "./apps/web"],
}
```

This is the deno.json that exports a simple function

```ts
// deno.json (packages/foo)
{
    "name": "@scope/foo",
    "version": "1.0.0",
    "exports": {
        ".": "./mod.ts"
    }
}

// mod.ts
export const hello = (msg: string) => {
  console.log(`Hello, ${msg}!`);
};
```

When I try to import this function into any TS file in my apps/web project, vite errors that it can't resolve the module.

```
Error: Cannot find module '@scope/foo' imported from '/Users/cm/Desktop/repos/playground/deno-repro/apps/web/src/routes/+page.ts'
    at nodeImport (file:///Users/cm/Desktop/repos/playground/deno-repro/node_modules/.deno/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52990:19)
    at ssrImport (file:///Users/cm/Desktop/repos/playground/deno-repro/node_modules/.deno/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52857:22)
    at eval (/Users/cm/Desktop/repos/playground/deno-repro/apps/web/src/routes/+page.ts, <anonymous>:3:50)
    at instantiateModule (file:///Users/cm/Desktop/repos/playground/deno-repro/node_modules/.deno/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52915:11)
```

Deno's LSP can resolve the path, but vite cannot. Is there a vite plugin or any config changes I can make that will allow it to resolve deno local module paths?

**Comment by marvinhagemeister** [comment]
Out of the box `vite` doesn't know about Deno specific resolution. We have a vite plugin for that: https://github.com/denoland/deno-vite-plugin . Does installing it resolve the issue?

**Comment by cam-mcevenue** [comment]
@marvinhagemeister Tried the above without luck. Got the same error, can't be resolved by vite.

I also tried adding alias to the deno.json in the project where the vite.config is and still no luck. Still can't be resolved by the bundler.

```
// deno.json in local sveltekit project directory
{
    "imports": {
        "@scope/foo": "jsr:@scope/foo@1.0.0"
    }
}
```

**Comment by marvinhagemeister** [comment]
Can confirm. The vite plugin calls `deno info` under the hood and that command seems to ignore workspaces. Was able to make a smaller reproduction:

1. Create a `deno.json` with these contents:
  ```json
  {
    "workspace": ["./foo"]
  }
  ```
2. Create folder `foo`
3. Create `./foo/deno.json` with these contents:
  ```json
  {
    "imports": {
      "@std/assert": "jsr:@std/assert@1"
    }
  }
  ```
4. Run `cd foo && deno info @std/assert` -> Error

Debug output:
```sh
DEBUG RS - deno_config::deno_json:779 - Config file found at '/<project>/foo/deno.json'
DEBUG RS - deno_config::deno_json:779 - Config file found at '/<project>/deno.json'
DEBUG RS - deno::args:930 - Finished config loading.
DEBUG RS - deno_config::workspace::resolver:315 - Workspace config generated this import map {
  "scopes": {
    "./foo/": {
      "@std/assert": "jsr:@std/assert@1",
      "@std/assert/": "jsr:/@std/assert@1/"
    }
  }
}
DEBUG RS - deno::cache::cache_db:168 - Opening cache /Users/marvinh/Library/Caches/deno/dep_analysis_cache_v2...
DEBUG RS - import_map:1110 - Specifier "@std/assert" was not mapped in import map.
DEBUG RS - deno::file_fetcher:622 - FileFetcher::fetch_no_follow_with_options - specifier: file:///<project>/foo/@std/assert
error: module could not be found
```

It seems like the `deno info` command only looks at the root `deno.json` and isn't aware that it's in a workspace member.

**Comment by cam-mcevenue** [comment]
@marvinhagemeister so this is an issue with @deno/plugin-vite? Should I link the issue there? Bit of a newb haha thanks for your help

**Comment by marvinhagemeister** [comment]
No need to, this is an issue in Deno itself.

**Comment by umajho** [comment]
Hello, I'm using deno 2.0.4 released 3 days ago, but I still encounter the same issue.

I cloned the reproduction repo in OP, and made these changes:

```diff
diff --git a/apps/web/package.json b/apps/web/package.json
index d16fe38..4712521 100644
--- a/apps/web/package.json
+++ b/apps/web/package.json
@@ -10,6 +10,9 @@
         "lint": "prettier --check . && eslint .",
         "format": "prettier --write ."
     },
+    "dependencies": {
+        "@deno/vite-plugin": "^1.0.0"
+    },
     "devDependencies": {
         "@fontsource/fira-mono": "^5.0.0",
         "@neoconfetti/svelte": "^2.0.0",
diff --git a/apps/web/vite.config.ts b/apps/web/vite.config.ts
index 7f49f02..0fb0c9c 100644
--- a/apps/web/vite.config.ts
+++ b/apps/web/vite.config.ts
@@ -1,8 +1,9 @@
+import deno from "@deno/vite-plugin";
 import { sveltekit } from '@sveltejs/kit/vite';
 import { defineConfig } from 'vite';
 
 export default defineConfig({
-	plugins: [sveltekit()],
+	plugins: [deno(), sveltekit()],
 	server: {
 		fs: {
 			allow: ['../../']
diff --git a/deno.lock b/deno.lock
index 7c62da5..39322e9 100644
--- a/deno.lock
+++ b/deno.lock
@@ -1,6 +1,7 @@
 {
   "version": "4",
   "specifiers": {
+    "npm:@deno/vite-plugin@1": "1.0.0_vite@5.4.8",
     "npm:@fontsource/fira-mono@5": "5.1.0",
     "npm:@neoconfetti/svelte@2": "2.2.1",
     "npm:@sveltejs/adapter-auto@3": "3.2.5_@sveltejs+kit@2.6.3__@sveltejs+vite-plugin-svelte@4.0.0-next.7___svelte@5.0.0-next.262____acorn@8.12.1___vite@5.4.8__svelte@5.0.0-next.262___acorn@8.12.1__vite@5.4.8_@sveltejs+vite-plugin-svelte@4.0.0-next.7__svelte@5.0.0-next.262___acorn@8.12.1__vite@5.4.8_svelte@5.0.0-next.262__acorn@8.12.1_vite@5.4.8",
@@ -46,6 +47,12 @@
         "sisteransi"
       ]
     },
+    "@deno/vite-plugin@1.0.0_vite@5.4.8": {
+      "integrity": "sha512-Q9UeWqs3s7B5lqzu1Z5QrzYAzqTj3+F9YW17tWobGRbT2G40ihwis6zK/+QgMgcG4fm3IqdIfXmpQYhkZpdMfw==",
+      "dependencies": [
+        "vite"
+      ]
+    },
     "@esbuild/aix-ppc64@0.21.5": {
       "integrity": "sha512-1SDgH6ZSPTlggy1yI6+Dbkiz8xzpHJEVAlF/AM1tHPLsf5STom9rwtjE4hKAF20FfXXNTFqEYXyJNWh1GiZedQ=="
     },
@@ -1241,6 +1248,7 @@
         ],
         "packageJson": {
           "dependencies": [
+            "npm:@deno/vite-plugin@1",
             "npm:@fontsource/fira-mono@5",
             "npm:@neoconfetti/svelte@2",
             "npm:@sveltejs/adapter-auto@3",

```

but running with deno 2.0.4, I still got:

```
Cannot find module '@scope/foo' imported from '/private/tmp/deno-monorepo-repro/apps/web/src/routes/+page.ts'
Error: Cannot find module '@scope/foo' imported from '/private/tmp/deno-monorepo-repro/apps/web/src/routes/+page.ts'
    at nodeImport (file:///private/tmp/deno-monorepo-repro/node_modules/.deno/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52990:19)
    at ssrImport (file:///private/tmp/deno-monorepo-repro/node_modules/.deno/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52857:22)
    at eval (/private/tmp/deno-monorepo-repro/apps/web/src/routes/+page.ts, <anonymous>:3:50)
    at instantiateModule (file:///private/tmp/deno-monorepo-repro/node_modules/.deno/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52915:11
```

**Comment by bartlomieju** [comment]
@umajho could you please open a new issue for this problem? If you could link to your repository that would be very helpful 🙏

**Comment by umajho** [comment]
> @umajho could you please open a new issue for this problem? If you could link to your repository that would be very helpful 🙏

Hello, I have opened a new issue (#26721) with reproductions.
