### ISSUE TITLE
Deno 2 compile doesn't work on sveltekit  (error: Module not found runtime/control.js)

### ISSUE THREAD

**Issue by SerJaimeLannister** [denoland/deno#26155]
Version: deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu) (archlinux)
v8 12.9.202.13-rusty
typescript 5.6.2

Running `deno compile` on a sveltekit app returns a `Module not found runtime/control.js` error.

## Steps to reproduce

1. Run `deno -A npm:create-svelte@latest my-app`
1.1. Click on Sveltekit demo app
1.2. Yes using typescript syntax
1.3. Selecting all the 5 options presented in the next step using space bar ) (Add eslint , prettier , vitest etc.)
2. Run `cd my-app`
3. Run `deno install`
4. Run `deno run dev` (shows the expected sveltekit demo app at localhost:5173)
5. Run `deno install npm:svelte-adapter-deno`
6. Update `svelte.config.js` file to use Deno adapter:
  ```js
  // svelte.config.js
  import adapter from 'svelte-adapter-deno';
  
  export default {
    kit: {
      adapter: adapter()
    }
  };
  ```
7. Run `deno run build` to produce build folder and then cd into it (interestingly the last time I ran this it produced a mod.ts file but this time it didn't produce mod.ts I am not exactly sure what has changed since the last time) (this is extremely weird)
8. but still running deno run index.js and giving it the permissions runs the sveltekit demo app
9. Run `deno compile build/server/index.js`

Output:

```sh
error: Module not found "file:///home/test/Projects/deno/my-app/build/runtime/control.js".
    at file:///home/test/Projects/deno/my-app/build/server/index.js:1345:23
```

**Comment by uncomfyhalomacro** [comment]
@SerJaimeLannister may i ask if that's really the content of your file `svelte.config.js`?

**Comment by uncomfyhalomacro** [comment]
Okay. I was able to reproduce. Mine is also looking for `my-app/build/runtime/control.js` hmm

**Comment by uncomfyhalomacro** [comment]
I find this really weird to be honest. see screenshot below

commands used
- `bonk` a touch+mkdir utility


![image](https://github.com/user-attachments/assets/10927488-2e3f-4a4d-8665-9858e27416a5)

**Comment by uncomfyhalomacro** [comment]
Update: I have a feeling it's looking for this????

![image](https://github.com/user-attachments/assets/7ba65f91-49f8-4e78-80fc-2481947f9247)

**Comment by SerJaimeLannister** [comment]
Were you able to fix this @uncomfyhalomacro

**Comment by uncomfyhalomacro** [comment]
> Were you able to fix this @uncomfyhalomacro

Nope. but i found out how to "make it run". Here is what I did
1. `cp -rf '/home/uncomfy/development/projects/.cache/deno/npm/registry.npmjs.org/@sveltejs/kit/2.7.0/src/runtime' runtime`
2. `cp /home/uncomfy/development/projects/.cache/deno/npm/registry.npmjs.org/svelte-eslint-parser/0.41.1/lib/parser/typescript/types.js server/types.js`
3. `mkdir -p server page && cp /home/uncomfy/development/projects/.cache/deno/npm/registry.npmjs.org/svelte-eslint-parser/0.41.1/lib/parser/typescript/types.js server/page/types.js`
5. `deno compila -A index.js && ./build`

![image](https://github.com/user-attachments/assets/9fd769bd-bdde-424f-8d24-e41a8a61dd9b)

**Comment by uncomfyhalomacro** [comment]
Nearly was able to. now time to sleep
![image](https://github.com/user-attachments/assets/7fdef537-48e0-44a7-95ca-cf2037f66aa4)
![image](https://github.com/user-attachments/assets/c4278d4c-d08f-4eb6-a949-a793f59708e4)

**Comment by yazan-abdalrahman** [comment]
@SerJaimeLannister 

I got this error while trying to reproduce the issue.

```
PS D:\yad\deno\my-app> ..\target\debug\deno run dev
Task dev vite dev
error: Unsupported lockfile version '4'. Try upgrading Deno or recreating the lockfile at 'D:\yad\deno\my-app\deno.lock'.
PS D:\yad\deno\my-app>
```

**Comment by SerJaimeLannister** [comment]
Hmm , this is kind of "good enough support" but this isn't enough and though I appreciate your efforts , I don't think this is worth enough to close this issue

Hopefully someone from the deno team can fix this completely

**Comment by yazan-abdalrahman** [comment]
I found the main issue and opened a new ticket (#26233) to make it easier to reproduce.  So, we can close this and proceed with the new (#26233). 

You can do some workarounds for this issue.  Go into index.js and remove each JSDoc comments with `@param` and `import(...)`statement (e.g., `@param {import('./page/types.js').Cookie['options']}`)

That will make the compile successful.

**Comment by luisfcofv** [comment]
Something similar is happening with this dependency: `https://esm.sh/v135/@sanity/client@6.22.1`

**Comment by SerJaimeLannister** [comment]
> I found the main issue and opened a new ticket (#26233) to make it easier to reproduce. So, we can close this and proceed with the new (#26233).
> 
> You can do some workarounds for this issue. Go into index.js and remove each JSDoc comments with `@param` and `import(...)`statement (e.g., `@param {import('./page/types.js').Cookie['options']}`)
> 
> That will make the compile successful.

Hey so I did try to remove the as a workaround and it still doesn't work , do I need to remove this jsdoc comment + import on each file of my project?

**Comment by yazan-abdalrahman** [comment]
> jsdoc comment + import on
I removed each `'@param {import(' `from `'build/server/index.js`' and it worked when I compiled it.

**Comment by yazan-abdalrahman** [comment]
Oh, I found a solution. It's not a bug.  

Use ` --no-check `  in compile to skip checking the` jsdoc`.

`deno compile  --no-check  build/server/index.js`

**Comment by SerJaimeLannister** [comment]
Also I think deno should give a warning / custom flag that hey you should do  --no-check  like how it does for --unstable-sloppy-imports and even then as in the recent issue by @marvinhagemeister  (I know this is amature but I tried looking for the issue but I couldn't find the issue created by marvin for --unstable-sloppy-imports) but If I remember correctly it was about asking at the runtime to enable unstable-sloppy-imports.

I think something like this should also be done with deno compile --no-check

also , fixing the issue as of the video could be of some priority

**Comment by yazan-abdalrahman** [comment]
> Version: deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu) (archlinux) v8 12.9.202.13-rusty typescript 5.6.2
> 
> Running `deno compile` on a sveltekit app returns a `Module not found runtime/control.js` error.
> 
> ## Steps to reproduce
> 1. Run `deno -A npm:create-svelte@latest my-app`
>    1.1. Click on Sveltekit demo app
>    1.2. Yes using typescript syntax
>    1.3. Selecting all the 5 options presented in the next step using space bar ) (Add eslint , prettier , vitest etc.)
> 2. Run `cd my-app`
> 3. Run `deno install`
> 4. Run `deno run dev` (shows the expected sveltekit demo app at localhost:5173)
> 5. Run `deno install npm:svelte-adapter-deno`
> 6. Update `svelte.config.js` file to use Deno adapter:
> 
> ```js
> // svelte.config.js
> import adapter from 'svelte-adapter-deno';
> 
> export default {
>   kit: {
>     adapter: adapter()
>   }
> };
> ```
> 
> 7. Run `deno run build` to produce build folder and then cd into it (interestingly the last time I ran this it produced a mod.ts file but this time it didn't produce mod.ts I am not exactly sure what has changed since the last time) (this is extremely weird)
> 8. but still running deno run index.js and giving it the permissions runs the sveltekit demo app
> 9. Run `deno compile build/server/index.js`
> 
> Output:
> 
> ```shell
> error: Module not found "file:///home/test/Projects/deno/my-app/build/runtime/control.js".
>     at file:///home/test/Projects/deno/my-app/build/server/index.js:1345:23
> ```
I thought your issue in compile (step 9) gives you this error. 
```
error: Module not found "file:///home/test/Projects/deno/my-app/build/runtime/control.js".
    at file:///home/test/Projects/deno/my-app/build/server/index.js:1345:23
```
and that is mentioned on the label of bug `compile`



So, to get build without error module not found (that's error occurs in import in commented JSdoc, it's not bug), use `--no-check` with the compile command

**Comment by yazan-abdalrahman** [comment]
> Also I think deno should give a warning / custom flag that hey you should do --no-check like how it does for --unstable-sloppy-imports and even then as in the recent issue by @marvinhagemeister (I know this is amature but I tried looking for the issue but I couldn't find the issue created by marvin for --unstable-sloppy-imports) but If I remember correctly it was about asking at the runtime to enable unstable-sloppy-imports.
> 
> I think something like this should also be done with deno compile --no-check
> 
> also , fixing the issue as of the video could be of some priority

I thought an outside bug was the major issue in compile, which was resolved with --no-check.

**Comment by yazan-abdalrahman** [comment]
@dsherret

**Comment by SerJaimeLannister** [comment]
oh I see I have to admit my mistake here
to compile the sveltekit project we need to actually build by changing the adapter
and then compiling build/index.js should atleast make it work though with some issues (instead of build/server/index.js) (this was my first time writing reproducible bug so I am sorry )

**Comment by SerJaimeLannister** [comment]
@yazan-abdalrahman  please check the video that I provided , it shows this error 
```
Error: Not found: /
    at resolve2 (file:///tmp/deno-compile-build/my-app/build/server/index.js:4831:18)
    at resolve (file:///tmp/deno-compile-build/my-app/build/server/index.js:4664:34)
    at Object.handle (file:///tmp/deno-compile-build/my-app/build/server/index.js:4896:71)
    at respond (file:///tmp/deno-compile-build/my-app/build/server/index.js:4662:43)
    at eventLoopTick (ext:core/01_core.js:175:7) {
  status: 404,
  text: "Not Found"
}
```

**Comment by yazan-abdalrahman** [comment]
That is the mentioned issue and his solution; I can't understand what a current issue, can provide further details. 
https://github.com/user-attachments/assets/133aa3b7-40b0-4888-94b6-30277feb5190

**Comment by SerJaimeLannister** [comment]
instead of deno compile build/server/index.js , you have to try deno compile --no-check build/index.js for it to have web app also 

also , even when you do that it shows an error on the first reload probably related to how deno runtime probably gets loaded into tmp for the first time

**Comment by SerJaimeLannister** [comment]
Also a minor nitpick for which I am not sure deserves a full issue is currently we need to use https://github.com/pluvial/svelte-adapter-deno or something along this line & change svelte.config.js because the svelte-adapter-auto doesn't have a default runtime for deno , but this only adds friction I suppose , maybe with deno 2.0 , we can get automatic support for deno in sveltekit?

**Comment by yazan-abdalrahman** [comment]
Sorry, I couldn't find any errors; maybe I misunderstood your requirements, but I believe you had an issue that was not caused by `deno compile`.



https://github.com/user-attachments/assets/a668d2de-0626-41c0-bb34-fe4a81fbd756

We should mention deno member; it will be more helpful in clarifying the situation. 

@bartlomieju @dsherret

**Comment by mindon** [comment]
something is wrong with fresh 2.0 built under deno 2.0.1 , it's ok under deno 2.0.0
https://github.com/denoland/fresh/issues/2714

**Comment by opensas** [comment]
I have the same issue as @yazan-abdalrahman 

I do the build, but when I run `deno run build/server/index.js` nothing happens, and obviously after compiling it with `deno run build/server/index.js` I run `./server` and nohting happens either

**Comment by dsherret** [comment]
I haven't tested it, but there's a chance it might be fixed in canary (`deno upgrade canary`)

**Comment by opensas** [comment]
ok, the problem was that we had to compile the `build/index.js` file instead of the `build/server/index.js` file

I also had to add a couple settings, like this:

```shell
$ deno compile --no-check --output server --allow-env --allow-net --unstable-node-globals build/index.js

$ ./server 
Listening on 0.0.0.0:3000
```

but when I browse the page I get a `handler is not a function` error:

```shell
$ curl -v localhost:3000
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< vary: Accept-Encoding
< transfer-encoding: chunked
< date: Sat, 23 Nov 2024 06:17:56 GMT
< 
* Connection #0 to host localhost left intact
handler is not a function
```

**Comment by opensas** [comment]
Here I'll try to document every step taken to ease reproduction

```shell
$ deno run -A --reload npm:sv create sveltekit-deno-app

$ deno run -A --reload npm:sv create sveltekit-deno-app
┌  Welcome to the Svelte CLI! (v0.6.5)
│
◇  Which template would you like?
│  SvelteKit demo
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  prettier, eslint
│
◇  Which package manager do you want to install dependencies with?
│  None

$ cd sveltekit-deno-app/

$ deno install --allow-scripts=npm:@sveltejs/kit@2.8.1

$ deno run dev (works ok)

$ deno install npm:svelte-adapter-deno
```

update svelte.config.js

```javascript
// import adapter from '@sveltejs/adapter-auto';
import adapter from 'svelte-adapter-deno';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

[...]
```


```shell
$ deno run build

$ deno compile --no-check --output server --allow-env --allow-net --unstable-node-globals build/index.js

$ ll -h server
-rwxr-xr-x 1 sas sas 174M Nov 23 15:51 server*

$ ./server 
Listening on http://0.0.0.0:3000
```

And I get this:

![image](https://github.com/user-attachments/assets/15bfdacf-03ea-4d46-9882-f1eda777ca3c)

it seems like all the assets are not being found

![image](https://github.com/user-attachments/assets/94deb478-a442-4828-b0f2-a01812c2189b)


If I run it like this:

```shell
$ deno run --allow-env --allow-read --allow-net build/index.js 
Listening on http://0.0.0.0:3000
```

it works ok

![image](https://github.com/user-attachments/assets/60b30c44-0bb9-43d0-8270-702effb0d7b0)

so it must be a problem with the compile command

**Comment by SerJaimeLannister** [comment]
Hmm very interesting , I tried to do what I had done earlier to get it to working and I also have gotten this same issue 

![image](https://github.com/user-attachments/assets/5ed8109a-9a32-44c0-bfbf-3517d58d252a)

My interest has been piqued once again. (I was so close to closing this issue) 

It is showing this in the logs which made me realise that this might be the fault of the compiler and not the adapter  https://github.com/pluvial/svelte-adapter-deno because I thought that the adapter hadn't been made compatible with the 5.0 release , but this error points to some compile issue 

Error: Not found: /
    at resolve2 (file:///tmp/deno-compile-binary/my-app/build/server/index.js:4194:18)
    at resolve (file:///tmp/deno-compile-binary/my-app/build/server/index.js:4027:34)
    at Object.handle (file:///tmp/deno-compile-binary/my-app/build/server/index.js:4262:71)
    at respond (file:///tmp/deno-compile-binary/my-app/build/server/index.js:4025:43)
    at eventLoopTick (ext:core/01_core.js:175:7) {
  status: 404,
  text: "Not Found"
}
Error: Not found: /favicon.png
    at resolve2 (file:///tmp/deno-compile-binary/my-app/build/server/index.js:4194:18)
    at resolve (file:///tmp/deno-compile-binary/my-app/build/server/index.js:4027:34)
    at Object.handle (file:///tmp/deno-compile-binary/my-app/build/server/index.js:4262:71)
    at respond (file:///tmp/deno-compile-binary/my-app/build/server/index.js:4025:43)
    at eventLoopTick (ext:core/01_core.js:175:7) {
  status: 404,
  text: "Not Found"
}
ls

**Comment by SerJaimeLannister** [comment]
Another thing to note is that deno doesn't work with the default database / authentication (lucia) example provided by sveltekit because sqllite node remapping isn't done or an error like this was shown , but I think it belongs in different issue

**Comment by Hugo-Dz** [comment]
Same issue here, unable to fetch assets / css files `404`. I use the Node adapter since it works out of the box with Deno 2.

**Comment by oneezy** [comment]
hopefully can get a working [Svelte example](https://github.com/denoland/examples/issues/31) up soon:

https://github.com/denoland/examples/issues/31

**Comment by opensas** [comment]
latest svelte `sv` version seems to support deno out of the box, but the issue still applies

in bun I see the same behavior, please check: https://github.com/oven-sh/bun/issues/15734

I guess it would be the same solution for both....

**Comment by nicola02nb** [comment]
Issue applies also to me with both `deno` and `bun`

**Comment by Hugo-Dz** [comment]
Built my own [adapter](https://github.com/Hugo-Dz/exe) to solve this. Using Bun though, but it can compile full-stack SvelteKit apps as a single binary executable (with all Kit features such as SSR, API endpoints, server hooks, remote functions...)

**Comment by opensas** [comment]
> Built my own [adapter](https://github.com/Hugo-Dz/exe) to solve this. Using Bun though, but it can compile full-stack SvelteKit apps as a single binary executable (with all Kit features such as SSR, API endpoints, server hooks, remote functions...)

This is great! I'm starring it and will definitely give it a try, and I hope deno devs could have a look at it so we can have deno compile sveltekit apps out of the box
