### ISSUE TITLE
Strange error message if you typo a remote package URL in a single-file script

### ISSUE THREAD

**Issue by Benaiah** [denoland/deno#26169]
Version: Deno 2.0.0

Detailed version info:

```
deno 2.0.0 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

---

Running `deno index.ts` with a clean cache (ran `deno clean` immediately before) in a directory containing only `index.ts` with the following contents:

```ts
import { DB } from "https://deno.land/x/sqlite@3.9.1/mod.ts"
```

(note: the `sqlite@3.9.1` instead of `sqlite@v3.9.1` is intentional; that's what triggers this strange and misleading error)

...results in the following error:

```sh
deno-experiments % deno -A index.ts
error: unrecognized subcommand

  tip: some similar subcommands exist: 'init', 'lint'
```

**Comment by tobylai-toby** [comment]
try deno run xxx

**Comment by yazan-abdalrahman** [comment]
```
PS D:\yad\deno> .\target\debug\deno -A  .\main.ts
error: Module not found "https://deno.land/x/sqlite@3.9.1/mod.ts".
    at file:///D:/yad/deno/main.ts:1:20
PS D:\yad\deno> .\target\debug\deno run -A  .\main.ts
error: Module not found "https://deno.land/x/sqlite@3.9.1/mod.ts".
    at file:///D:/yad/deno/main.ts:1:20
PS D:\yad\deno> 
```
I think it works; it is not a bug.

**Comment by lucacasonato** [comment]
I can not reproduce it, but I believe you this bug exists. The cause is likely in how we handle `deno main.ts` compared to `deno run main.ts`. Relevant code that is likely broken is https://github.com/denoland/deno/blob/afb33b3c2597c9ec943f71218b236486fbc86e23/cli/main.rs#L219.

**Comment by bartlomieju** [comment]
This no longer reproduces on the latest `main` (6048a0d9f). The error message is now correct:

```
Download https://deno.land/x/sqlite@3.9.1/mod.ts
error: Module not found "https://deno.land/x/sqlite@3.9.1/mod.ts".
    at file:///tmp/repro-26169/index.ts:1:20
```

Instead of the misleading `unrecognized subcommand` error, Deno now properly reports the module as not found with the source location. This was likely fixed as part of other error handling improvements since 2.0.0.

**Comment by bartlomieju** [comment]
Confirmed that the `deno index.ts` path (without explicit `run` subcommand) also works correctly now — both `deno index.ts` and `deno -A index.ts` produce the proper `Module not found` error instead of the misleading `unrecognized subcommand` message.
