### ISSUE TITLE
Unable to start Slack Bolt application server

### ISSUE THREAD

**Issue by ValorHeart** [denoland/deno#26182]
Version: Deno 2.0.0
```
Task start deno run --allow-sys --allow-read --allow-env --allow-net ./src/app.ts
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
Warning: Not implemented: ClientRequest.options.createConnection
⚡️ Bolt app is running! ⚡️
error: Uncaught (in promise) Error: Unhandled event 'server explicit disconnect' in state 'connecting'.
    at StateMachine.handleUnhandledEvent (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/finity/0.5.4/lib/core/StateMachine.js:76:13)
    at file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/finity/0.5.4/lib/core/HierarchicalStateMachine.js:79:33
    at TaskScheduler.execute (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/finity/0.5.4/lib/core/TaskScheduler.js:29:7)
    at TaskScheduler.enqueue (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/finity/0.5.4/lib/core/TaskScheduler.js:19:12)
    at HierarchicalStateMachine.handle (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/finity/0.5.4/lib/core/HierarchicalStateMachine.js:72:24)
    at SocketModeClient.onWebSocketMessage (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/@slack/socket-mode/1.3.6/dist/SocketModeClient.js:608:31)
    at WebSocket.onMessage (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/ws/7.5.10/lib/event-target.js:132:16)
    at WebSocket.emit (ext:deno_node/_events.mjs:393:28)
    at Receiver.receiverOnMessage (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/ws/7.5.10/lib/websocket.js:1070:20)
    at Receiver.emit (ext:deno_node/_events.mjs:393:28)
```

**Comment by reygarcia-develops** [comment]
> Version: Deno 2.0.0
> 
> ```
> Task start deno run --allow-sys --allow-read --allow-env --allow-net ./src/app.ts
> [INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
> Warning: Not implemented: ClientRequest.options.createConnection
> ⚡️ Bolt app is running! ⚡️
> error: Uncaught (in promise) Error: Unhandled event 'server explicit disconnect' in state 'connecting'.
>     at StateMachine.handleUnhandledEvent (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/finity/0.5.4/lib/core/StateMachine.js:76:13)
>     at file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/finity/0.5.4/lib/core/HierarchicalStateMachine.js:79:33
>     at TaskScheduler.execute (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/finity/0.5.4/lib/core/TaskScheduler.js:29:7)
>     at TaskScheduler.enqueue (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/finity/0.5.4/lib/core/TaskScheduler.js:19:12)
>     at HierarchicalStateMachine.handle (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/finity/0.5.4/lib/core/HierarchicalStateMachine.js:72:24)
>     at SocketModeClient.onWebSocketMessage (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/@slack/socket-mode/1.3.6/dist/SocketModeClient.js:608:31)
>     at WebSocket.onMessage (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/ws/7.5.10/lib/event-target.js:132:16)
>     at WebSocket.emit (ext:deno_node/_events.mjs:393:28)
>     at Receiver.receiverOnMessage (file:///Users/adi/Library/Caches/deno/npm/registry.npmjs.org/ws/7.5.10/lib/websocket.js:1070:20)
>     at Receiver.emit (ext:deno_node/_events.mjs:393:28)
> ```

Were you able to resolve this? I was looking at rewriting one of my slack bolt apps with deno rather than express.

**Comment by ValorHeart** [comment]
Hey @reygarcia-develops, the Deno team needs to implement that API which exists at NodeJS; I've found it related to this issue: https://github.com/denoland/deno/issues/19507

**Comment by bartlomieju** [comment]
`ClientRequest.options.createConnection` is now fully implemented (the "Not implemented" warning is gone). The `createConnection` option is properly supported both in the agent-less path and when bypassing the default agent.

Without a Slack API token we can't verify the full end-to-end Slack Bolt scenario, but the underlying cause of this issue has been addressed. If anyone using `@slack/bolt` with Socket Mode can confirm it works now, we can close this.

**Comment by bartlomieju** [comment]
With #25470 and https://github.com/denoland/deno/pull/33208 landed I'm confident this is now fixed.
