### ISSUE TITLE
Typechecking fails unexpectedly when using manual nodeModulesDir

### ISSUE THREAD

**Issue by redabacha** [denoland/deno#26222]
Version: Deno 2.0.0

clone [this repo](https://github.com/redabacha/react-deno-typecheck-error) and run `deno check test.tsx`. the command fails with the error:
```
error: Failed resolving types. [ERR_TYPES_NOT_FOUND] Could not find types for 'file:///home/reda/Documents/Projects/react-deno-typecheck-error/node_modules/.deno/react-dom@18.3.1/node_modules/react-dom/client.js' imported from 'file:///home/reda/Documents/Projects/react-deno-typecheck-error/test.tsx'
    at file:///home/reda/Documents/Projects/react-deno-typecheck-error/test.tsx:1:28
```
which is strange as when you run the same command with `--node-modules-dir=none` or `--node-modules-dir=auto` it works normally.

output when running with `RUST_BACKTRACE=1`:
```
❯ RUST_BACKTRACE=1 deno check test.tsx
error: Failed resolving types. [ERR_TYPES_NOT_FOUND] Could not find types for 'file:///home/reda/Documents/Projects/react-deno-typecheck-error/node_modules/.deno/react-dom@18.3.1/node_modules/react-dom/client.js' imported from 'file:///home/reda/Documents/Projects/react-deno-typecheck-error/test.tsx'
    at file:///home/reda/Documents/Projects/react-deno-typecheck-error/test.tsx:1:28

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: deno_core::error::custom_error
   2: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
   3: deno::graph_util::graph_valid
   4: deno::module_loader::ModuleLoadPreparer::prepare_module_load::{{closure}}
   5: deno::graph_container::MainModuleGraphContainer::check_specifiers::{{closure}}
   6: deno::spawn_subcommand::{{closure}}
   7: <deno_unsync::tokio::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   8: tokio::runtime::task::raw::poll
   9: deno::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: main
  14: __libc_start_call_main
  15: __libc_start_main_alias_1
  16: _start
```

**Comment by redabacha** [comment]
this seems to be resolved in later deno versions, closing this.
