### ISSUE TITLE
Deno 2.0.0: Compilation Fails When Import in JSDoc @param Tries to Resolve Non-Existent Module"

### ISSUE THREAD

**Issue by yazan-abdalrahman** [denoland/deno#26233]
Version: Deno 2.0.0 (stable, release, x86_64-pc-windows-msvc)
v8 12.9.202.13-rusty
typescript 5.6.2

**Description:**
In Deno 2.0.0 , when compiling a script that includes JSDoc comments with `@param` and an` import(...) `statement (e.g., `@param {import('./page/types.js').Cookie['options']}`), Deno incorrectly attempts to resolve the module specified in the comment. If the referenced module does not exist, it results in a "Module not found" error, even though this reference should only be used for documentation and type-checking purposes.

This issue occurs during compilation but not in earlier versions like Deno 1.46.3, where the script compiles without any errors, ignoring the JSDoc import.

**Steps to Reproduce:**

1. Create a `main.js` file with the following content:
```
//main.js

console.log("test_1");

class Test {
  /**
   * @param {string} name
   *  @param {import('./page/types.js').Cookie['options']} options
   */
  test(name, options2) {
    console.log(name);
    console.log(options2);
  }
}

console.log("test_2");
```

2. Compile the script:
` deno compile .\main.js`

**Expected Behavior:**
Deno should ignore JSDoc imports used for type-checking and not attempt to resolve or load the referenced module during compilation, especially if it doesn't exist.

**Actual Behavior:**
Deno 2.0.0 tries to resolve the module in the @param JSDoc comment, causing a "Module not found" error when the module does not exist.

**Reproduce Issue logs:**
```
PS D:\yad\deno> cat .\main.js
//main.js

console.log("test_1");

class Test {
  /**
   * @param {string} name
   *  @param {import('./page/types.js').Cookie['options']} options
   */
  test(name, options2) {
    console.log(name);
    console.log(options2);
  }
}

console.log("test_2");
PS D:\yad\deno> 
PS D:\yad\deno> deno --version 
deno 2.0.0 (stable, release, x86_64-pc-windows-msvc)
v8 12.9.202.13-rusty
typescript 5.6.2
PS D:\yad\deno> 
PS D:\yad\deno> 
PS D:\yad\deno> deno compile .\main.js
error: Module not found "file:///D:/yad/deno/page/types.js".
    at file:///D:/yad/deno/main.js:8:22
PS D:\yad\deno> 
```

**Deno1.46.3 (Working case):**
```
PS D:\yad\deno> deno upgrade --version 1.46.3
Current Deno version: v2.0.0
Downloading https://github.com/denoland/deno/releases/download/v1.46.3/deno-x86_64-pc-windows-msvc.zip
Deno is upgrading to version 1.46.3

Upgraded successfully to Deno v1.46.3 (stable)

Release notes:

  https://github.com/denoland/deno/releases/tag/v1.46.3

Blog post:

  https://deno.com/blog/v1.46

PS D:\yad\deno> 
PS D:\yad\deno>
PS D:\yad\deno> deno compile .\main.js       
Compile file:///D:/yad/deno/main.js to deno.exe
PS D:\yad\deno> 
```

**Comment by yazan-abdalrahman** [comment]
@bartlomieju

**Comment by yazan-abdalrahman** [comment]
Oh, I found a solution. It's not a bug.

Use` --no-check` in compile to skip checking the jsdoc.

```
PS D:\yad\deno> .\target\debug\deno compile .\main.js
error: Module not found "file:///D:/yad/deno/page/types.js".
    at file:///D:/yad/deno/main.js:8:24
PS D:\yad\deno> .\target\debug\deno compile --no-check .\main.js
Compile file:///D:/yad/deno/main.js to deno.exe
PS D:\yad\deno> 
```
