### ISSUE TITLE
Error when trying to run a jest set of tests panicked at ext\node\global.rs:286:56: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by jdmerinor** [denoland/deno#26290]
Hi guys,

I was trying to run the jest tests of a solution we have at work and I keep getting this consistently.

PS C:\git\wtg\Glow\Glow\DotNet\HTML\Client\Client> deno run test
Task test jest

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 2.0.0
Args: ["C:\\Users\\Jd.Merino\\.deno\\bin\\deno.exe", "run", "--ext=js", "-A", "C:\\git\\wtg\\Glow\\Glow\\DotNet\\HTML\\Client\\Client\\node_modules\\.bin\\../jest/bin/jest.js"]

thread 'main' panicked at ext\node\global.rs:286:56:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ff69e01a20d - node_api_get_module_file_name
   1:     0x7ff69c7fbee9 - node_api_get_module_file_name
   2:     0x7ff69dff7321 - node_api_get_module_file_name
   3:     0x7ff69e01e0c6 - node_api_get_module_file_name
   4:     0x7ff69e01d98a - node_api_get_module_file_name
   5:     0x7ff69e01d541 - node_api_get_module_file_name
   6:     0x7ff69c659a13 - uv_close
   7:     0x7ff69e01e467 - node_api_get_module_file_name
   8:     0x7ff69e01e2c9 - node_api_get_module_file_name
   9:     0x7ff69e01e24f - node_api_get_module_file_name
  10:     0x7ff69e01e238 - node_api_get_module_file_name
  11:     0x7ff69fb56dc4 - tree_sitter_javascript
  12:     0x7ff69fb56f5d - tree_sitter_javascript
  13:     0x7ff69fb5739e - tree_sitter_javascript
  14:     0x7ff69cf503fc - node_api_get_module_file_name
  15:     0x7ff69cf4dd45 - node_api_get_module_file_name
  16:     0x7ff69e42c5bf - node_api_get_module_file_name
  17:     0x7ff69e4222e4 - node_api_get_module_file_name
  18:     0x7ff69e42a44f - node_api_get_module_file_name
  19:     0x7ff69e4020bc - node_api_get_module_file_name
  20:     0x7ff69e9c9d4a - CrashForExceptionInNonABICompliantCodeRange
  21:     0x7ff69e9d21c1 - CrashForExceptionInNonABICompliantCodeRange
  22:     0x7ff69f7fee7a - CrashForExceptionInNonABICompliantCodeRange
  23:     0x7ff69f8ea184 - CrashForExceptionInNonABICompliantCodeRange
  24:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  25:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  26:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  27:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  28:     0x7ff61f9cbb31 - <unknown>
  29:     0x7ff61f9cbf63 - <unknown>
  30:     0x7ff61f9cc251 - <unknown>
  31:     0x7ff61f9ca2af - <unknown>
  32:     0x7ff61f9c2c85 - <unknown>
  33:     0x7ff61f9c2e4f - <unknown>
  34:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  35:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  36:     0x7ff61f9cbb31 - <unknown>
  37:     0x7ff61f9cbf63 - <unknown>
  38:     0x7ff61f9cc251 - <unknown>
  39:     0x7ff61f9ca2af - <unknown>
  40:     0x7ff61f9c2c85 - <unknown>
  41:     0x7ff61f9c2e4f - <unknown>
  42:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  43:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  44:     0x7ff61f9cbb31 - <unknown>
  45:     0x7ff61f9cbf63 - <unknown>
  46:     0x7ff61f9cc251 - <unknown>
  47:     0x7ff61f9ca2af - <unknown>
  48:     0x7ff61f9c2c85 - <unknown>
  49:     0x7ff61f9c2e4f - <unknown>
  50:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  51:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  52:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  53:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  54:     0x7ff69f833b4a - CrashForExceptionInNonABICompliantCodeRange
  55:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  56:     0x7ff69f83812c - CrashForExceptionInNonABICompliantCodeRange
  57:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  58:     0x7ff69f75db9e - CrashForExceptionInNonABICompliantCodeRange
  59:     0x7ff69f79e777 - CrashForExceptionInNonABICompliantCodeRange
  60:     0x7ff69f87ea75 - CrashForExceptionInNonABICompliantCodeRange
  61:     0x7ff69f78d14f - CrashForExceptionInNonABICompliantCodeRange
  62:     0x7ff69f75b5ef - CrashForExceptionInNonABICompliantCodeRange
  63:     0x7ff69e5299f4 - node_api_get_module_file_name
  64:     0x7ff69e52a605 - node_api_get_module_file_name
  65:     0x7ff69e52a80b - node_api_get_module_file_name
  66:     0x7ff69e6bab95 - CrashForExceptionInNonABICompliantCodeRange
  67:     0x7ff69e6ba991 - CrashForExceptionInNonABICompliantCodeRange
  68:     0x7ff69e4a8d45 - node_api_get_module_file_name
  69:     0x7ff69e3b1f10 - node_api_get_module_file_name
  70:     0x7ff69e3b1abd - node_api_get_module_file_name
  71:     0x7ff69e39e460 - node_api_get_module_file_name
  72:     0x7ff69cff2fae - node_api_get_module_file_name
  73:     0x7ff69c624f4d - uv_close
  74:     0x7ff69c5c867c - uv_close
  75:     0x7ff69c643aa4 - uv_close
  76:     0x7ff69c005e0d - uv_mutex_destroy
  77:     0x7ff69c7267b5 - node_api_get_module_file_name
  78:     0x7ff69c1598df - uv_mutex_destroy
  79:     0x7ff69c65c07c - uv_close
  80:     0x7ff69bfd221f - uv_mutex_destroy
  81:     0x7ff69c726896 - node_api_get_module_file_name
  82:     0x7ff69faf8c8c - tree_sitter_javascript
  83:     0x7ff9f41f257d - BaseThreadInitThunk
  84:     0x7ff9f5a4af08 - RtlUserThreadStart

**Comment by bartlomieju** [comment]
Unable to reproduce on current `main`. The panic at `ext/node/global.rs:286` (`.unwrap()` on `None`) has been fixed — Jest runs successfully via Deno without panicking.

Tested with a basic Jest test setup running through `deno run -A node_modules/.bin/jest` — tests pass without any crash.

If anyone can still reproduce on a recent Deno version, please reopen.
