### ISSUE TITLE
Deno compile could not resolve `fork` in a right way maybe?

### ISSUE THREAD

**Issue by Cufoon** [denoland/deno#26304]
# Version
```
deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2
```
# Problem Description
Suppose there are two files main.js and echo.js
I use `fork` of `node:child_process` to fork `echo.js` in `main.js` and then use
`createServer` of `node:net` to create a socket server and listen at `127.0.0.1:7788`,
=== 1. It will be working well if I just run `deno run -A main.js`
```bash
cus :: ~/app/tttttttttttt » deno run -A main.js
Listening on 127.0.0.1:7788
hello
hello
```
=== 2. But if I use `deno compile -A` and then run the executable file, `EADDRINUSE` will happen.
server
```
cus :: ~/app/tttttttttttt » ./main
Listening on 127.0.0.1:7788
error: Uncaught Error: listen EADDRINUSE: address already in use 127.0.0.1:7788
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_uvExceptionWithHostPort (ext:deno_node/internal/errors.ts:124:10)
    at Server._setupListenHandle [as _listen2] (node:net:1180:16)
    at _listenInCluster (node:net:1012:12)
    at doListen (node:net:1022:7)
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:39:15)
    at eventLoopTick (ext:core/01_core.js:172:29)
error: Uncaught Error: Channel closed
    at ChildProcess.target.send (ext:deno_node/internal/child_process.ts:1185:19)
    at Server.<anonymous> (file:///tmp/deno-compile-main/tttttttttttt/main.js:12:9)
    at Server.emit (ext:deno_node/_events.mjs:393:28)
    at TCP._onconnection (node:net:1127:8)
    at TCP.#accept (ext:deno_node/internal_binding/tcp_wrap.ts:356:12)
    at eventLoopTick (ext:core/01_core.js:175:7)
cus :: ~/app/tttttttttttt 1 »
```
client
```
~ » telnet 127.0.0.1 7788
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
```
It looks that `deno compile` could not make fork and listen work together.
# Minimal Reproducible Implementation
echo.js
```js
import process from 'node:process';

let shouldQuit = false;

process.on('message', (data) => {
  if (data.action === 'quit') {
    shouldQuit = true;
    return;
  }
  if (data.action === 'request') {
    process.send({ action: 'response', data: data.data });
  }
});

(async () => {
  while (true) {
    if (shouldQuit) {
      break;
    }
    await new Promise((rs) => {
      setTimeout(() => {
        rs();
      }, 1004);
    });
  }
})();
```

main.js
```js
import { fork } from 'node:child_process';
import { createServer } from 'node:net';

const child = fork('./echo.js');
child.on('message', (data) => {
  if (data.action === 'response') {
    console.log(data.data);
  }
});

const server = createServer((localSocket) => {
  child.send({ action: 'request', data: 'hello' });
  localSocket.write('You connected, and you disconnect now.\n');
  localSocket.destroy();
});

const LOCAL_PORT = 7788;

server.listen(LOCAL_PORT, '127.0.0.1', () => {
  console.log(`Listening on 127.0.0.1:${LOCAL_PORT}`);
});
```

**Comment by bartlomieju** [comment]
@Cufoon are you experiencing the same problem on latest Deno (2.1.3)?

**Comment by Cufoon** [comment]
> @Cufoon are you experiencing the same problem on latest Deno (2.1.3)?

No, It keeps error even in version 2.1.4.
![QQ20241214-223656](https://github.com/user-attachments/assets/cb21a4fc-6fb8-4ba2-a561-d14afe2a24d9)

**Comment by svenemtell** [comment]
I get the same problem using Deno 2.2.11 on macOS 15.4.
It seems like the compiled program tries to start main.js a second time instead of starting echo.js.
Here is my printout after adding _console.log('starting server')_ at the beginning of main.js:
 
```
% ./fork-test 
starting server
Listening on 127.0.0.1:7788
starting server
error: Uncaught Error: listen EADDRINUSE: address already in use 127.0.0.1:7788
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_uvExceptionWithHostPort (ext:deno_node/internal/errors.ts:124:10)
    at Server._setupListenHandle [as _listen2] (node:net:1488:16)
    at _listenInCluster (node:net:1318:12)
    at doListen (node:net:1330:7)
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:39:15)
    at eventLoopTick (ext:core/01_core.js:175:29)
```
