### ISSUE TITLE
Deno + Vite: cannot resolve deno dependencies

### ISSUE THREAD

**Issue by WerdoxDev** [denoland/deno#26319]
Version: Deno 2.0.0 & Deno 2.0.0-f94cdd1

I have followed both docs on creating a vite app with react:
- https://docs.deno.com/deploy/tutorials/vite/
- https://docs.deno.com/runtime/tutorials/how_to_with_npm/react/

Both tutorials work until you add a package. for example `@std/text` from `jsr`.
The first one uses a third-party vite template which fully uses a `deno.json` file.
The second one simply uses the `package.json`.

If the package is added through `deno.json`, It kind of gets the `mod.ts` file of the package and nothing more. so it prints an error pointing to the first `export * from "..."` line. in this case for `@std/text` it's the [levenshtein_distance.ts](https://github.com/denoland/std/blob/45be5d319dde70c3901ca24294936e95a8a7f0be/text/mod.ts#L22C1-L22C43) file.

And if the package is added through `package.json`, it simply fails with `Failed to resolve "package"`

I'm even using the deno's official [deno-vite-plugin](https://github.com/denoland/deno-vite-plugin) which should resolve `jsr`, `node`, `https` packages. But one thing I noticed is that inside the code some of the types have V1 in their name which may indicate the package is not updated for version 2.0.0 [here](https://github.com/denoland/deno-vite-plugin/blob/895724634320eb5946c8c606f2e6f342976b4c0c/src/resolver.ts#L38)

Here is a reproduction repo using the `deno.json` method: https://github.com/WerdoxDev/deno-vite-bug

**Comment by marvinhagemeister** [comment]
> I noticed is that inside the code some of the types have V1 in their name which may indicate the package is not updated for version 2.0.0 [here](https://github.com/denoland/deno-vite-plugin/blob/895724634320eb5946c8c606f2e6f342976b4c0c/src/resolver.ts#L38)

FYI: The format of the output of `deno info --json` hasn't changed with Deno 2. That version you linked there is not related to the Deno version itself.

**Comment by nathanwhit** [comment]
I can't reproduce the issue in the repo that's linked. It runs without errors on my machine (macOS). What OS are you using?

**Comment by WerdoxDev** [comment]
I'm on windows 11

**Comment by WerdoxDev** [comment]
For more info, here is the full error I get from a clean clone of the repo
![image](https://github.com/user-attachments/assets/d8ca780e-1134-4d30-a17a-463bd6b274fa)

**Comment by marvinhagemeister** [comment]
That sounds like the same error as in https://github.com/denoland/deno/issues/26343

**Comment by WerdoxDev** [comment]
> That sounds like the same error as in #26343

Nope, Just downgraded to 2.0.0. The BadResource error goes away but the main issue is still there.
![image](https://github.com/user-attachments/assets/97d60945-5fbb-4b4c-8b0b-70c3f23ad892)

**Comment by mattgi** [comment]
@WerdoxDev did u ever get this solved? I am having the same issue. I am using a workspace with a deno api and basic vite+react app. I add all dependencies into the root deno.json imports. but get the above error from vite on the app.

**Comment by petamoriken** [comment]
Probably this issue will be fixed when https://github.com/denoland/deno-vite-plugin/pull/68 is merged.

**Comment by bartlomieju** [comment]
This works correctly when using the official `@deno/vite-plugin` (now at v1.0.6):

```ts
// vite.config.ts
import { defineConfig } from "vite";
import deno from "@deno/vite-plugin";

export default defineConfig({
  plugins: [deno()],
});
```

With the plugin, Vite builds with JSR imports (e.g. `@std/text` via import map in `deno.json`) succeed without issues. The plugin handles resolving `jsr:`, `npm:`, and import map specifiers that Vite/Rollup don't natively understand.

Without the plugin, Vite will fail to resolve these imports — but that's expected behavior since Vite has no built-in knowledge of Deno's module resolution. The plugin has been updated since this issue was filed and handles this case correctly now.

**Comment by seckinu** [comment]
@bartlomieju 

```ts
import { defineConfig } from "@solidjs/start/config";
import tailwindcss from "@tailwindcss/vite";
import deno from "@deno/vite-plugin";

export default defineConfig({
  vite: {
    plugins: [tailwindcss(), deno()],
  },
});
```

in this setup of SolidStart + Deno I get the following error: 
```
[vite] Internal server error: Missing id to get assets.
      at LoadPluginContext.load (.../node_modules/.deno/vinxi@0.5.11/node_modules/vinxi/lib/plugins/manifest.js:60:14)
      at EnvironmentPluginContainer.load (.../node_modules/.deno/vite@6.4.3/node_modules/vite/dist/node/chunks/dep-Dm0c1Wj2.js:42424:17)
      at async loadAndTransform (.../node_modules/.deno/vite@6.4.3/node_modules/vite/dist/node/chunks/dep-Dm0c1Wj2.js:35779:22) (x2)
```

`    "@deno/vite-plugin": "^2.0.2"` in package.json dependencies
