### ISSUE TITLE
sveltekit demo app dev server fails with bad resource ID

### ISSUE THREAD

**Issue by nathanwhit** [denoland/deno#26341]
repro:

```
❯ deno run -A npm:create-svelte@latest repro

create-svelte version 6.4.0

┌  Welcome to SvelteKit!
│
◇  Which Svelte app template?
│  SvelteKit demo app
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◇  Select additional options (use arrow keys/space bar)
│  none
│
└  Your project is ready!
❯ cd repro
❯ deno i --allow-scripts
❯ deno task dev
```
Then navigate to the correct url in your browser (probably http://localhost:5173/). Fails with:

```
BadResource: Bad resource ID
    at TcpConn.setNoDelay (ext:deno_net/01_net.js:211:12)
    at TCP.setNoDelay (ext:deno_node/internal_binding/tcp_wrap.ts:229:28)
    at Socket.setNoDelay (node:net:595:20)
    at WebSocket.setSocket (file:///repro/node_modules/.deno/vite@5.4.9/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:57417:35)
    at WebSocketServer.completeUpgrade (file:///repro/node_modules/.deno/vite@5.4.9/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:59042:8)
    at WebSocketServer.handleUpgrade (file:///repro/node_modules/.deno/vite@5.4.9/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:58967:10)
    at ServerImpl.hmrServerWsListener (file:///repro/node_modules/.deno/vite@5.4.9/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:59217:13)
    at ServerImpl.emit (ext:deno_node/_events.mjs:393:28)
    at handler (node:http:1310:14)
    at ext:deno_http/00_serve.ts:369:24 {
  name: "BadResource"
}
Upgrade response was not returned from callback
```

**Comment by AllenAttuned** [comment]
I'm not sure if it would be related, but I'm getting the same error when starting up a fresh React SPA using: `deno run --allow-read --allow-write --allow-env npm:create-vite-extra@latest`. Downgrading from Deno `2.0.1` to `2.0.0` seems to resolve the issue.

```
Task dev deno run -A --node-modules-dir npm:vite

  VITE v5.4.9  ready in 65 ms

  ➜  Local:   http://localhost:3000/
  ➜  press h + enter to show help
BadResource: Bad resource ID
    at TcpConn.setNoDelay (ext:deno_net/01_net.js:211:12)
    at TCP.setNoDelay (ext:deno_node/internal_binding/tcp_wrap.ts:229:28)
    at Socket.setNoDelay (node:net:595:20)
    at WebSocket.setSocket (...)
    at WebSocketServer.completeUpgrade (...)
    at WebSocketServer.handleUpgrade (...)
    at ServerImpl.hmrServerWsListener (...)
    at ServerImpl.emit (ext:deno_node/_events.mjs:393:28)
    at handler (node:http:1310:14)
    at ext:deno_http/00_serve.ts:369:24
    at ext:deno_http/00_serve.ts:577:29
    at eventLoopTick (ext:core/01_core.js:175:7) {
  name: "BadResource"
}
Upgrade response was not returned from callback

```

**Comment by marvinhagemeister** [comment]
@AllenAttuned That issue is tracked in https://github.com/denoland/deno/issues/26343
