### ISSUE TITLE
CTRL+D in the REPL causes panic

### ISSUE THREAD

**Issue by ry** [denoland/deno#2637]
this was introduced in abe8a113ad8004f160eac5f3f115cb28c5072ba7
```
% ./target/debug/deno
> 1+2
3
> ^D
thread 'tokio-runtime-worker-1' panicked at 'Can't get ErrorKind for Eof', ../../cli/deno_error.rs:235:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'internal error: entered unreachable code', ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/mod.rs:296:26
thread 'tokio-runtime-worker-0' panicked at 'unexpected state while aborting task: Complete', ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/task/mod.rs:216:21
```

**Comment by ry** [comment]
I'm not sure about the fix yet, but here is a failing test
```patch
diff --git a/tools/repl_test.py b/tools/repl_test.py
index e8b1f1a6..424346c2 100644
--- a/tools/repl_test.py
+++ b/tools/repl_test.py
@@ -38,6 +38,12 @@ class TestRepl(DenoTestCase):
         self.assertEqual(err, '')
         self.assertEqual(code, 0)

+    def test_eof(self):
+        out, err, code = self.input("\04", "'ignored'", exit=False)
+        self.assertEqual(out, '')
+        self.assertEqual(err, '')
+        self.assertEqual(code, 0)
+
     def test_exit_command(self):
         out, err, code = self.input("exit", "'ignored'", exit=False)
         self.assertEqual(out, '')
```
