### ISSUE TITLE
storybook: init new project with storybook, deno fails to run it

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#26404]
deno 2.0.2

Repro:

- `deno run -A npm:storybook@latest init` or `npx storybook@latest init` (select vue 3 + vite)
- `deno task storybook`

Error:

```
➜ deno task storybook
Task storybook storybook dev -p 6006
@storybook/core v8.3.6

NotFound: No such file or directory (os error 2): readfile 'chromatic.config.json'
    at Object.readFileSync (ext:deno_fs/30_fs.js:733:10)
    at Object.readFileSync (ext:deno_node/_fs/_fs_readFile.ts:52:21)
    at Object.Ege (file://./node_modules/.deno/chromatic@11.12.6/node_modules/chromatic/dist/chunk-P6VYOOE6.js:827:1175)
    at Object.Uir [as experimental_serverChannel] (file://./node_modules/.deno/@chromatic-com+storybook@1.9.0/node_modules/@chromatic-com/storybook/dist/preset.js:595:402)
    at file://./node_modules/.deno/@storybook+core@8.3.6/node_modules/@storybook/core/dist/common/index.cjs:139480:18
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async storybookDevServer (file://./node_modules/.deno/@storybook+core@8.3.6/node_modules/@storybook/core/dist/core-server/index.cjs:47285:11)
    at async buildOrThrow (file://./node_modules/.deno/@storybook+core@8.3.6/node_modules/@storybook/core/dist/core-server/index.cjs:46581:12)
    at async buildDevStandalone (file://./node_modules/.deno/@storybook+core@8.3.6/node_modules/@storybook/core/dist/core-server/index.cjs:48518:78)
    at async withTelemetry (file://./node_modules/.deno/@storybook+core@8.3.6/node_modules/@storybook/core/dist/core-server/index.cjs:47080:12)


```

**Comment by kfp** [comment]
With deno v2.1.1:

```
$ deno task storybook
Task storybook storybook dev -p 6006
@storybook/core v8.4.5

TypeError: g.start is not a function
    at storybookDevServer (file://./node_modules/@storybook/core/dist/core-server/index.cjs:35974:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async buildOrThrow (file://./node_modules/@storybook/core/dist/core-server/index.cjs:35017:12)
    at async buildDevStandalone (file://./node_modules/@storybook/core/dist/core-server/index.cjs:37190:78)
    at async withTelemetry (file://./node_modules/@storybook/core/dist/core-server/index.cjs:35757:12)
    at async dev (file://./node_modules/@storybook/core/dist/cli/bin/index.cjs:2591:3)
    at async s.<anonymous> (file://./node_modules/@storybook/core/dist/cli/bin/index.cjs:2643:74)
```

**Comment by birkskyum** [comment]
In 2.1.6 I had deno pick an older version of storybook, even when specifying `storybook@latest` or `storybook@8.5.2`.

With Deno 2.1.7, this does appear to work as expected 🎉
