### ISSUE TITLE
storybook: deno fails to init storybook in react+vite project

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#26405]
Version: Deno 2.0.2

➜ `deno run -A npm:create-vite` (react, ts without swc)
➜ `deno i`
➜ `deno run -A npm:storybook@latest init`

```
╭──────────────────────────────────────────────────────╮
│                                                      │
│   Adding Storybook version 8.3.6 to your project..   │
│                                                      │
╰──────────────────────────────────────────────────────╯
 • Detecting project type. ✓
Installing dependencies...

npm error Cannot read properties of null (reading 'matches')
npm error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-10-18T22_52_29_828Z-debug-0.log
An error occurred while installing dependencies.

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry
```

**Comment by birkskyum** [comment]
I get:

```sh
➜ deno run -A npm:storybook@latest init
╭──────────────────────────────────────────────────────╮
│                                                      │
│   Adding Storybook version 8.5.2 to your project..   │
│                                                      │
╰──────────────────────────────────────────────────────╯
 • Detecting project type. ✓
Installing dependencies...

npm error Cannot read properties of null (reading 'matches')
npm error A complete log of this run can be found in: /Users/admin/.npm/_logs/2025-01-28T13_24_34_824Z-debug-0.log
An error occurred while installing dependencies.

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry
```

**Comment by WilcoKruijer** [comment]
Same for ShadCN. Deno 2.1.9

```
deno run -A npm:shadcn@latest add sidebar-07
✔ Checking registry.
✔ Updating tailwind.config.cjs
✔ Updating src/app.css
⠴ Installing dependencies.
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: npm install @radix-ui/react-slot class-variance-authority lucide-react @radix-ui/react-separator @radix-ui/react-dialog @radix-ui/react-tooltip @radix-ui/react-collapsible @radix-ui/react-dropdown-menu @radix-ui/react-avatar
npm error Cannot read properties of null (reading 'matches')
npm error A complete log of this run can be found in: /Users/wilco/.npm/_logs/2025-02-06T21_56_32_908Z-debug-0.log
```

```
455 verbose stack TypeError: Cannot read properties of null (reading 'matches')
455 verbose stack     at Link.matches (/Users/wilco/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1117:41)
455 verbose stack     at Link.canDedupe (/Users/wilco/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1071:15)
455 verbose stack     at PlaceDep.pruneDedupable (/Users/wilco/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:426:14)
455 verbose stack     at new PlaceDep (/Users/wilco/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:278:14)
455 verbose stack     at new PlaceDep (/Users/wilco/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:314:26)
455 verbose stack     at #buildDepStep (/Users/wilco/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:920:18)
455 verbose stack     at async Arborist.buildIdealTree (/Users/wilco/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
455 verbose stack     at async Promise.all (index 1)
455 verbose stack     at async Arborist.reify (/Users/wilco/.nvm/versions/node/v22.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
455 verbose stack     at async Install.exec (/Users/wilco/.nvm/versions/node/v22.13.1/lib/node_modules/npm/lib/commands/install.js:150:5)
456 error Cannot read properties of null (reading 'matches')
```

**Comment by kt3k** [comment]
> My guess is that Storybook and Shadcn hardcode calling npm install

This sounds true. Storybook detects the package manager, but it doesn't detect deno as package manager for now. So Storybook seems using `npm` for installing dependencies in the above scenario. https://github.com/storybookjs/storybook/tree/81513d004b7f40c662550c41169fa13967b9d1cd/code/core/src/common/js-package-manager

The issue seems caused by the mixture of deno-installed node_modules and npm-installed node_modules. If I skip `deno install` step in the original example, then the issue seems disappearing on my end:

```
deno run -A npm:create-vite
cd vite-project
deno run -A npm:storybook@latest init
```

I think one way of fixing this would be adding the `deno` detection in JsPackageManagerFactory in storybook. https://github.com/storybookjs/storybook/blob/81513d004b7f40c662550c41169fa13967b9d1cd/code/core/src/common/js-package-manager/JsPackageManagerFactory.ts

**Comment by littledivy** [comment]
Closing since `storybook init` is working. Let's open a new issue for `deno` detection in storybook for installing dependencies.

**Comment by birkskyum** [comment]
I get:

deno 2.3.1



```ts
➜ deno run -A npm:create-vite (react, ts without swc)
➜ deno i
➜ deno run -A npm:storybook@latest init

Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:fsevents@2.3.3
┃
┠─ This may cause the packages to not work correctly.
┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
┠─ Enable it in your deno config file:
┖─ "nodeModulesDir": "auto"
╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                 │
│   Adding Storybook version 8.5.2 to your project..                                              │
│   This version is behind the latest release, which is: 8.6.12!                                  │
│   You likely ran the init command through npx, which can use a locally cached version, to get   │
│   the latest please run:                                                                        │
│   npx storybook@latest init                                                                     │
│                                                                                                 │
│   You may want to CTRL+C to stop, and run with the latest version instead.                      │
│                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────╯
 • Detecting project type. ✓
Installing dependencies...

npm error Cannot read properties of null (reading 'matches')
npm error A complete log of this run can be found in: /Users/admin/.npm/_logs/2025-05-07T11_42_36_467Z-debug-0.log
An error occurred while installing dependencies.

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry
```

@littledivy any idea why it with `@latest` still select the not-latest version of storybook?

**Comment by radiocab** [comment]
May this relate, I mean that dir 'node_modules' was created not with npm install? :    

https://stackoverflow.com/questions/74650198/npm-err-cannot-read-properties-of-null-reading-matches

"This error shows up when you run npm install in a directory where you previously ran pnpm install. The solution is to remove your node_modules directory and run npm install again."

**Comment by birkskyum** [comment]
@kt3k , what would the full command be with the `--reload` flag?

**Comment by bartlomieju** [comment]
`deno run -A --reload npm:storybook@latest init`

**Comment by glesage** [comment]
Yep getting the error myself as well https://gist.github.com/glesage/f437d5475b353e2a69046610f24fc034

node v22.14.0
deno 2.3.1
npm 11.3.0
yarn 1.22.22

Attempting to install storybook latest which is 8.6.12

**Comment by SDVoGo** [comment]
Me too. Same result in both Arch and Win11. 

`deno 2.2.9`

**Comment by marvinhagemeister** [comment]
Can you check with the latest Deno version 2.4.0 (at the time of this writing)?

**Comment by SDVoGo** [comment]
Sure, 

`deno 2.4.1`

`deno run -A --reload npm:storybook@latest init`

```bash


info Installing dependencies...
info
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @ampproject/remapping@2.3.0
npm warn Found: peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.20.0
npm warn node_modules/.deno/@ampproject+remapping@2.3.0/node_modules/@ampproject/remapping/node_modules/@typescript-eslint/eslint-plugin
npm warn   dev @typescript-eslint/eslint-plugin@"5.20.0" from @ampproject/remapping@2.3.0
npm warn   node_modules/.deno/@ampproject+remapping@2.3.0/node_modules/@ampproject/remapping
npm warn
npm warn Could not resolve dependency:
npm warn peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.20.0
npm warn node_modules/.deno/@ampproject+remapping@2.3.0/node_modules/@ampproject/remapping/node_modules/@typescript-eslint/eslint-plugin
npm warn   dev @typescript-eslint/eslint-plugin@"5.20.0" from @ampproject/remapping@2.3.0
npm warn   node_modules/.deno/@ampproject+remapping@2.3.0/node_modules/@ampproject/remapping
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @jridgewell/gen-mapping@0.3.8
npm warn Found: peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.21.0
npm warn node_modules/.deno/@jridgewell+gen-mapping@0.3.8/node_modules/@jridgewell/gen-mapping/node_modules/@typescript-eslint/eslint-plugin
npm warn   dev @typescript-eslint/eslint-plugin@"5.21.0" from @jridgewell/gen-mapping@0.3.8
npm warn   node_modules/.deno/@jridgewell+gen-mapping@0.3.8/node_modules/@jridgewell/gen-mapping
npm warn
npm warn Could not resolve dependency:
npm warn peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.21.0
npm warn node_modules/.deno/@jridgewell+gen-mapping@0.3.8/node_modules/@jridgewell/gen-mapping/node_modules/@typescript-eslint/eslint-plugin
npm warn   dev @typescript-eslint/eslint-plugin@"5.21.0" from @jridgewell/gen-mapping@0.3.8
npm warn   node_modules/.deno/@jridgewell+gen-mapping@0.3.8/node_modules/@jridgewell/gen-mapping
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @jridgewell/trace-mapping@0.3.25
npm warn Found: peer @typescript-eslint/parser@"^6.0.0 || ^6.0.0-alpha" from @typescript-eslint/eslint-plugin@6.18.1
npm warn node_modules/.deno/@jridgewell+trace-mapping@0.3.25/node_modules/@jridgewell/trace-mapping/node_modules/@typescript-eslint/eslint-plugin
npm warn   dev @typescript-eslint/eslint-plugin@"6.18.1" from @jridgewell/trace-mapping@0.3.25
npm warn   node_modules/.deno/@jridgewell+trace-mapping@0.3.25/node_modules/@jridgewell/trace-mapping
npm warn
npm warn Could not resolve dependency:
npm warn peer @typescript-eslint/parser@"^6.0.0 || ^6.0.0-alpha" from @typescript-eslint/eslint-plugin@6.18.1
npm warn node_modules/.deno/@jridgewell+trace-mapping@0.3.25/node_modules/@jridgewell/trace-mapping/node_modules/@typescript-eslint/eslint-plugin
npm warn   dev @typescript-eslint/eslint-plugin@"6.18.1" from @jridgewell/trace-mapping@0.3.25
npm warn   node_modules/.deno/@jridgewell+trace-mapping@0.3.25/node_modules/@jridgewell/trace-mapping
npm warn ERESOLVE overriding peer dependency
npm error Cannot read properties of null (reading 'matches')
```

**Comment by birkskyum** [comment]
With
- deno 2.4.5
- npm 11.5.1
- storybook v9.1.5

This appear to be working

```sh
➜ deno run -A --reload npm:storybook@latest init
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.

error searching for splitDirname: ReferenceError: __dirname is not defined
╔ 🔎 Empty directory detected ═════════════════════════════════════════════════╗
║                                                                              ║
║   Would you like to generate a new project from the following list?          ║
║                                                                              ║
║   Note:                                                                      ║
║   Storybook supports many more frameworks and bundlers than listed below.    ║
║   If you don't see your                                                      ║
║   preferred setup, you can still generate a project then rerun this          ║
║   command to add Storybook.                                                  ║
║                                                                              ║
║   Press ^C at any time to quit.                                              ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝

? Choose a project template › - Use arrow-keys. Return to submit.
❯   React + Vite (TS)
    Next.js (TS)
✔ Choose a project template › React + Vite (TS)

Creating a new "React + Vite (TS)" project with npm...

╔ ✅ Success! ═══════════════════════════════════════════════════╗
║                                                                ║
║   "React + Vite (TS)" project with npm created successfully!   ║
║                                                                ║
║   Continuing with Storybook installation...                    ║
║                                                                ║
╚════════════════════════════════════════════════════════════════╝


error searching for splitDirname: ReferenceError: __dirname is not defined
info Installing dependencies...
info 
Attention: Storybook now collects completely anonymous telemetry regarding usage. This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.

added 233 packages, and audited 234 packages in 10s

47 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
info Dependencies installed
╭──────────────────────────────────────────────────────╮
│                                                      │
│   Adding Storybook version 9.1.5 to your project..   │
│                                                      │
╰──────────────────────────────────────────────────────╯
✔ New to Storybook? › Yes: Help me with onboarding
 • Detecting project type. ✓
 • Adding Storybook support to your "React" app • Detected Vite project. Setting builder to Vite. ✓

  ✅ Getting the correct version of 5 packages
  ⠙ Installing Storybook dependenciesnpm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.

added 128 packages, and audited 362 packages in 5s

87 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
  ✅ Installing Storybook dependencies
. ✓
info Installing dependencies...
info 
npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.

up to date, audited 362 packages in 924ms

87 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
info Dependencies installed
> npx storybook@9.1.5 add --yes @storybook/addon-a11y@9.1.5
npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.
(node:38401) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
(Use `node --trace-deprecation ...` to show where the warning was created)
npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
(node:38546) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Verifying @storybook/addon-a11y
Installing @storybook/addon-a11y@^9.1.5
npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.

added 2 packages, and audited 364 packages in 1s

88 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Adding '@storybook/addon-a11y@9.1.5' to the "addons" field in .storybook/main.ts
Running postinstall script for @storybook/addon-a11y
> npx storybook@9.1.5 add --yes @storybook/addon-vitest@9.1.5
npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.
(node:38703) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
(Use `node --trace-deprecation ...` to show where the warning was created)
npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.
(node:38745) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Verifying @storybook/addon-vitest
Installing @storybook/addon-vitest@^9.1.5
npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.

added 4 packages, and audited 368 packages in 2s

89 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Adding '@storybook/addon-vitest@9.1.5' to the "addons" field in .storybook/main.ts
Running postinstall script for @storybook/addon-vitest

╭ 👋 Howdy! ─────────────────────────────────────────────────────────────────╮
│                                                                            │
│   I'm the installation helper for @storybook/addon-vitest                  │
│                                                                            │
│   Hold on for a moment while I look at your project and get it set up...   │
│                                                                            │
╰────────────────────────────────────────────────────────────────────────────╯

╭ 🙈 Let me cover this for you ──────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                    │
│   You don't seem to have a coverage reporter installed. Vitest needs either V8 or Istanbul to generate coverage    │
│   reports.                                                                                                         │
│                                                                                                                    │
│   Adding "@vitest/coverage-v8" to enable coverage reporting.                                                       │
│   Read more about Vitest coverage providers at https://vitest.dev/guide/coverage.html#coverage-providers           │
│                                                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

› Installing dependencies:
  vitest, @vitest/browser, playwright, @vitest/coverage-v8
info Installing dependencies...
info 
npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.

added 44 packages, and audited 412 packages in 2s

97 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
info Dependencies installed

› Configuring Playwright with Chromium (this might take some time):
  npx playwright install chromium --with-deps

› Creating a Vitest setup file for Storybook:
  /Users/admin/repos/deno-kitchensink/sb-test/.storybook/vitest.setup.ts

› Updating your Vite config file:
  /Users/admin/repos/deno-kitchensink/sb-test/vite.config.ts
› Setting up @storybook/addon-a11y for @storybook/addon-vitest:
(node:39185) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
(Use `node --trace-deprecation ...` to show where the warning was created)
│
◇  Automigration detected: addon-a11y-addon-test
│
│
◆  Ran addon-a11y-addon-test migration
│
◇  Installing dependencies...
│
│
◆  Dependencies installed

╭ 🎉 All done! ───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                         │
│         @storybook/addon-vitest is now configured and you're ready to run your tests!                   │
│                                                                                                         │
│         Here are a couple of tips to get you started:                                                   │
│         • You can run tests with "npx vitest --project=storybook"                                       │
│         • When using the Vitest extension in your editor, all of your stories will be shown as tests!   │
│                                                                                                         │
│         Check the documentation for more information about its features and options at:                 │
│         https://storybook.js.org/docs/next/writing-tests/integrations/vitest-addon                      │
│                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────────────────────────────────────╮
│                                                                              │
│   Storybook was successfully installed in your project! 🎉                   │
│   Additional features: docs, test, onboarding                                │
│                                                                              │
│   To run Storybook manually, run npm run storybook. CTRL+C to stop.          │
│                                                                              │
│   Wanna know more about Storybook? Check out https://storybook.js.org/       │
│   Having trouble or want to chat? Join us at https://discord.gg/storybook/   │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

Running Storybook
npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.
npm warn Unknown env config "python". This will stop working in the next major version of npm.
npm warn Unknown user config "node_gyp". This will stop working in the next major version of npm.
npm warn Unknown user config "python". This will stop working in the next major version of npm.

> sb-test@0.0.0 storybook
> storybook dev -p 6006 --initial-path=/onboarding --quiet

storybook v9.1.5

(node:39299) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Serving static files from /Users/admin/repos/deno-kitchensink/sb-test/node_modules/@chromatic-com/storybook/assets at /addon-visual-tests-assets
info Using tsconfig paths for react-docgen
info Using tsconfig paths for react-docgen
```

**Comment by birkskyum** [comment]
@SDVoGo can you check again, if it's resolved on your side too?

**Comment by SDVoGo** [comment]
Hi @birkskyum, I'm sorry I've seen your message just a moment ago.  

On Arch:
```
❯ deno run -A --reload npm:storybook@latest init
/bin/sh: riga 1: npx: command not found
```
Do I need node installed on my machine?

**Comment by littledivy** [comment]
@SDVoGo `storybook` CLI tries to use `npm` by default to install dependencies. You can skip the install step and invoke `deno install` manually:

```
deno run -A npm:storybook@latest init  --skip-install
deno install
```

**Comment by SDVoGo** [comment]
@littledivy Done but doesn't launch the wizard like in @birkskyum 's machine

**Comment by bartlomieju** [comment]
This appears to be fixed. Tested with the latest development build:

1. Created a React+Vite project with `deno run -A npm:create-vite@latest . -- --template react-ts`
2. Added React dependencies and ran `deno install`
3. Ran `deno run -A npm:storybook@latest init`

Storybook (v10.2.17) initialized successfully — detected the React+Vite project, installed dependencies, and configured addons without the `Cannot read properties of null (reading 'matches')` npm error.

**Comment by bartlomieju** [comment]
The hang no longer reproduces on the latest development build. Without `-A`, the process now errors immediately with a clear permissions error instead of hanging:

```
error: Uncaught (in promise) NotCapable: Requires env access to "FORCE_NODE_FETCH", run again with the --allow-env flag
```

This is the expected behavior — npm packages that need env/net/read access should fail with a permissions error when those permissions aren't granted. Closing as fixed.
