### ISSUE TITLE
Cannot start nuxt:  EINVAL: invalid argument, stat  

### ISSUE THREAD

**Issue by merouaneamqor** [denoland/deno#26411]
#  I Can not run a Nuxt 3 app with deno 
 
 
```bash
 ERROR  Cannot start nuxt:  EINVAL: invalid argument, stat                                                                     4:37:02 p.m.  

  at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
  at __node_internal_uvException (ext:deno_node/internal/errors.ts:186:10)
  at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1895:14)
  at ext:deno_node/_fs/_fs_stat.ts:149:95
  at eventLoopTick (ext:core/01_core.js:175:7)
```

**Comment by Alt-iOS** [comment]
Having a similar issue here, in windows I get that same error and in macOS I get 
```
 ERROR  Bad resource ID                                                                                           1:37:34 PM

  at TcpConn.setNoDelay (ext:deno_net/01_net.js:211:12)
  at TCP.setNoDelay (ext:deno_node/internal_binding/tcp_wrap.ts:229:28)
  at Socket.setNoDelay (node:net:595:20)
  at setupSocket (node_modules/.deno/nuxi@3.14.0/node_modules/nuxi/dist/chunks/index4.mjs:59:10)
  at node_modules/.deno/nuxi@3.14.0/node_modules/nuxi/dist/chunks/index4.mjs:363:5
  at ProxyServer.ws (node_modules/.deno/nuxi@3.14.0/node_modules/nuxi/dist/chunks/index4.mjs:537:20)
  at ServerImpl.wsHandler (node_modules/.deno/nuxi@3.14.0/node_modules/nuxi/dist/chunks/dev.mjs:224:18)
  at ServerImpl.emit (ext:deno_node/_events.mjs:393:28)
  at handler (node:http:1310:14)
  at ext:deno_http/00_serve.ts:369:24

```

**Comment by mohanadshaban** [comment]
Same here !

**Comment by bartlomieju** [comment]
Are you all using Windows when getting this error? Which version of Deno are you on? Does the issue persists on Deno 2.0.2?
