### ISSUE TITLE
[ERR_HTTP2_SOCKET_UNBOUND]: The socket has been disconnected from the Http2Session

### ISSUE THREAD

**Issue by butadpj** [denoland/deno#26436]
Version: Deno 2.0.2 (stable, release, aarch64-apple-darwin)

I am working with Pulumi's Automation API and whenever I call `stack.preview()` or `stack.up()` which relies heavily on gRPC, I'm getting this error:

```
>>> Error in Http2Server Error [ERR_HTTP2_SOCKET_UNBOUND]: The socket has been disconnected from the Http2Session
    at Object.get (node:http2:92:19)
    at Http2Server.<anonymous> ([project's path]/node_modules/@grpc/grpc-js/src/server.ts:1638:25)
    at Http2Server.emit (ext:deno_node/_events.mjs:393:28)
    at Http2Server.<anonymous> (node:http2:1214:14)
    at Http2Server.emit (ext:deno_node/_events.mjs:393:28)
    at TCP._onconnection [as onconnection] (node:net:1127:8)
    at TCP.#accept (ext:deno_node/internal_binding/tcp_wrap.ts:358:12)
    at eventLoopTick (ext:core/01_core.js:175:7) {
  code: "ERR_HTTP2_SOCKET_UNBOUND",
  name: "Error"
}
```

This is the error Im getting from Pulumi when executing `stack.preview()`:
```
error: failed to discover plugin requirements: connection error: desc = "error reading server preface: read tcp 127.0.0.1:55811->127.0.0.1:55807: use of closed network connection"
Previewing update (dev)
```
- as you notice, the error seems like a result of Deno's issue with gRPC (socket being disconnected from the Http2Session)

**Comment by vinaydotblog** [comment]
I'm getting the same error.

**Comment by butadpj** [comment]
This issue stems on Deno lacking support for `npm:@grpc/grpc-js` on server-side, see the issue here - https://github.com/denoland/deno/issues/23714. Props to Deno team for including it on Q2 and Q3! 🥳 
> It's in the roadmap for Q2 and Q3 '25 

 _Originally posted by @bartlomieju in [#23714](https://github.com/denoland/deno/issues/23714#issuecomment-2846605679)_

**Temporary solution:**
- For now, I just created a regular `.js` file (`pulumi.js`) where all my pulumi-related scripts live, then, I'm just running that file with `node`
```js
export async function runPulumiScript(args: string[]) {
  const command = new Deno.Command("node", {
    args: ["pulumi.js", "--project-id"],
    stdout: "piped",
    stderr: "piped",
  });
....
}
```

**Comment by littledivy** [comment]
Fixed by 20e1ef892e7605469a239c269705f417e42bd5d8
