### ISSUE TITLE
Export feature for P-521 and X25519 cryptoKey

### ISSUE THREAD

**Issue by Srabutdotcom** [denoland/deno#26431]
It would be better if Deno fully support for Webcrypto API,..

I have tested that deno can create P-521 and X25519 cryptoKey like a charm.
**P-521 cryptoKey**
- [x] export to JWK failed on both private and public key - `NotSupportedError: Unsupported namedCurve`
- [x] export to RAW failed - `TypeError: expected valid private EC key`

**X25519 cryptoKey**
- [x] export to JWK failed on private key only - `NotSupportedError: Not implemented`

**Comment by hertzg** [comment]
This code also works in latest node LTS and does not issue experimental warning anymore:

```js
const { privateKey } = await crypto.subtle.generateKey(
  { name: "X25519" },
  true,
  ["deriveKey", "deriveBits"]
);
const jwk = await crypto.subtle.exportKey("jwk", privateKey);
console.log(jwk);
```

When running under `node v22.13.0`:
```
$ node -v     
v22.13.0
$ node node.mjs
{
  key_ops: [ 'deriveKey', 'deriveBits' ],
  ext: true,
  crv: 'X25519',
  d: '2LAP7t3KsI7n2JxKpatigiSxFS8IcNInjTnn-Bxx6VE',
  x: 'ldy_Ujc9T1Ml4zwyjVKdffGMiYXJJ4QTtn0P6VA7_H4',
  kty: 'OKP'
}
```

When running under `deno 2.1.5`:
```
$ deno -v
deno 2.1.5
$ deno node.mjs 
error: Uncaught (in promise) NotSupportedError: Not implemented
const jwk = await crypto.subtle.exportKey("jwk", privateKey);
                                ^
    at exportKeyX25519 (ext:deno_crypto/00_crypto.js:4536:15)
    at SubtleCrypto.exportKey (ext:deno_crypto/00_crypto.js:1054:18)
    at file:///Users/hertzg/projects/wireguard-tools/node.mjs:6:33
```

**Comment by hertzg** [comment]
This issue was mentioned from a pr #27828 ( thanks @littledivy ) and I can confirm the JWK export of x25519 private key works since `deno 2.1.8`.

```sh
$ deno -v
deno 2.1.8
$ deno run node.mjs
{
  kty: "OKP",
  crv: "X25519",
  key_ops: [ "deriveKey", "deriveBits" ],
  ext: true,
  x: "Pw0aODbPSnhp52nKS_iAyKV03LDzSnLVYrrllX3EGwA",
  d: "aLaBKkPJa3r_5DM44UToQQoZ1zVifqxH8LucGClaoo8"
}
```
