### ISSUE TITLE
Deno not working with Shopify Codegen tool

### ISSUE THREAD

**Issue by DannyTaki** [denoland/deno#26482]
Version: Deno 2.0.0
Steps to reproduce:
`deno init`
`deno add npm:@shopify/api-codegen-preset`
`deno add npm:@shopify/admin-api-client npm:@shopify/storefront-api-client`
`deno install`
`deno task graphql`

Add graphql-codegen to tasks in `deno.json`
```
"tasks": {
    "dev": "deno run --watch main.ts",
    "graphql": "graphql-codegen"
  }
 ```
Add `.graphqlrc.ts` in root
```
import {shopifyApiProject, ApiType} from '@shopify/api-codegen-preset';

export default {
  // For syntax highlighting / auto-complete when writing operations
  schema: 'https://shopify.dev/admin-graphql-direct-proxy/2023-10',
  documents: ['./app/**/*.{js,ts,jsx,tsx}'],
  projects: {
    // To produce variable / return types for Admin API operations
    default: shopifyApiProject({
      apiType: ApiType.Admin,
      apiVersion: '2023-10',
      documents: ['./app/**/*.{js,ts,jsx,tsx}'],
      outputDir: './app/types',
    }),
  },
};
```
`app.ts` 
```
// Shopify GraphQL query for orders and fulfillment info
const shopifyQuery = `#graphql
query FetchOrders($cursor: String) {
    orders(first: 50, after: $cursor) {
        edges {
            cursor
            node {
                id
                name
                fulfillments {
                    trackingInfo {
                        number
                        url
                        company
                    }
                    createdAt
                }
                shippingLine {
                    code
                    id
                    originalPriceSet {
                          shopMoney {
                            amount
                          }
                    }
                    title
                }
            }
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}`;
```

Expected Behavior: 

Graphql Query Types generated in ./types directory

Actual Behavior:

```
dannytaki@DESKTOP-DANNY:~/deno_bug$ deno task graphql
Task graphql graphql-codegen
graphql-codegen: command not found
```

`

**Comment by bartlomieju** [comment]
I know what the problem is - after you do `deno init` add `"nodeModulesDir": "auto"` option in `deno.json` - this will generate `node_modules/` directory for you which will contains proper entries in `node_modules/.bin`

**Comment by DannyTaki** [comment]
```
Task graphql-codegen graphql-codegen
Error: Cannot find module 'npm:@shopify/api-codegen-preset'
Require stack:
- /mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/.graphqlrc.ts
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at jitiResolve (/mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/node_modules/.deno/jiti@2.3.3/node_modules/jiti/dist/jiti.cjs:1:185088)
    at jitiRequire (/mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/node_modules/.deno/jiti@2.3.3/node_modules/jiti/dist/jiti.cjs:1:187143)
    at /mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/node_modules/.deno/jiti@2.3.3/node_modules/jiti/dist/jiti.cjs:1:197361
    at /mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/.graphqlrc.ts:1:215
    at eval_evalModule (/mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/node_modules/.deno/jiti@2.3.3/node_modules/jiti/dist/jiti.cjs:1:194312)
    at jitiRequire (/mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/node_modules/.deno/jiti@2.3.3/node_modules/jiti/dist/jiti.cjs:1:188088)
    at /mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/node_modules/.deno/jiti@2.3.3/node_modules/jiti/dist/jiti.cjs:1:197361
    at loadTypeScript (/mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/node_modules/.deno/graphql-config@5.1.3/node_modules/graphql-config/cjs/helpers/cosmiconfig.js:38:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/.graphqlrc.ts'
  ],
  filepath: '/mnt/extra_storage2/home/dannytaki/deno_fetch_shopify_orders/.graphqlrc.ts'
}
```

Do I have to run something else besides `deno task graphql-codegen` after I have the node_modules folder?

**Comment by bartlomieju** [comment]
This error is strange - it indicates that you have `npm:@shopify/api-codegen-present` import somewhere - it shouldn't use `npm:` prefix there. Unfortunately I'm not able to repeat that because this is what I get running with the files you provided:
```
Task graphql graphql-codegen
(node:2306) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate to ./app/types/admin-2023-10.schema.json
    ✖ Unexpected empty "data" and "errors" fields in result: {"error":"Invalid API version"}
    ◼ Load GraphQL documents
    ◼ Generate
  ❯ Generate to ./app/types/admin.types.d.ts
    ✖ Unexpected empty "data" and "errors" fields in result: {"error":"Invalid API version"}
    ◼ Load GraphQL documents
    ◼ Generate
  ❯ Generate to ./app/types/admin.generated.d.ts
    ✖ Unexpected empty "data" and "errors" fields in result: {"error":"Invalid API version"}
    ◼ Load GraphQL documents
    ◼ Generate

```

**Comment by DannyTaki** [comment]
Ah yes, that fixed it when I thought I had to add the npm prefix in my package import in the `.graphqlrc.ts` file because the linter was complaining but I think I just needed to let Deno VS Code extension finish installing.  Now it gets the same response as yourself, which means it worked! Thank you!

**Comment by bartlomieju** [comment]
Awesome, glad it worked!
