### ISSUE TITLE
Errors when using just Deno for NextJS app

### ISSUE THREAD

**Issue by ss153g** [denoland/deno#26483]
I'm trying to use Deno 2.02 for installing NextJS but getting errors.

`deno run -A npm:create-next-app@latest`

✔ What is your project named? … next-app
✔ Would you like to use TypeScript? … No / Yes
✔ Would you like to use ESLint? … No / Yes
✔ Would you like to use Tailwind CSS? … No / Yes
✔ Would you like to use 'src/' directory? … No / Yes
✔ Would you like to use App Router? (recommended) … No / Yes
✔ Would you like to customize the default import alias (@/*)? … No / Yes
Creating a new Next.js app in /Users/xxxxxxxxxxx/next-app.

Using npm.

Initializing project with template: app-tw 

Installing dependencies:
- react
- react-dom
- next

Installing devDependencies:
- typescript
- @types/node
- @types/react
- @types/react-dom
- postcss
- tailwindcss

`error: Uncaught Error: spawnSync npm ENOENT
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_errnoException (ext:deno_node/internal/errors.ts:141:10)
    at _createSpawnSyncError (ext:deno_node/internal/child_process.ts:685:17)
    at new ChildProcess (ext:deno_node/internal/child_process.ts:287:13)
    at Object.spawn (node:child_process:120:10)
    at spawn (file:///Users/xxxxxxxxxxx/Library/Caches/deno/npm/registry.npmjs.org/create-next-app/14.2.15/dist/index.js:7:76725)
    at file:///Users/xxxxxxxxxxx/Library/Caches/deno/npm/registry.npmjs.org/create-next-app/14.2.15/dist/index.js:73:33444
    at new Promise (<anonymous>)
    at install (file:///Users/xxxxxxxxxxx/Library/Caches/deno/npm/registry.npmjs.org/create-next-app/14.2.15/dist/index.js:73:33412)
    at installTemplate (file:///Users/xxxxxxxxxxx/Library/Caches/deno/npm/registry.npmjs.org/create-next-app/14.2.15/dist/index.js:73:40032)`

**Comment by littledivy** [comment]
Duplicate of https://github.com/denoland/deno/issues/26232

`create-next-app` is trying to spawn `npm` but it is not available in your PATH env. There is not much Deno can do here unless Next.js folks add `--skip-install` or `--use-deno` flag. In the meantime you need to install npm
