### ISSUE TITLE
Nuxt 3 : Cannot start nuxt:  EINVAL: invalid argument, stat

### ISSUE THREAD

**Issue by Ryuka25** [denoland/deno#26511]
## General Error

Hi, i'm unable to start a nuxt 3 application using deno 2 : `deno run dev`

```sh
 ERROR  Cannot start nuxt:  EINVAL: invalid argument, stat                                                    13:13:32

  at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
  at __node_internal_uvException (ext:deno_node/internal/errors.ts:186:10)
  at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1895:14)
  at ext:deno_node/_fs/_fs_stat.ts:149:95
  at eventLoopTick (ext:core/01_core.js:175:7)
```

## Local Environment

```sh
> deno --version
deno 2.0.2 (stable, release, x86_64-pc-windows-msvc)
v8 12.9.202.13-rusty
typescript 5.6.2
```

How i created nuxt 3 app: 

```
> deno run npm:nuxi@latest init hello-world
> cd hello-world
> deno install
```

```sh
> cat .\package.json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "nuxt": "^3.13.2",
    "vue": "latest",
    "vue-router": "latest"
  }
}
```

**Comment by bartlomieju** [comment]
This problem has already been fixed in https://github.com/denoland/deno/pull/26475 and will be released in Deno 2.0.3 tonight. You can try it already by upgrading to canary release with `deno upgrade canary`.
