### ISSUE TITLE
vite/node project can't use i.e. `jsr:@db/sqlite` in package.json/node-compat mode. Migrating to deno.json will break resolution

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#26569]
Version: Deno 2.0.3

Say I try to run a project, like a new solid start example

- deno run -A npm:create-solid
- Select SolidStart, TypeScript, Basic

And then I port package.json over to deno.json

```
{
  "tasks": {
    "dev": "vinxi dev",
    "build": "vinxi build",
    "start": "vinxi start",
    "version": "vinxi version"
  },
  "imports": {
    "@solidjs/meta": "npm:@solidjs/meta@^0.29.4",
    "@solidjs/router": "npm:@solidjs/router@^0.14.10",
    "@solidjs/start": "npm:@solidjs/start@^1.0.9",
    "solid-js": "npm:solid-js@^1.9.2",
    "vinxi": "npm:vinxi@^0.4.3"
  }
}

```

Now it'll break because it can't resolve any dependencies from these npm: packages that doesn't have the "npm:"

```
 ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

8:13:04 PM [vite] Pre-transform error: Failed to load url solid-js/web (resolved id: solid-js/web) in /Users/admin/repos/deno-kitchensink/solid-start-basic/src/entry-server.tsx. Does the file exist? (x5)
8:13:04 PM [vite] Pre-transform error: Failed to load url @solidjs/start/server (resolved id: @solidjs/start/server) in /Users/admin/repos/deno-kitchensink/solid-start-basic/src/entry-server.tsx. Does the file exist?
8:13:04 PM [vite] Error when evaluating SSR module /src/entry-server.tsx: failed to import "solid-js/web"
|- Error: Cannot find module 'solid-js/web' imported from '/Users/admin/repos/deno-kitchensink/solid-start-basic/src/entry-server.tsx'
    at nodeImport (/Users/admin/Library/Caches/deno/npm/registry.npmjs.org/vite/5.4.10/dist/node/chunks/dep-BWSbWtLw.js:53047:19)
    at ssrImport (/Users/admin/Library/Caches/deno/npm/registry.npmjs.org/vite/5.4.10/dist/node/chunks/dep-BWSbWtLw.js:52914:22)
    at undefined

```

Staying in package.json doesn't allow usage of  `jsr:@db/sqlite`

**Comment by bartlomieju** [comment]
Also look like there is a PR that tries to fix it too: https://github.com/vitejs/vite/pull/18479

**Comment by birkskyum** [comment]
@bartlomieju , when i have everything in deno.json and I enable the deno() plugin it does take some effect, but the server start still prints:

```
vinxi starting dev server
Failed to resolve dependency: solid-js, present in 'optimizeDeps.include'
Failed to resolve dependency: solid-js/web, present in 'optimizeDeps.include'
Failed to resolve dependency: solid-js/store, present in 'optimizeDeps.include'
Failed to resolve dependency: solid-js/html, present in 'optimizeDeps.include'
Failed to resolve dependency: solid-js/h, present in 'optimizeDeps.include'
Failed to resolve dependency: @solidjs/start > source-map-js, present in 'optimizeDeps.include'
Failed to resolve dependency: @solidjs/start > error-stack-parser, present in 'optimizeDeps.include'
Failed to resolve dependency: solid-js, present in 'optimizeDeps.include'
Failed to resolve dependency: solid-js, present in 'optimizeDeps.include' (x2)
Failed to resolve dependency: solid-js/web, present in 'optimizeDeps.include'
Failed to resolve dependency: solid-js/web, present in 'optimizeDeps.include' (x2)
Failed to resolve dependency: solid-js/store, present in 'optimizeDeps.include'
Failed to resolve dependency: solid-js/store, present in 'optimizeDeps.include' (x2)
Failed to resolve dependency: solid-js/html, present in 'optimizeDeps.include'
Failed to resolve dependency: solid-js/html, present in 'optimizeDeps.include' (x2)
Failed to resolve dependency: solid-js/h, present in 'optimizeDeps.include'
Failed to resolve dependency: solid-js/h, present in 'optimizeDeps.include' (x2)
Failed to resolve dependency: @solidjs/start > source-map-js, present in 'optimizeDeps.include'
Failed to resolve dependency: @solidjs/start > source-map-js, present in 'optimizeDeps.include' (x2)
Failed to resolve dependency: @solidjs/start > error-stack-parser, present in 'optimizeDeps.include'
Failed to resolve dependency: @solidjs/start > error-stack-parser, present in 'optimizeDeps.include' (x2)
```

**Comment by Ciantic** [comment]
It won't fix this though, it's my attempt.

I have pure repo example here: https://github.com/Ciantic/deno-pure-solid-start

**Comment by birkskyum** [comment]
Maybe this ticket got a bit convoluted, it's possible to split into:
- 1. Run a basic SolidStart with deno.json, no package.json/tsconfig.json
- 2. Add/use a deno-specific jsr package.

**Comment by Ciantic** [comment]
Basic solidStart works for me, in my attempt I get solidstart working *without* jsr packages.

**Comment by birkskyum** [comment]
Oh really, you can run SolidStart without a package.json?

**Comment by Ciantic** [comment]
@birkskyum yes, try this https://github.com/Ciantic/deno-pure-solid-start/tree/main

Then click the counter button.

**Comment by birkskyum** [comment]
Aha, didn't know about the `"dev": "deno run -A --node-modules-dir npm:vinxi dev"` trick

**Comment by Ciantic** [comment]
I've debugged it to somewhere in the `loadAndTransform` and `transformRequest` of vite, the call order is such.

First it always calls `loadAndTransform` and from there it gets a lot of relative URLs, like `./src/deno-sqlite-dialect.ts` etc then fail to be transformed:

```
loadAndTransform deno::TypeScript::@soapbox/kysely-deno-sqlite::C:/Users/jarip/AppData/Local/deno/remote/https/jsr.io/ad3ae390e7fd79d5cf03ee16955d8caa114ad936157a5250fff3a45520a6cb09
transformRequest ./src/deno-sqlite-dialect.ts
transformRequest ./src/deno-sqlite3-dialect.ts
transformRequest ./src/poly-sqlite-dialect.ts
transformRequest ./src/poly-sqlite-driver.ts
transformRequest deno::TypeScript::@db/sqlite::C:/Users/jarip/AppData/Local/deno/remote/https/jsr.io/ff2127150c5fc24dbc6b1daba62c248f566cce7c9346539da1003b4019d972c2
loadAndTransform deno::TypeScript::@db/sqlite::C:/Users/jarip/AppData/Local/deno/remote/https/jsr.io/ff2127150c5fc24dbc6b1daba62c248f566cce7c9346539da1003b4019d972c2
transformRequest ./src/database.ts
transformRequest ./src/blob.ts
transformRequest ./src/statement.ts
transformRequest ./src/util.ts
```

I don't yet understand why it tries to do such a complicated thing for SSR modules.

**Comment by Ciantic** [comment]
Good news everyone, jsr:@db/sqlite working just by using Deno's NPM compatibility mode, the `.npmrc` trick and using `@jsr/db__sqlite` import:

https://github.com/Ciantic/deno-solid-test/

^ I've updated the above repository, and it works.

However pure deno https://github.com/Ciantic/deno-pure-solid-start/ requires probably changes to Vite.

**Comment by alexgleason** [comment]
I think this issue is fixed? On the latest Deno it's working perfectly for me. I have Vite, deno.json with a jsr package, deno-plugin-vite, and no package.json and it's working.
