### ISSUE TITLE
npm package @myriaddreamin/typst-ts-node-compiler stop working in Deno 2.0

### ISSUE THREAD

**Issue by emotilla** [denoland/deno#26592]
Version: Deno 2.0.3
NPM package used to work in Deno 1.4.x
npm@myriaddreamin/typst-ts-node-compiler
npm:@resvg/resvg-js (also same problem)

`
error: Uncaught (in promise) Error: Failed to load native binding
Caused by: [
  Error: Unsupported OS: undefined, architecture: undefined
    at requireNative (file:///Users/enrique/Library/Caches/deno/npm/registry.npmjs.org/@myriaddreamin/typst-ts-node-compiler/0.5.0-rc7/index.js:288:7)
    at Object.<anonymous> (file:///Users/enrique/Library/Caches/deno/npm/registry.npmjs.org/@myriaddreamin/typst-ts-node-compiler/0.5.0-rc7/index.js:293:17)
    at Object.<anonymous> (file:///Users/enrique/Library/Caches/deno/npm/registry.npmjs.org/@myriaddreamin/typst-ts-node-compiler/0.5.0-rc7/index.js:333:4)
    at Module._compile (node:module:748:34)
    at Object.Module._extensions..js (node:module:767:10)
    at Module.load (node:module:665:32)
    at Function.Module._load (node:module:537:12)
    at Module.require (node:module:684:19)
    at require (node:module:808:16)
    at file:///Users/enrique/Library/Caches/deno/npm/registry.npmjs.org/@myriaddreamin/typst-ts-node-compiler/0.5.0-rc7/index.js:3:13
]
`

Contacted the author of both libraries but the response is that a might be an issue to Deno. I think it might be a config issue. Does anyone knows where to define the architecture. It used to work smoothly before migration to Deno 2. 

Thanks!!
E

**Comment by marvinhagemeister** [comment]
What are the full steps to reproduce this error? Which operating system are you on? I've ran this script but I'm not getting any error:

```ts
import * as foo from "npm:@myriaddreamin/typst-ts-node-compiler@0.5.0-rc7";
console.log(foo);
```

**Comment by emotilla** [comment]
I’m using Mac OSX, but the first error was found in deno.land, so it must be a config issue or the migration from deno 1.4x to 2.0.x)

Thanks for writing.. with the example it worked.. I’m testing and separating the code so it can easily replicate the error. It should be a deno install issue.
Once I replicate the error or find a solution I'll let you know. Thanks!

**Comment by bartlomieju** [comment]
Closing as resolved — both packages now work on current Deno.

The `Unsupported OS: undefined, architecture: undefined` error came from the native-binding loader reading `process.platform`/`process.arch` (or `os.platform()`/`os.arch()`) as undefined. Those all return correct values now (`darwin` / `arm64` here), and the platform-specific NAPI subpackages (the `@napi-rs` optionalDependencies pattern, e.g. `...-darwin-arm64`) resolve and load correctly from `node_modules`.

Verified on current `main`:
- `@myriaddreamin/typst-ts-node-compiler@0.7.0` (the package in the title): compiled Typst to SVG successfully.
- `@resvg/resvg-js@2.6.2`: rendered a PNG successfully.

This was filed against Deno 2.0.3; npm native-binding resolution has improved substantially since. If anyone still hits this on a current release, please reopen with a repro and the exact version + platform.
