### ISSUE TITLE
Node: HTTP request fails on `res.complete`

### ISSUE THREAD

**Issue by vicary** [denoland/deno#26733]
Version: Deno 2.0.2

In `npm:@adyen/api-library` they use Node's native `http` to send POST requests and it always fails in Deno with the following error:
```
An error occurred during route handling or page rendering.

  141 |                 res.on("end", () => {
  142 |                     if (!res.complete) {
> 143 |                         reject(new Error("The connection was terminated while the message was still being sent"));
      |                                ^
  144 |                     }
  145 |                     if (res.statusCode && (res.statusCode < 200 || res.statusCode >= 300)) {
  146 |                         try {

Error: The connection was terminated while the message was still being sent
    at IncomingMessageForClient.<anonymous> (file:///Users/vicary/Library/Caches/deno/npm/registry.npmjs.org/@adyen/api-library/20.0.0/lib/src/httpClient/httpURLConnectionClient.js:143:32)
    at IncomingMessageForClient.emit (ext:deno_node/_events.mjs:393:28)
    at endReadableNT (ext:deno_node/_stream.mjs:3210:16)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:36:15)
    at runNextTicks (ext:deno_node/_next_tick.ts:75:3)
    at eventLoopTick (ext:core/01_core.js:182:21)
```
Their [source code](https://github.com/Adyen/adyen-node-api-library/blob/fd0f0f45a0d2c24ba30458f3d49fc2ae058cd049/src/httpClient/httpURLConnectionClient.ts#L151) is checking `res.complete` the same way as [Deno recommended](https://docs.deno.com/api/node/http/~/IncomingMessage.prototype.complete).

Running the same script in Node.js works without problems, is it a Node compatibility issue?

**Comment by vicary** [comment]
Wrapping Adyen's `res.on("end", () => { ... })` callback in a `queueMicrotask()` gives enough time for the request to finish. 

For maximum Node.js compatibility, should Deno be waiting a short delay before firing the "end" event? e.g. until the current socket buffer is cleared

**Comment by bartlomieju** [comment]
Fixed in https://github.com/denoland/deno/pull/33208
