### ISSUE TITLE
Can't read from a file with `{ write: true }`

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#26759]
Version: Deno 2.0.5

I need to open a file, lock it, read from it, and then write to it. But no configuration of `Deno.open` lets me read and write to the same `Deno.FsFile` instance.

```ts
const file = await Deno.open('README.md', { write: true });

const bytes = await new Response(file.readable).arrayBuffer();

console.log(new TextEncoder().encode(bytes));
```

It says:

```
Uncaught Error: Bad file descriptor (os error 9)
    at async readableStreamCollectIntoUint8Array (ext:deno_web/06_streams.js:1066:19)
    at async consumeBody (ext:deno_fetch/22_body.js:254:9)
    at async <anonymous>:4:15
```

If I set `{ read: true }` it works. But then I cannot write to it. With `{ read: true, write: true }` I can read but not write to it:

```
Uncaught BadResource: Bad resource ID
    at write (ext:deno_io/12_io.js:52:15)
    at FsFile.write (ext:deno_fs/30_fs.js:585:12)
>     at <anonymous>:1:27
```

I need to lock the file. The only way to lock is with an instance of `Deno.FsFile`, which I can only get from `Deno.open`. But it's impossible to do it.

**Comment by alexgleason** [comment]
Apparently I can still read files even if I have an exclusive lock, so I worked around it like this:

```ts
using write = await Deno.open(path, { write: true });
await write.lock(true);

using read = await Deno.open(path, { read: true });
const bytes = await new Response(read.readable).bytes();
```

Maybe this is the intended behavior. :shrug: I thought the lock would prevent reads.

**Comment by kt3k** [comment]
> With { read: true, write: true } I can read but not write to it:

I think it's not writable because `new Response(file.readable).arrayBuffer()` call doesn't release the reader internally. If I call `getReader()` and `reader.releaseLock()` manually, then it can write after reading.

```js
const file = await Deno.open('README.md', { read: true, write: true });
const reader = file.readable.getReader();
console.log(await reader.read());
reader.releaseLock();
await new Response("hello").body.pipeTo(file.writable);
```

**Comment by brc-dd** [comment]
Manually releasing the lock also doesn't work. The example above throws:

```ts
{ value: undefined, done: true }
error: Uncaught (in promise) BadResource: Bad resource ID
    at Object.write (ext:deno_web/06_streams.js:1181:20)
    at Module.invokeCallbackFunction (ext:deno_webidl/00_webidl.js:1116:16)
    at WritableStreamDefaultController.writeAlgorithm (ext:deno_web/06_streams.js:3952:14)
    at writableStreamDefaultControllerProcessWrite (ext:deno_web/06_streams.js:4522:55)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (ext:deno_web/06_streams.js:4425:5)
    at writableStreamDefaultControllerWrite (ext:deno_web/06_streams.js:4569:3)
    at writableStreamDefaultWriterWrite (ext:deno_web/06_streams.js:4716:3)
    at Object.chunkSteps (ext:deno_web/06_streams.js:2780:17)
    at ReadableStreamDefaultController.[[[PullSteps]]] (ext:deno_web/06_streams.js:6125:19)
    at readableStreamDefaultReaderRead (ext:deno_web/06_streams.js:2544:36)
```

Maybe it used to work in some version, but can't seem to make it work with the latest (deno 2.3.3).

**Comment by kt3k** [comment]
The above script still works on my machine (macOS) with latest Deno (2.3.3), and your version also works. (They both writes `hello` to the end of `README.md`)

Maybe there's some race condition depending on the platform. What OS do you use?

BTW on my machine `console.log(await reader.read())` part prints `{ value: Uint8Array(3664) [...], done: false }`, instead of `{ value: undefined, done: true }`. That might be related.

**Comment by brc-dd** [comment]
Ah, I'm also on macOS. It logs undefined with empty README.md (`rm README.md; touch README.md`).

**Comment by 0f-0b** [comment]
As a rule of thumb, properties and methods on `Deno.FsFile` can be divided into 3 groups, where different groups do not mix well.

- (sequential read) `readable`.
- (sequential write) `writable`.
- (random access) `read`, `write`, `seek`, `truncate`, `close`.

It follows that if you want to read from and write to the same file handle, it's best to use methods in the “random access” group and not the “sequential read” or “sequential write” groups. [`@std/io`](https://jsr.io/@std/io/doc) has helper functions for working with those methods. For example, to read the entirety of `README.md` and then append `hello` to it,

```js
import { readAll } from "jsr:@std/io@^0.225.0/read-all";
import { writeAll } from "jsr:@std/io@^0.225.0/write-all";

const encoder = new TextEncoder();
using file = await Deno.open("README.md", { read: true, write: true });
console.log(await readAll(file));
await writeAll(file, encoder.encode("hello"));
```

**Comment by kt3k** [comment]
@brc-dd Ah, ok. Thanks. I can reproduce the issue with empty `README.md`.. This looks like a bug to me

@0f-0b 
> As a rule of thumb, properties and methods on Deno.FsFile can be divided into 3 groups, where different groups do not mix well.

oh, interesting.. I wasn't aware of that rule. I'm not sure that is intentional or not

**Comment by bartlomieju** [comment]
Closing this one after re-checking all the scenarios from this thread on the current canary (2.8.2+ecc3053):

1. **`Deno.open` with `{ write: true }` only, then reading from `file.readable`** still fails with `Bad file descriptor (os error 9)`, and that is expected. The file is opened write-only (`O_WRONLY`), so reads on the descriptor fail per OS semantics. To read and write the same handle, open it with `{ read: true, write: true }`.

2. **`{ read: true, write: true }`, draining `file.readable`, then calling `file.write()`** fails with `BadResource`, which is also by design: consuming the `readable` stream to EOF closes the underlying resource, because the stream takes ownership of the handle. As @0f-0b explained above, the APIs on `Deno.FsFile` fall into three groups (sequential read via `readable`, sequential write via `writable`, and random access via `read`/`write`/`seek`/`truncate`), and mixing groups on the same handle doesn't work. For the lock-read-write use case from the original report, use the random access methods (optionally with the helpers in [`@std/io`](https://jsr.io/@std/io/doc)).

3. **The empty file bug confirmed by @kt3k** (reading an empty file via `file.readable` resolved to `undefined`) is fixed: it now correctly returns an empty `ArrayBuffer`.

So the one genuine bug reported here no longer reproduces, and the remaining behaviors follow OS and stream-ownership semantics. If the stream-ownership behavior of `FsFile.readable` is surprising, that's worth a docs improvement; feel free to open a follow-up issue for that.
