### ISSUE TITLE
thread 'main' panicked at ext/cache/sqlite.rs:62:10: failed to execute pragmas: SqliteFailure(Error { code: ReadOnly, extended_code: 8 }, Some("attempt to write a readonly database"))

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#26775]
I'm not sure the cause of this yet. I upgraded Deno to the latest version and then changed ownership of the repo and systemd unit to a different user. I am making heavy use of the Web Cache API.

```
Nov 07 22:51:41 mostr deno[442486]: Task start deno run -A src/server.ts
Nov 07 22:51:42 mostr deno[442490]: Download https://jsr.io/@db/sqlite/0.11.1_meta.json
Nov 07 22:51:42 mostr deno[442490]: ============================================================
Nov 07 22:51:42 mostr deno[442490]: Deno has panicked. This is a bug in Deno. Please report this
Nov 07 22:51:42 mostr deno[442490]: at https://github.com/denoland/deno/issues/new.
Nov 07 22:51:42 mostr deno[442490]: If you can reliably reproduce this panic, include the
Nov 07 22:51:42 mostr deno[442490]: reproduction steps and re-run with the RUST_BACKTRACE=1 env
Nov 07 22:51:42 mostr deno[442490]: var set and include the backtrace in your report.
Nov 07 22:51:42 mostr deno[442490]: Platform: linux x86_64
Nov 07 22:51:42 mostr deno[442490]: Version: 2.0.5
Nov 07 22:51:42 mostr deno[442490]: Args: ["/usr/local/bin/deno", "run", "-A", "src/server.ts"]
Nov 07 22:51:42 mostr deno[442490]: thread 'main' panicked at ext/cache/sqlite.rs:62:10:
Nov 07 22:51:42 mostr deno[442490]: failed to execute pragmas: SqliteFailure(Error { code: ReadOnly, extended_code: 8 }, Some("attempt to write a readonly database"))
Nov 07 22:51:42 mostr deno[442490]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 07 22:51:42 mostr systemd[1]: mostr.service: Main process exited, code=exited, status=1/FAILURE
Nov 07 22:51:42 mostr systemd[1]: mostr.service: Failed with result 'exit-code'.
Nov 07 22:51:42 mostr systemd[1]: mostr.service: Scheduled restart job, restart counter is at 5.
Nov 07 22:51:42 mostr systemd[1]: Stopped Mostr.
Nov 07 22:51:42 mostr systemd[1]: mostr.service: Start request repeated too quickly.
Nov 07 22:51:42 mostr systemd[1]: mostr.service: Failed with result 'exit-code'.
Nov 07 22:51:42 mostr systemd[1]: Failed to start Mostr.
```

**Comment by alexgleason** [comment]
`rm -rf /tmp/deno_cache` fixed it. It was owned by the wrong user.
