### ISSUE TITLE
Deno executable doesn't work

### ISSUE THREAD

**Issue by NarHakobyan** [denoland/deno#26790]
Version: Deno 2.0.5

Deno Executable doesn't work and gives an error, but Deno run ... works perfect

```
error: Uncaught (in promise) TypeError: dlopen(/var/folders/0_/grgr92551ls_dpn4hjkj9vzr0000gn/T/deno-compile-main/awesome-nest-boilerplate/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node, 0x0001): tried: '/var/folders/0_/grgr92551ls_dpn4hjkj9vzr0000gn/T/deno-compile-main/awesome-nest-boilerplate/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/0_/grgr92551ls_dpn4hjkj9vzr0000gn/T/deno-compile-main/awesome-nest-boilerplate/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node' (no such file), '/var/folders/0_/grgr92551ls_dpn4hjkj9vzr0000gn/T/deno-compile-main/awesome-nest-boilerplate/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node' (no such file)
    at Object.Module._extensions..node (node:module:807:20)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:818:16)
    at Object.<anonymous> (file:///var/folders/0_/grgr92551ls_dpn4hjkj9vzr0000gn/T/deno-compile-main/awesome-nest-boilerplate/node_modules/bcrypt/bcrypt.js:6:16)
    at Object.<anonymous> (file:///var/folders/0_/grgr92551ls_dpn4hjkj9vzr0000gn/T/deno-compile-main/awesome-nest-boilerplate/node_modules/bcrypt/bcrypt.js:238:4)
    at Module._compile (node:module:745:34)
    at Object.Module._extensions..js (node:module:762:10)
    at Module.load (node:module:662:32)
```

**Comment by dsherret** [comment]
See and follow https://github.com/denoland/deno/issues/23266
