### ISSUE TITLE
Error: Cannot find package.json (astro compat issue)

### ISSUE THREAD

**Issue by quadratz** [denoland/deno#26794]
I’m not sure if this is the right repo for this issue, so my apologies if it’s actually related to the `Astro` or `vitefu` package instead of Deno. Please let me know, and I’ll open the issue in the correct repository. Thank you.

**Folder structure**:
```ascii
.
├─ deno.json
└─ src/
   └─ pages/
      └─ index.astro
```
**deno.json**:
```json
{
  "lock": false,
  "nodeModulesDir": "auto",
  "tasks": {
    "setup": "deno install && astro sync --verbose"
  },
  "imports": {
    "@astrojs/check": "npm:@astrojs/check@0.9.4",
    "astro": "npm:astro@5.0.0-beta.7",
    "typescript": "npm:typescript@5.6.3"
  }
}
```

**Cmd**:
```
deno task setup
```

**Output**:
```log
Cannot find package.json from /tmp/deno-bug/
  Location:
    /tmp/deno-bug/node_modules/.deno/vitefu@1.0.3/node_modules/vitefu/src/index.js:33:13
  Stack trace:
    at crawlFrameworkPkgs (file:///tmp/deno-bug/node_modules/.deno/vitefu@1.0.3/node_modules/vitefu/src/index.js:33:13)
    at async syncContentCollections (file:///tmp/deno-bug/node_modules/.deno/astro@5.0.0-beta.7/node_modules/astro/dist/core/sync/index.js:144:5)
    at async sync (file:///tmp/deno-bug/node_modules/.deno/astro@5.0.0-beta.7/node_modules/astro/dist/core/sync/index.js:48:10)
    at async runCommand (file:///tmp/deno-bug/node_modules/.deno/astro@5.0.0-beta.7/node_modules/astro/dist/cli/index.js:104:7)
```

**Version**:
deno 2.0.5+73fbd61 (canary, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2

**Comment by KnorpelSenf** [comment]
I think I ran into the same issue. In your case `astro` is not actually run by Deno. It is specific to Node that the `.bin` directory of the `node_modules` gets added to the path inside `npm run` scripts.

With Deno, you need to type out `deno -A npm:astro` if you want to run the package that you installed. Otherwise, it will run the globally installed CLI `astro`.

**Comment by kt3k** [comment]
What @KnorpelSenf points sounds true to me. deno.json's `tasks` script doesn't pick up executable from `node_modules/.bin`. You need to write "tasks" like:

```
{
  "tasks": {
    "setup": "deno install && deno -A npm:astro sync --verbose"
  }
}
```

With the above modification, I was able to run `deno task setup` successfully

**Comment by kt3k** [comment]
Looks like the above issue was resolved in upstream here https://github.com/svitejs/vitefu/commit/b7b5478cc888948b94be2273da10d4bbc80a2ab3

I can just execute `deno task setup` with the above settings successfully.

@quadratz Can you test it again after running the command `deno install --reload`?

**Comment by quadratz** [comment]
I did run the test after `deno install --reload`, and it works without any issues. Thanks for the update!
