### ISSUE TITLE
node-opcua-client (npm) with Deno

### ISSUE THREAD

**Issue by MGMehdi** [denoland/deno#26870]
Version: deno 2.0.6 (stable, release, x86_64-pc-windows-msvc)
Hello,
I want to try to migrate a little app to Deno because the compile option suit my need and that now it support npm package.
I want to use the npm package node-opcua-client  but I've got this error message

```
error: Uncaught (in promise) DataError: 'key_ops' property of JsonWebKey is invalid
    at importKeyRSA (ext:deno_crypto/00_crypto.js:3849:17)
    at importKeyInner (ext:deno_crypto/00_crypto.js:3585:14)
    at SubtleCrypto.importKey (ext:deno_crypto/00_crypto.js:989:26)
    at buildPublicKey (file:///D:/Code/DenoTest/node_modules/.deno/node-opcua-crypto@4.12.0/node_modules/node-opcua-crypto/dist/index.js:2026:42)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async createSelfSignedCertificate (file:///D:/Code/DenoTest/node_modules/.deno/node-opcua-crypto@4.12.0/node_modules/node-opcua-crypto/dist/index.js:6203:21)
```

NodeOPCUA creates automatically a default certificate when a client is first started. But my guess is either the symlink deno create for node_modules cause the issues or a permission missing but I already run the project using -A. I don't have this with Node
Can you help me troubleshooting this ? 

Here is the code I use for testing

```js
import {
  MessageSecurityMode,
  OPCUAClient,
  SecurityPolicy,
} from "npm:node-opcua-client";

const connectionStrategy = {
  initialDelay: 1000,
  maxRetry: 1,
};

const client = OPCUAClient.create({
  applicationName: "MyClient",
  connectionStrategy: connectionStrategy,
  securityMode: MessageSecurityMode.None,
  securityPolicy: SecurityPolicy.None,
  endpointMustExist: false,
});
const endpointUrl = "opc.tcp://opcuademo.sterfive.com:26543";

await client.connect(endpointUrl);
console.log("connected");
```

**Comment by MGMehdi** [comment]
Hello,
any news about that issue ?

**Comment by MGMehdi** [comment]
`deno 2.1.5`

If it can help, if node-opc-ua has not yet generated a certificate (empty or non-existent folder) this error appears even when only running `deno -A main.ts`
```
13:59:44.287Z :client_base_impl              :586   Creating default certificate ... please wait
error: Uncaught (in promise) DataError: 'key_ops' property of JsonWebKey is invalid
    at importKeyRSA (ext:deno_crypto/00_crypto.js:3849:17)
    at importKeyInner (ext:deno_crypto/00_crypto.js:3585:14)
    at SubtleCrypto.importKey (ext:deno_crypto/00_crypto.js:989:26)
    at buildPublicKey (file:///D:/Code/DenoTest/node_modules/.deno/node-opcua-crypto@4.12.0/node_modules/node-opcua-crypto/dist/index.js:2026:42)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async createSelfSignedCertificate (file:///D:/Code/DenoTest/node_modules/.deno/node-opcua-crypto@4.12.0/node_modules/node-opcua-crypto/dist/index.js:6203:21)
```

Certificates are generate here `C:\Users\USER\AppData\Roaming\node-opcua-default-nodejs`

**Comment by MGMehdi** [comment]
Hello,
just to thank you, I was able to compile and install the project for our customer!
