### ISSUE TITLE
deno compile: npm package node-red seems to not work

### ISSUE THREAD

**Issue by Crafter-Y** [denoland/deno#26876]
deno 2.0.6 (stable, release, x86_64-pc-windows-msvc)
v8 12.9.202.13-rusty
typescript 5.6.2
current latest node-red: 4.0.5

# Steps to reproduce:

1. `deno install npm:node-red`
2. `deno run --allow-all npm:node-red --userDir ./nodeRedData` (seems to work fine)
3. delete the ./nodeRedData
4. `deno compile -o nodered.exe --allow-all npm:node-red --userDir ./nodeRedData`
5. `.\nodered.exe`

```powershell
PS F:\programming\deno-compile-test> .\nodered.exe
error: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getTime')
    at Object.<anonymous> (file:///C:/Users/MY_NAME/AppData/Local/Temp/deno-compile-nodered.exe/.deno_compile_node_modules/localhost/node-red/4.0.5/red.js:145:36)
    at Object.<anonymous> (file:///C:/Users/MY_NAME/AppData/Local/Temp/deno-compile-nodered.exe/.deno_compile_node_modules/localhost/node-red/4.0.5/red.js:565:4)
    at Module._compile (node:module:745:34)
    at Object.Module._extensions..js (node:module:762:10)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at file:///C:/Users/BASTIP~1/AppData/Local/Temp/deno-compile-nodered.exe/.deno_compile_node_modules/localhost/node-red/4.0.5/red.js:5:32
```

# My expectation

I expect the compile command to behave the same like the run command before. But it just throws an error.

**Comment by bartlomieju** [comment]
The original crash (`Cannot read properties of null (reading 'getTime')`) was caused by `fs.statSync()` returning `null` for `mtime`/`ctime` on files inside the compiled binary's virtual filesystem. This specific bug was fixed in #28731 (becf24c8c, April 2025).

However, the compiled binary still does **not** work. After the mtime fix, there's a different error — `require()` of files outside the embedded VFS fails:

```
Error loading settings file: /Users/ib/.node-red/settings.js
NotFound: path not found
    at loadMaybeCjs (node:module:1138:19)
    at Object..js (node:module:1123:12)
    ...
```

The file exists on disk and is valid CJS (`module.exports = {…}`), but the compiled binary cannot load it. `deno run npm:node-red` works fine — it successfully loads external settings files via `require()`.

So the issue is partially fixed (mtime) but still broken due to what appears to be a `require()` resolution bug in compiled binaries when loading files from outside the embedded VFS.

Tested on main at 6048a0d (macOS arm64).
