### ISSUE TITLE
Deno v2 throws error on simple Mysql2 snippet

### ISSUE THREAD

**Issue by acrodrig** [denoland/deno#26902]
Deno Version: Deno 2.0.1.

Trying to run the following snippet from the Mysql2 [documentation](https://sidorares.github.io/node-mysql2/docs):

```typescript
// Get the client
import mysql from "mysql2/promise";

// Create the connection to database
const connection = await mysql.createConnection({
  host: "localhost",
  user: "me"
});

// A simple SELECT query
try {
  const [results, fields] = await connection.query("SELECT 1 + 1");
  console.log(results); // results contains rows returned by server
  console.log(fields); // fields contains extra meta data about results, if available
} catch (err) {
  console.log(err);
}
```

Throws the following:

```text
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setNoDelay')
    at TCP.setNoDelay (ext:deno_node/internal_binding/tcp_wrap.ts:229:28)
    at Socket.setNoDelay (node:net:595:20)
    at new Connection (file:///Users/andres/Library/Caches/deno/npm/registry.npmjs.org/mysql2/3.11.4/lib/connection.js:64:21)
    at Object.exports.createConnection (file:///Users/andres/Library/Caches/deno/npm/registry.npmjs.org/mysql2/3.11.4/index.js:10:10)
    at Object.createConnection (file:///Users/andres/Library/Caches/deno/npm/registry.npmjs.org/mysql2/3.11.4/promise.js:252:31)
    at file:///Users/andres/.../test/mysql2.ts:7:32
```

**Comment by nathanwhit** [comment]
Try updating to the latest version of deno, this issue should have been fixed in 2.0.2

**Comment by bartlomieju** [comment]
Closing due to lack of response to the information request. Please reopen if you can provide the requested details.
