### ISSUE TITLE
Uncaught BadResource error when closing the process and it has status promise callback

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#2692]
The following script starts `deno` (repl) process and stop it.

```ts
window.onload = async () => {
  const p = Deno.run({ args: [Deno.execPath] });
  p.close();
};
```

This exits with 0. But if we hook a callback to `.status()` promise, then it throws an uncaught error:

```ts
window.onload = async () => {
  const p = Deno.run({ args: [Deno.execPath] });
  p.status().then(() => {
    console.log(1);
  });
  p.close();
};
```

The above scripts throws the following:
```
error: Uncaught BadResource: bad resource id
► js/errors.ts:33:12
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at handleAsyncMsgFromRust (js/dispatch.ts:41:17)
    at handleAsyncMsgFromRust (shared_queue.js:157:9)
```
Is this intended behavior?

**Comment by ry** [comment]
Hard for me to say... My first thought is that this is intended behavior, because the subprocess resource was closed before the subprocess exited.

It's a confusing error message though. I could also see how we could throw a better error message from status() if the subprocess resource was already closed...

**Comment by nayeem-rahman** [comment]
The Promise is rejecting as it should, it has nothing to do with the callback:
```javascript
window.onload = async () => {
  const p = Deno.run({ args: [Deno.execPath] });
  p.status();
  p.close();
};
```
throws the same thing.

> if the subprocess resource was already closed...

I think that more applies to this script:
```javascript
window.onload = async () => {
  const p = Deno.run({ args: [Deno.execPath] });
  p.close();
  p.status();
};
```
which throws this:
```
error: Uncaught BadResource: bad resource id
► js/errors.ts:33:12
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at sendInternal (js/dispatch.ts:103:19)
    at sendAsync (js/dispatch.ts:121:10)
    at runStatus (js/process.ts:40:25)
    at status (js/process.ts:91:18)
    at window.onload (file:///mnt/c/Users/Nayeem/temp/a.js:4:5)
    at js/globals.ts:156:7
    at handleEvent (js/event_target.ts:89:10)
    at innerInvokeEventListeners (js/event_target.ts:484:20)
```
This one could be fixed by making status() synchronously check p's state before explicitly returning a Promise (i.e, no `async`). The original one seems a lot more difficult and will happen no matter how long you wait before closing:
```javascript
window.onload = async () => {
  const p = Deno.run({ args: [Deno.execPath] });
  p.status();
  setTimout(() => p.close(), 5000);
};
```
does the same.

I don't think it's safe for processes to be closeable this way, but the resource generalisation insists on it. Maybe get rid of Process::close() to discourage it?
