### ISSUE TITLE
Crawlee/Playwright struggles to start with default project

### ISSUE THREAD

**Issue by drewbitt** [denoland/deno#26925]
Version: Deno 2.0.6
macOS 15.2 arm64
https://github.com/apify/crawlee

## Reproduction

```
deno run -A npm:crawlee create crawlee -t getting-started-ts
cd crawlee
deno run -A npm:playwright install
deno run -A src/main.ts
```

## Result
```
❯ deno run -A src/main.ts
INFO  PlaywrightCrawler: Starting the crawler.
WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. page.goto: net::ERR_TIMED_OUT at https://crawlee.dev/
Call log:
  - navigating to "https://crawlee.dev/", waiting until "load"

    at eventLoopTick (/Users/drewbitt/Documents/Repos/crawlee/ext:core/01_core.js:214:9) {"id":"3FULW9cbbkMrV4R","url":"https://crawlee.dev","retryCount":1}
INFO  PlaywrightCrawler:Statistics: PlaywrightCrawler request statistics: {"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":null,"requestsFinishedPerMinute":0,"requestsFailedPerMinute":0,"requestTotalDurationMillis":0,"requestsTotal":0,"crawlerRuntimeMillis":60151,"retryHistogram":[]}
INFO  PlaywrightCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
```

## Expected result

Same command with tsx 
```
❯ npx tsx src/main.ts
INFO  PlaywrightCrawler: Starting the crawler.
INFO  PlaywrightCrawler: Title of https://crawlee.dev/ is 'Crawlee · Build reliable crawlers. Fast.'
```

## Comments

Crawlee encourages CLI usage so this is a typical flow someone might do to start a new crawlee project in Deno, even though it installs a node project only for now.

**Comment by jonaylor89** [comment]
a lot of the Crawlee crawlers seem to not work. For example, swapping with the `CheerioCrawler` one gets

```
error: Uncaught (in promise) BadResource: Bad resource ID
    at node:http2:363:42
    at Object.runMicrotasks (ext:core/01_core.js:686:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:59:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:76:3)
    at eventLoopTick (ext:core/01_core.js:184:21)
```

**Comment by jonaylor89** [comment]
I got it to work with `CheerioCrawler` by using a custom `httpClient`. I put the implementation here 

https://gist.github.com/jonaylor89/dbfc2b9b3d6f34d275d47ee1a5d5119d

**Comment by drewbitt** [comment]
Fixed in Deno 2.7.6
