### ISSUE TITLE
Vite & Astro SSR regression

### ISSUE THREAD

**Issue by mikepayne02** [denoland/deno#26960]
Version: Deno 2.1.0

This did not occur with versions before 2.1.0.

```
❯ deno task build
Task build astro check && astro build
1:09:03 AM [vite] (ssr) Error when evaluating SSR module /Users/michael/Documents/portfolio/astro.config.ts:
|- Error: TypeScript files are not supported in npm packages: file:///Users/michael/Documents/portfolio/node_modules/.deno/capnp-ts@0.7.0/node_modules/capnp-ts/src/serialization/index.ts
    at Object.Module._extensions..js.Module._extensions..ts.Module._extensions..jsx.Module._extensions..tsx (node:module:752:19)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:797:16)
    at Object.<anonymous> (file:///Users/michael/Documents/portfolio/node_modules/.deno/capnp-ts@0.7.0/node_modules/capnp-ts/src/index.js:7:23)
    at Object.<anonymous> (file:///Users/michael/Documents/portfolio/node_modules/.deno/capnp-ts@0.7.0/node_modules/capnp-ts/src/index.js:54:4)
    at Module._compile (node:module:745:34)
    at Object.Module._extensions..js.Module._extensions..ts.Module._extensions..jsx.Module._extensions..tsx (node:module:754:10)
    at Module.load (node:module:662:32)

[astro] Unable to load your Astro config
```

Capn proto seems to not like astro's method of configuration?

**Comment by vladjerca** [comment]
SvelteKit is also broken with `2.1.0`.

Build:

```sh
Task build vite build
error during build:
Error: TypeScript files are not supported in npm packages: .../node_modules/.deno/capnp-ts@0.7.0/node_modules/capnp-ts/src/serialization/index.ts
    at Object.Module._extensions..js.Module._extensions..ts.Module._extensions..jsx.Module._extensions..tsx (node:module:752:19)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:797:16)
    at Object.<anonymous> (.../node_modules/.deno/capnp-ts@0.7.0/node_modules/capnp-ts/src/index.js:7:23)
    at Object.<anonymous> (.../node_modules/.deno/capnp-ts@0.7.0/node_modules/capnp-ts/src/index.js:54:4)
    at Module._compile (node:module:745:34)
    at Object.Module._extensions..js.Module._extensions..ts.Module._extensions..jsx.Module._extensions..tsx (node:module:754:10)
    at Module.load (node:module:662:32)
```

Test:

```sh
Task test deno task test:unit --run && deno task test:e2e
Task test:unit vitest "--run"

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Startup Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: TypeScript files are not supported in npm packages: .../node_modules/.deno/capnp-ts@0.7.0/node_modules/capnp-ts/src/serialization/index.ts
    at Object.Module._extensions..js.Module._extensions..ts.Module._extensions..jsx.Module._extensions..tsx (node:module:752:19)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:797:16)
    at Object.<anonymous> (.../node_modules/.deno/capnp-ts@0.7.0/node_modules/capnp-ts/src/index.js:7:23)
    at Object.<anonymous> (.../node_modules/.deno/capnp-ts@0.7.0/node_modules/capnp-ts/src/index.js:54:4)
    at Module._compile (node:module:745:34)
    at Object.Module._extensions..js.Module._extensions..ts.Module._extensions..jsx.Module._extensions..tsx (node:module:754:10)
    at Module.load (node:module:662:32)
```

**Comment by dsherret** [comment]
Interesting. Looking into it.

**Comment by dsherret** [comment]
Sorry about this! We're going to do a hotfix for this one.

**Comment by dsherret** [comment]
Should be fixed now
