### ISSUE TITLE
Deno compile code cache seems not working when error thrown during module loading

### ISSUE THREAD

**Issue by felipecrs** [denoland/deno#26976]
Version: Deno 2.1.0

- Initially reported here: https://github.com/denoland/deno/pull/26528#issuecomment-2491735952

Reproduction:

```console
# clone pkgx
$ cd /tmp
$ git clone https://github.com/pkgxdev/pkgx
$ cd pkgx

# confirm deno is at the right version
$ deno upgrade 2.1.0

# let's cleanup the cache just in case
$ deno clean

# same as "deno task compile", but with --log-level debug
$ deno compile --lock=deno.lock --allow-all --output "$INIT_CWD/pkgx" --log-level debug ./entrypoint.ts

# cache was not supposed to work on first attempt indeed
$ ./pkgx --version 2>&1 | grep cache
DEBUG RS - denort::cache::cache_db:170 - Opening cache /home/felipecrs/.cache/deno/node_analysis_cache_v2...
DEBUG RS - denort::standalone::code_cache:56 - Failed to deserialize code cache: Cache key mismatch
DEBUG RS - denort::cache::cache_db:389 - Created parent directory for cache db.
× unexpected error unversioned developer build
│ Error: unversioned developer build
│     at default (file:///tmp/deno-compile-pkgx-cc/pkgx/src/modes/version.ts:2:9)
│     at default (file:///tmp/deno-compile-pkgx-cc/pkgx/src/app.ts:145:27)
│     at file:///tmp/deno-compile-pkgx-cc/pkgx/entrypoint.ts:59:9
╰─➤ https://github.com/pkgxdev/pkgx/issues/new

# but even on second attempt it still seems to fail
$ ./pkgx --version 2>&1 | grep cache
DEBUG RS - denort::cache::cache_db:170 - Opening cache /home/felipecrs/.cache/deno/node_analysis_cache_v2...
DEBUG RS - denort::standalone::code_cache:56 - Failed to deserialize code cache: Cache key mismatch
× unexpected error unversioned developer build
│ Error: unversioned developer build
│     at default (file:///tmp/deno-compile-pkgx-cc/pkgx/src/modes/version.ts:2:9)
│     at default (file:///tmp/deno-compile-pkgx-cc/pkgx/src/app.ts:145:27)
│     at file:///tmp/deno-compile-pkgx-cc/pkgx/entrypoint.ts:59:9
╰─➤ https://github.com/pkgxdev/pkgx/issues/new
```

**Comment by dsherret** [comment]
I think what's happening here is its using a code cache from a previous build, but `./pkgx --version 2>&1` is erroring on "unversioned developer build" before it code caches all the modules? If you have a successful run you should see it use the code cache I think.

I'll add the code cache path to the debug logs.

**Comment by felipecrs** [comment]
Oh ok, indeed, if I try a working command, code cache seems to be working:

```console
❯ ./pkgx --sync 2>&1 | grep cache
DEBUG RS - denort::cache::cache_db:170 - Opening cache /home/felipecrs/.cache/deno/node_analysis_cache_v2...
DEBUG RS - denort::standalone::code_cache:45 - Loaded 216 code cache entries
```

**Comment by dsherret** [comment]
Yeah, it doesn't save the code cache if it errors during module loading. Perhaps there could be a partial save done in some cases, but I'm not sure it's worth the effort.

**Comment by felipecrs** [comment]
Yeah, probably not worth it. Feel free to close this issue then.
