### ISSUE TITLE
can not start 

### ISSUE THREAD

**Issue by aohanhongzhi** [denoland/deno#27026]
Version: Deno 2.1.1

```javascript
deno task beta
Task beta vite --mode test
failed to load config from /Users/HOX4SGH/Project/Go/kuaima/kuaima-admin/vite.config.ts
error when starting dev server:
TypeError: Cannot convert undefined or null to object
    at getOwnPropertyDescriptor (<anonymous>)
    at file:///Users/HOX4SGH/Project/Go/kuaima/kuaima-admin/node_modules/.deno/typed-array-byte-offset@1.0.2/node_modules/typed-array-byte-offset/index.js:32:18
    at forEachArray (file:///Users/HOX4SGH/Project/Go/kuaima/kuaima-admin/node_modules/.deno/for-each@0.3.3/node_modules/for-each/index.js:12:17)
    at forEach (file:///Users/HOX4SGH/Project/Go/kuaima/kuaima-admin/node_modules/.deno/for-each@0.3.3/node_modules/for-each/index.js:54:9)
    at Object.<anonymous> (file:///Users/HOX4SGH/Project/Go/kuaima/kuaima-admin/node_modules/.deno/typed-array-byte-offset@1.0.2/node_modules/typed-array-byte-offset/index.js:22:2)
    at Object.<anonymous> (file:///Users/HOX4SGH/Project/Go/kuaima/kuaima-admin/node_modules/.deno/typed-array-byte-offset@1.0.2/node_modules/typed-array-byte-offset/index.js:80:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:755:12)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:812:16)
    at Object.<anonymous> (file:///Users/HOX4SGH/Project/Go/kuaima/kuaima-admin/node_modules/.deno/es-abstract@1.23.3/node_modules/es-abstract/2024/IsTypedArrayOutOfBounds.js:11:28)
    at Object.<anonymous> (file:///Users/HOX4SGH/Project/Go/kuaima/kuaima-admin/node_modules/.deno/es-abstract@1.23.3/node_modules/es-abstract/2024/IsTypedArrayOutOfBounds.js:56:4)
    at Module._compile (node:module:745:34)
```

<img width="1481" alt="image" src="https://github.com/user-attachments/assets/93ec9d5b-7390-4ae5-992e-fe03ef334d8a">

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/6b2b3147-2950-4029-b7e6-b5a53dba8a6a">

Both Bun and npm can start correctly.

<img width="676" alt="image" src="https://github.com/user-attachments/assets/5d046ae6-a229-4583-88cb-7ba659419f8e">

**Comment by 0f-0b** [comment]
This bug might have been fixed in the latest version of `typed-array-byte-offset` (released yesterday). Can you try updating the dependency by deleting `deno.lock` and then rerunning your app?

**Comment by dsherret** [comment]
Or else run with `--unstable-unsafe-proto`
