### ISSUE TITLE
`Deno.permissions.query({name:"imports"})` is not supported

### ISSUE THREAD

**Issue by lowlighter** [denoland/deno#27050]
Version: Deno 2.1.1

It's not possible to query `--allow-imports` descriptor currently

```ts
console.log(await Deno.permissions.query({name:"imports"}))
```
```
Uncaught TypeError: The provided value "imports" is not a valid permission name
    at Permissions.querySync (ext:runtime/10_permissions.js:211:13)
    at Permissions.query (ext:runtime/10_permissions.js:203:34)
    at <anonymous>:1:57
```

Possibly just a quick fix to do in:
https://github.com/denoland/deno/blob/12b377247be2b74155ded3a678ff2996ef3d7c9f/runtime/js/10_permissions.js#L41-L49

Edit: the name should probably be `import` and not `imports`, to match https://docs.deno.com/api/deno/~/Deno.PermissionOptionsObject

**Comment by dsherret** [comment]
Removed "good first issue" because this relates to permissions.
