### ISSUE TITLE
Full deno test suite fails on Macos Sequoia 15.0.1

### ISSUE THREAD

**Issue by irbull** [denoland/deno#27073]
Version: Deno 2.1.1

The latest Deno fails to run the full test suite on MacOS Sequoia 15.0.1. It fails with some network issues:

```
[tls_test 006.75] ./tests/unit_node/tls_test.ts (uncaught error)
[tls_test 006.75] error: Error: connect ECONNREFUSED ::1:62980
[tls_test 006.75]     at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:116:11)
[tls_test 006.75]     at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:298:12)
[tls_test 006.75]     at TCPConnectWrap._afterConnect [as oncomplete] (node:net:394:16)
[tls_test 006.75]     at TCP.afterConnect (ext:deno_node/internal_binding/connection_wrap.ts:87:11)
[tls_test 006.75]     at TCP.handle.afterConnect (node:_tls_wrap:173:29)
[tls_test 006.75] This error was not caught from a test and caused the test runner to fail on the referenced module.
[tls_test 006.75] It most likely originated from a dangling promise, event/timeout handler or top-level code.
[tls_test 006.75] 
[tls_test 006.75]  FAILURES 
```

**Comment by irbull** [comment]
Turns out there are some known issues with MacOS 15.0.1 & Network interfaces. There are a few fixes / workarounds posted at [1]. The best solution seems to be to cycle the network interface. It has also been reported that upgrading to 15.1.1 fixes the issue. I can confirm that after updating, I haven't seen the issue again.

[1] https://discussions.apple.com/thread/255765230?answerId=255765230021&sortBy=rank#255765230021
