### ISSUE TITLE
[Internal Formatting Error] AssertionError when trying to log a request already upgraded by `Deno.upgradeWebSocket()`

### ISSUE THREAD

**Issue by Mqxx** [denoland/deno#27083]
```
deno 2.1.1 (stable, release, x86_64-pc-windows-msvc)
v8 13.0.245.12-rusty
typescript 5.6.2
```

Assertion Error when trying to log a request that got upgraded to a WebSocket connection.

Stack trace:
```
> deno run -A index.ts
Listening on http://localhost:8000/
error: Uncaught AssertionError: Assertion failed
  socket.addEventListener('open', () => console.log('New connection from:', request))
                                                ^
    at assert (ext:deno_console/01_console.js:198:11)
    at getKeys (ext:deno_console/01_console.js:1293:7)
    at formatRaw (ext:deno_console/01_console.js:760:14)
    at formatValue (ext:deno_console/01_console.js:544:10)
    at inspect (ext:deno_console/01_console.js:3469:10)
    at inspect (ext:deno_console/01_console.js:3469:10)
    at inspect (ext:deno_console/01_console.js:3469:10)
    at inspect (ext:deno_console/01_console.js:3469:10)
    at inspect (ext:deno_console/01_console.js:3469:10)
    at Request.[Deno.privateCustomInspect] (ext:deno_fetch/23_request.js:514:12)
    at formatValue (ext:deno_console/01_console.js:486:48)
    at inspectArgs (ext:deno_console/01_console.js:3071:17)
    at console.log (ext:deno_console/01_console.js:3140:7)
    at WebSocket.<anonymous> (file:///D:/Projects/fs-watcher-web-socket/index.ts:19:49)
```

Steps to reproduce:
1. Run this example code:
```ts
function wss(
  request : Request,
  handler : (socket : WebSocket) => void
) : Response {
  if (request.headers.get("upgrade") != "websocket") {
    return new Response(null, { status: 501 });
  }

  const { socket, response } = Deno.upgradeWebSocket(request);

  handler(socket);

  return response;
}



Deno.serve((request) => wss(request, (socket) => {
  socket.addEventListener('open', () => console.log('New connection from:', request))
}))
```
This by itself does not throw any errors and works fine.

2. Now connect to the WebSocket server using for example [hoppscotch.io](https://hoppscotch.io/realtime/websocket)
![image](https://github.com/user-attachments/assets/a72015c2-c2b5-400e-9389-6ee324911cf6)
This instantly crashes the WebSocket server with the above error.

This issue is similar to https://github.com/denoland/deno/issues/19471

**Comment by Mqxx** [comment]
This issue is similar to https://github.com/denoland/deno/issues/19471

**Comment by Mqxx** [comment]
This team is amazing!
