### ISSUE TITLE
Binary produced by deno compile does not support node native bindings (swc / rust)

### ISSUE THREAD

**Issue by Dmitri-Sintsov** [denoland/deno#27082]
Version: Deno 2.1.1

```
user@h67:~/.deno/bin$ ./deno --version
deno 2.1.1 (stable, release, x86_64-unknown-linux-gnu)
v8 13.0.245.12-rusty
typescript 5.6.2
```

Compiling deno binary with node.js swc (rust) bindings:

```
Starting /home/user/.deno/bin/deno compile --allow-env --allow-ffi --allow-import --allow-net --allow-read --allow-sys --allow-scripts=npm:@swc/core --frozen=false --vendor --output=/home/user/work/djk-sample310/lib/python3.10/site-packages/django_deno/deno/django_deno --lock=/home/user/work/djk-sample310/lib/python3.10/site-packages/django_deno/deno/deno.lock /home/user/work/djk-sample310/lib/python3.10/site-packages/django_deno/deno/server.ts
pid=508057
Download https://jsr.io/@deno/emit/meta.json
Download https://jsr.io/@oak/oak/17.1.3_meta.json
Download https://jsr.io/@std/path/1.0.8_meta.json
Download https://jsr.io/@std/fs/1.0.5_meta.json
Download https://jsr.io/@deno/emit/0.46.0_meta.json
Download https://jsr.io/@std/fmt/1.0.3_meta.json
Download https://jsr.io/@std/cli/1.0.6/_data.json
Download https://jsr.io/@deno/cache-dir/meta.json
Download https://jsr.io/@deno/cache-dir/0.13.2_meta.json
Download https://jsr.io/@std/assert/1.0.8_meta.json
Download https://jsr.io/@std/bytes/1.0.4_meta.json
Download https://jsr.io/@std/http/1.0.10_meta.json
Download https://jsr.io/@std/media-types/1.1.0_meta.json
Download https://jsr.io/@std/path/0.223.0_meta.json
Download https://jsr.io/@deno/graph/meta.json
Download https://jsr.io/@deno/graph/0.73.1_meta.json
Download https://jsr.io/@std/fmt/0.223.0_meta.json
Download https://jsr.io/@std/fs/0.223.0_meta.json
Download https://jsr.io/@std/io/0.223.0_meta.json
Download https://jsr.io/@std/assert/0.223.0_meta.json
Download https://jsr.io/@std/bytes/0.223.0_meta.json
Download https://jsr.io/@std/cli/1.0.6/mod.ts
Download https://jsr.io/@oak/oak/17.1.3/mod.ts
Download https://jsr.io/@std/path/1.0.8/mod.ts
Download https://jsr.io/@std/fs/1.0.5/mod.ts
Download https://jsr.io/@deno/emit/0.46.0/mod.ts
Download https://jsr.io/@std/fmt/1.0.3/colors.ts
Download https://jsr.io/@std/cli/1.0.6/prompt_secret.ts
Download https://jsr.io/@std/cli/1.0.6/unicode_width.ts
Download https://jsr.io/@oak/oak/17.1.3/application.ts
Download https://jsr.io/@oak/oak/17.1.3/body.ts
Download https://jsr.io/@oak/oak/17.1.3/context.ts
Download https://jsr.io/@oak/oak/17.1.3/http_server_native.ts
Download https://jsr.io/@oak/oak/17.1.3/http_server_native_request.ts
Download https://jsr.io/@oak/oak/17.1.3/middleware/etag.ts
Download https://jsr.io/@oak/oak/17.1.3/middleware/proxy.ts
Download https://jsr.io/@oak/oak/17.1.3/middleware/serve.ts
Download https://jsr.io/@oak/oak/17.1.3/middleware.ts
Download https://jsr.io/@oak/oak/17.1.3/request.ts
Download https://jsr.io/@oak/oak/17.1.3/response.ts
Download https://jsr.io/@oak/oak/17.1.3/router.ts
Download https://jsr.io/@oak/oak/17.1.3/send.ts
Download https://jsr.io/@oak/oak/17.1.3/testing.ts
Download https://jsr.io/@oak/oak/17.1.3/types.ts
Download https://jsr.io/@oak/oak/17.1.3/deps.ts
Download https://jsr.io/@std/path/1.0.8/basename.ts
Download https://jsr.io/@std/path/1.0.8/constants.ts
Download https://jsr.io/@std/path/1.0.8/dirname.ts
Download https://jsr.io/@std/path/1.0.8/extname.ts
Download https://jsr.io/@std/path/1.0.8/format.ts
Download https://jsr.io/@std/path/1.0.8/from_file_url.ts
Download https://jsr.io/@std/path/1.0.8/is_absolute.ts
Download https://jsr.io/@std/path/1.0.8/join.ts
Download https://jsr.io/@std/path/1.0.8/normalize.ts
Download https://jsr.io/@std/path/1.0.8/parse.ts
Download https://jsr.io/@std/path/1.0.8/relative.ts
Download https://jsr.io/@std/path/1.0.8/resolve.ts
Download https://jsr.io/@std/path/1.0.8/to_file_url.ts
Download https://jsr.io/@std/path/1.0.8/to_namespaced_path.ts
Download https://jsr.io/@std/path/1.0.8/common.ts
Download https://jsr.io/@std/path/1.0.8/types.ts
Download https://jsr.io/@std/path/1.0.8/glob_to_regexp.ts
Download https://jsr.io/@std/path/1.0.8/is_glob.ts
Download https://jsr.io/@std/path/1.0.8/join_globs.ts
Download https://jsr.io/@std/path/1.0.8/normalize_glob.ts
Download https://jsr.io/@std/fs/1.0.5/empty_dir.ts
Download https://jsr.io/@std/fs/1.0.5/ensure_dir.ts
Download https://jsr.io/@std/fs/1.0.5/ensure_file.ts
Download https://jsr.io/@std/fs/1.0.5/ensure_link.ts
Download https://jsr.io/@std/fs/1.0.5/ensure_symlink.ts
Download https://jsr.io/@std/fs/1.0.5/exists.ts
Download https://jsr.io/@std/fs/1.0.5/expand_glob.ts
Download https://jsr.io/@std/fs/1.0.5/move.ts
Download https://jsr.io/@std/fs/1.0.5/copy.ts
Download https://jsr.io/@std/fs/1.0.5/walk.ts
Download https://jsr.io/@std/fs/1.0.5/eol.ts
Download https://jsr.io/@deno/emit/0.46.0/emit.generated.js
Download https://jsr.io/@deno/emit/0.46.0/_utils.ts
Download https://jsr.io/@std/cli/1.0.6/_run_length.ts
Download https://jsr.io/@oak/oak/17.1.3/utils/clone_state.ts
Download https://jsr.io/@oak/oak/17.1.3/utils/create_promise_with_resolvers.ts
Download https://jsr.io/@oak/oak/17.1.3/utils/type_guards.ts
Download https://jsr.io/@oak/oak/17.1.3/utils/consts.ts
Download https://jsr.io/@oak/oak/17.1.3/utils/encode_url.ts
Download https://jsr.io/@oak/oak/17.1.3/utils/streams.ts
Download https://jsr.io/@oak/oak/17.1.3/utils/decode.ts
Download https://jsr.io/@oak/oak/17.1.3/utils/decode_component.ts
Download https://jsr.io/@oak/oak/17.1.3/utils/resolve_path.ts
Download https://jsr.io/@std/path/1.0.8/_os.ts
Download https://jsr.io/@std/path/1.0.8/posix/basename.ts
Download https://jsr.io/@std/path/1.0.8/windows/basename.ts
Download https://jsr.io/@std/path/1.0.8/posix/dirname.ts
Download https://jsr.io/@std/path/1.0.8/windows/dirname.ts
Download https://jsr.io/@std/path/1.0.8/posix/extname.ts
Download https://jsr.io/@std/path/1.0.8/windows/extname.ts
Download https://jsr.io/@std/path/1.0.8/posix/format.ts
Download https://jsr.io/@std/path/1.0.8/windows/format.ts
Download https://jsr.io/@std/path/1.0.8/posix/from_file_url.ts
Download https://jsr.io/@std/path/1.0.8/windows/from_file_url.ts
Download https://jsr.io/@std/path/1.0.8/posix/is_absolute.ts
Download https://jsr.io/@std/path/1.0.8/windows/is_absolute.ts
Download https://jsr.io/@std/path/1.0.8/posix/join.ts
Download https://jsr.io/@std/path/1.0.8/windows/join.ts
Download https://jsr.io/@std/path/1.0.8/posix/normalize.ts
Download https://jsr.io/@std/path/1.0.8/windows/normalize.ts
Download https://jsr.io/@std/path/1.0.8/posix/parse.ts
Download https://jsr.io/@std/path/1.0.8/windows/parse.ts
Download https://jsr.io/@std/path/1.0.8/posix/relative.ts
Download https://jsr.io/@std/path/1.0.8/windows/relative.ts
Download https://jsr.io/@std/path/1.0.8/posix/resolve.ts
Download https://jsr.io/@std/path/1.0.8/windows/resolve.ts
Download https://jsr.io/@std/path/1.0.8/posix/to_file_url.ts
Download https://jsr.io/@std/path/1.0.8/windows/to_file_url.ts
Download https://jsr.io/@std/path/1.0.8/posix/to_namespaced_path.ts
Download https://jsr.io/@std/path/1.0.8/windows/to_namespaced_path.ts
Download https://jsr.io/@std/path/1.0.8/_common/common.ts
Download https://jsr.io/@std/path/1.0.8/_common/glob_to_reg_exp.ts
Download https://jsr.io/@std/path/1.0.8/posix/glob_to_regexp.ts
Download https://jsr.io/@std/path/1.0.8/windows/glob_to_regexp.ts
Download https://jsr.io/@std/path/1.0.8/posix/join_globs.ts
Download https://jsr.io/@std/path/1.0.8/windows/join_globs.ts
Download https://jsr.io/@std/path/1.0.8/posix/normalize_glob.ts
Download https://jsr.io/@std/path/1.0.8/windows/normalize_glob.ts
Download https://jsr.io/@std/fs/1.0.5/_to_path_string.ts
Download https://jsr.io/@std/fs/1.0.5/_get_file_info_type.ts
Download https://jsr.io/@std/fs/1.0.5/_create_walk_entry.ts
Download https://jsr.io/@std/fs/1.0.5/_is_subdir.ts
Download https://jsr.io/@std/fs/1.0.5/_is_same_path.ts
Download https://jsr.io/@deno/emit/0.46.0/emit.generated.d.ts
Download https://jsr.io/@oak/oak/17.1.3/node_shims.ts
Download https://jsr.io/@std/path/1.0.8/_common/basename.ts
Download https://jsr.io/@std/path/1.0.8/_common/strip_trailing_separators.ts
Download https://jsr.io/@std/path/1.0.8/posix/_util.ts
Download https://jsr.io/@std/path/1.0.8/_common/constants.ts
Download https://jsr.io/@std/path/1.0.8/windows/_util.ts
Download https://jsr.io/@std/path/1.0.8/_common/dirname.ts
Download https://jsr.io/@std/path/1.0.8/_common/assert_path.ts
Download https://jsr.io/@std/path/1.0.8/_common/format.ts
Download https://jsr.io/@std/path/1.0.8/_common/from_file_url.ts
Download https://jsr.io/@std/path/1.0.8/_common/normalize.ts
Download https://jsr.io/@std/path/1.0.8/_common/normalize_string.ts
Download https://jsr.io/@std/path/1.0.8/_common/relative.ts
Download https://jsr.io/@std/path/1.0.8/_common/to_file_url.ts
Download https://jsr.io/@std/path/1.0.8/posix/constants.ts
Download https://jsr.io/@std/path/1.0.8/windows/constants.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/mod.ts
Download https://jsr.io/@std/assert/1.0.8/assert.ts
Download https://jsr.io/@std/bytes/1.0.4/concat.ts
Download https://jsr.io/@std/bytes/1.0.4/copy.ts
Download https://jsr.io/@std/http/1.0.10/etag.ts
Download https://jsr.io/@std/http/1.0.10/negotiation.ts
Download https://jsr.io/@std/http/1.0.10/user_agent.ts
Download https://jsr.io/@std/media-types/1.1.0/content_type.ts
Download https://jsr.io/@std/media-types/1.1.0/type_by_extension.ts
Download https://jsr.io/@std/path/0.223.0/mod.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/cache.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/deno_dir.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/file_fetcher.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/http_cache.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/disk_cache.ts
Download https://jsr.io/@std/assert/1.0.8/assertion_error.ts
Download https://jsr.io/@std/http/1.0.10/_negotiation/encoding.ts
Download https://jsr.io/@std/http/1.0.10/_negotiation/language.ts
Download https://jsr.io/@std/http/1.0.10/_negotiation/media_type.ts
Download https://jsr.io/@std/io/0.224.9/types.ts
Download https://jsr.io/@std/media-types/1.1.0/parse_media_type.ts
Download https://jsr.io/@std/media-types/1.1.0/get_charset.ts
Download https://jsr.io/@std/media-types/1.1.0/format_media_type.ts
Download https://jsr.io/@std/media-types/1.1.0/_db.ts
Download https://jsr.io/@std/path/0.223.0/windows/mod.ts
Download https://jsr.io/@std/path/0.223.0/posix/mod.ts
Download https://jsr.io/@std/path/0.223.0/basename.ts
Download https://jsr.io/@std/path/0.223.0/constants.ts
Download https://jsr.io/@std/path/0.223.0/dirname.ts
Download https://jsr.io/@std/path/0.223.0/extname.ts
Download https://jsr.io/@std/path/0.223.0/format.ts
Download https://jsr.io/@std/path/0.223.0/from_file_url.ts
Download https://jsr.io/@std/path/0.223.0/is_absolute.ts
Download https://jsr.io/@std/path/0.223.0/join.ts
Download https://jsr.io/@std/path/0.223.0/normalize.ts
Download https://jsr.io/@std/path/0.223.0/parse.ts
Download https://jsr.io/@std/path/0.223.0/relative.ts
Download https://jsr.io/@std/path/0.223.0/resolve.ts
Download https://jsr.io/@std/path/0.223.0/to_file_url.ts
Download https://jsr.io/@std/path/0.223.0/to_namespaced_path.ts
Download https://jsr.io/@std/path/0.223.0/common.ts
Download https://jsr.io/@std/path/0.223.0/_interface.ts
Download https://jsr.io/@std/path/0.223.0/glob_to_regexp.ts
Download https://jsr.io/@std/path/0.223.0/is_glob.ts
Download https://jsr.io/@std/path/0.223.0/join_globs.ts
Download https://jsr.io/@std/path/0.223.0/normalize_glob.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/dirs.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/util.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/auth_tokens.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/lib/deno_cache_dir.generated.js
Download https://jsr.io/@std/http/1.0.10/_negotiation/common.ts
Download https://jsr.io/@std/media-types/1.1.0/_util.ts
Download https://jsr.io/@std/media-types/1.1.0/vendor/db.ts
Download https://jsr.io/@std/path/0.223.0/windows/basename.ts
Download https://jsr.io/@std/path/0.223.0/windows/constants.ts
Download https://jsr.io/@std/path/0.223.0/windows/dirname.ts
Download https://jsr.io/@std/path/0.223.0/windows/extname.ts
Download https://jsr.io/@std/path/0.223.0/windows/format.ts
Download https://jsr.io/@std/path/0.223.0/windows/from_file_url.ts
Download https://jsr.io/@std/path/0.223.0/windows/is_absolute.ts
Download https://jsr.io/@std/path/0.223.0/windows/join.ts
Download https://jsr.io/@std/path/0.223.0/windows/normalize.ts
Download https://jsr.io/@std/path/0.223.0/windows/parse.ts
Download https://jsr.io/@std/path/0.223.0/windows/relative.ts
Download https://jsr.io/@std/path/0.223.0/windows/resolve.ts
Download https://jsr.io/@std/path/0.223.0/windows/to_file_url.ts
Download https://jsr.io/@std/path/0.223.0/windows/to_namespaced_path.ts
Download https://jsr.io/@std/path/0.223.0/windows/common.ts
Download https://jsr.io/@std/path/0.223.0/windows/glob_to_regexp.ts
Download https://jsr.io/@std/path/0.223.0/windows/is_glob.ts
Download https://jsr.io/@std/path/0.223.0/windows/join_globs.ts
Download https://jsr.io/@std/path/0.223.0/windows/normalize_glob.ts
Download https://jsr.io/@std/path/0.223.0/posix/basename.ts
Download https://jsr.io/@std/path/0.223.0/posix/constants.ts
Download https://jsr.io/@std/path/0.223.0/posix/dirname.ts
Download https://jsr.io/@std/path/0.223.0/posix/extname.ts
Download https://jsr.io/@std/path/0.223.0/posix/format.ts
Download https://jsr.io/@std/path/0.223.0/posix/from_file_url.ts
Download https://jsr.io/@std/path/0.223.0/posix/is_absolute.ts
Download https://jsr.io/@std/path/0.223.0/posix/join.ts
Download https://jsr.io/@std/path/0.223.0/posix/normalize.ts
Download https://jsr.io/@std/path/0.223.0/posix/parse.ts
Download https://jsr.io/@std/path/0.223.0/posix/relative.ts
Download https://jsr.io/@std/path/0.223.0/posix/resolve.ts
Download https://jsr.io/@std/path/0.223.0/posix/to_file_url.ts
Download https://jsr.io/@std/path/0.223.0/posix/to_namespaced_path.ts
Download https://jsr.io/@std/path/0.223.0/posix/common.ts
Download https://jsr.io/@std/path/0.223.0/posix/glob_to_regexp.ts
Download https://jsr.io/@std/path/0.223.0/posix/is_glob.ts
Download https://jsr.io/@std/path/0.223.0/posix/join_globs.ts
Download https://jsr.io/@std/path/0.223.0/posix/normalize_glob.ts
Download https://jsr.io/@std/path/0.223.0/_os.ts
Download https://jsr.io/@std/path/0.223.0/_common/common.ts
Download https://jsr.io/@std/path/0.223.0/_common/glob_to_reg_exp.ts
Download https://jsr.io/@deno/cache-dir/0.13.2/lib/snippets/deno_cache_dir-ba33e10a7a030c61/fs.js
Download https://jsr.io/@deno/cache-dir/0.13.2/lib/deno_cache_dir.generated.d.ts
Download https://jsr.io/@std/path/0.223.0/_common/basename.ts
Download https://jsr.io/@std/path/0.223.0/_common/constants.ts
Download https://jsr.io/@std/path/0.223.0/_common/strip_trailing_separators.ts
Download https://jsr.io/@std/path/0.223.0/windows/_util.ts
Download https://jsr.io/@std/path/0.223.0/_common/dirname.ts
Download https://jsr.io/@std/path/0.223.0/_common/assert_path.ts
Download https://jsr.io/@std/path/0.223.0/_common/format.ts
Download https://jsr.io/@std/path/0.223.0/_common/from_file_url.ts
Download https://jsr.io/@std/path/0.223.0/_common/normalize.ts
Download https://jsr.io/@std/path/0.223.0/_common/normalize_string.ts
Download https://jsr.io/@std/path/0.223.0/_common/relative.ts
Download https://jsr.io/@std/path/0.223.0/_common/to_file_url.ts
Download https://jsr.io/@std/path/0.223.0/posix/_util.ts
Download https://jsr.io/@deno/graph/0.73.1/mod.ts
Download https://jsr.io/@deno/graph/0.73.1/types.ts
Download https://jsr.io/@std/fmt/0.223.0/colors.ts
Download https://jsr.io/@std/fs/0.223.0/ensure_dir.ts
Download https://jsr.io/@std/io/0.223.0/mod.ts
Download https://jsr.io/@std/assert/0.223.0/assert.ts
Download https://jsr.io/@deno/graph/0.73.1/deno_graph_wasm.generated.js
Download https://jsr.io/@deno/graph/0.73.1/loader.ts
Download https://jsr.io/@deno/graph/0.73.1/media_type.ts
Download https://jsr.io/@std/fs/0.223.0/_get_file_info_type.ts
Download https://jsr.io/@std/io/0.223.0/buf_reader.ts
Download https://jsr.io/@std/io/0.223.0/buf_writer.ts
Download https://jsr.io/@std/io/0.223.0/buffer.ts
Download https://jsr.io/@std/io/0.223.0/copy.ts
Download https://jsr.io/@std/io/0.223.0/copy_n.ts
Download https://jsr.io/@std/io/0.223.0/iterate_reader.ts
Download https://jsr.io/@std/io/0.223.0/limited_reader.ts
Download https://jsr.io/@std/io/0.223.0/multi_reader.ts
Download https://jsr.io/@std/io/0.223.0/read_all.ts
Download https://jsr.io/@std/io/0.223.0/read_delim.ts
Download https://jsr.io/@std/io/0.223.0/read_int.ts
Download https://jsr.io/@std/io/0.223.0/read_lines.ts
Download https://jsr.io/@std/io/0.223.0/read_long.ts
Download https://jsr.io/@std/io/0.223.0/read_range.ts
Download https://jsr.io/@std/io/0.223.0/read_short.ts
Download https://jsr.io/@std/io/0.223.0/read_string_delim.ts
Download https://jsr.io/@std/io/0.223.0/reader_from_stream_reader.ts
Download https://jsr.io/@std/io/0.223.0/slice_long_to_bytes.ts
Download https://jsr.io/@std/io/0.223.0/string_reader.ts
Download https://jsr.io/@std/io/0.223.0/string_writer.ts
Download https://jsr.io/@std/io/0.223.0/to_readable_stream.ts
Download https://jsr.io/@std/io/0.223.0/to_writable_stream.ts
Download https://jsr.io/@std/io/0.223.0/types.ts
Download https://jsr.io/@std/io/0.223.0/write_all.ts
Download https://jsr.io/@std/assert/0.223.0/assertion_error.ts
Download https://jsr.io/@deno/graph/0.73.1/deno_graph_wasm.generated.d.ts
Download https://jsr.io/@std/io/0.223.0/_constants.ts
Download https://jsr.io/@std/io/0.223.0/_common.ts
Download https://jsr.io/@std/bytes/0.223.0/copy.ts
Download https://jsr.io/@std/bytes/0.223.0/concat.ts
Download https://jsr.io/@oak/oak/17.1.3/http_server_bun.ts
Download https://jsr.io/@oak/oak/17.1.3/http_server_node.ts
Initialize path-to-regexp@6.2.1
Initialize @wwa/rollup-plugin-terser@1.1.2
Initialize @rollup/plugin-sucrase@5.0.2
Initialize rollup@2.79.2
Initialize @rollup/plugin-swc@0.4.0
Initialize @rollup/plugin-node-resolve@15.3.0
Initialize @types/node@22.5.4
Initialize terser@5.36.0
Initialize @babel/code-frame@7.26.2
Initialize sucrase@3.35.0
Initialize @rollup/pluginutils@5.1.3
Initialize smob@1.5.0
Initialize @swc/core@1.9.3
Initialize @types/resolve@1.20.2
Initialize deepmerge@4.3.1
Initialize is-module@1.0.0
Initialize resolve@1.22.8
Initialize undici-types@6.19.8
Initialize commander@2.20.3
Initialize source-map-support@0.5.21
Initialize @jridgewell/source-map@0.3.6
Initialize acorn@8.14.0
Initialize js-tokens@4.0.0
Initialize picocolors@1.1.1
Initialize @babel/helper-validator-identifier@7.25.9
Initialize commander@4.1.1
Initialize glob@10.4.5
Initialize mz@2.7.0
Initialize pirates@4.0.6
Initialize ts-interface-checker@0.1.13
Initialize lines-and-columns@1.2.4
Initialize @jridgewell/gen-mapping@0.3.5
Initialize picomatch@4.0.2
Initialize @types/estree@1.0.6
Initialize estree-walker@2.0.2
Initialize @swc/types@0.1.17
Initialize @swc/counter@0.1.3
Initialize @swc/core-linux-x64-musl@1.9.3
Initialize @swc/core-linux-x64-gnu@1.9.3
Initialize path-parse@1.0.7
Initialize supports-preserve-symlinks-flag@1.0.0
Initialize is-core-module@2.15.1
Initialize buffer-from@1.1.2
Initialize source-map@0.6.1
Initialize @jridgewell/trace-mapping@0.3.25
Initialize minipass@7.1.2
Initialize package-json-from-dist@1.0.1
Initialize minimatch@9.0.5
Initialize path-scurry@1.11.1
Initialize foreground-child@3.3.0
Initialize jackspeak@3.4.3
Initialize object-assign@4.1.1
Initialize any-promise@1.3.0
Initialize thenify-all@1.6.0
Initialize @jridgewell/set-array@1.2.1
Initialize @jridgewell/sourcemap-codec@1.5.0
Initialize hasown@2.0.2
Initialize @jridgewell/resolve-uri@3.1.2
Initialize brace-expansion@2.0.1
Initialize lru-cache@10.4.3
Initialize cross-spawn@7.0.5
Initialize signal-exit@4.1.0
Initialize @pkgjs/parseargs@0.11.0
Initialize @isaacs/cliui@8.0.2
Initialize thenify@3.3.1
Initialize function-bind@1.1.2
Initialize balanced-match@1.0.2
Initialize which@2.0.2
Initialize path-key@3.1.1
Initialize shebang-command@2.0.0
Initialize strip-ansi@7.1.0
Initialize string-width@4.2.3
Initialize wrap-ansi@8.1.0
Initialize wrap-ansi@7.0.0
Initialize string-width@5.1.2
Initialize strip-ansi@6.0.1
Initialize isexe@2.0.0
Initialize shebang-regex@3.0.0
Initialize ansi-regex@6.1.0
Initialize emoji-regex@8.0.0
Initialize is-fullwidth-code-point@3.0.0
Initialize ansi-styles@6.2.1
Initialize ansi-styles@4.3.0
Initialize eastasianwidth@0.2.0
Initialize emoji-regex@9.2.2
Initialize ansi-regex@5.0.1
Initialize color-convert@2.0.1
Initialize color-name@1.1.4
Initialize @swc/core@1.9.3: running 'postinstall' script
Compile file:///home/user/work/djk-sample310/lib/python3.10/site-packages/django_deno/deno/server.ts to /home/user/work/djk-sample310/lib/python3.10/site-packages/django_deno/deno/django_deno
Download https://dl.deno.land/release/v2.1.1/denort-x86_64-unknown-linux-gnu.zip
Finished with return code = 0
```

Trying to run the produced binary:

```
Starting deno server /home/user/work/djk-sample310/lib/python3.10/site-packages/django_deno/deno/django_deno --host=127.0.0.1 --port=8099
pid=508286
Sending import maps to deno server pid=508286
error: Uncaught (in promise) Error: Failed to load native binding
    at Object.<anonymous> (file:///tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/binding.js:329:11)
    at Object.<anonymous> (file:///tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/binding.js:353:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:755:12)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:812:16)
    at Object.<anonymous> (file:///tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/index.js:49:17)
Caused by: [
  Error: Cannot find module './swc.linux-x64-gnu.node'
Require stack:
- /tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/binding.js
- /tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/index.js
- /tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/index.js
    at Function.Module._resolveFilename (node:module:619:15)
    at Function.Module._load (node:module:497:27)
    at Module.require (node:module:681:19)
    at require (node:module:812:16)
    at requireNative (file:///tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/binding.js:211:18)
    at Object.<anonymous> (file:///tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/binding.js:302:17)
    at Object.<anonymous> (file:///tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/binding.js:353:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:755:12) {
    code: "MODULE_NOT_FOUND",
    requireStack: [
      "/tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/binding.js",
      "/tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/index.js",
      "/tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/index.js"
    ]
  },
  TypeError: /tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core-linux-x64-gnu@1.9.3/node_modules/@swc/core-linux-x64-gnu/swc.linux-x64-gnu.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:module:801:20)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:812:16)
    at requireNative (file:///tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/binding.js:216:18)
    at Object.<anonymous> (file:///tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/binding.js:302:17)
    at Object.<anonymous> (file:///tmp/deno-compile-django_deno/deno/node_modules/.deno/@swc+core@1.9.3/node_modules/@swc/core/binding.js:353:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
]

```

When swc is included, the size of compiled binary increases from 100mb to 200mb, so it seems that swc node binaries are included but the binary runtime is unable to load these.

The version without swc (with sucrase) runs successfully.

**Comment by dsherret** [comment]
Duplicates https://github.com/denoland/deno/issues/23266
