### ISSUE TITLE
About WebSocket upgrade unavailable when run code original for Node.js

### ISSUE THREAD

**Issue by wildtang** [denoland/deno#27106]
Recently I wrote a program using Node.js v22 and TypeScript, Express, [PeerJS](https://peerjs.com/) a WebRTC server and client lib, which use **WebSocket** for signaling.
I used ts-node run this program for debug and files change watching/HMR, but ts-node is very slow, every launch will cost 8-10 seconds.

So I tried Deno v2.1.1 today, (command: deno run  --allow-all --watch  src/main.ts), Deno is very fast, every launch will cost only 1-2 seconds🚀. And without any code change, this program can be run directly use Deno! It is amazing!

Everything is fine, but WebSocket. Once a WebRTC signaling start between PeerJS server and client, the error below occurs on the server side(accept WebSocket connection, encapsulted in PeerJS server component).

```
Error: upgrade unavailable
    at InnerRequest._wantsUpgrade (ext:deno_http/00_serve.ts:105:26)
    at upgradeHttpRaw (ext:deno_http/00_serve.ts:51:18)
    at handler (node:http:1314:36)
    at ext:deno_http/00_serve.ts:382:26
    at ext:deno_http/00_serve.ts:593:29
    at eventLoopTick (ext:core/01_core.js:175:7)
Upgrade response was not returned from callback
```

It looks like need to do some special operations in WebSocket connection related code when program run by Deno. Beside modify PeerJS code, Is there any other method to resolve this problem, such as add a run time parameter or config. Thanks a lot.

**Comment by bartlomieju** [comment]
Hey @wildtang could you share your code for an easy reproduction of a problem? Looks like an internal bug in Deno

**Comment by wildtang** [comment]
@bartlomieju 

Hi, the server side code is below:

```TypeScript
import cors from "cors"
import "dotenv/config"
import express from "express"
import { Xid } from "xid-ts"
import { ExpressPeerServer } from "peer"
import process from "node:process"

const app = express()

app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: true }))

app.on("mount", () => {
  console.log(`${new Date().toLocaleString()} Web app> Signaling server launched, ready to accept clients connection.`)
})

const PORT = process.env.PORT || 5001
const peerClients = new Map()
const MSG_TYPE_NOC = 'Online-Devices'

app.get('/api/hello', (_req, res) => {
  res.status(200).json({
    message: `Hi, this is server. Give you an ID:${new Xid().toString()}`,
  })
})

const server = app.listen(PORT, () => {
  console.log(`${new Date().toLocaleString()} Web app  > Server is running on port: ${PORT}`)
})

const peerServer = ExpressPeerServer(server, {
  path: "/signaling",
})

peerServer.on("connection", (client) => {
  peerClients.set(client.getId(), { client, serial: '' })

  console.log(`${new Date().toLocaleString()} Signaling> Peer √ connected: ${client.getId()}`)
  const onlinePeers = {
    type: MSG_TYPE_NOC,
    serverTime: new Date().toLocaleString(),
    serverId: 'A1',
    yourDeviceIds: Array.from(peerClients.keys()),
  }
  peerClients.forEach((peer) => { peer.client.send(JSON.stringify(onlinePeers)) })
})

peerServer.on("message", (client, message) => {
  console.log(`${new Date().toLocaleString()} Signaling> Got a message ${message.type.toString()} from client ${client.getId()}`)
})


// :5001/chat/signaling/peerjs
app.use("/chat", peerServer)

```

**Comment by wildtang** [comment]
Client side code just new a PeerJS client object, then it will begin WebRTC signaling through WebSocket to server side( code pasted above).

```
new Peer(peerID, {
      host: 'chat.some.com',
      port: 443,
      path: '/chat/signaling',
      pingInterval: 7000,
      secure: secure,

      config: {
        iceServers: [
          { urls: 'stun:stun.l.google.com:19302' }, // Default
        ],
        sdpSemantics: 'unified-plan'
      }
    })

```

**Comment by bartlomieju** [comment]
Fixed in https://github.com/denoland/deno/pull/33208
