### ISSUE TITLE
Error aborting a child process' signal right when it exits

### ISSUE THREAD

**Issue by 0f-0b** [denoland/deno#27112]
```js
const controller = new AbortController();
Deno.addSignalListener("SIGCHLD", () => controller.abort());
await new Deno.Command("true", { signal: controller.signal }).output();
```

On a Mac running macOS 15.1, the `abort` call sometimes throws a `TypeError`.

```shellsession
$ deno run --allow-run=true a.js
$ deno run --allow-run=true a.js
error: Uncaught (in promise) TypeError: Child process has already terminated.
Deno.addSignalListener("SIGCHLD", () => controller.abort());
                                                   ^
    at ChildProcess.kill (ext:runtime/40_process.js:357:5)
    at onAbort (ext:runtime/40_process.js:299:32)
    at AbortSignal.[[[runAbortSteps]]] (ext:deno_web/03_abort_signal.js:182:9)
    at AbortSignal.[[[signalAbort]]] (ext:deno_web/03_abort_signal.js:166:24)
    at AbortController.abort (ext:deno_web/03_abort_signal.js:304:30)
    at …/a.js:2:52
    at loop (ext:runtime/40_signals.js:77:7)
    at eventLoopTick (ext:core/01_core.js:175:7)
$ deno --version
deno 2.1.1+1e51b65 (canary, release, aarch64-apple-darwin)
v8 13.0.245.12-rusty
typescript 5.6.2
```

I wasn't able to reproduce this issue in a single-core Linux VM.

**Comment by lucacasonato** [comment]
This behaviour occurs because while killing of child processes is an async operation, the triggering of the killing is a sync operation and the child may have died already from the `SIGCHLD` (or a natural exit) before you try to call `abort()`.

This is a bug in Deno. At the minimum we should ensure that the call to `childProcess.kill()` inside of the `onAbort` handling of `ChildProcess` has a `try {} catch {}` around it that swallows the error. Secondly we should also consider suppressing the error altogether from `childProcess.kill()` when the child is already dead.

**Comment by brasswood** [comment]
There is an issue (https://github.com/gildas-lormeau/single-file-cli/issues/145) in SingleFile CLI:

> I just had `single-file` hang, and when I terminated it, it printed this error:
> 
> ```
> error: Uncaught (in promise) TypeError: Child process has already terminated
>                 child.kill();
>                       ^
>     at ChildProcess.kill (ext:deno_process/40_process.js:371:13)
>     at closeBrowser (file:///home/andrew/single-file-cli/lib/browser.js:115:9)
>     at closeBrowserAndExit (file:///home/andrew/single-file-cli/single-file-launcher.js:137:8)
>     at loop (ext:deno_os/40_signals.js:77:7)
> ```

Correct me if I'm wrong, but I think this issue the cause.

> Secondly we should also consider suppressing the error altogether from childProcess.kill() when the child is already dead.

You could do that. Or if you don't, at least [document](https://docs.deno.com/api/deno/~/Deno.ChildProcess.prototype.kill) that `kill` throws an error if the process is already dead.
