### ISSUE TITLE
Mongodb Deno SRV connection not working.

### ISSUE THREAD

**Issue by vikashsharma** [denoland/deno#27138]
Version: Deno 2.0.* / canary

I am using windows and decided to switch from feathersjs to simple deno or hono+deno with mongoose/mongodb

Tried all possible options, changing deno versions or mongoose or mongdb. 
It works on my IP (sometimes) but rest it doesnt work from any other IP. 
Evfen my Atlas cloud Network is set to 0.0.0.0, 
Connect well with Hono+Bun or Bun, or Nodejs or featherjs.

After spending 3 days and tried all possible solutions, I gave up and switched to bun for now. My project is getting delayed. I had I hopes from deno. 

**URI** :  mongodb+srv://<user>:<password>@cluster.rhaiu.mongodb.net/testdb

Latest error is around : 

`MongoDB connection failed: MongooseServerSelectionError: Server selection timed out after 5000 ms at _handleConnectionErrors (c:\home\git\anvil-api\node_modules\mongoose\lib\connection.js:909:11) at NativeConnection.openUri (c:\home\git\anvil-api\node_modules\mongoose\lib\connection.js:860:11) at eventLoopTick (ext:core/01_core.js:214:9) at async connectDB (file:///C:/home/git/anvil-api/src/config/db.ts:76:5) at async startApp (file:///C:/home/git/anvil-api/main.ts:20:7) { message: "Server selection timed out after 5000 ms", reason: TopologyDescription { type: "ReplicaSetNoPrimary",`

**Comment by vikashsharma** [comment]
I did further testing and found problem comes and go, when on VPN mostly. this only happens with Hono + Deno . No issues express or Hono + Bun

**Comment by jamesej** [comment]
+1 to this, can't use Deno + Mongo in production right now.

**Comment by EvaMach** [comment]
+ 1, have been struggling with it since yesterday and tried everything. Works well in node.

**Comment by bartlomieju** [comment]
Deno 2.8 rewrote the `node:*` APIs (including `node:dns` and `node:net`/`node:tls`), so the SRV + A lookup path that `mongodb+srv://` relies on now uses the new implementation. Verified locally that `dns.resolveSrv` followed by `dns.lookup` works correctly on 2.8.

Closing as resolved. If anyone still hits this on 2.8+ with a deterministic repro (i.e. not intermittent / VPN-related), please open a new issue with the exact connection string format and we'll take another look.
