### ISSUE TITLE
WebSocket memory leaks

### ISSUE THREAD

**Issue by zxch3n** [denoland/deno#27156]
Version: Deno 2.1.2

https://github.com/denoland/deno/blob/8626ec7c25e25c628eed9fdd517c0ec20b01d0a6/ext/websocket/01_websocket.js#L431

This line will wait even if the connection is closed locally.

Running the following code may reproduce the issue unstablely.

```ts
Deno.test("ws leak", async () => {
  const ws = new WebSocket(`validTarget`);
  await new Promise((resolve, reject) => {
    ws.addEventListener("open", resolve);
  });
  ws.close();
});
```

Run `deno test` would return the following error sometimes:

```
error: Leaks detected:
  - "serverWebSocket" was created during the test, but not cleaned up during the test. Close the resource before the end of the test.
  - An async operation to receive the next message on a WebSocket was started in this test, but never completed. This is often caused by not closing a `WebSocket` or `WebSocketStream`. The operation was started here:
    at op_ws_next_event (ext:core/00_infra.js:250:13)
    at WebSocket.[[[eventLoop]]] (ext:deno_websocket/01_websocket.js:431:26)
    at eventLoopTick (ext:core/01_core.js:175:7)
```

**Comment by digitalbase** [comment]
Same issue on deno `2.1.4`

Replicating code:

The code:

```
import { Relay } from "@nostr/tools";
import { expect } from "jsr:@std/expect";

const relayUrl = 'wss://relay.nostr.band';

Deno.test('connectivity', async () => {
  const relay = await Relay.connect(relayUrl)
  console.log(`connected to ${relay.url}`)

  expect(relay.connected).toBeTruthy();

  relay.close()
})
```

So the relay connection is being closed in `relay.close()`. Tried waiting or catching errors on relay close but nothing there.

Error

```
error: Leaks detected:
  - "serverWebSocket" was created during the test, but not cleaned up during the test. Close the resource before the end of the test.
  - An async operation to receive the next message on a WebSocket was started in this test, but never completed. This is often caused by not closing a `WebSocket` or `WebSocketStream`. The operation was started here:
    at op_ws_next_event (ext:core/00_infra.js:250:13)
    at WebSocket.[[[eventLoop]]] (ext:deno_websocket/01_websocket.js:431:26)
    at WebSocket.PromisePrototypeThen.<computed> (ext:deno_websocket/01_websocket.js:247:27)
    at eventLoopTick (ext:core/01_core.js:175:7)
```

**Comment by rusmisel** [comment]
unable to repro in 2.4.0

**Comment by bartlomieju** [comment]
Not reproducible on canary `2.8.1`. I ran the reported pattern (connect, await `open`, then `close()`) heavily:

- Local echo server: 25/25 passed, no leaks
- Remote (`wss://echo.websocket.org`, matching the remote-target setup in the reports): 15/15 passed, no leaks

40 runs with zero `Leaks detected` failures, and since this was an intermittent flake that is strong evidence it is gone. Matches @rusmisel's "unable to repro in 2.4.0".

The close-during-open race is now handled in `ext/websocket/01_websocket.js`: when the open promise resolves it checks whether `close()` was already called, and if so it closes cleanly without ever starting the event loop:

```js
if (this[_readyState] === CLOSING) {
  // close() was called before open completed -> close cleanly, do NOT start the event loop
  PromisePrototypeThen(op_ws_close(this[_rid]), () => { ... });
} else {
  this[_readyState] = OPEN;
  this.dispatchEvent(new Event("open"));
  this[_eventLoop]();   // op_ws_next_event only started here
}
```

The leaking `op_ws_next_event` op the issue points at is only started in the non-`CLOSING` branch, so closing right after the handshake no longer leaves a dangling receive op or an unclosed `serverWebSocket`. Closing as resolved; please reopen with a repro if it still happens on a current release.
