### ISSUE TITLE
node_unit_tests::http2_test is very flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#27154]
```
---- node_unit_tests::http2_test stdout ----
command /Users/runner/work/deno/deno/target/debug/deno test --config /Users/runner/work/deno/deno/tests/config/deno.json --no-lock --unstable-broadcast-channel --unstable-net -A --cert=./tests/testdata/tls/RootCA.pem /Users/runner/work/deno/deno/tests/unit_node/http2_test.ts
command cwd /Users/runner/work/deno/deno
[http2_test 000.23] Download http://localhost:4260/@types%2fnode
[http2_test 000.26] Download http://localhost:4260/undici-types
[http2_test 000.26] Download http://localhost:4260/@types/node/node-22.5.4.tgz
[http2_test 000.31] Download http://localhost:4260/undici-types/undici-types-6.19.8.tgz
[http2_test 000.59] Check file:///Users/runner/work/deno/deno/tests/unit_node/http2_test.ts
[http2_test 005.82] running 11 tests from ./tests/unit_node/http2_test.ts
[http2_test 007.85] [node/http2 client] http://localhost:4246 ... ok (2s)
[http2_test 009.85] [node/http2 client] https://localhost:4247 ... ok (2s)
[http2_test 011.88] [node/http2 client createConnection] ... ok (2s)
[http2_test 012.06] [node/http2 client GET https://www.example.com]/ ... ok (188ms)
[http2_test 012.28] [node/http2.createServer()] ...
[http2_test 012.29] Uncaught error from ./tests/unit_node/http2_test.ts FAILED
[http2_test 012.29] [node/http2.createServer()] ... cancelled (0ms)
[http2_test 012.29] [node/http2 client] write image buffer on request stream works ... cancelled (0ms)
[http2_test 012.29] [node/http2 client] write 512kb buffer on request stream works ... cancelled (0ms)
[http2_test 012.29] [node/http2 client] deno doesn't panic on uppercase headers ... cancelled (0ms)
[http2_test 012.29] [node/http2 ClientHttp2Session.socket] ... cancelled (0ms)
[http2_test 012.29] [node/http2 client] connection states ... cancelled (0ms)
[http2_test 012.29] request and response exports ... cancelled (0ms)
[http2_test 012.31] 
[http2_test 012.31]  ERRORS 
[http2_test 012.31] 
[http2_test 012.31] ./tests/unit_node/http2_test.ts (uncaught error)
[http2_test 012.31] error: (in promise) Http: Http: connection error
[http2_test 012.31]     at ext:deno_http/00_serve.ts:859:15
[http2_test 012.31]     at eventLoopTick (ext:core/01_core.js:175:7)
[http2_test 012.31] This error was not caught from a test and caused the test runner to fail on the referenced module.
[http2_test 012.31] It most likely originated from a dangling promise, event/timeout handler or top-level code.
[http2_test 012.31] 
[http2_test 012.31]  FAILURES 
[http2_test 012.31] 
[http2_test 012.31] ./tests/unit_node/http2_test.ts (uncaught error)
[http2_test 012.31] 
[http2_test 012.31] FAILED | 4 passed | 8 failed (6s)
[http2_test 012.31] 
[http2_test 012.37] error: Test failed
thread 'node_unit_tests::http2_test' panicked at tests/integration/node_unit_tests.rs:192:3:
assertion `left == right` failed: Deno should have exited cleanly
  left: Some(0)
 right: Some(1)
stack backtrace:
   0:        0x10d1e7266 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hcaf66bc4c0c453df
   1:        0x10d20bccb - core::fmt::write::hc9c5f1836b413410
   2:        0x10d1e2fa2 - std::io::Write::write_fmt::h5ce5bc7686de8484
   3:        0x10d1e8aa8 - std::panicking::default_hook::{{closure}}::h52c0b2f44f6107c5
   4:        0x10d1e8628 - std::panicking::default_hook::h5a6cf31501c161b2
   5:        0x10b12306b - test::test_main::{{closure}}::h3d665f637d89df05
   6:        0x10d1e9810 - std::panicking::rust_panic_with_hook::hda4640ee332466e9
   7:        0x10d1e9095 - std::panicking::begin_panic_handler::{{closure}}::haa3060694b34ea3d
   8:        0x10d1e7749 - std::sys::backtrace::__rust_end_short_backtrace::h8eb44913cfe71457
   9:        0x10d1e8cdc - _rust_begin_unwind
  10:        0x10d23d8ea - core::panicking::panic_fmt::h31edc3d6ff0aadca
  11:        0x10d23de6b - core::panicking::assert_failed_inner::had7e28e3814f0dcd
  12:        0x10d2142a6 - core::panicking::assert_failed::hd963831ec1dee0a2
  13:        0x10b09afef - integration_tests::node_unit_tests::node_unit_test::hbd288a83c64c81f7
  14:        0x10b0a3d10 - integration_tests::node_unit_tests::http2_test::hce393a6f45d5abc7
  15:        0x10b0a3cc5 - integration_tests::node_unit_tests::http2_test::{{closure}}::h97b7d5eb0be9d000
  16:        0x10ad1ac38 - core::ops::function::FnOnce::call_once::hefbc45d22c6afc5f
  17:        0x10b12763b - test::__rust_begin_short_backtrace::h93e921f893a90bb1
  18:        0x10b126ea1 - test::run_test::{{closure}}::h42576c3f690468a6
  19:        0x10b0ebb4d - std::sys::backtrace::__rust_begin_short_backtrace::hb534ca9204c87c90
  20:        0x10b0ef352 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h95ab9f9938de870a
  21:        0x10d1eed8b - std::sys::pal::unix::thread::Thread::new::thread_start::h55ff15b5f[2276](https://github.com/denoland/deno/actions/runs/12087577936/job/33709309912?pr=27141#step:43:2277)bcd
  22:     0x7ff811f681d3 - __pthread_start


failures:
    node_unit_tests::http2_test
```

https://github.com/denoland/deno/actions/runs/12087577936/job/33709309912?pr=27141

**Comment by dsherret** [comment]
http test is also flaky:

```
---- node_unit_tests::http_test stdout ----
command /Users/runner/work/deno/deno/target/debug/deno test --config /Users/runner/work/deno/deno/tests/config/deno.json --no-lock --unstable-broadcast-channel --unstable-net -A --cert=./tests/testdata/tls/RootCA.pem /Users/runner/work/deno/deno/tests/unit_node/http_test.ts
command cwd /Users/runner/work/deno/deno
[http_test 000.20] Download http://localhost:4260/@types%2fnode
[http_test 000.28] Download http://localhost:4260/undici-types
[http_test 000.28] Download http://localhost:4260/@types/node/node-22.5.4.tgz
[http_test 000.28] Download http://localhost:4260/undici-types/undici-types-6.19.8.tgz
[http_test 000.33] Check file:///Users/runner/work/deno/deno/tests/unit_node/http_test.ts
[http_test 005.39] running 60 tests from ./tests/unit_node/http_test.ts
[http_test 005.41] [node/http listen] ... ok (11ms)
[http_test 005.41] [node/http close] ... ok (6ms)
error: test failed, to rerun pass `-p deno --test integration`
[http_test 005.44] [node/http] chunked response ... ok (22ms)
[http_test 005.44] [node/http] .writeHead() ...
[http_test 005.45]   send status code ... ok (4ms)
[http_test 005.45]   send status + custom status text + headers obj ... ok (3ms)
[http_test 005.46]   send status + headers obj ... ok (4ms)
[http_test 005.50]   send status + headers array ... ok (4ms)
[http_test 005.50] [node/http] .writeHead() ... ok (54ms)
[http_test 005.50] [node/http] empty chunk in the middle of response ... ok (3ms)
[http_test 005.76] [node/http] server can respond with 101, 204, 205, 304 status ... ok (254ms)
[http_test 005.77] [node/http] multiple set-cookie headers ... ok (10ms)
[http_test 005.90] [node/http] IncomingRequest socket has remoteAddress + remotePort ... ok (3ms)
[http_test 006.06] [node/http] request default protocol ... ok (96ms)
[http_test 006.08] [node/http] request with headers ... ok (6ms)
[http_test 006.15] [node/http] non-string buffer response ... ok (57ms)
[http_test 006.16] [node/http] send request with non-chunked body ...
[http_test 006.16] ------- output -------
[http_test 006.16] Listening on http://[::1]:4505/
[http_test 006.29] ----- output end -----
[http_test 006.29] [node/http] send request with non-chunked body ... ok (125ms)
[http_test 006.33] [node/http] send request with chunked body ...
[http_test 006.33] ------- output -------
[http_test 006.33] Listening on http://[::1]:4505/
[http_test 006.39] ----- output end -----
[http_test 006.39] [node/http] send request with chunked body ... ok (69ms)
[http_test 006.39] [node/http] send request with chunked body as default ...
[http_test 006.39] ------- output -------
[http_test 006.39] Listening on http://[::1]:4505/
[http_test 006.42] ----- output end -----
[http_test 006.42] [node/http] send request with chunked body as default ... ok (28ms)
[http_test 006.44] [node/http] ServerResponse _implicitHeader ... ok (7ms)
[http_test 006.47] [node/http] ServerResponse flushHeaders ... ok (4ms)
[http_test 006.97] [node/http] server unref ... ok (494ms)
[http_test 006.98] [node/http] ClientRequest handle non-string headers ... ok (4ms)
[http_test 006.99] [node/http] ClientRequest uses HTTP/1.1 ... ok (7ms)
[http_test 006.99] [node/http] ClientRequest setTimeout ... ok (3ms)
[http_test 007.00] [node/http] ClientRequest setNoDelay ... ok (3ms)
[http_test 007.00] [node/http] ClientRequest PATCH ... ok (3ms)
[http_test 007.00] [node/http] ClientRequest PUT ... ok (3ms)
[http_test 007.01] [node/http] ClientRequest search params ... ok (2ms)
[http_test 007.03] [node/http] HTTPS server ... ok (20ms)
[http_test 007.09] [node/http] client upgrade ... ok (64ms)
[http_test 007.09] [node/http] client end with callback ...
[http_test 007.09] ------- output -------
[http_test 007.09] Listening on http://0.0.0.0:5928/
[http_test 007.11] ----- output end -----
[http_test 007.11] [node/http] client end with callback ... ok (14ms)
[http_test 007.11] [node/http] server emits error if addr in use ... ok (2ms)
[http_test 007.11] [node/http] client destroy doesn't leak ...
[http_test 007.11] ------- output -------
[http_test 007.11] Listening on http://0.0.0.0:5929/
[http_test 007.49] ----- output end -----
[http_test 007.49] [node/http] client destroy doesn't leak ... ok (164ms)
[http_test 007.69] [node/http] client destroy before sending request should not error ... ok (0ms)
[http_test 007.69] [node/http] destroyed requests should not be sent ...
[http_test 007.69] ------- output -------
[http_test 007.69] Listening on http://0.0.0.0:8000/
[http_test 008.39] ----- output end -----
[http_test 008.39] [node/http] destroyed requests should not be sent ... ok (502ms)
[http_test 008.59] [node/http] node:http exports globalAgent ... ok (0ms)
[http_test 008.75] [node/https] node:https exports globalAgent ... ok (0ms)
[http_test 008.77] [node/http] node:http request.setHeader(header, null) doesn't throw ... ok (1ms)
[http_test 008.81] [node/http] ServerResponse getHeader ... ok (4ms)
[http_test 008.93] [node/http] ServerResponse appendHeader ... ok (4ms)
[http_test 009.02] [node/http] ServerResponse appendHeader set-cookie ... ok (4ms)
[http_test 009.23] [node/http] ServerResponse header names case insensitive ... ok (6ms)
[http_test 009.32] [node/http] IncomingMessage override ... ok (1ms)
[http_test 009.39] [node/http] ServerResponse assignSocket and detachSocket ... ok (0ms)
[http_test 009.42] [node/http] ServerResponse getHeaders ... ok (0ms)
[http_test 009.43] [node/http] ServerResponse default status code 200 ... ok (0ms)
[http_test 009.54] [node/http] maxHeaderSize is defined ... ok (0ms)
[http_test 009.54] [node/http] server graceful close ... ok (4ms)
[http_test 011.75] [node/http] server closeAllConnections shutdown ... ok (2s)
[http_test 013.93] [node/http] server closeIdleConnections shutdown ... ok (2s)
[http_test 013.98] [node/http] client closing a streaming response doesn't terminate server ...
[http_test 013.98] ------- output -------
[http_test 013.98] Client connected to server
[http_test 014.42] ----- output end -----
[http_test 014.42] [node/http] client closing a streaming response doesn't terminate server ... ok (274ms)
[http_test 014.59] [node/http] client closing a streaming request doesn't terminate server ... FAILED (150ms)
[http_test 014.99] [node/http] http.request() post streaming body works ... FAILED (366ms)
[http_test 015.08] [node/http] ServerResponse write transfer-encoding chunked ... ok (24ms)
[http_test 015.30] [node/http] Server.address() can be null ... ok (0ms)
[http_test 015.46] [node/http] ClientRequest PUT subarray ... ok (65ms)
[http_test 015.67] [node/http] req.url equals pathname + search ... ok (5ms)
[http_test 015.86] [node/http] ClientRequest content-disposition header works ... ok (22ms)
[http_test 016.08] [node/http] In ClientRequest, option.hostname has precedence over options.host ... ok (14ms)
[http_test 017.57] [node/http] upgraded socket closes when the server closed without closing handshake ...
[http_test 017.57] ------- output -------
[http_test 017.57] Listening on http://0.0.0.0:1337/
[http_test 020.32] upgrade on server
[http_test 020.33] server received ping
[http_test 020.33] process closed
[http_test 020.33] client socket closed
[http_test 020.46] ----- output end -----
[http_test 020.46] [node/http] upgraded socket closes when the server closed without closing handshake ... ok (4s)
[http_test 020.53] [node/http] ServerResponse.call() ... ok (0ms)
[http_test 020.73] [node/http] ServerResponse _header ... ok (3ms)
[http_test 020.74] [node/http] ServerResponse connection ...
[http_test 020.74] ------- output -------
[http_test 020.74] AssertionError
[http_test 020.74]     at assert (file:///Users/runner/work/deno/deno/tests/util/std/assert/assert.ts:21:11)
[http_test 020.74]     at ServerImpl.<anonymous> (file:///Users/runner/work/deno/deno/tests/unit_node/http_test.ts:1744:5)
[http_test 020.74]     at ServerImpl.emit (ext:deno_node/_events.mjs:393:28)
[http_test 020.74]     at node:http:1761:16
[http_test 020.74]     at new Promise (<anonymous>)
[http_test 020.74]     at handler (node:http:1759:16)
[http_test 020.74]     at mapped (ext:deno_http/00_serve.ts:541:24)
[http_test 020.74]     at mapped (ext:deno_http/00_serve.ts:639:16)
[http_test 020.74]     at ext:deno_http/00_serve.ts:864:29
[http_test 020.74]     at eventLoopTick (ext:core/01_core.js:175:7) ***
[http_test 020.74]   name: "AssertionError"
[http_test 020.74] ***
[http_test 020.90] ----- output end -----
[http_test 020.90] [node/http] ServerResponse connection ... ok (8ms)
[http_test 020.90] [node/http] ServerResponse socket ...
[http_test 020.90] ------- output -------
[http_test 020.90] AssertionError
[http_test 020.90]     at assert (file:///Users/runner/work/deno/deno/tests/util/std/assert/assert.ts:21:11)
[http_test 020.90]     at ServerImpl.<anonymous> (file:///Users/runner/work/deno/deno/tests/unit_node/http_test.ts:1765:5)
[http_test 020.90]     at ServerImpl.emit (ext:deno_node/_events.mjs:393:28)
[http_test 020.90]     at node:http:1761:16
[http_test 020.90]     at new Promise (<anonymous>)
[http_test 020.90]     at handler (node:http:1759:16)
[http_test 020.90]     at mapped (ext:deno_http/00_serve.ts:541:24)
[http_test 020.90]     at mapped (ext:deno_http/00_serve.ts:639:16)
[http_test 020.90]     at ext:deno_http/00_serve.ts:864:29
[http_test 020.90]     at eventLoopTick (ext:core/01_core.js:175:7) ***
[http_test 020.90]   name: "AssertionError"
[http_test 020.90] ***
[http_test 021.10] ----- output end -----
[http_test 021.10] [node/http] ServerResponse socket ... ok (4ms)
[http_test 021.40] 
[http_test 021.40]  ERRORS 
[http_test 021.40] 
[http_test 021.40] [node/http] client closing a streaming request doesn't terminate server => ./tests/unit_node/http_test.ts:1369:6
[http_test 021.40] error: AssertionError: Server should have received an error
[http_test 021.40]     throw new AssertionError(msg);
[http_test 021.40]           ^
[http_test 021.40]     at assert (file:///Users/runner/work/deno/deno/tests/util/std/assert/assert.ts:21:11)
[http_test 021.40]     at file:///Users/runner/work/deno/deno/tests/unit_node/http_test.ts:1433:3
[http_test 021.40] 
[http_test 021.40] [node/http] http.request() post streaming body works => ./tests/unit_node/http_test.ts:1449:6
[http_test 021.40] error: Leaks detected:
[http_test 021.40]   - "requestBody" was created before the test started, but was cleaned up during the test. Do not close resources in a test that were not created during that test.
[http_test 021.40] 
[http_test 021.40]  FAILURES 
[http_test 021.40] 
[http_test 021.40] [node/http] client closing a streaming request doesn't terminate server => ./tests/unit_node/http_test.ts:1369:6
[http_test 021.40] [node/http] http.request() post streaming body works => ./tests/unit_node/http_test.ts:1449:6
[http_test 021.40] 
[http_test 021.40] FAILED | 58 passed (4 steps) | 2 failed (16s)
[http_test 021.40] 
[http_test 021.63] error: Test failed
thread 'node_unit_tests::http_test' panicked at tests/integration/node_unit_tests.rs:192:3:
assertion `left == right` failed: Deno should have exited cleanly
  left: Some(0)
 right: Some(1)
stack backtrace:
   0:        0x105617466 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hcaf66bc4c0c453df
   1:        0x10563becb - core::fmt::write::hc9c5f1836b413410
   2:        0x1056131a2 - std::io::Write::write_fmt::h5ce5bc7686de8484
   3:        0x105618ca8 - std::panicking::default_hook::***closure***::h52c0b2f44f6107c5
   4:        0x105618828 - std::panicking::default_hook::h5a6cf31501c161b2
   5:        0x10354eeab - test::test_main::***closure***::h3d665f637d89df05
   6:        0x105619a10 - std::panicking::rust_panic_with_hook::hda4640ee33[2466](https://github.com/denoland/deno/actions/runs/12126795075/job/33809661611#step:43:2467)e9
   7:        0x105619295 - std::panicking::begin_panic_handler::***closure***::haa3060694b34ea3d
   8:        0x105617949 - std::sys::backtrace::__rust_end_short_backtrace::h8eb44913cfe71457
   9:        0x105618edc - _rust_begin_unwind
  10:        0x10566e6fa - core::panicking::panic_fmt::h31edc3d6ff0aadca
  11:        0x10566ec7b - core::panicking::assert_failed_inner::had7e28e3814f0dcd
  12:        0x1056448f6 - core::panicking::assert_failed::h8f8e753f72b62b38
  13:        0x10334e44f - integration_tests::node_unit_tests::node_unit_test::hc791a72a846ce78a
  14:        0x1033570f0 - integration_tests::node_unit_tests::http_test::h8e12d1c9b6993000
  15:        0x1033570a5 - integration_tests::node_unit_tests::http_test::***closure***::h14555e2755be6e3b
  16:        0x10313e4e8 - core::ops::function::FnOnce::call_once::h7c87eaab0d4a2ed4
  17:        0x10355347b - test::__rust_begin_short_backtrace::h93e921f893a90bb1
  18:        0x103552ce1 - test::run_test::***closure***::h42576c3f690468a6
  19:        0x10351798d - std::sys::backtrace::__rust_begin_short_backtrace::hb534ca9204c87c90
  20:        0x10351b192 - core::ops::function::FnOnce::call_once***vtable.shim***::h95ab9f9938de870a
  21:        0x10561ef8b - std::sys::pal::unix::thread::Thread::new::thread_start::h55ff15b5f2276bcd
  22:     0x7ff8065b31d3 - __pthread_start


failures:
    node_unit_tests::http_test
```

https://github.com/denoland/deno/actions/runs/12126795075/job/33809661611
