### ISSUE TITLE
require not defined error when cjs module in npm package has no file extension

### ISSUE THREAD

**Issue by rnbguy** [denoland/deno#27172]
Version: Deno 2.1.0

Last working version `2.0.6`.
```console
$ docker run --rm -it denoland/deno:alpine-2.0.6 run -A npm:@informalsystems/quint@0.22.4 --version
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:protobufjs@7.4.0
┃
┠─ This may cause the packages to not work correctly.
┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
┠─ Enable it in your deno config file:
┖─ "nodeModulesDir": "auto
0.22.4
```

But for `>=2.1.0`, I am getting error for commonjs.
```console
$ docker run --rm -it denoland/deno:alpine-2.1.0 run -A npm:@informalsystems/quint@0.22.4 --version
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:protobufjs@7.4.0
┃
┠─ This may cause the packages to not work correctly.
┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
┠─ Enable it in your deno config file:
┖─ "nodeModulesDir": "auto"
error: Uncaught (in promise) ReferenceError: require is not defined
    at file:///deno-dir/npm/registry.npmjs.org/yargs/17.7.2/yargs:3:69
    at loadESMFromCJS (node:module:761:21)
    at Module._compile (node:module:722:12)
    at Object.Module._extensions..js.Module._extensions..ts.Module._extensions..jsx.Module._extensions..tsx (node:module:754:10)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:797:16)
    at Object.<anonymous> (file:///deno-dir/npm/registry.npmjs.org/@informalsystems/quint/0.22.4/dist/src/cli.js:16:33)
    at Object.<anonymous> (file:///deno-dir/npm/registry.npmjs.org/@informalsystems/quint/0.22.4/dist/src/cli.js:356:4)

    info: Deno supports CommonJS modules in .cjs files, or when the closest
          package.json has a "type": "commonjs" option.
    hint: Rewrite this module to ESM,
          or change the file extension to .cjs,
          or add package.json next to the file with "type": "commonjs" option.
    docs: https://docs.deno.com/go/commonjs

$ docker run --rm -it denoland/deno:alpine-2.1.1 run -A npm:@informalsystems/quint@0.22.4 --version
< same error as before >
```

In `2.1.2`, I do get a suggestion for `--unstable-detect-cjs`.
```console
$ docker run --rm -it denoland/deno:alpine-2.1.2 run -A npm:@informalsystems/quint@0.22.4 --version
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:protobufjs@7.4.0
┃
┠─ This may cause the packages to not work correctly.
┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
┠─ Enable it in your deno config file:
┖─ "nodeModulesDir": "auto"
error: Uncaught (in promise) ReferenceError: require is not defined
    at file:///deno-dir/npm/registry.npmjs.org/yargs/17.7.2/yargs:3:69
    at loadESMFromCJS (node:module:777:21)
    at Module._compile (node:module:722:12)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:761:12)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:812:16)
    at Object.<anonymous> (file:///deno-dir/npm/registry.npmjs.org/@informalsystems/quint/0.22.4/dist/src/cli.js:16:33)

    info: Deno supports CommonJS modules in .cjs files, or when the closest
          package.json has a "type": "commonjs" option.
    hint: Rewrite this module to ESM,
          or change the file extension to .cjs,
          or add package.json next to the file with "type": "commonjs" option,
          or pass --unstable-detect-cjs flag to detect CommonJS when loading.
    docs: https://docs.deno.com/go/commonjs
 ```
 
 But it still doesn't work with `--unstable-detect-cjs` flag.
 
 ```console
$ docker run --rm -it denoland/deno:alpine-2.1.2 run --unstable-detect-cjs -A npm:@informalsystems/quint@0.22.4 --version
...
< still same error >
```

**Comment by rnbguy** [comment]
Looks like, the error is coming from `deno_core`.

https://github.com/denoland/deno_core/blob/cf34ee3076d714b659b5c4e08a42e24515739794/core/modules/map.rs#L1299

Maybe something with `v8__Module__Evaluate`?

**Comment by rnbguy** [comment]
I managed to make a small reproducible:

```ts
// demo.cjs
const _yargs = require("yargs/yargs");
```

with `package.json`:

```json
{ "dependencies": { "yargs": "^17.7.2" } }
```

```console
$ deno@2.1.2 run -A --node-modules-dir=auto --unstable-detect-cjs demo.cjs
error: Uncaught (in promise) ReferenceError: require is not defined
    at file:///home/foo/node_modules/.deno/yargs@17.7.2/node_modules/yargs/yargs:3:69
    at loadESMFromCJS (node:module:777:21)
    at Module._compile (node:module:722:12)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:761:12)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:812:16)
    at Object.<anonymous> (file:///home/foo/demo.cjs:2:16)

    info: Deno supports CommonJS modules in .cjs files, or when the closest
          package.json has a "type": "commonjs" option.
    hint: Rewrite this module to ESM,
          or change the file extension to .cjs,
          or add package.json next to the file with "type": "commonjs" option,
          or pass --unstable-detect-cjs flag to detect CommonJS when loading.
    docs: https://docs.deno.com/go/commonjs
```

The example with `express` from https://docs.deno.com/go/commonjs works fine with this.

**Comment by dsherret** [comment]
It seems this issue occurs because the file `yargs` in `yargs@17.7.2` has no file extension.

**Comment by rnbguy** [comment]
@dsherret I am happy to open an PR. but I need some direction where to look at to solve this.

**Comment by rnbguy** [comment]
@dsherret any guidance? 🥺

**Comment by dsherret** [comment]
> any guidance? 🥺

Search the codebase for the functions mentioned in the stack trace:

```
at file:///home/foo/node_modules/.deno/yargs@17.7.2/node_modules/yargs/yargs:3:69
    at loadESMFromCJS (node:module:777:21)
    at Module._compile (node:module:722:12)
    at loadMaybeCjs (node:module:770:10) <-- specifically, this one
```

I believe it's considering this file as esm because the type in the package.json is "type": "module". Maybe files without extensions are treated as cjs by node. I'm not sure.

**Comment by rnbguy** [comment]
Thanks. 🙏 This was helpful. I managed to run the above code successfully if I change the follow line

https://github.com/denoland/deno/blob/1b7719c5d62a9303c8687f6b07c44f39a0349ae9/ext/node/polyfills/01_require.js#L432

to

```ts
  return ".cjs";
```

**Comment by dsherret** [comment]
I'm not sure about making the change there because the the referrer impacts whether the module is considered cjs or esm and it would make any ESM modules without an extension not work when required.

I think probably we should probably make the change around here to prefer `ResolutionMode::Require` when `MediaType::from_path(&path) == MediaType::Unknown`: https://github.com/denoland/deno/blob/1b7719c5d62a9303c8687f6b07c44f39a0349ae9/resolvers/deno/cjs.rs#L280

That will cause it to take the slow path of attempting to load as CJS before loading as ESM if it's ESM.

**Comment by rnbguy** [comment]
I may have commented too early 😅 my previous message meant as a confirmation that I tracked the issue as per your suggestion.

I did trace it back exactly where you pointed. So, I guess, the refactor would be make `check_based_on_pkg_json` take `media_type` argument and do a condition here? But it is being used some other places, so I guess, I will make it optional.

This doesn't look like a pretty-fix. But if it's alright with you, I can open a PR.

**Comment by rnbguy** [comment]
Or, I can check this `path`

https://github.com/denoland/deno/blob/1b7719c5d62a9303c8687f6b07c44f39a0349ae9/resolvers/deno/cjs.rs#L270-L281

has an extension.

```rs
        Ok(if path.extension().is_some() && is_file_location_cjs {
          ResolutionMode::Require
        } else {
          ResolutionMode::Import
        })
```

**Comment by Xyndra** [comment]
I have the same problem with pg in vite, even after setting `--unstable-detect-cjs`
