### ISSUE TITLE
Surface not found modules as diagnostics instead of erroring and failing to load

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#27188]
In this example: https://github.com/denoland/deno/issues/27186

tsc:

```
node_modules/.deno/@mapbox+search-js-web@1.0.0-beta.24/node_modules/@mapbox/search-js-web/dist/index.d.ts:1:22 - error TS6053: File 'V:/scratch/node_modules/.deno/@mapbox+search-js-web@1.0.0-beta.24/node_modules/@mapbox/search-js-web/src/types/custom_elements.d.ts' not found.

1 /// <reference path="../src/types/custom_elements.d.ts" />
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.deno/@mapbox+search-js-web@1.0.0-beta.24/node_modules/@mapbox/search-js-web/dist/index.d.ts:2:22 - error TS6053: File 'V:/scratch/node_modules/.deno/@mapbox+search-js-web@1.0.0-beta.24/node_modules/@mapbox/search-js-web/src/types/typehead.d.ts' not found.

2 /// <reference path="../src/types/typehead.d.ts" />
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Us:

```
> deno check asdf.ts
Check file:///V:/scratch/asdf.ts
error: Uncaught Error: Unable to load V:\scratch\node_modules\.deno\@mapbox+search-js-web@1.0.0-beta.24\node_modules\@mapbox\search-js-web\src\types\custom_elements.d.ts: The system cannot find the path specified. (os error 3)
    at Object.getSourceFile (ext:deno_tsc/99_main_compiler.js:621:28)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126789:23)
    at findSourceFile (ext:deno_tsc/00_typescript.js:126705:20)
    at ext:deno_tsc/00_typescript.js:126654:22
    at getSourceFileFromReferenceWorker (ext:deno_tsc/00_typescript.js:126625:26)
    at processSourceFile (ext:deno_tsc/00_typescript.js:126652:5)
    at ext:deno_tsc/00_typescript.js:126946:7
    at forEach (ext:deno_tsc/00_typescript.js:2284:22)
    at processReferencedFiles (ext:deno_tsc/00_typescript.js:126945:5)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126848:9)
```

**Comment by invalidred** [comment]
This issue still happens after I updated to deno 2.1.8

```
error: Error: Unable to load /Users/abdulkhan/github/asi/main/app/node_modules/.deno/@mapbox+search-js-web@1.0.0-beta.25/node_modules/@mapbox/search-js-web/src/types/custom_elements.d.ts: No such file or directory (os error 2)
    at Object.getSourceFile (ext:deno_tsc/97_ts_host.js:461:26)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126789:23)
    at findSourceFile (ext:deno_tsc/00_typescript.js:126705:20)
    at ext:deno_tsc/00_typescript.js:126654:22
    at getSourceFileFromReferenceWorker (ext:deno_tsc/00_typescript.js:126625:26)
    at processSourceFile (ext:deno_tsc/00_typescript.js:126652:5)
    at ext:deno_tsc/00_typescript.js:126946:7
    at forEach (ext:deno_tsc/00_typescript.js:2284:22)
    at processReferencedFiles (ext:deno_tsc/00_typescript.js:126945:5)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126848:9)
```

**Comment by dsherret** [comment]
Waiting on https://github.com/denoland/deno/pull/27548

**Comment by invalidred** [comment]
Gotcha tysm @dsherret !

**Comment by dsherret** [comment]
Reopening. Not fixed for the original scenario: https://github.com/denoland/deno/pull/28174#issuecomment-2689404293
