### ISSUE TITLE
Deno fetch gives TLS related "reset by peer" error, on a site with what appears to be strong security

### ISSUE THREAD

**Issue by RickCogley** [denoland/deno#27212]
Using `fetch` in Lume v2.4.2 (Deno Typescript static site generator app) on Deno 2.1.2, I get this error when fetching to our ops db REST API: 

> fetch TypeError: "client error connection reset by peer"

I see a lot of people have had this same or a similar problem, in various GH issues, and it appears that it is because of the underlying Rust [library](https://github.com/ctz/rustls) being used, is extra strict about TLS connections. For example: 

https://github.com/denoland/deno/issues/6427
https://github.com/denoland/deno/issues/6197
https://github.com/denoland/deno/issues/7528

When I test the connection using `curl -v` you can see the result below, and this well-known assessment site   https://www.ssllabs.com/ssltest/analyze.html?d=pro.dbflex.net returns an A rating, yet, Deno (well, the underlying library) rejects the connection. 

As a workaround, I used a different service to pull the json I am interested in, and represent it as an URL that does not require any auth / bearer tokens etc.

I am confused by this, because although TLS 1.2 is getting old, it seems like the A rating from SSLLabs should be good enough? 
Are there any workarounds on the code side, like using a different or 3rd party fetch library? 

![JRC CleanShot Microsoft Edge 2024-12-03-201735JST@2x](https://github.com/user-attachments/assets/d17ba811-dfbc-4867-ae8f-60e2ea75a3de)

```sh
❯ curl -v https://pro.dbflex.net/secure
* Host pro.dbflex.net:443 was resolved.
* IPv6: (none)
* IPv4: 208.100.33.100
*   Trying 208.100.33.100:443...
* Connected to pro.dbflex.net (208.100.33.100) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA384 / [blank] / UNDEF
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=dbflex.net
*  start date: Feb 15 00:00:00 2024 GMT
*  expire date: Mar 17 23:59:59 2025 GMT
*  subjectAltName: host "pro.dbflex.net" matched cert's "*.dbflex.net"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* using HTTP/1.x
> GET /secure HTTP/1.1
> Host: pro.dbflex.net
> User-Agent: curl/8.7.1
> Accept: */*
```

**Comment by bartlomieju** [comment]
@RickCogley you should be able to get around this error with `--unsafely-ignore-certificate-errors`. Do you have some special setup or should `await fetch("https://pro.dbflex.net/secure")` reproduce this error?

**Comment by RickCogley** [comment]
thank you for responding @bartlomieju! The app <https://pro.dbflex.net/secure> is running on IIS on iirc Windows Server 2019 which supports only TLS 1.2 and an older cipher suite. The PaaS provider responded to my support request that they will eventually upgrade all their servers to Windows Server 2024 (etc) so that TLS 1.3 and the latest cipher suite can be enabled, but it will take time (understandable, they have a lot of servers and users). Because of that background, I don't think it's a special usage, or related to my code, and it should be reproducible that way. 

Basically, <https://pro.dbflex.net/secure> is cloud database app, which requires a login, so I was accessing its REST api using a bearer token within my fetch function when I kept getting the error. I wrote about it, and how I resolved it with curl in a site pre-build script, here:
https://gist.github.com/RickCogley/58ac2531e473b7ae15791e68ab1031f5

It would feel cleaner to be able to fetch it, though, so I would like to try your flag. I assume that goes on `deno run`? 

```json
...
"tasks": {
    "lume": "echo \"import 'lume/cli.ts'\" | deno run --env-file -A -",
    "build": "deno task lume",
    "serve": "deno task lume -s",
    "format": "echo '=== Regular deno fmt... ===' && deno fmt --ignore=_dist && echo '=== Deno fmt for vento... ===' && deno fmt --unstable-component --ignore=_dist"
  }, 
...
```

**Comment by RickCogley** [comment]
I had a moment, so I setup a fetch command specifying a bearer token, and ran deno with `--unsafely-ignore-certificate-errors` like so in my `deno.json`: 

```json
{
  "imports": {
    "lume/": "https://deno.land/x/lume@v2.4.2/"
  },
  "tasks": {
    "lume": "echo \"import 'lume/cli.ts'\" | deno run --unsafely-ignore-certificate-errors --env-file -A -",
    "build": "deno task lume",
    "serve": "deno task lume -s",
    "format": "echo '=== Regular deno fmt... ===' && deno fmt --ignore=_dist && echo '=== Deno fmt for vento... ===' && deno fmt --unstable-component --ignore=_dist"
  },
  "compilerOptions": {
    "types": [
      "lume/types.ts"
    ]
  },
  "fmt": {
    "exclude": [
      "_site",
      "src/assets"
    ]
  }
}
``` 

This is how I called fetch:

```typescript
// Fetch holidays with bearer token
const response2 = await fetch("https://pro.dbflex.net/secure/api/v2/15331/Work%20Holiday/API%20Holidays%20Today%20or%20Later/select.json", {
  method: "GET",
  mode: "no-cors",
  headers: {
    "Accept": "application/json",
    "Authorization": "Bearer " + Deno.env.get("API_KEY_01"),
  },
});
const holidays2 = await response2.json();
export { holidays2 };
```

I get a warning about the risk, so I think the flag worked, and I know the `API_KEY_01` token is present in the environment, but when I run Lume, there's no difference from before. It still won't work giving "connection reset by peer": 

```bash
❯ lume serve
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run --unsafely-ignore-certificate-errors --env-file -A - "-s"
DANGER: TLS certificate validation is disabled for all hostnames
Loading config file file:///Users/rcogley/dev/rickcogley/_config.ts
...
error: Uncaught (in worker "") (in promise) TypeError: error sending request for url (https://pro.dbflex.net/secure/api/v2/15331/Work%20Holiday/API%20Holidays%20Today%20or%20Later/select.json): client error (Connect): Connection reset by peer (os error 54)
const response2 = await fetch("https://pro.dbflex.net/secure/api/v2/15331/Work%20Holiday/API%20Holidays%20Today%20or%20Later/select.json", {
                  ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:190:12)
    at async fetch (ext:deno_fetch/26_fetch.js:454:11)
    at async file:///Users/rcogley/dev/rickcogley/src/_data.ts:47:19
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
user=1.16s system=0.97s cpu=20% total=10.609
```

**Comment by RickCogley** [comment]
Hi @beshubh , the workaround I'm doing is to pull the json from a webhook service that deno accepts the TLS of. The web service's fetch has no problem with the TLS on my db. It's not ideal ... 

`database with API <- webhook service fetch() <- deno fetch()`

**Comment by beshubh** [comment]
Thanks for the response @RickCogley 

I think you are taking proxy approach, which might not work for me because of the scale.

**Comment by RickCogley** [comment]
True. I tried some other fetch libraries as well, but in the end they're an abstraction on deno fetch() anyway, and fail in the same way.

**Comment by beshubh** [comment]
@bartlomieju 
even with `--unsafely-ignore-certificate-errors` flag it does not work.
Anything being done for addressing this issue? our migration to deno is halted because of it.

**Comment by RickCogley** [comment]
Recently last week it still didn't work so I coded a cloudflare worker to proxy it. I really want this to just work directly though.

**Comment by RickCogley** [comment]
The PaaS db I was trying to use finally got upgraded to TLS 1.3, so now I can use deno natively without proxying via some edge function.

**Comment by bartlomieju** [comment]
Thanks for the detailed report, and especially for circling back to confirm the resolution.

This turned out to be a **cipher suite negotiation failure**, not a certificate issue. The `curl -v` output shows the connection was negotiated as:

```
TLSv1.2 / ECDHE-RSA-AES256-SHA384
```

`ECDHE-RSA-AES256-SHA384` is a **CBC-mode** cipher suite (`TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384`). Deno's TLS stack is [rustls](https://github.com/rustls/rustls), which by design does not implement any CBC cipher suites, only AEAD ones (AES-GCM and ChaCha20-Poly1305). CBC-in-TLS has a long history of vulnerabilities (BEAST, Lucky13, padding oracles), so rustls refuses to ship those suites.

If the server only offered CBC suites for TLS 1.2, then Deno's ClientHello and the server's supported ciphers had no overlap, the server aborted the handshake, and that surfaced as `Connection reset by peer (os error 54)`.

This also explains why `--unsafely-ignore-certificate-errors` made no difference: that flag only bypasses certificate validation, which happens *after* a cipher suite is agreed. The handshake here failed before any certificate was evaluated, so the flag was never reached.

As you found, once the PaaS provider upgraded the server to TLS 1.3 it started working natively, since TLS 1.3's cipher suites are all AEAD and fully supported by rustls. That confirms the diagnosis.

There isn't a fix we can make on Deno's side: re-enabling CBC suites would mean overriding rustls's security posture, and those suites aren't exposed to us anyway. The right fixes are server-side (enable a GCM/ChaCha20 suite or TLS 1.3), which is what ultimately resolved this. For anyone hitting the same wall before they can change the server, proxying through a tool with a more permissive TLS stack (curl/OpenSSL) is the practical workaround.

Closing as working as designed. Thanks again!
