### ISSUE TITLE
"TypeError: expected typed ArrayBufferView\n    at readableStreamWriteChunkFn (ext:deno_web/06_streams.js:785:15)\n    at Object.chunkSteps (ext:deno_web/06_streams.js:827:9)\n    at readableStreamFulfillReadRequest (ext:deno_web/06_streams.js:2584:17)\n    at readableStreamDefaultControllerEnqueue (ext:deno_web/06_streams.js:1755:5)\n    at ReadableStreamDefaultController.enqueue (ext:deno_web/06_streams.js:6026:5)\n    at Object.enqueue (file:///Users/NNRocaGoAr/Desktop/Sylcat/build/server.js:462:16)\n    at Va (file:///Users/NNRocaGoAr/Desktop/Sylcat/build/server.js:835:9)\n    at async yn (file:///Users/NNRocaGoAr/Desktop/Sylcat/build/server.js:942:7)\n    at async di (file:///Users/NNRocaGoAr/Desktop/Sylcat/build/server.js:931:5)\n    at async Va (file:///Users/NNRocaGoAr/Desktop/Sylcat/build/server.js:879:9)"

### ISSUE THREAD

**Issue by aralroca** [denoland/deno#27223]
Version: Deno x.x.x

**Comment by aralroca** [comment]
Adding `new TextEncoder().encode(chunk)` works, however, it should work without coding, just like Node or Bun.

**Comment by BlackAsLight** [comment]
Can you show an example of it working with node:https? I imagine the problem is that Response is expecting a ReadableStream<Uint8Array> and you're giving it a ReadableStream<string>.

**Comment by irbull** [comment]
I see the problem. Response is defined to take (among other things) a `ReadableStream<Uint8Array>`, and you gave it a `ReadableStream<any>`. This isn't actually checked anywhere until the chunk is passed through FFI to Rust [1]. Technically we could detect that the chunk is not a `Uint8Array` and encode it (I just tried this), but I'm not sure we should break from the spec. As @BlackAsLight mentioned, can you show the example using `node:http(s)`? I'd like to see how the type defs differ.

[1] https://github.com/denoland/deno/blob/main/ext/web/06_streams.js#L789

**Comment by irbull** [comment]
However, there does seem to be an issue. I think that `deno check` should have caught the type error.

**Comment by aralroca** [comment]
> Can you show an example of it working with `node:https`? I imagine the problem is that `Response` is expecting a `ReadableStream<Uint8Array>` and you're giving it a `ReadableStream<string>`.

It is good to know that it is by type, however in [Brisa Framework](https://github.com/brisa-build/brisa) we try to be JS runtime agnostic so we have the same compilation process (TS -> JS) where we make modifications of the AST, but we are not keeping the types... 😅 So far we supported bun and node, and we want to support deno. Currently, in the latest canary, Deno is working with `node:https`, so I wanted to change it to `Deno.serve`.

To reproduce it with `node:https`:

```ts

import https from "node:https";
import type http from "node:http";

const server = https.createServer(handler).listen(3000);

async function handler(
  req: http.IncomingMessage,
  res: http.ServerResponse,
) {
  const stream = new ReadableStream({
    start(controller) {
      controller.enqueue("Hello");
      controller.close();
    }
  });
  const response = new Response(stream, { headers: { "Content-Type": "text/html" } })

  await setResponse(res, response!);
}
```

<details>
<summary>

And this is the rest of the code

</summary>

```ts
/*
  Credits to the SvelteKit team
	https://github.com/sveltejs/kit/blob/8d1ba04825a540324bc003e85f36559a594aadc2/packages/kit/src/exports/node/index.js
*/
function get_raw_body(req: http.IncomingMessage) {
  const h = req.headers;

  if (!h['content-type']) {
    return null;
  }

  const content_length = Number(h['content-length']);

  // check if no request body
  if (
    (req.httpVersionMajor === 1 &&
      isNaN(content_length) &&
      h['transfer-encoding'] == null) ||
    content_length === 0
  ) {
    return null;
  }

  if (req.destroyed) {
    const readable = new ReadableStream();
    readable.cancel();
    return readable;
  }

  let cancelled = false;

  return new ReadableStream({
    start(controller) {
      req.on('error', (error) => {
        cancelled = true;
        controller.error(error);
      });

      req.on('end', () => {
        if (cancelled) return;
        controller.close();
      });

      req.on('data', (chunk) => {
        if (cancelled) return;

        controller.enqueue(chunk);

        if (controller.desiredSize === null || controller.desiredSize <= 0) {
          req.pause();
        }
      });
    },

    pull() {
      req.resume();
    },

    cancel(reason) {
      cancelled = true;
      req.destroy(reason);
    },
  });
}

export async function getRequest({
  request,
  base,
}: { request: http.IncomingMessage; base: string }) {
  return new Request(base + request.url, {
    duplex: 'half',
    method: request.method,
    // @ts-ignore
    headers: request.headers,
    body: get_raw_body(request),
  });
}

export async function setResponse(
  res: http.ServerResponse,
  response: Response,
) {
  for (const [key, value] of response.headers) {
    try {
      res.setHeader(
        key,
        key === 'set-cookie' ? splitCookiesString(value) : value,
      );
    } catch (error) {
      console.log({ error });
      res.getHeaderNames().forEach((name) => res.removeHeader(name));
      res.writeHead(500).end(String(error));
      return;
    }
  }

  res.writeHead(response.status);

  if (!response.body) {
    res.end();
    return;
  }

  if (response.body.locked) {
    res.write(
      'Fatal error: Response body is locked. ' +
        `This can happen when the response was already read (for example through 'response.json()' or 'response.text()').`,
    );
    res.end();
    return;
  }

  const reader = response.body.getReader();

  if (res.destroyed) {
    reader.cancel();
    return;
  }

  const cancel = (error?: Error) => {
    res.off('close', cancel);
    res.off('error', cancel);

    // If the reader has already been interrupted with an error earlier,
    // then it will appear here, it is useless, but it needs to be catch.
    reader.cancel(error).catch(() => {});
    if (error) res.destroy(error);
  };

  res.on('close', cancel);
  res.on('error', cancel);

  next();
  async function next() {
    try {
      for (;;) {
        const { done, value } = await reader.read();

        if (done) break;

        if (!res.write(value)) {
          res.once('drain', next);
          return;
        }
      }
      res.end();
    } catch (error) {
      cancel(error instanceof Error ? error : new Error(String(error)));
    }
  }
}

/*
  Credits to set-cookie-parser:
	https://github.com/nfriedly/set-cookie-parser/blob/dd61d424894f284b5e3cedebae51fbd5b6ad3fed/lib/set-cookie.js#L148
*/
export function splitCookiesString(
  cookiesString: string | string[],
): string[] {
  if (Array.isArray(cookiesString)) return cookiesString;
  if (typeof cookiesString !== 'string') return [];

  const cookiesStrings = [];
  let pos = 0;
  let start;
  let ch;
  let lastComma;
  let nextStart;
  let cookiesSeparatorFound;

  function skipWhitespace() {
    while (
      pos < cookiesString.length &&
      /\s/.test((cookiesString as string).charAt(pos))
    ) {
      pos += 1;
    }
    return pos < cookiesString.length;
  }

  function notSpecialChar() {
    ch = (cookiesString as string).charAt(pos);

    return ch !== '=' && ch !== ';' && ch !== ',';
  }

  while (pos < cookiesString.length) {
    start = pos;
    cookiesSeparatorFound = false;

    while (skipWhitespace()) {
      ch = cookiesString.charAt(pos);
      if (ch === ',') {
        // ',' is a cookie separator if we have later first '=', not ';' or ','
        lastComma = pos;
        pos += 1;

        skipWhitespace();
        nextStart = pos;

        while (pos < cookiesString.length && notSpecialChar()) {
          pos += 1;
        }

        // currently special character
        if (pos < cookiesString.length && cookiesString.charAt(pos) === '=') {
          // we found cookies separator
          cookiesSeparatorFound = true;
          // pos is inside the next cookie, so back up and return it.
          pos = nextStart;
          cookiesStrings.push(cookiesString.substring(start, lastComma));
          start = pos;
        } else {
          // in param ',' or param separator ';',
          // we continue from that comma
          pos = lastComma + 1;
        }
      } else {
        pos += 1;
      }
    }

    if (!cookiesSeparatorFound || pos >= cookiesString.length) {
      cookiesStrings.push(cookiesString.substring(start, cookiesString.length));
    }
  }

  return cookiesStrings;
}
```

</details>

**Comment by BlackAsLight** [comment]
Doing a bit of testing in the browser's console, `Response` does seem to accept a `ReadableStream<any>` but will throw an error if you try and use any of the properties on `Response` if it requires making use of `Uint8Array`s. Aka, `.blob()`, `.bytes()`, `.text()`, `.json()`.

The only property on `Response` that didn't throw an error was when pulling it out as another `ReadableStream` (`await Array.fromAsync(response.body)`).

On a different note, a simple fix to your problem is to pipe the stream through `TextEncoderStream` to easily convert it to a `ReadableStream<Uint8Array>`. I wouldn't agree in saying the current behaviour is at all a bug.

```ts
const stream = new ReadableStream({
  start(controller) {
    controller.enqueue("<!DOCTYPE html>");
    controller.close();
  }
});


Deno.serve({ handler: (req) => {
  return new Response(stream.pipeThrough(new TextEncoderStream()), { headers: { "Content-Type": "text/html" } });
}, port: 3000 })
```

**Comment by aralroca** [comment]
@BlackAsLight It worked. Thanks because as you say it was a bug we had on our side and finding this Deno bug has been worth it to fix one of ours.

**Comment by bartlomieju** [comment]
Refocusing this. The behavior has changed substantially since the original 2.1.2 report, tested on canary `2.8.1`:

**The catastrophic part is fixed.** The original symptom (`Terminating Deno.serve loop due to unexpected error` tearing down the entire server) no longer happens. With a handler returning `new Response(stream)` where `stream` enqueues a string, the server stays up across repeated requests and keeps serving.

**Residual bug (what this issue now tracks):** a non-`Uint8Array` chunk makes the individual response send `HTTP 200` headers and then **hang the connection indefinitely** — the body never completes or closes, and the `expected typed ArrayBufferView` error is **silently swallowed** (nothing on stderr). Repro:

```ts
Deno.serve({
  handler: () => {
    const stream = new ReadableStream({
      start(controller) {
        controller.enqueue("<!DOCTYPE html>"); // string, not Uint8Array
        controller.close();
      },
    });
    return new Response(stream, { headers: { "Content-Type": "text/html" } });
  },
  port: 3000,
});
```

`curl localhost:3000` receives `HTTP 200`, 0 bytes, then hangs until the client times out. The server should instead reset/close the connection (or fail the response) and surface the error, rather than send 200 and hang silently.

**Not in scope / not fixable here:**
- `deno check` catching this: `new ReadableStream({...})` infers `ReadableStream<any>` (the lib type parameter defaults to `any`), which is assignable to `ReadableStream<Uint8Array>`, so TS cannot flag it without diverging from the standard lib types.
- The user-facing fix remains `stream.pipeThrough(new TextEncoderStream())`, as noted in the thread.

cc @nathanwhit
