### ISSUE TITLE
"parallel/test-dgram-connect-send-empty-packet.js" is flaky

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#27247]
```
Node.js compatibility ... Node.js compatibility "parallel/test-dgram-connect-send-empty-packet.js" => ./tests/node_compat/test.ts:72:11
error: AssertionError: Failed assertion: "parallel/test-dgram-connect-send-empty-packet.js" failed:

error: Uncaught Error: Not running
    at healthCheck (node:dgram:1294:11)
    at Socket.send (node:dgram:967:5)
    at Timeout._onTimeout (file:///Users/runner/work/deno/deno/tests/node_compat/test/parallel/test-dgram-connect-send-empty-packet.js:22:14)
    at cb (ext:deno_node/internal/timers.mjs:64:31)
    at callback (ext:deno_web/02_timers.js:87:7)
    at eventLoopTick (ext:core/01_core.js:210:13)
```

Looks like this test was added in https://github.com/denoland/deno/pull/27134

CC @kt3k

**Comment by kt3k** [comment]
I'd suggest we should remove it for now #27249
