### ISSUE TITLE
More BrotliDecompress error info

### ISSUE THREAD

**Issue by shevernitskiy** [denoland/deno#27251]
I getting some BrotliDecompress error on several YT clients. It fails somewhere inside deno nodejs compat files.

```ts
import { Innertube } from "npm:youtubei.js";
const yt = await Innertube.create();
```

Error:
```sh
error: Uncaught TypeError: Failed to decompress
    at BrotliDecompress.transform [as _transform] (ext:deno_node/_brotli.js:69:23)
    at BrotliDecompress.Transform._write (ext:deno_node/_stream.mjs:4563:12)
    at writeOrBuffer (ext:deno_node/_stream.mjs:3520:16)
    at _write (ext:deno_node/_stream.mjs:3465:14)
    at BrotliDecompress.Writable.write (ext:deno_node/_stream.mjs:3468:14)
    at Readable.ondata (ext:deno_node/_stream.mjs:2744:26)
    at Readable.emit (ext:deno_node/_events.mjs:393:28)
    at Readable.read (ext:deno_node/_stream.mjs:2597:14)
    at flow (ext:deno_node/_stream.mjs:2933:38)
    at resume_ (ext:deno_node/_stream.mjs:2915:7)
```

deno:  2.1.3

**Comment by sigmachirality** [comment]
Seems like https://github.com/denoland/deno/issues/26086 could be related.

**Comment by bartlomieju** [comment]
This works correctly in Deno v2.6.10.
