### ISSUE TITLE
Next 15 Error with Turbopack (Nextjs starter example)

### ISSUE THREAD

**Issue by VestaCord** [denoland/deno#27275]
Version: Deno 2.1.3 (Tried on multiple 2.X.X versions)
`deno -A npm:create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"` runs ok

`deno install --allow-scripts` returns 

Similar to closed issue #26742

```error: Uncaught Error: spawnSync node-gyp ENOENT
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_errnoException (ext:deno_node/internal/errors.ts:141:10)
    at _createSpawnSyncError (ext:deno_node/internal/child_process.ts:685:17)
    at new ChildProcess (ext:deno_node/internal/child_process.ts:287:13)
    at Object.spawn (node:child_process:120:10)
    at build (file:///home/vestatian/Desktop/Deployments/nextjs-dashboard/node_modules/.deno/node-gyp-build@4.8.4/node_modules/node-gyp-build/bin.js:32:8)
    at preinstall (file:///home/vestatian/Desktop/Deployments/nextjs-dashboard/node_modules/.deno/node-gyp-build@4.8.error: failed to run scripts for packages: bufferutil@4.0.8```

Then ok after I run `deno install --allow-scripts`  again.

Issue comes with when I run `deno run dev`, I get this compilation error:
```
Error: An unexpected Turbopack error occurred. Please see the output of `next dev` for more details.
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Next.js
getServerError
node_modules/.deno/next@15.0.4/node_modules/next/src/client/components/react-dev-overlay/internal/helpers/node-stack-frames.ts (31:36)
getServerError
node_modules/.deno/next@15.0.4/node_modules/next/src/client/index.tsx (930:17)
```

Even more strangely, this error disappears if I delete the line `import '@/app/ui/global.css';` from root layout (`@/app/layout.tsx`). This is code written by Vercel and works when running with Node + pnpm rather than Deno.

**Comment by doveq** [comment]
I'm also getting this error and need to install pnpm install @tailwindcss/postcss

**Comment by dmint789** [comment]
I'm on Deno 2.1.7, and this still doesn't work. Next JS version: 15.1.6 (with React 19).

**Comment by stevefan1999-personal** [comment]
My best guess is that Turbopack was, well, not installed at all with `deno install` and then it became a ENOENT, since it cannot spawn the turbopack process (or load the library into node)

**Comment by mintydev789** [comment]
I believe Turbopack works as of Deno 2.3.3. At least it works for me.

**Comment by dante-sparras** [comment]
Im getting the same error using Deno 2.3.5

**Comment by bartlomieju** [comment]
I'm unable to reproduce this on a current Deno build (tested 2.8.1). Both reported problems appear fixed.

**1. `deno install --allow-scripts` (`spawnSync node-gyp ENOENT` for bufferutil)** — succeeded on the first attempt; no node-gyp ENOENT. The original report needed a second run to get past this.

**2. `deno run dev` with `import '@/app/ui/global.css'` in the root layout (Turbopack)** — I added that exact import back into `app/layout.tsx` and:
- **next@16.2.7** (what `latest` resolves to today): `GET / 200`, the CSS chunk compiles and is served with real Tailwind output, the stylesheet `<link>` is present, and there's no `getServerError` / `node-stack-frames` overlay.
- **next@15.0.4 pinned** (the exact version from the report): same result — `Compiled / in 1526ms`, `GET / 200`, CSS chunk linked and served, no error.

This matches the later comments in the thread ("works as of 2.3.3 / 2.3.5"). Closing as resolved.

If anyone still hits this on a recent Deno (2.x), please reopen with the Deno version, OS, and `deno install` output — I tested on macOS arm64, and the install-scripts/node-gyp path can differ on Linux.
