### ISSUE TITLE
Proposal: import attribute to resolve remote import map

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#27280]
## As-Is
https://raw.githubusercontent.com/dsherret/dax/refs/heads/main/deno.json has following imports:
```
  "imports": {
    "@deno/dnt": "jsr:@deno/dnt@~0.41.3",
    "@david/path": "jsr:@david/path@0.2",
    "@std/assert": "jsr:@std/assert@1",
    "@std/fmt": "jsr:@std/fmt@1",
    "@std/fs": "jsr:@std/fs@1",
    "@std/io": "jsr:@std/io@0.221",
    "@std/path": "jsr:@std/path@1",
    "@std/streams": "jsr:@std/streams@0.221",
    "which": "jsr:@david/which@~0.4.1",
    "which_runtime": "jsr:@david/which-runtime@0.2"
  }
```
thus it fails to "import $ from "https://raw.githubusercontent.com/dsherret/dax/refs/heads/main/mod.ts" because Deno has no way of knowing what imports these are:

```
Uncaught TypeError: Relative import path "@david/path" not prefixed with / or ./ or ../
    at https://raw.githubusercontent.com/dsherret/dax/refs/heads/main/mod.ts:41:22
    at https://raw.githubusercontent.com/dsherret/dax/refs/heads/main/mod.ts:41:22
    at async <anonymous>:1:47
```

## To-Be

```ts
import $ from "https://raw.githubusercontent.com/dsherret/dax/refs/heads/main/mod.ts" with { "import-map": "./deno.json" }
```

allow adding [import attribute](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import/with) to resolve path of import map (or deno.json's `import` field) in given remote file.

## Benefits

- No longer bound to JSR
- libraries can use import maps and work

**Comment by dsherret** [comment]
This would be very non-standard and require import map composition. It would need to be something done outside Deno, so going to close this one.

By the way, I think you might be interested in the experimental `patch` feature? We haven't had time to fix it up and stabilize or document it: https://github.com/denoland/deno/pull/25068

**Comment by bartlomieju** [comment]
Actually it looks like the spec added merging of import maps: https://html.spec.whatwg.org/multipage/webappapis.html#merge-existing-and-new-import-maps

Mentioned in https://github.com/denoland/deno/issues/25450#issuecomment-2511732799.

**Comment by scarf005** [comment]
@dsherret as import map merging is in web standard, could this issue be at least re-opened to continue discussion of how to handle this situation better?

**Comment by dsherret** [comment]
Something else that needs to be noted is even if deno allowed specifying multiple import maps, the file at https://raw.githubusercontent.com/dsherret/dax/refs/heads/main/deno.json would not work as the import map for that code. Deno.json files extend the import map spec by allowing jsr and npm specifiers (it adds additional artificial entries to allow joining to mapped nom and jsr specifiers). Probably what you are looking for is the patch feature as I previously mentioned. Probably it could be improved to use git repos in the future.

**Comment by oscarotero** [comment]
I like to suggest a new `importMaps` entry in deno.json (or repurpose the existing `importMap` to allow an array), so you can link import maps of other dependencies. For example:

```js
{
  "importMaps": [
    "https://deno.land/x/lume@2.5.1/deno.json"
  ]
}
```

Now, the Lume's import map is merged with the main import map, adding entries like "lume/", and other dependencies (markdown-it, std, etc).
