### ISSUE TITLE
parallel/test-dgram-send-empty-packet.js is flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#27316]
```
 ERRORS 

Node.js compatibility ... Node.js compatibility "parallel/test-dgram-send-empty-packet.js" => ./tests/node_compat/test.ts:65:11
error: AssertionError: Failed assertion: "parallel/test-dgram-send-empty-packet.js" failed:

error: Uncaught Error: Not running
    at healthCheck (node:dgram:1294:11)
    at Socket.send (node:dgram:967:5)
    at Timeout._onTimeout (file:///Users/runner/work/deno/deno/tests/node_compat/test/parallel/test-dgram-send-empty-packet.js:24:12)
    at cb (ext:deno_node/internal/timers.mjs:64:31)
    at callback (ext:deno_web/02_timers.js:87:7)
    at eventLoopTick (ext:core/01_core.js:210:13)
```

https://github.com/denoland/deno/actions/runs/12258680855/job/34199028916

**Comment by dsherret** [comment]
Still flaky https://github.com/denoland/deno/actions/runs/12549930638/job/34991830452
