### ISSUE TITLE
"Component auth has not been registered yet" starting from firebase/app@0.10.17 (Deno CDN)

### ISSUE THREAD

**Issue by svscorp** [denoland/deno#27352]
On December 7th, my deployments to Deno were successful, and same code deploying from December 8th is failing:

![image](https://github.com/user-attachments/assets/85b6023a-be4f-4180-b32c-00274aedc0c6)

```
Error: Component auth has not been registered yet
    at c.initialize (https://esm.sh/v135/@firebase/component@0.6.11/denonext/component.mjs:2:2558)
    at ti (https://esm.sh/v135/@firebase/auth@1.8.1/denonext/auth.mjs:2:60691)
    at za (https://esm.sh/v135/@firebase/auth@1.8.1/denonext/auth.mjs:2:123594)
    at file:///src/src/utils/firestore.ts:42:14
```

The firestore.ts line is: `const auth = getAuth(app);`

I'm using Firestore according to the guideline/tutorial available on Deno:
``` 
import "https://deno.land/x/xhr@0.1.1/mod.ts";
import { installGlobals } from "https://deno.land/x/virtualstorage@0.1.0/mod.ts";
installGlobals();

import { initializeApp } from "https://esm.sh/@firebase/app";

import {  getFirestore, doc, collection,  query, where, updateDoc, getDocs,getDoc, addDoc, orderBy, Firestore, Query, DocumentData, WhereFilterOp } from "https://esm.sh/@firebase/firestore";

import { getAuth, signInWithEmailAndPassword, Auth } from "https://esm.sh/@firebase/auth";

// ... firebaseConfig

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);

// ... rest of the code
```

**Comment by lucacasonato** [comment]
Is this on Deno Deploy?

**Comment by svscorp** [comment]
@lucacasonato yes it is. I deploy with `deno run --env -A https://deno.land/x/deploy@1.10.0/deployctl.ts deploy`

**Comment by svscorp** [comment]
I checked the build logs. From December 8, it started to show:
```
https://esm.sh/v135/@firebase/app@0.10.17/denonext/app.mjs
Downloaded
```

in addition to the
```
https://esm.sh/v135/@firebase/app@0.10.16/denonext/app.mjs
Downloaded
```

**Comment by fredkzk** [comment]
@lucacasonato Thanks for the fix! Can the documentation be updated then?

**Comment by svscorp** [comment]
It's not yet fixed, @fredkzk. I tagged Lucas to show the finding, for now it's a rollback to the older versio.

**Comment by svscorp** [comment]
Alright, so now, I can see that `firebase/app@0.10.18` was introduced, and together with this, the `firebase/auth@1.8.2` was released.

So `firebase/app@0.10.18` works only with `firebase/auth@1.8.2`, if you had `firebase/app@0.10.16` locked with `firebase/auth@` < `1.8.2`, you need to update and lock both to the latest version.
