### ISSUE TITLE
Unable to use NPM packages like `debug` and `chai` due to `ERR_TYPES_NOT_FOUND`

### ISSUE THREAD

**Issue by silverbucket** [denoland/deno#27365]
Version: Deno 2.1.4

Unable to use NPM packages like `debug` and `chai` due to `ERR_TYPES_NOT_FOUND`

```bash
$ deno run test
Task test deno test --coverage --clean --allow-env src/**/*.test.ts
error: Failed resolving types. [ERR_TYPES_NOT_FOUND] Could not find types for 'file:///Users/njenning/code/projects/sockethub-deno/node_modules/.deno/debug@4.4.0/node_modules/debug/index.js' imported from 'file:///Users/njenning/code/projects/sockethub-deno/packages/schemas/src/validator.ts'
    at file:///Users/njenning/code/projects/sockethub-deno/packages/schemas/src/validator.ts:2:19

$ cat deno.json
{
  "name": "@sockethub/schemas",
  "description": "JSON schema files for validating Sockethub Activity Streams",
  "version": "3.0.0-alpha.5",
  "exports": "./src/index.ts",
  "license": "MIT",
  "tasks": {
    "build": "deno run --allow-read --allow-write scripts/export-json-schema.ts",
    "coverage": "deno coverage | deno run jsr:@silverbucket/threshold 100 88",
    "test": "deno test --coverage --clean --allow-env src/**/*.test.ts"
  },
  "imports": {
    "@silverbucket/threshold": "jsr:@silverbucket/threshold@1.0.2",
    "@types/node": "npm:@types/node@22.5.0",
    "@types/debug": "npm:@types/debug@4.1.12",
    "ajv": "npm:ajv@8.12.0",
    "ajv-formats": "npm:ajv-formats@2.1.1",
    "@silverbucket/ajv-formats-draft2019": "jsr:@silverbucket/ajv-formats-draft2019@1.6.1",
    "debug": "npm:debug@^4.4.0"
  }
}
```

```bash
$ deno run test
Task test deno test --coverage --clean --allow-env --allow-read src/**/*.test.ts
error: Failed resolving types. [ERR_TYPES_NOT_FOUND] Could not find types for 'file:///Users/njenning/code/projects/sockethub-deno/node_modules/.deno/chai@4.3.10/node_modules/chai/index.js' imported from 'file:///Users/njenning/code/projects/sockethub-deno/packages/activity-streams/src/activity-streams.test.ts'
    at file:///Users/njenning/code/projects/sockethub-deno/packages/activity-streams/src/activity-streams.test.ts:12:23

$ cat deno.json
{
  "name": "@sockethub/activity-streams",
  "version": "4.4.0-alpha.5",
  "description": "A simple tool to facilitate handling and referencing activity streams without unnecessary verbosity",
  "license": "MIT",
  "exports": "./src/activity-streams.ts",
  "tasks": {
    "clean": "rm -rf npm coverage",
    "build": "deno run -A ./build.ts .",
    "coverage": "deno coverage | deno run jsr:@silverbucket/threshold 90 95",
    "test": "deno test --coverage --clean --allow-env --allow-read src/**/*.test.ts"
  },
  "imports": {
    "@types/chai": "npm:@types/chai@^4.3.19",
    "chai": "npm:chai@^4.3.10",
    "eventemitter3": "npm:eventemitter3@^5.0.1",
    "mocha": "npm:mocha@^10.7.3"
  }
}
```

**Comment by silverbucket** [comment]
Any update on this?

**Comment by dsherret** [comment]
It might be fixed as of the latest release.

**Comment by bartlomieju** [comment]
This appears to be fixed on main. Both `debug` and `chai` npm packages now resolve types correctly — `deno check` passes without `ERR_TYPES_NOT_FOUND` errors.
