### ISSUE TITLE
dynamic import with absolute path broken after deno compile

### ISSUE THREAD

**Issue by hw104** [denoland/deno#27371]
Version: Deno 2.1.4

dynamic import with absolute path broken after deno compile. But it will work at least in version 1.40.2.

## Reproduce

/Users/me/main.ts:
```ts
// main.ts
const { shouldBeImported } = await import("/Users/me/a.ts");
console.log(shouldBeImported("world"));
```

/Users/me/a.ts:
```ts
// a.ts
export const shouldBeImported = (name: string) => `hello, ${name}!`;
```

works file before compile:
```shell
~ $ deno main.ts
hello, world!
```

I got `SyntaxError` after compile:
```
~ $ deno compile --output main main.ts
Compile file:///Users/wadahironori/main.ts to main
~ $ ./main
error: Uncaught (in promise) SyntaxError: Unexpected token ':' at file:///Users/me/a.ts:2:38
    at async file:///var/folders/v0/wwm6gnhx2p107jtdmn473nxh0000gn/T/deno-compile-main/me/main.ts:2:30
```

**Comment by dsherret** [comment]
Can you try in `deno upgrade --canary`? It's probably fixed there.

**Comment by hw104** [comment]
@dsherret 

Upgraded with `deno upgrade --canary`, but the issue persists:

```console
root@1d3d432c5450:~# cat *.ts
// a.ts
export const shouldBeImported = (name: string) => `hello, ${name}!`;
// main.ts
const { shouldBeImported } = await import("/tmp/deno-test/a.ts");
console.log(shouldBeImported("world"));
root@1d3d432c5450:~# deno --version
deno 2.1.4+c562742 (canary, release, aarch64-unknown-linux-gnu)
v8 13.0.245.12-rusty
typescript 5.6.2
root@1d3d432c5450:~# deno compile --output main main.ts
Check file:///root/main.ts
Compile file:///root/main.ts to main

Embedded Files

main
└── main.ts (571B)

Size: 571B

root@1d3d432c5450:~# ./main
error: Uncaught (in promise) TypeError: Module not found: file:///tmp/deno-test/a.ts
    at async file:///tmp/deno-compile-main/main.ts:2:30
root@1d3d432c5450:~#
```

**Comment by hw104** [comment]
@dsherret

Upgraded with deno upgrade --canary, but the issue persists:

```console
root@1d3d432c5450:~# deno --version
deno 2.1.4+c562742 (canary, release, aarch64-unknown-linux-gnu)
v8 13.0.245.12-rusty
typescript 5.6.2
root@1d3d432c5450:~# cat *.ts
// a.ts
export const shouldBeImported = (name: string) => `hello, ${name}!`;
// main.ts
const { shouldBeImported } = await import("/root/a.ts");
console.log(shouldBeImported("world"));
root@1d3d432c5450:~# deno main.ts
hello, world!
root@1d3d432c5450:~# deno compile --output main main.ts
Check file:///root/main.ts
Compile file:///root/main.ts to main

Embedded Files

main
├── a.ts (449B)
└── main.ts (550B)

Size: 999B

root@1d3d432c5450:~# ./main
error: Uncaught (in promise) SyntaxError: Unexpected token ':' at file:///root/a.ts:2:38
    at async file:///tmp/deno-compile-main/main.ts:2:30
root@1d3d432c5450:~#
```

**Comment by dsherret** [comment]
Thanks, I understand now. If you're expecting Deno to actually read the file at `/root/a.ts`, then this is https://github.com/denoland/deno/issues/18327 (but also, you should be importing with a file url instead--`file:///root/a.ts`)

If you're expecting to actually read the path from the binary, then this is now by design. Deno previously was embedding absolute paths in the binary, which was bad because it was exposing user's paths and also it lead to non-deterministic builds.

To make this work, you need to use a relative import or resolve the path relative to `import.meta.dirname`.
