### ISSUE TITLE
zsh: illegal hardware instruction  deno run a.ts

### ISSUE THREAD

**Issue by eavidy** [denoland/deno#27399]
Version: Deno 2.1.2
OS: Mac OS

a.ts
```ts
export class Case {
  constructor() {
    get() as any;
  }
  @doc
  method() {}
}
function get() {}
function doc(args: any): any {}
console.log(1);
```
`deno run a.ts` terminal Output  `zsh: illegal hardware instruction  deno run a.ts`

When I comment out the third or fifth line, this bug will not appear

```ts
export class Case {
  constructor() {
    // get() as any;
  }
//   @doc
  method() {}
}
function get() {}
function doc(args: any): any {}
console.log(1);
```

**Comment by eavidy** [comment]
In windows Power Shell, there is no output

**Comment by lucacasonato** [comment]
@eavidy What is the actual system you are on? Like what Macbook / iMac / Mac Mini are you using?

**Comment by dsherret** [comment]
I get this:

```
$ deno run -A main.ts
Segmentation fault
```

**Comment by nathanwhit** [comment]
It looks like it's hitting an `unreachable_unchecked` in swc. You can see the source in a debug build (it uses `unreachable!()` in debug, `unreachable_unchecked` in release):

```
❯ RUST_BACKTRACE=1 dbgdeno run -A a.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 2.1.4
Args: ["/Users/nathanwhit/Documents/Code/deno/target/debug/deno", "run", "-A", "a.ts"]

thread 'tokio-runtime-worker' panicked at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/lib.rs:552:9:
internal error: entered unreachable code: This visitor does not support TypeScript. This method fails for optimization purposes. Encountered in unreachable visitor: visit_mut_ts_type
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: swc_ecma_visit::fail_no_typescript
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/lib.rs:552:9
   3: <swc_ecma_utils::constructor::ExprInjector as swc_ecma_visit::generated::VisitMut>::visit_mut_ts_type
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/lib.rs:909:13
   4: <swc_ecma_ast::typescript::TsType as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:63552:9
   5: <alloc::boxed::Box<T> as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:65038:17
   6: <swc_ecma_ast::typescript::TsAsExpr as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:62260:21
   7: swc_ecma_visit::generated::VisitMut::visit_mut_ts_as_expr
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:49818:9
   8: <swc_ecma_ast::typescript::TsAsExpr as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:62243:9
   9: <swc_ecma_ast::expr::Expr as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59775:17
  10: <swc_ecma_utils::constructor::ExprInjector as swc_ecma_visit::generated::VisitMut>::visit_mut_expr
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_utils-0.134.2/src/constructor.rs:129:9
  11: <swc_ecma_ast::expr::Expr as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59673:9
  12: <alloc::boxed::Box<T> as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:65038:17
  13: <swc_ecma_ast::stmt::ExprStmt as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59827:21
  14: swc_ecma_visit::generated::VisitMut::visit_mut_expr_stmt
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:48808:9
  15: <swc_ecma_ast::stmt::ExprStmt as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59817:9
  16: <swc_ecma_ast::stmt::Stmt as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:61922:17
  17: swc_ecma_visit::generated::VisitMut::visit_mut_stmt
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:49686:9
  18: <swc_ecma_ast::stmt::Stmt as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:61862:9
  19: <swc_ecma_utils::constructor::Injector as swc_ecma_visit::generated::Fold>::fold_stmts::{{closure}}
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_utils-0.134.2/src/constructor.rs:86:17
  20: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:810:29
  21: <alloc::vec::into_iter::IntoIter<T,A> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/into_iter.rs:318:25
  22: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/iter/traits/iterator.rs:813:9
  23: <swc_ecma_utils::constructor::Injector as swc_ecma_visit::generated::Fold>::fold_stmts
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_utils-0.134.2/src/constructor.rs:58:9
  24: <alloc::vec::Vec<swc_ecma_ast::stmt::Stmt> as swc_ecma_visit::generated::FoldWith<V>>::fold_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:107852:9
  25: <swc_ecma_ast::stmt::BlockStmt as swc_ecma_visit::generated::FoldWith<V>>::fold_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:101973:31
  26: swc_ecma_visit::generated::Fold::fold_block_stmt
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:91478:9
  27: <swc_ecma_ast::stmt::BlockStmt as swc_ecma_visit::generated::FoldWith<V>>::fold_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:101965:9
  28: <core::option::Option<swc_ecma_ast::stmt::BlockStmt> as swc_ecma_visit::generated::FoldWith<V>>::fold_children_with::{{closure}}
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:107497:26
  29: core::option::Option<T>::map
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:1105:29
  30: <core::option::Option<swc_ecma_ast::stmt::BlockStmt> as swc_ecma_visit::generated::FoldWith<V>>::fold_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:107497:9
  31: swc_ecma_visit::generated::Fold::fold_opt_block_stmt
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:92245:9
  32: <core::option::Option<swc_ecma_ast::stmt::BlockStmt> as swc_ecma_visit::generated::FoldWith<V>>::fold_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:107492:9
  33: swc_ecma_utils::constructor::inject_after_super
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_utils-0.134.2/src/constructor.rs:16:14
  34: <swc_ecma_transforms_proposal::decorator_impl::DecoratorPass as swc_ecma_visit::generated::VisitMut>::visit_mut_class
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_proposal-0.179.0/src/decorator_impl.rs:821:17
  35: <swc_ecma_ast::class::Class as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59023:9
  36: <alloc::boxed::Box<T> as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:65038:17
  37: <swc_ecma_ast::decl::ClassDecl as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59092:21
  38: swc_ecma_visit::generated::VisitMut::visit_mut_class_decl
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:48598:9
  39: <swc_ecma_ast::decl::ClassDecl as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59078:9
  40: <swc_ecma_ast::decl::Decl as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59379:17
  41: swc_ecma_visit::generated::VisitMut::visit_mut_decl
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:48675:9
  42: <swc_ecma_ast::decl::Decl as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59373:9
  43: <swc_ecma_ast::module_decl::ExportDecl as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59544:21
  44: swc_ecma_visit::generated::VisitMut::visit_mut_export_decl
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:48731:9
  45: <swc_ecma_ast::module_decl::ExportDecl as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:59534:9
  46: <swc_ecma_ast::module_decl::ModuleDecl as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:61030:17
  47: swc_ecma_visit::generated::VisitMut::visit_mut_module_decl
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:49221:9
  48: <swc_ecma_ast::module_decl::ModuleDecl as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:61021:9
  49: <swc_ecma_ast::module::ModuleItem as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:61082:17
  50: <swc_ecma_transforms_proposal::decorator_impl::DecoratorPass as swc_ecma_visit::generated::VisitMut>::visit_mut_module_item
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_proposal-0.179.0/src/decorator_impl.rs:1585:17
  51: <swc_ecma_ast::module::ModuleItem as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:61076:9
  52: <swc_ecma_transforms_proposal::decorator_impl::DecoratorPass as swc_ecma_visit::generated::VisitMut>::visit_mut_module_items
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_proposal-0.179.0/src/decorator_impl.rs:1599:13
  53: <alloc::vec::Vec<swc_ecma_ast::module::ModuleItem> as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:64398:9
  54: <swc_ecma_ast::module::Module as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:61009:21
  55: swc_ecma_visit::generated::VisitMut::visit_mut_module
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:49214:9
  56: <swc_ecma_ast::module::Module as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:60995:9
  57: <swc_ecma_ast::module::Program as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_children_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:61547:17
  58: swc_ecma_visit::generated::VisitMut::visit_mut_program
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:49581:9
  59: <swc_ecma_ast::module::Program as swc_ecma_visit::generated::VisitMutWith<V>>::visit_mut_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:61541:9
  60: <swc_ecma_visit::Folder<V> as swc_ecma_visit::generated::Fold>::fold_program
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/lib.rs:292:13
  61: <swc_visit::Optional<V> as swc_ecma_visit::generated::Fold>::fold_program
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:100405:13
  62: swc_ecma_visit::<impl swc_ecma_visit::generated::Fold for swc_visit::AndThen<A,B>>::fold_program
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/lib.rs:26:17
  63: swc_ecma_visit::<impl swc_ecma_visit::generated::Fold for swc_visit::AndThen<A,B>>::fold_program
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/lib.rs:27:9
  64: swc_ecma_visit::<impl swc_ecma_visit::generated::Fold for swc_visit::AndThen<A,B>>::fold_program
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/lib.rs:27:9
  65: swc_ecma_visit::<impl swc_ecma_visit::generated::Fold for swc_visit::AndThen<A,B>>::fold_program
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/lib.rs:27:9
  66: <swc_ecma_ast::module::Program as swc_ecma_visit::generated::FoldWith<V>>::fold_with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_visit-0.104.8/src/generated.rs:104610:9
  67: deno_ast::transpiling::fold_program::{{closure}}::{{closure}}
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_ast-0.44.0/src/transpiling/mod.rs:759:7
  68: scoped_tls::ScopedKey<T>::set
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scoped-tls-1.0.1/src/lib.rs:137:9
  69: better_scoped_tls::ScopedKey<T>::set
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/better_scoped_tls-0.1.1/src/lib.rs:55:9
  70: deno_ast::transpiling::fold_program::{{closure}}
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_ast-0.44.0/src/transpiling/mod.rs:758:5
  71: scoped_tls::ScopedKey<T>::set
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scoped-tls-1.0.1/src/lib.rs:137:9
  72: better_scoped_tls::ScopedKey<T>::set
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/better_scoped_tls-0.1.1/src/lib.rs:55:9
  73: deno_ast::transpiling::fold_program
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_ast-0.44.0/src/transpiling/mod.rs:757:16
  74: deno_ast::transpiling::transpile::{{closure}}
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_ast-0.44.0/src/transpiling/mod.rs:399:5
  75: deno_ast::parsed_source::Globals::with::{{closure}}
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_ast-0.44.0/src/parsed_source.rs:57:55
  76: scoped_tls::ScopedKey<T>::set
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scoped-tls-1.0.1/src/lib.rs:137:9
  77: better_scoped_tls::ScopedKey<T>::set
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/better_scoped_tls-0.1.1/src/lib.rs:55:9
  78: deno_ast::parsed_source::Globals::with
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_ast-0.44.0/src/parsed_source.rs:57:5
  79: deno_ast::transpiling::transpile
             at /Users/nathanwhit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_ast-0.44.0/src/transpiling/mod.rs:398:17
```

**Comment by eavidy** [comment]
> @eavidy What is the actual system you are on? Like what Macbook / iMac / Mac Mini are you using?

Macbook, Intel Core

**Comment by nayeemrmn** [comment]
Fixed
