### ISSUE TITLE
Uncaught PermissionDenied: Permission denied (os error 13) When running vite

### ISSUE THREAD

**Issue by nsetyo** [denoland/deno#27420]
Version: Deno 2.1.4

I have a remix project which contain a directory with restricted permission. When i run the project with npm the project run without a problem. But with Deno it gives me  `Uncaught PermissionDenied`. The folder itself is ignored in `.gitignore`

Here is the log

```
DEBUG RS - deno_config::deno_json:731 - Config file found at '/home/nsetyo/projects/ppatk/sipandai/deno.jsonc'
DEBUG RS - deno_config::workspace::discovery:266 - package.json file found at '/home/nsetyo/projects/ppatk/sipandai/package.json'
DEBUG RS - deno::args:593 - .npmrc found at: '/home/nsetyo/.npmrc'
DEBUG RS - deno::args:937 - Finished config loading.
DEBUG RS - deno::task_runner:438 - Resolving commands in '/home/nsetyo/projects/ppatk/sipandai/node_modules/.bin'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'sucrase-node' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/sucrase/bin/sucrase-node'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'jsesc' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/jsesc/bin/jsesc'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'uuid' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/uuid/dist/bin/uuid'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'tsc' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/typescript/bin/tsc'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'vite' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/vite/bin/vite.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'mkdirp' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/mkdirp/bin/cmd.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'resolve' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/resolve/bin/resolve'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'semver' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/semver/bin/semver.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'jiti' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/jiti/bin/jiti.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'pidtree' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/pidtree/bin/pidtree.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'vite-node' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/vite-node/vite-node.mjs'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'loose-envify' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/loose-envify/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'migrate-flat-routes' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/remix-flat-routes/dist/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'prisma' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/prisma/build/index.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'json5' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/json5/lib/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'nanoid' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/nanoid/bin/nanoid.cjs'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'mime' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/mime/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'astring' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/astring/bin/astring'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'sucrase' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/sucrase/bin/sucrase'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'husky' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/husky/bin.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'acorn' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/acorn/bin/acorn'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'glob' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/glob/dist/esm/bin.mjs'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'autoprefixer' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/autoprefixer/bin/autoprefixer'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'conventional-commits-parser' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/conventional-commits-parser/cli.mjs'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'prettier' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/prettier/bin/prettier.cjs'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'commitizen' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/commitizen/bin/commitizen'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'remix-serve' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/@remix-run/serve/dist/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'cz' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/commitizen/bin/git-cz'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'tailwind' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/tailwindcss/lib/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'parser' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/@babel/parser/bin/babel-parser.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'biome' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/@biomejs/biome/bin/biome'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'update-browserslist-db' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/update-browserslist-db/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'rollup' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/rollup/dist/bin/rollup'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'git-raw-commits' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/git-raw-commits/cli.mjs'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'cssesc' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/cssesc/bin/cssesc'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'git-cz' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/commitizen/bin/git-cz'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'gunzip-maybe' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/gunzip-maybe/bin.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'commitlint' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/@commitlint/cli/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'yaml' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/yaml/bin.mjs'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'tsconfck' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/tsconfck/bin/tsconfck.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'tailwindcss' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/tailwindcss/lib/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'browserslist' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/browserslist/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'commit' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/@commitlint/prompt-cli/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'tsserver' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/typescript/bin/tsserver'.
DEBUG RS - deno::task_runner:481 - Failed resolving npx command 'JSONStream'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'node-which' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/which/bin/which.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'js-yaml' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/js-yaml/bin/js-yaml.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'remix' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/@remix-run/dev/dist/cli.js'.
DEBUG RS - deno::task_runner:474 - Resolved npx command 'uvu' to '/home/nsetyo/projects/ppatk/sipandai/node_modules/uvu/bin.js'.
Task dev remix vite:dev --logLevel info
error: Uncaught PermissionDenied: Permission denied (os error 13) about ["/home/nsetyo/projects/ppatk/sipandai/.volumes/mssql/secrets/machine-key"]
    at new FsWatcher (ext:runtime/40_fs_events.js:24:17)
    at Object.watchFs (ext:runtime/40_fs_events.js:74:10)
    at ext:deno_node/_fs/_fs_watch.ts:57:21
    at callback (ext:deno_web/02_timers.js:58:7)
    at eventLoopTick (ext:core/01_core.js:210:13)

```

**Comment by littledivy** [comment]
It's hard to investigate without a reproduction. Is the project using a mssql client? Does the user launching Deno has access to the restricted directory?

**Comment by nsetyo** [comment]
> It's hard to investigate without a reproduction. Is the project using a mssql client? Does the user launching Deno has access to the restricted directory?

So, I have a docker volume directory inside the project root which I ignore in `.gitignore`. Run the project using npm doesn't have this problem, but using deno task show the error above

**Comment by nsetyo** [comment]
> It's hard to investigate without a reproduction. Is the project using a mssql client? Does the user launching Deno has access to the restricted directory?

To reproduce this issue is first create a vite based project, in project root directory create a directory that have no read permission (in my case owned by root and have linux 700 permission) and run `deno task dev`

```
error: Uncaught PermissionDenied: Permission denied (os error 13) about ["/home/nsetyo/projects/my-react-router-app/restricted-dir"]
    at new FsWatcher (ext:runtime/40_fs_events.js:24:17)
    at Object.watchFs (ext:runtime/40_fs_events.js:74:10)
    at ext:deno_node/_fs/_fs_watch.ts:57:21
    at callback (ext:deno_web/02_timers.js:58:7)
    at eventLoopTick (ext:core/01_core.js:210:13)
```

**Comment by Antonio476587** [comment]
https://github.com/denoland/deno_docker/issues/317#issue-1964101729

**Comment by bartlomieju** [comment]
Re-triaged on canary 2.8.1.

This was substantially fixed by #34398 (`fix(ext/node): emit 'error' event for fs.watch open failures`). `fs.watch` no longer throws a raw `Deno.errors.PermissionDenied` synchronously from inside `Deno.watchFs` — the open failure is now caught, translated into a Node-style `EACCES` error via `denoErrorToNodeError`, and emitted on the returned `FSWatcher` as an `'error'` event.

Verified on Linux with a root-owned mode-000 directory:
- With an `'error'` listener (chokidar / vite path): the event fires with `error.code === 'EACCES'` and the watcher continues cleanly.
- Without a listener: the error is still thrown (Node's EventEmitter rethrows unhandled `'error'` events — same as Node.js itself), but now as a proper Node `EACCES` error rather than a raw Deno error.

The original stack trace from `new FsWatcher` / `Object.watchFs` / `_fs_watch.ts:57` is no longer reachable. Closing — please open a fresh issue with a current repro on 2.8.1+ if you still see it.
