### ISSUE TITLE
next.js build isn't working

### ISSUE THREAD

**Issue by hedefalk** [denoland/deno#27424]
```
deno --version
deno 2.1.1 (stable, release, aarch64-apple-darwin)
v8 13.0.245.12-rusty
typescript 5.6.2
```

Following the guide here: https://docs.deno.com/examples/next_tutorial/

just doing the first steps but doing a build:

deno task build

```
🐟 deno task build
Task build next build
   ▲ Next.js 15.1.2

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
   Collecting page data  ..TypeError: e[o] is not a function
    at t (.next/server/webpack-runtime.js:1:363)
    at r (.next/server/app/page.js:1:56005)
    at <unknown> (.next/server/app/page.js:1:56035)
    at t.X (.next/server/webpack-runtime.js:1:1427)
    at <unknown> (.next/server/app/page.js:1:56018)
    at Object.<anonymous> (.next/server/app/page.js:1:56062)
    at Object.<anonymous> (.next/server/app/page.js:2:4)

> Build error occurred
Error: Failed to collect page data for /
    at Object.runMicrotasks (ext:core/01_core.js:683:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:59:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:76:3)
    at eventLoopTick (ext:core/01_core.js:182:21) {
  type: "Error"
}

```

**Comment by hedefalk** [comment]
Oh, forgot standalone…
