### ISSUE TITLE
Error running preact project with `create-vite`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#27432]
Version: Deno 2.1.4

## Reproduction

```
scarf@fedora /r/m/h/s/r/e/what-a-week> deno run -A npm:create-vite
✔ Project name: … vite-project
✔ Select a framework: › Preact
✔ Select a variant: › TypeScript

Scaffolding project in /run/media/home/scarf/repo/etc/what-a-week/vite-project...

Done. Now run:

  cd vite-project
  deno install
  deno run dev
scarf@fedora /r/m/h/s/r/e/what-a-week> cd vite-project/
scarf@fedora /r/m/h/s/r/e/w/vite-project> deno install
scarf@fedora /r/m/h/s/r/e/w/vite-project> deno run dev
```

## Error log

```
Task dev vite

  VITE v6.0.5  ready in 409 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
오후 9:57:54 [vite] Pre-transform error: Cannot find package '@babel/plugin-transform-react-jsx-development' imported from /run/media/home/scarf/repo/etc/what-a-week/vite-project/babel-virtual-resolve-base.js
  Plugin: vite:preact-jsx
  File: /run/media/home/scarf/repo/etc/what-a-week/vite-project/src/main.tsx
오후 9:57:54 [vite] Internal server error: Cannot find package '@babel/plugin-transform-react-jsx-development' imported from /run/media/home/scarf/repo/etc/what-a-week/vite-project/babel-virtual-resolve-base.js
  Plugin: vite:preact-jsx
  File: /run/media/home/scarf/repo/etc/what-a-week/vite-project/src/main.tsx
      at __node_internal_ (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:225:9)
      at new NodeError (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:195:5)
      at packageResolve (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:899:9)
      at moduleResolve (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:939:18)
      at defaultResolve (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1017:15)
      at resolve (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1030:12)
      at tryImportMetaResolve (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/files/plugins.js:148:45)
      at resolveStandardizedNameForImport (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/files/plugins.js:173:19)
      at resolveStandardizedName (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/files/plugins.js:185:22)
      at loadPlugin (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/files/plugins.js:55:7)
      at undefined
      at createDescriptor (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-descriptors.js:140:16)
      at undefined
      at step (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:261:32)
      at evaluateAsync (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:291:5)
      at /run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:44:11
      at undefined
      at Function.async (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:43:15)
      at Function.all (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:216:13)
      at undefined
      at createDescriptors (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-descriptors.js:102:41)
      at undefined
      at createPluginDescriptors (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-descriptors.js:99:17)
      at undefined
      at /run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-descriptors.js:65:32
      at undefined
      at Function.<anonymous> (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
      at undefined
      at step (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:269:25)
      at evaluateAsync (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:291:5)
      at Function.errback (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:113:7)
      at errback (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/gensync-utils/async.js:65:18)
      at async (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:188:17)
      at onFirstPause (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:216:13)
      at undefined
      at cachedFunction (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/caching.js:52:46)
      at undefined
      at mergeChainOpts (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-chain.js:349:34)
      at undefined
      at chainWalker (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-chain.js:316:14)
      at undefined
      at buildRootChain (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/config-chain.js:56:36)
      at undefined
      at loadPrivatePartialConfig (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/partial.js:72:62)
      at undefined
      at loadFullConfig (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/config/full.js:36:46)
      at undefined
      at transform (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/transform.js:20:44)
      at undefined
      at step (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:269:25)
      at evaluateAsync (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:291:5)
      at /run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:93:9
      at undefined
      at async (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/gensync@1.0.0-beta.2/node_modules/gensync/index.js:92:14)
      at stopHiding - secret - don't use this - v1 (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
      at transformAsync (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@babel+core@7.26.0/node_modules/@babel/core/lib/transform.js:45:77)
      at TransformPluginContext.transform (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/@preact+preset-vite@2.9.3/node_modules/@preact/preset-vite/dist/esm/index.mjs:77:34)
      at EnvironmentPluginContainer.transform (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/vite@6.0.5/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:47215:19)
      at loadAndTransform (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/vite@6.0.5/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:41025:49)
      at eventLoopTick (ext:core/01_core.js:175:7)
      at async viteTransformMiddleware (/run/media/home/scarf/repo/etc/what-a-week/vite-project/node_modules/.deno/vite@6.0.5/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:42469:24)
```

related: https://github.com/bluwy/create-vite-extra/issues/67

**Comment by Krivich1337** [comment]
Same

```
[plugin:vite:preact-jsx] Cannot find package '@babel/plugin-transform-react-jsx-development' imported from /home/user/repos/blog/babel-virtual-resolve-base.js

/home/user/repos/blog/src/main.tsx
```

**Comment by marvinhagemeister** [comment]
Just published a [new version](https://github.com/preactjs/preset-vite/releases/tag/v2.10.0) of `@preact/vite-preset` that resolves this issue. Update to `v2.10.0` in your project to resolve it.
