### ISSUE TITLE
`Deno.serve` terminates due to unexpected error if `--unstable-otel` is specified

### ISSUE THREAD

**Issue by kawmra** [denoland/deno#27462]
Version: Deno 2.1.4

# Reproduction

This reproduction code panics in v2.1.2 and 2.1.3.
It works in 2.1.1.

```ts
// main.ts
Deno.serve((_req) => new Response("Hello, world!"));
```

```sh
$ deno run -A --unstable-otel main.ts
```

Then request to `http://localhost:8000`, the following error occurs:

```sh
Terminating Deno.serve loop due to unexpected error Error: instrumentation scope not available
    at submitSpan (ext:deno_telemetry/telemetry.ts:56:3)
    at endSpan (ext:deno_telemetry/telemetry.ts:170:7)
    at ext:deno_http/00_serve.ts:449:71
    at <anonymous>
    at eventLoopTick (ext:core/01_core.js:175:7)
```

No env vars are specified.

This doesn't happen if `OTEL_EXPORTER_OTLP_PROTOCOL` env var is specified (e.g. `http/json`) but I don't want to enable otel export in local development.

**Comment by anders-scholander** [comment]
I experience a smiliar problem, even if I do not set the --unstable-otel flag.

If I do this:
`touch main.ts && echo "console.log(42)" > main.ts &&  OTEL_EXPORTER_OTLP_PROTOCOL=grpc deno run main.ts`
then Deno end silently with exit code 1
This is on Deno version > 2.1.4 - with version 2.1.4 the line above works.

**Comment by bartlomieju** [comment]
Indeed this is fixed in 2.1.10.
