### ISSUE TITLE
`deno check` doesn't output source file information in stack trace when it can't open library file

### ISSUE THREAD

**Issue by dandv** [denoland/deno#27477]
I'm running `deno check` and getting a stack trace that only includes Deno internals, not my source file(s):

```
$ deno check main.ts
Check file:///home/dandv/deno-bugs/main.ts
error: Uncaught Error: Unable to load /home/dandv/.cache/deno/npm/registry.npmjs.org/@anthropic-ai/sdk/0.33.1/src/resources/messages.d.ts: No such file or directory (os error 2)
    at Object.getSourceFile (ext:deno_tsc/99_main_compiler.js:621:28)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126789:23)
    at findSourceFile (ext:deno_tsc/00_typescript.js:126705:20)
    at processImportedModules (ext:deno_tsc/00_typescript.js:127105:11)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126854:7)
    at findSourceFile (ext:deno_tsc/00_typescript.js:126705:20)
    at processImportedModules (ext:deno_tsc/00_typescript.js:127105:11)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126854:7)
    at findSourceFile (ext:deno_tsc/00_typescript.js:126705:20)
    at ext:deno_tsc/00_typescript.js:126654:22
```

I would expect to see `main.ts` and `lib.ts` at the top of (actually instead of) that stack trace.

**main.ts**
```ts
import { message } from './lib.ts';

console.log(message);
```

**lib.ts**
```ts
import type { Message } from '@anthropic-ai/sdk/src/resources/messages';

export const message: Message = 'foo';  // this is wrong, Message is an object
```

# Reproduction

1. `git clone https://github.com/dandv/deno-bug-check-stack-trace-omits-source-file`
2. `deno check main.ts`

Version: Deno 2.1.4

# Related

#27472

**Comment by dandv** [comment]
An additional bug is that when multiple files are passed to `deno check`, even the offending file is not listed.

For example in the repo above, notice how the error appears after `Check... main.ts`, but the source of the error is in `lib.ts`.

```
$ deno check *.ts
Check file:///home/dandv/deno-bugs/deno-check-stack-trace/lib.ts
Check file:///home/dandv/deno-bugs/deno-check-stack-trace/main.ts
error: Uncaught Error: Unable to load /home/dandv/.cache/deno/npm/registry.npmjs.org/@anthropic-ai/sdk/0.33.1/src/resources/messages.d.ts: No such file or directory (os error 2)
    at Object.getSourceFile (ext:deno_tsc/99_main_compiler.js:621:28)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126789:23)
    at findSourceFile (ext:deno_tsc/00_typescript.js:126705:20)
    at processImportedModules (ext:deno_tsc/00_typescript.js:127105:11)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126854:7)
    at findSourceFile (ext:deno_tsc/00_typescript.js:126705:20)
    at ext:deno_tsc/00_typescript.js:126654:22
    at getSourceFileFromReferenceWorker (ext:deno_tsc/00_typescript.js:126625:26)
    at processSourceFile (ext:deno_tsc/00_typescript.js:126652:5)
    at processRootFile (ext:deno_tsc/00_typescript.js:126444:5)
```

**Comment by bartlomieju** [comment]
This is fixed on current versions (verified on 2.8.2, the report was on 2.1.4).

`deno check` no longer throws an uncaught internal error with a `deno_tsc` stack trace. The same input now produces a proper diagnostic that points at the actual source file:

```
TS2307 [ERROR]: Import "@anthropic-ai/sdk/src/resources/messages" not a dependency and not in import map from "file:///.../lib.ts"
    at file:///.../lib.ts:1:30
```

The multi-file `deno check *.ts` case from the follow-up comment also names the offending file correctly now. Closing as fixed, please open a new issue if you run into anything similar.
