### ISSUE TITLE
node:fs - cpSync doesn't respect options

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#27494]
Reproduction:

```ts
import { cpSync } from "node:fs";

for (let i = 0; i < 100_000; i++) {
  cpSync("folder", "other", {
    force: true,
    recursive: true
  });
}
```

```
> node main.mjs
> deno run -A main.mjs
error: Uncaught (in promise) AlreadyExists: Cannot create a file when that file already exists. (os error 183)
  cpSync("folder", "other", {
  ^
    at cpSync (ext:deno_node/_fs/_fs_cp.js:17:3)
    at file:///V:/scratch/main.mjs:4:3
```

The op doesn't even use the options:

```
export function cpSync(src, dest, options) {
  validateCpOptions(options);
  const srcPath = getValidatedPath(src, "src");
  const destPath = getValidatedPath(dest, "dest");

  op_node_cp_sync(srcPath, destPath);
}
```

**Comment by chyzwar** [comment]
Same issue with `cp`
