### ISSUE TITLE
Uncaught PermissionDenied

### ISSUE THREAD

**Issue by 0x018** [denoland/deno#2837]
I want to use rxjs and install it with `npm  i rxjs` .

at [config.ts] 

    import { Observable, timer } from './node_modules/rxjs';
    .........
    timer(0,1000).subscribe(v=>{
        console.log('timer(0,1000)');
    })

when run: 

    E:\test\deno>deno run -A main.ts

    Compile file:///E:/test/deno/config.ts

    error: Uncaught PermissionDenied: 拒绝访问。 (os error 5)

    ► js/errors.ts:33:12

        at DenoError (js/errors.ts:22:5)
        
        at maybeError (js/errors.ts:33:12)
        
        at maybeThrowError (js/errors.ts:39:15)
        
        at sendSync (js/dispatch.ts:137:5)
        
        at fetchSourceFile (js/compiler.ts:134:19)
        
        at _resolveModule (js/compiler.ts:253:12)
        
        at js/compiler.ts:369:33
        
        at resolveModuleNames (js/compiler.ts:367:24)
        
        at resolveModuleNamesWorker (third_party/node_modules/typescript/lib/typescript.js:89230:127)
        
        at resolveModuleNamesReusingOldState (third_party/node_modules/typescript/lib/typescript.js:89473:24)

**Comment by StefanYohansson** [comment]
I think you misunderstood the deno' proposal.

![image](https://user-images.githubusercontent.com/1783252/64066992-3e0e5c80-cbf7-11e9-8316-93c759594c62.png)

deno allow imports from URL, so you can go for it on your example.

https://deno.land/manual.html#philosophy

**Comment by kevinkassimo** [comment]
Per discussion from other channels, you should import directly from files instead of using Node like `index.js` resolution. Also npm version of rxjs would definitely not work, you can use versions from e.g. https://dev.jspm.io/rxjs 

I do notice that the error messages are confusing. On windows you get `Permission denied`, and on macOS I got `Is a directory`. Either of the 2 error messages mention about the path of import that causes the trouble. We need to fix this behavior

**Comment by bartlomieju** [comment]
Can this issue be closed?
