### ISSUE TITLE
travis strace test sometimes failing

### ISSUE THREAD

**Issue by ry** [denoland/deno#3047]
[Failure looks like this](https://travis-ci.com/denoland/deno/jobs/241080896):
```
======================================================================
ERROR: strace (__main__.TestBenchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tools/benchmark_test.py", line 43, in test_strace
    benchmark.run_strace_benchmarks(self.deno_exe, new_data)
  File "/home/travis/build/denoland/deno/tools/benchmark.py", line 151, in run_strace_benchmarks
    s = get_strace_summary([deno_exe, "run"] + args)
  File "/home/travis/build/denoland/deno/tools/benchmark.py", line 134, in get_strace_summary
    return strace_parse(get_strace_summary_text(test_args))
  File "/home/travis/build/denoland/deno/tools/benchmark.py", line 114, in strace_parse
    "% time": float(syscall_fields[0]),
ValueError: could not convert string to float: ------
----------------------------------------------------------------------
Ran 4 tests in 9.386s
```

I suppose this is due to a new version of strace with different output...

```
Build system information
Build language: rust
Build group: stable
Build dist: xenial
Build id: 130018702
Job id: 241080896
Runtime kernel version: 4.15.0-1028-gcp
travis-build version: beba64be6
Build image provisioning date and time
Mon Mar 25 16:52:50 UTC 2019
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

**Comment by lucacasonato** [comment]
Travis has been removed so this can be closed.
