### ISSUE TITLE
windows debug build doesn't work

### ISSUE THREAD

**Issue by ry** [denoland/deno#3065]
because of CRT + V8 thing

**Comment by piscisaureus** [comment]
https://github.com/rust-lang/rust/pull/62534
https://github.com/rust-lang/libc/pull/1433

**Comment by gewoonwoutje** [comment]
Fyi, downloading the static rusty_v8 release doesn't work either. (Should this be a separate issue?)

TLDR: it's setting TARGET env variable to `i686-pc-windows-msvc` instead of the expected `x86_64-pc-windows-msvc`.
```log
[rusty_v8 0.3.10] Downloading https://github.com/denoland/rusty_v8/releases/download/v0.3.10/rusty_v8_release_i686-pc-windows-msvc.lib...  
[rusty_v8 0.3.10] HTTP Error 404: Not Found
[rusty_v8 0.3.10] Traceback (most recent call last):
[rusty_v8 0.3.10]   File "./tools/download_file.py", line 62, in <module>
[rusty_v8 0.3.10]     sys.exit(main())
[rusty_v8 0.3.10]   File "./tools/download_file.py", line 57, in main
[rusty_v8 0.3.10]     DownloadUrl(args.url, f)
[rusty_v8 0.3.10]   File "./tools/download_file.py", line 43, in DownloadUrl
[rusty_v8 0.3.10]     raise e
[rusty_v8 0.3.10] urllib2.HTTPError: HTTP Error 404: Not Found
[rusty_v8 0.3.10] thread 'main' panicked at 'assertion failed: status.success()', C:\Users\Wout\.cargo\registry\src\github.com-1ecc6299db9ec823\rusty_v8-0.3.10\build.rs:231:5
[rusty_v8 0.3.10] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `rusty_v8 v0.3.10`

Caused by:
  process didn't exit successfully: `C:\Users\Wout\deno\target\debug\build\rusty_v8-ac889d769df58dc0\build-script-build` (exit code: 101)
--- stdout
static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.3.10/rusty_v8_release_i686-pc-windows-msvc.lib
cargo:rustc-link-search=C:\Users\Wout\deno\target\debug\gn_out\obj
Downloading https://github.com/denoland/rusty_v8/releases/download/v0.3.10/rusty_v8_release_i686-pc-windows-msvc.lib
Downloading https://github.com/denoland/rusty_v8/releases/download/v0.3.10/rusty_v8_release_i686-pc-windows-msvc.lib...
HTTP Error 404: Not Found

--- stderr
Traceback (most recent call last):
  File "./tools/download_file.py", line 62, in <module>
    sys.exit(main())
  File "./tools/download_file.py", line 57, in main
    DownloadUrl(args.url, f)
  File "./tools/download_file.py", line 43, in DownloadUrl
    raise e
urllib2.HTTPError: HTTP Error 404: Not Found
thread 'main' panicked at 'assertion failed: status.success()', C:\Users\Wout\.cargo\registry\src\github.com-1ecc6299db9ec823\rusty_v8-0.3.10\build.rs:231:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

When hardcoding this to the expected TARGET path, the next step in the build (compiling deno) fails.

**Comment by piscisaureus** [comment]
This issue is very old. Deno has been building fine on windows as long as I can remember.

@gewoonwoutje You should install & active the 64 bit rust toolchain. We don't support 32-bit windows builds.
