### ISSUE TITLE
Remove message passing phase from errors stack trace

### ISSUE THREAD

**Issue by beshanoe** [denoland/deno#3255]
Hi! I think it makes sense to remove all the calls from dispatch_json and further to backend part cause they are distracting from the real source of error and they are present in almost every single stack trace. What do you think?
Here are the stack traces from deno and node to compare

```
$ deno util.ts -A
Compile file:///src/util.ts
error: Uncaught NotFound: No such file or directory (os error 2)
► $deno$/dispatch_json.ts:40:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_json.ts:40:11)
    at sendSync ($deno$/dispatch_json.ts:67:10)
    at openSync ($deno$/files.ts:26:15)
    at readFileSync ($deno$/read_file.ts:12:16)
    at file:///src/util.ts:5:6
```

```
$ node util.js
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'non-existing file'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/src/util.js:3:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by ry** [comment]
It’s probably more trouble than it’s worth. You might make things less distracting for novices but at the cost of masking the source or errors. This is something to consider when Deno is a stable and mature piece of software - we have bigger problems to deal with now.
