### ISSUE TITLE
[Permissions] Deno.permissions ignored?

### ISSUE THREAD

**Issue by raven78** [denoland/deno#3682]
Given this:

```typescript
// testRead.ts
import { readJsonSync, readJson } from "https://deno.land/std@v0.29.0/fs/mod.ts";

const settingFilePath = "./settings.json";

console.log("Query permission for read file:");

const permission = await Deno.permissions.query({
  name: "read",
  path: settingFilePath
});
console.log(permission);

console.log("Read the file:");
console.log('READ JSON:', readJsonSync(settingFilePath))
```
with this invocation:
```bash
$:> deno --allow-read=. testRead.ts 
```

**Expected:**
`PermissionStatus { state: "granted" } `
Read the file 

**I get:**
`PermissionStatus { state: "granted" } `
`error: Uncaught PermissionDenied: run again with the --allow-read flag`

```
Query permission for read file:
PermissionStatus { state: "granted" }
Read the file:
error: Uncaught PermissionDenied: run again with the --allow-read flag
► $deno$/dispatch_json.ts:40:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_json.ts:40:11)
    at sendSync ($deno$/dispatch_json.ts:67:10)
    at openSync ($deno$/files.ts:26:15)
    at readFileSync ($deno$/read_file.ts:12:16)
    at readJsonSync (read_json.ts:21:39)
    at testRead.ts:11:26
```

Settings.json is a dummy file and present in the same directory:
```json
{ "dummy": "value" }
```
```bash
deno --version
    deno 0.29.0
    v8 8.1.108
    typescript 3.7.2
```

**Comment by nayeemrmn** [comment]
I don't see the whitelist elements being resolved from cwd anywhere... that has to be a regression.

**Comment by kt3k** [comment]
Thank you @nayeemrmn for the fix!

**Comment by raven78** [comment]
@nayeemrmn  thank you!
