### ISSUE TITLE
crash during 'cargo publish' for cli (aka "deno" crate)

### ISSUE THREAD

**Issue by ry** [denoland/deno#3712]
The error comes from here:
https://github.com/denoland/deno/blob/v0.30.0/deno_typescript/lib.rs#L271

No idea why. Here's the log

```
[...]
cargo:rerun-if-changed=/Users/rld/src/deno/target/package/deno-0.30.0/js/streams/readable-stream-byob-reader.ts
cargo:rerun-if-changed=/Users/rld/src/deno/target/package/deno-0.30.0/js/repl.ts
cargo:rerun-if-changed=/Users/rld/src/deno/target/package/deno-0.30.0/js/format_error.ts
cargo:rerun-if-changed=/Users/rld/src/deno/target/package/deno-0.30.0/js/location.ts

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933
  16: deno_typescript::read_file
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_typescript-0.30.0/lib.rs:256
  17: deno_typescript::get_asset
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_typescript-0.30.0/lib.rs:271
  18: deno_typescript::get_asset2
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_typescript-0.30.0/lib.rs:246
  19: deno_typescript::ops::read_file
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_typescript-0.30.0/ops.rs:48
  20: deno_typescript::ops::json_op::{{closure}}::{{closure}}
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_typescript-0.30.0/ops.rs:23
  21: core::result::Result<T,E>::and_then
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:691
  22: deno_typescript::ops::json_op::{{closure}}
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_typescript-0.30.0/ops.rs:21
  23: deno_typescript::compiler_op::{{closure}}
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_typescript-0.30.0/lib.rs:62
  24: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:956
  25: deno_core::ops::OpRegistry::call
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.30.0/ops.rs:95
  26: deno_core::isolate::Isolate::dispatch_op
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.30.0/isolate.rs:496
  27: deno_core::bindings::send
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.30.0/bindings.rs:440
  28: core::ops::function::Fn::call
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:69
  29: rusty_v8::function::<impl rusty_v8::support::MapFnFrom<F> for extern "C" fn(*const rusty_v8::function::FunctionCallbackInfo)>::mapping::{{closure}}
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.1.0/src/function.rs:240
  30: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
             at /Users/rld/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.1.0/src/support.rs:398
  31: Call
             at ../../../../../../../../.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.1.0/v8/src/api/api-arguments-inl.h:158
  32: HandleApiCallHelper<false>
             at ../../../../../../../../.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.1.0/v8/src/builtins/builtins-api.cc:111
  33: Builtin_Impl_HandleApiCall
             at ../../../../../../../../.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.1.0/v8/src/builtins/builtins-api.cc:141
  34: Builtin_HandleApiCall
             at ../../../../../../../../.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.1.0/v8/src/builtins/builtins-api.cc:129
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

**Comment by ry** [comment]
I believe this was caused by 32cbcfe4e9943a0318c497188e045d23c5f6703a

**Comment by ry** [comment]
Fixed in https://github.com/denoland/deno/commit/fa7f34eb8cec07f4c68ca4e9c46a983bc3e2308f
