### ISSUE TITLE
Can't install file_server

### ISSUE THREAD

**Issue by Cyang39** [denoland/deno#3758]
I followed the [manual](https://deno.land/std/manual.md#file-server) to install `file_server` and encountered the following problem:
```shell
➜  ~ deno install file_server https://deno.land/std/http/file_server.ts --allow-net --allow-read

...
Download https://deno.land/std/testing/diff.ts
Download https://deno.land/std/testing/format.ts
error TS2345: Argument of type '{ recursive: boolean; }' is not assignable to parameter of type 'boolean'.

► https://deno.land/std/io/util.ts:43:39

43   await mkdir(path.dirname(filepath), { recursive: true });
                                         ~~~~~~~~~~~~~~~~~~~

Error: Failed to fetch module.
    at install (https://deno.land/std@v0.26.0/installer/mod.ts:238:11)
    at async main (https://deno.land/std@v0.26.0/installer/mod.ts:294:5)
```
I think these commits may be related: #3617

**Comment by bartlomieju** [comment]
It looks like `deno` version installed on you machine is not up to date. There were a lot of changes to APIs recently so I'd suggest upgrade to latest version - the problem will go away
