### ISSUE TITLE
deno fmt glob expander yielding non-existent file

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#3835]
`RUST_BACKTRACE=1 cargo run -- fmt "std/fs/testdata/*"`:

```
[cli/fmt.rs:102] &file_path = "std/fs/testdata/0-link.ts"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933
  16: deno::fmt::format_source_files
             at cli/fmt.rs:103
...
```
having added `dbg!(&file_path);` right above https://github.com/denoland/deno/blob/25b13c8917061c569e8f92da124b1b446dc223f0/cli/fmt.rs#L102 which is the error.

There is a `std/fs/testdata/0.ts`, but no `std/fs/testdata/0-link.ts`.

cc @bartlomieju

**Comment by nayeemrmn** [comment]
The exact files being matched by that glob are:
```
[cli/fmt.rs:146] &target_files = [
    "std/fs/testdata/0-link.ts",
    "std/fs/testdata/0.ts",
    "std/fs/testdata/copy_dir",
    "std/fs/testdata/copy_dir_link_file",
    "std/fs/testdata/copy_file.txt",
    "std/fs/testdata/empty_dir.ts",
    "std/fs/testdata/empty_dir_sync.ts",
    "std/fs/testdata/exists.ts",
    "std/fs/testdata/exists_sync.ts",
    "std/fs/testdata/expand_wildcard.js",
    "std/fs/testdata/glob",
    "std/fs/testdata/json_empty.json",
    "std/fs/testdata/json_invalid.json",
    "std/fs/testdata/json_valid_array.json",
    "std/fs/testdata/json_valid_obj.json",
]
```

**Comment by nayeemrmn** [comment]
Ugh I had a red file called `0-link.ts` in that directory. Nevermind.
