### ISSUE TITLE
readDir/readDirSync panics when run on a directory with non-Unicode filenames

### ISSUE THREAD

**Issue by seishun** [denoland/deno#3950]
Related to https://github.com/denoland/deno/issues/627.

First, create a directory containing a non-UTF-16 filename. You can use the following code to create such a file:
```cpp
#include <iostream>
#include <windows.h>
#include <string>
using namespace std;

int main()
{
       // Junk surrogate pair
   const wchar_t *filename = L"hi\xD801\x0037";
   HANDLE hfile = CreateFileW(filename, GENERIC_READ, 0, NULL, CREATE_NEW, FILE_ATTRIBUTE_NORMAL, NULL);
   return 0;
}
```
Then run this deno code inside that directory:
```ts
const files = Deno.readDirSync('.\\');
```
Output:
```
..\target\debug\deno.exe --allow-read test.ts
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\macros\mod.rs:15:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by bnoordhuis** [comment]
It's not just Windows and UTF-16. Deno doesn't like invalid UTF-8 either:
```
$ python2 -c 'open("\x80\x7F", "w")'

$ deno eval 'Deno.readDirSync(".")'
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/ops/fs.rs:373:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by bnoordhuis** [comment]
I've opened #4004 with a proposed fix.
