### ISSUE TITLE
read big file line by line

### ISSUE THREAD

**Issue by saostad** [denoland/deno#4007]
I am trying to read a big file (13,147,026 lines of text) line by line with deno but it's giving me error:
```ts
BufferFullError: Buffer full
    at BufReader.readSlice (bufio.ts:339:15)
    at async BufReader.readString (bufio.ts:217:20)
    at async stream_file (buffer.ts:9:18)
```

Here is my code: 
```ts
import { BufReader } from "https://deno.land/std/io/bufio.ts";

export async function stream_file(filename: string) {
  const file = await Deno.open(filename);
  const bufReader = new BufReader(file);
  console.log("Reading data...");
  let line: string | any;
  let lineCount: number = 0;
  while ((line = await bufReader.readString("\n")) != Deno.EOF) {
    lineCount++;
    // do something with `line`.
  }
  file.close();
  console.log(`${lineCount} lines read.`);
}
```

versions: 
```
deno 0.33.0
v8 8.1.108
typescript 3.7.2
```
I am trying to find an equivalent of node streams.
please advise!

**Comment by artisonian** [comment]
In Deno, the I/O model is different. The `Reader` interface is what you want. The idea of a reader is to give the caller a way to request data while getting back pressure (which you can detect by checking to see if the `Reader` gave you the number of bytes you expected). If you aren't familiar with Go, this might seems a bit odd.

But to give an example of your code above:

```typescript
import { BufReader } from "https://deno.land/std@v0.33.0/io/mod.ts";
import { TextProtoReader } from "https://deno.land/std@v0.33.0/textproto/mod.ts";
import { parse } from "https://deno.land/std@v0.33.0/flags/mod.ts";
import { basename } from "https://deno.land/std@v0.33.0/path/mod.ts";

export async function read(r: Deno.Reader) {
  const reader = new TextProtoReader(BufReader.create(r));
  console.log("Reading data...");

  let lineCount = 0;
  while (true) {
    let line = await reader.readLine();
    if (line === Deno.EOF) break;
    // do something with `line`
    lineCount += 1;
  }

  console.log(`${lineCount} lines read.`);
}

if (import.meta.main) {
  const args = parse(Deno.args, {
    boolean: ["h"],
    alias: {
      h: ["help"]
    }
  });

  if (args.h) {
    printUsage();
    Deno.exit(0);
  }

  const [filename] = args._;
  if (!filename) {
    printUsage();
    Deno.exit(1);
  }

  const file = filename === "-" ? Deno.stdin : await Deno.open(filename);
  await read(file);
  file.close();

  function printUsage() {
    console.error(
      `Usage: ${basename(import.meta.url)} --allow-read <filename>`
    );
  }
}
```

The thing to note is that I'm using `TextProtoReader` as a convenience because it has logic for reading lines when the underlying `BufReader`'s buffer is full (you can check out the source…it's pretty straightforward).

**Comment by saostad** [comment]
I tried it with 3 approaches to read 307 MB [test file](http://mattmahoney.net/dc/enwik9.zip) :
- Approach 1: (failed for big file - just worked for medium size file with 128,457 lines )
```ts
import { BufReader } from "https://deno.land/std/io/bufio.ts";

export async function stream_file(filename: string) {
  const file = await Deno.open(filename);
  const bufReader = new BufReader(file);
  console.log("Reading data...");
  let line: string | any;
  let lineCount: number = 0;
  while ((line = await bufReader.readString("\n")) != Deno.EOF) {
    lineCount++;
    // do something with `line`.
  }
  file.close();
  console.log(`${lineCount} lines read.`);
}
```
- Approach 2: 
  - CPU utilization: 18%
  - time to read data: 1':24"
```ts
import { BufReader } from "https://deno.land/std@v0.33.0/io/mod.ts";
import { TextProtoReader } from "https://deno.land/std@v0.33.0/textproto/mod.ts";

export async function textProtoReader(filename:string) {
  const r: Deno.Reader = await Deno.open(filename)
  const reader = new TextProtoReader(BufReader.create(r));
  console.log("Reading data...");

  let lineCount = 0;
  while (true) {
    let line = await reader.readLine();
    if (line === Deno.EOF) break;
    // do something with `line`
    lineCount += 1;
  }

  console.log(`${lineCount} lines read.`);
}
```
- Approach 3: 
  - CPU: 23%
  - time: 27"
```ts
import { BufReader } from "https://deno.land/std/io/bufio.ts";

export async function readLine(filename: string) {
  const file = await Deno.open(filename);
  const bufReader = new BufReader(file);
  console.log("Reading data...");
  let line: string | any;
  let lineCount: number = 0;
  while ((line = await bufReader.readLine()) != Deno.EOF) {
    lineCount++;
    // do something with `line`.
  }
  file.close();
  console.log(`${lineCount} lines read.`);
}
```

can anybody explain why it's different?
I guess the best way to read big file is last approach.

**Comment by kitsonk** [comment]
Side note, feels like something we need to add to the benchmarks.

**Comment by josephrocca** [comment]
saostad's approach 3 doesn't seem to be working for me. For others arrive here via Google looking for a quick copy/paste line-by-line file reader, deepakshrma has a neat example that seems to work well:

```js
import { readLine } from "https://raw.githubusercontent.com/deepakshrma/deno-by-example/feacd84bd5cd5b1a630dfcc72afb3cd64de21b91/examples/file_reader.ts";
let lineIterator = await readLine("yourFile.txt");
for await (let line of lineIterator) {
  console.log(line);
}
```

(I haven't benchmarked it.)
