### ISSUE TITLE
Where is zlib?

### ISSUE THREAD

**Issue by hazae41** [denoland/deno#4045]
It seems it was there:
https://deno.land/std/zlib/
But it is not longer available, and https://deno.land/std/ does not have it

Also, I found a PR that removed it from third parties:
https://github.com/denoland/deno/pull/2958

So, where did it go?

**Comment by ry** [comment]
zlib is an internal dependency - we don't have user-level bindings - it's located here: https://github.com/denoland/rusty_v8/tree/master/third_party

**Comment by hazae41** [comment]
Why is it no longer in std?

**Comment by ry** [comment]
It was never in std

**Comment by hazae41** [comment]
Is there plans to add it to std?

**Comment by ry** [comment]
There are not any issues I'm aware of. We do have zlib compiled in, so exposing some ops to use it seems reasonable.

**Comment by hazae41** [comment]
How can I expose them?

**Comment by 7flash** [comment]
Does it mean my binary executable made with 'deno compile' might not work on macos systems which might not have zlib installed?

I just tried running following code:

```
import { Database } from "https://deno.land/x/sqlite3@0.10.0/mod.ts";

const db = new Database("test.db");

const [version] = db.prepare("select sqlite_version()").value<[string]>()!;
console.log(version);

db.close();
```

then I have an error when running:

```
deno run -A --unstable Jan05-2100.ts
error: Uncaught (in promise) Error: Failed to load SQLite3 Dynamic Library
  throw new Error("Failed to load SQLite3 Dynamic Library", { cause: e });
        ^
    at https://deno.land/x/sqlite3@0.10.0/src/ffi.ts:631:9
    at eventLoopTick (ext:core/01_core.js:181:11)
Caused by: Error: Could not open library: Could not open library: dlopen(/Users/gur/Library/Caches/deno/plug/https/github.com/104011a9e1238b1ae4e9c5bd462569d5bdcb9ae2d6b36d982871dbce44f79c44.dylib, 0x0005): Library not loaded: /opt/homebrew/opt/zlib/lib/libz.1.dylib
  Referenced from: <61850E31-E458-361A-ADCC-2CD22831D197> /Users/gur/Library/Caches/deno/plug/https/github.com/104011a9e1238b1ae4e9c5bd462569d5bdcb9ae2d6b36d982871dbce44f79c44.dylib (built for macOS 14.0 which is newer than running OS)
  Reason: tried: '/opt/homebrew/opt/zlib/lib/libz.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/zlib/lib/libz.1.dylib' (no such file), '/opt/homebrew/opt/zlib/lib/libz.1.dylib' (no such file)
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:454:46)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:591:10)
    at dlopen (https://deno.land/x/plug@1.0.1/mod.ts:155:15)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async https://deno.land/x/sqlite3@0.10.0/src/ffi.ts:614:7
```

This issue is resolved by installing zlib

```
brew install zlib
```

Then it works

```
deno run -A --unstable Jan05-2100.ts
3.44.0
```
