### ISSUE TITLE
Test failures on WSL Linux

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#4169]
These failures seem to have popped up all of a sudden.
These results are from running `cargo test` on from-scratch debug build of current master (9b6a9b769ed6df9d24dc0c5173cf2590a4bdcb47).

```

--SNIP--

There were 2 test failures.
 FAIL  netUdpListenClose
PermissionDenied: Permission denied (os error 13)
    at Object.constructError ($deno$/errors.ts:39:13)
    at unwrapResponse ($deno$/dispatch_json.ts:41:12)
    at Object.sendSync ($deno$/dispatch_json.ts:70:10)
    at Object.listen ($deno$/net.ts:255:15)
    at Object.netUdpListenClose [as fn] (file:///mnt/c/Users/BertBelder/d/denol/cli/js/net_test.ts:15:23)
    at Object.runTests ($deno$/testing.ts:157:22)
    at async file:///mnt/c/Users/BertBelder/d/denol/cli/js/unit_tests.ts:72:3
 FAIL  netUdpSendReceive
AddrInUse: Address already in use (os error 98)
    at Object.constructError ($deno$/errors.ts:49:13)
    at unwrapResponse ($deno$/dispatch_json.ts:41:12)
    at Object.sendSync ($deno$/dispatch_json.ts:70:10)
    at Object.listen ($deno$/net.ts:255:15)
    at Object.netUdpSendReceive [as fn] (file:///mnt/c/Users/BertBelder/d/denol/cli/js/net_test.ts:96:22)
    at Object.runTests ($deno$/testing.ts:157:22)
    at async file:///mnt/c/Users/BertBelder/d/denol/cli/js/unit_tests.ts:72:3

-- SNIP --

Unit tests failed
test js_unit_tests ... FAILED
test lock_check_err ... FAILED
test lock_check_err2 ... FAILED
test lock_check_ok ... FAILED
test lock_check_ok2 ... FAILED
test type_directives_01 ... FAILED

failures:

---- js_unit_tests stdout ----
tools/http_server.py starting...
target_dir /mnt/c/Users/BertBelder/d/denol/target/debug
thread 'js_unit_tests' panicked at 'assertion failed: `(left == right)`
  left: `Some(0)`,
 right: `Some(1)`', cli/tests/integration_tests.rs:278:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- lock_check_err stdout ----
target_dir /mnt/c/Users/BertBelder/d/denol/target/debug
root path /mnt/c/Users/BertBelder/d/denol/cli/..
deno_exe path /mnt/c/Users/BertBelder/d/denol/target/debug/deno
thread 'lock_check_err' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5

---- lock_check_err2 stdout ----
target_dir /mnt/c/Users/BertBelder/d/denol/target/debug
root path /mnt/c/Users/BertBelder/d/denol/cli/..
deno_exe path /mnt/c/Users/BertBelder/d/denol/target/debug/deno
thread 'lock_check_err2' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5

---- lock_check_ok stdout ----
target_dir /mnt/c/Users/BertBelder/d/denol/target/debug
root path /mnt/c/Users/BertBelder/d/denol/cli/..
deno_exe path /mnt/c/Users/BertBelder/d/denol/target/debug/deno
thread 'lock_check_ok' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5

---- lock_check_ok2 stdout ----
target_dir /mnt/c/Users/BertBelder/d/denol/target/debug
root path /mnt/c/Users/BertBelder/d/denol/cli/..
deno_exe path /mnt/c/Users/BertBelder/d/denol/target/debug/deno
thread 'lock_check_ok2' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5

---- type_directives_01 stdout ----
target_dir /mnt/c/Users/BertBelder/d/denol/target/debug
root path /mnt/c/Users/BertBelder/d/denol/cli/..
deno_exe path /mnt/c/Users/BertBelder/d/denol/target/debug/deno
thread 'type_directives_01' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5


failures:
    js_unit_tests
    lock_check_err
    lock_check_err2
    lock_check_ok
    lock_check_ok2
    type_directives_01

test result: FAILED. 139 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by kitsonk** [comment]
I get those on occasion on Mac and have to reboot.  Never really chased it down.

**Comment by ry** [comment]
Check if the python http server was left running in the background?

**Comment by piscisaureus** [comment]
I did reboot actually, it didn't help.

**Comment by piscisaureus** [comment]
Apparently this is due to the UDP tests failing on windows, and the other tests fail because something in the test harness goes awry when that happens.

Since this has already been reported in other issues, I'm closing this one.
