### ISSUE TITLE
Deno.write() API example fails

### ISSUE THREAD

**Issue by cknight** [denoland/deno#4177]
The following partially modified example, taken from the [Deno.write() API](https://deno.land/typedoc/index.html#write), fails.

Example `writeTest.ts`:
```
const encoder = new TextEncoder();
const data = encoder.encode("Hello world\n");
const file = await Deno.open("test_file.txt");
console.log('File: ', file);
console.log(Deno.resources());
await Deno.write(file.rid, data);
```

```
chris@chris-desktop ~/development/deno $ deno --version
deno 0.34.0
v8 8.1.108
typescript 3.7.2

chris@chris-desktop ~/development/deno $ deno --allow-read --allow-write writeTest.ts 
File:  File { rid: 3 }
{ 0: "stdin", 1: "stdout", 2: "stderr", 3: "fsFile" }
error: Uncaught Other: Bad file descriptor (os error 9)
► $deno$/dispatch_minimal.ts:59:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_minimal.ts:59:11)
    at sendAsyncMinimal ($deno$/dispatch_minimal.ts:102:10)
```

**Comment by kevinkassimo** [comment]
The reason of the failure is due to missing of the `create` or `write` flag as OpenOptions. I think in this part, besides problems with the documentation, the error message seems very confusing. I wonder if there is a way to improve that in general...
