### ISSUE TITLE
Integration test _055_import_wasm_via_network fails

### ISSUE THREAD

**Issue by Nautigsam** [denoland/deno#4260]
On master, this test fails with the following output:

```
test _055_import_wasm_via_network ... FAILED

failures:

---- _055_import_wasm_via_network stdout ----
target_dir /home/abertron/Projects/deno/target/debug
root path /home/abertron/Projects/deno/cli/..
deno_exe path /home/abertron/Projects/deno/target/debug/deno
tools/http_server.py starting...
target_dir /home/abertron/Projects/deno/target/debug
OUTPUT

OUTPUT
thread '_055_import_wasm_via_network' panicked at 'bad exit code, expected: 0, actual: 101', cli/tests/integration_tests.rs:2056:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by nayeemrmn** [comment]
Which platform? WSL by any chance?

**Comment by Nautigsam** [comment]
@nayeemrmn Plain old Linux (Ubuntu 19.10)

**Comment by Nautigsam** [comment]
Apparently there is an error fetching the file `055_import_wasm_via_network.wasm`. Here is the full output:
```
[0m[38;5;10mDownload[0m http://127.0.0.1:4545/cli/tests/055_import_wasm_via_network.ts
[0m[38;5;10mCompile[0m http://127.0.0.1:4545/cli/tests/055_import_wasm_via_network.ts
[0m[38;5;10mDownload[0m http://127.0.0.1:4545/cli/tests/055_import_wasm_via_network.wasm
thread 'deno-ts-compiler' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [0, 97, 115, 109, 1, 0, 0, 0, 1, 10, 2, 96, 0, 0, 96, 2, 127, 127, 1, 127, 3, 3, 2, 0, 1, 4, 5, 1, 112, 1, 1, 1, 5, 3, 1, 0, 2, 6, 33, 5, 127, 1, 65, 128, 136, 4, 11, 127, 0, 65, 128, 8, 11, 127, 0, 65, 128, 8, 11, 127, 0, 65, 128, 136, 4, 11, 127, 0, 65, 128, 8, 11, 7, 94, 7, 6, 109, 101, 109, 111, 114, 121, 2, 0, 17, 95, 95, 119, 97, 115, 109, 95, 99, 97, 108, 108, 95, 99, 116, 111, 114, 115, 0, 0, 10, 95, 95, 100, 97, 116, 97, 95, 101, 110, 100, 3, 1, 13, 95, 95, 103, 108, 111, 98, 97, 108, 95, 98, 97, 115, 101, 3, 2, 11, 95, 95, 104, 101, 97, 112, 95, 98, 97, 115, 101, 3, 3, 12, 95, 95, 100, 115, 111, 95, 104, 97, 110, 100, 108, 101, 3, 4, 3, 97, 100, 100, 0, 1, 10, 66, 2, 2, 0, 11, 61, 1, 6, 127, 35, 128, 128, 128, 128, 0, 33, 2, 65, 16, 33, 3, 32, 2, 32, 3, 107, 33, 4, 32, 4, 32, 0, 54, 2, 12, 32, 4, 32, 1, 54, 2, 8, 32, 4, 40, 2, 12, 33, 5, 32, 4, 40, 2, 8, 33, 6, 32, 5, 32, 6, 106, 33, 7, 32, 7, 15, 11, 0, 32, 4, 110, 97, 109, 101, 1, 25, 2, 0, 17, 95, 95, 119, 97, 115, 109, 95, 99, 97, 108, 108, 95, 99, 116, 111, 114, 115, 1, 3, 97, 100, 100, 0, 62, 9, 112, 114, 111, 100, 117, 99, 101, 114, 115, 1, 12, 112, 114, 111, 99, 101, 115, 115, 101, 100, 45, 98, 121, 1, 5, 99, 108, 97, 110, 103, 30, 57, 46, 48, 46, 48, 32, 40, 116, 97, 103, 115, 47, 82, 69, 76, 69, 65, 83, 69, 95, 57, 48, 48, 47, 102, 105, 110, 97, 108, 41], error: Utf8Error { valid_up_to: 43, error_len: Some(1) } }', src/libcore/result.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1188
  14: core::result::Result<T,E>::unwrap
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/result.rs:956
  15: deno::ops::compiler::op_fetch_source_files::{{closure}}::{{closure}}::{{closure}}
             at cli/ops/compiler.rs:151
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  17: <F as futures_core::future::TryFuture>::try_poll
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:83
  18: <futures_util::future::try_join_all::TryJoinAll<F> as core::future::future::Future>::poll
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/try_join_all.rs:145
  19: std::future::poll_with_tls_context
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  20: deno::ops::compiler::op_fetch_source_files::{{closure}}
             at cli/ops/compiler.rs:162
  21: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  22: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  23: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/chain.rs:44
  24: <futures_util::future::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/then.rs:44
  25: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  26: <F as futures_core::future::TryFuture>::try_poll
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:83
  27: <futures_util::future::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/try_future/map_ok.rs:45
  28: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  29: <F as futures_core::future::TryFuture>::try_poll
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:83
  30: <futures_util::future::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/try_future/map_ok.rs:45
  31: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  32: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/futures_unordered/mod.rs:544
  33: <&mut S as futures_core::stream::Stream>::poll_next
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:102
  34: <futures_util::stream::stream::fuse::Fuse<S> as futures_core::stream::Stream>::poll_next
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/stream/fuse.rs:85
  35: futures_util::stream::select::poll_inner
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/select.rs:115
  36: <futures_util::stream::select::Select<St1,St2> as futures_core::stream::Stream>::poll_next
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/select.rs:100
  37: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/stream/mod.rs:1184
  38: <deno_core::isolate::Isolate as core::future::future::Future>::poll
             at core/isolate.rs:518
  39: <alloc::boxed::Box<F> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/boxed.rs:1182
  40: futures_util::future::future::FutureExt::poll_unpin
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/mod.rs:507
  41: <deno_core::es_isolate::EsIsolate as core::future::future::Future>::poll
             at core/es_isolate.rs:521
  42: <alloc::boxed::Box<F> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/boxed.rs:1182
  43: futures_util::future::future::FutureExt::poll_unpin
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/mod.rs:507
  44: <deno::worker::Worker as core::future::future::Future>::poll
             at cli/worker.rs:184
  45: futures_util::future::future::FutureExt::poll_unpin
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/mod.rs:507
  46: <deno::web_worker::WebWorker as core::future::future::Future>::poll
             at cli/web_worker.rs:76
  47: futures_util::future::future::FutureExt::poll_unpin
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/mod.rs:507
  48: <deno::compilers::compiler_worker::CompilerWorker as core::future::future::Future>::poll
             at cli/compilers/compiler_worker.rs:65
  49: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/basic_scheduler.rs:138
  50: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:411
  51: tokio::runtime::context::enter
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/context.rs:72
  52: tokio::runtime::handle::Handle::enter
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/handle.rs:34
  53: tokio::runtime::Runtime::block_on
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:408
  54: deno::tokio_util::run_basic
             at cli/tokio_util.rs:18
  55: deno::compilers::ts::execute_in_thread::{{closure}}::{{closure}}
             at cli/compilers/ts.rs:614
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'Compiler didn't respond', src/libcore/option.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::option::expect_failed
             at src/libcore/option.rs:1188
  14: core::option::Option<T>::expect
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/option.rs:348
  15: deno::compilers::ts::execute_in_thread::{{closure}}
             at cli/compilers/ts.rs:618
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  17: std::future::poll_with_tls_context
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  18: deno::compilers::ts::TsCompiler::compile::{{closure}}
             at cli/compilers/ts.rs:381
  19: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  20: std::future::poll_with_tls_context
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  21: deno::global_state::GlobalState::fetch_compiled_module::{{closure}}
             at cli/global_state.rs:130
  22: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  23: std::future::poll_with_tls_context
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  24: <deno::state::State as deno_core::modules::ModuleLoader>::load::{{closure}}
             at cli/state.rs:211
  25: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  27: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  28: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/futures_unordered/mod.rs:544
  29: <S as futures_core::stream::TryStream>::try_poll_next
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:193
  30: futures_util::stream::try_stream::TryStreamExt::try_poll_next_unpin
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/try_stream/mod.rs:791
  31: <deno_core::modules::RecursiveModuleLoad as futures_core::stream::Stream>::poll_next
             at core/modules.rs:212
  32: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/stream/mod.rs:1184
  33: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/stream/next.rs:35
  34: std::future::poll_with_tls_context
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  35: deno_core::es_isolate::EsIsolate::load_module::{{closure}}
             at ./core/es_isolate.rs:497
  36: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  37: std::future::poll_with_tls_context
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  38: deno::worker::Worker::preload_module::{{closure}}
             at cli/worker.rs:146
  39: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  40: std::future::poll_with_tls_context
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  41: deno::worker::Worker::execute_module::{{closure}}
             at cli/worker.rs:154
  42: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  43: std::future::poll_with_tls_context
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  44: deno::run_command::{{closure}}
             at cli/lib.rs:355
  45: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  46: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  47: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/basic_scheduler.rs:138
  48: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:411
  49: tokio::runtime::context::enter
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/context.rs:72
  50: tokio::runtime::handle::Handle::enter
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/handle.rs:34
  51: tokio::runtime::Runtime::block_on
             at /home/abertron/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:408
  52: deno::tokio_util::run_basic
             at cli/tokio_util.rs:18
  53: deno::main
             at cli/lib.rs:486
  54: deno::main
             at cli/main.rs:4
  55: std::rt::lang_start::{{closure}}
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  56: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  57: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  58: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  59: std::panicking::try
             at src/libstd/panicking.rs:270
  60: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  61: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  62: std::rt::lang_start
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  63: main
  64: __libc_start_main
  65: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ry** [comment]
I can't repeat this failure. What OS are you on?

Is it possible your local repo has an old checkout? Have you looked at #3856 ?

**Comment by Nautigsam** [comment]
@ry This is specifically the wasm file introduced in #3856 that causes troubles:
```shell
$ iconv cli/tests/055_import_wasm_via_network.wasm 
asm
``p!Aiconv: illegal input sequence at position 43
```

**Comment by ry** [comment]
@Nautigsam Thanks - I've merged your PR.
