### ISSUE TITLE
flaky: unit test runner sometimes crashes on Windows

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#4373]
```
Running tests for: --allow-run --allow-env
running 1 tests
error: Uncaught ConnectionReset: An existing connection was forcibly closed by the remote host. (os error 10054) 
► $deno$/ops/dispatch_minimal.ts:63:11
    at ConnectionReset ($deno$/errors.ts:93:5)
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
```
https://github.com/denoland/deno/pull/4349/checks?check_run_id=507856283

It looks like this happens during running of `envCaseInsensitive` test, but happens only sometimes. Error suggests that TCP connection between parent and worker process is closed. I'm not sure what cases this failure.

**Comment by bartlomieju** [comment]
As a reference each subprocess that is spawned connects to TCP socket at `127.0.0.1:4100`

**Comment by ry** [comment]
Let's give this two days - if we can't figure out the cause, then I think we need to revert the test runner changes unfortunately.

**Comment by ry** [comment]
not yet fixed https://github.com/denoland/deno/runs/511787896

**Comment by ry** [comment]
happened again https://github.com/denoland/deno/runs/513693237

**Comment by dubiousjim** [comment]
I've encountered this a bunch of times over the past couple of days.

**Comment by ry** [comment]
Happened again https://github.com/denoland/deno/pull/4412/checks?check_run_id=515144958#step:19:942

**Comment by ry** [comment]
and again https://github.com/denoland/deno/pull/4416/checks?check_run_id=515520636 

(i'll stop updating.. it seems to be happening regularly)

**Comment by ry** [comment]
I caught some debug output in https://github.com/denoland/deno/runs/516691695

```
msg {"kind":"testStart","name":"runStderrOutput"}
test runStderrOutput ... msg {"kind":"testEnd","result":{"name":"runStderrOutput","duration":31,"status":"passed"}}
ok (31ms)
msg {"kind":"testStart","name":"runEnv"}
test runEnv ... msg {"kind":"testEnd","result":{"name":"runEnv","duration":31,"status":"passed"}}
ok (31ms)
error: Uncaught Error: Worker runner didn't report end
msg {"kind":"testStart","name":"runClose"}
► file:///D:/a/deno/deno/cli/js/tests/unit_test_runner.ts:166:11
test runClose ... msg {"kind":"testEnd","result":{"name":"runClose","duration":0,"status":"passed"}}

ok (0ms)
166     throw new Error("Worker runner didn't report end");
msg {"kind":"testStart","name":"signalPromiseTest"}
              ^
test signalPromiseTest ... msg {"kind":"testEnd","result":{"name":"signalPromiseTest","duration":0,"status":"skipped"}}

SKIPPED (0ms)
    at runTestsForPermissionSet (file:///D:/a/deno/deno/cli/js/tests/unit_test_runner.ts:166:11)
msg {"kind":"testStart","name":"signalShorthandsTest"}
test signalShorthandsTest ... msg {"kind":"testEnd","result":{"name":"signalShorthandsTest","duration":0,"status":"skipped"}}
SKIPPED (0ms)
test runner master ConnectionReset
test js_unit_tests ... FAILED
```
