### ISSUE TITLE
flaky test: netTcpListenClose

### ISSUE THREAD

**Issue by ry** [denoland/deno#4467]
https://github.com/denoland/deno/runs/527902802
```
failures:

netTcpListenClose
AddrInUse: Address already in use (os error 98)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.listen ($deno$/ops/net.ts:54:10)
    at Object.listen ($deno$/net.ts:168:22)
    at netTcpListenClose (file:///home/runner/work/deno/deno/cli/js/tests/net_test.ts:12:25)
    at asyncOpSanitizer ($deno$/testing.ts:29:11)
    at resourceSanitizer ($deno$/testing.ts:54:11)
    at TestApi.[Symbol.asyncIterator] ($deno$/testing.ts:222:17)
    at TestApi.next (<anonymous>)
    at Object.runTests ($deno$/testing.ts:396:20)
```

probably related to 60cee4f045778777a16b6fffd6d5b9a1400d7246

**Comment by ry** [comment]
Similar but probably related flakiness https://github.com/denoland/deno/runs/530755938

```
netTcpDialListen
AddrInUse: Address already in use (os error 98)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.listen ($deno$/ops/net.ts:50:10)
    at Object.listen ($deno$/net.ts:168:18)
    at netTcpDialListen (file:///home/runner/work/deno/deno/cli/js/tests/net_test.ts:163:25)
    at asyncOpSanitizer ($deno$/testing.ts:29:11)
    at resourceSanitizer ($deno$/testing.ts:54:11)
    at TestApi.[Symbol.asyncIterator] ($deno$/testing.ts:222:17)
    at TestApi.next (<anonymous>)
    at Object.runTests ($deno$/testing.ts:396:20)
```
