### ISSUE TITLE
deno doc crash

### ISSUE THREAD

**Issue by ondras** [denoland/deno#4523]
Version:
```sh
$ ~/deno/deno -V
deno 0.38.0
```

Crash:
```sh
$ ~/deno/deno doc test.ts
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/doc/printer.rs:381:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Source:
```js
$ cat test.ts
export function clamp(direction: number) {
	direction = direction % 4;
	return (direction >= 0 ? direction : direction + 4);
}
```

Backtrace:
```
$ RUST_BACKTRACE=full ~/deno/deno doc test.ts
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/doc/printer.rs:381:21
stack backtrace:
   0:     0x562674fcdeb4 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x562674fcdeb4 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x562674fcdeb4 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x562674fcdeb4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x562674ff6a0c - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x562674fc6307 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x562674fd0875 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x562674fd0875 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x562674fd0875 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x562674fd0561 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x562674fd0eda - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x562674fd0ac0 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x562674ff5521 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x562674ff546d - core::panicking::panic::hcdc9f0ba8d71d265
                               at src/libcore/panicking.rs:52
  14:     0x562673e450b7 - deno::doc::printer::format_signature::haa4f73c26537b779
  15:     0x562673e453e5 - deno::doc::printer::format_::h0acf5ae5945bf48a
  16:     0x562673e26759 - <std::future::GenFuture<T> as core::future::future::Future>::poll::h9ef7bffaecbac9cf
  17:     0x562673aaf0fc - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::he75c1efcc8f1a7e7
  18:     0x562673bac40d - tokio::runtime::context::enter::hab3ef43b32f2530e
  19:     0x562673e7ae65 - deno::tokio_util::run_basic::h2bacce0813974fd8
  20:     0x562673b31459 - deno::main::ha505de62e23897e8
  21:     0x562673a93943 - std::rt::lang_start::{{closure}}::h0607a1d30979f59e
  22:     0x562674fd09a3 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  23:     0x562674fd09a3 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  24:     0x562674fdce37 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  25:     0x562674fd1380 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  26:     0x562674fd1380 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  27:     0x562674fd1380 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  28:     0x562673a93932 - main
  29:     0x7faea5d621e3 - __libc_start_main
  30:     0x562673a937f9 - _start
  31:                0x0 - <unknown>
```

**Comment by ondras** [comment]
I wish I had a nonzero Rust experience/knowledge so I could aid more in debugging things like this :-(
