### ISSUE TITLE
typescript errors are printed twice during rollup

### ISSUE THREAD

**Issue by ry** [denoland/deno#459]
If you induce some typescript error, the build will fail (as expected) during the "bundle" step, but it will print the error message twice. Example:
```
~/src/deno> ./tools/build.py
DENO_BUILD_PATH: /Users/rld/src/deno/out/debug
[3/16] ACTION //:bundle(//build/toolchain/mac:clang_x64)
FAILED: gen/bundle/main.js gen/bundle/main.js.map
python ../../tools/run_node.py ./node_modules/rollup/bin/rollup -c ../../rollup.config.js -i ../../js/main.ts -o gen/bundle/main.js --silent --environment BASEPATH:../..
[!] (rpt2 plugin) Error: ../../js/deno.ts:4:26 - error TS2307: Cannot find module './dispatch'.

4 export { pub, sub } from "./dispatch";
                           ~~~~~~~~~~~~

../../js/deno.ts
Error: ../../js/deno.ts:4:26 - error TS2307: Cannot find module './dispatch'.

4 export { pub, sub } from "./dispatch";
                           ~~~~~~~~~~~~

    at error (/Users/rld/src/deno/third_party/node_modules/rollup/dist/rollup.js:3365:15)
    at Object.error (/Users/rld/src/deno/third_party/node_modules/rollup/dist/rollup.js:20727:13)
    at RollupContext.error (/Users/rld/src/deno/third_party/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:36:18)
    at lodash_2 (/Users/rld/src/deno/third_party/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:37:10)
    at arrayEach (/Users/rld/src/deno/third_party/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at forEach (/Users/rld/src/deno/third_party/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9342:14)
    at printDiagnostics (/Users/rld/src/deno/third_party/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/Users/rld/src/deno/third_party/node_modules/rollup-plugin-typescript2/src/index.ts:238:5)
    at /Users/rld/src/deno/third_party/node_modules/rollup/dist/rollup.js:20750:41
    at <anonymous>

ninja: build stopped: subcommand failed.
Error 1 ~/src/deno>
```
It would be nice if that error message was only displayed once.

cc @kitsonk

**Comment by kitsonk** [comment]
Not entirely sure what is going on and don't know if the plugin is causing the duplication or if that is just the _way_ rollup works.  Either way, opened: ezolenko/rollup-plugin-typescript2#103
