### ISSUE TITLE
Test case is leaking async ops. When using setInterval inside promise

### ISSUE THREAD

**Issue by bsunderhus** [denoland/deno#4591]
I don't know if this has to do with the PR #4209, but I got myself in the middle of a little bug during a test due to the usage of `setInterval` to create async cases inside a promise: 

```
Error: Test case is leaking async ops.
Before:
  - dispatched: 0
  - completed: 0
After: 
  - dispatched: 3
  - completed: 2
    at Object.assert ($deno$/util.ts:25:11)
    at asyncOpSanitizer ($deno$/testing.ts:35:5)
    at async resourceSanitizer ($deno$/testing.ts:54:5)
    at async TestApi.[Symbol.asyncIterator] ($deno$/testing.ts:222:11)
    at async Object.runTests ($deno$/testing.ts:398:20)
```

here's the code sample;
```ts
Deno.test(async function setIntervalTest() {
  let times = 0;
  await new Promise((resolve) => {
    const id = setInterval(() => {
      if (++times === 2) {
        clearInterval(id)
        resolve()
      }
    })
  })
  assertEquals(times, 2)
});
```
if I do the exact same behaviour but with `setTimeout` instead everything runs smoothly:

```ts
Deno.test(async function setTimeoutTest() {
  let times = 0;
  await new Promise((resolve) => {
    setTimeout(() => {
       if (++times === 2) {
         resolve()
       }
     })
     setTimeout(() => {
       if (++times === 2) {
         resolve()
       }
     })
  })
  assertEquals(times, 2)
});
```

**Comment by bartlomieju** [comment]
Hey @bsunderhus, thanks for report. This is actually false positive - I opened #4602 that fixes this problem.

**Comment by bsunderhus** [comment]
Thx for the quick response! I'll following #4602  then!
