### ISSUE TITLE
Clean up source maps in bundle

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#461]
The maps locations for sources that originate in the bundle are a bit ugly and confusing.  There are relative to the output path of the bundle.  It would be nice if they were cleaner and at least lopped off the `../../../../` and just output `/js/runtime.ts:114:5` for example or `$deno$/js/runtime.ts`:

```
$ ./out/debug/deno ./tests/008_stack_trace.ts
Error: exception from mod1
    at Object.throwsError (file:///Users/kkelly/github/deno/tests/subdir/mod1.ts:16:9)
    at foo (file:///Users/kkelly/github/deno/tests/008_stack_trace.ts:4:3)
    at eval (file:///Users/kkelly/github/deno/tests/008_stack_trace.ts:7:1)
    at localDefine (../../../../js/runtime.ts:157:5)
    at eval (/Users/kkelly/github/deno/tests/008_stack_trace.ts, <anonymous>)
    at eval (<anonymous>)
    at execute (../../../../js/runtime.ts:219:3)
    at FileModule.compileAndRun (../../../../js/runtime.ts:114:5)
    at denoMain (../../../../js/main.ts:56:7)
    at deno_main.js:1:1
```

**Comment by ry** [comment]
I agree!
