### ISSUE TITLE
error: Uncaught Error: Too many open files (os error 24)

### ISSUE THREAD

**Issue by crookse** [denoland/deno#4694]
With deno v0.40.0, was there a change to how many files could be opened? I'm running into the following error when compiling the docs for Drash:

```
  {
   filename: "creating_an_api",
   path: "deno-drash-website/docs/src/example_code/advanced_tutorials/creating_an_api"
  },
  ... 201 more items
]
error: Uncaught Error: Too many open files (os error 24)
► $deno$/ops/dispatch_json.ts:43:11
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at sendAsync ($deno$/ops/dispatch_json.ts:98:10)
```

The Drash project reads around 300+ files to compile JSON data for front-end usage with Vue. This worked with v0.39.0, but now it's running into the `too many open files` error. The code uses `Deno.readFileSync()` to open each file.

**Example Code:**

https://github.com/drashland/debug-too-many-files-open

**Zip File:**

https://github.com/drashland/debug-too-many-files-open/archive/master.zip

**Comment by crookse** [comment]
no longer an issue with deno v0.41.0
