### ISSUE TITLE
JSPM modules requiring NodeJS Buffer failing to work.

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#4721]
This is due to a sniff in jspm-core that tries to augment `__proto__` on `UInt8Array`, which fails since we removed `__proto__` for security reasons.

This issue is to track issue https://github.com/jspm/jspm-core/issues/2

**Comment by kitsonk** [comment]
(This was the PR that removed `__proto__`: https://github.com/denoland/deno/pull/4341)

**Comment by kitsonk** [comment]
JSPM are going to update their dependency on the Node.JS Buffer polyfill, which will resolve the issue.  It is expected over the next couple of days.

**Comment by lucacasonato** [comment]
For reference: https://github.com/jspm/jspm-core/issues/2

**Comment by kitsonk** [comment]
@lucacasonato also listed in the initial comment... 😉

**Comment by lucacasonato** [comment]
Whoops - it's getting late again :man_facepalming:

**Comment by kitsonk** [comment]
JSPM was updated with a more recent version of the Node.js Buffer polyfill that does not access `__proto__` and appears to have resolved the issue.

**Comment by hayd** [comment]
Is this expected to work for other libraries too, e.g. JSZip (using [this branch](https://github.com/hayd/deno-zip/tree/jspm)):

```
❱ deno test --allow-net
This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.
running 3 tests
test read ... error: Uncaught TypeError: buf.write is not a function
► https://dev.jspm.io/npm:@jspm/core@1.0.4/nodelibs/buffer.js:458:22

458     var actual = buf.write(string, encoding);
                         ^

    at fromString (https://dev.jspm.io/npm:@jspm/core@1.0.4/nodelibs/buffer.js:458:22)
    at from (https://dev.jspm.io/npm:@jspm/core@1.0.4/nodelibs/buffer.js:339:14)
    at Function.Buffer.from (https://dev.jspm.io/npm:@jspm/core@1.0.4/nodelibs/buffer.js:384:12)
    at Object.newBufferFrom (https://dev.jspm.io/npm:jszip@3.4.0/lib/nodejsUtils.dew.js:24:23)
    at Object.utf8encode (https://dev.jspm.io/npm:jszip@3.4.0/lib/utf8.dew.js:211:26)
    at Utf8EncodeWorker.processChunk (https://dev.jspm.io/npm:jszip@3.4.0/lib/utf8.dew.js:315:21)
    at DataWorker.<anonymous> (https://dev.jspm.io/npm:jszip@3.4.0/lib/stream/GenericWorker.dew.js:167:14)
    at DataWorker.emit (https://dev.jspm.io/npm:jszip@3.4.0/lib/stream/GenericWorker.dew.js:133:36)
    at DataWorker.push (https://dev.jspm.io/npm:jszip@3.4.0/lib/stream/GenericWorker.dew.js:52:12)
    at DataWorker._tick (https://dev.jspm.io/npm:jszip@3.4.0/lib/stream/DataWorker.dew.js:124:19)
```
