### ISSUE TITLE
Deno v0.41.0 regression: readAllSync returns zero bytes reading from stdin

### ISSUE THREAD

**Issue by srackham** [denoland/deno#4789]
`Deno.readAllSync(Deno.stdin)` always returns a zero length array, for example:

```
$ deno --version
deno 0.41.0
v8 8.2.308
typescript 3.8.3

$ echo Hello | deno eval "console.log(Deno.readAllSync(Deno.stdin))"
Uint8Array(0) []
```

I verified this behaviour on Ubuntu 18.04 and Windows 10.

The issue does does not occur in Deno v0.40.0

**Comment by ry** [comment]
Thanks for the report. Almost certainly introduced in #4762.

**Comment by ccheng** [comment]
hmm, this is probably related: `readSync` not allowed on `stdin`:

```
$ deno --version
deno 0.41.0
v8 8.2.308
typescript 3.8.3

$ deno eval "Deno.stdin.readSync(new Uint8Array(1000))"
error: Uncaught TypeError: sync read not allowed on this resource  
► $deno$/ops/dispatch_minimal.ts:63:11
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendSyncMinimal ($deno$/ops/dispatch_minimal.ts:118:10)
    at Object.readSync ($deno$/ops/io.ts:20:17)
    at File.readSync ($deno$/files.ts:101:12)
```

I verified this `readSync` and the `readAllSync` behaviours on Ubuntu 19.10 and Mac 10.12, and that they did not occur in Deno v0.40.0.

Although this `readSync` issue didn't occur in Deno v0.40.0, I was encountering a problem where if `Deno.stdin.readSync` was called about 55-ish times, Deno freezes using 100% CPU...

**Comment by ccheng** [comment]
So I tested in Deno v0.39.0, and found `Deno.stdin.readSync` works correctly.

I mentioned that in Deno v0.40.0, if `Deno.stdin.readSync` was called about 55-ish times, Deno freezes using 100% CPU.  And in v0.41.0, it throws a `Uncaught TypeError: sync read not allowed on this resource`.

I'm only guessing the `readSync` and `readAllSync` issues are related.  If it's not, I can open a new issue for it.  Thanks!

**Comment by SyrupThinker** [comment]
https://github.com/denoland/deno/blob/93c21646739a46a9710be9d580256e18bee740c0/cli/js/buffer.ts#L180-L192

@bartlomieju What is the reason for suppressing exceptions here?
Currently is masks the `TypeError: sync read not allowed on this resource`
error when synchronously reading on stdin.

**Comment by bartlomieju** [comment]
@SyrupThinker I'm not sure, please open a separate issue for that, seems like a bug.
