### ISSUE TITLE
Failed to fetch file `chromium-gn` issue

### ISSUE THREAD

**Issue by are1000** [denoland/deno#490]
This may be a very obvious issue, but I cannot get `./build/setup.py` to work. It throws this:

```
0> Failed to fetch file gs://chromium-gn/f08024240631f4974bb924b2f05712df185263ea for /Users/are/.bin/lib/deno/third_party/v8/buildtools/mac/gn, skipping. [Err: Traceback (most recent call last):
  File "/Users/are/.bin/lib/deno/third_party/depot_tools/gsutil.py", line 182, in <module>
    sys.exit(main())
  File "/Users/are/.bin/lib/deno/third_party/depot_tools/gsutil.py", line 179, in main
    clean=args.clean)
  File "/Users/are/.bin/lib/deno/third_party/depot_tools/gsutil.py", line 128, in run_gsutil
    gsutil_bin = ensure_gsutil(force_version, target, clean)
  File "/Users/are/.bin/lib/deno/third_party/depot_tools/gsutil.py", line 107, in ensure_gsutil
    target_zip_filename = download_gsutil(version, instance_dir)
  File "/Users/are/.bin/lib/deno/third_party/depot_tools/gsutil.py", line 65, in download_gsutil
    u = urllib2.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
]
Failed to fetch file gs://chromium-gn/f08024240631f4974bb924b2f05712df185263ea for /Users/are/.bin/lib/deno/third_party/v8/buildtools/mac/gn. [Err: Traceback (most recent call last):
  File "/Users/are/.bin/lib/deno/third_party/depot_tools/gsutil.py", line 182, in <module>
    sys.exit(main())
  File "/Users/are/.bin/lib/deno/third_party/depot_tools/gsutil.py", line 179, in main
    clean=args.clean)
  File "/Users/are/.bin/lib/deno/third_party/depot_tools/gsutil.py", line 128, in run_gsutil
    gsutil_bin = ensure_gsutil(force_version, target, clean)
  File "/Users/are/.bin/lib/deno/third_party/depot_tools/gsutil.py", line 107, in ensure_gsutil
    target_zip_filename = download_gsutil(version, instance_dir)
  File "/Users/are/.bin/lib/deno/third_party/depot_tools/gsutil.py", line 65, in download_gsutil
    u = urllib2.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
]
```

```
deno on  master is 📦 ⚠ via ⬢ v8.11.2 via 𝗥 v1.27.1
➜ python --version
Python 2.7.15
➜ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
```

I am more than happy to provide additional info if needed. Any help appreciated!

**Comment by bartlomieju** [comment]
I think it's out-of-date. Please try with latest release. 

CC @ry
