### ISSUE TITLE
Whitelisting example in manual does not work

### ISSUE THREAD

**Issue by David-Else** [denoland/deno#4921]
OK:
```shell
deno --allow-read=/usr https://deno.land/std/examples/cat.ts /etc/passwd
error: Uncaught PermissionDenied: read access to "/etc/passwd", run again with the --allow-read flag
► $deno$/ops/dispatch_json.ts:43:11
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async Object.open ($deno$/files.ts:65:15)
    at async https://deno.land/std/examples/cat.ts:4:16
```
BUG:
```shell
$ deno --allow-read=/etc https://deno.land/std/examples/cat.ts /etc/passwd
# (nothing happens until you press return)

error: Uncaught Error: Bad file descriptor (os error 9)
► $deno$/ops/dispatch_minimal.ts:63:11
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.write ($deno$/ops/io.ts:66:18)
    at async Object.copy ($deno$/io.ts:81:12)
    at async https://deno.land/std/examples/cat.ts:5:3
```
```shell
$cat /etc/passwd
# works fine
```
```
deno --version
deno 0.41.0
v8 8.2.308
typescript 3.8.3
```
Using Cenos 8.1

**Comment by disizali** [comment]
I reproduce this issue whit the last compiled version of deno from HEAD of the master branch, 
`no problem`!
and of course, if I change cat.ts
```typescript
//from
Deno.copy(file, Deno.stdout);
//to
Deno.copy(Deno.stdout,file);
```
it'll be ok with installed deno version on my system and yours ( v0.41.0)

I think its because of changes in #4885 into cat.ts file, before landing in deno [and will be ok with next version without any changes]

but how to handle and showing error [  Bad file descriptor ], it's out of this conversation.

**Comment by ry** [comment]
Use https://deno.land/std@v0.41.0/examples/cat.ts

we're making a lot of last minute API changes on master branch.
