### ISSUE TITLE
Reqeusting net permission with a url without protocol panics

### ISSUE THREAD

**Issue by dyladan** [denoland/deno#4969]
If permissions are requested on a url which does not have a proto specified, the runtime panics. It looks like the error is in `cli/permissions.rs`:

https://github.com/denoland/deno/blob/76ee6fb335f2ad779402e746d81c72f6c87614d9/cli/permissions.rs#L171-L184

It looks to me like the proto is thrown away anyway, but the use of `URL::parse` means that something with only a host and port is not properly parsed. As a solution, I would suggest allowing users to either continue to use the `url` as they currently can, but also offer a `{ host: string; port: number }` option to the interface.

### Simple reproduction:

```typescript
await Deno.permissions.request(
    { name: "net", url: "localhost:35242" },
);
```

```sh
$ deno repro.ts 
Compile file:///[...elided]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/permissions.rs:182:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    86239 abort      deno repro.ts
```

### Workaround

Adding anything for the protocol causes parsing to succeed.

```typescript
await Deno.permissions.request(
    { name: "net", url: "my-service://localhost:35242" },
);
```

### With backtrace:
```sh
$ RUST_BACKTRACE=1 deno repro.ts
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/permissions.rs:182:41
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: deno::permissions::DenoPermissions::get_state_net_url
  10: deno::permissions::DenoPermissions::request_net
  11: deno::ops::permissions::op_request_permission
  12: deno::state::State::core_op::{{closure}}
  13: deno_core::ops::OpRegistry::call
  14: deno_core::isolate::Isolate::dispatch_op
  15: deno_core::bindings::send
  16: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
  17: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  18: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  19: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
[1]    87069 abort      RUST_BACKTRACE=1 deno repro.ts
```

### With full backtrace:
```sh
RUST_BACKTRACE=full deno repro.ts         
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/permissions.rs:182:41
stack backtrace:
   0:        0x110017fb5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
   1:        0x11003eabd - core::fmt::write::hd42cb3dea57bae40
   2:        0x11001006b - std::io::Write::write_fmt::ha39f6009af02b1d2
   3:        0x11001a4fa - std::panicking::default_hook::{{closure}}::h389f076017b5df43
   4:        0x11001a1fa - std::panicking::default_hook::h04b06ec20c41bf02
   5:        0x11001ab4d - std::panicking::rust_panic_with_hook::hccde7faed9a5c398
   6:        0x11001a712 - rust_begin_unwind
   7:        0x110064ccf - core::panicking::panic_fmt::h272b9afd5b7b725a
   8:        0x110064c27 - core::panicking::panic::h8627f9662a331d41
   9:        0x10eea6263 - deno::permissions::DenoPermissions::get_state_net_url::h6035cc8eb9dbbe0f
  10:        0x10eea69bf - deno::permissions::DenoPermissions::request_net::ha3d7390ecbd8b296
  11:        0x10ece49bd - deno::ops::permissions::op_request_permission::hc07c1fb2227c6411
  12:        0x10ed53441 - deno::state::State::core_op::{{closure}}::ha06894f58039d3cb
  13:        0x10f495370 - deno_core::ops::OpRegistry::call::hb1e4977de87486c5
  14:        0x10f49b1ad - deno_core::isolate::Isolate::dispatch_op::h1e6ac889cb5eabcc
  15:        0x10f481728 - deno_core::bindings::send::hdd6343e740bee9d2
  16:        0x10f48818d - <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn::hcba4fa5587bb0723
  17:        0x10f513eaf - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  18:        0x10f5133c1 - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  19:        0x10f512a31 - _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
fatal runtime error: failed to initiate panic, error 5
[1]    87194 abort      RUST_BACKTRACE=full deno repro.ts
```

**Comment by Spoonbender** [comment]
I'd like to tackle this issue

**Comment by Spoonbender** [comment]
I'd like to first try and get rid of the panic, regardless of whether we expand the interface.

The complexity originates from the way Rust parses the url "`ocalhost:35242` - it considers it a valid url which has no host, and considers `localhost` to be the scheme (proto), similar to what you'd expect parsing `mailto:someone@something.com`.

At first I though we should just ensure the parsed url has a host, like we do at `check_net_url`.
However, adding this check yields an obscure result: if the user passes "localhost:443" as the input, they get a "missing host" error, which can be very confusing since the user did provide a host (as they understand it).

IMO better approach is to use the `cannot_be_a_base()` function, and throw an error aiming the user at the right format: `invalid url, expected format: <scheme>://<host>:[port][/subpath]`.

Another option is to implicitly add a dummy scheme for urls like "localhost:35242", but that seems too dangerous and breaking.

The following rust program exemplifies the issue:
```rust
use url::*;

fn main() {
    test("localhost");
    test("localhost:235");
    test("http://localhost");
    test("http://localhost:235");
    test("127.0.0.1");
    test("127.0.0.1:235");
    test("http://127.0.0.1");
    test("http://127.0.0.1:235");
    test("mailto:someone@something.com");
    test("data:text/plain");
    test("http://");
    test("2001:db8::8a2e:370:7334");
    test("[2001:db8::8a2e:370:7334]:80");
    test("http://[2001:db8::8a2e:370:7334]:80");
}

fn test(url: &str) {
    match inner_test(url) {
        Ok(res) => println!("INPUT {} RESULT = OK {}", url, res),
        Err(e) => println!("INPUT {} RESULT = ERROR {}", url, e),
    }
}

fn inner_test(url: &str) -> Result<String, url::ParseError> {
    let parsed = Url::parse(url)?;
    let host = parsed.host();
    let port = parsed.port();
    let scheme = parsed.scheme();
    let cannot_be_a_base = parsed.cannot_be_a_base();

    let res = format!(
        "INPUT {} host = {:?} port = {:?} scheme = {:?} cannot_be_a_base = {:?}",
        url, host, port, scheme, cannot_be_a_base
    );
    Ok(res)
}
```
output:
```
INPUT localhost RESULT = ERROR relative URL without a base
INPUT localhost:235 RESULT = OK INPUT localhost:235 host = None port = None scheme = "localhost" cannot_be_a_base = true
INPUT http://localhost RESULT = OK INPUT http://localhost host = Some(Domain("localhost")) port = None scheme = "http" cannot_be_a_base = false
INPUT http://localhost:235 RESULT = OK INPUT http://localhost:235 host = Some(Domain("localhost")) port = Some(235) scheme = "http" cannot_be_a_base = false
INPUT 127.0.0.1 RESULT = ERROR relative URL without a base
INPUT 127.0.0.1:235 RESULT = ERROR relative URL without a base
INPUT http://127.0.0.1 RESULT = OK INPUT http://127.0.0.1 host = Some(Ipv4(127.0.0.1)) port = None scheme = "http" cannot_be_a_base = false
INPUT http://127.0.0.1:235 RESULT = OK INPUT http://127.0.0.1:235 host = Some(Ipv4(127.0.0.1)) port = Some(235) scheme = "http" cannot_be_a_base = false
INPUT mailto:someone@something.com RESULT = OK INPUT mailto:someone@something.com host = None port = None scheme = "mailto" cannot_be_a_base = true
INPUT data:text/plain RESULT = OK INPUT data:text/plain host = None port = None scheme = "data" cannot_be_a_base = true
INPUT http:// RESULT = ERROR empty host
INPUT 2001:db8::8a2e:370:7334 RESULT = ERROR relative URL without a base
INPUT [2001:db8::8a2e:370:7334]:80 RESULT = ERROR relative URL without a base
INPUT http://[2001:db8::8a2e:370:7334]:80 RESULT = OK INPUT http://[2001:db8::8a2e:370:7334]:80 host = Some(Ipv6(2001:db8::8a2e:370:7334)) port = None scheme = "http" cannot_be_a_base = false
```

**Comment by bartlomieju** [comment]
@Spoonbender proposed solution sounds good 👍  as long as it doesn't panic and provides a useful error message it's an improvement. Feel free to open a PR!

**Comment by dyladan** [comment]
I would also make sure to document the fact that a scheme is required, with a suggestion what to do if (like me) you are using a custom protocol that does not have an obvious or pre-defined scheme.

**Comment by Spoonbender** [comment]
@dyladan I'll make sure to do that! 
BTW, can you explain your scenario: what custom protocol are you using?

**Comment by dyladan** [comment]
In the case that caused me to open this bug it was actually IRC protocol (a very simple line protocol if you're not familiar), but in general I think it is not safe to assume that users will be using a premade protocol. For instance, in the past I have used a custom binary protocol to gather precise low-latency telemetry data from a drone for remote piloting (I admit I was not using and would likely not use something like deno for that particular use case).
