### ISSUE TITLE
Running Example Complex Application Errors

### ISSUE THREAD

**Issue by Smithx10** [denoland/deno#5019]
Installed Deno Via 
```
curl -fsSL https://deno.land/x/install/install.sh | sh
```

Version
```
~/g/my-deno ❯❯❯ deno --version                                                                                                                         
deno 0.42.0
v8 8.2.308
typescript 3.8.3
```

Example taken from https://deno.land/
```
~/g/my-deno ❯❯❯ cat index.ts
import {serve} from "https://deno.land/std@v0.36.0/http/server.ts";
const s = serve({port: 8000});
console.log("http://localhost:8000/");
for await (const req of s) {
        req.respond({body: "Hello World\n"});
}
```

Error:
```
~/g/my-deno ❯❯❯ deno index.ts                                                                                                                          ✘ 130
Compile file:///home/smith/git/my-deno/index.ts
error TS2694: Namespace 'Deno' has no exported member 'EOF'.
    async read(_: Uint8Array): Promise<number | Deno.EOF> {
                                                     ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:10:54

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:11:19

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async function read(buf: Uint8Array): Promise<number | Deno.EOF> {
                                                              ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:19:63

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (finished) return Deno.EOF;
                              ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:20:31

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
    let result: number | Deno.EOF;
                              ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:21:31

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (result !== Deno.EOF) {
                        ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:29:25

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async function read(buf: Uint8Array): Promise<number | Deno.EOF> {
                                                              ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:46:63

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (finished) return Deno.EOF;
                              ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:47:31

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
        if ((await tp.readLine()) === Deno.EOF) {
                                           ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:59:44

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (line === Deno.EOF) throw new UnexpectedEOFError();
                      ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:66:23

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
        if (eof === Deno.EOF) {
                         ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:76:26

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
        if (eof === Deno.EOF) {
                         ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:81:26

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
        if (eof === Deno.EOF) {
                         ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:93:26

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
        if ((await tp.readLine()) === Deno.EOF) {
                                           ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:97:44

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      if ((await r.readLine()) === Deno.EOF) {
                                        ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:105:41

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:110:19

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
  assert(result != Deno.EOF, "trailer must be set");
                        ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:134:25

error TS2339: Property 'toAsyncIterator' does not exist on type 'typeof Deno'.
  for await (const chunk of Deno.toAsyncIterator(r)) {
                                 ~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.36.0/http/io.ts:167:34

error TS2345: Argument of type 'BufWriter' is not assignable to parameter of type 'Reader'.
  Property 'read' is missing in type 'BufWriter' but required in type 'Reader'.
    const n = await Deno.copy(writer, r.body);
                              ~~~~~~
    at https://deno.land/std@v0.36.0/http/io.ts:276:31

    'read' is declared here.
        read(p: Uint8Array): Promise<number | null>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at $asset$/lib.deno.ns.d.ts:398:5

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
): Promise<ServerRequest | Deno.EOF> {
                                ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:346:33

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
  if (firstLine === Deno.EOF) return Deno.EOF;
                         ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:349:26

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
  if (firstLine === Deno.EOF) return Deno.EOF;
                                          ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:349:43

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
  if (headers === Deno.EOF) throw new UnexpectedEOFError();
                       ~~~
    at https://deno.land/std@v0.36.0/http/io.ts:351:24

error TS2339: Property 'listenTLS' does not exist on type 'typeof Deno'.
const { listen, listenTLS } = Deno;
                ~~~~~~~~~
    at https://deno.land/std@v0.36.0/http/server.ts:16:17

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    while ((await body.read(buf)) !== Deno.EOF) {}
                                           ~~~
    at https://deno.land/std@v0.36.0/http/server.ts:120:44

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
    let req: ServerRequest | Deno.EOF | undefined;
                                  ~~~
    at https://deno.land/std@v0.36.0/http/server.ts:141:35

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      if (req === Deno.EOF) {
                       ~~~
    at https://deno.land/std@v0.36.0/http/server.ts:151:24

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (req === Deno.EOF) {
                     ~~~
    at https://deno.land/std@v0.36.0/http/server.ts:171:22

error TS2694: Namespace 'Deno' has no exported member 'ListenTLSOptions'.
export type HTTPSOptions = Omit<Deno.ListenTLSOptions, "transport">;
                                     ~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.36.0/http/server.ts:258:38

error TS2694: Namespace 'Deno' has no exported member 'ListenTLSOptions'.
  const tlsOptions: Deno.ListenTLSOptions = {
                         ~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.36.0/http/server.ts:278:26

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      if (rr === Deno.EOF) {
                      ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:85:23

error TS2531: Object is possibly 'null'.
      assert(rr >= 0, "negative read");
             ~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:89:14

error TS2531: Object is possibly 'null'.
      this.w += rr;
                ~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:90:17

error TS2531: Object is possibly 'null'.
      if (rr > 0) {
          ~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:91:11

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async read(p: Uint8Array): Promise<number | Deno.EOF> {
                                                   ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:122:52

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
    let rr: number | Deno.EOF = p.byteLength;
                          ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:123:27

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
        const nread = rr === Deno.EOF ? 0 : rr;
                                  ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:131:35

error TS2531: Object is possibly 'null'.
        assert(nread >= 0, "negative read");
               ~~~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:132:16

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      if (rr === 0 || rr === Deno.EOF) return rr;
                                  ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:145:35

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async readFull(p: Uint8Array): Promise<Uint8Array | Deno.EOF> {
                                                           ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:172:60

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
        if (rr === Deno.EOF) {
                        ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:177:25

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
            return Deno.EOF;
                        ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:179:25

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async readByte(): Promise<number | Deno.EOF> {
                                          ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:194:43

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      if (this.eof) return Deno.EOF;
                                ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:196:33

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async readString(delim: string): Promise<string | Deno.EOF> {
                                                         ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:214:58

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buffer == Deno.EOF) return Deno.EOF;
                       ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:218:24

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buffer == Deno.EOF) return Deno.EOF;
                                        ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:218:41

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async readLine(): Promise<ReadLineResult | Deno.EOF> {
                                                  ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:244:51

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
    let line: Uint8Array | Deno.EOF;
                                ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:245:33

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (line === Deno.EOF) {
                      ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:278:23

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:279:19

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async readSlice(delim: number): Promise<Uint8Array | Deno.EOF> {
                                                            ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:312:61

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
          return Deno.EOF;
                      ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:329:23

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async peek(n: number): Promise<Uint8Array | Deno.EOF> {
                                                   ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:374:52

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:391:19

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (result === Deno.EOF) {
                        ~~~
    at https://deno.land/std@v0.36.0/io/bufio.ts:550:25

error TS2345: Argument of type '"a"' is not assignable to parameter of type 'OpenOptions | undefined'.
  const file = await open(filepath, "a");
                                    ~~~
    at https://deno.land/std@v0.36.0/io/util.ts:44:37

error TS2367: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
export const isWindows = build.os === "win";
                         ~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.36.0/path/constants.ts:51:26

error TS2367: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
const isWin = Deno.build.os === "win";
              ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.36.0/path/globrex.ts:5:15

error TS2349: This expression is not callable.
  Type '{ get(key: string): string | undefined; set(key: string, value: string): void; toObject(): { [index: string]: string; }; }' has no call signatures.
      path = env()[`=${resolvedDevice}`] || cwd();
             ~~~
    at https://deno.land/std@v0.36.0/path/win32.ts:42:14

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
export function assertNotEOF<T extends {}>(val: T | Deno.EOF): T {
                                                         ~~~
    at https://deno.land/std@v0.36.0/testing/asserts.ts:382:58

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
  assertNotEquals(val, Deno.EOF);
                            ~~~
    at https://deno.land/std@v0.36.0/testing/asserts.ts:383:29

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async readLine(): Promise<string | Deno.EOF> {
                                          ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:42:43

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (s === Deno.EOF) return Deno.EOF;
                   ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:44:20

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (s === Deno.EOF) return Deno.EOF;
                                    ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:44:37

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async readMIMEHeader(): Promise<Headers | Deno.EOF> {
                                                 ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:68:50

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buf === Deno.EOF) {
                     ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:74:22

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:75:19

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buf === Deno.EOF) {
                     ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:81:22

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      if (kv === Deno.EOF) throw new UnexpectedEOFError();
                      ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:91:23

error TS2694: Namespace 'Deno' has no exported member 'EOF'.
  async readLineSlice(): Promise<Uint8Array | Deno.EOF> {
                                                   ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:136:52

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      if (r === Deno.EOF) return Deno.EOF;
                     ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:141:22

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
      if (r === Deno.EOF) return Deno.EOF;
                                      ~~~
    at https://deno.land/std@v0.36.0/textproto/mod.ts:141:39

Found 73 errors.

```

**Comment by bartlomieju** [comment]
Update your dependency on `std` to latest version:
```
https://deno.land/std@v0.36.0/http/server.ts
-> 
https://deno.land/std@0.42.0/http/server.ts
```

**Comment by magnattic** [comment]
Not sure if this is the right repo for that, but this should really be fixed in the code example on https://deno.land/. I had the same issue and I suspect this will throw off a lot of newcomers.
