### ISSUE TITLE
Std syntax error

### ISSUE THREAD

**Issue by asins** [denoland/deno#5064]
The Deno version was updated yesterday, and the std version was modified today, but there are still errors.

Referenced in my code is version 0.32.0
```js
import { resolve, extname } from "https://deno.land/std@v0.32.0/path/mod.ts
```

But I see that in the latest code in git, the logic of isWindows is already correct, does the std version need to be updated? (`build.os === "windows"`)

```
error TS2367: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
export const isWindows = build.os === "win";
                         ~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.32.0/path/constants.ts:51:26

error TS2339: Property 'DenoError' does not exist on type 'typeof Deno'.
const { DenoError, ErrorKind } = Deno;
        ~~~~~~~~~
    at https://deno.land/std@v0.32.0/path/glob.ts:4:9

error TS2339: Property 'ErrorKind' does not exist on type 'typeof Deno'.
const { DenoError, ErrorKind } = Deno;
                   ~~~~~~~~~
    at https://deno.land/std@v0.32.0/path/glob.ts:4:20

error TS2367: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
const isWin = Deno.build.os === "win";
              ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.32.0/path/globrex.ts:5:15

error TS2349: This expression is not callable.
  Type '{ get(key: string): string | undefined; set(key: string, value: string): void; toObject(): { [index: string]: string; }; }' has no call signatures.
      path = env()[`=${resolvedDevice}`] || cwd();
             ~~~
    at https://deno.land/std@v0.32.0/path/win32.ts:41:14
```

**Comment by asins** [comment]
This is my fault, the correct one should be:

```
https://deno.land/std@v0.42.0/path/mod.ts
```
