### ISSUE TITLE
Report original file and line for unsupported scheme when compiling

### ISSUE THREAD

**Issue by dstaley** [denoland/deno#5080]
One of my source files mistakenly had the following import:

`import { HelloResponse } from "c:/Users/Dylan/Desktop/kinto-http.deno.ts/kinto-http/types";`

When compiling, the following error was given:

```
Compile file:///C:/Users/Dylan/Desktop/kinto-http.deno.ts/test.ts
error: Uncaught Error: Unsupported scheme "c" for module "c:/Users/Dylan/Desktop/kinto-http.deno.ts/kinto-http/types". Supported schemes: [
    "http",
    "https",
    "file",
]
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async processImports ($deno$/compiler/imports.ts:117:23)
    at async processImports ($deno$/compiler/imports.ts:125:7)
    at async processImports ($deno$/compiler/imports.ts:125:7)
    at async processImports ($deno$/compiler/imports.ts:125:7)
    at async Object.processImports ($deno$/compiler/imports.ts:125:7)
    at async compile (file:///D:/a/deno/deno/cli/js/compiler.ts:144:31)
    at async tsCompilerOnMessage (file:///D:/a/deno/deno/cli/js/compiler.ts:359:22)
    at async workerMessageRecvCallback ($deno$/runtime_worker.ts:73:9)
```

It would have been really nice if Deno had reported the original filename and line number containing the invalid import instead of just reporting the filename being executed.

**Comment by drodsou** [comment]
I did not find info about not being able to use "C:/somedir/..." in Deno imports on Windows. Is this a bug or some expected behaviour?
