### ISSUE TITLE
Regression in exception stack handling

### ISSUE THREAD

**Issue by alexjeffburke** [denoland/deno#5127]
Hi there,

I'm trying to restore Unexpected support for deno 1.0. The most immediate issue is what looks like a regression in exception handling to do with stack traces - if you run execute `make test-deno` in the Unexpected branch `deno-v1-support` (https://github.com/unexpectedjs/unexpected/tree/deno-v1-support) it quickly dies with:

```
error: Uncaught TypeError: Cannot redefine property: __callSiteEvals
    at Function.defineProperties (<anonymous>)
    at Function.prepareStackTrace ($deno$/error_stack.ts:221:10)
    at Function.getOwnPropertyDescriptor (<anonymous>)
    at Object.propertyIsWritable (file:///some/path/unexpected/unexpected.esm.js:105:17361)
    at Gt (file:///some/path/unexpected/unexpected.esm.js:105:19389)
    at Object.Xt [as ensureErrorObject] (file:///some/path/unexpected/unexpected.esm.js:105:19465)
    at w._rejectCallback (file:///some/path/unexpected/unexpected.esm.js:105:64548)
    at w._settlePromiseFromHandler (file:///some/path/unexpected/unexpected.esm.js:105:65199)
    at w._settlePromiseAt (file:///some/path/unexpected/unexpected.esm.js:105:66370)
    at w._settlePromises (file:///some/path/unexpected/unexpected.esm.js:105:68217)
    at le._drainQueue (file:///some/path/unexpected/unexpected.esm.js:105:25498)
    at le._drainQueues (file:///some/path/unexpected/unexpected.esm.js:105:25560)
    at drainQueues (file:///some/path/unexpected/unexpected.esm.js:105:23830)
    at file:///some/path/unexpected/unexpected.esm.js:105:86829
    at Array.forEach (<anonymous>)
    at Object.drain (file:///some/path/unexpected/unexpected.esm.js:105:86808)
```

If there's anything else I can provide please let me know.

Thanks, Alex J Burke.

**Comment by nayeemrmn** [comment]
@alexjeffburke Is Unexpected also using the `__callSiteEvals` key for something? Or did you somehow get the `prepareStackTrace()` callback to run twice? This is very interesting.

**Comment by alexjeffburke** [comment]
@nayeemrmn I don't think we've done anything special here except throw exceptions/rejections - that call to prepareStackTrace is happening inside internal deno code from what I can tell and there are no occurrences of calling that function in our tree.

**Comment by alexjeffburke** [comment]
Is there anything else that I can provide here?

**Comment by nayeemrmn** [comment]
@alexjeffburke Sorry for the wait. We currently use V8's [`prepareStackTrace()` API](https://v8.dev/docs/stack-trace-api#customizing-stack-traces) for internal purposes. As long as you're not also using this API for something, I don't know why this could be happening but maybe we can just make our callback safer by not trying to write `__callSiteEvals` if it's already defined.

What we'll probably do, regardless, is open up this API to users by re-implementing it with our internal behaviour as a proxy. This should be fixed in the process.

Could you provide a bit of code or a shell command for quick reproduction? Thanks.

**Comment by alexjeffburke** [comment]
@nayeemrmn no worries, was just me being keen to try to have Unexpected work with 1.0 :)

Should be reproduceable as follows:

- git checkout git@github.com:unexpectedjs/unexpected.git
- cd unexpected && git checkout deno-v1-support && npm install
- make test-deno
