### ISSUE TITLE
Different errors with `--allow-net`

### ISSUE THREAD

**Issue by bin0x00** [denoland/deno#5240]
When trying to use `--allow-net` with an URL that's doesn't exists I get three different errors(tested on macOS):
```bash
Macbook-Pro-2015 :: ~/git » deno --allow-net="http://z/" test.js
Does compile
error: Uncaught PermissionDenied: network access to "http://z/", run again with the --allow-net flag
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async fetch ($deno$/web/fetch.ts:591:27)
Macbook-Pro-2015 :: ~/git » deno --allow-net "http://z/" test.js
Download http://z/
error sending request for url (http://z/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
Macbook-Pro-2015 :: ~/git » deno --allow-net="z" test.js        
Does compile
error: Uncaught Http: error sending request for url (http://z/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async fetch ($deno$/web/fetch.ts:591:27)
```

My `test.js`:

```javascript
console.log('Does compile')
fetch('http://z/').then( (resp) => {
    console.log(resp)
} )
```

Now the first and the second one does seem to be intended, when using `--allow-net` with an `=`, will allow an domain name to be used in the code, but when I write the whole URL it wont allow me to access the file, while in the other hand using` --allow-net` without an `=` and only a ` ` it does allow me to use the file but an error happens because I dident put a proper URL in it(just a quick note if you where to run this your self it would also show no error color on the second command, in which `fetch` is giving an error).

Lastly the second and the third error seems to be quite related, the difference is the second one doesn't give me as much info as the third one, I am not sure if that's intended.

Thanks,
Dex Devlon

**Comment by bin0x00** [comment]
I will recreate my issue
