### ISSUE TITLE
Better error message when bad filename is loaded

### ISSUE THREAD

**Issue by ry** [denoland/deno#526]
Currently the output looks like this

```
> ./out/release/deno badfile
TypeError: Cannot read property 'compileAndRun' of null
    at denoMain (deno/js/main.ts:90:7)
    at deno_main.js:1:1
```

It should look something like this:
```
> ./out/release/deno badfile
DoesNotExist: Cannot read file "badfile"
    at [frame]
    at [frame]
```

The proper fix forwards the error from rust. But I'll accept hacky solutions too as long as they include a TODO for the proper fix.

**Comment by kitsonk** [comment]
@ry currently in #518 it now outputs:

```
$ ./out/debug/deno foo.ts
Error: Cannot resolve module "foo.ts" from "/Users/kkelly/github/deno/".
    at assert (deno/js/util.ts:20:11)
    at DenoCompiler.run (deno/js/compiler.ts:316:5)
    at denoMain (deno/js/main.ts:77:12)
    at deno_main.js:1:1
```

**Comment by ry** [comment]
awesome!
