### ISSUE TITLE
Address parsing in http serve() does not work with IPv6

### ISSUE THREAD

**Issue by Raqbit** [denoland/deno#5261]
## Description

When specifying a string address as parameter to `serve()`, the following logic is used to extract the hostname/IP and the port to listen on.

```ts
const [hostname, port] = addr.split(":");
addr = { hostname, port: Number(port) };
```

(https://deno.land/std@0.50.0/http/server.ts, line 257)

When this is done with an IPv6 address, like localhost (`[::1]:8080`) or if you want to listen on all addresses (`[::]:8080`), this parsing will break.

## Repro snippet

The following snippet:

```ts
import { serve } from "https://deno.land/std@0.50.0/http/server.ts";

// Listen on port 8080 on all addresses
const s = serve("[::]:8080");
for await (const req of s) {
  req.respond({ body: `Hello IPv6` });
}
```
will produce this error:

```
error: Uncaught Error: failed to lookup address information: Name or service not known
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.listen ($deno$/ops/net.ts:51:10)
    at listen ($deno$/net.ts:152:22)
    at serve (server.ts:261:20)
    at server.ts:3:11
```

which can be explained because:

```ts
let [hostname, port] = "[::]:8080".split(":")
port = Number(port)
// hostname === "["
// port === 0
```
## Workaround
A workaround is to pass `HTTPOptions` instead, which allow you to specify `hostname` and `port` separately:

```ts
import { serve } from "https://deno.land/std@0.50.0/http/server.ts";

const s = serve({hostname: '::', port: 8080});
for await (const req of s) {
  req.respond({ body: `Hello IPv6` });
}
```

Verifying with `netstat` shows that deno is indeed listening on `[::]:8080`.

```
$ sudo netstat -tlpn | grep deno
tcp6       0      0 :::8080                 :::*                    LISTEN      <pid>/deno 
```

**Comment by oronsh** [comment]
https://github.com/denoland/deno/pull/5263

**Comment by humancalico** [comment]
@bartlomieju It seems like this issue can be closed now
