### ISSUE TITLE
Import Error Backtraces

### ISSUE THREAD

**Issue by tubbo** [denoland/deno#5419]
The errors you get when an import fails, for almost any reason, are pretty useless in debugging. Importing a library which has a faulty import of its own (for example, not being updated to the latest Deno syntax) throws an error telling you which import failed, but doesn't tell you exactly where that import came from. The only way you can tell is by reading the previous download/compile statements printed to STDOUT.

Here's a recent example:

```
error: Uncaught TypeError: Cannot resolve extension for "https://raw.githubusercontent.com/jshttp/mime-db/master/db.json" with mediaType "Json".
    at getExtension ($deno$/compiler.ts:218:13)
    at new SourceFile ($deno$/compiler.ts:263:22)
    at Function.addToCache ($deno$/compiler.ts:339:16)
    at processImports ($deno$/compiler.ts:743:31)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
    at async processImports ($deno$/compiler.ts:753:7)
```

I'm not sure what to do with this. The error in and of itself doesn't point me to the actual place that it happened on. I propose that we add some kind of additional backtrace to show what line number and file that a bad `import` occurred on, rather than just say that the import failed and not tell the user where it happened.

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno/issues/5080

This problem will be fixed as part of https://github.com/denoland/deno/issues/5018
