### ISSUE TITLE
Cargo install deno fails

### ISSUE THREAD

**Issue by sant123** [denoland/deno#5430]
Hi, trying to install Deno from Cargo fails with the following output:

```bash
error: failed to run custom build command for `rusty_v8 v0.4.2`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installOY1Ygi/release/build/rusty_v8-707ae4523ba6e402/build-script-build` (exit code: 101)
--- stdout
static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.4.2/librusty_v8_release_x86_64-unknown-linux-gnu.a
cargo:rustc-link-search=/tmp/cargo-installOY1Ygi/release/gn_out/obj
Downloading https://github.com/denoland/rusty_v8/releases/download/v0.4.2/librusty_v8_release_x86_64-unknown-linux-gnu.a

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/sant821/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.4.2/build.rs:221:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: build_script_build::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  19: std::panicking::try
             at src/libstd/panicking.rs:281
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-installOY1Ygi`

Caused by:
  build failed
```
Rust version: v1.43.1
Cargo version: v1.43.0

I can add `RUST_BACKTRACE=full` if needed.

Thank you!

**Comment by invipal** [comment]
Check your python path and  "./tools/download_file.py" location. 

If you added extra unsupported target (rustup target add any-platform ), it could be source of problem.

Source of problem: https://github.com/denoland/rusty_v8/blob/v0.4.2/build.rs 
Error message: { code: 2, kind: NotFound, message: "No such file or directory" }

**Comment by sant123** [comment]
Thank you @invipal it works! 

In my path was registered python2 and python3 but not python. My workaround was to install this package to alias python to python3.

`sudo apt install python-is-python3`

I tried adding a custom alias in .zshrc but it didn't work.

As a note I'm using Ubuntu 20.04

**Comment by offline-pixel** [comment]
@sant123  i am having issue with https://github.com/denoland/deno/issues/5616 and want to install deno on windows 7 64bit. Please help me to close this issue ASAP

**Comment by sant123** [comment]
@offline-pixel what about installing Chocolatey? Seems straightforward and will let you install many packages.

**Comment by nleguen** [comment]
I'm trying to install deno v1.20.5 and the problem is back. Running `cargo install deno` produces the following error:
```
error: failed to add native library /tmp/cargo-installneCg64/release/gn_out/obj/librusty_v8.a: truncated or malformed archive (offset to next archive member past the end of the archive after member /)
```
Running it a second time with `cargo install deno --target-dir /tmp/cargo-installneCg64` makes the build to succeed.
