### ISSUE TITLE
node compatibility not working 

### ISSUE THREAD

**Issue by shinokada** [denoland/deno#5442]
My code from [the doc](https://deno.land/std/node/).

```
import { createRequire } from "https://deno.land/std/node/module.ts";
const require = createRequire(import.meta.url);
// Loads native module polyfill.
const path = require("path");
```

```
deno run path.ts
...
error: TS2339 [ERROR]: Property 'dir' does not exist on type 'typeof Deno'.
  return Deno.dir("home");
              ~~~
    at https://deno.land/std/node/os.ts:139:15

TS2339 [ERROR]: Property 'hostname' does not exist on type 'typeof Deno'.
  return Deno.hostname();
              ~~~~~~~~
    at https://deno.land/std/node/os.ts:144:15

TS2339 [ERROR]: Property 'loadavg' does not exist on type 'typeof Deno'.
  return Deno.loadavg();
              ~~~~~~~
    at https://deno.land/std/node/os.ts:152:15

TS2339 [ERROR]: Property 'osRelease' does not exist on type 'typeof Deno'.
  return Deno.osRelease();
              ~~~~~~~~~
    at https://deno.land/std/node/os.ts:166:15

TS2339 [ERROR]: Property 'dir' does not exist on type 'typeof Deno'.
  return Deno.dir("tmp");
              ~~~
    at https://deno.land/std/node/os.ts:185:15

TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'.
  signals: Deno.Signal,
                ~~~~~~
    at https://deno.land/std/node/os.ts:219:17

Found 6 errors.
```

Am I doing anything wrong here?

**Comment by crowlKats** [comment]
you need to run using the `--unstable` flag

**Comment by shinokada** [comment]
Thanks. 
It will be nice if it is in the doc.
