### ISSUE TITLE
fmt command panicked by throw statement

### ISSUE THREAD

**Issue by srackham** [denoland/deno#5567]
The snippet below compiles and runs but causes the `fmt` command to panic:

```
$ deno --version
deno 1.0.0
v8 8.4.300
typescript 3.9.2

$ cat deno-fmt-panic.ts 
try {
  throw new TypeError
}
catch {
}

$ deno run deno-fmt-panic.ts 
Compile file:///home/srackham/local/projects/drake/tmp/deno-fmt-panic.ts

$ deno fmt deno-fmt-panic.ts 
thread 'tokio-runtime-worker' panicked at 'Expected to find a close paren token.', /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/dprint-plugin-typescript-0.17.2/src/parsing/parser_types.rs:787:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Panic formatting: deno-fmt-panic.ts', cli/fmt.rs:232:5

```

**Comment by kitsonk** [comment]
Currently `deno fmt` panics on bad syntax like the above (`new TypeError` is invalid syntax as it is missing the parens), maybe it should raise one of the conformed errors.

**Comment by dsherret** [comment]
It would be good to improve it not to panic in these scenarios. I'll look into this.

**Comment by bartlomieju** [comment]
Ref https://github.com/dprint/dprint/issues/212
