### ISSUE TITLE
Is there a problem with transferring binary objects by Worker?

### ISSUE THREAD

**Issue by geeeger** [denoland/deno#5586]
my issue:
```javascript
// main.ts
worker.onmessage = async function (e: MessageEvent) {
    console.log(e.data)
}
```
```javascript
// worker.ts
self.onmessage = async function (e) {
    // this.console.log(e.data)
    self.fetch(e.data.url, {
        headers: {
            range: e.data.range
        }
    }).then(res => (res.blob()))
    .then(res => res.arrayBuffer())
    // .then(res=> this.console.log(res))
    .then(res => self.postMessage(res))
    .catch(e => this.console.log(e))
}
```

then i got an [object Object] and it is not ArrayBuffer

if i use transfer list

i got an error:

```sh
error: Uncaught Error: TS2554 [ERROR]: Expected 1 arguments, but got 2.
    .then(res => self.postMessage(res, [res]))
                                       ~~~~~
    at file:///D:/works/deno/worker.ts:10:40
    at WorkerImpl.#poll ($deno$/web/workers.ts:198:17)
```

**Comment by geeeger** [comment]
In addition, I set the deno option to true

**Comment by bartlomieju** [comment]
Structured clone and transfer are not yet implemented: https://github.com/denoland/deno/issues/3557

We should change the typing to allow transfer list and throw an error like in case of structured close.
