### ISSUE TITLE
http#serveTLS() "error uncaught NotFound" deno 1.0.1

### ISSUE THREAD

**Issue by teknsl** [denoland/deno#5675]
example
```ts
import { serveTLS } from "https://deno.land/std/http/mod.ts";
serveTLS({
  certFile: "cert",
  keyFile: "key",
  port: 9057,
});
```
console
```
$ deno run --allow-net file.ts
error: Uncaught NotFound: System cant find specified file. (os error 2)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.listenTls ($deno$/ops/tls.ts:67:10)
    at listenTls ($deno$/tls.ts:51:22)
    at serveTLS (https://deno.land/std/http/server.ts:313:20)
    at file:///the/path/to/file.ts:2:1
```  
may be related to me clearing the ``$deno$/deps/https/deno.land/`` folder, due to the 1.0.1 update; i do not know if re-downloading is automatic or needed to be done manually

**Comment by bartlomieju** [comment]
Do `cert` and `key` files exist? If not then you'll get `NotFound` error as reported.

**Comment by teknsl** [comment]
i figured the cert and key properties were supposed to be the string of their contents like on node, apparently not. thanks
