### ISSUE TITLE
Error on "std/bytes" when sending ArrayBuffers over WebSockets

### ISSUE THREAD

**Issue by diguifi** [denoland/deno#5735]
I think @keroxp might know better how to proceed.  

I'm trying to transfer binary data, by sending an ArrayBuffer over WebSockets, from a server to a client. When I do so, I get this error inside "std/bytes" lib:
_Uncaught RangeError: offset is out of bounds_

This is the code involved:
```ts
private pong(player: Player): void {
  let data = this.stringToArrayBuffer('{"command":3');
  player.clientWs?.send(data); // <------ line 42
}

private stringToArrayBuffer(stringfiedData: string): ArrayBuffer {
  const size = stringfiedData.length;

  let buf = new ArrayBuffer(size);
  let bufView = new Uint8Array(buf);
  for (var i=0; i < size; i++) {
      bufView[i] = stringfiedData.charCodeAt(i);
  }
  return buf;
}
```

Error:
```
error: Uncaught RangeError: offset is out of bounds
  output.set(a, 0);
         ^
    at Uint8Array.set (<anonymous>)
    at concat (https://deno.land/std/bytes/mod.ts:101:10)
    at writeFrame (https://deno.land/std/ws/mod.ts:141:12)
    at WebSocketImpl.dequeue (https://deno.land/std/ws/mod.ts:295:5)
    at WebSocketImpl.enqueue (https://deno.land/std/ws/mod.ts:311:12)
    at WebSocketImpl.send (https://deno.land/std/ws/mod.ts:327:17)
    at ClientHandler.pong (file:///F:/.../clientHandler.ts:42:22)
    at ClientHandler.handleClient (file:///F:/.../clientHandler.ts:94:18)
```

Any idea of what might be going on?

**Edit**: I managed to transfer binary data over WebSockets by transfering Uint8Arrays directly (not ArrayBuffers), but I don't even know if that's the right way to do it.

**Comment by diguifi** [comment]
After some research, I don't think it is useful to transfer binary data in most cases, since all strings sent are already binary encoded by default. My implementation is kinda redundant.
