### ISSUE TITLE
Standard library fails type check

### ISSUE THREAD

**Issue by brundonsmith** [denoland/deno#5821]
I'm trying out Deno and I can't get the standard library to pass the type check.

```
deno 1.0.2
v8 8.4.300
typescript 3.9.2
```

To reproduce, create `test.ts` with nothing but the following contents:
```typescript
import { readFileStrSync } from "https://deno.land/std/fs/mod.ts";
```

Then:
```bash
deno run test.ts
```

Output:
```
Compile file:///Users/brundolf/crafting-interpreters/jlox/test.ts
error: TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'.
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std/fs/copy.ts:90:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'.
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:101:10

TS2339 [ERROR]: Property 'symlink' does not exist on type 'typeof Deno'.
  await Deno.symlink(originSrcFilePath, dest, type);
             ~~~~~~~
    at https://deno.land/std/fs/copy.ts:114:14

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'.
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std/fs/copy.ts:119:16

TS2339 [ERROR]: Property 'symlinkSync' does not exist on type 'typeof Deno'.
  Deno.symlinkSync(originSrcFilePath, dest, type);
       ~~~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:132:8

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'.
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:137:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'.
    await Deno.utime(dest, srcStatInfo.atime, srcStatInfo.mtime);
               ~~~~~
    at https://deno.land/std/fs/copy.ts:157:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'.
    Deno.utimeSync(dest, srcStatInfo.atime, srcStatInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:185:10

TS2339 [ERROR]: Property 'link' does not exist on type 'typeof Deno'.
  await Deno.link(src, dest);
             ~~~~
    at https://deno.land/std/fs/ensure_link.ts:28:14

TS2339 [ERROR]: Property 'linkSync' does not exist on type 'typeof Deno'.
  Deno.linkSync(src, dest);
       ~~~~~~~~
    at https://deno.land/std/fs/ensure_link.ts:52:8

TS2339 [ERROR]: Property 'symlink' does not exist on type 'typeof Deno'.
  await Deno.symlink(src, dest, srcFilePathType);
             ~~~~~~~
    at https://deno.land/std/fs/ensure_symlink.ts:31:14

TS2339 [ERROR]: Property 'symlinkSync' does not exist on type 'typeof Deno'.
  Deno.symlinkSync(src, dest, srcFilePathType);
       ~~~~~~~~~~~
    at https://deno.land/std/fs/ensure_symlink.ts:58:8

Found 12 errors.
```

**Comment by bartlomieju** [comment]
@brundonsmith you need to use `--unstable` flag because `std/fs` uses some unstable APIs. More info here: https://deno.land/manual/standard_library#troubleshooting

**Comment by brundonsmith** [comment]
Ok. I ran with `--unstable` and got some different errors:
```
error: TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  await Deno.symlink(originSrcFilePath, dest, type);
                                              ~~~~
    at https://deno.land/std/fs/copy.ts:114:47

TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  Deno.symlinkSync(originSrcFilePath, dest, type);
                                            ~~~~
    at https://deno.land/std/fs/copy.ts:132:45

TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  await Deno.symlink(src, dest, srcFilePathType);
                                ~~~~~~~~~~~~~~~
    at https://deno.land/std/fs/ensure_symlink.ts:31:33

TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  Deno.symlinkSync(src, dest, srcFilePathType);
                              ~~~~~~~~~~~~~~~
    at https://deno.land/std/fs/ensure_symlink.ts:58:31

Found 4 errors.
```

**Comment by bartlomieju** [comment]
@brundonsmith use tagged URL of std: eg. if you're running Deno v1.0.2 then use `https://deno.land/std@0.53.0/fs/ensure_symlink.ts` 

Standard library is not yet stable and there are changes made daily so it's preferable to use tagged URL

**Comment by brundonsmith** [comment]
Ok
