### ISSUE TITLE
https error: Uncaught UnexpectedEof: tls handshake eof

### ISSUE THREAD

**Issue by teknsl** [denoland/deno#5857]
```
error: Uncaught UnexpectedEof: tls handshake eof
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async TLSListenerImpl.accept ($deno$/tls.ts:31:17)
    at async Server.acceptConnAndIterateHttpRequests (https://deno.land/std/http/server.ts:221:14)
    at async MuxAsyncIterator.callIteratorNext (https://deno.land/std/async/mux_async_iterator.ts:28:29)
```
occurs randomly in varying scale; 4~ days ago happened non-stop, now rarely

**Comment by bartlomieju** [comment]
@teknsl thanks for opening the issue, can you provide more context like:
- Deno version
- are you behind a proxy?
- is self-signed certificate used?

**Comment by teknsl** [comment]
- **Deno version**
happened more in 1.0.0, only experienced it happening twice in 1.0.1
- **are you behind a proxy?**
not locally, but cloudflare proxy is on, also have a worker that redirects requests to my port as i cant use 443 
- **is self-signed certificate used?**
certificate & key is provided from cloudflare's free universal SSL

**Comment by teknsl** [comment]
still happens in 1.0.2

**Comment by aricart** [comment]
Also noticing that on a TLS upgraded connection:

```
error: Uncaught (in promise) UnexpectedEof: tls handshake eof
    nwritten += await w.write(arr.subarray(nwritten));
                ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async write (deno:runtime/js/12_io.js:107:12)
    at async writeAll (https://deno.land/std@0.95.0/io/util.ts:79:17)
    at async BufWriter.flush (https://deno.land/std@0.95.0/io/bufio.ts:470:7)
    at async write (file:///Users/xxx/Dropbox/code/src/github.com/nats-io/nats.deno/src/deno_transport.ts:45:3)
```

Also not quite sure when this is called. In my test cases, I get the above failure, but no particular test case fails because of it.

**Comment by acrodrig** [comment]
I am getting the same error on:

```
deno 1.23.1 (release, aarch64-apple-darwin)
v8 10.4.132.8
typescript 4.7.2
```

On the request below:

```
error: Uncaught (in promise) TypeError: error sending request for url (https://*****/***): error trying to connect: tls handshake eof
        const response = await fetch(url.toString(), options);
```
