### ISSUE TITLE
deno does not support http proxy

### ISSUE THREAD

**Issue by saibing** [denoland/deno#588]
I set a http/https proxy on os:

```bash
baas@SZX1000428520:~/git/js/deno$ env | grep proxy
http_proxy=http://10.77.28.6:9090
https_proxy=http://10.77.28.6:9090
```

but deno cannot use them:

```bash
baas@SZX1000428520:~/git/js/deno$ deno hello.ts
Downloading http://unpkg.com/deno_testing@0.0.7/testing.ts
Error: Cannot resolve module "http://unpkg.com/deno_testing@0.0.7/testing.ts" from "/home/baas/git/js/deno/hello.ts".
  os.codeFetch message: an error occurred trying to connect: Connection timed out (os error 110)
    at throwResolutionError (deno/js/compiler.ts:99:9)
    at DenoCompiler.resolveModule (deno/js/compiler.ts:362:16)
    at DenoCompiler.resolveModuleName (deno/js/compiler.ts:396:33)
    at moduleNames.map.name (deno/js/compiler.ts:552:33)
    at Array.map (<anonymous>)
    at DenoCompiler.resolveModuleNames (deno/js/compiler.ts:543:24)
    at Object.compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:111649:117)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:82561:106)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:82768:24)
    at processImportedModules (deno/third_party/node_modules/typescript/lib/typescript.js:84005:35)
```

**Comment by cedric05** [comment]
will work on this

**Comment by zekth** [comment]
Does anyone have a workaround for this? Tried using this on windows but does not work:
```
netsh winhttp set proxy 'proxyurl'
```

**Comment by zekth** [comment]
We can achieve it by using `hyper_proxy` library. At the moment Deno only uses `hyper` base library which does not offer the possibility to use a proxy.

Are you ok to add `hyper_proxy` ? I can handle this.

**Comment by fd** [comment]
I'm also interested in this functionality.

**Comment by j-blank** [comment]
@zekth could you a tutorial how to use the hyper_proxy ? now im using deno on windows and got this problem because coorperate proxy

**Comment by zekth** [comment]
> @zekth could you a tutorial how to use the hyper_proxy ? now im using deno on windows and got this problem because coorperate proxy

Working on it ATM. There is a draft PR. Have to make it work.

**Comment by kt3k** [comment]
ref: `request`'s handlings of http proxy settings https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

npm seems depending on `request` for this feature. https://github.com/nodejs/node/blob/master/deps/npm/doc/misc/npm-config.md#https-proxy

**Comment by bartlomieju** [comment]
FYI proxies should work on latest `master`, there's still tests missing tho

**Comment by ry** [comment]
Support is in v0.17.0 - missing docs still https://github.com/denoland/deno/issues/2873
