### ISSUE TITLE
Wrong behavior when parsing csv

### ISSUE THREAD

**Issue by Driky** [denoland/deno#5984]
Just tried the csv parsing that comes with the STD. And I get an error when  passing headers:

The first two line of my csv

```csv
Entry Date;Settlement Date;Action;Qty;Symbol;Description;Price;Comm.;Net Amount
25-May-20;06-janv-20;ROC COST ADJ;0;CWW;ISHARES S&P GBL WATER UN ETF;;;
```

```typsecript
const options = {
    header: [
      "entryDate",
      "settlementDate",
      "action",
      "quantity",
      "symbol",
      "description",
      "price",
      "commission",
      "NetAmmount",
    ],
  };
  const parsed = await parse(csv, options);
```

The error:
```
error: Uncaught Error number of fields line:0
```

and if I add `fieldsPerRecord: 9,` to my options, I get an error but this time not from the `parse` function but the `readMatrix` function:
```
error: Uncaught Error: wrong number of fields
        throw new ParseError(lineIndex, lineIndex, ERR_FIELD_COUNT);
              ^
    at readMatrix (https://deno.land/std@0.51.0/encoding/csv.ts:247:15)
    at async parse (https://deno.land/std@0.51.0/encoding/csv.ts:301:9)
    at async parseHistory (file:///G:/projects/deno/qtrade-history-parser/history-parser.ts:20:18)
```

My csv properly opens in excel and other spreadsheet software.

**Comment by Caesar2011** [comment]
Did you tried to specify the separator `;` manually?

**Comment by Driky** [comment]
Ah.... Shame on me. Thank you @Caesar2011

**Comment by alldayalone** [comment]
Hit the same thing today. Thank you!
