### ISSUE TITLE
TS2531 [ERROR]: Object is possibly 'null' when matching boundary

### ISSUE THREAD

**Issue by devYusuf** [denoland/deno#6010]
Hello, I ran into Errors after running the code below, I got it from a github gist.

```ts
import {
  yellow,
  cyan,
  bold,
  red
} from "https://deno.land/std/fmt/colors.ts";
import { serve } from "https://deno.land/std/http/server.ts";
import {
  MultipartReader,
  FormFile
} from "https://deno.land/std@v0.53.0/mime/multipart.ts";
import { decode } from "https://deno.land/std/strings/mod.ts";

const s = serve({ port: 1447 });
console.log(bold("Listening on"), yellow("http://localhost:1447/"));

const html = `<!DOCTYPE html>
<html>
<head>
  <title>Multipart Reader Example</title>
</head>
<body>
  <form method="POST" action="/upload" enctype="multipart/form-data">
    <label for="attachment">Attach file:</label>
    <input name="attachment" type="file" />
    <button type="submit">Upload</button>
  </form>
</body>
`;

for await (const req of s) {
  if (req.url === "/upload" && req.method !== "POST") {
    req.respond({
      status: 405,
      body: "405 Method Not Allowed"
    });
  } else if (req.url === "/upload") {
    try {
      const contentType = req.headers.get("content-type");
      const boundary = contentType.match(/boundary=([^\s]+)/)[1];
      const reader = new MultipartReader(req.body, boundary);
      const form = await reader.readForm(1024 * 1024); // 1MB
      console.log(form);

      const attachment = form.attachment as FormFile;
      if (attachment.content) {
        console.log(cyan("content"), decode(content));
      } else if (attachment.tempfile) {
        console.log(
          cyan("content"),
          decode(await Deno.readFile(attachment.tempfile))
        );
      }

      const headers = new Headers();
      headers.set("Location", "/");
      req.respond({
        status: 302,
        headers
      });
    } catch (e) {
      console.error(red(e.message));
      console.error(e.stack);
      req.respond({
        status: 500,
        body: "500 Internal Server Error"
      });
    }
  } else {
    req.respond({ body: html });
  }
}
```

after running the code I got the error:

```
error: TS2531 [ERROR]: Object is possibly 'null'.
      const boundary = contentType.match(/boundary=([^\s]+)/)[1];
                       ~~~~~~~~~~~
    at file:///home/yusuf/Documents/multip.ts:40:24

TS2531 [ERROR]: Object is possibly 'null'.
      const boundary = contentType.match(/boundary=([^\s]+)/)[1];
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/yusuf/Documents/multip.ts:40:24

TS2339 [ERROR]: Property 'attachment' does not exist on type 'MultipartFormData'.
      const attachment = form.attachment as FormFile;
                              ~~~~~~~~~~
    at file:///home/yusuf/Documents/multip.ts:45:31

TS2304 [ERROR]: Cannot find name 'decode'.
          decode(await Deno.readFile(attachment.tempfile))
          ~~~~~~
    at file:///home/yusuf/Documents/multip.ts:51:11

Found 4 errors.

```

**Comment by kitsonk** [comment]
The errors are correct, this is not an issue with Deno.  Please read the errors and correct your code.

**Comment by deebloo** [comment]
@devYusuf Deno uses strict ts compiler options by default. You CAN provide your own tsconfig and disable them but I would NOT recommend it. Do as @kitsonk said and just fix the errors the compiler is giving you.
