### ISSUE TITLE
@ts-expect-error directive breaks under non-strict tsconfig

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno#6033]
Today at morning time (New York). My application started throwing the following error in multiple tests: 
```error: TS2578 [ERROR]: Unused '@ts-expect-error' directive.
  // @ts-expect-error
  ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.54.0/ws/mod.ts:494:3```
```
All test cases were tested and they were all throwing the same error.  

tsconfig.json

```
{
    "compilerOptions": {
        "strict": false,
        "noImplicitAny": false,
        "noImplicitThis": false,
        "alwaysStrict": false,
        "strictNullChecks": false,
        "strictFunctionTypes": true,
        "strictPropertyInitialization": false,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "allowUmdGlobalAccess": false,
    }
}
```

After investigation, // @ts-ignore worked properly in all test cases, but // @ts-expect-error broke the code.

**Comment by andreespirela** [comment]
Setting `strict` to **true** keeps the error and creates a new one.
```
error: TS2578 [ERROR]: Unused '@ts-expect-error' directive.
  // @ts-expect-error
  ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.54.0/ws/mod.ts:494:3

TS2684 [ERROR]: The 'this' context of type 'Function | BodyFunction' is not assignable to method's 'this' of type '((this: unknown) => string | number | bigint | boolean | symbol | object | Promise<Body>) & Function'.
  Type 'Function' is not assignable to type '((this: unknown) => string | number | bigint | boolean | symbol | object | Promise<Body>) & Function'.
    Type 'Function' is not assignable to type '(this: unknown) => string | number | bigint | boolean | symbol | object | Promise<Body>'.
      Type 'Function' provides no match for the signature '(this: unknown): string | number | bigint | boolean | symbol | object | Promise<Body>'.
    const result = body.call(null);
                   ~~~~
    at https://deno.land/x/oak/response.ts:73:20
```
As you can see, yes, my app uses Oak, setting strict to true "breaks" the oak system and also **keeps** the first error
