### ISSUE TITLE
@deno-types don't work when I export directly a JS file from url

### ISSUE THREAD

**Issue by OverGlass** [denoland/deno#6044]
Hello 👋 

file `./deps.ts`
```javascript
// [1]

// @deno-types="https://deno.land/x/types/react/v16.13.1/react.d.ts"
export { default as React } from "https://dev.jspm.io/react@16.12.0";
 ```
```javascript
// [2]

// @deno-types="https://deno.land/x/types/react/v16.13.1/react.d.ts"
import React  from "https://dev.jspm.io/react@16.12.0";
export { React }
 ```
file `./app.ts`
```javascript
import { React } from "./deps.ts"
const component = <h1>Deno</h1>
console.log("It Works !") 
 ```
[output] [1] ❌
```bash
❯ deno run --allow-net  app.ts
Compile file:///Users/overglass/lab/deno/app.ts
error: TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
  const component = <h1>Deno</h1>;
                    ~~~~
    at file:///Users/antonincarlin/lab/piaf-api/views/Render.tsx:4:21

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
  const component = <h1>Deno</h1>;
                            ~~~~~
    at file:///Users/antonincarlin/lab/piaf-api/views/Render.tsx:4:29

Found 2 errors.
```
[output] [2] 🦕
```bash
❯ deno run --allow-net  app.ts
Compile file:///Users/overglass/lab/deno/app.ts
It Works !
```
I have the same issue with pika.dev CDN

Thanks you for your work :)

**Comment by Soremwar** [comment]
Might be unrelated, but Deno only accepts JSX syntax inside `.jsx` or `.tsx` so you might try to rename that first.

**Comment by OverGlass** [comment]
Oh I made a mistake when I wrote this issue, I'm using app.tsx, not app.ts.
