### ISSUE TITLE
thread 'main' panicked at 'already borrowed: BorrowMutError' when in REPL

### ISSUE THREAD

**Issue by hastri** [denoland/deno#6053]
```
C:\workspace>deno-1.0.3.exe
Deno 1.0.3
exit using ctrl+d or close()
> crypto.getRandomValues(new Uint8Array(10))
Uint8Array(10) [
  255, 146, 102,  81,
  25, 238, 144, 127,
  185, 250
]
> 
```

```
C:\workspace\deno>deno
Deno 1.0.4
exit using ctrl+d or close()
> crypto.getRandomValues(new Uint8Array(10))
thread 'main' panicked at 'already borrowed: BorrowMutError', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libcore\cell.rs:878:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

C:\workspace\deno>
```

```
C:\workspace\deno>set RUST_BACKTRACE=full& deno
Deno 1.0.4
exit using ctrl+d or close()
> crypto.getRandomValues(new Uint8Array(10))
thread 'main' panicked at 'already borrowed: BorrowMutError', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libcore\cell.rs:878:9
stack backtrace:
   0:     0x7ff7eaab92df - CrashForExceptionInNonABICompliantCodeRange
   1:     0x7ff7eaada82b - CrashForExceptionInNonABICompliantCodeRange
   2:     0x7ff7eaaaf09c - CrashForExceptionInNonABICompliantCodeRange
   3:     0x7ff7eaabc96c - CrashForExceptionInNonABICompliantCodeRange
   4:     0x7ff7eaabc5bf - CrashForExceptionInNonABICompliantCodeRange
   5:     0x7ff7eaabd147 - CrashForExceptionInNonABICompliantCodeRange
   6:     0x7ff7eaabcccf - CrashForExceptionInNonABICompliantCodeRange
   7:     0x7ff7eaad9130 - CrashForExceptionInNonABICompliantCodeRange
   8:     0x7ff7eaad8f83 - CrashForExceptionInNonABICompliantCodeRange
   9:     0x7ff7e9fdd070 - <unknown>
  10:     0x7ff7e9fcf8ab - <unknown>
  11:     0x7ff7ea4731bb - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff7ea4725f8 - CrashForExceptionInNonABICompliantCodeRange
  13:     0x7ff7ea471b46 - CrashForExceptionInNonABICompliantCodeRange
  14:     0x7ff7ea471767 - CrashForExceptionInNonABICompliantCodeRange
  15:     0x7ff7ea2842fc - CrashForExceptionInNonABICompliantCodeRange
  16:     0x7ff7ea216755 - CrashForExceptionInNonABICompliantCodeRange
  17:     0x7ff7ea20ff1f - CrashForExceptionInNonABICompliantCodeRange
  18:     0x7ff7ea216755 - CrashForExceptionInNonABICompliantCodeRange
  19:     0x7ff7ea216755 - CrashForExceptionInNonABICompliantCodeRange
  20:     0x7ff7ea21421e - CrashForExceptionInNonABICompliantCodeRange
  21:     0x7ff7ea213e0c - CrashForExceptionInNonABICompliantCodeRange
  22:     0x7ff7ea0d57a7 - <unknown>
  23:     0x7ff7ea0d4b2a - <unknown>
  24:     0x7ff7ea003be3 - <unknown>
  25:     0x7ff7e9ffb6a1 - <unknown>
  26:     0x7ff7e9fdde9d - <unknown>
  27:     0x7ff7e9fcf71b - <unknown>
  28:     0x7ff7ea4731bb - CrashForExceptionInNonABICompliantCodeRange
  29:     0x7ff7ea4725f8 - CrashForExceptionInNonABICompliantCodeRange
  30:     0x7ff7ea471b46 - CrashForExceptionInNonABICompliantCodeRange
  31:     0x7ff7ea471767 - CrashForExceptionInNonABICompliantCodeRange
  32:     0x7ff7ea2842fc - CrashForExceptionInNonABICompliantCodeRange
  33:     0x7ff7ea216755 - CrashForExceptionInNonABICompliantCodeRange
  34:     0x7ff7ea216755 - CrashForExceptionInNonABICompliantCodeRange
  35:     0x7ff7ea245a51 - CrashForExceptionInNonABICompliantCodeRange
  36:     0x7ff7ea2c930f - CrashForExceptionInNonABICompliantCodeRange
  37:     0x7ff7ea237dad - CrashForExceptionInNonABICompliantCodeRange
  38:     0x7ff7ea21410c - CrashForExceptionInNonABICompliantCodeRange
  39:     0x7ff7ea0d56de - <unknown>
  40:     0x7ff7ea0d5dac - <unknown>
  41:     0x7ff7ea0d5eaf - <unknown>
  42:     0x7ff7ea199b28 - CrashForExceptionInNonABICompliantCodeRange
  43:     0x7ff7ea199905 - CrashForExceptionInNonABICompliantCodeRange
  44:     0x7ff7ea035ae1 - <unknown>
  45:     0x7ff7ea010321 - <unknown>
  46:     0x7ff7e9ffb436 - <unknown>
  47:     0x7ff7e9fb9380 - <unknown>
  48:     0x7ff7e9fb7ce0 - <unknown>
  49:     0x7ff7e9fc3179 - <unknown>
  50:     0x7ff7e98121fa - <unknown>
  51:     0x7ff7e96f250e - <unknown>
  52:     0x7ff7e9787669 - <unknown>
  53:     0x7ff7e9741a54 - <unknown>
  54:     0x7ff7e98c16f5 - <unknown>
  55:     0x7ff7e9764f20 - <unknown>
  56:     0x7ff7e9948d26 - <unknown>
  57:     0x7ff7eaabcb67 - CrashForExceptionInNonABICompliantCodeRange
  58:     0x7ff7eaacab92 - CrashForExceptionInNonABICompliantCodeRange
  59:     0x7ff7eaabd388 - CrashForExceptionInNonABICompliantCodeRange
  60:     0x7ff7e9768da7 - <unknown>
  61:     0x7ff7eaaeaf44 - CrashForExceptionInNonABICompliantCodeRange
  62:     0x7ffd92e77bd4 - BaseThreadInitThunk
  63:     0x7ffd9398ce51 - RtlUserThreadStart

C:\workspace\deno>
```

**Comment by bartlomieju** [comment]
Most likely caused by #5929

**Comment by afinch7** [comment]
It's worth noting you can produce the same error with any op not just `crypto.getRandomValues`.
