### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by dkuroi** [denoland/deno#6100]
```bash
$ deno run -A --unstable server.ts
INFO load deno plugin "deno_mongo" from local "C:\Users\hp\workspaces\stack-DORM-boilerplate\backend\.deno_plugins\deno_mongo_d39a70f1ebd90a74818be406f169051f.dll"
thread '' panicked at 'called `Option::unwrap()` on a `None` value', src\command\connect.rs:63:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace           
Segmentation fault
```

```bash
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\command\connect.rs:63:24
stack backtrace:
   0:     0x7ffa17bf7ddf - CrashForExceptionInNonABICompliantCodeRange
   1:     0x7ffa17c1497b - rust_eh_personality
   2:     0x7ffa17bef16c - CrashForExceptionInNonABICompliantCodeRange
   3:     0x7ffa17bfb08c - CrashForExceptionInNonABICompliantCodeRange
   4:     0x7ffa17bfacdf - CrashForExceptionInNonABICompliantCodeRange
   5:     0x7ffa17bfb847 - CrashForExceptionInNonABICompliantCodeRange
   6:     0x7ffa17bfb3cf - CrashForExceptionInNonABICompliantCodeRange
   7:     0x7ffa17c12fc0 - rust_eh_personality
   8:     0x7ffa17c12f0c - rust_eh_personality
   9:     0x7ffa177dff2f - <unknown>
  10:     0x7ffa177e0bd0 - deno_plugin_init
  11:     0x7ff7e2037619 - <unknown>
  12:     0x7ff7e283c77a - <unknown>
  13:     0x7ff7e2861f83 - <unknown>
  14:     0x7ff7e285e31b - <unknown>
  15:     0x7ff7e2cf835b - CrashForExceptionInNonABICompliantCodeRange
  16:     0x7ff7e2cf7798 - CrashForExceptionInNonABICompliantCodeRange
  17:     0x7ff7e2cf6ce6 - CrashForExceptionInNonABICompliantCodeRange
  18:     0x7ff7e2cf6907 - CrashForExceptionInNonABICompliantCodeRange
  19:     0x7ff7e2b0949c - CrashForExceptionInNonABICompliantCodeRange
  20:     0x7ff7e2a9b8f5 - CrashForExceptionInNonABICompliantCodeRange
  21:     0x7ff7e2a9b8f5 - CrashForExceptionInNonABICompliantCodeRange
  22:     0x7ff7e2a9b8f5 - CrashForExceptionInNonABICompliantCodeRange
  23:     0x7ff7e2a9b8f5 - CrashForExceptionInNonABICompliantCodeRange
  24:     0x7ff7e2acd46d - CrashForExceptionInNonABICompliantCodeRange
  25:     0x7ff7e2a993be - CrashForExceptionInNonABICompliantCodeRange
  26:     0x7ff7e2a98fac - CrashForExceptionInNonABICompliantCodeRange
  27:     0x7ff7e295a957 - <unknown>
  28:     0x7ff7e295af5c - <unknown>
  29:     0x7ff7e295aece - <unknown>
  30:     0x7ff7e2962ccf - <unknown>
  31:     0x7ff7e29626d3 - <unknown>
  32:     0x7ff7e2d555f9 - CrashForExceptionInNonABICompliantCodeRange
  33:     0x7ff7e2d55307 - CrashForExceptionInNonABICompliantCodeRange
  34:     0x7ff7e2b0949c - CrashForExceptionInNonABICompliantCodeRange
  35:     0x7ff7e2b4e4af - CrashForExceptionInNonABICompliantCodeRange
  36:     0x7ff7e2abcf4d - CrashForExceptionInNonABICompliantCodeRange
  37:     0x7ff7e2a992ac - CrashForExceptionInNonABICompliantCodeRange
  38:     0x7ff7e295a88e - <unknown>
  39:     0x7ff7e295af5c - <unknown>
  40:     0x7ff7e295b05f - <unknown>
  41:     0x7ff7e2a1ecd8 - CrashForExceptionInNonABICompliantCodeRange
  42:     0x7ff7e2a1eab5 - CrashForExceptionInNonABICompliantCodeRange
  43:     0x7ff7e28bac91 - <unknown>
  44:     0x7ff7e28954d1 - <unknown>
  45:     0x7ff7e28805a6 - <unknown>
  46:     0x7ff7e283cf28 - <unknown>
  47:     0x7ff7e283b850 - <unknown>
  48:     0x7ff7e28442ff - <unknown>
  49:     0x7ff7e20d4655 - <unknown>
  50:     0x7ff7e1f7cbbe - <unknown>
  51:     0x7ff7e2012b49 - <unknown>
  52:     0x7ff7e1fcd684 - <unknown>
  53:     0x7ff7e214cbe5 - <unknown>
  54:     0x7ff7e1ff0b50 - <unknown>
  55:     0x7ff7e220ea16 - <unknown>
  56:     0x7ff7e3341d67 - CrashForExceptionInNonABICompliantCodeRange
  57:     0x7ff7e334fd92 - CrashForExceptionInNonABICompliantCodeRange
  58:     0x7ff7e3342588 - CrashForExceptionInNonABICompliantCodeRange
  59:     0x7ff7e1ff49d7 - <unknown>
  60:     0x7ff7e3370144 - CrashForExceptionInNonABICompliantCodeRange
  61:     0x7ffa7cfe7bd4 - BaseThreadInitThunk
  62:     0x7ffa7ef8ce51 - RtlUserThreadStart
Segmentation fault
```

**Comment by ry** [comment]
Is this maybe an issue in the deno_mongo plugin? cc @manyuanrong

**Comment by manyuanrong** [comment]
Seems to be caused by changes to plugin api in deno v1.0.4. deno_mongo has not been built on the new version

**Comment by dkuroi** [comment]
uhm i understand, i'll wait for a new library to come out or deno_mongo being updated

**Comment by manyuanrong** [comment]
@dkuroi https://github.com/manyuanrong/deno_mongo/releases/tag/v0.8.0

**Comment by dkuroi** [comment]
Great! Now works! Thanks 😄
