### ISSUE TITLE
lock_check_ok is flaky 

### ISSUE THREAD

**Issue by ry** [denoland/deno#6108]
ex: https://github.com/denoland/deno/runs/738886402
ex2: https://github.com/denoland/deno/runs/742816063
ex3: https://github.com/denoland/deno/pull/6112/checks?check_run_id=745606058
```
2020-06-04T14:57:03.2101177Z ---- lock_check_ok stdout ----
2020-06-04T14:57:03.2101533Z target_dir /home/runner/work/deno/deno/target/release
2020-06-04T14:57:03.2101827Z root path /home/runner/work/deno/deno/cli/..
2020-06-04T14:57:03.2102119Z deno_exe path /home/runner/work/deno/deno/target/release/deno
2020-06-04T14:57:03.2102415Z tools/http_server.py starting...
2020-06-04T14:57:03.2102708Z target_dir /home/runner/work/deno/deno/target/release
2020-06-04T14:57:03.2103018Z output path /home/runner/work/deno/deno/cli/../cli/tests/003_relative_import.ts.out
2020-06-04T14:57:03.2103292Z OUTPUT
2020-06-04T14:57:03.2103621Z Download http://127.0.0.1:4545/cli/tests/003_relative_import.ts
2020-06-04T14:57:03.2103982Z Download http://127.0.0.1:4545/cli/tests/subdir/print_hello.ts
2020-06-04T14:57:03.2104320Z Compile http://127.0.0.1:4545/cli/tests/003_relative_import.ts
2020-06-04T14:57:03.2104607Z Hello
2020-06-04T14:57:03.2104812Z 
2020-06-04T14:57:03.2105066Z OUTPUT
2020-06-04T14:57:03.2106711Z EXPECTED
2020-06-04T14:57:03.2107042Z Hello
2020-06-04T14:57:03.2107244Z 
2020-06-04T14:57:03.2107498Z EXPECTED
2020-06-04T14:57:03.2115414Z ##[error]thread 'lock_check_ok' panicked at 'pattern match failed', cli/tests/integration_tests.rs:3031:9
2020-06-04T14:57:03.2118601Z stack backtrace:
2020-06-04T14:57:03.2119696Z    0:     0x5596c0b3c3d4 - backtrace::backtrace::libunwind::trace::h5ae3454ebe40b621
2020-06-04T14:57:03.2120463Z                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
2020-06-04T14:57:03.2121304Z    1:     0x5596c0b3c3d4 - backtrace::backtrace::trace_unsynchronized::hbf6f267a483fb2c0
2020-06-04T14:57:03.2122040Z                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
2020-06-04T14:57:03.2122850Z    2:     0x5596c0b3c3d4 - std::sys_common::backtrace::_print_fmt::h37755015d94b9085
2020-06-04T14:57:03.2123477Z                                at src/libstd/sys_common/backtrace.rs:78
2020-06-04T14:57:03.2124359Z    3:     0x5596c0b3c3d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0561c8cd3569b40d
2020-06-04T14:57:03.2124775Z                                at src/libstd/sys_common/backtrace.rs:59
2020-06-04T14:57:03.2125515Z    4:     0x5596c0b6416c - core::fmt::write::h86a597a35d48a212
2020-06-04T14:57:03.2125882Z                                at src/libcore/fmt/mod.rs:1063
2020-06-04T14:57:03.2126700Z    5:     0x5596c0a50965 - std::io::Write::write_fmt::h1fd8f7c3aaade85d
2020-06-04T14:57:03.2127111Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/io/mod.rs:1426
2020-06-04T14:57:03.2128067Z    6:     0x5596c0b33851 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h11a95b4981a262a0
2020-06-04T14:57:03.2128948Z                                at src/libstd/io/impls.rs:156
2020-06-04T14:57:03.2131658Z    7:     0x5596c0b40635 - std::sys_common::backtrace::_print::h6c60c5ee09af0233
2020-06-04T14:57:03.2131880Z                                at src/libstd/sys_common/backtrace.rs:62
2020-06-04T14:57:03.2132779Z    8:     0x5596c0b40635 - std::sys_common::backtrace::print::hf9d1db01634f9b2a
2020-06-04T14:57:03.2132995Z                                at src/libstd/sys_common/backtrace.rs:49
2020-06-04T14:57:03.2133617Z    9:     0x5596c0b40635 - std::panicking::default_hook::{{closure}}::h1db9298dd213ae95
2020-06-04T14:57:03.2133825Z                                at src/libstd/panicking.rs:204
2020-06-04T14:57:03.2135221Z   10:     0x5596c0b4032b - std::panicking::default_hook::h3272faf6cc91fd2e
2020-06-04T14:57:03.2135469Z                                at src/libstd/panicking.rs:221
2020-06-04T14:57:03.2136187Z   11:     0x5596c0b40c92 - std::panicking::rust_panic_with_hook::hb976084785e50594
2020-06-04T14:57:03.2136391Z                                at src/libstd/panicking.rs:470
2020-06-04T14:57:03.2136967Z   12:     0x5596c09fe44e - std::panicking::begin_panic::h771c914462e13332
2020-06-04T14:57:03.2137603Z   13:     0x5596c09e176f - integration_tests::util::CheckOutputIntegrationTest::run::h2be5af95a3b7862b
2020-06-04T14:57:03.2138203Z   14:     0x5596c09baa51 - core::ops::function::FnOnce::call_once::hb7437f2fe7697a55
2020-06-04T14:57:03.2138845Z   15:     0x5596c0a5ce6f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h012be6ce828b5d0b
2020-06-04T14:57:03.2139086Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/boxed.rs:1017
2020-06-04T14:57:03.2139453Z   16:     0x5596c0b4a617 - __rust_maybe_catch_panic
2020-06-04T14:57:03.2139646Z                                at src/libpanic_unwind/lib.rs:86
2020-06-04T14:57:03.2151830Z   17:     0x5596c0a782cc - std::panicking::try::h4cc8d292e9fe5dd8
2020-06-04T14:57:03.2152088Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/panicking.rs:281
2020-06-04T14:57:03.2152696Z   18:     0x5596c0a782cc - std::panic::catch_unwind::h963079ac534210f7
2020-06-04T14:57:03.2152927Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/panic.rs:394
2020-06-04T14:57:03.2153499Z   19:     0x5596c0a782cc - test::run_test_in_process::h9a1821a43e552ab8
2020-06-04T14:57:03.2153699Z                                at src/libtest/lib.rs:542
2020-06-04T14:57:03.2154285Z   20:     0x5596c0a782cc - test::run_test::run_test_inner::{{closure}}::h022f4c17b23ed2cb
2020-06-04T14:57:03.2154488Z                                at src/libtest/lib.rs:451
2020-06-04T14:57:03.2161204Z   21:     0x5596c0a50096 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc71773c677d1c1ee
2020-06-04T14:57:03.2161486Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/sys_common/backtrace.rs:130
2020-06-04T14:57:03.2162218Z   22:     0x5596c0a54736 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hc99fda77faf31579
2020-06-04T14:57:03.2162630Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/thread/mod.rs:475
2020-06-04T14:57:03.2163344Z   23:     0x5596c0a54736 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he4800ebccddde5b2
2020-06-04T14:57:03.2163585Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/panic.rs:318
2020-06-04T14:57:03.2164162Z   24:     0x5596c0a54736 - std::panicking::try::do_call::hc2cca8f4b20030d5
2020-06-04T14:57:03.2164395Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/panicking.rs:303
2020-06-04T14:57:03.2164760Z   25:     0x5596c0b4a617 - __rust_maybe_catch_panic
2020-06-04T14:57:03.2165047Z                                at src/libpanic_unwind/lib.rs:86
2020-06-04T14:57:03.2165666Z   26:     0x5596c0a551a6 - std::panicking::try::h061e25305e6e95c0
2020-06-04T14:57:03.2165892Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/panicking.rs:281
2020-06-04T14:57:03.2166475Z   27:     0x5596c0a551a6 - std::panic::catch_unwind::he0ee09490dbb649b
2020-06-04T14:57:03.2166705Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/panic.rs:394
2020-06-04T14:57:03.2167322Z   28:     0x5596c0a551a6 - std::thread::Builder::spawn_unchecked::{{closure}}::hab5579c66226575e
2020-06-04T14:57:03.2167557Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/thread/mod.rs:474
2020-06-04T14:57:03.2168167Z   29:     0x5596c0a551a6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbc145bf8f99ddd0f
2020-06-04T14:57:03.2168407Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/ops/function.rs:232
2020-06-04T14:57:03.2169048Z   30:     0x5596c0b2e1bf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h553ef812d1929d1b
2020-06-04T14:57:03.2169288Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/boxed.rs:1017
2020-06-04T14:57:03.2169923Z   31:     0x5596c0b497bd - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h51b51bce029ae491
2020-06-04T14:57:03.2170161Z                                at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/boxed.rs:1017
2020-06-04T14:57:03.2173972Z   32:     0x5596c0b497bd - std::sys_common::thread::start_thread::hca943f45f04c8e46
2020-06-04T14:57:03.2174186Z                                at src/libstd/sys_common/thread.rs:13
2020-06-04T14:57:03.2174834Z   33:     0x5596c0b497bd - std::sys::unix::thread::Thread::new::thread_start::h352e8a5875b189ee
2020-06-04T14:57:03.2175042Z                                at src/libstd/sys/unix/thread.rs:80
2020-06-04T14:57:03.2175384Z   34:     0x7f25277e76ba - start_thread
2020-06-04T14:57:03.2175709Z   35:     0x7f252730541d - clone
2020-06-04T14:57:03.2176027Z   36:                0x0 - <unknown>
2020-06-04T14:57:03.2176114Z 
2020-06-04T14:57:03.2176195Z 
2020-06-04T14:57:03.2176325Z failures:
2020-06-04T14:57:03.2176466Z     lock_check_ok
```

**Comment by lucacasonato** [comment]
Another example: https://github.com/denoland/deno/runs/743564013

**Comment by ry** [comment]
https://github.com/denoland/deno/pull/6304/checks?check_run_id=787624331

lock_check_err is also flaky - probably for the same reason

**Comment by bartlomieju** [comment]
Ref #5231
