### ISSUE TITLE
WebAssembly runtime errors don't propagate

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#6120]
WebAssembly errors are getting caught up in the source-map/caching mechanism.

For example

```typescript
// WebAssembly module containing a single function with an unreachable instruction
const binary = Uint8Array.of(
	0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x04, 0x01, 0x60,
	0x00, 0x00, 0x03, 0x02, 0x01, 0x00, 0x07, 0x0f, 0x01, 0x0b, 0x75, 0x6e,
	0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x00, 0x00, 0x0a,
	0x05, 0x01, 0x03, 0x00, 0x00, 0x0b
);

const module = new WebAssembly.Module(binary);
const instance = new WebAssembly.Instance(module);

instance.exports.unreachable();
```

Actual output:

```
thread 'main' panicked at 'not implemented: Don't know how to create cache name for scheme: wasm', cli/disk_cache.rs:95:9
```

Expected output:

```
RuntimeError: unreachable
    at wasm-function[0]:0x28
    at Object.<anonymous> (/Users/caspervonb/wasm_error_test.ts:13:18)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Traceback:

```
   0:        0x10adfe1ec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1216a26f3ce3c114
   1:        0x10ae1cbae - core::fmt::write::ha0ec7ad9e1aa7104
   2:        0x10adfd929 - std::io::Write::write_fmt::he79f4e513ba146b5
   3:        0x10adef49a - std::panicking::default_hook::{{closure}}::hdf6a192f990c9642
   4:        0x10adef1a5 - std::panicking::default_hook::hc1d0cb86aebc9fbd
   5:        0x10adefb08 - std::panicking::rust_panic_with_hook::hbe9b3056eff949a6
   6:        0x10adef6d2 - rust_begin_unwind
   7:        0x10ae4298b - std::panicking::begin_panic_fmt::hb770b3908b606330
   8:        0x109bc117e - deno::disk_cache::DiskCache::get_cache_filename_with_extension::h9bead961694c7bab
   9:        0x109b0080f - deno::tsc::TsCompiler::get_source_map_file::he10d1f955e964df3
  10:        0x109b00db8 - <deno::tsc::TsCompiler as deno::source_maps::SourceMapGetter>::get_source_map::h9a57a5b6593e518a
  11:        0x1099f068b - deno::source_maps::get_orig_position::h0fcac86f7ca8ea7d
  12:        0x1099efe1c - deno::source_maps::apply_source_map::ha23dbe5088bcb2f3
  13:        0x109b3520c - deno::worker::Worker::new::{{closure}}::h1031ac6f522a4c0e
  14:        0x10a237a47 - deno_core::isolate::exception_to_err_result::he185b15303110714
  15:        0x10a2303bc - deno_core::es_isolate::EsIsolate::mod_evaluate::ha4e54ab131b37f04
  16:        0x109a9df52 - <std::future::GenFuture<T> as core::future::future::Future>::poll::hef4c9d64af759bf3
  17:        0x109a72fbe - <std::future::GenFuture<T> as core::future::future::Future>::poll::h13505288ce1a253d
  18:        0x109a2d958 - std::thread::local::LocalKey<T>::with::hdd75ccf8bc47ed44
  19:        0x109bba4fe - tokio::macros::scoped_tls::ScopedKey<T>::set::h9b3141d2c27c8389
  20:        0x109c50af1 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::ha0be0ef39a82a650
  21:        0x109bbd332 - tokio::runtime::context::enter::h0ff9f498deb68362
  22:        0x109a1ea46 - deno::tokio_util::run_basic::h3538e974f25d293c
  23:        0x109b04a11 - deno::main::h5f6baf7a364ebade
  24:        0x109c1ee46 - std::rt::lang_start::{{closure}}::h9ec716e45ba52b55
  25:        0x10adef5d8 - std::panicking::try::do_call::h69374c200cb9b71d
  26:        0x10ae060cb - __rust_maybe_catch_panic
  27:        0x10adea733 - std::rt::lang_start_internal::h892855ab5abc97d0
  28:        0x109b08509 - main```

**Comment by caspervonb** [comment]
This is a major problem for me right now in iterating on [deno-wasi](https://github.com/caspervonb/deno-wasi); so I'll be taking a look at this myself over the weekend.
