### ISSUE TITLE
Test case is leaking async ops

### ISSUE THREAD

**Issue by iliran11** [denoland/deno#6138]
Hey,
I want to understand this behavior.

I have this sample test.

```
import { assertEquals } from "https://deno.land/std/testing/asserts.ts";
import "https://unpkg.com/@sinonjs/fake-timers@6.0.1/fake-timers.js";

const clock = (window as any).FakeTimers.install();

Deno.test("test spy", () => {
  assertEquals(1, 1);
});
```
 I comment out the clock statement:

```
import { assertEquals } from "https://deno.land/std/testing/asserts.ts";
import "https://unpkg.com/@sinonjs/fake-timers@6.0.1/fake-timers.js";

// const clock = (window as any).FakeTimers.install();

Deno.test("test spy", () => {
  assertEquals(1, 1);
});
```

Then I run again `deno test` and I get this error:

```
failures:

test spy
AssertionError: Test case is leaking async ops.
Before:
  - dispatched: 1
  - completed: 0
After:
  - dispatched: 2
  - completed: 2

Make sure to await all promises returned from Deno APIs before
finishing test case.
    at Object.assert ($deno$/util.ts:33:11)
    at asyncOpSanitizer ($deno$/testing.ts:46:5)
    at async Object.resourceSanitizer [as fn] ($deno$/testing.ts:70:5)
    at async TestApi.[Symbol.asyncIterator] ($deno$/testing.ts:264:11)
    at async Object.runTests ($deno$/testing.ts:345:20)
```

**Comment by nayeemrmn** [comment]
The behaviour of your first code snippet is this, right?
```
$ deno test -A temp.ts
running 1 tests
test test spy ... $ 
```
You didn't write it anywhere. Seems buggy.

**Comment by bartlomieju** [comment]
As pointed by @nayeemrmn problem is most likely in 3rd party code. Not really actionable for Deno, please reopen if problem persists.
