### ISSUE TITLE
Fetch returns: Error trying to connect: Connection reset by peer (os error 54)

### ISSUE THREAD

**Issue by jeffreyvdhondel** [denoland/deno#6197]
`let a = await fetch('https://pictures.vwe.nl');
console.log(a)`

Returns "Error trying to connect: Connection reset by peer (os error 54)"

`deno --version`
- deno 1.0.5
- v8 8.4.300
- typescript 3.9.2

**Comment by gaurav219** [comment]
The URL `https://pictures.vwe.nl` results in a 403 (Forbidden Acess), if you open in a browser.

Correct me, if I misinterpreted your issue.

**Comment by jeffreyvdhondel** [comment]
Yes thats correct i would like to do a.statuscode to know the http status code of the request.

**Comment by iugo** [comment]
```
error: Uncaught ConnectionReset: Connection reset by peer (os error 104)
  at unwrapResponse (rt/10_dispatch_json.js:24:13)
  at sendAsync (rt/10_dispatch_json.js:75:12)
  at async TLSListener.accept (rt/40_tls.js:42:19)
  at async Server.acceptConnAndIterateHttpRequests
  at async MuxAsyncIterator.callIteratorNext
```

**Comment by erfanium** [comment]
Same problem when I fetch with HTTPS, HTTP is ok
```
https://api.kavenegar.com/v1/xxxx/verify/lookup.json
Http: error sending request for url (https://api.kavenegar.com/v1/xxxx/verify/lookup.json): error trying to connect: Connection reset by peer (os error 104)
    at unwrapResponse (deno:cli/rt/10_dispatch_json.js:24:13)
    at sendAsync (deno:cli/rt/10_dispatch_json.js:75:12)
    at async fetch (deno:cli/rt/26_fetch.js:279:29)
    at async sendToKN (main.ts:39:15)
    at async server.ts:27:22

```

**Comment by erfanium** [comment]
@bartlomieju 
This problem is from `rustls`, This can be closed.

**Comment by lucacasonato** [comment]
This error looks to be solved in 1.4:
```
fetch('https://pictures.vwe.nl').then(console.log)
Promise { <pending> }
Response {
  _bodySource: ReadableStream { locked: false },
  _stream: null,
  url: "https://pictures.vwe.nl",
  statusText: "Forbidden",
  status: 403,
  headers: Headers { content-type: text/html, server: Microsoft-IIS/10.0, x-powered-by: ASP.NET, date: Thu, 17 Sep 2020 09:58:52 GMT, content-length: 1233 },
  redirected: false,
  type: "default"
}
```

**Comment by wperron** [comment]
Reopening because we're getting reports of a regression in Discord since at least 1.9, possibly earlier https://discord.com/channels/684898665143206084/689420767620104201/852181010614976533

**Comment by searchableguy** [comment]
> This error looks to be solved in 1.4:
> 
> ```
> fetch('https://pictures.vwe.nl').then(console.log)
> Promise { <pending> }
> Response {
>   _bodySource: ReadableStream { locked: false },
>   _stream: null,
>   url: "https://pictures.vwe.nl",
>   statusText: "Forbidden",
>   status: 403,
>   headers: Headers { content-type: text/html, server: Microsoft-IIS/10.0, x-powered-by: ASP.NET, date: Thu, 17 Sep 2020 09:58:52 GMT, content-length: 1233 },
>   redirected: false,
>   type: "default"
> }
> ```

I tried running the same on deno 1.4.0 and I am getting the same error. 
```
deno 1.4.0
v8 8.7.75
typescript 4.0.2
```
```
deno run -A --log-level=debug test.ts
Deno isolate init with snapshots.
rust:shared_queue:reset
DEBUG JS - cwd /home/user/Projects/deno/import_js
DEBUG JS - args []
main_module file:///home/user/Projects/deno/import_js/test.ts
fetch_source_file specifier: file:///home/user/Projects/deno/import_js/test.ts maybe_referrer: None
⚠️️  Granted read access to "/home/user/Projects/deno/import_js/test.ts"
compiled filename: "/home/user/.cache/deno/gen/file/home/user/Projects/deno/import_js/test.ts.js"
register_complete file:///home/user/Projects/deno/import_js/test.ts
DEBUG JS - sendAsync op_fetch
⚠️️  Granted network access to "https://api.sl.se/"
Before fetch https://api.sl.se
starting new connection: https://api.sl.se/
resolving host="api.sl.se" 
connecting to 194.68.78.66:443 
connected to 194.68.78.66:443 
No cached session for DNSNameRef("api.sl.se")
Not resuming any session
rust:shared_queue:pre-push: op=8, off=812, end=983, len=171, aligned_end=984
rust:shared_queue:push: num_records=1, num_shifted_off=0, head=984
DEBUG JS - sendSync op_apply_source_map
DEBUG JS - sendSync op_apply_source_map
DEBUG JS - sendSync op_apply_source_map
error: Uncaught Http: error sending request for url (https://api.sl.se/): error trying to connect: Connection reset by peer (os error 104)
    at unwrapResponse (deno:cli/rt/10_dispatch_json.js:24:13)
    at sendAsync (deno:cli/rt/10_dispatch_json.js:75:12)
    at async fetch (deno:cli/rt/26_fetch.js:279:29)
 ```

**Comment by jsejcksn** [comment]
I encountered this today as well:

```
% deno
Deno 1.11.1
exit using ctrl+d or close()
> await fetch("https://www.co.walton.fl.us/523/Morrison-Springs");
Uncaught TypeError: error sending request for url (https://www.co.walton.fl.us/523/Morrison-Springs): error trying to connect: Connection reset by peer (os error 54)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async mainFetch (deno:extensions/fetch/26_fetch.js:228:14)
```

and here's the beginning of the verbose `curl` output (I'm truncating it before the headers):

```
% curl -s -v -D - -o /dev/null "https://www.co.walton.fl.us/523/Morrison-Springs"
*   Trying 208.90.188.209...
* TCP_NODELAY set
* Connected to www.co.walton.fl.us (208.90.188.209) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [233 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [85 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3053 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=www.co.walton.fl.us
*  start date: Sep 23 00:00:00 2020 GMT
*  expire date: Sep 23 23:59:59 2021 GMT
*  subjectAltName: host "www.co.walton.fl.us" matched cert's "www.co.walton.fl.us"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> GET /523/Morrison-Springs HTTP/1.1
> Host: www.co.walton.fl.us
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
```

This seemed odd to me:
```
ALPN, server did not agree to a protocol
```

but I'm guessing it just means the server didn't accept http/2?

**Comment by erfanium** [comment]
As I said before, This problem is not about Deno itself. 
### Reproduce steps with reqwest + rustls:
Cargo.toml:
```toml
[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
tokio = { version = "1", features = ["full"] }
```

main.rs
```rs
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let resp = reqwest::get("https://www.co.walton.fl.us/523/Morrison-Springs")
        .await?
        .text()
        .await?;
    println!("{:#?}", resp);
    Ok(())
}
```
output:
```
Error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("www.co.walton.fl.us")), port: None, path: "/523/Morrison-Springs", query: None, fragment: None }, source: hyper::Error(Connect, Custom { kind: Other, error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" } }) }
```

**Comment by rockvcp** [comment]
has anyone had a proper solution on this? 
actually trying this from postman code snippet: js - fetch
`TypeError: error sending request for url (https://3rd-party.api/Login): error trying to connect: Connection reset by peer (os error 54)
    at async mainFetch (deno:ext/fetch/26_fetch.js:259:14)`

actually trying this from postman code snippet: js - fetch but still getting the error above.

```
var myHeaders = new Headers();
myHeaders.append("Content-Type", "application/json");

var raw = JSON.stringify({
  "AccountId": 1234,
  "BranchId": 1234,
  "UserName": "test",
  "Password": "test"
});

var requestOptions = {
  method: 'POST',
  headers: myHeaders,
  body: raw,
  redirect: 'follow'
};

fetch("https://3rd-party.api/Login", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
  ```

appreciate if anyone can help thank you
OS:  MacOS Monterey
Version: 12.2.1

**Comment by in64** [comment]
I have the same problem
```
error: Uncaught (in promise) TypeError: error sending request for url (https://dynamodb.ap-east-1.amazonaws.com/): connection error: Connection reset by peer (os error 104)
    at async mainFetch (deno:ext/fetch/26_fetch.js:280:14)
    at async fetch (deno:ext/fetch/26_fetch.js:490:9)
```
Deno Version:
```
#deno -V
deno 1.20.4
```
centos8

**Comment by aapoalas** [comment]
Verified:

```
deno
Deno 1.30.3
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> await fetch("https://www.co.walton.fl.us/523/Morrison-Springs");
Uncaught TypeError: error sending request for url (https://www.co.walton.fl.us/523/Morrison-Springs): error trying to connect: Connection reset by peer (os error 104)
    at async mainFetch (internal:ext/fetch/26_fetch.js:267:14)
    at async fetch (internal:ext/fetch/26_fetch.js:491:9)
    at async <anonymous>:2:1
```

**Comment by mwk24** [comment]
I'm having the same issue with firebase. (exact same code work with node) Code snippet:

```
const db = getFirestore(app);
  console.log(db);
  const ref = db.collection('xyzzy').limit(10);

  ref.onSnapshot((snapshot) => {
    snapshot.docs.forEach((doc) => {
      console.log(doc.data()['name']);
    });
  },
  (error) => {
    console.log(error);
  });
```
  
  Throws as follows:
  
 ```
 error: Uncaught TypeError: error sending request for url (http://firestore.googleapis.com:443/google.firestore.v1.Firestore/Listen): connection error: Connection reset by peer (os error 54)
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
    at async node:http2:144:28
```

As I mentioned, exact same code works fine with node.

**Comment by louis77** [comment]
The issue is still unsolved in:

deno 1.37.2 (release, aarch64-apple-darwin)
v8 11.8.172.13
typescript 5.2.2

Most external https URLs I try to fetch result in the following error:

```
Uncaught TypeError: error sending request for url (https://[redacted]): error trying to connect: Connection reset by peer (os error 54)
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:504:7)
    at async <anonymous>:2:14
```

Curl says:

```
* Connected to [redacted] port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=*.[redacted]
*  start date: Nov 15 07:21:50 2022 GMT
*  expire date: Dec 17 07:21:49 2023 GMT
*  subjectAltName: host "[redacted]" matched cert's "[redacted]"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*  SSL certificate verify ok.
```

Almost always I try to start a project with Deno I end up with this, for the past two years, making it impossible to use Deno or Deno Deploy.

The same fetch works in Node, Bun, and literally every other runtime/language I tried.

**Comment by iuioiua** [comment]
@louis77, can you provide a snippet? I'm unsure of your use case, but are you aware of [`Deno.HttpClient`](https://deno.land/api@v1.37.2?s=Deno.HttpClient&unstable=)?

**Comment by louis77** [comment]
@iuioiua I've tried with Deno.HttpClient, but it has the same problem. There is nothing wrong with the certificate of the remote, it seems to be a TLS issue that Deno struggles with.

It is just a single line of fetch:

```js
    const resp = await fetch(myUrl, {
        headers: {
            'Authorization': `Basic ${btoa('[user:pass]')}`,
        },
    })
```

With that line, I immediately get the `os error 54` exception as reported by the other commenters on this issue. Since I have no "custom certificate", Deno.httpClient did not make any change here.

Unfortunately I can't share the remote URL here, but if you are on Discord or somewhere I'd be glad to send you the full fetch line so you can test it on your side.

**Comment by pvaldesoiro** [comment]
I found this same error, and got stuck since I am not able to connect to the provider's API. Exactly same fetch work perfectly fine with Node:

deno 1.37.2 (release, aarch64-apple-darwin)
v8 11.8.172.13
typescript 5.2.2

error:
```
cause: TypeError: error sending request for url (https://[redacted]): error trying to connect: Connection reset by peer (os error 54)
    at async Promise.all (index 0)
    at async node:http:432:26
```

curl -v:
```
* Connected to [redacted] port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: [redacted]
*  start date: Sep 22 07:33:14 2023 GMT
*  expire date: Sep 21 07:33:13 2024 GMT
*  subjectAltName: host [redacted] matched cert's [redacted]
*  issuer: [redacted]
*  SSL certificate verify ok.
```

**Comment by Kieran-who** [comment]
Came across the same issue yesterday. App has been operating fine then yesterday with no apparent changes, started seeing the same error for calls to external APIs and APIs from apps running in docker on the same machine.

**Comment by birgersp** [comment]
I am getting this in an import statement:

```
import { config } from "https://deno.land/x/dotenv@v3.2.2/mod.ts"
```

> error: Import 'https://deno.land/x/dotenv@v3.2.2/mod.ts' failed: error sending request for url (https://deno.land/x/dotenv@v3.2.2/mod.ts): error trying to connect: Connection reset by peer (os error 104)

**Comment by dandv** [comment]
@mwk24 Deno fails to resolve `firestore.googleapis.com` for me - #27384.

**Comment by Levminer** [comment]
This still occurs in Deno 2.5.0

**Comment by bartlomieju** [comment]
Closing this out after re-checking on Deno 2.8.1.

The original report is **fixed**: `fetch("https://pictures.vwe.nl")` now returns `403` just like curl, and the other early repro URL (`www.co.walton.fl.us/...`) no longer resolves.

Over the past 5 years this thread has become a catch-all for `Connection reset by peer (os error 54/104)`, but that string is a *symptom* with several unrelated root causes, which is why it's no longer actionable as a single issue:

1. **rustls TLS strictness** (the native-tls vs rustls repro above). Still real: Deno can't connect to TLS 1.0/1.1-only or legacy-cipher (e.g. RC4) servers that OpenSSL/Node accept. Verified: `tls-v1-1.badssl.com` and `rc4.badssl.com` fail in Deno but succeed in curl. This is by design (rustls excludes those), and it now surfaces as a clear `HandshakeFailure`, not a connection reset. If reaching legacy-TLS servers matters to you, please open a focused issue for that specific limitation with the exact endpoint.
2. **TLS intolerance by RST** — a broken middlebox that sends a TCP RST on a modern ClientHello instead of a TLS alert. Server-specific; needs a concrete reproducible endpoint to investigate.
3. **Keep-alive connection-pool reuse races** — tracked in #17627.
4. **DNS resolution failures** — e.g. #27384.

If you're hitting `os error 54/104` on current Deno, please file a new issue with a **reproducible URL** (or a minimal server) and your `deno --version`, and we can route it to the right root cause. A single mega-thread spanning TLS, DNS, connection pooling, and anti-bot blocking can't be triaged effectively.
