### ISSUE TITLE
expand std_lint test to also cover cli/tests/unit 

### ISSUE THREAD

**Issue by ry** [denoland/deno#6302]
current output looks like this
```
> deno lint --unstable cli/tests/unit
(no-namespace) custom typescript modules are outdated
  namespace Deno {
  ~~~~~~~~~~~~~~~~
    at cli/tests/unit/dispatch_minimal_test.ts:30:2

(no-explicit-any) `any` type is not allowed
    var core: any;
              ~~~
    at cli/tests/unit/dispatch_minimal_test.ts:31:14

(ban-ts-comment) ts directives are not allowed
// @ts-expect-error
~~~~~~~~~~~~~~~~~~~
    at cli/tests/unit/unit_test_runner.ts:16:0

(no-namespace) custom typescript modules are outdated
  namespace Deno {
  ~~~~~~~~~~~~~~~~
    at cli/tests/unit/globals_test.ts:50:2

(no-explicit-any) `any` type is not allowed
    var core: any;
              ~~~
    at cli/tests/unit/globals_test.ts:51:14

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:61:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:66:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:70:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:77:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:81:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:87:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:91:10

(no-namespace) custom typescript modules are outdated
  namespace Deno {
  ~~~~~~~~~~~~~~~~
    at cli/tests/unit/dispatch_json_test.ts:24:2

(no-explicit-any) `any` type is not allowed
    var core: any;
              ~~~
    at cli/tests/unit/dispatch_json_test.ts:25:14

(ban-untagged-ignore) Ignore directive requires lint rule code
    // eslint-disable-next-line
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at cli/tests/unit/streams_transform_test.ts:509:4

(no-explicit-any) `any` type is not allowed
    () => new TransformStream({ readableType: "bytes" as any }),
                                                         ~~~
    at cli/tests/unit/streams_transform_test.ts:510:57

(ban-untagged-ignore) Ignore directive requires lint rule code
    // eslint-disable-next-line
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at cli/tests/unit/streams_transform_test.ts:519:4

(no-explicit-any) `any` type is not allowed
    () => new TransformStream({ writableType: "bytes" as any }),
                                                         ~~~
    at cli/tests/unit/streams_transform_test.ts:520:57

(no-empty) Empty block statement
    } catch {}
            ~~
    at cli/tests/unit/fetch_test.ts:750:12

(no-empty) Empty block statement
    } catch {}
            ~~
    at cli/tests/unit/fetch_test.ts:771:12

(no-empty) Empty block statement
  } catch (err) {}
                ~~
    at cli/tests/unit/console_test.ts:611:16

Found 21 problems
```

**Comment by Nasafato** [comment]
Does this mean adding `cli/tests/unit` to the coverage of `std_lint` in [`tests/integration_tests.rs`](https://github.com/denoland/deno/blob/e88d72f101e773728c27306a3639589c1350e4ed/cli/tests/integration_tests.rs#L35)? And then figuring out how to fix the lint errors in the unit tests?

**Comment by ry** [comment]
@Nasafato yes

**Comment by Nasafato** [comment]
PR is ready for review: https://github.com/denoland/deno/pull/6327
