### ISSUE TITLE
deno lint output should go to stdout not stderr

### ISSUE THREAD

**Issue by ry** [denoland/deno#6303]

**Comment by bartlomieju** [comment]
Why? If something goes wrong in TS compiler it goes to stderr as well

**Comment by David-Else** [comment]
It makes sense if it is a lint error to go to standard error.

**Comment by ry** [comment]
It depends on what the main output of the program is. With "deno run" the main output is the program's output. But with "deno lint" what you're expecting is errors.

This is surprising in a bad way:
```
> deno lint --unstable cli/tests/unit/ | wc -l
(ban-ts-comment) ts directives are not allowed
// @ts-expect-error
~~~~~~~~~~~~~~~~~~~
    at cli/tests/unit/unit_test_runner.ts:16:0

(no-namespace) custom typescript modules are outdated
  namespace Deno {
  ~~~~~~~~~~~~~~~~
    at cli/tests/unit/dispatch_json_test.ts:24:2

(no-explicit-any) `any` type is not allowed
    var core: any;
              ~~~
    at cli/tests/unit/dispatch_json_test.ts:25:14

(no-namespace) custom typescript modules are outdated
  namespace Deno {
  ~~~~~~~~~~~~~~~~
    at cli/tests/unit/dispatch_minimal_test.ts:30:2

(no-explicit-any) `any` type is not allowed
    var core: any;
              ~~~
    at cli/tests/unit/dispatch_minimal_test.ts:31:14

(no-namespace) custom typescript modules are outdated
  namespace Deno {
  ~~~~~~~~~~~~~~~~
    at cli/tests/unit/globals_test.ts:50:2

(no-explicit-any) `any` type is not allowed
    var core: any;
              ~~~
    at cli/tests/unit/globals_test.ts:51:14

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:61:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:66:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:70:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:77:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:81:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:87:10

(no-empty) Empty block statement
  } catch {}
          ~~
    at cli/tests/unit/globals_test.ts:91:10

(ban-untagged-ignore) Ignore directive requires lint rule code
    // eslint-disable-next-line
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at cli/tests/unit/streams_transform_test.ts:509:4

(no-explicit-any) `any` type is not allowed
    () => new TransformStream({ readableType: "bytes" as any }),
                                                         ~~~
    at cli/tests/unit/streams_transform_test.ts:510:57

(ban-untagged-ignore) Ignore directive requires lint rule code
    // eslint-disable-next-line
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at cli/tests/unit/streams_transform_test.ts:519:4

(no-explicit-any) `any` type is not allowed
    () => new TransformStream({ writableType: "bytes" as any }),
                                                         ~~~
    at cli/tests/unit/streams_transform_test.ts:520:57

(no-empty) Empty block statement
  } catch (err) {}
                ~~
    at cli/tests/unit/console_test.ts:611:16

(no-empty) Empty block statement
    } catch {}
            ~~
    at cli/tests/unit/fetch_test.ts:750:12

(no-empty) Empty block statement
    } catch {}
            ~~
    at cli/tests/unit/fetch_test.ts:771:12

Found 21 problems
       0
```

**Comment by nayeemrmn** [comment]
-1. `cargo clippy` uses stderr. I'm surprised that ESLint uses stdout.

> But with "deno lint" what you're expecting is errors, nothing else.

I would actually say the expected result is nothing, and errors are always unexpected. That's why we exit with code 1, it's precisely the same logic.

**Comment by ry** [comment]
Ok - `go vet` also outputs to stderr. I retract my request.
