### ISSUE TITLE
Starting REPLServer manually

### ISSUE THREAD

**Issue by kungfooman** [denoland/deno#6311]
Node has: https://nodejs.org/api/repl.html#repl_repl_start_options

So I can simply start a webserver and spawn a REPL in the same context to manipulate the server object for example:

```ts
require("repl").start("custom repl>");
```

 How can I do the same in deno?

**Comment by bartlomieju** [comment]
There's no way to do that currently.

**Comment by kungfooman** [comment]
I asked on Discord and @SyrupThinker shared his attempt (thanks a lot ❤️):

https://gist.githubusercontent.com/SyrupThinker/bdc1e7a3bf359745908be8f93db34830/raw/9139335b0a66b7aa16b180c83b26d72595a03436/repl.ts

Usage like:
```ts
// Filename: test_repl.ts
import * as repl from "./repl.ts";
Object.assign(window, {
	i: 42
});
await repl.replLoop();
```

Only problem so far seems to be that it crashes when objects are too "complex" (e.g. type in `Deno` itself), then it requires:

```shell
deno run --allow-read test_repl.ts
```

Otherwise it will fail like this:

![image](https://user-images.githubusercontent.com/5236548/84852463-38d2af00-b05d-11ea-819d-568d39f15dd0.png)

```
Deno 1.1.0
exit using ctrl+d or close()
> Deno
error: Uncaught PermissionDenied: read access to <main_module>, run again with the --allow-read flag
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.opMainModule [as mainModule] ($deno$/ops/runtime.ts:25:10)
    at createRawObjectString ($deno$/web/console.ts:512:43)
    at createObjectString ($deno$/web/console.ts:592:12)
    at stringify ($deno$/web/console.ts:296:14)
    at stringifyArgs ($deno$/web/console.ts:685:14)
    at Object.Console.log ($deno$/web/console.ts:729:7)
    at replLog (file:///D:/web/libwebgame_node/src/repl_deno.ts:57:11)
    at evaluate (file:///D:/web/libwebgame_node/src/repl_deno.ts:109:7)
```

**Comment by SyrupThinker** [comment]
As noted when I shared this gist, this heavily relies on internal behaviour and might break at any release.

**Comment by caspervonb** [comment]
> As noted when I shared this gist, this heavily relies on internal behaviour and might break at any release.

As of https://github.com/denoland/deno/commit/4c779b5e8ca427faf24c26443a8054004827d450 there are no repl ops.

**Comment by bartlomieju** [comment]
This is supported today via the `node:repl` module, which now ships a full
`REPLServer` implementation and `repl.start()`. You can spawn an interactive
REPL inside a running program (e.g. alongside a web server) and manipulate
objects in its context, matching the Node API referenced above.

```js
// server.mjs
import repl from "node:repl";

const server = { name: "myserver", connections: 0 };

const r = repl.start("custom repl> ");
r.context.server = server; // inject into the REPL context
```

```console
$ deno run -A server.mjs
custom repl> server.name
'myserver'
custom repl> server.connections++
0
custom repl> server.connections
1
```

The CommonJS form works too:

```js
const repl = require("repl");
repl.start("custom repl> ");
```

Verified on Deno 2.8.1. This looks resolved and can probably be closed.

**Comment by bartlomieju** [comment]
Closing as resolved — `node:repl`'s `repl.start()` provides the requested functionality (see example above).
