### ISSUE TITLE
Deno HTTP Server Crashed after running autocannon on it

### ISSUE THREAD

**Issue by Justsnoopy30** [denoland/deno#6390]
```js
error: Uncaught ConnectionReset: An existing connection was forcibly closed by the remote host. (os error 10054)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async TLSListenerImpl.accept ($deno$/tls.ts:31:17)
    at async Server.acceptConnAndIterateHttpRequests (https://deno.land/std@0.57.0/http/server.ts:216:14)
    at async MuxAsyncIterator.callIteratorNext (https://deno.land/std@0.57.0/async/mux_async_iterator.ts:28:29)
[denon] app crashed - waiting for file changes before starting ...
 ```

**Comment by marcosc90** [comment]
Can you please share the server code?

**Comment by Justsnoopy30** [comment]
I will once I get home (GitHub project is currently private) and I am on mobile.

**Comment by Justsnoopy30** [comment]
Fixed by using try/catch on req.respond().
