### ISSUE TITLE
Panic on executing `deno run` on stdin disabled environment

### ISSUE THREAD

**Issue by horihiro** [denoland/deno#6409]
When executing `deno run` on stdin disabled environment, deno panics as following.

```
2020-06-20T07:11:34.862 [Information] Starting worker process:D:\home\site\wwwroot\bin\windows\deno.exe  run --allow-net --allow-env --allow-read "D:\home\site\wwwroot\worker.bundle.js"
2020-06-20T07:11:35.218 [Information] D:\home\site\wwwroot\bin\windows\deno.exe process with Id=16464 started
2020-06-20T07:11:35.484 [Information] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "The handle is invalid." }', cli\ops\io.rs:86:17
2020-06-20T07:11:35.485 [Information] stack backtrace:
2020-06-20T07:11:35.551 [Information] 0:     0x7ff7554d176f - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 1:     0x7ff7554f31bb - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 2:     0x7ff7554c732c - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 3:     0x7ff7554d4ccc - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 4:     0x7ff7554d490f - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 5:     0x7ff7554d54b7 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.552 [Information] 6:     0x7ff7554d503f - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.552 [Information] 7:     0x7ff7554f1b10 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.553 [Information] 8:     0x7ff7554f1963 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.553 [Information] 9:     0x7ff753f0c616 - <unknown>
2020-06-20T07:11:35.553 [Information] 10:     0x7ff754122eca - <unknown>
2020-06-20T07:11:35.553 [Information] 11:     0x7ff753ec4c83 - <unknown>
2020-06-20T07:11:35.553 [Information] 12:     0x7ff753e6949e - <unknown>
2020-06-20T07:11:35.553 [Information] 13:     0x7ff753f7bf69 - <unknown>
2020-06-20T07:11:35.554 [Information] 14:     0x7ff753eb2724 - <unknown>
2020-06-20T07:11:35.554 [Information] 15:     0x7ff753ffc125 - <unknown>
2020-06-20T07:11:35.554 [Information] 16:     0x7ff753f57160 - <unknown>
2020-06-20T07:11:35.554 [Information] 17:     0x7ff7540e9326 - <unknown>
2020-06-20T07:11:35.554 [Information] 18:     0x7ff7554d56ca - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.559 [Information] 19:     0x7ff753f5b027 - <unknown>
2020-06-20T07:11:35.559 [Information] 20:     0x7ff755503df0 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.559 [Information] 21:     0x7fff7e5a84d4 - BaseThreadInitThunk
2020-06-20T07:11:35.582 [Information] 22:     0x7fff80cae8b1 - RtlUserThreadStart
```

According to the above stack, it is caused by [this change](https://github.com/denoland/deno/commit/1e0808d501cf9adea65e7cacd123ea4fea06a13a#diff-52a4a7cdf78afa52dbd3506067839baa) in https://github.com/denoland/deno/pull/6126 .

I think that deno shouldn't panic even if stdin is disabled, because server side application doesn't necessarily require interaction using stdin. 

I would appreciate your comment.

Thanks
Hiro

Related to https://github.com/anthonychu/azure-functions-deno-worker/issues/13#issuecomment-646988127
/cc @anthonychu

**Comment by caspervonb** [comment]
Yeah this should just be reporting EBADF or ENODEV to the caller.

**Comment by horihiro** [comment]
Thanks @caspervonb 
Can this be improved on deno side?

**Comment by horihiro** [comment]
@ry @bartlomieju 
Sorry for bothering you

Do you have any comment?

**Comment by ry** [comment]
@horihiro Sorry for the delayed response - it would be very helpful if you could provide a small standalone example that demonstrates the panic. We can debug and fix it then.

**Comment by horihiro** [comment]
Thanks @ry 

I tried to reproduce this on simple standalone app.

But I couldn't do it now, except combination of Azure Web App and aspnetcore app, which invokes deno 1.1.x by `Process#Start` like [Azure Functions Host](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/ProcessManagement/DefaultWorkerProcessFactory.cs#L26)

**Comment by caspervonb** [comment]
So I can explain why this happens; we're making the assumption that GetStdHandle always returns a value but it _can_ return NULL on error.

Coming with an integration test for this turned out to be non-trivial, as setting it to `Stdio::null()` means redirect to the null device so it returns valid handles; I'd guess that calling `SetStdHandle(STD_INPUT_HANDLE, NULL)` would replicate the environment. Maybe PowerShell get access to this?

One possible workaround is to ditch the forced unwrap() that panics, change the signature of get_stdio to `Result<StreamResourceHolder>` and check them before adding to the resource table.

**Comment by horihiro** [comment]
Sorry for delay.

I confirmed that following simple console app can reproduce this behavior.

CallerConsoleApp.cs
```c#
using System;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;

namespace CallerConsoleApp
{
    
   class Program
    {
        private const int STD_INPUT_HANDLE = -10;
        [DllImport("kernel32.dll")]
        private static extern void SetStdHandle(int nStdHandle, IntPtr handle);

        static void Main(string[] args)
        {
            SetStdHandle(STD_INPUT_HANDLE, (IntPtr)null);
            string executable = @"C:\Users\horihiro\.deno\bin\deno.exe";
            var startInfo = new ProcessStartInfo(executable)
            {
                RedirectStandardInput = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                ErrorDialog = false,
                Arguments = @"run -A file1.ts",
            };
            Process p = new Process { StartInfo = startInfo };
            p.Start();
            StreamReader ereader = p.StandardError;
            string error = ereader.ReadToEnd();

            // Write the redirected output to this application's window.
            Console.Error.WriteLine(error);
            p.WaitForExit();
        }
    }
}
```

file1.ts
```ts
const sleep = (msec:number) => new Promise(resolve => setTimeout(resolve, msec));

console.log('Start');
await sleep(10000);
console.log('Finish')
```

**Comment by Spoonbender** [comment]
I'd like to tackle this one

**Comment by Spoonbender** [comment]
First, @horihiro 's reproduction works well 👍🏼

Second, while this repro is specific to Windows, **a similar problem can also occur on Linux**.
In Linux, you can also close the `stdin` handle (see: https://superuser.com/questions/813472/how-do-i-close-stdin-in-a-shell-script )
So, the following scenario fails on Linux:
```bash
~/.deno/bin/deno run -A /tmp/test2.ts<&-
```

TypeScript file:
```ts
import { readLines } from "https://deno.land/std/io/bufio.ts";

async function main() {
   for await (const line of readLines(Deno.stdin)) {
      console.log("read line", line);
  }
}

console.log("reading lines from stdin");
main();
```

prints:
```
reading lines from stdin
error: Uncaught TypeError: Invalid argument (os error 22)
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.read ($deno$/ops/io.ts:39:17)
    at async readDelim (https://deno.land/std/io/bufio.ts:649:20)
    at async readStringDelim (https://deno.land/std/io/bufio.ts:699:20)
    at async readLines (https://deno.land/std/io/bufio.ts:709:3)
    at async main (file:///tmp/test2.ts:4:21)
```

Third, this issue is probably reproducible with regards to missing `stdout` and `stderr` as well.

For detection in the Windows case: 
The `GetStdHandle` API in Windows does document three possible outcomes (see: https://docs.microsoft.com/en-us/windows/console/getstdhandle )
1. Success: returns a handle
2. The function fails, return value is INVALID_HANDLE_VALUE (which is -1), and additional details are available via `GetLastError`
3. If there is no associated handle, the function returns `NULL`, which is our case

So by comparing the returned handle to the null pointer, we can detect the 3rd outcome. 
See example in this commit: https://github.com/Spoonbender/deno/commit/d39fcf996cefa5664ecd7f25428d258319c7cdf1 (panics as expected in the repro)

**Comment by caspervonb** [comment]
> error: Uncaught TypeError: Invalid argument (os error 22)
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.read ($deno$/ops/io.ts:39:17)
    at async readDelim (https://deno.land/std/io/bufio.ts:649:20)
    at async readStringDelim (https://deno.land/std/io/bufio.ts:699:20)
    at async readLines (https://deno.land/std/io/bufio.ts:709:3)
    at async main (file:///tmp/test2.ts:4:21)

This is fine as it's throwing EINVAL.

> Third, this issue is probably reproducible with regards to missing stdout and stderr as well.

Yep should give all 3 stdio streams the same treatment.

> So by comparing the returned handle to the null pointer, we can detect the 3rd outcome.

Yeah just don't unwrap() in cli/ops/io.rs; this requires a bit of refactoring as it's initialized in a lazy static block and the call-sites of get_stdio expects to **always** get all streams no matter what.

**Comment by Spoonbender** [comment]
@caspervonb yup I'll follow your suggestion from https://github.com/denoland/deno/issues/6409#issuecomment-647881600 - ditch the `unwrap()`, expose a `Result` (or `Option`) and fix the callers.

**Comment by horihiro** [comment]
I really appreciate your help!
I'm looking forward to the next release.

Thanks

**Comment by caspervonb** [comment]
> I'm looking forward to the next release.

Should be dropping on Monday.
