### ISSUE TITLE
Bad Request body type: URLSearchParamsImpl

### ISSUE THREAD

**Issue by ccouzens** [denoland/deno#6415]
When I try and use a URLSearchParams as a request body, I get an error saying it's rejected.

Code to reproduce:

In deno:
```javascript
> new Request('/', {method: 'POST', body: new URLSearchParams({hello: 'world'})})
Uncaught Error: Bad Request body type: URLSearchParamsImpl
    at validateBodyType ($deno$/web/body.ts:31:9)
    at new Body ($deno$/web/body.ts:87:5)
    at new Request ($deno$/web/request.ts:73:5)
    at <unknown>:3:1
    at evaluate ($deno$/repl.ts:54:34)
    at Object.replLoop ($deno$/repl.ts:156:13)
```

In Firefox:
```javascript
new Request('/', {method: 'POST', body: new URLSearchParams({hello: 'world'})})
Request { method: "POST", url: "https://developer.mozilla.org/", headers: Headers, destination: "", referrer: "about:client", referrerPolicy: "", mode: "cors", credentials: "same-origin", cache: "default", redirect: "follow" }
```

In Chrome it works much the same as in Firefox.

In Chrome and Firefox, when I `fetch` the request object, I can confirm the request body is `hello=world`.

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request) says
> body: Any body that you want to add to your request: this can be a Blob, BufferSource, FormData, URLSearchParams, USVString, or ReadableStream object. Note that a request using the GET or HEAD method cannot have a body.

Deno should support using a `URLSearchParams` object as a `Request` body.

To work around this, I've used `toString` on it which works in Deno and in the browsers:

```javascript
new Request('/', {method: 'POST', body: new URLSearchParams({hello: 'world'}).toString()})
```

PS: Thank you for making Deno - it is awesome :smiley:

**Comment by ccouzens** [comment]
I'm going to try and fix this myself.

**Comment by ccouzens** [comment]
The fix is merged, so I'll close
