### ISSUE TITLE
Incorrect relative module imports from remote scripts

### ISSUE THREAD

**Issue by NewLunarFire** [denoland/deno#645]
The following

_main.ts_
```typescript
import bar from "https://example.com/bar.ts"
```

_bar.ts_
```typescript
import foo from "./foo.ts"
```

In the second example, foo.ts ends up resolving to "$HOME/.deno/deps/example.com/foo.ts" instead of the expected "https://example.com/foo.ts".

**Comment by DanielRamosAcosta** [comment]
I might be having the same error at v0.1.3. I have [this source file at Gist](https://gist.githubusercontent.com/DanielRamosAcosta/ad514503b1c7cf8290dadb96a5fddee9/raw/4733e267f05d20110ba962c4418bab5e98abfe93/factorial.ts) but my local module isn't able to import it:

`myimport.ts`:
```typescript
import { factorial } from "https://gist.githubusercontent.com/DanielRamosAcosta/ad514503b1c7cf8290dadb96a5fddee9/raw/4733e267f05d20110ba962c4418bab5e98abfe93/factorial.ts"

console.log(factorial(10))
```

When executing I'm having the following error:
```
./deno myimport.ts
Error: Cannot resolve module "https://gist.githubusercontent.com/DanielRamosAcosta/ad514503b1c7cf8290dadb96a5fddee9/raw/4733e267f05d20110ba962c4418bab5e98abfe93/factorial.ts" from "/home/daniel/Documentos/Trabajo/deno-test/myimport.ts".
  Invalid source code or file name.
    at throwResolutionError (deno/js/compiler.ts:128:9)
    at DenoCompiler.resolveModule (deno/js/compiler.ts:526:14)
    at DenoCompiler.resolveModuleName (deno/js/compiler.ts:551:33)
    at moduleNames.map.name (deno/js/compiler.ts:679:33)
    at Array.map (<anonymous>)
    at DenoCompiler.resolveModuleNames (deno/js/compiler.ts:671:24)
    at Object.compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:111649:117)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:82561:106)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:82768:24)
    at processImportedModules (deno/third_party/node_modules/typescript/lib/typescript.js:84005:35)
```

Deno version:
```
deno: 0.1.3
v8: 7.0.247-deno
```

Any ideas?

**Comment by ry** [comment]
@DanielRamosAcosta I was unable to repeat the error - it works for me.... I'm not sure what's happening

**Comment by johnsoncodehk** [comment]
@ry I am trying to run this example from https://deno.land/:
```ts
import { serve } from "https://deno.land/x/http/server.ts";
const s = serve("0.0.0.0:8000");

async function main() {
  for await (const req of s) {
    req.respond({ body: new TextEncoder().encode("Hello World\n") });
  }
}

main();
```
Then I got this error:
```
Uncaught NotFound: Cannot resolve module "../util/deferred.ts" from "/Users/johnsonchu/.deno/deps/https/deno.land/x/http/server.ts"
```

I guess you can reproduce this error after clearing the cache directory.

**Comment by hayd** [comment]
@johnsoncodehk Please try:

```
import { serve } from "https://deno.land/x/std@v0.2.8/http/http.ts";
```

**Comment by johnsoncodehk** [comment]
@hayd Yes, it works, thank you!
And I found that the reason is that https://deno.land/x/util/deferred.ts failed to download.
