### ISSUE TITLE
Nested imports failing

### ISSUE THREAD

**Issue by ykis-0-0** [denoland/deno#6497]
When re-exporting modules, `deno` will throw an error.
`deno` binary used: `x86_64-pc-windows-msvc`.

<details>
<summary>Log:</summary>

```
Download https://deno.land/std@0.58.0/log/mod.ts
Download https://deno.land/std@0.58.0/fs/mod.ts
Download https://deno.land/std@0.58.0/log/logger.ts
Download https://deno.land/std@0.58.0/log/handlers.ts
Download https://deno.land/std@0.58.0/_util/assert.ts
Download https://deno.land/std@0.58.0/log/levels.ts
Download https://deno.land/std@0.58.0/fs/empty_dir.ts
Download https://deno.land/std@0.58.0/fs/ensure_dir.ts
Download https://deno.land/std@0.58.0/fs/ensure_file.ts
Download https://deno.land/std@0.58.0/fs/ensure_link.ts
Download https://deno.land/std@0.58.0/fs/ensure_symlink.ts
Download https://deno.land/std@0.58.0/fs/exists.ts
Download https://deno.land/std@0.58.0/fs/expand_glob.ts
Download https://deno.land/std@0.58.0/fs/move.ts
Download https://deno.land/std@0.58.0/fs/copy.ts
Download https://deno.land/std@0.58.0/fs/read_file_str.ts
Download https://deno.land/std@0.58.0/fs/write_file_str.ts
Download https://deno.land/std@0.58.0/fs/read_json.ts
Download https://deno.land/std@0.58.0/fs/write_json.ts
Download https://deno.land/std@0.58.0/fs/walk.ts
Download https://deno.land/std@0.58.0/fs/eol.ts
Download https://deno.land/std@0.58.0/fs/_util.ts
Download https://deno.land/std@0.58.0/path/mod.ts
Download https://deno.land/std@0.58.0/fmt/colors.ts
Download https://deno.land/std@0.58.0/io/bufio.ts
Download https://deno.land/std@0.58.0/path/_constants.ts
Download https://deno.land/std@0.58.0/path/win32.ts
Download https://deno.land/std@0.58.0/path/posix.ts
Download https://deno.land/std@0.58.0/path/common.ts
Download https://deno.land/std@0.58.0/path/separator.ts
Download https://deno.land/std@0.58.0/path/_interface.ts
Download https://deno.land/std@0.58.0/path/glob.ts
Download https://deno.land/std@0.58.0/io/util.ts
Download https://deno.land/std@0.58.0/path/_globrex.ts
Download https://deno.land/std@0.58.0/path/_util.ts
Compile file:///C:/Users/user/Desktop/Rpi/deno-x86_64-pc-windows-msvc/mod.mjs
error: Failed to get compiled source code of https://deno.land/std@0.58.0/log/mod.ts.
Reason: 系統找不到指定的路徑。 (os error 3)
```
</details>

Files used (all are in the same directory):

start.bat (I tried but the `--unstable` seems doesn't matter):
```batch
@echo off
SETLOCAL
SET DENO_DIR=%~dp0\deno_modules
%~dp0\deno.exe run -A -c .\tsconfig.json --unstable -L info .\mod.mjs
PAUSE > NUL
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "allowJs": false,
    "checkJs": false
  }
}
```

mod.mjs:
```mjs
import * as std from './std.mjs';
```

std.mjs:
```mjs
export * as log from 'https://deno.land/std@0.58.0/log/mod.ts';
export * as fs from 'https://deno.land/std@0.58.0/fs/mod.ts';
```

If it's my fault please also kindly point it out since I am a newcomer to coding.

**Comment by bartlomieju** [comment]
@ykis-0-0 try changing `checkJs` to true - if you switch it off then any `.ts` imports from `.js` imports won't get compiled

**Comment by ykis-0-0** [comment]
@bartlomieju that works, thanks!
and by the way, is there any method to compile a single import as JavaScript but not TypeScript?
importing an `.mjs` file on the internet with `"allowJs": true` in `tsconfig.json` will produce a bunch of errors like this:

<details>
<summary>Log:</summary>

```
Download https://github.com/janl/mustache.js/raw/master/mustache.mjs
Download https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs
Compile file:///C:/Users/YouSuck/Desktop/Rpi/deno-x86_64-pc-windows-msvc/mod.mjs
error: TS7006 [ERROR]: Parameter 'object' implicitly has an 'any' type.
function isFunction (object) {
                     ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:11:22

TS7006 [ERROR]: Parameter 'obj' implicitly has an 'any' type.
function typeStr (obj) {
                  ~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:19:19

TS7006 [ERROR]: Parameter 'string' implicitly has an 'any' type.
function escapeRegExp (string) {
                       ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:23:24

TS7006 [ERROR]: Parameter 'obj' implicitly has an 'any' type.
function hasProperty (obj, propName) {
                      ~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:31:23

TS7006 [ERROR]: Parameter 'propName' implicitly has an 'any' type.
function hasProperty (obj, propName) {
                           ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:31:28

TS7006 [ERROR]: Parameter 'primitive' implicitly has an 'any' type.
function primitiveHasOwnProperty (primitive, propName) {
                                  ~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:39:35

TS7006 [ERROR]: Parameter 'propName' implicitly has an 'any' type.
function primitiveHasOwnProperty (primitive, propName) {
                                             ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:39:46

TS7006 [ERROR]: Parameter 're' implicitly has an 'any' type.
function testRegExp (re, string) {
                     ~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:51:22

TS7006 [ERROR]: Parameter 'string' implicitly has an 'any' type.
function testRegExp (re, string) {
                         ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:51:26

TS7006 [ERROR]: Parameter 'string' implicitly has an 'any' type.
function isWhitespace (string) {
                       ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:56:24

TS7006 [ERROR]: Parameter 'string' implicitly has an 'any' type.
function escapeHtml (string) {
                     ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:71:22

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ '&': string; '<': string; '>': string; '"': string; "'": string; '/': string; '`': string; '=': string; }'.
  No index signature with a parameter of type 'string' was found on type '{ '&': string; '<': string; '>': string; '"': string; "'": string; '/': string; '`': string; '=': string; }'.
    return entityMap[s];
           ~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:73:12

TS7006 [ERROR]: Parameter 'template' implicitly has an 'any' type.
function parseTemplate (template, tags) {
                        ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:109:25

TS7006 [ERROR]: Parameter 'tags' implicitly has an 'any' type.
function parseTemplate (template, tags) {
                                  ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:109:35

TS7034 [ERROR]: Variable 'tokens' implicitly has type 'any[]' in some locations where its type cannot be determined.
  var tokens = [];       // Buffer to hold the tokens
      ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:114:7

TS7034 [ERROR]: Variable 'spaces' implicitly has type 'any[]' in some locations where its type cannot be determined.
  var spaces = [];       // Indices of whitespace tokens on the current line
      ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:115:7

TS7005 [ERROR]: Variable 'tokens' implicitly has an 'any[]' type.
        delete tokens[spaces.pop()];
               ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:126:16

TS7005 [ERROR]: Variable 'spaces' implicitly has an 'any[]' type.
        delete tokens[spaces.pop()];
                      ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:126:23

TS7006 [ERROR]: Parameter 'tagsToCompile' implicitly has an 'any' type.
  function compileTags (tagsToCompile) {
                        ~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:136:25

TS7009 [ERROR]: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
  var scanner = new Scanner(template);
                ~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:150:17

TS7006 [ERROR]: Parameter 'tokens' implicitly has an 'any' type.
function squashTokens (tokens) {
                       ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:255:24

TS7006 [ERROR]: Parameter 'tokens' implicitly has an 'any' type.
function nestTokens (tokens) {
                     ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:282:22

TS7034 [ERROR]: Variable 'nestedTokens' implicitly has type 'any[]' in some locations where its type cannot be determined.
  var nestedTokens = [];
      ~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:283:7

TS7005 [ERROR]: Variable 'nestedTokens' implicitly has an 'any[]' type.
  var collector = nestedTokens;
                  ~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:284:19

TS7005 [ERROR]: Variable 'nestedTokens' implicitly has an 'any[]' type.
        collector = sections.length > 0 ? sections[sections.length - 1][4] : nestedTokens;
                                                                             ~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:301:78

TS7005 [ERROR]: Variable 'nestedTokens' implicitly has an 'any[]' type.
  return nestedTokens;
         ~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:308:10

TS7006 [ERROR]: Parameter 'string' implicitly has an 'any' type.
function Scanner (string) {
                  ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:315:19

TS2683 [ERROR]: 'this' implicitly has type 'any' because it does not have a type annotation.
  this.string = string;
  ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:316:3

TS2683 [ERROR]: 'this' implicitly has type 'any' because it does not have a type annotation.
  this.tail = string;
  ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:317:3

TS2683 [ERROR]: 'this' implicitly has type 'any' because it does not have a type annotation.
  this.pos = 0;
  ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:318:3

TS7006 [ERROR]: Parameter 're' implicitly has an 'any' type.
Scanner.prototype.scan = function scan (re) {
                                        ~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:332:41

TS7006 [ERROR]: Parameter 're' implicitly has an 'any' type.
Scanner.prototype.scanUntil = function scanUntil (re) {
                                                  ~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:350:51

TS7006 [ERROR]: Parameter 'view' implicitly has an 'any' type.
function Context (view, parentContext) {
                  ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:375:19

TS7006 [ERROR]: Parameter 'parentContext' implicitly has an 'any' type.
function Context (view, parentContext) {
                        ~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:375:25

TS2683 [ERROR]: 'this' implicitly has type 'any' because it does not have a type annotation.
  this.view = view;
  ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:376:3

TS2683 [ERROR]: 'this' implicitly has type 'any' because it does not have a type annotation.
  this.cache = { '.': this.view };
  ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:377:3

TS2683 [ERROR]: 'this' implicitly has type 'any' because it does not have a type annotation.
  this.cache = { '.': this.view };
                      ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:377:23

TS2683 [ERROR]: 'this' implicitly has type 'any' because it does not have a type annotation.
  this.parent = parentContext;
  ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:378:3

TS7006 [ERROR]: Parameter 'view' implicitly has an 'any' type.
Context.prototype.push = function push (view) {
                                        ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:385:41

TS7009 [ERROR]: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
  return new Context(view, this);
         ~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:386:10

TS7006 [ERROR]: Parameter 'name' implicitly has an 'any' type.
Context.prototype.lookup = function lookup (name) {
                                            ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:393:45

TS2683 [ERROR]: 'this' implicitly has type 'any' because it does not have a type annotation.
  this.templateCache = {
  ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:482:3

TS7006 [ERROR]: Parameter 'key' implicitly has an 'any' type.
    set: function set (key, value) {
                       ~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:484:24

TS7006 [ERROR]: Parameter 'value' implicitly has an 'any' type.
    set: function set (key, value) {
                            ~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:484:29

TS7006 [ERROR]: Parameter 'key' implicitly has an 'any' type.
    get: function get (key) {
                       ~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:487:24

TS7006 [ERROR]: Parameter 'template' implicitly has an 'any' type.
Writer.prototype.parse = function parse (template, tags) {
                                         ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:510:42

TS7006 [ERROR]: Parameter 'tags' implicitly has an 'any' type.
Writer.prototype.parse = function parse (template, tags) {
                                                   ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:510:52

TS7006 [ERROR]: Parameter 'template' implicitly has an 'any' type.
Writer.prototype.render = function render (template, view, partials, tags) {
                                           ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:536:44

TS7006 [ERROR]: Parameter 'view' implicitly has an 'any' type.
Writer.prototype.render = function render (template, view, partials, tags) {
                                                     ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:536:54

TS7006 [ERROR]: Parameter 'partials' implicitly has an 'any' type.
Writer.prototype.render = function render (template, view, partials, tags) {
                                                           ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:536:60

TS7006 [ERROR]: Parameter 'tags' implicitly has an 'any' type.
Writer.prototype.render = function render (template, view, partials, tags) {
                                                                     ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:536:70

TS7009 [ERROR]: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
  var context = (view instanceof Context) ? view : new Context(view, undefined);
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:538:52

TS7006 [ERROR]: Parameter 'tokens' implicitly has an 'any' type.
Writer.prototype.renderTokens = function renderTokens (tokens, context, partials, originalTemplate, tags) {
                                                       ~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:551:56

TS7006 [ERROR]: Parameter 'context' implicitly has an 'any' type.
Writer.prototype.renderTokens = function renderTokens (tokens, context, partials, originalTemplate, tags) {
                                                               ~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:551:64

TS7006 [ERROR]: Parameter 'partials' implicitly has an 'any' type.
Writer.prototype.renderTokens = function renderTokens (tokens, context, partials, originalTemplate, tags) {
                                                                        ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:551:73

TS7006 [ERROR]: Parameter 'originalTemplate' implicitly has an 'any' type.
Writer.prototype.renderTokens = function renderTokens (tokens, context, partials, originalTemplate, tags) {
                                                                                  ~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:551:83

TS7006 [ERROR]: Parameter 'tags' implicitly has an 'any' type.
Writer.prototype.renderTokens = function renderTokens (tokens, context, partials, originalTemplate, tags) {
                                                                                                    ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:551:101

TS7006 [ERROR]: Parameter 'token' implicitly has an 'any' type.
Writer.prototype.renderSection = function renderSection (token, context, partials, originalTemplate) {
                                                         ~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:574:58

TS7006 [ERROR]: Parameter 'context' implicitly has an 'any' type.
Writer.prototype.renderSection = function renderSection (token, context, partials, originalTemplate) {
                                                                ~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:574:65

TS7006 [ERROR]: Parameter 'partials' implicitly has an 'any' type.
Writer.prototype.renderSection = function renderSection (token, context, partials, originalTemplate) {
                                                                         ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:574:74

TS7006 [ERROR]: Parameter 'originalTemplate' implicitly has an 'any' type.
Writer.prototype.renderSection = function renderSection (token, context, partials, originalTemplate) {
                                                                                   ~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:574:84

TS7006 [ERROR]: Parameter 'template' implicitly has an 'any' type.
  function subRender (template) {
                      ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:581:23

TS7006 [ERROR]: Parameter 'token' implicitly has an 'any' type.
Writer.prototype.renderInverted = function renderInverted (token, context, partials, originalTemplate) {
                                                           ~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:608:60

TS7006 [ERROR]: Parameter 'context' implicitly has an 'any' type.
Writer.prototype.renderInverted = function renderInverted (token, context, partials, originalTemplate) {
                                                                  ~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:608:67

TS7006 [ERROR]: Parameter 'partials' implicitly has an 'any' type.
Writer.prototype.renderInverted = function renderInverted (token, context, partials, originalTemplate) {
                                                                           ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:608:76

TS7006 [ERROR]: Parameter 'originalTemplate' implicitly has an 'any' type.
Writer.prototype.renderInverted = function renderInverted (token, context, partials, originalTemplate) {
                                                                                     ~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:608:86

TS7006 [ERROR]: Parameter 'partial' implicitly has an 'any' type.
Writer.prototype.indentPartial = function indentPartial (partial, indentation, lineHasNonSpace) {
                                                         ~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:617:58

TS7006 [ERROR]: Parameter 'indentation' implicitly has an 'any' type.
Writer.prototype.indentPartial = function indentPartial (partial, indentation, lineHasNonSpace) {
                                                                  ~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:617:67

TS7006 [ERROR]: Parameter 'lineHasNonSpace' implicitly has an 'any' type.
Writer.prototype.indentPartial = function indentPartial (partial, indentation, lineHasNonSpace) {
                                                                               ~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:617:80

TS7006 [ERROR]: Parameter 'token' implicitly has an 'any' type.
Writer.prototype.renderPartial = function renderPartial (token, context, partials, tags) {
                                                         ~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:628:58

TS7006 [ERROR]: Parameter 'context' implicitly has an 'any' type.
Writer.prototype.renderPartial = function renderPartial (token, context, partials, tags) {
                                                                ~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:628:65

TS7006 [ERROR]: Parameter 'partials' implicitly has an 'any' type.
Writer.prototype.renderPartial = function renderPartial (token, context, partials, tags) {
                                                                         ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:628:74

TS7006 [ERROR]: Parameter 'tags' implicitly has an 'any' type.
Writer.prototype.renderPartial = function renderPartial (token, context, partials, tags) {
                                                                                   ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:628:84

TS7006 [ERROR]: Parameter 'token' implicitly has an 'any' type.
Writer.prototype.unescapedValue = function unescapedValue (token, context) {
                                                           ~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:644:60

TS7006 [ERROR]: Parameter 'context' implicitly has an 'any' type.
Writer.prototype.unescapedValue = function unescapedValue (token, context) {
                                                                  ~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:644:67

TS7006 [ERROR]: Parameter 'token' implicitly has an 'any' type.
Writer.prototype.escapedValue = function escapedValue (token, context) {
                                                       ~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:650:56

TS7006 [ERROR]: Parameter 'context' implicitly has an 'any' type.
Writer.prototype.escapedValue = function escapedValue (token, context) {
                                                              ~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:650:63

TS2722 [ERROR]: Cannot invoke an object which is possibly 'undefined'.
    return typeof value === 'number' ? String(value) : mustache.escape(value);
                                                       ~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:653:56

TS7006 [ERROR]: Parameter 'token' implicitly has an 'any' type.
Writer.prototype.rawValue = function rawValue (token) {
                                               ~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:656:48

TS7009 [ERROR]: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
var defaultWriter = new Writer();
                    ~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:688:21

TS2322 [ERROR]: Type '() => any' is not assignable to type 'undefined'.
mustache.clearCache = function clearCache () {
~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:693:1

TS2322 [ERROR]: Type '(template: any, tags: any) => any' is not assignable to type 'undefined'.
mustache.parse = function parse (template, tags) {
~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:702:1

TS7006 [ERROR]: Parameter 'template' implicitly has an 'any' type.
mustache.parse = function parse (template, tags) {
                                 ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:702:34

TS7006 [ERROR]: Parameter 'tags' implicitly has an 'any' type.
mustache.parse = function parse (template, tags) {
                                           ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:702:44

TS2322 [ERROR]: Type '(template: any, view: any, partials: any, tags: any) => any' is not assignable to type 'undefined'.
mustache.render = function render (template, view, partials, tags) {
~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:712:1

TS7006 [ERROR]: Parameter 'template' implicitly has an 'any' type.
mustache.render = function render (template, view, partials, tags) {
                                   ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:712:36

TS7006 [ERROR]: Parameter 'view' implicitly has an 'any' type.
mustache.render = function render (template, view, partials, tags) {
                                             ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:712:46

TS7006 [ERROR]: Parameter 'partials' implicitly has an 'any' type.
mustache.render = function render (template, view, partials, tags) {
                                                   ~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:712:52

TS7006 [ERROR]: Parameter 'tags' implicitly has an 'any' type.
mustache.render = function render (template, view, partials, tags) {
                                                             ~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:712:62

TS2322 [ERROR]: Type '(string: any) => string' is not assignable to type 'undefined'.
mustache.escape = escapeHtml;
~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:724:1

TS2322 [ERROR]: Type '(string: any) => void' is not assignable to type 'undefined'.
mustache.Scanner = Scanner;
~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:727:1

TS2322 [ERROR]: Type '(view: any, parentContext: any) => void' is not assignable to type 'undefined'.
mustache.Context = Context;
~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:728:1

TS2322 [ERROR]: Type '() => void' is not assignable to type 'undefined'.
mustache.Writer = Writer;
~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/janl/mustache.js/master/mustache.mjs:729:1

Found 93 errors.
```
</details>

Is there any way to deal with it without downloading the source file and adding `// @ts-nocheck`?

**Comment by bartlomieju** [comment]
@ykis-0-0 you might find this chapter useful: https://deno.land/manual/getting_started/typescript#using-external-type-definitions

**Comment by ykis-0-0** [comment]
@bartlomieju Thank you very much! I didn't know it needed a declaration file since I didn't use TypeScript, and now I finally resorted to use DefinitelyTyped.
