### ISSUE TITLE
 Maximum call stack size exceeded on res.arrayBuffer()

### ISSUE THREAD

**Issue by marcosc90** [denoland/deno#6536]
To replicate:

```
# create big file
truncate -s 2g 2gb.bin
```

**server.js**
```
import { serve } from 'https://deno.land/std/http/mod.ts';

const server = serve({ port: 3000 })

for await (const req of server) {
        const file = await Deno.open('./2gb.bin');
        req.respond({ body: file })
}
```

**client.js**
```
const res = await fetch('http://localhost:3000');
const ab = await res.arrayBuffer();
````

Throws:

```
error: Uncaught RangeError: Maximum call stack size exceeded
    at bufferFromStream ($deno$/web/body.ts:76:10)
    at async file:///tmp/client.js:2:12
```

**Comment by marcosc90** [comment]
I'm working on a fix
