### ISSUE TITLE
BUG: Try Finally errors when Finally is empty

### ISSUE THREAD

**Issue by zinthose** [denoland/deno#6545]
When using a 'try finally` block, if the finally block is empty an error is raised as if the try block was not there.

## Environment
```javascript
// Deno.version
{ deno: "1.1.2", v8: "8.5.216", typescript: "3.9.2" }
```
```sh
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
```

## Test Code
The following is a deno test chain to demonstrate and my output from the test.
```typescript
/** DenoBug.ts
 * FileName: DenoBug.ts
 * Test: deno test DenoBug.ts
 */

import { assertEquals } from "https://deno.land/std/testing/asserts.ts";

function tryCatchA(value:string | undefined): any {
  try {
    value = JSON.parse(value as string);
  } catch {
    // Do nothing
  }
  return value;
}

function tryFinallyA(value:string | undefined): any {
  try {
    value = JSON.parse(value as string);
  } finally {
    // Do nothing
  }
  return value;
}

function tryCatchB(value:string | undefined): any {
  try {
    value = JSON.parse(value as string);
  } catch {
    return value;
  }
  return value;
}

function tryFinallyB(value:string | undefined): any {
  try {
    value = JSON.parse(value as string);
  } finally {
    return value;
  }
}

/** Start Tests outside Catch/Finally */
Deno.test("tryCatchA", () => {
  
  assertEquals(
    tryCatchA('{"Fu": "Bar"}'),
    {"Fu": "Bar"},
    "tryCatchA: JSON Parse Failed"
  );

  assertEquals(
    tryCatchA('{"Fu" = "Bar"}'),
    '{"Fu" = "Bar"}',
    "tryCatchA: String Parse Failed"
  );

});

Deno.test("tryFinallyA", () => {
  
  assertEquals(
    tryFinallyA('{"Fu": "Bar"}'),
    {"Fu": "Bar"},
    "tryFinallyA: JSON Parse Failed"
  );

  assertEquals(
    tryFinallyA('{"Fu" = "Bar"}'),
    '{"Fu" = "Bar"}',
    "tryFinallyA: String Parse Failed"
  );

});

/** Start Tests inside Catch/Finally */
Deno.test("tryCatchB", () => {
  
  assertEquals(
    tryCatchB('{"Fu": "Bar"}'),
    {"Fu": "Bar"},
    "tryCatchB: JSON Parse Failed"
  );

  assertEquals(
    tryCatchB('{"Fu" = "Bar"}'),
    '{"Fu" = "Bar"}',
    "tryCatchB: String Parse Failed"
  );

});

Deno.test("tryFinallyB", () => {
  
  assertEquals(
    tryFinallyB('{"Fu": "Bar"}'),
    {"Fu": "Bar"},
    "tryFinallyB: JSON Parse Failed"
  );

  assertEquals(
    tryFinallyB('{"Fu" = "Bar"}'),
    '{"Fu" = "Bar"}',
    "tryFinallyB: String Parse Failed"
  );

});
```
## Results
```sh
$ deno test --allow-net --allow-read --allow-env DenoBug.ts
Check file:///C:/Users/nurse/Google%20Drive/Projects/deno-dotenv/.deno.test.ts
running 4 tests
test tryCatchA ... ok (3ms)
test tryFinallyA ... FAILED (0ms)
test tryCatchB ... ok (1ms)
test tryFinallyB ... ok (1ms)

failures:

tryFinallyA
SyntaxError: Unexpected token = in JSON at position 6
    at JSON.parse (<anonymous>)
    at tryFinallyA (DenoBug.ts:19:18)
    at DenoBug.ts:69:5
    at asyncOpSanitizer ($deno$/testing.ts:33:11)
    at Object.resourceSanitizer [as fn] ($deno$/testing.ts:67:11)
    at TestRunner.[Symbol.asyncIterator] ($deno$/testing.ts:275:22)
    at TestRunner.next (<anonymous>)
    at Object.runTests ($deno$/testing.ts:358:20)

failures:

        tryFinallyA

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (21ms)
```

**Comment by kitsonk** [comment]
This has nothing to do with Deno, that is the way JavaScript works... if you have an empty finally block, the code throws.

You can easily reproduce this in a browser on Node.js.  The fix is not to have an empty finally block.  For example, Chrome:

<img width="550" alt="New_Tab" src="https://user-images.githubusercontent.com/1282577/85969836-23219a00-ba0c-11ea-9f1f-d329b7b1f75d.png">

**Comment by nayeemrmn** [comment]
It doesn't have anything to do with the `finally` block being empty, `finally` doesn't catch errors. It allows you to run some stuff before the error is propagated / the function returns.

**Comment by zinthose** [comment]
@nayeemrmn correct, catching errors is the job for try, but if fetch is empty try fails to catch errors.. Thus the bug.

**Comment by zinthose** [comment]
@kitsonk I see, still, the behavior is rather odd, especially looking closer at the results as the failure seems to only next iteration and not the current.  

Not a Deno issue then.
