### ISSUE TITLE
Possible websocket buffer flushing bug

### ISSUE THREAD

**Issue by SirJosh3917** [denoland/deno#6554]
Unfortunately, I don't know precisely what happened to make this bug occur - I know that someone was sending a lot of packets on a websocket connection, but I'd like to report this stack trace in case anyone may find it useful

```
error: Uncaught BrokenPipe: Broken pipe (os error 32)
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.write ($deno$/ops/io.ts:65:18)
    at async BufWriter.flush (https://deno.land/std@0.57.0/io/bufio.ts:479:25)
    at async writeResponse (https://deno.land/std@0.57.0/http/_io.ts:287:3)
    at async Server.iterateHttpRequests (https://deno.land/std@0.57.0/http/server.ts:158:11)
    at async Server.acceptConnAndIterateHttpRequests (https://deno.land/std@0.57.0/http/server.ts:231:5)
    at async MuxAsyncIterator.callIteratorNext (https://deno.land/std@0.57.0/async/mux_async_iterator.ts:28:29)
```

deno --version output:
```
deno 1.1.1
v8 8.5.104
typescript 3.9.2
```

Feel free to close as I don't know how to reproduce this error.

**Comment by kitsonk** [comment]
It isn't necessarily a "bug" in that such situations can happen when the far end drops unexpectedly, or there is some internal host issue.  You can't expect a flush to succeed and should have some error handling built into the application.

**Comment by SirJosh3917** [comment]
Ah, that makes more sense - I was using oak to handle requests, and I'll report this to them instead since they're the ones handling the flushing. Thank you and sorry for the misunderstanding!
