### ISSUE TITLE
Fetch seems to be fetching wrongly formatted URL when it involves redirect

### ISSUE THREAD

**Issue by just-small-potato** [denoland/deno#6708]
When trying to fetch a [Wikipedia REST API](https://en.wikipedia.org/api/rest_v1/#/Page%20content/get_page_summary__title_), Deno will thrown error saying failed to connect, while the url displayed in the error message is not a valid URL. With further testing, it seems that the API will have some redirect behind.

---

Sample failure code:
```ts
fetch("https://en.wikipedia.org/api/rest_v1/page/summary/computer").then((res)=> {
  res.json().then((data)=> {
    console.log(data)
  });
});
```

Error:
```
error: Uncaught Http: error sending request for url (https://en.wikipedia.orgcomputer/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```

---

Similar code which the request is without redirect:
```ts
fetch("https://en.wikipedia.org/api/rest_v1/page/summary/Computer").then((res)=> {
  res.json().then((data)=> {
    console.log(data)
  });
});
```

Response: 
```json
{
  "type": "standard",
  "title": "Computer",
  "displaytitle": "Computer",
  "namespace": {
    "id": 0,
    "text": ""
  },
  "wikibase_item": "Q68",
  "titles": {
    "canonical": "Computer",
    "normalized": "Computer",
    "display": "Computer"
  },
  "pageid": 7878457,
  "lang": "en",
  "dir": "ltr",
  "revision": "966740228",
  "tid": "1d4a2fc0-c3cb-11ea-a890-c1085d3174ec",
  "timestamp": "2020-07-08T22:21:37Z",
  "description": "Automatic general-purpose device for performing arithmetic or logical operations",
  "description_source": "local",
  "content_urls": {
    "desktop": {
      "page": "https://en.wikipedia.org/wiki/Computer",
      "revisions": "https://en.wikipedia.org/wiki/Computer?action=history",
      "edit": "https://en.wikipedia.org/wiki/Computer?action=edit",
      "talk": "https://en.wikipedia.org/wiki/Talk:Computer"
    },
    "mobile": {
      "page": "https://en.m.wikipedia.org/wiki/Computer",
      "revisions": "https://en.m.wikipedia.org/wiki/Special:History/Computer",
      "edit": "https://en.m.wikipedia.org/wiki/Computer?action=edit",
      "talk": "https://en.m.wikipedia.org/wiki/Talk:Computer"
    }
  },
  "api_urls": {
    "summary": "https://en.wikipedia.org/api/rest_v1/page/summary/Computer",
    "metadata": "https://en.wikipedia.org/api/rest_v1/page/metadata/Computer",
    "references": "https://en.wikipedia.org/api/rest_v1/page/references/Computer",
    "media": "https://en.wikipedia.org/api/rest_v1/page/media/Computer",
    "edit_html": "https://en.wikipedia.org/api/rest_v1/page/html/Computer",
    "talk_page_html": "https://en.wikipedia.org/api/rest_v1/page/html/Talk:Computer"
  },
  "extract": "A computer is a machine that can be instructed to carry out sequences of arithmetic or logical operations automatically via computer programming. Modern computers have the ability to follow generalized sets of operations, called programs. These programs enable computers to perform an extremely wide range of tasks. A \"complete\" computer including the hardware, the operating system, and peripheral equipment required and used for \"full\" operation can be referred to as a computer system. This term may as well be used for a group of computers that are connected and work together, in particular a computer network or computer cluster.",
  "extract_html": "<p>A <b>computer</b> is a machine that can be instructed to carry out sequences of arithmetic or logical operations automatically via computer programming. Modern computers have the ability to follow generalized sets of operations, called <i>programs.</i> These programs enable computers to perform an extremely wide range of tasks. A \"complete\" computer including the hardware, the operating system, and peripheral equipment required and used for \"full\" operation can be referred to as a <b>computer system</b>. This term may as well be used for a group of computers that are connected and work together, in particular a computer network or computer cluster.</p>"
}
```

**Comment by MarkTiedemann** [comment]
When setting redirect to manual, Deno does not crash:

```typescript
// fetch.ts
let res = await fetch("https://en.wikipedia.org/api/rest_v1/page/summary/computer", { redirect: "manual" });
console.assert(res.status === 0);
console.assert(res.type === "opaqueredirect");
```
```
C:\>deno run --allow-net fetch.ts
```

I noticed that Wikipedia uses relative locations in redirects.
``` 
C:\>curl -sI https://en.wikipedia.org/api/rest_v1/page/summary/computer | findstr location:
location: Computer
```

Perhaps Deno does not follow relative locations properly?

**Comment by MarkTiedemann** [comment]
Can confirm that relative locations are the problem:

```typescript
// repro.ts
import { serve } from "https://deno.land/std@0.60.0/http/server.ts";

let server = serve({ port: 80 });

async function listen() {
  for await (let req of server) {
    if (req.url === "/path/computer") {
      req.respond({
        status: 301,
        headers: new Headers({
          location: Deno.args[0] === "relative" ? "Computer" : "/path/Computer",
        }),
      });
    } else {
      req.respond({ status: 200 });
    }
  }
}

listen();
await fetch("http://localhost/path/computer");
server.close();
```

```
C:\>deno run --allow-net repro.ts

C:\>deno run --allow-net repro.ts relative
error: Uncaught Http: error sending request for url (http://localhostcomputer/): error trying to connect: dns error: No such host is known. (os error 11001)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:42:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:93:10)
    at async fetch ($deno$/web/fetch.ts:265:27)
    at async repro.ts:17:1
```

**Comment by marcosc90** [comment]
Found the issue, working on a fix right now.
