### ISSUE TITLE
"Too many open files" error on macOS when benchmarking deno using autocannon and 1000K connections

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#6719]
### System Information

<details>
<summary>Click to expand</summary>

```console
$ sw_vers                           
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G3020

$ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz

$ deno --version
deno 1.1.3
v8 8.5.216
typescript 3.9.2

$ node --version
v14.5.0

$ autocannon --version
autocannon v5.0.1
node v14.5.0
```

</details>

### Deno v1.1.3

<details>
<summary>Code</summary>

```ts
import { serve } from "https://deno.land/std@0.60.0/http/server.ts";

const port = 3000;
const s = serve({ port });

console.log("deno_http listen on", port);
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

</details>

#### Output
```console
$ deno run --allow-net deno_http.ts &
[1] 94340

$ deno_http listen on 3000

$ autocannon -c1000 localhost:3000
Running 10s test @ http://localhost:3000
1000 connections

running [                    ] 0%error: Uncaught Error: Too many open files (os error 24)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:42:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:93:10)
    at async ListenerImpl.accept ($deno$/net.ts:63:17)
    at async Server.acceptConnAndIterateHttpRequests (https://deno.land/std@0.60.0/http/server.ts:185:20)
    at async MuxAsyncIterator.callIteratorNext (https://deno.land/std@0.60.0/async/mux_async_iterator.ts:22:37)
[1]  + exit 1     deno run --allow-net deno_http.ts
┌─────────┬──────┬──────┬───────┬──────┬──────┬───────┬──────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg  │ Stdev │ Max  │
├─────────┼──────┼──────┼───────┼──────┼──────┼───────┼──────┤
│ Latency │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │
└─────────┴──────┴──────┴───────┴──────┴──────┴───────┴──────┘
┌───────────┬─────┬──────┬─────┬───────┬─────┬───────┬─────┐
│ Stat      │ 1%  │ 2.5% │ 50% │ 97.5% │ Avg │ Stdev │ Min │
├───────────┼─────┼──────┼─────┼───────┼─────┼───────┼─────┤
│ Req/Sec   │ 0   │ 0    │ 0   │ 0     │ 0   │ 0     │ 0   │
├───────────┼─────┼──────┼─────┼───────┼─────┼───────┼─────┤
│ Bytes/Sec │ 0 B │ 0 B  │ 0 B │ 0 B   │ 0 B │ 0 B   │ 0 B │
└───────────┴─────┴──────┴─────┴───────┴─────┴───────┴─────┘

Req/Bytes counts sampled once per second.

0 requests in 10.25s, 0 B read
2k errors (206 timeouts)

$ lsof -ti tcp:3000 | xargs kill 
```

### Node.js v14.5.0

<details>
<summary>Code</summary>

```js
const http = require("http");

const hostname = "127.0.0.1";
const port = 3000;

const server = http.createServer((req, res) => {
  res.end("Helloi World!");
});

server.listen(port, hostname, () => {
  console.log("node listening on:", port);
});
```

</details>

#### Output
```console
$ node node_http.js &
[1] 94503

$ node listening on: 3000

$ autocannon -c1000 localhost:3000   
Running 10s test @ http://localhost:3000
1000 connections

┌─────────┬───────┬───────┬───────┬────────┬──────────┬──────────┬────────────┐
│ Stat    │ 2.5%  │ 50%   │ 97.5% │ 99%    │ Avg      │ Stdev    │ Max        │
├─────────┼───────┼───────┼───────┼────────┼──────────┼──────────┼────────────┤
│ Latency │ 32 ms │ 49 ms │ 91 ms │ 169 ms │ 54.97 ms │ 48.72 ms │ 1087.64 ms │
└─────────┴───────┴───────┴───────┴────────┴──────────┴──────────┴────────────┘
┌───────────┬────────┬────────┬─────────┬─────────┬─────────┬────────┬────────┐
│ Stat      │ 1%     │ 2.5%   │ 50%     │ 97.5%   │ Avg     │ Stdev  │ Min    │
├───────────┼────────┼────────┼─────────┼─────────┼─────────┼────────┼────────┤
│ Req/Sec   │ 4515   │ 4515   │ 19311   │ 21887   │ 18277.8 │ 4860   │ 4515   │
├───────────┼────────┼────────┼─────────┼─────────┼─────────┼────────┼────────┤
│ Bytes/Sec │ 510 kB │ 510 kB │ 2.18 MB │ 2.47 MB │ 2.07 MB │ 549 kB │ 510 kB │
└───────────┴────────┴────────┴─────────┴─────────┴─────────┴────────┴────────┘

Req/Bytes counts sampled once per second.

183k requests in 10.38s, 20.7 MB read
2 errors (0 timeouts)

$ lsof -ti tcp:3000 | xargs kill 
```

**Comment by trivikr** [comment]
The code works fine for 100 connections

```console

$ deno run --allow-net deno_http.ts &
[1] 94340

$ deno_http listen on 3000

$ autocannon -c100 localhost:3000  
Running 10s test @ http://localhost:3000
100 connections

┌─────────┬──────┬──────┬───────┬───────┬─────────┬─────────┬───────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%   │ Avg     │ Stdev   │ Max       │
├─────────┼──────┼──────┼───────┼───────┼─────────┼─────────┼───────────┤
│ Latency │ 3 ms │ 4 ms │ 10 ms │ 13 ms │ 4.79 ms │ 3.89 ms │ 260.19 ms │
└─────────┴──────┴──────┴───────┴───────┴─────────┴─────────┴───────────┘
┌───────────┬────────┬────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ Stat      │ 1%     │ 2.5%   │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min    │
├───────────┼────────┼────────┼─────────┼─────────┼─────────┼─────────┼────────┤
│ Req/Sec   │ 13599  │ 13599  │ 19903   │ 22367   │ 18780.8 │ 2874.56 │ 13596  │
├───────────┼────────┼────────┼─────────┼─────────┼─────────┼─────────┼────────┤
│ Bytes/Sec │ 694 kB │ 694 kB │ 1.01 MB │ 1.14 MB │ 958 kB  │ 147 kB  │ 693 kB │
└───────────┴────────┴────────┴─────────┴─────────┴─────────┴─────────┴────────┘

Req/Bytes counts sampled once per second.

188k requests in 10.07s, 9.58 MB read

$ lsof -ti tcp:3000 | xargs kill 
```

**Comment by mikeal** [comment]
This looks like a typical error you’d encounter when you go past file descriptor limit. These settings vary by OS and configuration, try increasing the limits set for the system and the user you’re running as.

**Comment by trivikr** [comment]
Thanks @mikeal for the response

> Try increasing the limits set for the system and the user you’re running as.

I increased the settings as suggested on StackOverflow https://superuser.com/a/443168
```console
$ ulimit -S -n 2048
```

And the error is not reproducible.

File descriptor limit was 256 by default when error was reproducible
```console
$ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       1418
-n: file descriptors                256
```

**Comment by caspervonb** [comment]
Don't see anything actionable here and think this was mislabeled as a bug when it's not really.
This is just operating system limits and the proper errno bubbles up just fine.
