### ISSUE TITLE
Flaky tests for Buffer max size

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#6731]
https://github.com/denoland/deno/pull/6729/checks?check_run_id=864887110

```
2020-07-13T11:52:15.3420551Z bufferGrowReadCloseToMaxBuffer
2020-07-13T11:52:15.3420757Z RangeError: Array buffer allocation failed
2020-07-13T11:52:15.3420962Z     at new ArrayBuffer (<anonymous>)
2020-07-13T11:52:15.3428091Z     at new Uint8Array (<anonymous>)
2020-07-13T11:52:15.3428312Z     at Buffer.#grow ($deno$/buffer.ts:141:19)
2020-07-13T11:52:15.3428677Z     at Buffer.writeSync ($deno$/buffer.ts:110:25)
2020-07-13T11:52:15.3428895Z     at Buffer.readFrom ($deno$/buffer.ts:176:28)
2020-07-13T11:52:15.3429171Z     at async bufferGrowReadCloseToMaxBuffer (file:///home/runner/work/deno/deno/cli/tests/unit/buffer_test.ts:252:7)
2020-07-13T11:52:15.3433703Z     at async asyncOpSanitizer ($deno$/testing.ts:34:5)
2020-07-13T11:52:15.3439068Z     at async Object.resourceSanitizer [as fn] ($deno$/testing.ts:68:5)
2020-07-13T11:52:15.3439333Z     at async TestRunner.[Symbol.asyncIterator] ($deno$/testing.ts:276:11)
2020-07-13T11:52:15.3439564Z     at async runTests ($deno$/testing.ts:364:20)
2020-07-13T11:52:15.3439710Z 
2020-07-13T11:52:15.3442568Z bufferReadCloseToMaxBufferWithInitialGrow
2020-07-13T11:52:15.3442899Z Unit tests failed
2020-07-13T11:52:15.3443119Z RangeError: Array buffer allocation failed
2020-07-13T11:52:15.3443345Z     at new ArrayBuffer (<anonymous>)
2020-07-13T11:52:15.3445762Z     at new Uint8Array (<anonymous>)
2020-07-13T11:52:15.3446000Z     at Buffer.#grow ($deno$/buffer.ts:141:19)
2020-07-13T11:52:15.3478588Z     at Buffer.grow ($deno$/buffer.ts:155:25)
2020-07-13T11:52:15.3486037Z     at bufferReadCloseToMaxBufferWithInitialGrow (file:///home/runner/work/deno/deno/cli/tests/unit/buffer_test.ts:265:11)
2020-07-13T11:52:15.3486568Z     at asyncOpSanitizer ($deno$/testing.ts:34:11)
2020-07-13T11:52:15.3486819Z     at Object.resourceSanitizer [as fn] ($deno$/testing.ts:68:11)
2020-07-13T11:52:15.3487062Z     at TestRunner.[Symbol.asyncIterator] ($deno$/testing.ts:276:22)
2020-07-13T11:52:15.3490019Z     at TestRunner.next (<anonymous>)
2020-07-13T11:52:15.3490281Z     at runTests ($deno$/testing.ts:364:20)
```

I've seen this error pop up several times over past days. 

Also @nayeemrmn pointed out that tests using max buffer size are very slow.

CC @marcosc90

**Comment by marcosc90** [comment]
Weird that [`MAX_SIZE` allocation](https://github.com/denoland/deno/pull/6570/commits/7d717db18d33a428c1dcd9d33d410d6911119a8c) isn't failing once the test starts, and fails later.

We can ignore those tests. Unfortunately, the only way to test MAX_SIZE logic is reading MAX_SIZE bytes, and if the environment doesn't have enough memory it will fail.

As an alternative, we can add a `maxSize` argument to Buffer.

Thoughts?
