### ISSUE TITLE
Deno.seek seems to be off by one

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#6766]
Seems that Deno.seek is off by one when seeking to the current position.

```typescript
import { assertEquals } from "https://deno.land/std/testing/asserts.ts";

const file = await Deno.open("test.txt", {
  create: true,
  write: true,
});

assertEquals(await Deno.seek(file.rid, Deno.SeekMode.Current, 0), 0);
```

```shell
error: Uncaught AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   1
+   0

    const diffResult = diff(
    ^
    at assertEquals (https://deno.land/std/testing/asserts.ts:155:5)
    at test.ts:8:1
```

**Comment by caspervonb** [comment]
For comparison; this is the expected behavior

```rust
use std::io::Seek;

fn main() {
  let mut file = std::fs::File::create("test.txt").unwrap();
  assert_eq!(file.seek(std::io::SeekFrom::Current(0)).unwrap(), 0);
}
```

**Comment by caspervonb** [comment]
And it's not that it's initially 1, e.g this also fails

```typescript
import { assertEquals } from "https://deno.land/std/testing/asserts.ts";

const file = await Deno.open("test.txt", {
  create: true,
  write: true,
});

await Deno.seek(file.rid, Deno.SeekMode.Start, 0);
assertEquals(await Deno.seek(file.rid, Deno.SeekMode.Current, 0), 0);
```

**Comment by caspervonb** [comment]
So I was sure I double checked before writing this test case (this is a defect in std/wasi) but this is just a user error, parameters are in the wrong order, nothing to see here.
