### ISSUE TITLE
(std/encoding) TOML parser throws SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#6776]
When parsing the same spec-valid TOML strings, with only an apostrophe or semicolon difference, the parser throws an error when the semicolon or apostrophe is present. See Deno test and terminal output for details.

`toml.test.ts`:
```ts
import {assertEquals} from 'https://deno.land/std@0.61.0/testing/asserts.ts';
import {parse} from 'https://deno.land/std@0.61.0/encoding/toml.ts';

type TOMLTest = [
  string, // name
  string, // tomlString
  Record<string, string>, // expected
];

const tests: TOMLTest[] = [
  [
    'without apostrophe',
    `message = "What if it is not?"`,
    {message: `What if it is not?`},
  ],
  [
    'with apostrophe',
    `message = "What if it's not?"`,
    {message: `What if it's not?`},
  ],
  [
    'without semicolon',
    `snippet = "const message = 'hello world'"`,
    {snippet: `const message = 'hello world'`},
  ],
  [
    'with semicolon',
    `snippet = "const message = 'hello world';"`,
    {snippet: `const message = 'hello world';`},
  ],
];

for (const [name, tomlString, expected] of tests) {
  Deno.test(name, () => {
    const data = parse(tomlString);
    assertEquals(data, expected);
  });
}
```

shell:
```
> deno test toml.test.ts
running 4 tests
test without apostrophe ... ok (3ms)
test with apostrophe ... FAILED (0ms)
test without semicolon ... ok (1ms)
test with semicolon ... FAILED (0ms)

failures:

with apostrophe
SyntaxError: Invalid or unexpected token
    at Parser._parseData (toml.ts:261:17)
    at Parser._processDeclaration (toml.ts:190:24)
    at Parser._parseLines (toml.ts:340:25)
    at Parser.parse (toml.ts:389:10)
    at parse (toml.ts:569:33)
    at toml.test.ts:35:18
    at asyncOpSanitizer ($deno$/testing.ts:34:11)
    at Object.resourceSanitizer [as fn] ($deno$/testing.ts:68:11)
    at TestRunner.[Symbol.asyncIterator] ($deno$/testing.ts:276:22)
    at TestRunner.next (<anonymous>)

with semicolon
SyntaxError: Invalid or unexpected token
    at Parser._parseData (toml.ts:261:17)
    at Parser._processDeclaration (toml.ts:190:24)
    at Parser._parseLines (toml.ts:340:25)
    at Parser.parse (toml.ts:389:10)
    at parse (toml.ts:569:33)
    at toml.test.ts:35:18
    at asyncOpSanitizer ($deno$/testing.ts:34:11)
    at Object.resourceSanitizer [as fn] ($deno$/testing.ts:68:11)
    at TestRunner.[Symbol.asyncIterator] ($deno$/testing.ts:276:22)
    at TestRunner.next (<anonymous>)

failures:

	with apostrophe
	with semicolon

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out (5ms)
```

**Comment by uki00a** [comment]
I'll work on a fix.

**Comment by jsejcksn** [comment]
Thanks @uki00a!
