### ISSUE TITLE
[std/path] fromFileUrl does not decode spaces on Windows

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#6892]
Possibly related: #6351, #6408

I have prepared a test to demonstrate the issue.

Essentially, the result of `path.fromFileUrl` must be decoded by `decodeURI` in order to be correctly handled by `Deno.readTextFile`. It also appears that providing a URL object fails in this test.

See code for details:

<details>
<summary><code>test.ts</code></summary>

```ts
// deno test --allow-env --allow-read --allow-write test.ts

import * as path from 'https://deno.land/std@0.62.0/path/mod.ts';
import {assertEquals} from 'https://deno.land/std@0.62.0/testing/asserts.ts';
import {ensureDir} from 'https://deno.land/std@0.62.0/fs/ensure_dir.ts';

const dirname = '___Deno URL Path Test';
const filename = 'hello.txt';
const fileContent = 'hello world';

const getRequiredEnvVar = (varName: string): string => {
  const value = Deno.env.get(varName);
  if (!value?.length) throw new Error(`$env:${varName} not set`);
  return value;
};

const writeTestData = async (testDir: string): Promise<string> => {
  await ensureDir(testDir);
  await Deno.writeTextFile(path.join(testDir, filename), fileContent);
  return testDir;
};

const deleteTestData = async (testDir: string): Promise<void> => {
  await Deno.remove(testDir, {recursive: true});
};

if (Deno.build.os === 'windows') {
  const username = getRequiredEnvVar('USERNAME');
  const rawUrl = `/Users/${username}/${dirname}/${filename}`;
  const fileUrl = new URL(`file://${rawUrl}`);

  const fromFileUrl = path.fromFileUrl(fileUrl);
  const resolvedPath = path.resolve(fromFileUrl);

  const decodedPath = decodeURI(fromFileUrl);
  const resolvedDecodedPath = path.resolve(decodedPath);

  const paths = {
    fileUrl,
    fromFileUrl,
    resolvedPath,
    decodedPath,
    resolvedDecodedPath,
  };

  const userprofile = getRequiredEnvVar('USERPROFILE');
  const testDir = path.join(userprofile, dirname);

  for (const [name, path] of Object.entries(paths)) {
    Deno.test({
      name: `${name}: ${path}`,
      fn: async (): Promise<void> => {
        await writeTestData(testDir);
        try {
          const content = await Deno.readTextFile(path);
          assertEquals(content, fileContent);
        }
        finally {
          await deleteTestData(testDir);
        }
      },
    });
  }
}
```
</details>

Output:

```
> deno test --allow-env --allow-read --allow-write test.ts
running 5 tests
test fileUrl: "file:///Users/Jesse/___Deno%20URL%20Path%20Test/hello.txt" ... FAILED (6ms)
test fromFileUrl: "\Users\Jesse\___Deno%20URL%20Path%20Test\hello.txt" ... FAILED (3ms)
test resolvedPath: "C:\Users\Jesse\___Deno%20URL%20Path%20Test\hello.txt" ... FAILED (3ms)
test decodedPath: "\Users\Jesse\___Deno URL Path Test\hello.txt" ... ok (5ms)
test resolvedDecodedPath: "C:\Users\Jesse\___Deno URL Path Test\hello.txt" ... ok (3ms)

failures:

fileUrl: "file:///Users/Jesse/___Deno%20URL%20Path%20Test/hello.txt"
TypeError: A URL with the file schema must be absolute.
    at pathFromURLWin32 (rt\06_util.js:79:13)
    at pathFromURL (rt\06_util.js:101:11)
    at opOpen (rt\30_files.js:35:41)
    at open (rt\30_files.js:52:23)
    at Object.readTextFile (rt\40_read_file.js:30:24)
    at fn (test.ts:56:38)
    at async asyncOpSanitizer (rt\40_testing.js:34:7)
    at async Object.resourceSanitizer [as fn] (rt\40_testing.js:68:7)
    at async TestRunner.[Symbol.asyncIterator] (rt\40_testing.js:240:13)
    at async Object.runTests (rt\40_testing.js:317:22)

fromFileUrl: "\Users\Jesse\___Deno%20URL%20Path%20Test\hello.txt"
NotFound: The system cannot find the path specified. (os error 3)
    at unwrapResponse (rt\10_dispatch_json.js:25:13)
    at sendAsync (rt\10_dispatch_json.js:76:12)
    at async open (rt\30_files.js:52:17)
    at async Object.readTextFile (rt\40_read_file.js:30:18)
    at async fn (test.ts:56:27)
    at async asyncOpSanitizer (rt\40_testing.js:34:7)
    at async Object.resourceSanitizer [as fn] (rt\40_testing.js:68:7)
    at async TestRunner.[Symbol.asyncIterator] (rt\40_testing.js:240:13)
    at async Object.runTests (rt\40_testing.js:317:22)

resolvedPath: "C:\Users\Jesse\___Deno%20URL%20Path%20Test\hello.txt"
NotFound: The system cannot find the path specified. (os error 3)
    at unwrapResponse (rt\10_dispatch_json.js:25:13)
    at sendAsync (rt\10_dispatch_json.js:76:12)
    at async open (rt\30_files.js:52:17)
    at async Object.readTextFile (rt\40_read_file.js:30:18)
    at async fn (test.ts:56:27)
    at async asyncOpSanitizer (rt\40_testing.js:34:7)
    at async Object.resourceSanitizer [as fn] (rt\40_testing.js:68:7)
    at async TestRunner.[Symbol.asyncIterator] (rt\40_testing.js:240:13)
    at async Object.runTests (rt\40_testing.js:317:22)

failures:

        fileUrl: "file:///Users/Jesse/___Deno%20URL%20Path%20Test/hello.txt"
        fromFileUrl: "\Users\Jesse\___Deno%20URL%20Path%20Test\hello.txt"
        resolvedPath: "C:\Users\Jesse\___Deno%20URL%20Path%20Test\hello.txt"

test result: FAILED. 2 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out (22ms)
```

**Comment by jsejcksn** [comment]
@nayeemrmn Thanks!

Also, the first test is still failing. Any ideas?

**Comment by nayeemrmn** [comment]
@jsejcksn Can you provide a smaller test with simple actual/expected values for `fromFileUrl()`? It's harder to run that not being on Windows.

**Comment by jsejcksn** [comment]
The test requires running on Windows because the absolute path needs to be a Windows path and the failure happens during the call to `Deno.readTextFile`. See the first failure in the output; it's identical to the failure using the updated code (except for some line numbers):

```
fileUrl: "file:///Users/Jesse/___Deno%20URL%20Path%20Test/hello.txt"
TypeError: A URL with the file schema must be absolute.
    at pathFromURLWin32 (rt\06_util.js:79:13)
    at pathFromURL (rt\06_util.js:101:11)
    at opOpen (rt\30_files.js:35:41)
    at open (rt\30_files.js:52:23)
    at Object.readTextFile (rt\40_read_file.js:30:24)
    at fn (test.ts:56:38)
    at async asyncOpSanitizer (rt\40_testing.js:34:7)
    at async Object.resourceSanitizer [as fn] (rt\40_testing.js:68:7)
    at async TestRunner.[Symbol.asyncIterator] (rt\40_testing.js:240:13)
    at async Object.runTests (rt\40_testing.js:317:22)
```

**Comment by nayeemrmn** [comment]
@jsejcksn Thanks, I see the problem. The built-in file URL conversion assumes that Windows paths must have a drive letter: https://github.com/denoland/deno/blob/6afe7bbd395eb34febd25bda48c5cd82f0a4f8b3/cli/rt/06_util.js#L75-L80

It's separate from the one is `std`, can you open an issue? I'll get on it tomorrow if no one else has.
