### ISSUE TITLE
type error from the imports

### ISSUE THREAD

**Issue by Conando025** [denoland/deno#6947]
This is the error that occurs when I try to use the example code.
```
error: TS2322 [ERROR]: Type 'import("https://deno.land/std/io/bufio").BufReader' is not assignable to type 'import("https://deno.land/std@0.63.0/io/bufio").BufReader'.
  Types have separate declarations of a private property 'buf'.
      bufReader: req.r,
      ~~~~~~~~~
    at file:///C:/.../test.ts:47:7

    The expected type comes from property 'bufReader' which is declared here on type '{ conn: Conn; bufWriter: BufWriter; bufReader: BufReader; headers: Headers; }'
      bufReader: BufReader;
      ~~~~~~~~~
        at https://deno.land/std@0.63.0/ws/mod.ts:421:3

TS2322 [ERROR]: Type 'import("https://deno.land/std/io/bufio").BufWriter' is not assignable to type 'import("https://deno.land/std@0.63.0/io/bufio").BufWriter'.
  Types have separate declarations of a private property 'writer'.
      bufWriter: req.w,
      ~~~~~~~~~
    at file:///C:/.../test.ts:48:7

    The expected type comes from property 'bufWriter' which is declared here on type '{ conn: Conn; bufWriter: BufWriter; bufReader: BufReader; headers: Headers; }'
      bufWriter: BufWriter;
      ~~~~~~~~~
        at https://deno.land/std@0.63.0/ws/mod.ts:420:3

Found 2 errors.
```

**Comment by lucacasonato** [comment]
> This is the error that occurs when I try to use the example code.

What example are you talking about?

**Comment by MarkTiedemann** [comment]
@Conando025 The import statement is incorrect:
```ts
import("https://deno.land/std/io/bufio").BufReader
```

It's should be a static import:

```ts
import { BufReader } from "https://deno.land/std@0.63.0/io/bufio.ts";
```

Or a dynamic import:
```ts
const { BufReader } = await import("https://deno.land/std@0.63.0/io/bufio.ts");
```

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import for more info.

**Comment by mundish** [comment]
As an extra note on @MarkTiedemann 's comment, importing explicitly from a tagged release (like in Mark's example with  `std@0.63.0` rather than just `std` in the import paths) is recommended: [docs](https://deno.land/std@0.63.0#how-to-use)

**Comment by Conando025** [comment]
So I am using the example found in the readme but in that, there is no import from bufio.ts do I need to add that?

**Comment by lucacasonato** [comment]
What readme are you talking about? Can you give us a link? You should change the imports from deno.land/std/ to deno.land/std@0.63.0/

**Comment by Conando025** [comment]
oh my mistake I thought this was just the repository for the WebSocket module.

the code is the following:
```
import { serve } from "https://deno.land/std/http/server.ts";
import {
  acceptWebSocket,
  isWebSocketCloseEvent,
  isWebSocketPingEvent,
  WebSocket,
} from "https://deno.land/std/ws/mod.ts";

async function handleWs(sock: WebSocket) {
  console.log("socket connected!");
  try {
    for await (const ev of sock) {
      if (typeof ev === "string") {
        // text message
        console.log("ws:Text", ev);
        await sock.send(ev);
      } else if (ev instanceof Uint8Array) {
        // binary message
        console.log("ws:Binary", ev);
      } else if (isWebSocketPingEvent(ev)) {
        const [, body] = ev;
        // ping
        console.log("ws:Ping", body);
      } else if (isWebSocketCloseEvent(ev)) {
        // close
        const { code, reason } = ev;
        console.log("ws:Close", code, reason);
      }
    }
  } catch (err) {
    console.error(`failed to receive frame: ${err}`);

    if (!sock.isClosed) {
      await sock.close(1000).catch(console.error);
    }
  }
}

if (import.meta.main) {
  /** websocket echo server */
  const port = Deno.args[0] || "8080";
  console.log(`websocket server is running on :${port}`);
  for await (const req of serve(`:${port}`)) {
    const { conn, r: bufReader, w: bufWriter, headers } = req;
    acceptWebSocket({
      conn,
      bufReader,
      bufWriter,
      headers,
    })
      .then(handleWs)
      .catch(async (err) => {
        console.error(`failed to accept websocket: ${err}`);
        await req.respond({ status: 400 });
      });
  }
}
```

**Comment by mundish** [comment]
@Conando025 have you tried changing your import paths to
´https://deno.land/std@0.63.0/http/server.ts´
and
´https://deno.land/std@0.63.0/ws/mod.ts´ respectively?

**Comment by MarkTiedemann** [comment]
@Conando025 I can reproduce your error if I use different versions of `https://deno.land/std/http/server.ts` and `https://deno.land/std/ws/mod.ts`, e.g. if `std/http/server` is v0.63.0 and `std/ws/mod` is v0.62.0. If both use the same `std` version, it's fine.

**Comment by lucacasonato** [comment]
This issue seems to be resolved.
