### ISSUE TITLE
Getting build errors

### ISSUE THREAD

**Issue by mwoodpatrick** [denoland/deno#6981]
I'm getting the following build errors when builing 

    https://github.com/second-state/ssvm-deno-starter

I don't see the definitions for these missing functions, where are they defined

error: TS2339 [ERROR]: Property 'fdatasyncSync' does not exist on type 'typeof Deno'.
          Deno.fdatasyncSync(entry.handle.rid);
               ~~~~~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:501:16

TS2551 [ERROR]: Property 'fstatSync' does not exist on type 'typeof Deno'. Did you mean 'lstatSync'?
          const info = Deno.fstatSync(entry.handle.rid);
                            ~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:545:29

    'lstatSync' is declared here.
      export function lstatSync(path: string | URL): FileInfo;
                      ~~~~~~~~~
        at asset:///lib.deno.ns.d.ts:1485:19

TS2551 [ERROR]: Property 'ftruncateSync' does not exist on type 'typeof Deno'. Did you mean 'truncateSync'?
          Deno.ftruncateSync(entry.handle.rid, Number(size));
               ~~~~~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:616:16

    'truncateSync' is declared here.
      export function truncateSync(name: string, len?: number): void;
                      ~~~~~~~~~~~~
        at asset:///lib.deno.ns.d.ts:1611:19

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
          Deno.utimeSync(entry.path, Number(atim), Number(mtim));
               ~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:648:16

TS2339 [ERROR]: Property 'fsyncSync' does not exist on type 'typeof Deno'.
          Deno.fsyncSync(entry.handle.rid);
               ~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:914:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
          Deno.utimeSync(path, Number(atim), Number(mtim));
               ~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:1117:16

TS2339 [ERROR]: Property 'linkSync' does not exist on type 'typeof Deno'. 'Deno.linkSync' is an unstable API. Did you forget to run with the '--unstable' flag?
          Deno.linkSync(old_path, new_path);
               ~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:1159:16

TS2339 [ERROR]: Property 'symlinkSync' does not exist on type 'typeof Deno'. 'Deno.symlinkSync' is an unstable API. Did you forget to run with the '--unstable' flag?
          Deno.symlinkSync(old_path, new_path);
               ~~~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:1435:16

**Comment by jeroenptrs** [comment]
The CLI errors seem to indicate you're not running/building with the `--unstable` flag.
Can you try again with that flag?

**Comment by mwoodpatrick** [comment]
Yep, just realized that was the issue, paper that went with this repository:

https://www.infoq.com/articles/deno-loves-webassembly/

Did not list those flags see:

https://github.com/second-state/ssvm-deno-starter/issues/1

for details, close that issue, closing this one, many thanks for the very prompt and accurate assistance, much appreciated

**Comment by juntao** [comment]
There is an update to the article here. I will see if InfoQ can update their web site. Thanks!

https://www.secondstate.io/articles/deno-webassembly-rust-wasi/
