### ISSUE TITLE
std/node/path.ts: Type 'URL' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by balupton** [denoland/deno#7089]
``` bash
deno eval -T "import { dirname } from 'https://deno.land/std/node/path.ts'"
```

```
Check file:///Users/balupton/Projects/active/filedirname/__$deno$eval.ts
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std/path/win32.ts:917:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std/path/posix.ts:438:18

Found 2 errors.
```

---

```
> deno --version
deno 1.3.0
v8 8.6.334
typescript 3.9.7
```

**Comment by balupton** [comment]
Possible dupe of #5365

**Comment by balupton** [comment]
```
> deno eval -T "import { dirname } from 'https://deno.land/std@0.65.0/node/path.ts'"
Check file:///Users/balupton/Projects/active/filedirname/__$deno$eval.ts
```

does not seem to have this issue

**Comment by balupton** [comment]
Closing. Just do to refresh the deno cache with `--reload`

**Comment by darklight9811** [comment]
Same issue here, but reloading didn't work out
