### ISSUE TITLE
Deno attempts to create source files from non-reference triple-slash syntax.

### ISSUE THREAD

**Issue by brainkim** [denoland/deno#7205]
I’m currently experimenting with different syntaxes for portable asset references. If I use the following syntax:

```tsx
/** @jsx createElement */
/// <asset path="./styles.css" />
```

Deno bundling and compilation will throw the error:

error: Uncaught TypeError: Cannot resolve extension for "file:///my/project/styles.css" with mediaType "Unknown".
    at getExtension (tsc/99_main_compiler.js:470:15)
    at new SourceFile (tsc/99_main_compiler.js:523:24)
    at Function.addToCache (tsc/99_main_compiler.js:530:18)
    at buildSourceFileCache (tsc/99_main_compiler.js:886:18)
    at bundle (tsc/99_main_compiler.js:1562:5)
    at tsCompilerOnMessage (tsc/99_main_compiler.js:1803:24)
    at <compiler>:1:12

My expectation is that deno would check the tag of the XML element before following the path attribute. Typescript itself doesn’t seem to have a problem with this syntax. Naming the attribute something other than `path` works, but I wonder if this is just an oversight in `pre_process_file`: https://github.com/denoland/deno/blob/9bfb0df805719cb3f022a5b5d9f9d898ae954c2e/cli/tsc.rs#L1379

deno 1.3.0
v8 8.6.334
typescript 3.9.7

**Comment by kitsonk** [comment]
Yes, the regex is too broad...

I am using a much more specific one in [#6894](https://github.com/denoland/deno/pull/6894/files#diff-b7e70546f30382bfae80fbd491df1f9aR128-R138).
