### ISSUE TITLE
Lint: no-unreachable will warn std & cli/tests

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno#7269]
In the next version of `deno_lint`, the `no-unreachable` rule will be present.
Running lint with this rule enabled gives us the following error:

```
(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:322:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:325:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:328:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:331:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:334:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:337:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:340:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:343:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:346:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:350:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:353:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:356:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:359:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:362:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:365:8

(no-unreachable) This statement is unreachable
        break;
        ~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/std/fmt/printf.ts:368:8

(no-unreachable) This statement is unreachable
      return "b";
      ~~~~~~~~~~~
    at /home/yusuktan/Repos/github.com/magurotuna/deno/cli/tests/unit/console_test.ts:725:6

Found 17 problems
```

So we probably have to address these errors before the next version of `deno_lint` is released.

Question:

1. Can we remove `break;` from
https://github.com/denoland/deno/blob/62809cd6052c12bb6df59708c56f44cd49e64427/std/fmt/printf.ts#L321-L322

2. Is there any reason to put `return "b";` after `throw`?
https://github.com/denoland/deno/blob/62809cd6052c12bb6df59708c56f44cd49e64427/cli/tests/unit/console_test.ts#L724-L725

**Comment by bartlomieju** [comment]
Thanks for looking into that @magurotuna!

> Can we remove break; from

Yes, please do.

> Is there any reason to put return "b"; after throw? 

Not really, can be removed.

**Comment by caspervonb** [comment]
> Can we remove break after return statements

A return statement followed by break statement is nonsense, I'd say remove and I'm fairly confident no one would ever object to that.

> Is there any reason to put return after throw?

No, quite a few tests used to do this but I've probably missed some during that refactor.

**Comment by magurotuna** [comment]
@bartlomieju @caspervonb 
Thanks for your quick answer!
OK, then I will remove `break;` and `return "b";`.
