### ISSUE TITLE
std fetch raises TypeError when return body is empty since v1.3 

### ISSUE THREAD

**Issue by bidoubiwa** [denoland/deno#7338]
When using fetch with a URL that does not return any body (i.e a delete route of an API) the following error is returned: 

```
Check file:///[...]/project/demo/empty_body.js
Provided input is not of type ArrayBuffer or ArrayBufferView
TypeError: Provided input is not of type ArrayBuffer or ArrayBufferView
    at TextDecoder.decode (/Users/runner/work/deno/deno/op_crates/web/08_text_encoding.js:456:15)
    at Response.text (rt/24_body.js:200:22)
    at async HttpRequests.request (http-requests.ts:50:34)
    at async HttpRequests.delete (http-requests.ts:163:12)
    at async Index.deleteIndex (index.ts:168:12)
    at async file:///[...]/project/demo/empty_body.js:14:1
```

Apparently the return body should be of either type `ArrayBuffer` or `ArrayBufferView`.
This error did not exists in previous versions.
I think it has to do with #7178

It does not expect the body to be `null` in `08_text_encoding.js:456:15`.

```javascript
 decode(
      input,
      options = { stream: false },
    ) {
      if (options.stream) {
        throw new TypeError("Stream not supported.");
      }

      let bytes;
      if (input instanceof Uint8Array) {
        bytes = input;
      } else if (isEitherArrayBuffer(input)) {
        bytes = new Uint8Array(input);
      } else if (
        typeof input === "object" &&
        input !== null &&
        "buffer" in input &&
        isEitherArrayBuffer(input.buffer)
      ) {
        bytes = new Uint8Array(
          input.buffer,
          input.byteOffset,
          input.byteLength,
        );
      } else {
        throw new TypeError(
          "Provided input is not of type ArrayBuffer or ArrayBufferView",
        );
      }
```

So my question is: 
Is this a problem with fetch, a problem with this function or a bad practice to not return a body?

**Comment by bartlomieju** [comment]
@bidoubiwa thanks for reporting the issue, however I'm having trouble reproducing it. Could you provide output of `curl -I` for your endpoint? 

The bug is most likely connected to `TextDecoder` implementation you linked to.

That said fetching empty response like this:
```
HTTP/1.1 200 OK
content-length: 0
date: Fri, 04 Sep 2020 15:56:51 GMT


```
does not result in the error you got.

**Comment by bidoubiwa** [comment]
So after some tests you are right. The problem does not come from the `fetch` api but from the `response.text()`. 

Apparently since the new version it is not possible to `.text()` on a empty body.

this is my Response object: 
```javascript
Response {
  _bodySource: null,
  _stream: null,
  url: "http://127.0.0.1:7700/indexes/movies",
  statusText: "No Content",
  status: 204,
  headers: Headers { date: Mon, 07 Sep 2020 21:09:32 GMT },
  redirected: false,
  type: "default"
}
```

This is my code: 
```javascript
const parsedBody: string = await response.text();
```

## Working example

I created a small API with one route that returns an empty body.

endpoint.ts 
```javascript
// endpoint.ts
import { Application } from 'https://deno.land/x/oak/mod.ts'
import { Router } from 'https://deno.land/x/oak/mod.ts'

const HOST = '127.0.0.1'
const PORT = 1234

const app = new Application()

const deleteThing = ({ response }: { response: any }) => {
    console.log('Delete');
    response.status = 204
}

const router = new Router()
router.delete('/test', deleteThing)

app.use(router.routes())
app.use(router.allowedMethods())

console.log(`Listening on port ${PORT} ...`)
await app.listen(`${HOST}:${PORT}`)
```
This will listen on port `1234`

run it like this 
```bash
deno run --allow-net endpoint.ts
```

small script that call that endpoint: 
```javascript
// fetch.js
const response = await fetch("http://localhost:1234/test", {
    method: 'DELETE',
  })

const parsedBody = await response.text();
console.log({ parsedBody });
```
run it like this: 
```bash
deno run --allow-net fetch.js
```

This will throw the following error: 
```
error: Uncaught TypeError: Provided input is not of type ArrayBuffer or ArrayBufferView
    at TextDecoder.decode (/Users/runner/work/deno/deno/op_crates/web/08_text_encoding.js:456:15)
    at Response.text (rt/24_body.js:200:22)
    at async file:///[...]project/fetch.js:5:20
```

**Comment by caspervonb** [comment]
Minimal reproducible example

```typescript
 new Response().text();
```
And at first glance, all the methods in response are incorrect in this scenario.
I'm on it.

**Comment by caspervonb** [comment]
Will most likely be fixed in the upcoming release on Friday.
