### ISSUE TITLE
"invalid op id: Uint32 expected" when trying to use deno_core

### ISSUE THREAD

**Issue by FredrikNoren** [denoland/deno#7356]
Hi,

I was just playing around with trying to get a minimal example of using deno_core (0.56.0) going, but I got stuck with an error saying "invalid op id: Uint32 expected". I basically took the http server example and removed everything until I just had a "testy" function left and tried to call that from js, like this:

```
isolate.register_op_json_sync("testy", op_testy);

...

fn op_testy(
  _state: &mut CoreIsolateState,
  _args: serde_json::Value,
  _buf: &mut [ZeroCopyBuf],
) -> Result<serde_json::Value, ErrBox> {
  println!("testy");
  Ok(serde_json::json!(()))
}
```

Then in js:
```
Deno.core.jsonOpSync("testy", { });
```

Which resulted in this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Boxed(JSError { message: "Uncaught TypeError: invalid op id: Uint32 expected", source_line: Some("    return send(opsCache[opName], control, ...zeroCopy);"), script_resource_name: Some("core.js"), line_number: Some(188), start_column: Some(11), end_column: Some(12), frames: [], formatted_frames: [] })', /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.56.0/core_isolate.rs:350:46
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  14: core::result::Result<T,E>::unwrap
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/result.rs:1005
  15: deno_core::core_isolate::CoreIsolate::shared_init
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.56.0/core_isolate.rs:350
  16: <deno_core::core_isolate::CoreIsolate as core::future::future::Future>::poll
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.56.0/core_isolate.rs:562
  17: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  18: tokio::coop::with_budget::{{closure}}
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  19: std::thread::local::LocalKey<T>::try_with
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:263
  20: std::thread::local::LocalKey<T>::with
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:239
  21: tokio::coop::with_budget
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  22: tokio::coop::budget
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  23: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  24: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  25: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  26: tokio::runtime::basic_scheduler::enter
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  27: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:123
  28: tokio::runtime::Runtime::block_on::{{closure}}
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:444
  29: tokio::runtime::context::enter
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  30: tokio::runtime::handle::Handle::enter
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  31: tokio::runtime::Runtime::block_on
             at /Users/noren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  32: pixelport2::main
             at src/main.rs:71
  33: std::rt::lang_start::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  34: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  35: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  36: std::panicking::try
             at src/libstd/panicking.rs:325
  37: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  38: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  39: std::rt::lang_start
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  40: main
```

Here's the full source: https://gist.github.com/FredrikNoren/bd6fae76cf2c1463d66e68a5b2a815a6

**Comment by bartlomieju** [comment]
@FredrikNoren make sure to call `Deno.core.ops()` in JS before dispatching ops - the error tells that `opId` is undefined - which means that ops haven't been "initialized" by JS side.

**Comment by FredrikNoren** [comment]
@bartlomieju Ah I see, that solved it! Thank you
