### ISSUE TITLE
Process.kill on a dead process results in "thread 'main' panicked at 'internal error: entered unreachable code'"

### ISSUE THREAD

**Issue by andykais** [denoland/deno#7362]
```ts
const proc = Deno.run({cmd: ['echo', 'hi']})

await proc.status()

proc.kill(Deno.Signal.SIGQUIT)
```
output:
```bash
 ✘ andrew  ~  deno run --allow-run --unstable simple.ts
Check file:///home/andrew/simple.ts
hi
thread 'main' panicked at 'internal error: entered unreachable code', cli/errors.rs:164:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    137739 abort (core dumped)  deno run --allow-run --unstable simple.ts
```

This seems like an error that is not supposed to be exposed to users of deno. On top of that, I dont actually know how I am supposed to check if a process is still alive before sending it a signal. I think ideally Process.kill should throw a catchable error if the process is no longer running.

**Comment by andykais** [comment]
I have come up with a workaround to checking if a process is closed.
```ts
class ProcessManager {
  activeProcess: Deno.Process | null
  async triggerProcess(cmd: string[]) {
    // ensure only one process is running at a time
    this.kill()
    const proc = Deno.run({ cmd })
    this.activeProcess = proc
    await proc.status()
    if (this.activeProcess.pid === proc.pid) this.activeProcess = null
  }
  kill() {
    this.activeProcess?.kill(Deno.Signal.SIGQUIT)
  }
}
```
I will keep this issue open to address the deno runtime error, but I am not blocked anymore

**Comment by mustafapc19** [comment]
Using try and catch can be used for a way around this.

**Comment by andykais** [comment]
thats actually not true. In this example, the catch and finally blocks are never reached.
```ts
try {
  console.log('try!')
  const proc = Deno.run({cmd: ['echo', 'hi']})

  await proc.status()

  console.error('kill!')
  proc.kill(Deno.Signal.SIGQUIT)
} catch(e) {
  console.error('catch!')
} finally {
  console.error('finally!')
}
```
```bash
deno run --unstable --allow-run sample-deno.ts
Check file:///Users/andrew/Code/development/hydra-ssc/sample-deno.ts
try!
hi
kill!
thread 'main' panicked at 'internal error: entered unreachable code', cli/errors.rs:164:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    9956 abort      deno run --unstable --allow-run sample-deno.ts
```
