### ISSUE TITLE
`getNBytes` throws EOF when it should wait for more input

### ISSUE THREAD

**Issue by solson** [denoland/deno#7393]
The `encoding/binary` function [`getNBytes`](https://deno.land/std@0.68.0/encoding/binary.ts#L45-L56) gives up too easily — EOF is not the only case when [`Deno.Reader#read`](https://doc.deno.land/builtin/v1.3.3#Deno.Reader) can read less than `n` bytes:

> If some data is available but not `p.byteLength` bytes, `read()` conventionally resolves to what is available instead of waiting for more.

It is possible to expose this issue through higher-level `encoding/binary` functions like `readVarnum` as well:

```console
$ cat binary_bug.ts
import { readVarnum } from "https://deno.land/std@0.68.0/encoding/binary.ts"
// Reads a 4-byte int32 varnum by default
console.log(await readVarnum(Deno.stdin));

$ echo -ne '\x01\x02\x03\x04' | xxd
00000000: 0102 0304                                ....

$ (echo -ne '\x01\x02'; sleep 1; echo -ne '\x03\x04') | xxd
00000000: 0102 0304                                ....

$ echo -ne '\x01\x02\x03\x04' | deno run binary_bug.ts
16909060

$ (echo -ne '\x01\x02'; sleep 1; echo -ne '\x03\x04') | deno run binary_bug.ts
error: Uncaught UnexpectedEof:
  if (nRead === null || nRead < n) throw new Deno.errors.UnexpectedEof();
                                         ^
    at getNBytes (binary.ts:54:42)
    at async readVarnum (binary.ts:204:19)
    at async binary_bug.ts:3:13
```

The [original Go code](https://golang.org/src/encoding/binary/varint.go#L106) avoids this problem by manually reading one byte at a time, but we could handle it more cleanly with a new `Deno.readExact` function inspired by Go's [`readFull`](https://golang.org/pkg/io/#ReadFull) (and/or `readAtLeast`) and Rust's [`read_exact`](https://github.com/rust-lang/rust/blob/5a6b426e3471382c0385c11b09c2d6b37f70ac49/library/std/src/io/mod.rs#L770-L787)<sup>1</sup>.

(I suggest `readExact` as the name because `readFull` sounds too much like a synonym for the already existing `Deno.readAll`.)

Then, `getNBytes` could be reimplemented as...

```ts
export async function getNBytes(
  r: Deno.Reader,
  n: number,
): Promise<Uint8Array> {
  const scratch = new Uint8Array(n);
  await Deno.readExact(r, scratch);
  return scratch;
}
```

...while other potential users could take advantage of the buffer re-use that `readExact` enables.

---

<sup>1</sup> There is even a [very detailed RFC](https://github.com/rust-lang/rfcs/blob/master/text/0980-read-exact.md) justifying the precise API and behaviour of `read_exact` in Rust.

**Comment by hermesespinola** [comment]
Hi @solson I'd like to give this a try 😄  I'll work on this this week
