### ISSUE TITLE
invalid certificate: UnknownIssuer

### ISSUE THREAD

**Issue by matthew-gordon** [denoland/deno#7662]
I've seen a related-ish issue but has no applicable solution for my use case.. I have been trying to test deno out for a few weeks now and no resource on stackoverflow/in issues here has resolved the problem. 

running the below command

`deno run --allow-net=example.com https://deno.land/std@0.70.0/examples/curl.ts https://example.com`

returns this output everytime

```
Download https://deno.land/std@0.70.0/examples/curl.ts
Check https://deno.land/std@0.70.0/examples/curl.ts
WARN RS - rustls::session:744 - Sending fatal alert BadCertificate
error: Uncaught Http: error sending request for url (https://example.com/): error trying to connect: invalid certificate: UnknownIssuer
    at Object.jsonOpAsync (core.js:236:13)
    at async fetch (deno:op_crates/fetch/26_fetch.js:1272:29)
    at async https://deno.land/std@0.70.0/examples/curl.ts:3:13
```

Any help on this front would be greatly appreciated, tried installing via curl command as well as homebrew

**Comment by lucacasonato** [comment]
Are you behind a corporate proxy?

**Comment by matthew-gordon** [comment]
> Are you behind a corporate proxy?

Thank you for the quick response! I am not behind a corporate proxy, I am on a personal laptop at home

**Comment by lucacasonato** [comment]
@matthew-gordon Could you run `curl -v https://example.com` and post the output here?

**Comment by matthew-gordon** [comment]
@lucacasonato 
```
$ curl -v https://example.com

*   Trying 209.67.208.202...
* TCP_NODELAY set
* Connected to example.com (209.67.208.202) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by lucacasonato** [comment]
What OS are you on? You seem to not have a recent set of root CA certificates installed. Because of this Deno (and `curl`) don't trust the certificate of `example.org`. To be able to visit `example.org` you must have at least `DigiCert Global Root CA` installed.

**Comment by matthew-gordon** [comment]
macOS Catalina 10.15.7

thank you for eliminating this as a deno bug, I will try and get this sorted 🤜  🤛

**Comment by justinmchase** [comment]
I'm getting this same error but curl from the terminal succeeds. I am behind a corporate firewall and so is the destination server. I have the same CA cert the server is using installed locally.

I am also on macOS Catalina 10.15.7

I'm using `fetch(url)` and its giving me this error:
```
Sending fatal alert BadCertificate
error: Uncaught (in promise) TypeError: error sending request for url (https://myinternaldomain.corporate.com/health): error trying to connect: invalid certificate: UnknownIssuer
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async mainFetch (deno:extensions/fetch/26_fetch.js:229:14)
```

Querying the same url using curl from the terminal gives me a success result (domains and cert details altered):
```sh
$  curl -v https://foo.bar.com/health
*   Trying 10.202.14.185...
* TCP_NODELAY set
* Connected to foo.bar.com (10.202.14.185) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=State; L=City; O=Foo Bar; OU=Baz; CN=foo.bar.com
*  start date: Oct 20 13:30:16 2020 GMT
*  expire date: Oct 20 13:30:16 2021 GMT
*  subjectAltName: host "foo.bar.com" matched cert's "foo.bar.com"
*  issuer: C=US; ST=State; L=City; O=Name; CN=More
*  SSL certificate verify ok.
> GET /health HTTP/1.1
> Host: foo.bar.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 20 Jul 2021 22:22:39 GMT
< Content-Type: text/plain
< Server: Kestrel
< Cache-Control: no-store, no-cache
< Pragma: no-cache
< Transfer-Encoding: chunked
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Strict-Transport-Security: max-age=300; includeSubDomains
< 
* Connection #0 to host foo.bar.com left intact
Healthy* Closing connection 0
```

**Comment by justinmchase** [comment]
I'm adding `--watch --cert /etc/ssl/cert.pem` and still getting the same error

> Sending fatal alert BadCertificate

Curl takes it though...

**Comment by justinmchase** [comment]
I believe this is related to https://github.com/denoland/deno/issues/10312#issuecomment-846536294

**Comment by justinmchase** [comment]
I opened a new ticket so I don't have to keep spamming this closed / invalid issue https://github.com/denoland/deno/issues/11482
