### ISSUE TITLE
module_graph::tests::source_graph_type_references is flaky

### ISSUE THREAD

**Issue by ry** [denoland/deno#7694]
https://github.com/denoland/deno/runs/1170119138
```
failures:

---- module_graph::tests::source_graph_type_references stdout ----
Error: thread 'module_graph::tests::source_graph_type_references' panicked at 'Failed to build graph: Cannot resolve module "http://localhost:4545/cli/tests/type_definitions.ts"', cli/module_graph.rs:722:8
stack backtrace:
   0:     0x560659e326f5 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x560659e326f5 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x560659e326f5 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x560659e326f5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x560659e6252c - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x560657033545 - std::io::Write::write_fmt::h1152922039931516
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/io/mod.rs:1537
   6:     0x560659e26851 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::ha927d7e5f294bce5
                               at src/libstd/io/impls.rs:176
   7:     0x560659e35460 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   8:     0x560659e35460 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   9:     0x560659e35460 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
  10:     0x560659e3515a - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:214
  11:     0x560659e35aa3 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:526
  12:     0x560659e3569b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  13:     0x560659e60be1 - core::panicking::panic_fmt::h09c929f06bb87c98
                               at src/libcore/panicking.rs:85
  14:     0x560659e60a03 - core::option::expect_none_failed::h188f17af6c9f404b
                               at src/libcore/option.rs:1269
  15:     0x560656e66c34 - core::result::Result<T,E>::expect::h59068c1fd3c070d0
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/result.rs:963
  16:     0x560656b18b80 - deno::module_graph::tests::source_graph_type_references::{{closure}}::hf73e49cda48fd106
                               at cli/module_graph.rs:720
  17:     0x560656d5edd9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h701b7c93a0689073
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  18:     0x5606567dc513 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}::h85957d687403ee44
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  19:     0x560656b6c7c6 - tokio::coop::with_budget::{{closure}}::hdd7d40cbb19de20c
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  20:     0x560656eef3e1 - std::thread::local::LocalKey<T>::try_with::hc4c9947c71195f75
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:263
  21:     0x560656ed5f0d - std::thread::local::LocalKey<T>::with::hb5e9988bb53a2cb5
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:239
  22:     0x5606567ba943 - tokio::coop::with_budget::h12f2b56ec9b6c0c3
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  23:     0x5606567ba943 - tokio::coop::budget::h7e71f32b596e4685
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  24:     0x5606567ba943 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::h02345f1d887d943c
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  25:     0x5606567ec062 - tokio::runtime::basic_scheduler::enter::{{closure}}::h1a3da75471891a28
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  26:     0x560656f0569f - tokio::macros::scoped_tls::ScopedKey<T>::set::hedad61f5c5575af6
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  27:     0x5606567df429 - tokio::runtime::basic_scheduler::enter::h04bf70506bc5b063
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  28:     0x5606567b8cab - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h1267706e8e225323
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:123
  29:     0x560656aabe3d - tokio::runtime::Runtime::block_on::{{closure}}::h02fd93dcd47b7f53
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:444
  30:     0x5606569eac37 - tokio::runtime::context::enter::h7071c8efa7d9a552
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  31:     0x560656da5aeb - tokio::runtime::handle::Handle::enter::h81ca9407a3dc53b2
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  32:     0x560656aaa9cb - tokio::runtime::Runtime::block_on::h4f19562d9a96fe91
                               at /home/runner/work/deno/deno/.cargo_home/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  33:     0x560656b18828 - deno::module_graph::tests::source_graph_type_references::hab70c3e8b22b1999
                               at cli/module_graph.rs:711
  34:     0x560656b1873a - deno::module_graph::tests::source_graph_type_references::{{closure}}::h2ec24404c4b23053
                               at cli/module_graph.rs:711
  35:     0x560656bc288e - core::ops::function::FnOnce::call_once::h92df0485c47e9fd7
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ops/function.rs:233
  36:     0x56065705aabc - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h6633cb15d0d76942
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
  37:     0x56065705aabc - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1e20120def172c5c
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:318
  38:     0x56065705aabc - std::panicking::try::do_call::hcc2ec3bbb75e9316
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
  39:     0x56065705aabc - std::panicking::try::h94eaebaaa7dd6f41
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
  40:     0x56065705aabc - std::panic::catch_unwind::h151c07c08497cf8b
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
  41:     0x56065705aabc - test::run_test_in_process::hd082de93b1922c89
                               at src/libtest/lib.rs:541
  42:     0x56065705aabc - test::run_test::run_test_inner::{{closure}}::h22369c9424e5ab3a
                               at src/libtest/lib.rs:450
  43:     0x560657032a36 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0660a89f67243e05
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/sys_common/backtrace.rs:130
  44:     0x560657037ae5 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h8bb2049509aa1add
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/mod.rs:475
  45:     0x560657037ae5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb49f3484cb9c3dd3
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:318
  46:     0x560657037ae5 - std::panicking::try::do_call::ha910a12d1577339b
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
  47:     0x560657037ae5 - std::panicking::try::hd8b3d620360e55fa
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
  48:     0x560657037ae5 - std::panic::catch_unwind::h475454730ea43154
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
  49:     0x560657037ae5 - std::thread::Builder::spawn_unchecked::{{closure}}::h2407d9379d805151
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/mod.rs:474
  50:     0x560657037ae5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haef9f772dfab225e
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ops/function.rs:233
  51:     0x560659e406da - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd2b3bc04af94a84f
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
  52:     0x560659e406da - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1044417e186e567a
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
  53:     0x560659e406da - std::sys::unix::thread::Thread::new::thread_start::h276e6ca033938925
                               at src/libstd/sys/unix/thread.rs:87
  54:     0x7f30067316db - start_thread
  55:     0x7f3006242a3f - __clone
  56:                0x0 - <unknown>


failures:
    module_graph::tests::source_graph_type_references

test result: FAILED. 258 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out

```

**Comment by bartlomieju** [comment]
I haven't encountered this failure even once. Were there more of those failures @ry?

**Comment by ry** [comment]
I think this was the only one. Tracking to see if we get more.

**Comment by bartlomieju** [comment]
Haven't seen this one in a month, closing.
