### ISSUE TITLE
std/http: unexpected error when specifying "hostname" as undefined

### ISSUE THREAD

**Issue by blockba5her** [denoland/deno#7697]
When you set the `hostname` option for `serve` to `undefined`, it results in an unexpected error:

```
error: Uncaught InvalidData: data did not match any variant of untagged enum ArgsEnum
    at Object.jsonOpSync (core.js:247:13)
    at opListen (deno:cli/rt/30_net.js:32:17)
    at Object.listen (deno:cli/rt/30_net.js:207:17)
    at serve (server.ts:287:25)
    at index.ts:3:14
```

When you do not include the `hostname` option at all, the error does not happen. It only happens when you specifically set it to `undefined` yourself.

**Reproduction Code**

```ts
import { serve } from 'https://deno.land/std@0.70.0/http/server.ts';

let server = serve({ port: 8080, hostname: undefined });
for await (let req of server) {
    req.respond({ body: 'Hello World' });
}
```

**Additional Information**

```
deno 1.4.1
deno std 0.70.0
v8 8.7.75
typescript 4.0.2
Win 10 Pro
```

**Comment by grosto** [comment]
Hi @blockba5her,

This should be an easy fix, will make a PR for it.
