### ISSUE TITLE
TS2345 Error Type 'string' is not assignable to type '"write"' with example in Permissions API

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#7731]
**Describe the bug**
TS2345 Error Type 'string' is not assignable to type '"write"' with example in Permissions API.
Manual: https://deno.land/manual/runtime/permission_apis#request-permissions

**To Reproduce**

<details>
<summary>Code</summary>

```ts
// deno run --unstable main.ts

const desc1 = { name: "read", path: "/foo" };
const status1 = await Deno.permissions.request(desc1);
// ⚠️ Deno requests read access to "/foo". Grant? [g/d (g = grant, d = deny)] g
console.log(status1);
// PermissionStatus { state: "granted" }

const desc2 = { name: "read", path: "/bar" };
const status2 = await Deno.permissions.request(desc2);
// ⚠️ Deno requests read access to "/bar". Grant? [g/d (g = grant, d = deny)] d
console.log(status2);
// PermissionStatus { state: "denied" }
```

</details>

<details>

<summary>Output</summary>

```console
$ deno run --unstable main.ts 
Check file:///home/trivikr/workspace/temp/main.ts
error: TS2345 [ERROR]: Argument of type '{ name: string; path: string; }' is not assignable to parameter of type 'PermissionDescriptor'.
  Type '{ name: string; path: string; }' is not assignable to type 'WritePermissionDescriptor'.
    Types of property 'name' are incompatible.
      Type 'string' is not assignable to type '"write"'.
const status1 = await Deno.permissions.request(desc1);
                                               ~~~~~
    at file:///home/trivikr/workspace/temp/main.ts:4:48

TS2345 [ERROR]: Argument of type '{ name: string; path: string; }' is not assignable to parameter of type 'PermissionDescriptor'.
  Type '{ name: string; path: string; }' is not assignable to type 'WritePermissionDescriptor'.
    Types of property 'name' are incompatible.
      Type 'string' is not assignable to type '"write"'.
const status2 = await Deno.permissions.request(desc2);
                                               ~~~~~
    at file:///home/trivikr/workspace/temp/main.ts:10:48

Found 2 errors.
```

</details>

**Expected behavior**
The code prompts for:
```
⚠️ Deno requests read access to "/foo". Grant? [g/d (g = grant, d = deny)] g
```

**Deno version:**
```console
$ deno --version
deno 1.4.2
v8 8.7.75
typescript 4.0.3
```

**Comment by trivikr** [comment]
The code works if the object is passed in function param directly.

<details>
<summary>Code</summary>

```ts
// deno run --unstable main.ts

const status1 = await Deno.permissions.request({ name: "read", path: "/foo" });
// ⚠️ Deno requests read access to "/foo". Grant? [g/d (g = grant, d = deny)] g
console.log(status1);
// PermissionStatus { state: "granted" }

const status2 = await Deno.permissions.request({ name: "read", path: "/bar" });
// ⚠️ Deno requests read access to "/bar". Grant? [g/d (g = grant, d = deny)] d
console.log(status2);
// PermissionStatus { state: "denied" }
```

</details>

<details>
<summary>Output</summary>

```console
$ deno run --unstable main.ts 
️⚠️  Deno requests read access to "/foo". Grant? [g/d (g = grant, d = deny)] g
PermissionStatus { state: "granted" }
️⚠️  Deno requests read access to "/bar". Grant? [g/d (g = grant, d = deny)] d
PermissionStatus { state: "denied" }
```

</details>

**Comment by nayeemrmn** [comment]
We need `as const` after the assignment right-hand-side -- patches welcome.

**Comment by trivikr** [comment]
> We need `as const` after the assignment right-hand-side -- patches welcome.

Fixed in https://github.com/denoland/deno/pull/7733
