### ISSUE TITLE
js_unit_tests startTls fails with "Network is unreachable (os error 101)"

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#7815]
**Describe the bug**
Unit test startTls fails with "Network is unreachable (os error 101)"

**Deno version**
master

**To Reproduce**
Follow steps mentioned in https://deno.land/manual/contributing/development_tools#tests to run tests:
```console
cargo test js_unit_tests
```

Unit tests fail with the following error: 

<details>
<summary>Error: Network is unreachable (os error 101)</summary>

```console
startTls
Error: Network is unreachable (os error 101)
    at Object.jsonOpAsync (core.js:236:13)
    at async Object.connect (deno:cli/rt/30_net.js:224:13)
    at async startTls (file:///home/trivikr/workspace/deno/cli/tests/unit/tls_test.ts:192:16)
    at async asyncOpSanitizer (deno:cli/rt/40_testing.js:34:7)
    at async Object.resourceSanitizer [as fn] (deno:cli/rt/40_testing.js:68:7)
    at async TestRunner.[Symbol.asyncIterator] (deno:cli/rt/40_testing.js:240:13)
    at async runTests (deno:cli/rt/40_testing.js:317:22)
    at async workerRunnerMain (file:///home/trivikr/workspace/deno/cli/tests/unit/unit_test_runner.ts:75:3)
```

</details>

<details>
<summary>Details with RUST_BACKTRACE=1</summary>

```console
---- js_unit_tests stdout ----
test_server starting...
target_dir /home/trivikr/workspace/deno/target/debug
target_dir /home/trivikr/workspace/deno/target/debug
thread 'js_unit_tests' panicked at 'assertion failed: `(left == right)`
  left: `Some(0)`,
 right: `Some(1)`', cli/tests/integration_tests.rs:699:3
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/io/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:176
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:214
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  12: rust_begin_unwind
             at src/libstd/panicking.rs:437
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:391
  14: integration_tests::js_unit_tests
             at cli/tests/integration_tests.rs:699
  15: integration_tests::js_unit_tests::{{closure}}
             at cli/tests/integration_tests.rs:685
  16: core::ops::function::FnOnce::call_once
             at /home/trivikr/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:233
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:318
  19: std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
  20: std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
  21: std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:541
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    js_unit_tests

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 288 filtered out
```

</details>

**Expected behavior**
Unit tests pass for master.

**Question:** Is some additional setup required to pass `startTls` unit tests in Deno workspace?

**Comment by trivikr** [comment]
cc @manyuanrong who'd added startTls feature+test in https://github.com/denoland/deno/pull/4773

**Comment by bnoordhuis** [comment]
@trivikr The test is looking up and connecting to smtp.gmail.com:587 but that's a port some ISPs block to combat spam.

It's probably okay to mark the test as pass when it sees that error. Want to open a pull request?

**Comment by trivikr** [comment]
> Want to open a pull request?

Sure.

> It's probably okay to mark the test as pass when it sees that error.

What's the procedure to mark a test as pass/ignore/flaky?
Is there a central config maintained somewhere or it needs to be defined per test?

The unit test to be marked as pass/ignore/flaky is https://github.com/denoland/deno/blob/2ae59318ee708306d852ffd8aae5b1ab62cb3455/cli/tests/unit/tls_test.ts#L185-L187

**Comment by trivikr** [comment]
Draft PR created at https://github.com/denoland/deno/pull/7904

How to ignore the test only when `smtp.gmail.com:587` is blocked by ISP?

**Comment by trivikr** [comment]
> We should find a way to test this without needing to connect outside of the environment by creating a mock TLS server on the localhost, like we have for other tests.

Refs: https://github.com/denoland/deno/pull/7904#issuecomment-706490056

**Comment by bartlomieju** [comment]
I can't repeat the problem. I'm going to tentatively close this issue for now. Please comment if the problem persists.
