### ISSUE TITLE
Separate build instructions for Windows

### ISSUE THREAD

**Issue by Ashniu123** [denoland/deno#802]
Hi,

I was trying to build deno on Windows when I ran into a large amount of errors. Currently also I am unable to finish my build.

After setting GYP_MSVS_VERSION by `set GYP_MSVS_VERSION 2017` (I have installed VS2017 Build Tools already), the error I am facing is this

```
E:\Workspace\Github\deno> python .\tools\setup.py
python E:\Workspace\Github\deno\third_party\depot_tools\download_from_google_storage.py --platform=win32 --no_auth --bucket=chromium-gn --sha1_file E:\Workspace\Github\deno\third_party\v8\buildtools\win\gn.exe.sha1
python E:\Workspace\Github\deno\third_party\depot_tools\download_from_google_storage.py --platform=win32 --no_auth --bucket=chromium-clang-format --sha1_file E:\Workspace\Github\deno\third_party\v8\buildtools\win\clang-format.exe.sha1
python E:\Workspace\Github\deno\third_party\v8\tools\clang\scripts\update.py --if-needed
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-338452-1.tgz .......... Done.
Traceback (most recent call last):
  File "E:\Workspace\Github\deno\third_party\v8\tools\clang\scripts\update.py", line 937, in <module>
    sys.exit(main())
  File "E:\Workspace\Github\deno\third_party\v8\tools\clang\scripts\update.py", line 933, in main
    return UpdateClang(args)
  File "E:\Workspace\Github\deno\third_party\v8\tools\clang\scripts\update.py", line 474, in UpdateClang
    CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
  File "E:\Workspace\Github\deno\third_party\v8\tools\clang\scripts\update.py", line 401, in CopyDiaDllTo
    GetWinSDKDir()
  File "E:\Workspace\Github\deno\third_party\v8\tools\clang\scripts\update.py", line 381, in GetWinSDKDir
    win_sdk_dir = vs_toolchain.SetEnvironmentAndGetSDKDir()
  File "E:\Workspace\Github\deno\third_party\v8\build\vs_toolchain.py", line 427, in SetEnvironmentAndGetSDKDir
    SetEnvironmentAndGetRuntimeDllDirs()
  File "E:\Workspace\Github\deno\third_party\v8\build\vs_toolchain.py", line 72, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "E:\Workspace\Github\deno\third_party\v8\build\vs_toolchain.py", line 154, in DetectVisualStudioPath
    ' not found.') % (version_as_year))
Exception: Visual Studio Version 2017 (from GYP_MSVS_VERSION) not found.
```
I would like to know how the current Windows build is being done and perhaps separate build steps be written for the Windows users.

**Comment by iamjesse98** [comment]
I am also getting python errors like Queue, cStringIO modules not found.

**Comment by hayd** [comment]
@iamjesse98 are you on python 2.7? Please create a separate issue with the stacktrace.

**Comment by ry** [comment]
cc @piscisaureus

**Comment by iamjesse98** [comment]
Yes I'm using python 2.7 in windows OS, I'll surely create a separate issue with stacktrace.

**Comment by Ashniu123** [comment]
Back to original topic,
I raised this because I think that it will be better to have proper build instructions for separate platforms like in some major repos ([node](https://github.com/nodejs/node/blob/master/BUILDING.md) and [vscode](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source))
so that more people can contribute to it (like me)
