### ISSUE TITLE
Error when using Deno.mkdir on Windows with absolute path

### ISSUE THREAD

**Issue by coyotte508** [denoland/deno#8036]
## Version

- deno 1.4.6
- v8 8.7.220.3
- typescript 4.0.3

## Problem

```
const dirname = new URL('../../data', import.meta.url);
console.log(dirname.toString());
await Deno.mkdir(dirname, {recursive: true});
```

![image](https://user-images.githubusercontent.com/342922/96471486-aec76c80-122f-11eb-84be-74dd93951a91.png)

Relative paths seem to work, but not absolute paths.

**Comment by piscisaureus** [comment]
I can reproduce this issue:

```
PS D:\deno> deno --version
deno 1.4.6
v8 8.7.220.3
typescript 4.0.3
PS D:\deno> cat .\test.js
const dirname = new URL('../../data', import.meta.url);
console.log(dirname.toString());
await Deno.mkdir(dirname, {recursive: true});
PS D:\deno> deno run -A .\test.js
file:///D:/data
error: Uncaught Error: The filename, directory name, or volume label syntax is incorrect. (os error 123)
    at processResponse (core.js:226:13)
    at Object.jsonOpAsync (core.js:244:12)
    at async Object.mkdir (deno:cli/rt/30_fs.js:100:5)
    at async file:///D:/deno/test.js:3:1
PS D:\deno>
```

The problem appears to be that deno.exe is trying to create the directory `D:\deno\file:\D:\data`. So deno is not treating the URL as an (absolute) URL, but as a relative file path.
