### ISSUE TITLE
Swallowed error

### ISSUE THREAD

**Issue by ry** [denoland/deno#817]
If this script is run without `--allow-write`, the error is swallowed:
```ts
import { mkdir } from "deno";

let dir = "/tmp/hello_world"
async function main() {
  console.log(`creating ${dir}...`);
  await mkdir(dir);
  console.log(`created ${dir}`);
}
main();
```

```
~/src/deno> ./out/debug/deno t.ts
creating /tmp/hello_world...
~/src/deno> echo $?
0
~/src/deno>
```

**Comment by kevinkassimo** [comment]
Could not reproduce this issue on both mac and linux (fedora) from latest master. I got the error message as expected
```
creating /tmp/hello_world...
PermissionDenied: permission denied
    at maybeError (deno/js/errors.ts:25:12)
    at handleAsyncMsgFromRust (deno/js/dispatch.ts:19:15)
```

**Comment by Bassab03** [comment]
Can't reproduce on Windows 10 build 17134 either.
```
creating /tmp/hello_world...
PermissionDenied: permission denied
    at maybeError (deno/js/errors.ts:25:12)
    at handleAsyncMsgFromRust (deno/js/dispatch.ts:18:15)
```

**Comment by ry** [comment]
Ok. I think I was experiencing this on a dev branch of some sort. It appears to be a false alarm. Thanks everyone.
