### ISSUE TITLE
Uncaught ReferenceError when running bundle created with Deno 1.5.x

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#8211]
I'm getting runtime errors when executing bundles created with Deno `1.5.x` that I didn't get in `1.4.6`:

`main.ts`:
```
example % cat main.ts 
import * as luxon from 'https://unpkg.com/luxon@1.25.0/src/luxon.js';
```

Link to module for examination: https://unpkg.com/luxon@1.25.0/src/luxon.js

Bundling with `1.5.1`:
```
example % deno --version
deno 1.5.1
v8 8.7.220.3
typescript 4.0.3

example % deno bundle main.ts main-1.5.1.bundle.js
Bundle file:///Users/jesse/example/main.ts
Check file:///Users/jesse/example/main.ts
Emit "main-1.5.1.bundle.js" (102.86KB)

example % deno run main-1.5.1.bundle.js 
error: Uncaught ReferenceError: Cannot access 'Zone' before initialization
class IANAZone extends Zone {
                       ^
    at file:///Users/jesse/example/main-1.5.1.bundle.js:2015:24

example %
```

Bundling with `1.5.0`:
```
example % deno --version
deno 1.5.0
v8 8.7.220.3
typescript 4.0.3

example % deno bundle main.ts main-1.5.0.bundle.js
Bundle file:///Users/jesse/example/main.ts
Check file:///Users/jesse/example/main.ts
Emit "main-1.5.0.bundle.js" (102.88KB)

example % deno run main-1.5.0.bundle.js 
error: Uncaught ReferenceError: Cannot access 'Zone' before initialization
class IANAZone extends Zone {
                       ^
    at file:///Users/jesse/example/main-1.5.0.bundle.js:2015:24

example %
```

Bundling with `1.4.6`:
```
example % deno --version
deno 1.4.6
v8 8.7.220.3
typescript 4.0.3

example % deno bundle main.ts main-1.4.6.bundle.js
Bundle file:///Users/jesse/example/main.ts
Emit "main-1.4.6.bundle.js" (200KB)

example % deno run main-1.4.6.bundle.js 

example %
```

Running the `1.4.6` bundle with `1.5.1`:
```
example % deno --version               
deno 1.5.1
v8 8.7.220.3
typescript 4.0.3

example % deno run main-1.4.6.bundle.js 

example %
```

Any ideas?

**Comment by lucacasonato** [comment]
cc @kdy1

**Comment by jsejcksn** [comment]
It looks like this will be fixed by https://github.com/swc-project/swc/pull/1196 in the next Deno release. Is that right?

**Comment by bartlomieju** [comment]
@jsejcksn yes, it should be available in `1.5.2` on Friday

**Comment by jsejcksn** [comment]
@bartlomieju Can I close it, or do the project members keep issues open for housekeeping tasks like release notes compilation? (I don't see a label for "fixed" / "patched" / etc.)

**Comment by kitsonk** [comment]
We will ensure it is closed when the update to swc is merged (it isn't yet).

**Comment by mvolkmann** [comment]
It seems this isn't fixed. Here are steps I took to reproduce this error in deno 1.5.4:

1. Create `demo.js` containing this:

```js
import * as c from "https://deno.land/x/case@v2.1.0/mod.ts";
const s = "one FINE day";
console.log("camel:", c.camelCase(s));
```

1. `deno bundle demo.js demob.js`
1. `deno run demob.js`
1. That gives "error: Uncaught ReferenceError: __default is not defined"

**Comment by jsejcksn** [comment]
Another reproduction case:

```
example % deno --version  
deno 1.6.0 (release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.1.2

example % cat deps.ts     
export * as luxon from 'https://unpkg.com/luxon@1.25.0/src/luxon.js';

example % cat main.ts     
import {luxon} from './deps.ts';

const date = new Date();
const dt = luxon.DateTime.fromJSDate(date);
console.log(dt.toISO());

example % deno run main.ts 
2020-12-08T15:33:21.020-06:00

example % deno bundle main.ts main.bundle.js
Bundle file:///Users/jesse/example/main.ts
Check file:///Users/jesse/example/main.ts
Emit "main.bundle.js" (159.83KB)

example % deno run main.bundle.js 
error: Uncaught ReferenceError: Cannot access '__default4' before initialization
    const DateTime1 = __default4;
                      ^
    at file:///Users/jesse/example/main.bundle.js:313:23
    at file:///Users/jesse/example/main.bundle.js:4748:2
```
