### ISSUE TITLE
`os error 2` thrown using Deno.run in Deno.test

### ISSUE THREAD

**Issue by couetilc** [denoland/deno#8217]
I'm trying to run an http server in a subprocess so I can make fetch calls against it in a test run. I first started out with an oak server, but kept running into the same error regardless if I used Deno's http server or Oak's application server.

Error:
```
NotFound: No such file or directory (os error 2)
    at processResponse (core.js:226:13)
    at Object.jsonOpSync (core.js:250:12)
    at opRun (deno:cli/rt/40_process.js:19:17)
    at Object.run (deno:cli/rt/40_process.js:103:17)
    at s.test.ts:5:33
    at asyncOpSanitizer (deno:cli/rt/40_testing.js:36:13)
    at Object.resourceSanitizer [as fn] (deno:cli/rt/40_testing.js:70:13)
    at TestRunner.[Symbol.asyncIterator] (deno:cli/rt/40_testing.js:245:24)
    at AsyncGenerator.next (<anonymous>)
    at Object.runTests (deno:cli/rt/40_testing.js:322:22)
```

Server file
```ts
// file: s.ts
import { serve } from "https://deno.land/std@0.76.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

Test file:
```ts
// file: s.test.ts
import { assertEquals } from "https://deno.land/std/testing/asserts.ts";

Deno.test('subprocess', async () => {
    // setup
    const server_process = Deno.run({
        cmd: [
            "deno run",
            "--allow-net",
            "--allow-run",
            "--allow-write",
            "--allow-read"
            `"${new URL('.', import.meta.url).pathname}s.ts"`,
        ]
    });

    // tests
    const res = await fetch('http://localhost:8000/')
    assertEquals(await res.text(), "Hello World\n")

    // teardown
    server_process.close();
});
```

Debug log from running the server: `deno run -Ldebug --allow-net s.ts`
```
DEBUG RS - deno::js:20 - Deno isolate init with snapshots.
DEBUG RS - deno_core::shared_queue:77 - rust:shared_queue:reset
DEBUG JS - cwd /Users/rene/repos/repro
DEBUG JS - args []
DEBUG RS - deno:618 - main_module file:///Users/rene/repos/repro/s.ts
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: file:///Users/rene/repos/repro/s.ts maybe_referrer: None
DEBUG RS - deno::permissions:658 - ⚠️️  Granted read access to "/Users/rene/repos/repro/s.ts"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(0) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(0) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/http/server.ts maybe_referrer: Some(
    ModuleSpecifier(
        "file:///Users/rene/repos/repro/s.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/http/server.ts"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(75) is on the line at byte pos BytePos(75)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(75) is on the line at char pos CharPos(75)
DEBUG RS - swc_common::source_map:303 - byte is on line: 2
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(121) is on the line at byte pos BytePos(121)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(121) is on the line at char pos CharPos(121)
DEBUG RS - swc_common::source_map:303 - byte is on line: 3
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(176) is on the line at byte pos BytePos(176)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(176) is on the line at char pos CharPos(176)
DEBUG RS - swc_common::source_map:303 - byte is on line: 4
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(221) is on the line at byte pos BytePos(221)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(221) is on the line at char pos CharPos(221)
DEBUG RS - swc_common::source_map:303 - byte is on line: 5
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(293) is on the line at byte pos BytePos(293)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(293) is on the line at char pos CharPos(293)
DEBUG RS - swc_common::source_map:303 - byte is on line: 6
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/io/bufio.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/http/server.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/io/bufio.ts"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(396) is on the line at byte pos BytePos(396)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(396) is on the line at char pos CharPos(396)
DEBUG RS - swc_common::source_map:303 - byte is on line: 10
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(441) is on the line at byte pos BytePos(441)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(441) is on the line at char pos CharPos(441)
DEBUG RS - swc_common::source_map:303 - byte is on line: 11
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/async/mod.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/http/server.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/async/mod.ts"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(75) is on the line at byte pos BytePos(75)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(75) is on the line at char pos CharPos(75)
DEBUG RS - swc_common::source_map:303 - byte is on line: 2
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(106) is on the line at byte pos BytePos(106)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(106) is on the line at char pos CharPos(106)
DEBUG RS - swc_common::source_map:303 - byte is on line: 3
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(134) is on the line at byte pos BytePos(134)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(134) is on the line at char pos CharPos(134)
DEBUG RS - swc_common::source_map:303 - byte is on line: 4
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(175) is on the line at byte pos BytePos(175)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(175) is on the line at char pos CharPos(175)
DEBUG RS - swc_common::source_map:303 - byte is on line: 5
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/_util/assert.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/http/server.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/_util/assert.ts"
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/encoding/utf8.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/http/server.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/encoding/utf8.ts"
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/http/_io.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/http/server.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/http/_io.ts"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(75) is on the line at byte pos BytePos(75)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(75) is on the line at char pos CharPos(75)
DEBUG RS - swc_common::source_map:303 - byte is on line: 2
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(130) is on the line at byte pos BytePos(130)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(130) is on the line at char pos CharPos(130)
DEBUG RS - swc_common::source_map:303 - byte is on line: 3
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(185) is on the line at byte pos BytePos(185)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(185) is on the line at char pos CharPos(185)
DEBUG RS - swc_common::source_map:303 - byte is on line: 4
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(230) is on the line at byte pos BytePos(230)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(230) is on the line at char pos CharPos(230)
DEBUG RS - swc_common::source_map:303 - byte is on line: 5
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(277) is on the line at byte pos BytePos(277)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(277) is on the line at char pos CharPos(277)
DEBUG RS - swc_common::source_map:303 - byte is on line: 6
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(332) is on the line at byte pos BytePos(332)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(332) is on the line at char pos CharPos(332)
DEBUG RS - swc_common::source_map:303 - byte is on line: 7
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/bytes/mod.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/io/bufio.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/bytes/mod.ts"
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/async/deferred.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/async/mod.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/async/deferred.ts"
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/async/delay.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/async/mod.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/async/delay.ts"
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/async/mux_async_iterator.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/async/mod.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/async/mux_async_iterator.ts"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(75) is on the line at byte pos BytePos(75)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(75) is on the line at char pos CharPos(75)
DEBUG RS - swc_common::source_map:303 - byte is on line: 2
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/async/pool.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/async/mod.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/async/pool.ts"
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/http/http_status.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/http/_io.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/http/http_status.ts"
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/textproto/mod.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/http/_io.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/textproto/mod.ts"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(306) is on the line at byte pos BytePos(306)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(306) is on the line at char pos CharPos(306)
DEBUG RS - swc_common::source_map:303 - byte is on line: 7
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(355) is on the line at byte pos BytePos(355)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(355) is on the line at char pos CharPos(355)
DEBUG RS - swc_common::source_map:303 - byte is on line: 8
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(397) is on the line at byte pos BytePos(397)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(397) is on the line at char pos CharPos(397)
DEBUG RS - swc_common::source_map:303 - byte is on line: 9
DEBUG RS - deno::module_graph2:747 - graph does not need to be checked or emitted.
DEBUG RS - deno::program_state:181 - Compilation statistics:

DEBUG RS - deno_core::modules:448 - register_complete file:///Users/rene/repos/repro/s.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/http/server.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/encoding/utf8.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/io/bufio.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/_util/assert.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/async/mod.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/http/_io.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/bytes/mod.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/async/deferred.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/async/delay.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/async/mux_async_iterator.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/async/pool.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/textproto/mod.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/http/http_status.ts
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "0.0.0.0:8000"
DEBUG RS - deno::ops::net:513 - New listener 3 0.0.0.0:8000
http://localhost:8000/
```

Debug log from running the test `deno test -Ldebug --allow-run --allow-net server.test.ts`
```
DEBUG RS - deno::js:20 - Deno isolate init with snapshots.
DEBUG RS - deno_core::shared_queue:77 - rust:shared_queue:reset
DEBUG JS - cwd /Users/rene/repos/repro
DEBUG JS - args []
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: file:///Users/rene/repos/repro/$deno$test.ts maybe_referrer: None
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(0) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(0) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: file:///Users/rene/repos/repro/s.test.ts maybe_referrer: Some(
    ModuleSpecifier(
        "file:///Users/rene/repos/repro/$deno$test.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted read access to "/Users/rene/repos/repro/s.test.ts"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(0) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(0) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std/testing/asserts.ts maybe_referrer: Some(
    ModuleSpecifier(
        "file:///Users/rene/repos/repro/s.test.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std/testing/asserts.ts"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(203) is on the line at byte pos BytePos(203)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(203) is on the line at char pos CharPos(203)
DEBUG RS - swc_common::source_map:303 - byte is on line: 5
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(281) is on the line at byte pos BytePos(281)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(281) is on the line at char pos CharPos(281)
DEBUG RS - swc_common::source_map:303 - byte is on line: 6
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/testing/_diff.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/testing/asserts.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/testing/_diff.ts"
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/std@0.76.0/fmt/colors.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/std@0.76.0/testing/asserts.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/std@0.76.0/fmt/colors.ts"
DEBUG RS - deno::module_graph2:747 - graph does not need to be checked or emitted.
DEBUG RS - deno::program_state:181 - Compilation statistics:

DEBUG RS - deno_core::modules:448 - register_complete file:///Users/rene/repos/repro/$deno$test.ts
DEBUG RS - deno_core::modules:448 - register_complete file:///Users/rene/repos/repro/s.test.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/testing/asserts.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/fmt/colors.ts
DEBUG RS - deno_core::modules:448 - register_complete https://deno.land/std@0.76.0/testing/_diff.ts
DEBUG RS - deno::ops::io:361 - write rid=1
running 1 tests
DEBUG RS - deno::ops::io:361 - write rid=1
test subprocess ... DEBUG RS - deno::permissions:658 - ⚠️️  Granted access to run a subprocess
DEBUG RS - deno::ops::io:361 - write rid=1
FAILED (7ms)
DEBUG RS - deno::ops::io:361 - write rid=1

failures:

DEBUG RS - deno::ops::io:361 - write rid=1
subprocess
DEBUG RS - deno::ops::io:361 - write rid=1
NotFound: No such file or directory (os error 2)
    at processResponse (core.js:226:13)
    at Object.jsonOpSync (core.js:250:12)
    at opRun (deno:cli/rt/40_process.js:19:17)
    at Object.run (deno:cli/rt/40_process.js:103:17)
    at s.test.ts:5:33
    at asyncOpSanitizer (deno:cli/rt/40_testing.js:36:13)
    at Object.resourceSanitizer [as fn] (deno:cli/rt/40_testing.js:70:13)
    at TestRunner.[Symbol.asyncIterator] (deno:cli/rt/40_testing.js:245:24)
    at AsyncGenerator.next (<anonymous>)
    at Object.runTests (deno:cli/rt/40_testing.js:322:22)
DEBUG RS - deno::ops::io:361 - write rid=1

DEBUG RS - deno::ops::io:361 - write rid=1
failures:

DEBUG RS - deno::ops::io:361 - write rid=1
        subprocess
DEBUG RS - deno::ops::io:361 - write rid=1

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (7ms)
```

Deno Info:
```
deno 1.5.1
v8 8.7.220.3
typescript 4.0.3
```

OS info:
```
macOS Mojave v10.14
```

**Comment by bartlomieju** [comment]
```
cmd: [
            "deno run",
            "--allow-net",
            "--allow-run",
            "--allow-write",
            "--allow-read"
            `"${new URL('.', import.meta.url).pathname}s.ts"`,
        ]
```
should be
```
cmd: [
            "deno",
            "run",
            "--allow-net",
            "--allow-run",
            "--allow-write",
            "--allow-read"
            `"${new URL('.', import.meta.url).pathname}s.ts"`,
        ]
```

**Comment by couetilc** [comment]
Thank you @bartlomieju ! That worked, I run into another error after waiting 10 seconds after starting the subprocess though. I will try to figure this out. Closing issue as `os error 2` is resolve

```
Http: error sending request for url (http://localhost:8000/): error trying to connect: tcp connect error: Connection refused (os error 61)
    at processResponse (core.js:226:13)
    at Object.jsonOpAsync (core.js:244:12)
    at async fetch (deno:op_crates/fetch/26_fetch.js:1273:29)
    at async s.test.ts:21:17
    at async asyncOpSanitizer (deno:cli/rt/40_testing.js:36:7)
    at async Object.resourceSanitizer [as fn] (deno:cli/rt/40_testing.js:70:7)
    at async TestRunner.[Symbol.asyncIterator] (deno:cli/rt/40_testing.js:245:13)
    at async Object.runTests (deno:cli/rt/40_testing.js:322:22)
    at async $deno$test.ts:3:1
```
