### ISSUE TITLE
Deno cache sodium results in Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sanderhahn** [denoland/deno#8229]
Reported by crowlKats on Discord:
```
deno cache -L debug https://deno.land/x/sodium@0.2.0/basic.ts

DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/x/sodium@0.2.0/basic.ts maybe_referrer: None
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/x/sodium@0.2.0/basic.ts"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(81) is on the line at byte pos BytePos(81)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(81) is on the line at char pos CharPos(81)
DEBUG RS - swc_common::source_map:303 - byte is on line: 3
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(129) is on the line at byte pos BytePos(129)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(129) is on the line at char pos CharPos(129)
DEBUG RS - swc_common::source_map:303 - byte is on line: 4
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(212) is on the line at byte pos BytePos(212)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(212) is on the line at char pos CharPos(212)
DEBUG RS - swc_common::source_map:303 - byte is on line: 8
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/x/sodium@0.2.0/basic_types.ts maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/x/sodium@0.2.0/basic.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/x/sodium@0.2.0/basic_types.ts"
DEBUG RS - deno::file_fetcher:160 - fetch_source_file specifier: https://deno.land/x/sodium@0.2.0/dist/browsers/sodium.js maybe_referrer: Some(
    ModuleSpecifier(
        "https://deno.land/x/sodium@0.2.0/basic.ts",
    ),
)
DEBUG RS - deno::permissions:658 - ⚠️️  Granted network access to "https://deno.land/x/sodium@0.2.0/dist/browsers/sodium.js"
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(911) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(911) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(1017) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(1017) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(1038) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(1038) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(295226) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(295226) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(320650) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(320650) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(320756) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(320756) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(320777) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(320777) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
DEBUG RS - swc_common::source_map:295 - byte pos BytePos(472338) is on the line at byte pos BytePos(0)
DEBUG RS - swc_common::source_map:299 - char pos CharPos(472338) is on the line at char pos CharPos(0)
DEBUG RS - swc_common::source_map:303 - byte is on line: 1
Check https://deno.land/x/sodium@0.2.0/basic.ts
DEBUG RS - deno::js:26 - Deno compiler isolate init with snapshots.
DEBUG RS - deno_core::shared_queue:77 - rust:shared_queue:reset
DEBUG TS - ">>> exec start" {"rootNames":["https://deno.land/x/sodium@0.2.0/basic.ts"]}
DEBUG TS - {"allowJs":true,"esModuleInterop":true,"experimentalDecorators":true,"incremental":true,"isolatedModules":true,"lib":["deno.window"],"module":"esnext","strict":true,"target":"esnext","tsBuildInfoFile":"deno:///.tsbuildinfo","emitDecoratorMetadata":false,"jsx":"react","inlineSourceMap":true,"outDir":"deno://","removeComments":true}
DEBUG TS - "host.readFile(\"deno:///.tsbuildinfo\")"
DEBUG TS - "host.getSourceFile(\"https://deno.land/x/sodium@0.2.0/basic.ts\", Latest)"
DEBUG TS - "host.resolveModuleNames()"
DEBUG TS - "  base: https://deno.land/x/sodium@0.2.0/basic.ts"
DEBUG TS - "  specifiers: ./basic_types.ts, ./dist/browsers/sodium.js, ./basic_types.ts"
DEBUG TS - "host.getSourceFile(\"https://deno.land/x/sodium@0.2.0/basic_types.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"https://deno.land/x/sodium@0.2.0/dist/browsers/sodium.js\", Latest)"
DEBUG TS - "host.resolveModuleNames()"
DEBUG TS - "  base: https://deno.land/x/sodium@0.2.0/dist/browsers/sodium.js"
DEBUG TS - "  specifiers: path, fs, path, crypto, path, fs, path, crypto"
DEBUG TS - "host.getSourceFile(\"deno:///none.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.deno.window.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.deno.ns.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.esnext.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2020.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2019.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2018.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2017.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2016.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2015.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es5.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2015.core.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2015.collection.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2015.iterable.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2015.symbol.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2015.generator.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2015.promise.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2015.proxy.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2015.reflect.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2015.symbol.wellknown.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2016.array.include.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2017.object.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2017.sharedmemory.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2017.string.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2017.intl.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2017.typedarrays.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2018.asynciterable.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2018.asyncgenerator.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2018.promise.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2018.regexp.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2018.intl.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2019.array.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2019.object.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2019.string.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2019.symbol.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2020.bigint.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2020.promise.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2020.string.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2020.symbol.wellknown.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.es2020.intl.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.esnext.intl.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.esnext.string.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.esnext.promise.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.esnext.weakref.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.deno.shared_globals.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.deno.web.d.ts\", Latest)"
DEBUG TS - "host.getSourceFile(\"asset:///lib.deno.fetch.d.ts\", Latest)"
DEBUG TS - "host.writeFile(\"deno://basic_types.js\")"
error: RangeError: Maximum call stack size exceeded
    at markParameterAssignments (deno:cli/tsc/00_typescript.js:62604:20)
    at visitNode (deno:cli/tsc/00_typescript.js:27028:24)
    at Object.forEachChild (deno:cli/tsc/00_typescript.js:27253:24)
    at markParameterAssignments (deno:cli/tsc/00_typescript.js:62604:20)
    at visitNode (deno:cli/tsc/00_typescript.js:27028:24)
    at Object.forEachChild (deno:cli/tsc/00_typescript.js:27253:24)
    at markParameterAssignments (deno:cli/tsc/00_typescript.js:62604:20)
    at visitNode (deno:cli/tsc/00_typescript.js:27028:24)
    at Object.forEachChild (deno:cli/tsc/00_typescript.js:27253:24)
    at markParameterAssignments (deno:cli/tsc/00_typescript.js:62604:20)
```

**Comment by kitsonk** [comment]
@sanderhahn why didn't @crowlKats open the issue?

There was a change in 1.5.X where we incorrectly didn't analyse JavaScript in some cases, and it appears that this is the case.  This is a 558k minified JavaScript file which TypeScript is trying to parse and type check.

When I download the `dist/sodium.js` locally and attempt to import it like:

```ts
import sodium from "./sodium";

console.log(sodium);
```

And then do a:

```
> tsc --allowJs test.ts
```

I basically peg my CPU and hand infinitely.

The way the package is distributed isn't ideal, as it really isn't applying the types in a support way.  The package maintainer should change their `basic.ts` to something like this:

```ts
// Copyright 2020-present the denosaurs team. All rights reserved. MIT license.

import type { Sodium } from "./basic_types.ts";
// @deno-types="./basic_types.ts";
import sodium from "./dist/browsers/sodium.js";

export default sodium;
export types * from "./basic_types.ts";
```

`./basic_types.ts` should really be a `.d.ts` file, but it contains some enums, but ideally those would be emitted in the JavaScript bundle anyways.  Also, it should ideally `export default` on the `Sodium` interface.

This will cause Deno not to look at or analyse `./dist/browsers/sodium.js`.

I suspect the author was working around challenges/limitations of Deno prior to 1.5, but it really should be updated now that a lot of these challenges are fixed.

**Comment by crowlKats** [comment]
> @sanderhahn why didn't @crowlKats open the issue?

I posted it in #help and they offered to open it.

I see, i will contact the author then.

**Comment by kitsonk** [comment]
Not really, because it is internal to TypeScript. Technically you are doing something unprocessible in TypeScript.

**Comment by sanderhahn** [comment]
Sorry, didn't know and because it was working before i thought it was a real issue. The stacktrace made it feel like a compiler error. Just tried `tsc --allowJs browsers/sodium.js` and that will not stack trace but just keeps processing. Will close the issue for now.

**Comment by kitsonk** [comment]
It used to work because it was taking advantage of bugs in Deno that are now fixed.
