### ISSUE TITLE
WebSocket server is ignoring all events after connection.

### ISSUE THREAD

**Issue by jcc10** [denoland/deno#8271]
I am currently attempting to create a wrapper for WebSockets in oak. (Then probably make something simlar to socket.io but that's another project.)

The project in reference: https://github.com/jcc10/oak_websoket_middleware

The issue is that I can't get the event loop to work. The issue seems to stem from [line 16 in echo_server.ts](https://github.com/jcc10/oak_websoket_middleware/blob/5f35ff32179973b6fa27cc8c72b125048dcbda80/echo_server.ts#L16) of the example server. Line 12 is running, this means that:

1. the middleware is loading.
2. acceptWebSocket from std/ws did not throw.
3. a websocket was passed to the handler function in echo_server.ts and has gotten past line 12.
4. line 43 is not running, this means that we are not catching the error even in the following situation.

To get a error on line 16 do the following:

1. clone & cd to project.
2. run `deno run --allow-net --allow-read example_server.ts`
3. load `http://localhost:3000/`
4. refresh the page you just loaded.
5. wait < 15 seconds.
6. :

```
BadResource: Bad resource ID  
    at unwrapResponse (rt/10_dispatch_json.js:24:13)  
    at sendSync (rt/10_dispatch_json.js:51:12)  
    at close (rt/11_resources.js:16:5)  
    at Conn.close (rt/30_net.js:87:7)  
    at WebSocketImpl.ensureSocketClosed (mod.ts:372:17)  
    at WebSocketImpl.[Symbol.asyncIterator] (mod.ts:229:14)  
    at async Echo_Server.handler (echo_server.ts:16:30)
```

Could someone tell me what stupid I'm doing?

**Comment by jcc10** [comment]
And the reason I'm opening this here is because the repo is entirely based off the ws mod in the std lib. So hopefully someone can help.

**Comment by MarkTiedemann** [comment]
Hi @jcc10, not sure what you're doing wrong there. Can you post a minimal reproduction example for your BadResource error? Something like the code below (which works well on my machine)...

```typescript
import { Application } from "https://deno.land/x/oak@v6.3.1/mod.ts";
import { acceptable, acceptWebSocket } from "https://deno.land/std@0.73.0/ws/mod.ts";

let app = new Application();
app.use(async ({ request, response }) => {
	if (acceptable(request)) {
		let req = request.serverRequest;
		let ws = await acceptWebSocket({ bufReader: req.r, bufWriter: req.w, ...req });
		for await (const ev of ws) {
			await ws.send(ev as string);
			await ws.close();
		}
	} else {
		response.body = `
			<!DOCTYPE html>
			<script>
				let ws = new WebSocket("ws://" + location.host);
				ws.onmessage = (ev) => console.log(ev.data);
				ws.onopen = () => ws.send("Hello, world!");
			</script>`;
	}
});
await app.listen({ port: 3000 });
```

**Comment by jcc10** [comment]
And see, your example works.

```
import {
    Application
} from "https://deno.land/x/oak@v6.3.1/mod.ts";
import { WebSocket, acceptWebSocket } from 'https://deno.land/std@0.76.0/ws/mod.ts'

async function handler(ws: WebSocket): Promise<void> {

    // Register user connection
    await ws.send(`${Date.now()} is connected`);
    console.info(`Line 13, ws.constructor.name: ${ws.constructor.name}`);
    // Wait for new messages
    try {
        for await (const ev of ws) {
            console.log(ev);
            await ws.send(ev as string);
        }
    } catch (err) {
        console.error(`failed to receive frame: ${err}`);

        if (!ws.isClosed) {
            await ws.close(1000).catch(console.error);
        }
    }

}

const app = new Application();
app.use(async (ctx: any, next: any) => {
    if(ctx.request.url.pathname != "/ws") {
    return await next();
}
if (ctx.request.headers.get("upgrade") !== "websocket") {
    ctx.response.status = 200;
    return;
}

const req = ctx.request.serverRequest;

try {
    const ws = await acceptWebSocket({ bufReader: req.r, bufWriter: req.w, ...req });

    handler(ws);
    return;
} catch (err) {
    console.error(`Dev Server failed to accept websocket: ${err}`);
    ctx.response.status = 400;
}
    }
);
app.use(async (ctx: any, next: any) => {
    ctx.response.body = `<!DOCTYPE html>
<html lang="en">
<body>
    <script>
        const socket = new WebSocket(\`ws://\${window.location.host}/ws\`);
        socket.onmessage = (event) => {
            console.log("WS: " + event.data);
        }
        setTimeout(() => {
            socket.send("test");
            console.log("test sent out");
        }, 1000)
    </script>
</body>
</html>`;
});

console.log("Server running on localhost:3000");
await app.listen({ port: 3000 });
```

Load the page, refresh the page, wait no more then 60 seconds and the error will pop up.

**Comment by MarkTiedemann** [comment]
Seems to be an issue with Oak.

This code works fine:

```typescript
// deno run -A ws.ts

import { serve, ServerRequest } from "https://deno.land/std@0.73.0/http/server.ts";
import { acceptable, acceptWebSocket } from "https://deno.land/std@0.73.0/ws/mod.ts";

async function handleWebsocket(req: ServerRequest) {
  let ws = await acceptWebSocket({ bufReader: req.r, bufWriter: req.w, ...req });
  for await (const ev of ws) {
    await ws.send(ev as string);
    await ws.close();
  }
}

function handleHttp(req: ServerRequest) {
  req.respond({
    body: `
      <!DOCTYPE html>
      <script>
          let ws = new WebSocket("ws://" + location.host);
          ws.onmessage = (ev) => console.log(ev.data);
          ws.onopen = () => ws.send("Hello, world!");
      </script>`,
  });
}

for await (let req of serve({ port: 3000 })) {
  if (acceptable(req)) {
    handleWebsocket(req);
  } else {
    handleHttp(req);
  }
}
```

Whereas this code produces the BadResource ID error.

```typescript
// deno run -A ws_oak.ts

import { Application, Context } from "https://deno.land/x/oak@v6.3.1/mod.ts";
import { acceptable, acceptWebSocket } from "https://deno.land/std@0.73.0/ws/mod.ts";

async function handleWebsocket(ctx: Context) {
  let req = ctx.request.serverRequest;
  let ws = await acceptWebSocket({ bufReader: req.r, bufWriter: req.w, ...req });
  for await (const ev of ws) {
    await ws.send(ev as string);
    await ws.close();
  }
}

function handleHttp(ctx: Context) {
  ctx.response.body = `
    <!DOCTYPE html>
    <script>
        let ws = new WebSocket("ws://" + location.host);
        ws.onmessage = (ev) => console.log(ev.data);
        ws.onopen = () => ws.send("Hello, world!");
    </script>`;
}

let app = new Application();
app.use(async (ctx) => {
  if (acceptable(ctx.request)) {
    handleWebsocket(ctx);
  } else {
    handleHttp(ctx);
  }
});
await app.listen({ port: 3000 });
```

This is the stacktrace:

```
BadResource: Bad resource ID
    at processResponse (core.js:226:13)
    at jsonOpSync (core.js:250:12)
    at Object.close (core.js:266:5)
    at Conn.close (deno:cli/rt/30_net.js:90:12)
    at WebSocketImpl.ensureSocketClosed (mod.ts:372:17)
    at WebSocketImpl.[Symbol.asyncIterator] (mod.ts:229:14)
    at async handleWebsocket (ws_oak.ts:7:20)
```

Seems like Oak is calling `Conn.close` after the async `app.use` handler which is destroying the websocket connection. So I guess you'll have to find a way to keep Oak from closing your connection.

**Comment by MarkTiedemann** [comment]
@jcc10 Turns out that Oak has support for Websockets already:

```typescript
import { Application, Context } from "https://deno.land/x/oak@v6.3.1/mod.ts";
import { acceptable } from "https://deno.land/std@0.73.0/ws/mod.ts";

async function handleWebsocket(ctx: Context) {
  let ws = await ctx.upgrade();
  for await (const ev of ws) {
    await ws.send(ev as string);
    await ws.close();
  }
}

function handleHttp(ctx: Context) {
  ctx.response.body = `
    <!DOCTYPE html>
    <script>
        let ws = new WebSocket("ws://" + location.host);
        ws.onmessage = (ev) => console.log(ev.data);
        ws.onopen = () => ws.send("Hello, world!");
    </script>`;
}

let app = new Application();
app.use(async (ctx) => {
  if (acceptable(ctx.request)) {
    await handleWebsocket(ctx);
  } else {
    handleHttp(ctx);
  }
});
await app.listen({ port: 3000 });
```

From the documentation of `ctx.upgrade`:
> Take the current request and upgrade it to a web socket, resolving with the web socket object. This will set `.respond` to `false`.

**Comment by jcc10** [comment]
@MarkTiedemann thank you and everyone on the Discord server for being so patent with me.

As it turns out, I had a intermediary function that wasn't async/await. This added with the fact that Firefox was not handling the Invalid Frame Header correctly meant I had no idea what was going wrong and, in fact, thought the initial connection was fine. (It wasn't.)

```
return (ctx: any, next: any) => { this.real_middleware(ctx, next) };
```
Needed to be
```
return async (ctx, next) => { await this.real_middleware(ctx, next) };
```
