### ISSUE TITLE
thread 'main' panicked at 'Cached source file doesn't exist'

### ISSUE THREAD

**Issue by ayntee** [denoland/deno#8279]
Without `RUST_BACKTRACE`
```bash
Check file:///home/test1/test.ts
thread 'main' panicked at 'Cached source file doesn't exist', cli/program_state.rs:206:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With `RUST_BACKTRACE=1`:
```bash
thread 'main' panicked at 'Cached source file doesn't exist', cli/program_state.rs:206:8
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
   3: core::option::Option<T>::expect
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
   6: <deno_core::modules::RecursiveModuleLoad as futures_core::stream::Stream>::poll_next
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: deno::run_command::{{closure}}
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: tokio::runtime::Runtime::block_on
  12: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

With `RUST_BACKTRACE=full`:

```bash
thread 'main' panicked at 'Cached source file doesn't exist', cli/program_state.rs:206:8
stack backtrace:
   0:     0x55a2c2b0bd83 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55a2c2b0bd83 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55a2c2b0bd83 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:     0x55a2c2b0bd83 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:     0x55a2c27a11ac - core::fmt::write::h9ddafa4860d8adff
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:     0x55a2c2b0b5b6 - std::io::Write::write_fmt::h1d2ee292d2b65481
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:     0x55a2c2b0af40 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:     0x55a2c2b0af40 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:     0x55a2c2b0af40 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:     0x55a2c2b0a638 - std::panicking::default_hook::he30ad7589e0970f9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:     0x55a2c2b0a638 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:     0x55a2c2b0a2d8 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
  12:     0x55a2c2b0a2a4 - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
  13:     0x55a2c2b0a25d - rust_begin_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
  14:     0x55a2c279e880 - core::panicking::panic_fmt::h4e2659771ebc78eb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
  15:     0x55a2c27a58c2 - core::option::expect_failed::hd5a1da3a6b6bbb34
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
  16:     0x55a2c25e5c63 - core::option::Option<T>::expect::hb09dbc765aa5ae29
  17:     0x55a2c265b4a4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdde66c28789f890e
  18:     0x55a2c27b6e08 - <core::pin::Pin<P> as core::future::future::Future>::poll::hdcc7cb1733f8f646
  19:     0x55a2c27b6603 - <deno_core::modules::RecursiveModuleLoad as futures_core::stream::Stream>::poll_next::he006242bd12754af
  20:     0x55a2c2656264 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9b3f326a1b645f86
  21:     0x55a2c2658d8b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc92eb54ac15f0a05
  22:     0x55a2c27439ad - deno::run_command::{{closure}}::h2731d1858f4ccaf6
  23:     0x55a2c265509b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h84023c1f02b7ced5
  24:     0x55a2c2618192 - tokio::runtime::Runtime::block_on::h7148315b848bf24b
  25:     0x55a2c274d551 - deno::main::hfcf455f2df1a44ec
  26:     0x55a2c25b5495 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcc04b8b81d5e1708
  27:     0x55a2c2754494 - main
  28:     0x7f0c5579a0b3 - __libc_start_main
  29:     0x55a2c252433a - _start
  30:                0x0 - <unknown>
```

**Comment by lucacasonato** [comment]
Can you add a dump of `deno info /home/test1/test.ts` to this issue?

**Comment by ayntee** [comment]
> Can you add a dump of `deno info /home/test1/test.ts` to this issue?

https://hastebin.com/locilesava

**Comment by lucacasonato** [comment]
@ayntee Ok - I will close then. Did you run with 1.4.x previously and then upgrade to 1.5?

For Google searchability: the solution is to delete your `$DENO_DIR`. You can find the location of the deno dir by running `deno info`. Then delete the entire deno dir folder.
