### ISSUE TITLE
Deno.compile panic -- declaration: true

### ISSUE THREAD

**Issue by TradeIdeasPhilip** [denoland/deno#8289]
When I run the code below Deno panics.  It does not continue running and I cannot catch anything.

I can fix the code by removing the "declaration" flag.  I was expecting that flag to create the .d.ts files.  Without that flag Deno returns the name and contents of the JavaScript files, and that works as expected.

100% repeatable.  Same results on Windows and Linux.

```
[phil@joey-mousepad static]$ cat RunOnServer.ts                                 
const opt : Deno.CompilerOptions = { declaration: true };
try {
  const output = await Deno.compile("./RunOnClient.ts", undefined, opt);
  // Never gets here!
  console.log("./RunOnClient.ts", output);
} catch (ex) {
  // Or here!
  console.log("Caught error", ex);
}
[phil@joey-mousepad static]$ cat RunOnClient.ts
// Compile this to *.js then run it on the client, a web page.
console.log("Hello world.");
[phil@joey-mousepad static]$ deno run --unstable --allow-all RunOnServer.ts
thread 'main' panicked at 'Trying to cache unknown file type file:///home/phil/cpp_alert_server/deno/admin/static/RunOnClient.d.ts', cli/tsc.rs:344:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[phil@joey-mousepad static]$ env RUST_BACKTRACE=1 deno run --unstable --allow-all RunOnServer.ts
thread 'main' panicked at 'Trying to cache unknown file type file:///home/phil/cpp_alert_server/deno/admin/static/RunOnClient.d.ts', cli/tsc.rs:344:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
   2: deno::tsc::runtime_compile::{{closure}}
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   5: <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll
   6: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   7: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
   8: deno_core::runtime::JsRuntime::poll_event_loop
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: deno::run_command::{{closure}}
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: tokio::runtime::Runtime::block_on
  13: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[phil@joey-mousepad static]$ uname -a
Linux joey-mousepad 4.13.16-100.fc25.x86_64 #1 SMP Mon Nov 27 19:52:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[phil@joey-mousepad static]$ deno --version
deno 1.5.1
v8 8.7.220.3
typescript 4.0.3
[phil@joey-mousepad static]$
```

**Comment by kitsonk** [comment]
In Deno 1.5.2 the behaviour is different, as we refactored that bit of code, but it still was a terminal error.  It is fixed though in #8303.
