### ISSUE TITLE
Sometimes CI loses its ability to connect to the net

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#8332]
An example: https://github.com/denoland/deno/runs/1375569003#step:16:3872

**Comment by bartlomieju** [comment]
```
test [examples/chat] GET / should serve html ... test test_permissions_with_allow ... ok
ok (2914ms)
error: Uncaught (in promise) AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
    at processResponse (core.js:223:11)
    at Object.jsonOpSync (core.js:246:12)
    at opListen (deno:cli/rt/30_net.js:32:17)
    at Object.listen (deno:cli/rt/30_net.js:207:17)
    at serve (file:///D:/a/deno/deno/std/http/server.ts:301:25)
    at listenAndServe (file:///D:/a/deno/deno/std/http/server.ts:321:18)
    at file:///D:/a/deno/deno/std/examples/chat/server.ts:34:1
error: Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promise.
```

https://github.com/denoland/deno/runs/1465359528

**Comment by kitsonk** [comment]
This does seem to have abated.
