### ISSUE TITLE
WebSocket silently exits if --allow-net is not enabled

### ISSUE THREAD

**Issue by Apacheli** [denoland/deno#8394]
```ts
const socket = new WebSocket('wss://gateway.discord.gg');

socket.onmessage = (ev) => console.log(ev.data);
```
WebSocket silently exits if --allow-net flag is not enabled. Expected behavior should be network access error.
* Deno: 1.5.2
* TypeScript: 4.x

**Comment by lucacasonato** [comment]
I am pretty sure the error is reported through the onerror event of the websocket.

**Comment by MarkTiedemann** [comment]
> I am pretty sure the error is reported through the onerror event of the websocket.

Yes. Running...

```typescript
let ws = new WebSocket("wss://gateway.discord.gg");
ws.onopen = (ev) => console.log("open", ev);
ws.onmessage = (ev) => console.log("message", ev);
ws.onerror = (ev) => console.log("error", ev);
ws.onclose = (ev) => console.log("close", ev);
```

...with...

```
C:\> deno run test.ts
```

...prints...

```js
error ErrorEvent {
  bubbles: false,
  cancelable: false,
  composed: false,
  currentTarget: EventTarget {
    [Symbol(eventHandlers)]: Map {
      "open" => [Function: wrappedHandler],
      "message" => [Function: wrappedHandler],
      "error" => [Function: wrappedHandler],
      "close" => [Function: wrappedHandler]
    }
  },
  defaultPrevented: false,
  eventPhase: 2,
  target: EventTarget {
    [Symbol(eventHandlers)]: Map {
      "open" => [Function: wrappedHandler],
      "message" => [Function: wrappedHandler],
      "error" => [Function: wrappedHandler],
      "close" => [Function: wrappedHandler]
    }
  },
  timeStamp: 1605551101691,
  type: "error",
  message: 'PermissionDenied: network access to "wss://gateway.discord.gg/", run again with the --allow-net flag',
  filename: "",
  lineno: 0,
  colno: 0,
  error: PermissionDenied: network access to "wss://gateway.discord.gg/", run again with the --allow-net flag
    at processResponse (core.js:224:13)
    at Object.jsonOpAsync (core.js:242:12)
}
```
```js
close CloseEvent {
  bubbles: false,
  cancelable: false,
  composed: false,
  currentTarget: EventTarget {
    [Symbol(eventHandlers)]: Map {
      "open" => [Function: wrappedHandler],
      "message" => [Function: wrappedHandler],
      "error" => [Function: wrappedHandler],
      "close" => [Function: wrappedHandler]
    }
  },
  defaultPrevented: false,
  eventPhase: 2,
  target: EventTarget {
    [Symbol(eventHandlers)]: Map {
      "open" => [Function: wrappedHandler],
      "message" => [Function: wrappedHandler],
      "error" => [Function: wrappedHandler],
      "close" => [Function: wrappedHandler]
    }
  },
  timeStamp: 1605551101699,
  type: "close",
  wasClean: false,
  code: 0,
  reason: ""
}
```

This is consistent with the browser, except that, in the browser, no `close` event is emitted (which makes sense to me - if it was not `open`ed first, it probably should not be `close`d).

**Comment by MarkTiedemann** [comment]
At the same time, I think it makes sense to separate Deno permission errors from connection errors.

**Comment by crowlKats** [comment]
> which makes sense to me - if it was not `open`ed first, it probably should not be `close`d

That is behaviour as per spec, see https://html.spec.whatwg.org/multipage/web-sockets.html#the-websocket-interface:concept-websocket-closed

**Comment by crowlKats** [comment]
But regarding the connection error, it should indeed not be caught by the WS and sent in the error event. 

https://github.com/denoland/deno/blob/ab7b8ba8d15f37d6244784a16a3f4f3c96e38769/cli/rt/27_websocket.js#L92

Currently we catch all errors; maybe a check if the error message starts with `PermissionDenied`? Wouldnt really be ideal, but would do the job...

**Comment by lucacasonato** [comment]
@crowlKats We can check if it is a `Deno.errors.PermissionDenied` error

**Comment by crowlKats** [comment]
perfect
