### ISSUE TITLE
Cargo test fails _074_worker_nested_error

### ISSUE THREAD

**Issue by Dygear** [denoland/deno#8410]
Only two issues on the 1.5.3 build with test, I've commented on the other one already and this is one that doesn't seem to have an issue attached to it.
```
failures:

---- _074_worker_nested_error stdout ----
target_dir /home/pi/deno/target/debug
root path /home/pi/deno/test_util/..
deno_exe path /home/pi/deno/target/debug/deno
target_dir /home/pi/deno/target/debug
deno_exe args run -A 074_worker_nested_error.ts
deno_exe tests path "/home/pi/deno/test_util/../cli/tests"
OUTPUT
Check file:///home/pi/deno/cli/tests/074_worker_nested_error.ts
Check file:///home/pi/deno/cli/tests/073_worker_error.ts
Check file:///home/pi/deno/cli/tests/subdir/worker_error.ts

OUTPUT
thread '_074_worker_nested_error' panicked at 'bad exit code, expected: 1, actual: 0', test_util/src/lib.rs:867:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
pi@pi400:~/deno $ export RUST_BACKTRACE=1
pi@pi400:~/deno $ cargo test -p deno --test integration_tests
    Finished test [unoptimized + debuginfo] target(s) in 1.81s
     Running target/debug/deps/integration_tests-3cc1836bbdeee374

running 316 tests
[snip]
test _074_worker_nested_error ... FAILED
[snip]
OUTPUT
thread '_074_worker_nested_error' panicked at 'bad exit code, expected: 1, actual: 0', test_util/src/lib.rs:867:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
   2: test_util::CheckOutputIntegrationTest::run
             at /home/pi/deno/test_util/src/lib.rs:867
   3: integration_tests::_074_worker_nested_error
             at ./tests/integration_tests.rs:1735
   4: integration_tests::_074_worker_nested_error::{{closure}}
             at ./tests/integration_tests.rs:1734
   5: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
   6: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
Not really getting any helpful information from the `RUST_BACKTRACE` environment variable.

**Comment by bartlomieju** [comment]
Is there any error printed out? It's hard to debug with so little info

**Comment by kitsonk** [comment]
I believe this relates to building on ARM64 (ref: #1846) for clarity purposes.  Really need to try to be more clear on what is trying to be accomplished here.

**Comment by Dygear** [comment]
@bartlomieju There is no error at all printed out. Just the backtrace that I have and the failed test case. @kitsonk Is correct, I'm building this on an ARM64 kernel on the Raspberry Pi 400.

**Comment by bartlomieju** [comment]
@Dygear I'm going to close this issue for now. We don't provide official builds for Arm64 so it's really hard to say what might be causing this. Once we'll start working towards #1846 this issue will be addressed accordingly.
