### ISSUE TITLE
client.connect()

### ISSUE THREAD

**Issue by B-Griffinn** [denoland/deno#8417]
Hello When running `client.connect()` i am receiving the following error: err Error: 
```md
Unknown auth message code 10
    at Connection.handleAuth (connection.ts:197:15)
    at Connection.startup (connection.ts:155:16)
    at async Client.connect (client.ts:14:5)
    at async addProduct (products.ts:88:13)
    at async dispatch (middleware.ts:41:7)
    at async dispatch (middleware.ts:41:7)
    at async dispatch (middleware.ts:41:7)
    at async Application.#handleRequest (application.ts:252:9)
```

Here is my code:

```ts
const addProduct = async ({ request, response }: { request: any, response: any }) => {
    // capture the body of the incoming request aka the new product being added to our DB
    // body() method returns a promise which is why we need async await
    const body = await request.body()
    // single out the product from the body
    const product = await body.value
    console.log('product', product)

    // check and ensure the user has provided the end point with the proper information
    if (!product) {
        console.log('im in the IF')
        response.status = 400
        response.body = {
            success: false,
            message: 'Please provide the required information.'
        }
    } else {
        console.log('im in the ELSE')
        try {            
        console.log('im in the TRY')

            // connect to our db to make queries
            await client.connect()
           const result = await client.query("INSERT INTO products(name, description, price) VALUES($1, $2, $3)", 
           product.name,
           product.description,
           product.price)

           response.status = 201
           response.body = {
               success: true,
               data: product
           }
       } catch (error) {
           response.status = 500
           response.body = {
               success: false,
               message: `SERVER ERROR ${error}`
           }
           console.log('err', error)
       } finally {
           await client.end()
       }
    }
}   
```

**Comment by MarkTiedemann** [comment]
This is not an issue with Deno but an authentication issue with your database driver.

https://github.com/deno-postgres/deno-postgres/issues/182
