### ISSUE TITLE
EventEmitter not default export of events node shim

### ISSUE THREAD

**Issue by juliangruber** [denoland/deno#8501]
In node both of these work, but deno only supports the former:

```js
const { EventEmitter } = require('events')
const EventEmitter = require('events')
```

**Comment by ayntee** [comment]
1. https://deno.land/std@0.79.0/node/events.ts#L54

2. https://deno.land/std@0.79.0/node/events.ts#L554

**Comment by juliangruber** [comment]
Steps to reproduce:

```js
// node.js
const EventEmitter = require('events')
console.log(new EventEmitter())
```

```ts
// deno.ts
import { createRequire } from "https://deno.land/std@0.79.0/node/module.ts";
const require = createRequire(import.meta.url);
require("./node.js");
```

```bash
$ deno run --unstable --allow-read --allow-env deno.ts
error: Uncaught TypeError: EventEmitter is not a constructor
    at Object.<anonymous> (file:///home/julian/Desktop/nt/node.js:2:13)
    at Module._compile (module.ts:160:36)
    at Object.Module._extensions..js (module.ts:1079:10)
    at Module.load (module.ts:139:34)
    at Function._load (module.ts:405:14)
    at Module.require (module.ts:125:21)
    at require (module.ts:1128:16)
    at deno.ts:3:1
```

**Comment by juliangruber** [comment]
I think this is due to how the module is reexported in

https://deno.land/std@0.79.0/node/module.ts#L25 and https://deno.land/std@0.79.0/node/module.ts#L598
