### ISSUE TITLE
Unknown extension during import of dependency module

### ISSUE THREAD

**Issue by agolomoodysaada** [denoland/deno#852]
myfile.ts

```ts
import * as inquirer from 'https://unpkg.com/inquirer@6.2.0/lib/inquirer.js'
```

run deno version: v0.1.5

```sh
deno myfile.ts
```

Error shows up

```
Error: Debug Failure. File /Users/myusername/.deno/deps/unpkg.com/inquirer@6.2.0/lib/objects/separator has unknown extension.
    at Object.extensionFromPath (deno/third_party/node_modules/typescript/lib/typescript.js:14997:48)
    at deno/third_party/node_modules/typescript/lib/typescript.js:82567:46
    at Array.map (<anonymous>)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:82561:195)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:82768:24)
    at processImportedModules (deno/third_party/node_modules/typescript/lib/typescript.js:84005:35)
    at findSourceFile (deno/third_party/node_modules/typescript/lib/typescript.js:83880:17)
    at processImportedModules (deno/third_party/node_modules/typescript/lib/typescript.js:84041:25)
    at findSourceFile (deno/third_party/node_modules/typescript/lib/typescript.js:83880:17)
    at deno/third_party/node_modules/typescript/lib/typescript.js:83739:85
```

**Comment by kevinkassimo** [comment]
```js
inquirer.Separator = require('./objects/separator');
```
This caused the file to be downloaded as `separator`, which does not have an extension. Furthermore, I believe the package still has a lot of issues besides this one, including its reliance on `package.json` for importing other modules (like `chalk`).

**Comment by agolomoodysaada** [comment]
Should deno be able to support certain features at import time? What's the course of action here?

**Comment by ry** [comment]
I'm not opposed to supporting it - it'll make adoption easier.

**Comment by kitsonk** [comment]
@ry point though, your not implying supporting `require()` though, so this would still fail.

**Comment by agolomoodysaada** [comment]
Closing this issue in favor of #857 discussion. Thank you everyone
