### ISSUE TITLE
Deno can't bundle tensorflow.js from Skypack

### ISSUE THREAD

**Issue by ryanwhite04** [denoland/deno#8597]
- deno 1.5.4 (bc79d55, release, x86_64-unknown-linux-gnu)
- v8 8.8.278.2
- typescript 4.0.5

Using the command:

```deno bundle https://cdn.skypack.dev/@tensorflow/tfjs tfjs.js```

I get the following error: 

```
Bundle https://cdn.skypack.dev/@tensorflow/tfjs
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_bundler-0.17.1/src/bundler/chunk/merge.rs:128:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: core::option::Option<T>::unwrap
   4: scoped_tls::ScopedKey<T>::set
   5: core::iter::adapters::map_fold::{{closure}}
   6: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
   7: core::iter::traits::iterator::Iterator::collect
   8: swc_bundler::bundler::chunk::merge::<impl swc_bundler::bundler::Bundler<L,R>>::merge_deps
   9: swc_bundler::bundler::chunk::merge::<impl swc_bundler::bundler::Bundler<L,R>>::merge_modules
  10: scoped_tls::ScopedKey<T>::set
  11: scoped_tls::ScopedKey<T>::set
  12: core::iter::adapters::map_fold::{{closure}}
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
  14: core::iter::traits::iterator::Iterator::collect
  15: swc_bundler::bundler::chunk::merge::<impl swc_bundler::bundler::Bundler<L,R>>::merge_deps
  16: swc_bundler::bundler::chunk::merge::<impl swc_bundler::bundler::Bundler<L,R>>::merge_modules
  17: swc_bundler::bundler::chunk::<impl swc_bundler::bundler::Bundler<L,R>>::chunk
  18: deno::module_graph::Graph::emit_bundle
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: tokio::runtime::Runtime::block_on
  22: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```
I can't figure out what it means or how to fix it.

Deno seems to be able to bundle other libraries from Skypack correctly such as 

``````deno bundle https://cdn.skypack.dev/lit-element lit-element.js```

So it could just be a problem with tensorflow.

**Comment by lucacasonato** [comment]
cc @kdy1
