### ISSUE TITLE
runUrl Test fails due to Permission error

### ISSUE THREAD

**Issue by iammack** [denoland/deno#8599]
Linux Distro: Ubuntu Bionic
```cargo test``` fails with 

```
failures:

runUrl
PermissionDenied: Permission denied (os error 13)
    at processResponse (core.js:223:11)
    at Object.jsonOpSync (core.js:246:12)
    at opRun (deno:cli/rt/40_process.js:19:17)
    at Object.run (deno:cli/rt/40_process.js:103:17)
    at runUrl (file:///home/mayank/Documents/Projects/Deno/deno/cli/tests/unit/process_test.ts:39:18)
    at async asyncOpSanitizer (deno:cli/rt/40_testing.js:36:7)
    at async Object.resourceSanitizer [as fn] (deno:cli/rt/40_testing.js:70:7)
    at async TestRunner.[Symbol.asyncIterator] (deno:cli/rt/40_testing.js:245:13)
    at async runTests (deno:cli/rt/40_testing.js:322:22)
    at async workerRunnerMain (file:///home/mayank/Documents/Projects/Deno/deno/cli/tests/unit/unit_test_runner.ts:75:3)

failures:

	runUrl

test result: FAILED. 18 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (1026ms)

```

**Comment by bartlomieju** [comment]
Looks like tests is failing when trying to call Python using file URL. @iammack please make sure your Python binary has proper permissions for the user you're running the tests as.

**Comment by iammack** [comment]
Yes, I wasn't able to reproduce this on a different machine. Thanks @bartlomieju . Closing as not error in deno.
