### ISSUE TITLE
TS1243 [ERROR]: 'async' modifier cannot be used with 'abstract' modifier.

### ISSUE THREAD

**Issue by hoangtranson** [denoland/deno#8690]
I am using Deno now and deploy it to Heroku. Today my deployment get this issue

```
TS1243 [ERROR]: 'async' modifier cannot be used with 'abstract' modifier.
remote:   public abstract async encrypt(m: Uint8Array): Promise<Uint8Array>;
remote:                   ~~~~~
remote:     at https://cdn.jsdelivr.net/gh/invisal/god_crypto@22eb70429c998d84a57e786217c277373fbeca9f/src/aes/aes_base.ts:2:19
remote: 
remote: TS1243 [ERROR]: 'async' modifier cannot be used with 'abstract' modifier.
remote:   public abstract async decrypt(m: Uint8Array): Promise<Uint8Array>;
remote:                   ~~~~~
remote:     at https://cdn.jsdelivr.net/gh/invisal/god_crypto@22eb70429c998d84a57e786217c277373fbeca9f/src/aes/aes_base.ts:3:19
remote: 
```
Then, I have opened the file and its content is like this:

```
export abstract class AESBase {
  public abstract async encrypt(m: Uint8Array): Promise<Uint8Array>;
  public abstract async decrypt(m: Uint8Array): Promise<Uint8Array>;
}
```

I have no idea how to fix it. Really need some help or any clue to resolve this issue.

![error](https://user-images.githubusercontent.com/35447677/101652863-b65e0180-3a79-11eb-9400-b07a3e269529.png)

**Comment by hastri** [comment]
Deno 1.6 upgraded Typescript to 4.1

https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#abstract-members-cant-be-marked-async

**Comment by hoangtranson** [comment]
Could you give me more information @hastri ?

Here is my Deno version that I just upgrade today. Before that my code running well. 

```
deno 1.6.0 (release, x86_64-unknown-linux-gnu)
v8 8.8.278.2
typescript 4.1.2
```

I want to remove this error out of my code. But the problem is that it is not from my code.

**Comment by lucacasonato** [comment]
It needs to be resolved upstream in the library you are importing from.

**Comment by invisal** [comment]
This is from my library. I am working on fixing to support Deno 1.6.0

https://github.com/invisal/god_crypto/pull/20

**Comment by ITT-2153** [comment]
I have the same problem, i tried to update Deno but it didn't work.
Error:
```
error: TS1243 [ERROR]: 'async' modifier cannot be used with 'abstract' modifier.
  public abstract async encrypt(m: Uint8Array): Promise<Uint8Array>;
                  ~~~~~
    at https://cdn.jsdelivr.net/gh/invisal/god_crypto@22eb70429c998d84a57e786217c277373fbeca9f/src/aes/aes_base.ts:2:19

TS1243 [ERROR]: 'async' modifier cannot be used with 'abstract' modifier.
  public abstract async decrypt(m: Uint8Array): Promise<Uint8Array>;
                  ~~~~~
    at https://cdn.jsdelivr.net/gh/invisal/god_crypto@22eb70429c998d84a57e786217c277373fbeca9f/src/aes/aes_base.ts:3:19
```

This is the content of the links:
```
Couldn't find the requested file /src/aes/aes_base.ts:2:19 in invisal/god_crypto.
Couldn't find the requested file /src/aes/aes_base.ts:3:19 in invisal/god_crypto.
```
Deno version (updated):
```
deno 1.6.0 (release, x86_64-pc-windows-msvc)
v8 8.8.278.2
typescript 4.1.2
```

**Comment by Korin92** [comment]
I have the same problem and de updated >= 2.0 not found
