### ISSUE TITLE
Internal error while debugging a HTTP server and making a request

### ISSUE THREAD

**Issue by Pronian** [denoland/deno#8895]
The following Rust error is thrown when in debug mode and making a request with the browser:
```
/home/terr/.deno/bin/deno run --allow-net --inspect-brk -A mod.ts
Debugger listening on ws://127.0.0.1:9229/ws/3f36ddc5-a570-43a0-82d8-83f46120c9d0
Check file:///home/terr/Documents/deno/deno-res-serv/mod.ts
Debugger session started.
http://localhost:8000/
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', core/bindings.rs:426:3
stack backtrace:
   0:     0x55873ec9c523 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55873ec9c523 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55873ec9c523 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55873ec9c523 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55873e7f197c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55873ec9bd11 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55873ec9b615 - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55873ec9b615 - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55873ec9b615 - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55873ec9b615 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55873ec9b615 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55873ecb5728 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55873ecb56f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55873ecb56ad - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55873ecb5670 - std::panicking::begin_panic_fmt::hf0503558fbe5b251
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
  15:     0x55873e8021e3 - <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn::h08c027467655b1c4
  16:     0x55873f4d4649 - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  17:     0x55873f4d3b60 - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  18:     0x55873f4d313b - _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
  19:     0x55873f3a0538 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
fatal runtime error: failed to initiate panic, error 5

```
Tested and reproducible on versions: `v1.6.2` and `v1.5.4`

Tested and reproducible on OSes: `Manjaro Linux 20.2` with `kernel 5.4.80` and `Windows 10 version 20H2`

Steps to reproduce:

1. Create a `mod.ts` file with these contents:
```Typescript
import { serve } from "https://deno.land/std@0.82.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```
2. Open in VS code and create the following launch option:
```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Deno",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "env": {
                "RUST_BACKTRACE": "full"
            },
            "runtimeExecutable": "deno",
            "runtimeArgs": ["run","--allow-net", "--inspect-brk","-A", "mod.ts"],
            "outputCapture": "std",
            "port": 9229,
        }
    ]
} 
```
3. Run this launch option by starting a debug session and wait for program to load
4. Open `http://localhost:8000/` in browser
5. Observe debug console in VS Code

Note: Does not happen when starting the program normally: `deno run --allow-net mod.ts`

**Comment by Pronian** [comment]
I re-checked this issue on `v1.7.1` and it's still reproducible.

**Comment by bartlomieju** [comment]
@Pronian we've had major rework to inspector infrastructure recently, does it problem still happen for you?

**Comment by Pronian** [comment]
Hello @bartlomieju !

I just checked and it's no longer reproducible on `v1.11.2` We can close this.
