### ISSUE TITLE
thread 'main' panicked at 'Error 'IO error: Broken pipe (os error 32)'

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#8936]
**Error:**
thread 'main' panicked at 'Error 'IO error: Broken pipe (os error 32)' contains boxed error of unknown type', cli/errors.rs:35:7

When I first started moving my code to a production environment I was hit with this error after about 30 minutes. I had no idea what could be causing it. `Note:` This same code runs without issues for days in a canary build. Moving it to production causes this. Something about scaling it causes rust to throw this error.

```ts
0|prod  | thread 'main' panicked at 'Error 'IO error: Broken pipe (os error 32)' contains boxed error of unknown type', cli/errors.rs:35:7
0|prod  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I decided to mess around with any interval codes I had running at exactly 30 minutes and changed it to 2 minutes. Suddenly this error started happening after 2 minutes. So i ran it with the RUST_BACKTRACE=1

```rust
thread 'main' panicked at 'Error 'IO error: Broken pipe (os error 32)' contains boxed error of unknown type', cli/errors.rs:35:7
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: deno::errors::get_error_class_name::{{closure}}
   3: deno::errors::get_error_class_name
   4: deno_core::ops::json_serialize_op_result
   5: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   6: <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll
   7: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   8: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
   9: deno_core::runtime::JsRuntime::poll_event_loop
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: tokio::runtime::Runtime::block_on
  13: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Then I ran it with full

```rust
stack backtrace:
   0:        0x1053f6bd3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcfc48256a5ab8835
   1:        0x104f3e020 - core::fmt::write::haf3903118f694c48
   2:        0x1053f6286 - std::io::Write::write_fmt::h7385463ac87804ed
   3:        0x1053f5ade - std::panicking::rust_panic_with_hook::hae2b05f08a320721
   4:        0x10541195c - std::panicking::begin_panic_handler::{{closure}}::h72d68d3a77e0b718
   5:        0x105411927 - std::sys_common::backtrace::__rust_end_short_backtrace::h7c5e286792f94edb
   6:        0x1054118e0 - _rust_begin_unwind
   7:        0x10614bacf - std::panicking::begin_panic_fmt::h6826a3ebe3a95a51
   8:        0x104e8c351 - deno::errors::get_error_class_name::{{closure}}::he7b5cf43a7440e79
9:        0x104e8c29b - deno::errors::get_error_class_name::h6a78aa1aa634d3b5
  10:        0x104f5eb16 - deno_core::ops::json_serialize_op_result::h6b15b9e9885e5494
  11:        0x10512209a - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::hc177adc862a150b8
  12:        0x1050a534c - <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll::h0f12552e99f7d31d
  13:        0x104f51cf8 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h60e442913a0948da
  14:        0x104f5439f - <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next::hab8299b4a2fd1563
  15:        0x104f633b4 - deno_core::runtime::JsRuntime::poll_event_loop::h51bc4e4307314fd8
  16:        0x104e40fa6 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h496c19454c0453cd
  17:        0x104e4d6ef - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha3de6ef56dc3002c
  18:        0x1050b1e04 - tokio::runtime::Runtime::block_on::hdd7ada3fea6b85d6
  19:        0x104ee6769 - deno::main::h958eb9d50f1f6eb6
  20:        0x104cfea82 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3d0e7ff309beb454
  21:        0x104ef1b5b - _main
```

---

The code that causes this is almost certainly this loop. I am not sure why this would matter but seemingly as soon as this loop finishes logging everything a second or two later this error appears crashing the process.

```ts
export function sweepInactiveGuildsCache() {
  for (const guild of cache.guilds.values()) {
    if (botCache.activeGuildIDs.has(guild.id)) continue;

    console.log(`[DISPATCH] Removing Guild ${guild.name} with ID: ${guild.id}`);
    // This is inactive guild. Not a single thing has happened for atleast 30 minutes.
    // Not a reaction, not a message, not any event!

    for (const channel of cache.channels.values()) {
      if (channel.guildID !== guild.id) continue;
      cache.channels.delete(channel.id);
      botCache.dispatchedChannelIDs.add(channel.id);
    }

    cache.guilds.delete(guild.id);
    botCache.dispatchedGuildIDs.add(guild.id);
  }

  // Reset activity for next interval
  botCache.activeGuildIDs.clear();
}
```

**Comment by bartlomieju** [comment]
What OS and Deno version are you using?

**Comment by Skillz4Killz** [comment]
Skillz@Home gamer-deno % deno --version
deno 1.6.2 (release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.1.3

![image](https://user-images.githubusercontent.com/23035000/103362966-f8320480-4a87-11eb-9ae4-2d0375d1128b.png)

**Comment by bnoordhuis** [comment]
@Skillz4Killz v1.6.3 was released yesterday and there's a pretty good chance it contains the fix if canary builds work okay for you.

**Comment by Skillz4Killz** [comment]
![image](https://user-images.githubusercontent.com/23035000/104028926-500ef080-5197-11eb-806a-f46e4b50740b.png)

![image](https://user-images.githubusercontent.com/23035000/104028943-543b0e00-5197-11eb-86c9-78585267057c.png)
![image](https://user-images.githubusercontent.com/23035000/104028952-57ce9500-5197-11eb-91f6-54c6d7218bca.png)

**Comment by KnorpelSenf** [comment]
This happens also when running `deno bundle` and piping it to a program that does not read from stdin. In my case, I wanted to count the lines of the bundled output, so I ran
```
deno bundle https://deno.land/x/grammy@v0.3.1/mod.ts | wc -h
```
which reproduces the issue. Notice the typo for `wc`, it should be `-l`, not `-h`, which is why `wc` exits immediately.

```
$ uname -v && deno --version 
#1 SMP Debian 4.19.181-1 (2021-03-19)
deno 1.8.3 (release, x86_64-unknown-linux-gnu)
v8 9.0.257.3
typescript 4.2.2
```

**Comment by cmoog** [comment]
#11039 should fix the panic behavior here.

**Comment by bartlomieju** [comment]
We are now mapping all possible errors to a runtime exceptions so this issue should no longer be relevant. I'm going to tentatively close it.
