### ISSUE TITLE
Deno.tls in 1.6.2 and 1.6.3 not working correctly

### ISSUE THREAD

**Issue by aricart** [denoland/deno#8994]
Haven't verified a reason on the server side, as I need to get a properly configured server and look at our logs, but clients that do tls upgrades under 1.6.3 are not connecting (had been working correctly until 1.6.2). Likely there's a cypher/curve that was removed from deno - our server currently supports:

```
Available cipher suites include:
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    TLS_RSA_WITH_3DES_EDE_CBC_SHA
    TLS_RSA_WITH_AES_128_CBC_SHA256
    TLS_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
    TLS_AES_128_GCM_SHA256
    TLS_AES_256_GCM_SHA384
    TLS_RSA_WITH_RC4_128_SHA
    TLS_RSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    TLS_CHACHA20_POLY1305_SHA256
    TLS_ECDHE_RSA_WITH_RC4_128_SHA
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    TLS_RSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256

Available curve preferences include:
    X25519
    CurveP256
    CurveP384
    CurveP521
```

```
❯ deno upgrade --version 1.6.2
Version 1.6.2 is already installed
❯ deno run --allow-all --unstable https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/nats-pub.ts -s demo.nats.io:4443 test foo
Check https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/nats-pub.ts
error: Uncaught (in promise) NatsError: TIMEOUT
    return new NatsError(m, code, chainedError);
           ^
    at Function.errorForCode (error.ts:102:12)
    at util.ts:153:24
    at fire (deno:runtime/js/11_timers.js:444:5)
    at handleTimerMacrotask (deno:runtime/js/11_timers.js:305:7)

❯. deno upgrade --version 1.6.1
Checking https://github.com/denoland/deno/releases/download/v1.6.1/deno-x86_64-apple-darwin.zip
Download has been found
Deno is upgrading to version 1.6.1
Archive:  /var/folders/1y/_rk6yz81341g5q8k1vr5nqmw0000gq/T/.tmp9miLs1/deno.zip
  inflating: deno                    
Upgraded successfully
❯ deno run --allow-all --unstable https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/nats-pub.ts -s demo.nats.io:4443 test foo
Check https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/nats-pub.ts
[1] test: foo
```

**Comment by lucacasonato** [comment]
We are going to need a little more info here. What TLS APIs are you using?

**Comment by aricart** [comment]
tls connection upgrade.
```  export function startTls(
    conn: Conn,
    options?: StartTlsOptions
  ): Promise<Conn>;
```

**Comment by aricart** [comment]
@lucacasonato  - found the issue. If the `StartTlsOption.certFile` has an empty value the connection fails. Previous behaviour ignored the empty string value.

**Comment by aricart** [comment]
> @lucacasonato - found the issue. If the `StartTlsOption.certFile` has an empty value the connection fails. Previous behaviour ignored the empty string value.

hold on - StartTlsOption.certFile may not have anything to do with this.

**Comment by aricart** [comment]
Creating a new issue, with better information.
