### ISSUE TITLE
PermissionDenied errors are misleading in self-contained binaries

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#9002]
```
~/p/g/d/deno ❯❯❯ deno compile --unstable https://deno.land/std@0.79.0/examples/cat.ts CODE_OF_CONDUCT.md 
Check https://deno.land/std@0.79.0/examples/cat.ts
Bundle https://deno.land/std@0.79.0/examples/cat.ts
Compile https://deno.land/std@0.79.0/examples/cat.ts
Emit cat
~/p/g/d/deno ❯❯❯ ./cat
error: PermissionDenied: read access to "CODE_OF_CONDUCT.md", run again with the --allow-read flag
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpAsync (deno:core/core.js:240:12)
    at async Object.open (deno:runtime/js/30_files.js:44:17)
    at async file://$deno$/bundle.js:3:18
```

`run again with the --allow-read flag` makes no sense in self-contained binaries because after (#8738) permissions are embedded in the binary and can't be changed. 

In this situation we should provide different message.

CC @lucacasonato @nayeemrmn

**Comment by yos1p** [comment]
Is it possible for this to be check during compile time? That'd be great so that users don't need to re-compile again.

**Comment by bartlomieju** [comment]
> Is it possible for this to be check during compile time? That'd be great so that users don't need to re-compile again.

No, permission can only be checked during runtime.

**Comment by Spoonbender** [comment]
I wonder how to fix this.
Currently, the error message is being built at `permissions.rs`:
```rust
impl PermissionState {
  /// Check the permission state.
  fn check(self, msg: &str, flag_name: &str) -> Result<(), AnyError> {
    if self == PermissionState::Granted {
      log_perm_access(msg);
      return Ok(());
    }
    let message = format!("{}, run again with the {} flag", msg, flag_name);
    Err(custom_error("PermissionDenied", message))
  }
}
```

Without much thought, I see three possible approaches here:
1. `check` will receive an argument telling it if we're in a self-contained binary, and build the error message accordingly. This will require flowing this argument throughout the callstack...
2. `check` will deduce if we're running in a self-contained binary autonomously, perhaps by checking some ambient/global state. Examples:
    - On startup, a self-contained binary will set some environment variable (`DENO__SELF_CONTAINED`) which `check` will inspect
    - `check` will inspect the `std::env::current_exe` to deduce if we are "deno" or some other process
3. `check` will not produce the "help text" ("run again with..."). Instead, the "help text" will be appended to the printed message at a higher-layer, near the surface. That location could inspect the error struct fields (like `class`) and combine that with knowledge of deno's running mode (self-contained, CLI, REPL) to provide contextually-relevant help text. (Do notice that the `class` field is currently set to `PermissionDenied`, which is insufficient to distinguish read permission errors from write permission errors, so we'll need to refine the class or add another field, maybe `error_code`).

**Comment by lucacasonato** [comment]
This is now done.
