### ISSUE TITLE
Connection to language server got closed unexpectedly

### ISSUE THREAD

**Issue by finalwhy** [denoland/deno#9024]
### test

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
> Info  - 下午6:50:12] Connection to server got closed. Server will restart.
[Error - 下午6:50:12] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\main.js:904:25)
	at Object.dispose (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-languageclient\lib\client.js:74:35)
	at LanguageClient.handleConnectionClosed (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-languageclient\lib\client.js:2309:42)
	at LanguageClient.handleConnectionClosed (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-languageclient\lib\main.js:155:15)
	at closeHandler (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-languageclient\lib\client.js:2296:18)
	at CallbackList.invoke (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at closeHandler (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\main.js:240:26)
	at CallbackList.invoke (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at StreamMessageReader.fireClose (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.<anonymous> (c:\Users\45180\.vscode\extensions\denoland.vscode-deno-canary-0.0.6\client\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)

**Versions**

vscode: 1.52.1
deno: 1.6.3
extension: canary 0.0.6

**Comment by kitsonk** [comment]
This is an issue with the lsp.  I believe it is related to #8753.

**Comment by satyarohith** [comment]
@finalwhy are you still having this issue?

**Comment by kitsonk** [comment]
No, I believe this specific issue was resolved when #8753 was resolved.
