### ISSUE TITLE
deno upgrade --canary fails with thread main panicked

### ISSUE THREAD

**Issue by starkpsmichael** [denoland/deno#9048]
Trying to upgrade from v1.6.3 to latest canary:

```sh
Checking https://dl.deno.land/canary/e61e81eb57351782862aa50775ce4348f10b1856/deno-x86_64-unknown-linux-gnu.zip
Download has been found
Deno is upgrading to version e61e81eb57351782862aa50775ce4348f10b1856
Archive:  /tmp/.tmpFypHxG/deno.zip
  inflating: deno
error: 
thread 'main' panicked at 'assertion failed: output.status.success()', cli/tools/upgrade.rs:254:3
stack backtrace:
   0: std::panicking::begin_panic
   1: deno::tools::upgrade::upgrade_command::{{closure}}
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: tokio::runtime::Runtime::block_on
   4: deno::main
```

**Comment by lucacasonato** [comment]
Does it work if you run the command again?

**Comment by lucacasonato** [comment]
Nevermind. I can reproduce too.

```
~/p/g/d/deno ❯❯❯ export RUST_BACKTRACE=1
~/p/g/d/deno ❯❯❯ deno upgrade --canary --force
Looking up latest version
Found latest version e61e81eb57351782862aa50775ce4348f10b1856
Checking https://dl.deno.land/canary/e61e81eb57351782862aa50775ce4348f10b1856/deno-x86_64-unknown-linux-gnu.zip
Download has been found
Deno is upgrading to version e61e81eb57351782862aa50775ce4348f10b1856
Archive:  /tmp/.tmpZIAe97/deno.zip
  inflating: deno                    
error: 
thread 'main' panicked at 'assertion failed: output.status.success()', cli/tools/upgrade.rs:254:3
stack backtrace:
   0: std::panicking::begin_panic
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:521:12
   1: deno::tools::upgrade::check_exe
             at ./cli/tools/upgrade.rs:254:3
   2: deno::tools::upgrade::upgrade_command::{{closure}}
             at ./cli/tools/upgrade.rs:117:3
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
   5: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131:58
   6: tokio::coop::with_budget::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127:9
   7: std::thread::local::LocalKey<T>::try_with
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
   8: std::thread::local::LocalKey<T>::with
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
   9: tokio::coop::with_budget
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120:5
  10: tokio::coop::budget
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96:5
  11: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131:35
  12: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213:29
  13: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63:9
  14: tokio::runtime::basic_scheduler::enter
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213:5
  15: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:123:9
  16: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:444:34
  17: tokio::runtime::context::enter
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72:5
  18: tokio::runtime::handle::Handle::enter
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76:9
  19: tokio::runtime::Runtime::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441:9
  20: deno::tokio_util::run_basic
             at ./cli/tokio_util.rs:24:3
  21: deno::main
             at ./cli/main.rs:1259:18
  22: core::ops::function::FnOnce::call_once
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
~/p/g/d/deno ❯❯❯ deno -V
deno 1.6.3error: 
```

That `error:` looks like the issue.

**Comment by starkpsmichael** [comment]
Btw, why looks my backtrace other than yours? 😓

Using alpine and sh in a vscode devcontainer.

**Comment by lucacasonato** [comment]
@starkpsmichael I am using a debug build. Those have more verbose stack traces :-)

**Comment by starkpsmichael** [comment]
> @starkpsmichael I am using a debug build. Those have more verbose stack traces :-)

👍 Thx for explaining! I have to fork deno too 😓
