### ISSUE TITLE
Benchmark CI stage panics and doesn't fail

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#9050]
Example: https://github.com/denoland/deno/runs/1666284126

There's a lot of JS code intertwined in the panic backtrace

```
Error: thread 'main' panicked at 'failed printing to stdout: Resource temporarily unavailable (os error 11)', library/std/src/io/stdio.rs:1021:9
stack backtrace:
   0:     0x56439a267cd3 - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
            return ***
                y: down.y + 1,
                id: ptr
            ***;
        ***
    ***
<snip>
   1:     0x56439a267cd3 - std::backtrace_rs::backtrace::trace_unsynchronized::h1459b974b6fbe5e1
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56439a267cd3 - std::sys_common::backtrace::_print_fmt::h9b8396a669123d95
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56439a267cd3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x564399dad58c - core::fmt::write::h77b4746b0dea1dd3
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:     0x56439a267571 - std::io::Write::write_fmt::heb7e50902e98831c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:     0x56439a266f35 - std::sys_common::backtrace::_print::h2d880c9e69a21be9
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56439a266f35 - std::sys_common::backtrace::print::h5f02b1bb49f36879
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56439a266f35 - std::panicking::default_hook::***closure***::h658e288a7a809b29
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:     0x56439a266515 - std::panicking::default_hook::hb52d73f0da9a4bb8
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:     0x56439a266515 - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:     0x56439a281a18 - std::panicking::begin_panic_handler::***closure***::h42939e004b32765c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
  12:     0x56439a28198c - std::sys_common::backtrace::__rust_end_short_backtrace::h9d2070f7bf9fd56c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x56439a28193d - rust_begin_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  14:     0x56439a281900 - std::panicking::begin_panic_fmt::h4a7e15187eac098d
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
  15:     0x56439a28b69e - std::io::stdio::print_to::h1a7efc3ff8ad6f06
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1021:9
  16:     0x56439a28b69e - std::io::stdio::_print::h0a0a01475e28ce35
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1033:5
  17:     0x564399cb0955 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha277817d9a7e1114
  18:     0x564399c94156 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h029fea4d3610b190
  19:     0x564399f18ad0 - tokio::runtime::Runtime::block_on::h8580a3c9862f8273
  20:     0x564399d52480 - deno::main::h3c15fd13117d944e
  21:     0x564399b6dbfa - std::sys_common::backtrace::__rust_begin_short_backtrace::h0c51cd69dd6c6ad4
  22:     0x564399d6235d - main
  23:     0x7fc5010c7bf7 - __libc_start_main
  24:     0x564399b0613a - _start
  25:                0x0 - <unknown>
```

**Comment by littledivy** [comment]
Closing. deno_core has moved to `denoland/deno_core` and we've not seen this panic i think.
