### ISSUE TITLE
Unix socket server crashes with errno 22 when client closes without reading

### ISSUE THREAD

**Issue by mk12** [denoland/deno#9051]
A Unix socket server (stream) will crash with errno 22 (EINVAL) if a client connects to it and closes without attempting to read.

### Repro

Server:

```typescript
// server.ts
const listener = Deno.listen({ transport: "unix", path: "sock" });
for await (const conn of listener) {
  Deno.copy(conn, conn).finally(() => conn.close());
}
```

Client:

```python
# client.py
import socket
sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
sock.connect("sock")
# sock.recv(1)  # uncommenting prevents server crash
sock.close()
```

Run the server:

```
$ deno run --unstable --allow-read --allow-write server.ts
```

Run the client:

```
$ python3 client.py
```

Server result:

```
Check file:///path/to/server.ts
error: Uncaught (in promise) TypeError: Invalid argument (os error 22)
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpAsync (deno:core/core.js:240:12)
    at async Listener.accept (deno:cli/rt/30_net.js:117:19)
    at async Listener.next (deno:cli/rt/30_net.js:124:16)
    at async file:///path/to/server.ts:2:18
```

If you uncomment the indicated line in client.py, this does not happen.

The same thing happens with the following C client:

```c
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/un.h>
#include <unistd.h>

int main(void) {
    int sock = socket(AF_UNIX, SOCK_STREAM, 0);
    if (sock == -1) { perror("socket"); return 1; }
    struct sockaddr_un addr;
    addr.sun_family = AF_UNIX;
    strcpy(addr.sun_path, "sock");
    if (connect(sock, (struct sockaddr*)&addr, sizeof addr) == -1) {
        perror("connect");
        return 1;
    }
    // char buf[1]; recv(sock, buf, 1, 0);  // uncommenting prevents server crash 
    close(sock);
    return 0;
}
```

### Environment

macOS Catalina 10.15.7

Installed deno via `brew install deno`.

```
$ deno --version
deno 1.6.0 (release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.1.2
```

**Comment by bnoordhuis** [comment]
I can reproduce on macOS but not Linux. The error originates here:

https://github.com/denoland/deno/blob/cd2f7ae69d85c56d4865423f6f76d6911f7fe8a6/runtime/ops/net_unix.rs#L84

The peer is already gone and the kernel signals that by returning EINVAL. We could either:

1. Chalk this up as a platform difference - regrettable but reality, or

2. ignore the error and retry:

<details>

```diff
diff --git a/runtime/ops/net_unix.rs b/runtime/ops/net_unix.rs
index 23981a7f..443038bf 100644
--- a/runtime/ops/net_unix.rs
+++ b/runtime/ops/net_unix.rs
@@ -68,20 +68,25 @@ pub(crate) async fn accept_unix(
 ) -> Result<Value, AnyError> {
   let rid = args.rid as u32;
 
-  let resource = state
-    .borrow()
-    .resource_table
-    .get::<UnixListenerResource>(rid)
-    .ok_or_else(|| bad_resource("Listener has been closed"))?;
-  let mut listener = RcRef::map(&resource, |r| &r.listener)
-    .try_borrow_mut()
-    .ok_or_else(|| custom_error("Busy", "Listener already in use"))?;
-  let cancel = RcRef::map(resource, |r| &r.cancel);
-  let (unix_stream, _socket_addr) =
-    listener.accept().try_or_cancel(cancel).await?;
-
-  let local_addr = unix_stream.local_addr()?;
-  let remote_addr = unix_stream.peer_addr()?;
+  let (unix_stream, local_addr, remote_addr) = loop {
+    let resource = state
+      .borrow()
+      .resource_table
+      .get::<UnixListenerResource>(rid)
+      .ok_or_else(|| bad_resource("Listener has been closed"))?;
+    let mut listener = RcRef::map(&resource, |r| &r.listener)
+      .try_borrow_mut()
+      .ok_or_else(|| custom_error("Busy", "Listener already in use"))?;
+    let cancel = RcRef::map(resource, |r| &r.cancel);
+    let (unix_stream, _socket_addr) =
+      listener.accept().try_or_cancel(cancel).await?;
+    let local_addr = unix_stream.local_addr()?;
+    let remote_addr = match unix_stream.peer_addr() {
+      Ok(remote_addr) => remote_addr,
+      Err(_) => continue, // Peer closed connection.
+    };
+    break (unix_stream, local_addr, remote_addr);
+  };
   let resource = StreamResource::unix_stream(unix_stream);
   let mut state = state.borrow_mut();
   let rid = state.resource_table.add(resource);
```

</details>

**Comment by mk12** [comment]
Thanks for investigating. I assume this doesn't happen in other languages/frameworks on macOS because they don't eagerly get the peer address after accepting a connection?

When I (new to Deno, not really familiar with Node) write `for await (const conn of listener) { ... }`, I expect my program to wait for a connection. I might want to put a try/catch around the loop in case that fails. But even if I do that, I think I'd have no way of knowing if the EINVAL is from `accept(2)` or the hidden `getpeername(2)` call.

Would it be possible to make `Deno.Conn.remoteAddr` as lazily-loaded property that only invokes the syscall on first access? If not, I think the retry loop seems reasonable.

**Comment by bnoordhuis** [comment]
@bartlomieju WDYT? I'd prefer the simple retry loop. Looking at `runtime/ops/net.rs`, TCP likely has the same issue.

Talking about - it bubbles up `ConnectionAborted` errors, when the client RSTs before the server can accept? I'd ignore those for the reason @mk12 mentioned, it isn't actionable for user scripts.

**Comment by mk12** [comment]
Was pleased to see the email that this was fixed until I realized it was one of these awful stale bots.
