### ISSUE TITLE
Panic while formatting error

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#9077]
Stack unwind:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/fmt_errors.rs:211:45
stack backtrace:
   0:     0x55d18d4104a3 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55d18d4104a3 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55d18d4104a3 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55d18d4104a3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55d18cf5ca3c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55d18d40fc91 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55d18d40f595 - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55d18d40f595 - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55d18d40f595 - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55d18d40f595 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55d18d40f595 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55d18d4296a8 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55d18d429674 - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55d18d42962d - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55d18cf5a030 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x55d18cf59e4c - core::panicking::panic::h184ede6dd822ffb4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:     0x55d18cd4de67 - core::option::Option<T>::unwrap::h00128de0aadcc2ac
  17:     0x55d18ceb7db4 - <deno::fmt_errors::PrettyJsError as core::fmt::Display>::fmt::h60dcb48dfb5fb3f0
  18:     0x55d18cf5ca3c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
  19:     0x55d18cf620d3 - core::fmt::Formatter::write_fmt::h610a3b7429e5462e
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1509
  20:     0x55d18cf20718 - anyhow::error::<impl core::fmt::Display for anyhow::Error>::fmt::h908d2c3d7f1d9f3c
  21:     0x55d18cf5ca3c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
  22:     0x55d18cf620d3 - core::fmt::Formatter::write_fmt::h610a3b7429e5462e
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1509
  23:     0x55d18cf20718 - anyhow::error::<impl core::fmt::Display for anyhow::Error>::fmt::h908d2c3d7f1d9f3c
  24:     0x55d18cf5ca3c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
  25:     0x55d18d3f4764 - core::fmt::Write::write_fmt::h076b1b3611776a3c
  26:     0x55d18cd2a558 - <T as alloc::string::ToString>::to_string::hfaf68a090b8ed610
  27:     0x55d18cf02f60 - deno::main::ha2d27aa65e12940b
  28:     0x55d18cd2286a - std::sys_common::backtrace::__rust_begin_short_backtrace::h9a5cc0e9c63a2e26
  29:     0x55d18cf112c2 - main
  30:     0x7fdfde1a3bf7 - __libc_start_main
  31:     0x55d18ccc04ba - _start
  32:                0x0 - <unknown>
```

Attached is the actual file that I was working on when this happened.
[panic.txt](https://github.com/denoland/deno/files/5792216/panic.txt)
file.ts may be an empty file.
I tried to cut down the file to a minimum reproducible example, but it wasn't working without everything.

Run with `--no-check`, this does not occur without it.

I believe that the bad formatting is on line 37, `(_, i)`.

**Comment by nayeemrmn** [comment]
Duplicate of #6965.

**Comment by 00ff0000red** [comment]
@nayeemrmn Are you sure that these are the same?
Their error was the result of an active, runtime exception, mine is the result of the parser running before even running my TS.

**Comment by nayeemrmn** [comment]
Yes, I don't think it has anything to do with what causes the error. That code tries to read the source line of an error with some incorrect assumptions.

**Comment by 00ff0000red** [comment]
Okay, I guess I can see that parallel between them, I'll re-close it.

**Comment by lucacasonato** [comment]
@00ff0000red Can you try on canary (`deno upgrade --canary`)? I might have fixed this last week by accident.

**Comment by 00ff0000red** [comment]
I was going to try running on canary yesterday, but I'd forgotten to; I'll try it soon.

**Comment by 00ff0000red** [comment]
@lucacasonato
Ran the code that caused the panic, upgraded to canary, re-ran and it worked flawlessly.

Do you think that what you had done fixed https://github.com/denoland/deno/issues/6965 too?
