### ISSUE TITLE
Error: No such host is known

### ISSUE THREAD

**Issue by FSou1** [denoland/deno#9122]
I am trying to connect to a MongoDB instance with various Deno packages (e.g. deno_mongo, denodb).

All of them throw the error, which seems like a part of the framework:

```
error: Uncaught (in promise) Error: No such host is known. (os error 11001)
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpAsync (deno:core/core.js:240:12)
    at async Object.connect (deno:runtime/rt/30_net.js:224:13)
    at async MongoClient.connect (client.ts:20:18)
    at async MongoDBConnector._makeConnection (mongodb-connector.ts:42:7)
    at async MongoDBConnector.query (mongodb-connector.ts:65:5)
    at async Database.query (database.ts:227:21)
    at async Function.createTable (model.ts:161:5)
    at async Database.sync (database.ts:197:7)
```

Any reason why this host is not supported: `mongodb+srv://admin:RehlmKTm5pr9f9MG@cluster0.vsk29.mongodb.net` ?

**Comment by lucacasonato** [comment]
This is the issue tracker for Deno, not third party packages for Deno. Please ask your question on denodb or deno_mongo repo.

**Comment by FSou1** [comment]
Could it be a framework issue?
