### ISSUE TITLE
Regression: ReadableStream pipeThrough() assertion failed

### ISSUE THREAD

**Issue by danopia** [denoland/deno#9252]
Seems like pipeThrough crashes when given just one argument starting in Deno 1.7.0.

```typescript
const resp = await fetch("https://example.com");
resp.body.pipeThrough(new TransformStream());
```

```
error: Uncaught (in promise) AssertionError: Assertion failed.
      throw new AssertionError(msg);
            ^
    at assert (deno:op_crates/fetch/11_streams.js:25:13)
    at readableStreamPipeTo (deno:op_crates/fetch/11_streams.js:1223:5)
    at ReadableStream.pipeThrough (deno:op_crates/fetch/11_streams.js:3148:23)
    at file:///$deno$eval.ts:1:65
    at async file:///$deno$eval.ts:1:1
```

Workaround of specifying all the options explicitly:

```typescript
const pipeOpts: PipeOptions = {
  preventAbort: false,
  preventCancel: false,
  preventClose: false,
};

const resp = await fetch("https://example.com");
resp.body.pipeThrough(new TransformStream(), pipeOpts);
```

Copy-paste repro:

```
> docker run --rm hayd/alpine-deno:1.6.2 eval 'await fetch("https://example.com").then(x => console.log(x.body.pipeThrough(new TransformStream())))'
ReadableStream { locked: false }

> docker run --rm hayd/alpine-deno:1.6.3 eval 'await fetch("https://example.com").then(x => console.log(x.body.pipeThrough(new TransformStream())))'
ReadableStream { locked: false }

> docker run --rm hayd/alpine-deno:1.7.0 eval 'await fetch("https://example.com").then(x => console.log(x.body.pipeThrough(new TransformStream())))'
error: Uncaught (in promise) AssertionError: Assertion failed.
      throw new AssertionError(msg);
            ^
    at assert (deno:op_crates/fetch/11_streams.js:25:13)
    at readableStreamPipeTo (deno:op_crates/fetch/11_streams.js:1223:5)
    at ReadableStream.pipeThrough (deno:op_crates/fetch/11_streams.js:3148:23)
    at file:///$deno$eval.ts:1:65
    at async file:///$deno$eval.ts:1:1
```

**Comment by caspervonb** [comment]
Comes up in btoa wpt tests as-well.

> Internal Error: AssertionError: Assertion failed.
4864
    at assert (deno:op_crates/fetch/11_streams.js:25:13)
4865
    at writableStreamFinishInFlightCloseWithError (deno:op_crates/fetch/11_streams.js:2762:5)
4866
    at deno:op_crates/fetch/11_streams.js:2489:7
