### ISSUE TITLE
Attempt to open TLS connection with self-signed certificate fails with "InvalidData: invalid certificate: BadDER"

### ISSUE THREAD

**Issue by metaquanta** [denoland/deno#9296]
After working around #7660 `Deno.connectTls` produces:
```
[ "65786b16-b2dd-afdc-992a-fe0cbb2bc174", "8009" ]
Connecting to 65786b16-b2dd-afdc-992a-fe0cbb2bc174:8009...
error: Uncaught (in promise) InvalidData: invalid certificate: BadDER
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpAsync (deno:core/core.js:240:12)
    at async Object.connectTls (deno:runtime/rt/40_tls.js:31:17)
    at async Object.open (CastConnection.ts:22:20)
    at async Object.open (CastMessageLink.ts:14:22)
    at async Object.connect (CastController.ts:12:23)
    at async castcontrol.ts:16:12
```
both with and without the `certFile` argument.

If I provide the cert file to `openssl` it fixes the verification error there.
```
 openssl s_client -noservername -connect 192.168.31.102:8009 -CAfile ext/ssl.crt
CONNECTED(00000003)
depth=0 CN = 65786b16-b2dd-afdc-992a-fe0cbb2bc174
verify return:1
---
Certificate chain
 0 s:CN = 65786b16-b2dd-afdc-992a-fe0cbb2bc174
   i:CN = 65786b16-b2dd-afdc-992a-fe0cbb2bc174
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIC2jCCAcKgAwIBAgIEDYAEHDANBgkqhkiG9w0BAQsFADAvMS0wKwYDVQQDDCQ2
NTc4NmIxNi1iMmRkLWFmZGMtOTkyYS1mZTBjYmIyYmMxNzQwHhcNMjEwMTI2MjE1
NzQwWhcNMjEwMTI4MjE1NzQwWjAvMS0wKwYDVQQDDCQ2NTc4NmIxNi1iMmRkLWFm
ZGMtOTkyYS1mZTBjYmIyYmMxNzQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQCnal6FM8AWhYn2vtlVOiG9pgtFQsiNVNQ9DMhI22/ccCkuCtMeZvY5c5wO
xP7qrPACK0vpxnKLUBfB0bo5A2d5T8UuHMZ97bJJzKyPXI0ejNURbzK3QfFSHwz1
FXIBXf3sJ9MH7GIKkSX9ZNfdYW+GtfMwtsslaHBXjdzplNwgscftwSaBnFyV/dBj
526gRAT9NmOQKxvX/iqWq6Mka3tvicrreFda5tl0upz1pmzNeH05ISRrUVjcBe7+
U3Lpv525ptHdnTR4071GUnyEzJvduTC0kBKI6MeHgwC8FRUpH171EW35UvdOF57u
Z5OEm1Xim0cM3Mdu3AHn8+Ihrc1ZAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAEzy
0ZBrktot0KeTA4eol1jyJYinJ1sjqswhFn1RUepvxvbXVNSSmgT+sAaIbPTKKbhg
00T3P1b4YQC6QnlU89YbVFSj8vo3fKj4dRzOYT5/5rJ8wsMXL+6ndU5E3x9+B1HW
gsSolD9TKnHrDeJjeyq52Js2UKBHXKKMmsfi1XELdkrHOr/VzcaUC2SLPVYkQWSz
0tZZahrF+7SafMWm9Q/T8LOqGd/0WTiRn3BpNv2Zt3kIOpUJ/q5MbcHPBYh7nMkg
4nToRieyn0Ewkf9xXwFO5hehT8UPqynThA0Wiffs72N7L0RLviSWGZ/xi+dif14G
+bI1YITrHLUXF0JjIDk=
-----END CERTIFICATE-----
subject=CN = 65786b16-b2dd-afdc-992a-fe0cbb2bc174

issuer=CN = 65786b16-b2dd-afdc-992a-fe0cbb2bc174

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1208 bytes and written 347 bytes
Verification: OK

...
```

It would be really great if there was a workaround. I do not control the server.
Does https://github.com/denoland/deno/issues/7660#issuecomment-753675258 imply there once was/might be again?

**Comment by bnoordhuis** [comment]
This would be an upstream bug (certificate parsing is done by the [webpki](https://crates.io/crates/webpki) crate) but are you sure it's serving up the same certificate to openssl and deno?

The one that openssl prints looks okay to me at first glance, when I run it through `openssl asn1parse`.
