### ISSUE TITLE
bundle error: Cannot specify --jsx

### ISSUE THREAD

**Issue by AkifumiSato** [denoland/deno#9308]
deno: 1.7.0

I ran this command because I want to bundle jsx.

```
deno bundle pages/Index.tsx public/pages/Index.js
error: TS17004 [ERROR]: Cannot use JSX unless the '--jsx' flag is provided.
...
```

Then I ran it with the `--jsx` flag.

```
deno bundle --jsx pages/Index.tsx public/pages/Index.js
error: Found argument '--jsx' which wasn't expected, or isn't valid in this context
```

Is the error message incorrect, or am I making a mistake?

**Comment by ry** [comment]
I believe you can work around this by using `--no-check`

**Comment by lucacasonato** [comment]
cc @kitsonk

**Comment by amrox** [comment]
if it helps, I hit this too. I was working with the tutorial here https://dev.to/craigmorten/writing-a-react-ssr-app-in-deno-2m7

deno 1.7.1

client.tsx:
```
import React from "https://dev.jspm.io/react@16.13.1";
import ReactDOM from "https://dev.jspm.io/react-dom@16.13.1";
import App from "./app.tsx";

(ReactDOM as any).hydrate(
    <App />,
    //@ts-ignore
    document.getElementById("root"),
);
```
```
❯ deno bundle client.tsx                                                                                                                                                                    ~/Projects/deno1
Bundle file:///Users/amrox/Projects/deno1/client.tsx
Check file:///Users/amrox/Projects/deno1/client.tsx
error: TS6142 [ERROR]: Module './app.tsx' was resolved to 'file:///Users/amrox/Projects/deno1/app.tsx', but '--jsx' is not set.
import App from "./app.tsx";
                ~~~~~~~~~~~
    at file:///Users/amrox/Projects/deno1/client.tsx:3:17

TS17004 [ERROR]: Cannot use JSX unless the '--jsx' flag is provided.
    <App />,
    ~~~~~~~
    at file:///Users/amrox/Projects/deno1/client.tsx:6:5
...
```

`--no-check` does work around this issue

**Comment by ebebbington** [comment]
Use the config flag with a tsconfig + lib prop should fix this right?
