### ISSUE TITLE
Upgrading Conn to TLS Fails

### ISSUE THREAD

**Issue by fannst** [denoland/deno#9360]
Hi, I'm trying to upgrade an existing connection to a client socket to use TLS, in this case the SMTP 'STARTTLS' command... There is not much to find about this online, but this is the code I have, and the result bellow.

```ts
logger.trace('Upgrading to STARTTLS.');

await new Reply(220, 'OK, Go ahead!', '2.0.0').send(session.conn);
const tls: Deno.Conn = await Deno.startTls(session.conn);
```

```
Mon, 01 Feb 2021 14:18:10 GMT : (Trace@SMTP/127.0.0.1) » Upgrading to STARTTLS.
thread 'main' panicked at 'Only a single use of this resource should happen: FullDuplexResource { rd: AsyncRefCell<tokio::net::tcp::split_owned::OwnedReadHalf>, wr: AsyncRefCell<tokio::net::tcp::split_owned::OwnedWriteHalf>, cancel_handle: CancelHandle { node: Node { inner: UnsafeCell, _pin: PhantomPinned } } }', runtime/ops/tls.rs:126:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
   3: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   4: <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll
   5: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   6: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
   7: deno_core::runtime::JsRuntime::poll_event_loop
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: tokio::runtime::Runtime::block_on
  11: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by webdev3301** [comment]
I have been trying to login to Apple's iCloud SMTP server but to no avail because of error `530 5.7.0 Must issue a STARTTLS command first` right after retrying the connection with `Deno.connect()` on port 587.

OpenSSL seems to be able to connect to iCloud SMTP servers but `Deno.connectTls()` cannot.
`openssl s_client -host smtp.mail.me.com -port 587 -starttls smtp`

Is it something I'm not understanding or a limitation?

**Comment by porsager** [comment]
Hi @fannst . Did you find a solution for this issue? I'm experiencing the same with 1.17.2
