### ISSUE TITLE
Panic in repl

### ISSUE THREAD

**Issue by Srinivasa314** [denoland/deno#9398]
Steps to reproduce
* Launch deno repl
* type "Deno.internal."
* Press tab key

Error message:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: {"code":-32000,"message":"Value with given id is not an object"}', cli/tools/repl.rs:113:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', cli/tools/repl.rs:315:23
```

Deno version : deno 1.7.1

**Comment by caspervonb** [comment]
Thanks! fix incoming in a lil bit.

**Comment by Srinivasa314** [comment]
This bug applies to all `Symbol`s. It can be triggered by
```
let obj={s:Symbol('foo')}
```
Then type "obj.s." and press tab
