### ISSUE TITLE
Deno run resulting in loads of errors with third party module

### ISSUE THREAD

**Issue by Tobi696** [denoland/deno#9401]
(This is my first time using Deno, please don't flame me for beginner mistakes.)

When I run a simple file with no dependencies (e.g. `console.log("Hello")`), everything works fine.

As soon as I import a third-party library, I get loads of errors.

Script using third-party library:
````js
import { opine, json } from "https://deno.land/x/opine@0.3.0/mod.ts";

const app = opine();

app.listen(3000, () => {
    console.log('Server is listening on port 3000')
});
````

Output:
````
Check file:///Users/tobiaswimmer/Documents/Development/auth-microservice/test.js
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.52.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.52.0/path/posix.ts:433:18

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { AsyncReturnType } from "./AsyncReturnType.ts";
         ~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/tools/typeSafety/index.ts:2:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackPromise } from "./UnpackPromise.ts";
         ~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/tools/typeSafety/index.ts:8:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackTypeGuard } from "./UnpackTypeGuard.ts";
         ~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/tools/typeSafety/index.ts:9:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Ctx, DoneOrAborted } from "./Ctx.ts";
         ~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:1:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Ctx, DoneOrAborted } from "./Ctx.ts";
              ~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:1:15

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { CtxLike, VoidCtxLike } from "./CtxLike.ts";
                  ~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:2:19

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Evt } from "./Evt.ts";
         ~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:3:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { NonPostableEvt } from "./NonPostableEvt.ts";
         ~~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:4:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Postable } from "./Postable.ts";
         ~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:5:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { StatefulEvt } from "./StatefulEvt.ts";
         ~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:6:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { StatefulReadonlyEvt, StateDiff as Diff } from "./StatefulReadonlyEvt.ts";
         ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:7:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { StatefulReadonlyEvt, StateDiff as Diff } from "./StatefulReadonlyEvt.ts";
                              ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:7:31

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { StatefulPostable } from "./StatefulPostable.ts";
         ~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:8:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { VoidCtx } from "./VoidCtx.ts";
         ~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:9:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { VoidEvt } from "./VoidEvt.ts";
         ~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/interfaces/index.ts:10:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { FactorizeEvt } from "./FactorizeEvt.ts";
         ~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/helper/index.ts:1:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { SwapEvtType } from "./SwapEvtType.ts";
         ~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/helper/index.ts:2:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ToPostableEvt } from "./ToPostableEvt.ts";
         ~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/helper/index.ts:3:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ToNonPostableEvt } from "./ToNonPostableEvt.ts";
         ~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/helper/index.ts:4:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackCtx } from "./UnpackCtx.ts";
         ~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/helper/index.ts:5:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackEvt, EvtLike } from "./UnpackEvt.ts";
         ~~~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/helper/index.ts:6:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackEvt, EvtLike } from "./UnpackEvt.ts";
                    ~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/helper/index.ts:6:21

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Handler } from "./Handler.ts";
         ~~~~~~~
    at https://deno.land/x/evt@1.7.9/lib/types/index.ts:5:10

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Response,
  ~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/deps.ts:9:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Cookies,
  ~~~~~~~
    at https://deno.land/x/oak@v4.0.0/deps.ts:20:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Cookie,
  ~~~~~~
    at https://deno.land/x/oak@v4.0.0/deps.ts:21:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  HTTPSOptions,
  ~~~~~~~~~~~~
    at https://deno.land/x/opine@0.3.0/deps.ts:4:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  HTTPOptions,
  ~~~~~~~~~~~
    at https://deno.land/x/opine@0.3.0/deps.ts:5:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Response,
  ~~~~~~~~
    at https://deno.land/x/opine@0.3.0/deps.ts:8:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Cookie,
  ~~~~~~
    at https://deno.land/x/opine@0.3.0/deps.ts:16:3

Found 34 errors.
````

**Comment by crowlKats** [comment]
You are using an extremely outdated version of opine

**Comment by shadowtime2000** [comment]
Yeah, use the latest which I believe is `1.1.0` with the same code and it works.
