### ISSUE TITLE
[autocannon] Uncaught (in promise) BrokenPipe: Broken pipe

### ISSUE THREAD

**Issue by ynwd** [denoland/deno#9440]
Error:
```
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32) 
      throw new ErrorClass(res.err.message);
            ^
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)
    at async write (deno:runtime/js/12_io.js:118:20)
    at async Object.writeAll (deno:runtime/js/13_buffer.js:224:19)
    at async BufWriter.flush (bufio.ts:468:7)
    at async writeResponse (_io.ts:288:3)
    at async ServerRequest.respond (server.ts:89:7)
```

Step to reproduce:
- Install fastro:
  ```
  deno install -A https://deno.land/x/fastro@v0.30.36/cli/fastro.ts
  ```
- Init folder:
  ```
  mkdir webapp && cd webapp && fastro init
  ```
- Run fastro:
  ```
  deno run -A main.ts
  ```
- Install autocannon: https://www.npmjs.com/package/autocannon
- Run autocannon:
  ```
  autocannon -c 100 -d 40 -p 10 localhost:8080/hello
  ```
  
  (this command line is taken from https://github.com/fastify/benchmarks)

**Comment by bnoordhuis** [comment]
Do you have reason to believe this is an issue with deno itself rather than e.g. fastro? "Broken pipe" in itself isn't an unexpected error, it just means the other end of the connection has gone away.

It'd be helpful if you could post a server example that only uses Deno's built-in APIs, not third-party modules.

**Comment by ynwd** [comment]
Error:
```
error: Uncaught (in promise) ConnectionReset: Connection reset by peer (os error 104)  
      throw new ErrorClass(res.err.message);
            ^
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)
    at async write (deno:runtime/js/12_io.js:118:20)
    at async Object.writeAll (deno:runtime/js/13_buffer.js:224:19)
    at async BufWriter.flush (https://deno.land/std@0.86.0/io/bufio.ts:468:7)
    at async writeResponse (https://deno.land/std@0.86.0/http/_io.ts:288:3)
    at async ServerRequest.respond (https://deno.land/std@0.86.0/http/server.ts:89:7)

```

deno standard lib
```
deno run -A https://deno.land/x/fastro@v0.30.36/benchmarks/deno_app.ts
```

autocannon:
```
autocannon -c 100 -d 40 -p 10 localhost:8080
```

**Comment by kitsonk** [comment]
> ```
> deno run -A https://deno.land/x/fastro@v0.30.36/benchmarks/deno_app.ts
> ```

That is not that Deno standard library, that is a 3rd party module, `fastro`.

**Comment by ynwd** [comment]
> > ```
> > deno run -A https://deno.land/x/fastro@v0.30.36/benchmarks/deno_app.ts
> > ```
> 
> That is not that Deno standard library, that is a 3rd party module, `fastro`.

https://deno.land/x/fastro@v0.30.36/deps.ts

```
export {
  decode as decodeBase64,
  encode as encodeBase64,
} from "https://deno.land/std@0.86.0/encoding/base64.ts";
export { decode } from "https://deno.land/std@0.86.0/encoding/utf8.ts";
export {
  parse as parseYml,
  stringify,
} from "https://deno.land/std@0.86.0/encoding/yaml.ts";
export { parse } from "https://deno.land/std@0.86.0/flags/mod.ts";
export { green, red, yellow } from "https://deno.land/std@0.86.0/fmt/colors.ts";
export * from "https://deno.land/std@0.86.0/http/cookie.ts";
export * from "https://deno.land/std@0.86.0/http/server.ts";
export * from "https://deno.land/std@0.86.0/mime/mod.ts";
export {
  assertEquals,
  assertStringIncludes,
  assertThrows,
} from "https://deno.land/std@0.86.0/testing/asserts.ts";
export { v4 } from "https://deno.land/std@0.86.0/uuid/mod.ts";
export { createElement } from "https://esm.sh/react";
export { renderToString } from "https://esm.sh/react-dom/server";
```

**Comment by ynwd** [comment]
https://deno.land/x/fastro@v0.30.36/benchmarks/deno_app.ts

```
import { serve } from "../deps.ts";

const server = serve({ hostname: "0.0.0.0", port: 8080 });
console.log(`HTTP webserver running.  Access it at:  http://localhost:8080`);

for await (const request of server) {
  const res = {
    body: "Hello World",
    headers: new Headers(),
  };
  res.headers.set("Date", new Date().toUTCString());
  res.headers.set("Connection", "keep-alive");
  request.respond(res);
}
```

**Comment by ynwd** [comment]
This error always show if we use autocannon with 
```
p/--pipelining
```
option.

more info:  
https://www.npmjs.com/package/autocannon

**Comment by yoshixmk** [comment]
I use the `-p` option, and the same phenomenon seems to occur in the following libraries.
↓
[alosaur](https://github.com/alosaur/alosaur)  
[aqua](https://github.com/l2ig/aqua)  
[deno-drash](https://github.com/drashland/deno-drash)  
[dragon](https://github.com/xanny-projects/dragon)  
[mandarinets](https://github.com/mandarineorg/mandarinets)  
[opine](https://github.com/asos-craigmorten/opine)  
[reno](https://github.com/reno-router/reno)  

However, some libraries do not occur, so I do not know if it is a problem in Deno.
↓
[oak](https://github.com/oakserver/oak)  
[pogo](https://github.com/sholladay/pogo)  
[reno](https://github.com/reno-router/reno)  
[servest](https://github.com/keroxp/servest)

**Comment by ynwd** [comment]
it looks like `serverst` don't use [the standard library](https://deno.land/std@0.91.0/http/server.ts#L299).


## Servest
```ts
function createListener(opts: {
  hostname?: string;
  port: number;
}): Deno.Listener {
  return Deno.listen({ ...opts, transport: "tcp" });
}
```

> https://github.com/keroxp/servest/blob/860bf16e292dacf82897dfd15123f99beec32284/server.ts#L121

**Comment by kitsonk** [comment]
Neither does oak. This seems like something related to the std library.
