### ISSUE TITLE
Deno.readDir("/dev/fd") is panic

### ISSUE THREAD

**Issue by disjukr** [denoland/deno#9578]
```
❯ deno --version
deno 1.7.5 (release, x86_64-apple-darwin)
v8 9.0.123
typescript 4.1.4

❯ deno eval 'Deno.readDir("/dev/fd")'
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Other, message: "Bad file descriptor" }', runtime/ops/fs.rs:1059:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', runtime/ops/fs.rs:1077:4
```

**Comment by caspervonb** [comment]
Looking into it.
