### ISSUE TITLE
Deno.File#readSync & Deno.File#read are broken

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#9581]
I'm not sure if anyone else has encountered this, but Deno.File#readSync and Deno.File#read both consistently throw an error:
```
error: Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    if (buffer.length === 0) {
               ^
    at read (deno:runtime/js/12_io.js:95:16)
    at File.read (deno:runtime/js/30_files.js:90:14)
    at ...
```

constructed as
```js
const input = await Deno.open(
	"./in.txt", {
		create: false,
		truncate: false,
		write: false,
		read: true
	}
);
```

Linux, Deno 1.7.0, given full file IO permissions

**Comment by 00ff0000red** [comment]
Nevermind, I obviously didn't look at the API, but a better error message would've been nice ;)
