### ISSUE TITLE
Runtime permission api panic on ctrl-d

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#9633]
```js
// test.js
await Deno.permissions.request({ name: `env` });
```

1. Run `deno run test.js`
2. When the prompt comes up, press `ctrl-d`
3. See following panic:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', runtime/permissions.rs:657:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: deno_runtime::permissions::permission_prompt
   4: deno_core::ops::json_op_sync::{{closure}}
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
   6: deno_runtime::metrics::metrics_op::{{closure}}
   7: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
   8: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
   9: <unknown>
             at ./../../../../v8/src/api/api-arguments-inl.h:158:3
  10: <unknown>
             at ./../../../../v8/src/builtins/builtins-api.cc:113:36
  11: <unknown>
             at ./../../../../v8/src/builtins/builtins-api.cc:143:5
  12: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
fish: “deno run bug.js” terminated by signal SIGABRT (Abort)
```

To fix this, remove the unwrap on line 657 and instead `return false` when the given char is `None`.

**Comment by upendra1997** [comment]
Hi, I am matching on option and if it is None: returning false, otherwise continuing.

**Comment by Yweryfixthy** [comment]
Anyway I could get in to closed beta? If it’s alright with you guys if I could test it so far and get my opinion?
