### ISSUE TITLE
Non deterministic AssertionError during deno-test when using Deno.run

### ISSUE THREAD

**Issue by bergercookie** [denoland/deno#9767]
I have the following dummy test case for deno:

```typescript
Deno.test("Run LS", () => {
  const cmd = Deno.run({
    cmd: ["ls"],
    stdout: "piped",
    stderr: "piped",
  });

  let status: Deno.ProcessStatus, stdout: string, stderr: string;

  const f = async () => {
    const [status_, stdout_, stderr_] = await Promise.all([
      cmd.status(),
      cmd.output(),
      cmd.stderrOutput(),
    ]);
    cmd.close();

    status = status_;
    stdout = new TextDecoder().decode(stdout_);
    stderr = new TextDecoder().decode(stderr_);
  };

  f()
    .then(
      function (result) {
        console.log(`My result: ${result}`);

        console.log(`status: `, status);
        console.log(`stdout: `, stdout);
        console.log(`stderr: `, stderr);

      },
      function (error) {
        console.log(`My error: ${error}`);
      }
    )
    .catch(function (error) {
      console.log(`My cought error: ${error}`);
    })
    .finally(function () {
      console.log("In the finally clause...");
    });
});
```

When I run it using `deno test --allow-read --allow-run --unstable <filename>` sometimes I get the following correct output:

```
running 1 tests
test fetch pending tasks ... My result: undefined
status:  { success: true, code: 0 }
stdout:  a.ts
<rest of files in the directory>

stderr:
In the finally clause...
ok (7ms)
```

And sometimes I get the following assertion error emitted:

```
running 1 tests
test Run LS ... FAILED (4ms)

failures:

Run LS
AssertionError: Test case is leaking async ops.
Before:
  - dispatched: 0
  - completed: 0
After:
  - dispatched: 5
  - completed: 4

Make sure to await all promises returned from Deno APIs before
finishing test case.
    at assert (deno:runtime/js/06_util.js:34:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:50:7)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:74:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:101:9)
    at async TestRunner.[Symbol.asyncIterator] (deno:runtime/js/40_testing.js:275:13)
    at async Object.runTests (deno:runtime/js/40_testing.js:352:22)
    at async file:///home/berger/src/taskwarrior-deno/$deno$test.ts:3:1

failures:

        Run LS
```

If I don't wrap my function in `Deno.test(...)`, and instead I run it as a regular script (i.e., `deno run ...` instead of `deno.test`) then I never get this assertion error.

Is this the right way of calling and using `Deno.run`? If so, is there something else that I'm doing wrong? Is it an error with the way deno itself is running my test case?

**Comment by caspervonb** [comment]
You aren't awaiting on `f` which is why it's leaking.

**Comment by bergercookie** [comment]
> You aren't awaiting on f which is why it's leaking, since it returns before that promise finishes.

Isn't `await`ing the same as explicitly calling `then().catch()`?

Also, how can I `await` on f inside the Deno.test scope? AFAICT `await` operations are forbidden outside `async` contect, i.e., async functions. Doing something like the following to bypass it also doesn't help and I'm still getting the same error message:

```typescript
  const f = async () => {
    const [status_, stdout_, stderr_] = await Promise.all([
   ...
  }

  (async () => { await f(); })();
```

**Comment by searchableguy** [comment]
@bergercookie 
Could you refactor it in this way? 

```typescript
Deno.test("Run LS", async () => {
  const cmd = Deno.run({
    cmd: ["ls"],
    stdout: "piped",
    stderr: "piped",
  });
  const f = async () => {
    const [status_, stdout_, stderr_] = await Promise.all([
      cmd.status(),
      cmd.output(),
      cmd.stderrOutput(),
    ]);
    cmd.close();

    return {
      status: status_,
      stdout: new TextDecoder().decode(stdout_),
      stderr: new TextDecoder().decode(stderr_),
    };
  };
  try {
    const { status, stderr, stdout } = await f();
    console.log("status:", status);
    console.log("stdout:", stdout);
    console.log("stderr:", stderr);
  } catch (error) {
    console.log("Caught error:", error);
  }
});
````

**Comment by bergercookie** [comment]
Yeah, this works just fine. Thanks for the pointers @searchableguy

**Comment by caspervonb** [comment]
Tests can be async functions, they're awaited on in the test runner :)
