### ISSUE TITLE
Type check fails when using both --config and --unstable

### ISSUE THREAD

**Issue by jeiea** [denoland/deno#9783]
## Reproducible steps
1. Make the following files

**test.ts**
```
const file = await Deno.open("test.ts", { read: true });
console.log(await Deno.fstat(file.rid));
file.close();
```
**deno.config.json**
```
{
  "compilerOptions": {
    "lib": ["ES2020", "deno.ns"],
    "strict": true
  }
}

```
2. Run `deno run -A --unstable --config deno.tsconfig.json test.ts`.

## Expected behavior
```
> deno run -A --unstable test.ts
Check file:///{...}/test.ts
{
  isFile: true,      
  isDirectory: false,
  isSymlink: false,
  size: 115,
  mtime: 2021-03-14T09:46:49.233Z,
  atime: 2021-03-14T09:46:50.406Z,
  birthtime: 2021-03-07T11:07:32.810Z,
  dev: null,
  ino: null,
  mode: null,
  nlink: null,
  uid: null,
  gid: null,
  rdev: null,
  blksize: null,
  blocks: null
}
```

## Actual behavior

<details>
<summary>deno run -A --unstable --config deno.tsconfig.json test.ts</summary>

```
> deno run -A --unstable --config deno.tsconfig.json test.ts
Check file:///{...}/test.ts
error: TS2304 [ERROR]: Cannot find name 'PerformanceMark'.
  mark(markName: string, options?: PerformanceMarkOptions): PerformanceMark;
                                                            ~~~~~~~~~~~~~~~ 
    at asset:///lib.deno.ns.d.ts:31:61

TS2304 [ERROR]: Cannot find name 'PerformanceMeasure'.
  ): PerformanceMeasure;
     ~~~~~~~~~~~~~~~~~~
    at asset:///lib.deno.ns.d.ts:38:6

TS2304 [ERROR]: Cannot find name 'URL'.
  export function openSync(path: string | URL, options?: OpenOptions): File;
                                          ~~~
    at asset:///lib.deno.ns.d.ts:510:43

TS2304 [ERROR]: Cannot find name 'URL'.
    path: string | URL,
                   ~~~
    at asset:///lib.deno.ns.d.ts:526:20

TS2304 [ERROR]: Cannot find name 'URL'.
  export function createSync(path: string | URL): File;
                                            ~~~
    at asset:///lib.deno.ns.d.ts:539:45

TS2304 [ERROR]: Cannot find name 'URL'.
  export function create(path: string | URL): Promise<File>;
                                        ~~~
    at asset:///lib.deno.ns.d.ts:550:41

TS2304 [ERROR]: Cannot find name 'URL'.
  export function mkdirSync(path: string | URL, options?: MkdirOptions): void;
                                           ~~~
    at asset:///lib.deno.ns.d.ts:1032:44

TS2304 [ERROR]: Cannot find name 'URL'.
    path: string | URL,
                   ~~~
    at asset:///lib.deno.ns.d.ts:1046:20

TS2304 [ERROR]: Cannot find name 'URL'.
  export function chmodSync(path: string | URL, mode: number): void;
                                           ~~~
    at asset:///lib.deno.ns.d.ts:1156:44

TS2304 [ERROR]: Cannot find name 'URL'.
  export function chmod(path: string | URL, mode: number): Promise<void>;
                                       ~~~
    at asset:///lib.deno.ns.d.ts:1186:40

TS2304 [ERROR]: Cannot find name 'URL'.
    path: string | URL,
                   ~~~
    at asset:///lib.deno.ns.d.ts:1204:20

TS2304 [ERROR]: Cannot find name 'URL'.
    path: string | URL,
                   ~~~
    at asset:///lib.deno.ns.d.ts:1225:20

TS2304 [ERROR]: Cannot find name 'URL'.
  export function removeSync(path: string | URL, options?: RemoveOptions): void;
                                            ~~~
    at asset:///lib.deno.ns.d.ts:1247:45

TS2304 [ERROR]: Cannot find name 'URL'.
    path: string | URL,
                   ~~~
    at asset:///lib.deno.ns.d.ts:1261:20

TS2304 [ERROR]: Cannot find name 'URL'.
  export function readTextFileSync(path: string | URL): string;
                                                  ~~~
    at asset:///lib.deno.ns.d.ts:1308:51

TS2304 [ERROR]: Cannot find name 'URL'.
  export function readTextFile(path: string | URL): Promise<string>;
                                              ~~~
    at asset:///lib.deno.ns.d.ts:1319:47

TS2304 [ERROR]: Cannot find name 'URL'.
  export function readFileSync(path: string | URL): Uint8Array;
                                              ~~~
    at asset:///lib.deno.ns.d.ts:1332:47

TS2304 [ERROR]: Cannot find name 'URL'.
  export function readFile(path: string | URL): Promise<Uint8Array>;
                                          ~~~
    at asset:///lib.deno.ns.d.ts:1345:43

TS2304 [ERROR]: Cannot find name 'URL'.
  export function readDirSync(path: string | URL): Iterable<DirEntry>;
                                             ~~~
    at asset:///lib.deno.ns.d.ts:1463:46

TS2304 [ERROR]: Cannot find name 'URL'.
  export function readDir(path: string | URL): AsyncIterable<DirEntry>;
                                         ~~~
    at asset:///lib.deno.ns.d.ts:1477:42

TS2304 [ERROR]: Cannot find name 'URL'.
    fromPath: string | URL,
                       ~~~
    at asset:///lib.deno.ns.d.ts:1490:24

TS2304 [ERROR]: Cannot find name 'URL'.
    toPath: string | URL,
                     ~~~
    at asset:///lib.deno.ns.d.ts:1491:22

TS2304 [ERROR]: Cannot find name 'URL'.
    fromPath: string | URL,
                       ~~~
    at asset:///lib.deno.ns.d.ts:1505:24

TS2304 [ERROR]: Cannot find name 'URL'.
    toPath: string | URL,
                     ~~~
    at asset:///lib.deno.ns.d.ts:1506:22

TS2304 [ERROR]: Cannot find name 'URL'.
  export function readLinkSync(path: string | URL): string;
                                              ~~~
    at asset:///lib.deno.ns.d.ts:1519:47

TS2304 [ERROR]: Cannot find name 'URL'.
  export function readLink(path: string | URL): Promise<string>;
                                          ~~~
    at asset:///lib.deno.ns.d.ts:1531:43

TS2304 [ERROR]: Cannot find name 'URL'.
  export function lstat(path: string | URL): Promise<FileInfo>;
                                       ~~~
    at asset:///lib.deno.ns.d.ts:1544:40

TS2304 [ERROR]: Cannot find name 'URL'.
  export function lstatSync(path: string | URL): FileInfo;
                                           ~~~
    at asset:///lib.deno.ns.d.ts:1556:44

TS2304 [ERROR]: Cannot find name 'URL'.
  export function stat(path: string | URL): Promise<FileInfo>;
                                      ~~~
    at asset:///lib.deno.ns.d.ts:1568:39

TS2304 [ERROR]: Cannot find name 'URL'.
  export function statSync(path: string | URL): FileInfo;
                                          ~~~
    at asset:///lib.deno.ns.d.ts:1580:43

TS2304 [ERROR]: Cannot find name 'URL'.
    path: string | URL,
                   ~~~
    at asset:///lib.deno.ns.d.ts:1610:20

TS2304 [ERROR]: Cannot find name 'URL'.
    path: string | URL,
                   ~~~
    at asset:///lib.deno.ns.d.ts:1630:20

TS2304 [ERROR]: Cannot find name 'URL'.
    path: string | URL,
                   ~~~
    at asset:///lib.deno.ns.d.ts:1645:20

TS2304 [ERROR]: Cannot find name 'URL'.
    path: string | URL,
                   ~~~
    at asset:///lib.deno.ns.d.ts:1660:20

TS2304 [ERROR]: Cannot find name 'URL'.
    cmd: string[] | [URL, ...string[]];
                     ~~~
    at asset:///lib.deno.ns.d.ts:2000:22

TS2304 [ERROR]: Cannot find name 'Event'.
    "change": Event;
              ~~~~~
    at asset:///lib.deno.ns.d.ts:2161:15

TS2304 [ERROR]: Cannot find name 'EventTarget'.
  export class PermissionStatus extends EventTarget {
                                        ~~~~~~~~~~~
    at asset:///lib.deno.ns.d.ts:2164:41

TS2304 [ERROR]: Cannot find name 'Event'.
    onchange: ((this: PermissionStatus, ev: Event) => any) | null;
                                            ~~~~~
    at asset:///lib.deno.ns.d.ts:2166:45

TS2304 [ERROR]: Cannot find name 'AddEventListenerOptions'.
      options?: boolean | AddEventListenerOptions,
                          ~~~~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.deno.ns.d.ts:2174:27

TS2304 [ERROR]: Cannot find name 'EventListenerOrEventListenerObject'.
      listener: EventListenerOrEventListenerObject,
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.deno.ns.d.ts:2178:17

TS2304 [ERROR]: Cannot find name 'AddEventListenerOptions'.
      options?: boolean | AddEventListenerOptions,
                          ~~~~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.deno.ns.d.ts:2179:27

TS2304 [ERROR]: Cannot find name 'EventListenerOptions'.
      options?: boolean | EventListenerOptions,
                          ~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.deno.ns.d.ts:2187:27

TS2304 [ERROR]: Cannot find name 'EventListenerOrEventListenerObject'.
      listener: EventListenerOrEventListenerObject,
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.deno.ns.d.ts:2191:17

TS2304 [ERROR]: Cannot find name 'EventListenerOptions'.
      options?: boolean | EventListenerOptions,
                          ~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.deno.ns.d.ts:2192:27

TS2584 [ERROR]: Cannot find name 'console'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.
console.log(await Deno.fstat(file.rid));
~~~~~~~
    at file:///{...}/test.ts:2:1

TS2551 [ERROR]: Property 'fstat' does not exist on type 'typeof Deno'. 'Deno.fstat' is an unstable API. Did you forget to run with the '--unstable' flag, or did you mean 'stat'?
console.log(await Deno.fstat(file.rid));
                       ~~~~~
    at file:///{...}/test.ts:2:24

    'stat' is declared here.
      export function stat(path: string | URL): Promise<FileInfo>;
                      ~~~~
        at asset:///lib.deno.ns.d.ts:1568:19

Found 46 errors.
```
</details>

## Additional context
```
> deno --version
deno 1.8.1 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2
```

**Comment by jeiea** [comment]
Maybe documentation is necessary. And It's a little wierd that `Cannot find name 'console'.` error.

**Comment by searchableguy** [comment]
You should check out: https://deno.land/manual/typescript/configuration#how-deno-uses-a-configuration-file

When you supply your own tsconfig.json, it overrides the default options.

**Comment by jeiea** [comment]
That sounds like it is intended behavior. Then `--config` and `--unstable` is mutually exclusive? I think it is hard to notice from cli help command and error message.

**Comment by lucacasonato** [comment]
No they are not mutually exclusive. --unstable enables both the unstable types, and the sets the internal flag to be able to use the unstable APIs at runtime.

Setting a config which overwrites the built in default config means that --unstable won't auto add the `deno.unstable` types to the config. You have to do this yourself.

Closing as all behavior described in this issue is correct, and intended.
