### ISSUE TITLE
Output tests failed on the directory other than 'deno'

### ISSUE THREAD

**Issue by amoseui** [denoland/deno#979]
When I run ./tools/test.py on the directory other than 'deno', several errors occurs during output tests.

If it's not intended, it'd be better if 'deno/' is replaced with [WILDCARD] rule.

```
Expected: hello
before error
Error: error
    at foo ([WILDCARD]tests/async_error.ts:4:9)
    at eval ([WILDCARD]tests/async_error.ts:7:1)
    at DenoCompiler.eval [as _globalEval] (<anonymous>)
    at DenoCompiler._gatherDependencies (deno/js/compiler.ts:[WILDCARD])
    at DenoCompiler.run (deno/js/compiler.ts:[WILDCARD])
    at denoMain (deno/js/main.ts:[WILDCARD])
    at deno_main.js:1:1

Actual: hello
before error
Error: error
    at foo (file:///home/amoseui/Workspace/github/deno-amoseui/tests/async_error.ts:4:9)
    at eval (file:///home/amoseui/Workspace/github/deno-amoseui/tests/async_error.ts:7:1)
    at DenoCompiler.eval [as _globalEval] (<anonymous>)
    at DenoCompiler._gatherDependencies (deno-amoseui/js/compiler.ts:215:10)
    at DenoCompiler.run (deno-amoseui/js/compiler.ts:561:12)
    at denoMain (deno-amoseui/js/main.ts:84:12)
    at deno_main.js:1:1    
```

But I am not sure how we'll prevent this case from the tests that will be added later.

**Comment by hayd** [comment]
Or we can os.chdir before doing the tests.

**Comment by kitsonk** [comment]
@hayd but what if the root of `deno` isn't called `deno` on a local system, which is more revelant.  There is no dir to `.chdir()` to.  My feeling is that we shouldn't assume the root of the project is named `deno` in tests.
