### ISSUE TITLE
How to make embedding deno_runtime's code safe from assert carsh?

### ISSUE THREAD

**Issue by saibing** [denoland/deno#9812]
I intend to use [deno_runtime](https://crates.io/crates/deno_runtime/) as an embedded script engine for my cloud service. However, the following code will cause the service process to crash:

```js
//log.js

Deno.core.print("hello", false, 1);
```

```bash
$ RUST_BACKTRACE=1 deno run log.js
thread'main' panicked at' assertion failed: (0..=2).contains(&arg_len)', core/bindings.rs:318:3
stack backtrace:
0: rust_begin_unwind
at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
1: core::panicking::panic_fmt
at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
2: core::panicking::panic
at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
3: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
4: <unknown>
at ./../../../../v8/src/api/api-arguments-inl.h:158:3
5: <unknown>
at ./../../../../v8/src/builtins/builtins-api.cc:113:36
6: <unknown>
at ./../../../../v8/src/builtins/builtins-api.cc:143:5
7: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

How can I prevent this malicious code from crashing my service process?

**Comment by bnoordhuis** [comment]
You probably want to remove `Deno.core` before running user scripts. It's a grab bag of things that you probably don't want to expose in a multi-tenant system.

**Comment by bartlomieju** [comment]
This should be an easy fix, `Deno.core.print` should throw TypeError if number of arguments is wrong. That said, Ben's suggestion still stands.

**Comment by bnoordhuis** [comment]
There's more than one way to trip up that binding:
https://github.com/denoland/deno/blob/bd961c3bc305e90e760394d2f424c5360a67543b/core/bindings.rs#L325-L327
```
> Deno.core.print("ok", { [Symbol.toPrimitive]() { throw "boom" } })
thread 'main' panicked at 'Unable to convert to integer', core/bindings.rs:327:8
```
