### ISSUE TITLE
`Deno.emit` throws `RangeError: Invalid string length` with too many diagnostic messages

### ISSUE THREAD

**Issue by helmutkian** [denoland/deno#9829]
### Expected

`Deno.emit` should make a best effort to capture all diagnostic messages when compiling.

### Actual

Large numbers of `Deno.emit` diagnostic messages result in a `RangeError: Invalid string length` due to the resulting JSON string being too large.

### Steps to replicate

`main.js`

````javascript
import * as dep from "dep";
console.log(dep);
````

`importMap.json`

````json
{
	"imports": {
		"dep": "https://jspm.dev/npm:joi@13!cjs"
	}
}
````

Executing the following 

````javascript
Deno.emit('./main.js', {
  compilerOptions: {
    module: "commonjs",
    sourceMap: false,
    target: "es6",
    checkJs: true
  },
  importMapPath: "importMap.json"
})
````

yields the `RangeError`

````
thread 'main' panicked at 'Error 'RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at encodeJson (deno:core/core.js:191:20)
    at Object.jsonOpSync (deno:core/core.js:234:21)
    at exec (deno:cli/tsc/99_main_compiler.js:508:10)
    at [native_code]:1:12' contains boxed error of unknown type:
  JsError { message: "Uncaught RangeError: Invalid string length", source_line: Some("    const s = JSON.stringify(args);"), script_resource_name: Some("deno:core/core.js"), line_number: Some(191), start_column: Some(19), end_column: Some(20), frames: [], stack: Some("RangeError: Invalid string length\n    at JSON.stringify (<anonymous>)\n    at encodeJson (deno:core/core.js:191:20)\n    at Object.jsonOpSync (deno:core/core.js:234:21)\n    at exec (deno:cli/tsc/99_main_compiler.js:508:10)\n    at [native_code]:1:12") }', cli/errors.rs:35:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
````

Changing `checkJs: false` results in no errors

**Comment by kitsonk** [comment]
That is a diagnostic structure in excess of 560mb. I can't believe that would be useful. Likely the fix will be to truncate the diagnostic messages at some limit.

**Comment by helmutkian** [comment]
@kitsonk Yeah, trying to actually show all those diagnostic messages is unrealistic, but the current behavior is a bit obscure with trying to comb through every import to identify the culprit. Something other than panicking would make it much easier to reason about what's going on.
