### ISSUE TITLE
 TypeError: Unable to handle the given specifier (TSX)

### ISSUE THREAD

**Issue by creepinson** [denoland/deno#9831]
I heard somewhere that you can use Deno to compile react apps that are made with deno, however this does not appear to work (it gives a typescript type error as seen below).
Here is the error:

```
❯ deno run --unstable --allow-read src/cli/cli.ts -e example/src/app.tsx
Check file:///home/theo/Documents/Code/denweb/src/cli/cli.ts
error: Uncaught (in promise) TypeError: Unable to handle the given specifier: file:///home/theo/Documents/Code/denweb/example/src/app.tsx
const { files, diagnostics } = await Deno.emit(
                               ^
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpAsync (deno:core/core.js:230:12)
    at async file:///home/theo/Documents/Code/denweb/src/cli/cli.ts:13:32
```

I kept looking for this issue but only found that people said TSX and JSX should work fine...

I don't know if I'm supposed to set any specific settings with deno.emit or what.

This is my code for the CLI:
```typescript
import { Command } from "https://deno.land/x/cliffy@v0.18.1/command/mod.ts";
import ReactDOM from "https://esm.sh/react-dom/server";
import sass from "https://esm.sh/sass";

const { options } = await new Command<{ entrypoint: string }>()
    .name("denoweb")
    .version("0.1.0")
    .description("Command-line tool for compiling static sites")
    .option("-e, --entrypoint [entrypoint:string]", "Entrypoint", {
        default: `${Deno.cwd()}/src/app.tsx`,
    })
    .parse(Deno.args);

const { files, diagnostics } = await Deno.emit(
    `${Deno.cwd()}/${options.entrypoint}`,
    {
        bundle: "esm",
        importMapPath: `${Deno.cwd()}/import_map.json`,
        compilerOptions: {
            jsx: "react",
            allowJs: true,
        },
    },
);

if (diagnostics && diagnostics.length > 0) {
    console.log(diagnostics);
}

for await (const file of Object.keys(files)) {
    const txt = files[file];

    await Deno.writeTextFile(`${Deno.cwd()}/dist/${file}`, txt);
}
```

**Comment by Liamolucko** [comment]
What are the contents of `import_map.json`?

**Comment by creepinson** [comment]
Right now its just
```json
{
    "imports": {}
}
```
