### ISSUE TITLE
Test FAIL copyFileSyncFailure_permW1N0E0

### ISSUE THREAD

**Issue by rjoydip** [denoland/deno#984]
Getting copy file sync failed permission in windows

```
6/28 +5 -0: copyFileSyncFailure_permW1N0E0
assertEqual failed. actual =  1 expected = 12

Test FAIL copyFileSyncFailure_permW1N0E0
Error: actual: 1 expected: 12
    at Object.assertEqual (file:///../deno/js/testing/util.ts:29:11)
    at copyFileSyncFailure (file:///../deno/js/copy_file_test.ts:47:3)
    at runTests (file:///../deno/js/testing/testing.ts:63:13)

DONE. Test passed: 5, failed: 1
Error: There were 1 test failures.
    at setTimeout (file:///../deno/js/testing/testing.ts:83:13)
    at sendAsync.then.baseRes (deno/js/timers.ts:64:9)
```
- OS: Win 7

**Comment by kevinkassimo** [comment]
Interesting. The test case has a special case for windows
https://github.com/denoland/deno/blob/bbf88c529587647aaa0089233fea19e961a764f1/js/copy_file_test.ts#L46-L54
It seems that on your platform, `deno.platform.os` for some reason is not `win`?
