### ISSUE TITLE
🐛 `deno coverage` line and branch counts are incorrect

### ISSUE THREAD

**Issue by rivy** [denoland/deno#9865]
I'm getting some broken coverage results.

For the code:

```js
export function f(b: boolean) {
        var result;
        if (b) {
                result = true;
        } else {
                result = false;
        }
        return result;
}
```

as a Deno script (from the repo https://github.com/rivy-t/cover-deno):

```shell
C:>deno test --unstable -A --coverage=coverage && deno coverage --unstable coverage --lcov
...
SF:C:\Users\Roy\OneDrive\Projects\deno\dexter\repo.t-cover-deno\src\mod.ts
FN:2,f
FNDA:4,f
FNF:1
FNH:1
BRDA:4,1,0,2
BRF:1
BRH:1
DA:1,2
DA:2,6
DA:3,6
DA:4,8
DA:5,8
DA:6,8
DA:7,6
DA:8,6
DA:9,2
LH:9
LF:9
end_of_record
```

vs the same code as ESM, using nyc/ava (from https://github.com/rivy-t/cover-esm):

```shell
C:>npm i --silent && npx nyc --silent ava && npx nyc report --reporter=text-lcov
...
TN:
SF:src\esm.js
FN:1,f
FNF:1
FNH:1
FNDA:2,f
DA:3,2
DA:4,1
DA:6,1
DA:8,2
LF:4
LH:4
BRDA:3,0,0,1
BRDA:3,0,1,1
BRF:2
BRH:2
end_of_record
```

Specifically, the Deno branch coverage is incorrect; the line coverage has odd counts, off-by-one's, and, arguably, counts non-executing lines.

**Comment by bartlomieju** [comment]
CC @caspervonb

**Comment by caspervonb** [comment]
Thanks for the report @rivy

**Comment by caspervonb** [comment]
Actually links seem to 404...

**Comment by rivy** [comment]
Fixed URLs (GitHub didn't like angle brackets around the GitHub URLs).

**Comment by aricart** [comment]
@caspervonb this is the same as https://github.com/denoland/deno/issues/9754? Glad there's a reproducible test case.

**Comment by caspervonb** [comment]
> Fixed URLs in the original post (GitHub didn't like angle brackets around the GitHub URLs).
Seems both of your repos still 404 @rivy, also searched your profile(s) for cover and found nothing.

> @caspervonb this is the same as #9754? Glad there's a reproducible test case.

Might be, we'll see :thinking:

**Comment by rivy** [comment]
> Seems both of your repos still 404 @rivy, also searched your profile(s) for cover and found nothing. Did you perhaps not make them public?

You were correct, they were both inadvertently marked private. I've reset them to public availability.

**Comment by caspervonb** [comment]
> Sorry for the additional stumbling blocks.

No worries.
Looked into it but it's non trivial, will try to get this fixed in 1.9.x

**Comment by rivy** [comment]
Ping @caspervonb.

Just checking back in... Any progress or timeline?

**Comment by caspervonb** [comment]
Soon (TM).
I have a wip cleanup branch.

**Comment by bartlomieju** [comment]
Hey @rivy I just tried to reproduce the problem and the `cover-esm` repo doesn't work, I get errors returned:
```
❯ npm run nyc1

> repo.t-avajs@1.0.0 nyc1
> nyc --silent ava


  ✖ No tests found in test/test.mjs, make sure to import "ava" at the top of your test file

  ─

  ✖ Internal error when running test/test.mjs
  Error: ECMAScript Modules are not supported in this Node.js version.
  Error: ECMAScript Modules are not supported in this Node.js version.
      at load (/Users/biwanczuk/dev/cover-esm/node_modules/ava/lib/worker/subprocess.js:201:91)
      at /Users/biwanczuk/dev/cover-esm/node_modules/ava/lib/worker/subprocess.js:244:3
  ─

```
That said, I also ran `cover-deno` and got somewhat similar results to yours:
```
SF:/Users/biwanczuk/dev/cover-deno/src/mod.ts
FN:1,f
FNDA:2,f
FNF:1
FNH:1
BRDA:3,1,0,1
BRF:1
BRH:1
DA:1,1
DA:2,3
DA:3,3
DA:4,4
DA:5,8
DA:6,4
DA:7,4
DA:8,3
DA:9,3
LH:9
LF:9
end_of_record

```
When I viewed results using https://lcov-viewer.netlify.app/ I get 100% coverage (which matches what `deno coverage coverage/` shows too):
![Screenshot 2022-01-11 at 05 09 45](https://user-images.githubusercontent.com/13602871/148879760-f33ec501-ede8-41f4-85ea-99301784cbbf.png)

So I'm not sure if there's something wrong here?

**Comment by rivy** [comment]
@bartlomieju , thanks for circling back around to this issue.

> Hey @rivy I just tried to reproduce the problem and the `cover-esm` repo doesn't work, I get errors returned:

The master branch code had the wrong file extensions. It's now corrected.

```shell
$ node --version
v12.18.3
$ npm --version
6.14.6
$ npm i --silent && npx nyc --silent ava && npx nyc report --reporter=text-lcov
...
  1 test passed
TN:
SF:src/esm.js
FN:1,f
FNF:1
FNH:1
FNDA:2,f
DA:3,2
DA:4,1
DA:6,1
DA:8,2
LF:4
LH:4
BRDA:3,0,0,1
BRDA:3,0,1,1
BRF:2
BRH:2
end_of_record
```

The corresponding `deno` coverage was wildly different (in March 2021).

> branch coverage is incorrect; the line coverage has odd counts, off-by-one's (line numbers), and, arguably, counts non-executing lines

Since @caspervonb said everything was still pending, I hadn't looked back into this until your message just now. 

The newest coverage info (`deno` v1.17.2) seems improved, but still seems quite oddly off.

```shell
$ deno --version
deno 1.17.2 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
$ deno test --unstable -A --coverage=coverage && deno coverage --unstable coverage --lcov
running 1 test from file:///c/Users/Roy/OneDrive/Projects/deno/dexter/repo.t-cover-deno/test/test.ts
test m ... ok (6ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (76ms)

SF:/c/Users/Roy/OneDrive/Projects/deno/dexter/repo.t-cover-deno/src/mod.ts
FN:1,f
FNDA:2,f
FNF:1
FNH:1
BRDA:3,1,0,1
BRF:1
BRH:1
DA:1,1
DA:2,3
DA:3,3
DA:4,4
DA:5,8
DA:6,4
DA:7,4
DA:8,3
DA:9,3
LH:9
LF:9
end_of_record
```

The branch coverage (`BRDA`, `BRF`, and `BRH`) looks wrong and the individual line numbers are oddly discordant with each other. (Why is the `if` line counted as being taken 3 times and the `else` line being taken 8 times?...)

**Comment by bartlomieju** [comment]
Thanks for checking, I believe this is stemming from the same issue as https://github.com/denoland/deno/issues/10944, ie. covered ranges are not properly merged. I got a PR going at https://github.com/denoland/deno/pull/13334

**Comment by rivy** [comment]
Will that fix the branch info as well?

I see this code as having two covered branches, eg:

```text
BRDA:3,0,0,1
BRDA:3,0,1,1
BRF:2
BRH:2
```

instead of the one noted by the `deno` coverage.

**Comment by bartlomieju** [comment]
I'm not sure about that, will get back to you once the PR lands.

**Comment by rivy** [comment]
@bartlomieju @caspervonb , the coverage numbers are still off...

```shell
SF:C:\Users\Roy\OneDrive\Projects\deno\testing\cover-deno\src\mod.ts
FN:1,f
FNDA:2,f
FNF:1
FNH:1
BRDA:3,1,0,1
BRF:1
BRH:1
DA:1,1
DA:2,3
DA:3,3
DA:4,4
DA:5,8
DA:6,4
DA:7,4
DA:8,3
DA:9,3
LH:9
LF:9
end_of_record
```

This incorrectly states that there's only 1 branch is seen/taken (there are two and both are covered). And the line coverage line counts are still strange and not correctly correlated to each other.

**Comment by bartlomieju** [comment]
@rivy did you remove your coverage directory before running tests?

**Comment by rivy** [comment]
Yes sir, I just double-checked.
Coverage results are the same.
From <https://github.com/rivy-t/cover-deno>...

```shell
C:>deno --version
deno 1.18.0 (release, x86_64-pc-windows-msvc)
v8 9.8.177.6
typescript 4.5.2

C:>rm -r .coverage coverage_html
rm: cannot remove 'coverage_html': No such file or directory

C:>deno test -A --coverage=.coverage/profile
Check file:///C:/Users/Roy/OneDrive/Projects/deno/testing/cover-deno/test/test.ts
running 1 test from file:///C:/Users/Roy/OneDrive/Projects/deno/testing/cover-deno/test/test.ts
test m ... ok (5ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (65ms)


C:>deno coverage .coverage/profile --lcov
SF:C:\Users\Roy\OneDrive\Projects\deno\testing\cover-deno\src\mod.ts
FN:1,f
FNDA:2,f
FNF:1
FNH:1
BRDA:3,1,0,1
BRF:1
BRH:1
DA:1,1
DA:2,3
DA:3,3
DA:4,4
DA:5,8
DA:6,4
DA:7,4
DA:8,3
DA:9,3
LH:9
LF:9
end_of_record
```

**Comment by bartlomieju** [comment]
Thanks for checking, I've reopened the issue. I'll try to revisit it soon.

**Comment by rivy** [comment]
FYI, for additional comparison, Linux coverage calculations match the WinOS calculations.

```shell
$ deno --version
deno 1.18.1 (release, x86_64-unknown-linux-gnu)
v8 9.8.177.6
typescript 4.5.2
$ rm -r .coverage
$ deno test --coverage=.coverage/nix.profile
Check file:///c/Users/Roy/OneDrive/Projects/deno/testing/cover-deno/test/test.ts
running 1 test from file:///c/Users/Roy/OneDrive/Projects/deno/testing/cover-deno/test/test.ts
test m ... ok (5ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (73ms)
$ deno coverage .coverage/nix.profile --lcov
SF:/c/Users/Roy/OneDrive/Projects/deno/testing/cover-deno/src/mod.ts
FN:1,f
FNDA:2,f
FNF:1
FNH:1
BRDA:3,1,0,1
BRF:1
BRH:1
DA:1,1
DA:2,3
DA:3,3
DA:4,4
DA:5,8
DA:6,4
DA:7,4
DA:8,3
DA:9,3
LH:9
LF:9
end_of_record
```

**Comment by rivy** [comment]
@bartlomieju , @caspervonb , I'm just checking back in on this issue.
I see it is now tracked in #12826, but the future plan is not clear to me.
Thoughts?

**Comment by bartlomieju** [comment]
@rivy I did try to investigate what is the problem, but after a couple hours of debugging I had to prioritize other things.

**Comment by caspervonb** [comment]
It's still from source mapping, it's not greedy enough.

Had a fix that we reverted a long time ago that should be easy to apply, just had some unwraps I didn't clean up (that should've been unwrap_or).

**Comment by rivy** [comment]
@bartlomieju , @caspervonb , I'm checking back in on this issue.

After reviewing the output of the most recent Deno v1.30.0, the output is unchanged with incorrect counts (for lines and branches) and incorrect branch detection. Is this still on the map to be fixed?

**Comment by bartlomieju** [comment]
> Is this still on the map to be fixed?

Yes, but due to limited bandwidth no one has picked it up yet.

**Comment by rivy** [comment]
Ok, thanks for the reply.

**Comment by sgurijala9** [comment]
@bartlomieju is there any update on this ?

**Comment by bartlomieju** [comment]
@sgurijala9 sadly no update :(

**Comment by csvn** [comment]
I don't know exactly if this is referencing the same issue, or if it should be a separate one. But I have weird case where **Branches** are `0/0` when a file is completely untested, and the file is just imported but never runs. 

<img width="886" height="338" alt="Image" src="https://github.com/user-attachments/assets/c59b599c-2366-4176-9bf0-64ec49954648" />

After adding a test to start testing the untested code, **Lines** go up, but branches drops to from 100% because branches start being counted correctly.

<img width="542" height="135" alt="Image" src="https://github.com/user-attachments/assets/c59674f2-7e27-43f6-a499-03eba536f06d" />

It's very weird to see tests being added (Lines go 📈), but **Branches** drop 📉.

<img width="1116" height="153" alt="Image" src="https://github.com/user-attachments/assets/e44ae499-8ecc-4dd8-bfb3-8649fd5f2ee9" />

I made a comparison with how Vitest coverage looks for **Branches** for files without tests, and it still counts them correctly (e.g. `0/5`). So this seems to be related to how Deno computes branches for code that doesn't run (functions that aren't called).
