### ISSUE TITLE
--no-check problem

### ISSUE THREAD

**Issue by chenguzhen87** [denoland/deno#9869]
```js
PS E:\github-repo\deno-study\oak> deno run --no-check mod.ts
warning: Compiled module not found "https://deno.land/x/oak/types.d.ts"
  From: https://deno.land/x/oak/mod.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.
error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.53.0/http/server.ts' does not provide an export named 'Response'
  Response,
~~~~~~~~
    at <anonymous> (https://deno.land/x/oak/deps.ts:9:1)
PS E:\github-repo\deno-study\oak> deno run mod.ts --no-check
Check file:///E:/github-repo/deno-study/oak/mod.ts
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.53.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.       
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
```

**Comment by lucacasonato** [comment]
Import a versioned version of oak: https://deno.land/x/oak@v6.5.0/mod.ts
