### ISSUE TITLE
[fmt] thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()`

### ISSUE THREAD

**Issue by erikbrinkman** [denoland/deno#9887]
calling `deno fmt` on
```
type T =
  | unknown
  { } & unknown;
```
results in
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-plugin-typescript-0.41.0/src/parsing/swc/flatten_binary_expr.rs:22:94
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Panic formatting: <file>', cli/tools/fmt.rs:393:5
```

`deno -V # deno 1.8.1`

**Comment by satyarohith** [comment]
This is no longer an issue with the latest canary.

```
➜  ~ deno -V
deno 1.8.3+df49a84

➜  ~ cat test.ts
type T =
  | unknown
  { } & unknown;
  
➜  ~ deno fmt test.ts
Error formatting: /Users/sr/test.ts
   Line 3, column 7: Expression expected

    { } & unknown;
        ~
Checked 1 file
```
