### ISSUE TITLE
const { encode } = new TextEncoder() is invalid

### ISSUE THREAD

**Issue by iugo** [denoland/deno#9899]
code:

```ts
const encoder = new TextEncoder();
const { encode } = encoder;

const res = encode("resBody");
console.log("encode res", res);
```

Expected: valid

Actual: invalid

```
error: Uncaught TypeError: Cannot read property 'encoding' of undefined
const res = encode("resBody");
            ^
    at encode (deno:op_crates/web/08_text_encoding.js:4217:16)
    at ./t2.ts:4:13
```

deno version:

```
deno 1.8.2 (release, x86_64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2
```

---

Current solution:

```ts
const encoder = new TextEncoder();

const res = encoder.encode("resBody");
console.log("encode res", res);
```

**Comment by iugo** [comment]
There is also an error in the browser, which seems to be the problem with my use.
