### ISSUE TITLE
LSP Error: Debug Failure. Invalid cast.

### ISSUE THREAD

**Issue by danopia** [denoland/deno#9913]
I don't have a lot of breadcrumbs on this exactly... I was writing up a new test file and the function I was testing was wrongly showing as returning `Promise<any>`. So I went to manually copy in the structure I was testing as a workaround, and this error popped up soon after the paste. Later on the function's return type started showing correctly. I'm assuming that is somehow related 🤷 

```
Error getting actions from TypeScript: Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isLabeledStatement'.
    at Object.cast (deno:cli/tsc/00_typescript.js:1694:25)
    at doChange (deno:cli/tsc/00_typescript.js:141104:39)
    at deno:cli/tsc/00_typescript.js:141096:96
    at Function.ChangeTracker.with (deno:cli/tsc/00_typescript.js:134879:17)
    at Object.getCodeActions (deno:cli/tsc/00_typescript.js:141096:64)
    at deno:cli/tsc/00_typescript.js:136053:77
    at Object.flatMap (deno:cli/tsc/00_typescript.js:709:25)
    at Object.getFixes (deno:cli/tsc/00_typescript.js:136053:23)
    at deno:cli/tsc/00_typescript.js:150119:35
    at Object.flatMap (deno:cli/tsc/00_typescript.js:709:25)
[Error - 9:46:32 PM] Request textDocument/codeAction failed.
```

![Screenshot 2021-03-27 21 46 25](https://user-images.githubusercontent.com/40628/112734641-510a1f80-8f47-11eb-9096-e9778264c4e8.png)

```
deno 1.8.2 (release, x86_64-unknown-linux-gnu)
v8 9.0.257.3
typescript 4.2.2
```

```
code-server: v3.9.2
 VS Code: v1.54.2
Commit: 109d2ce3247869eaeab67aa7e5423503ec9eb859
Date: 2021-03-25T17:47:07Z
Browser: Mozilla/5.0 (X11; CrOS x86_64 13729.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.95 Safari/537.36
```

**Comment by kitsonk** [comment]
These type of errors are hard because it is an integral TS thing, likely because we don't exactly behave like other language server consumers.

**Comment by danopia** [comment]
Ok... based on https://github.com/microsoft/TypeScript/issues/25641 this can happen with normal tsc too, but it's not easy to repro

**Comment by danopia** [comment]
In the past week I've seen a small variety of different tsc/lsp debug failures, most recently:

```
Error getting actions from TypeScript: Error: Debug Failure. Token and statement should start at the same point. {"statementKind":"ReturnStatement","tokenKind":"SemicolonToken","errorCode":7027,"start":1744,"length":5}
    at doChange (deno:cli/tsc/00_typescript.js:141044:26)
    at deno:cli/tsc/00_typescript.js:141027:96
    at Function.ChangeTracker.with (deno:cli/tsc/00_typescript.js:134880:17)
    at Object.getCodeActions (deno:cli/tsc/00_typescript.js:141027:64)
    at deno:cli/tsc/00_typescript.js:136054:77
    at Object.flatMap (deno:cli/tsc/00_typescript.js:709:25)
    at Object.getFixes (deno:cli/tsc/00_typescript.js:136054:23)
    at deno:cli/tsc/00_typescript.js:150120:35
    at Object.flatMap (deno:cli/tsc/00_typescript.js:709:25)
    at Object.getCodeFixesAtPosition (deno:cli/tsc/00_typescript.js:150118:23)
```

Are these failed expectations from tsc 'ok' enough to ignore them?

**Comment by kitsonk** [comment]
@danopia this latest one seems to be happening occasionally in vscode: https://github.com/microsoft/TypeScript/issues/32856.  It appears that it built in telemetry in vscode dispatches.  While these are interesting, they obviously are a bit distracting.  I think for code actions, we should not fail the response, but we can still log these to the output.

**Comment by danopia** [comment]
Another stack, this time https://github.com/microsoft/TypeScript/issues/32852 open since 2019

```
Error getting actions from TypeScript: Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isParameter'.
    at Object.cast (deno:cli/tsc/00_typescript.js:1694:25)
    at doChange (deno:cli/tsc/00_typescript.js:141527:40)
    at deno:cli/tsc/00_typescript.js:141423:109
    at Function.ChangeTracker.with (deno:cli/tsc/00_typescript.js:134880:17)
    at Object.getCodeActions (deno:cli/tsc/00_typescript.js:141423:64)
    at deno:cli/tsc/00_typescript.js:136054:77
    at Object.flatMap (deno:cli/tsc/00_typescript.js:709:25)
    at Object.getFixes (deno:cli/tsc/00_typescript.js:136054:23)
    at deno:cli/tsc/00_typescript.js:150120:35
    at Object.flatMap (deno:cli/tsc/00_typescript.js:709:25)
```

Seems smart to not interrupt the user for these if tsc has had them occurring like forever
