### ISSUE TITLE
Deno test WebSocket completing cleanly, but reporting BadResource: Bad resource ID

### ISSUE THREAD

**Issue by aricart** [denoland/deno#9958]
I am a bit miffed by this error reported by the test runner (notice the async/ops resource sanitizer is not printing (I am the one doing the print). The test completes, reports passed, but a trace at the end.
Any hints, thoughts?
```
running 1 tests
test clean shutdown ...
{ "0": "stdin", "1": "stdout", "2": "stderr", "3": "webSocketStream" }
ok (11ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (11ms)

error: Uncaught (in promise) BadResource: Bad resource ID
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at opSync (deno:core/core.js:259:32)
    at jsonOpSync (deno:core/core.js:372:12)
    at Object.close (deno:core/core.js:383:12)
    at WebSocket.#eventLoop (deno:op_crates/websocket/01_websocket.js:353:18)

```

**Comment by aricart** [comment]
yeap duplicate of this. https://github.com/denoland/deno/issues/9879
sorry didn't see it at first.

**Comment by aricart** [comment]
Thanks @lucacasonato
